// 生成タスク 第49波：各レベル2問化フェーズ(4)。lv193〜244 に2問目を追加。
// 配列/行列/二分探索/bit演算の「要素」。重複なし・決定的・採点一意。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 193, concept: '配列: 和が偶数の部分配列数', title: '和が偶数の連続部分配列の数', tags: ['配列'], io: '整数列が1行で与えられます。', ask: '和が偶数になる連続部分配列の個数を出力してください。', h1: '累積和の偶奇を数える。', h2: '同じ偶奇の累積和ペアが偶数和。', ref: 'a=list(map(int,input().split()))\neven=1\nodd=0\ns=0\nres=0\nfor x in a:\n    s+=x\n    if s%2==0:\n        res+=even\n        even+=1\n    else:\n        res+=odd\n        odd+=1\nprint(res)', tip: '和が偶数の区間は「累積和の偶奇が同じ2点」。偶奇別に累積個数を数えると O(n)。', ins: ['1 2 3 4\n', '2 4 6\n', '1 1 1\n', '5\n', '2\n', '1 3 5 7\n'] })

t({ lv: 194, concept: '配列: 偶数を含む部分配列数', title: '偶数を含む連続部分配列の数', tags: ['配列'], io: '整数列が1行で与えられます。', ask: '少なくとも1つ偶数を含む連続部分配列の個数を出力してください。', h1: '全部分配列数から「全て奇数」を引く。', h2: '連続奇数の長さ L は L(L+1)/2 個。', ref: 'a=list(map(int,input().split()))\nn=len(a)\ntotal=n*(n+1)//2\nrun=0\nallodd=0\nfor x in a:\n    if x%2==1:\n        run+=1\n    else:\n        allodd+=run*(run+1)//2\n        run=0\nallodd+=run*(run+1)//2\nprint(total-allodd)', tip: '「少なくとも1つ偶数」は余事象「全て奇数の区間」を引く。連続奇数ランごとに L(L+1)/2 を引く。', ins: ['1 2 3\n', '1 3 5\n', '2 4\n', '5\n', '2\n', '1 1 2 1\n'] })

t({ lv: 195, concept: '配列: 相異なるペア和の数', title: '相異なる2要素和の種類数', tags: ['配列', '集合'], io: '整数列が1行で与えられます(2個以上)。', ask: '異なる2要素の和として現れる相異なる値の種類数を出力してください。', h1: '全ペアの和を集合に入れる。', h2: '要素数を取る。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nsums=set()\nfor i in range(n):\n    for j in range(i+1,n):\n        sums.add(a[i]+a[j])\nprint(len(sums))', tip: 'ペア和の種類数は全ペアの和を集合に。O(n²)だが重複する和は自動でまとまる。', ins: ['1 2 3\n', '1 1 1\n', '0 5\n', '1 2 3 4\n', '2 2 2\n', '1 5 3'] })

t({ lv: 196, concept: 'ハッシュ: 等しい値のペア数', title: '値が等しいペアの個数', tags: ['ハッシュ'], io: '整数列が1行で与えられます。', ask: '同じ値を持つ要素のペア (i<j) の個数を出力してください。', h1: '各値の出現回数を数える。', h2: '回数 c から C(c,2) を足す。', ref: 'from collections import Counter\na=list(map(int,input().split()))\ncnt=Counter(a)\nprint(sum(c*(c-1)//2 for c in cnt.values()))', tip: '等値ペア数は各値の出現回数 c から C(c,2)=c(c-1)/2 を足す。組合せの基本。', ins: ['1 1 2 2 2\n', '1 2 3\n', '5 5\n', '1\n', '7 7 7\n', '1 1 1 1\n'] })

t({ lv: 197, concept: '配列: 和0の三つ組の数', title: '和が0になる3要素の組数', tags: ['配列'], io: '整数列が1行で与えられます。', ask: '3要素 (i<j<k) の和が0になる組の個数を出力してください。', h1: '全3つ組を調べる。', h2: '和0を数える(O(n³))。', ref: 'a=list(map(int,input().split()))\nn=len(a)\ncnt=0\nfor i in range(n):\n    for j in range(i+1,n):\n        for k in range(j+1,n):\n            if a[i]+a[j]+a[k]==0:\n                cnt+=1\nprint(cnt)', tip: '3-sum の数え上げ。素朴は O(n³)、ソート＋二ポインタで O(n²) に落とせる。', ins: ['-1 0 1 2\n', '1 2 3\n', '0 0 0\n', '-1 -1 2\n', '5\n', '-2 1 1 0\n'] })

t({ lv: 198, concept: '配列: 和が3の倍数の部分配列数', title: '和が3の倍数の連続部分配列数', tags: ['ハッシュ'], io: '整数列が1行で与えられます。', ask: '和が3で割り切れる連続部分配列の個数を出力してください。', h1: '累積和の mod 3 を数える。', h2: '同じ余りのペアが3の倍数和。', ref: 'a=list(map(int,input().split()))\ncnt=[1,0,0]\ns=0\nres=0\nfor x in a:\n    s=(s+x)%3\n    res+=cnt[s]\n    cnt[s]+=1\nprint(res)', tip: '和が3の倍数の区間は累積和の余りが等しい2点。余りごとに個数を数える。', ins: ['1 2 3\n', '3 3 3\n', '1 1 1\n', '2 4 6\n', '5\n', '1 2 3 4 5\n'] })

t({ lv: 199, concept: 'ハッシュ: 最初に重複する要素', title: '最初に再出現する値', tags: ['ハッシュ'], io: '整数列が1行で与えられます。', ask: '2回目に現れる時点が最も早い値を出力してください。重複が無ければ -1。', h1: '既出集合を持つ。', h2: '既出なら即その値を返す。', ref: 'a=list(map(int,input().split()))\nseen=set()\nans=-1\nfor x in a:\n    if x in seen:\n        ans=x\n        break\n    seen.add(x)\nprint(ans)', tip: '最初に重複する値は「既出集合に2回目に入る値」。1パスで検出できる。', ins: ['1 2 3 2 1\n', '1 2 3\n', '5 5\n', '1\n', '3 1 3 1\n', '7 8 9 7\n'] })

t({ lv: 201, concept: '配列: 対角の差', title: '正方行列の対角の差', tags: ['配列'], io: '1行目に n、続く n 行に n 個の整数が与えられます。', ask: '主対角の和と反対角の和の差の絶対値を出力してください。', h1: '両対角の和を求める。', h2: '差の絶対値。', ref: 'n=int(input())\ng=[list(map(int,input().split())) for _ in range(n)]\nmain=sum(g[i][i] for i in range(n))\nanti=sum(g[i][n-1-i] for i in range(n))\nprint(abs(main-anti))', tip: '2つの対角和の差は行列の対称性の指標。主対角 g[i][i] と反対角 g[i][n-1-i]。', ins: ['2\n1 2\n3 4\n', '1\n5\n', '3\n1 2 3\n4 5 6\n7 8 9\n', '2\n1 1\n1 1\n', '3\n11 2 4\n4 5 6\n10 8 -12\n', '2\n5 0\n0 5\n'] })

t({ lv: 202, concept: '配列: 行和最大の行', title: '和が最大の行の番号', tags: ['配列'], io: '1行目に R C、続く R 行に行列が与えられます。', ask: '行の和が最大になる行の番号(0始まり、最初のもの)を出力してください。', h1: '各行の和を求める。', h2: '最大の行の添字を取る。', ref: 'first=input().split()\nR=int(first[0])\nC=int(first[1])\ng=[list(map(int,input().split())) for _ in range(R)]\nsums=[sum(row) for row in g]\nprint(sums.index(max(sums)))', tip: '行和最大の行は各行の sum を求めて argmax。データ行の集計でよく使う。', ins: ['2 2\n1 2\n3 4\n', '1 1\n5\n', '3 2\n1 1\n5 5\n2 2\n', '2 3\n1 1 1\n0 0 0\n', '2 2\n5 5\n5 5\n', '3 1\n3\n1\n2\n'] })

t({ lv: 203, concept: '配列: 列和最大の列', title: '和が最大の列の番号', tags: ['配列'], io: '1行目に R C、続く R 行に行列が与えられます。', ask: '列の和が最大になる列の番号(0始まり、最初のもの)を出力してください。', h1: 'zip(*g) で列和を求める。', h2: '最大の列の添字を取る。', ref: 'first=input().split()\nR=int(first[0])\nC=int(first[1])\ng=[list(map(int,input().split())) for _ in range(R)]\nsums=[sum(col) for col in zip(*g)]\nprint(sums.index(max(sums)))', tip: '列和最大の列は zip(*g) で列を作り argmax。特徴量(列)の集計に対応する。', ins: ['2 2\n1 5\n2 1\n', '1 1\n5\n', '2 3\n1 1 1\n0 0 9\n', '2 2\n5 5\n5 5\n', '3 2\n1 2\n3 4\n5 6\n', '1 3\n3 1 2\n'] })

t({ lv: 204, concept: '配列: 行の最小値の最大', title: '各行の最小値の最大', tags: ['配列'], io: '1行目に R C、続く R 行に行列が与えられます。', ask: '各行の最小値を求め、それらの最大値を出力してください(マックスミニ)。', h1: '各行の min を取る。', h2: 'その最大。', ref: 'first=input().split()\nR=int(first[0])\nC=int(first[1])\ng=[list(map(int,input().split())) for _ in range(R)]\nprint(max(min(row) for row in g))', tip: '行の最小の最大(maximin)はゲーム理論やロバスト最適化の基本。各行 min→全体 max。', ins: ['2 2\n1 2\n3 4\n', '1 1\n5\n', '3 2\n1 9\n5 5\n2 8\n', '2 3\n1 2 3\n4 5 6\n', '2 2\n0 0\n0 0\n', '3 1\n3\n1\n2\n'] })

t({ lv: 205, concept: '配列: 列の最大値の最小', title: '各列の最大値の最小', tags: ['配列'], io: '1行目に R C、続く R 行に行列が与えられます。', ask: '各列の最大値を求め、それらの最小値を出力してください(ミニマックス)。', h1: 'zip(*g) で列を取る。', h2: '各列の max→全体 min。', ref: 'first=input().split()\nR=int(first[0])\nC=int(first[1])\ng=[list(map(int,input().split())) for _ in range(R)]\nprint(min(max(col) for col in zip(*g)))', tip: '列の最大の最小(minimax)はゲームの安全戦略に対応。各列 max→全体 min。', ins: ['2 2\n1 2\n3 4\n', '1 1\n5\n', '2 3\n1 2 3\n4 5 6\n', '2 2\n9 1\n1 9\n', '3 2\n1 2\n3 4\n5 6\n', '1 3\n3 1 2\n'] })

t({ lv: 206, concept: '配列: 行列の負の数の個数', title: '行・列ソート行列の負の数の個数', tags: ['配列'], io: '1行目に R C、続く R 行に各行・各列が降順の行列が与えられます。', ask: '負の数の個数を階段状走査で求めて出力してください。', h1: '右上から始める。', h2: '負なら左下、非負なら下へ。', ref: 'first=input().split()\nR=int(first[0])\nC=int(first[1])\ng=[list(map(int,input().split())) for _ in range(R)]\ncnt=0\nr=0\nc=C-1\nwhile r<R and c>=0:\n    if g[r][c]<0:\n        cnt+=r+1\n        c-=1\n    else:\n        r+=1\nprint(cnt)', tip: '行・列がソート済みなら階段状走査(右上から)で負の数を O(R+C) で数えられる。', ins: ['3 4\n4 3 2 -1\n3 2 1 -1\n1 1 -1 -2\n', '1 1\n-5\n', '1 1\n5\n', '2 2\n1 -1\n-1 -2\n', '2 2\n3 2\n1 0\n', '2 3\n5 4 3\n2 1 -1\n'] })

t({ lv: 207, concept: '配列: 行列の周囲の和', title: '行列の外周要素の和', tags: ['配列'], io: '1行目に R C、続く R 行に行列が与えられます。', ask: '最外周(1行目・最終行・1列目・最終列)の要素の和を出力してください(重複は1回だけ)。', h1: '周囲のマスを判定する。', h2: '端の行か端の列なら加える。', ref: 'first=input().split()\nR=int(first[0])\nC=int(first[1])\ng=[list(map(int,input().split())) for _ in range(R)]\ntotal=0\nfor i in range(R):\n    for j in range(C):\n        if i==0 or i==R-1 or j==0 or j==C-1:\n            total+=g[i][j]\nprint(total)', tip: '外周和は「端の行か端の列か」で判定。角が二重計上されないよう or 条件でまとめる。', ins: ['2 2\n1 2\n3 4\n', '1 1\n5\n', '3 3\n1 1 1\n1 9 1\n1 1 1\n', '1 4\n1 2 3 4\n', '3 1\n1\n2\n3\n', '3 3\n1 2 3\n4 5 6\n7 8 9\n'] })

t({ lv: 208, concept: 'ハッシュ: 相異なる行の数', title: '行列の相異なる行の数', tags: ['ハッシュ'], io: '1行目に R C、続く R 行に行列が与えられます。', ask: '相異なる行(内容が同じ行は同一とみなす)の種類数を出力してください。', h1: '各行をタプルにする。', h2: '集合の要素数。', ref: 'first=input().split()\nR=int(first[0])\nC=int(first[1])\nrows=set()\nfor _ in range(R):\n    rows.add(tuple(map(int,input().split())))\nprint(len(rows))', tip: '行をタプル化すると集合に入れられる(リストは不可)。重複行の検出に使う。', ins: ['3 2\n1 2\n1 2\n3 4\n', '1 1\n5\n', '2 2\n1 1\n2 2\n', '3 1\n1\n1\n1\n', '2 3\n1 2 3\n1 2 3\n', '2 2\n1 2\n3 4\n'] })

t({ lv: 209, concept: '配列: 行列の180度回転', title: '行列を180度回転', tags: ['配列'], io: '1行目に R C、続く R 行に行列が与えられます。', ask: '180度回転した行列を各行空白区切りで出力してください。', h1: '行を逆順、各行も逆順。', h2: 'g[::-1] の各行を反転。', ref: 'first=input().split()\nR=int(first[0])\nC=int(first[1])\ng=[list(map(int,input().split())) for _ in range(R)]\nfor row in g[::-1]:\n    print(*row[::-1])', tip: '180度回転は「行を逆順にして各行も逆順」。90度回転を2回かけたものに等しい。', ins: ['2 2\n1 2\n3 4\n', '1 1\n5\n', '2 3\n1 2 3\n4 5 6\n', '1 4\n1 2 3 4\n', '3 1\n1\n2\n3\n', '2 2\n1 0\n0 1\n'] })

t({ lv: 211, concept: '配列: 範囲内の要素数', title: '指定範囲に入る要素の数', tags: ['配列'], io: '1行目に lo hi、2行目に整数列が与えられます。', ask: 'lo 以上 hi 以下の要素の個数を出力してください。', h1: '各要素が範囲内か見る。', h2: '条件カウント。', ref: 'lo,hi=map(int,input().split())\na=list(map(int,input().split()))\nprint(sum(1 for x in a if lo<=x<=hi))', tip: '範囲内カウントは lo<=x<=hi の連鎖比較。ソート済みなら二分探索で O(log n)。', ins: ['2 4\n1 2 3 4 5\n', '0 0\n5\n', '1 10\n5 15 7\n', '-1 1\n-2 0 2\n', '5 5\n5 5 5\n', '1 3\n4 5 6\n'] })

t({ lv: 212, concept: '配列: 窓和がしきい値超えの数', title: '長さkの窓で和がt超の数', tags: ['二ポインタ'], io: '1行目に k t、2行目に整数列が与えられます。', ask: '長さ k の連続窓のうち、和が t より大きいものの個数を出力してください。', h1: '窓和をスライドで更新。', h2: 't 超を数える。', ref: 'first=input().split()\nk=int(first[0])\nth=int(first[1])\na=list(map(int,input().split()))\nn=len(a)\ncur=sum(a[:k])\ncnt=1 if cur>th else 0\nfor i in range(k,n):\n    cur+=a[i]-a[i-k]\n    if cur>th:\n        cnt+=1\nprint(cnt)', tip: '固定長窓の和はスライドで O(1) 更新。条件を満たす窓の数を数える典型。', ins: ['2 3\n1 2 3 4\n', '1 0\n1 2 3\n', '3 10\n1 2 3 4\n', '2 100\n1 2 3\n', '1 2\n3 1 4\n', '2 5\n2 3 4 5\n'] })

t({ lv: 213, concept: '配列: 窓の最小和', title: '長さkの窓の最小和', tags: ['二ポインタ'], io: '1行目に k、2行目に整数列が与えられます。', ask: '長さ k の連続窓の和の最小値を出力してください。', h1: '窓和をスライドで更新。', h2: '最小を取る。', ref: 'k=int(input())\na=list(map(int,input().split()))\nn=len(a)\ncur=sum(a[:k])\nbest=cur\nfor i in range(k,n):\n    cur+=a[i]-a[i-k]\n    if cur<best:\n        best=cur\nprint(best)', tip: '固定長窓の最小和はスライディングウィンドウ。最大和(別問題)と対称。', ins: ['2\n4 2 1 3\n', '1\n5 1 9\n', '3\n3 3 3\n', '2\n-1 -2 -3\n', '4\n1 2 3 4\n', '2\n5 5\n'] })

t({ lv: 214, concept: '二分探索: 回転回数', title: '回転したソート配列の回転回数', tags: ['二分探索'], io: '相異なる整数を昇順にして何回か左回転した列が1行で与えられます。', ask: '最小値の添字(=回転回数)を出力してください。', h1: '二分探索で最小を探す。', h2: '中央と右端を比べる。', ref: 'a=list(map(int,input().split()))\nlo=0\nhi=len(a)-1\nwhile lo<hi:\n    mid=(lo+hi)//2\n    if a[mid]>a[hi]:\n        lo=mid+1\n    else:\n        hi=mid\nprint(lo)', tip: '回転ソート配列の最小位置は二分探索で。a[mid]>a[hi] なら最小は右側にある。', ins: ['3 4 5 1 2\n', '1 2 3\n', '2 1\n', '5\n', '4 5 6 7 0 1 2\n', '1\n'] })

t({ lv: 215, concept: '二分探索: 値の探索', title: 'ソート配列で値を探す', tags: ['二分探索'], io: '1行目に探す値 x、2行目に昇順の整数列が与えられます。', ask: 'x の添字(0始まり)を出力してください。無ければ -1。', h1: '二分探索する。', h2: '見つかれば添字、なければ -1。', ref: 'import bisect\nx=int(input())\na=list(map(int,input().split()))\ni=bisect.bisect_left(a,x)\nif i<len(a) and a[i]==x:\n    print(i)\nelse:\n    print(-1)', tip: '二分探索は bisect_left で挿入位置を得て、その位置が x かを確認する。O(log n)。', ins: ['3\n1 2 3 4 5\n', '6\n1 2 3\n', '1\n1\n', '5\n1 3 5 7\n', '2\n1 3 5\n', '4\n2 4 6\n'] })

t({ lv: 216, concept: '二分探索: 出現回数', title: 'ソート配列での出現回数', tags: ['二分探索'], io: '1行目に値 x、2行目に昇順の整数列が与えられます。', ask: 'x の出現回数を出力してください。', h1: '左端と右端の挿入位置を求める。', h2: '差が個数。', ref: 'import bisect\nx=int(input())\na=list(map(int,input().split()))\nprint(bisect.bisect_right(a,x)-bisect.bisect_left(a,x))', tip: '出現回数は bisect_right - bisect_left。ソート済みなら O(log n) で範囲を特定できる。', ins: ['2\n1 2 2 2 3\n', '5\n1 2 3\n', '1\n1 1 1\n', '4\n2 4 4 6\n', '3\n1 2 3\n', '7\n5 6 7 7 7\n'] })

t({ lv: 217, concept: '二分探索: 床(x以下の最大)', title: 'ソート配列でx以下の最大値', tags: ['二分探索'], io: '1行目に値 x、2行目に昇順の整数列が与えられます。', ask: 'x 以下で最大の要素を出力してください。無ければ NONE。', h1: '挿入位置の1つ手前を見る。', h2: 'bisect_right-1。', ref: 'import bisect\nx=int(input())\na=list(map(int,input().split()))\ni=bisect.bisect_right(a,x)-1\nprint(a[i] if i>=0 else "NONE")', tip: 'floor(x以下の最大)は bisect_right-1 の位置。範囲クエリや最近値探索に使う。', ins: ['3\n1 2 4 5\n', '0\n1 2 3\n', '5\n1 3 5\n', '10\n2 4 6\n', '2\n2 2 2\n', '1\n1\n'] })

t({ lv: 218, concept: '二分探索: 天井(x以上の最小)', title: 'ソート配列でx以上の最小値', tags: ['二分探索'], io: '1行目に値 x、2行目に昇順の整数列が与えられます。', ask: 'x 以上で最小の要素を出力してください。無ければ NONE。', h1: '挿入位置を見る。', h2: 'bisect_left。', ref: 'import bisect\nx=int(input())\na=list(map(int,input().split()))\ni=bisect.bisect_left(a,x)\nprint(a[i] if i<len(a) else "NONE")', tip: 'ceil(x以上の最小)は bisect_left の位置。floor と対で範囲探索の基本になる。', ins: ['3\n1 2 4 5\n', '4\n1 2 3\n', '0\n1 3 5\n', '7\n2 4 6\n', '2\n2 2 2\n', '1\n1\n'] })

t({ lv: 219, concept: 'ハッシュ: 差がdのペア数', title: '差がちょうどdのペアの数', tags: ['ハッシュ'], io: '1行目に d(d>=0)、2行目に整数列が与えられます。', ask: '|x-y|=d となる相異なる値ペア {x,y} の種類数を出力してください。', h1: '値の集合を作る。', h2: 'x と x+d の共存を数える。', ref: 'd=int(input())\na=list(map(int,input().split()))\nfrom collections import Counter\ncnt=Counter(a)\nvals=set(a)\nif d==0:\n    print(sum(1 for v in cnt if cnt[v]>=2))\nelse:\n    print(sum(1 for v in vals if v+d in vals))', tip: '差dのペア種類数は集合で判定。d=0は重複値、d>0は x と x+d の共存を数える。', ins: ['1\n1 2 3 4\n', '0\n1 1 2 2\n', '2\n1 3 5\n', '3\n1 2 3\n', '1\n5\n', '2\n1 1 3 3\n'] })

t({ lv: 220, concept: 'ソート: 和がs未満のペア数', title: '和がs未満のペアの数', tags: ['ソート', '二ポインタ'], io: '1行目に s、2行目に整数列が与えられます。', ask: '2要素の和が s 未満になるペア (i<j) の個数を出力してください。', h1: 'ソートして両端から詰める。', h2: '和<s なら間の全ペアが条件を満たす。', ref: 's=int(input())\na=sorted(map(int,input().split()))\ni=0\nj=len(a)-1\ncnt=0\nwhile i<j:\n    if a[i]+a[j]<s:\n        cnt+=j-i\n        i+=1\n    else:\n        j-=1\nprint(cnt)', tip: '「和<s のペア数」はソート＋二ポインタ。a[i]+a[j]<s なら i と (i,j] の全ペアが条件を満たす。', ins: ['5\n1 2 3 4\n', '3\n1 1 1\n', '10\n1 2 3\n', '0\n1 2\n', '4\n2 2 2\n', '6\n1 2 3 4 5\n'] })

t({ lv: 221, concept: 'ハッシュ: 0と1が同数の最長部分配列', title: '0と1が同数の最長連続部分配列', tags: ['ハッシュ'], io: '0と1の列が1行で与えられます。', ask: '0の個数と1の個数が等しい最長の連続部分配列の長さを出力してください。', h1: '0を-1とみなして累積和。', h2: '同じ累積和の最遠2点。', ref: 'a=list(map(int,input().split()))\nfirst={0:-1}\ns=0\nbest=0\nfor i,x in enumerate(a):\n    s+=1 if x==1 else -1\n    if s in first:\n        best=max(best,i-first[s])\n    else:\n        first[s]=i\nprint(best)', tip: '0と1が同数は「0を-1にした累積和が等しい2点」。和0の最長区間に帰着する。', ins: ['0 1 0\n', '0 1 1 0 1 1 1 0\n', '1 1 1\n', '0 0\n', '0 1\n', '1 0 1 0\n'] })

t({ lv: 222, concept: 'ソート: 最小の絶対差', title: '任意2要素の最小絶対差', tags: ['ソート'], io: '整数列が1行で与えられます(2個以上)。', ask: '任意の2要素の差の絶対値の最小値を出力してください。', h1: 'ソートする。', h2: '隣接差の最小を取る。', ref: 'a=sorted(map(int,input().split()))\nprint(min(a[i+1]-a[i] for i in range(len(a)-1)))', tip: '最小絶対差はソート後の隣接差の最小。離れた要素ほど差が大きいので隣だけ見ればよい。', ins: ['3 8 1 5\n', '1 2\n', '10 1 100\n', '5 5\n', '1 3 6 10\n', '-3 0 4\n'] })

t({ lv: 223, concept: 'ソート: 小さいk個の和', title: '最も小さいk個の和', tags: ['ソート'], io: '1行目に k、2行目に整数列が与えられます。', ask: '最も小さい k 個の要素の和を出力してください。', h1: '昇順にソートする。', h2: '先頭 k 個を足す。', ref: 'k=int(input())\na=sorted(map(int,input().split()))\nprint(sum(a[:k]))', tip: '小さいk個の和は昇順ソートの先頭kの和。nsmallest でも O(n log k) で求まる。', ins: ['2\n3 1 4 1 5\n', '1\n5\n', '3\n5 4 3 2 1\n', '3\n1 2 3\n', '2\n9 8 7\n', '4\n2 2 2 2\n'] })

t({ lv: 224, concept: 'ソート: k番目に小さい相異なる値', title: 'k番目に小さい相異なる値', tags: ['ソート', '集合'], io: '1行目に k、2行目に整数列が与えられます。', ask: '相異なる値の中で k 番目に小さいものを出力してください。存在しなければ -1。', h1: '重複を除いてソート。', h2: '添字 k-1(範囲外なら -1)。', ref: 'k=int(input())\na=sorted(set(map(int,input().split())))\nprint(a[k-1] if k<=len(a) else -1)', tip: '相異なる値の k 番目は set でユニーク化してソート。重複を無視した順位統計。', ins: ['2\n1 1 2 3 3\n', '1\n5 5\n', '4\n1 2 3\n', '3\n3 1 2 2\n', '1\n7\n', '2\n5 5 5\n'] })

t({ lv: 225, concept: '配列: 過半数要素の有無', title: '過半数を占める要素があるか', tags: ['配列', 'ハッシュ'], io: '整数列が1行で与えられます。', ask: '出現回数が要素数の半分を超える値が存在すれば yes、なければ no を出力してください。', h1: '出現回数を数える。', h2: '最大回数が n/2 を超えるか。', ref: 'from collections import Counter\na=list(map(int,input().split()))\nn=len(a)\nprint("yes" if max(Counter(a).values())*2>n else "no")', tip: '過半数要素の有無は最頻値の回数が n/2 超かで判定。ボイヤー・ムーア法の前提確認。', ins: ['1 1 2\n', '1 2 3\n', '5 5 5\n', '1 1 2 2\n', '7\n', '3 3 3 1 2\n'] })

t({ lv: 226, concept: 'ハッシュ: 最頻の偶数', title: '最も多く現れる偶数', tags: ['ハッシュ'], io: '整数列が1行で与えられます(偶数が1つ以上ある)。', ask: '偶数のうち最も多く現れる値を出力してください。同点は最小。', h1: '偶数だけ数える。', h2: '(回数降順, 値昇順)で選ぶ。', ref: 'from collections import Counter\na=[x for x in map(int,input().split()) if x%2==0]\ncnt=Counter(a)\nbest=None\nbestc=-1\nfor v in sorted(cnt):\n    if cnt[v]>bestc:\n        bestc=cnt[v]\n        best=v\nprint(best)', tip: 'フィルタ(偶数)してから最頻値。条件付き集計の組合せパターン。', ins: ['2 2 4\n', '1 2 3 2\n', '6\n', '4 4 6 6\n', '2 4 6 4\n', '8 8 8 2 2'] })

t({ lv: 227, concept: 'ハッシュ: 一度だけの要素の和', title: '1回だけ現れる値の合計', tags: ['ハッシュ'], io: '整数列が1行で与えられます。', ask: 'ちょうど1回だけ現れる値の合計を出力してください。', h1: '出現回数を数える。', h2: '回数1の値を足す。', ref: 'from collections import Counter\na=list(map(int,input().split()))\ncnt=Counter(a)\nprint(sum(v for v in cnt if cnt[v]==1))', tip: 'ユニーク要素の和は Counter で回数1の値を足す。重複を除いた寄与の集計。', ins: ['1 2 2 3\n', '1 2 3\n', '1 1 1\n', '5\n', '4 4 5 6 6\n', '7 8 8 9\n'] })

t({ lv: 228, concept: 'ハッシュ: 2回現れる要素の和', title: 'ちょうど2回現れる値の合計', tags: ['ハッシュ'], io: '整数列が1行で与えられます。', ask: '出現回数がちょうど2回の値の合計を出力してください。', h1: '出現回数を数える。', h2: '回数2の値を足す。', ref: 'from collections import Counter\na=list(map(int,input().split()))\ncnt=Counter(a)\nprint(sum(v for v in cnt if cnt[v]==2))', tip: '回数指定の集計は Counter の値でフィルタ。1回・2回・k回と一般化できる。', ins: ['1 1 2 3 3\n', '1 2 3\n', '5 5\n', '1 1 1\n', '4 4 5 5 6\n', '7 8 8\n'] })

t({ lv: 229, concept: '配列: 積のmod', title: 'リストの積をmで割った余り', tags: ['数論'], io: '1行目に m、2行目に整数列が与えられます。', ask: '全要素の積を m で割った余りを出力してください。', h1: '掛けるたびに mod を取る。', h2: 'オーバーフロー対策(Pythonは多倍長だが習慣)。', ref: 'm=int(input())\na=list(map(int,input().split()))\np=1\nfor x in a:\n    p=p*x%m\nprint(p)', tip: '積のmodは掛けるたびに %m を取ると値が小さく保てる。(a·b)%m=((a%m)(b%m))%m。', ins: ['1000\n2 3 4\n', '7\n10 20\n', '5\n1 2 3 4\n', '100\n5\n', '13\n12 12\n', '1000000007\n2 2 2\n'] })

t({ lv: 230, concept: 'bit演算: 全要素のXOR', title: 'リスト全要素のXOR', tags: ['bit演算'], io: '非負整数の列が1行で与えられます。', ask: '全要素のXORを出力してください。', h1: '順にXORを取る。', h2: '初期値0。', ref: 'a=list(map(int,input().split()))\nx=0\nfor v in a:\n    x^=v\nprint(x)', tip: '全XORは「2回現れる数が消える」性質を持つ。1つだけ奇数回の数を見つけるのに使う。', ins: ['1 2 3\n', '5\n', '4 4 7\n', '0 0 0\n', '1 1 2 2 3\n', '8 8\n'] })

t({ lv: 231, concept: 'bit演算: 全要素のAND', title: 'リスト全要素のビットAND', tags: ['bit演算'], io: '非負整数の列が1行で与えられます。', ask: '全要素のビットANDを出力してください。', h1: '順にANDを取る。', h2: '最初の要素から始める。', ref: 'a=list(map(int,input().split()))\nx=a[0]\nfor v in a[1:]:\n    x&=v\nprint(x)', tip: '全ANDは全要素で共通して立つビットだけ残る。範囲ANDなどの基礎。', ins: ['7 3 5\n', '5\n', '12 8\n', '6 6 6\n', '1 2 4\n', '15 7 3'] })

t({ lv: 232, concept: 'bit演算: 全要素のOR', title: 'リスト全要素のビットOR', tags: ['bit演算'], io: '非負整数の列が1行で与えられます。', ask: '全要素のビットORを出力してください。', h1: '順にORを取る。', h2: '初期値0。', ref: 'a=list(map(int,input().split()))\nx=0\nfor v in a:\n    x|=v\nprint(x)', tip: '全ORはどれかで立つビットを集める。使われているビットの和集合に対応する。', ins: ['1 2 4\n', '5\n', '8 1\n', '0 0 0\n', '6 6 6\n', '3 5 9'] })

t({ lv: 233, concept: 'bit演算: 立ちビットの総数', title: '全要素の立ちビット数の合計', tags: ['bit演算'], io: '非負整数の列が1行で与えられます。', ask: '各要素の立っているビット数の合計を出力してください。', h1: '各要素の popcount を足す。', h2: 'bin(x).count("1")。', ref: 'a=list(map(int,input().split()))\nprint(sum(bin(x).count("1") for x in a))', tip: '立ちビット総数は各要素の popcount の和。ハミング重みの集計で、特徴の総数などに使う。', ins: ['1 2 3\n', '0\n', '7 7\n', '255\n', '1 1 1\n', '8 4 2'] })

t({ lv: 234, concept: 'bit演算: 立ちビット最多の要素', title: '立ちビットが最多の要素', tags: ['bit演算'], io: '非負整数の列が1行で与えられます。', ask: '立っているビット数が最も多い要素を出力してください。同数なら最初のもの。', h1: 'popcount をキーにする。', h2: 'max に key を渡す。', ref: 'a=list(map(int,input().split()))\nprint(max(a,key=lambda x:bin(x).count("1")))', tip: 'max に key=popcount を渡すと「最もビットが立つ要素」が得られる。同点は先頭。', ins: ['1 7 3\n', '5\n', '8 7\n', '0 0\n', '15 1 2\n', '4 6 12'] })

t({ lv: 235, concept: 'bit演算: 立ちビット数で整列', title: '立ちビット数の昇順に並べる', tags: ['bit演算', 'ソート'], io: '非負整数の列が1行で与えられます。', ask: '立っているビット数の昇順に並べて出力してください(同数は値の昇順)。', h1: 'key を (popcount, 値) に。', h2: 'sorted で並べる。', ref: 'a=list(map(int,input().split()))\nprint(*sorted(a,key=lambda x:(bin(x).count("1"),x)))', tip: '複合キー (popcount, 値) のソートで同点の並びも一意に決まる。安定ソートの活用。', ins: ['3 1 2\n', '7 1 0\n', '5\n', '0 1 2 3\n', '8 4 2 1\n', '6 5 3'] })

t({ lv: 236, concept: '配列: 偶数位置と奇数位置の和の差', title: '偶数添字と奇数添字の和の差', tags: ['配列'], io: '整数列が1行で与えられます。', ask: '偶数添字の要素の和から奇数添字の要素の和を引いた値を出力してください。', h1: '添字の偶奇で分ける。', h2: '差を取る。', ref: 'a=list(map(int,input().split()))\neven=sum(a[i] for i in range(0,len(a),2))\nodd=sum(a[i] for i in range(1,len(a),2))\nprint(even-odd)', tip: '偶数/奇数添字の和の差は交代和の一種。ステップ2のスライス a[::2], a[1::2] でも分けられる。', ins: ['1 2 3 4\n', '5\n', '1 1 1 1\n', '10 1 10 1\n', '0 0 0\n', '3 1 4 1 5'] })

t({ lv: 237, concept: '配列: ジグザグ配置の判定', title: '配列がジグザグか', tags: ['配列'], io: '整数列が1行で与えられます。', ask: 'a0<=a1>=a2<=a3>=... の交互パターン(ジグザグ)になっていれば yes、違うなら no を出力してください。', h1: '各位置で向きを確認。', h2: '偶数位置は<=、奇数位置は>=。', ref: 'a=list(map(int,input().split()))\nok=True\nfor i in range(len(a)-1):\n    if i%2==0:\n        if not a[i]<=a[i+1]:\n            ok=False\n    else:\n        if not a[i]>=a[i+1]:\n            ok=False\nprint("yes" if ok else "no")', tip: 'ジグザグ判定は位置の偶奇で比較向きを切り替える。wiggle sort の検証に対応する。', ins: ['1 3 2 4\n', '1 2 3\n', '3 1 2\n', '5\n', '1 1 1\n', '2 5 1 6 3'] })

t({ lv: 238, concept: '配列: 局所最小の数', title: '谷(局所最小)の個数', tags: ['配列'], io: '整数列が1行で与えられます。', ask: '両隣より真に小さい要素(局所最小)の個数を出力してください(端は対象外)。', h1: '内側の各位置を見る。', h2: '左右より小さいか判定。', ref: 'a=list(map(int,input().split()))\ncnt=0\nfor i in range(1,len(a)-1):\n    if a[i]<a[i-1] and a[i]<a[i+1]:\n        cnt+=1\nprint(cnt)', tip: '局所最小(谷)は両隣より小さい内部要素。極大(山, 別問題)と対称な極値検出。', ins: ['3 1 2 0 4\n', '1 2 3\n', '3 2 1\n', '5\n', '2 1 2 1 2\n', '1 1 1\n'] })

t({ lv: 239, concept: '配列: 連続増加3つ組の数', title: '連続して増加する3つ組の数', tags: ['配列'], io: '整数列が1行で与えられます。', ask: 'a[i]<a[i+1]<a[i+2] となる連続3要素の組の個数を出力してください。', h1: '連続3要素を見る。', h2: '増加しているか判定。', ref: 'a=list(map(int,input().split()))\ncnt=0\nfor i in range(len(a)-2):\n    if a[i]<a[i+1]<a[i+2]:\n        cnt+=1\nprint(cnt)', tip: '連続増加3つ組は連鎖比較 a[i]<a[i+1]<a[i+2] で判定。トレンド検出の基本。', ins: ['1 2 3 4\n', '1 2 1 2 3\n', '3 2 1\n', '1 2\n', '5\n', '1 3 5 4 6 7'] })

t({ lv: 240, concept: '配列: 最長の同値連続', title: '同じ値が続く最大長', tags: ['配列'], io: '整数列が1行で与えられます。', ask: '同じ値が連続する最大の長さを出力してください。', h1: '直前と同じか見る。', h2: '連続長の最大。', ref: 'a=list(map(int,input().split()))\nif not a:\n    print(0)\nelse:\n    best=1\n    cur=1\n    for i in range(1,len(a)):\n        if a[i]==a[i-1]:\n            cur+=1\n            if cur>best:\n                best=cur\n        else:\n            cur=1\n    print(best)', tip: '同値連続の最大長(最長プラトー)はリセット型走査。ランレングスの最大ラン長に対応。', ins: ['1 1 2 2 2\n', '1 2 3\n', '5 5 5 5\n', '1\n', '1 1 1 2\n', '3 3 4 4 4 1'] })

t({ lv: 241, concept: '配列: 2番目に大きい相異なる値', title: '2番目に大きい相異なる値', tags: ['配列', '集合'], io: '整数列が1行で与えられます。', ask: '相異なる値の中で2番目に大きいものを出力してください。存在しなければ -1。', h1: '重複を除いてソート。', h2: '降順で2番目。', ref: 'a=sorted(set(map(int,input().split())),reverse=True)\nprint(a[1] if len(a)>=2 else -1)', tip: '相異なる値の2番目は set 後にソート。重複を無視した順位は集合化が基本。', ins: ['1 2 2 3\n', '5 5\n', '1 2 3\n', '7\n', '4 4 4\n', '10 5 10 8'] })

t({ lv: 242, concept: '配列: 2番目に小さい相異なる値', title: '2番目に小さい相異なる値', tags: ['配列', '集合'], io: '整数列が1行で与えられます。', ask: '相異なる値の中で2番目に小さいものを出力してください。存在しなければ -1。', h1: '重複を除いてソート。', h2: '昇順で2番目。', ref: 'a=sorted(set(map(int,input().split())))\nprint(a[1] if len(a)>=2 else -1)', tip: '相異なる値の2番目に小さい値も set＋昇順ソート。最大版と対称。', ins: ['1 2 2 3\n', '5 5\n', '1 2 3\n', '7\n', '4 4 4\n', '3 1 1 2'] })

t({ lv: 243, concept: '配列: 偶数の値域', title: '偶数の最大-最小', tags: ['配列'], io: '整数列が1行で与えられます(偶数が1つ以上ある)。', ask: '偶数の要素のうち最大と最小の差を出力してください。', h1: '偶数だけ取り出す。', h2: 'max-min。', ref: 'a=[x for x in map(int,input().split()) if x%2==0]\nprint(max(a)-min(a))', tip: 'フィルタ後の値域。偶数だけ抽出して max-min を取る、条件付き集計の組合せ。', ins: ['1 2 4 6\n', '2\n', '3 8 1 4\n', '2 2 2\n', '0 10 5\n', '6 2 8 3'] })

t({ lv: 244, concept: '数: 合計の桁和', title: 'リストの和の桁和', tags: ['数学'], io: '整数列が1行で与えられます。', ask: '全要素の合計を求め、その合計(非負とする)の各桁の和を出力してください。', h1: '合計を求める。', h2: '桁和を計算。', ref: 'a=list(map(int,input().split()))\ns=sum(a)\nprint(sum(int(c) for c in str(abs(s))))', tip: '2段階の集計(合計→桁和)。abs で負号を除いてから桁を分解する。', ins: ['1 2 3\n', '99 1\n', '10 20 30\n', '5\n', '100\n', '4 5 6'] })

export const CATALOG = TASKS
