// 生成タスク 第18波：競技プログラミングの定番テクニック。整数=採点一意。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 120, concept: 'CP: 座標圧縮', title: '座標圧縮', tags: ['ソート', 'アルゴリズム'], io: '整数列が1行で与えられます。', ask: '各要素を「小さい順の順位 (0始まり、同じ値は同じ順位)」に置き換えて空白区切りで出力してください。', h1: '重複除去してソート。', h2: '値→順位の辞書を作る。', ref: 'a=list(map(int,input().split()))\norder={v:i for i,v in enumerate(sorted(set(a)))}\nprint(*[order[x] for x in a])', ins: ['40 10 20 20 30\n', '5 5 5\n', '1 2 3\n', '100 1 50\n', '3 1 4 1 5\n', '7\n'], tip: '💡 座標圧縮は値域が広いがデータ数が少ないときの定番前処理。' })
t({ lv: 120, concept: 'CP: 区間和クエリ', title: '累積和で区間和クエリ', tags: ['累積和', 'アルゴリズム'], io: '1行目に n q、2行目に n 個の整数、続く q 行に l r (1始まり, 両端含む) が与えられます。', ask: '各クエリで a[l..r] の和を1行ずつ出力してください。', h1: '累積和 pre を前計算。', h2: 'pre[r]-pre[l-1]。', ref: 'import sys\nd=sys.stdin.read().split()\ni=0\nn=int(d[i]);i+=1\nq=int(d[i]);i+=1\na=[int(d[i+j]) for j in range(n)];i+=n\npre=[0]*(n+1)\nfor j in range(n):\n    pre[j+1]=pre[j]+a[j]\nout=[]\nfor _ in range(q):\n    l=int(d[i]);r=int(d[i+1]);i+=2\n    out.append(str(pre[r]-pre[l-1]))\nprint("\\n".join(out))', ins: ['5 2\n1 2 3 4 5\n1 3\n2 5\n', '3 1\n10 20 30\n1 3\n', '4 2\n1 1 1 1\n1 1\n2 4\n', '1 1\n7\n1 1\n', '5 1\n5 4 3 2 1\n2 4\n', '6 2\n1 2 3 4 5 6\n1 6\n3 3\n'], tip: '💡 累積和で区間和は前計算 O(n)・各クエリ O(1)。' })
t({ lv: 150, concept: 'CP: 累積XOR', title: 'XORがKの部分配列の個数', tags: ['累積和', 'ハッシュ', 'アルゴリズム'], io: '1行目に n k、2行目に n 個の非負整数が与えられます。', ask: '連続部分配列のXORがちょうど k になるものの個数を出力してください。', h1: '累積XOR を進める。', h2: 'これまでに x^k が何回出たか。', ref: 'from collections import defaultdict\nn,k=map(int,input().split())\na=list(map(int,input().split()))\ncnt=defaultdict(int)\ncnt[0]=1\nx=0\nans=0\nfor v in a:\n    x^=v\n    ans+=cnt[x^k]\n    cnt[x]+=1\nprint(ans)', ins: ['4 1\n1 1 1 1\n', '3 0\n1 1 1\n', '5 6\n4 2 2 6 4\n', '3 2\n1 2 3\n', '4 0\n2 2 2 2\n', '2 3\n1 2\n'], tip: '💡 区間XOR = 累積XORの差(XOR)。和の代わりにXORでも同じ手法。' })
t({ lv: 150, concept: 'CP: しゃくとり法', title: '和がK以下の最長区間', tags: ['スライディングウィンドウ', '二点ポインタ', 'アルゴリズム'], io: '1行目に n k、2行目に n 個の非負整数が与えられます。', ask: '和が k 以下になる連続区間の最大の長さを出力してください。', h1: '右を伸ばし、超えたら左を縮める。', h2: '尺取り法。', ref: 'n,k=map(int,input().split())\na=list(map(int,input().split()))\nl=0\ns=0\nbest=0\nfor r in range(n):\n    s+=a[r]\n    while s>k:\n        s-=a[l]\n        l+=1\n    best=max(best,r-l+1)\nprint(best)', ins: ['5 7\n2 1 3 4 1\n', '4 0\n1 2 3 4\n', '3 100\n1 2 3\n', '5 5\n5 5 5 5 5\n', '6 8\n1 2 1 4 1 1\n', '1 3\n5\n'], tip: '💡 尺取り法は「単調に伸縮する窓」で O(n)。和や種類数の条件に。' })
t({ lv: 170, concept: 'CP: ヒストグラム最大長方形', title: 'ヒストグラム内の最大長方形', tags: ['単調スタック', 'スタック', 'アルゴリズム'], io: '棒グラフの高さが空白区切りで与えられます。', ask: '連続する棒からなる最大長方形の面積を出力してください。', h1: '高さが減るところで確定。', h2: '単調増加スタックに開始位置を保持。', ref: 'a=list(map(int,input().split()))\na.append(0)\nst=[]\nbest=0\nfor i,h in enumerate(a):\n    start=i\n    while st and st[-1][1]>h:\n        idx,height=st.pop()\n        best=max(best,height*(i-idx))\n        start=idx\n    st.append((start,h))\nprint(best)', ins: ['2 1 5 6 2 3\n', '2 4\n', '1 1 1\n', '5\n', '6 2 5 4 5 1 6\n', '3 1 3 2 2\n'], tip: '💡 単調スタックでヒストグラム最大長方形は O(n)。' })
t({ lv: 550, concept: 'CP: 次の順列', title: '辞書順で次の順列', tags: ['順列', 'アルゴリズム'], io: '相異なる整数の並び (順列) が1行で与えられます。', ask: '辞書順で次の順列を空白区切りで出力してください。最後の順列なら -1 を出力します。', h1: '右から下降が崩れる位置を探す。', h2: 'そこを次に大きい値と交換し、後ろを反転。', ref: 'a=list(map(int,input().split()))\nn=len(a)\ni=n-2\nwhile i>=0 and a[i]>=a[i+1]:\n    i-=1\nif i<0:\n    print(-1)\nelse:\n    j=n-1\n    while a[j]<=a[i]:\n        j-=1\n    a[i],a[j]=a[j],a[i]\n    a[i+1:]=a[i+1:][::-1]\n    print(*a)', ins: ['1 2 3\n', '3 2 1\n', '1 3 2\n', '2 3 1\n', '1 2 3 4\n', '1\n'], tip: '💡 next_permutation のアルゴリズム。全順列を辞書順に列挙する基礎。' })
t({ lv: 600, concept: 'CP: 無向グラフの閉路判定', title: '無向グラフに閉路があるか', tags: ['グラフ', 'BFS', 'アルゴリズム'], io: '1行目に n m、続く m 行に無向辺 u v (1始まり, 単純グラフ) が与えられます。', ask: '閉路があれば yes、なければ no を出力してください。', h1: '森(閉路なし)の辺数は n−連結成分数。', h2: 'BFSで連結成分数を数え、辺数がそれを超えれば閉路。', ref: 'from collections import deque\nn,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\nseen=[False]*(n+1)\nc=0\nfor s in range(1,n+1):\n    if not seen[s]:\n        c+=1\n        dq=deque([s])\n        seen[s]=True\n        while dq:\n            x=dq.popleft()\n            for y in g[x]:\n                if not seen[y]:\n                    seen[y]=True\n                    dq.append(y)\nprint("yes" if m>n-c else "no")', ins: ['3 3\n1 2\n2 3\n1 3\n', '3 2\n1 2\n2 3\n', '4 2\n1 2\n3 4\n', '4 4\n1 2\n2 3\n3 4\n4 1\n', '2 1\n1 2\n', '5 0\n'], tip: '💡 連結な森は辺数 n−1。辺がそれより多い成分があれば必ず閉路。' })
t({ lv: 650, concept: 'CP: トポロジカルソート可能か', title: '有向グラフがDAGか', tags: ['トポロジカル', 'グラフ', 'アルゴリズム'], io: '1行目に n m、続く m 行に有向辺 u→v (1始まり) が与えられます。', ask: '閉路がなく順序づけできる (DAG) なら yes、閉路があれば no を出力してください。', h1: '入次数0から取り除く(Kahn法)。', h2: '全部取り除けたらDAG。', ref: 'from collections import deque\nn,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nindeg=[0]*(n+1)\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    indeg[v]+=1\ndq=deque(i for i in range(1,n+1) if indeg[i]==0)\ncnt=0\nwhile dq:\n    x=dq.popleft()\n    cnt+=1\n    for y in g[x]:\n        indeg[y]-=1\n        if indeg[y]==0:\n            dq.append(y)\nprint("yes" if cnt==n else "no")', ins: ['3 2\n1 2\n2 3\n', '3 3\n1 2\n2 3\n3 1\n', '4 3\n1 2\n1 3\n3 4\n', '2 2\n1 2\n2 1\n', '5 0\n', '3 2\n1 2\n3 2\n'], tip: '💡 Kahn法で取り除けない頂点が残れば閉路あり。' })
t({ lv: 130, concept: 'CP: 特定数字を含まない数', title: '4を含まない数の個数', tags: ['数え上げ'], io: '非負整数 N が与えられます。', ask: '0 以上 N 以下で、数字 4 を含まない整数の個数を出力してください。', h1: '各数を文字列にして判定。', h2: '"4" not in str(x)。', ref: "n=int(input())\nprint(sum(1 for x in range(n+1) if '4' not in str(x)))", ins: ['10\n', '44\n', '100\n', '3\n', '50\n', '4\n'], tip: '💡 桁の条件を満たす数の数え上げは桁DPの入口。' })
t({ lv: 550, concept: 'CP: 中央値で総距離最小化', title: '全要素を等しくする最小コスト', tags: ['貪欲', 'ソート', 'アルゴリズム'], io: '整数列が1行で与えられます。', ask: '全要素をある整数 t に揃える操作のコストを Σ|aᵢ−t| とするとき、コストの最小値を出力してください。', h1: '最適な t は中央値。', h2: '中央値からの絶対差の和。', ref: 'a=sorted(map(int,input().split()))\nmed=a[len(a)//2]\nprint(sum(abs(x-med) for x in a))', ins: ['1 2 3\n', '1 10\n', '5 5 5\n', '1 2 3 4\n', '100 1\n', '2 4 6 8\n'], tip: '💡 L1距離の和を最小にする点は中央値(平均ではない)。' })

export const CATALOG = TASKS
