// 生成タスク 第61波：各レベル2問化フェーズ(16)。lv691〜699, lv701〜715 に2問目を追加。
// 高度DP/区間DP/株DP帯。重複なし・決定的・採点一意。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 691, concept: 'DP: 斜め腕の最大X印', title: '1で作る最大のX印', tags: ['DP'], io: '1行目に H W、続く H 行に0/1の行列が与えられます。', ask: '中心から斜め4方向に同じ長さの腕を伸ばした「X印」が全て1でできているときの、腕の長さ+1(中心含む片腕のマス数)の最大を出力してください。1が無ければ 0。', h1: '各マスで斜め4方向に連続する1の長さを前計算する。', h2: '4方向の最小値が、そのマスを中心にできるXの大きさ。', ref: 'h,w=map(int,input().split())\ng=[list(map(int,input().split())) for _ in range(h)]\ndef arm(dr,dc):\n    a=[[0]*w for _ in range(h)]\n    for i in (range(h) if dr<=0 else range(h-1,-1,-1)):\n        for j in (range(w) if dc<=0 else range(w-1,-1,-1)):\n            if g[i][j]:\n                pi,pj=i+dr,j+dc\n                a[i][j]=1+(a[pi][pj] if 0<=pi<h and 0<=pj<w else 0)\n    return a\nul=arm(-1,-1)\nur=arm(-1,1)\ndl=arm(1,-1)\ndr_=arm(1,1)\nbest=0\nfor i in range(h):\n    for j in range(w):\n        if g[i][j]:\n            v=min(ul[i][j],ur[i][j],dl[i][j],dr_[i][j])\n            if v>best:\n                best=v\nprint(best)', tip: '十字(上下左右)のX版。4方向の連続長を独立に前計算してminで束ねる構図は、腕の向きが変わっても崩れない。走査の向きを腕の向きに合わせるのが唯一の注意点。', ins: ['3 3\n1 0 1\n0 1 0\n1 0 1\n', '1 1\n1\n', '3 3\n1 1 1\n1 1 1\n1 1 1\n', '2 2\n0 0\n0 0\n', '5 5\n1 0 1 0 1\n0 1 0 1 0\n1 0 1 0 1\n0 1 0 1 0\n1 0 1 0 1\n', '3 4\n1 0 1 0\n0 1 0 0\n1 0 1 0\n'] })

t({ lv: 692, concept: '文字列: 隣接交換で回文にする最小回数', title: 'スワップだけで回文を作る', tags: ['文字列', '貪欲'], io: '英小文字の文字列が1行で与えられます。', ask: '隣接する2文字の交換だけで回文にできるなら最小交換回数を、できなければ -1 を出力してください。', h1: '奇数回現れる文字が2種類以上なら不可能。', h2: '左端の文字と対になる文字を右から探して端まで運ぶ(貪欲)。相方が無い(奇数文字)場合は1つ内側へ送る。', ref: 's=list(input())\nfrom collections import Counter\nodd=sum(1 for v in Counter(s).values() if v%2)\nif odd>1:\n    print(-1)\nelse:\n    cnt=0\n    l,r=0,len(s)-1\n    while l<r:\n        k=r\n        while k>l and s[k]!=s[l]:\n            k-=1\n        if k==l:\n            s[l],s[l+1]=s[l+1],s[l]\n            cnt+=1\n            continue\n        for i in range(k,r):\n            s[i],s[i+1]=s[i+1],s[i]\n            cnt+=1\n        l+=1\n        r-=1\n    print(cnt)', tip: '「右から最も近い相方を選ぶ」貪欲が最小性を与える(交差させない対応が最適)。奇数文字は中央行きなので一歩ずつ内側へ送ればよい。', ins: ['mamad\n', 'asflkj\n', 'aabb\n', 'ntiin\n', 'a\n', 'ab\n'] })

t({ lv: 693, concept: '区間DP: 括弧づけで作れる値の種類数', title: '計算順で何通りの値ができるか', tags: ['区間DP', '再帰'], io: '1行目に整数列、2行目に演算子(+, -, * のいずれか)が数より1個少なく与えられます。', ask: '計算の順序(括弧の付け方)を全て試したとき、式の値として現れる相異なる値の個数を出力してください。', h1: '最後に計算する演算子で式を2つに割る。', h2: '左右の「作れる値の集合」の直積に演算を適用し、集合で重複を潰す(メモ化)。', ref: 's=input().split()\nops=input().split()\nnums=[int(x) for x in s]\nmemo={}\ndef f(i,j):\n    if i==j:\n        return {nums[i]}\n    if (i,j) in memo:\n        return memo[(i,j)]\n    res=set()\n    for k in range(i,j):\n        for a in f(i,k):\n            for b in f(k+1,j):\n                if ops[k]=="+":\n                    res.add(a+b)\n                elif ops[k]=="-":\n                    res.add(a-b)\n                else:\n                    res.add(a*b)\n    memo[(i,j)]=res\n    return res\nprint(len(f(0,len(nums)-1)))', tip: '「値そのもの」でなく「値の集合」を区間DPの状態にする発想。括弧の付け方はカタラン数通りあるが、集合が重複を吸収して現実的な計算量になる。', ins: ['2 3 4\n+ *\n', '1 1 1\n+ +\n', '2 2\n-\n', '1 2 3 4\n- - -\n', '5 5\n*\n', '2 3 2\n* - \n'] })

t({ lv: 694, concept: 'bit演算: 部分集合ORの種類数', title: '部分集合ORで作れる値の数', tags: ['bit演算'], io: '非負整数の列が1行で空白区切りで与えられます。', ask: '空でない部分集合のOR(ビット和)として作れる相異なる値の個数を出力してください。', h1: '2^n通り試さなくてもよい。', h2: '「これまでに作れるORの集合」を持ち、新しい要素とのORを全部足して育てる。集合サイズはビット数に抑えられる。', ref: 'a=list(map(int,input().split()))\nall_=set()\nprev=set()\nfor x in a:\n    prev={p|x for p in prev}\n    prev.add(x)\n    all_|=prev\nprint(len(all_))', tip: '「iで終わる部分集合のOR集合」はORの単調性(ビットは増える一方)で高々ビット数個。指数の敵を単調性で斬る、集合DPの小さな傑作(LC 898の亜種)。', ins: ['1 2\n', '1 1 1\n', '1 2 4\n', '3 1\n', '0\n', '5 3 6\n'] })

t({ lv: 695, concept: '累積和: 同符号だけの区間の数', title: '符号が揃った区間を数える', tags: ['数学'], io: '0を含まない整数列が1行で空白区切りで与えられます。', ask: '全要素が正、または全要素が負の連続部分配列の個数を出力してください。', h1: '同符号が連続する塊(ラン)に分ける。', h2: '長さ L のランは L×(L+1)/2 個の区間を生む。', ref: 'a=list(map(int,input().split()))\ntotal=0\nrun=0\nprev=0\nfor x in a:\n    sgn=1 if x>0 else -1\n    if sgn==prev:\n        run+=1\n    else:\n        total+=run*(run+1)//2\n        run=1\n        prev=sgn\ntotal+=run*(run+1)//2\nprint(total)', tip: '「性質を満たす極大ラン」に切ってから区間数を公式で数える2段構え。性質を変えれば単調区間・同一値区間など何にでも化ける汎用の骨格。', ins: ['1 2 3\n', '1 -1 1\n', '-1 -2 -3 -4\n', '5\n', '1 2 -3 -4 5\n', '-1 1 -1 1\n'] })

t({ lv: 696, concept: '貪欲: 数直線の全点訪問最短', title: '全ての家を回る最短の移動距離', tags: ['貪欲', '数学'], io: '1行目に開始位置 s、2行目に訪ねる家の座標の列が与えられます。', ask: '数直線上を移動して全ての家を訪ねる(どこで終わってもよい)ときの、移動距離の合計の最小を出力してください。', h1: '結局「左端まで」と「右端まで」に行くかで決まる。', h2: '片側を先に往復してからもう片側へ行く。左往復か右往復かの2通りの小さい方。', ref: 's=int(input())\na=list(map(int,input().split()))\nlo=min(a+[s])\nhi=max(a+[s])\nL=s-lo\nR=hi-s\nprint(min(2*L+R,L+2*R))', tip: '「後で戻らない側を最後に回る」と往復が1回で済む。最適解の形を2候補に絞り切る、数直線の巡回問題の代表的な整理。', ins: ['0\n-3 5\n', '0\n1 2 3\n', '5\n1 2\n', '0\n-2 -7\n', '3\n-1 10\n', '0\n0\n'] })

t({ lv: 697, concept: '全探索: k個除いた最大間隔の最小化', title: '石をk個取り除いた最悪の跳び幅', tags: ['全探索'], io: '1行目に 川幅 L、石の数 n、取り除く数 k。2行目に石の位置(0とLの間、昇順)が与えられます。', ask: 'ちょうど k 個の石を取り除いたあと、岸(0とL)と残った石が作る隣接間隔の最大値を、取り除き方を工夫して最小にした値を出力してください。', h1: '取り除く組合せを全部試す。', h2: 'itertoolsのcombinationsで除く石を選び、残りの隣接差の最大を計算する。', ref: 'from itertools import combinations\nfirst=input().split()\nL,n,k=int(first[0]),int(first[1]),int(first[2])\nstones=list(map(int,input().split()))\nbest=None\nfor rm in combinations(range(n),k):\n    pts=[0]+[stones[i] for i in range(n) if i not in rm]+[L]\n    mx=max(pts[i+1]-pts[i] for i in range(len(pts)-1))\n    if best is None or mx<best:\n        best=mx\nprint(best)', tip: '除去で間隔は広がる一方なので「どれを犠牲にするか」の組合せ問題になる。nが大きいときは答えを二分探索して貪欲判定に切り替える。', ins: ['10 3 1\n2 5 8\n', '10 2 2\n3 7\n', '6 1 0\n3\n', '10 4 2\n1 2 8 9\n', '5 3 3\n1 2 3\n', '100 3 1\n20 50 80\n'] })

t({ lv: 698, concept: 'DP: 素数に分割する方法の数', title: '数字列を素数に切り分ける', tags: ['DP', '数論'], io: '数字だけの文字列が1行で与えられます。', ask: '文字列を連続した部分に切り、どの部分も(先頭の0を持たない)素数になるような切り方の数を出力してください。', h1: '位置 i までの切り方の数を dp で持つ。', h2: '最後の1片 s[j..i] が素数(かつ先頭が0でない)なら dp[j] を足す。', ref: 's=input()\nn=len(s)\ndef isp(x):\n    if x<2:\n        return False\n    i=2\n    while i*i<=x:\n        if x%i==0:\n            return False\n        i+=1\n    return True\ndp=[0]*(n+1)\ndp[0]=1\nfor i in range(1,n+1):\n    for j in range(max(0,i-4),i):\n        if s[j]!="0" or i-j==1:\n            if s[j]=="0":\n                continue\n            if isp(int(s[j:i])):\n                dp[i]+=dp[j]\nprint(dp[n])', tip: '単語分割DPの「辞書にあるか」を「素数か」に差し替えた形。片の長さを適度に制限すれば素数判定の回数も抑えられる。', ins: ['23\n', '113\n', '4\n', '3175\n', '11373\n', '22\n'] })

t({ lv: 699, concept: '配列: 斜めが揃った行列の判定', title: '斜めのラインが全部同じ値か', tags: ['配列'], io: '1行目に H W、続く H 行に行列が与えられます。', ask: '左上から右下へ向かう全ての斜めライン上で値が一定(テプリッツ行列)なら yes、そうでなければ no を出力してください。', h1: '各要素を左上の要素と比べる。', h2: 'g[i][j] と g[i−1][j−1] が全て等しければよい。', ref: 'h,w=map(int,input().split())\ng=[list(map(int,input().split())) for _ in range(h)]\nok=True\nfor i in range(1,h):\n    for j in range(1,w):\n        if g[i][j]!=g[i-1][j-1]:\n            ok=False\nprint("yes" if ok else "no")', tip: '「ライン単位」の性質は「隣接2点の関係」に還元すると走査1回で済む。テプリッツ行列は畳み込みの行列表現として信号処理の主役でもある。', ins: ['3 4\n1 2 3 4\n5 1 2 3\n9 5 1 2\n', '2 2\n1 2\n2 2\n', '1 3\n1 2 3\n', '3 3\n7 7 7\n7 7 7\n7 7 7\n', '2 3\n1 2 3\n4 1 2\n', '2 2\n5 3\n3 5\n'] })

t({ lv: 701, concept: '区間DP: 年数倍で売るワインの最大', title: 'ワインを端から売る最大売上', tags: ['区間DP', '再帰'], io: 'ワインの価値の列が1行で空白区切りで与えられます。毎年、列の左端か右端のどちらかを1本売ります。', ask: 'y 年目に売ったワインは「価値×y」の売上になります(1年目から)。総売上の最大を出力してください。', h1: '残っているのは常に連続した区間。', h2: '区間 [i,j] が残っているとき今が何年目かは自動的に決まる。左右どちらを売るかで再帰。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nmemo={}\ndef f(i,j):\n    if i>j:\n        return 0\n    if (i,j) in memo:\n        return memo[(i,j)]\n    y=n-(j-i)\n    r=max(a[i]*y+f(i+1,j),a[j]*y+f(i,j-1))\n    memo[(i,j)]=r\n    return r\nprint(f(0,n-1))', tip: '「経過年数を状態に持たない」のがポイントで、区間の長さから年が復元できる。冗長な状態を削ると2次元で収まる、状態設計の教材的な一問。', ins: ['4 1 2 3\n', '2 3 5 1 4\n', '5\n', '1 100\n', '3 3 3\n', '10 1 1 10\n'] })

t({ lv: 702, concept: '二点法: 併合して回文にする最小回数', title: '隣を足し合わせて回文を作る', tags: ['二点法', '貪欲'], io: '正整数列が1行で空白区切りで与えられます。1回の操作で隣接する2要素を足して1つにまとめられます。', ask: '列を回文にするための最小の操作回数を出力してください。', h1: '両端から比べる。等しければ両方を内側へ。', h2: '小さい側を隣と併合する(大きい側を崩すのは損)。', ref: 'a=list(map(int,input().split()))\ni,j=0,len(a)-1\ncnt=0\nwhile i<j:\n    if a[i]==a[j]:\n        i+=1\n        j-=1\n    elif a[i]<a[j]:\n        a[i+1]+=a[i]\n        i+=1\n        cnt+=1\n    else:\n        a[j-1]+=a[j]\n        j-=1\n        cnt+=1\nprint(cnt)', tip: '「小さい方を伸ばす」二点法貪欲は、和の単調性から最適性が証明できる。区間DPで書けば O(n²)、この貪欲なら O(n) で済む対比も面白い。', ins: ['1 2 3 1\n', '1 1 1\n', '1 4\n', '1 2 3 4\n', '5\n', '2 1 1 2\n'] })

t({ lv: 703, concept: '区間DP: 同じ数字の塊消しで得点最大', title: '同じ数字をまとめて消す最大得点', tags: ['区間DP', '再帰'], io: '数字(1〜9)の列が1行で空白区切りで与えられます(9個以下)。', ask: '連続した同じ数字 k 個をまとめて消すと k² 点もらえます(消えた後は左右が詰まる)。全て消すときの最大得点を出力してください。', h1: '右端の数字を「今すぐ消す」か「後で同じ数字と一緒に消す」か。', h2: '状態 (i, j, k)=「区間[i,j]の右に既に同じ数字がk個付いている」で再帰(remove boxes型)。', ref: 'import sys\nsys.setrecursionlimit(100000)\na=list(map(int,input().split()))\nmemo={}\ndef f(i,j,k):\n    if i>j:\n        return 0\n    key=(i,j,k)\n    if key in memo:\n        return memo[key]\n    jj,kk=j,k\n    while jj>i and a[jj-1]==a[jj]:\n        jj-=1\n        kk+=1\n    res=(kk+1)*(kk+1)+f(i,jj-1,0)\n    for m in range(i,jj):\n        if a[m]==a[jj]:\n            res=max(res,f(m+1,jj-1,0)+f(i,m,kk+1))\n    memo[key]=res\n    return res\nprint(f(0,len(a)-1,0))', tip: '「後で仲間と合流させる」選択を第3の状態kが担う、区間DPの最難関級(remove boxes)。k²という超加法的な得点が合流を促す構造になっている。', ins: ['1 1 1\n', '1 2 1\n', '1 3 2 2 2 3 4 3 1\n', '5\n', '1 2\n', '2 2 1 2 2\n'] })

t({ lv: 704, concept: 'スタック: 不正な括弧を除いた結果', title: '直せない括弧を消した残り', tags: ['スタック', '文字列'], io: '( と ) と英小文字からなる文字列が1行で与えられます。', ask: '対応の取れない括弧を最小個数だけ取り除いて正しい括弧列(文字はそのまま)にした結果を出力してください。除き方は「対応しない ) は左から順に、対応しない ( は右から順に消す」規則で一意に定めます(空になったら empty)。', h1: '左走査で余った ) の位置、右走査で余った ( の位置が分かる。', h2: '消す位置の集合を作ってから、残りを連結する。', ref: 's=input()\nremove=set()\nbal=0\nfor i,c in enumerate(s):\n    if c=="(":\n        bal+=1\n    elif c==")":\n        if bal>0:\n            bal-=1\n        else:\n            remove.add(i)\nbal=0\nfor i in range(len(s)-1,-1,-1):\n    c=s[i]\n    if c==")":\n        bal+=1\n    elif c=="(":\n        if bal>0:\n            bal-=1\n        else:\n            remove.add(i)\nres="".join(c for i,c in enumerate(s) if i not in remove)\nprint(res if res else "empty")', tip: '「個数」だけでなく「どれを消すか」まで構成する版。左右からの2走査で不正の位置が過不足なく特定できるのは、括弧のバランスが接頭辞量だから。', ins: ['a)b(c)d\n', '))((\n', '(a(b)\n', '()\n', ')(\n', 'x)\n'] })

t({ lv: 705, concept: '貪欲: 最大利益とその最小取引回数', title: '最大利益を最少の売買で', tags: ['貪欲'], io: '株価の列が1行で空白区切りで与えられます(同時に1株まで保有可、何度でも売買可)。', ask: '得られる利益の最大と、その利益を達成するための最小の取引回数(買って売って1回)を空白区切りで出力してください。', h1: '利益の最大は上り坂の合計。', h2: '取引回数を最小にするには「谷で買い、次の山まで持ち切って売る」。極大の上昇区間の本数を数える。', ref: 'a=list(map(int,input().split()))\nprofit=sum(max(0,a[i+1]-a[i]) for i in range(len(a)-1))\ncnt=0\ni=0\nn=len(a)\nwhile i<n-1:\n    while i<n-1 and a[i+1]<=a[i]:\n        i+=1\n    j=i\n    while j<n-1 and a[j+1]>=a[j]:\n        j+=1\n    if j>i:\n        cnt+=1\n    i=j\nprint(profit,cnt)', tip: '「毎日の上昇を刻む」解釈と「谷山でまとめる」解釈は利益が同じで回数が違う。最適解の同値な表現から目的に合う方を選ぶ、貪欲の応用問題。', ins: ['7 1 5 3 6 4\n', '1 2 3 4 5\n', '5 4 3 2 1\n', '3\n', '1 5 1 5 1 5\n', '2 2 2\n'] })

t({ lv: 706, concept: 'DP: 出席記録の数え上げ', title: '賞をもらえる出席パターンの数', tags: ['DP'], io: '日数 n が1行で与えられます。', ask: '各日の記録は P(出席)・L(遅刻)・A(欠席)のどれか。「Aが合計2回未満」かつ「Lが3日連続しない」記録は何通りあるかを出力してください。', h1: '状態は (Aの総数, 直近のLの連続数)。', h2: '2×3=6状態のDPを日数ぶん回す。', ref: 'n=int(input())\ndp={(0,0):1}\nfor _ in range(n):\n    nd={}\n    for (a,l),c in dp.items():\n        for ch in "PLA":\n            na,nl=a,0\n            if ch=="A":\n                na+=1\n                if na>1:\n                    continue\n            if ch=="L":\n                nl=l+1\n                if nl>2:\n                    continue\n            nd[(na,nl)]=nd.get((na,nl),0)+c\n    dp=nd\nprint(sum(dp.values()))', tip: '複数の制約(総数の上限・連続の上限)は状態の直積で共存させる。状態数が定数なら日数が伸びても線形、が有限状態DPの強み。', ins: ['1\n', '2\n', '3\n', '4\n', '5\n', '10\n'] })

t({ lv: 707, concept: 'シミュレーション: 移動平均の交差回数', title: '短期線と長期線のクロス回数', tags: ['シミュレーション'], io: '1行目に窓幅 a b (a<b)、2行目に価格の列が与えられます。', ask: '短期(幅a)と長期(幅b)の移動平均を各日について計算し、両方が定義される範囲で「差の符号が入れ替わった」回数を出力してください(差が0の日は無視して直前の符号を引き継ぐ)。', h1: '移動平均の比較は割り算せずにできる。', h2: '和どうしをクロス乗算(Sa×b と Sb×a)で比べれば整数のまま符号が分かる。', ref: 'a,b=map(int,input().split())\np=list(map(int,input().split()))\nn=len(p)\ndef sums(w):\n    out={}\n    s=sum(p[:w])\n    out[w-1]=s\n    for i in range(w,n):\n        s+=p[i]-p[i-w]\n        out[i]=s\n    return out\nSa=sums(a)\nSb=sums(b)\nprev=0\ncnt=0\nfor i in range(b-1,n):\n    d=Sa[i]*b-Sb[i]*a\n    sgn=(d>0)-(d<0)\n    if sgn!=0:\n        if prev!=0 and sgn!=prev:\n            cnt+=1\n        prev=sgn\nprint(cnt)', tip: 'ゴールデンクロスの検出そのもの。浮動小数の平均を比較せず「和×窓幅」の整数比較にすれば、誤差による偽クロスが原理的に起きない。', ins: ['1 2\n1 2 1 2 1\n', '1 2\n1 2 3 4\n', '2 3\n3 1 4 1 5 9 2 6\n', '1 3\n5 5 5 5\n', '1 2\n2 1 2 1 2 1\n', '2 4\n1 2 3 4 3 2 1 2 3 4\n'] })

t({ lv: 708, concept: '文字列: ルック・アンド・セイ数列', title: '前の項を読み上げて作る数列', tags: ['文字列', 'シミュレーション'], io: '1行目に開始の数字列、2行目に回数 k が与えられます。', ask: '「前の項を左から読み上げる」(例 1211 → 1が1個,2が1個,1が2個 → 111221)操作を k 回行った結果を出力してください。', h1: '連続する同じ数字の塊に分ける。', h2: '各塊を「個数+数字」に置き換える。ランレングス符号化の繰り返し。', ref: 's=input()\nk=int(input())\nfor _ in range(k):\n    res=[]\n    i=0\n    while i<len(s):\n        j=i\n        while j<len(s) and s[j]==s[i]:\n            j+=1\n        res.append(str(j-i))\n        res.append(s[i])\n        i=j\n    s="".join(res)\nprint(s)', tip: 'コンウェイが解析した有名な数列で、長さの増加率は「コンウェイ定数」1.3035…に収束する。数字の4以上が(1から始めると)決して現れない性質も証明されている。', ins: ['1\n1\n', '1\n4\n', '1211\n1\n', '3\n2\n', '22\n3\n', '1\n6\n'] })

t({ lv: 709, concept: '文字列: 部分列に現れない最短の長さ', title: '部分列として作れない最短の文字列', tags: ['文字列', '貪欲'], io: '1行目にアルファベットの種類数 k(最初のk文字 a,b,… を使う)、2行目に文字列 S が与えられます。', ask: '長さ最小で「S の部分列として現れない」k種の文字だけからなる文字列の長さを出力してください。', h1: 'どんな1文字も部分列に現れるなら答えは2以上。', h2: 'Sを走査してk種類すべて集まるたびにカウントを増やす(完全アルファベットの回数+1が答え)。', ref: 'k=int(input())\ns=input()\nletters=set(chr(97+i) for i in range(k))\nseen=set()\nrounds=0\nfor c in s:\n    if c in letters:\n        seen.add(c)\n        if len(seen)==k:\n            rounds+=1\n            seen=set()\nprint(rounds+1)', tip: '長さLの全列が部分列に現れる ⇔ 「全種類が揃うブロック」がL回取れる、という同値変形が核心。貪欲なブロック分割が最短反例の長さを与える。', ins: ['2\nabab\n', '1\naaa\n', '2\naabb\n', '3\nabcabc\n', '2\nb\n', '3\ncba\n'] })

t({ lv: 710, concept: '貪欲: 全要素を相異なるにする最小加算', title: '重複を+1で解消する最小コスト', tags: ['貪欲', 'ソート'], io: '正整数の列が1行で空白区切りで与えられます。1回の操作でどれか1つを+1できます。', ask: '全要素を相異なる値にするための最小の操作回数を出力してください。', h1: 'ソートすると「前の値+1未満なら持ち上げる」だけになる。', h2: '各要素を max(自分, 前の確定値+1) に引き上げ、差を合計する。', ref: 'a=sorted(map(int,input().split()))\ncost=0\nprev=a[0]\nfor x in a[1:]:\n    if x<=prev:\n        cost+=prev+1-x\n        prev=prev+1\n    else:\n        prev=x\nprint(cost)', tip: 'ソート後の1パス貪欲で最適になるのは「どの重複も結局どこかへ持ち上げるしかない」から。カウンタで空き値へ流し込むO(n+max)版もある。', ins: ['1 2 2\n', '3 2 1 2 1 7\n', '1 1 1\n', '5\n', '2 2 2 2\n', '1 2 3\n'] })

t({ lv: 711, concept: 'DP: 塗り直し最小で隣接違いに', title: '柵の塗り直し最小本数', tags: ['DP'], io: '1行目に色数 k、2行目に現在の柵の色(1〜k)の列が与えられます (k≥2)。', ask: '隣どうしが必ず違う色になるように塗り直す本数の最小を出力してください。', h1: '各柵を「今の色のまま」か「別の色」にするかのDP。', h2: 'dp[i][c] を i 本目を色 c にする最小塗り直し数とする。k が大きいときは最小と2番目の最小だけ持てばよい。', ref: 'k=int(input())\na=list(map(int,input().split()))\nn=len(a)\nINF=10**9\ndp=[0 if c+1==a[0] else 1 for c in range(k)]\nfor i in range(1,n):\n    m1=min(dp)\n    i1=dp.index(m1)\n    m2=min(dp[c] for c in range(k) if c!=i1) if k>1 else INF\n    nd=[0]*k\n    for c in range(k):\n        best=m2 if c==i1 else m1\n        nd[c]=best+(0 if c+1==a[i] else 1)\n    dp=nd\nprint(min(dp))', tip: '「前の行の最小と次点だけ覚える」テクニックで色数kに対してO(nk)。塗り替え問題は“作る”と“直す”でコスト定義が変わるだけで骨格は同じ。', ins: ['3\n1 1 1\n', '2\n1 2 1\n', '3\n2 2 2 2\n', '2\n1 1\n', '4\n1 2 3 4\n', '3\n1 1 2 2 3 3\n'] })

t({ lv: 712, concept: '数え上げ: ちょうどc色使う列の塗り方', title: '全色を使い切る柵の塗り方', tags: ['数学'], io: 'n c が空白区切りで1行で与えられます(柵n本、色c種)。', ask: '隣どうしが違う色で、かつ c 色すべてを少なくとも1回使う塗り方の数を出力してください。', h1: '「c色以下で塗る」なら c×(c−1)^(n−1) 通り。', h2: '使う色集合のサイズで包除原理: Σ (−1)^j C(c,j) (c−j)(c−j−1)^(n−1)。', ref: 'from math import comb\nn,c=map(int,input().split())\ntotal=0\nfor j in range(c):\n    k=c-j\n    ways=k*(k-1)**(n-1) if n>=1 else 0\n    total+=(-1)**j*comb(c,j)*ways\nprint(total)', tip: '「ちょうど」は「以下」の包除で作るのが数え上げの王道。全射の数え上げ(スターリング数×階乗)と同じ構図が塗り分けにも現れる。', ins: ['3 2\n', '3 3\n', '2 2\n', '4 3\n', '2 3\n', '5 2\n'] })

t({ lv: 713, concept: 'スタック: 隣どうし同じ文字の全消し', title: 'ペア消しの最終結果', tags: ['スタック'], io: '英小文字の文字列が1行で与えられます。', ask: '隣り合う同じ2文字を消す操作を、できなくなるまで繰り返した最終結果を出力してください(空になったら empty)。', h1: '消えた後にまた同じペアができる連鎖をどう処理するか。', h2: 'スタックに積み、天辺と同じ文字が来たら積まずに天辺を捨てる。1回の走査で連鎖まで処理できる。', ref: 's=input()\nst=[]\nfor c in s:\n    if st and st[-1]==c:\n        st.pop()\n    else:\n        st.append(c)\nprint("".join(st) if st else "empty")', tip: '「消して詰めて再スキャン」の素朴な繰り返しはO(n²)。スタックは“過去の消し残し”を保持しているので連鎖消去が1パスに畳める。', ins: ['abbaca\n', 'azxxzy\n', 'aabb\n', 'abc\n', 'aa\n', 'abba\n'] })

t({ lv: 714, concept: '数え上げ: サイコロの面の塗り分け', title: '回して同じなら同一視する立方体の塗り', tags: ['数学'], io: '色の種類数 k が1行で与えられます。', ask: '立方体の6面を k 色で塗る方法のうち、回転して一致するものを同一視した数を出力してください。', h1: '回転群(24通り)ごとに「固定される塗り方」を数える(バーンサイドの補題)。', h2: '恒等1個: k^6、面軸90°系6個: k^3、面軸180°系3個: k^4、頂点軸120°系8個: k^2、辺軸180°系6個: k^3。平均を取る。', ref: 'k=int(input())\nprint((k**6+3*k**4+12*k**3+8*k**2)//24)', tip: 'バーンサイドの補題「軌道数=固定点数の平均」の教科書的名品。k=2で10通り、k=6で30通り(全色違いのサイコロは30種類)になる。', ins: ['1\n', '2\n', '3\n', '6\n', '4\n', '10\n'] })

t({ lv: 715, concept: 'BFS: 蛇と梯子の最小手数', title: 'すごろくを上がる最小サイコロ回数', tags: ['BFS'], io: '1行目にマス数 n とワープ数 w、続く w 行に「a b」(マスaに止まると必ずbへ移動)が与えられます。', ask: 'マス1から出発し、毎回1〜6の好きな目で進める(nを超える手は不可)とき、マスnに着く最小手数を出力してください。到達不能なら -1。', h1: '各マスを頂点、サイコロの一手を辺と見なす。', h2: '止まったマスにワープがあれば強制移動してからBFS。', ref: 'from collections import deque\nn,w=map(int,input().split())\nwarp={}\nfor _ in range(w):\n    a,b=map(int,input().split())\n    warp[a]=b\ndist={1:0}\nq=deque([1])\nans=-1\nwhile q:\n    x=q.popleft()\n    if x==n:\n        ans=dist[x]\n        break\n    for d in range(1,7):\n        y=x+d\n        if y>n:\n            continue\n        y=warp.get(y,y)\n        if y not in dist:\n            dist[y]=dist[x]+1\n            q.append(y)\nprint(ans)', tip: '蛇も梯子も「そのマスに実在しない」と考え、遷移先を書き換えるだけでBFSの骨格は不変。盤面ゲームの最短手数はほぼこの型に落ちる。', ins: ['10 0\n', '10 1\n2 9\n', '10 1\n7 2\n', '8 2\n3 7\n4 2\n', '2 0\n', '15 2\n5 14\n10 3\n'] })

export const CATALOG = TASKS
