// 生成タスク 第90波：各レベル3問化フェーズ(17)。lv825〜849, 851〜874 の薄い49段に3問目を追加。
// クエリ応用/数論後半帯。クラスタ3問まで可・言い換え水増し禁止。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 825, concept: 'ヒープ: 優先度と到着順の診察順', title: '救急外来の呼び出し順', tags: ['ヒープ'], io: '1行目に患者数 n、続く n 行に到着順に優先度(小さいほど重症)が与えられます。', ask: '優先度の小さい順(同じ優先度なら到着が早い順)に診察するときの、患者番号(到着順の番号)の列を空白区切りで出力してください。', h1: '(優先度, 到着番号)のタプルでソートかヒープ。', h2: 'タプルの辞書順比較がタイブレークを自動処理。', ref: 'n=int(input())\nps=[(int(input()),i+1) for i in range(n)]\nps.sort()\nprint(" ".join(str(i) for p,i in ps))', tip: '優先度キューの実務での鉄則「同点はFIFO」をタプル比較で実現する型。heapqに(priority, seq, item)を入れる3要素タプルの慣用は、この問題の直系の子孫。', ins: ['3\n2\n1\n2\n', '1\n5\n', '4\n3\n3\n1\n2\n', '2\n1\n1\n', '5\n5\n4\n3\n2\n1\n', '3\n1\n1\n1\n'] })

t({ lv: 826, concept: 'シミュレーション: 指数バックオフの合計待ち時間', title: 'リトライは倍々で待つ', tags: ['シミュレーション'], io: '1行目に初回の待ち時間 b と リトライ回数 n が与えられます。', ask: 'リトライのたびに待ち時間が2倍になる(初回b、次2b、…)とき、n 回のリトライの待ち時間の合計を出力してください。', h1: '等比数列の和。', h2: 'b×(2^n−1)。', ref: 'b,n=map(int,input().split())\nprint(b*((1<<n)-1))', tip: 'ネットワーク再試行の標準戦略(exponential backoff)の待ち時間勘定。2^n−1が「n枚の円盤のハノイ」や「全部分集合の数−1」と同じ顔で現れる、等比和の遍在。', ins: ['1 3\n', '2 1\n', '100 4\n', '1 10\n', '5 0\n', '3 5\n'] })

t({ lv: 827, concept: '窓: 記録更新した窓の数', title: '売上新記録の回数', tags: ['窓'], io: '1行目に k、2行目に整数列(長さk以上)が与えられます。', ask: '長さ k の窓を左から順に見て、窓の合計が「それまでの窓の合計の最大」を厳密に超えた回数を出力してください(最初の窓は数えません)。', h1: '窓和の差分更新+走行最大。', h2: '更新のたびに記録を塗り替える。', ref: 'k=int(input())\na=list(map(int,input().split()))\ns=sum(a[:k])\nbest=s\ncnt=0\nfor i in range(k,len(a)):\n    s+=a[i]-a[i-k]\n    if s>best:\n        best=s\n        cnt+=1\nprint(cnt)', tip: '移動合計と記録更新(running max)の合成で、「今四半期は過去最高」のニュースを数える計算。2つの既出部品を直列に繋ぐだけで新しい統計が生まれる。', ins: ['2\n1 2 3 4\n', '1\n5 4 3\n', '3\n1 1 1 1\n', '2\n5 1 5 1\n', '2\n1 1 2 3\n', '1\n2 2 2\n'] })

t({ lv: 828, concept: 'ハッシュ: 頻度トップkの値の一覧', title: '人気ランキングの上位k', tags: ['ハッシュ'], io: '1行目に k、2行目に整数列が与えられます(相異なる値はk種類以上)。', ask: '出現回数の多い順(同数なら値の小さい順)に k 個の値を空白区切りで出力してください。', h1: '上位kの合計(同レベル既出)の実体版。', h2: '(−回数, 値)でソートして先頭k個。', ref: 'k=int(input())\nfrom collections import Counter\nc=Counter(map(int,input().split()))\nks=sorted(c,key=lambda v:(-c[v],v))\nprint(" ".join(map(str,ks[:k])))', tip: 'トレンドワード抽出の最小形。全ソートO(m log m)の代わりにヒープでO(m log k)、さらにバケツ(頻度別)でO(m)まで落ちる、top-k問題の階段の1段目。', ins: ['2\n1 1 2 2 3\n', '1\n5 5 4\n', '3\n1 2 3\n', '2\n7 7 7 8 8 9\n', '1\n3 1 3 1\n', '2\n4 4 5 5\n'] })

t({ lv: 829, concept: 'スタック: 左で最初に大きい値の一覧', title: '前方の壁の高さ', tags: ['スタック'], io: '整数列が1行で空白区切りで与えられます。', ask: '各要素について「左方向で最初に現れる自分より大きい値」を求め、無ければ −1 として空白区切りで出力してください。', h1: '左で最初に小さい値(既出)の鏡像。', h2: '自分以下をポップした後のスタックの頭。', ref: 'a=list(map(int,input().split()))\nst=[]\nout=[]\nfor x in a:\n    while st and st[-1]<=x:\n        st.pop()\n    out.append(st[-1] if st else -1)\n    st.append(x)\nprint(" ".join(map(str,out)))', tip: '単調スタック4方位(左右×大小)の最後のピース。株価スパン(既出)はこの「左で最初に大きい」までの距離そのもので、部品の対応表が完成する。', ins: ['3 1 4 2\n', '1 2 3\n', '5 4 3\n', '2 2\n', '1 5 2 4\n', '9\n'] })

t({ lv: 830, concept: 'シミュレーション: メモリキー付き電卓', title: 'M+の記憶術', tags: ['シミュレーション'], io: '1行目に操作数 q、続く q 行に「M+ x」(メモリにxを足す)、「M- x」(引く)、「MR」(メモリを出力)、「MC」(メモリを0に) が与えられます。', ask: '各 MR に対して現在のメモリ値を1行ずつ出力してください(初期値0)。', h1: '状態変数1つのシミュレーション。', h2: 'コマンドで分岐するだけ。', ref: 'q=int(input())\nmem=0\nfor _ in range(q):\n    parts=input().split()\n    if parts[0]=="M+":\n        mem+=int(parts[1])\n    elif parts[0]=="M-":\n        mem-=int(parts[1])\n    elif parts[0]=="MR":\n        print(mem)\n    else:\n        mem=0', tip: '実物の電卓のM+/M-/MR/MCの仕様の再現で、レジスタ1本の状態機械。仕様書(ボタンの意味)をそのまま分岐に写す「翻訳としてのプログラミング」の練習。', ins: ['4\nM+ 5\nM+ 3\nMR\nMC\n', '3\nMR\nM+ 7\nMR\n', '5\nM+ 10\nM- 4\nMR\nM- 6\nMR\n', '2\nMC\nMR\n', '4\nM- 5\nMR\nMC\nMR\n', '3\nM+ 1\nMC\nMR\n'] })

t({ lv: 831, concept: 'クエリ: 区間のしっぽの最高の伸び', title: '締めくくりの追い込み', tags: ['クエリ'], io: '1行目に n q、2行目に長さ n の列、続く q 行に区間 l r が与えられます。', ask: '各区間について「区間の末尾で終わる連続部分列の和の最大」(最大接尾辞和、空は不可)を1行ずつ出力してください。', h1: '頭からの最高の伸び(同レベル既出)の鏡像。', h2: '後ろから足しながらの最大。', ref: 'n,q=map(int,input().split())\na=list(map(int,input().split()))\nfor _ in range(q):\n    l,r=map(int,input().split())\n    s=0\n    best=None\n    for i in range(r-1,l-2,-1):\n        s+=a[i]\n        if best is None or s>best:\n            best=s\n    print(best)', tip: 'セグ木で最大部分和(既出)を解くとき、ノードに持つ4点セット(和・接頭辞max・接尾辞max・部分和max)の1つがこれ。部品を単独の問題として素振りする趣向。', ins: ['3 2\n1 -2 3\n1 3\n1 2\n', '2 1\n-1 5\n1 2\n', '4 2\n2 -1 2 -3\n1 4\n2 3\n', '1 1\n-7\n1 1\n', '5 1\n1 2 3 4 5\n2 4\n', '3 1\n-1 -2 -3\n1 3\n'] })

t({ lv: 832, concept: 'スタック: アンドゥつき文字列作成', title: '書いては戻すエディタ', tags: ['スタック', '文字列'], io: '1行目に操作数 q、続く q 行に「T s」(文字列sを末尾に追加) か「U」(直前の追加を取り消す) が与えられます。', ask: '全操作後の文字列を出力してください(空なら - を出力)。', h1: '加算器のアンドゥ(同レベル既出)の文字列版。', h2: '追加した長さの履歴をスタックに積む。', ref: 'q=int(input())\ns=""\nhist=[]\nfor _ in range(q):\n    parts=input().split()\n    if parts[0]=="T":\n        s+=parts[1]\n        hist.append(len(parts[1]))\n    else:\n        L=hist.pop()\n        s=s[:-L]\nprint(s if s else "-")', tip: 'アンドゥは「操作の逆」を覚えるのではなく「元に戻すのに必要な最小情報(ここでは長さ)」を積むのが軽量実装のコツ。エディタのコマンドパターンの縮図。', ins: ['3\nT ab\nT cd\nU\n', '2\nT xyz\nU\n', '4\nT a\nT b\nU\nT c\n', '1\nT hello\n', '5\nT ab\nU\nT cd\nT ef\nU\n', '3\nT a\nU\nT b\n'] })

t({ lv: 833, concept: '窓: 窓和の最大と最小の差', title: '好調期と不調期の落差', tags: ['窓'], io: '1行目に k、2行目に整数列(長さk以上)が与えられます。', ask: '長さ k の全ての窓の合計のうち、最大と最小の差を出力してください。', h1: '窓和の列を差分更新で作る。', h2: 'maxとminを同時に追う。', ref: 'k=int(input())\na=list(map(int,input().split()))\ns=sum(a[:k])\nmx=mn=s\nfor i in range(k,len(a)):\n    s+=a[i]-a[i-k]\n    if s>mx:\n        mx=s\n    if s<mn:\n        mn=s\nprint(mx-mn)', tip: '移動合計の振れ幅は季節変動の粗い指標。窓和の列(既出)を作ってからmax−minを取る2段でも書けるが、1パスで両方追えばメモリO(1)で済む。', ins: ['2\n1 2 3 4\n', '1\n5 1 3\n', '3\n1 1 1 1\n', '2\n5 -5 5\n', '2\n0 0 0\n', '3\n1 9 1 9 1\n'] })

t({ lv: 834, concept: 'いもす: 1枚だけの部分の面積', title: '一枚きりの領域', tags: ['いもす', 'グリッド'], io: '1行目に紙の枚数 n、続く n 行に軸に平行な長方形「x1 y1 x2 y2」(左下と右上、[x1,x2)×[y1,y2))が与えられます。', ask: 'ちょうど1枚の紙だけに覆われている部分の面積を出力してください。', h1: '全部重なる面積(同レベル既出)の相方。', h2: '2次元いもすで各マスの枚数を数え、1のマスを数える。', ref: 'n=int(input())\nrects=[tuple(map(int,input().split())) for _ in range(n)]\nmx=max(r[2] for r in rects)\nmy=max(r[3] for r in rects)\ng=[[0]*(my+2) for _ in range(mx+2)]\nfor x1,y1,x2,y2 in rects:\n    g[x1][y1]+=1\n    g[x1][y2]-=1\n    g[x2][y1]-=1\n    g[x2][y2]+=1\nfor x in range(mx+1):\n    for y in range(1,my+1):\n        g[x][y]+=g[x][y-1]\nfor y in range(my+1):\n    for x in range(1,mx+1):\n        g[x][y]+=g[x-1][y]\nprint(sum(1 for x in range(mx+1) for y in range(my+1) if g[x][y]==1))', tip: '1次元いもすの「ちょうどk重」の2次元版で、四隅への±1が2次元差分の心臓部。累積を2方向に2回かける手順は、矩形和の前計算のちょうど逆再生になっている。', ins: ['2\n0 0 2 2\n1 1 3 3\n', '1\n0 0 3 2\n', '2\n0 0 1 1\n0 0 1 1\n', '2\n0 0 2 1\n2 0 4 1\n', '3\n0 0 3 3\n1 1 2 2\n0 0 1 1\n', '2\n0 0 4 4\n1 1 3 3\n'] })

t({ lv: 835, concept: 'リスト: 底値を更新した回数', title: '最安値の記録更新', tags: ['リスト'], io: '整数列が1行で空白区切りで与えられます。', ask: '先頭から見ていき「それまでの最小値を厳密に下回った」回数を出力してください(先頭の要素は数えません)。', h1: '走行最小を持ち回る。', h2: '更新の瞬間だけカウント。', ref: 'a=list(map(int,input().split()))\nlo=a[0]\ncnt=0\nfor x in a[1:]:\n    if x<lo:\n        lo=x\n        cnt+=1\nprint(cnt)', tip: 'ランダムな並びでの記録更新回数の期待値は 1+1/2+…+1/n−1 (調和数)にしかならない、という美しい確率の定理の実験装置でもある。', ins: ['5 3 4 2 1\n', '1 2 3\n', '5\n', '3 3 3\n', '9 8 7 6\n', '2 5 1 7 0\n'] })

t({ lv: 836, concept: '数え上げ: 併合手順の総数', title: '合体の段取りは何通り', tags: ['数え上げ'], io: '塊の個数 n が1行で与えられます。', ask: 'n 個の塊から毎回好きな2つを選んで1つに併合し、1個になるまで続けるときの手順の総数(選んだペアの列として区別)を出力してください。', h1: '各ステップで選べるペア数の積。', h2: 'C(n,2)×C(n−1,2)×…×C(2,2)。', ref: 'n=int(input())\nans=1\nfor k in range(n,1,-1):\n    ans*=k*(k-1)//2\nprint(ans)', tip: '積の各因子が「その瞬間の選択肢」という積の法則の直用。n!(n−1)!/2^(n−1) という閉形式に整理でき、系統樹(進化の木)の数え上げにも同じ形が現れる。', ins: ['2\n', '3\n', '4\n', '1\n', '5\n', '6\n'] })

t({ lv: 837, concept: '統計: 箱ひげ図の外れ値の数', title: 'ひげの外に出た点', tags: ['統計'], io: '整数列(4個以上)が1行で空白区切りで与えられます。', ask: 'ソート後の位置 ⌈n/4⌉ 番目を Q1、⌈3n/4⌉ 番目を Q3 (1始まり)とし、IQR=Q3−Q1 として、Q1−1.5×IQR 未満または Q3+1.5×IQR 超の値の個数を出力してください。', h1: 'IQR(同レベル既出)の応用。', h2: '1.5倍の比較は2倍して整数のまま(2(Q1−x)>3IQR)。', ref: 'import math\na=sorted(map(int,input().split()))\nn=len(a)\nq1=a[math.ceil(n/4)-1]\nq3=a[math.ceil(3*n/4)-1]\niqr=q3-q1\nprint(sum(1 for x in a if 2*(q1-x)>3*iqr or 2*(x-q3)>3*iqr))', tip: '「1.5×IQRルール」は箱ひげ図の標準の外れ値基準(テューキー)。1.5倍を整数比較に直す2倍3倍のトリックで、浮動小数を一度も触らずに済む。', ins: ['1 2 3 4 100\n', '1 2 3 4\n', '10 12 11 13 12 50\n', '1 1 1 1 1 1 1 1\n', '-50 1 2 3 4 5 6 7\n', '5 6 7 8\n'] })

t({ lv: 838, concept: 'シミュレーション: 区間コピーを重ねた結果', title: 'コピペを繰り返した紙面', tags: ['シミュレーション'], io: '1行目に n q、2行目に長さ n の列、続く q 行に「l r d」(その時点の a[l..r] を位置 d 以降に上書きコピー。はみ出さない入力のみ)が与えられます。', ask: '全操作後の列を空白区切りで出力してください。', h1: 'コピー元を先に控える(スナップショット)。', h2: 'スライスを変数に取ってから代入。', ref: 'n,q=map(int,input().split())\na=input().split()\nfor _ in range(q):\n    l,r,d=map(int,input().split())\n    seg=a[l-1:r]\n    a[d-1:d-1+len(seg)]=seg\nprint(" ".join(a))', tip: 'コピー元と先が重なるとき、控えを取らない実装は自己上書きで壊れる——memmoveとmemcpyの違いとして知られる古典的な罠を、スライスの複製が自然に回避する。', ins: ['4 1\n1 2 3 4\n1 2 3\n', '3 1\n5 6 7\n3 3 1\n', '5 2\n1 2 3 4 5\n1 3 3\n4 5 1\n', '2 1\n9 8\n2 2 1\n', '4 2\n1 1 2 2\n3 4 1\n1 2 3\n', '3 0\n4 5 6\n'] })

t({ lv: 839, concept: 'グラフ: 隣接行列の友達の友達の数', title: '2ステップで届く知り合い', tags: ['グラフ', '行列'], io: '1行目に n、2行目に対象の人 v、続く n 行に n×n の隣接行列(無向、対角0)が与えられます。', ask: 'v の「友達の友達」(距離がちょうど2の人)の人数を出力してください。', h1: '友達の友達の集合から、自分と直接の友達を除く。', h2: '集合演算で書ける。', ref: 'n=int(input())\nv=int(input())\nA=[list(map(int,input().split())) for _ in range(n)]\nfriends={j for j in range(n) if A[v-1][j]==1}\nfof=set()\nfor f in friends:\n    for j in range(n):\n        if A[f][j]==1:\n            fof.add(j)\nfof-=friends\nfof.discard(v-1)\nprint(len(fof))', tip: '隣接行列の2乗の(v,j)成分が「2歩の経路数」で、この問題はその非ゼロ判定から直接・自分を除いたもの。SNSの「友達かも」候補数の数理そのもの。', ins: ['3\n1\n0 1 0\n1 0 1\n0 1 0\n', '2\n1\n0 1\n1 0\n', '4\n1\n0 1 0 0\n1 0 1 1\n0 1 0 0\n0 1 0 0\n', '3\n2\n0 1 1\n1 0 1\n1 1 0\n', '4\n4\n0 1 0 0\n1 0 1 0\n0 1 0 1\n0 0 1 0\n', '3\n1\n0 0 0\n0 0 1\n0 1 0\n'] })

t({ lv: 840, concept: 'クエリ: 区間最小とその最右の位置', title: '最後に現れた最小値', tags: ['クエリ'], io: '1行目に n q、2行目に長さ n の列、続く q 行に区間 l r が与えられます。', ask: '各区間の最小値と、その最小値が現れる最も右の位置(1始まり)を「値 位置」で1行ずつ出力してください。', h1: '最大と最左(同レベル既出)の対角の鏡像。', h2: '逆順走査か、min+右からのindex探し。', ref: 'n,q=map(int,input().split())\na=list(map(int,input().split()))\nfor _ in range(q):\n    l,r=map(int,input().split())\n    seg=a[l-1:r]\n    m=min(seg)\n    pos=r-1-seg[::-1].index(m)\n    print(m,pos+1)', tip: 'タイブレークの向き(最左/最右)はセグメント木のマージで「どちらの子を優先するか」の1行に対応する。逆順スライスのindexで最右を取る小技も覚えておくと速い。', ins: ['4 2\n3 1 4 1\n1 4\n2 3\n', '2 1\n7 7\n1 2\n', '3 2\n1 2 3\n2 3\n1 1\n', '1 1\n9\n1 1\n', '5 2\n5 1 5 1 5\n2 4\n1 5\n', '3 1\n2 9 2\n1 3\n'] })

t({ lv: 841, concept: '二分探索: 合格ライン別の人数の一覧', title: 'ボーダーを動かして数える', tags: ['二分探索'], io: '1行目に得点の列、2行目に合格ラインの候補の列が与えられます。', ask: '各ラインについて「そのライン以上の得点の人数」を順に空白区切りで出力してください。', h1: 'ソートしてbisectで一撃。', h2: 'n − bisect_left(ソート済み, ライン)。', ref: 'import bisect\na=sorted(map(int,input().split()))\nqs=list(map(int,input().split()))\nn=len(a)\nprint(" ".join(str(n-bisect.bisect_left(a,q)) for q in qs))', tip: '合格ラインを動かしながら人数を見る操作は、累積分布関数(CDF)の読み取りそのもの。1回のソートで全クエリがO(log n)になる「前処理の償却」の実感が得られる。', ins: ['50 80 70\n60 80\n', '10 20 30\n25\n', '5 5 5\n5 6\n', '90\n100 90 80\n', '1 2 3 4 5\n3\n', '40 60\n50 40 70\n'] })

t({ lv: 842, concept: 'クエリ: 区間の積の符号', title: 'プラスかマイナスかゼロか', tags: ['クエリ'], io: '1行目に n q、2行目に長さ n の整数列、続く q 行に区間 l r が与えられます。', ask: '各区間の要素の積の符号を、正なら +、負なら -、0なら 0 として1行ずつ出力してください。', h1: '実際に掛けるとオーバーフローの世界では破綻する(Pythonでは遅くなる)。', h2: '0の有無と負の個数の偶奇だけで決まる。', ref: 'n,q=map(int,input().split())\na=list(map(int,input().split()))\nfor _ in range(q):\n    l,r=map(int,input().split())\n    seg=a[l-1:r]\n    if 0 in seg:\n        print(0)\n    elif sum(1 for x in seg if x<0)%2==1:\n        print("-")\n    else:\n        print("+")', tip: '積の符号は「0の個数」と「負の個数の偶奇」の2つの累積和で前計算できる——値そのものを持たない符号の代数が、巨大数の積を一切計算せずに答えを出す。', ins: ['3 2\n1 -2 3\n1 3\n2 2\n', '2 1\n0 5\n1 2\n', '4 2\n-1 -1 -1 2\n1 3\n1 4\n', '1 1\n-7\n1 1\n', '5 2\n1 2 0 -1 -1\n4 5\n1 5\n', '3 1\n2 3 4\n1 3\n'] })

t({ lv: 843, concept: '窓: 各窓の値域の最小', title: '一番おだやかな窓', tags: ['窓'], io: '1行目に k、2行目に整数列(長さk以上)が与えられます。', ask: '長さ k の窓のうち「最大−最小」が最小になる値を出力してください。', h1: '値域の最大(同レベル既出)の鏡像。', h2: '窓ごとに range を計算してmin。', ref: 'k=int(input())\na=list(map(int,input().split()))\nprint(min(max(a[i:i+k])-min(a[i:i+k]) for i in range(len(a)-k+1)))', tip: '最も安定していた期間の検出で、ボラティリティ最小の窓を探す金融の実務クエリ。デック2本の高速化は最大版と全く同じに使い回せる。', ins: ['2\n1 3 2\n', '3\n1 2 3\n', '1\n4 5\n', '2\n5 5 5\n', '3\n4 1 7 2\n', '2\n10 1 10\n'] })

t({ lv: 844, concept: 'リスト: 右にある大きい要素の数の一覧', title: '後方の格上を数える', tags: ['リスト'], io: '整数列が1行で空白区切りで与えられます。', ask: '各要素について「自分より右にある、自分より大きい要素の個数」を空白区切りで出力してください。', h1: '右の小さい要素の一覧(既出)の鏡像。', h2: '総当たりが基準解。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nprint(" ".join(str(sum(1 for j in range(i+1,n) if a[j]>a[i])) for i in range(n)))', tip: 'この一覧の総和は「非転倒ペア(同値を除く)」の数で、転倒数と足し合わせて同値対の検算ができる。BITを値の大きい方から流せばO(n log n)になる。', ins: ['3 1 2\n', '1 2 3\n', '3 2 1\n', '5\n', '2 2 1\n', '1 3 2 4\n'] })

t({ lv: 845, concept: 'クエリ: 一番右の空きはどこか', title: '最後尾の空席案内', tags: ['クエリ'], io: '1行目に席数 n と操作数 q、続く q 行に「U i」(席iを埋める)、「F i」(席iを空ける)、「Q」(最も右の空き席を出力) が与えられます。', ask: '各 Q に対して最も右の空き席の番号を1行ずつ出力してください(空きが無ければ none)。', h1: '最左の空き(同レベル既出)の鏡像。', h2: '素朴に右から走査。', ref: 'n,q=map(int,input().split())\nseat=[False]*(n+1)\nfor _ in range(q):\n    parts=input().split()\n    if parts[0]=="U":\n        seat[int(parts[1])]=True\n    elif parts[0]=="F":\n        seat[int(parts[1])]=False\n    else:\n        ans="none"\n        for i in range(n,0,-1):\n            if not seat[i]:\n                ans=str(i)\n                break\n        print(ans)', tip: '空き管理はメモリアロケータやホテルの部屋割りの基本操作。セグ木に「区間の空き数」を持てば最右空きは二分降下でO(log n)、の高速化が定番の次の一歩。', ins: ['3 4\nU 3\nQ\nU 2\nQ\n', '2 3\nU 1\nU 2\nQ\n', '4 5\nU 4\nQ\nF 4\nQ\nU 1\n', '1 2\nQ\nU 1\n', '5 4\nU 5\nU 4\nQ\nQ\n', '2 2\nQ\nQ\n'] })

t({ lv: 846, concept: '数え上げ: 各接頭辞の最大和の総和', title: '節目ごとのベスト記録の合計', tags: ['数え上げ', 'DP'], io: '整数列が1行で空白区切りで与えられます。', ask: '各接頭辞(先頭i個、i=1..n)について「その中の最大連続部分和」を求め、それらの総和を出力してください。', h1: '接尾辞版(同レベル既出)の鏡像。', h2: 'カダネ法の走行中、各ステップのbestを足し込む。', ref: 'a=list(map(int,input().split()))\ncur=best=a[0]\ntotal=a[0]\nfor x in a[1:]:\n    cur=x+max(0,cur)\n    if cur>best:\n        best=cur\n    total+=best\nprint(total)', tip: 'カダネ法が各接頭辞の答えを「ついでに」全部生産していることに気づけば、追加コストゼロで総和が出る。オンラインアルゴリズムの中間出力を集計する発想。', ins: ['1 -2 3\n', '1 2 3\n', '-1 -2\n', '2 -1 2\n', '5\n', '-3 4 -1\n'] })

t({ lv: 847, concept: 'クエリ: 絶対値が最大の値のクエリ', title: 'いちばん過激な値', tags: ['クエリ'], io: '1行目に n q、2行目に長さ n の整数列、続く q 行に区間 l r が与えられます。', ask: '各区間で絶対値が最大の値を1行ずつ出力してください(絶対値が同じ正負があれば正の方)。', h1: '0に近い値(同レベル既出)の鏡像。', h2: 'max(seg, key=lambda x:(abs(x), x))。', ref: 'n,q=map(int,input().split())\na=list(map(int,input().split()))\nfor _ in range(q):\n    l,r=map(int,input().split())\n    print(max(a[l-1:r],key=lambda x:(abs(x),x)))', tip: 'maxのkeyにタプルを渡すとタイブレークまで宣言的に書ける。絶対値最大は区間のmaxと|min|の大きい方、なので既存のmax/min前計算2本で高速化できる。', ins: ['3 2\n1 -5 3\n1 3\n1 1\n', '2 1\n-2 2\n1 2\n', '4 2\n0 -1 1 -3\n1 3\n1 4\n', '1 1\n-9\n1 1\n', '5 1\n4 -4 2 -2 0\n1 5\n', '3 1\n-7 6 5\n2 3\n'] })

t({ lv: 848, concept: 'ハッシュ: 追加するたびの最頻値', title: '票が入るたびの首位', tags: ['ハッシュ'], io: '整数列(投票の列)が1行で空白区切りで与えられます。', ask: '1票入るごとに、その時点の最頻値(同数なら最小の値)を空白区切りで出力してください。', h1: '逐次順位(同レベル既出)の最頻値版。', h2: 'Counterを育てながら(−回数, 値)の最小を追う。', ref: 'from collections import Counter\na=list(map(int,input().split()))\nc=Counter()\nout=[]\nfor x in a:\n    c[x]+=1\n    out.append(min(c.items(),key=lambda kv:(-kv[1],kv[0]))[0])\nprint(" ".join(map(str,out)))', tip: '開票速報の「現在のトップ」表示の计算。都度全走査のO(nk)を、最頻値は1票で高々1変わる性質で O(n) に均す差分管理が次の一手になる。', ins: ['1 2 2 1 1\n', '5\n', '3 3 3\n', '1 2 3\n', '2 1 2 1\n', '4 4 5 5 5\n'] })

t({ lv: 849, concept: 'ソート: 最も長距離を動く要素', title: '引っ越し距離の最長記録', tags: ['ソート'], io: '整数列が1行で空白区切りで与えられます。', ask: '安定ソートで並べ替えたとき、元の位置からソート後の位置までの距離(添字の差の絶対値)が最大の値を出力してください。', h1: '動く距離の合計(同レベル既出)のmax版。', h2: '(値, 元の位置)で安定ソートして位置差を測る。', ref: 'a=list(map(int,input().split()))\norder=sorted(range(len(a)),key=lambda i:(a[i],i))\nprint(max(abs(new-old) for new,old in enumerate(order)))', tip: 'ソートによる移動距離の最大は「その要素がどれだけ場違いな場所にいたか」の指標。安定ソートのタイブレーク(値, 元位置)が距離の定義を一意にする要。', ins: ['3 1 2\n', '1 2 3\n', '5 1\n', '2 2 2\n', '4 1 3 2\n', '1 5 2 3 4\n'] })

t({ lv: 851, concept: '多項式: 微分した係数列', title: '多項式を1回微分する', tags: ['多項式'], io: '多項式の係数が低次から順に(定数項から)1行で空白区切りで与えられます。', ask: '微分した多項式の係数を低次から順に空白区切りで出力してください(結果が0多項式なら 0)。', h1: 'x^k の微分は k·x^(k−1)。', h2: '係数c[k]はk倍されて1つ下の次数へ。', ref: 'c=list(map(int,input().split()))\nd=[str(k*c[k]) for k in range(1,len(c))]\nprint(" ".join(d) if d else "0")', tip: '係数配列の微分は「添字倍してシフト」の1行に潰れる。積の係数(同レベル既出)と合わせると、多項式の代数が配列操作の語彙に翻訳されていく。', ins: ['1 2 3\n', '5\n', '0 1\n', '2 0 0 4\n', '1 1 1 1\n', '7 -3\n'] })

t({ lv: 852, concept: '数え上げ: XORが0になる3つ組', title: '三すくみの打ち消し', tags: ['数え上げ', 'bit演算'], io: '非負整数の列が1行で空白区切りで与えられます。', ask: 'i<j<k で a[i] XOR a[j] XOR a[k] が 0 になる3つ組の個数を出力してください。', h1: '2つ決まれば3つ目は一意(a^b)。', h2: 'ペアごとに「後ろに a[i]^a[j] が何個あるか」を数える。', ref: 'a=list(map(int,input().split()))\nn=len(a)\ncnt=0\nfor i in range(n):\n    for j in range(i+1,n):\n        need=a[i]^a[j]\n        cnt+=sum(1 for k in range(j+1,n) if a[k]==need)\nprint(cnt)', tip: 'XORの自己逆元性で「3つ目が確定する」構造は、和がKのペア(相方が確定)の3要素版。後ろだけ数えることで順序 i<j<k の重複勘定が自然に消える。', ins: ['1 2 3\n', '1 1\n', '0 0 0\n', '5 5 0\n', '1 2 3 0\n', '4 4 4\n'] })

t({ lv: 853, concept: 'bit演算: ビットごとの人数の一覧', title: 'ビット別の点呼', tags: ['bit演算'], io: '非負整数の列が1行で空白区切りで与えられます。', ask: 'ビット0(最下位)から、列の中の最大値の最上位ビットまで、各ビットが立っている要素数を空白区切りで出力してください(全要素が0なら 0 を1つ出力)。', h1: 'AND/ORの総和(既出)の前段となる集計。', h2: '各ビットで >> と & 1。', ref: 'a=list(map(int,input().split()))\nm=max(a)\nif m==0:\n    print(0)\nelse:\n    out=[]\n    for b in range(m.bit_length()):\n        out.append(sum(x>>b&1 for x in a))\n    print(" ".join(map(str,out)))', tip: 'ビット別の度数分布は、AND/OR/XORの総和・多数決ビット復元(過半数のビットで作る値)など多くの集計の共通の中間生成物。列を「ビットの行列」として転置して見る目が養われる。', ins: ['1 2 3\n', '0 0\n', '7 7\n', '4 4 4\n', '1 1 1 1\n', '5 3\n'] })

t({ lv: 854, concept: 'bit演算: 全体のORを作る最小の要素数', title: '全ビットをそろえる最小人数', tags: ['bit演算'], io: '非負整数の列が1行で空白区切りで与えられます。', ask: '全要素のORと同じ値を、できるだけ少ない要素のORで作るときの要素数の最小を出力してください(全要素0なら 0)。', h1: '小さい個数の部分集合から試す。', h2: 'combinationsでサイズ1から。', ref: 'from itertools import combinations\na=list(map(int,input().split()))\ntarget=0\nfor x in a:\n    target|=x\nif target==0:\n    print(0)\nelse:\n    def solve():\n        for size in range(1,len(a)+1):\n            for combo in combinations(a,size):\n                v=0\n                for x in combo:\n                    v|=x\n                if v==target:\n                    return size\n    print(solve())', tip: 'これは集合被覆問題(各要素=ビットの集合)のOR版で、一般にはNP困難。小さい方から試す反復深化が「最小」の証明書になる、全探索の正しい姿。', ins: ['1 2 3\n', '7 1 2\n', '0 0\n', '5 3\n', '1 2 4 7\n', '6 5\n'] })

t({ lv: 855, concept: '数列: 漸化式の不動点', title: '動かなくなる値', tags: ['数列'], io: 'a b が空白区切りで1行で与えられます(a≠1、解は整数)。', ask: '漸化式 x → a·x + b で値が変化しなくなる x (不動点)を出力してください。', h1: 'x = ax + b を解く。', h2: 'x = b / (1−a) = −b / (a−1)。', ref: 'a,b=map(int,input().split())\nprint(-b//(a-1))', tip: '線形漸化式の一般解は「不動点+等比のずれ」に分解でき、遠い項の計算(同レベル既出)の見通しが一気に良くなる。|a|>1なら反発点、|a|<1なら吸引点という力学系の顔も持つ。', ins: ['2 3\n', '3 -4\n', '0 7\n', '-1 6\n', '5 -8\n', '2 -10\n'] })

t({ lv: 856, concept: '行列累乗: 長さkの閉路の数', title: 'ぐるっと回ってk歩で戻る', tags: ['行列累乗', 'グラフ'], io: '1行目に頂点数 n と歩数 k、続く n 行に隣接行列(有向、0/1)が与えられます。', ask: 'ちょうど k 歩で出発点に戻る歩き方の総数(全頂点についての合計)を出力してください。', h1: '長さkの経路数(同レベル既出)の対角成分版。', h2: 'A^k のトレース(対角和)。', ref: 'n,k=map(int,input().split())\nA=[list(map(int,input().split())) for _ in range(n)]\ndef mul(X,Y):\n    return [[sum(X[i][t]*Y[t][j] for t in range(n)) for j in range(n)] for i in range(n)]\nR=[[1 if i==j else 0 for j in range(n)] for i in range(n)]\nB=A\ne=k\nwhile e:\n    if e&1:\n        R=mul(R,B)\n    B=mul(B,B)\n    e>>=1\nprint(sum(R[i][i] for i in range(n)))', tip: 'トレースは行列の固有値の和で、tr(A^k)=Σλ^k は閉路数と固有値を結ぶスペクトルグラフ理論の入り口。三角形の数がtr(A³)/6になる(既出の問題の別解)のもこの式から。', ins: ['2 2\n0 1\n1 0\n', '3 3\n0 1 0\n0 0 1\n1 0 0\n', '2 1\n0 1\n1 0\n', '2 4\n0 1\n1 0\n', '3 2\n0 1 1\n1 0 1\n1 1 0\n', '1 5\n1\n'] })

t({ lv: 857, concept: '数論: 互いに素になる最小の数', title: '一番小さな新顔', tags: ['数論'], io: '2以上の整数 n が1行で与えられます。', ask: '2以上で n と互いに素な最小の整数を出力してください。', h1: '答えは必ず素数になる。', h2: '2から順にgcdを確かめる。', ref: 'from math import gcd\nn=int(input())\nx=2\nwhile gcd(x,n)!=1:\n    x+=1\nprint(x)', tip: '答えは「nを割らない最小の素数」で、素数階乗(2·3·5·…)のときに最も大きくなる。φ(n)が「個数」を数えるのに対し、こちらは「最初の1つ」を探す構成版。', ins: ['6\n', '2\n', '15\n', '30\n', '7\n', '210\n'] })

t({ lv: 858, concept: '数論: 既約分数の分子の合計', title: '約分できない分子を集めて', tags: ['数論'], io: '2以上の整数 n が1行で与えられます。', ask: '分母が n の真分数 k/n (1≤k<n) のうち既約なものの分子の合計を出力してください。', h1: 'kとn−kは互いに素かどうかが一致する。', h2: 'ペアの和がnなので、合計は n×φ(n)÷2。', ref: 'from math import gcd\nn=int(input())\nprint(sum(k for k in range(1,n) if gcd(k,n)==1))', tip: '互いに素な k を n−k と組にする対称性から nφ(n)/2 の公式が出る。ガウスの「対にして数える」流儀が、φの総和(同レベル既出)の隣で再演される。', ins: ['6\n', '2\n', '5\n', '12\n', '7\n', '10\n'] })

t({ lv: 859, concept: '数論: 約数にわたるμの和', title: 'メビウスの打ち消し実験', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: 'n の全ての約数 d について μ(d) (メビウス関数)を足した値を出力してください。', h1: '答えを予想してから確かめる。', h2: 'n=1 のとき1、それ以外は0になる(メビウスの基本恒等式)。', ref: 'n=int(input())\ndef mu(x):\n    r=1\n    p=2\n    while p*p<=x:\n        if x%p==0:\n            x//=p\n            if x%p==0:\n                return 0\n            r=-r\n        p+=1\n    if x>1:\n        r=-r\n    return r\ntotal=0\nd=1\nwhile d*d<=n:\n    if n%d==0:\n        total+=mu(d)\n        if d!=n//d:\n            total+=mu(n//d)\n    d+=1\nprint(total)', tip: 'Σ_{d|n} μ(d)=[n=1] はメビウス反転公式の心臓部で、包除原理の数論版。自分の手で総当たり計算して0が出続けるのを見るのが、公式を信じる一番の近道。', ins: ['1\n', '2\n', '6\n', '12\n', '30\n', '7\n'] })

t({ lv: 860, concept: '数論: k番目のパワフル数', title: '力持ちの数を順に', tags: ['数論'], io: '正整数 k が1行で与えられます。', ask: 'パワフル数(全ての素因数が2乗以上で割り切る数。1も含む)を小さい順に並べたときの k 番目を出力してください。', h1: '判定(同レベル既出)を数え上げに乗せる。', h2: '順に判定して数える。', ref: 'k=int(input())\ndef powerful(x):\n    p=2\n    while p*p<=x:\n        if x%p==0:\n            if x%(p*p)!=0:\n                return False\n            while x%p==0:\n                x//=p\n        p+=1\n    return x==1\nc=0\nx=0\nwhile c<k:\n    x+=1\n    if powerful(x):\n        c+=1\nprint(x)', tip: '1, 4, 8, 9, 16, 25, 27, 32, 36…と続くパワフル数は a²b³ の形に必ず書ける。n以下に約√n個しかない疎な集合で、隣接するパワフル数のペア(8,9)の希少性は未解決問題に繋がる。', ins: ['1\n', '2\n', '5\n', '10\n', '3\n', '15\n'] })

t({ lv: 861, concept: '数論: n番目の素数のべき', title: '素数一族の勢ぞろい', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: '素数のべき乗 p^k (pは素数、k≥1) を小さい順に並べたときの n 番目を出力してください(2, 3, 4, 5, 7, 8, 9, 11, …)。', h1: '素数べき判定(既出)を順に適用。', h2: '素因数が1種類かどうか。', ref: 'n=int(input())\ndef pp(x):\n    if x<2:\n        return False\n    p=2\n    while p*p<=x:\n        if x%p==0:\n            while x%p==0:\n                x//=p\n            return x==1\n        p+=1\n    return True\nc=0\nx=1\nwhile c<n:\n    x+=1\n    if pp(x):\n        c+=1\nprint(x)', tip: '素数べきの列は素数列に4,8,9,16,25,27…が混ざった姿。巡回群が存在する位数、原始根が存在する法(2,4,p^k,2p^k)など、この列は代数の重要な境界線を刻んでいる。', ins: ['1\n', '3\n', '5\n', '8\n', '10\n', '15\n'] })

t({ lv: 862, concept: '数論: N以下の半素数の個数', title: '素数×素数を数える', tags: ['数論'], io: '正整数 N が1行で与えられます。', ask: '1 以上 N 以下の半素数(ちょうど2つの素数の積。4=2×2も含む)の個数を出力してください。', h1: '半素数の判定(既出)を範囲に適用。', h2: 'Ω(重複込みの素因数の個数)が2の数。', ref: 'n=int(input())\ndef omega(x):\n    c=0\n    p=2\n    while p*p<=x:\n        while x%p==0:\n            c+=1\n            x//=p\n        p+=1\n    if x>1:\n        c+=1\n    return c\nprint(sum(1 for x in range(4,n+1) if omega(x)==2))', tip: '半素数はRSA暗号の合成数の形そのもので、その分布(N以下に約N·lnlnN/lnN個)は素数定理の兄弟分。Ω=2という判定がシンプルさの源。', ins: ['10\n', '4\n', '3\n', '20\n', '30\n', '50\n'] })

t({ lv: 863, concept: '整数: 余りの総和', title: 'あまりを全部かき集める', tags: ['整数'], io: '正整数 n が1行で与えられます。', ask: 'n を 1 から n までの各数で割った余りの総和 Σ(n mod i) を出力してください。', h1: 'n mod i = n − i×⌊n/i⌋。', h2: '総当たりで足すのが基準解。', ref: 'n=int(input())\nprint(sum(n%i for i in range(1,n+1)))', tip: 'Σ(n mod i) = n² − Σ i⌊n/i⌋ と変形でき、Σfloor(同レベル既出)の兄弟であることが見える。商のブロック分け(既出)を使えばO(√n)に落ちる。', ins: ['5\n', '1\n', '10\n', '3\n', '7\n', '100\n'] })

t({ lv: 864, concept: '数論: 商がkになる範囲', title: '同じ商をもつ仲間の区間', tags: ['数論'], io: 'n k が空白区切りで1行で与えられます。', ask: '⌊n/i⌋ = k となる整数 i の範囲を「最小 最大」で出力してください(存在しなければ none)。', h1: '商の種類数(同レベル既出)のブロックの正体。', h2: '最大は n//k、最小は n//(k+1)+1。', ref: 'n,k=map(int,input().split())\nif k>n:\n    print("none")\nelse:\n    hi=n//k\n    lo=n//(k+1)+1\n    if lo<=hi and n//lo==k:\n        print(lo,hi)\n    else:\n        print("none")', tip: '「商が同じiのブロック」の端点公式は、約数系の総和をO(√n)にする数論の主力エンジン。導出は不等式 k≤n/i<k+1 を i について解くだけ、と意外に素直。', ins: ['10 3\n', '10 1\n', '10 10\n', '10 4\n', '100 7\n', '5 6\n'] })

t({ lv: 865, concept: '数論: 範囲内の合同な数の個数', title: '同じ余りの住人を数える', tags: ['数論'], io: 'N m a が空白区切りで1行で与えられます (0≤a<m)。', ask: '1 以上 N 以下で m で割った余りが a の整数の個数を出力してください。', h1: '等差数列の項数の勘定。', h2: '床関数で一撃だが、端の処理に注意。', ref: 'N,m,a=map(int,input().split())\nif a==0:\n    print(N//m)\nelse:\n    print((N-a)//m+1 if a<=N else 0)', tip: '「N以下でd の倍数」の個数 N//d の一般化で、a=0だけ式が変わる境界が定番の事故現場。二つの式を max(0, (N−a)//m + 1) 系に統一する書き方も練習になる。', ins: ['10 3 1\n', '10 3 0\n', '5 7 2\n', '100 10 9\n', '1 2 1\n', '9 3 0\n'] })

t({ lv: 866, concept: '数論: 互除法の手数', title: 'ユークリッドの足取り', tags: ['数論'], io: 'a b が空白区切りで1行で与えられます (a, b ≥ 1)。', ask: 'ユークリッドの互除法(大きい方を小さい方で割った余りに置き換える)で gcd に到達するまでの剰余演算の回数を出力してください(bが0になったら終了)。', h1: '普通のgcdループに回数カウンタを足すだけ。', h2: '最悪ケースはフィボナッチ数の隣接ペア。', ref: 'a,b=map(int,input().split())\nc=0\nwhile b:\n    a,b=b,a%b\n    c+=1\nprint(c)', tip: 'ラメの定理: 手数は小さい方の桁数の約5倍以下で、最悪を達成するのはフィボナッチ数対。アルゴリズムの計算量解析が19世紀に始まった、その記念碑的な結果。', ins: ['12 8\n', '5 5\n', '13 8\n', '1 1\n', '100 3\n', '21 13\n'] })

t({ lv: 867, concept: '数論: 合同方程式の解の一覧', title: '解を全部ならべる', tags: ['数論'], io: 'a b m が空白区切りで1行で与えられます。', ask: 'ax ≡ b (mod m) の解 x (0≤x<m) を昇順に全て空白区切りで出力してください(解が無ければ none)。', h1: '解の個数(同レベル既出)と最小解(同レベル既出)の完全版。', h2: '素朴に全部試すのが確実。', ref: 'a,b,m=map(int,input().split())\nsol=[str(x) for x in range(m) if a*x%m==b%m]\nprint(" ".join(sol) if sol else "none")', tip: '解はg=gcd(a,m)がbを割るときだけ存在し、ちょうどg個がm/g間隔で等間隔に並ぶ——一覧を出力すると、その等間隔構造が目で見える。', ins: ['2 4 6\n', '3 1 7\n', '2 3 4\n', '4 0 8\n', '1 5 9\n', '6 3 9\n'] })

t({ lv: 868, concept: '数論: 分数を法pで評価', title: '割り算を掛け算に化かす', tags: ['数論'], io: 'a b p が空白区切りで1行で与えられます (pは素数、bはpで割り切れない)。', ask: 'a/b を法 p で評価した値(a×b^(p−2) mod p)を出力してください。', h1: '逆元(同レベル既出)の応用。', h2: 'pow(b, p−2, p) がbの逆元。', ref: 'a,b,p=map(int,input().split())\nprint(a*pow(b,p-2,p)%p)', tip: '確率や組合せを mod で答える問題の頻出部品。「分数のmod」は値でなく合同類の演算であり、1/2 mod 7 = 4 のような直感に反する値に慣れるのが第一関門。', ins: ['1 2 7\n', '3 4 5\n', '10 3 7\n', '1 1 13\n', '5 6 11\n', '2 3 5\n'] })

t({ lv: 869, concept: '文字列: 括弧列の鏡映', title: '鏡の中の括弧', tags: ['文字列'], io: '括弧列(正しいとは限らない)が1行で与えられます。', ask: '左右を反転し、各括弧の向きも反転した文字列(鏡に映した姿)を出力してください。', h1: '逆順と置換の合成。', h2: 'reversedしながら ( と ) を交換。', ref: 's=input()\nprint("".join(")" if c=="(" else "(" for c in reversed(s)))', tip: '鏡映は「正しい括弧列を正しい括弧列に写す」対合(2回やると元通り)で、カタラン数の対称性の証明にも使われる操作。反転と置換の順序はどちらでも同じ、も確かめたい。', ins: ['(()\n', '()\n', '((((\n', ')(\n', '(())\n', '()(\n'] })

t({ lv: 870, concept: '組合せ: 二項係数の桁数', title: '組合せ爆発の大きさを測る', tags: ['組合せ'], io: 'n k が空白区切りで1行で与えられます (0≤k≤n)。', ask: 'C(n, k) の十進の桁数を出力してください。', h1: '多倍長で厳密に計算してlen(str())。', h2: 'combが一撃。', ref: 'from math import comb\nn,k=map(int,input().split())\nprint(len(str(comb(n,k))))', tip: 'C(100,50)は30桁——「組合せ爆発」の実寸をこの目で確かめる問題。log10の和による桁数推定はスターリング近似の練習台にもなる。', ins: ['10 5\n', '100 50\n', '5 0\n', '20 10\n', '50 25\n', '30 1\n'] })

t({ lv: 871, concept: '順列: 完全順列かどうか', title: '全員よその席か点検', tags: ['順列'], io: '1〜n の並べ替えが1行で空白区切りで与えられます。', ask: 'どの i でも i 番目の値が i でない(完全順列)なら yes、そうでなければ no を出力してください。', h1: '数(同レベル既出)の判定版。', h2: 'enumerate して一致を探す。', ref: 'a=list(map(int,input().split()))\nprint("no" if any(v==i for i,v in enumerate(a,1)) else "yes")', tip: 'プレゼント交換の成立条件そのもの。判定はO(n)の全称チェックで、数え上げ(D(n)、既出)や生成と役割分担する三点セットの一角。', ins: ['2 1\n', '1 2\n', '2 3 1\n', '3 2 1\n', '1\n', '4 3 2 1\n'] })

t({ lv: 872, concept: '数え上げ: 車輪グラフの全域木数', title: '車輪を支える木の数', tags: ['数え上げ', 'グラフ'], io: '外周の頂点数 n (3〜8) が1行で与えられます。車輪グラフはハブ1個+外周n個(ハブと外周全て、外周は隣どうしが辺)です。', ask: 'この車輪グラフの全域木の総数を出力してください。', h1: '辺は2n本、全域木はn本の辺を選ぶ。', h2: '辺の部分集合を総当たりし、Union-Findで木か確かめる。', ref: 'from itertools import combinations\nn=int(input())\nes=[]\nfor i in range(1,n+1):\n    es.append((0,i))\nfor i in range(1,n+1):\n    es.append((i,i%n+1))\ncnt=0\nfor combo in combinations(range(len(es)),n):\n    p=list(range(n+1))\n    def find(x):\n        while p[x]!=x:\n            p[x]=p[p[x]]\n            x=p[x]\n        return x\n    ok=True\n    for idx in combo:\n        u,v=es[idx]\n        ru,rv=find(u),find(v)\n        if ru==rv:\n            ok=False\n            break\n        p[ru]=rv\n    if ok:\n        cnt+=1\nprint(cnt)', tip: '答えはリュカ数を使って L(2n)−2 と書ける(n=3で16、n=4で45)。行列木定理の閉じた式と総当たりの一致を見る、数え上げ理論の「実験ノート」的1問。', ins: ['3\n', '4\n', '5\n', '6\n', '7\n', '8\n'] })

t({ lv: 873, concept: '数え上げ: 奇数個の項への分割数', title: '奇数チームに割る方法', tags: ['数え上げ', 'DP'], io: '正整数 n が1行で与えられます。', ask: 'n を正整数の和に分ける方法(順序は区別しない)のうち、項の個数が奇数であるものの数を出力してください。', h1: '個数の偶奇を状態に足したDP。', h2: 'dp[部品の上限][和][個数の偶奇]。', ref: 'n=int(input())\ndp=[[0]*2 for _ in range(n+1)]\ndp[0][0]=1\nfor part in range(1,n+1):\n    for s in range(part,n+1):\n        for par in range(2):\n            dp[s][par^1]+=dp[s-part][par]\nprint(dp[n][1])', tip: '偶数個の項の分割数との差は「相異なる奇数への分割数」に等しい、という分割恒等式の世界の入り口。パリティを1ビット持つだけでDPが答えてくれる。', ins: ['4\n', '1\n', '5\n', '6\n', '3\n', '8\n'] })

t({ lv: 874, concept: '数え上げ: 置換の位数の最大', title: '一番戻ってこない入れ替え', tags: ['数え上げ'], io: '正整数 n が1行で与えられます。', ask: 'n 要素の置換を繰り返し適用して恒等に戻るまでの回数(位数)として、あり得る最大の値を出力してください。', h1: '位数はサイクル長のLCM。', h2: 'nの分割全てについてLCMの最大を探す(ランダウ関数)。', ref: 'from math import lcm\nimport sys\nsys.setrecursionlimit(10000)\nn=int(input())\nbest=1\ndef go(rest,minpart,cur):\n    global best\n    if cur>best:\n        best=cur\n    for p in range(minpart,rest+1):\n        go(rest-p,p,lcm(cur,p))\ngo(n,1,1)\nprint(best)', tip: 'ランダウ関数 g(n) は e^√(n ln n) 程度で育つ、置換群の「最長の周期」。何回で戻るか(既出)の最悪ケースを分割の全探索で暴く、群論と分割の交差点。', ins: ['1\n', '3\n', '5\n', '7\n', '10\n', '12\n'] })

export const CATALOG = TASKS
