// 生成タスク 第51波：各レベル2問化フェーズ(6)。lv295〜343 に2問目を追加。
// 上位問題(AtCoder/LeetCode/古典)の要素分解。重複なし・決定的・採点一意。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 160, concept: '最適化: 1変数グリッドサーチ', title: '候補から二次関数を最小にする値', tags: ['最適化', 'データ分析'], io: '1行目に係数 a b c、2行目に候補値(整数)の列が与えられます。', ask: 'f(x)=ax²+bx+c を最小にする候補値を出力してください。最小値が複数の候補で並んだ場合は、その中で最小の候補値を出力します。', h1: '候補を1つずつ評価して最良を更新する(グリッドサーチ)。', h2: '同点の扱いを一意にするため候補を昇順に見て「より小さい値のときだけ」更新する。', ref: 'a,b,c=map(int,input().split())\nxs=list(map(int,input().split()))\nbest=None\nbx=None\nfor x in sorted(xs):\n    v=a*x*x+b*x+c\n    if best is None or v<best:\n        best=v\n        bx=x\nprint(bx)', tip: 'ハイパーパラメータ調整の最も基本的な形が候補総当たり(グリッドサーチ)。同点の規則を決めておくと結果が再現可能になる。', ins: ['1 -6 9\n0 1 2 3 4 5 6\n', '1 0 0\n-3 -1 2 5\n', '0 1 0\n4 2 8\n', '0 0 7\n3 1 2\n', '2 -4 1\n0 1 2\n', '1 2 1\n-5 -1 3\n'] })

t({ lv: 160, concept: '最適化: 2変数グリッドサーチ', title: '2つの候補リストの最良の組合せ', tags: ['最適化', 'データ分析'], io: '1行目に目標 tx ty、2行目に x の候補列、3行目に y の候補列が与えられます。', ask: 'f(x,y)=(x-tx)²+(y-ty)² を最小にする組を「x y」の形で出力してください。同点なら x が最小、さらに同点なら y が最小の組を選びます。', h1: '2重ループで全組合せを評価する。', h2: 'x も y も昇順に走査して「より小さいときだけ」更新すれば優先規則が自動で満たされる。', ref: 'tx,ty=map(int,input().split())\nxs=list(map(int,input().split()))\nys=list(map(int,input().split()))\nbest=None\nbp=None\nfor x in sorted(xs):\n    for y in sorted(ys):\n        v=(x-tx)**2+(y-ty)**2\n        if best is None or v<best:\n            best=v\n            bp=(x,y)\nprint(bp[0],bp[1])', tip: 'パラメータが2つなら組合せは積になる(グリッドの呪い)。候補4×4=16通り程度なら総当たりが最も確実。', ins: ['1 2\n0 1 2 3\n0 1 2 3\n', '5 5\n0 1 2\n0 9\n', '0 0\n-1 1\n-1 1\n', '3 0\n0 1 2 3\n0 1 2 3\n', '2 2\n1 3\n1 3\n', '10 1\n4 8\n1 2\n'] })

t({ lv: 295, concept: 'グラフ: 一筆書きの最小ストローク数', title: '全ての辺をなぞる最小ストローク数', tags: ['グラフ'], io: '1行目に頂点数 n と辺数 m、続く m 行に無向辺 u v が与えられます。', ask: 'ペンを紙から離さずに辺をなぞる「ストローク」で全ての辺をちょうど1回ずつなぞるとき、必要なストロークの最小本数を出力してください。', h1: '辺を持つ連結成分ごとに考える。奇数次数の頂点の数を数える。', h2: '各成分の必要本数は max(1, 奇数次数の頂点数/2)。孤立点は無視。', ref: 'n,m=map(int,input().split())\nadj=[[] for _ in range(n+1)]\ndeg=[0]*(n+1)\nfor _ in range(m):\n    u,v=map(int,input().split())\n    adj[u].append(v)\n    adj[v].append(u)\n    deg[u]+=1\n    deg[v]+=1\nseen=[False]*(n+1)\nans=0\nfor s in range(1,n+1):\n    if seen[s] or deg[s]==0:\n        continue\n    seen[s]=True\n    st=[s]\n    odd=0\n    while st:\n        x=st.pop()\n        if deg[x]%2==1:\n            odd+=1\n        for y in adj[x]:\n            if not seen[y]:\n                seen[y]=True\n                st.append(y)\n    ans+=max(1,odd//2)\nprint(ans)', tip: 'オイラー路の一般化。奇数次数の頂点が2k個ある連結成分は k 本(k=0なら1本)のストロークで描ける。', ins: ['4 4\n1 2\n2 3\n3 4\n4 1\n', '3 2\n1 2\n2 3\n', '4 3\n1 2\n1 3\n1 4\n', '6 4\n1 2\n2 3\n4 5\n5 6\n', '5 4\n1 2\n2 3\n3 1\n4 5\n', '2 1\n1 2\n'] })

t({ lv: 296, concept: 'グラフ: 母頂点の探索', title: '全頂点へ到達できる最小の頂点', tags: ['グラフ'], io: '1行目に頂点数 n と辺数 m、続く m 行に有向辺 u v が与えられます。', ask: 'そこから全ての頂点へ到達できる頂点(母頂点)のうち番号最小のものを出力してください。存在しなければ -1 を出力してください。', h1: '各頂点からDFS/BFSして到達数を数える。', h2: '到達数が n になる最小の頂点を探す。', ref: 'n,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\nans=-1\nfor s in range(1,n+1):\n    seen=[False]*(n+1)\n    seen[s]=True\n    st=[s]\n    c=1\n    while st:\n        x=st.pop()\n        for y in g[x]:\n            if not seen[y]:\n                seen[y]=True\n                c+=1\n                st.append(y)\n    if c==n:\n        ans=s\n        break\nprint(ans)', tip: '母頂点(mother vertex)はDFSで最後に終了する頂点が候補になる性質があり、O(V+E)でも解ける。', ins: ['3 2\n1 2\n2 3\n', '3 2\n1 2\n3 2\n', '4 4\n2 1\n1 3\n3 4\n4 2\n', '1 0\n', '5 4\n3 1\n3 2\n3 4\n4 5\n', '2 1\n2 1\n'] })

t({ lv: 297, concept: 'グラフ: 相互に結ばれた頂点対', title: '双方向に辺がある頂点対の数', tags: ['グラフ', 'ハッシュ'], io: '1行目に頂点数 n と辺数 m、続く m 行に有向辺 u v が与えられます(同じ辺は2回現れない)。', ask: 'u→v と v→u の両方の辺がある頂点対 {u,v} (u≠v) の個数を出力してください。', h1: '辺を集合に入れる。', h2: 'u<v のペアについて両方向が集合にあるか確認。', ref: 'n,m=map(int,input().split())\nes=set()\nfor _ in range(m):\n    u,v=map(int,input().split())\n    es.add((u,v))\ncnt=0\nfor (u,v) in es:\n    if u<v and (v,u) in es:\n        cnt+=1\nprint(cnt)', tip: 'タプルを集合に入れると逆向きの辺の存在が O(1) で引ける。u<v の片側だけ数えると重複カウントを防げる。', ins: ['3 4\n1 2\n2 1\n2 3\n3 1\n', '2 2\n1 2\n2 1\n', '3 3\n1 2\n2 3\n3 1\n', '4 6\n1 2\n2 1\n3 4\n4 3\n1 3\n2 4\n', '2 1\n1 2\n', '5 0\n'] })

t({ lv: 298, concept: 'グラフ: 次数列の実現可能性', title: '次数列から単純グラフを作れるか', tags: ['グラフ', '貪欲'], io: '非負整数の次数列が1行で空白区切りで与えられます。', ask: 'その次数列を持つ単純無向グラフ(自己ループ・多重辺なし)が存在するなら yes、しないなら no を出力してください。', h1: 'Havel–Hakimi: 最大次数 k の頂点を取り、次に大きい k 個の次数を1ずつ減らす。', h2: 'これを全て0になるまで繰り返す。途中で負になるか頂点が足りなければ no。', ref: 'd=list(map(int,input().split()))\nok=True\nwhile True:\n    d.sort(reverse=True)\n    if d[0]==0:\n        break\n    k=d.pop(0)\n    if k>len(d):\n        ok=False\n        break\n    for i in range(k):\n        d[i]-=1\n        if d[i]<0:\n            ok=False\n            break\n    if not ok:\n        break\nprint("yes" if ok else "no")', tip: 'Havel–Hakimiの定理: 次数列の実現可能性は「最大次数を取り除いて上位を1ずつ減らす」貪欲で判定できる。', ins: ['3 3 3 3\n', '1 1\n', '3 1 1\n', '0\n', '2 2 2\n', '1\n'] })

t({ lv: 299, concept: '数論: ビット数が偶数の整数の個数', title: '1からNでビットが偶数個の数', tags: ['bit演算'], io: '正整数 N が1行で与えられます。', ask: '1 以上 N 以下で、2進表記の1のビット数が偶数である整数の個数を出力してください。', h1: '各数の popcount を調べる。', h2: 'bin(i).count("1") の偶奇でフィルタ。', ref: 'n=int(input())\nprint(sum(1 for i in range(1,n+1) if bin(i).count("1")%2==0))', tip: 'ビット数が偶数の数は evil number と呼ばれる。Thue–Morse 数列の0の位置に対応する。', ins: ['10\n', '1\n', '3\n', '100\n', '64\n', '1000\n'] })

t({ lv: 300, concept: 'DP: 共通部分列の組数', title: '共通部分列の組の総数', tags: ['DP', '文字列'], io: '2行に文字列 s と t が与えられます。', ask: 's から選んだ部分列と t から選んだ部分列が同じ文字列になる選び方(添字の組)の総数を出力してください(空でない部分列のみ数える)。', h1: 'dp[i][j]=sのi文字目まで・tのj文字目までの共通部分列の組数。', h2: '包除で dp[i-1][j]+dp[i][j-1]-dp[i-1][j-1]、末尾文字が一致したらさらに dp[i-1][j-1]+1。', ref: 's=input()\nt=input()\nn,m=len(s),len(t)\ndp=[[0]*(m+1) for _ in range(n+1)]\nfor i in range(1,n+1):\n    for j in range(1,m+1):\n        dp[i][j]=dp[i-1][j]+dp[i][j-1]-dp[i-1][j-1]\n        if s[i-1]==t[j-1]:\n            dp[i][j]+=dp[i-1][j-1]+1\nprint(dp[n][m])', tip: '2次元の数え上げDPでは重複領域を引く包除 dp[i-1][j]+dp[i][j-1]-dp[i-1][j-1] が頻出。LCSの「長さ」を「組数」に変えた親戚問題。', ins: ['ab\nab\n', 'aa\na\n', 'abc\nxyz\n', 'abc\nabc\n', 'aba\nab\n', 'zz\nzz\n'] })

t({ lv: 301, concept: '数論: ユニタリ約数の個数', title: 'ユニタリ約数の個数', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: 'n の約数 d のうち gcd(d, n/d)=1 を満たすもの(ユニタリ約数)の個数を出力してください。', h1: '全約数について gcd(d, n/d) を確認。', h2: '個数は 2^(相異なる素因数の数) になる。', ref: 'import math\nn=int(input())\nprint(sum(1 for d in range(1,n+1) if n%d==0 and math.gcd(d,n//d)==1))', tip: 'ユニタリ約数の個数は 2^ω(n) (ωは相異なる素因数の個数)。素因数の「全部入り/全部なし」の選択だから。', ins: ['12\n', '1\n', '8\n', '30\n', '100\n', '7\n'] })

t({ lv: 302, concept: '数論: 区間の双子素数の組数', title: '区間内の双子素数の組数', tags: ['数論'], io: 'l r が空白区切りで1行で与えられます。', ask: 'l ≤ p かつ p+2 ≤ r で、p と p+2 がともに素数である組 (p, p+2) の個数を出力してください。', h1: '区間の各 p について p と p+2 を素数判定。', h2: '試し割りで十分。', ref: 'l,r=map(int,input().split())\ndef ip(x):\n    if x<2:\n        return False\n    d=2\n    while d*d<=x:\n        if x%d==0:\n            return False\n        d+=1\n    return True\nprint(sum(1 for p in range(l,r-1) if ip(p) and ip(p+2)))', tip: '差が2の素数の組が双子素数。(3,5),(5,7),(11,13),…。無限に存在するかは未解決問題。', ins: ['1 20\n', '10 20\n', '1 5\n', '20 28\n', '1 100\n', '2 4\n'] })

t({ lv: 303, concept: '数論: オイラリアン数', title: '上昇がちょうどk箇所の順列の数', tags: ['数学', 'DP'], io: 'n k が空白区切りで1行で与えられます。', ask: '1〜n の順列のうち、隣接して増加する位置(p[i]<p[i+1])がちょうど k 箇所あるものの個数(オイラリアン数 A(n,k))を出力してください。', h1: '漸化式 A(n,k)=(k+1)A(n-1,k)+(n-k)A(n-1,k-1)。', h2: 'A(n,0)=1。表を埋める。', ref: 'n,k=map(int,input().split())\nprev=[1]+[0]*n\nfor i in range(1,n+1):\n    cur=[0]*(n+1)\n    for j in range(i):\n        cur[j]=(j+1)*prev[j]+(i-j)*(prev[j-1] if j>0 else 0)\n    prev=cur\nprint(prev[k])', tip: 'オイラリアン数はカタラン数と並ぶ順列の数え上げの基本。新しい最大値 n を挿入する位置で場合分けすると漸化式が出る。', ins: ['3 1\n', '4 2\n', '1 0\n', '5 2\n', '4 0\n', '6 3\n'] })

t({ lv: 304, concept: '累積和: 重ならない2つの長さK区間の最大和', title: '重ならない2つの長さK区間の和の最大', tags: ['累積和'], io: '1行目に K、2行目に整数列(長さ2K以上)が与えられます。', ask: '重ならない長さ K の連続区間を2つ選ぶときの、和の合計の最大値を出力してください。', h1: '全ての長さKの窓の和をスライドで求める。', h2: '右の窓を固定し、左側(K個以上手前)の窓和の最大を前計算と合わせる。', ref: 'k=int(input())\na=list(map(int,input().split()))\nn=len(a)\nw=[sum(a[:k])]\nfor i in range(1,n-k+1):\n    w.append(w[-1]-a[i-1]+a[i+k-1])\nbest=None\nmx=w[0]\nfor j in range(k,len(w)):\n    mx=max(mx,w[j-k])\n    s=mx+w[j]\n    if best is None or s>best:\n        best=s\nprint(best)', tip: '「2つの区間」は片方を走査しながらもう片方の最良値を累積max で持つと O(n)。3区間版も同じ発想。', ins: ['2\n1 2 3 4 5 6\n', '1\n5 1 5\n', '2\n1 1 1 1\n', '3\n1 2 3 4 5 6\n', '1\n-1 -2 -3\n', '2\n3 -1 4 -1 5 9\n'] })

t({ lv: 305, concept: '二点法: 和がT未満の三つ組の数', title: '和がT未満になる3要素の組数', tags: ['二点法'], io: '1行目に T、2行目に整数列が与えられます。', ask: '相異なる3つの添字の組で、要素の和が T 未満になるものの個数を出力してください。', h1: 'ソートして1つ目を固定。', h2: '残りを両端から狭める。a[i]+a[lo]+a[hi]<T なら hi-lo 個まとめて数える。', ref: 't=int(input())\na=sorted(map(int,input().split()))\nn=len(a)\ncnt=0\nfor i in range(n-2):\n    lo,hi=i+1,n-1\n    while lo<hi:\n        if a[i]+a[lo]+a[hi]<t:\n            cnt+=hi-lo\n            lo+=1\n        else:\n            hi-=1\nprint(cnt)', tip: '和が条件を満たす組を「まとめて数える」のが二点法の威力。a[lo]とのペアが成立すればa[lo+1..hi]全部成立する。', ins: ['8\n1 2 3 4 5\n', '0\n-2 0 1 3\n', '10\n1 1 1\n', '6\n1 2 3\n', '100\n10 20 30 40\n', '5\n0 0 0 0\n'] })

t({ lv: 306, concept: '貪欲: 相異なる正整数に分ける最大個数', title: '相異なる正整数に分ける最大個数', tags: ['貪欲', '数学'], io: '正整数 n が1行で与えられます。', ask: 'n を相異なる正整数の和に分けるとき、項数の最大値を出力してください。', h1: '1,2,3,… と小さい順に使うのが最適。', h2: 'k(k+1)/2 ≤ n を満たす最大の k。余りは最後の項に吸収できる。', ref: 'n=int(input())\nk=0\ns=0\nwhile s+k+1<=n:\n    k+=1\n    s+=k\nprint(k)', tip: '1+2+…+k ≤ n なら余りを最大項に足して調整できるので答えは三角数の逆関数。頻出の貪欲パターン。', ins: ['10\n', '1\n', '5\n', '6\n', '100\n', '2\n'] })

t({ lv: 307, concept: 'DP: ちょうどk個の項への分割数', title: 'ちょうどk個の項に分ける方法の数', tags: ['DP', '数学'], io: 'n k が空白区切りで1行で与えられます。', ask: 'n を順序を区別しない k 個の正整数の和に分ける方法の数 p(n,k) を出力してください。', h1: '最小の項が1かどうかで場合分け。', h2: 'p(n,k)=p(n-1,k-1)+p(n-k,k)。', ref: 'n,k=map(int,input().split())\ndp=[[0]*(k+1) for _ in range(n+1)]\ndp[0][0]=1\nfor i in range(1,n+1):\n    for j in range(1,k+1):\n        dp[i][j]=dp[i-1][j-1]+(dp[i-j][j] if i>=j else 0)\nprint(dp[n][k])', tip: 'p(n,k)=p(n-1,k-1)+p(n-k,k) は「1を含む分割」と「全項から1引ける分割」の二分。分割数p(n)はこの和。', ins: ['5 2\n', '6 3\n', '4 1\n', '10 4\n', '3 3\n', '7 2\n'] })

t({ lv: 308, concept: 'DP: サイコロの和の場合の数', title: 'n個のサイコロで和Sになる場合の数', tags: ['DP'], io: 'n S が空白区切りで1行で与えられます。', ask: '1〜6 の目を持つサイコロを n 個振って目の合計がちょうど S になる出方の数(サイコロは区別する)を出力してください。', h1: 'dp[個数][和] を順に埋める。', h2: '各サイコロで 1〜6 を加えて遷移。', ref: 'n,s=map(int,input().split())\ndp=[1]+[0]*s\nfor _ in range(n):\n    ndp=[0]*(s+1)\n    for v in range(s+1):\n        if dp[v]:\n            for f in range(1,7):\n                if v+f<=s:\n                    ndp[v+f]+=dp[v]\n    dp=ndp\nprint(dp[s])', tip: 'サイコロの和は畳み込みDP。確率を求めるなら最後に 6^n で割るだけ。面の数や個数を変えても同じ形。', ins: ['2 7\n', '1 3\n', '3 5\n', '2 12\n', '3 18\n', '2 1\n'] })

t({ lv: 309, concept: 'DP: 値の削除で得る最大得点', title: '値を消して得る最大得点', tags: ['DP'], io: '正整数の列が1行で空白区切りで与えられます。', ask: '値 v を選ぶと v×(vの出現回数) 点を得るが、値 v-1 と v+1 の要素は全て消える。得られる得点の最大を出力してください。', h1: '値ごとの合計得点を作ると「隣り合う値は同時に取れない」問題になる。', h2: 'House Robber と同じ take/skip の遷移を値1..maxで回す。', ref: 'from collections import Counter\na=list(map(int,input().split()))\nc=Counter(a)\nm=max(a)\ntake,skip=0,0\nfor v in range(1,m+1):\n    take,skip=skip+v*c.get(v,0),max(take,skip)\nprint(max(take,skip))', tip: '一見複雑な削除ルールも「値の軸に集計し直す」と隣接制約のDPに帰着する。', ins: ['3 4 2\n', '2 2 3 3 3 4\n', '1\n', '1 1 1\n', '5 5 6\n', '1 2 3 4 5\n'] })

t({ lv: 310, concept: 'DP: 最短共通超列の長さ', title: '最短共通超列の長さ', tags: ['DP', '文字列'], io: '2行に文字列 s と t が与えられます。', ask: 's と t の両方を部分列として含む最短の文字列(最短共通超列)の長さを出力してください。', h1: 'LCSを求める。', h2: '答えは len(s)+len(t)-LCS。共通部分は1回だけ書けばよい。', ref: 's=input()\nt=input()\nn,m=len(s),len(t)\ndp=[[0]*(m+1) for _ in range(n+1)]\nfor i in range(n):\n    for j in range(m):\n        dp[i+1][j+1]=dp[i][j]+1 if s[i]==t[j] else max(dp[i][j+1],dp[i+1][j])\nprint(n+m-dp[n][m])', tip: '最短共通超列(SCS)はLCSの双対。LCSの文字を共有し、残りを両方から流し込むと最短になる。', ins: ['abac\ncab\n', 'geek\neke\n', 'abc\nabc\n', 'a\nb\n', 'aaa\naa\n', 'abcd\nxycd\n'] })

t({ lv: 311, concept: 'DP: 単語分割の方法数', title: '辞書の単語で分割する方法の数', tags: ['DP', '文字列'], io: '1行目に文字列 s、2行目に辞書の単語が空白区切りで与えられます。', ask: 's を辞書の単語の連結として分割する方法の数を出力してください(同じ単語は何度でも使える)。', h1: 'dp[i]=先頭i文字の分割方法数。', h2: '各 j<i について s[j:i] が辞書語なら dp[j] を加算。', ref: 's=input()\nwords=set(input().split())\nn=len(s)\ndp=[0]*(n+1)\ndp[0]=1\nfor i in range(1,n+1):\n    for j in range(i):\n        if dp[j] and s[j:i] in words:\n            dp[i]+=dp[j]\nprint(dp[n])', tip: '可否判定(Word Break)を数え上げに変えるには bool を整数カウンタにするだけ。DPの可否↔場合の数の典型対応。', ins: ['catsanddog\ncat cats and sand dog\n', 'aaa\na aa\n', 'abc\nx y\n', 'ab\na b ab\n', 'aaaa\na aa\n', 'pen\npen pe n\n'] })

t({ lv: 312, concept: '文字列: 1文字削除で回文', title: '高々1文字削除で回文にできるか', tags: ['文字列', '二点法'], io: '文字列 s が1行で与えられます。', ask: '高々1文字削除して(削除しなくてもよい)回文にできるなら yes、できなければ no を出力してください。', h1: '両端から比較し、最初に食い違った場所で分岐。', h2: '左を飛ばすか右を飛ばすかの2通りだけ試せばよい。', ref: 's=input()\ndef pal(x):\n    return x==x[::-1]\ni,j=0,len(s)-1\nans="yes"\nwhile i<j:\n    if s[i]!=s[j]:\n        ans="yes" if pal(s[i+1:j+1]) or pal(s[i:j]) else "no"\n        break\n    i+=1\n    j-=1\nprint(ans)', tip: '不一致は高々1回しか許されないので、分岐は2通りで尽きる。バックトラックを定数回に抑える典型。', ins: ['abca\n', 'abc\n', 'aba\n', 'deeee\n', 'abcdba\n', 'abccga\n'] })

t({ lv: 313, concept: '文字列: 同型な文字列の判定', title: '2つの文字列が同型か', tags: ['文字列', 'ハッシュ'], io: '2行に同じ長さの文字列 s と t が与えられます。', ask: '文字の一対一の置き換えで s を t に変換できる(同型である)なら yes、できなければ no を出力してください。', h1: 's→t と t→s の両方向の対応表を作る。', h2: '対応が矛盾したら no。', ref: 's=input()\nt=input()\nok=len(s)==len(t)\nif ok:\n    m1={}\n    m2={}\n    for a,b in zip(s,t):\n        if m1.get(a,b)!=b or m2.get(b,a)!=a:\n            ok=False\n            break\n        m1[a]=b\n        m2[b]=a\nprint("yes" if ok else "no")', tip: '片方向の辞書だけだと ab→aa を見逃す。一対一(全単射)の判定は両方向の対応を持つのが鉄則。', ins: ['egg\nadd\n', 'foo\nbar\n', 'paper\ntitle\n', 'ab\naa\n', 'abc\nxyz\n', 'badc\nbaba\n'] })

t({ lv: 314, concept: 'グラフ: 偶数深さの頂点数', title: '根から偶数の深さにある頂点数', tags: ['グラフ'], io: '1行目に頂点数 n、続く n-1 行に木の辺 u v が与えられます。根は頂点1です。', ask: '根からの深さが偶数(根自身は深さ0)の頂点の個数を出力してください。', h1: 'BFSで各頂点の深さを求める。', h2: '深さの偶奇で数える。', ref: 'from collections import deque\nn=int(input())\ng=[[] for _ in range(n+1)]\nfor _ in range(n-1):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\ndist=[-1]*(n+1)\ndist[1]=0\nq=deque([1])\nwhile q:\n    x=q.popleft()\n    for y in g[x]:\n        if dist[y]<0:\n            dist[y]=dist[x]+1\n            q.append(y)\nprint(sum(1 for v in range(1,n+1) if dist[v]%2==0))', tip: '深さの偶奇は木の2彩色そのもの。偶数層と奇数層は独立集合になる(木は二部グラフ)。', ins: ['3\n1 2\n2 3\n', '1\n', '5\n1 2\n1 3\n2 4\n2 5\n', '4\n1 2\n2 3\n3 4\n', '7\n1 2\n1 3\n2 4\n2 5\n3 6\n3 7\n', '2\n1 2\n'] })

t({ lv: 315, concept: 'グラフ: 島の周長', title: '島の周の長さ', tags: ['グラフ', 'グリッド'], io: '1行目に行数 h と列数 w、続く h 行に 0/1 の文字列が与えられます。', ask: '1 のマス全体が作る図形の周の長さ(外周＋穴の縁の合計)を出力してください。', h1: '各1マスの4辺を見る。', h2: '隣が0か盤外ならその辺は周になる。', ref: 'h,w=map(int,input().split())\ng=[input() for _ in range(h)]\np=0\nfor i in range(h):\n    for j in range(w):\n        if g[i][j]=="1":\n            for di,dj in ((1,0),(-1,0),(0,1),(0,-1)):\n                ni,nj=i+di,j+dj\n                if ni<0 or ni>=h or nj<0 or nj>=w or g[ni][nj]=="0":\n                    p+=1\nprint(p)', tip: '周長=4×(1の数)−2×(隣接する1のペア数)。境界を数える問題は「セル単位」でなく「辺単位」で考える。', ins: ['1 1\n1\n', '2 2\n11\n11\n', '1 3\n101\n', '3 3\n010\n111\n010\n', '2 3\n110\n010\n', '1 2\n00\n'] })

t({ lv: 316, concept: 'グラフ: ナイトの最短手数', title: 'ナイトが目的地に着く最短手数', tags: ['グラフ', 'BFS'], io: '1行目に盤の大きさ n、2行目に開始位置 sx sy と目標位置 gx gy (0始まり)が与えられます。', ask: 'n×n 盤でチェスのナイトが開始位置から目標位置へ移動する最短手数を出力してください。到達できなければ -1。', h1: 'ナイトの8方向の跳びでBFS。', h2: '盤外と訪問済みを除いて距離を伝播。', ref: 'from collections import deque\nn=int(input())\nsx,sy,gx,gy=map(int,input().split())\ndist=[[-1]*n for _ in range(n)]\ndist[sx][sy]=0\nq=deque([(sx,sy)])\nwhile q:\n    x,y=q.popleft()\n    for dx,dy in ((1,2),(2,1),(-1,2),(-2,1),(1,-2),(2,-1),(-1,-2),(-2,-1)):\n        nx,ny=x+dx,y+dy\n        if 0<=nx<n and 0<=ny<n and dist[nx][ny]<0:\n            dist[nx][ny]=dist[x][y]+1\n            q.append((nx,ny))\nprint(dist[gx][gy])', tip: '騎士の動きのような特殊な遷移も、辺重みが等しければBFSで最短手数が出る。3×3盤の中央のように孤立するマスもある。', ins: ['8\n0 0 7 7\n', '8\n0 0 1 2\n', '8\n0 0 0 0\n', '3\n0 0 1 1\n', '5\n0 0 4 4\n', '8\n3 3 4 5\n'] })

t({ lv: 317, concept: 'グラフ: DAG最長経路の本数', title: '最長経路の本数 (DAG)', tags: ['グラフ', 'DP'], io: '1行目に頂点数 n と辺数 m、続く m 行に有向辺 u v (DAG)が与えられます。', ask: '辺数が最大の単純経路が何本あるかを出力してください(頂点1つだけの経路は長さ0とみなす)。', h1: 'トポロジカル順に dp[v]=vで終わる最長経路長と本数 cnt[v] を更新。', h2: 'より長い経路が来たら本数を上書き、同じ長さなら加算。', ref: 'from collections import deque\nn,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nindeg=[0]*(n+1)\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    indeg[v]+=1\nq=deque(v for v in range(1,n+1) if indeg[v]==0)\ndp=[0]*(n+1)\ncnt=[1]*(n+1)\nwhile q:\n    x=q.popleft()\n    for y in g[x]:\n        if dp[x]+1>dp[y]:\n            dp[y]=dp[x]+1\n            cnt[y]=cnt[x]\n        elif dp[x]+1==dp[y]:\n            cnt[y]+=cnt[x]\n        indeg[y]-=1\n        if indeg[y]==0:\n            q.append(y)\nL=max(dp[1:n+1])\nprint(sum(cnt[v] for v in range(1,n+1) if dp[v]==L))', tip: '「最大値とその個数」を同時に持つDPは最短路の本数と同じ型。更新(>)で個数リセット、同値(=)で加算。', ins: ['4 4\n1 2\n1 3\n2 4\n3 4\n', '3 2\n1 2\n2 3\n', '2 0\n', '5 5\n1 2\n2 3\n1 4\n4 5\n5 3\n', '6 6\n1 2\n1 3\n2 4\n3 4\n4 5\n4 6\n', '3 3\n1 2\n1 3\n2 3\n'] })

t({ lv: 318, concept: 'グラフ: 木の離心数の総和', title: '全頂点の離心数の合計', tags: ['グラフ', 'BFS'], io: '1行目に頂点数 n、続く n-1 行に木の辺 u v が与えられます。', ask: '各頂点の離心数(その頂点から最も遠い頂点までの距離)の総和を出力してください。', h1: '各頂点からBFSして最遠距離を求める。', h2: 'n回のBFSの最大距離を合計。', ref: 'from collections import deque\nn=int(input())\ng=[[] for _ in range(n+1)]\nfor _ in range(n-1):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\ntotal=0\nfor s in range(1,n+1):\n    dist=[-1]*(n+1)\n    dist[s]=0\n    q=deque([s])\n    while q:\n        x=q.popleft()\n        for y in g[x]:\n            if dist[y]<0:\n                dist[y]=dist[x]+1\n                q.append(y)\n    total+=max(dist[1:n+1])\nprint(total)', tip: '離心数の最大が直径、最小が半径。木なら各頂点の最遠点は必ず直径の端点になる性質で O(n) にもできる。', ins: ['3\n1 2\n2 3\n', '2\n1 2\n', '1\n', '4\n1 2\n1 3\n1 4\n', '5\n1 2\n2 3\n3 4\n4 5\n', '7\n1 2\n1 3\n2 4\n2 5\n3 6\n3 7\n'] })

t({ lv: 319, concept: 'データ構造: 一点更新と区間積', title: '一点更新つき区間の積', tags: ['データ構造'], io: '1行目に n q、2行目に長さ n の正整数列、続く q 行にクエリ「1 i x」(i番目をxに変更) または「2 l r」(積を質問)が与えられます。', ask: '各「2 l r」に対し a[l..r] の積を 1000000007 で割った余りを1行ずつ出力してください。', h1: '更新と区間集約はセグメント木の出番(小さい入力なら素朴でも可)。', h2: '積もモノイドなので和・最小と同じ木構造で扱える。', ref: 'MOD=10**9+7\nn,q=map(int,input().split())\na=list(map(int,input().split()))\nfor _ in range(q):\n    t,x,y=map(int,input().split())\n    if t==1:\n        a[x-1]=y\n    else:\n        p=1\n        for v in a[x-1:y]:\n            p=p*v%MOD\n        print(p)', tip: 'セグメント木は結合的な演算(モノイド)なら何でも載る。和・最小・最大に続き「積 mod p」も同じ型で書ける。', ins: ['3 3\n1 2 3\n2 1 3\n1 2 5\n2 1 3\n', '2 1\n4 5\n2 1 2\n', '3 2\n2 2 2\n2 2 3\n2 1 1\n', '4 3\n1 1 1 1\n1 4 7\n2 3 4\n2 1 4\n', '1 2\n9\n2 1 1\n2 1 1\n', '3 3\n5 1 3\n2 1 3\n1 2 2\n2 1 3\n'] })

t({ lv: 320, concept: 'データ構造: スタック2本で作るキュー', title: '2本のスタックで作るキュー', tags: ['データ構造', 'スタック'], io: '1行目にクエリ数 q、続く q 行に「push x」または「pop」が与えられます(popは空でないときのみ)。', ask: '2本のスタックでFIFOキューを実装したとして、各 pop で取り出される値を1行ずつ出力してください。', h1: '入力用スタックと出力用スタックを使う。', h2: '出力用が空のときだけ入力用を全部移し替えると償却O(1)。', ref: 'q=int(input())\na=[]\nb=[]\nfor _ in range(q):\n    op=input().split()\n    if op[0]=="push":\n        a.append(int(op[1]))\n    else:\n        if not b:\n            while a:\n                b.append(a.pop())\n        print(b.pop())', tip: 'LIFOを2回通すとFIFOになる。移し替えは各要素高々1回なので全体O(n)(償却分析の代表例)。', ins: ['5\npush 1\npush 2\npop\npush 3\npop\n', '3\npush 7\npush 8\npop\n', '6\npush 1\npop\npush 2\npop\npush 3\npop\n', '4\npush 5\npush 6\npop\npop\n', '2\npush 9\npop\n', '7\npush 3\npush 1\npop\npush 4\npop\npop\npush 5\n'] })

t({ lv: 321, concept: 'ヒープ: 最後に残る石の重さ', title: '石の衝突で最後に残る重さ', tags: ['ヒープ'], io: '石の重さの列が1行で空白区切りで与えられます。', ask: '最も重い2つをぶつけ、同じなら両方消え、違えば差の石が残る。これを繰り返して最後に残る石の重さ(残らなければ0)を出力してください。', h1: '最大2つを取り出すのは最大ヒープ。', h2: 'Pythonは最小ヒープなので符号反転で代用。', ref: 'import heapq\na=[-x for x in map(int,input().split())]\nheapq.heapify(a)\nwhile len(a)>1:\n    x=-heapq.heappop(a)\n    y=-heapq.heappop(a)\n    if x>y:\n        heapq.heappush(a,-(x-y))\nprint(-a[0] if a else 0)', tip: 'heapqは最小ヒープのみ。最大ヒープが欲しいときは値を反転して入れるのがPythonの定石。', ins: ['2 7 4 1 8 1\n', '1\n', '3 3\n', '10 4 2\n', '5 5 5\n', '9 3 2 10\n'] })

t({ lv: 322, concept: 'ヒープ: 最大値を半減するk回操作', title: '最大値を半分にするk回操作後の和', tags: ['ヒープ', '貪欲'], io: '1行目に操作回数 k、2行目に正整数列が与えられます。', ask: '「最大の要素を選び、その値を半分(切り捨て)に置き換える」を k 回行った後の総和を出力してください。', h1: '毎回の最大取り出しはヒープ。', h2: '取り出して半分にして戻す。', ref: 'import heapq\nk=int(input())\na=[-x for x in map(int,input().split())]\nheapq.heapify(a)\nfor _ in range(k):\n    x=-heapq.heappop(a)\n    heapq.heappush(a,-(x//2))\nprint(-sum(a))', tip: '「毎回最大(最小)に操作する」シミュレーションはヒープの典型。ソートし直すと O(nk log n) が O(k log n) になる。', ins: ['2\n10 7\n', '1\n8\n', '3\n6 6\n', '0\n5 5\n', '4\n16\n', '2\n3 9 4\n'] })

t({ lv: 323, concept: 'スライディングウィンドウ: ちょうどk種類の部分配列数', title: 'ちょうどk種類の値を含む部分配列の数', tags: ['しゃくとり'], io: '1行目に k、2行目に整数列が与えられます。', ask: '相異なる値がちょうど k 種類含まれる連続部分配列の個数を出力してください。', h1: '「ちょうどk」は「k種類以下の個数 − k-1種類以下の個数」。', h2: 'k種類以下の個数はしゃくとりで、右端ごとに r-l+1 を加算。', ref: 'from collections import defaultdict\nk=int(input())\na=list(map(int,input().split()))\ndef atmost(m):\n    cnt=defaultdict(int)\n    res=0\n    l=0\n    kinds=0\n    for r,x in enumerate(a):\n        if cnt[x]==0:\n            kinds+=1\n        cnt[x]+=1\n        while kinds>m:\n            cnt[a[l]]-=1\n            if cnt[a[l]]==0:\n                kinds-=1\n            l+=1\n        res+=r-l+1\n    return res\nprint(atmost(k)-atmost(k-1))', tip: '「ちょうどk」の窓は単調でないのでしゃくとりが直接効かない。atMost(k)-atMost(k-1) への分解が決定打。', ins: ['2\n1 2 1 2 3\n', '1\n1 1 1\n', '3\n1 2 3\n', '2\n1 1 2\n', '1\n1 2 3\n', '2\n1 2 1\n'] })

t({ lv: 324, concept: 'DP: 符号の割り当てで目標和', title: '+と-を付けて目標を作る方法の数', tags: ['DP'], io: '1行目に目標 T、2行目に整数列が与えられます。', ask: '各要素に + か - を付けて全体の和を T にする方法の数を出力してください。', h1: '到達できる和ごとの場合の数を辞書で持つ。', h2: '各要素で +x と -x の両方に分配する。', ref: 'from collections import defaultdict\nt=int(input())\na=list(map(int,input().split()))\ndp=defaultdict(int)\ndp[0]=1\nfor x in a:\n    ndp=defaultdict(int)\n    for s,c in dp.items():\n        ndp[s+x]+=c\n        ndp[s-x]+=c\n    dp=ndp\nprint(dp[t])', tip: '+群の和をPとすると P=(総和+T)/2 の部分集合和の数え上げに変換できる。', ins: ['3\n1 1 1 1 1\n', '1\n1\n', '0\n1 1\n', '2\n1 2 3\n', '5\n2 3\n', '0\n0 0\n'] })

t({ lv: 325, concept: '数え上げ: 電話キーの文字列数', title: '電話キーで作れる文字列の総数', tags: ['数学'], io: '2〜9 の数字だけからなる文字列が1行で与えられます。', ask: '電話のキー(2=abc, 3=def, 4=ghi, 5=jkl, 6=mno, 7=pqrs, 8=tuv, 9=wxyz)で各数字を文字に置き換えてできる文字列の総数を出力してください。', h1: '各数字の選択肢の数を掛け合わせる。', h2: '7 と 9 は4文字、それ以外は3文字。', ref: 's=input().strip()\np=1\nfor c in s:\n    p*=4 if c in "79" else 3\nprint(p)', tip: '独立な選択の総数は積の法則。組合せ爆発を「列挙せずに数える」のが数え上げの第一歩。', ins: ['23\n', '7\n', '79\n', '2\n', '234\n', '799\n'] })

t({ lv: 326, concept: 'グラフ: 完全グラフの判定', title: '隣接行列が完全グラフか', tags: ['グラフ', '行列'], io: '1行目に頂点数 n、続く n 行に隣接行列(0/1、空白区切り)が与えられます。', ask: 'どの異なる2頂点間にも辺がある(完全グラフ)なら yes、そうでなければ no を出力してください(対角は0であること)。', h1: '対角成分は0、それ以外は全て1か確認。', h2: '1つでも違えば no。', ref: 'n=int(input())\nok=True\nfor i in range(n):\n    row=list(map(int,input().split()))\n    for j in range(n):\n        if i==j and row[j]!=0:\n            ok=False\n        if i!=j and row[j]!=1:\n            ok=False\nprint("yes" if ok else "no")', tip: '完全グラフ K_n の辺数は n(n-1)/2。隣接行列なら「対角0・他は全部1」という形の検査になる。', ins: ['3\n0 1 1\n1 0 1\n1 1 0\n', '2\n0 0\n0 0\n', '1\n0\n', '3\n0 1 0\n1 0 1\n0 1 0\n', '2\n0 1\n1 0\n', '3\n1 1 1\n1 0 1\n1 1 0\n'] })

t({ lv: 327, concept: '数論: 二重階乗', title: '二重階乗 n!!', tags: ['数学'], io: '非負整数 n が1行で与えられます。', ask: 'n!! (n から2ずつ減らした正の整数の積。0!!=1!!=1) を出力してください。', h1: 'n, n-2, n-4, … を掛ける。', h2: '1以下になったら止める。', ref: 'n=int(input())\np=1\nwhile n>1:\n    p*=n\n    n-=2\nprint(p)', tip: '二重階乗は組合せ論や積分の漸化式に頻出。(2n)!!=2^n·n!、(2n-1)!!=(2n)!/(2^n·n!) の関係がある。', ins: ['5\n', '6\n', '0\n', '1\n', '8\n', '9\n'] })

t({ lv: 328, concept: '二点法: 配列を回文にする最小併合回数', title: '隣接併合で回文にする最小回数', tags: ['二点法', '貪欲'], io: '正整数列が1行で空白区切りで与えられます。', ask: '隣り合う2要素をその和で置き換える「併合」だけを使い、配列を回文にするための最小併合回数を出力してください。', h1: '両端の値を比べる。等しければ内側へ。', h2: '小さい側を隣と併合して大きい側に追いつかせるのが最適。', ref: 'a=list(map(int,input().split()))\ni,j=0,len(a)-1\nops=0\nx,y=a[0],a[-1]\nwhile i<j:\n    if x==y:\n        i+=1\n        j-=1\n        if i<=j:\n            x,y=a[i],a[j]\n    elif x<y:\n        i+=1\n        x+=a[i]\n        ops+=1\n    else:\n        j-=1\n        y+=a[j]\n        ops+=1\nprint(ops)', tip: '両端固定の貪欲が最適なのは「端の小さい方は必ずいつか併合される」から。交換論法で証明できる典型。', ins: ['1 4 1\n', '1 2\n', '11 14 15 99\n', '1 2 3 4 3\n', '5\n', '3 6 2 1\n'] })

t({ lv: 329, concept: '貪欲: 連結の辞書順最小化', title: '連結して辞書順最小になる並べ方', tags: ['貪欲', '文字列'], io: '英小文字の単語が1行で空白区切りで与えられます。', ask: '全ての単語を並べ替えて連結した文字列のうち辞書順最小のものを出力してください。', h1: '単純な辞書順ソートでは b と ba の順を誤る。', h2: 'a+b と b+a を比べる比較関数でソートする。', ref: 'from functools import cmp_to_key\nws=input().split()\nws.sort(key=cmp_to_key(lambda a,b:-1 if a+b<b+a else (1 if a+b>b+a else 0)))\nprint("".join(ws))', tip: '「連結結果で比較」(a+b vs b+a)は推移律を満たすので全体最適になる。最大の数を作る問題と同じ技。', ins: ['b ba\n', 'c cb\n', 'a b c\n', 'xa xb x\n', 'ab a\n', 'ba b a\n'] })

t({ lv: 330, concept: '行列: 対角線ジグザグ走査', title: '行列の対角線ジグザグ走査', tags: ['行列'], io: '1行目に h w、続く h 行に行列が与えられます。', ask: '左上から対角線に沿って、右上向きと左下向きを交互に往復しながら全要素を読む順序で空白区切りで出力してください。', h1: '反対角線は i+j が一定。', h2: 'i+j の偶奇で走る向きを切り替える。', ref: 'h,w=map(int,input().split())\nm=[list(map(int,input().split())) for _ in range(h)]\nres=[]\nfor s in range(h+w-1):\n    if s%2==0:\n        i=min(s,h-1)\n        j=s-i\n        while i>=0 and j<w:\n            res.append(m[i][j])\n            i-=1\n            j+=1\n    else:\n        j=min(s,w-1)\n        i=s-j\n        while j>=0 and i<h:\n            res.append(m[i][j])\n            i+=1\n            j-=1\nprint(*res)', tip: '対角線ごとの分解は i+j(反対角線)・i-j(対角線)が不変量という見方。走査問題の多くはこの座標変換で単純化する。', ins: ['3 3\n1 2 3\n4 5 6\n7 8 9\n', '1 1\n5\n', '2 2\n1 2\n3 4\n', '1 4\n1 2 3 4\n', '4 1\n1\n2\n3\n4\n', '2 3\n1 2 3\n4 5 6\n'] })

t({ lv: 331, concept: '数: スミス数の判定', title: 'スミス数かどうか', tags: ['数論'], io: '2以上の整数 n が1行で与えられます。', ask: 'n が合成数で、n の桁和が素因数(重複込み)の桁和の合計に等しいなら yes、そうでなければ no を出力してください。', h1: '素因数分解しながら各素因数の桁和を足す。', h2: '素数は自明に等しくなるので除外する。', ref: 'n=int(input())\ndef ds(x):\n    return sum(int(c) for c in str(x))\nm=n\ntotal=0\nf=2\ncnt=0\nwhile f*f<=m:\n    while m%f==0:\n        total+=ds(f)\n        m//=f\n        cnt+=1\n    f+=1\nif m>1:\n    total+=ds(m)\n    cnt+=1\nprint("yes" if cnt>1 and ds(n)==total else "no")', tip: 'スミス数(4,22,27,58,85,94,…)は義兄の電話番号 4937775 から命名された。素因数の「重複込み」が定義のポイント。', ins: ['4\n', '22\n', '12\n', '7\n', '666\n', '85\n'] })

t({ lv: 332, concept: '数論: -2進法表記', title: '-2進法(ネガバイナリ)で表す', tags: ['数学'], io: '非負整数 n が1行で与えられます。', ask: 'n を基数 -2 の位取り記数法(各桁は0か1)で表した文字列を出力してください。', h1: '通常の基数変換と同じく余りを取るが、商は -2 で割る。', h2: 'Pythonでは r=n%2、n=-(n//2) を繰り返すと正しい桁が出る。', ref: 'n=int(input())\nif n==0:\n    print(0)\nelse:\n    s=""\n    while n!=0:\n        r=n%2\n        n=-(n//2)\n        s=str(r)+s\n    print(s)', tip: '負の基数では負数も符号なしで表せる。Pythonの % が常に非負を返す性質がここで効く。', ins: ['2\n', '3\n', '0\n', '6\n', '1\n', '10\n'] })

t({ lv: 333, concept: '数論: フィボナッチ数の最大公約数', title: '2つのフィボナッチ数のGCD', tags: ['数論'], io: 'm n が空白区切りで1行で与えられます(F(1)=1, F(2)=1, …)。', ask: 'm番目とn番目のフィボナッチ数の最大公約数を出力してください。', h1: 'F(m) と F(n) を生成して gcd を取る。', h2: '実は gcd(F(m),F(n))=F(gcd(m,n)) が成り立つ。', ref: 'import math\nm,n=map(int,input().split())\ndef fib(k):\n    a,b=0,1\n    for _ in range(k):\n        a,b=b,a+b\n    return a\nprint(math.gcd(fib(m),fib(n)))', tip: 'フィボナッチ数は gcd(F(m),F(n))=F(gcd(m,n)) という美しい性質を持つ(強可除列)。ユークリッドの互除法と相性が良い。', ins: ['6 9\n', '10 15\n', '7 11\n', '12 18\n', '5 5\n', '1 2\n'] })

t({ lv: 334, concept: '数: カプレカ数の判定', title: 'カプレカ数かどうか', tags: ['数学'], io: '正整数 n が1行で与えられます。', ask: 'n の2乗を10進で書き、下位を n の桁数ぶん、残りを上位として2つに分けたとき、両者の和が n に等しい(カプレカ数)なら yes、違えば no を出力してください。', h1: 'd = n の桁数。n² を 10^d で割った商と余りに分ける。', h2: '商+余り==n を確認。', ref: 'n=int(input())\nd=len(str(n))\nsq=n*n\nq,r=divmod(sq,10**d)\nprint("yes" if q+r==n else "no")', tip: '45²=2025 → 20+25=45。divmod は商と余りを同時に返すので桁分割に便利。カプレカ操作(495/6174)とは別の概念。', ins: ['45\n', '9\n', '10\n', '297\n', '1\n', '7\n'] })

t({ lv: 335, concept: '数論: N以下の過剰数の個数', title: 'N以下の過剰数を数える', tags: ['数論'], io: '正整数 N が1行で与えられます。', ask: '1 以上 N 以下の過剰数(自分を除く約数の和が自分より大きい数)の個数を出力してください。', h1: '各数の約数和を √x までの試し割りで求める。', h2: '約数和-自分 > 自分 を数える。', ref: 'n=int(input())\ncnt=0\nfor x in range(1,n+1):\n    s=0\n    d=1\n    while d*d<=x:\n        if x%d==0:\n            s+=d\n            if d!=x//d:\n                s+=x//d\n        d+=1\n    if s-x>x:\n        cnt+=1\nprint(cnt)', tip: '最小の過剰数は12。奇数の過剰数は945まで現れない。範囲が大きいときは篩の要領で約数和を前計算する。', ins: ['20\n', '11\n', '12\n', '100\n', '50\n', '1\n'] })

t({ lv: 336, concept: 'ソート: 1回の交換でソート可能か', title: '高々1回の交換でソートできるか', tags: ['ソート'], io: '整数列が1行で空白区切りで与えられます。', ask: '高々1回、2要素を交換するだけで非減少に並べられるなら yes、できなければ no を出力してください。', h1: 'ソート済みの列と比較する。', h2: '食い違う位置が0個か2個ならyes。', ref: 'a=list(map(int,input().split()))\nb=sorted(a)\ndiff=[i for i in range(len(a)) if a[i]!=b[i]]\nprint("yes" if len(diff)==0 or len(diff)==2 else "no")', tip: '「正解の形(ソート済み)との差分」を取ると判定が一瞬。差分位置が2つなら交換でちょうど直る。', ins: ['1 5 3 4 2\n', '1 2 3\n', '3 2 1\n', '2 1 4 3\n', '1 1 1\n', '4 1 2 3\n'] })

t({ lv: 337, concept: '二点法: 2本の壁の最大水量', title: '2本の壁が囲う最大の水量', tags: ['二点法'], io: '壁の高さの列が1行で空白区切りで与えられます(2本以上)。', ask: '2本の壁 i<j を選んだときに溜められる水量 (j-i)×min(高さi, 高さj) の最大値を出力してください。', h1: '両端から始めて内側へ狭める。', h2: '低い方の壁を動かす。高い方を動かしても改善しない。', ref: 'h=list(map(int,input().split()))\ni,j=0,len(h)-1\nbest=0\nwhile i<j:\n    best=max(best,(j-i)*min(h[i],h[j]))\n    if h[i]<h[j]:\n        i+=1\n    else:\n        j-=1\nprint(best)', tip: '低い方を捨てる正当性: その壁が作る他のどの組も今より幅が狭く高さも伸びない。O(n²)をO(n)にする交換論法。', ins: ['1 8 6 2 5 4 8 3 7\n', '1 1\n', '4 3 2 1 4\n', '1 2 1\n', '2 1\n', '3 9 3\n'] })

t({ lv: 338, concept: '累積和: 和が0の連続部分配列の個数', title: '和が0になる連続部分配列の数', tags: ['累積和', 'ハッシュ'], io: '整数列が1行で空白区切りで与えられます。', ask: '要素の和が0になる連続部分配列の個数を出力してください。', h1: '累積和が同じ値になる2点の間は和が0。', h2: '累積和の出現回数を辞書で数え、同じ値を見るたび回数を加算。', ref: 'from collections import defaultdict\na=list(map(int,input().split()))\ncnt=defaultdict(int)\ncnt[0]=1\ns=0\nans=0\nfor x in a:\n    s+=x\n    ans+=cnt[s]\n    cnt[s]+=1\nprint(ans)', tip: '「区間和=2つの累積和の差」により、同じ累積和のペア数 C(k,2) の合計が答えになる。和がKの個数も同じ型。', ins: ['1 -1 2 -2\n', '0 0\n', '1 2 3\n', '3 -3\n', '1 -1 1 -1\n', '5\n'] })

t({ lv: 339, concept: '行列: 行和と列和が等しいセル数', title: '行の和と列の和が一致するセル数', tags: ['行列'], io: '1行目に h w、続く h 行に行列が与えられます。', ask: 'セル (i,j) のうち、i 行目の合計と j 列目の合計が等しいものの個数を出力してください。', h1: '行和と列和を前計算する。', h2: '全セルを見て比較。', ref: 'h,w=map(int,input().split())\nm=[list(map(int,input().split())) for _ in range(h)]\nrs=[sum(r) for r in m]\ncs=[sum(m[i][j] for i in range(h)) for j in range(w)]\nprint(sum(1 for i in range(h) for j in range(w) if rs[i]==cs[j]))', tip: '行和・列和の前計算で O(hw(h+w)) が O(hw) に落ちる。集計の再利用は2次元問題の基本動作。', ins: ['2 2\n1 2\n3 4\n', '2 2\n1 1\n1 1\n', '2 3\n1 2 3\n3 2 1\n', '1 1\n5\n', '3 3\n1 0 0\n0 1 0\n0 0 1\n', '2 2\n1 2\n2 1\n'] })

t({ lv: 340, concept: 'スタック: 小惑星の衝突', title: '小惑星の衝突シミュレーション', tags: ['スタック'], io: '0でない整数列が1行で空白区切りで与えられます。正は右向き、負は左向きに動く小惑星の大きさです。', ask: '右向きと左向きがぶつかると小さい方が消え(同じなら両方消える)、全衝突後に残る小惑星を順に空白区切りで出力してください。何も残らなければ none と出力してください。', h1: '左向きの小惑星が来たときだけ衝突が起きる。', h2: 'スタックの右向きとぶつけ続け、生き残れば積む。', ref: 'a=list(map(int,input().split()))\nst=[]\nfor x in a:\n    alive=True\n    while alive and x<0 and st and st[-1]>0:\n        if st[-1]<-x:\n            st.pop()\n        elif st[-1]==-x:\n            st.pop()\n            alive=False\n        else:\n            alive=False\n    if alive:\n        st.append(x)\nprint(*(st if st else ["none"]))', tip: '「後から来たものが前のものを消すかも」という処理はスタックの合図。括弧の対消滅や株価スパンと同じ骨格。', ins: ['5 10 -5\n', '8 -8\n', '10 2 -5\n', '-2 -1 1 2\n', '1 -2 3\n', '3 -3 -3\n'] })

t({ lv: 341, concept: '文字列: 全文字を含む最短の窓', title: '指定文字を全部含む最短部分文字列', tags: ['文字列', 'しゃくとり'], io: '1行目に文字列 s、2行目に文字列 t が与えられます。', ask: 't の全文字を(重複も数えて)含む s の最短の連続部分文字列の長さを出力してください。存在しなければ 0。', h1: '不足文字数 missing を持ちながら右端を進める。', h2: 'missing が0になったら左端を縮めて最短を更新。', ref: 'from collections import Counter\ns=input()\nt=input()\nneed=Counter(t)\nmissing=len(t)\nbest=len(s)+1\nl=0\nfor r,c in enumerate(s):\n    if need[c]>0:\n        missing-=1\n    need[c]-=1\n    while missing==0:\n        if r-l+1<best:\n            best=r-l+1\n        need[s[l]]+=1\n        if need[s[l]]>0:\n            missing+=1\n        l+=1\nprint(best if best<=len(s) else 0)', tip: '最小ウィンドウ部分文字列の典型。Counterを負まで減らし「不足数」だけ別に持つと判定がO(1)になる。', ins: ['ADOBECODEBANC\nABC\n', 'a\na\n', 'a\naa\n', 'aabbcc\nabc\n', 'abcabc\ncba\n', 'hello\nll\n'] })

t({ lv: 342, concept: 'スタック: 重複を除いた辞書順最小', title: '各文字1回で辞書順最小の部分列', tags: ['スタック', '貪欲', '文字列'], io: '英小文字の文字列が1行で与えられます。', ask: '現れる文字をそれぞれちょうど1回ずつ含む部分列のうち、辞書順最小のものを出力してください。', h1: '単調増加スタックに積む。今の文字より大きく、かつ後ろにまだ出てくる文字は捨てられる。', h2: '各文字の最終出現位置を前計算し、採用済み集合も持つ。', ref: 's=input()\nlast={c:i for i,c in enumerate(s)}\nst=[]\nused=set()\nfor i,c in enumerate(s):\n    if c in used:\n        continue\n    while st and st[-1]>c and last[st[-1]]>i:\n        used.remove(st.pop())\n    st.append(c)\n    used.add(c)\nprint("".join(st))', tip: '捨ててよい条件は「後ろに再出現する」こと。単調スタック+最終出現位置は重複文字を除いた辞書順最小化の核。', ins: ['bcabc\n', 'cbacdcbc\n', 'a\n', 'abacb\n', 'zyx\n', 'abab\n'] })

t({ lv: 343, concept: '貪欲: 評点に応じた最小のキャンディ', title: '隣より高評価へ多く配る最小個数', tags: ['貪欲'], io: '子供の評点の列が1行で空白区切りで与えられます。', ask: '各子供に1個以上配り、隣より評点が高い子はその隣より多くもらうという条件で、配るキャンディの最小総数を出力してください。', h1: '左から「左隣より高ければ+1」で走査。', h2: '右からも同様に走査して max を取る。', ref: 'r=list(map(int,input().split()))\nn=len(r)\nc=[1]*n\nfor i in range(1,n):\n    if r[i]>r[i-1]:\n        c[i]=c[i-1]+1\nfor i in range(n-2,-1,-1):\n    if r[i]>r[i+1]:\n        c[i]=max(c[i],c[i+1]+1)\nprint(sum(c))', tip: '左右の制約が絡むときは「左だけ満たす解」と「右だけ満たす解」のmaxを取ると両方満たす。', ins: ['1 0 2\n', '1 2 2\n', '1 2 3\n', '3 2 1\n', '1\n', '1 3 2 2 1\n'] })

export const CATALOG = TASKS
