// 生成タスク 第64波：各レベル2問化フェーズ(19)。lv766〜790 に2問目を追加。
// ハッシュ/文字列/数え上げ帯。重複なし・決定的・採点一意。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 766, concept: '文字列: 禁止語以外の最頻単語', title: '禁止リストを除いた一番人気の単語', tags: ['文字列', 'ハッシュ'], io: '1行目に文章(小文字の単語の空白区切り)、2行目に禁止語が空白区切りで与えられます(禁止語以外が必ず存在)。', ask: '禁止語を除いて最も多く現れる単語を出力してください(同数なら辞書順最小)。', h1: '禁止語を集合にして数え歩く。', h2: '最頻タイの処理は (−回数, 単語) の最小で選ぶと1行になる。', ref: 'words=input().split()\nban=set(input().split())\nfrom collections import Counter\nc=Counter(w for w in words if w not in ban)\nprint(min(c.items(),key=lambda kv:(-kv[1],kv[0]))[0])', tip: '除外集合を先に作ってから集計するとロジックが混ざらない。「タイは辞書順」は(−頻度, 単語)のタプル比較で書くのがPython流。', ins: ['the cat and the hat\nthe\n', 'a a b b\nb\n', 'x y z\nq\n', 'dog dog cat cat bird\nbird\n', 'a b a b c\nc\n', 'one\ntwo\n'] })

t({ lv: 767, concept: '数え上げ: 部分配列GCDの種類数', title: '区間のGCDは何種類あるか', tags: ['数え上げ', '数論'], io: '正整数列が1行で空白区切りで与えられます。', ask: '全ての連続部分配列のGCD(最大公約数)として現れる相異なる値の個数を出力してください。', h1: '右端を伸ばすとGCDは減るだけ。', h2: '「iで終わる区間のGCDの集合」は前の集合の各値と a[i] のgcdで作れ、サイズは log 程度に潰れる。', ref: 'import math\na=list(map(int,input().split()))\nall_=set()\nprev=set()\nfor x in a:\n    prev={math.gcd(p,x) for p in prev}\n    prev.add(x)\n    all_|=prev\nprint(len(all_))', tip: 'GCDは単調に割る方向へしか動かないので、末尾固定の集合が対数サイズで収まる。ORやANDでも同じ骨格が動く「単調収束の集合DP」。', ins: ['4 6 12\n', '2 4 8\n', '1 1 1\n', '6 10 15\n', '7\n', '9 6 3 12\n'] })

t({ lv: 768, concept: '数え上げ: 和が0の区間の個数', title: '合計が0になる区間を数える', tags: ['数え上げ', '累積和'], io: '整数列が1行で空白区切りで与えられます。', ask: '要素の合計が0の空でない連続部分配列の個数を出力してください。', h1: '接頭辞和が等しい2点の間が和0。', h2: '接頭辞和ごとの出現回数を辞書で数え、C(回数,2) の合計…を走査しながら足す。', ref: 'from collections import Counter\na=list(map(int,input().split()))\nc=Counter([0])\ns=0\ncnt=0\nfor x in a:\n    s+=x\n    cnt+=c[s]\n    c[s]+=1\nprint(cnt)', tip: '「同じ接頭辞和の再会」を数える定石。初期値 c[0]=1 (空の接頭辞)を忘れると先頭から始まる区間を数え漏らす。', ins: ['1 -1 2 -2\n', '0 0 0\n', '1 2 3\n', '3 -3\n', '1 -1 1 -1\n', '5\n'] })

t({ lv: 769, concept: '文字列: 逐次の最初の一意文字', title: 'ストリームの先頭非重複文字', tags: ['文字列', 'ハッシュ'], io: '英小文字の文字列が1行で与えられます(文字が1つずつ届くとみなす)。', ask: '各文字が届いた時点での「最初の、1回しか現れていない文字」を並べた文字列を出力してください(存在しない時点は #)。', h1: '候補をキューで持つ。', h2: '重複した文字はキューの先頭から捨てる(遅延削除)。先頭が常に答え。', ref: 'from collections import deque,Counter\ns=input()\ncnt=Counter()\nq=deque()\nout=[]\nfor ch in s:\n    cnt[ch]+=1\n    q.append(ch)\n    while q and cnt[q[0]]>1:\n        q.popleft()\n    out.append(q[0] if q else "#")\nprint("".join(out))', tip: 'キュー+遅延削除は「先頭だけ正しければよい」データの持ち方。全履歴を再走査せずO(1)償却で先頭非重複が追える、ストリーム処理の小技。', ins: ['aabc\n', 'abc\n', 'aa\n', 'abac\n', 'z\n', 'aabbcc\n'] })

t({ lv: 770, concept: '数え上げ: 2倍を超えて上回る逆転ペア', title: '相手の2倍より大きいペア', tags: ['数え上げ'], io: '整数列が1行で空白区切りで与えられます。', ask: 'i<j で a[i] が 2×a[j] より大きいペアの個数を出力してください。', h1: '普通の転倒数の条件を変えただけ。', h2: '小さい入力は2重ループ。大規模はマージソート中に「左の値>2×右の値」を別走査で数える。', ref: 'a=list(map(int,input().split()))\nn=len(a)\ncnt=0\nfor i in range(n):\n    for j in range(i+1,n):\n        if a[i]>2*a[j]:\n            cnt+=1\nprint(cnt)', tip: '逆転ペア(reverse pairs)は条件が非対称なので、マージソートでは「数える走査」と「併合する走査」を分けるのがコツ。BIT+座標圧縮でも解ける。', ins: ['1 3 2 3 1\n', '2 4 3 5 1\n', '1 2 3\n', '5 1\n', '0 0 0\n', '8 4 2 1\n'] })

t({ lv: 771, concept: 'ソート済み: 4分の1超の要素', title: 'ソート済み配列の1/4超の値', tags: ['配列'], io: '昇順にソートされた整数列が1行で与えられます(全体の1/4を厳密に超えて現れる値がちょうど1つ存在)。', ask: 'その値を出力してください。', h1: 'ソート済みなら候補は限られる。', h2: '1/4超なら位置 n/4, n/2, 3n/4 のどれかに必ず現れる。その3候補の実際の頻度を二分探索(bisect)で確かめる。', ref: 'import bisect\na=list(map(int,input().split()))\nn=len(a)\nfor cand in (a[n//4],a[n//2],a[3*n//4]):\n    lo=bisect.bisect_left(a,cand)\n    hi=bisect.bisect_right(a,cand)\n    if 4*(hi-lo)>n:\n        print(cand)\n        break', tip: '「1/k超なら等間隔のk−1点のどこかに必ず顔を出す」鳩ノ巣の使い方。候補を絞ってから検証する2段構えでO(log n)になる。', ins: ['1 2 2 6 6 6 6 7 10\n', '1 1\n', '1 2 3 3\n', '5 5 5 5\n', '0 0 0 1 2 3\n', '1 2 3 4 5 6 7 7 7 7 7 8\n'] })

t({ lv: 772, concept: '文字列: 低頻度文字の除去', title: 'k回未満の文字を消す', tags: ['文字列', 'ハッシュ'], io: '1行目に k、2行目に英小文字の文字列が与えられます。', ask: '出現回数が k 回未満の文字を全て取り除いた文字列を出力してください(空になったら empty)。', h1: 'まず頻度表を作る。', h2: '2周目で頻度が k 以上の文字だけ残す。', ref: 'k=int(input())\ns=input()\nfrom collections import Counter\nc=Counter(s)\nres="".join(ch for ch in s if c[ch]>=k)\nprint(res if res else "empty")', tip: '「数える1周目・使う2周目」の2パス構成はストリームでないデータの基本形。順序を保った選別は join+genexp が最短で書ける。', ins: ['2\naabbcde\n', '1\nabc\n', '3\naabb\n', '2\nabab\n', '5\nzzzzz\n', '2\nxyz\n'] })

t({ lv: 773, concept: '区間: 全てと交わる区間の数', title: 'みんなと重なる区間はいくつ', tags: ['区間'], io: '1行目に区間の数 n、続く n 行に区間 l r が与えられます。', ask: '他の全ての区間と共通部分を持つ区間の個数を出力してください。', h1: '全区間と交わる条件を1つの区間で表す。', h2: '[max(l), min(r)] と交わるかを見ればよい(自分自身も含めて条件は同じ)。', ref: 'n=int(input())\niv=[tuple(map(int,input().split())) for _ in range(n)]\nL=max(l for l,r in iv)\nR=min(r for l,r in iv)\nprint(sum(1 for l,r in iv if l<=R and L<=r))', tip: '「全てと交わる」⇔「最大の左端と最小の右端の区間と交わる」への圧縮が効く。n個との条件がたった1個との条件に潰れる、順序統計の魔法。', ins: ['3\n1 5\n2 6\n3 7\n', '2\n1 2\n3 4\n', '3\n1 10\n2 3\n5 6\n', '1\n5 5\n', '4\n1 4\n2 5\n3 6\n4 7\n', '3\n1 2\n2 3\n3 4\n'] })

t({ lv: 774, concept: '数え上げ: 最大値がちょうどkの区間数', title: '一番大きい値がちょうどkの区間', tags: ['数え上げ'], io: '1行目に k、2行目に正整数列が与えられます。', ask: '区間内の最大値がちょうど k である連続部分配列の個数を出力してください。', h1: '「最大がk以下」なら数えやすい。', h2: '「k以下の区間数」−「k−1以下の区間数」。閾値を超える要素で列を分断して各ランの長さから数える。', ref: 'k=int(input())\na=list(map(int,input().split()))\ndef atmost(t):\n    total=0\n    run=0\n    for x in a:\n        if x<=t:\n            run+=1\n            total+=run\n        else:\n            run=0\n    return total\nprint(atmost(k)-atmost(k-1))', tip: '「ちょうど=以下の差」はしゃくとり数え上げの万能変換。分断とランの数え上げの組み合わせは最大・最小・範囲の条件すべてに流用できる。', ins: ['2\n1 2 3\n', '3\n3 3 3\n', '1\n2 2\n', '2\n2 1 2\n', '5\n1 5 1 5\n', '4\n1 2 3 4 3 2 1\n'] })

t({ lv: 775, concept: 'シミュレーション: 1次元セルオートマトンの1歩', title: 'ルール90をkステップ進める', tags: ['シミュレーション', 'bit演算'], io: '1行目にステップ数 k、2行目に0/1の文字列(セルの状態、両端の外は常に0)が与えられます。', ask: '各セルの次状態が「左右の隣のXOR」となるルールで k ステップ進めた状態の文字列を出力してください。', h1: '1ステップは新しい配列を作って埋める。', h2: '端は外側を0とみなす。kステップは単純に繰り返す。', ref: 'k=int(input())\ns=input()\nn=len(s)\na=[int(c) for c in s]\nfor _ in range(k):\n    a=[(a[i-1] if i>0 else 0)^(a[i+1] if i<n-1 else 0) for i in range(n)]\nprint("".join(map(str,a)))', tip: 'ルール90はXORの線形性からパスカル三角形 mod 2(シェルピンスキー模様)を描く。状態遷移が線形なら行列(GF(2))のべき乗で一気に飛ばせる。', ins: ['1\n00100\n', '2\n00100\n', '1\n1\n', '3\n0001000\n', '1\n1111\n', '2\n10\n'] })

t({ lv: 776, concept: '数え上げ: 同じ値のペアの数', title: 'おそろいのペアを数える', tags: ['数え上げ', 'ハッシュ'], io: '整数列が1行で空白区切りで与えられます。', ask: 'i<j で a[i] と a[j] が等しいペアの個数を出力してください。', h1: '値ごとの個数 c から C(c,2) を足す。', h2: '走査しながら「これまでの同じ値の個数」を足していく方法なら1パス。', ref: 'from collections import Counter\na=list(map(int,input().split()))\nseen=Counter()\ncnt=0\nfor x in a:\n    cnt+=seen[x]\n    seen[x]+=1\nprint(cnt)', tip: '「過去の同類の数を足してから自分を登録」は、等値ペア・条件付きペアの数え上げに共通するオンライン集計の型。C(c,2)の一括計算と答えは一致する。', ins: ['1 2 3 1 1 3\n', '1 1 1 1\n', '1 2 3\n', '5\n', '2 2\n', '4 4 4 5 5\n'] })

t({ lv: 777, concept: '文字列: 1回だけの文字を順に残す', title: '一度きりの文字だけ拾う', tags: ['文字列', 'ハッシュ'], io: '英小文字の文字列が1行で与えられます。', ask: '文字列中にちょうど1回しか現れない文字だけを、元の順のまま並べて出力してください(無ければ empty)。', h1: '頻度表を先に作る。', h2: '頻度1の文字だけ通すフィルタを2周目でかける。', ref: 's=input()\nfrom collections import Counter\nc=Counter(s)\nres="".join(ch for ch in s if c[ch]==1)\nprint(res if res else "empty")', tip: '一意な要素の抽出は集計→選別の2パスが素直。頻度条件を「==1」から「>=k」「素数回」へ変えても1文字も書き直しにならない設計が良い設計。', ins: ['abcabd\n', 'aabb\n', 'abc\n', 'aabbc\n', 'x\n', 'abba\n'] })

t({ lv: 778, concept: '数え上げ: 同数の束に分ける最大サイズ', title: '同じ大きさの束に完全に分ける', tags: ['数え上げ', '数論'], io: 'カードの値の列が1行で空白区切りで与えられます。', ask: '同じ値だけからなる束に分け、全ての束の大きさを同じにするときの、束の大きさの最大を出力してください。', h1: '各値の枚数を束サイズで割り切れる必要がある。', h2: '答えは全頻度のGCD。', ref: 'import math\nfrom collections import Counter\na=input().split()\nc=Counter(a)\ng=0\nfor v in c.values():\n    g=math.gcd(g,v)\nprint(g)', tip: '「全てを割り切る最大」と聞こえたら頻度のGCD。gcdの畳み込みは初期値0から始めると gcd(0,x)=x で自然に立ち上がる。', ins: ['1 2 3 4 4 3 2 1\n', '1 1 1 2 2 2\n', '1\n', '5 5 5 5\n', '1 1 2 2 2\n', '7 7 7 7 8 8\n'] })

t({ lv: 779, concept: 'ハッシュ: 和が0になるペアの最大組数', title: '打ち消し合うペアを最大限つくる', tags: ['ハッシュ'], io: '整数列が1行で空白区切りで与えられます。', ask: '和が0になる2要素のペア(各要素は1つのペアにしか入れない)を最大何組作れるかを出力してください。', h1: 'xと−xの在庫の少ない方だけ組める。', h2: '正の値ごとに min(count(x), count(−x))、0は count//2。', ref: 'from collections import Counter\na=list(map(int,input().split()))\nc=Counter(a)\npairs=c[0]//2\nfor x in list(c):\n    if x>0:\n        pairs+=min(c[x],c[-x])\nprint(pairs)', tip: '0だけが「自分自身と組む」特異点で //2 になる。相方が決まっているマッチングは最大化も貪欲(在庫のmin)で確定する。', ins: ['1 -1 2 -2\n', '0 0 0\n', '1 1 -1\n', '3 4 5\n', '2 -2 2 -2 2\n', '0\n'] })

t({ lv: 780, concept: 'bit演算: XORが0の最長区間', title: 'XORして消える最長の区間', tags: ['bit演算', 'ハッシュ'], io: '非負整数の列が1行で空白区切りで与えられます。', ask: '全要素のXORが0になる連続部分配列の最大の長さを出力してください(無ければ0)。', h1: '接頭辞XORが同じ2点の間はXOR 0。', h2: '各接頭辞XOR値の「最初の出現位置」を辞書に覚え、再会したときの距離の最大を取る。', ref: 'a=list(map(int,input().split()))\nfirst={0:-1}\nx=0\nbest=0\nfor i,v in enumerate(a):\n    x^=v\n    if x in first:\n        if i-first[x]>best:\n            best=i-first[x]\n    else:\n        first[x]=i\nprint(best)', tip: '和が0の最長区間と同じ「初出位置の辞書」がXORでもそのまま動く。累積量の再会=区間の消滅、という見方は群構造があれば常に有効。', ins: ['1 2 3\n', '1 1\n', '1 2 3 4\n', '5\n', '0 0 0\n', '3 3 3 3\n'] })

t({ lv: 781, concept: '文字列: 単語列の回文判定', title: '単語の並びとして回文か', tags: ['文字列'], io: '単語が空白区切りで1行に与えられます。', ask: '単語の並びを逆順にしても同じ(単語単位の回文)なら yes、そうでなければ no を出力してください。', h1: '文字でなく単語のリストで比べる。', h2: 'split したリストと反転の比較1発。', ref: 'w=input().split()\nprint("yes" if w==w[::-1] else "no")', tip: '回文判定は「何を1単位とみなすか」で別問題になる。文字→単語→段落と単位を差し替えても、リスト化して反転比較という骨格は不変。', ins: ['king queen king\n', 'a b b a\n', 'hello world\n', 'x\n', 'a b a b\n', 'one two two one\n'] })

t({ lv: 782, concept: '数え上げ: 回文になる並べ替えの数', title: '回文の並べ替えは何通りか', tags: ['数え上げ', '数学'], io: '英小文字の文字列が1行で与えられます。', ask: '文字を並べ替えてできる相異なる回文の個数を出力してください(作れなければ0)。', h1: '奇数回の文字が2種類以上なら0。', h2: '半分側の多重集合の並べ方 (Σc/2)! / Π(c/2)! が答え。', ref: 'from collections import Counter\nfrom math import factorial\ns=input()\nc=Counter(s)\nodd=sum(1 for v in c.values() if v%2)\nif odd>1:\n    print(0)\nelse:\n    half=sum(v//2 for v in c.values())\n    r=factorial(half)\n    for v in c.values():\n        r//=factorial(v//2)\n    print(r)', tip: '回文は前半で完全に決まるので「半分の多重集合の順列」に帰着する。多重集合の順列=多項係数、はこの種の数え上げの共通言語。', ins: ['aabb\n', 'abc\n', 'aab\n', 'aaaa\n', 'aabbcc\n', 'z\n'] })

t({ lv: 783, concept: '数え上げ: 等差の3つ組の数', title: '等差数列になる3か所', tags: ['数え上げ', 'ハッシュ'], io: '整数列が1行で空白区切りで与えられます。', ask: 'i<j<k で a[j]−a[i] と a[k]−a[j] が等しい(3つが等差)組の個数を出力してください。', h1: '真ん中 j を固定する。', h2: '各 i<j について、右側に 2a[j]−a[i] が何個あるかを頻度表で数える。', ref: 'from collections import Counter\na=list(map(int,input().split()))\nn=len(a)\ntotal=0\nright=Counter(a)\nfor j in range(n):\n    right[a[j]]-=1\n    for i in range(j):\n        total+=right[2*a[j]-a[i]]\nprint(total)', tip: '「真ん中固定+右側の頻度表を進行と同時に減らす」オンライン集計。等差の第3項は2b−aと一意に決まるので、探索が辞書参照に変わる。', ins: ['1 2 3\n', '1 1 1\n', '1 3 5 7\n', '1 2 4\n', '2 2 2 2\n', '0 5 10 15\n'] })

t({ lv: 784, concept: '文字列: 部分列として含む最短の窓', title: '順番どおり拾える最短の区間', tags: ['文字列', '二点法'], io: '1行目に文字列 S、2行目にパターン T が与えられます。', ask: 'S の連続区間であって、T をその中で部分列として(順序を保って)拾えるものの最小の長さを出力してください。存在しなければ -1。', h1: 'まず前へ進んでTを拾い切る。', h2: '拾い終えた位置から逆向きに縮めて左端を確定する(前進+後退の2フェーズ)。', ref: 's=input()\nt=input()\nn=len(s)\nm=len(t)\nbest=-1\ni=0\nwhile i<n:\n    j=0\n    k=i\n    while k<n and j<m:\n        if s[k]==t[j]:\n            j+=1\n        k+=1\n    if j<m:\n        break\n    end=k-1\n    j=m-1\n    k=end\n    while j>=0:\n        if s[k]==t[j]:\n            j-=1\n        k-=1\n    start=k+1\n    L=end-start+1\n    if best<0 or L<best:\n        best=L\n    i=start+1\nprint(best)', tip: '「進んで拾い、戻して締める」2方向スキャンが最短窓を漏らさない。文字の多重集合で覆う最小窓としゃくとり、部分列で覆う最小窓は2方向走査、と手法が分かれる。', ins: ['abcdebdde\nbde\n', 'abc\nabc\n', 'abc\nd\n', 'aaaa\naa\n', 'bbbbb\nb\n', 'axbxcxaxbc\nabc\n'] })

t({ lv: 785, concept: '数え上げ: 増加している区間の数', title: '右肩上がりの区間を数える', tags: ['数え上げ'], io: '整数列が1行で空白区切りで与えられます。', ask: '狭義単調増加の連続部分配列(長さ1以上)の個数を出力してください。', h1: '増加が続く長さを持ち歩く。', h2: '位置 i で終わる増加区間は「そこまでの増加ランの長さ」個ある。', ref: 'a=list(map(int,input().split()))\ntotal=0\nrun=0\nprev=None\nfor x in a:\n    if prev is not None and x>prev:\n        run+=1\n    else:\n        run=1\n    total+=run\n    prev=x\nprint(total)', tip: '「iで終わる◯◯の個数」を足し上げる末尾固定の数え上げ。ランの長さがそのまま個数になるのは、増加の部分区間も増加だから。', ins: ['1 2 3\n', '3 2 1\n', '1 2 1 2\n', '5\n', '1 1 1\n', '2 4 6 3 5\n'] })

t({ lv: 786, concept: '貪欲: 3つ選ぶ最大の積', title: '3つ掛けて一番大きく', tags: ['貪欲', 'ソート'], io: '整数列(3個以上、負を含みうる)が1行で空白区切りで与えられます。', ask: '3つの要素を選んだ積の最大値を出力してください。', h1: '大きい3つの積だけが候補ではない。', h2: '「最大3つの積」と「最小2つ(負×負)×最大」の大きい方。', ref: 'a=sorted(map(int,input().split()))\nprint(max(a[-1]*a[-2]*a[-3],a[0]*a[1]*a[-1]))', tip: '負数のペアが正に化けるため候補は2通りだけに絞れる。ソートして端だけ見る、が「上位k個系」の最速の近道。', ins: ['1 2 3\n', '-10 -10 1 3 2\n', '-1 -2 -3\n', '0 0 0\n', '-5 -4 1 2 3\n', '7 3 1 9\n'] })

t({ lv: 787, concept: '文字列: 逆さまでも同じ数字か', title: '180度回しても同じ数字', tags: ['文字列'], io: '数字だけの文字列が1行で与えられます。', ask: '180度回転して読んでも同じになる(0,1,8はそのまま、6と9は入れ替わり、他の数字は使えない)なら yes、そうでなければ no を出力してください。', h1: '回転で意味を持つ数字は5種類だけ。', h2: '両端から、対応表(6↔9など)で照合する。', ref: 's=input()\nm={"0":"0","1":"1","8":"8","6":"9","9":"6"}\nok=True\ni,j=0,len(s)-1\nwhile i<=j:\n    if s[i] not in m or m[s[i]]!=s[j]:\n        ok=False\n        break\n    i+=1\n    j-=1\nprint("yes" if ok else "no")', tip: 'ストロボグラマティック数と呼ばれる遊び。回文判定に「文字の対応表」を差し込んだだけで、鏡文字・レート表記などの照合にも一般化できる。', ins: ['69\n', '88\n', '962\n', '1\n', '818\n', '2\n'] })

t({ lv: 788, concept: '数え上げ: 積が10の倍数の区間数', title: '掛けると10の倍数になる区間', tags: ['数え上げ'], io: '正整数列が1行で空白区切りで与えられます。', ask: '要素の積が10の倍数になる連続部分配列の個数を出力してください。', h1: '積が10の倍数 ⇔ 因数に2と5を両方含む。', h2: '各右端について「直近の偶数の位置」と「直近の5の倍数の位置」の小さい方までが左端の許容範囲。', ref: 'a=list(map(int,input().split()))\nlast2=-1\nlast5=-1\ncnt=0\nfor i,x in enumerate(a):\n    if x%2==0:\n        last2=i\n    if x%5==0:\n        last5=i\n    m=min(last2,last5)\n    cnt+=m+1\nprint(cnt)', tip: '合成条件(2かつ5)は「それぞれの直近位置のmin」で左端の限界が決まる。「直近の必要条件の位置」を持ち歩く型は、含む系の数え上げで繰り返し登場する。', ins: ['2 5 1\n', '10\n', '1 3 7\n', '4 25 2 5\n', '5 2\n', '6 15 1 1\n'] })

t({ lv: 789, concept: '文字列: 母音だけを逆順に', title: '母音の位置だけ入れ替える', tags: ['文字列', '二点法'], io: '英小文字の文字列が1行で与えられます。', ask: '子音の位置は動かさず、母音(a,i,u,e,o)だけを全体で逆順に並べ替えた文字列を出力してください。', h1: '両端から母音を探して交換する。', h2: '2本のポインタを母音に合わせて進め、出会うまでスワップ。', ref: 's=list(input())\nv=set("aiueo")\ni,j=0,len(s)-1\nwhile i<j:\n    if s[i] not in v:\n        i+=1\n    elif s[j] not in v:\n        j-=1\n    else:\n        s[i],s[j]=s[j],s[i]\n        i+=1\n        j-=1\nprint("".join(s))', tip: '「条件を満たす要素だけの部分列を反転する」は二点法の練習として最適。条件を偶数・大文字に替えても1文字も構造が変わらない。', ins: ['hello\n', 'aiueo\n', 'python\n', 'a\n', 'xyz\n', 'umbrella\n'] })

t({ lv: 790, concept: '数え上げ: 和が素数の区間数', title: '合計が素数になる区間', tags: ['数え上げ', '数論'], io: '正整数列が1行で空白区切りで与えられます。', ask: '要素の合計が素数になる連続部分配列の個数を出力してください。', h1: '累積和で区間和をO(1)に。', h2: '全区間O(n²)を試し、和を試し割りで素数判定する。', ref: 'a=list(map(int,input().split()))\nn=len(a)\npre=[0]\nfor x in a:\n    pre.append(pre[-1]+x)\ndef isp(x):\n    if x<2:\n        return False\n    i=2\n    while i*i<=x:\n        if x%i==0:\n            return False\n        i+=1\n    return True\ncnt=0\nfor i in range(n):\n    for j in range(i+1,n+1):\n        if isp(pre[j]-pre[i]):\n            cnt+=1\nprint(cnt)', tip: '和の最大値までの篩を先に作れば判定がO(1)になる。「区間の量+性質判定」の組は、累積和と前計算テーブルの合わせ技が定番。', ins: ['1 1 1\n', '2 3\n', '4 6\n', '1 2 3 4\n', '5\n', '2 2 2\n'] })

export const CATALOG = TASKS
