// 生成タスク 第11波：競技プログラミング/数論パズル(AtCoder/Project Euler系)をオリジナル化。整数=採点一意。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 120, concept: 'AC: 3と5の倍数の和', title: '3または5の倍数の和', tags: ['全探索', '数論'], io: '整数 n が与えられます。', ask: '1以上 n 以下で 3 または 5 の倍数である数の総和を出力してください。', h1: '1..n を調べる。', h2: '%3==0 or %5==0。', ref: 'n=int(input())\nprint(sum(x for x in range(1,n+1) if x%3==0 or x%5==0))', ins: ['10\n', '100\n', '15\n', '3\n', '1\n', '1000\n'] })
t({ lv: 120, concept: 'AC: 偶数フィボの和', title: '偶数フィボナッチ数の和', tags: ['数列'], io: '整数 n が与えられます。', ask: 'n を超えないフィボナッチ数のうち偶数のものの和を出力してください。', h1: 'フィボを n まで生成。', h2: '偶数だけ足す。', ref: 'n=int(input())\na,b=1,2\ns=0\nwhile a<=n:\n    if a%2==0:\n        s+=a\n    a,b=b,a+b\nprint(s)', ins: ['10\n', '100\n', '4000000\n', '2\n', '1\n', '34\n'] })
t({ lv: 120, concept: 'AC: 平方和と和の平方の差', title: '平方の和と和の平方の差', tags: ['数論'], io: '整数 n が与えられます。', ask: '(1+2+…+n)² − (1²+2²+…+n²) を出力してください。', h1: '2つを別々に計算。', h2: '差を取る。', ref: 'n=int(input())\ns=sum(range(1,n+1))\nsq=sum(i*i for i in range(1,n+1))\nprint(s*s-sq)', ins: ['10\n', '100\n', '1\n', '5\n', '3\n', '20\n'] })
t({ lv: 120, concept: 'AC: K個連続の最大和', title: '連続するK個の最大和', tags: ['スライディングウィンドウ', '累積和'], io: '1行目に n k、2行目に n 個の整数が与えられます。', ask: '連続する k 要素の和の最大値を出力してください。', h1: '窓を1つずらすと差分更新。', h2: '出た分を引き入った分を足す。', ref: 'n,k=map(int,input().split())\na=list(map(int,input().split()))\ns=sum(a[:k])\nbest=s\nfor i in range(k,n):\n    s+=a[i]-a[i-k]\n    best=max(best,s)\nprint(best)', ins: ['5 2\n1 3 2 5 1\n', '4 2\n4 3 2 1\n', '3 3\n1 2 3\n', '6 1\n5 1 9 2 8 3\n', '5 3\n1 1 1 1 1\n', '4 4\n2 2 2 2\n'], tip: '💡 スライディングウィンドウで O(n)。毎回足し直すと O(nk)。' })
t({ lv: 120, concept: 'AC: 最大の隣接積', title: '隣り合う2数の積の最大', tags: ['全探索'], io: '整数列が1行で与えられます。', ask: '隣り合う2要素の積のうち最大を出力してください。', h1: '各 i で a[i]*a[i+1]。', h2: 'その最大。', ref: 'a=list(map(int,input().split()))\nprint(max(a[i]*a[i+1] for i in range(len(a)-1)))', ins: ['1 5 4 2\n', '3 6 1 2\n', '-1 -2 -3\n', '2 2\n', '0 5 0 6\n', '1 2 3 4\n'] })
t({ lv: 120, concept: 'AC: 等比数列の和', title: '等比数列の和', tags: ['数列'], io: '初項 a、公比 r、項数 n が空白区切りで与えられます。', ask: 'a + ar + … + ar^(n-1) を出力してください。', h1: '項を掛けながら足す。', h2: 'p*=r。', ref: 'a,r,n=map(int,input().split())\ns=0\np=a\nfor _ in range(n):\n    s+=p\n    p*=r\nprint(s)', ins: ['1 2 5\n', '3 1 4\n', '2 3 3\n', '5 2 1\n', '1 10 4\n', '1 1 10\n'] })
t({ lv: 130, concept: 'AC: 配列のGCD', title: '配列全体の最大公約数', tags: ['数論', '素数'], io: '整数列が1行で与えられます。', ask: 'すべての要素の最大公約数を出力してください。', h1: '次々と gcd を取る。', h2: 'math.gcd を畳み込む。', ref: 'import math\na=list(map(int,input().split()))\ng=a[0]\nfor x in a[1:]:\n    g=math.gcd(g,x)\nprint(g)', ins: ['12 18 24\n', '7 14 21\n', '5\n', '100 75 50\n', '9 6\n', '17 5\n'] })
t({ lv: 130, concept: 'AC: 配列のLCM', title: '配列全体の最小公倍数', tags: ['数論'], io: '整数列が1行で与えられます。', ask: 'すべての要素の最小公倍数を出力してください。', h1: '次々と lcm を取る。', h2: 'math.lcm を畳み込む。', ref: 'import math\na=list(map(int,input().split()))\nl=a[0]\nfor x in a[1:]:\n    l=math.lcm(l,x)\nprint(l)', ins: ['1 2 3 4 5\n', '2 3\n', '6 4\n', '1 2 3 4 5 6 7 8 9 10\n', '7\n', '10 20\n'] })
t({ lv: 130, concept: 'AC: フィボナッチ mod', title: 'フィボナッチ数 mod m', tags: ['数列', 'モジュラ'], io: '整数 n と m が空白区切りで与えられます。', ask: '第 n フィボナッチ数 (F0=0,F1=1) を m で割った余りを出力してください。', h1: '毎ステップ余りを取る。', h2: '巨大化を防ぐ。', ref: 'n,m=map(int,input().split())\na,b=0,1\nfor _ in range(n):\n    a,b=b,(a+b)%m\nprint(a)', ins: ['10 1000\n', '100 7\n', '0 5\n', '50 10\n', '7 3\n', '1000 9\n'], tip: '💡 各ステップで mod を取れば大きな n でも桁が爆発しない。' })
t({ lv: 130, concept: 'AC: 階乗 mod', title: '階乗 mod m', tags: ['モジュラ'], io: '整数 n と m が空白区切りで与えられます。', ask: 'n! を m で割った余りを出力してください。', h1: '掛けるたびに余りを取る。', h2: 'r=r*i%m。', ref: 'n,m=map(int,input().split())\nr=1\nfor i in range(2,n+1):\n    r=r*i%m\nprint(r)', ins: ['5 1000\n', '10 7\n', '100 13\n', '3 2\n', '1 5\n', '20 1000000007\n'] })
t({ lv: 130, concept: 'AC: 連続和で表す方法', title: '連続する整数の和で表す方法の数', tags: ['数論'], io: '正の整数 n が与えられます。', ask: '2つ以上の連続する正整数の和として n を表す方法の数を出力してください。', h1: '長さ k+1 の連続和を試す。', h2: '初項が正整数になるか。', ref: 'n=int(input())\nc=0\nk=1\nwhile k*(k+1)//2<=n:\n    if (n-k*(k+1)//2)%(k+1)==0:\n        c+=1\n    k+=1\nprint(c)', ins: ['15\n', '9\n', '1\n', '100\n', '16\n', '45\n'] })
t({ lv: 130, concept: 'AC: 最大の真の約数', title: '最大の真の約数', tags: ['数論', '素数'], io: '2以上の整数 n が与えられます。', ask: 'n 自身を除く最大の約数を出力してください。', h1: 'n を最小素因数で割る。', h2: '素数なら 1。', ref: 'n=int(input())\nspf=n\nd=2\nwhile d*d<=n:\n    if n%d==0:\n        spf=d\n        break\n    d+=1\nprint(n//spf if spf!=n else 1)', ins: ['12\n', '7\n', '15\n', '100\n', '49\n', '2\n'] })

export const CATALOG = TASKS
