// 生成タスク 第54波：各レベル2問化フェーズ(9)。lv442〜490 に2問目を追加。
// 幾何/数論/文字列/DP/数え上げ/グラフ/木/データ構造帯。重複なし・決定的・採点一意。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 442, concept: '幾何: 直角三角形の数', title: '直角三角形になる3点の組の数', tags: ['幾何'], io: '1行目に点数 n、続く n 行に相異なる点の座標が与えられます。', ask: '3点を選んで直角三角形になる組の個数を出力してください。', h1: 'どの頂点が直角になるかを3通り試す。', h2: '直角は「2辺のベクトルの内積が0」。相異なる点なら退化の心配はない。', ref: 'n=int(input())\npts=[tuple(map(int,input().split())) for _ in range(n)]\ncnt=0\nfor i in range(n):\n    for j in range(i+1,n):\n        for k in range(j+1,n):\n            tri=(pts[i],pts[j],pts[k])\n            for a in range(3):\n                o=tri[a]\n                b=tri[(a+1)%3]\n                c=tri[(a+2)%3]\n                if (b[0]-o[0])*(c[0]-o[0])+(b[1]-o[1])*(c[1]-o[1])==0:\n                    cnt+=1\n                    break\n    \nprint(cnt)', tip: '垂直の判定は内積、平行や共線の判定は外積。整数座標なら誤差なしで厳密に判定できるのが強み。', ins: ['4\n0 0\n1 0\n0 1\n1 1\n', '3\n0 0\n1 0\n0 1\n', '3\n0 0\n1 0\n2 0\n', '3\n0 0\n2 1\n1 3\n', '5\n0 0\n1 0\n0 1\n1 1\n2 2\n', '3\n0 0\n3 0\n0 4\n'] })

t({ lv: 443, concept: '数論: 平方三角数', title: 'k番目の平方三角数', tags: ['数論'], io: '正整数 k が1行で与えられます。', ask: '平方数でも三角数でもある正整数(平方三角数)のうち、小さい方から k 番目を出力してください(1番目は1)。', h1: '1, 36, 1225, … と急激に大きくなる。', h2: '漸化式 a(n+1) は「34·a(n) − a(n−1) + 2」で求まる(初期値 0 と 1)。', ref: 'k=int(input())\na,b=0,1\nfor _ in range(k-1):\n    a,b=b,34*b-a+2\nprint(b)', tip: '平方三角数はペル方程式 x²−2y²=1 の解と1対1に対応する。だから解が等比級数的に増え、線形漸化式で繋がる。', ins: ['1\n', '2\n', '3\n', '4\n', '5\n', '6\n'] })

t({ lv: 444, concept: '数論: 連分数から分数を復元', title: '連分数を分数に戻す', tags: ['数論'], io: '連分数の係数 a0 a1 … が1行で空白区切りで与えられます。', ask: '連分数 [a0; a1, a2, …] が表す分数を既約分数 p q として空白区切りで出力してください。', h1: '後ろから「逆数にして足す」を繰り返す。', h2: '分数 p/q に a を作用させると (a·p+q)/p になる。', ref: 'a=list(map(int,input().split()))\np,q=a[-1],1\nfor x in reversed(a[:-1]):\n    p,q=x*p+q,p\nprint(p,q)', tip: '互除法の商列(分数→連分数)の逆演算。後ろから畳むと約分が一切不要で、結果は自動的に既約になる。', ins: ['3 7 16\n', '1\n', '0 2\n', '2 1 2\n', '4\n', '1 1 1 1\n'] })

t({ lv: 445, concept: '数論: オイラーの規準', title: '平方剰余かどうかの判定', tags: ['数論'], io: '奇素数 p と p で割り切れない正整数 a が空白区切りで1行で与えられます。', ask: 'x²≡a (mod p) を満たす x が存在する(a が平方剰余である)なら yes、なければ no を出力してください。', h1: '全ての x を試さなくても判定できる。', h2: 'オイラーの規準: a^((p−1)/2) mod p が 1 なら平方剰余、p−1 なら非剰余。', ref: 'p,a=map(int,input().split())\nprint("yes" if pow(a,(p-1)//2,p)==1 else "no")', tip: '「根を求める」より「存在判定」の方がずっと軽い、という数論の典型例。pow(a,e,p) の高速べき乗で一発。実際に根を求めるにはTonelli-Shanks法が要る。', ins: ['7 2\n', '7 3\n', '11 3\n', '13 5\n', '5 4\n', '17 16\n'] })

t({ lv: 446, concept: '文字列: 辞書順k番目の部分文字列', title: '辞書順でk番目の相異なる部分文字列', tags: ['文字列'], io: '1行目に k、2行目に英小文字の文字列が与えられます(kは種類数以下)。', ask: '相異なる空でない連続部分文字列を辞書順に並べたとき、k 番目のものを出力してください。', h1: '全部分文字列を集合に入れて重複を消す。', h2: 'sorted して k−1 番目を取る。', ref: 'k=int(input())\ns=input()\nsubs=set()\nfor i in range(len(s)):\n    for j in range(i+1,len(s)+1):\n        subs.add(s[i:j])\nprint(sorted(subs)[k-1])', tip: '大きな文字列では接尾辞配列を使い「各接尾辞が何個の新しい部分文字列を生むか」を数えながら k を消費していく。set全列挙はその理解の土台。', ins: ['3\nabc\n', '1\nbanana\n', '5\naab\n', '2\nzz\n', '4\nabab\n', '1\nq\n'] })

t({ lv: 447, concept: 'データ構造: 区間最大値の個数', title: '区間の最大値が現れる回数', tags: ['データ構造'], io: '1行目に n q、2行目に整数列、続く q 行に「1 i x」(i番目をxに変更)または「2 l r」(質問)が与えられます。', ask: '各「2 l r」に対し、区間 [l,r] の最大値が区間内に現れる回数を1行ずつ出力してください。', h1: '小さい入力なら max と count で素直に。', h2: '大きい入力はセグメント木の各ノードに(最大値, その個数)のペアを持たせてマージする。', ref: 'n,q=map(int,input().split())\na=list(map(int,input().split()))\nfor _ in range(q):\n    t,x,y=map(int,input().split())\n    if t==1:\n        a[x-1]=y\n    else:\n        seg=a[x-1:y]\n        mx=max(seg)\n        print(seg.count(mx))', tip: 'セグ木は「マージできる情報」なら何でも載る。(最大値,個数)のペアは「等しければ個数を足し、違えば大きい方を採る」で結合律を満たす。', ins: ['5 3\n1 3 3 2 3\n2 1 5\n1 4 3\n2 2 4\n', '3 2\n5 5 5\n2 1 3\n2 2 2\n', '4 3\n1 2 3 4\n2 1 4\n1 1 9\n2 1 2\n', '2 2\n7 7\n1 1 1\n2 1 2\n', '6 2\n2 8 2 8 8 1\n2 1 6\n2 3 4\n', '1 2\n4\n2 1 1\n1 1 2\n'] })

t({ lv: 448, concept: 'データ構造: スライド窓の中央値', title: '長さkの窓の中央値の列', tags: ['データ構造'], io: '1行目に窓の長さ k(奇数)、2行目に整数列が与えられます。', ask: '長さ k の窓を左から右へ1つずつずらしながら、各窓の中央値を空白区切りで出力してください。', h1: '各窓をソートして真ん中を取る。', h2: '高速化するなら bisect.insort で挿入し、出る要素を bisect で消す(ソート済みリストの維持)。', ref: 'k=int(input())\na=list(map(int,input().split()))\nout=[]\nfor i in range(len(a)-k+1):\n    w=sorted(a[i:i+k])\n    out.append(w[k//2])\nprint(*out)', tip: '「流れてくるデータの中央値」は2本のヒープが定石だが、窓のように削除が要る場合はソート済みリスト+bisectの方が素直に書ける。', ins: ['3\n1 3 2 5 4\n', '1\n7 1\n', '5\n5 4 3 2 1\n', '3\n1 1 1 1\n', '3\n9 2 7 4 6\n', '1\n0\n'] })

t({ lv: 449, concept: 'グラフ: 閉路空間の次元', title: '独立な閉路の数', tags: ['グラフ'], io: '1行目に n m、続く m 行に無向辺が与えられます(自己ループ・多重辺なし)。', ask: 'このグラフの独立な閉路の最大数(閉路空間の次元)を出力してください。連結成分数を c とすると「m − n + c」で求まります。', h1: '全域森に入らない辺が1本増えるごとに独立な閉路が1つ増える。', h2: 'Union-Find で連結成分数 c を数え、m−n+c を計算。', ref: 'n,m=map(int,input().split())\npar=list(range(n+1))\ndef find(x):\n    while par[x]!=x:\n        par[x]=par[par[x]]\n        x=par[x]\n    return x\ncomps=n\nfor _ in range(m):\n    u,v=map(int,input().split())\n    ru,rv=find(u),find(v)\n    if ru!=rv:\n        par[ru]=rv\n        comps-=1\nprint(m-n+comps)', tip: '回路理論のループ数、構文解析の循環複雑度(McCabe)もこの量。全域木+余剰辺という見方はグラフのあちこちで効く。', ins: ['4 4\n1 2\n2 3\n3 4\n4 1\n', '3 2\n1 2\n2 3\n', '6 7\n1 2\n2 3\n3 1\n3 4\n4 5\n5 6\n6 4\n', '2 1\n1 2\n', '4 0\n', '5 5\n1 2\n2 3\n3 4\n4 5\n5 1\n'] })

t({ lv: 450, concept: 'bitDP: 完全マッチングの数', title: '全員をペアにする方法の数', tags: ['bitDP'], io: '1行目に人数 n(偶数)とペア候補数 m、続く m 行に「u と v は組める」ペアが与えられます。', ask: '全員をちょうど2人ずつの組に分ける方法の数を出力してください。', h1: 'dp[使った人の集合] を数える。', h2: '未使用の最小番号の人の相手を決めて遷移すると重複なく数えられる。', ref: 'n,m=map(int,input().split())\nadj=[[False]*n for _ in range(n)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    adj[u-1][v-1]=True\n    adj[v-1][u-1]=True\nfull=(1<<n)-1\ndp=[0]*(1<<n)\ndp[0]=1\nfor mask in range(1<<n):\n    if not dp[mask] or mask==full:\n        continue\n    i=0\n    while mask>>i&1:\n        i+=1\n    for j in range(i+1,n):\n        if not mask>>j&1 and adj[i][j]:\n            dp[mask|1<<i|1<<j]+=dp[mask]\nprint(dp[full])', tip: '「最小の未処理要素の相手を決める」と各マッチングがちょうど1回だけ数えられる。順序の重複を潰すbitDPの基本形。', ins: ['4 4\n1 2\n3 4\n1 3\n2 4\n', '2 1\n1 2\n', '2 0\n', '4 6\n1 2\n1 3\n1 4\n2 3\n2 4\n3 4\n', '6 6\n1 2\n2 3\n3 4\n4 5\n5 6\n6 1\n', '4 3\n1 2\n2 3\n3 4\n'] })

t({ lv: 451, concept: '文字列: ボーダーの個数', title: 'ボーダー(接頭辞かつ接尾辞)の個数', tags: ['文字列'], io: '英小文字の文字列が1行で与えられます。', ask: '文字列全体より短い空でない文字列で、接頭辞でも接尾辞でもあるもの(ボーダー)の個数を出力してください。', h1: '接頭辞関数(KMPのπ配列)を作る。', h2: 'π[n−1] から π をたどる連鎖の長さが答え。', ref: 's=input()\nn=len(s)\npi=[0]*n\nfor i in range(1,n):\n    k=pi[i-1]\n    while k and s[i]!=s[k]:\n        k=pi[k-1]\n    if s[i]==s[k]:\n        k+=1\n    pi[i]=k\nc=0\nk=pi[n-1]\nwhile k:\n    c+=1\n    k=pi[k-1]\nprint(c)', tip: '全ボーダーはπの連鎖 π[n−1], π[π[n−1]−1], … で漏れなく列挙できる。周期性(n−π[n−1]が最小周期)と表裏一体の構造。', ins: ['aaaa\n', 'abcab\n', 'abab\n', 'aabaa\n', 'abc\n', 'aaaaaa\n'] })

t({ lv: 452, concept: '文字列: 重ならない出現回数', title: '重ならない出現の最大回数', tags: ['文字列'], io: '1行目にテキスト、2行目にパターンが与えられます。', ask: 'テキスト中でパターンが互いに重ならないように現れる箇所を最大でいくつ選べるかを出力してください。', h1: '左から貪欲に取ってよい(早く終わる出現を取るほど得)。', h2: 'find の開始位置を「直前の出現の終わり」に進めながら数える。', ref: 's=input()\np=input()\ni=0\nc=0\nwhile True:\n    j=s.find(p,i)\n    if j<0:\n        break\n    c+=1\n    i=j+len(p)\nprint(c)', tip: '区間スケジューリングと同じ「終端が早いものから貪欲」の理屈で最適性が言える。str.find(sub, start) の第2引数が主役。', ins: ['aaaa\naa\n', 'ababab\naba\n', 'abcabcabc\nabc\n', 'aaa\nb\n', 'xyxyxyxy\nxyxy\n', 'a\na\n'] })

t({ lv: 453, concept: '文字列: 回文でない最長部分文字列', title: '回文でない最長の部分文字列', tags: ['文字列'], io: '英小文字の文字列が1行で与えられます。', ask: '回文で「ない」連続部分文字列の最大の長さを出力してください。存在しなければ 0 を出力してください。', h1: '全部同じ文字なら、どの部分文字列も回文。', h2: '全体が回文でなければ全体が答え。全体が回文(かつ2種類以上の文字)なら、末尾を1文字削ったものが回文でないことを示せる。', ref: 's=input()\nif len(set(s))==1:\n    print(0)\nelif s!=s[::-1]:\n    print(len(s))\nelse:\n    print(len(s)-1)', tip: '答えが n / n−1 / 0 の3択に潰れる「観察一発」問題。探索を書く前に、構造から答えを絞れないか疑う癖をつけたい。', ins: ['aba\n', 'abc\n', 'aaaa\n', 'a\n', 'abba\n', 'ab\n'] })

t({ lv: 454, concept: '文字列: 回転の中での辞書順位', title: '自分は回転の中で何番目か', tags: ['文字列'], io: '英小文字の文字列が1行で与えられます。', ask: '文字列の全ての回転(巡回シフト)を重複を除いて辞書順に並べたとき、元の文字列が何番目(1始まり)かを出力してください。', h1: 's[i:]+s[:i] で全回転を作れる。', h2: 'set で重複を除き、sorted の中で index を探す。', ref: 's=input()\nrots=sorted(set(s[i:]+s[:i] for i in range(len(s))))\nprint(rots.index(s)+1)', tip: '全回転をソートした表はBurrows-Wheeler変換(bzip2圧縮の心臓部)の土台。元の文字列の順位はBWTの復元で使う量そのもの。', ins: ['bca\n', 'aaa\n', 'ab\n', 'ba\n', 'banana\n', 'cabcab\n'] })

t({ lv: 455, concept: '文字列: 共通部分文字列の種類数', title: '2つの文字列に共通する部分文字列の種類', tags: ['文字列'], io: '1行目と2行目に英小文字の文字列が与えられます。', ask: '両方の文字列に(連続部分文字列として)現れる空でない文字列の種類数を出力してください。', h1: 'それぞれの部分文字列の集合を作る。', h2: '集合の共通部分(&)のサイズが答え。', ref: 's=input()\nt=input()\ndef subs(x):\n    r=set()\n    for i in range(len(x)):\n        for j in range(i+1,len(x)+1):\n            r.add(x[i:j])\n    return r\nprint(len(subs(s)&subs(t)))', tip: '集合の & 一発で「共通」が数えられるのがPythonの気持ちよさ。大規模では2文字列を連結した一般化接尾辞配列で数える世界になる。', ins: ['ab\nb\n', 'abc\nabd\n', 'xy\nzw\n', 'aa\naaa\n', 'abab\nba\n', 'same\nsame\n'] })

t({ lv: 456, concept: 'DP: 最大交互和部分列', title: '交互和が最大の部分列', tags: ['DP'], io: '整数列が1行で空白区切りで与えられます。', ask: '空でない部分列 b1,b2,… を選び、交互和 b1−b2+b3−… を最大化した値を出力してください。', h1: '「次に足す番」「次に引く番」の2状態を持つ。', h2: 'odd(足す側で終わる最大)と even(引く側で終わる最大)を同時に更新する。', ref: 'a=list(map(int,input().split()))\nodd=-10**18\neven=0\nfor x in a:\n    odd,even=max(odd,even+x),max(even,odd-x)\nprint(odd)', tip: '状態を「偶数個選んだ/奇数個選んだ」に割るDP。タプル同時代入なら古い値どうしで遷移でき、一時変数が要らない。', ins: ['4 2 5 3\n', '1 2 3\n', '5\n', '-1 -2 -3\n', '6 2 1 2 4 5\n', '3 -1 4 -1 5\n'] })

t({ lv: 457, concept: '貪欲: 和が非減少の最大分割数', title: '和が減らないように切る最大分割', tags: ['貪欲'], io: '正整数列が1行で空白区切りで与えられます。', ask: '列を連続したブロックに分け、ブロックの和が左から右へ一度も減らないようにするとき、ブロック数の最大を出力してください。', h1: '各ブロックは「条件を満たす最短」で切るのが得。', h2: '直前の和以上になった瞬間に切る。末尾の余りは最後のブロックへ合流させれば条件は壊れない。', ref: 'a=list(map(int,input().split()))\nprev=0\ncur=0\ncnt=0\nfor x in a:\n    cur+=x\n    if cur>=prev:\n        cnt+=1\n        prev=cur\n        cur=0\nprint(cnt)', tip: '「早く切るほど後が楽になる」単調性が貪欲の正しさの根拠。余りを最後のブロックに吸収させても和は増える方向なので条件が保たれる。', ins: ['1 2 3\n', '5 1 1 1\n', '1 1 1 1\n', '3 1 2 4\n', '2 9 3 1\n', '4 3 2 6\n'] })

t({ lv: 458, concept: 'DP: 最長フィボナッチ風部分列', title: '最長のフィボナッチ風部分列', tags: ['DP'], io: '狭義単調増加の整数列が1行で空白区切りで与えられます。', ask: '「3項目以降が直前2項の和」になる長さ3以上の部分列の最大の長さを出力してください。なければ 0。', h1: '末尾の2項 (i,j) を状態にする。', h2: 'a[j]−a[i] が配列にあれば、その位置 k から dp[(k,i)]+1 で伸ばせる。値→位置の辞書を作る。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nidx={v:i for i,v in enumerate(a)}\ndp={}\nbest=0\nfor j in range(n):\n    for i in range(j):\n        p=a[j]-a[i]\n        if p<a[i] and p in idx:\n            k=idx[p]\n            dp[(i,j)]=dp.get((k,i),2)+1\n            if dp[(i,j)]>best:\n                best=dp[(i,j)]\nprint(best if best>=3 else 0)', tip: '「末尾2項が列を決める」タイプのDPは状態をペアにする。前の項は引き算で一意に決まるので、辞書で O(1) 参照できる。', ins: ['1 2 3 4 5 6 7 8\n', '1 3 7 11 12 14 18\n', '1 2 3\n', '1 4 7\n', '2 4 6 10 16 26\n', '1 5 6 11 17 28\n'] })

t({ lv: 459, concept: '区間DP: 最小印字回数', title: '同じ文字の帯で印字する最小回数', tags: ['区間DP'], io: '英小文字の文字列が1行で与えられます。', ask: 'プリンタは1回の操作で「同じ文字の連続した帯」を印字でき、後の印字は前の文字を上書きできます。この文字列を作る最小の印字回数を出力してください。', h1: 'まず連続する同じ文字を1文字に潰してよい。', h2: '区間DP。右端の文字と同じ文字が区間内にあれば、その印字を右端とまとめられる。', ref: 's=input()\nt=""\nfor c in s:\n    if not t or t[-1]!=c:\n        t+=c\nn=len(t)\nmemo={}\ndef f(i,j):\n    if i>j:\n        return 0\n    if (i,j) in memo:\n        return memo[(i,j)]\n    res=f(i,j-1)+1\n    for k in range(i,j):\n        if t[k]==t[j]:\n            r=f(i,k)+f(k+1,j-1)\n            if r<res:\n                res=r\n    memo[(i,j)]=res\n    return res\nprint(f(0,n-1))', tip: '「上書きできる」制約は区間DPで「同じ文字を同じ操作にまとめる」遷移に化ける。連長圧縮の前処理で状態数を減らすのも定石。', ins: ['aaabbb\n', 'aba\n', 'a\n', 'abcabc\n', 'tbgtgb\n', 'aaaa\n'] })

t({ lv: 460, concept: '区間DP: 式の括弧化で最大値', title: '括弧の付け方で式の値を最大に', tags: ['区間DP'], io: '1行目に正整数列、2行目に演算子(+ または *)が空白区切りで数列より1個少なく与えられます(数が1個なら空行)。', ask: '演算の順序(括弧の付け方)を自由に決めるとき、式の値の最大を出力してください。', h1: '最後に計算する演算子の位置で区間を2つに割る。', h2: '正整数だけなので、両側とも最大値を使えば全体も最大になる。', ref: 'a=list(map(int,input().split()))\nops=input().split()\nn=len(a)\ndp=[[0]*n for _ in range(n)]\nfor i in range(n):\n    dp[i][i]=a[i]\nfor L in range(2,n+1):\n    for i in range(0,n-L+1):\n        j=i+L-1\n        best=None\n        for k in range(i,j):\n            if ops[k]=="+":\n                v=dp[i][k]+dp[k+1][j]\n            else:\n                v=dp[i][k]*dp[k+1][j]\n            if best is None or v>best:\n                best=v\n        dp[i][j]=best\nprint(dp[0][n-1])', tip: '行列連鎖積と同じ「最後の分割点を全部試す」型。負の数が混ざると最小値も同時に持つ必要が出る(最小×最小が最大になりうる)。', ins: ['2 3 4\n+ *\n', '1 1\n+\n', '5\n\n', '2 2 2 2\n* * *\n', '1 2 3 4\n+ * +\n', '3 0 5\n* +\n'] })

t({ lv: 461, concept: 'DP: 順序を区別する両替の数', title: '順番を区別して金額を作る方法の数', tags: ['DP'], io: '1行目に金額 T、2行目に硬貨の種類が与えられます。', ask: '硬貨を並べる順番も区別して(1+2 と 2+1 は別と数える)、合計を T にする並べ方の数を出力してください。', h1: '金額を外側、硬貨を内側にループする。', h2: 'dp[v] は「最後の1枚」を全種類試して dp[v−c] を足す。', ref: 't=int(input())\ncoins=list(map(int,input().split()))\ndp=[0]*(t+1)\ndp[0]=1\nfor v in range(1,t+1):\n    for c in coins:\n        if c<=v:\n            dp[v]+=dp[v-c]\nprint(dp[t])', tip: '硬貨を外側に回すと組合せ(順序なし)、金額を外側に回すと順列(順序あり)。ループの順番が数える対象を変える、DPで最も有名な落とし穴。', ins: ['4\n1 2\n', '3\n1 2 3\n', '0\n1 2\n', '5\n5\n', '6\n2 3\n', '10\n2 5 3\n'] })

t({ lv: 462, concept: 'DP: 作れない金額の個数', title: '硬貨で作れない金額を数える', tags: ['DP'], io: '1行目に上限 N、2行目に硬貨の種類(各硬貨は何枚でも使える)が与えられます。', ask: '1 以上 N 以下の金額のうち、硬貨の組合せでは作れないものの個数を出力してください。', h1: '到達可能フラグを金額0から順に立てる。', h2: 'ok[v] は「ある硬貨 c で ok[v−c] が真」なら真。', ref: 'n=int(input())\ncoins=list(map(int,input().split()))\nok=[False]*(n+1)\nok[0]=True\nfor v in range(1,n+1):\n    for c in coins:\n        if c<=v and ok[v-c]:\n            ok[v]=True\n            break\nprint(sum(1 for v in range(1,n+1) if not ok[v]))', tip: '2種の互いに素な硬貨 a,b なら作れない最大は ab−a−b、作れない個数は (a−1)(b−1)/2 という閉形式がある(シルベスターの定理)。', ins: ['10\n3 5\n', '5\n2\n', '6\n1\n', '7\n4 6\n', '1\n2 3\n', '20\n6 9 20\n'] })

t({ lv: 463, concept: '数え上げ: 連続整数の和への分解数', title: '連続する整数の和で表す方法の数', tags: ['数学'], io: '正整数 n が1行で与えられます。', ask: 'n を「2個以上の連続する正整数の和」として表す方法の数を出力してください。', h1: '長さ k の連続和は k·a + k(k−1)/2 の形。', h2: '各 k について残り n − k(k−1)/2 が正の k の倍数かを見る。', ref: 'n=int(input())\nc=0\nk=2\nwhile k*(k+1)//2<=n:\n    r=n-k*(k-1)//2\n    if r>0 and r%k==0:\n        c+=1\n    k+=1\nprint(c)', tip: '答えは「1より大きい奇数の約数の個数」に一致する。2のべき乗だけが連続和で表せない、という美しい特徴付けが得られる。', ins: ['9\n', '15\n', '8\n', '3\n', '1\n', '100\n'] })

t({ lv: 464, concept: '数え上げ: 全カタラン経路の面積総和', title: '正しい括弧列たちの高さの合計', tags: ['数学', 'DP'], io: '正整数 n が1行で与えられます。', ask: '長さ 2n の正しい括弧列すべてについて「各文字を処理した直後のネストの深さの合計」を求め、その総和(全経路の面積の総和)を出力してください。', h1: '経路を1つずつ列挙すると爆発する。', h2: 'dp[高さ] に (経路数, これまでの面積の総和) のペアを持ち、1歩ごとに新しい高さを面積へ足し込む。', ref: 'n=int(input())\ndp={0:(1,0)}\nfor _ in range(2*n):\n    nd={}\n    for h,(c,s) in dp.items():\n        for nh in (h+1,h-1):\n            if nh<0:\n                continue\n            cc,ss=nd.get(nh,(0,0))\n            nd[nh]=(cc+c,ss+s+nh*c)\n    dp=nd\nprint(dp.get(0,(0,0))[1])', tip: '「個数」と「統計量の総和」をペアで運ぶDPは、平均や期待値を数え上げから求める常套手段。カタラン経路の面積総和は 4^n − C(2n+1,n) という閉形式も知られる。', ins: ['1\n', '2\n', '3\n', '4\n', '5\n', '6\n'] })

t({ lv: 465, concept: '数え上げ: 偶数個の組への分割数', title: '偶数チームに分ける方法', tags: ['数学', 'DP'], io: '正整数 n が1行で与えられます。', ask: 'n 人を空でないいくつかの組に分ける方法(組に順序なし)のうち、組の数が偶数であるものの総数を出力してください。', h1: '組の数 k ごとの分け方は第二種スターリング数 S(n,k)。', h2: 'S(n,k) の表を漸化式 S(n,k)=k·S(n−1,k)+S(n−1,k−1) で作り、偶数の k だけ足す。', ref: 'n=int(input())\nS=[[0]*(n+1) for _ in range(n+1)]\nS[0][0]=1\nfor i in range(1,n+1):\n    for j in range(1,i+1):\n        S[i][j]=j*S[i-1][j]+S[i-1][j-1]\nprint(sum(S[n][k] for k in range(2,n+1,2)))', tip: 'ベル数を偶奇で割った半分…にはならない(偶奇のバランスは崩れる)。分類パラメータで条件付き集計する練習として、三角形のDP表がそのまま使える。', ins: ['2\n', '3\n', '4\n', '5\n', '6\n', '1\n'] })

t({ lv: 466, concept: '数え上げ: 同じ人数の組だけの分割', title: '全チーム同じ人数に分ける方法', tags: ['数学'], io: '正整数 n が1行で与えられます。', ask: 'n 人を「全ての組の人数が等しい」ように組に分ける方法(組に順序なし)の総数を出力してください(全員で1組、1人ずつn組も含む)。', h1: '組の人数 s は n の約数に限る。', h2: '人数 s、組数 g=n/s のときの分け方は n! / ((s!)^g · g!)。約数ごとに足す。', ref: 'from math import factorial\nn=int(input())\ntotal=0\ns=1\nwhile s<=n:\n    if n%s==0:\n        g=n//s\n        total+=factorial(n)//(factorial(s)**g*factorial(g))\n    s+=1\nprint(total)', tip: '「同サイズブロックの分割」は多項係数を組の並べ替え g! で割る定番の形。s=1 と s=n が自明な両端になり、約数構造が数え上げに直結する。', ins: ['1\n', '2\n', '3\n', '4\n', '6\n', '8\n'] })

t({ lv: 467, concept: '数え上げ: 隣接値禁止の順列', title: '連続する数が隣り合わない並べ方', tags: ['数学', '再帰'], io: '正整数 n が1行で与えられます (n≤7)。', ask: '1..n の並べ方のうち、隣り合う位置に「差が1の2数」が来ないものの数を出力してください。', h1: '使った数の集合と直前の数を状態にして深さ優先で数える。', h2: '直前との差の絶対値が1なら枝を切る。', ref: 'n=int(input())\ncnt=0\ndef go(used,last,depth):\n    global cnt\n    if depth==n:\n        cnt+=1\n        return\n    for v in range(1,n+1):\n        if not used>>v&1 and (last==0 or abs(v-last)!=1):\n            go(used|1<<v,v,depth+1)\ngo(0,0,0)\nprint(cnt)', tip: '数列 1,0,0,2,14,90,646,… はヘルツシュプルングの問題として知られる。大きな n では包除原理で「隣接ペアをちょうどj個含む」を数える。', ins: ['4\n', '1\n', '2\n', '3\n', '5\n', '6\n'] })

t({ lv: 468, concept: '包除原理: いずれかの素数で割り切れる数', title: 'どれかの素数で割り切れる数の個数', tags: ['数学'], io: '1行目に N、2行目に相異なる素数の列が与えられます。', ask: '1 以上 N 以下で、与えられた素数の少なくとも1つで割り切れる数の個数を出力してください。', h1: '「pで割り切れる個数」は N//p。重複をどう処理するか。', h2: '部分集合の積ごとに符号を交互にして N//積 を足し引きする(包除原理)。', ref: 'n=int(input())\nps=list(map(int,input().split()))\nk=len(ps)\ntotal=0\nfor mask in range(1,1<<k):\n    prod=1\n    bits=0\n    for i in range(k):\n        if mask>>i&1:\n            prod*=ps[i]\n            bits+=1\n    if bits%2:\n        total+=n//prod\n    else:\n        total-=n//prod\nprint(total)', tip: 'ビットマスクで部分集合を全列挙し、要素数の偶奇で符号を決めるのが包除原理の実装定石。エラトステネスの篩を式にした形とも言える。', ins: ['10\n2 3\n', '30\n2 3 5\n', '7\n7\n', '100\n2 5\n', '20\n3 7\n', '1\n2 3 5\n'] })

t({ lv: 469, concept: '桁DP: 桁が非減少の数', title: '桁が左から非減少の数の個数', tags: ['DP'], io: '正整数 N が1行で与えられます。', ask: '1 以上 N 以下で、10進表記の桁が左から右へ一度も減らない数(例 1123, 448)の個数を出力してください。', h1: '各数を文字列にして隣接桁を比べる。', h2: '大きな N では「直前の桁・上限に張り付いているか」を状態にした桁DPになる。', ref: 'n=int(input())\nc=0\nfor x in range(1,n+1):\n    s=str(x)\n    if all(s[i]<=s[i+1] for i in range(len(s)-1)):\n        c+=1\nprint(c)', tip: '桁が非減少の数は「重複を許して数字を選ぶ組合せ」と1対1なので、d桁ならC(d+8,8)個と閉形式でも数えられる。', ins: ['30\n', '9\n', '100\n', '1\n', '21\n', '55\n'] })

t({ lv: 470, concept: 'bitDP: 一般グラフの最大独立集合', title: 'どの2人も知り合いでない最大人数', tags: ['bitDP'], io: '1行目に n m、続く m 行に「u と v は知り合い」が与えられます (n≤16)。', ask: 'どの2人も知り合いでないように選べる最大人数(最大独立集合のサイズ)を出力してください。', h1: '各頂点の隣接をビットマスクで持つ。', h2: '全部分集合について「誰の隣接とも交わらない」を確認し、最大の要素数を取る。', ref: 'n,m=map(int,input().split())\nadjm=[0]*n\nfor _ in range(m):\n    u,v=map(int,input().split())\n    adjm[u-1]|=1<<(v-1)\n    adjm[v-1]|=1<<(u-1)\nbest=0\nfor mask in range(1<<n):\n    ok=True\n    x=mask\n    while x:\n        i=(x&-x).bit_length()-1\n        if adjm[i]&mask:\n            ok=False\n            break\n        x&=x-1\n    if ok:\n        c=bin(mask).count("1")\n        if c>best:\n            best=c\nprint(best)', tip: '木なら多項式時間で解けるが一般グラフはNP困難。n≤16程度なら2^nの全列挙が現実解。x&-x で最下位ビットを取り出すイディオムは頻出。', ins: ['3 2\n1 2\n2 3\n', '4 6\n1 2\n1 3\n1 4\n2 3\n2 4\n3 4\n', '1 0\n', '4 2\n1 2\n3 4\n', '5 4\n1 2\n2 3\n3 4\n4 5\n', '6 3\n1 4\n2 5\n3 6\n'] })

t({ lv: 471, concept: 'グラフ: 経由頂点を制限した最短路', title: '番号k以下しか経由できない最短路', tags: ['グラフ'], io: '1行目に n m k s t、続く m 行に無向辺 u v w が与えられます。', ask: '途中で経由してよい頂点は番号 k 以下だけ(始点 s と終点 t 自身は制限なし)という条件での s から t への最短距離を出力してください。到達できなければ -1。', h1: 'ワーシャルフロイドの3重ループの意味を思い出す。', h2: '外側ループ(経由点)を 1..k までで打ち切れば、それがちょうど答えになる。', ref: 'n,m,k,s,t=map(int,input().split())\nINF=float("inf")\nd=[[INF]*(n+1) for _ in range(n+1)]\nfor i in range(1,n+1):\n    d[i][i]=0\nfor _ in range(m):\n    u,v,w=map(int,input().split())\n    if w<d[u][v]:\n        d[u][v]=w\n        d[v][u]=w\nfor mid in range(1,k+1):\n    for i in range(1,n+1):\n        for j in range(1,n+1):\n            nd=d[i][mid]+d[mid][j]\n            if nd<d[i][j]:\n                d[i][j]=nd\nprint(d[s][t] if d[s][t]<INF else -1)', tip: 'ワーシャルフロイドは本来「経由点をk番まで許した最短路」を k について積み上げるDP。途中で止めれば制限付き最短路が読める。', ins: ['4 4 2 3 4\n3 1 2\n1 4 3\n3 2 1\n2 4 10\n', '3 2 0 1 3\n1 2 1\n2 3 1\n', '3 3 1 2 3\n2 1 1\n1 3 1\n2 3 5\n', '2 1 0 1 2\n1 2 7\n', '5 5 3 4 5\n4 1 1\n1 2 1\n2 3 1\n3 5 1\n4 5 9\n', '4 3 4 1 4\n1 2 2\n2 3 2\n3 4 2\n'] })

t({ lv: 472, concept: 'グラフ: 負閉路の影響を受ける頂点数', title: '最短距離が定まらない頂点の数', tags: ['グラフ'], io: '1行目に n m s、続く m 行に有向辺 u v w が与えられます。', ask: '始点 s からの最短距離がいくらでも小さくできてしまう(負閉路の影響を受ける)頂点の個数を出力してください。', h1: 'ベルマンフォードを n−1 回回した後、まだ緩和できる辺を探す。', h2: 'その辺の行き先から到達できる頂点は全て「発散」する。BFSで広げる。', ref: 'from collections import deque\nn,m,s=map(int,input().split())\nedges=[]\nadj=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v,w=map(int,input().split())\n    edges.append((u,v,w))\n    adj[u].append(v)\nINF=float("inf")\ndist=[INF]*(n+1)\ndist[s]=0\nfor _ in range(n-1):\n    for u,v,w in edges:\n        if dist[u]<INF and dist[u]+w<dist[v]:\n            dist[v]=dist[u]+w\nmark=[False]*(n+1)\nq=deque()\nfor u,v,w in edges:\n    if dist[u]<INF and dist[u]+w<dist[v] and not mark[v]:\n        mark[v]=True\n        q.append(v)\nwhile q:\n    x=q.popleft()\n    for y in adj[x]:\n        if not mark[y]:\n            mark[y]=True\n            q.append(y)\nprint(sum(mark))', tip: '「負閉路がある」だけでなく「どの頂点に波及するか」まで追うのが実戦形。n−1回で収束しない緩和が発散の証拠になる。', ins: ['4 4 1\n1 2 1\n2 3 -1\n3 2 -1\n3 4 1\n', '3 2 1\n1 2 -5\n2 3 -5\n', '4 4 1\n1 2 1\n2 3 1\n3 1 -5\n3 4 1\n', '2 1 2\n1 2 -1\n', '5 6 1\n1 2 1\n2 3 -2\n3 2 1\n3 4 1\n4 5 1\n1 5 0\n', '3 2 1\n1 2 3\n1 3 -4\n'] })

t({ lv: 473, concept: 'グラフ: 依存タスクの並列ラウンド数', title: '並列実行での最小ラウンド数', tags: ['グラフ'], io: '1行目に n m、続く m 行に「u を v より先に終える必要がある」という依存 u v が与えられます(閉路なし)。', ask: '各タスクは1ラウンドかかり、依存が全て済んだタスクは同じラウンドで何個でも並列実行できます。全タスクを終える最小ラウンド数を出力してください。', h1: '答えは依存の最長チェーンの長さ。', h2: 'トポロジカル順に dp[v] を「1 + 先行タスクの最大」で更新する。', ref: 'from collections import deque\nn,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nindeg=[0]*(n+1)\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    indeg[v]+=1\nq=deque(v for v in range(1,n+1) if indeg[v]==0)\ndp=[1]*(n+1)\nwhile q:\n    x=q.popleft()\n    for y in g[x]:\n        if dp[x]+1>dp[y]:\n            dp[y]=dp[x]+1\n        indeg[y]-=1\n        if indeg[y]==0:\n            q.append(y)\nprint(max(dp[1:n+1]))', tip: 'クリティカルパスの長さが並列度をいくら上げても縮まない下限を与える。ビルドシステムやCIのパイプライン最適化そのもの。', ins: ['5 4\n1 2\n1 3\n2 4\n3 4\n', '3 0\n', '4 3\n1 2\n2 3\n3 4\n', '6 6\n1 3\n2 3\n3 4\n3 5\n4 6\n5 6\n', '2 1\n1 2\n', '7 2\n1 2\n3 4\n'] })

t({ lv: 474, concept: 'bitDP: 独立集合の個数', title: '独立集合は何通りあるか', tags: ['bitDP'], io: '1行目に n m、続く m 行に無向辺が与えられます (n≤16)。', ask: '辺で結ばれた2頂点を同時に含まない頂点部分集合(独立集合)の総数を出力してください。空集合も数えます。', h1: '部分集合をビットマスクで全列挙する。', h2: '集合内の各頂点について、隣接マスクと集合が交わらないことを確認。', ref: 'n,m=map(int,input().split())\nadjm=[0]*n\nfor _ in range(m):\n    u,v=map(int,input().split())\n    adjm[u-1]|=1<<(v-1)\n    adjm[v-1]|=1<<(u-1)\ncnt=0\nfor mask in range(1<<n):\n    x=mask\n    while x:\n        i=(x&-x).bit_length()-1\n        if adjm[i]&mask:\n            break\n        x&=x-1\n    else:\n        cnt+=1\nprint(cnt)', tip: 'whileにelseを付けると「breakせずに抜けた」を素直に書ける。パスグラフの独立集合数はフィボナッチ数になる、という検算も面白い。', ins: ['3 2\n1 2\n2 3\n', '2 1\n1 2\n', '1 0\n', '3 3\n1 2\n2 3\n1 3\n', '4 2\n1 2\n3 4\n', '4 0\n'] })

t({ lv: 475, concept: 'グラフ: 貪欲彩色の色数', title: '番号順の貪欲彩色で使う色数', tags: ['グラフ'], io: '1行目に n m、続く m 行に無向辺が与えられます。', ask: '頂点 1,2,…,n の順に「隣接頂点で使われていない最小の色番号」を塗っていくとき、使われる色の総数を出力してください。', h1: '各頂点で隣接の色を集合に集める。', h2: '1から順に「集合に無い最小の色」を探して塗る。', ref: 'n,m=map(int,input().split())\nadj=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    adj[u].append(v)\n    adj[v].append(u)\ncolor=[0]*(n+1)\nfor v in range(1,n+1):\n    used=set(color[u] for u in adj[v] if color[u])\n    c=1\n    while c in used:\n        c+=1\n    color[v]=c\nprint(max(color[1:n+1]))', tip: '貪欲彩色は「最大次数+1」色で必ず塗れるが、最適(彩色数)とは限らない。頂点の順番次第で結果が変わるのが味噌で、次数降順に並べるなどの改良がある。', ins: ['4 5\n1 2\n2 3\n3 4\n4 1\n1 3\n', '3 2\n1 2\n2 3\n', '1 0\n', '4 6\n1 2\n1 3\n1 4\n2 3\n2 4\n3 4\n', '5 4\n1 2\n1 3\n1 4\n1 5\n', '6 5\n2 4\n4 6\n1 3\n3 5\n2 6\n'] })

t({ lv: 476, concept: 'グラフ: 頂点素な2経路の判定', title: '内部で交わらない2本の経路はあるか', tags: ['グラフ'], io: '1行目に n m s t、続く m 行に無向辺が与えられます。', ask: 's から t へ、端点以外の頂点を共有しない2本の経路が取れるなら yes、取れなければ no を出力してください。', h1: 'メンガーの定理: 2本取れないなら、取り除くと分断される頂点が1つある。', h2: 's,t 以外の各頂点を1つずつ取り除き、毎回 s から t へ届くか確かめる。', ref: 'from collections import deque\nn,m,s,t=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\ndef reach(ban):\n    seen=[False]*(n+1)\n    seen[s]=True\n    q=deque([s])\n    while q:\n        x=q.popleft()\n        for y in g[x]:\n            if y!=ban and not seen[y]:\n                seen[y]=True\n                q.append(y)\n    return seen[t]\nok=reach(0)\nif ok:\n    for v in range(1,n+1):\n        if v!=s and v!=t and not reach(v):\n            ok=False\n            break\nprint("yes" if ok else "no")', tip: '「k本の互いに素な経路」と「分断に要する頂点数」が等しいというメンガーの定理の k=2 の場合。大きなグラフでは頂点を入口と出口に分裂させて最大流に帰着する。', ins: ['4 4 1 4\n1 2\n2 4\n1 3\n3 4\n', '3 2 1 3\n1 2\n2 3\n', '2 1 1 2\n1 2\n', '5 5 1 5\n1 2\n2 5\n1 3\n3 4\n4 5\n', '4 3 1 4\n1 2\n2 3\n3 4\n', '5 6 1 4\n1 2\n2 4\n1 3\n3 4\n2 3\n4 5\n'] })

t({ lv: 477, concept: 'グラフ: 橋を無くす最小追加辺数', title: '橋を全て消すための最小追加辺数', tags: ['グラフ'], io: '1行目に n m、続く m 行に連結な無向グラフの辺が与えられます。', ask: '辺を何本か追加して、どの辺も橋でない(2辺連結な)グラフにしたい。必要な追加辺数の最小を出力してください。', h1: '橋以外の辺で頂点をまとめると、橋だけからなる木(ブリッジツリー)になる。', h2: '木の葉の数を L とすると答えは (L+1)//2。葉どうしを繋ぐのが最も効率がよい。', ref: 'from collections import deque\nn,m=map(int,input().split())\nedges=[tuple(map(int,input().split())) for _ in range(m)]\ndef connected(skip):\n    g=[[] for _ in range(n+1)]\n    for i,(u,v) in enumerate(edges):\n        if i!=skip:\n            g[u].append(v)\n            g[v].append(u)\n    seen=[False]*(n+1)\n    seen[1]=True\n    q=deque([1])\n    c=1\n    while q:\n        x=q.popleft()\n        for y in g[x]:\n            if not seen[y]:\n                seen[y]=True\n                c+=1\n                q.append(y)\n    return c==n\nbridges=[i for i in range(m) if not connected(i)]\nif not bridges:\n    print(0)\nelse:\n    par=list(range(n+1))\n    def find(x):\n        while par[x]!=x:\n            par[x]=par[par[x]]\n            x=par[x]\n        return x\n    bs=set(bridges)\n    for i,(u,v) in enumerate(edges):\n        if i not in bs:\n            ru,rv=find(u),find(v)\n            if ru!=rv:\n                par[ru]=rv\n    deg={}\n    for i in bridges:\n        u,v=edges[i]\n        for r in (find(u),find(v)):\n            deg[r]=deg.get(r,0)+1\n    leaves=sum(1 for d in deg.values() if d==1)\n    print((leaves+1)//2)', tip: '「2辺連結成分に縮約して木を作り、葉をペアで繋ぐ」。ネットワークの耐障害化(単一リンク故障への強化)の最小コスト設計そのもの。', ins: ['5 4\n1 2\n2 3\n3 4\n4 5\n', '3 3\n1 2\n2 3\n1 3\n', '7 7\n1 2\n2 3\n3 1\n3 4\n4 5\n5 6\n6 4\n', '2 1\n1 2\n', '6 6\n1 2\n2 3\n3 1\n1 4\n1 5\n1 6\n', '4 4\n1 2\n2 3\n3 4\n4 1\n'] })

t({ lv: 478, concept: 'グラフ: 補グラフの連結成分数', title: '繋がっていない関係で見た成分数', tags: ['グラフ'], io: '1行目に n m、続く m 行に無向辺が与えられます。', ask: '補グラフ(元のグラフで辺が「無い」2頂点を辺で結んだグラフ)の連結成分数を出力してください。', h1: '隣接を集合で持ち、「隣接に無い頂点」へ移動するBFSをする。', h2: '各頂点から y が adj[x] に無いことを条件に探索する。', ref: 'from collections import deque\nn,m=map(int,input().split())\nadj=[set() for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    adj[u].add(v)\n    adj[v].add(u)\nseen=[False]*(n+1)\ncomps=0\nfor s in range(1,n+1):\n    if seen[s]:\n        continue\n    comps+=1\n    seen[s]=True\n    q=deque([s])\n    while q:\n        x=q.popleft()\n        for y in range(1,n+1):\n            if y!=x and not seen[y] and y not in adj[x]:\n                seen[y]=True\n                q.append(y)\nprint(comps)', tip: '元のグラフが疎なら補グラフは密で、ほとんどの頂点対が繋がる。「未訪問集合を持ち回って一気に消す」工夫でO(n+m)にできる。', ins: ['4 4\n1 2\n2 3\n3 4\n4 1\n', '3 3\n1 2\n2 3\n1 3\n', '3 0\n', '5 4\n1 2\n1 3\n1 4\n1 5\n', '2 1\n1 2\n', '6 7\n1 2\n1 3\n2 3\n4 5\n4 6\n5 6\n1 4\n'] })

t({ lv: 479, concept: 'マッチング: 一般グラフの最大マッチング', title: '2部とは限らないグラフの最大ペア数', tags: ['bitDP'], io: '1行目に n m、続く m 行に無向辺が与えられます (n≤16)。', ask: '端点を共有しない辺の集合(マッチング)の最大サイズを出力してください。グラフは2部グラフとは限りません。', h1: 'dp[残っている頂点集合] で最大ペア数を持つ。', h2: '集合の最小番号の頂点を「使わない」か「隣接の誰かと組む」かで遷移。', ref: 'n,m=map(int,input().split())\nadjm=[0]*n\nfor _ in range(m):\n    u,v=map(int,input().split())\n    adjm[u-1]|=1<<(v-1)\n    adjm[v-1]|=1<<(u-1)\ndp=[0]*(1<<n)\nfor mask in range(1,1<<n):\n    i=0\n    while not mask>>i&1:\n        i+=1\n    rest=mask^(1<<i)\n    best=dp[rest]\n    for j in range(n):\n        if rest>>j&1 and adjm[i]>>j&1:\n            v=dp[rest^(1<<j)]+1\n            if v>best:\n                best=v\n    dp[mask]=best\nprint(dp[(1<<n)-1])', tip: '2部グラフなら増加道(ハンガリー法)で解けるが、奇閉路のある一般グラフは花(blossom)の縮約が要る難問。小さいnならbitDPが確実。', ins: ['3 2\n1 2\n2 3\n', '4 4\n1 2\n3 4\n1 3\n2 4\n', '5 4\n1 2\n2 3\n3 4\n4 5\n', '1 0\n', '6 5\n1 2\n1 3\n1 4\n1 5\n1 6\n', '6 7\n1 2\n2 3\n3 1\n3 4\n4 5\n5 6\n6 4\n'] })

t({ lv: 480, concept: '木DP: 頂点重みの最大パス和', title: '木の中で最も重いパス', tags: ['木DP'], io: '1行目に頂点数 n、2行目に各頂点の重み(負もありうる)、続く n−1 行に木の辺が与えられます。', ask: '木の中の(1頂点以上の)パスであって、パス上の頂点重みの合計が最大のものの値を出力してください。', h1: '各頂点で「子方向へ降りる最良の腕」を返す再帰を書く。', h2: 'その頂点を頂上とするパスは「自分+腕の上位2本(負なら使わない)」。全頂点で最大を取る。', ref: 'import sys\nsys.setrecursionlimit(10000)\nn=int(input())\nw=list(map(int,input().split()))\ng=[[] for _ in range(n+1)]\nfor _ in range(n-1):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\nbest=-10**18\ndef dfs(v,p):\n    global best\n    t1=0\n    t2=0\n    for c in g[v]:\n        if c!=p:\n            d=dfs(c,v)\n            if d>t1:\n                t1,t2=d,t1\n            elif d>t2:\n                t2=d\n    cur=w[v-1]+t1+t2\n    if cur>best:\n        best=cur\n    return max(0,w[v-1]+t1)\ndfs(1,0)\nprint(best)', tip: '「頂上を全頂点で試し、腕は非負のときだけ伸ばす」。二分木の最大パス和の一般木版で、直径DPと同じ骨格を持つ。', ins: ['5\n1 2 3 4 5\n1 2\n1 3\n2 4\n2 5\n', '3\n-1 -2 -3\n1 2\n2 3\n', '1\n7\n', '4\n5 -10 5 5\n1 2\n2 3\n3 4\n', '5\n2 -1 2 -1 2\n1 2\n2 3\n3 4\n4 5\n', '3\n0 0 0\n1 2\n1 3\n'] })

t({ lv: 481, concept: '木DP: 全頂点からの距離総和', title: '各頂点から他の全頂点への距離の和', tags: ['木DP'], io: '1行目に頂点数 n、続く n−1 行に木の辺が与えられます。', ask: '各頂点 v について「v から他の全頂点への距離の合計」を、頂点1から順に空白区切りで出力してください。', h1: '各頂点からBFSすれば求まる。', h2: '大きな木では根の答えから「子へ移ると部分木側は−1、残りは+1」で全頂点へ展開する(全方位木DP)。', ref: 'from collections import deque\nn=int(input())\ng=[[] for _ in range(n+1)]\nfor _ in range(n-1):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\nout=[]\nfor s in range(1,n+1):\n    dist=[-1]*(n+1)\n    dist[s]=0\n    q=deque([s])\n    tot=0\n    while q:\n        x=q.popleft()\n        for y in g[x]:\n            if dist[y]<0:\n                dist[y]=dist[x]+1\n                tot+=dist[y]\n                q.append(y)\n    out.append(tot)\nprint(*out)', tip: '根を隣へ動かすと距離和は「向こう側の頂点数−こちら側の頂点数」だけ変わる。この差分展開(rerooting)は木の全頂点集計の万能パターン。', ins: ['4\n1 2\n2 3\n2 4\n', '2\n1 2\n', '1\n', '5\n1 2\n2 3\n3 4\n4 5\n', '4\n1 2\n1 3\n1 4\n', '6\n1 2\n1 3\n2 4\n2 5\n3 6\n'] })

t({ lv: 482, concept: '木: k個上の祖先', title: 'k個上の祖先を答える', tags: ['木'], io: '1行目に頂点数 n(根は1)、2行目に頂点2..nの親、3行目にクエリ数 q、続く q 行に「v k」が与えられます。', ask: '各クエリについて、頂点 v の k 個上の祖先の番号を出力してください。存在しなければ -1。', h1: '親を k 回たどる。', h2: '根を超えたら -1。大量クエリでは2^i個上の祖先表(ダブリング)を前計算する。', ref: 'n=int(input())\npar=[0,0]+list(map(int,input().split()))\nq=int(input())\nfor _ in range(q):\n    v,k=map(int,input().split())\n    for _ in range(k):\n        v=par[v]\n        if v==0:\n            break\n    print(v if v else -1)', tip: 'レベル祖先クエリと呼ばれる基本操作。kを2進展開して2^iずつ跳ぶダブリング表を作ればクエリO(log n)、LCAの部品にもなる。', ins: ['5\n1 1 2 2\n3\n4 1\n4 2\n4 3\n', '2\n1\n1\n2 1\n', '3\n1 2\n2\n3 2\n1 1\n', '6\n1 2 3 4 5\n2\n6 5\n6 6\n', '4\n1 1 3\n2\n4 1\n4 2\n', '3\n1 1\n1\n2 1\n'] })

t({ lv: 483, concept: 'データ構造: 逆順に見るUnion-Find', title: '辺を消すたびの連結成分数', tags: ['データ構造'], io: '1行目に n m、続く m 行に辺、最後の行に辺を消す順番(辺番号 1..m の並び、全て消す)が与えられます。', ask: '辺を1本消すたびに、その時点の連結成分数を順に空白区切りで出力してください。', h1: 'Union-Find は結合はできるが分割はできない。', h2: '時間を逆回しにして「消す」を「足す」に読み替えれば、後ろから Union-Find で処理できる。', ref: 'n,m=map(int,input().split())\nedges=[tuple(map(int,input().split())) for _ in range(m)]\norder=list(map(int,input().split()))\npar=list(range(n+1))\ndef find(x):\n    while par[x]!=x:\n        par[x]=par[par[x]]\n        x=par[x]\n    return x\ncomps=n\nvals=[0]*(m+1)\nvals[m]=n\nfor i in range(m-1,-1,-1):\n    u,v=edges[order[i]-1]\n    ru,rv=find(u),find(v)\n    if ru!=rv:\n        par[ru]=rv\n        comps-=1\n    vals[i]=comps\nprint(*vals[1:])', tip: '「削除は苦手でも追加は得意」な構造は、クエリを逆順に処理すると削除問題が解ける。オフライン処理の代表的な発想転換。', ins: ['4 3\n1 2\n2 3\n3 4\n3 1 2\n', '2 1\n1 2\n1\n', '3 3\n1 2\n2 3\n1 3\n1 2 3\n', '4 2\n1 2\n3 4\n2 1\n', '5 4\n1 2\n2 3\n4 5\n3 4\n4 2 3 1\n', '3 2\n1 2\n1 3\n1 2\n'] })

t({ lv: 484, concept: 'データ構造: デカルト木の高さ', title: '最小値を根にした木の高さ', tags: ['データ構造', '再帰'], io: '相異なる整数の列が1行で空白区切りで与えられます。', ask: '「区間の最小値を根とし、左側・右側の区間から再帰的に子を作る」木(デカルト木)の高さ(根から葉までの頂点数の最大)を出力してください。', h1: '区間の最小値の位置で左右に分ける。', h2: '高さは 1 + max(左の高さ, 右の高さ)。', ref: 'a=list(map(int,input().split()))\ndef h(l,r):\n    if l>r:\n        return 0\n    m=l\n    for i in range(l+1,r+1):\n        if a[i]<a[m]:\n            m=i\n    return 1+max(h(l,m-1),h(m+1,r))\nprint(h(0,len(a)-1))', tip: 'デカルト木は区間最小クエリと木構造を繋ぐ橋。ソート済み列では高さがnに退化する、という観察が乱択平衡木(Treap)の動機になる。', ins: ['3 1 2\n', '1 2 3 4\n', '2 1 4 3 5\n', '7\n', '4 3 2 1\n', '3 1 4 2 5\n'] })

t({ lv: 485, concept: 'DP: 和がSの部分長方形の数', title: '和がちょうどSの部分長方形を数える', tags: ['DP', '累積和'], io: '1行目に H W S、続く H 行に W 個ずつ整数が与えられます。', ask: '行・列とも連続した部分長方形のうち、要素の合計がちょうど S のものの個数を出力してください。', h1: '上端と下端の行の組を固定すると、列ごとの和の1次元問題になる。', h2: '1次元では累積和と辞書で「和がSの区間」を数える定石が使える。', ref: 'h,w,s=map(int,input().split())\ng=[list(map(int,input().split())) for _ in range(h)]\ncnt=0\nfor top in range(h):\n    col=[0]*w\n    for bot in range(top,h):\n        for c in range(w):\n            col[c]+=g[bot][c]\n        seen={0:1}\n        run=0\n        for c in range(w):\n            run+=col[c]\n            cnt+=seen.get(run-s,0)\n            seen[run]=seen.get(run,0)+1\nprint(cnt)', tip: '2次元を「行の組を固定して1次元に潰す」のはO(H²W)への典型的な次元削減。1次元側の「接頭和の差」の辞書勘定と組み合わせる。', ins: ['2 2 3\n1 2\n3 4\n', '1 3 0\n0 0 0\n', '2 2 10\n1 2\n3 4\n', '1 1 5\n5\n', '3 3 4\n1 1 1\n1 1 1\n1 1 1\n', '2 3 6\n1 2 3\n3 2 1\n'] })

t({ lv: 486, concept: '幾何: 軸平行長方形の数', title: '4点が作る軸に平行な長方形の数', tags: ['幾何'], io: '1行目に点数 n、続く n 行に相異なる点の座標が与えられます。', ask: '4点を選んで「辺が座標軸に平行な長方形」になる組の個数を出力してください。', h1: '同じ x 座標の点の y のペアが「縦の辺」の候補。', h2: '同じ (y1,y2) ペアが2つの異なる x に現れるごとに長方形が1つ。辞書でペアの出現数を数える。', ref: 'from collections import defaultdict\nn=int(input())\ncols=defaultdict(list)\nfor _ in range(n):\n    x,y=map(int,input().split())\n    cols[x].append(y)\npair=defaultdict(int)\nans=0\nfor x in sorted(cols):\n    ys=sorted(cols[x])\n    for i in range(len(ys)):\n        for j in range(i+1,len(ys)):\n            key=(ys[i],ys[j])\n            ans+=pair[key]\n            pair[key]+=1\nprint(ans)', tip: '「見つけるたびに、これまでの同類の数を足してから自分を登録する」勘定は、ペア数え上げ全般の定石。列ごとのyペアが長方形の縦辺そのもの。', ins: ['5\n0 0\n0 1\n1 0\n1 1\n2 2\n', '4\n0 0\n0 1\n1 0\n2 1\n', '6\n0 0\n0 1\n1 0\n1 1\n2 0\n2 1\n', '4\n0 0\n0 2\n3 0\n3 2\n', '3\n0 0\n1 1\n2 2\n', '9\n0 0\n0 1\n0 2\n1 0\n1 1\n1 2\n2 0\n2 1\n2 2\n'] })

t({ lv: 487, concept: '幾何: 2円の共有点の数', title: '2つの円の共有点はいくつか', tags: ['幾何'], io: 'x1 y1 r1 x2 y2 r2 が1行で与えられます(全て整数、同一の円は与えられない)。', ask: '2つの円の共有点の個数(0, 1, 2 のどれか)を出力してください。', h1: '中心間距離の2乗を、半径の和・差の2乗と比べる。', h2: '和より遠い、または差より近ければ0個。ちょうど等しければ接して1個。間なら2個。平方根は不要。', ref: 'x1,y1,r1,x2,y2,r2=map(int,input().split())\nd2=(x1-x2)**2+(y1-y2)**2\ns=(r1+r2)**2\nt=(r1-r2)**2\nif d2>s or d2<t:\n    print(0)\nelif d2==s or d2==t:\n    print(1)\nelse:\n    print(2)', tip: '距離の比較は2乗のまま行えば浮動小数を一切使わず厳密に判定できる。外接と内接の両方が「等号」で1点接触になる対称性が綺麗。', ins: ['0 0 2 5 0 2\n', '0 0 2 4 0 2\n', '0 0 2 3 0 2\n', '0 0 5 1 0 2\n', '0 0 3 1 0 2\n', '0 0 1 0 3 1\n'] })

t({ lv: 488, concept: '幾何: 多角形の重心', title: '多角形の重心の座標', tags: ['幾何'], io: '1行目に頂点数 n、続く n 行に単純多角形の頂点座標(整数、順に並ぶ)が与えられます。', ask: '多角形(一様な板とみなす)の重心の座標を、x y の順に小数第2位まで空白区切りで出力してください。', h1: '頂点の平均では正しい重心にならない(辺の長さに偏りがあるとずれる)。', h2: '各辺の外積を重みに、(x_i+x_{i+1}) を足し込み、最後に 3×符号付き面積の2倍 で割る。', ref: 'n=int(input())\npts=[tuple(map(int,input().split())) for _ in range(n)]\na=0\ncx=0\ncy=0\nfor i in range(n):\n    x1,y1=pts[i]\n    x2,y2=pts[(i+1)%n]\n    cr=x1*y2-x2*y1\n    a+=cr\n    cx+=(x1+x2)*cr\n    cy+=(y1+y2)*cr\nprint(f"{cx/(3*a):.2f} {cy/(3*a):.2f}")', tip: '靴ひも公式の重み付き版。符号付きで計算するので、頂点が時計回りでも反時計回りでも同じ答えになる。頂点平均との違いは細長い凹多角形で顕著。', ins: ['4\n0 0\n2 0\n2 2\n0 2\n', '3\n0 0\n3 0\n0 3\n', '3\n0 0\n6 0\n0 3\n', '4\n0 0\n4 0\n4 2\n0 2\n', '3\n1 1\n4 1\n1 4\n', '5\n0 0\n4 0\n4 4\n2 6\n0 4\n'] })

t({ lv: 489, concept: '幾何: 円内の格子点数', title: '円の内部と周上の格子点の数', tags: ['幾何', '数学'], io: '非負整数の半径 r が1行で与えられます。', ask: '原点中心・半径 r の円の内部または周上にある格子点 (x,y) の個数を出力してください。', h1: '各 x について y の範囲を数える。', h2: 'x を固定すると y は ±√(r²−x²) の範囲。math.isqrt で整数のまま数えられる。', ref: 'import math\nr=int(input())\nc=0\nfor x in range(-r,r+1):\n    y=math.isqrt(r*r-x*x)\n    c+=2*y+1\nprint(c)', tip: 'ガウスの円問題。個数はπr²に漸近し、誤差の評価は現在も未解決の難問。isqrtは浮動小数のsqrtと違い大きな整数でも誤差ゼロ。', ins: ['1\n', '2\n', '0\n', '3\n', '5\n', '10\n'] })

t({ lv: 490, concept: '線形代数: XORでTを作れるか', title: '部分集合のXORでTを作れるか', tags: ['bit演算'], io: '1行目に目標値 T、2行目に非負整数列が与えられます。', ask: 'いくつかの要素(0個でもよい)のXORをちょうど T にできるなら yes、できなければ no を出力してください。', h1: '全部分集合を試すと2^n通り。基底なら多項式時間。', h2: 'XOR基底を作り、T を基底で上位ビットから消していく。0にできれば作れる。', ref: 't=int(input())\na=list(map(int,input().split()))\nbasis=[0]*60\nfor x in a:\n    for i in range(59,-1,-1):\n        if not x>>i&1:\n            continue\n        if basis[i]==0:\n            basis[i]=x\n            break\n        x^=basis[i]\nfor i in range(59,-1,-1):\n    if t>>i&1 and basis[i]:\n        t^=basis[i]\nprint("yes" if t==0 else "no")', tip: '「作れる値の集合」は基底が張る線形空間。到達可能性の判定は掃き出しの残りが0かどうか、という線形代数の言葉に翻訳できる。', ins: ['3\n1 2\n', '4\n1 2\n', '0\n5 6\n', '7\n5 2\n', '6\n5 3\n', '1\n2 4\n'] })

export const CATALOG = TASKS
