// 生成タスク 第10波：コーディング面接(LeetCode系)の定番をオリジナル化。整数/文字列=採点一意。
const TASKS = []
const t = (obj) => TASKS.push(obj)

// 配列 (lv100)
t({ lv: 100, concept: 'LC: 欠けている数', title: '欠けている数', tags: ['配列', 'set'], io: '1行目に n、2行目に 0〜n のうち n 個の相異なる整数が与えられます。', ask: '0〜n のうち与えられていない数を1つ出力してください。', h1: '集合に入れて 0..n を探す。', h2: '無い数。', ref: 'n=int(input())\na=set(map(int,input().split()))\nfor i in range(n+1):\n    if i not in a:\n        print(i)\n        break', ins: ['3\n0 1 3\n', '3\n0 1 2\n', '1\n1\n', '5\n0 1 2 3 5\n', '4\n4 3 2 1\n', '2\n0 2\n'] })
t({ lv: 100, concept: 'LC: 最大連続1', title: '最大の連続する1の長さ', tags: ['配列', 'ループ'], io: '0と1からなる列が空白区切りで与えられます。', ask: '1が連続する最大の長さを出力してください。', h1: '1で伸ばし0でリセット。', h2: '最大を更新。', ref: 'a=input().split()\nbest=cur=0\nfor x in a:\n    cur=cur+1 if x=="1" else 0\n    best=max(best,cur)\nprint(best)', ins: ['1 1 0 1 1 1\n', '0 0 0\n', '1 1 1 1\n', '1 0 1 0 1\n', '0 1 1 0\n', '1\n'] })
t({ lv: 100, concept: 'LC: ゼロを後ろへ', title: 'ゼロを末尾へ移動', tags: ['配列'], io: '整数列が1行で与えられます。', ask: '0以外の順序を保ったまま、すべての0を末尾に寄せた列を出力してください。', h1: '非ゼロを先に集める。', h2: '残りを0で埋める。', ref: 'a=list(map(int,input().split()))\nnz=[x for x in a if x!=0]\nprint(*(nz+[0]*(len(a)-len(nz))))', ins: ['0 1 0 3 12\n', '1 2 3\n', '0 0 1\n', '0 0 0\n', '5 0 0 5\n', '1 0\n'] })
t({ lv: 100, concept: 'LC: 2乗してソート', title: '2乗してソート', tags: ['配列', 'ソート'], io: '昇順とは限らない整数列が1行で与えられます。', ask: '各要素を2乗し、昇順に並べて出力してください。', h1: '2乗してから sorted。', h2: '負も2乗で正に。', ref: 'a=list(map(int,input().split()))\nprint(*sorted(x*x for x in a))', ins: ['-4 -1 0 3 10\n', '-7 -3 2 3 11\n', '1 2 3\n', '-5 -4 -3\n', '0\n', '-2 2\n'] })
t({ lv: 100, concept: 'LC: プラスワン', title: '配列で表した数に1を足す', tags: ['配列'], io: '大きな整数の各桁が空白区切りで与えられます。', ask: '1を足した結果を各桁空白区切りで出力してください。', h1: '数に直して+1。', h2: '桁に戻す。', ref: 'd=input().split()\nn=int("".join(d))+1\nprint(*str(n))', ins: ['1 2 3\n', '9 9 9\n', '4 3 2 1\n', '9\n', '1 0 0\n', '9 9\n'] })

// パターン (lv150)
t({ lv: 150, concept: 'LC: 連続する整数の最長', title: '最長の連続する整数列', tags: ['set', 'アルゴリズム'], io: '整数列が1行で与えられます。', ask: '値が連続する (順不同) 最長の長さを出力してください。', h1: '集合にして列の始点を探す。', h2: '始点から伸ばす。', ref: 'a=set(map(int,input().split()))\nbest=0\nfor x in a:\n    if x-1 not in a:\n        y=x\n        while y in a:\n            y+=1\n        best=max(best,y-x)\nprint(best)', ins: ['100 4 200 1 3 2\n', '0 3 7 2 5 8 4 6 1\n', '1 2 3\n', '5\n', '9 1 4 7 3\n', '10 20 30\n'], tip: '💡 集合で「自分が列の先頭か」を O(1) 判定すると全体 O(n)。' })
t({ lv: 150, concept: 'LC: 隣接しない最大和', title: '隣接しない要素の最大和', tags: ['dp', 'アルゴリズム'], io: '正の整数列が1行で与えられます。', ask: '隣り合う要素を同時に選ばずに取るときの和の最大を出力してください。', h1: '各位置で「取る/取らない」。', h2: 'inc,exc を更新するDP。', ref: 'a=list(map(int,input().split()))\ninc=exc=0\nfor x in a:\n    inc,exc=exc+x,max(inc,exc)\nprint(max(inc,exc))', ins: ['2 7 9 3 1\n', '1 2 3 1\n', '5\n', '2 1 1 2\n', '10 5 10\n', '1 1 1 1\n'] })
t({ lv: 150, concept: 'LC: 部分配列の最大積', title: '連続部分配列の最大積', tags: ['dp', 'アルゴリズム'], io: '整数列が1行で与えられます。', ask: '連続する部分配列の積の最大値を出力してください。', h1: '最大と最小を同時に持つ。', h2: '負で最大最小が入れ替わる。', ref: 'a=list(map(int,input().split()))\nmx=mn=res=a[0]\nfor x in a[1:]:\n    if x<0:\n        mx,mn=mn,mx\n    mx=max(x,mx*x)\n    mn=min(x,mn*x)\n    res=max(res,mx)\nprint(res)', ins: ['2 3 -2 4\n', '-2 0 -1\n', '2 3 -2 4 -1\n', '-2 -3 -4\n', '3\n', '1 2 3\n'], tip: '💡 負×負で最大化するので「最小積」も同時に追う。' })
t({ lv: 150, concept: 'LC: 和が0の3つ組', title: '和が0になる3つ組の個数', tags: ['全探索', 'アルゴリズム'], io: '整数列が1行で与えられます。', ask: '異なる3要素 (位置 i<j<k) の和が0になる組の個数を出力してください。', h1: '3重ループ。', h2: 'i<j<k。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nc=0\nfor i in range(n):\n    for j in range(i+1,n):\n        for k in range(j+1,n):\n            if a[i]+a[j]+a[k]==0:\n                c+=1\nprint(c)', ins: ['-1 0 1 2 -1 -4\n', '0 0 0\n', '1 2 3\n', '-2 1 1 0\n', '3 -1 -2 0\n', '1 -1 0 2 -2\n'] })
t({ lv: 150, concept: 'LC: 括弧の深さ', title: '括弧の最大ネスト深さ', tags: ['スタック', '文字列'], io: '( と ) からなる文字列が与えられます。', ask: '括弧の最大の入れ子の深さを出力してください。', h1: '( で+1, ) で-1。', h2: '途中の最大値。', ref: 's=input()\nd=best=0\nfor c in s:\n    if c=="(":\n        d+=1\n        best=max(best,d)\n    elif c==")":\n        d-=1\nprint(best)', ins: ['((()))\n', '(())()\n', '()\n', '(((\n', '()()()\n', '(()(()))\n'] })
t({ lv: 150, concept: 'LC: 有効な回文', title: '英数字だけ見た回文判定', tags: ['二点ポインタ', '文字列'], io: '記号や空白を含む文字列が与えられます。', ask: '英数字だけを取り出し大小を無視したとき回文なら yes、違えば no を出力してください。', h1: 'isalnum で絞る。', h2: '小文字化して反転比較。', ref: 's=input()\nt=[c.lower() for c in s if c.isalnum()]\nprint("yes" if t==t[::-1] else "no")', ins: ['A man a plan a canal Panama\n', 'race a car\n', 'abba\n', 'Was it a car or a cat I saw\n', 'x\n', 'ab\n'] })
t({ lv: 150, concept: 'LC: ローマ数字を整数に', title: 'ローマ数字を整数に', tags: ['文字列'], io: 'ローマ数字の文字列が与えられます。', ask: '対応する整数を出力してください。', h1: '右より小さい文字は引く。', h2: 'I,V,X,L,C,D,M。', ref: 's=input()\nv={"I":1,"V":5,"X":10,"L":50,"C":100,"D":500,"M":1000}\ntotal=0\nfor i in range(len(s)):\n    if i+1<len(s) and v[s[i]]<v[s[i+1]]:\n        total-=v[s[i]]\n    else:\n        total+=v[s[i]]\nprint(total)', ins: ['III\n', 'IV\n', 'IX\n', 'LVIII\n', 'MCMXCIV\n', 'XLII\n'] })
t({ lv: 150, concept: 'LC: 整数をローマ数字に', title: '整数をローマ数字に', tags: ['文字列', '貪欲'], io: '1〜3999 の整数が与えられます。', ask: 'ローマ数字に変換して出力してください。', h1: '大きい値から貪欲に引く。', h2: '900,400,90,40,9,4 も用意。', ref: 'n=int(input())\nval=[1000,900,500,400,100,90,50,40,10,9,5,4,1]\nsym=["M","CM","D","CD","C","XC","L","XL","X","IX","V","IV","I"]\nr=""\nfor v,s in zip(val,sym):\n    while n>=v:\n        r+=s\n        n-=v\nprint(r)', ins: ['3\n', '4\n', '9\n', '58\n', '1994\n', '42\n'] })
t({ lv: 150, concept: 'LC: 最初のユニーク文字', title: '最初に1度だけ現れる文字の位置', tags: ['collections', '文字列'], io: '英小文字の文字列が与えられます。', ask: '1度だけ現れる最初の文字の位置 (0始まり) を、無ければ -1 を出力してください。', h1: 'Counter で回数。', h2: '前から1回の文字を探す。', ref: 'from collections import Counter\ns=input()\nc=Counter(s)\nfor i,ch in enumerate(s):\n    if c[ch]==1:\n        print(i)\n        break\nelse:\n    print(-1)', ins: ['beetroot\n', 'aabb\n', 'abcabc\n', 'x\n', 'swiss\n', 'aabbc\n'] })
t({ lv: 150, concept: 'LC: 最長共通接頭辞(複数)', title: '複数語の最長共通接頭辞', tags: ['文字列'], io: '空白区切りの単語が1行で与えられます。', ask: 'すべてに共通する最長の接頭辞 (無ければ空行) を出力してください。', h1: '先頭語から削っていく。', h2: '全語が startswith するまで。', ref: 'ws=input().split()\np=ws[0]\nfor w in ws[1:]:\n    while not w.startswith(p):\n        p=p[:-1]\n    if not p:\n        break\nprint(p)', ins: ['flower flow flight\n', 'dog racecar car\n', 'abc abc abc\n', 'interspecies interstellar interstate\n', 'alone\n', 'pre prefix prefab\n'] })

export const CATALOG = TASKS
