// 生成タスク 第17波：定番アルゴリズムの別計算。整数/文字列=採点一意。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 150, concept: 'スタック: 逆ポーランド記法', title: '逆ポーランド記法の計算', tags: ['スタック', 'アルゴリズム'], io: '逆ポーランド記法 (後置記法) の式が空白区切りで与えられます (整数と + - * /)。', ask: '計算結果を出力してください (除算は0方向への切り捨て)。', h1: '数はスタックに積む。', h2: '演算子で2つ取り出して計算。', ref: "st=[]\nfor tok in input().split():\n    if tok in ('+','-','*','/'):\n        b=st.pop()\n        a=st.pop()\n        st.append(a+b if tok=='+' else a-b if tok=='-' else a*b if tok=='*' else int(a/b))\n    else:\n        st.append(int(tok))\nprint(st[0])", ins: ['3 4 +\n', '5 1 2 + 4 * + 3 -\n', '2 3 *\n', '10 2 /\n', '4 5 6 * +\n', '7\n'], tip: '💡 後置記法はスタックで括弧なしに評価できる。電卓の内部表現。' })
t({ lv: 750, concept: '文字列DP: 最長回文部分列', title: '最長回文部分列の長さ', tags: ['dp', '文字列'], io: '文字列 s が与えられます。', ask: '(連続でなくてよい) 回文になる部分列の最大の長さを出力してください。', h1: 'dp[i][j]=区間[i,j]の答え。', h2: '両端一致なら+2、違えば内側の最大。', ref: 's=input()\nn=len(s)\ndp=[[0]*n for _ in range(n)]\nfor i in range(n-1,-1,-1):\n    dp[i][i]=1\n    for j in range(i+1,n):\n        if s[i]==s[j]:\n            dp[i][j]=dp[i+1][j-1]+2\n        else:\n            dp[i][j]=max(dp[i+1][j],dp[i][j-1])\nprint(dp[0][n-1])', ins: ['bbbab\n', 'cbbd\n', 'a\n', 'agbdba\n', 'abcde\n', 'aa\n'] })
t({ lv: 130, concept: '数論: 友愛数', title: '友愛数の判定', tags: ['数論'], io: '正の整数 a が与えられます。', ask: 'a の真の約数の和を b としたとき、a≠b かつ b の真の約数の和が a に戻るなら yes (友愛数)、違えば no を出力してください。', h1: '真の約数の和 s(x) を作る。', h2: 's(s(a))==a かつ a≠s(a)。', ref: 'def s(x):\n    return sum(i for i in range(1,x) if x%i==0)\na=int(input())\nb=s(a)\nprint("yes" if b!=a and s(b)==a else "no")', ins: ['220\n', '284\n', '6\n', '12\n', '1184\n', '10\n'], tip: '💡 220 と 284 は最小の友愛数ペア。' })
t({ lv: 600, concept: 'グラフ: 最短経路の辺数', title: '最短経路の辺数 (BFS)', tags: ['グラフ', 'BFS', 'アルゴリズム'], io: '1行目に n m、続く m 行に無向辺 u v (1始まり)、最後に始点と終点 s t が与えられます。', ask: 's から t までの最短経路の辺数を、到達不能なら -1 を出力してください。', h1: '重みなし最短路はBFS。', h2: '訪問時に距離を確定。', ref: 'from collections import deque\nn,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\ns,t=map(int,input().split())\ndist=[-1]*(n+1)\ndist[s]=0\ndq=deque([s])\nwhile dq:\n    x=dq.popleft()\n    for y in g[x]:\n        if dist[y]<0:\n            dist[y]=dist[x]+1\n            dq.append(y)\nprint(dist[t])', ins: ['4 3\n1 2\n2 3\n3 4\n1 4\n', '3 1\n1 2\n1 3\n', '2 0\n1 2\n', '5 4\n1 2\n2 3\n3 4\n4 5\n1 5\n', '3 2\n1 2\n2 3\n1 3\n', '4 2\n1 2\n3 4\n1 4\n'] })
t({ lv: 600, concept: 'グラフ: 連結成分の数', title: '連結成分の数', tags: ['グラフ', 'BFS', 'アルゴリズム'], io: '1行目に n m、続く m 行に無向辺 u v (1始まり) が与えられます。', ask: '連結成分の個数を出力してください。', h1: '未訪問の頂点からBFS。', h2: '開始した回数が成分数。', ref: 'from collections import deque\nn,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\nseen=[False]*(n+1)\nc=0\nfor s in range(1,n+1):\n    if not seen[s]:\n        c+=1\n        dq=deque([s])\n        seen[s]=True\n        while dq:\n            x=dq.popleft()\n            for y in g[x]:\n                if not seen[y]:\n                    seen[y]=True\n                    dq.append(y)\nprint(c)', ins: ['4 2\n1 2\n3 4\n', '5 0\n', '3 3\n1 2\n2 3\n1 3\n', '6 3\n1 2\n3 4\n5 6\n', '4 3\n1 2\n2 3\n3 4\n', '1 0\n'] })
t({ lv: 150, concept: 'スタック: 多種括弧の対応', title: '3種の括弧の整合', tags: ['スタック', '文字列'], io: '() [] {} からなる文字列が与えられます。', ask: 'すべての括弧が正しく対応していれば yes、いなければ no を出力してください。', h1: '開き括弧をスタックに積む。', h2: '閉じ括弧は直近の開きと一致するか。', ref: "s=input()\nst=[]\npair={')':'(',']':'[','}':'{'}\nok=True\nfor c in s:\n    if c in '([{':\n        st.append(c)\n    elif c in ')]}':\n        if not st or st.pop()!=pair[c]:\n            ok=False\n            break\nprint('yes' if ok and not st else 'no')", ins: ['()[]{}\n', '([{}])\n', '(]\n', '([)]\n', '(((\n', '()\n'] })
t({ lv: 45, concept: '文字列: ハミング距離', title: '2文字列のハミング距離', tags: ['文字列', 'zip'], io: '同じ長さの2つの文字列が各行で与えられます。', ask: '異なる位置の文字数 (ハミング距離) を出力してください。', h1: '位置ごとに比較。', h2: 'zip で対応づけ。', ref: 'a=input()\nb=input()\nprint(sum(1 for x,y in zip(a,b) if x!=y))', ins: ['karolin\nkathrin\n', 'abc\nabc\n', '1011\n1001\n', 'aaaa\nbbbb\n', 'xx\nxy\n', 'abcd\nabce\n'] })
t({ lv: 45, concept: '文字列: 最長共通接尾辞', title: '2語の最長共通接尾辞', tags: ['文字列'], io: '2つの文字列が各行で与えられます。', ask: '末尾から一致する最長の共通部分 (無ければ空行) を出力してください。', h1: '末尾から1文字ずつ比較。', h2: '違ったら止める。', ref: 'a=input()\nb=input()\ni=0\nwhile i<len(a) and i<len(b) and a[-1-i]==b[-1-i]:\n    i+=1\nprint(a[len(a)-i:] if i else "")', ins: ['testing\nrunning\n', 'abc\nxyc\n', 'same\nsame\n', 'abc\ndef\n', 'ing\nsing\n', 'a\nba\n'] })

export const CATALOG = TASKS
