// 生成タスク 第80波：各レベル3問化フェーズ(7)。lv329〜377 の薄い49段に3問目を追加。
// 数論/文字列/グラフ/DP/貪欲帯。クラスタ3問まで可・言い換え水増し禁止。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 329, concept: '文字列: 共通する最長接尾辞の長さ', title: '語尾はどこまで揃うか', tags: ['文字列'], io: '単語が空白区切りで1行に与えられます。', ask: '全ての単語に共通する最長の接尾辞(末尾の並び)の長さを出力してください。', h1: '共通接頭辞(同レベル既出)の後ろ版。', h2: '末尾から1文字ずつ全単語で一致する限り数える。', ref: 'ws=input().split()\ni=0\nwhile all(len(w)>i for w in ws) and len(set(w[len(w)-1-i] for w in ws))==1:\n    i+=1\nprint(i)', tip: '活用語尾や複数形の -s の検出は共通接尾辞の集計そのもの。全単語を反転して接頭辞の問題に写す解法もあり、変換で既存の道具を再利用する発想が学べる。', ins: ['running walking talking\n', 'abc abc\n', 'x y\n', 'hat cat rat\n', 'a ba\n', 'hello\n'] })

t({ lv: 330, concept: '行列: 蛇行順の走査', title: '牛耕式に読み上げる', tags: ['行列'], io: '1行目に H W、続く H 行に行列が与えられます。', ask: '1行目は左から右、2行目は右から左、と1行ごとに向きを変えながら全要素を空白区切りで1行に出力してください。', h1: '奇数番目の行だけ反転する。', h2: '行番号の偶奇でスライス[::-1]を切り替える。', ref: 'h,w=map(int,input().split())\nout=[]\nfor i in range(h):\n    row=input().split()\n    if i%2==1:\n        row=row[::-1]\n    out+=row\nprint(" ".join(out))', tip: '畑を耕す牛の往復に似た走査は「ブストロフェドン」と呼ばれ、プリンタのヘッド移動やメモリのアクセス局所性の最適化に現れる。斜めジグザグ(同レベル既出)より一段素直な蛇行。', ins: ['2 3\n1 2 3\n4 5 6\n', '1 4\n1 2 3 4\n', '3 2\n1 2\n3 4\n5 6\n', '2 2\n9 8\n7 6\n', '3 1\n1\n2\n3\n', '2 4\n1 1 1 1\n2 2 2 2\n'] })

t({ lv: 331, concept: '数論: 五角数かどうか', title: '五角形に並べられる数か', tags: ['数論'], io: '正整数 k が1行で与えられます。', ask: 'k が五角数(1, 5, 12, 22, 35, …、n(3n−1)/2 の形)なら yes、そうでなければ no を出力してください。', h1: '三角数の判定(同レベル既出)と同じ発想。', h2: 'n を1から増やして n(3n−1)/2 を k と比べる。', ref: 'k=int(input())\nn=1\nwhile n*(3*n-1)//2<k:\n    n+=1\nprint("yes" if n*(3*n-1)//2==k else "no")', tip: '五角数はオイラーの五角数定理で分割数の計算に劇的な高速化をもたらす主役。判定は 1+24k が平方数かつ根が6で割って1余るか、という閉じた式でも書ける。', ins: ['5\n', '1\n', '12\n', '10\n', '22\n', '7\n'] })

t({ lv: 332, concept: '進数: k進法の筆算たし算', title: 'k進の世界の足し算', tags: ['進数'], io: '1行目に基数 k (2〜10)、2行目と3行目に k 進表記の正整数が与えられます。', ask: '2つの数の和を k 進表記で出力してください。', h1: '10進に直して足してから戻すのが確実。', h2: '桁ごとの繰り上がりで直接やってもよい。', ref: 'k=int(input())\na=int(input(),k)\nb=int(input(),k)\ns=a+b\nds=[]\nwhile s:\n    ds.append(str(s%k))\n    s//=k\nprint("".join(reversed(ds)))', tip: 'int(s, k) が任意基数のパースを一手に引き受ける。変換(既出)を往復に組むと「基数はただの表記」という実感が固まり、繰り上がりの一般論も見えてくる。', ins: ['2\n101\n11\n', '8\n17\n1\n', '3\n12\n12\n', '5\n44\n1\n', '10\n99\n1\n', '2\n1\n1\n'] })

t({ lv: 333, concept: '数論: フィボナッチをその番号で割った余り', title: '自分の背番号で割ってみる', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: 'フィボナッチ数 F(n) (F(1)=F(2)=1) を n で割った余りを出力してください。', h1: '割り算は最後にやらず、途中からmodで持ち回れる。', h2: 'a,b=b,(a+b)%n の型。', ref: 'n=int(input())\na,b=1,1\nfor _ in range(n-1):\n    a,b=b,(a+b)%n\nprint(a%n)', tip: 'F(p)≡±1 (mod p) が素数pで成り立つ(フィボナッチ・オイラーの規準)ため、この余りは素数性の弱いテストにもなる。mod nの世界でフィボナッチを回す練習。', ins: ['5\n', '1\n', '7\n', '10\n', '12\n', '11\n'] })

t({ lv: 334, concept: '数論: 完全トーティエント数か', title: 'φを繰り返すと自分に戻る数', tags: ['数論'], io: '2以上の整数 n が1行で与えられます。', ask: 'オイラー関数φを n に繰り返し適用して1になるまでの値(φ(n), φ(φ(n)), …, 1)の総和が n 自身と等しい(完全トーティエント数)なら yes、そうでなければ no を出力してください。', h1: 'φを素朴に計算する関数を作る。', h2: '1になるまで足し込んで比較。', ref: 'def phi(x):\n    c=0\n    for k in range(1,x+1):\n        a,b=k,x\n        while b:\n            a,b=b,a%b\n        if a==1:\n            c+=1\n    return c\nn=int(input())\ns=0\nx=n\nwhile x>1:\n    x=phi(x)\n    s+=x\nprint("yes" if s==n else "no")', tip: '3, 9, 15, 27, 39…と3の倍数が目立つのは、3^k が全て完全トーティエント数だから。関数の反復(軌道)を集計する発想はハッピー数やコラッツと同じ族。', ins: ['3\n', '9\n', '4\n', '27\n', '10\n', '15\n'] })

t({ lv: 335, concept: '数論: N以下の不足数の個数', title: '控えめな数を数える', tags: ['数論'], io: '正整数 N が1行で与えられます。', ask: '1 以上 N 以下で、真の約数の和が自分より小さい数(不足数)の個数を出力してください。', h1: '過剰数を数える(同レベル既出)の鏡像。', h2: '1も不足数(真の約数の和は0)。', ref: 'n=int(input())\ndef s(x):\n    total=0\n    i=1\n    while i*i<=x:\n        if x%i==0:\n            if i<x:\n                total+=i\n            j=x//i\n            if j!=i and j<x:\n                total+=j\n        i+=1\n    return total\nprint(sum(1 for x in range(1,n+1) if s(x)<x))', tip: '不足数は圧倒的多数派で、素数は全て不足数(約数和が1)。過剰・完全・不足の3分類の個数を足すとNになる、という検算が一行で書ける。', ins: ['10\n', '6\n', '1\n', '12\n', '20\n', '30\n'] })

t({ lv: 336, concept: 'ソート: 昇順が保たれる最長の接頭辞', title: 'どこまでは順番どおりか', tags: ['ソート', 'リスト'], io: '整数列が1行で空白区切りで与えられます。', ask: '先頭から見て広義単調増加(次の値が前の値以上)が保たれる最長の接頭辞の長さを出力してください。', h1: '最初に順序が崩れる場所を探す。', h2: 'a[i]<a[i−1] となる最初のiまで。', ref: 'a=list(map(int,input().split()))\nk=1\nwhile k<len(a) and a[k]>=a[k-1]:\n    k+=1\nprint(k)', tip: 'ほぼソート済みのデータで「どこから乱れたか」を特定する診断は、差分ソートや修復の前処理になる。breakのあるループを while の条件式に畳む書き方の練習にもよい。', ins: ['1 2 2 1 5\n', '3 1\n', '1 2 3\n', '5\n', '2 2 2\n', '9 1 2 3\n'] })

t({ lv: 337, concept: '二点法: 2列から選ぶ差の最小', title: '二つの箱から一番近い組', tags: ['二点法', 'ソート'], io: '1行目と2行目に整数列が与えられます。', ask: 'それぞれの列から1つずつ選んだ2数の差の絶対値の最小を出力してください。', h1: '両方ソートすると二点法が使える。', h2: '小さい方の指を進めながら差を記録する。', ref: 'a=sorted(map(int,input().split()))\nb=sorted(map(int,input().split()))\ni=j=0\nbest=abs(a[0]-b[0])\nwhile i<len(a) and j<len(b):\n    d=abs(a[i]-b[j])\n    if d<best:\n        best=d\n    if a[i]<b[j]:\n        i+=1\n    else:\n        j+=1\nprint(best)', tip: '1つの列の最近ペア(既出)は隣接だけ見ればよかったが、2列版は「小さい方を進める」マージの足取りになる。全組合せO(nm)からO(n log n)への典型的な圧縮。', ins: ['1 5 9\n3 10\n', '1 2\n8 9\n', '5\n5\n', '1 100\n50\n', '3 7\n4 8\n', '10 20 30\n25 5\n'] })

t({ lv: 338, concept: '累積和: 2つに切る差の最小', title: '一番公平な切れ目', tags: ['累積和'], io: '整数列(2個以上)が1行で空白区切りで与えられます。', ask: '列を空でない前半と後半に切るとき、前半の和と後半の和の差の絶対値の最小を出力してください。', h1: '切れ目ごとの差を全部試す。', h2: '前の和を伸ばしながら |前−(全体−前)| を更新。', ref: 'a=list(map(int,input().split()))\ntotal=sum(a)\nleft=0\nbest=None\nfor i in range(len(a)-1):\n    left+=a[i]\n    d=abs(left-(total-left))\n    if best is None or d<best:\n        best=d\nprint(best)', tip: '「連続した2分割」は切れ目がn−1通りしかないので全探索できる。部分集合で分ける2分割(自由な割り振り)がDPを要するのと対照的で、制約が強いほど簡単になる好例。', ins: ['1 2 3 4\n', '5 5\n', '1 1 1\n', '10 1 1\n', '1 9\n', '3 1 2\n'] })

t({ lv: 339, concept: '行列: 転置で値が変わらない場所の数', title: '鏡に映しても同じマス', tags: ['行列'], io: '1行目に n、続く n 行に n×n の行列が与えられます。', ask: 'A[i][j] と A[j][i] が等しいマス (i,j) の個数を出力してください(対角のマスも数えます)。', h1: '対称判定(既出)の全否ではなく個数版。', h2: '二重ループで比較して数えるだけ。', ref: 'n=int(input())\nA=[list(map(int,input().split())) for _ in range(n)]\nprint(sum(1 for i in range(n) for j in range(n) if A[i][j]==A[j][i]))', tip: '対称行列ならn²、非対称の崩れは必ず2マスずつ対で減る(答えとn²の差は偶数)。判定のyes/noを「どれくらい対称か」の度合いに拡張する見方。', ins: ['2\n1 2\n2 1\n', '2\n1 2\n3 4\n', '1\n7\n', '3\n1 0 0\n0 1 0\n0 0 1\n', '3\n1 2 3\n2 1 4\n3 5 1\n', '2\n0 5\n6 0\n'] })

t({ lv: 340, concept: '文字列: 中置記法を後置記法へ', title: '式を計算しやすい順に並べ替える', tags: ['文字列', 'スタック'], io: '英小文字と数字を項とし、+ - * / と括弧からなる式(空白なし)が1行で与えられます。', ask: '後置記法(逆ポーランド記法)に変換した文字列を出力してください。', h1: '操車場アルゴリズム: 項は即出力、演算子はスタックへ。', h2: '優先順位が自分以上の演算子をスタックから吐き出してから積む。( は壁、) は ( まで吐く。', ref: 's=input()\nprec={"+":1,"-":1,"*":2,"/":2}\nout=[]\nst=[]\nfor c in s:\n    if c.isalnum():\n        out.append(c)\n    elif c=="(":\n        st.append(c)\n    elif c==")":\n        while st[-1]!="(":\n            out.append(st.pop())\n        st.pop()\n    else:\n        while st and st[-1]!="(" and prec[st[-1]]>=prec[c]:\n            out.append(st.pop())\n        st.append(c)\nwhile st:\n    out.append(st.pop())\nprint("".join(out))', tip: 'ダイクストラ考案の操車場(shunting-yard)アルゴリズム。逆ポーランドの計算(既出)と繋げると、括弧つきの式を評価する電卓が2部品の合成で完成する。', ins: ['a+b*c\n', '(a+b)*c\n', 'a+b+c\n', 'a*(b+c)/d\n', 'x\n', 'a-b*c+d\n'] })

t({ lv: 341, concept: '数え上げ: 重複のない部分文字列の数', title: '全部違う文字でできた区間を数える', tags: ['数え上げ', '二点法'], io: '英小文字の文字列が1行で与えられます。', ask: '同じ文字を2度含まない連続部分文字列の個数(位置で区別)を出力してください。', h1: '最長(同レベル既出)と同じ窓の動きで数えられる。', h2: '右端ごとに有効な左端の範囲の長さ r−l+1 を足す。', ref: 's=input()\nlast={}\nl=0\ncnt=0\nfor r,c in enumerate(s):\n    if c in last and last[c]>=l:\n        l=last[c]+1\n    last[c]=r\n    cnt+=r-l+1\nprint(cnt)', tip: '最長を求める窓とまったく同じ走査で、maxを取る代わりに窓の長さを足すだけ。二点法の「各右端での有効範囲」という視点が最長と個数を同時に説明する。', ins: ['abc\n', 'aa\n', 'aab\n', 'abab\n', 'x\n', 'abcd\n'] })

t({ lv: 342, concept: '貪欲: 辞書順最大の部分列', title: '選んで作る一番強い文字列', tags: ['貪欲', '文字列'], io: '英小文字の文字列が1行で与えられます。', ask: '部分列(文字を取り除いてできる列)のうち辞書順最大のものを出力してください。', h1: 'k文字選ぶ最小(同レベル既出)と違い長さは自由。', h2: '右から見て「今までの最大以上」の文字だけ残すと、単調非増加の列になる。', ref: 's=input()\nres=[]\nfor c in reversed(s):\n    if not res or c>=res[-1]:\n        res.append(c)\nprint("".join(reversed(res)))', tip: '答えは必ず非増加列になる、と先に構造を見抜くと貪欲の正しさが一目で分かる。接尾辞の最大値の並びを拾っているだけ、という見方もできる。', ins: ['ababb\n', 'abc\n', 'cba\n', 'banana\n', 'zzz\n', 'abczxy\n'] })

t({ lv: 343, concept: '貪欲: 一周に必要な最初の燃料', title: '出発前に積んでおく燃料', tags: ['貪欲', '累積和'], io: '1行目に地点数 n、2行目に各地点の補給量、3行目に次の地点までの消費量が与えられます。地点1から出発して一周します。', ask: '出発時に積んでおくべき燃料の最小量(途中で燃料が負にならないため)を出力してください。', h1: '補給−消費の累積を追う。', h2: '累積の最小値が−mなら、最初にmを積めばよい。', ref: 'n=int(input())\ng=list(map(int,input().split()))\nc=list(map(int,input().split()))\ns=0\nlow=0\nfor i in range(n):\n    s+=g[i]-c[i]\n    if s<low:\n        low=s\nprint(-low)', tip: '「どこかで足りなくなる最大の不足分だけ最初に持てばよい」という累積最小の直読み。一周できる出発点を探す問題(既出)と同じデータを別の問いで眺めている。', ins: ['3\n1 1 1\n2 1 1\n', '2\n5 5\n1 1\n', '3\n0 0 6\n2 2 2\n', '1\n0\n3\n', '4\n1 2 3 4\n4 3 2 1\n', '2\n3 0\n1 1\n'] })

t({ lv: 344, concept: 'DP: 差がちょうどDの2分割があるか', title: '差を狙い通りにする山分け', tags: ['DP'], io: '1行目に D、2行目に正整数の列が与えられます。', ask: '列を2つのグループ(空でもよい)に分けて和の差の絶対値をちょうど D にできるなら yes、できなければ no を出力してください。', h1: '差の最小(同レベル既出)の「ちょうど」版。', h2: '片方の和sを全通り求め、|合計−2s|==D を探す。', ref: 'D=int(input())\na=list(map(int,input().split()))\ntotal=sum(a)\ns={0}\nfor x in a:\n    s|={y+x for y in s}\nprint("yes" if any(abs(total-2*x)==D for x in s) else "no")', tip: '2分割の差は「合計−2×片方」なので、部分集合の和の集合さえあれば差の問いは全部答えられる。1つの前計算が最小・ちょうど・以下の全変種を賄う。', ins: ['2\n1 3\n', '0\n2 2\n', '1\n2 2\n', '3\n1 2\n', '10\n1 2 3\n', '4\n5 1\n'] })

t({ lv: 345, concept: 'DP: 無くても困らない硬貨の数', title: 'その額面、本当に必要?', tags: ['DP'], io: '1行目に上限 M、2行目に相異なる額面(どれも何枚でも使え、全部使えば1〜Mの全額が作れる)が与えられます。', ask: '「その額面を取り除いても1からMまでの全ての金額が作れる」額面の個数を出力してください。', h1: '額面ごとに取り除いて全額判定をやり直す。', h2: '作れる金額の判定は硬貨DP(到達可能集合)で。', ref: 'M=int(input())\ncoins=list(map(int,input().split()))\ndef covers(cs):\n    dp=[False]*(M+1)\n    dp[0]=True\n    for c in cs:\n        for s in range(c,M+1):\n            if dp[s-c]:\n                dp[s]=True\n    return all(dp[1:])\nprint(sum(1 for i in range(len(coins)) if covers(coins[:i]+coins[i+1:])))', tip: '額面系の冗長性の分析で、1円だけは絶対に外せない(1が作れなくなる)。システム設計で「この部品を外しても仕様を満たすか」を全数検査する、削減テストの型そのもの。', ins: ['6\n1 2 3\n', '4\n1 2\n', '10\n1 2 5\n', '3\n1 3\n', '5\n1 5\n', '8\n1 2 4 8\n'] })

t({ lv: 346, concept: 'グリッド: 8近傍がすべて1のマスの数', title: 'まわりを味方に囲まれたマス', tags: ['グリッド'], io: '1行目に H W、続く H 行に 0/1 の文字列が与えられます。', ask: '自分が1で、周囲8方向のマスもすべて1であるマスの個数を出力してください(盤外は0とみなします)。', h1: '端のマスは自動的に失格。', h2: '内側だけ二重ループし、3×3を確かめる。', ref: 'h,w=map(int,input().split())\ng=[input() for _ in range(h)]\ncnt=0\nfor i in range(1,h-1):\n    for j in range(1,w-1):\n        if all(g[i+di][j+dj]=="1" for di in (-1,0,1) for dj in (-1,0,1)):\n            cnt+=1\nprint(cnt)', tip: '画像処理の「侵食(erosion)」の1ステップで、輪郭の1層を削って芯だけ残す操作の数え上げ版。範囲を1..h−2に絞ると境界チェックが丸ごと消える。', ins: ['3 3\n111\n111\n111\n', '3 3\n111\n101\n111\n', '3 4\n1111\n1111\n1111\n', '2 2\n11\n11\n', '4 4\n1111\n1111\n1111\n1111\n', '3 3\n010\n111\n010\n'] })

t({ lv: 347, concept: '貪欲: 両端から取って作る辞書順最小', title: '前からか後ろからか、いい方を取る', tags: ['貪欲', '文字列'], io: '英小文字の文字列が1行で与えられます。', ask: '毎回「残りの先頭か末尾」のどちらかの文字を取り除いて答えの末尾に追加していき、最後にできる文字列を辞書順最小にしたものを出力してください。', h1: '先頭と末尾の文字が違えば小さい方。', h2: '同じときは残り全体と反転を比較して決める。', ref: 's=input()\nres=[]\nwhile s:\n    if s<=s[::-1]:\n        res.append(s[0])\n        s=s[1:]\n    else:\n        res.append(s[-1])\n        s=s[:-1]\nprint("".join(res))', tip: '端の文字だけ比べると同字のときに将来の損得が見えない。「残り全体と反転の比較」で先読みを一括処理するのがこの貪欲の芯で、文字列比較の辞書順が先読みを肩代わりしている。', ins: ['cab\n', 'ab\n', 'ba\n', 'aab\n', 'zya\n', 'cbca\n'] })

t({ lv: 348, concept: 'DAG: 重みつき最短経路', title: '一方通行の街の最短路', tags: ['グラフ', 'DP'], io: '1行目に頂点数 n と辺数 m、続く m 行に有向辺 u v w (閉路なし、負の重みもあり得る) が与えられます(頂点1から頂点nへ到達可能)。', ask: '頂点1から頂点nへの最短距離を出力してください。', h1: '閉路が無いのでダイクストラの制約(非負)が要らない。', h2: 'トポロジカル順に緩和すれば1パスで確定する。', ref: 'from collections import deque\nn,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nind=[0]*(n+1)\nfor _ in range(m):\n    u,v,w=map(int,input().split())\n    g[u].append((v,w))\n    ind[v]+=1\nINF=10**18\ndist=[INF]*(n+1)\ndist[1]=0\nq=deque(v for v in range(1,n+1) if ind[v]==0)\nwhile q:\n    x=q.popleft()\n    for to,w in g[x]:\n        if dist[x]<INF and dist[x]+w<dist[to]:\n            dist[to]=dist[x]+w\n        ind[to]-=1\n        if ind[to]==0:\n            q.append(to)\nprint(dist[n])', tip: 'DAGなら負辺があってもトポ順DPでO(V+E)、ベルマンフォード(同レベル既出)のO(VE)より速い。「グラフの形の制約がアルゴリズムの選択肢を広げる」代表例。', ins: ['3 3\n1 2 5\n2 3 -2\n1 3 4\n', '2 1\n1 2 -7\n', '4 4\n1 2 1\n1 3 4\n2 4 2\n3 4 -5\n', '3 2\n1 2 2\n2 3 2\n', '4 5\n1 2 3\n2 3 -1\n1 3 5\n3 4 2\n2 4 10\n', '2 2\n1 2 5\n1 2 3\n'] })

t({ lv: 349, concept: 'グラフ: 全頂点対の最短距離の合計', title: '全員どうしの距離を足すと', tags: ['グラフ', 'BFS'], io: '1行目に頂点数 n と辺数 m、続く m 行に無向辺 u v が与えられます(連結)。', ask: '全ての頂点対 (u<v) の最短距離の合計を出力してください。', h1: '各頂点からBFSして距離を足す。', h2: '全対を足すと各対が2回ずつ数えられるので2で割る。', ref: 'from collections import deque\nn,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\ntotal=0\nfor s in range(1,n+1):\n    dist=[-1]*(n+1)\n    dist[s]=0\n    q=deque([s])\n    while q:\n        x=q.popleft()\n        for y in g[x]:\n            if dist[y]<0:\n                dist[y]=dist[x]+1\n                q.append(y)\n    total+=sum(dist[1:n+1])\nprint(total//2)', tip: 'ネットワークの「平均距離」の分子で、スモールワールド性の測定に使う量。木なら辺ごとの寄与(両側の頂点数の積)でO(n)にできる、と高速化の道も既出の部品で見えている。', ins: ['3 2\n1 2\n2 3\n', '2 1\n1 2\n', '3 3\n1 2\n2 3\n1 3\n', '4 3\n1 2\n2 3\n3 4\n', '4 4\n1 2\n2 3\n3 4\n4 1\n', '1 0\n'] })

t({ lv: 350, concept: 'グラフ: 次数が偶数の頂点の数', title: '偶数本の腕を持つ頂点', tags: ['グラフ'], io: '1行目に頂点数 n と辺数 m、続く m 行に無向辺 u v が与えられます。', ask: '次数が偶数(0を含む)の頂点の個数を出力してください。', h1: '次数配列を作って偶奇を見る。', h2: '孤立点の次数0も偶数。', ref: 'n,m=map(int,input().split())\ndeg=[0]*(n+1)\nfor _ in range(m):\n    u,v=map(int,input().split())\n    deg[u]+=1\n    deg[v]+=1\nprint(sum(1 for v in range(1,n+1) if deg[v]%2==0))', tip: '握手補題より奇数次数の頂点は必ず偶数個、なので答えは n−(偶数個) 。全頂点が偶数次数かつ連結ならオイラー閉路が引ける、と一筆書き判定(既出)の条件の半分がこの集計。', ins: ['3 3\n1 2\n2 3\n3 1\n', '2 1\n1 2\n', '4 2\n1 2\n1 3\n', '1 0\n', '5 4\n1 2\n1 3\n1 4\n1 5\n', '3 2\n1 2\n2 3\n'] })

t({ lv: 351, concept: '数え上げ: 偶奇が交互の区間の数', title: '交互のリズムを刻む区間', tags: ['数え上げ'], io: '整数列が1行で空白区切りで与えられます。', ask: '隣り合う要素の偶奇が必ず入れ替わっている連続部分配列(長さ1以上)の個数を出力してください。', h1: '最長(同レベル既出)と同じ走査で数えられる。', h2: '各位置で終わる交互区間の数は、交互が続いていれば前の値+1。', ref: 'a=list(map(int,input().split()))\nrun=1\ntotal=1\nfor i in range(1,len(a)):\n    if a[i]%2!=a[i-1]%2:\n        run+=1\n    else:\n        run=1\n    total+=run\nprint(total)', tip: '「各位置で終わる有効な区間の数を足す」数え上げの定型が、交互条件でもそのまま通用する。runのリセットが1(自分だけ)なのは長さ1が常に有効だから。', ins: ['1 2 3\n', '2 4\n', '1\n', '1 2 4 5\n', '2 1 2 1\n', '3 3 3\n'] })

t({ lv: 352, concept: 'スタック: 向きの反転で正しくする最小回数', title: '括弧をひっくり返して直す', tags: ['スタック'], io: '長さが偶数の括弧列(正しいとは限らない)が1行で与えられます。', ask: '括弧の向きを反転する操作の最小回数で正しい括弧列にできる回数を出力してください。', h1: '対応が取れるペアを先に消す。', h2: '残るのは ))…(( の形。閉じ残りc、開き残りoに対して ceil(c/2)+ceil(o/2)。', ref: 's=input()\no=0\nc=0\nfor ch in s:\n    if ch=="(":\n        o+=1\n    else:\n        if o>0:\n            o-=1\n        else:\n            c+=1\nprint((c+1)//2+(o+1)//2)', tip: '相殺後に残る形が ))(( に限られる、という正規化が肝。)) は1回の反転で ()に、)( は2回必要、と残りの偶奇まで含めて切り上げ2つの式に畳まれる。', ins: ['))((\n', '()\n', ')(\n', '(())\n', '()))\n', '((((\n'] })

t({ lv: 353, concept: '文字列: 全ての文字が2回以上現れるか', title: 'ひとりぼっちの文字はいないか', tags: ['文字列', 'ハッシュ'], io: '英小文字の文字列が1行で与えられます。', ask: '現れる全ての文字が2回以上現れているなら yes、1回しか現れない文字があれば no を出力してください。', h1: 'Counterの値を全部確かめる。', h2: 'min(回数)が2以上か。', ref: 'from collections import Counter\nc=Counter(input())\nprint("yes" if min(c.values())>=2 else "no")', tip: '1度だけ現れる最初の文字(同レベル既出)が「見つける」問題なら、こちらは「存在しないことの確認」。all()やminによる全称条件の書き方は集計検証の基本形。', ins: ['aabb\n', 'aab\n', 'abab\n', 'x\n', 'aaa\n', 'aabbc\n'] })

t({ lv: 354, concept: 'グリッド: 両方から行けるマスの数', title: '二人とも辿り着ける場所', tags: ['グリッド', 'BFS'], io: '1行目に H W、続く H 行に盤面(A と B が始点、. が空き、# が壁)が与えられます。移動は上下左右です。', ask: 'A からも B からも到達できるマスの個数(A・B のマス自身も含む)を出力してください。', h1: '2回のBFS(またはDFS)で到達集合を作る。', h2: '両方の集合に入るマスを数える。', ref: 'from collections import deque\nh,w=map(int,input().split())\ng=[input() for _ in range(h)]\ndef reach(mark):\n    seen=[[False]*w for _ in range(h)]\n    q=deque()\n    for i in range(h):\n        for j in range(w):\n            if g[i][j]==mark:\n                seen[i][j]=True\n                q.append((i,j))\n    while q:\n        i,j=q.popleft()\n        for di,dj in ((1,0),(-1,0),(0,1),(0,-1)):\n            ni,nj=i+di,j+dj\n            if 0<=ni<h and 0<=nj<w and g[ni][nj]!="#" and not seen[ni][nj]:\n                seen[ni][nj]=True\n                q.append((ni,nj))\n    return seen\nra=reach("A")\nrb=reach("B")\nprint(sum(1 for i in range(h) for j in range(w) if ra[i][j] and rb[i][j]))', tip: '到達集合の積は「待ち合わせ可能な場所」の集合。関数に切り出してマークだけ変えて2回呼ぶ構成は、同じ探索を再利用する設計の基本練習になる。', ins: ['1 3\nA.B\n', '3 3\nA#B\n.#.\n...\n', '1 3\nA#B\n', '2 2\nAB\n..\n', '1 5\nA.#.B\n', '2 3\nA.B\n###\n'] })

t({ lv: 355, concept: '数論: gcdの総和(ピライ関数)', title: '相方を変えながらgcdを足す', tags: ['数論'], io: '正整数 N が1行で与えられます。', ask: 'gcd(1,N)+gcd(2,N)+…+gcd(N,N) を出力してください。', h1: 'ユークリッドの互除法をN回。', h2: 'math.gcdをループで足すだけ。', ref: 'from math import gcd\nn=int(input())\nprint(sum(gcd(k,n) for k in range(1,n+1)))', tip: 'ピライの算術関数と呼ばれ、Σ d·φ(N/d) という約数とオイラー関数の畳み込みに等しい。約数の個数・和の総和(同レベル既出)と同じ「数論関数の集計」ファミリーの一員。', ins: ['6\n', '1\n', '4\n', '10\n', '5\n', '12\n'] })

t({ lv: 356, concept: '整数: 桁和を引き続けて1桁にする回数', title: '自分の桁和を引いていく', tags: ['整数', 'シミュレーション'], io: '正整数 n が1行で与えられます。', ask: '「n から n の各桁の和を引く」操作を n が10未満になるまで繰り返した回数を出力してください。', h1: '操作を素直に繰り返す。', h2: 'n−桁和は必ず9の倍数になる。', ref: 'n=int(input())\nc=0\nwhile n>=10:\n    n-=sum(int(d) for d in str(n))\n    c+=1\nprint(c)', tip: 'n−digitsum(n) が常に9の倍数なのは、10^k≡1 (mod 9) だから。1回目の操作以降は9の倍数だけを渡り歩く、という軌道の構造が観察できる。', ins: ['23\n', '9\n', '100\n', '10\n', '55\n', '77\n'] })

t({ lv: 357, concept: '数え上げ: XORがKになるペアの数', title: 'XORで結ばれた2人', tags: ['数え上げ', 'bit演算'], io: '1行目に K、2行目に整数列が与えられます。', ask: 'i<j で a[i] XOR a[j] が K になるペアの個数を出力してください。', h1: '和がKのペア(同レベル既出)と同じCounterの型。', h2: 'x の相方は x XOR K。K=0 のときは同値ペア C(c,2)。', ref: 'from collections import Counter\nk=int(input())\nc=Counter(map(int,input().split()))\nif k==0:\n    print(sum(v*(v-1)//2 for v in c.values()))\nelse:\n    print(sum(c[x]*c[x^k] for x in c if x<(x^k)))', tip: 'XORは自身が逆演算(x^K^K=x)なので「相方」が一意に定まり、和・積のペア数えと同じ骨格に乗る。K=0だけ相方が自分になる場合分けも和のときと同型。', ins: ['2\n1 3 5 7\n', '0\n4 4 4\n', '1\n2 3\n', '6\n1 7 2 4\n', '3\n1 1 2 2\n', '5\n1 2 3\n'] })

t({ lv: 358, concept: 'スタック: 必要なスタックの最大サイズ', title: '荷物置き場は何段必要か', tags: ['スタック'], io: '1, 2, …, n をこの順に押し込み、ポップで取り出して作った出力順(実現可能なもの)が1行で与えられます。', ask: 'この出力順を実現するときにスタックが最も高くなる瞬間の段数を出力してください。', h1: '作れる順か判定する問題(同レベル既出)のシミュレーションを流用。', h2: 'プッシュのたびに高さを記録して最大を取る。', ref: 'target=list(map(int,input().split()))\nn=len(target)\nst=[]\nbest=0\nnxt=1\nfor x in target:\n    while nxt<=x:\n        st.append(nxt)\n        nxt+=1\n        if len(st)>best:\n            best=len(st)\n    st.pop()\nprint(best)', tip: '判定問題と同じシミュレーションに「観測」を1つ足すだけで資源使用量の問題になる。必要スタック深さは、駅の引き込み線の長さや作業台の広さの見積もりそのもの。', ins: ['2 1 3\n', '1 2 3\n', '3 2 1\n', '2 3 1\n', '1 3 2\n', '4 3 2 1\n'] })

t({ lv: 359, concept: 'DAG: タスクの余裕時間の合計', title: 'プロジェクトの遊びを総計する', tags: ['グラフ', 'DP'], io: '1行目にタスク数 n と依存数 m、2行目に各タスクの所要時間、続く m 行に「u v」(uが終わってからvを開始)が与えられます(閉路なし)。', ask: '全体の最短完了時間を変えずに各タスクが持てる余裕(最も遅く始められる時刻−最も早く始められる時刻)の合計を出力してください。', h1: '最早開始と、そのタスクから後ろの最長所要を両方求める。', h2: 'タスクvを通る最長経路長は 最早開始+後ろの最長。全体Tとの差が余裕。', ref: 'import sys\nsys.setrecursionlimit(100000)\nn,m=map(int,input().split())\ndur=list(map(int,input().split()))\npre=[[] for _ in range(n+1)]\nsuc=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    pre[v].append(u)\n    suc[u].append(v)\nes={}\ndef E(v):\n    if v in es:\n        return es[v]\n    r=0\n    for u in pre[v]:\n        c=E(u)+dur[u-1]\n        if c>r:\n            r=c\n    es[v]=r\n    return r\ntl={}\ndef Tl(v):\n    if v in tl:\n        return tl[v]\n    r=dur[v-1]\n    for w in suc[v]:\n        c=dur[v-1]+Tl(w)\n        if c>r:\n            r=c\n    tl[v]=r\n    return r\nT=max(E(v)+dur[v-1] for v in range(1,n+1))\nprint(sum(T-E(v)-Tl(v) for v in range(1,n+1)))', tip: 'クリティカルパス法(CPM)のスラック計算そのもの。余裕合計が大きい工程表は組み替えの自由度が高い、というプロジェクト管理の実務量になっている。', ins: ['3 2\n5 3 2\n1 2\n1 3\n', '2 1\n4 4\n1 2\n', '3 0\n2 5 1\n', '4 3\n1 1 1 1\n1 2\n2 3\n3 4\n', '4 2\n3 1 1 5\n1 4\n2 3\n', '2 0\n7 7\n'] })

t({ lv: 360, concept: '文字列: 最も重なるずらし幅', title: '重ねて一番一致する位置', tags: ['文字列'], io: '1行目に文字列 s、2行目に文字列 t (tはsより長くない) が与えられます。', ask: 't を s の上に(はみ出さないように)重ねるとき、同じ位置の文字の一致数が最大になる開始位置(1始まり、同数なら最小)を出力してください。', h1: '全ての開始位置を試す。', h2: 'zipで重なり部分を比較して数える。', ref: 's=input()\nt=input()\nbest=-1\nans=0\nfor off in range(len(s)-len(t)+1):\n    c=sum(1 for a,b in zip(s[off:],t) if a==b)\n    if c>best:\n        best=c\n        ans=off\nprint(ans+1)', tip: '編集距離が挿入や削除で伸縮を許すのに対し、こちらは「ずらすだけ」の剛体的な整列。信号処理の相互相関の文字列版で、DNA断片の粗いアラインメントもこの発想から始まる。', ins: ['ababab\nba\n', 'aaaa\naa\n', 'abcde\ncd\n', 'xyz\nq\n', 'hello\nll\n', 'abab\nab\n'] })

t({ lv: 361, concept: 'DP: 最長減少部分列の長さ', title: '下りだけの最長の飛び石', tags: ['DP'], io: '整数列が1行で空白区切りで与えられます。', ask: '厳密に減少する部分列(連続でなくてよい)の最長の長さを出力してください。', h1: 'LIS(同レベル既出)の不等号反転。', h2: '列を反転してLISを呼んでもよい。', ref: 'a=list(map(int,input().split()))\nn=len(a)\ndp=[1]*n\nfor i in range(n):\n    for j in range(i):\n        if a[j]>a[i] and dp[j]+1>dp[i]:\n            dp[i]=dp[j]+1\nprint(max(dp))', tip: 'LDSはLISの鏡像だが、ディルワースの定理を通すと「増加列で列全体を覆う最小本数=LDS」という深い対応が現れる。同レベルの分割問題と実は同じ数を数えている。', ins: ['5 2 8 6 3 6 9 5\n', '1 2 3\n', '9 7 4 2\n', '3\n', '2 2 1\n', '6 1 5 2 4 3\n'] })

t({ lv: 362, concept: 'ソート: 偶数の要素だけ並べ替える', title: '偶数だけ席替えする', tags: ['ソート', 'リスト'], io: '整数列が1行で空白区切りで与えられます。', ask: '奇数の要素は位置を固定したまま、偶数の要素だけをそれらの位置の中で昇順に並べ替えた列を空白区切りで出力してください。', h1: '偶数を抜き出してソートし、元の偶数の位置へ戻す。', h2: 'イテレータやインデックスのリストで書ける。', ref: 'a=list(map(int,input().split()))\nev=sorted(x for x in a if x%2==0)\nk=0\nfor i in range(len(a)):\n    if a[i]%2==0:\n        a[i]=ev[k]\n        k+=1\nprint(" ".join(map(str,a)))', tip: '「一部だけソート」は抜き出し→整列→書き戻しの3段が定石。条件をインデックスの偶奇や範囲に替えても同じ骨格で書ける、部分ソートの汎用パターン。', ins: ['5 4 3 2 1\n', '2 4 6\n', '6 4 2\n', '1 3 5\n', '8 1 6 3 4\n', '7 2\n'] })

t({ lv: 363, concept: 'DP: 隣り合わずにちょうどk個選ぶ最大和', title: '間隔を空けてぴったりk個', tags: ['DP'], io: '1行目に k、2行目に整数列が与えられます(隣り合わずにk個選ぶことは可能)。', ask: '隣り合う2要素を同時に選ばずにちょうど k 個選ぶときの、選んだ値の合計の最大を出力してください。', h1: '隣り合わず選ぶ最大和(既出)に「個数」の次元を足す。', h2: 'dp[i][j] = 先頭i個からj個選ぶ最大。選ぶなら i−2 から、選ばないなら i−1 から。', ref: 'k=int(input())\na=list(map(int,input().split()))\nn=len(a)\nNEG=-(10**9)\ndp=[[NEG]*(k+1) for _ in range(n+1)]\nfor i in range(n+1):\n    dp[i][0]=0\nfor i in range(1,n+1):\n    for j in range(1,k+1):\n        dp[i][j]=dp[i-1][j]\n        base=dp[i-2][j-1] if i>=2 else (0 if j==1 else NEG)\n        if base>NEG and base+a[i-1]>dp[i][j]:\n            dp[i][j]=base+a[i-1]\nprint(dp[n][k])', tip: '制約(隣接禁止)と割当量(ちょうどk個)の2軸を持つDPは、次元を1つ増やすだけで書ける。負の値があっても「ちょうどk個」の強制で選ばざるを得ない、が番兵で自然に処理される。', ins: ['2\n5 1 4 2\n', '1\n3 7\n', '2\n1 2 3\n', '3\n5 1 5 1 5\n', '2\n-1 -2 -3\n', '1\n4\n'] })

t({ lv: 364, concept: 'ハッシュ: 連結して回文になる順序対の数', title: 'つなげると回文になる2語', tags: ['ハッシュ', '文字列'], io: '単語が空白区切りで1行に与えられます。', ask: '順序対 (i, j) (i≠j) で、i番目の単語のあとに j 番目の単語をつなげた文字列が回文になるものの個数を出力してください。', h1: '全ての順序対を試す。', h2: '(w1+w2) == 反転 で判定。', ref: 'ws=input().split()\nn=len(ws)\ncnt=0\nfor i in range(n):\n    for j in range(n):\n        if i!=j:\n            u=ws[i]+ws[j]\n            if u==u[::-1]:\n                cnt+=1\nprint(cnt)', tip: '有名な「回文ペア」問題の総当たり基準解。高速版は各単語の接頭辞・接尾辞の回文性と反転辞書を組み合わせるが、まず正しい素朴版を持つことがその検証台になる。', ins: ['ab ba\n', 'a b\n', 'a aa\n', 'ab b\n', 'x y x\n', 'abc cba a\n'] })

t({ lv: 365, concept: '整数: 桁が厳密増加の数の個数', title: '右肩上がりの数を数える', tags: ['整数'], io: '正整数 N が1行で与えられます。', ask: '1 以上 N 以下で、十進の桁が左から右へ厳密に増加している数(1桁の数を含む)の個数を出力してください。', h1: '判定(既出)を範囲に適用。', h2: '文字列比較 all(s[i]<s[i+1])。', ref: 'n=int(input())\ncnt=0\nfor x in range(1,n+1):\n    s=str(x)\n    if all(s[i]<s[i+1] for i in range(len(s)-1)):\n        cnt+=1\nprint(cnt)', tip: '厳密増加の数は桁の部分集合と1対1なので、総数は高々2^9−1=511個。Nが巨大でも組合せC(9,桁数)の和で数えられる、と総当たりの先に閉じた式が見えている。', ins: ['20\n', '9\n', '100\n', '12\n', '1\n', '50\n'] })

t({ lv: 366, concept: 'bitDP: 割当問題の最大利益', title: '適材適所で稼ぎを最大に', tags: ['bitDP'], io: '1行目に n、続く n 行に n×n の利益表(i行j列は人iが仕事jをしたときの利益)が与えられます。', ask: '各人にちょうど1つずつ仕事を割り当てるときの利益の合計の最大を出力してください。', h1: '最小コスト(同レベル既出)のmax版。', h2: '順列全探索かbitDPで。', ref: 'from itertools import permutations\nn=int(input())\nP=[list(map(int,input().split())) for _ in range(n)]\nprint(max(sum(P[i][p[i]] for i in range(n)) for p in permutations(range(n))))', tip: '最小化はコストを負にすれば最大化に帰着する、という双対の関係。n!の全探索が基準解で、bitDPのO(n·2^n)、ハンガリアン法のO(n³)へと同じ答えのまま高速化が積み上がる。', ins: ['2\n1 2\n3 4\n', '2\n5 1\n1 5\n', '1\n7\n', '3\n1 2 3\n3 1 2\n2 3 1\n', '3\n9 0 0\n0 9 0\n0 0 9\n', '2\n0 0\n0 0\n'] })

t({ lv: 367, concept: 'bitDP: ペア分けの相性の最大', title: '最高のバディ編成', tags: ['bitDP'], io: '1行目に偶数 n、続く n 行に n×n の相性表(対称、対角は0)が与えられます。', ask: 'n 人を2人組 n/2 組に分けるとき、各組の相性の合計の最大を出力してください。', h1: '番号最小の未処理の人の相手を順に試す。', h2: '再帰+メモ(ビットマスク)で状態は「誰が残っているか」。', ref: 'import sys\nsys.setrecursionlimit(100000)\nn=int(input())\nC=[list(map(int,input().split())) for _ in range(n)]\nmemo={}\ndef f(mask):\n    if mask==(1<<n)-1:\n        return 0\n    if mask in memo:\n        return memo[mask]\n    i=0\n    while mask>>i&1:\n        i+=1\n    best=0\n    for j in range(i+1,n):\n        if not mask>>j&1:\n            v=C[i][j]+f(mask|1<<i|1<<j)\n            if v>best:\n                best=v\n    memo[mask]=best\n    return best\nprint(f(0))', tip: '「最小の未処理者に必ず相手を付ける」枝刈りで、探索は(n−1)!!通りに収まる。ダブルス編成やルームメイト割りなど完全マッチングの重み最大化はこの型が原型。', ins: ['2\n0 5\n5 0\n', '4\n0 9 1 1\n9 0 1 1\n1 1 0 9\n1 1 9 0\n', '2\n0 3\n3 0\n', '4\n0 2 8 1\n2 0 3 7\n8 3 0 2\n1 7 2 0\n', '4\n0 0 0 0\n0 0 0 0\n0 0 0 0\n0 0 0 0\n', '4\n0 1 1 9\n1 0 9 1\n1 9 0 1\n9 1 1 0\n'] })

t({ lv: 368, concept: '順列: サイクルの個数', title: '席替えの輪を数える', tags: ['順列'], io: '1〜n の並べ替え(i番目の値は「iの行き先」)が1行で空白区切りで与えられます。', ask: 'この置換をサイクル(巡回する輪)に分解したときのサイクルの個数を出力してください(固定点も長さ1のサイクル)。', h1: '未訪問の点から行き先を辿って輪を閉じる。', h2: '訪問済み配列で二重カウントを防ぐ。', ref: 'p=list(map(int,input().split()))\nn=len(p)\nseen=[False]*(n+1)\ncnt=0\nfor s in range(1,n+1):\n    if not seen[s]:\n        cnt+=1\n        x=s\n        while not seen[x]:\n            seen[x]=True\n            x=p[x-1]\nprint(cnt)', tip: '偶置換か奇置換か(既出)も恒等に戻る回数(同レベル既出)も、実はこのサイクル分解が計算の心臓部。n−サイクル数が最小互換数、という基本等式も一緒に覚えたい。', ins: ['2 1 4 3\n', '1 2 3\n', '2 3 1\n', '1\n', '3 1 2 5 4\n', '5 4 3 2 1\n'] })

t({ lv: 369, concept: '数論: 一次不定方程式の最小の非負解', title: '両替の一番節約な内訳', tags: ['数論'], io: 'a b c が空白区切りで1行で与えられます(ax+by=c に非負整数解が存在します)。', ask: 'ax+by=c を満たす非負整数解のうち x が最小のものを「x y」の形で出力してください。', h1: '解の存在判定(同レベル既出)の構成版。', h2: 'x を 0 から増やし、(c−ax) が b で割り切れて非負になる最初を取る。', ref: 'a,b,c=map(int,input().split())\nx=0\nwhile (c-a*x)%b!=0:\n    x+=1\nprint(x,(c-a*x)//b)', tip: '一般解は x=x0+bt/g の等差なので、最小非負の x は高々 b/g−1 までに必ず現れる。全探索の上限に理論保証がある、安心して回せるループ。', ins: ['3 5 22\n', '2 3 7\n', '1 1 5\n', '5 7 35\n', '4 6 10\n', '3 4 12\n'] })

t({ lv: 370, concept: '数論: 拡張ユークリッドの標準解', title: '基準になるベズー係数', tags: ['数論'], io: 'a b が空白区切りで1行で与えられます (a, b ≥ 1)。', ask: 'g を gcd(a,b) とするとき、ax+by=g を満たす整数解のうち 0≤x<b/g となる唯一の x とそのときの y を「x y」の形で出力してください。', h1: '解は b/g 間隔で並ぶので、その1周期に必ず1つある。', h2: 'x を 0 から b/g−1 まで試して (g−ax) が b で割り切れるものを探す。', ref: 'a,b=map(int,input().split())\nx,y=a,b\nwhile y:\n    x,y=y,x%y\ng=x\nfor x in range(b//g):\n    if (g-a*x)%b==0:\n        print(x,(g-a*x)//b)\n        break', tip: 'ベズーの等式の解は無数にあるが、xを剰余系で正規化すると一意に定まる。モジュラ逆元(既出)は b が法のときの x そのもので、この標準化の特別な場合にあたる。', ins: ['3 5\n', '4 6\n', '5 3\n', '1 1\n', '6 4\n', '7 10\n'] })

t({ lv: 371, concept: '木: 帰りがけ順の出力', title: '子を見届けてから自分', tags: ['木'], io: '1行目に頂点数 n (n≥2)、2行目に頂点2〜nの親が与えられます(根は頂点1、子は番号の小さい順に辿ります)。', ask: '帰りがけ順(postorder: 子を全て訪ねてから自分)で頂点番号を空白区切りで出力してください。', h1: '行きがけ順(同レベル既出)と再帰の出力位置が違うだけ。', h2: '再帰呼び出しの後に自分を追加する。', ref: 'import sys\nsys.setrecursionlimit(100000)\nn=int(input())\npar=list(map(int,input().split()))\nch=[[] for _ in range(n+1)]\nfor i in range(2,n+1):\n    ch[par[i-2]].append(i)\nout=[]\ndef dfs(v):\n    for c in ch[v]:\n        dfs(c)\n    out.append(v)\ndfs(1)\nprint(" ".join(map(str,out)))', tip: '式木の帰りがけ順は逆ポーランド記法、ディレクトリの容量集計も「子を全部足してから自分」。行きがけとの違いはappendの1行の位置だけ、というのが再帰の教育的な瞬間。', ins: ['5\n1 1 2 2\n', '3\n1 2\n', '2\n1\n', '4\n1 1 1\n', '6\n1 2 3 1 5\n', '7\n1 1 2 2 3 3\n'] })

t({ lv: 372, concept: '木DP: 独立集合の総数', title: '隣り合わない選び方は何通り', tags: ['木DP'], io: '1行目に頂点数 n (n≥2)、2行目に頂点2〜nの親が与えられます(根は頂点1)。', ask: '辺で隣り合う2頂点を同時に含まない頂点部分集合(空集合も含む)の総数を出力してください。', h1: '最大独立集合(同レベル既出)の数え上げ版。', h2: '各頂点で「選ぶ場合」「選ばない場合」の2つの数を子から掛け上げる。', ref: 'n=int(input())\npar=list(map(int,input().split()))\na=[1]*(n+1)\nb=[1]*(n+1)\nfor v in range(n,1,-1):\n    p=par[v-2]\n    a[p]*=a[v]+b[v]\n    b[p]*=a[v]\nprint(a[1]+b[1])', tip: '親リスト形式は「番号の大きい順に処理すれば子が先に確定」なので、再帰なしのループで木DPが書ける。max(最適化)を掛け算と足し算(数え上げ)に替える対応も一目瞭然。', ins: ['2\n1\n', '3\n1 1\n', '3\n1 2\n', '4\n1 2 3\n', '5\n1 1 1 1\n', '7\n1 1 2 2 3 3\n'] })

t({ lv: 373, concept: '文字列: 回文である最長の接尾辞', title: '末尾に隠れた回文', tags: ['文字列'], io: '文字列が1行で与えられます。', ask: '回文になっている最長の接尾辞(末尾からの連続部分)の長さを出力してください。', h1: '回文の最長接頭辞(同レベル既出)の鏡像。', h2: '長い接尾辞から順に判定して最初に見つかったもの。', ref: 's=input()\nn=len(s)\nfor i in range(n):\n    t=s[i:]\n    if t==t[::-1]:\n        print(n-i)\n        break', tip: '末尾に文字を足して全体を回文にする最小追加数は「n−この長さ」…ではなく先頭側の回文接頭辞を使う、と鏡像どうしの役割分担がある。KMPで線形にする有名な変換の部品。', ins: ['abac\n', 'abacaba\n', 'abcbc\n', 'xyz\n', 'aa\n', 'abcba\n'] })

t({ lv: 374, concept: 'クエリ: 区間の相異なる値の数', title: '区間の顔ぶれの豊かさ', tags: ['クエリ'], io: '1行目に n q、2行目に長さ n の列、続く q 行に区間 l r が与えられます。', ask: '各区間に含まれる相異なる値の個数を1行ずつ出力してください。', h1: '切り出してsetに入れるのが基準解。', h2: 'len(set(a[l−1:r]))。', ref: 'n,q=map(int,input().split())\na=list(map(int,input().split()))\nfor _ in range(q):\n    l,r=map(int,input().split())\n    print(len(set(a[l-1:r])))', tip: '区間distinctはセグメント木で素直に解けない代表格で、オフラインならクエリを右端順に並べたBIT解法(有名)がある。素朴解を持つことがその検証の出発点。', ins: ['5 2\n1 2 1 3 2\n1 3\n2 5\n', '3 1\n7 7 7\n1 3\n', '4 2\n1 2 3 4\n2 3\n1 4\n', '2 1\n5 6\n1 1\n', '6 2\n1 1 2 2 3 3\n2 5\n1 6\n', '5 1\n4 4 2 4 4\n1 5\n'] })

t({ lv: 375, concept: '貪欲: 期限内に全部消費できるか', title: '賞味期限との競走', tags: ['貪欲', 'ソート'], io: '1行目に個数 n、2行目に各品物の期限(日目)が与えられます。1日に1個だけ消費でき、1日目から始めます。', ask: '全ての品物をそれぞれの期限の日までに消費できるなら yes、できなければ no を出力してください。', h1: '期限が近いものから食べるのが最善。', h2: 'ソートして i 番目(1始まり)の期限が i 以上か。', ref: 'n=int(input())\nd=sorted(map(int,input().split()))\nprint("yes" if all(d[i]>=i+1 for i in range(n)) else "no")', tip: 'EDF(締切最早優先)スケジューリングの実行可能性判定で、リアルタイムOSの理論の入り口。「ソートして i 番目と i を比べる」形はホールの条件の1次元版でもある。', ins: ['3\n2 1 3\n', '2\n1 1\n', '3\n5 5 5\n', '4\n1 2 2 4\n', '1\n1\n', '3\n3 3 1\n'] })

t({ lv: 376, concept: 'ダイクストラ: 頂点に料金がある最短', title: '通行料は交差点で払う', tags: ['ダイクストラ', 'グラフ'], io: '1行目に頂点数 n と辺数 m、2行目に各頂点の通行料、続く m 行に無向辺 u v が与えられます(連結)。', ask: '頂点1から頂点nへ移動するとき、通った頂点(両端を含む)の料金の合計の最小を出力してください。', h1: '辺ではなく頂点にコストがある。', h2: '移動先の頂点の料金を辺コストとみなし、始点の料金を初期値にする。', ref: 'import heapq\nn,m=map(int,input().split())\ncost=list(map(int,input().split()))\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\nINF=float("inf")\ndist=[INF]*(n+1)\ndist[1]=cost[0]\npq=[(cost[0],1)]\nwhile pq:\n    d,v=heapq.heappop(pq)\n    if d>dist[v]:\n        continue\n    for to in g[v]:\n        nd=d+cost[to-1]\n        if nd<dist[to]:\n            dist[to]=nd\n            heapq.heappush(pq,(nd,to))\nprint(dist[n])', tip: '頂点コストは「入ってくる辺すべてにそのコストを乗せる」変換で辺コストに帰着できる。グラフ問題の多くはこうした equivalent な作り替えで既存アルゴリズムに載せる。', ins: ['3 2\n1 5 1\n1 2\n2 3\n', '3 3\n1 9 1\n1 2\n2 3\n1 3\n', '2 1\n3 4\n1 2\n', '4 4\n1 1 100 1\n1 2\n2 4\n1 3\n3 4\n', '1 0\n5\n', '4 3\n2 3 4 5\n1 2\n2 3\n3 4\n'] })

t({ lv: 377, concept: 'DP: 立方数の和で表す最小の項数', title: '立方体のブロックで組み上げる', tags: ['DP', '数論'], io: '正整数 n が1行で与えられます。', ask: 'n を正の立方数(1, 8, 27, …)の和で表すときの最小の項数を出力してください。', h1: '平方数の和の最小項数(同レベル既出)の立方版。', h2: 'dp[x]=min(dp[x−k³])+1。', ref: 'n=int(input())\nINF=10**9\ndp=[0]+[INF]*n\nfor x in range(1,n+1):\n    k=1\n    while k*k*k<=x:\n        if dp[x-k*k*k]+1<dp[x]:\n            dp[x]=dp[x-k*k*k]+1\n        k+=1\nprint(dp[n])', tip: '平方数なら4個で必ず足りる(ラグランジュ)が、立方数は9個必要な数(23と239だけ)がある、というウェアリングの問題の入り口。DPの形は全く同じで数論の答えだけ変わる。', ins: ['9\n', '8\n', '23\n', '1\n', '27\n', '17\n'] })

export const CATALOG = TASKS
