// 生成タスク 第29波：lv271〜300。
// 前提分解の踏み段。数論(約数和/桁和/ピタゴラス/階乗mod/二項係数mod素数)・
// DP変種(階段コスト/ジグザグ/等差/塗り分け/個数制限/回文カット/区間ゲーム/LCIS)・
// 文字列(連長圧縮/括弧/異なる部分文字列/最小回転)・グラフ(島数/有向閉路/オイラー/到達数/辞書順topo)。
// lv500未満なので再帰なし(反復)。重複なし・決定的・採点一意。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 271, concept: '数論: 約数の総和', title: '約数の総和', tags: ['数論'], io: '整数 n (>=1) が1行で与えられます。', ask: 'n のすべての正の約数の総和を出力してください。', h1: 'd*d<=n まで調べる。', h2: 'd が約数なら n//d も約数 (重複に注意)。', ref: 'n=int(input())\ns=0\nd=1\nwhile d*d<=n:\n    if n%d==0:\n        s+=d\n        if d!=n//d:\n            s+=n//d\n    d+=1\nprint(s)', tip: '約数を平方根まで調べてペアで拾えば O(√n)。', ins: ['6\n', '1\n', '12\n', '28\n', '7\n', '100\n'] })

t({ lv: 272, concept: '数論: 1からNまでの桁和の合計', title: '1〜Nの各桁和の総和', tags: ['数論'], io: '整数 N (>=1) が1行で与えられます。', ask: '1 から N までの各整数について「各桁の和」を求め、その総和を出力してください。', h1: 'str(x) の各文字を int にして足す。', h2: '1..N で繰り返して合計。', ref: 'n=int(input())\ntotal=0\nfor x in range(1,n+1):\n    total+=sum(int(c) for c in str(x))\nprint(total)', tip: '桁を文字として扱うと割り算ループより読みやすい。', ins: ['10\n', '1\n', '20\n', '100\n', '5\n', '99\n'] })

t({ lv: 273, concept: '数論: ピタゴラス数の組数', title: 'N以下のピタゴラス数の組数', tags: ['数論'], io: '整数 N (>=1) が1行で与えられます。', ask: 'a<=b<=c<=N かつ a²+b²=c² を満たす整数の組 (a,b,c) の個数を出力してください。', h1: 'a,b を全探索し c を平方根から求める。', h2: 'math.isqrt で平方判定すると誤差が出ない。', ref: 'import math\nn=int(input())\ncnt=0\nfor a in range(1,n+1):\n    for b in range(a,n+1):\n        c2=a*a+b*b\n        c=math.isqrt(c2)\n        if c*c==c2 and c<=n:\n            cnt+=1\nprint(cnt)', tip: 'isqrt は整数の平方根を誤差なく返す (float の sqrt より安全)。', ins: ['5\n', '10\n', '20\n', '1\n', '13\n', '4\n'] })

t({ lv: 274, concept: '数論: 階乗 mod', title: '階乗を法で割った余り', tags: ['数論'], io: 'n m が空白区切りで与えられます。', ask: 'n! を m で割った余りを出力してください。', h1: '1から n まで掛けながら毎回 m で割る。', h2: '途中で mod を取れば桁あふれしない。', ref: 'n,m=map(int,input().split())\nr=1%m\nfor i in range(2,n+1):\n    r=r*i%m\nprint(r)', tip: '掛けるたびに mod を取るのが大きな階乗を扱う基本。', ins: ['5 1000\n', '0 7\n', '10 1000000007\n', '20 100\n', '3 5\n', '1 9\n'] })

t({ lv: 275, concept: '数論: 二項係数 mod 素数', title: '組合せ C(n,k) を素数で割った余り', tags: ['数論'], io: 'n k p が空白区切りで与えられます (p は素数)。', ask: 'C(n,k) を p で割った余りを出力してください (k<0 または k>n のときは0)。', h1: '分子・分母をそれぞれ mod p で積。', h2: '分母の逆元はフェルマーの小定理 (p-2 乗) で。', ref: 'n,k,p=map(int,input().split())\nif k<0 or k>n:\n    print(0)\nelse:\n    num=1\n    for i in range(n-k+1,n+1):\n        num=num*i%p\n    den=1\n    for i in range(1,k+1):\n        den=den*i%p\n    e=p-2\n    inv=1\n    base=den%p\n    while e>0:\n        if e%2==1:\n            inv=inv*base%p\n        base=base*base%p\n        e//=2\n    print(num*inv%p)', tip: '素数を法にすれば割り算は「逆元の掛け算」に変換できる。', ins: ['5 2 1000000007\n', '10 3 13\n', '100 50 1000000007\n', '6 0 7\n', '4 4 5\n', '7 3 11\n'] })

t({ lv: 276, concept: 'ソート: 最も近い2数の差', title: '最も近い2数の差', tags: ['ソート'], io: '整数列 (2個以上) が1行で与えられます。', ask: '2つの要素の差の絶対値の最小値を出力してください。', h1: 'まず昇順にソート。', h2: '隣り合う差の最小が答え。', ref: 'a=sorted(map(int,input().split()))\nbest=min(a[i+1]-a[i] for i in range(len(a)-1))\nprint(best)', tip: 'ソートすると最も近いペアは必ず隣り合う。', ins: ['3 8 1 5\n', '1 2\n', '10 1 100\n', '5 5\n', '1 100 2 99 50\n', '7 3\n'] })

t({ lv: 277, concept: '二点法: 2列マージの下中央値', title: '2つの昇順列をマージした下中央値', tags: ['二点法'], io: '1行目に n m、2行目に昇順の n 個、3行目に昇順の m 個が与えられます。', ask: '2列をマージした昇順列の下側中央値 (0始まりで位置 (n+m-1)//2 の要素) を出力してください。', h1: '2列を先頭から比べて小さい方を取る。', h2: 'マージ後の指定位置を返す。', ref: 'n,m=map(int,input().split())\na=list(map(int,input().split()))\nb=list(map(int,input().split()))\ni=0\nj=0\nmerged=[]\nwhile i<n and j<m:\n    if a[i]<=b[j]:\n        merged.append(a[i])\n        i+=1\n    else:\n        merged.append(b[j])\n        j+=1\nwhile i<n:\n    merged.append(a[i])\n    i+=1\nwhile j<m:\n    merged.append(b[j])\n    j+=1\nprint(merged[(n+m-1)//2])', tip: '2つのソート済み列のマージは O(n+m) の基本操作。', ins: ['3 2\n1 3 5\n2 4\n', '2 2\n1 2\n3 4\n', '1 1\n5\n10\n', '3 3\n1 2 3\n4 5 6\n', '1 4\n10\n1 2 3 4\n', '2 3\n5 8\n1 2 9\n'] })

t({ lv: 278, concept: 'ハッシュ: 異なる値がK種の部分配列数', title: 'ちょうどK種類の値を含む部分配列の数', tags: ['スライディングウィンドウ', 'ハッシュ'], io: '1行目に n k、2行目に n 個の整数が与えられます。', ask: '異なる値をちょうど k 種類含む連続部分配列の個数を出力してください。', h1: '「高々k種」の数 − 「高々k-1種」の数。', h2: '高々K種は尺取りで O(n)。', ref: 'from collections import defaultdict\nn,k=map(int,input().split())\na=list(map(int,input().split()))\ndef at_most(K):\n    if K<0:\n        return 0\n    cnt=defaultdict(int)\n    l=0\n    res=0\n    distinct=0\n    for r in range(n):\n        if cnt[a[r]]==0:\n            distinct+=1\n        cnt[a[r]]+=1\n        while distinct>K:\n            cnt[a[l]]-=1\n            if cnt[a[l]]==0:\n                distinct-=1\n            l+=1\n        res+=r-l+1\n    return res\nprint(at_most(k)-at_most(k-1))', tip: '「ちょうどK」は「高々K」の差分で求めるのが定石。', ins: ['4 2\n1 2 1 3\n', '3 1\n1 1 1\n', '5 2\n1 2 1 2 3\n', '1 1\n5\n', '4 3\n1 2 3 4\n', '5 1\n1 2 3 4 5\n'] })

t({ lv: 279, concept: 'ビット全探索: 最大XOR部分集合', title: '部分集合のXORの最大値', tags: ['bit全探索'], io: '整数列 (要素数は16以下) が1行で与えられます。', ask: '要素の部分集合 (空集合を含む) を選んだとき、その排他的論理和 (XOR) の最大値を出力してください。', h1: '2^n 通りの選び方をビットで全探索。', h2: '選んだ要素を XOR していく。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nbest=0\nfor mask in range(1<<n):\n    x=0\n    for i in range(n):\n        if (mask>>i)&1:\n            x^=a[i]\n    if x>best:\n        best=x\nprint(best)', tip: 'mask の各ビットが「i番目を選ぶか」を表す全探索の常套句。', ins: ['1 2 3\n', '8 4 2\n', '5\n', '0 0\n', '1 2 4 8\n', '7 3 5\n'] })

t({ lv: 280, concept: '文字列: 連長圧縮の出力', title: 'ランレングス圧縮した文字列', tags: ['文字列'], io: '文字列 s が1行で与えられます。', ask: '同じ文字の連続を「文字＋個数」で表した圧縮文字列を出力してください (例: aaabb → a3b2)。', h1: '同じ文字が続く区間を見つける。', h2: '文字と長さを連結。', ref: 's=input()\nres=[]\ni=0\nwhile i<len(s):\n    j=i\n    while j<len(s) and s[j]==s[i]:\n        j+=1\n    res.append(s[i]+str(j-i))\n    i=j\nprint("".join(res))', tip: '連続区間の検出はランレングス系の問題すべての土台。', ins: ['aaabbc\n', 'abc\n', 'aaaa\n', 'x\n', 'aabbaa\n', 'wwwwwww\n'] })

t({ lv: 281, concept: '文字列: 括弧の最大深さ', title: '括弧のネストの最大の深さ', tags: ['文字列', 'スタック'], io: '括弧やその他の文字を含む文字列が1行で与えられます。', ask: '丸括弧 ( ) のネストの最大の深さを出力してください。', h1: '( で深さ+1、) で深さ-1。', h2: '途中の最大値が答え。', ref: 's=input()\ndepth=0\nbest=0\nfor ch in s:\n    if ch=="(":\n        depth+=1\n        if depth>best:\n            best=depth\n    elif ch==")":\n        depth-=1\nprint(best)', tip: '深さカウンタは括弧の対応・ネスト系の万能道具。', ins: ['((()))\n', '()()\n', '(()(()))\n', '\n', 'abc\n', '(a(b)c(d(e)))\n'] })

t({ lv: 282, concept: '文字列: 最長の正しい括弧列', title: '最長の正しく対応した括弧列', tags: ['文字列', 'スタック'], io: '( と ) のみからなる文字列が1行で与えられます。', ask: '正しく対応している連続部分文字列の最大の長さを出力してください。', h1: '位置をスタックに積む。基準位置を-1で初期化。', h2: ') で取り出した後、空なら基準を更新、そうでなければ長さを測る。', ref: 's=input()\nst=[-1]\nbest=0\nfor i in range(len(s)):\n    if s[i]=="(":\n        st.append(i)\n    else:\n        st.pop()\n        if not st:\n            st.append(i)\n        else:\n            if i-st[-1]>best:\n                best=i-st[-1]\nprint(best)', tip: '「最後に対応が崩れた位置」を基準にすると長さが一気に測れる。', ins: ['(()\n', ')()())\n', '\n', '()(()\n', '()()\n', '((()))\n'] })

t({ lv: 283, concept: '文字列: 最長の繰り返し部分文字列', title: '2回以上現れる最長部分文字列の長さ', tags: ['文字列'], io: '文字列 s が1行で与えられます。', ask: 's の中に (位置を変えて) 2回以上現れる連続部分文字列のうち、最長のものの長さを出力してください (無ければ0)。', h1: '長さごとに、出現済みの部分文字列を集合で管理。', h2: '同じものが2回現れた長さの最大が答え。', ref: 's=input()\nn=len(s)\nbest=0\nfor length in range(1,n):\n    seen=set()\n    found=False\n    for i in range(n-length+1):\n        sub=s[i:i+length]\n        if sub in seen:\n            found=True\n            break\n        seen.add(sub)\n    if found:\n        best=length\nprint(best)', tip: '繰り返し部分文字列は、高度には接尾辞配列＋LCPで高速に求まる。', ins: ['banana\n', 'abcd\n', 'aaaa\n', 'abab\n', 'a\n', 'abcabc\n'] })

t({ lv: 284, concept: '文字列: 最小の回転', title: '辞書順で最小になる回転', tags: ['文字列'], io: '文字列 s が1行で与えられます。', ask: 's を回転 (先頭の何文字かを末尾へ移す) して作れる文字列のうち、辞書順で最小のものを出力してください。', h1: '回転の仕方は |s| 通り。', h2: 'それぞれ作って最小を取る。', ref: 's=input()\nn=len(s)\nbest=s\nfor i in range(1,n):\n    rot=s[i:]+s[:i]\n    if rot<best:\n        best=rot\nprint(best)', tip: '最小回転は文字列を環として見る問題の基本形。', ins: ['bca\n', 'aaa\n', 'baca\n', 'z\n', 'cba\n', 'dcba\n'] })

t({ lv: 285, concept: 'DP: 階段の最小コスト', title: '階段を上り切る最小コスト', tags: ['dp'], io: '各段を踏むのにかかるコストの列が1行で与えられます。1段または2段ずつ上れ、段0か段1のどちらからでも開始できます。', ask: '最上段の1つ上 (ゴール) に到達する最小コストを出力してください。', h1: 'dp[i]=位置iに来る最小コスト。', h2: 'dp[i]=min(dp[i-1]+cost[i-1], dp[i-2]+cost[i-2])。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nprev2=0\nprev1=0\nfor i in range(2,n+1):\n    cur=min(prev1+a[i-1],prev2+a[i-2])\n    prev2=prev1\n    prev1=cur\nprint(prev1)', tip: '「ゴールはn段目」と置くと開始の自由度が自然に表せる。', ins: ['10 15 20\n', '1 100 1 1 1 100 1 1 100 1\n', '0 0\n', '5\n', '1 2\n', '10 10\n'] })

t({ lv: 286, concept: 'DP: ジグザグ部分列の最長', title: '増減を繰り返す最長部分列', tags: ['dp'], io: '整数列が1行で与えられます。', ask: '隣り合う差の符号が交互になる (増加→減少→増加…) 部分列の最大の長さを出力してください。', h1: '「直前が上がった」「下がった」の2状態を持つ。', h2: '増えたら up=down+1、減ったら down=up+1。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nup=1\ndown=1\nfor i in range(1,n):\n    if a[i]>a[i-1]:\n        up=down+1\n    elif a[i]<a[i-1]:\n        down=up+1\nprint(max(up,down))', tip: '2つの状態を交互に更新するだけで O(n)。', ins: ['1 7 4 9 2 5\n', '1 4 7 2 5\n', '1 2 3 4\n', '5\n', '3 3 3\n', '10 1 10 1 10\n'] })

t({ lv: 287, concept: 'DP: 等差部分列の最長', title: '最長の等差部分列', tags: ['dp', 'ハッシュ'], io: '整数列が1行で与えられます。', ask: '公差が一定である部分列 (連続でなくてよい) の最大の長さを出力してください。', h1: 'dp[i][公差]=a[i]で終わる長さ。', h2: '各 i,j で公差 d=a[i]-a[j] を辞書で持つ。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nif n<=1:\n    print(n)\nelse:\n    dp=[{} for _ in range(n)]\n    best=1\n    for i in range(n):\n        for j in range(i):\n            d=a[i]-a[j]\n            cur=dp[j].get(d,1)+1\n            if cur>dp[i].get(d,0):\n                dp[i][d]=cur\n            if dp[i][d]>best:\n                best=dp[i][d]\n    print(best)', tip: '公差をキーにした辞書DPで、無数の公差を効率よく扱える。', ins: ['3 6 9 12\n', '9 4 7 2 10\n', '1 2 3 4\n', '5\n', '1 5 2 6 3\n', '20 1 15 3 10 5 8\n'] })

t({ lv: 288, concept: 'DP: 家の塗り分け最小コスト', title: '隣を別色にする塗り分けの最小コスト', tags: ['dp'], io: '1行目に家の数 n、続く n 行に各家を色0/色1/色2 で塗るコストが3つずつ与えられます。', ask: '隣り合う家が同じ色にならないように全部塗るときの、合計コストの最小値を出力してください。', h1: '各家ごとに「その色で塗ったときの最小累計」を持つ。', h2: '今の色は直前の別の2色の小さい方に足す。', ref: 'n=int(input())\nprev=[0,0,0]\nfor _ in range(n):\n    c=list(map(int,input().split()))\n    cur=[0,0,0]\n    cur[0]=c[0]+min(prev[1],prev[2])\n    cur[1]=c[1]+min(prev[0],prev[2])\n    cur[2]=c[2]+min(prev[0],prev[1])\n    prev=cur\nprint(min(prev))', tip: '状態数が少ない列のDPは「直前の各状態の最小」だけ持てばよい。', ins: ['3\n17 2 17\n16 16 5\n14 3 19\n', '1\n5 8 2\n', '0\n', '2\n1 2 3\n3 2 1\n', '2\n5 5 5\n5 5 5\n', '3\n1 1 1\n1 1 1\n1 1 1\n'] })

t({ lv: 289, concept: 'DP: 個数制限ナップサック', title: '個数に上限があるナップサック', tags: ['dp'], io: '1行目に品物数 n と容量 W、続く n 行に重さ w・価値 v・使える個数 cnt が与えられます。', ask: '重さの合計が W 以下での価値の合計の最大値を出力してください。', h1: '各品物の cnt を 1,2,4,… と2の冪に分解。', h2: '分解した束を0/1ナップサックとして処理。', ref: 'n,W=map(int,input().split())\ndp=[0]*(W+1)\nfor _ in range(n):\n    w,v,cnt=map(int,input().split())\n    k=1\n    while cnt>0:\n        take=min(k,cnt)\n        ww=w*take\n        vv=v*take\n        for c in range(W,ww-1,-1):\n            if dp[c-ww]+vv>dp[c]:\n                dp[c]=dp[c-ww]+vv\n        cnt-=take\n        k*=2\nprint(dp[W])', tip: '2進分割で「個数制限」を O(log) 個の0/1品物に圧縮できる。', ins: ['2 5\n2 3 2\n3 4 1\n', '1 10\n3 5 2\n', '0 5\n', '1 7\n2 3 3\n', '2 6\n1 1 6\n4 10 1\n', '1 4\n5 100 1\n'] })

t({ lv: 290, concept: 'DP: 回文分割の最小カット', title: '回文に分割する最小カット数', tags: ['dp', '文字列'], io: '文字列 s が1行で与えられます。', ask: 's をすべて回文になるように分割するとき、必要な最小のカット数を出力してください。', h1: 'まず全区間が回文かを表で前計算。', h2: 'cut[i]=先頭 i+1 文字を分割する最小カット数。', ref: 's=input()\nn=len(s)\nif n==0:\n    print(0)\nelse:\n    pal=[[False]*n for _ in range(n)]\n    for i in range(n):\n        pal[i][i]=True\n    for length in range(2,n+1):\n        for i in range(n-length+1):\n            j=i+length-1\n            if s[i]==s[j] and (length==2 or pal[i+1][j-1]):\n                pal[i][j]=True\n    cut=[0]*n\n    for i in range(n):\n        if pal[0][i]:\n            cut[i]=0\n        else:\n            m=i\n            for j in range(1,i+1):\n                if pal[j][i] and cut[j-1]+1<m:\n                    m=cut[j-1]+1\n            cut[i]=m\n    print(cut[n-1])', tip: '回文判定を区間DPで前計算しておくと本体DPが O(n²)。', ins: ['aab\n', 'a\n', 'abccba\n', 'abcde\n', 'noonabbad\n', 'racecar\n'] })

t({ lv: 291, concept: 'DP: 区間ゲームの得点差', title: '両端から取るゲームの最大得点差', tags: ['dp', '区間DP'], io: '整数列が1行で与えられます。2人が交互に列の左端か右端の数を取り、各自合計を最大化します。', ask: '両者が最善を尽くしたときの「先手の合計 − 後手の合計」を出力してください。', h1: 'dp[i][j]=区間[i,j]での手番側の最大得点差。', h2: '左を取る/右を取るで a[端]-dp[残り] の大きい方。', ref: 'a=list(map(int,input().split()))\nn=len(a)\ndp=[[0]*n for _ in range(n)]\nfor i in range(n):\n    dp[i][i]=a[i]\nfor length in range(2,n+1):\n    for i in range(n-length+1):\n        j=i+length-1\n        dp[i][j]=max(a[i]-dp[i+1][j],a[j]-dp[i][j-1])\nprint(dp[0][n-1])', tip: '相手の最善も同じ式に含まれる「差」を持つのがゲームDPの定石。', ins: ['1 2 3 4\n', '5\n', '1 5 2\n', '3 9 1 2\n', '10 10\n', '2 4 8 16 32\n'] })

t({ lv: 292, concept: 'DP: グリッド最大価値収集', title: '右下まで集める価値の最大', tags: ['dp', 'グリッド'], io: '1行目に H W、続く H 行に W 個の整数が与えられます。左上から右下へ右か下にのみ進みます。', ask: '通過したマスの値の合計の最大値を出力してください。', h1: 'dp[i][j]=そこまでの最大和。', h2: '上と左の大きい方 + 自分の値。', ref: 'h,w=map(int,input().split())\ng=[list(map(int,input().split())) for _ in range(h)]\ndp=[[0]*w for _ in range(h)]\nfor i in range(h):\n    for j in range(w):\n        best=0\n        if i>0:\n            best=dp[i-1][j]\n        if j>0 and dp[i][j-1]>best:\n            best=dp[i][j-1]\n        dp[i][j]=best+g[i][j]\nprint(dp[h-1][w-1])', tip: '最小経路和と同型。min を max に変えるだけ。', ins: ['2 2\n1 2\n3 4\n', '1 1\n5\n', '3 3\n1 2 3\n4 5 6\n7 8 9\n', '1 3\n1 2 3\n', '2 3\n1 0 5\n2 3 1\n', '3 1\n5\n3\n2\n'] })

t({ lv: 293, concept: 'グラフ: 島の個数', title: '連結した1のかたまりの数', tags: ['BFS', 'グリッド'], io: '1行目に H W、続く H 行に 0/1 のグリッドが与えられます。', ask: '上下左右に繋がった 1 のかたまり (島) の個数を出力してください。', h1: '未訪問の1から幅優先で塗りつぶす。', h2: '塗り始めるたびに島の数を1増やす。', ref: 'from collections import deque\nh,w=map(int,input().split())\ng=[input().split() for _ in range(h)]\nseen=[[False]*w for _ in range(h)]\ncnt=0\nfor i in range(h):\n    for j in range(w):\n        if g[i][j]=="1" and not seen[i][j]:\n            cnt+=1\n            seen[i][j]=True\n            dq=deque([(i,j)])\n            while dq:\n                y,x=dq.popleft()\n                for dy,dx in ((1,0),(-1,0),(0,1),(0,-1)):\n                    ny,nx=y+dy,x+dx\n                    if 0<=ny<h and 0<=nx<w and g[ny][nx]=="1" and not seen[ny][nx]:\n                        seen[ny][nx]=True\n                        dq.append((ny,nx))\nprint(cnt)', tip: '連結成分の個数を数える典型 (塗りつぶしの回数＝島の数)。', ins: ['3 3\n1 1 0\n0 1 0\n0 0 1\n', '2 2\n0 0\n0 0\n', '1 4\n1 0 1 1\n', '3 3\n1 0 1\n0 0 0\n1 0 1\n', '2 2\n1 1\n1 1\n', '3 3\n1 1 1\n0 0 0\n1 1 1\n'] })

t({ lv: 294, concept: 'グラフ: 有向グラフの閉路判定', title: '有向グラフに閉路があるか', tags: ['トポロジカル', 'グラフ'], io: '1行目に n m、続く m 行に有向辺 u→v が与えられます。', ask: '閉路 (有向サイクル) があれば yes、なければ no を出力してください。', h1: '入次数0から順に取り除く (Kahn法)。', h2: '全頂点を取り除けなければ閉路あり。', ref: 'from collections import deque\nn,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nindeg=[0]*(n+1)\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    indeg[v]+=1\ndq=deque(i for i in range(1,n+1) if indeg[i]==0)\nseen=0\nwhile dq:\n    x=dq.popleft()\n    seen+=1\n    for y in g[x]:\n        indeg[y]-=1\n        if indeg[y]==0:\n            dq.append(y)\nprint("yes" if seen<n else "no")', tip: 'トポロジカルソートできない＝閉路がある、と同値。', ins: ['3 3\n1 2\n2 3\n3 1\n', '3 2\n1 2\n2 3\n', '1 1\n1 1\n', '4 4\n1 2\n2 3\n3 4\n2 4\n', '2 2\n1 2\n2 1\n', '5 0\n'] })

t({ lv: 295, concept: 'グラフ: オイラー路の存在', title: 'オイラー路が存在するか', tags: ['グラフ', 'BFS'], io: '1行目に n m、続く m 行に無向辺 u v (多重辺なし) が与えられます。', ask: 'すべての辺をちょうど1回ずつ通る経路 (オイラー路) が存在するなら yes、なければ no を出力してください。', h1: '辺を持つ頂点が連結であること。', h2: '奇数次数の頂点が0個か2個であること。', ref: 'from collections import deque\nn,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\ndeg=[0]*(n+1)\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\n    deg[u]+=1\n    deg[v]+=1\nstart=-1\nfor i in range(1,n+1):\n    if deg[i]>0:\n        start=i\n        break\nconnected=True\nif start!=-1:\n    seen=[False]*(n+1)\n    seen[start]=True\n    dq=deque([start])\n    while dq:\n        x=dq.popleft()\n        for y in g[x]:\n            if not seen[y]:\n                seen[y]=True\n                dq.append(y)\n    for i in range(1,n+1):\n        if deg[i]>0 and not seen[i]:\n            connected=False\nodd=sum(1 for i in range(1,n+1) if deg[i]%2==1)\nprint("yes" if connected and (odd==0 or odd==2) else "no")', tip: 'オイラー路の存在条件は「連結 ＋ 奇数次数が0か2」。', ins: ['3 3\n1 2\n2 3\n1 3\n', '4 3\n1 2\n2 3\n3 4\n', '4 4\n1 2\n2 3\n3 4\n4 1\n', '5 3\n1 2\n3 4\n4 5\n', '4 4\n1 2\n1 3\n1 4\n2 3\n', '1 0\n'] })

t({ lv: 296, concept: 'グラフ: 各点から到達できる頂点数の最大', title: '到達可能な頂点数の最大', tags: ['グラフ', 'BFS'], io: '1行目に n m、続く m 行に有向辺 u→v が与えられます。', ask: 'ある頂点から有向辺をたどって到達できる頂点数 (自分を含む) を、出発点を変えたときの最大値を出力してください。', h1: '各頂点を始点に幅優先。', h2: '訪問数の最大を取る。', ref: 'from collections import deque\nn,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\nbest=0\nfor s in range(1,n+1):\n    seen=[False]*(n+1)\n    seen[s]=True\n    dq=deque([s])\n    c=0\n    while dq:\n        x=dq.popleft()\n        c+=1\n        for y in g[x]:\n            if not seen[y]:\n                seen[y]=True\n                dq.append(y)\n    if c>best:\n        best=c\nprint(best)', tip: '小規模なら全頂点からのBFSで到達集合を総当たりできる。', ins: ['3 2\n1 2\n2 3\n', '3 0\n', '4 3\n1 2\n1 3\n1 4\n', '2 1\n2 1\n', '5 4\n1 2\n2 3\n3 4\n4 5\n', '3 3\n1 2\n2 3\n3 1\n'] })

t({ lv: 297, concept: 'グラフ: 辞書順最小のトポロジカル順序', title: '辞書順で最小のトポロジカル順序', tags: ['トポロジカル', 'heapq'], io: '1行目に n m、続く m 行に有向辺 u→v (閉路なし) が与えられます。', ask: 'トポロジカル順序のうち辞書順で最小のものを空白区切りで出力してください。', h1: '入次数0の頂点を優先度付きキューで管理。', h2: '常に最小番号を取り出す。', ref: 'import heapq\nn,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nindeg=[0]*(n+1)\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    indeg[v]+=1\nh=[i for i in range(1,n+1) if indeg[i]==0]\nheapq.heapify(h)\nres=[]\nwhile h:\n    x=heapq.heappop(h)\n    res.append(x)\n    for y in g[x]:\n        indeg[y]-=1\n        if indeg[y]==0:\n            heapq.heappush(h,y)\nprint(*res)', tip: 'Kahn法の「取り出し」をヒープにすると辞書順最小が得られる。', ins: ['3 2\n1 2\n2 3\n', '4 2\n3 4\n1 2\n', '3 0\n', '4 3\n1 2\n1 3\n2 4\n', '5 4\n5 4\n4 3\n3 2\n2 1\n', '6 3\n1 4\n2 5\n3 6\n'] })

t({ lv: 298, concept: 'グラフ: 閉路を持つ成分の数', title: '閉路を含む連結成分の数', tags: ['データ構造', 'グラフ'], io: '1行目に n m、続く m 行に無向辺 u v (多重辺・自己ループなし) が与えられます。', ask: '閉路を含む連結成分の個数を出力してください。', h1: '各成分の頂点数と辺数を Union-Find で数える。', h2: '辺数 >= 頂点数 の成分は閉路を持つ。', ref: 'from collections import defaultdict\nn,m=map(int,input().split())\npar=list(range(n+1))\ndef find(x):\n    while par[x]!=x:\n        par[x]=par[par[x]]\n        x=par[x]\n    return x\nedges=[]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    edges.append((u,v))\n    ru=find(u)\n    rv=find(v)\n    if ru!=rv:\n        par[ru]=rv\nvcnt=defaultdict(int)\necnt=defaultdict(int)\nfor i in range(1,n+1):\n    vcnt[find(i)]+=1\nfor u,v in edges:\n    ecnt[find(u)]+=1\nans=0\nfor r in vcnt:\n    if ecnt[r]>=vcnt[r]:\n        ans+=1\nprint(ans)', tip: '木は「辺数＝頂点数−1」。それを超える成分は必ず閉路を含む。', ins: ['3 3\n1 2\n2 3\n1 3\n', '4 2\n1 2\n3 4\n', '5 4\n1 2\n2 3\n3 1\n4 5\n', '1 0\n', '6 6\n1 2\n2 3\n3 1\n4 5\n5 6\n6 4\n', '4 3\n1 2\n2 3\n3 4\n'] })

t({ lv: 299, concept: '数論: 1からNまでのXOR', title: '1からNまでの排他的論理和', tags: ['数論', 'bit'], io: '整数 N (>=1) が1行で与えられます。', ask: '1 から N までのすべての整数の排他的論理和 (XOR) を出力してください。', h1: 'N を4で割った余りで結果が決まる。', h2: '余り 0→N, 1→1, 2→N+1, 3→0。', ref: 'n=int(input())\nr=n%4\nif r==0:\n    print(n)\nelif r==1:\n    print(1)\nelif r==2:\n    print(n+1)\nelse:\n    print(0)', tip: '連続整数のXORは周期4の規則があり、O(1)で求まる。', ins: ['1\n', '2\n', '3\n', '4\n', '5\n', '7\n'] })

t({ lv: 300, concept: 'DP: 最長共通増加部分列', title: '最長共通増加部分列の長さ', tags: ['dp'], io: '2つの整数列が各行で与えられます。', ask: '両方に共通して現れ、かつ狭義単調増加である部分列の最大の長さを出力してください。', h1: 'b の各位置に対する dp を a の要素ごとに更新。', h2: 'b[j]==x で dp[j]=best+1、b[j]<x で best を更新。', ref: 'a=list(map(int,input().split()))\nb=list(map(int,input().split()))\nm=len(b)\ndp=[0]*m\nfor x in a:\n    best=0\n    for j in range(m):\n        if b[j]==x:\n            if best+1>dp[j]:\n                dp[j]=best+1\n        elif b[j]<x:\n            if dp[j]>best:\n                best=dp[j]\nprint(max(dp) if m>0 else 0)', tip: '共通部分列(LCS)と増加部分列(LIS)を1つのDPに融合した発展形。', ins: ['1 4 2 3\n1 2 3 4\n', '2 8 4\n2 4 8\n', '1 2 3\n1 2 3\n', '5\n5\n', '3 2 1\n1 2 3\n', '1 3 5\n2 4 6\n'] })

export const CATALOG = TASKS
