// 生成タスク 第35波：lv451〜499。lv450(最上級踏み段)とlv500(再帰・二分探索)の間を、
// 文字列アルゴリズム/古典DP/グラフ構造解析/計算幾何/線形代数(GF2)/組合せ論の
// 「本物の別問題」で連続充足する。再帰は prereq 土台外なので使用可。
// 重複なし・決定的・採点一意(整数/文字列出力のみ)。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 451, concept: '文字列: Z配列で出現回数', title: 'Z配列によるパターン出現回数', tags: ['文字列'], io: '1行目に本文 text、2行目にパターン pat が与えられます。', ask: 'text 中に pat が現れる回数（重なり可）を出力してください。', h1: 'pat + 区切り + text を連結し Z 配列を作る。', h2: 'Z 値が |pat| 以上の位置が出現位置。', ref: 'text=input()\npat=input()\ns=pat+"\\0"+text\nn=len(s)\nz=[0]*n\nl=0\nr=0\nfor i in range(1,n):\n    if i<r:\n        z[i]=min(r-i,z[i-l])\n    while i+z[i]<n and s[z[i]]==s[i+z[i]]:\n        z[i]+=1\n    if i+z[i]>r:\n        l=i\n        r=i+z[i]\nm=len(pat)\ncnt=0\nfor i in range(n):\n    if z[i]>=m:\n        cnt+=1\nprint(cnt)', tip: 'Z配列は各位置から始まる接頭辞との最長一致長。文字列検索を線形時間にできる。', ins: ['ababab\nab\n', 'aaaa\naa\n', 'abc\nd\n', 'aaa\na\n', 'xyzxyz\nxyz\n', 'a\nab\n'] })

t({ lv: 452, concept: '文字列: KMPの最小周期', title: '接頭辞関数で最小周期', tags: ['文字列'], io: '文字列 s が1行で与えられます。', ask: 's の全ての有効な i で s[i]=s[i+p] が成り立つ最小の p（最小周期）を出力してください。', h1: '接頭辞関数(失敗関数) pi を計算する。', h2: '最小周期は n - pi[n-1]。', ref: 's=input()\nn=len(s)\nif n==0:\n    print(0)\nelse:\n    pi=[0]*n\n    for i in range(1,n):\n        j=pi[i-1]\n        while j>0 and s[i]!=s[j]:\n            j=pi[j-1]\n        if s[i]==s[j]:\n            j+=1\n        pi[i]=j\n    print(n-pi[n-1])', tip: '接頭辞関数(KMP)は最長の真の境界(接頭辞=接尾辞)長を与え、周期検出に直結する。', ins: ['abcabcab\n', 'aaaa\n', 'abcd\n', 'ababab\n', 'a\n', 'abab\n'] })

t({ lv: 453, concept: '文字列: Manacher最長回文', title: 'Manacher法で最長回文部分文字列', tags: ['文字列'], io: '文字列 s が1行で与えられます。', ask: 's の最長の回文連続部分文字列の長さを出力してください。', h1: '#区切りを入れて奇偶を統一する。', h2: '中心と右端を保持して半径を伸ばす(Manacher)。', ref: 's=input()\nt="#"+"#".join(s)+"#"\nn=len(t)\np=[0]*n\nc=0\nr=0\nfor i in range(n):\n    if i<r:\n        p[i]=min(r-i,p[2*c-i])\n    while i-p[i]-1>=0 and i+p[i]+1<n and t[i-p[i]-1]==t[i+p[i]+1]:\n        p[i]+=1\n    if i+p[i]>r:\n        c=i\n        r=i+p[i]\nprint(max(p) if n>0 else 0)', tip: 'Manacher法は全中心の最長回文半径を線形時間で求める。', ins: ['babad\n', 'cbbd\n', 'a\n', 'abba\n', 'abc\n', 'aaaa\n'] })

t({ lv: 454, concept: '文字列: 辞書順最小の回転', title: '最小の巡回シフト', tags: ['文字列'], io: '文字列 s が1行で与えられます。', ask: 's の全ての巡回シフトのうち辞書順で最小のものを出力してください。', h1: '各開始位置から s[i:]+s[:i] を作る。', h2: '最小を更新する。', ref: 's=input()\nn=len(s)\nif n==0:\n    print("")\nelse:\n    best=s\n    for i in range(1,n):\n        cand=s[i:]+s[:i]\n        if cand<best:\n            best=cand\n    print(best)', tip: '最小回転は循環文字列の正規形。大規模ではBoothのアルゴリズムでO(n)化できる。', ins: ['bca\n', 'cba\n', 'aaa\n', 'dcba\n', 'abcabc\n', 'b\n'] })

t({ lv: 455, concept: '文字列: 相異なる部分文字列の数', title: '異なる連続部分文字列の総数', tags: ['文字列'], io: '文字列 s が1行で与えられます。', ask: 's に現れる相異なる連続部分文字列の個数を出力してください。', h1: '全ての開始・終了位置の部分文字列を集合に入れる。', h2: '集合の要素数を数える。', ref: 's=input()\nn=len(s)\nsubs=set()\nfor i in range(n):\n    for j in range(i+1,n+1):\n        subs.add(s[i:j])\nprint(len(subs))', tip: '相異なる部分文字列数は接尾辞配列＋LCPで n(n+1)/2 − ΣLCP として高速に求まる。', ins: ['abc\n', 'aaa\n', 'abab\n', 'a\n', 'abcabc\n', 'aab\n'] })

t({ lv: 456, concept: 'DP: 最長ジグザグ部分列', title: '最長ジグザグ(交互)部分列の長さ', tags: ['dp'], io: '整数列が1行で空白区切りで与えられます。', ask: '隣接差の符号が交互になる最長の部分列(ジグザグ列)の長さを出力してください。', h1: '直前が上りで終わる長さ up と下りで終わる長さ down を持つ。', h2: '増加で up=down+1、減少で down=up+1 と更新。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nif n==0:\n    print(0)\nelif n==1:\n    print(1)\nelse:\n    up=1\n    down=1\n    for i in range(1,n):\n        if a[i]>a[i-1]:\n            up=down+1\n        elif a[i]<a[i-1]:\n            down=up+1\n    print(max(up,down))', tip: 'ジグザグ(wiggle)部分列は up/down の2状態を持てば O(n) の貪欲で解ける。', ins: ['1 7 4 9 2 5\n', '1 2 3 4 5\n', '1 1 1\n', '5\n', '3 3 3 2 5\n', '10 22 9 33 49 50 31 60\n'] })

t({ lv: 457, concept: 'DP: 最大和増加部分列', title: '最大和の増加部分列', tags: ['dp'], io: '整数列が1行で空白区切りで与えられます。', ask: '狭義単調増加な部分列のうち、要素の和が最大になる値を出力してください。', h1: 'dp[i]=a[i]で終わる増加部分列の最大和。', h2: 'a[j]<a[i] の j から dp[j]+a[i] を取り最大化。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nif n==0:\n    print(0)\nelse:\n    dp=a[:]\n    for i in range(n):\n        for j in range(i):\n            if a[j]<a[i] and dp[j]+a[i]>dp[i]:\n                dp[i]=dp[j]+a[i]\n    print(max(dp))', tip: '最大和増加部分列はLISの「長さ」を「和」に置き換えたDP。', ins: ['1 101 2 3 100\n', '3 4 5 10\n', '10 5 4 3\n', '1\n', '4 6 1 3 8 4 6\n', '2 2 2\n'] })

t({ lv: 458, concept: 'DP: 最長等差部分列', title: '最長等差部分列の長さ', tags: ['dp'], io: '整数列が1行で空白区切りで与えられます。', ask: '公差が一定になる最長の部分列の長さを出力してください。', h1: 'dp[i][d]=a[i]で終わり公差dの最長長さ。', h2: 'j<i について d=a[i]-a[j] を辞書で引いて+1。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nif n<=1:\n    print(n)\nelse:\n    dp=[{} for _ in range(n)]\n    best=1\n    for i in range(n):\n        for j in range(i):\n            d=a[i]-a[j]\n            dp[i][d]=dp[j].get(d,1)+1\n            if dp[i][d]>best:\n                best=dp[i][d]\n    print(best)', tip: '最長等差部分列は「公差」を辞書のキーにしたDP。各位置で公差ごとの最長を保持する。', ins: ['3 6 9 12\n', '9 4 7 2 10\n', '1 2 3 4\n', '5\n', '1 7 10 13 14 19\n', '2 2 2\n'] })

t({ lv: 459, concept: '区間DP: 文字ごとのコストで回文にする最小費用', title: '削除費用つきで回文にする', tags: ['DP'], io: '1行目に英小文字の文字列、2行目に a から z までの削除コスト26個が空白区切りで与えられます。', ask: '文字を削除して回文にするとき、削除した文字のコストの合計の最小を出力してください。', h1: '両端が同じ文字なら、その2文字は削らずに内側だけ考えればよい。', h2: '違うなら、左端を削るか右端を削るかの安い方。区間の長さが短い順に埋める。', ref: 's=input().strip()\ncost=list(map(int,input().split()))\nn=len(s)\ndp=[[0]*n for _ in range(n)]\nfor L in range(2,n+1):\n    for i in range(n-L+1):\n        j=i+L-1\n        if s[i]==s[j]:\n            dp[i][j]=dp[i+1][j-1]\n        else:\n            dp[i][j]=min(cost[ord(s[i])-97]+dp[i+1][j], cost[ord(s[j])-97]+dp[i][j-1])\nprint(dp[0][n-1])', tip: '削除の回数を数える版(既出)に文字ごとの重みを足すと、同じ区間DPのまま最小化の対象だけが変わる。回数はコストがすべて1の特別な場合にすぎない、と分かるのがこの問題の狙い。', ins: ['ab\n1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1', 'aba\n5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5', 'abc\n1 10 100 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1', 'a\n3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3', 'abcb\n2 3 4 5 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1', 'aabb\n1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1'] })

t({ lv: 460, concept: '区間DP: 行列連鎖積', title: '行列連鎖積の最小コスト', tags: ['区間DP', 'dp'], io: '1行目に行列数 n、2行目に n+1 個の次元 p0..pn が与えられます(i番目の行列は p[i-1]×p[i])。', ask: '全ての積を計算する最小スカラー乗算回数を出力してください。', h1: '区間 [i,j] を分割点 k で切る。', h2: 'dp[i][j]=min(dp[i][k]+dp[k+1][j]+p_i·p_{k+1}·p_{j+1})。', ref: 'n=int(input())\np=list(map(int,input().split()))\nINF=float("inf")\ndp=[[0]*n for _ in range(n)]\nfor length in range(2,n+1):\n    for i in range(n-length+1):\n        j=i+length-1\n        dp[i][j]=INF\n        for k in range(i,j):\n            cost=dp[i][k]+dp[k+1][j]+p[i]*p[k+1]*p[j+1]\n            if cost<dp[i][j]:\n                dp[i][j]=cost\nprint(dp[0][n-1])', tip: '行列連鎖積は区間DPの代表例。掛ける順序で計算量が大きく変わる。', ins: ['3\n10 30 5 60\n', '2\n10 20 30\n', '1\n5 10\n', '4\n40 20 30 10 30\n', '3\n1 2 3 4\n', '2\n5 5 5\n'] })

t({ lv: 461, concept: 'DP: 硬貨の組合せ数', title: '金額を作る組合せの数', tags: ['dp'], io: '1行目に金額 amount、2行目に硬貨の額面が空白区切りで与えられます。', ask: '順序を区別せず amount を作る方法の数を出力してください(各硬貨は何枚でも使える)。', h1: '硬貨を外側ループにして順序の重複を防ぐ。', h2: 'dp[x]+=dp[x-c]。', ref: 'amount=int(input())\ncoins=list(map(int,input().split()))\ndp=[0]*(amount+1)\ndp[0]=1\nfor c in coins:\n    for x in range(c,amount+1):\n        dp[x]+=dp[x-c]\nprint(dp[amount])', tip: '硬貨を外側ループにすると組合せ(順不同)、金額を外側にすると順列(順序あり)を数える。', ins: ['5\n1 2 5\n', '3\n2\n', '0\n1 2\n', '10\n2 5 3 6\n', '4\n1 2 3\n', '11\n1 5 10\n'] })

t({ lv: 462, concept: 'DP: 硬貨の最小枚数', title: '金額を作る最小硬貨枚数', tags: ['dp'], io: '1行目に金額 amount、2行目に硬貨の額面が空白区切りで与えられます。', ask: 'amount を作る最小の硬貨枚数を出力してください。作れないなら -1 を出力してください。', h1: 'dp[x]=金額xを作る最小枚数。', h2: 'dp[x]=min(dp[x-c]+1)。', ref: 'amount=int(input())\ncoins=list(map(int,input().split()))\nINF=float("inf")\ndp=[INF]*(amount+1)\ndp[0]=0\nfor x in range(1,amount+1):\n    for c in coins:\n        if c<=x and dp[x-c]+1<dp[x]:\n            dp[x]=dp[x-c]+1\nprint(dp[amount] if dp[amount]<INF else -1)', tip: '最小枚数は貪欲では誤ることがあり、DPが必要(例: 額面1,3,4で6)。', ins: ['11\n1 2 5\n', '3\n2\n', '0\n5\n', '7\n2 4\n', '6\n1 3 4\n', '27\n9 6 5 1\n'] })

t({ lv: 463, concept: '数え上げ: 分割数', title: '整数の分割数 p(n)', tags: ['数え上げ', 'dp'], io: '整数 n が1行で与えられます。', ask: 'n を正整数の和で表す方法(順不同)の数 p(n) を出力してください。', h1: '部品 k を 1..n と増やしながら詰める。', h2: 'dp[x]+=dp[x-k]（各kで昇順更新）。', ref: 'n=int(input())\ndp=[0]*(n+1)\ndp[0]=1\nfor k in range(1,n+1):\n    for x in range(k,n+1):\n        dp[x]+=dp[x-k]\nprint(dp[n])', tip: '分割数は各部品サイズを一度ずつ無制限ナップサックで詰めると求まる。', ins: ['5\n', '0\n', '1\n', '10\n', '7\n', '20\n'] })

t({ lv: 464, concept: '数え上げ: カタラン数', title: '階乗を使わずにカタラン数', tags: ['数え上げ'], io: '整数 n が1行で与えられます。', ask: 'n 番目のカタラン数 C(n) を出力してください。', h1: 'C(0)=1 から漸化式で進める。', h2: 'C(i+1)=C(i)·2(2i+1)/(i+2)。', ref: 'n=int(input())\nc=1\nfor i in range(n):\n    c=c*(2*(2*i+1))//(i+2)\nprint(c)', tip: 'カタラン数は括弧列・二分木・多角形分割など多くの数え上げに現れる。', ins: ['5\n', '0\n', '1\n', '10\n', '3\n', '15\n'] })

t({ lv: 465, concept: '数え上げ: ベル数', title: 'ベル数(集合の分割数)', tags: ['数え上げ'], io: '整数 n が1行で与えられます。', ask: 'n 要素の集合を空でない部分集合に分割する方法の数(ベル数 B(n))を出力してください。', h1: 'ベル三角形を1行ずつ作る。', h2: '次行の先頭は前行末尾、以降は左+真上前行。', ref: 'n=int(input())\nrow=[1]\nfor i in range(1,n+1):\n    nxt=[row[-1]]\n    for j in range(i):\n        nxt.append(nxt[-1]+row[j])\n    row=nxt\nprint(row[0])', tip: 'ベル数は第二種スターリング数の総和。ベル三角形で逐次計算できる。', ins: ['5\n', '0\n', '1\n', '3\n', '7\n', '10\n'] })

t({ lv: 466, concept: '数え上げ: 第二種スターリング数', title: '第二種スターリング数 S(n,k)', tags: ['数え上げ', 'dp'], io: 'n k が空白区切りで与えられます。', ask: 'n 要素を空でない k 個のグループに分ける方法の数 S(n,k) を出力してください。', h1: 'dp[i][j]=S(i,j)。', h2: 'S(i,j)=j·S(i-1,j)+S(i-1,j-1)。', ref: 'n,k=map(int,input().split())\ndp=[[0]*(k+1) for _ in range(n+1)]\ndp[0][0]=1\nfor i in range(1,n+1):\n    for j in range(1,k+1):\n        dp[i][j]=j*dp[i-1][j]+dp[i-1][j-1]\nprint(dp[n][k])', tip: '第二種スターリング数は「ラベルなしグループへの分割」。新要素を既存に入れるか新グループにするかで漸化式が立つ。', ins: ['5 2\n', '4 2\n', '3 3\n', '5 0\n', '0 0\n', '6 3\n'] })

t({ lv: 467, concept: '数え上げ: 完全順列', title: '完全順列(撹乱)の数', tags: ['数え上げ'], io: '整数 n が1行で与えられます。', ask: 'どの要素も元の位置に来ない順列(完全順列)の数 D(n) を出力してください。', h1: 'D(0)=1, D(1)=0 から始める。', h2: 'D(i)=(i-1)·(D(i-1)+D(i-2))。', ref: 'n=int(input())\nif n==0:\n    print(1)\nelse:\n    a=1\n    b=0\n    for i in range(2,n+1):\n        c=(i-1)*(a+b)\n        a=b\n        b=c\n    print(b)', tip: '完全順列(モンモール数)は包除原理でも導け、D(n)≈n!/e に近い。', ins: ['4\n', '0\n', '1\n', '5\n', '3\n', '10\n'] })

t({ lv: 468, concept: '包除原理: 全射の数', title: '全射(onto写像)の数', tags: ['数え上げ', '包除原理'], io: 'n k が空白区切りで与えられます。', ask: 'n 要素から k 要素への全射(値域を網羅する写像)の数を出力してください。', h1: '包除原理で「i 個の像を除外」を交互に足し引き。', h2: 'Σ(-1)^i·C(k,i)·(k-i)^n。', ref: 'import math\nn,k=map(int,input().split())\ntotal=0\nfor i in range(k+1):\n    total+=(-1)**i*math.comb(k,i)*(k-i)**n\nprint(total)', tip: '全射の数は k!·S(n,k) にも等しい(第二種スターリング数×グループの並べ方)。', ins: ['3 2\n', '4 2\n', '5 3\n', '2 2\n', '3 3\n', '0 0\n'] })

t({ lv: 469, concept: '桁DP: 桁和が指定値の数', title: '桁和がSになる数の個数', tags: ['桁DP', 'dp'], io: 'N S が空白区切りで与えられます(N は大きくてよい)。', ask: '0 以上 N 以下の整数で各桁の和がちょうど S になるものの個数を出力してください。', h1: '上位桁から「Nに張り付いているか(tight)」を状態に持つ。', h2: 'メモ化再帰で桁を1つずつ決める。', ref: 'import sys\nsys.setrecursionlimit(10000)\nfrom functools import lru_cache\nN,S=input().split()\nS=int(S)\ndigits=[int(c) for c in N]\nL=len(digits)\n@lru_cache(maxsize=None)\ndef rec(pos,tight,ssum):\n    if ssum>S:\n        return 0\n    if pos==L:\n        return 1 if ssum==S else 0\n    hi=digits[pos] if tight else 9\n    total=0\n    for d in range(hi+1):\n        total+=rec(pos+1,tight and d==hi,ssum+d)\n    return total\nprint(rec(0,True,0))', tip: '桁DPは「上限への張り付き」を状態に持つことで [0,N] の数を桁ごとに数える定石。', ins: ['100 5\n', '9 9\n', '20 2\n', '0 0\n', '999 1\n', '50 13\n'] })

t({ lv: 470, concept: 'bitDP: ハミルトン路の数', title: '全頂点を一度ずつ通る経路の数', tags: ['bitDP', 'グラフ'], io: '1行目に n m、続く m 行に無向辺 u v(1始まり)が与えられます。', ask: '全頂点をちょうど1回ずつ訪れる経路(ハミルトン路)の総数を出力してください(向きの違うものは別に数える)。', h1: 'dp[訪問集合][現在地]=経路数。', h2: '未訪問の隣接へ遷移して足し込む。', ref: 'first=input().split()\nn=int(first[0])\nm=int(first[1])\nadj=[[False]*n for _ in range(n)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    adj[u-1][v-1]=True\n    adj[v-1][u-1]=True\ndp=[[0]*n for _ in range(1<<n)]\nfor i in range(n):\n    dp[1<<i][i]=1\nfor mask in range(1<<n):\n    for v in range(n):\n        if dp[mask][v]==0:\n            continue\n        for to in range(n):\n            if not adj[v][to] or mask&(1<<to):\n                continue\n            dp[mask|(1<<to)][to]+=dp[mask][v]\nfull=(1<<n)-1\nprint(sum(dp[full][v] for v in range(n)))', tip: 'ハミルトン路はbitDPで「訪問済み集合×現在地」を状態にO(2^n·n^2)で数えられる。', ins: ['3 2\n1 2\n2 3\n', '3 3\n1 2\n2 3\n1 3\n', '2 1\n1 2\n', '4 4\n1 2\n2 3\n3 4\n4 1\n', '1 0\n', '4 3\n1 2\n1 3\n1 4\n'] })

t({ lv: 471, concept: 'グラフ: 全点対最短路の総和', title: 'ワーシャルフロイドの距離総和', tags: ['グラフ'], io: '1行目に n m、続く m 行に有向辺 u v w が与えられます。', ask: '到達可能な全順序対 (i,j)(i≠j) の最短距離の総和を出力してください。', h1: 'dist[i][j] を全頂点経由で緩和する。', h2: 'k,i,j の三重ループ(ワーシャルフロイド)。', ref: 'first=input().split()\nn=int(first[0])\nm=int(first[1])\nINF=float("inf")\ndist=[[INF]*n for _ in range(n)]\nfor i in range(n):\n    dist[i][i]=0\nfor _ in range(m):\n    u,v,w=map(int,input().split())\n    u-=1\n    v-=1\n    if w<dist[u][v]:\n        dist[u][v]=w\nfor k in range(n):\n    for i in range(n):\n        dik=dist[i][k]\n        if dik==INF:\n            continue\n        for j in range(n):\n            if dik+dist[k][j]<dist[i][j]:\n                dist[i][j]=dik+dist[k][j]\ntotal=0\nfor i in range(n):\n    for j in range(n):\n        if i!=j and dist[i][j]<INF:\n            total+=dist[i][j]\nprint(total)', tip: 'ワーシャルフロイドは全点対最短路を O(n^3) で。負辺OK(負閉路は不可)。', ins: ['3 3\n1 2 1\n2 3 2\n1 3 4\n', '2 1\n1 2 5\n', '3 2\n1 2 1\n2 1 1\n', '1 0\n', '4 4\n1 2 1\n2 3 1\n3 4 1\n4 1 1\n', '3 3\n1 2 2\n2 3 2\n3 1 2\n'] })

t({ lv: 472, concept: 'グラフ: 負閉路の検出', title: 'ベルマンフォードで負閉路判定', tags: ['グラフ'], io: '1行目に n m、続く m 行に有向辺 u v w が与えられます。', ask: '負の重みの閉路が存在するなら yes、なければ no を出力してください。', h1: '全頂点を始点扱いに dist を 0 で初期化する。', h2: 'n 回目の緩和で更新が起きれば負閉路あり。', ref: 'first=input().split()\nn=int(first[0])\nm=int(first[1])\nedges=[]\nfor _ in range(m):\n    u,v,w=map(int,input().split())\n    edges.append((u-1,v-1,w))\ndist=[0]*n\nneg=False\nfor i in range(n):\n    updated=False\n    for u,v,w in edges:\n        if dist[u]+w<dist[v]:\n            dist[v]=dist[u]+w\n            updated=True\n    if i==n-1 and updated:\n        neg=True\nprint("yes" if neg else "no")', tip: '全点を始点に dist=0 とすると、どこかにある負閉路を1回の実行で検出できる。', ins: ['3 3\n1 2 1\n2 3 -2\n3 1 -1\n', '2 1\n1 2 5\n', '3 3\n1 2 1\n2 3 1\n3 1 1\n', '2 2\n1 2 -1\n2 1 -1\n', '1 0\n', '3 2\n1 2 -5\n2 3 -5\n'] })

t({ lv: 473, concept: 'グラフ: 辞書順最小トポロジカル順序', title: '辞書順最小のトポロジカルソート', tags: ['グラフ'], io: '1行目に n m、続く m 行に有向辺 u v(u が v より前)が与えられます(DAG)。', ask: '辞書順で最小のトポロジカル順序を頂点番号の空白区切りで出力してください。', h1: '入次数0の頂点を優先度付きキューに入れる。', h2: '常に最小番号を取り出して隣接の入次数を減らす。', ref: 'import heapq\nfirst=input().split()\nn=int(first[0])\nm=int(first[1])\ng=[[] for _ in range(n+1)]\nindeg=[0]*(n+1)\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    indeg[v]+=1\npq=[]\nfor i in range(1,n+1):\n    if indeg[i]==0:\n        heapq.heappush(pq,i)\norder=[]\nwhile pq:\n    x=heapq.heappop(pq)\n    order.append(x)\n    for y in g[x]:\n        indeg[y]-=1\n        if indeg[y]==0:\n            heapq.heappush(pq,y)\nprint(*order)', tip: 'カーンのトポロジカルソートでキューをヒープにすると辞書順最小の順序が得られる。', ins: ['3 2\n1 2\n1 3\n', '4 3\n1 2\n1 3\n2 4\n', '3 0\n', '5 4\n2 1\n3 1\n1 4\n1 5\n', '2 1\n2 1\n', '4 2\n3 4\n1 2\n'] })

t({ lv: 474, concept: 'bitDP: ハミルトン閉路の数', title: '全頂点を一周する閉路の数', tags: ['bitDP', 'グラフ'], io: '1行目に n m、続く m 行に無向辺 u v(1始まり)が与えられます。', ask: '全頂点をちょうど1回ずつ訪れて出発点に戻る閉路(ハミルトン閉路)の数を出力してください(回転・反転で同じものは1つと数える)。', h1: '頂点0を始点に固定し dp[訪問集合][現在地] を持つ。', h2: '全頂点を回り0に戻る経路を数え、向きの分(2)で割る。', ref: 'first=input().split()\nn=int(first[0])\nm=int(first[1])\nadj=[[False]*n for _ in range(n)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    adj[u-1][v-1]=True\n    adj[v-1][u-1]=True\nif n<3:\n    print(0)\nelse:\n    dp=[[0]*n for _ in range(1<<n)]\n    dp[1][0]=1\n    for mask in range(1<<n):\n        for v in range(n):\n            if dp[mask][v]==0:\n                continue\n            for to in range(n):\n                if not adj[v][to] or mask&(1<<to):\n                    continue\n                dp[mask|(1<<to)][to]+=dp[mask][v]\n    full=(1<<n)-1\n    total=0\n    for v in range(n):\n        if adj[v][0]:\n            total+=dp[full][v]\n    print(total//2)', tip: 'ハミルトン閉路は始点固定のbitDPで数え、無向では向き2通り分を割る。', ins: ['3 3\n1 2\n2 3\n1 3\n', '4 4\n1 2\n2 3\n3 4\n4 1\n', '4 6\n1 2\n1 3\n1 4\n2 3\n2 4\n3 4\n', '4 3\n1 2\n2 3\n3 4\n', '3 2\n1 2\n2 3\n', '5 5\n1 2\n2 3\n3 4\n4 5\n5 1\n'] })

t({ lv: 475, concept: 'グラフ: 彩色数', title: 'グラフの彩色数', tags: ['グラフ', 'bitDP'], io: '1行目に n m、続く m 行に無向辺 u v が与えられます。', ask: '隣接頂点が同色にならないように塗るのに必要な最小の色数(彩色数)を出力してください。', h1: '独立集合に1色を割り当てる。', h2: 'dp[集合]=その集合を塗る最小色数。独立な部分集合で1色ずつ進める。', ref: 'first=input().split()\nn=int(first[0])\nm=int(first[1])\nadj=[0]*n\nfor _ in range(m):\n    u,v=map(int,input().split())\n    if u!=v:\n        adj[u-1]|=(1<<(v-1))\n        adj[v-1]|=(1<<(u-1))\nfull=(1<<n)-1\nindep=[True]*(1<<n)\nfor mask in range(1<<n):\n    ok=True\n    for v in range(n):\n        if (mask>>v)&1 and (adj[v]&mask):\n            ok=False\n            break\n    indep[mask]=ok\nINF=n+1\ndp=[INF]*(1<<n)\ndp[0]=0\nfor mask in range(1<<n):\n    if dp[mask]==INF:\n        continue\n    rest=full^mask\n    sub=rest\n    while sub>0:\n        if indep[sub] and dp[mask]+1<dp[mask|sub]:\n            dp[mask|sub]=dp[mask]+1\n        sub=(sub-1)&rest\nprint(dp[full] if n>0 else 0)', tip: '彩色数は「独立集合を1色」とみなし、集合をbitDPで塗り分ける O(3^n) で求まる。', ins: ['3 3\n1 2\n2 3\n1 3\n', '4 4\n1 2\n2 3\n3 4\n4 1\n', '3 2\n1 2\n2 3\n', '5 0\n', '4 6\n1 2\n1 3\n1 4\n2 3\n2 4\n3 4\n', '1 0\n'] })

t({ lv: 476, concept: 'グラフ: 関節点の個数', title: '関節点(切断点)の数', tags: ['グラフ'], io: '1行目に n m、続く m 行に無向辺 u v が与えられます。', ask: '取り除くと連結成分が増える頂点(関節点)の個数を出力してください。', h1: 'DFS木で発見時刻 tin と低リンク low を計算。', h2: '根は子2つ以上、非根は子の low>=tin なら関節点。', ref: 'import sys\nsys.setrecursionlimit(500000)\nfirst=input().split()\nn=int(first[0])\nm=int(first[1])\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\nvisited=[False]*(n+1)\ntin=[0]*(n+1)\nlow=[0]*(n+1)\ntimer=[1]\nap=set()\ndef dfs(u,parent):\n    visited[u]=True\n    tin[u]=low[u]=timer[0]\n    timer[0]+=1\n    children=0\n    for v in g[u]:\n        if v==parent:\n            continue\n        if visited[v]:\n            low[u]=min(low[u],tin[v])\n        else:\n            dfs(v,u)\n            low[u]=min(low[u],low[v])\n            if low[v]>=tin[u] and parent!=0:\n                ap.add(u)\n            children+=1\n    if parent==0 and children>1:\n        ap.add(u)\nfor i in range(1,n+1):\n    if not visited[i]:\n        dfs(i,0)\nprint(len(ap))', tip: '関節点はDFS木のlowリンクで判定する。根だけ「子2つ以上」の特別扱いが要る。', ins: ['3 2\n1 2\n2 3\n', '3 3\n1 2\n2 3\n1 3\n', '5 4\n1 2\n2 3\n3 4\n4 5\n', '1 0\n', '5 5\n1 2\n2 3\n3 1\n3 4\n4 5\n', '4 3\n1 2\n1 3\n1 4\n'] })

t({ lv: 477, concept: 'グラフ: 橋の個数', title: '橋(切断辺)の数', tags: ['グラフ'], io: '1行目に n m、続く m 行に無向辺 u v が与えられます。', ask: '取り除くと連結成分が増える辺(橋)の個数を出力してください。', h1: '各辺に番号を振り、親辺を区別して DFS する。', h2: '子の low>tin なら親への辺は橋。', ref: 'import sys\nsys.setrecursionlimit(500000)\nfirst=input().split()\nn=int(first[0])\nm=int(first[1])\ng=[[] for _ in range(n+1)]\nedges=[]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append((v,len(edges)))\n    g[v].append((u,len(edges)))\n    edges.append((u,v))\nvisited=[False]*(n+1)\ntin=[0]*(n+1)\nlow=[0]*(n+1)\ntimer=[1]\nbridges=[0]\ndef dfs(u,pe):\n    visited[u]=True\n    tin[u]=low[u]=timer[0]\n    timer[0]+=1\n    for v,ei in g[u]:\n        if ei==pe:\n            continue\n        if visited[v]:\n            low[u]=min(low[u],tin[v])\n        else:\n            dfs(v,ei)\n            low[u]=min(low[u],low[v])\n            if low[v]>tin[u]:\n                bridges[0]+=1\nfor i in range(1,n+1):\n    if not visited[i]:\n        dfs(i,-1)\nprint(bridges[0])', tip: '橋は low[v]>tin[u] で判定。多重辺に備えて親「辺」で区別するのが安全。', ins: ['3 2\n1 2\n2 3\n', '3 3\n1 2\n2 3\n1 3\n', '5 4\n1 2\n2 3\n3 4\n4 5\n', '1 0\n', '5 5\n1 2\n2 3\n3 1\n3 4\n4 5\n', '4 4\n1 2\n2 3\n3 1\n3 4\n'] })

t({ lv: 478, concept: 'グラフ: 最短の奇数長閉路', title: '一番短い奇数の輪', tags: ['グラフ', 'BFS'], io: '1行目に n m、続く m 行に無向辺 u v が与えられます。', ask: '辺の本数が奇数である閉路のうち、最も短いものの辺の本数を出力してください。そのような閉路が1つも無ければ -1 を出力してください。', h1: '各頂点を「偶数歩で来た」「奇数歩で来た」の2状態に分けて幅優先探索する。', h2: '始点 s へ奇数歩で戻れたなら、その歩数が s を通る最短の奇数閉路の長さ。すべての s で試して最小を取る。', ref: 'from collections import deque\nn,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\nbest=-1\nfor s in range(1,n+1):\n    dist=[[-1,-1] for _ in range(n+1)]\n    dist[s][0]=0\n    dq=deque([(s,0)])\n    while dq:\n        x,p=dq.popleft()\n        for y in g[x]:\n            if dist[y][1-p]==-1:\n                dist[y][1-p]=dist[x][p]+1\n                dq.append((y,1-p))\n    d=dist[s][1]\n    if d!=-1 and (best==-1 or d<best):\n        best=d\nprint(best)', tip: '2部グラフかどうか(既出)は「奇数長の閉路があるか」の言い換えだったが、ここではその閉路の短さまで測る。頂点を(頂点, 歩数の偶奇)の組に増やすと、ただの幅優先探索に載る——状態を増やして既知の道具に持ち込む典型。', ins: ['3 3\n1 2\n2 3\n1 3\n', '4 4\n1 2\n2 3\n3 4\n4 1\n', '5 5\n1 2\n2 3\n3 4\n4 5\n5 1\n', '1 0\n', '6 6\n1 2\n2 3\n3 1\n4 5\n5 6\n6 4\n', '7 8\n1 2\n2 3\n3 4\n4 5\n5 1\n5 6\n6 7\n7 5\n'] })

t({ lv: 479, concept: 'グラフ: 最大2部マッチング', title: '最大2部マッチングのサイズ', tags: ['グラフ'], io: '1行目に L R E(左頂点数・右頂点数・辺数)、続く E 行に辺 a b(左 a と右 b、1始まり)が与えられます。', ask: '最大マッチングのサイズを出力してください。', h1: '左頂点ごとに増加道を探す(Kuhn法)。', h2: '空きか、相手をずらせれば確保できる。', ref: 'first=input().split()\nL=int(first[0])\nR=int(first[1])\nE=int(first[2])\ng=[[] for _ in range(L+1)]\nfor _ in range(E):\n    a,b=map(int,input().split())\n    g[a].append(b)\nmatchR=[0]*(R+1)\ndef try_kuhn(u,used):\n    for v in g[u]:\n        if not used[v]:\n            used[v]=True\n            if matchR[v]==0 or try_kuhn(matchR[v],used):\n                matchR[v]=u\n                return True\n    return False\nres=0\nfor u in range(1,L+1):\n    used=[False]*(R+1)\n    if try_kuhn(u,used):\n        res+=1\nprint(res)', tip: 'Kuhn法は増加道を見つけてマッチングを1ずつ増やす。König定理で最小頂点被覆とも結びつく。', ins: ['2 2 2\n1 1\n2 2\n', '3 3 4\n1 1\n1 2\n2 1\n3 3\n', '2 2 1\n1 1\n', '1 1 0\n', '3 2 4\n1 1\n2 1\n3 2\n2 2\n', '2 3 3\n1 1\n1 2\n2 3\n'] })

t({ lv: 480, concept: 'グラフ: 木の直径', title: '重み付き木の直径', tags: ['グラフ', '木'], io: '1行目に頂点数 n、続く n-1 行に無向辺 u v w(重み)が与えられます。', ask: '木の直径(最も離れた2頂点間の距離)を出力してください。', h1: '任意の点から最遠点 a を見つける。', h2: 'a から最遠点までの距離が直径(2回BFS)。', ref: 'from collections import deque\nn=int(input())\ng=[[] for _ in range(n+1)]\nfor _ in range(n-1):\n    u,v,w=map(int,input().split())\n    g[u].append((v,w))\n    g[v].append((u,w))\ndef bfs(s):\n    dist=[-1]*(n+1)\n    dist[s]=0\n    dq=deque([s])\n    far=s\n    while dq:\n        x=dq.popleft()\n        for y,w in g[x]:\n            if dist[y]==-1:\n                dist[y]=dist[x]+w\n                if dist[y]>dist[far]:\n                    far=y\n                dq.append(y)\n    return far,dist\na,_=bfs(1)\nb,dist=bfs(a)\nprint(dist[b])', tip: '木の直径は「最遠点から最遠点」を2回探索すれば求まる(任意始点でも最初の最遠点は直径の端)。', ins: ['4\n1 2 1\n2 3 2\n2 4 1\n', '2\n1 2 5\n', '1\n', '5\n1 2 1\n2 3 1\n3 4 1\n4 5 1\n', '3\n1 2 3\n1 3 4\n', '4\n1 2 2\n1 3 2\n1 4 2\n'] })

t({ lv: 481, concept: '木DP: 全頂点間距離の総和', title: '木の全頂点ペア間距離の総和', tags: ['木', 'dp'], io: '1行目に頂点数 n、続く n-1 行に無向辺 u v が与えられます。', ask: '全ての頂点ペア(無向、i<j)の距離(辺数)の総和を出力してください。', h1: '各辺は木を2つに分ける。', h2: '辺ごとに(片側のサイズ)×(反対側のサイズ)を足す。', ref: 'n=int(input())\ng=[[] for _ in range(n+1)]\nfor _ in range(n-1):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\nsize=[1]*(n+1)\nparent=[0]*(n+1)\norder=[]\nseen=[False]*(n+1)\nseen[1]=True\nstack=[1]\nwhile stack:\n    x=stack.pop()\n    order.append(x)\n    for y in g[x]:\n        if not seen[y]:\n            seen[y]=True\n            parent[y]=x\n            stack.append(y)\nfor x in reversed(order):\n    if parent[x]!=0:\n        size[parent[x]]+=size[x]\ntotal=0\nfor x in range(2,n+1):\n    s=size[x]\n    total+=s*(n-s)\nprint(total)', tip: '全ペア距離の総和は「各辺が何ペアの経路に使われるか」を size×(n−size) で数えると O(n)。', ins: ['3\n1 2\n2 3\n', '1\n', '4\n1 2\n1 3\n1 4\n', '5\n1 2\n2 3\n3 4\n4 5\n', '7\n1 2\n1 3\n2 4\n2 5\n3 6\n3 7\n', '2\n1 2\n'] })

t({ lv: 482, concept: 'グラフ: LCAで2頂点間距離', title: '二分上昇LCAで距離クエリ', tags: ['グラフ', '木'], io: '1行目に頂点数 n、続く n-1 行に無向辺 u v、次の行にクエリ数 q、続く q 行に a b が与えられます。', ask: '各クエリの2頂点間の辺数(距離)の総和を出力してください。', h1: 'ダブリングで 2^k 先の親を前計算。', h2: '距離は depth[a]+depth[b]-2·depth[LCA]。', ref: 'from collections import deque\nn=int(input())\ng=[[] for _ in range(n+1)]\nfor _ in range(n-1):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\nLOG=1\nwhile (1<<LOG)<n:\n    LOG+=1\nLOG+=1\nup=[[0]*(n+1) for _ in range(LOG)]\ndepth=[0]*(n+1)\nseen=[False]*(n+1)\nseen[1]=True\ndq=deque([1])\nup[0][1]=1\nwhile dq:\n    x=dq.popleft()\n    for y in g[x]:\n        if not seen[y]:\n            seen[y]=True\n            up[0][y]=x\n            depth[y]=depth[x]+1\n            dq.append(y)\nfor k in range(1,LOG):\n    for v in range(1,n+1):\n        up[k][v]=up[k-1][up[k-1][v]]\ndef lca(a,b):\n    if depth[a]<depth[b]:\n        a,b=b,a\n    d=depth[a]-depth[b]\n    for k in range(LOG):\n        if (d>>k)&1:\n            a=up[k][a]\n    if a==b:\n        return a\n    for k in range(LOG-1,-1,-1):\n        if up[k][a]!=up[k][b]:\n            a=up[k][a]\n            b=up[k][b]\n    return up[0][a]\nq=int(input())\ntotal=0\nfor _ in range(q):\n    a,b=map(int,input().split())\n    l=lca(a,b)\n    total+=depth[a]+depth[b]-2*depth[l]\nprint(total)', tip: 'ダブリングLCAは前計算O(n log n)・各クエリO(log n)。木上の距離計算の定石。', ins: ['3\n1 2\n2 3\n2\n1 3\n1 2\n', '5\n1 2\n1 3\n2 4\n2 5\n2\n4 5\n4 3\n', '2\n1 2\n1\n1 2\n', '4\n1 2\n2 3\n3 4\n1\n1 4\n', '1\n0\n', '3\n1 2\n1 3\n1\n2 3\n'] })

t({ lv: 483, concept: 'データ構造: Union-Findで連結成分', title: 'Union-Findで連結成分数', tags: ['データ構造', 'グラフ'], io: '1行目に n m、続く m 行に無向辺 u v が与えられます。', ask: '連結成分の個数を出力してください。', h1: '辺ごとに2頂点の根を併合する。', h2: '最後に異なる根の数を数える。', ref: 'first=input().split()\nn=int(first[0])\nm=int(first[1])\npar=list(range(n+1))\ndef find(x):\n    while par[x]!=x:\n        par[x]=par[par[x]]\n        x=par[x]\n    return x\nfor _ in range(m):\n    u,v=map(int,input().split())\n    ru=find(u)\n    rv=find(v)\n    if ru!=rv:\n        par[ru]=rv\nprint(len(set(find(i) for i in range(1,n+1))))', tip: 'Union-Find(素集合森)は経路圧縮でほぼO(1)。連結性の動的判定に必須。', ins: ['5 3\n1 2\n2 3\n4 5\n', '3 0\n', '4 4\n1 2\n2 3\n3 4\n4 1\n', '1 0\n', '6 2\n1 2\n3 4\n', '2 1\n1 2\n'] })

t({ lv: 484, concept: 'データ構造: Sparse Tableで区間最小', title: 'Sparse Tableの区間最小クエリ', tags: ['データ構造'], io: '1行目に n q、2行目に n 個の値、続く q 行に l r(0始まり・両端含む)が与えられます。', ask: '各クエリの区間最小値の総和を出力してください。', h1: '2^k 長の最小値テーブルを前計算する。', h2: '区間を重なり許して2ブロックで覆い min を取る。', ref: 'first=input().split()\nn=int(first[0])\nq=int(first[1])\na=list(map(int,input().split()))\nsp=[a[:]]\nk=1\nwhile (1<<k)<=n:\n    prev=sp[k-1]\n    cur=[]\n    for i in range(n-(1<<k)+1):\n        cur.append(min(prev[i],prev[i+(1<<(k-1))]))\n    sp.append(cur)\n    k+=1\ndef query(l,r):\n    j=(r-l+1).bit_length()-1\n    return min(sp[j][l],sp[j][r-(1<<j)+1])\ntotal=0\nfor _ in range(q):\n    l,r=map(int,input().split())\n    total+=query(l,r)\nprint(total)', tip: 'Sparse Tableは更新なし区間minを前計算O(n log n)・クエリO(1)で。冪等演算が前提。', ins: ['5 2\n3 1 4 1 5\n0 4\n1 3\n', '3 1\n5 2 8\n0 2\n', '1 1\n7\n0 0\n', '4 2\n4 3 2 1\n0 1\n2 3\n', '5 1\n9 8 7 6 5\n1 4\n', '6 2\n1 2 3 4 5 6\n0 2\n3 5\n'] })

t({ lv: 485, concept: 'DP: 最大部分長方形和', title: '2次元最大部分長方形の和', tags: ['dp'], io: '1行目に R C、続く R 行に C 個の整数が与えられます。', ask: '任意の部分長方形(連続)の要素和の最大値を出力してください。', h1: '上端・下端を固定して列ごとに圧縮する。', h2: '圧縮した1次元配列でKadaneの最大部分和。', ref: 'first=input().split()\nR=int(first[0])\nC=int(first[1])\nmat=[list(map(int,input().split())) for _ in range(R)]\nbest=None\nfor top in range(R):\n    temp=[0]*C\n    for bottom in range(top,R):\n        for c in range(C):\n            temp[c]+=mat[bottom][c]\n        run=temp[0]\n        cur=temp[0]\n        for c in range(1,C):\n            run=max(temp[c],run+temp[c])\n            cur=max(cur,run)\n        if best is None or cur>best:\n            best=cur\nprint(best)', tip: '2次元最大部分和は「行帯の固定＋列方向Kadane」で O(R^2·C) に落とせる。', ins: ['2 2\n1 2\n3 4\n', '1 1\n-5\n', '2 3\n1 -2 3\n-4 5 -6\n', '3 3\n-1 -1 -1\n-1 -1 -1\n-1 -1 -1\n', '2 2\n-1 2\n3 -4\n', '1 4\n1 2 3 4\n'] })

t({ lv: 486, concept: '幾何: 最大三角形面積', title: '3点で作る最大三角形の面積の2倍', tags: ['幾何'], io: '1行目に点数 n、続く n 行に点 x y が与えられます。', ask: '3点を選んで作る三角形の面積の2倍の最大値を出力してください(3点未満なら0)。', h1: '3点の外積の絶対値が面積の2倍。', h2: '全ての3つ組を調べて最大を取る。', ref: 'n=int(input())\npts=[tuple(map(int,input().split())) for _ in range(n)]\nbest=0\nfor i in range(n):\n    for j in range(i+1,n):\n        for k in range(j+1,n):\n            ax,ay=pts[i]\n            bx,by=pts[j]\n            cx,cy=pts[k]\n            area2=abs((bx-ax)*(cy-ay)-(by-ay)*(cx-ax))\n            if area2>best:\n                best=area2\nprint(best)', tip: '三角形の面積2倍は外積の絶対値。最大三角形の頂点は必ず凸包上にある。', ins: ['3\n0 0\n4 0\n0 3\n', '4\n0 0\n2 0\n2 2\n0 2\n', '2\n0 0\n1 1\n', '3\n0 0\n1 1\n2 2\n', '5\n0 0\n4 0\n4 4\n0 4\n2 2\n', '4\n0 0\n1 0\n0 1\n3 3\n'] })

t({ lv: 487, concept: '幾何: 線分の交差ペア数', title: '交差する線分ペアの数', tags: ['幾何'], io: '1行目に線分数 m、続く m 行に線分の端点 x1 y1 x2 y2 が与えられます。', ask: '互いに交差する(端点での接触も含む)線分ペアの個数を出力してください。', h1: '外積の符号で互いに反対側にあるかを判定する。', h2: '端点が他方の線分上に乗るケースも別途確認する。', ref: 'm=int(input())\nsegs=[tuple(map(int,input().split())) for _ in range(m)]\ndef sgn(x):\n    if x>0:\n        return 1\n    if x<0:\n        return -1\n    return 0\ndef cross(ox,oy,ax,ay,bx,by):\n    return (ax-ox)*(by-oy)-(ay-oy)*(bx-ox)\ndef on_seg(px,py,ax,ay,bx,by):\n    return min(ax,bx)<=px<=max(ax,bx) and min(ay,by)<=py<=max(ay,by)\ndef intersect(s1,s2):\n    ax,ay,bx,by=s1\n    cx,cy,dx,dy=s2\n    d1=sgn(cross(cx,cy,dx,dy,ax,ay))\n    d2=sgn(cross(cx,cy,dx,dy,bx,by))\n    d3=sgn(cross(ax,ay,bx,by,cx,cy))\n    d4=sgn(cross(ax,ay,bx,by,dx,dy))\n    if d1!=d2 and d3!=d4:\n        return True\n    if d1==0 and on_seg(ax,ay,cx,cy,dx,dy):\n        return True\n    if d2==0 and on_seg(bx,by,cx,cy,dx,dy):\n        return True\n    if d3==0 and on_seg(cx,cy,ax,ay,bx,by):\n        return True\n    if d4==0 and on_seg(dx,dy,ax,ay,bx,by):\n        return True\n    return False\ncnt=0\nfor i in range(m):\n    for j in range(i+1,m):\n        if intersect(segs[i],segs[j]):\n            cnt+=1\nprint(cnt)', tip: '線分交差は4つの外積の符号で「互いに反対側か」を見る。共線・端点接触は別判定が要る。', ins: ['3\n0 0 2 2\n0 2 2 0\n3 3 4 4\n', '2\n0 0 1 0\n2 0 3 0\n', '2\n0 0 2 0\n1 0 3 0\n', '3\n0 0 1 1\n1 1 2 2\n0 2 2 0\n', '2\n0 0 0 2\n1 0 1 2\n', '4\n0 0 4 0\n0 0 0 4\n4 0 4 4\n0 4 4 4\n'] })

t({ lv: 488, concept: '幾何: 多角形内部の点の数', title: '多角形に含まれる点の個数', tags: ['幾何'], io: '1行目に頂点数 n、続く n 行に多角形の頂点、次の行にクエリ数 q、続く q 行に点 x y が与えられます。', ask: '多角形の内部または境界にある点の個数を出力してください。', h1: '辺上にあるか先に判定する。', h2: '水平レイを右に飛ばし交差回数の偶奇で内外判定。', ref: 'n=int(input())\npoly=[tuple(map(int,input().split())) for _ in range(n)]\ndef on_seg(px,py,ax,ay,bx,by):\n    cross=(bx-ax)*(py-ay)-(by-ay)*(px-ax)\n    if cross!=0:\n        return False\n    return min(ax,bx)<=px<=max(ax,bx) and min(ay,by)<=py<=max(ay,by)\ndef inside(px,py):\n    for i in range(n):\n        ax,ay=poly[i]\n        bx,by=poly[(i+1)%n]\n        if on_seg(px,py,ax,ay,bx,by):\n            return True\n    cnt=0\n    for i in range(n):\n        ax,ay=poly[i]\n        bx,by=poly[(i+1)%n]\n        if (ay>py)!=(by>py):\n            xint=(bx-ax)*(py-ay)/(by-ay)+ax\n            if px<xint:\n                cnt+=1\n    return cnt%2==1\nq=int(input())\nres=0\nfor _ in range(q):\n    px,py=map(int,input().split())\n    if inside(px,py):\n        res+=1\nprint(res)', tip: '点の内外判定はレイキャスティング。境界上は別途セグメント判定で取りこぼさない。', ins: ['4\n0 0\n4 0\n4 4\n0 4\n3\n2 2\n5 5\n0 0\n', '3\n0 0\n4 0\n0 4\n2\n1 1\n3 3\n', '4\n0 0\n2 0\n2 2\n0 2\n1\n1 1\n', '4\n0 0\n4 0\n4 4\n0 4\n1\n4 2\n', '3\n0 0\n2 0\n1 2\n2\n1 1\n0 2\n', '4\n0 0\n3 0\n3 3\n0 3\n2\n1 1\n2 2\n'] })

t({ lv: 489, concept: '幾何: ピックの定理', title: 'ピックの定理で内部格子点数', tags: ['幾何', '数論'], io: '1行目に頂点数 n、続く n 行に格子点多角形の頂点 x y が与えられます。', ask: '多角形の内部にある格子点の数を出力してください。', h1: '面積の2倍を靴ひもで、境界格子点を辺のgcdで求める。', h2: 'I = A - B/2 + 1 を整数演算で。', ref: 'import math\nn=int(input())\npts=[tuple(map(int,input().split())) for _ in range(n)]\narea2=0\nB=0\nfor i in range(n):\n    x1,y1=pts[i]\n    x2,y2=pts[(i+1)%n]\n    area2+=x1*y2-x2*y1\n    B+=math.gcd(abs(x2-x1),abs(y2-y1))\narea2=abs(area2)\nI=(area2-B+2)//2\nprint(I)', tip: 'ピックの定理 A=I+B/2−1。面積と境界点から内部格子点が整数演算で出る。', ins: ['4\n0 0\n4 0\n4 4\n0 4\n', '3\n0 0\n4 0\n0 4\n', '4\n0 0\n2 0\n2 2\n0 2\n', '3\n0 0\n2 0\n1 2\n', '4\n0 0\n5 0\n5 3\n0 3\n', '3\n0 0\n3 0\n0 3\n'] })

t({ lv: 490, concept: '線形代数: XOR基底の最大値', title: 'XOR基底で部分集合XOR最大', tags: ['bit演算'], io: '1行目に n、2行目に n 個の非負整数が与えられます。', ask: '任意の部分集合のXORで作れる最大値を出力してください。', h1: '上位ビットから掃き出して基底を作る。', h2: '基底を上位から貪欲にXORして最大化。', ref: 'n=int(input())\na=list(map(int,input().split()))\nbasis=[0]*64\nfor x in a:\n    cur=x\n    for i in range(63,-1,-1):\n        if not (cur>>i)&1:\n            continue\n        if basis[i]==0:\n            basis[i]=cur\n            break\n        cur^=basis[i]\nres=0\nfor i in range(63,-1,-1):\n    if (res^basis[i])>res:\n        res^=basis[i]\nprint(res)', tip: 'XOR基底(線形基底)はGF(2)上の掃き出し。最大XORや到達可能集合の判定に使う。', ins: ['3\n1 2 3\n', '2\n5 5\n', '1\n0\n', '4\n8 4 2 1\n', '3\n7 7 7\n', '5\n1 2 4 8 16\n'] })

t({ lv: 491, concept: '線形代数: GF(2)行列の階数', title: 'GF(2)上の行列の階数', tags: ['bit演算'], io: '1行目に r c、続く r 行に c 個の 0/1 が与えられます。', ask: 'GF(2)(mod 2)上での行列の階数を出力してください。', h1: '各行をビットマスクにする。', h2: '列ごとにピボットを立てて他行をXOR消去。', ref: 'first=input().split()\nr=int(first[0])\nc=int(first[1])\nrows=[]\nfor _ in range(r):\n    bits=list(map(int,input().split()))\n    val=0\n    for j in range(c):\n        if bits[j]:\n            val|=(1<<j)\n    rows.append(val)\nrank=0\nfor col in range(c):\n    pivot=-1\n    for i in range(rank,len(rows)):\n        if (rows[i]>>col)&1:\n            pivot=i\n            break\n    if pivot==-1:\n        continue\n    rows[rank],rows[pivot]=rows[pivot],rows[rank]\n    for i in range(len(rows)):\n        if i!=rank and (rows[i]>>col)&1:\n            rows[i]^=rows[rank]\n    rank+=1\nprint(rank)', tip: 'GF(2)のガウス消去は行をビット整数で持つとXOR一発で消去でき高速。', ins: ['2 2\n1 0\n0 1\n', '2 2\n1 1\n1 1\n', '3 3\n1 0 0\n0 1 0\n0 0 1\n', '2 3\n1 1 0\n0 1 1\n', '1 1\n0\n', '3 3\n1 1 0\n1 0 1\n0 1 1\n'] })

t({ lv: 492, concept: '線形代数: 行列式 mod 素数', title: '行列式を素数で割った余り', tags: ['数論'], io: '1行目に n p(p は素数)、続く n 行に n 個の整数が与えられます。', ask: '行列式を p で割った余り(0以上p未満)を出力してください。', h1: 'mod p のガウス消去で上三角化する。', h2: 'ピボットの逆元(フェルマー)で前進消去、対角積が行列式。', ref: 'first=input().split()\nn=int(first[0])\np=int(first[1])\nmat=[[int(x)%p for x in input().split()] for _ in range(n)]\ndet=1\nfor i in range(n):\n    pivot=-1\n    for r in range(i,n):\n        if mat[r][i]%p!=0:\n            pivot=r\n            break\n    if pivot==-1:\n        det=0\n        break\n    if pivot!=i:\n        mat[i],mat[pivot]=mat[pivot],mat[i]\n        det=(-det)%p\n    inv=pow(mat[i][i],p-2,p)\n    det=det*mat[i][i]%p\n    for r in range(i+1,n):\n        factor=mat[r][i]*inv%p\n        for cc in range(i,n):\n            mat[r][cc]=(mat[r][cc]-factor*mat[i][cc])%p\nprint(det%p)', tip: 'mod素数の行列式はフェルマー逆元を使ったガウス消去で。行交換ごとに符号が反転する。', ins: ['2 1000000007\n1 2\n3 4\n', '2 7\n2 3\n1 4\n', '3 1000000007\n1 0 0\n0 1 0\n0 0 1\n', '1 5\n3\n', '2 13\n0 1\n1 0\n', '3 1000000007\n2 0 0\n0 3 0\n0 0 4\n'] })

t({ lv: 493, concept: 'bit演算: グレイコードの逆変換', title: 'グレイコードから元の整数へ', tags: ['bit演算'], io: 'グレイコード値 g が1行で与えられます。', ask: 'g に対応する元の整数(逆グレイ変換)を出力してください。', h1: '上位から自分自身を右シフトしながらXOR。', h2: 'n ^= g; g >>= 1 を g が0になるまで。', ref: 'g=int(input())\nn=0\nwhile g>0:\n    n^=g\n    g>>=1\nprint(n)', tip: 'グレイコード変換 g=n^(n>>1) の逆は、上位ビットから累積XORで復元できる。', ins: ['7\n', '0\n', '1\n', '15\n', '10\n', '2\n'] })

t({ lv: 494, concept: '組合せ: 順列の辞書順位', title: '順列の辞書順ランク', tags: ['数え上げ'], io: '1行目に n、2行目に 1..n の順列が与えられます。', ask: 'その順列が辞書順で何番目か(0始まり)を出力してください。', h1: '各位置で「残りの中で何番目に小さいか」を数える。', h2: 'その順位に (残り個数)! を掛けて足す。', ref: 'n=int(input())\nperm=list(map(int,input().split()))\nfact=[1]*(n+1)\nfor i in range(1,n+1):\n    fact[i]=fact[i-1]*i\nrank=0\navailable=sorted(perm)\nfor i in range(n):\n    idx=available.index(perm[i])\n    rank+=idx*fact[n-1-i]\n    available.pop(idx)\nprint(rank)', tip: '順列のランク付けは階乗進法(factorial number system)そのもの。', ins: ['3\n1 2 3\n', '3\n3 2 1\n', '1\n1\n', '4\n2 1 4 3\n', '3\n2 1 3\n', '4\n1 2 3 4\n'] })

t({ lv: 495, concept: 'シミュレーション: ヨセフス問題', title: 'ヨセフス問題の生存者', tags: ['数学'], io: 'n k が空白区切りで与えられます。', ask: '0..n-1 の n 人が輪になり k 人ごとに脱落するとき、最後に残る人の番号(0始まり)を出力してください。', h1: 'J(1)=0 から始める漸化式。', h2: 'J(i)=(J(i-1)+k) mod i。', ref: 'n,k=map(int,input().split())\nres=0\nfor i in range(2,n+1):\n    res=(res+k)%i\nprint(res)', tip: 'ヨセフス問題は人数を1つずつ増やす漸化式で O(n) に解ける。', ins: ['7 3\n', '1 1\n', '5 2\n', '10 1\n', '6 5\n', '41 3\n'] })

t({ lv: 496, concept: 'マッチング: 安定結婚問題', title: 'Gale-Shapleyの安定マッチング', tags: ['グラフ'], io: '1行目に n、続く n 行に各男の女への選好(女番号1..nを優先順)、続く n 行に各女の男への選好が与えられます。', ask: '男最適の安定マッチングで各男(1..n)が結ばれる女の番号を空白区切りで出力してください。', h1: '自由な男が次点の女に求婚していく。', h2: '女は今の相手より好きなら乗り換える(Gale-Shapley)。', ref: 'n=int(input())\nmen_pref=[list(map(int,input().split())) for _ in range(n)]\nwomen_pref=[list(map(int,input().split())) for _ in range(n)]\nwomen_rank=[[0]*(n+1) for _ in range(n)]\nfor w in range(n):\n    for r,m in enumerate(women_pref[w]):\n        women_rank[w][m]=r\nnext_prop=[0]*n\nmatch_w=[-1]*n\nmatch_m=[-1]*n\nfree=list(range(n))\nwhile free:\n    m=free.pop()\n    w=men_pref[m][next_prop[m]]-1\n    next_prop[m]+=1\n    if match_w[w]==-1:\n        match_w[w]=m\n        match_m[m]=w\n    else:\n        cur=match_w[w]\n        if women_rank[w][m+1]<women_rank[w][cur+1]:\n            match_w[w]=m\n            match_m[m]=w\n            match_m[cur]=-1\n            free.append(cur)\n        else:\n            free.append(m)\nprint(*[match_m[m]+1 for m in range(n)])', tip: 'Gale-Shapleyは必ず安定マッチングを返し、求婚する側に最適な解になる。', ins: ['2\n1 2\n2 1\n1 2\n2 1\n', '2\n2 1\n2 1\n1 2\n1 2\n', '1\n1\n1\n', '3\n1 2 3\n1 2 3\n1 2 3\n1 2 3\n1 2 3\n1 2 3\n', '2\n1 2\n1 2\n2 1\n2 1\n', '3\n2 1 3\n1 2 3\n1 2 3\n2 1 3\n1 2 3\n1 2 3\n'] })

t({ lv: 497, concept: '文字列: 2つの単語がどちらも現れる行', title: '二つの言葉が同居する行', tags: ['文字列', 'ハッシュ'], io: '1行目に行数 n、続く n 行に空白区切りの単語列、最後の1行に単語 a と b が空白区切りで与えられます。', ask: 'a と b の両方が現れる行の番号(1始まり)を昇順に空白区切りで出力してください。1行も無ければ none を出力してください。', h1: '各行を集合にしておくと「その単語を含むか」が一発で判定できる。', h2: '行番号は0始まりの添字に1を足す。', ref: 'n=int(input())\nrows=[set(input().split()) for _ in range(n)]\na,b=input().split()\nres=[str(i+1) for i in range(n) if a in rows[i] and b in rows[i]]\nprint(" ".join(res) if res else "none")', tip: '転置インデックス(同レベル既出)を先に張り、2語の行番号集合の積を取る道もある。検索が1回だけならこの「行を集合にして総当たり」で十分速く、問い合わせが何度も来るなら索引が効いてくる——前処理をどこまでやるかは回数で決まる。', ins: ['3\nred blue green\nblue yellow\nred green blue\nred blue\n', '2\ncat dog\ndog bird\ncat bird\n', '1\na b c\na c\n', '4\nx y\ny z\nx z\nx y z\nx y\n', '2\napple pie\napple pie\napple pie\n', '3\none\ntwo\nthree\none two\n'] })

t({ lv: 498, concept: 'スタック: ヒストグラム最大長方形', title: 'ヒストグラム中の最大長方形', tags: ['スタック'], io: '1行目に n、2行目に n 個の高さが与えられます。', ask: '連続するバーで作れる最大の長方形の面積を出力してください。', h1: '高さが減る位置で確定する単調増加スタック。', h2: 'pop した高さ×(その左右に広がる幅)で面積。', ref: 'n=int(input())\nh=list(map(int,input().split()))\nh.append(0)\nstack=[]\nbest=0\nfor i in range(len(h)):\n    while stack and h[stack[-1]]>=h[i]:\n        height=h[stack.pop()]\n        width=i if not stack else i-stack[-1]-1\n        if height*width>best:\n            best=height*width\n    stack.append(i)\nprint(best)', tip: '単調スタックで各バーを高さとする最大幅を線形時間で求める典型。末尾に番兵0を置くと処理が楽。', ins: ['6\n2 1 5 6 2 3\n', '1\n5\n', '3\n2 2 2\n', '4\n1 2 3 4\n', '5\n5 4 3 2 1\n', '3\n0 0 0\n'] })

t({ lv: 499, concept: 'DP: 最大正方形', title: '0/1行列の最大全1正方形', tags: ['dp'], io: '1行目に R C、続く R 行に C 個の 0/1 が与えられます。', ask: 'すべて1で埋まった最大正方形の一辺の長さを出力してください。', h1: 'dp[i][j]=その位置を右下とする最大正方形の辺。', h2: '1なら上・左・左上の min + 1。', ref: 'first=input().split()\nR=int(first[0])\nC=int(first[1])\nmat=[list(map(int,input().split())) for _ in range(R)]\ndp=[[0]*C for _ in range(R)]\nbest=0\nfor i in range(R):\n    for j in range(C):\n        if mat[i][j]==1:\n            if i==0 or j==0:\n                dp[i][j]=1\n            else:\n                dp[i][j]=min(dp[i-1][j],dp[i][j-1],dp[i-1][j-1])+1\n            if dp[i][j]>best:\n                best=dp[i][j]\nprint(best)', tip: '最大正方形は「右下を固定し3方向の min+1」で表せる古典DP。', ins: ['3 3\n1 1 0\n1 1 1\n0 1 1\n', '2 2\n1 1\n1 1\n', '2 2\n0 0\n0 0\n', '1 4\n1 1 1 1\n', '3 3\n1 0 1\n0 1 0\n1 0 1\n', '4 4\n1 1 1 1\n1 1 1 1\n1 1 1 0\n1 1 1 1\n'] })

export const CATALOG = TASKS
