// 生成タスク 第63波：各レベル2問化フェーズ(18)。lv741〜749, lv751〜765 に2問目を追加。
// bit/窓/累積和/ヒープ/ソート帯。重複なし・決定的・採点一意。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 741, concept: 'bit演算: 連続部分配列のXOR最大', title: '連続区間のXORの最大値', tags: ['bit演算'], io: '非負整数の列が1行で空白区切りで与えられます。', ask: '連続部分配列のXOR(全要素のビット排他的論理和)の最大値を出力してください。', h1: '区間XORは接頭辞XORの2点で書ける。', h2: 'prefix[j]⊕prefix[i] の最大化。全ペアを試すか、大規模ではビットのトライ木で最良の相方を探す。', ref: 'a=list(map(int,input().split()))\npre=[0]\nfor x in a:\n    pre.append(pre[-1]^x)\nbest=0\nn=len(pre)\nfor i in range(n):\n    for j in range(i+1,n):\n        v=pre[i]^pre[j]\n        if v>best:\n            best=v\nprint(best)', tip: '和の区間問題で使う「接頭辞の2点差」がXORでもそのまま通用する(⊕は自分が逆元)。トライ木で相方を貪欲に選べばO(nビット長)になる。', ins: ['1 2 3 4\n', '8 1 2 12\n', '5\n', '0 0 0\n', '3 8 2 6 4\n', '1 1 1 1\n'] })

t({ lv: 742, concept: 'bit演算: 2要素の最大AND', title: 'ANDが最大になるペア', tags: ['bit演算'], io: '非負整数の列(2個以上)が1行で空白区切りで与えられます。', ask: '2つの要素のAND(ビット論理積)の最大値を出力してください。', h1: '上位ビットから貪欲に決める。', h2: 'そのビットを立てられる(候補内で該当ビットが1の数が2個以上ある)なら確定し、候補を絞る。', ref: 'a=list(map(int,input().split()))\ncand=a[:]\nres=0\nfor b in range(29,-1,-1):\n    hi=[x for x in cand if x>>b&1]\n    if len(hi)>=2:\n        res|=1<<b\n        cand=hi\nprint(res)', tip: '「上位ビットを立てられるなら必ず立てる」貪欲は、上位1ビットが下位全ビットの合計より重いことから正当化される。XOR最大のトライ木と対をなす、AND版の絞り込み。', ins: ['4 8 6 2\n', '1 2 3\n', '7 7\n', '0 0\n', '5 10 12\n', '3 5 6 9\n'] })

t({ lv: 743, concept: 'BFS: 川渡りパズルの最小回数', title: '全員を対岸へ運ぶ最少の渡し', tags: ['BFS', 'bit演算'], io: '1行目に 荷物の数 n と禁止ペア数 m (n≤4)、続く m 行に「農夫がいない岸で一緒に置けないペア a b」が与えられます。', ask: '農夫はボートで荷物を1つまで載せて岸を往復します。全ての荷物を対岸へ運ぶ最小の渡河回数を出力してください。不可能なら -1。', h1: '状態は「各荷物がどちらの岸か+農夫の位置」。', h2: 'ビットマスク+農夫の0/1でBFS。移動後、農夫のいない岸に禁止ペアが揃っていたら無効。', ref: 'from collections import deque\nn,m=map(int,input().split())\nbad=[tuple(map(int,input().split())) for _ in range(m)]\ndef ok(mask,farmer):\n    for a,b in bad:\n        sa=mask>>(a-1)&1\n        sb=mask>>(b-1)&1\n        if sa==sb and sa!=farmer:\n            return False\n    return True\nstart=(0,0)\ngoal=((1<<n)-1,1)\ndist={start:0}\nq=deque([start])\nans=-1\nwhile q:\n    mask,f=q.popleft()\n    if (mask,f)==goal:\n        ans=dist[(mask,f)]\n        break\n    moves=[None]+[i for i in range(n) if mask>>i&1==f]\n    for it in moves:\n        nm=mask\n        if it is not None:\n            nm=mask^(1<<it)\n        nf=1-f\n        if ok(nm,nf) and (nm,nf) not in dist:\n            dist[(nm,nf)]=dist[(mask,f)]+1\n            q.append((nm,nf))\nprint(ans)', tip: '狼・ヤギ・キャベツの古典は n=3, 禁止{(狼,ヤギ),(ヤギ,キャベツ)} で答え7。パズルの「詰み状態の除外」を遷移でなく状態の妥当性関数に置くと実装が締まる。', ins: ['3 2\n1 2\n2 3\n', '1 0\n', '2 1\n1 2\n', '3 3\n1 2\n2 3\n1 3\n', '2 0\n', '4 2\n1 2\n3 4\n'] })

t({ lv: 744, concept: '二点法: 前後から取る等しい山分け', title: '前と後ろから同じ重さだけ取る', tags: ['二点法'], io: '正整数の列が1行で空白区切りで与えられます。', ask: '先頭からいくつか、末尾からいくつか(重ならない)取り、両者の合計が等しくなるようにするとき、取れる個数の合計の最大を出力してください(取らないのも合計0で等しいとみなす)。', h1: '左右の取り分の和を持ち、二点法で釣り合わせる。', h2: '左が軽ければ左を増やし、右が軽ければ右を増やす。等しくなった瞬間を記録する。', ref: 'a=list(map(int,input().split()))\nn=len(a)\ni=0\nj=n\nsl=0\nsr=0\nbest=0\nwhile i<j:\n    if sl==sr:\n        best=i+(n-j)\n        sl+=a[i]\n        i+=1\n    elif sl<sr:\n        sl+=a[i]\n        i+=1\n    else:\n        j-=1\n        sr+=a[j]\nif sl==sr and i<=j:\n    best=i+(n-j)\nprint(best)', tip: '両側から伸ばす二点法は「軽い側を進める」だけで等号の機会を漏らさない。キャンディー山分け(LC 1877系)として知られる形。', ins: ['3 2 1 1 4\n', '1 1 1 1\n', '5 4\n', '1 2 3\n', '2 2\n', '1 1 2 1 1\n'] })

t({ lv: 745, concept: 'バックトラック: 相異なる片への最大分割', title: '全部違う破片に切る最大数', tags: ['バックトラック', '再帰'], io: '英小文字の文字列(8文字以下)が1行で与えられます。', ask: '文字列を連続した破片に切り、全ての破片が相異なるようにするときの破片数の最大を出力してください。', h1: '先頭からどこまでを次の破片にするか総当たり。', h2: '使用済みの破片集合を持って再帰し、未使用の切り出しだけ許す。', ref: 's=input()\nn=len(s)\nbest=0\ndef go(i,used):\n    global best\n    if i==n:\n        if len(used)>best:\n            best=len(used)\n        return\n    for j in range(i+1,n+1):\n        p=s[i:j]\n        if p not in used:\n            used.add(p)\n            go(j,used)\n            used.discard(p)\ngo(0,set())\nprint(best)', tip: '「短い破片から試す」と枝刈りが効きやすい。分割系バックトラックは(位置, 使用集合)が状態で、集合の追加と削除を対で書くのが作法。', ins: ['ababccc\n', 'aba\n', 'aa\n', 'abcdef\n', 'aaaa\n', 'ab\n'] })

t({ lv: 746, concept: '全探索: 1回の区間反転で辞書順最小', title: '一度だけ区間を裏返して最小の文字列', tags: ['全探索', '文字列'], io: '英小文字の文字列が1行で与えられます。', ask: '連続する区間を1箇所だけ選んで反転(しなくてもよい)してできる文字列のうち、辞書順最小のものを出力してください。', h1: '区間の選び方は O(n²) 通りしかない。', h2: '全部試して最小を取る。大きな n では「最初に下がる位置」から貪欲に決める。', ref: 's=input()\nbest=s\nn=len(s)\nfor i in range(n):\n    for j in range(i+1,n+1):\n        c=s[:i]+s[i:j][::-1]+s[j:]\n        if c<best:\n            best=c\nprint(best)', tip: 'まず全探索で正解の形を観察し、それから貪欲(最初の逆転位置から最長に伸ばす)へ進むのが安全な開発順。答え合わせ用の遅い正解は残しておく価値がある。', ins: ['dcba\n', 'abab\n', 'aaa\n', 'ba\n', 'acb\n', 'cabba\n'] })

t({ lv: 747, concept: '数え上げ: 山型の3つ組の数', title: '真ん中が一番大きい3つ組', tags: ['数え上げ'], io: '相異なる整数の列が1行で空白区切りで与えられます。', ask: 'i<j<k で a[j] が3つの中で最大となる組の個数を出力してください。', h1: '真ん中 j を固定する。', h2: '左にある小さい値の個数 × 右にある小さい値の個数 を足し合わせる。', ref: 'a=list(map(int,input().split()))\nn=len(a)\ntotal=0\nfor j in range(n):\n    L=sum(1 for i in range(j) if a[i]<a[j])\n    R=sum(1 for k in range(j+1,n) if a[k]<a[j])\n    total+=L*R\nprint(total)', tip: '3つ組の数え上げは「真ん中を固定して左右の積」が定石。BITで左右の小さい個数を前計算すればO(n log n)に落ちる。', ins: ['1 3 2\n', '1 2 3\n', '3 2 1\n', '2 5 1 4 3\n', '1 2\n', '4 7 2 6 1\n'] })

t({ lv: 748, concept: '貪欲: 任意スワップで交互01にする最小回数', title: 'スワップで交互の01列を作る', tags: ['貪欲'], io: '0/1の文字列が1行で与えられます。', ask: '任意の2文字の交換だけで「隣どうしが必ず異なる」文字列にするときの最小交換回数を出力してください。不可能なら -1。', h1: '0と1の個数の差が2以上なら不可能。', h2: '目標形(0101…か1010…)とのずれのうち「1が偶数位置にあるべき箇所」…両形とのミスマッチ数÷2 の小さい方(個数が同じときは両方、違うときは多い方が先頭)。', ref: 's=input()\nn=len(s)\nones=s.count("1")\nzeros=n-ones\nif abs(ones-zeros)>1:\n    print(-1)\nelse:\n    def cost(first):\n        mis=sum(1 for i,c in enumerate(s) if int(c)!=(first+i)%2)\n        return mis//2\n    if ones>zeros:\n        print(cost(1))\n    elif zeros>ones:\n        print(cost(0))\n    else:\n        print(min(cost(0),cost(1)))', tip: '書き換えなら「ミスマッチ数」、交換なら「ミスマッチ数÷2」(1回の交換が2箇所を同時に直す)。操作の“修復力”が回数の分母になる。', ins: ['111000\n', '010\n', '1110\n', '10\n', '11\n', '100110\n'] })

t({ lv: 749, concept: 'DP: 無料券つき階段のコスト最小', title: '無料券k枚で階段を安く上る', tags: ['DP'], io: '1行目に無料券の枚数 k、2行目に各段のコストが与えられます。0段目から出発し、1歩で1段か2段上り、最後の段の先(ゴール)まで到達します。', ask: '踏んだ段のコストを支払います(無料券を使えばその段は0円)。合計の最小を出力してください。', h1: '状態は(位置, 残り券)。', h2: '各段で「払う/券を使う」の2択、遷移は1段か2段。', ref: 'k=int(input())\nc=list(map(int,input().split()))\nn=len(c)\nINF=float("inf")\ndp=[[INF]*(k+1) for _ in range(n+1)]\nfor j in range(k+1):\n    dp[0][j]=0\nfor i in range(1,n+1):\n    for j in range(k+1):\n        pay=min(dp[i-1][j],dp[i-2][j] if i>=2 else INF)\n        if pay<INF:\n            dp[i][j]=min(dp[i][j],pay+c[i-1])\n        if j>0:\n            free=min(dp[i-1][j-1],dp[i-2][j-1] if i>=2 else INF)\n            if free<INF:\n                dp[i][j]=min(dp[i][j],free)\nans=min(min(dp[n]),min(dp[n-1]) if n>=1 else INF)\nprint(ans)', tip: '「クーポン・スキップ・無敵時間」の類は残回数を次元に足すのが定石。ゴールは段nか段n−1のどちらからでも越えられる点に注意。', ins: ['1\n10 15 20\n', '0\n10 15 20\n', '2\n1 100 1 100\n', '1\n5\n', '3\n9 9 9\n', '1\n1 2 3 4 5\n'] })

t({ lv: 751, concept: '累積和: 合計が閾値超えの窓の数', title: '売上が目標を超えた期間を数える', tags: ['累積和'], io: '1行目に 窓の長さ k と閾値 T、2行目に数列が与えられます。', ask: '長さ k の連続区間のうち、合計が T を厳密に超えるものの個数を出力してください。', h1: '窓の和は「1つ入れて1つ出す」で更新できる。', h2: '最初の窓だけ足し、以降はO(1)ずつずらす。', ref: 'k,t=map(int,input().split())\na=list(map(int,input().split()))\ns=sum(a[:k])\ncnt=1 if s>t else 0\nfor i in range(k,len(a)):\n    s+=a[i]-a[i-k]\n    if s>t:\n        cnt+=1\nprint(cnt)', tip: '固定長の窓は累積和よりも「差分更新」の方が速くて簡潔。移動平均・移動合計・移動最大(こちらはデック)と、窓もの三点セットで覚える。', ins: ['3 5\n1 2 3 4 5\n', '1 0\n1 -1 2\n', '2 10\n5 5 5 5\n', '2 9\n5 5 5\n', '4 0\n-1 -1 -1 -1 -1\n', '1 100\n50\n'] })

t({ lv: 752, concept: 'いもす法: 等差数列の重ね掛け', title: '坂道の重ね塗りの最大値', tags: ['累積和'], io: '1行目に 長さ n とクエリ数 q、続く q 行に「l r a d」(位置 l..r に a, a+d, a+2d, … を加算、1始まり)が与えられます。', ask: '全クエリ適用後の配列の最大値を出力してください。', h1: '定数の区間加算は差分1回、等差の加算は?', h2: '「傾き」と「切片」を別々の差分配列で管理する。位置 i の値は 切片累積 + i×傾き累積。', ref: 'n,q=map(int,input().split())\nc1=[0]*(n+2)\nc2=[0]*(n+2)\nfor _ in range(q):\n    l,r,a,d=map(int,input().split())\n    base=a-l*d\n    c1[l]+=base\n    c1[r+1]-=base\n    c2[l]+=d\n    c2[r+1]-=d\ns1=0\ns2=0\nbest=None\nfor i in range(1,n+1):\n    s1+=c1[i]\n    s2+=c2[i]\n    v=s1+i*s2\n    if best is None or v>best:\n        best=v\nprint(best)', tip: '等差の重ね掛けは「値=切片+位置×傾き」に分解すると差分配列2本で済む(2階差分いもす)。多項式の次数が上がるたび配列を1本足せばよい。', ins: ['5 1\n1 5 1 1\n', '4 2\n1 2 5 0\n2 4 1 2\n', '3 1\n2 3 10 -5\n', '5 2\n1 3 1 1\n3 5 1 1\n', '1 1\n1 1 7 3\n', '6 3\n1 6 0 1\n1 6 5 0\n2 3 100 -1\n'] })

t({ lv: 753, concept: '累積和: 行と列の和が最大の交点', title: '縦横の合計が最大になるマス', tags: ['累積和'], io: '1行目に H W、続く H 行に行列が与えられます。', ask: '各マス (i,j) について「i行の合計 + j列の合計 − そのマスの値」を計算し、その最大値を出力してください。', h1: '行の合計と列の合計を先に配列にする。', h2: '各マスはO(1)で評価できる。', ref: 'h,w=map(int,input().split())\ng=[list(map(int,input().split())) for _ in range(h)]\nrows=[sum(r) for r in g]\ncols=[sum(g[i][j] for i in range(h)) for j in range(w)]\nprint(max(rows[i]+cols[j]-g[i][j] for i in range(h) for j in range(w)))', tip: '十字の合計は「行和+列和−交点」の包除で1発。前計算とO(1)評価の分業は、2次元集計の一番小さな成功体験になる。', ins: ['2 2\n1 2\n3 4\n', '1 3\n5 -1 2\n', '3 3\n1 1 1\n1 9 1\n1 1 1\n', '2 3\n-1 -2 -3\n-4 -5 -6\n', '1 1\n7\n', '3 2\n2 0\n0 2\n2 0\n'] })

t({ lv: 754, concept: 'しゃくとり: 和がk以下の区間の数', title: '合計がk以下の区間を数える', tags: ['しゃくとり'], io: '1行目に k、2行目に正整数列が与えられます。', ask: '要素の合計が k 以下の空でない連続部分配列の個数を出力してください。', h1: '右端を固定すると左端は単調に動く。', h2: '窓 [l,r] の和がkを超えたら l を進める。各 r で r−l+1 個を加算。', ref: 'k=int(input())\na=list(map(int,input().split()))\nl=0\ns=0\ncnt=0\nfor r,x in enumerate(a):\n    s+=x\n    while s>k:\n        s-=a[l]\n        l+=1\n    cnt+=r-l+1\nprint(cnt)', tip: '「右端ごとに左端の可動域の幅を足す」のがしゃくとり数え上げの心臓部。正数限定という前提が単調性を保証している。', ins: ['5\n1 2 3\n', '3\n1 1 1 1\n', '1\n2 3\n', '100\n1 2 3\n', '2\n2 2 2\n', '4\n1 4 1\n'] })

t({ lv: 755, concept: 'しゃくとり: 各値2回までの最長区間', title: 'どの値も2回までの最長区間', tags: ['しゃくとり'], io: '整数列が1行で空白区切りで与えられます。', ask: 'どの値も高々2回しか現れない連続区間の最大の長さを出力してください。', h1: '3回目が現れたら左を縮める。', h2: 'Counterで窓内の頻度を保ち、違反が消えるまで左端を進める。', ref: 'from collections import Counter\na=list(map(int,input().split()))\ncnt=Counter()\nl=0\nbest=0\nfor r,x in enumerate(a):\n    cnt[x]+=1\n    while cnt[x]>2:\n        cnt[a[l]]-=1\n        l+=1\n    if r-l+1>best:\n        best=r-l+1\nprint(best)', tip: '「k種以下」「重複なし」「各値m回以下」は全部同じ骨格で、違反条件のwhileだけが違う。しゃくとりのテンプレ性が最もよく見える一群。', ins: ['1 2 1 2 1\n', '1 1 1\n', '1 2 3\n', '5 5\n', '1 2 1 1 2\n', '3 3 4 3 4 4\n'] })

t({ lv: 756, concept: 'ハッシュ: 最初に繰り返された値', title: '最初にダブった値はどれか', tags: ['ハッシュ'], io: '整数列が1行で空白区切りで与えられます(重複が少なくとも1つあります)。', ask: '左から見て「2回目の出現」が最も早い値を出力してください。', h1: '見た値を集合に入れながら走査する。', h2: '既に集合にある値に出会った瞬間、それが答え。', ref: 'a=list(map(int,input().split()))\nseen=set()\nfor x in a:\n    if x in seen:\n        print(x)\n        break\n    seen.add(x)', tip: '「最初の重複」は全部数えてから探すのでなく、見つけた瞬間にbreakするのが正しい。setのO(1)照会がこの早期終了を支えている。', ins: ['2 1 3 5 3 2\n', '1 1\n', '2 2 1 1\n', '5 4 3 4 5\n', '1 2 3 1\n', '7 8 9 9\n'] })

t({ lv: 757, concept: 'ハッシュ: ずらして一致する単語のグループ', title: 'シフトすると同じ単語をまとめる', tags: ['ハッシュ', '文字列'], io: '英小文字の単語が1行で空白区切りで与えられます。', ask: '各文字を同じ量だけアルファベット上でずらす(zの次はaに戻る)と一致する単語どうしをグループにまとめ、グループ数を出力してください。', h1: 'ずらしても変わらない「正規形」を作る。', h2: '隣接文字の差(mod 26)の列をキーにすれば、シフト同値が同じキーになる。', ref: 'ws=input().split()\ngroups=set()\nfor w in ws:\n    key=tuple((ord(w[i+1])-ord(w[i]))%26 for i in range(len(w)-1))\n    groups.add((len(w),key))\nprint(len(groups))', tip: '同値類の判定は「代表元(正規形)への写像」を設計する問題。差分列は平行移動を消す正規形の典型で、図形の形状照合でも同じ発想を使う。', ins: ['abc bcd xyz az ba a z\n', 'aa bb cc\n', 'abc acd\n', 'a\n', 'ab yz za\n', 'abcd bcde cdef xyza\n'] })

t({ lv: 758, concept: 'ハッシュ: ずらして重ねる最大一致数', title: '2つの列を最も合う位置で重ねる', tags: ['ハッシュ'], io: '1行目と2行目に同じ長さの整数列が与えられます。', ask: '2列目を右へ d (0以上、列長未満) だけずらして重ねたとき(はみ出しは比較しない)、値が一致する位置の数の最大を出力してください。', h1: '各ずらし幅を全部試す。', h2: 'ずらし d では a[i+d] と b[i] を比較する。', ref: 'a=list(map(int,input().split()))\nb=list(map(int,input().split()))\nn=len(a)\nbest=0\nfor d in range(n):\n    c=sum(1 for i in range(n-d) if a[i+d]==b[i])\n    if c>best:\n        best=c\nprint(best)', tip: '信号の相互相関(アラインメント)の離散版。値の種類が少なければ「値→出現位置リスト」からずらし幅ごとの一致数を票読みしてO(出現ペア数)にできる。', ins: ['1 2 3 4\n9 1 2 3\n', '1 1 1\n1 1 1\n', '1 2 3\n4 5 6\n', '5 3 5 3\n3 5 3 5\n', '2\n2\n', '1 2 1 2 1\n2 1 2 1 2\n'] })

t({ lv: 759, concept: 'ソート: 同点を考慮した順位表', title: '同点は同順位の順位表', tags: ['ソート'], io: '得点の列が1行で空白区切りで与えられます。', ask: '各人の順位(自分より厳密に高い得点の人数+1。同点は同順位で、次の順位は飛ぶ)を、入力の順に空白区切りで出力してください。', h1: '順位は「自分より上の人数」で決まる。', h2: 'ソート済みリストへの二分探索か、得点→順位の辞書を先に作る。', ref: 'a=list(map(int,input().split()))\ns=sorted(a,reverse=True)\nrank={}\nfor i,v in enumerate(s):\n    if v not in rank:\n        rank[v]=i+1\nprint(*[rank[v] for v in a])', tip: '「1,2,2,4」と順位が飛ぶ standard competition ranking の実装。降順ソートで最初に現れた位置が順位、という辞書の初出だけ採用する書き方が簡潔。', ins: ['100 90 90 80\n', '50 50 50\n', '1 2 3\n', '7\n', '10 20 10 30\n', '5 4 3 2 1\n'] })

t({ lv: 760, concept: 'ヒープ: 最大を取ってはceil3分の1に', title: '砕きながらk回集める最大', tags: ['ヒープ'], io: '1行目に操作回数 k、2行目に正整数の山の列が与えられます。', ask: '毎回、最大の山を選んでその値を得点に加え、山を「3で割って切り上げた値」に置き換えます。k 回でスコアの最大を出力してください。', h1: '常に最大を選ぶ貪欲でよい。', h2: '最大ヒープ(符号反転)でk回、pop→加算→push。', ref: 'import heapq\nk=int(input())\na=[-x for x in map(int,input().split())]\nheapq.heapify(a)\nscore=0\nfor _ in range(k):\n    x=-heapq.heappop(a)\n    score+=x\n    heapq.heappush(a,-((x+2)//3))\nprint(score)', tip: '取るたびに減衰する資源は「今一番大きいものから」の貪欲が交換論法で最適になる。切り上げ÷3は (x+2)//3 の整数イディオムで。', ins: ['3\n10 10 10\n', '2\n1 10 3 3 3\n', '1\n5 4\n', '4\n9\n', '2\n2 2\n', '5\n27 9\n'] })

t({ lv: 761, concept: 'ヒープ: k窓口の完了時刻', title: '窓口k個で全員さばく時刻', tags: ['ヒープ'], io: '1行目に窓口の数 k、2行目に並んでいる客の所要時間の列(先頭から順に案内)が与えられます。', ask: '時刻0から、空いた窓口に先頭の客を案内していきます(同時に空いたら番号の小さい窓口へ)。全員の処理が終わる時刻を出力してください。', h1: '各窓口の「空く時刻」を管理する。', h2: '(空く時刻, 窓口番号) の最小ヒープから取り出して客を割り当てる。', ref: 'import heapq\nk=int(input())\na=list(map(int,input().split()))\nh=[(0,i) for i in range(k)]\nheapq.heapify(h)\nend=0\nfor t in a:\n    free,i=heapq.heappop(h)\n    free+=t\n    if free>end:\n        end=free\n    heapq.heappush(h,(free,i))\nprint(end)', tip: '「最も早く空く資源に次の仕事」はリスト・スケジューリングの基本形。タプルの第2要素(番号)がタイブレークを機械的に決めてくれる。', ins: ['2\n3 1 4 1 5\n', '1\n2 3 4\n', '3\n5 5 5\n', '2\n10 1 1 1\n', '4\n1 2 3\n', '2\n7\n'] })

t({ lv: 762, concept: '区間: 連続範囲へのまとめ表示', title: '数の集まりを範囲表記に圧縮', tags: ['区間'], io: '昇順で相異なる整数の列が1行で空白区切りで与えられます。', ask: '連続している部分を「a-b」、単独の数を「a」と表し、これらをカンマ区切りで1行に出力してください。', h1: '連続の切れ目を探す。', h2: '開始値を覚え、次が+1でなくなったら区間を確定する。', ref: 'a=list(map(int,input().split()))\nres=[]\ni=0\nn=len(a)\nwhile i<n:\n    j=i\n    while j+1<n and a[j+1]==a[j]+1:\n        j+=1\n    if i==j:\n        res.append(str(a[i]))\n    else:\n        res.append(f"{a[i]}-{a[j]}")\n    i=j+1\nprint(",".join(res))', tip: 'ページ指定「1-3,5,7-9」の生成そのもの。ランレングス圧縮の「値の繰り返し」を「+1の連鎖」に替えただけ、と気づくと実装が写経になる。', ins: ['0 1 2 4 5 7\n', '1 3 5\n', '1 2 3 4\n', '7\n', '-2 -1 0 3\n', '1 2 4 5 6 9\n'] })

t({ lv: 763, concept: 'ソート: ペアの差の総和の最小化', title: '2人組の実力差の合計を最小に', tags: ['ソート', '貪欲'], io: '偶数個の整数列が1行で空白区切りで与えられます。', ask: '全員を2人ずつの組に分け、各組の差(絶対値)の合計を最小化した値を出力してください。', h1: 'ソートして考える。', h2: '隣どうしを組にするのが最適(交差する組み方は交換で改善できる)。', ref: 'a=sorted(map(int,input().split()))\nprint(sum(a[i+1]-a[i] for i in range(0,len(a),2)))', tip: '「交差をほどくと必ず得」の交換論法で隣接ペアが最適と示せる。差の合計・最大差の最小化・和の均等化で最適な組み方が変わるのも面白い比較。', ins: ['1 3 2 4\n', '5 5\n', '1 10 2 9\n', '4 3 2 1\n', '0 0 0 0\n', '1 2 8 9 10 11\n'] })

t({ lv: 764, concept: '数え上げ: 並べ替えの偶奇', title: 'この並びは偶置換か奇置換か', tags: ['数え上げ'], io: '1..n の順列が1行で空白区切りで与えられます。', ask: '隣接交換で昇順に直すときの最小交換回数(転倒数)の偶奇を、even / odd で出力してください。', h1: '転倒数そのものは数えなくても偶奇だけなら別の方法もある。', h2: 'サイクル分解して「n−サイクル数」の偶奇でも、転倒数を数えて%2でもよい。', ref: 'a=list(map(int,input().split()))\nn=len(a)\ninv=0\nfor i in range(n):\n    for j in range(i+1,n):\n        if a[i]>a[j]:\n            inv+=1\nprint("even" if inv%2==0 else "odd")', tip: '置換の符号(偶奇)は15パズルの可解性、行列式の展開の符号、交代群の定義と、あちこちで主役になる不変量。どんな交換手順でも偶奇は変わらない。', ins: ['1 2 3\n', '2 1 3\n', '3 1 2\n', '4 3 2 1\n', '1\n', '2 3 4 1\n'] })

t({ lv: 765, concept: '数え上げ: 和が平方数のペア数', title: '足すと平方数になる2人', tags: ['数え上げ', '数学'], io: '正整数の列が1行で空白区切りで与えられます。', ask: 'i<j で a[i]+a[j] が平方数になるペアの個数を出力してください。', h1: '全ペアを試して isqrt で判定する。', h2: 'x が平方数 ⇔ isqrt(x)² が x に等しい。', ref: 'import math\na=list(map(int,input().split()))\nn=len(a)\ncnt=0\nfor i in range(n):\n    for j in range(i+1,n):\n        s=a[i]+a[j]\n        r=math.isqrt(s)\n        if r*r==s:\n            cnt+=1\nprint(cnt)', tip: 'isqrtは浮動小数を経由しない整数平方根なので、大きな値でも判定が壊れない。「和が◯◯」系は条件関数を差し替えるだけの再利用しやすい骨格。', ins: ['1 3 6 10\n', '2 2\n', '1 8\n', '5 4 11 21\n', '1 1 1\n', '7 9 16 20\n'] })

export const CATALOG = TASKS
