// 生成タスク 第86波：各レベル3問化フェーズ(13)。lv626〜649, 651〜675 の薄い49段に3問目を追加。
// グラフ後半+DP帯。クラスタ3問まで可・言い換え水増し禁止。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 626, concept: 'DAG: 同じ層になる頂点ペア数', title: '同期入社のペア', tags: ['DAG'], io: '1行目に頂点数 n と辺数 m、続く m 行に有向辺 u v (閉路なし) が与えられます。', ask: '「入次数0の頂点を同時に取り除く」ラウンドを繰り返すとき、同じラウンドで取り除かれる頂点のペア (u<v) の総数を出力してください。', h1: 'トポロジカル層の数(同レベル既出)の中身の集計。', h2: '層ごとの人数 c から C(c,2) を足す。', ref: 'from collections import deque\nn,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nind=[0]*(n+1)\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    ind[v]+=1\ncur=[v for v in range(1,n+1) if ind[v]==0]\ntotal=0\nwhile cur:\n    c=len(cur)\n    total+=c*(c-1)//2\n    nxt=[]\n    for v in cur:\n        for w in g[v]:\n            ind[w]-=1\n            if ind[w]==0:\n                nxt.append(w)\n    cur=nxt\nprint(total)', tip: '層(レベル)は「並列に実行できるタスクの束」で、このペア数は並列度の指標になる。層分けのアルゴリズムはトポロジカルソートのラウンド版そのもの。', ins: ['4 3\n1 2\n1 3\n2 4\n', '3 0\n', '4 4\n1 2\n2 3\n1 4\n3 4\n', '5 2\n1 3\n2 4\n', '2 1\n1 2\n', '6 3\n1 4\n2 5\n3 6\n'] })

t({ lv: 627, concept: 'グラフ: 次数の平均', title: '平均的なつながりの濃さ', tags: ['グラフ'], io: '1行目に頂点数 n と辺数 m、続く m 行に無向辺 u v が与えられます。', ask: '全頂点の次数の平均を小数第1位まで出力してください。', h1: '次数の合計は数えなくても分かる。', h2: '握手補題より合計は 2m、平均は 2m/n。', ref: 'n,m=map(int,input().split())\nfor _ in range(m):\n    input()\nprint(f"{2*m/n:.1f}")', tip: '辺を1本も読まずに答えが出る、握手補題の実用形。SNSの「平均友達数」は2m/nで、これが中央値より大きくなりがち(友情のパラドックス)という話にも繋がる。', ins: ['3 2\n1 2\n2 3\n', '4 4\n1 2\n2 3\n3 4\n4 1\n', '2 1\n1 2\n', '5 0\n', '3 3\n1 2\n2 3\n1 3\n', '4 3\n1 2\n1 3\n1 4\n'] })

t({ lv: 628, concept: 'リスト: 必要なタンク容量の最小', title: '無給油区間に耐える容量', tags: ['リスト'], io: '1行目にゴールまでの距離 L、2行目に給油所の位置(昇順、無い場合は空行)が与えられます。距離1につき燃料1を使い、給油所では満タンにできます。', ask: 'スタート(位置0、満タン発進)からゴールまで走り切るのに必要なタンク容量の最小を出力してください。', h1: '容量は「給油できない最長区間」で決まる。', h2: 'スタート・各給油所・ゴールの隣接間隔の最大。', ref: 'L=int(input())\nps=list(map(int,input().split()))\npts=[0]+ps+[L]\nprint(max(pts[i+1]-pts[i] for i in range(len(pts)-1)))', tip: 'ボトルネック(最悪区間)が全体の要件を決める、ミニマックス思考の1次元版。両端を番兵として挟むリストの作り方が、境界処理をループから消している。', ins: ['10\n3 6\n', '10\n5\n', '8\n2 4 6\n', '6\n\n', '100\n50\n', '9\n1 8\n'] })

t({ lv: 629, concept: 'シミュレーション: 勝敗表の整合性検証', title: 'その星取表は本物か', tags: ['シミュレーション'], io: '1行目に n、続く n 行に n×n の表(i行j列が1なら i が j に勝ち。対角は0)が与えられます。引き分けはありません。', ask: 'どの2人の間にも「どちらか一方だけが勝っている」ことが成り立つなら yes、矛盾があれば no を出力してください。', h1: '対角が0、i≠jで w[i][j]+w[j][i]==1。', h2: '二重ループで確かめる。', ref: 'n=int(input())\nw=[list(map(int,input().split())) for _ in range(n)]\nok=all(w[i][i]==0 for i in range(n))\nok=ok and all(w[i][j]+w[j][i]==1 for i in range(n) for j in range(n) if i!=j)\nprint("yes" if ok else "no")', tip: 'この条件を満たす有向グラフはトーナメントと呼ばれ、必ずハミルトン路を持つ(誰かから始めて全員を順に倒す並びが作れる)という美しい定理がある。', ins: ['2\n0 1\n0 0\n', '2\n0 1\n1 0\n', '3\n0 1 1\n0 0 0\n0 1 0\n', '3\n0 1 1\n0 0 1\n0 0 0\n', '2\n0 0\n0 0\n', '1\n0\n'] })

t({ lv: 630, concept: 'BFS: 何らかの最短路に乗る辺の数', title: '最短ルート網の道路', tags: ['BFS', 'グラフ'], io: '1行目に頂点数 n と辺数 m、続く m 行に無向辺 u v が与えられます(1からnへ到達可能)。', ask: '頂点1から頂点nへのいずれかの最短経路に含まれる辺の本数を出力してください。', h1: '頂点版(同レベル既出)の辺版。', h2: '両端からのBFSで d1[u]+1+dn[v]==D (どちらかの向き)。', ref: 'from collections import deque\nn,m=map(int,input().split())\nes=[]\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    es.append((u,v))\n    g[u].append(v)\n    g[v].append(u)\ndef bfs(s):\n    dist=[-1]*(n+1)\n    dist[s]=0\n    q=deque([s])\n    while q:\n        x=q.popleft()\n        for y in g[x]:\n            if dist[y]<0:\n                dist[y]=dist[x]+1\n                q.append(y)\n    return dist\nd1=bfs(1)\ndn=bfs(n)\nD=d1[n]\ncnt=0\nfor u,v in es:\n    if d1[u]>=0 and dn[v]>=0 and d1[u]+1+dn[v]==D:\n        cnt+=1\n    elif d1[v]>=0 and dn[u]>=0 and d1[v]+1+dn[u]==D:\n        cnt+=1\nprint(cnt)', tip: '最短路DAGの辺を数えている(既出の「最短路DAGの辺数」の判定式そのもの)。両端からの距離の和で「その部品が最短に貢献するか」を測る型は辺でも頂点でも同じ。', ins: ['3 2\n1 2\n2 3\n', '3 3\n1 2\n2 3\n1 3\n', '4 4\n1 2\n2 4\n1 3\n3 4\n', '2 1\n1 2\n', '4 5\n1 2\n2 4\n1 3\n3 4\n2 3\n', '5 5\n1 2\n2 5\n1 3\n3 4\n4 5\n'] })

t({ lv: 631, concept: 'ソート: k個選ぶ最小の値域', title: 'k人の実力を揃えて選抜', tags: ['ソート'], io: '1行目に k、2行目に整数列(k個以上)が与えられます。', ask: 'k 個の要素を選ぶとき、選んだ中の最大と最小の差の最小値を出力してください。', h1: 'ソートすれば最適は連続するk個。', h2: '長さkの窓の a[i+k−1]−a[i] の最小。', ref: 'k=int(input())\na=sorted(map(int,input().split()))\nprint(min(a[i+k-1]-a[i] for i in range(len(a)-k+1)))', tip: '「ソート後の連続窓が最適」は交換論法の一行証明つき。チョコレート配布問題の名で知られ、公平な分配の定番モデルになっている。', ins: ['2\n1 5 3 9\n', '3\n1 5 3 9\n', '1\n7 2\n', '2\n4 4 4\n', '3\n10 1 2 3 20\n', '2\n8 1\n'] })

t({ lv: 632, concept: '数え上げ: 勝ち抜き戦の試合総数', title: '優勝までの試合数', tags: ['数え上げ'], io: '参加者の人数 n が1行で与えられます。', ask: '1試合ごとにちょうど1人が敗退する勝ち抜き戦で、優勝者が決まるまでの試合の総数を出力してください。', h1: 'トーナメント表を書かなくても分かる。', h2: '敗者はn−1人、1試合で1人だけ敗退する。', ref: 'n=int(input())\nprint(n-1)', tip: 'ブラケットの形やシードに一切よらず n−1 で確定する、不変量による数え上げの傑作。「何が1試合で1つ減るか」に注目する視点はあらゆる操作回数の解析に効く。', ins: ['8\n', '2\n', '1\n', '16\n', '5\n', '100\n'] })

t({ lv: 633, concept: '幾何: 最近点までの距離の2乗の合計', title: 'それぞれの一番近いご近所', tags: ['幾何'], io: '1行目に点の数 n (n≥2)、続く n 行に座標 x y が与えられます。', ask: '各点について「他の点への距離の2乗の最小」を求め、その合計を出力してください。', h1: '最近ペア(既出)は全体で1つ、こちらは点ごと。', h2: '総当たりで各点のminを足す。', ref: 'n=int(input())\npts=[tuple(map(int,input().split())) for _ in range(n)]\ntotal=0\nfor i in range(n):\n    best=None\n    for j in range(n):\n        if i!=j:\n            d=(pts[i][0]-pts[j][0])**2+(pts[i][1]-pts[j][1])**2\n            if best is None or d<best:\n                best=d\n    total+=best\nprint(total)', tip: '最近傍距離の分布は点配置の「混み具合」の指標で、空間統計の最近隣解析の生データ。全体の最近ペアと違い、点ごとの値は非対称(AのNNがBでもBのNNはCかも)。', ins: ['3\n0 0\n0 3\n4 0\n', '2\n0 0\n1 1\n', '3\n0 0\n1 0\n5 0\n', '4\n0 0\n0 1\n10 0\n10 1\n', '2\n-3 0\n3 0\n', '3\n1 1\n2 2\n3 3\n'] })

t({ lv: 634, concept: 'DP: 最小コスト経路の本数', title: '最安ルートは何通り', tags: ['DP', 'グリッド'], io: '1行目に H W、続く H 行にコストの格子が与えられます。左上から右下へ、右か下にのみ進みます。', ask: 'コスト合計が最小の経路の本数を出力してください。', h1: '最小値のDPと本数のDPを同時に走らせる。', h2: 'より安い経路が来たら本数を上書き、同額なら加算。', ref: 'h,w=map(int,input().split())\ng=[list(map(int,input().split())) for _ in range(h)]\nINF=10**18\ncost=[[INF]*w for _ in range(h)]\ncnt=[[0]*w for _ in range(h)]\ncost[0][0]=g[0][0]\ncnt[0][0]=1\nfor i in range(h):\n    for j in range(w):\n        for pi,pj in ((i-1,j),(i,j-1)):\n            if pi>=0 and pj>=0:\n                c=cost[pi][pj]+g[i][j]\n                if c<cost[i][j]:\n                    cost[i][j]=c\n                    cnt[i][j]=cnt[pi][pj]\n                elif c==cost[i][j]:\n                    cnt[i][j]+=cnt[pi][pj]\nprint(cnt[h-1][w-1])', tip: '「上書きか加算か」の分岐が最適性の伝播を正確に写す、値+本数のペアDPの定石。重みつき最短路の本数(既出)のグリッド版で、遷移が2方向しかないぶん構造が見やすい。', ins: ['2 2\n1 1\n1 1\n', '2 2\n1 2\n2 1\n', '2 3\n1 1 1\n1 1 1\n', '2 2\n1 5\n1 1\n', '3 3\n1 1 1\n1 9 1\n1 1 1\n', '1 4\n1 2 3 4\n'] })

t({ lv: 635, concept: 'Union-Find: 自分の島の大きさ', title: 'うちのグループは何人?', tags: ['Union-Find'], io: '1行目に頂点数 n、辺数 m、質問数 q、続く m 行に無向辺、続く q 行に頂点番号が与えられます。', ask: '各質問の頂点が属する連結成分の頂点数を1行ずつ出力してください。', h1: 'サイズつきUnion-Find。', h2: '根にサイズを持たせて併合時に足す。', ref: 'first=input().split()\nn,m,q=map(int,first)\np=list(range(n+1))\nsz=[1]*(n+1)\ndef find(x):\n    while p[x]!=x:\n        p[x]=p[p[x]]\n        x=p[x]\n    return x\nfor _ in range(m):\n    u,v=map(int,input().split())\n    ru,rv=find(u),find(v)\n    if ru!=rv:\n        p[ru]=rv\n        sz[rv]+=sz[ru]\nfor _ in range(q):\n    v=int(input())\n    print(sz[find(v)])', tip: 'サイズ情報を根に集約する「重みつきUnion-Find」の入り口。サイズの小さい方を大きい方へ繋ぐ(union by size)高速化も、この配列がそのまま材料になる。', ins: ['5 2 3\n1 2\n3 4\n1\n3\n5\n', '3 3 1\n1 2\n2 3\n1 3\n2\n', '4 0 2\n1\n4\n', '6 3 2\n1 2\n2 3\n4 5\n3\n6\n', '2 1 1\n1 2\n2\n', '7 4 2\n1 2\n3 4\n4 5\n5 3\n4\n1\n'] })

t({ lv: 636, concept: '文字列: 鏡映で同じに見える単語か', title: '鏡の国でも読める単語', tags: ['文字列'], io: '英大文字の単語が1行で与えられます。', ask: '鏡に映しても同じに見える(全ての文字が左右対称な文字 A H I M O T U V W X Y で、かつ単語全体が回文)なら yes、そうでなければ no を出力してください。', h1: '条件は2つ: 文字の対称性と並びの対称性。', h2: '集合による所属チェック+回文判定。', ref: 's=input()\nM=set("AHIMOTUVWXY")\nprint("yes" if all(c in M for c in s) and s==s[::-1] else "no")', tip: '「文字単位の性質」と「列全体の性質」の合成条件で、片方だけ確かめて満足する読み落としを誘う。救急車のAMBULANCE鏡文字表記など実世界の応用もある。', ins: ['TOT\n', 'WOW\n', 'CAT\n', 'MOM\n', 'TO\n', 'AHA\n'] })

t({ lv: 637, concept: '統計: 中央絶対偏差', title: '真ん中からのばらつきの真ん中', tags: ['統計'], io: '奇数個の整数列が1行で空白区切りで与えられます。', ask: '中央値からの絶対偏差 |x−中央値| の中央値(MAD)を出力してください。', h1: '中央値を2回使う。', h2: '偏差のリストを作ってまた中央値。', ref: 'a=sorted(map(int,input().split()))\nm=a[len(a)//2]\nd=sorted(abs(x-m) for x in a)\nprint(d[len(d)//2])', tip: '標準偏差が外れ値に敏感なのに対し、MADは50%までの汚染に耐える最強クラスの頑健統計量。異常検知の閾値(中央値±k×MAD)として実務で日常的に使われる。', ins: ['1 2 9\n', '5\n', '1 1 1\n', '1 5 9\n', '2 4 6 8 10\n', '1 2 3 4 100\n'] })

t({ lv: 638, concept: 'シミュレーション: 信号待ちの合計時間', title: '青のうちに渡れるか', tags: ['シミュレーション'], io: '1行目に青の秒数 g と赤の秒数 r、2行目に各信号までの区間距離の列が与えられます。時刻0に出発し、毎秒1進みます。信号は時刻0から青g秒→赤r秒を繰り返し、到着時に赤なら次の青まで待ちます。', ask: '最後の信号を通過する時刻を出力してください。', h1: '到着時刻を周期 g+r で割った余りで判定。', h2: '赤なら次の周期の頭まで時刻を進める。', ref: 'g,r=map(int,input().split())\nds=list(map(int,input().split()))\nt2=0\nc=g+r\nfor d in ds:\n    t2+=d\n    if t2%c>=g:\n        t2=(t2//c+1)*c\nprint(t2)', tip: '周期現象との同期は「周期で割った余り」が全てを語る。切り上げを (t//c+1)*c で書く整数の作法も含め、バスの時刻表や機械のポーリングと同じ計算。', ins: ['5 5\n3 4\n', '3 2\n1 1 1\n', '10 1\n5\n', '2 3\n4\n', '1 1\n1 1\n', '4 4\n2 2 2\n'] })

t({ lv: 639, concept: 'グラフ: 次数列から辺数を求める', title: '握手の回数から本数へ', tags: ['グラフ'], io: '各頂点の次数の列が1行で空白区切りで与えられます(実現可能なグラフの次数列)。', ask: 'このグラフの辺の本数を出力してください。', h1: '辺1本は次数を2増やす。', h2: '合計÷2。', ref: 'print(sum(map(int,input().split()))//2)', tip: '握手補題(次数和=2m)の直用で、辺リストが無くても辺数だけは即答できる。次数和が奇数の列はそもそもグラフとして実現不可能、という検算にも同じ式が効く。', ins: ['1 2 1\n', '0 0\n', '3 3 3 3\n', '1 1\n', '2 2 2\n', '4 1 1 1 1\n'] })

t({ lv: 640, concept: 'BFS: どちらの拠点に近いか集計', title: '二大拠点の勢力図', tags: ['BFS', 'グラフ'], io: '1行目に n m a b、続く m 行に無向辺 u v が与えられます(連結)。', ask: '各頂点を「aに近い」「bに近い」「等距離」に分類し、その3つの数をこの順に空白区切りで出力してください。', h1: '両拠点からBFS。', h2: '距離を比べて3分類。', ref: 'from collections import deque\nfirst=input().split()\nn,m,a,b=map(int,first)\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\ndef bfs(s):\n    dist=[-1]*(n+1)\n    dist[s]=0\n    q=deque([s])\n    while q:\n        x=q.popleft()\n        for y in g[x]:\n            if dist[y]<0:\n                dist[y]=dist[x]+1\n                q.append(y)\n    return dist\nda=bfs(a)\ndb=bfs(b)\nca=sum(1 for v in range(1,n+1) if da[v]<db[v])\ncb=sum(1 for v in range(1,n+1) if db[v]<da[v])\nprint(ca,cb,n-ca-cb)', tip: '2点からの距離比較でグラフをボロノイ分割している。商圏分析(どの店に近い客か)のネットワーク版で、等距離の境界層の扱いを仕様に明記する練習にもなる。', ins: ['3 2 1 3\n1 2\n2 3\n', '2 1 1 2\n1 2\n', '5 4 1 5\n1 2\n2 3\n3 4\n4 5\n', '4 3 1 4\n1 2\n2 3\n3 4\n', '3 3 1 2\n1 2\n2 3\n1 3\n', '1 0 1 1\n'] })

t({ lv: 641, concept: '累積和: 累積XORの列', title: 'XORを積み上げた足あと', tags: ['累積和', 'bit演算'], io: '非負整数の列が1行で空白区切りで与えられます。', ask: '先頭からの累積XOR(1個目、1〜2個目、…)を空白区切りで出力してください。', h1: '累積和・累積積(既出)のXOR版。', h2: '持ち回りの変数に ^= で畳む。', ref: 'a=list(map(int,input().split()))\nout=[]\nx=0\nfor v in a:\n    x^=v\n    out.append(x)\nprint(" ".join(map(str,out)))', tip: '区間XORは累積XORの2点の差(XOR)で出る——和と同じ引き算の構造がXORでも成り立つ(自己逆元だから)。区間XORクエリ問題群の前処理がこの1行。', ins: ['1 2 3\n', '5\n', '7 7\n', '1 1 1 1\n', '4 2\n', '3 5 6\n'] })

t({ lv: 642, concept: '木: 葉の一覧', title: '末端メンバーの名簿', tags: ['木'], io: '1行目に頂点数 n (n≥2)、2行目に頂点2〜nの親が与えられます(根は頂点1)。', ask: '葉(子を持たない頂点)を番号の昇順に空白区切りで出力してください。', h1: '葉の数(既出)の一覧版。', h2: '親として現れない頂点が葉。', ref: 'n=int(input())\npar=set(map(int,input().split()))\nprint(" ".join(str(v) for v in range(1,n+1) if v not in par))', tip: '「親の集合に現れない=子がいない」という補集合の読み替えで、木を組み立てずに済む。ディレクトリツリーの末端ファイル列挙と同じ操作。', ins: ['5\n1 1 2 2\n', '2\n1\n', '4\n1 2 3\n', '7\n1 1 2 2 3 3\n', '4\n1 1 1\n', '6\n1 2 3 3 4\n'] })

t({ lv: 643, concept: 'グラフ: 輪を1つだけ持つ成分の数', title: 'ちょうど一巻きの部品', tags: ['グラフ'], io: '1行目に頂点数 n と辺数 m、続く m 行に無向辺 u v (自己ループ・多重辺なし) が与えられます。', ask: '「辺の数と頂点の数が等しい」連結成分(閉路をちょうど1つ含む)の個数を出力してください。', h1: '木の成分(同レベル既出)は辺=頂点−1、こちらは辺=頂点。', h2: '成分ごとに頂点と辺を数える。', ref: 'n,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\nseen=[False]*(n+1)\ncnt=0\nfor s in range(1,n+1):\n    if seen[s]:\n        continue\n    seen[s]=True\n    vs=0\n    deg=0\n    st=[s]\n    while st:\n        x=st.pop()\n        vs+=1\n        deg+=len(g[x])\n        for y in g[x]:\n            if not seen[y]:\n                seen[y]=True\n                st.append(y)\n    if deg//2==vs:\n        cnt+=1\nprint(cnt)', tip: '辺=頂点の成分は「木+1本」で、関数グラフの成分と同じρ形。木(辺=頂点−1)・単閉路(辺=頂点)・それ以上、の3分類は成分の複雑さの物差しになる。', ins: ['3 3\n1 2\n2 3\n1 3\n', '4 3\n1 2\n2 3\n3 4\n', '6 6\n1 2\n2 3\n3 1\n4 5\n5 6\n6 4\n', '5 5\n1 2\n2 3\n3 1\n1 4\n4 5\n', '2 1\n1 2\n', '4 4\n1 2\n2 3\n3 4\n4 1\n'] })

t({ lv: 644, concept: '貪欲: 予算で買える最大の品数', title: '安い順に買えるだけ', tags: ['貪欲', 'ソート'], io: '1行目に予算、2行目に品物の価格の列が与えられます。', ask: '合計が予算以下になるように買える品数の最大を出力してください。', h1: '安い順に取るのが最適。', h2: 'ソートして累計が超えるまで数える。', ref: 'b=int(input())\ncnt=0\ntotal=0\nfor p in sorted(map(int,input().split())):\n    if total+p<=b:\n        total+=p\n        cnt+=1\n    else:\n        break\nprint(cnt)', tip: '価値が全部1のナップサックは貪欲で厳密に解ける、という特殊ケースの威力。個数最大と価値最大で難しさが天と地ほど違う対比が学べる。', ins: ['10\n3 5 4\n', '1\n2 3\n', '100\n10 20 30\n', '7\n7\n', '6\n2 2 2 2\n', '5\n1 1 1 1 1 1\n'] })

t({ lv: 645, concept: '統計: 2列の一致率', title: '答案の一致度', tags: ['統計'], io: '1行目と2行目に同じ長さの整数列が与えられます。', ask: '同じ位置で値が一致している割合を、パーセントの整数(切り捨て)で出力してください。', h1: 'zipで対応を見る。', h2: '一致数×100 を個数で整数除算。', ref: 'a=input().split()\nb=input().split()\nc=sum(1 for x,y in zip(a,b) if x==y)\nprint(c*100//len(a))', tip: '分類モデルの正解率(accuracy)の計算そのもの。100倍してから割る整数演算の作法は異なり語率(既出)と同じで、浮動小数を経ないのが信頼の源。', ins: ['1 2 3\n1 5 3\n', '1 1\n1 1\n', '1\n2\n', '1 2 3 4\n1 2 3 4\n', '5 5 5 5 5\n5 0 5 0 5\n', '0 1\n1 0\n'] })

t({ lv: 646, concept: 'グラフ: 縮約後の出口なし成分の数', title: '行き着く先の吹きだまり', tags: ['グラフ'], io: '1行目に頂点数 n と辺数 m、続く m 行に有向辺 u v が与えられます。', ask: '強連結成分に縮約したとき、他の成分への出て行く辺を持たない成分(シンク)の個数を出力してください。', h1: '入次数0成分(同レベル既出)の鏡像。', h2: '相互到達で成分分けし、成分外への辺があるか調べる。', ref: 'n,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nes=[]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    es.append((u,v))\nreach=[]\nfor s in range(n+1):\n    seen=[False]*(n+1)\n    if s>0:\n        seen[s]=True\n        st=[s]\n        while st:\n            x=st.pop()\n            for y in g[x]:\n                if not seen[y]:\n                    seen[y]=True\n                    st.append(y)\n    reach.append(seen)\ncomp=[0]*(n+1)\ncid=0\nfor v in range(1,n+1):\n    if comp[v]==0:\n        cid+=1\n        for u in range(1,n+1):\n            if reach[v][u] and reach[u][v]:\n                comp[u]=cid\nhasout=[False]*(cid+1)\nfor u,v in es:\n    if comp[u]!=comp[v]:\n        hasout[comp[u]]=True\nprint(sum(1 for c in range(1,cid+1) if not hasout[c]))', tip: 'ランダムウォークが最終的に吸い込まれる先がシンク成分で、マルコフ連鎖の再帰類に対応する。ソース(入口なし)とシンク(出口なし)の対で縮約DAGの両端が見える。', ins: ['3 3\n1 2\n2 3\n3 1\n', '2 1\n1 2\n', '4 4\n1 2\n2 1\n3 4\n4 3\n', '3 2\n1 2\n1 3\n', '5 5\n1 2\n2 3\n3 1\n3 4\n4 5\n', '3 0\n'] })

t({ lv: 647, concept: 'DAG: トポロジカル順での最悪の順位', title: 'どこまで後回しにできるか', tags: ['DAG'], io: '1行目に頂点数 n、辺数 m、対象の頂点 v、続く m 行に有向辺 u w (uが先) が与えられます(閉路なし)。', ask: '頂点 v がトポロジカル順序の中で取り得る最も遅い順位(1始まり)を出力してください。', h1: '最良の順位(同レベル既出)の鏡像。', h2: 'vより後に必ず来るのはvから到達できる頂点だけ。最悪順位は n−(その数)。', ref: 'n,m,v=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,w=map(int,input().split())\n    g[u].append(w)\nseen=[False]*(n+1)\nst=[v]\nseen[v]=True\ncnt=0\nwhile st:\n    x=st.pop()\n    for y in g[x]:\n        if not seen[y]:\n            seen[y]=True\n            st.append(y)\n            cnt+=1\nprint(n-cnt)', tip: '最良順位は「vへ来られる頂点数+1」、最悪は「n−vから行ける頂点数」と、到達可能性の前後2方向が順位の自由度を挟み撃ちにする。スケジュールの余裕の言い換えでもある。', ins: ['4 3 1\n1 2\n1 3\n2 4\n', '4 3 4\n1 2\n1 3\n2 4\n', '3 0 2\n', '5 4 3\n1 2\n2 3\n3 4\n4 5\n', '2 1 2\n1 2\n', '6 5 2\n1 2\n2 3\n2 4\n4 5\n3 6\n'] })

t({ lv: 648, concept: 'bit演算: グレイコード順の一覧', title: '1ビットずつ変わる行進', tags: ['bit演算'], io: '正整数 k (1〜4程度) が1行で与えられます。', ask: 'kビットのグレイコード順(隣り合う値が1ビットだけ違う列)を、i XOR (i>>1) の順で 2^k 個、空白区切りで出力してください。', h1: 'グレイコードから整数へ(既出)の逆方向の列挙。', h2: 'i=0..2^k−1 について i^(i>>1)。', ref: 'k=int(input())\nprint(" ".join(str(i^(i>>1)) for i in range(1<<k)))', tip: 'ロータリーエンコーダやカルノー図の並びとして実世界で現役。1ビットずつしか変わらないので、部分集合の全列挙で差分更新O(1)を可能にする巡回路でもある。', ins: ['2\n', '1\n', '3\n', '4\n'] })

t({ lv: 649, concept: '木: 各深さの最初の頂点', title: '各階の窓口一番', tags: ['木'], io: '1行目に頂点数 n (n≥2)、2行目に頂点2〜nの親が与えられます(根は頂点1)。', ask: '各深さ(0から最深まで)について最小番号の頂点を、浅い順に空白区切りで出力してください。', h1: '木の幅(同レベル既出)と同じ深さ集計の別の統計。', h2: '深さごとのminを配列で。', ref: 'n=int(input())\npar=list(map(int,input().split()))\ndepth=[0]*(n+1)\nfor i in range(2,n+1):\n    depth[i]=depth[par[i-2]]+1\nmx=max(depth[1:n+1])\nbest=[None]*(mx+1)\nfor v in range(1,n+1):\n    d=depth[v]\n    if best[d] is None or v<best[d]:\n        best[d]=v\nprint(" ".join(map(str,best)))', tip: '二分木の「各段の左端」を一般の木と番号規約で言い換えた形。深さをキーにした集計(人数・最初・最後)は全部同じ1パスで揃う、集計設計の練習台。', ins: ['5\n1 1 2 2\n', '2\n1\n', '7\n1 1 1 2 2 2\n', '6\n1 2 3 4 5\n', '4\n1 1 1\n', '9\n1 1 2 2 3 3 4 4\n'] })

t({ lv: 651, concept: '行列: 行にも列にも1が1つ以下か', title: 'ルークが利き合わない配置か', tags: ['行列'], io: '1行目に n、続く n 行に 0/1 の n×n 行列が与えられます。', ask: 'どの行にもどの列にも1が高々1つしかないなら yes、2つ以上ある行か列があれば no を出力してください。', h1: '行の和と列の和を全部調べる。', h2: 'zip(*A)で列が取れる。', ref: 'n=int(input())\nA=[list(map(int,input().split())) for _ in range(n)]\nok=all(sum(r)<=1 for r in A) and all(sum(c)<=1 for c in zip(*A))\nprint("yes" if ok else "no")', tip: 'ルーク(飛車)の非攻撃配置の検証で、1がちょうどn個なら置換行列。二部マッチングの解を行列で表すとこの形になる、と representation の橋渡しにもなる。', ins: ['2\n1 0\n0 1\n', '2\n1 1\n0 0\n', '3\n0 1 0\n1 0 0\n0 0 1\n', '1\n1\n', '3\n1 0 0\n1 0 0\n0 1 0\n', '2\n0 0\n0 0\n'] })

t({ lv: 652, concept: 'シミュレーション: 北西隅法の輸送表', title: '左上から順に割り当てる', tags: ['シミュレーション'], io: '1行目に供給地の数 s と需要地の数 d、2行目に各供給量、3行目に各需要量(合計は一致)、続く s 行に単位輸送コストの表が与えられます。', ask: '北西隅法(表の左上から、供給と需要の小さい方を割り当てて行/列を消し込む)で決めた輸送の総コストを出力してください。', h1: '2つのポインタで表を進む。', h2: 'min(残り供給, 残り需要)を割り当てる。', ref: 'first=input().split()\ns,d=int(first[0]),int(first[1])\nsup=list(map(int,input().split()))\ndem=list(map(int,input().split()))\ncost=[list(map(int,input().split())) for _ in range(s)]\ni=j=0\ntotal=0\nwhile i<s and j<d:\n    x=min(sup[i],dem[j])\n    total+=x*cost[i][j]\n    sup[i]-=x\n    dem[j]-=x\n    if sup[i]==0:\n        i+=1\n    if j<d and dem[j]==0:\n        j+=1\nprint(total)', tip: '輸送問題の初期実行可能解を作る古典手法で、コストを見ないぶん速いが質はそこそこ。最小費用流(既出)の答えと比べると「初期解と最適解の距離」が数字で見える。', ins: ['2 2\n10 20\n15 15\n1 2\n3 4\n', '1 1\n5\n5\n7\n', '2 2\n5 5\n5 5\n1 1\n1 1\n', '2 3\n8 7\n5 5 5\n2 1 3\n4 2 1\n', '3 1\n2 3 4\n9\n5\n6\n7\n', '2 2\n1 9\n9 1\n1 2\n3 4\n'] })

t({ lv: 653, concept: 'グリッド: 市松塗りの白黒差', title: '欠けた盤の色バランス', tags: ['グリッド'], io: '1行目に H W、続く H 行に盤面(. が使えるマス、# が欠け)が与えられます。', ask: '使えるマスを市松模様に塗ったときの、白マス数と黒マス数の差の絶対値を出力してください((行+列)が偶数を白とします)。', h1: 'ドミノ敷き詰め(同レベル既出)の実行前チェック。', h2: '(i+j)%2 で2種類を数える。', ref: 'h,w=map(int,input().split())\ng=[input() for _ in range(h)]\nwhite=sum(1 for i in range(h) for j in range(w) if g[i][j]=="." and (i+j)%2==0)\nblack=sum(1 for i in range(h) for j in range(w) if g[i][j]=="." and (i+j)%2==1)\nprint(abs(white-black))', tip: 'ドミノは必ず白黒1マスずつ覆うので、差が0でなければ完全敷き詰めは不可能(有名な欠けチェス盤の証明)。不変量による不可能性証明の代表例が、この単純な集計。', ins: ['2 2\n..\n..\n', '2 2\n.#\n..\n', '1 3\n...\n', '3 3\n...\n.#.\n...\n', '1 1\n.\n', '2 3\n#..\n...\n'] })

t({ lv: 654, concept: 'DP: ナップサック解の復元', title: '何を持っていくかまで答える', tags: ['DP'], io: '1行目に品数 n と容量 W、続く n 行に「重さ 価値」が与えられます。', ask: '価値最大の選び方のうち、選ぶ品物の番号の集合が辞書順最小のものを昇順に空白区切りで出力してください(何も選ばないのが最適なら none)。', h1: '後ろ向きDPで「残りでの最大」を前計算。', h2: '前から順に「入れても最適が保てるなら入れる」貪欲で復元。', ref: 'n,W=map(int,input().split())\nitems=[tuple(map(int,input().split())) for _ in range(n)]\nbest=[[0]*(W+1) for _ in range(n+1)]\nfor i in range(n-1,-1,-1):\n    w,v=items[i]\n    for c in range(W+1):\n        best[i][c]=best[i+1][c]\n        if w<=c and best[i+1][c-w]+v>best[i][c]:\n            best[i][c]=best[i+1][c-w]+v\nres=[]\nc=W\nfor i in range(n):\n    w,v=items[i]\n    if w<=c and best[i+1][c-w]+v==best[i][c]:\n        res.append(str(i+1))\n        c-=w\nprint(" ".join(res) if res else "none")', tip: '「若い番号を入れても損しないなら必ず入れる」が辞書順最小の集合を作る。値のDPと構成の貪欲の分業は、LCS復元・LIS復元と同じ三度目の型稽古。', ins: ['3 5\n2 3\n3 4\n5 6\n', '2 4\n5 1\n5 2\n', '1 3\n3 10\n', '3 6\n2 2\n2 3\n2 4\n', '3 5\n5 6\n2 3\n3 4\n', '2 5\n3 4\n3 4\n'] })

t({ lv: 655, concept: '貪欲: 分けて持てるナップサック', title: '量り売りの詰め放題', tags: ['貪欲'], io: '1行目に容量 C と品数 n、続く n 行に「重さ 価値」(単位重さあたりの価値は全て相異なる)が与えられます。品物は好きな量だけ切り分けて持てます。', ask: '持ち出せる価値の最大を小数第1位まで出力してください。', h1: '0/1ナップサック(同レベル既出)と違い貪欲で最適。', h2: '価値密度の高い順に詰め、最後だけ端数。', ref: 'from fractions import Fraction\nfirst=input().split()\nC,n=int(first[0]),int(first[1])\nitems=[tuple(map(int,input().split())) for _ in range(n)]\nitems.sort(key=lambda wv:Fraction(wv[1],wv[0]),reverse=True)\ncap=C\ntotal=Fraction(0)\nfor w,v in items:\n    take=min(w,cap)\n    total+=Fraction(v*take,w)\n    cap-=take\n    if cap==0:\n        break\nprint(f"{float(total):.1f}")', tip: '分割を許した瞬間、NP困難だった問題が貪欲で厳密に解ける——連続緩和の威力の代表例。0/1版の分枝限定法では、この値が上界(枝刈りの物差し)として使われる。', ins: ['10 2\n5 10\n6 18\n', '5 1\n10 30\n', '7 2\n3 9\n4 4\n', '8 3\n2 10\n4 8\n6 6\n', '3 1\n6 12\n', '10 2\n4 12\n6 6\n'] })

t({ lv: 656, concept: 'リスト: 超増加列かどうか', title: '前の全部を超えていく列', tags: ['リスト'], io: '正整数の列が1行で空白区切りで与えられます。', ask: '各要素が「それより前の全要素の合計より大きい」(超増加列)なら yes、そうでなければ no を出力してください。', h1: '累積和を持ち回って比べる。', h2: '最初の要素は無条件で合格。', ref: 'a=list(map(int,input().split()))\ns=0\nok=True\nfor x in a:\n    if x<=s:\n        ok=False\n    s+=x\nprint("yes" if ok else "no")', tip: '超増加列なら部分和問題が貪欲で一意に解ける(初期のナップサック暗号の心臓部)。作れない最小の金額(同レベル既出)の貪欲が成立する条件でもある。', ins: ['1 2 4 8\n', '1 2 3\n', '5\n', '1 2 4 7\n', '2 3 6 12\n', '1 1\n'] })

t({ lv: 657, concept: 'DP: 最も多い枚数でちょうどTを作る', title: 'なるべく細かく払う', tags: ['DP'], io: '1行目に目標 T、2行目に正整数の列(和をTにできる)が与えられます。', ask: '各要素を高々1回使って和をちょうど T にするときの、使う要素数の最大を出力してください。', h1: '最少枚数(同レベル既出)の鏡像。', h2: 'dpの初期値を−∞にしてmaxで更新、逆順ループ。', ref: 'T=int(input())\na=list(map(int,input().split()))\nNEG=-(10**9)\ndp=[NEG]*(T+1)\ndp[0]=0\nfor x in a:\n    for s in range(T,x-1,-1):\n        if dp[s-x]+1>dp[s]:\n            dp[s]=dp[s-x]+1\nprint(dp[T])', tip: 'minとmaxでコードは1語しか違わないのに、番兵の符号(∞と−∞)まで対で反転する。DPの構成要素(初期値・遷移・集約)の対応表を自分で書ける様になる好例。', ins: ['6\n1 2 3 4\n', '5\n5 1 4\n', '7\n3 3 1\n', '10\n5 5 5\n', '1\n1 1\n', '9\n4 5 2\n'] })

t({ lv: 658, concept: 'ゲーム: 平方数を取るゲームの必勝判定', title: '平方数だけ取れる石取り', tags: ['ゲーム'], io: '石の数 n (1以上) が1行で与えられます。', ask: '交互に「正の平方数(1,4,9,…)個」の石を取り、取れなくなった(石が0で手番が来た)方が負けです。双方最善で先手が勝つなら first、後手なら second を出力してください。', h1: '石取りゲームのDP(既出)の手の集合を平方数に変えた形。', h2: 'win[k] = ある平方数sでwin[k−s]が負け。', ref: 'n=int(input())\nwin=[False]*(n+1)\nfor k in range(1,n+1):\n    s=1\n    while s*s<=k:\n        if not win[k-s*s]:\n            win[k]=True\n            break\n        s+=1\nprint("first" if win[n] else "second")', tip: '負け位置(0,2,5,7,10,…)には未解明の構造があり、その密度が正かどうかは未解決に近い難問。ルールの集合を差し替えるだけでゲームDPが別世界になる見本。', ins: ['1\n', '2\n', '3\n', '5\n', '7\n', '10\n'] })

t({ lv: 659, concept: 'シミュレーション: 倍加と加算の命令列', title: 'IとDの計算機', tags: ['シミュレーション'], io: 'I(1を足す)と D(2倍する)からなる命令列が1行で与えられます。0から始めます。', ask: '命令列を実行した後の値を出力してください。', h1: '素直に左から実行。', h2: '1文字ずつ分岐。', ref: 's=input()\nx=0\nfor c in s:\n    if c=="I":\n        x+=1\n    else:\n        x*=2\nprint(x)', tip: 'この命令列は目標の数の2進表記と1対1対応する(Dが桁送り、Iが最下位ビット)。1にする最小操作(同レベル既出)の逆再生が、まさにこの命令列の最短版。', ins: ['IDID\n', 'III\n', 'D\n', 'IDD\n', 'IIDI\n', 'IDIDID\n'] })

t({ lv: 660, concept: 'ソート: コスパ最強の品物', title: '単価あたりの王者', tags: ['ソート'], io: '1行目に品数 n、続く n 行に「重さ 価値」が与えられます。', ask: '重さあたりの価値が最大の品物の番号(1始まり、同率なら最小)を出力してください。', h1: '比の比較は分数で厳密に。', h2: 'v1/w1 と v2/w2 の比較は v1×w2 と v2×w1 の比較。', ref: 'n=int(input())\nbw,bv,bi=1,-1,0\nfor i in range(1,n+1):\n    w,v=map(int,input().split())\n    if v*bw>bv*w:\n        bw,bv,bi=w,v,i\nprint(bi)', tip: '交差乗算による分数比較は浮動小数の丸めから完全に自由で、同率の判定も厳密。分数ナップサック(同レベル既出)のソートキーの正しい実装がこれ。', ins: ['3\n2 10\n3 9\n1 4\n', '1\n5 5\n', '2\n4 8\n2 4\n', '3\n10 1\n1 9\n2 4\n', '2\n3 7\n2 5\n', '4\n1 1\n1 2\n1 3\n1 4\n'] })

t({ lv: 661, concept: '数え上げ: 値域k以下の区間の数', title: '荒れていない期間を数える', tags: ['数え上げ'], io: '1行目に k、2行目に整数列が与えられます。', ask: '区間内の最大と最小の差が k 以下である連続部分配列(長さ1以上)の個数を出力してください。', h1: '最長(同レベル既出)の数え上げ版。', h2: '総当たりで最大最小を持ち回るO(n²)が基準解。', ref: 'k=int(input())\na=list(map(int,input().split()))\nn=len(a)\ncnt=0\nfor i in range(n):\n    lo=hi=a[i]\n    for j in range(i,n):\n        if a[j]<lo:\n            lo=a[j]\n        if a[j]>hi:\n            hi=a[j]\n        if hi-lo<=k:\n            cnt+=1\n        else:\n            break\nprint(cnt)', tip: 'iを固定するとjについて条件は単調(壊れたら二度と直らない)なのでbreakできる——この単調性こそが二点法+両デックのO(n)解の存在理由でもある。', ins: ['1\n1 2 4\n', '0\n2 2 2\n', '10\n1 5 9\n', '1\n3 5\n', '2\n1 3 5\n', '5\n7\n'] })

t({ lv: 662, concept: 'DP: 最大の正方形はいくつあるか', title: 'チャンピオン正方形の数', tags: ['DP', 'グリッド'], io: '1行目に H W、続く H 行に 0/1 の文字列が与えられます。', ask: '全て1でできた正方形のうち最大サイズのものが何箇所あるかを出力してください(1が無ければ 0)。', h1: '最大サイズ(同レベル既出)を求めてから数える。', h2: 'dp値が最大に等しいマスを数える。', ref: 'h,w=map(int,input().split())\ng=[input() for _ in range(h)]\ndp=[[0]*w for _ in range(h)]\nbest=0\nfor i in range(h):\n    for j in range(w):\n        if g[i][j]=="1":\n            if i==0 or j==0:\n                dp[i][j]=1\n            else:\n                dp[i][j]=min(dp[i-1][j],dp[i][j-1],dp[i-1][j-1])+1\n            if dp[i][j]>best:\n                best=dp[i][j]\nprint(sum(1 for i in range(h) for j in range(w) if dp[i][j]==best) if best>0 else 0)', tip: 'dp[i][j]は「(i,j)を右下隅とする最大正方形の辺」なので、右下隅の位置と正方形が1対1——数える対象の同一視が正確に決まっているから二重計上が起きない。', ins: ['2 3\n110\n110\n', '2 2\n11\n11\n', '1 3\n101\n', '2 4\n1111\n1111\n', '1 1\n0\n', '3 3\n111\n111\n111\n'] })

t({ lv: 663, concept: '文字列: 隣り合う桁の和の列', title: '隣同士を足した数列', tags: ['文字列'], io: '数字だけの文字列(2桁以上)が1行で与えられます。', ask: '隣り合う桁の和を順に空白区切りで出力してください。', h1: 'zipで隣接ペア。', h2: 'int変換して足す。', ref: 's=input()\nprint(" ".join(str(int(a)+int(b)) for a,b in zip(s,s[1:])))', tip: 'パスカルの三角形を1行作る操作と同じ畳み込みで、繰り返すと二項係数の重みが現れる。zip(s, s[1:])の隣接ペアイディオムの最小の練習台。', ins: ['12345\n', '11\n', '505\n', '99\n', '1234\n', '87\n'] })

t({ lv: 664, concept: 'リスト: 対応する要素の和の最大', title: '上下ペアの最強コンビ', tags: ['リスト'], io: '1行目と2行目に同じ長さの整数列が与えられます。', ask: '同じ位置どうしの和の最大を出力してください。', h1: 'zipで対応させてmax。', h2: '1行で書ける。', ref: 'a=list(map(int,input().split()))\nb=list(map(int,input().split()))\nprint(max(x+y for x,y in zip(a,b)))', tip: '2つの系列の同時点の合計(合算負荷のピークなど)は、要素ごとの演算+集約の最小形。maxをmin・absに替えるだけの姉妹問題が量産できる基本パターン。', ins: ['1 2 3\n3 2 1\n', '5\n5\n', '1 1\n1 9\n', '-1 -2\n-3 -4\n', '0 10\n10 0\n', '2 4 6\n1 3 5\n'] })

t({ lv: 665, concept: 'DP: 最大部分和の区間の位置', title: '一番稼いだ期間はいつ', tags: ['DP'], io: '整数列が1行で空白区切りで与えられます。', ask: '和が最大の連続部分配列(長さ1以上)の位置を「左 右」(1始まり)で出力してください(最大が複数なら左が最小、次に右が最小のもの)。', h1: '最大部分和(同レベル既出)のargmax版。', h2: 'タイブレークまで確実にするなら総当たりが安全。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nbest=None\nbl=br=0\nfor i in range(n):\n    s=0\n    for j in range(i,n):\n        s+=a[j]\n        if best is None or s>best:\n            best=s\n            bl,br=i+1,j+1\nprint(bl,br)', tip: '値だけならカダネ法O(n)だが、「同点の中で位置最小」の保証には更新条件の設計が要る。仕様のタイブレーク1行が実装の難度を変える、を体感する問題。', ins: ['1 -2 3\n', '1 2 3\n', '-1 -2\n', '2 -1 2\n', '1 2 -100 3\n', '5\n'] })

t({ lv: 666, concept: 'DP: 円環の最小部分和', title: '輪の中の一番の冷え込み', tags: ['DP'], io: '整数列(円環状に並ぶ)が1行で空白区切りで与えられます。', ask: '円環上の連続部分配列(長さ1以上、全体は不可…ではなく全体も可)の和の最小を出力してください。ただし端をまたいでもよいものとします。', h1: '環状の最大部分和(同レベル既出)の鏡像。', h2: 'またぐ最小は「全体−またがない最大」。全体が最大と一致する退化に注意。', ref: 'a=list(map(int,input().split()))\ntotal=sum(a)\ndef kad(sign):\n    best=cur=a[0]*sign\n    for x in a[1:]:\n        v=x*sign\n        cur=v+max(0,cur)\n        if cur>best:\n            best=cur\n    return best*sign if sign==1 else -best\nmx=kad(1)\nmn=kad(-1)\nif mx==total:\n    print(mn)\nelse:\n    print(min(mn,total-mx))', tip: 'またぐ区間の和=全体−(またがない補区間の和)という補集合変換が芯。最大側と同じ退化(補区間が空)の罠が符号を替えて現れるのが、鏡像問題の教育的なところ。', ins: ['3 -1 2\n', '1 2 3\n', '-5 3 -5\n', '2 2\n', '-1 -2 -3\n', '5 -3 5\n'] })

t({ lv: 667, concept: '数え上げ: 積が負になる区間の数', title: 'マイナスに落ちる区間', tags: ['数え上げ'], io: '0を含まない整数列が1行で空白区切りで与えられます。', ask: '要素の積が負になる連続部分配列の個数を出力してください。', h1: '積の符号は負の個数の偶奇だけで決まる。', h2: '負の個数の偶奇の累積が異なる2点の組を数える。', ref: 'a=list(map(int,input().split()))\ncnt=[1,0]\np=0\nans=0\nfor x in a:\n    if x<0:\n        p^=1\n    ans+=cnt[1-p]\n    cnt[p]+=1\nprint(ans)', tip: '積の正負を「負の個数のパリティ累積」に写すと、0/1同数区間(既出)と同じペア勘定になる。値の掛け算を一切せずに符号だけ追う、が桁あふれ知らずの美点。', ins: ['1 -2 3\n', '1 2\n', '-1\n', '-1 -2\n', '-1 2 -3\n', '1 -1 1 -1\n'] })

t({ lv: 668, concept: 'スタック: 3種類の括弧の対応判定', title: '丸角波の三重奏', tags: ['スタック'], io: '( ) [ ] { } からなる文字列が1行で与えられます。', ask: '3種類の括弧が全て正しく対応しているなら yes、そうでなければ no を出力してください。', h1: '1種類の対応判定のスタックに「種類の一致」を足す。', h2: '閉じ括弧が来たらスタックの頭と照合。', ref: 's=input()\npair={")":"(","]":"[","}":"{"}\nst=[]\nok=True\nfor c in s:\n    if c in "([{":\n        st.append(c)\n    else:\n        if not st or st[-1]!=pair[c]:\n            ok=False\n            break\n        st.pop()\nprint("yes" if ok and not st else "no")', tip: 'コンパイラの構文検査の第一歩で、「深さだけでは足りず種類の照合が要る」のが1種類版との本質差。([)]のような交差だけを弾ける仕組みがスタックのLIFOそのもの。', ins: ['([{}])\n', '([)]\n', '{}[]()\n', '(\n', '()]\n', '([]{})\n'] })

t({ lv: 669, concept: '整数: その月の日曜日の回数', title: 'カレンダーの赤い日を数える', tags: ['整数'], io: '1行目にその月の日数、2行目に1日の曜日(0=日曜, 1=月曜, …, 6=土曜)が与えられます。', ask: 'その月に日曜日が何回あるかを出力してください。', h1: '日付kの曜日は (初日の曜日+k−1) mod 7。', h2: '数式一発でも、ループで数えても。', ref: 'days=int(input())\nfirst=int(input())\nprint(sum(1 for k in range(days) if (first+k)%7==0))', tip: '答えは4か5にしかならない(28〜31日の月で日曜が6回はあり得ない)。曜日計算の剰余モデルはカレンダーAPIが無い環境での定番の手作業になる。', ins: ['30\n0\n', '28\n0\n', '31\n6\n', '30\n1\n', '7\n3\n', '1\n0\n'] })

t({ lv: 670, concept: '文字列: 共通の文字だけ残す', title: '相手にもある文字だけ生かす', tags: ['文字列'], io: '1行目と2行目に文字列が与えられます。', ask: '1行目の文字列から「2行目にも現れる文字」だけを元の順で残した文字列を出力してください(1文字も残らなければ -)。', h1: '共通の文字を取り除く(既出)の裏返し。', h2: '2行目の文字集合に入っている文字だけjoin。', ref: 's=input()\nt=set(input())\nr="".join(c for c in s if c in t)\nprint(r if r else "-")', tip: 'フィルタの条件をnot inからinへ返すだけの対問題だが、「残す」と「消す」で頭の中の述語が反転する。集合を先に作るO(1)判定の作法は共通。', ins: ['abcdef\nbdf\n', 'hello\nlo\n', 'abc\nxyz\n', 'aab\nab\n', 'xyz\nzzz\n', 'test\nt\n'] })

t({ lv: 671, concept: 'DP: 単語単位の編集距離', title: '文と文の距離', tags: ['DP'], io: '1行目と2行目に単語の列(空白区切り)が与えられます。', ask: '単語の挿入・削除・置換をそれぞれ1操作として、一方の列を他方に変える最小操作数を出力してください。', h1: '文字の編集距離(既出)の要素を単語に変えるだけ。', h2: 'リストどうしの比較でDP表を埋める。', ref: 'a=input().split()\nb=input().split()\nm,n=len(a),len(b)\ndp=[[0]*(n+1) for _ in range(m+1)]\nfor i in range(m+1):\n    dp[i][0]=i\nfor j in range(n+1):\n    dp[0][j]=j\nfor i in range(1,m+1):\n    for j in range(1,n+1):\n        c=0 if a[i-1]==b[j-1] else 1\n        dp[i][j]=min(dp[i-1][j]+1,dp[i][j-1]+1,dp[i-1][j-1]+c)\nprint(dp[m][n])', tip: '編集距離のアルファベットは文字である必要がない——トークン列なら何でも同じDPが走る。機械翻訳の評価(WER: 単語誤り率)の分子はまさにこの値。', ins: ['the cat sat\nthe dog sat\n', 'a b c\na c\n', 'x\ny z\n', 'a b\na b\n', 'one two three\nthree two one\n', 'a\nb\n'] })

t({ lv: 672, concept: 'ハッシュ: 共通する最長の単語', title: '二人の語彙の最長一致', tags: ['ハッシュ'], io: '1行目と2行目に単語の列(空白区切り)が与えられます。', ask: '両方に現れる単語のうち最長のものを出力してください(同じ長さなら辞書順最小、無ければ none)。', h1: '集合の積を取ってから選ぶ。', h2: '(−長さ, 単語) の最小。', ref: 'A=set(input().split())\nB=set(input().split())\nC=A&B\nprint(min(C,key=lambda w:(-len(w),w)) if C else "none")', tip: '文字単位の最長共通部分文字列(既出)が高価なDPだったのに対し、単語単位なら集合の積で一瞬。粒度を変えると計算の景色が変わる、トークン化の御利益。', ins: ['apple dog cat\ncat elephant apple\n', 'a b\nc d\n', 'hi yo\nyo hi\n', 'x\nx\n', 'abc ab\nab abc\n', 'dog\ncat\n'] })

t({ lv: 673, concept: '数え上げ: 単調な区間の総数', title: '揺れない区間を全部数える', tags: ['数え上げ'], io: '整数列が1行で空白区切りで与えられます。', ask: '広義単調増加または広義単調減少である連続部分配列(長さ1以上)の個数を出力してください(両方に該当する定数区間は1回だけ数えます)。', h1: '重複(定数区間)の二重計上に注意。', h2: '増加の数+減少の数−定数の数(包除)。総当たりでもよい。', ref: 'a=list(map(int,input().split()))\nn=len(a)\ncnt=0\nfor i in range(n):\n    inc=dec=True\n    for j in range(i,n):\n        if j>i:\n            if a[j]<a[j-1]:\n                inc=False\n            if a[j]>a[j-1]:\n                dec=False\n        if inc or dec:\n            cnt+=1\n        else:\n            break\nprint(cnt)', tip: '「増加でも減少でもある」区間(定数)の扱いが包除原理のミニ演習になっている。ラン(単調な連なり)ごとの三角数で数えるO(n)解への足がかりも同じ観察。', ins: ['1 2 1\n', '1 1\n', '1 2 3\n', '3 1 2\n', '5\n', '2 2 1\n'] })

t({ lv: 674, concept: 'いもす: 重みつきの最大の重なり', title: '一番の書き入れどき', tags: ['いもす', '区間'], io: '1行目に n、続く n 行に「l r w」(時刻lからrまで([l,r))重みwの負荷)が与えられます。', ask: 'ある瞬間の負荷(重なっている区間の重みの合計)の最大を出力してください。', h1: '会議室数(重みなし)の重みつき版。', h2: 'lで+w、rで−wのいもす法。', ref: 'n=int(input())\nevents=[]\nmx=0\nfor _ in range(n):\n    l,r,w=map(int,input().split())\n    events.append((l,w))\n    events.append((r,-w))\n    if r>mx:\n        mx=r\nimos=[0]*(mx+2)\nfor t2,d in events:\n    imos[t2]+=d\ncur=0\nbest=0\nfor t2 in range(mx+1):\n    cur+=imos[t2]\n    if cur>best:\n        best=cur\nprint(best)', tip: 'サーバーの同時負荷、電力のピーク需要——重みつきの重なり最大は容量設計の核になる数。+1/−1を+w/−wへ替えるだけで、いもす法が重みに自然に一般化する。', ins: ['3\n1 5 2\n2 6 3\n0 3 1\n', '1\n0 10 5\n', '2\n0 2 3\n2 4 4\n', '2\n0 5 1\n1 3 10\n', '3\n0 2 1\n1 3 1\n2 4 1\n', '2\n5 6 7\n0 1 2\n'] })

t({ lv: 675, concept: 'リスト: 最長増加区間の開始位置', title: '一番長い上り坂の入口', tags: ['リスト'], io: '整数列が1行で空白区切りで与えられます。', ask: '厳密に増加する最長の連続区間のうち最も左のものの開始位置(1始まり)を出力してください。', h1: '最長の長さ(同レベル既出)のarg版。', h2: '「より長いときだけ」更新すれば最左が残る。', ref: 'a=list(map(int,input().split()))\nbest=1\nstart=1\nrun=1\ncur=1\nfor i in range(1,len(a)):\n    if a[i]>a[i-1]:\n        run+=1\n    else:\n        run=1\n        cur=i+1\n    if run>best:\n        best=run\n        start=cur\nprint(start)', tip: '長さと開始位置の2変数を並走させ、リセット時に開始候補を記録する——ラン系のargmax復元の共通形。等号を入れるか(>か>=)が最左と最右を分ける。', ins: ['1 2 1 2 3\n', '5\n', '3 2 1\n', '1 2 3 1 2 3 4\n', '2 2 2\n', '1 3 2 4 6\n'] })

export const CATALOG = TASKS
