// 生成タスク 第13波：2次元グリッド操作。整数/文字列=採点一意。
const TASKS = []
const t = (obj) => TASKS.push(obj)

const GRID = ['2 3\n1 2 3\n4 5 6\n', '3 3\n1 2 3\n4 5 6\n7 8 9\n', '2 2\n1 2\n3 4\n', '1 3\n7 8 9\n', '3 1\n5\n6\n7\n', '2 2\n9 8\n7 6\n']
const SQ = ['3 3\n1 2 3\n4 5 6\n7 8 9\n', '2 2\n1 2\n3 4\n', '1 1\n5\n', '3 3\n1 0 0\n0 1 0\n0 0 1\n', '2 2\n9 8\n7 6\n', '4 4\n1 2 3 4\n5 6 7 8\n9 10 11 12\n13 14 15 16\n']

t({ lv: 50, concept: 'グリッド: 90度回転', title: 'グリッドを時計回りに90度回転', tags: ['2次元リスト', 'zip'], io: '1行目に H W、続く H 行に行列が与えられます。', ask: '時計回りに90度回転した行列を出力してください。', h1: '行を逆順にして転置。', h2: 'zip(*g[::-1])。', ref: 'h,w=map(int,input().split())\ng=[input().split() for _ in range(h)]\nfor row in zip(*g[::-1]):\n    print(*row)', ins: GRID, tip: '💡 時計回り90度回転は zip(*g[::-1])。' })
t({ lv: 50, concept: 'グリッド: 上下反転', title: 'グリッドの上下反転', tags: ['2次元リスト'], io: '1行目に H W、続く H 行に行列が与えられます。', ask: '行の並びを上下に反転して出力してください。', h1: '行リストを逆順。', h2: 'g[::-1]。', ref: 'h,w=map(int,input().split())\ng=[input() for _ in range(h)]\nfor row in g[::-1]:\n    print(row)', ins: GRID })
t({ lv: 50, concept: 'グリッド: 左右反転', title: 'グリッドの左右反転', tags: ['2次元リスト', 'スライス'], io: '1行目に H W、続く H 行に行列が与えられます。', ask: '各行の要素を左右反転して出力してください。', h1: '各行を逆順。', h2: 'row[::-1]。', ref: 'h,w=map(int,input().split())\nfor _ in range(h):\n    print(*input().split()[::-1])', ins: GRID })
t({ lv: 50, concept: 'グリッド: 列の和', title: '各列の和', tags: ['2次元リスト', 'zip'], io: '1行目に H W、続く H 行に整数行列が与えられます。', ask: '各列の和を空白区切りで出力してください。', h1: 'zip で列を取る。', h2: '列ごとに sum。', ref: 'h,w=map(int,input().split())\ng=[list(map(int,input().split())) for _ in range(h)]\nprint(*[sum(col) for col in zip(*g)])', ins: GRID })
t({ lv: 50, concept: 'グリッド: 副対角の和', title: '副対角成分の和', tags: ['2次元リスト'], io: '1行目に n、続く n 行に n×n の整数行列が与えられます。', ask: '右上から左下への副対角成分の和を出力してください。', h1: 'g[i][n-1-i]。', h2: 'i=0..n-1。', ref: 'n=int(input())\ng=[list(map(int,input().split())) for _ in range(n)]\nprint(sum(g[i][n-1-i] for i in range(n)))', ins: ['3\n1 2 3\n4 5 6\n7 8 9\n', '2\n1 2\n3 4\n', '1\n5\n', '3\n1 0 0\n0 1 0\n0 0 1\n', '2\n9 8\n7 6\n', '4\n1 2 3 4\n5 6 7 8\n9 10 11 12\n13 14 15 16\n'] })
t({ lv: 50, concept: 'グリッド: 最大値の位置', title: 'グリッドの最大値の位置', tags: ['2次元リスト'], io: '1行目に H W、続く H 行に整数行列が与えられます。', ask: '最大値の (行 列) を0始まりで出力してください (複数あれば最も上、同行なら最も左)。', h1: '全マスを走査。', h2: '今の最大を更新。', ref: 'h,w=map(int,input().split())\ng=[list(map(int,input().split())) for _ in range(h)]\nbi,bj=0,0\nfor i in range(h):\n    for j in range(w):\n        if g[i][j]>g[bi][bj]:\n            bi,bj=i,j\nprint(bi,bj)', ins: GRID })
t({ lv: 50, concept: 'グリッド: スパイラル順', title: 'グリッドを渦巻き順に', tags: ['2次元リスト'], io: '1行目に H W、続く H 行に整数行列が与えられます。', ask: '外周から内側へ時計回り (渦巻き) に読んだ順で空白区切りで出力してください。', h1: '上端→右端→下端→左端を縮めながら。', h2: '4方向を順に。', ref: 'h,w=map(int,input().split())\ng=[list(map(int,input().split())) for _ in range(h)]\nres=[]\ntop,bot,left,right=0,h-1,0,w-1\nwhile top<=bot and left<=right:\n    for j in range(left,right+1):\n        res.append(g[top][j])\n    top+=1\n    for i in range(top,bot+1):\n        res.append(g[i][right])\n    right-=1\n    if top<=bot:\n        for j in range(right,left-1,-1):\n            res.append(g[bot][j])\n        bot-=1\n    if left<=right:\n        for i in range(bot,top-1,-1):\n            res.append(g[i][left])\n        left+=1\nprint(*res)', ins: GRID })
t({ lv: 600, concept: 'グリッド: 島の数', title: '島の数 (連結成分)', tags: ['グラフ', 'BFS', 'アルゴリズム'], io: '1行目に H W、続く H 行に 0/1 のグリッドが与えられます。', ask: '上下左右に繋がった 1 のかたまり (島) の個数を出力してください。', h1: '未訪問の1からBFS/DFS。', h2: '塗りつぶした回数が島の数。', ref: 'from collections import deque\nh,w=map(int,input().split())\ng=[input().split() for _ in range(h)]\nseen=[[False]*w for _ in range(h)]\ncnt=0\nfor i in range(h):\n    for j in range(w):\n        if g[i][j]=="1" and not seen[i][j]:\n            cnt+=1\n            dq=deque([(i,j)])\n            seen[i][j]=True\n            while dq:\n                y,x=dq.popleft()\n                for dy,dx in ((1,0),(-1,0),(0,1),(0,-1)):\n                    ny,nx=y+dy,x+dx\n                    if 0<=ny<h and 0<=nx<w and g[ny][nx]=="1" and not seen[ny][nx]:\n                        seen[ny][nx]=True\n                        dq.append((ny,nx))\nprint(cnt)', ins: ['3 3\n1 1 0\n0 1 0\n0 0 1\n', '2 2\n1 1\n1 1\n', '3 3\n1 0 1\n0 0 0\n1 0 1\n', '1 4\n1 0 1 1\n', '2 3\n0 0 0\n0 0 0\n', '3 3\n1 1 1\n1 1 1\n1 1 1\n'], tip: '💡 グリッドの連結成分はBFS/DFSで塗りつぶす定番。' })

export const CATALOG = TASKS
