// 生成タスク 第21波：lv51〜84 の空き段を別計算で埋める。既存と重複しない概念のみ。1段=1問。
const TASKS = []
const t = (obj) => TASKS.push(obj)

// 文字列 (51-59)
t({ lv: 51, concept: '文字列: 埋め込まれた数字の和', title: '文字列中の数字の合計', tags: ['文字列'], io: '文字列 s が与えられます。', ask: 's に含まれる数字 (0-9) の合計を出力してください。', h1: 'isdigit で数字を選ぶ。', h2: 'int にして合計。', ref: 's=input()\nprint(sum(int(c) for c in s if c.isdigit()))', ins: ['a1b2c3\n', 'abc\n', '12 34\n', 'x9y\n', '0\n', '7a7\n'] })
t({ lv: 52, concept: '文字列: 交互の大文字小文字', title: '交互に大文字小文字', tags: ['文字列'], io: '文字列 s が与えられます。', ask: '偶数番目(0始まり)を大文字、奇数番目を小文字にして出力してください。', h1: 'enumerate で位置。', h2: 'i%2 で分岐。', ref: 's=input()\nprint("".join(c.upper() if i%2==0 else c.lower() for i,c in enumerate(s)))', ins: ['hello\n', 'abcdef\n', 'x\n', 'Test\n', 'aaaa\n', 'python\n'] })
t({ lv: 53, concept: '文字列: 初出の文字だけ残す', title: '文字の重複除去 (順序保持)', tags: ['文字列'], io: '文字列 s が与えられます。', ask: '各文字を初めて現れた順に1回だけ残した文字列を出力してください。', h1: 'dict.fromkeys は順序維持。', h2: '初出のみ。', ref: 'print("".join(dict.fromkeys(input())))', ins: ['banana\n', 'aabbcc\n', 'abc\n', 'mississippi\n', 'xxyy\n', 'hello\n'] })
t({ lv: 54, concept: '文字列: 2番目に多い文字', title: '2番目に多い文字', tags: ['文字列', 'collections'], io: '相異なる文字を2種類以上含む文字列が与えられます。', ask: '出現回数が2番目に多い文字を出力してください (同数なら文字の小さい方)。', h1: 'Counter で回数。', h2: '(-回数, 文字) でソートして2番目。', ref: 'from collections import Counter\nc=Counter(input())\nprint(sorted(c, key=lambda x:(-c[x],x))[1])', ins: ['aabbbc\n', 'aaabbc\n', 'xxyyz\n', '112233\n', 'abcde\n', 'wwwooo\n'] })
t({ lv: 55, concept: '文字列: シーザー復号', title: 'シーザー暗号の復号 (-3)', tags: ['文字列'], io: '英小文字の文字列 s が与えられます。', ask: '各文字を3つ前へ戻して復号した文字列を出力してください (a の3つ前は x)。', h1: '-3 して 26 で剰余。', h2: 'chr で戻す。', ref: 's=input()\nprint("".join(chr((ord(c)-97-3)%26+97) for c in s))', ins: ['def\n', 'abc\n', 'khoor\n', 'xyz\n', 'aaa\n', 'sbwkrq\n'] })
t({ lv: 56, concept: '文字列: 最長の数字列', title: '最長の連続数字列の長さ', tags: ['文字列'], io: '文字列 s が与えられます。', ask: '数字が連続する最長の長さを出力してください。', h1: '数字で伸ばし、非数字でリセット。', h2: '最大を更新。', ref: 's=input()\nbest=cur=0\nfor c in s:\n    cur=cur+1 if c.isdigit() else 0\n    best=max(best,cur)\nprint(best)', ins: ['ab123cd45\n', 'abc\n', '007\n', '1a2b3\n', '9999\n', 'x\n'] })
t({ lv: 57, concept: '文字列: 文字をソート', title: '文字を昇順に並べた文字列', tags: ['文字列', 'ソート'], io: '文字列 s が与えられます。', ask: '文字を昇順に並べ替えた文字列を出力してください。', h1: 'sorted(s)。', h2: '連結。', ref: 'print("".join(sorted(input())))', ins: ['banana\n', 'cba\n', 'dcba\n', 'aaa\n', 'zyx\n', 'hello\n'] })
t({ lv: 58, concept: '文字列: 母音と子音の差', title: '母音と子音の個数差', tags: ['文字列'], io: '英小文字の文字列 s が与えられます。', ask: '母音の数と子音の数の差の絶対値を出力してください。', h1: '母音を数える。', h2: '残りが子音。', ref: 's=input()\nv=sum(1 for c in s if c in "aeiou")\nprint(abs(v-(len(s)-v)))', ins: ['hello\n', 'aeiou\n', 'xyz\n', 'banana\n', 'programming\n', 'a\n'] })
t({ lv: 59, concept: '文字列: 大文字だけ抽出', title: '大文字だけ取り出す', tags: ['文字列'], io: '文字列 s が与えられます。', ask: '大文字だけを順に並べた文字列を出力してください (無ければ空行)。', h1: 'isupper で選ぶ。', h2: '連結。', ref: 's=input()\nprint("".join(c for c in s if c.isupper()))', ins: ['HelloWorld\n', 'ABC\n', 'abc\n', 'PyThOn\n', 'Test123\n', 'aXbYc\n'] })

// リスト (61-69)
t({ lv: 61, concept: 'リスト: 偶数と奇数に分割', title: '偶数を先に奇数を後に', tags: ['list'], io: '整数列が1行で与えられます。', ask: '偶数を元の順で先に、奇数を元の順で後に並べて出力してください。', h1: '2回の内包表記。', h2: '偶数列+奇数列。', ref: 'a=list(map(int,input().split()))\nprint(*[x for x in a if x%2==0],*[x for x in a if x%2==1])', ins: ['1 2 3 4 5\n', '2 4 6\n', '1 3 5\n', '7\n', '10 11 12\n', '5 4 3 2 1\n'] })
t({ lv: 62, concept: 'リスト: 符号反転', title: '全要素の符号を反転', tags: ['list'], io: '整数列が1行で与えられます。', ask: '各要素の符号を反転して出力してください。', h1: '各 x を -x に。', h2: '内包表記。', ref: 'a=list(map(int,input().split()))\nprint(*[-x for x in a])', ins: ['1 -2 3\n', '0 0\n', '5\n', '-1 -2 -3\n', '100 -100\n', '7 8\n'] })
t({ lv: 63, concept: 'リスト: 正の数の平均', title: '正の数だけの平均', tags: ['list'], io: '整数列 (正の数を1つ以上含む) が1行で与えられます。', ask: '正の数だけの平均を小数2桁で出力してください。', h1: '正の数を集める。', h2: '和÷個数。', ref: 'a=[x for x in map(int,input().split()) if x>0]\nprint(f"{sum(a)/len(a):.2f}")', ins: ['1 -2 3 4\n', '5 5 5\n', '-1 2\n', '10 -10 20\n', '7\n', '1 2 3\n'] })
t({ lv: 64, concept: 'リスト: 0の個数', title: '0の個数', tags: ['list'], io: '整数列が1行で与えられます。', ask: '0 の個数を出力してください。', h1: 'count を使う。', h2: '"0" を数える。', ref: 'a=input().split()\nprint(a.count("0"))', ins: ['1 0 2 0 0\n', '1 2 3\n', '0\n', '0 0 0\n', '5 0 5\n', '0 1 0 1\n'] })
t({ lv: 65, concept: 'リスト: 絶対値最大の要素', title: '絶対値が最大の要素', tags: ['list'], io: '整数列が1行で与えられます。', ask: '絶対値が最大の要素を出力してください (同じ絶対値なら先に現れた方)。', h1: 'max の key に abs。', h2: 'key=abs。', ref: 'a=list(map(int,input().split()))\nprint(max(a,key=abs))', ins: ['1 -5 3\n', '-2 2\n', '0\n', '-10 5\n', '7 -7\n', '1 2 3\n'] })
t({ lv: 66, concept: 'リスト: 上位3つの和', title: '大きい方から3つの和', tags: ['list', 'ソート'], io: '整数列が1行で与えられます。', ask: '大きい方から最大3つ (要素が3未満なら全部) の和を出力してください。', h1: '降順ソート。', h2: '先頭3つ。', ref: 'a=sorted(map(int,input().split()),reverse=True)\nprint(sum(a[:3]))', ins: ['1 2 3 4 5\n', '10 20\n', '5 5 5 5\n', '100 1 2 3\n', '9\n', '3 1 4 1 5 9\n'] })
t({ lv: 67, concept: 'リスト: 最小2つの和', title: '小さい方から2つの和', tags: ['list', 'ソート'], io: '整数列が1行で与えられます。', ask: '小さい方から2つの和を出力してください。', h1: '昇順ソート。', h2: '先頭2つ。', ref: 'a=sorted(map(int,input().split()))\nprint(sum(a[:2]))', ins: ['3 1 4 1 5\n', '10 20\n', '5 5\n', '1 2 3\n', '9 8 7\n', '2 2 2\n'] })
t({ lv: 68, concept: 'リスト: 右回転', title: '配列を右に k 回転', tags: ['list', 'スライス'], io: '1行目に整数列、2行目に回転量 k が与えられます。', ask: '右に k 個ぶん回転させた列を出力してください。', h1: 'k を長さで割った余り。', h2: 'a[-k:]+a[:-k]。', ref: 'a=list(map(int,input().split()))\nk=int(input())%len(a)\nprint(*(a[-k:]+a[:-k] if k else a))', ins: ['1 2 3 4 5\n2\n', '1 2 3\n0\n', '1 2 3 4\n4\n', '5 6 7\n1\n', '10 20\n3\n', '1 2 3 4 5\n5\n'] })
t({ lv: 69, concept: 'リスト: 平均から最も遠い要素', title: '平均から最も離れた要素', tags: ['list'], io: '整数列が1行で与えられます。', ask: '平均との差の絶対値が最大の要素を出力してください (同じなら先に現れた方)。', h1: '平均を出す。', h2: 'max(key=平均との距離)。', ref: 'a=list(map(int,input().split()))\nm=sum(a)/len(a)\nprint(max(a,key=lambda x:abs(x-m)))', ins: ['1 2 3 100\n', '5 5 5\n', '1 10\n', '3 1 4 1 5\n', '7\n', '0 100 50\n'] })

// 数の応用 (71-79)
t({ lv: 71, concept: '整数: 立方数か', title: '立方数か', tags: ['整数'], io: '正の整数 n が与えられます。', ask: 'ある整数の3乗で表せれば yes、そうでなければ no を出力してください。', h1: 'i³<n の間 i を増やす。', h2: 'i³==n か。', ref: 'n=int(input())\ni=0\nwhile i*i*i<n:\n    i+=1\nprint("yes" if i*i*i==n else "no")', ins: ['27\n', '8\n', '9\n', '64\n', '1\n', '30\n'] })
t({ lv: 72, concept: '整数: 桁を昇順', title: '桁を昇順に並べた数', tags: ['整数', 'ソート'], io: '非負整数 n が与えられます。', ask: '桁を小さい順に並べてできる数を出力してください (先頭0は消える)。', h1: '文字をソート。', h2: 'int に戻す。', ref: 'n=input()\nprint(int("".join(sorted(n))))', ins: ['321\n', '1234\n', '100\n', '999\n', '510\n', '40\n'] })
t({ lv: 73, concept: '整数: 各桁の2乗和', title: '各桁の2乗の和', tags: ['整数'], io: '非負整数 n が与えられます。', ask: '各桁の数字を2乗して合計したものを出力してください。', h1: '桁ごとに c²。', h2: '合計。', ref: 'n=input()\nprint(sum(int(c)**2 for c in n))', ins: ['123\n', '9\n', '100\n', '44\n', '5\n', '321\n'] })
t({ lv: 74, concept: '整数: 反転して足す', title: '元の数と逆順の数の和', tags: ['整数'], io: '正の整数 n が与えられます。', ask: 'n と「n の桁を逆順にした数」の和を出力してください。', h1: '逆順は str[::-1]。', h2: '足す。', ref: 'n=int(input())\nprint(n+int(str(n)[::-1]))', ins: ['12\n', '123\n', '5\n', '100\n', '99\n', '47\n'] })
t({ lv: 75, concept: 'ビット: 下位kビット', title: '下位 k ビットの値', tags: ['ビット演算'], io: '非負整数 n と k が空白区切りで与えられます。', ask: 'n の下位 k ビットだけを取り出した値を出力してください。', h1: 'マスク (1<<k)-1。', h2: 'n & マスク。', ref: 'n,k=map(int,input().split())\nprint(n&((1<<k)-1))', ins: ['13 2\n', '255 4\n', '8 3\n', '7 1\n', '100 0\n', '1024 5\n'] })
t({ lv: 76, concept: '整数: べき乗の下1桁', title: 'a の b 乗の下1桁', tags: ['モジュラ'], io: '非負整数 a b が空白区切りで与えられます。', ask: 'a の b 乗の下1桁 (10で割った余り) を出力してください。', h1: 'pow(a,b,10)。', h2: '3引数 pow。', ref: 'a,b=map(int,input().split())\nprint(pow(a,b,10))', ins: ['2 10\n', '3 4\n', '7 2\n', '5 3\n', '9 9\n', '2 0\n'] })
t({ lv: 77, concept: '整数: べき乗の桁数', title: 'a の b 乗の桁数', tags: ['整数'], io: '正の整数 a b が空白区切りで与えられます。', ask: 'a の b 乗の桁数を出力してください。', h1: '実際に計算して文字列化。', h2: 'len(str(a**b))。', ref: 'a,b=map(int,input().split())\nprint(len(str(a**b)))', ins: ['2 10\n', '3 4\n', '10 3\n', '5 5\n', '2 1\n', '9 2\n'] })
t({ lv: 78, concept: '数列: 調和数', title: '調和数の整数部', tags: ['数列'], io: '正の整数 n が与えられます。', ask: '1 + 1/2 + … + 1/n の整数部分を出力してください。', h1: '1/i を足す。', h2: 'int で切り捨て。', ref: 'n=int(input())\nprint(int(sum(1/i for i in range(1,n+1))))', ins: ['1\n', '4\n', '10\n', '100\n', '2\n', '11\n'], tip: '💡 調和数は緩やかに発散し、おおよそ ln(n) で増える。' })
t({ lv: 79, concept: '整数: 逆三角数', title: '何番目の三角数か', tags: ['数列'], io: '正の整数 n が与えられます。', ask: 'n が k 番目の三角数 k(k+1)/2 ならその k を、三角数でなければ -1 を出力してください。', h1: '三角数を順に作る。', h2: '一致する k。', ref: 'n=int(input())\nk=1\nwhile k*(k+1)//2<n:\n    k+=1\nprint(k if k*(k+1)//2==n else -1)', ins: ['10\n', '15\n', '11\n', '1\n', '21\n', '6\n'] })

// 2列・集計 (81-84)
t({ lv: 81, concept: 'リスト: 要素ごとの最大', title: '2列の要素ごとの最大', tags: ['list', 'zip'], io: '2つの同じ長さの整数列が各行で与えられます。', ask: '位置ごとに大きい方を取った列を出力してください。', h1: 'zip で対応づけ。', h2: '各組で max。', ref: 'a=list(map(int,input().split()))\nb=list(map(int,input().split()))\nprint(*[max(x,y) for x,y in zip(a,b)])', ins: ['1 5 3\n4 2 6\n', '1 2\n2 1\n', '0 0\n1 1\n', '9 8 7\n7 8 9\n', '5\n3\n', '1 1 1\n2 2 2\n'] })
t({ lv: 82, concept: 'リスト: 2列のマンハッタン距離', title: '2列のマンハッタン距離', tags: ['list', 'zip'], io: '2つの同じ長さの整数列が各行で与えられます。', ask: '位置ごとの差の絶対値の総和を出力してください。', h1: '|aᵢ−bᵢ| を足す。', h2: 'zip。', ref: 'a=list(map(int,input().split()))\nb=list(map(int,input().split()))\nprint(sum(abs(x-y) for x,y in zip(a,b)))', ins: ['1 2 3\n4 5 6\n', '0 0\n0 0\n', '5 5\n1 1\n', '1 2\n2 1\n', '10\n3\n', '1 1 1\n1 1 1\n'] })
t({ lv: 83, concept: 'リスト: 頻度表', title: '値ごとの出現回数', tags: ['collections'], io: '整数列が1行で与えられます。', ask: '出現する値を昇順に「値:回数」の形で空白区切りで出力してください。', h1: 'Counter で数える。', h2: '値を sorted。', ref: 'from collections import Counter\nc=Counter(map(int,input().split()))\nprint(*[f"{v}:{c[v]}" for v in sorted(c)])', ins: ['1 2 2 3 3 3\n', '5 5 5\n', '1 2 3\n', '7\n', '3 1 3 1\n', '9 8 9\n'] })
t({ lv: 84, concept: 'リスト: 1回だけの値', title: '1度だけ現れる値', tags: ['collections'], io: '整数列が1行で与えられます。', ask: '出現回数がちょうど1回の値を昇順に空白区切りで出力してください (無ければ空行)。', h1: 'Counter で回数。', h2: '回数1の値を集める。', ref: 'from collections import Counter\nc=Counter(map(int,input().split()))\nprint(*sorted(x for x in c if c[x]==1))', ins: ['1 1 2 3 3\n', '1 2 3\n', '5 5\n', '7 7 8 9 9\n', '4\n', '1 1 1\n'] })

export const CATALOG = TASKS
