// 生成タスク 第36波：lv501〜549。lv500(再帰・二分探索)とlv550(貪欲・バックトラッキング)の橋渡し。
// 二分探索(答えで二分)/分割統治/単調スタック/バックトラッキング/再帰の本物の別問題。
// 重複なし・決定的・採点一意(整数/文字列/列出力のみ)。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 501, concept: '二分探索: 最小距離の最大化', title: '牛を配置する最大の最小間隔', tags: ['二分探索'], io: '1行目に位置数 n と牛の数 k、2行目に n 個の位置が与えられます。', ask: 'k 頭の牛を置くとき、隣り合う牛の最小間隔を最大化した値を出力してください。', h1: '答え(間隔)で二分探索する。', h2: '貪欲に詰めて k 頭置けるかで判定する。', ref: 'first=input().split()\nn=int(first[0])\nk=int(first[1])\na=sorted(map(int,input().split()))\ndef feasible(d):\n    cnt=1\n    last=a[0]\n    for x in a[1:]:\n        if x-last>=d:\n            cnt+=1\n            last=x\n    return cnt>=k\nlo=0\nhi=a[-1]-a[0]\nans=0\nwhile lo<=hi:\n    mid=(lo+hi)//2\n    if feasible(mid):\n        ans=mid\n        lo=mid+1\n    else:\n        hi=mid-1\nprint(ans)', tip: '「最小値の最大化」は答えを二分して実現可能性で判定するのが定石(パラメトリックサーチ)。', ins: ['5 3\n1 2 8 4 9\n', '5 2\n1 2 3 4 5\n', '3 3\n10 20 30\n', '4 2\n1 1 1 1\n', '2 2\n0 100\n', '6 3\n1 3 6 8 10 15\n'] })

t({ lv: 502, concept: '二分探索: 分割の最大和の最小化', title: 'k分割の最大和を最小化', tags: ['二分探索'], io: '1行目に n k、2行目に n 個の非負整数が与えられます。', ask: '配列を連続する k 個以下のグループに分けるとき、各グループの和の最大値を最小化した値を出力してください。', h1: '答え(上限)を二分探索する。', h2: '上限以下で詰めると何分割必要かで判定する。', ref: 'first=input().split()\nn=int(first[0])\nk=int(first[1])\na=list(map(int,input().split()))\ndef need(cap):\n    cnt=1\n    cur=0\n    for x in a:\n        if cur+x>cap:\n            cnt+=1\n            cur=x\n        else:\n            cur+=x\n    return cnt\nlo=max(a)\nhi=sum(a)\nans=hi\nwhile lo<=hi:\n    mid=(lo+hi)//2\n    if need(mid)<=k:\n        ans=mid\n        hi=mid-1\n    else:\n        lo=mid+1\nprint(ans)', tip: '「最大値の最小化」も答えを二分し、その上限で必要分割数が k 以下かを見る。', ins: ['5 2\n7 2 5 10 8\n', '4 2\n1 2 3 4\n', '1 1\n10\n', '5 5\n1 2 3 4 5\n', '3 1\n1 2 3\n', '6 3\n1 4 4 1 2 5\n'] })

t({ lv: 503, concept: '二分探索: 最小の食べる速さ', title: '時間内に食べ切る最小速度', tags: ['二分探索'], io: '1行目に山の数 n と制限時間 h、2行目に各山の量が与えられます。', ask: 'h 時間以内に全部食べ切れる最小の毎時速度を出力してください(1時間に1山だけ、速度分まで食べる)。', h1: '速度で二分探索する。', h2: '各山 ceil(量/速度) の合計が h 以下かで判定。', ref: 'first=input().split()\nn=int(first[0])\nh=int(first[1])\npiles=list(map(int,input().split()))\ndef hours(sp):\n    return sum((p+sp-1)//sp for p in piles)\nlo=1\nhi=max(piles)\nans=hi\nwhile lo<=hi:\n    mid=(lo+hi)//2\n    if hours(mid)<=h:\n        ans=mid\n        hi=mid-1\n    else:\n        lo=mid+1\nprint(ans)', tip: '速度↑で所要時間↓という単調性があるので答えを二分できる。切り上げは (p+sp-1)//sp。', ins: ['4 8\n3 6 7 11\n', '5 5\n30 11 23 4 20\n', '5 6\n30 11 23 4 20\n', '1 1\n5\n', '3 3\n1 1 1\n', '4 5\n1 2 3 4\n'] })

t({ lv: 504, concept: '二分探索: D日で運ぶ最小積載量', title: 'D日で運ぶ船の最小積載量', tags: ['二分探索'], io: '1行目に荷物数 n と日数 D、2行目に各荷物の重さ(順序固定)が与えられます。', ask: '荷物を順番通りに D 日以内で運び切れる船の最小積載量を出力してください。', h1: '積載量で二分探索する。', h2: '順に詰めて必要日数が D 以下かで判定。', ref: 'first=input().split()\nn=int(first[0])\nD=int(first[1])\nw=list(map(int,input().split()))\ndef days(cap):\n    d=1\n    cur=0\n    for x in w:\n        if cur+x>cap:\n            d+=1\n            cur=x\n        else:\n            cur+=x\n    return d\nlo=max(w)\nhi=sum(w)\nans=hi\nwhile lo<=hi:\n    mid=(lo+hi)//2\n    if days(mid)<=D:\n        ans=mid\n        hi=mid-1\n    else:\n        lo=mid+1\nprint(ans)', tip: '下限は最大の1個(必ず積めるため)、上限は総和(1日で運ぶ)。その間を二分する。', ins: ['10 5\n1 2 3 4 5 6 7 8 9 10\n', '3 3\n1 2 3\n', '5 1\n1 2 3 4 5\n', '5 5\n1 2 3 4 5\n', '4 2\n3 2 2 4\n', '1 1\n7\n'] })

t({ lv: 505, concept: '二分探索: 商の和を抑える最小の除数', title: '商の合計を閾値以下にする最小除数', tags: ['二分探索'], io: '1行目に n と閾値 threshold、2行目に n 個の正整数が与えられます。', ask: '各数を d で割って切り上げた値の合計が threshold 以下になる最小の正整数 d を出力してください。', h1: '除数 d で二分探索する。', h2: 'd を大きくすると合計は単調に減る。', ref: 'first=input().split()\nn=int(first[0])\nth=int(first[1])\nnums=list(map(int,input().split()))\ndef total(d):\n    return sum((x+d-1)//d for x in nums)\nlo=1\nhi=max(nums)\nans=hi\nwhile lo<=hi:\n    mid=(lo+hi)//2\n    if total(mid)<=th:\n        ans=mid\n        hi=mid-1\n    else:\n        lo=mid+1\nprint(ans)', tip: '除数を大きくすると切り上げ商の和は単調減少するので答えを二分できる。', ins: ['3 6\n1 2 5\n', '4 8\n1 2 3 4\n', '3 3\n3 3 3\n', '1 1\n100\n', '5 10\n2 3 5 7 11\n', '3 4\n1 1 1\n'] })

t({ lv: 506, concept: '二分探索: 整数平方根', title: '整数平方根(床)', tags: ['二分探索'], io: '非負整数 n が1行で与えられます。', ask: 'floor(√n) を出力してください。', h1: 'mid*mid<=n となる最大の mid を探す。', h2: '答えで二分探索する。', ref: 'n=int(input())\nlo=0\nhi=n\nans=0\nwhile lo<=hi:\n    mid=(lo+hi)//2\n    if mid*mid<=n:\n        ans=mid\n        lo=mid+1\n    else:\n        hi=mid-1\nprint(ans)', tip: '平方根の床は「mid²≤n の最大 mid」を二分探索で。浮動小数の誤差を避けられる。', ins: ['16\n', '15\n', '1\n', '0\n', '100\n', '1000000\n'] })

t({ lv: 507, concept: '二分探索: 整数k乗根', title: '整数k乗根(床)', tags: ['二分探索'], io: 'n k が空白区切りで与えられます。', ask: 'floor(n^(1/k))、すなわち mid^k<=n となる最大の非負整数 mid を出力してください。', h1: 'mid**k<=n を判定に使う。', h2: '答えで二分探索する。', ref: 'n,k=map(int,input().split())\nlo=0\nhi=n\nans=0\nwhile lo<=hi:\n    mid=(lo+hi)//2\n    if mid**k<=n:\n        ans=mid\n        lo=mid+1\n    else:\n        hi=mid-1\nprint(ans)', tip: 'k乗根も「mid^k≤n の最大 mid」で二分探索。整数演算なので誤差が出ない。', ins: ['27 3\n', '28 3\n', '16 2\n', '1 5\n', '1000 3\n', '81 4\n'] })

t({ lv: 508, concept: '二分探索: ピーク要素', title: 'ピーク要素の添字', tags: ['二分探索'], io: '整数列が1行で空白区切りで与えられます(隣接要素は相異なるとする)。', ask: '隣接要素より大きい要素(ピーク)の添字(0始まり)を1つ出力してください。', h1: '中央と右隣を比べる。', h2: '大きい側にピークが必ずある。', ref: 'a=list(map(int,input().split()))\nlo=0\nhi=len(a)-1\nwhile lo<hi:\n    mid=(lo+hi)//2\n    if a[mid]<a[mid+1]:\n        lo=mid+1\n    else:\n        hi=mid\nprint(lo)', tip: 'ピーク探索は「登り坂の側に必ず頂上がある」性質で O(log n)。', ins: ['1 2 3 1\n', '1 2 1 3 5 6 4\n', '5 4 3 2 1\n', '1\n', '1 2\n', '2 1\n'] })

t({ lv: 509, concept: '二分探索: ソート済み行列のk番目', title: '行・列ソート行列のk番目に小さい値', tags: ['二分探索'], io: '1行目に n k、続く n 行に n 個ずつ(各行・各列が昇順)の値が与えられます。', ask: '行列全体で k 番目に小さい値を出力してください。', h1: '値 x で二分し「x 以下の個数」を数える。', h2: '左下から数えると O(n) で count できる。', ref: 'first=input().split()\nn=int(first[0])\nk=int(first[1])\nmat=[list(map(int,input().split())) for _ in range(n)]\nlo=mat[0][0]\nhi=mat[n-1][n-1]\ndef count_le(x):\n    cnt=0\n    r=n-1\n    c=0\n    while r>=0 and c<n:\n        if mat[r][c]<=x:\n            cnt+=r+1\n            c+=1\n        else:\n            r-=1\n    return cnt\nwhile lo<hi:\n    mid=(lo+hi)//2\n    if count_le(mid)<k:\n        lo=mid+1\n    else:\n        hi=mid\nprint(lo)', tip: '値で二分し「以下の個数」を数える手法は、ソート済み行列のk番目に有効。', ins: ['3 8\n1 5 9\n10 11 13\n12 13 15\n', '2 2\n1 2\n3 4\n', '1 1\n5\n', '3 1\n1 2 3\n4 5 6\n7 8 9\n', '3 9\n1 2 3\n4 5 6\n7 8 9\n', '2 3\n1 3\n2 4\n'] })

t({ lv: 510, concept: '配列: 2ソート配列の中央値', title: '2つのソート配列の中央値の2倍', tags: ['配列'], io: '1行目にソート済み列 a、2行目にソート済み列 b が与えられます(空行可)。', ask: '2配列を合わせた中央値の2倍(整数)を出力してください。', h1: '2つを統合してソートする。', h2: '長さが偶数なら中央2要素の和、奇数なら中央要素の2倍。', ref: 'first=input()\na=list(map(int,first.split())) if first.strip() else []\nsecond=input()\nb=list(map(int,second.split())) if second.strip() else []\nm=sorted(a+b)\nL=len(m)\nif L%2==1:\n    print(2*m[L//2])\nelse:\n    print(m[L//2-1]+m[L//2])', tip: '中央値を2倍で答えさせると偶数長の .5 を整数で扱え、採点が一意になる。', ins: ['1 3\n2\n', '1 2\n3 4\n', '\n1\n', '1 2 3\n4 5 6\n', '5\n5\n', '1 1 1\n1 1 1\n'] })

t({ lv: 511, concept: '二分探索: 掛け算表のk番目', title: '掛け算表のk番目に小さい値', tags: ['二分探索'], io: 'm n k が空白区切りで与えられます。', ask: 'm×n の掛け算表(i行j列の値は i·j)で k 番目に小さい値を出力してください。', h1: '値 x で二分する。', h2: '各行 i で x 以下は min(x//i, n) 個。', ref: 'm,n,k=map(int,input().split())\nlo=1\nhi=m*n\nwhile lo<hi:\n    mid=(lo+hi)//2\n    cnt=0\n    for i in range(1,m+1):\n        cnt+=min(mid//i,n)\n    if cnt<k:\n        lo=mid+1\n    else:\n        hi=mid\nprint(lo)', tip: '掛け算表は明示的に作らず、各行ごとの「x以下の個数」を足して二分探索する。', ins: ['3 3 5\n', '2 3 6\n', '1 1 1\n', '3 3 9\n', '2 2 3\n', '5 5 13\n'] })

t({ lv: 512, concept: '二分探索: m束作る最小日数', title: '隣接k本でm束作る最小日数', tags: ['二分探索'], io: '1行目に n m k(花の数・束数・1束の連続本数)、2行目に各花の開花日が与えられます。', ask: 'm 束(各 k 本の連続した花)を作れる最小の日数を出力してください。不可能なら -1。', h1: '日数で二分探索する。', h2: 'その日までに咲いた花で連続 k 本の束が m 個作れるか判定。', ref: 'first=input().split()\nn=int(first[0])\nm=int(first[1])\nk=int(first[2])\nbloom=list(map(int,input().split()))\nif m*k>n:\n    print(-1)\nelse:\n    def ok(day):\n        cnt=0\n        run=0\n        for b in bloom:\n            if b<=day:\n                run+=1\n                if run==k:\n                    cnt+=1\n                    run=0\n            else:\n                run=0\n        return cnt>=m\n    lo=min(bloom)\n    hi=max(bloom)\n    ans=hi\n    while lo<=hi:\n        mid=(lo+hi)//2\n        if ok(mid):\n            ans=mid\n            hi=mid-1\n        else:\n            lo=mid+1\n    print(ans)', tip: '「最小の日数」も日数で二分し、その日に条件達成できるかの判定関数を作る。', ins: ['5 3 1\n1 10 3 10 2\n', '6 3 2\n1 10 2 9 3 12\n', '7 2 2\n7 7 7 7 12 7 7\n', '3 1 3\n1 2 3\n', '1 1 1\n5\n', '5 3 2\n1 2 3 4 5\n'] })

t({ lv: 513, concept: '配列: k番目に欠けた正整数', title: 'k番目に欠けている正整数', tags: ['配列'], io: '1行目に k、2行目に昇順の正整数列(空行可)が与えられます。', ask: '配列に含まれない正整数のうち k 番目に小さいものを出力してください。', h1: '1から順に存在を確認する。', h2: '欠けている数を数えて k 個目を返す。', ref: 'k=int(input())\nline=input()\narr=list(map(int,line.split())) if line.strip() else []\nmissing=0\ncur=0\ni=0\nwhile True:\n    cur+=1\n    if i<len(arr) and arr[i]==cur:\n        i+=1\n    else:\n        missing+=1\n        if missing==k:\n            print(cur)\n            break', tip: '欠番探索は線形でも書けるが、大規模なら「位置-値」の差を二分探索して O(log n) にできる。', ins: ['5\n2 3 4 7 11\n', '1\n1 2 3\n', '2\n1 2 3\n', '3\n\n', '4\n2 3 4 7 11\n', '1\n2\n'] })

t({ lv: 514, concept: '分割統治: クイックセレクト', title: 'クイックセレクトでk番目に小さい要素', tags: ['分割統治'], io: '1行目に k(1始まり)、2行目に整数列が与えられます。', ask: 'k 番目に小さい要素を出力してください。', h1: 'ピボットで小・等・大に分割する。', h2: 'k がどの区画に入るかで再帰する。', ref: 'import sys\nsys.setrecursionlimit(100000)\nk=int(input())\na=list(map(int,input().split()))\ndef select(arr,k):\n    pivot=arr[len(arr)//2]\n    less=[x for x in arr if x<pivot]\n    eq=[x for x in arr if x==pivot]\n    great=[x for x in arr if x>pivot]\n    if k<=len(less):\n        return select(less,k)\n    elif k<=len(less)+len(eq):\n        return pivot\n    else:\n        return select(great,k-len(less)-len(eq))\nprint(select(a,k))', tip: 'クイックセレクトは平均O(n)で順位統計量を求める。ソートして取り出すより速い。', ins: ['3\n7 10 4 3 20 15\n', '1\n5 4 3 2 1\n', '5\n5 4 3 2 1\n', '1\n42\n', '2\n2 2 2\n', '4\n9 1 8 2 7 3\n'] })

t({ lv: 515, concept: '分割統治: カラツバ乗算', title: 'カラツバ法で大きな数の積', tags: ['分割統治'], io: '1行目に非負整数 a、2行目に非負整数 b が与えられます。', ask: 'a×b を出力してください。', h1: '各数を上位・下位に分けて3回の再帰積に。', h2: 'z1=(low+high)の積 - z2 - z0 で中間項を1回に。', ref: 'import sys\nsys.setrecursionlimit(100000)\na=int(input())\nb=int(input())\ndef kara(x,y):\n    if x<10 or y<10:\n        return x*y\n    m=max(len(str(x)),len(str(y)))\n    half=m//2\n    high1,low1=divmod(x,10**half)\n    high2,low2=divmod(y,10**half)\n    z0=kara(low1,low2)\n    z2=kara(high1,high2)\n    z1=kara(low1+high1,low2+high2)-z2-z0\n    return z2*10**(2*half)+z1*10**half+z0\nprint(kara(a,b))', tip: 'カラツバ法は乗算を4回でなく3回の半分サイズの積に減らし O(n^1.585) を実現する。', ins: ['12\n34\n', '0\n5\n', '1234\n5678\n', '99\n99\n', '100000\n100000\n', '7\n8\n'] })

t({ lv: 516, concept: 'ヒープ: k個のソート列のマージ', title: 'k個のソート済み列をマージ', tags: ['ヒープ'], io: '1行目に列数 k、続く k 行に各ソート済み列(空行可)が与えられます。', ask: '全要素を昇順に並べた列を空白区切りで出力してください(全て空なら空行)。', h1: '各列の先頭をヒープに入れる。', h2: '最小を取り出し、その列の次を入れる。', ref: 'import heapq\nk=int(input())\nlists=[]\nfor _ in range(k):\n    line=input()\n    lists.append(list(map(int,line.split())) if line.strip() else [])\npq=[]\nfor i in range(k):\n    if lists[i]:\n        heapq.heappush(pq,(lists[i][0],i,0))\nres=[]\nwhile pq:\n    val,li,idx=heapq.heappop(pq)\n    res.append(val)\n    if idx+1<len(lists[li]):\n        heapq.heappush(pq,(lists[li][idx+1],li,idx+1))\nprint(*res)', tip: 'k列のマージはヒープで各列の先頭だけ比較すれば O(N log k) で済む。', ins: ['3\n1 4 5\n1 3 4\n2 6\n', '2\n1 2 3\n\n', '1\n5\n', '2\n\n\n', '3\n1\n2\n3\n', '2\n1 1 1\n1 1\n'] })

t({ lv: 517, concept: '数え上げ: 和と積が等しい連続部分配列の個数', title: '足しても掛けても同じ区間', tags: ['数え上げ'], io: '整数列が1行で空白区切りで与えられます。', ask: '連続部分配列(長さ1以上)のうち、要素の和と要素の積が等しいものの個数を出力してください。', h1: '左端を固定して右へ伸ばすと、和は足し算1回、積は掛け算1回で更新できる。', h2: '長さ1の区間は必ず条件を満たすことに注意する。', ref: 'a=list(map(int,input().split()))\nn=len(a)\ncnt=0\nfor i in range(n):\n    s=0\n    p=1\n    for j in range(i,n):\n        s+=a[j]\n        p*=a[j]\n        if s==p:\n            cnt+=1\nprint(cnt)', tip: '1+2+3 と 1×2×3 がどちらも 6 になるような偶然を、全区間で数える。全区間の和の合計(同レベル既出)は各要素の寄与を数えて O(n) に落ちたが、和と積という性質の違う2つを同時に見るこちらは、左端を固定して伸ばす素朴な O(n²) 走査が素直で速い。', ins: ['1 2 3\n', '2 2\n', '5\n', '0 0 0\n', '1 1 1\n', '1 2 3 4\n'] })

t({ lv: 518, concept: '配列: 最長の山(連続)', title: '最長の山(連続部分配列)の長さ', tags: ['配列'], io: '整数列が1行で空白区切りで与えられます。', ask: '厳密に増加してから厳密に減少する最長の連続部分配列の長さを出力してください(山が無ければ0)。', h1: '山の頂上候補で左右に伸ばす。', h2: '長さ3未満は山にならない。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nbest=0\ni=1\nwhile i<n-1:\n    if a[i-1]<a[i]>a[i+1]:\n        l=i-1\n        r=i+1\n        while l>0 and a[l-1]<a[l]:\n            l-=1\n        while r<n-1 and a[r]>a[r+1]:\n            r+=1\n        best=max(best,r-l+1)\n        i=r+1\n    else:\n        i+=1\nprint(best)', tip: '山の検出は「頂上から両側に伸ばす」二ポインタで線形時間。', ins: ['2 1 4 7 3 2 5\n', '2 2 2\n', '1 2 3\n', '5 4 3 2 1\n', '0 1 0 1 0\n', '1 3 2\n'] })

t({ lv: 519, concept: 'ハッシュ: 和がkの部分配列数', title: '和がkの連続部分配列の数', tags: ['ハッシュ'], io: '1行目に k、2行目に整数列が与えられます。', ask: '和がちょうど k になる連続部分配列の個数を出力してください。', h1: '累積和を使う。', h2: '累積和 s に対し s-k の出現数を辞書で数える。', ref: 'from collections import defaultdict\nk=int(input())\na=list(map(int,input().split()))\ncnt=defaultdict(int)\ncnt[0]=1\ns=0\nres=0\nfor x in a:\n    s+=x\n    res+=cnt[s-k]\n    cnt[s]+=1\nprint(res)', tip: '累積和の差 = 部分配列の和。s-k の出現回数を辞書で数えると O(n)。', ins: ['3\n1 1 1\n', '0\n1 -1 1 -1\n', '2\n1 2 3\n', '5\n5\n', '3\n3 3 3\n', '7\n1 2 3 4\n'] })

t({ lv: 520, concept: 'ハッシュ: 和がkの倍数の部分配列数', title: '和がkで割り切れる部分配列の数', tags: ['ハッシュ'], io: '1行目に k、2行目に整数列が与えられます。', ask: '和が k で割り切れる連続部分配列の個数を出力してください。', h1: '累積和の mod k を見る。', h2: '同じ余りどうしの組が割り切れる区間。', ref: 'from collections import defaultdict\nk=int(input())\na=list(map(int,input().split()))\ncnt=defaultdict(int)\ncnt[0]=1\ns=0\nres=0\nfor x in a:\n    s+=x\n    r=s%k\n    res+=cnt[r]\n    cnt[r]+=1\nprint(res)', tip: '「累積和の余りが等しい2点」の区間和は k の倍数。Pythonの % は負でも0以上を返す。', ins: ['5\n4 5 0 -2 -3 1\n', '3\n1 2 3\n', '2\n2 4 6\n', '1\n1 2 3\n', '4\n4 4 4\n', '3\n-1 2 9\n'] })

t({ lv: 521, concept: '配列: 雨水を溜める量', title: '高さ配列に溜まる雨水', tags: ['配列'], io: '非負整数の高さ列が1行で与えられます。', ask: '降った雨が溜まる水の総量を出力してください。', h1: '各位置の水位は左右の最大値の小さい方。', h2: '左最大・右最大の配列を前計算する。', ref: 'h=list(map(int,input().split()))\nn=len(h)\nif n==0:\n    print(0)\nelse:\n    left=[0]*n\n    right=[0]*n\n    left[0]=h[0]\n    for i in range(1,n):\n        left[i]=max(left[i-1],h[i])\n    right[n-1]=h[n-1]\n    for i in range(n-2,-1,-1):\n        right[i]=max(right[i+1],h[i])\n    water=0\n    for i in range(n):\n        water+=min(left[i],right[i])-h[i]\n    print(water)', tip: '各位置の貯水量は min(左の最大, 右の最大) − 自分の高さ。', ins: ['0 1 0 2 1 0 1 3 2 1 2 1\n', '4 2 0 3 2 5\n', '1 2 3\n', '3 2 1\n', '5\n', '2 0 2\n'] })

t({ lv: 522, concept: '二ポインタ: 最大貯水コンテナ', title: '最も水を貯められる2本の線', tags: ['二ポインタ'], io: '非負整数の高さ列が1行で与えられます。', ask: '2本の縦線と水平面で作れる最大の面積を出力してください。', h1: '両端から内側へ詰める。', h2: '低い側を動かすと面積が増える可能性がある。', ref: 'h=list(map(int,input().split()))\ni=0\nj=len(h)-1\nbest=0\nwhile i<j:\n    area=min(h[i],h[j])*(j-i)\n    if area>best:\n        best=area\n    if h[i]<h[j]:\n        i+=1\n    else:\n        j-=1\nprint(best)', tip: '面積は低い方の高さ×幅。低い側を動かすと改善余地があるので両端から詰める。', ins: ['1 8 6 2 5 4 8 3 7\n', '1 1\n', '4 3 2 1 4\n', '1 2 1\n', '2 3 4 5 18 17 6\n', '1\n'] })

t({ lv: 523, concept: '投票法: 過半数要素', title: 'ボイヤー・ムーアで過半数要素', tags: ['配列'], io: '整数列が1行で与えられます(過半数を占める要素が必ず存在)。', ask: '出現回数が要素数の半分を超える要素を出力してください。', h1: '候補と票数を1つずつ持つ。', h2: '同じなら+1、違えば-1、0になったら候補交代。', ref: 'a=list(map(int,input().split()))\ncand=None\ncount=0\nfor x in a:\n    if count==0:\n        cand=x\n        count=1\n    elif x==cand:\n        count+=1\n    else:\n        count-=1\nprint(cand)', tip: 'ボイヤー・ムーア投票法は過半数要素を O(n)・追加メモリ O(1) で見つける。', ins: ['3 2 3\n', '1\n', '2 2 1 1 2 2\n', '5 5 5\n', '1 2 1 2 1\n', '7 7 7 1 2\n'] })

t({ lv: 524, concept: '三分割: オランダ国旗', title: 'オランダ国旗で0/1/2を整列', tags: ['配列'], io: '0・1・2 のみからなる列が1行で与えられます。', ask: '昇順に並べ替えた列を空白区切りで出力してください。', h1: 'lo・mid・hi の3つのポインタを使う。', h2: '0は前へ、2は後ろへ送り、1はそのまま。', ref: 'a=list(map(int,input().split()))\nlo=0\nmid=0\nhi=len(a)-1\nwhile mid<=hi:\n    if a[mid]==0:\n        a[lo],a[mid]=a[mid],a[lo]\n        lo+=1\n        mid+=1\n    elif a[mid]==1:\n        mid+=1\n    else:\n        a[mid],a[hi]=a[hi],a[mid]\n        hi-=1\nprint(*a)', tip: '3値ソートは1パス・定数メモリで完了する(ダイクストラのオランダ国旗問題)。', ins: ['2 0 2 1 1 0\n', '2 0 1\n', '0\n', '1 1 1\n', '2 2 2\n', '0 1 2 0 1 2\n'] })

t({ lv: 525, concept: '配列: 最大ギャップ', title: 'ソート後の最大隣接差', tags: ['配列'], io: '整数列が1行で与えられます。', ask: '昇順に並べたとき隣り合う要素の差の最大値を出力してください(要素2未満なら0)。', h1: 'ソートして隣接差を見る。', h2: '最大差を更新する。', ref: 'a=sorted(map(int,input().split()))\nif len(a)<2:\n    print(0)\nelse:\n    best=0\n    for i in range(1,len(a)):\n        if a[i]-a[i-1]>best:\n            best=a[i]-a[i-1]\n    print(best)', tip: '最大ギャップはバケットソートを使えば O(n) でも求まる(鳩の巣原理)。', ins: ['3 6 9 1\n', '10\n', '1 1 1\n', '1 100\n', '5 4 3 2 1\n', '0 3 9 10\n'] })

t({ lv: 526, concept: 'ソート: h指数', title: 'h指数を求める', tags: ['ソート'], io: '各論文の被引用数の列が1行で与えられます。', ask: 'h 本以上が各 h 回以上引用されている最大の h(h指数)を出力してください。', h1: '降順に並べる。', h2: 'i+1 番目の引用数が i+1 以上なら h=i+1。', ref: 'c=sorted(map(int,input().split()),reverse=True)\nh=0\nfor i,v in enumerate(c):\n    if v>=i+1:\n        h=i+1\n    else:\n        break\nprint(h)', tip: 'h指数は降順ソートして「順位 ≤ 引用数」が成り立つ最大位置。', ins: ['3 0 6 1 5\n', '1 3 1\n', '0 0 0\n', '10\n', '5 5 5 5 5\n', '100\n'] })

t({ lv: 527, concept: '区間: 最小プラットフォーム数', title: '同時に必要なホーム数', tags: ['区間'], io: '1行目に n、2行目に n 個の到着時刻、3行目に n 個の出発時刻が与えられます。', ask: '同時に在線する列車の最大数(必要なホーム数)を出力してください。', h1: '到着・出発を別々にソートする。', h2: '到着なら+1、出発なら-1して最大同時数を追う。', ref: 'n=int(input())\narr=sorted(map(int,input().split()))\ndep=sorted(map(int,input().split()))\ni=0\nj=0\ncur=0\nbest=0\nwhile i<n:\n    if arr[i]<=dep[j]:\n        cur+=1\n        i+=1\n        if cur>best:\n            best=cur\n    else:\n        cur-=1\n        j+=1\nprint(best)', tip: '到着・出発をマージして+1/-1する典型。最大同時数が必要資源数になる。', ins: ['6\n900 940 950 1100 1500 1800\n910 1200 1120 1130 1900 2000\n', '1\n100\n200\n', '3\n1 2 3\n4 5 6\n', '3\n1 1 1\n2 2 2\n', '2\n100 200\n150 300\n', '4\n1 3 5 7\n2 4 6 8\n'] })

t({ lv: 528, concept: '配列: 自分以外の積', title: '自分以外の要素の積', tags: ['配列'], io: '整数列が1行で与えられます。', ask: '各位置について、その要素以外の全要素の積を並べた列を空白区切りで出力してください(除算は使わない方針)。', h1: '前から累積積を入れる。', h2: '後ろから累積積を掛ける。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nres=[1]*n\npre=1\nfor i in range(n):\n    res[i]=pre\n    pre*=a[i]\nsuf=1\nfor i in range(n-1,-1,-1):\n    res[i]*=suf\n    suf*=a[i]\nprint(*res)', tip: '前方累積積×後方累積積で、割り算を使わず O(n) で「自分以外の積」が出せる(0があっても安全)。', ins: ['1 2 3 4\n', '2 3 4\n', '1 0\n', '5\n', '0 0\n', '2 2 2\n'] })

t({ lv: 529, concept: '単調スタック: 次に大きい要素', title: '各要素の次に大きい要素', tags: ['スタック'], io: '整数列が1行で与えられます。', ask: '各要素について、その右側で最初に出る大きい要素を並べて出力してください(無ければ -1)。', h1: '減少スタックに添字を積む。', h2: '今の値より小さい先頭を解決して答えを埋める。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nres=[-1]*n\nstack=[]\nfor i in range(n):\n    while stack and a[stack[-1]]<a[i]:\n        res[stack.pop()]=a[i]\n    stack.append(i)\nprint(*res)', tip: '単調(減少)スタックは「次に大きい/小さい要素」を全体 O(n) で求める基本形。', ins: ['2 1 2 4 3\n', '1 2 3\n', '3 2 1\n', '5\n', '1 3 2 4\n', '4 4 4\n'] })

t({ lv: 530, concept: 'バックトラック: Nクイーン数', title: 'Nクイーンの配置数', tags: ['バックトラック'], io: '整数 n が1行で与えられます。', ask: 'n×n の盤に互いに取り合わないよう n 個のクイーンを置く配置の総数を出力してください。', h1: '行ごとに列を選ぶ。', h2: '列・2方向の対角線の使用状況を集合で管理。', ref: 'import sys\nsys.setrecursionlimit(100000)\nn=int(input())\ncount=[0]\ndef solve(row,cols,d1,d2):\n    if row==n:\n        count[0]+=1\n        return\n    for c in range(n):\n        if c in cols or (row-c) in d1 or (row+c) in d2:\n            continue\n        cols.add(c)\n        d1.add(row-c)\n        d2.add(row+c)\n        solve(row+1,cols,d1,d2)\n        cols.remove(c)\n        d1.remove(row-c)\n        d2.remove(row+c)\nsolve(0,set(),set(),set())\nprint(count[0])', tip: 'Nクイーンは行ごとに置き、列・対角線(row-c, row+c)の衝突を集合で枝刈りする。', ins: ['4\n', '1\n', '2\n', '3\n', '5\n', '6\n'] })

t({ lv: 531, concept: 'バックトラック: m彩色の総数', title: 'm色での彩色の総数', tags: ['バックトラック', 'グラフ'], io: '1行目に n m e(頂点数・色数・辺数)、続く e 行に無向辺 u v が与えられます。', ask: '隣接頂点が異色になる m 色の塗り方(色は区別)の総数を出力してください。', h1: '頂点を順に塗る。', h2: '隣接に同色が無ければ次へ進む。', ref: 'import sys\nsys.setrecursionlimit(100000)\nfirst=input().split()\nn=int(first[0])\nm=int(first[1])\ne=int(first[2])\nadj=[[] for _ in range(n)]\nfor _ in range(e):\n    u,v=map(int,input().split())\n    adj[u-1].append(v-1)\n    adj[v-1].append(u-1)\ncolor=[0]*n\ncount=[0]\ndef solve(v):\n    if v==n:\n        count[0]+=1\n        return\n    for c in range(1,m+1):\n        ok=True\n        for u in adj[v]:\n            if color[u]==c:\n                ok=False\n                break\n        if ok:\n            color[v]=c\n            solve(v+1)\n            color[v]=0\nsolve(0)\nprint(count[0])', tip: 'm彩色の数え上げは頂点ごとに色を試すバックトラック。彩色多項式の値そのもの。', ins: ['3 3 3\n1 2\n2 3\n1 3\n', '3 2 2\n1 2\n2 3\n', '2 2 1\n1 2\n', '3 3 0\n', '4 2 4\n1 2\n2 3\n3 4\n4 1\n', '1 5 0\n'] })

t({ lv: 532, concept: 'バックトラック: 部分集合和の数', title: '合計が目標になる部分集合の数', tags: ['バックトラック'], io: '1行目に target、2行目に整数列が与えられます。', ask: '各要素を高々1回使って合計が target になる部分集合の個数を出力してください。', h1: 'i 番目を使う/使わないで分岐する。', h2: '残りが0になったら1通り。', ref: 'target=int(input())\na=list(map(int,input().split()))\nn=len(a)\ncount=[0]\ndef solve(i,rem):\n    if rem==0:\n        count[0]+=1\n        return\n    if rem<0 or i==n:\n        return\n    solve(i+1,rem-a[i])\n    solve(i+1,rem)\nsolve(0,target)\nprint(count[0])', tip: '部分集合和の数え上げは「各要素を使うか否か」の二分木探索。重複なしの選択が硬貨問題との違い。', ins: ['5\n1 2 3 4 5\n', '0\n1 2 3\n', '10\n2 3 5\n', '7\n1 2 3 4\n', '3\n3\n', '6\n1 2 3\n'] })

t({ lv: 533, concept: 'DP: 等和分割の可否', title: '等しい和の2集合に分けられるか', tags: ['dp'], io: '正整数の列が1行で与えられます。', ask: '和が等しい2つの部分集合に分割できるなら yes、できないなら no を出力してください。', h1: '総和が奇数なら不可能。', h2: '総和の半分が作れるか部分和DPで判定。', ref: 'a=list(map(int,input().split()))\ntotal=sum(a)\nif total%2==1:\n    print("no")\nelse:\n    target=total//2\n    dp=set([0])\n    for x in a:\n        ndp=set(dp)\n        for s in dp:\n            ndp.add(s+x)\n        dp=ndp\n    print("yes" if target in dp else "no")', tip: '等和分割は「総和の半分を作れるか」の部分和問題に帰着する。', ins: ['1 5 11 5\n', '1 2 3 5\n', '1 1\n', '2\n', '3 3 3 3\n', '1 2 3 4 5 6 7\n'] })

t({ lv: 534, concept: 'バックトラック: k等分割の可否', title: 'k個の等和集合に分けられるか', tags: ['バックトラック'], io: '1行目に k、2行目に整数列が与えられます。', ask: '和が等しい k 個の部分集合に分けられるなら yes、できないなら no を出力してください。', h1: '総和が k で割れることが必要。', h2: '大きい順に1つずつバケツへ詰めるバックトラック。', ref: 'import sys\nsys.setrecursionlimit(100000)\nk=int(input())\na=list(map(int,input().split()))\ntotal=sum(a)\nif k==0 or total%k!=0:\n    print("no")\nelse:\n    target=total//k\n    a.sort(reverse=True)\n    if a and a[0]>target:\n        print("no")\n    else:\n        n=len(a)\n        used=[False]*n\n        def solve(count,cur,start):\n            if count==k:\n                return True\n            if cur==target:\n                return solve(count+1,0,0)\n            for i in range(start,n):\n                if not used[i] and cur+a[i]<=target:\n                    used[i]=True\n                    if solve(count,cur+a[i],i+1):\n                        return True\n                    used[i]=False\n                    if cur==0:\n                        break\n            return False\n        print("yes" if solve(0,0,0) else "no")', tip: 'k等分割は大きい順に詰め、空バケツで失敗したら即枝刈りするのが効く。', ins: ['4\n4 3 2 3 5 2 1\n', '3\n1 2 3 4\n', '2\n1 2 3 4 5 6 7\n', '1\n5 5\n', '2\n1 1\n', '3\n2 2 2 2 2 2\n'] })

t({ lv: 535, concept: 'バックトラック: 辞書の単語での分割をすべて列挙', title: '辞書の単語で読める区切り方をすべて', tags: ['バックトラック', '文字列'], io: '1行目に文字列 s、2行目に単語数 w、3行目に w 個の単語(空白区切り。w=0 なら3行目なし)が与えられます。', ask: 's を辞書の単語(何度でも使える)の連結として読む区切り方をすべて、単語を空白で区切った1行にして辞書順に出力してください。1通りもなければ none を出力してください。', h1: '位置 i から始まる辞書の単語を順に試し、その先を再帰で処理する。', h2: '末尾まで届いたら、それまでに選んだ単語列を答えの1つとして記録する。', ref: 's=input()\nw=int(input())\nwords=set(input().split()) if w>0 else set()\nn=len(s)\nres=[]\ndef rec(i,cur):\n    if i==n:\n        res.append(" ".join(cur))\n        return\n    for j in range(i+1,n+1):\n        if s[i:j] in words:\n            cur.append(s[i:j])\n            rec(j,cur)\n            cur.pop()\nrec(0,[])\nif res:\n    for line in sorted(res):\n        print(line)\nelse:\n    print("none")', tip: '可否のDPは「できるか」しか答えない。区切り方そのものが欲しいときは、選んだ単語を積みながら戻る(バックトラック)で全部拾える。', ins: ['catsanddog\n5\ncat cats and sand dog\n', 'pineapplepenapple\n5\napple pen applepen pine pineapple\n', 'catsandog\n5\ncats dog sand and cat\n', 'aaa\n2\na aa\n', 'abcd\n4\nab cd abcd d\n', 'sunday\n3\nsun day sunday\n'] })

t({ lv: 536, concept: 'バックトラック: 騎士の周遊数', title: '騎士の開いた周遊の数', tags: ['バックトラック'], io: '盤の一辺 n が1行で与えられます。', ask: 'n×n 盤の左上(0,0)から始め、全マスをちょうど1回ずつ訪れる騎士の経路(開いた周遊)の数を出力してください。', h1: '8方向の桂馬移動を試す。', h2: '全マス訪問で1通りと数えるDFS。', ref: 'import sys\nsys.setrecursionlimit(100000)\nn=int(input())\nmoves=[(1,2),(2,1),(-1,2),(-2,1),(1,-2),(2,-1),(-1,-2),(-2,-1)]\nvisited=[[False]*n for _ in range(n)]\ncount=[0]\ndef solve(x,y,cnt):\n    if cnt==n*n:\n        count[0]+=1\n        return\n    for dx,dy in moves:\n        nx=x+dx\n        ny=y+dy\n        if 0<=nx<n and 0<=ny<n and not visited[nx][ny]:\n            visited[nx][ny]=True\n            solve(nx,ny,cnt+1)\n            visited[nx][ny]=False\nvisited[0][0]=True\nsolve(0,0,1)\nprint(count[0])', tip: '騎士の周遊はDFSバックトラック。小さい盤(3,4)では存在しないことが知られている。', ins: ['1\n', '2\n', '3\n', '4\n', '3\n', '2\n'] })

t({ lv: 537, concept: 'DP: 障害物ありグリッド経路数', title: '障害物を避けるグリッド経路数', tags: ['dp'], io: '1行目に R C、続く R 行に C 個の 0/1(1=通れる)が与えられます。', ask: '左上(0,0)から右下へ、右または下だけに進む経路の数を出力してください。始点か終点が通れないなら0。', h1: 'dp[i][j]=そのマスへの経路数。', h2: '通れないマスは0、それ以外は上+左。', ref: 'first=input().split()\nR=int(first[0])\nC=int(first[1])\ng=[list(map(int,input().split())) for _ in range(R)]\nif g[0][0]==0 or g[R-1][C-1]==0:\n    print(0)\nelse:\n    dp=[[0]*C for _ in range(R)]\n    dp[0][0]=1\n    for i in range(R):\n        for j in range(C):\n            if g[i][j]==0:\n                dp[i][j]=0\n                continue\n            if i==0 and j==0:\n                continue\n            up=dp[i-1][j] if i>0 else 0\n            left=dp[i][j-1] if j>0 else 0\n            dp[i][j]=up+left\n    print(dp[R-1][C-1])', tip: '障害物ありの経路数は、通行不可マスを0に固定した上下左の漸化式で解く。', ins: ['2 2\n1 1\n1 1\n', '3 3\n1 1 1\n1 0 1\n1 1 1\n', '2 2\n1 0\n0 1\n', '1 1\n1\n', '3 3\n1 1 1\n1 1 1\n1 1 1\n', '2 3\n1 1 1\n1 1 1\n'] })

t({ lv: 538, concept: '組合せ: 重複ありの順列数', title: '重複を含む並べ替えの数', tags: ['数え上げ'], io: '整数(重複可)の列が1行で与えられます。', ask: 'それらを並べ替えてできる相異なる列の数を出力してください。', h1: '全体の階乗から始める。', h2: '同じ値の個数の階乗で割る。', ref: 'import math\nfrom collections import Counter\na=input().split()\nn=len(a)\nres=math.factorial(n)\nfor v in Counter(a).values():\n    res//=math.factorial(v)\nprint(res)', tip: '重複順列の数は n! を各重複数の階乗で割る(多項係数)。', ins: ['1 1 2\n', '1 2 3\n', '1 1 1\n', '1\n', '1 2 2 3\n', '5 5 5 5\n'] })

t({ lv: 539, concept: 'DP: 符号付き和の組合せ数', title: '+/-を付けて目標和にする方法の数', tags: ['dp'], io: '1行目に target、2行目に非負整数列(空行可)が与えられます。', ask: '各数の前に + か - を付けて合計を target にする方法の数を出力してください。', h1: '到達可能な和とその通り数を持つ。', h2: '各数で +x と -x の両方へ遷移して足す。', ref: 'from collections import defaultdict\ntarget=int(input())\nline=input()\na=list(map(int,line.split())) if line.strip() else []\ndp=defaultdict(int)\ndp[0]=1\nfor x in a:\n    ndp=defaultdict(int)\n    for s,c in dp.items():\n        ndp[s+x]+=c\n        ndp[s-x]+=c\n    dp=ndp\nprint(dp[target])', tip: '符号付き和は「到達可能な和→通り数」の辞書DP。部分和問題に変換しても解ける。', ins: ['3\n1 1 1 1 1\n', '0\n1 1\n', '1\n1 2 3\n', '5\n5\n', '0\n\n', '2\n1 1 1 1\n'] })

t({ lv: 540, concept: 'DP: 階段の上り方(順序あり)', title: '指定歩幅で階段を上る方法の数', tags: ['dp'], io: '1行目に段数 n、2行目に歩幅の集合が与えられます。', ask: 'ちょうど n 段上る方法(上る順序を区別)の数を出力してください。', h1: 'dp[x]=x 段に達する方法の数。', h2: '各歩幅 s について dp[x]+=dp[x-s](歩幅を内側ループ)。', ref: 'n=int(input())\nsteps=list(map(int,input().split()))\ndp=[0]*(n+1)\ndp[0]=1\nfor x in range(1,n+1):\n    for s in steps:\n        if s<=x:\n            dp[x]+=dp[x-s]\nprint(dp[n])', tip: '順序を区別する「合成数」は段(x)を外側に回す。硬貨の組合せ数とループ順が逆。', ins: ['4\n1 2\n', '3\n1 2 3\n', '0\n1 2\n', '5\n1 3 5\n', '3\n2\n', '10\n1 2\n'] })

t({ lv: 541, concept: '再帰: 4本塔のハノイ', title: 'フレーム・スチュワートの4本塔ハノイ', tags: ['再帰', 'dp'], io: '円盤数 n が1行で与えられます。', ask: '4本の塔でハノイの塔を解く最小手数(フレーム・スチュワート値)を出力してください。', h1: '上 k 枚を4本で別の塔へ退避。', h2: '残りを3本で動かし、退避分を戻す。最適 k を全探索。', ref: 'import sys\nsys.setrecursionlimit(100000)\nfrom functools import lru_cache\nn=int(input())\n@lru_cache(maxsize=None)\ndef fs(disks,pegs):\n    if disks==0:\n        return 0\n    if disks==1:\n        return 1\n    if pegs==3:\n        return 2**disks-1\n    best=None\n    for k in range(1,disks):\n        cost=2*fs(k,pegs)+fs(disks-k,pegs-1)\n        if best is None or cost<best:\n            best=cost\n    return best\nprint(fs(n,4))', tip: 'フレーム・スチュワート法は「上 k 枚を退避→残りを3本で→戻す」の最適 k を探す再帰。', ins: ['3\n', '1\n', '0\n', '4\n', '5\n', '10\n'] })

t({ lv: 542, concept: '再帰: アッカーマン関数', title: 'アッカーマン関数の値', tags: ['再帰'], io: 'm n が空白区切りで与えられます(小さい値)。', ask: 'アッカーマン関数 A(m,n) の値を出力してください。', h1: 'm=0 なら n+1。', h2: 'n=0 なら A(m-1,1)、それ以外は A(m-1,A(m,n-1))。', ref: 'import sys\nsys.setrecursionlimit(1000000)\nfrom functools import lru_cache\nm,n=map(int,input().split())\n@lru_cache(maxsize=None)\ndef ack(m,n):\n    if m==0:\n        return n+1\n    if n==0:\n        return ack(m-1,1)\n    return ack(m-1,ack(m,n-1))\nprint(ack(m,n))', tip: 'アッカーマン関数は原始再帰でない代表例。爆発的に増えるので m は小さく抑える。', ins: ['2 2\n', '0 0\n', '1 1\n', '3 3\n', '2 3\n', '3 4\n'] })

t({ lv: 543, concept: 'シミュレーション: コラッツ数列の長さ', title: 'コラッツ操作で1に至る回数', tags: ['シミュレーション'], io: '正整数 n が1行で与えられます。', ask: '偶数なら半分、奇数なら3倍+1を繰り返して n が1になるまでの操作回数を出力してください。', h1: 'n が1になるまでループする。', h2: '偶奇で操作を分ける。', ref: 'n=int(input())\nsteps=0\nwhile n!=1:\n    if n%2==0:\n        n//=2\n    else:\n        n=3*n+1\n    steps+=1\nprint(steps)', tip: 'コラッツ予想は「必ず1に至る」が未証明だが、現実の範囲では必ず停止する。', ins: ['6\n', '1\n', '27\n', '7\n', '100\n', '97\n'] })

t({ lv: 544, concept: '数: 数字根', title: '桁和を繰り返した数字根', tags: ['数学'], io: '非負整数 n が1行で与えられます。', ask: '各桁の和を1桁になるまで繰り返した値(数字根)を出力してください。', h1: '10未満になるまで桁和を取る。', h2: '内側のループで桁を分解する。', ref: 'n=int(input())\nwhile n>=10:\n    s=0\n    while n>0:\n        s+=n%10\n        n//=10\n    n=s\nprint(n)', tip: '数字根は n が0なら0、そうでなければ 1+(n-1)%9 でも一発で求まる(9の剰余)。', ins: ['38\n', '0\n', '9\n', '12345\n', '99999\n', '10\n'] })

t({ lv: 545, concept: 'bit演算: 0..Nの立っているビット総数', title: '0からNまでの1ビットの総数', tags: ['bit演算'], io: '非負整数 N が1行で与えられます。', ask: '0 から N までの全整数の2進表現に現れる1の総数を出力してください。', h1: 'ビット位置 i ごとに数える。', h2: '周期 2^(i+1) の中で上半分が1。', ref: 'N=int(input())\ntotal=0\ni=1\nwhile i<=N:\n    full=(N+1)//(2*i)\n    total+=full*i\n    rem=(N+1)%(2*i)\n    total+=max(0,rem-i)\n    i*=2\nprint(total)', tip: '各ビットは周期 2^(i+1) で「i 個連続1」が現れる。位置ごとに数えると O(log N)。', ins: ['5\n', '0\n', '1\n', '2\n', '16\n', '1023\n'] })

t({ lv: 546, concept: 'DP: 1が連続しない2進列の数', title: '1が連続しない長さnの2進列', tags: ['dp'], io: '非負整数 n が1行で与えられます。', ask: '長さ n の2進文字列で、1が2つ以上連続しないものの数を出力してください。', h1: 'フィボナッチ的な漸化式になる。', h2: 'f(n)=f(n-1)+f(n-2)。', ref: 'n=int(input())\nif n==0:\n    print(1)\nelse:\n    a=1\n    b=2\n    for _ in range(2,n+1):\n        a,b=b,a+b\n    print(b)', tip: '末尾が0なら自由、1なら前は0という制約からフィボナッチ漸化式が出る。', ins: ['1\n', '2\n', '3\n', '4\n', '5\n', '0\n'] })

t({ lv: 547, concept: 'DP: トリボナッチ数', title: 'トリボナッチ数', tags: ['dp'], io: '非負整数 n が1行で与えられます。', ask: 'T0=0, T1=1, T2=1, Tn=Tn-1+Tn-2+Tn-3 で定まる n 番目のトリボナッチ数を出力してください。', h1: '直近3項を保持する。', h2: '3項の和で次を作る。', ref: 'n=int(input())\nif n==0:\n    print(0)\nelif n<=2:\n    print(1)\nelse:\n    a,b,c=0,1,1\n    for _ in range(3,n+1):\n        a,b,c=b,c,a+b+c\n    print(c)', tip: 'トリボナッチは直前3項の和。3段の階段(1,2,3歩)の上り方とも一致する。', ins: ['4\n', '0\n', '1\n', '2\n', '10\n', '25\n'] })

t({ lv: 548, concept: '組合せ: グリッド経路数', title: '格子の右下までの経路数', tags: ['数え上げ'], io: 'R C が空白区切りで与えられます。', ask: 'R×C の格子で左上から右下へ、右または下だけに進む経路の数を出力してください。', h1: '右移動 C-1 回・下移動 R-1 回の並べ方。', h2: 'C(R+C-2, R-1) を計算する。', ref: 'import math\nR,C=map(int,input().split())\nprint(math.comb(R+C-2,R-1))', tip: '障害物なしの格子経路数は二項係数 C(R+C-2, R-1) で一発(下移動の位置の選び方)。', ins: ['3 3\n', '2 2\n', '1 1\n', '3 7\n', '1 5\n', '4 4\n'] })

t({ lv: 549, concept: '組合せ: パスカルの三角形の行', title: 'パスカルの三角形の第n行', tags: ['数え上げ'], io: '非負整数 n が1行で与えられます。', ask: 'パスカルの三角形の第 n 行(C(n,0)..C(n,n))を空白区切りで出力してください。', h1: '直前の項から C(n,k)=C(n,k-1)·(n-k+1)/k。', h2: '1から順に掛けて割る。', ref: 'n=int(input())\nrow=[1]\nfor k in range(1,n+1):\n    row.append(row[-1]*(n-k+1)//k)\nprint(*row)', tip: '二項係数の行は隣の項から乗算1回・除算1回で次々に作れる(階乗を使わない)。', ins: ['4\n', '0\n', '1\n', '5\n', '3\n', '6\n'] })

export const CATALOG = TASKS
