// 生成タスク 第45波：lv900, lv950, lv951〜998。これで全999段が完成。
// 最高峰帯: Frobenius/OEIS定番数列/高度数論/組合せ幾何の閉形式/上級DP・グラフ。
// 重複なし・決定的・採点一意。無限ループ無し。
const MOD = 1000000007
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 900, concept: '数論: フロベニウス数(2硬貨)', title: '2つの互いに素な額面で作れない最大金額', tags: ['数論'], io: 'a b が空白区切りで与えられます(gcd(a,b)=1)。', ask: 'a と b の非負整数倍の和で表せない最大の金額(フロベニウス数)を出力してください。', h1: '互いに素な2数の公式を使う。', h2: 'a·b - a - b。', ref: 'a,b=map(int,input().split())\nprint(a*b-a-b)', tip: '互いに素な2額面のフロベニウス数は ab-a-b(チキンマックナゲット定理)。3額面以上は閉じた式がない。', ins: ['3 5\n', '2 3\n', '4 7\n', '5 8\n', '3 7\n', '6 7\n'] })

t({ lv: 950, concept: '数論: 表せない金額の個数', title: '2硬貨で表せない金額の個数', tags: ['数論'], io: 'a b が空白区切りで与えられます(gcd(a,b)=1)。', ask: 'a と b の非負整数倍の和で表せない非負整数の個数を出力してください。', h1: '互いに素な2数の公式を使う。', h2: '(a-1)(b-1)/2。', ref: 'a,b=map(int,input().split())\nprint((a-1)*(b-1)//2)', tip: '互いに素な2額面で表せない数の個数は (a-1)(b-1)/2。フロベニウス数の半分に対応する。', ins: ['3 5\n', '2 3\n', '4 7\n', '5 8\n', '3 7\n', '1 5\n'] })

t({ lv: 951, concept: 'DP: 相異なる部分列の数', title: '相異なる部分列の総数', tags: ['dp', '文字列'], io: '文字列が1行で与えられます。', ask: '空でない相異なる部分列の総数を 1000000007 で割った余りで出力してください。', h1: 'dp[i]=先頭i文字での相異なる部分列数(空を含む)。', h2: 'dp[i]=2·dp[i-1]、直前に同じ文字があればその分を引く。', ref: `s=input()\nMOD=${MOD}\nn=len(s)\ndp=[0]*(n+1)\ndp[0]=1\nlast={}\nfor i in range(1,n+1):\n    c=s[i-1]\n    dp[i]=2*dp[i-1]%MOD\n    if c in last:\n        dp[i]=(dp[i]-dp[last[c]-1])%MOD\n    last[c]=i\nprint((dp[n]-1)%MOD)`, tip: '相異なる部分列数は dp[i]=2dp[i-1] から「直前の同じ文字の寄与」を引く。重複を除く定石。', ins: ['abc\n', 'aaa\n', 'aba\n', 'a\n', 'abab\n', 'abcabc\n'] })

t({ lv: 952, concept: '二ポインタ: 2種類以下の最長部分文字列', title: '高々2種類の文字の最長部分文字列', tags: ['二ポインタ', '文字列'], io: '文字列が1行で与えられます。', ask: '異なる文字が高々2種類しか現れない最長の連続部分文字列の長さを出力してください。', h1: '窓内の文字種を辞書で数える。', h2: '3種になったら左端を縮める。', ref: 's=input()\nfrom collections import defaultdict\ncnt=defaultdict(int)\nleft=0\ndistinct=0\nbest=0\nfor right in range(len(s)):\n    if cnt[s[right]]==0:\n        distinct+=1\n    cnt[s[right]]+=1\n    while distinct>2:\n        cnt[s[left]]-=1\n        if cnt[s[left]]==0:\n            distinct-=1\n        left+=1\n    if right-left+1>best:\n        best=right-left+1\nprint(best)', tip: '「高々k種の文字」の最長窓はしゃくとり法。窓内の文字種数を辞書で管理して伸縮させる。', ins: ['eceba\n', 'ccaabbb\n', 'a\n', 'abc\n', 'aaaa\n', 'abaccc\n'] })

t({ lv: 953, concept: '幾何: 一直線上の最大点数', title: '同一直線上にある最大の点数', tags: ['幾何'], io: '1行目に点数 n、続く n 行に点 x y が与えられます。', ask: '同一直線上にある点の最大数を出力してください。', h1: '各点を基準に他点との傾きを正規化して数える。', h2: '傾きを既約分数で表しハッシュする。', ref: 'import math\nfrom collections import defaultdict\nn=int(input())\npts=[tuple(map(int,input().split())) for _ in range(n)]\nif n<=2:\n    print(n)\nelse:\n    best=1\n    for i in range(n):\n        slopes=defaultdict(int)\n        for j in range(n):\n            if i==j:\n                continue\n            dx=pts[j][0]-pts[i][0]\n            dy=pts[j][1]-pts[i][1]\n            g=math.gcd(abs(dx),abs(dy))\n            if g!=0:\n                dx//=g\n                dy//=g\n            if dx<0 or (dx==0 and dy<0):\n                dx=-dx\n                dy=-dy\n            slopes[(dx,dy)]+=1\n        for v in slopes.values():\n            if v+1>best:\n                best=v+1\n    print(best)', tip: '各点を基準に傾きを既約分数で正規化して数える。符号を一意化して同一直線をまとめるのが鍵。', ins: ['3\n0 0\n1 1\n2 2\n', '3\n0 0\n1 0\n0 1\n', '1\n5 5\n', '5\n1 1\n2 2\n3 3\n1 2\n2 1\n', '4\n0 0\n1 1\n2 2\n3 3\n', '2\n0 0\n5 5\n'] })

t({ lv: 954, concept: '幾何: 凸包の面積', title: '凸包の面積の2倍', tags: ['幾何'], io: '1行目に点数 n、続く n 行に点 x y が与えられます。', ask: '点集合の凸包の面積の2倍(整数)を出力してください(2点以下なら0)。', h1: 'Andrew の単調鎖で凸包を作る。', h2: '靴ひも公式で面積の2倍を出す。', ref: 'n=int(input())\npts=sorted(set(tuple(map(int,input().split())) for _ in range(n)))\nif len(pts)<3:\n    print(0)\nelse:\n    def cross(o,a,b):\n        return (a[0]-o[0])*(b[1]-o[1])-(a[1]-o[1])*(b[0]-o[0])\n    lower=[]\n    for p in pts:\n        while len(lower)>=2 and cross(lower[-2],lower[-1],p)<=0:\n            lower.pop()\n        lower.append(p)\n    upper=[]\n    for p in reversed(pts):\n        while len(upper)>=2 and cross(upper[-2],upper[-1],p)<=0:\n            upper.pop()\n        upper.append(p)\n    hull=lower[:-1]+upper[:-1]\n    s=0\n    h=len(hull)\n    for i in range(h):\n        x1,y1=hull[i]\n        x2,y2=hull[(i+1)%h]\n        s+=x1*y2-x2*y1\n    print(abs(s))', tip: '凸包を単調鎖で作り、靴ひも公式で面積。面積2倍を整数で出せば誤差ゼロで採点一意になる。', ins: ['4\n0 0\n2 0\n2 2\n0 2\n', '3\n0 0\n4 0\n0 3\n', '2\n0 0\n1 1\n', '5\n0 0\n2 0\n2 2\n0 2\n1 1\n', '3\n0 0\n1 1\n2 2\n', '4\n0 0\n4 0\n4 4\n0 4\n'] })

t({ lv: 955, concept: '幾何: 凸多角形の判定', title: '多角形が凸か', tags: ['幾何'], io: '1行目に頂点数 n、続く n 行に多角形の頂点 x y が順に与えられます。', ask: '多角形が凸なら yes、凹なら no を出力してください。', h1: '連続する3頂点の外積の符号を見る。', h2: '符号が途中で変わらなければ凸。', ref: 'n=int(input())\npts=[tuple(map(int,input().split())) for _ in range(n)]\nif n<3:\n    print("yes")\nelse:\n    sign=0\n    ok=True\n    for i in range(n):\n        ax,ay=pts[i]\n        bx,by=pts[(i+1)%n]\n        cx,cy=pts[(i+2)%n]\n        cross=(bx-ax)*(cy-by)-(by-ay)*(cx-bx)\n        if cross!=0:\n            s=1 if cross>0 else -1\n            if sign==0:\n                sign=s\n            elif s!=sign:\n                ok=False\n                break\n    print("yes" if ok else "no")', tip: '凸判定は隣接3頂点の外積の符号が一貫しているか。途中で符号が反転すれば凹角がある。', ins: ['4\n0 0\n2 0\n2 2\n0 2\n', '4\n0 0\n2 0\n1 1\n2 2\n', '3\n0 0\n1 0\n0 1\n', '5\n0 0\n2 0\n3 1\n1 3\n0 2\n', '4\n0 0\n3 0\n3 3\n0 3\n', '5\n0 0\n4 0\n4 4\n2 1\n0 4\n'] })

t({ lv: 956, concept: '数列: テトラナッチ数', title: 'テトラナッチ数T(n)', tags: ['数学', 'dp'], io: '非負整数 n が1行で与えられます。', ask: 'T(0)=T(1)=T(2)=0, T(3)=1, T(n)=T(n-1)+T(n-2)+T(n-3)+T(n-4) で定まる n 番目のテトラナッチ数を出力してください。', h1: '直近4項を保持する。', h2: '4項の和で次を作る。', ref: 'n=int(input())\nt=[0,0,0,1]\nif n<4:\n    print(t[n])\nelse:\n    for i in range(4,n+1):\n        t.append(t[i-1]+t[i-2]+t[i-3]+t[i-4])\n    print(t[n])', tip: 'テトラナッチは直前4項の和。フィボナッチ(2項)・トリボナッチ(3項)の自然な拡張。', ins: ['4\n', '0\n', '3\n', '7\n', '10\n', '5\n'] })

t({ lv: 957, concept: '数列: ヤコブスタール数', title: 'ヤコブスタール数J(n)', tags: ['数学', 'dp'], io: '非負整数 n が1行で与えられます。', ask: 'J(0)=0, J(1)=1, J(n)=J(n-1)+2·J(n-2) で定まる n 番目のヤコブスタール数を出力してください。', h1: '直近2項を保持する。', h2: '前項+2·前々項。', ref: 'n=int(input())\nif n==0:\n    print(0)\nelif n==1:\n    print(1)\nelse:\n    a,b=0,1\n    for _ in range(2,n+1):\n        a,b=b,b+2*a\n    print(b)', tip: 'ヤコブスタール数は J(n)=J(n-1)+2J(n-2)。(2^n-(-1)^n)/3 という閉じた式も持つ。', ins: ['0\n', '1\n', '5\n', '2\n', '10\n', '7\n'] })

t({ lv: 958, concept: '数列: パドヴァン数', title: 'パドヴァン数P(n)', tags: ['数学', 'dp'], io: '非負整数 n が1行で与えられます。', ask: 'P(0)=P(1)=P(2)=1, P(n)=P(n-2)+P(n-3) で定まる n 番目のパドヴァン数を出力してください。', h1: '直近3項を保持する。', h2: 'P(n-2)+P(n-3)。', ref: 'n=int(input())\np=[1,1,1]\nif n<3:\n    print(p[n])\nelse:\n    for i in range(3,n+1):\n        p.append(p[i-2]+p[i-3])\n    print(p[n])', tip: 'パドヴァン数は P(n)=P(n-2)+P(n-3)。正三角形のらせん配置(プラスチック数)に現れる。', ins: ['0\n', '3\n', '9\n', '5\n', '12\n', '1\n'] })

t({ lv: 959, concept: '数列: ペラン数', title: 'ペラン数P(n)', tags: ['数学', 'dp'], io: '非負整数 n が1行で与えられます。', ask: 'P(0)=3, P(1)=0, P(2)=2, P(n)=P(n-2)+P(n-3) で定まる n 番目のペラン数を出力してください。', h1: '直近3項を保持する。', h2: 'パドヴァンと同じ漸化式だが初期値が違う。', ref: 'n=int(input())\np=[3,0,2]\nif n<3:\n    print(p[n])\nelse:\n    for i in range(3,n+1):\n        p.append(p[i-2]+p[i-3])\n    print(p[n])', tip: 'ペラン数はパドヴァンと同じ漸化式で初期値が違う。素数 p では P(p)≡0 (mod p) という擬素数性で有名。', ins: ['0\n', '1\n', '2\n', '9\n', '10\n', '5\n'] })

t({ lv: 960, concept: '数列: ペル・リュカ数', title: 'ペル・リュカ数Q(n)', tags: ['数学', 'dp'], io: '非負整数 n が1行で与えられます。', ask: 'Q(0)=2, Q(1)=2, Q(n)=2·Q(n-1)+Q(n-2) で定まる n 番目のペル・リュカ数(随伴ペル数)を出力してください。', h1: '直近2項を保持する。', h2: '2倍して前々項を足す。', ref: 'n=int(input())\nif n==0:\n    print(2)\nelif n==1:\n    print(2)\nelse:\n    a,b=2,2\n    for _ in range(2,n+1):\n        a,b=b,2*b+a\n    print(b)', tip: 'ペル・リュカ数(随伴ペル数)はペル数と同じ漸化式で初期値2,2。(1+√2)^n+(1-√2)^n に等しい。', ins: ['0\n', '1\n', '2\n', '5\n', '10\n', '3\n'] })

t({ lv: 961, concept: '数論: 中央二項係数', title: '中央二項係数C(2n,n) mod p', tags: ['数論'], io: '非負整数 n が1行で与えられます。', ask: 'C(2n,n) を 1000000007 で割った余りを出力してください。', h1: '階乗とその逆元を前計算する。', h2: 'C(2n,n)=(2n)!/(n!)²。', ref: `n=int(input())\nMOD=${MOD}\nN=2*n+1\nfact=[1]*(N+1)\nfor i in range(1,N+1):\n    fact[i]=fact[i-1]*i%MOD\ninv=pow(fact[2*n],MOD-2,MOD) if n>0 else 1\nif n==0:\n    print(1)\nelse:\n    invn=pow(fact[n],MOD-2,MOD)\n    print(fact[2*n]*invn%MOD*invn%MOD)`, tip: '中央二項係数 C(2n,n) はカタラン数や格子経路の中心値。階乗とフェルマー逆元で計算する。', ins: ['0\n', '1\n', '2\n', '5\n', '10\n', '3\n'] })

t({ lv: 962, concept: '数え上げ: 周長nの整数三角形', title: '周長nの整数三角形の数', tags: ['数え上げ'], io: '正整数 n が1行で与えられます。', ask: '3辺が正整数で周長が n、三角不等式を満たす相異なる三角形(a<=b<=c)の数を出力してください。', h1: 'a<=b<=c で a+b+c=n を全探索。', h2: 'a+b>c を満たすものを数える。', ref: 'n=int(input())\ncnt=0\nfor a in range(1,n//3+1):\n    for b in range(a,(n-a)//2+1):\n        c=n-a-b\n        if c>=b and a+b>c:\n            cnt+=1\nprint(cnt)', tip: '整数三角形の数は a<=b<=c の順序で全探索し三角不等式 a+b>c を確認する。閉じた式(最近接整数)もある。', ins: ['3\n', '12\n', '1\n', '5\n', '10\n', '15\n'] })

t({ lv: 963, concept: '数論: 完全数の判定', title: '完全数かどうか', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: 'n が完全数(自分自身を除く約数の和が n に等しい)なら yes、そうでなければ no を出力してください。', h1: '真の約数の和を求める。', h2: '和が n に等しいか判定。', ref: 'n=int(input())\nif n<2:\n    print("no")\nelse:\n    s=1\n    d=2\n    while d*d<=n:\n        if n%d==0:\n            s+=d\n            if d!=n//d:\n                s+=n//d\n        d+=1\n    print("yes" if s==n else "no")', tip: '完全数は真約数の和が自分自身に等しい(6,28,496…)。約数列挙は√nで足し合わせる。', ins: ['6\n', '28\n', '12\n', '1\n', '496\n', '8\n'] })

t({ lv: 964, concept: '数論: アリコット和', title: '真の約数の総和', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: 'n 自身を除く正の約数の総和(アリコット和)を出力してください。', h1: '√n まで約数を探す。', h2: 'ペアで足し、n 自身は除く。', ref: 'n=int(input())\nif n==1:\n    print(0)\nelse:\n    s=1\n    d=2\n    while d*d<=n:\n        if n%d==0:\n            s+=d\n            if d!=n//d:\n                s+=n//d\n        d+=1\n    print(s)', tip: 'アリコット和=σ(n)-n(真約数の和)。完全数・友愛数・社交数の判定の基礎になる。', ins: ['12\n', '6\n', '1\n', '28\n', '10\n', '15\n'] })

t({ lv: 965, concept: '数論: 友愛数の判定', title: '友愛数かどうか', tags: ['数論'], io: 'a b が空白区切りで与えられます。', ask: 'a と b が友愛数(互いに相手の真約数の和に等しく、a≠b)なら yes、そうでなければ no を出力してください。', h1: '各数のアリコット和を求める。', h2: 'aliquot(a)=b かつ aliquot(b)=a かつ a≠b。', ref: 'def aliquot(n):\n    if n<2:\n        return 0\n    s=1\n    d=2\n    while d*d<=n:\n        if n%d==0:\n            s+=d\n            if d!=n//d:\n                s+=n//d\n        d+=1\n    return s\na,b=map(int,input().split())\nif a!=b and aliquot(a)==b and aliquot(b)==a:\n    print("yes")\nelse:\n    print("no")', tip: '友愛数は互いに相手の真約数和になる対(220と284が最小)。各数のアリコット和を比較する。', ins: ['220 284\n', '6 6\n', '10 20\n', '284 220\n', '1184 1210\n', '12 15\n'] })

t({ lv: 966, concept: '数論: ハーシャッド数の判定', title: 'ハーシャッド数かどうか', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: 'n が桁和で割り切れる(ハーシャッド数)なら yes、そうでなければ no を出力してください。', h1: '各桁の和を求める。', h2: 'n が桁和で割り切れるか。', ref: 'n=int(input())\ns=sum(int(c) for c in str(n))\nprint("yes" if s!=0 and n%s==0 else "no")', tip: 'ハーシャッド(ニヴェン)数は桁和で割り切れる数。すべての1桁正整数はハーシャッド数。', ins: ['18\n', '19\n', '1\n', '100\n', '21\n', '13\n'] })

t({ lv: 967, concept: '数論: 約数がちょうどk個の数の個数', title: 'n以下で約数がちょうどk個の数の個数', tags: ['数論'], io: 'n k が空白区切りで与えられます。', ask: '1以上 n 以下で正の約数の個数がちょうど k 個の整数の数を出力してください。', h1: '篩で各数の約数の個数を数える。', h2: '各 d がその倍数の約数数を+1。', ref: 'n,k=map(int,input().split())\ndcnt=[0]*(n+1)\nfor d in range(1,n+1):\n    for m in range(d,n+1,d):\n        dcnt[m]+=1\ncnt=sum(1 for i in range(1,n+1) if dcnt[i]==k)\nprint(cnt)', tip: '約数の個数の分布は篩で一括計算。約数がちょうど2個=素数、奇数個=平方数という性質がある。', ins: ['10 2\n', '10 1\n', '16 5\n', '1 1\n', '100 9\n', '20 6\n'] })

t({ lv: 968, concept: '数論: 約数の2乗和', title: '約数の2乗の総和σ₂(n)', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: 'n のすべての正の約数の2乗の総和 σ₂(n) を出力してください。', h1: '√n まで約数を探す。', h2: '各約数 d で d² を足す(ペアの平方も)。', ref: 'n=int(input())\ns=0\nd=1\nwhile d*d<=n:\n    if n%d==0:\n        s+=d*d\n        if d!=n//d:\n            s+=(n//d)**2\n    d+=1\nprint(s)', tip: 'σ_k(n) は約数の k 乗和。乗法的関数で σ₂(p^e)=(p^(2e+2)-1)/(p²-1) と積で計算もできる。', ins: ['6\n', '1\n', '4\n', '12\n', '10\n', '7\n'] })

t({ lv: 969, concept: '数論: 平方数の約数の個数', title: '指数から平方な約数を数える', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: 'n の約数のうち平方数(1,4,9,...)であるものの個数を出力してください。', h1: '素因数分解の各指数 e を求める。', h2: '平方約数の個数は Π(⌊e/2⌋+1)。', ref: 'n=int(input())\nm=n\nres=1\np=2\nwhile p*p<=m:\n    if m%p==0:\n        e=0\n        while m%p==0:\n            m//=p\n            e+=1\n        res*=(e//2+1)\n    p+=1\nif m>1:\n    res*=1\nprint(res)', tip: '平方約数の個数は各素因数の指数 e から ⌊e/2⌋+1 の積。素因数べきの偶数指数の選び方に対応する。', ins: ['12\n', '1\n', '36\n', '8\n', '100\n', '7\n'] })

t({ lv: 970, concept: '数論: ファレイ数列の長さ', title: 'ファレイ数列F_nの項数', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: '分母が n 以下の0以上1以下の既約分数の個数(ファレイ数列 F_n の項数)を出力してください。', h1: '1 + Σ_{i=1}^{n} φ(i)。', h2: '篩でφを求めて累積。', ref: 'n=int(input())\nphi=list(range(n+1))\nfor p in range(2,n+1):\n    if phi[p]==p:\n        for k in range(p,n+1,p):\n            phi[k]-=phi[k]//p\nprint(1+sum(phi[1:n+1]))', tip: 'ファレイ数列 F_n の項数は 1+Σφ(i)。分母 i の既約分数は φ(i) 個あることから導かれる。', ins: ['1\n', '2\n', '5\n', '3\n', '10\n', '6\n'] })

t({ lv: 971, concept: '数論: lcmの総和', title: 'Σlcm(i,n)の値', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: 'Σ_{i=1}^{n} lcm(i,n) を出力してください。', h1: 'lcm(i,n)=i·n/gcd(i,n)。', h2: '各 i について計算して足す。', ref: 'import math\nn=int(input())\ntotal=0\nfor i in range(1,n+1):\n    total+=i*n//math.gcd(i,n)\nprint(total)', tip: 'lcm(i,n)=i·n/gcd(i,n)。総和は (n/2)(1+Σ_{d|n} d·φ(d)) という約数を使った閉じた式も持つ。', ins: ['6\n', '1\n', '5\n', '10\n', '2\n', '12\n'] })

t({ lv: 972, concept: '数論: 回文数の個数', title: 'n以下の回文数の個数', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: '1以上 n 以下で10進表記が回文になる数の個数を出力してください。', h1: '各数の文字列が回文か確認する。', h2: '回文数を数える。', ref: 'n=int(input())\ncnt=0\nfor i in range(1,n+1):\n    s=str(i)\n    if s==s[::-1]:\n        cnt+=1\nprint(cnt)', tip: '回文数は文字列の前後反転と一致する数。桁数ごとに前半を決めれば桁DP/構成で高速に数えられる。', ins: ['10\n', '1\n', '100\n', '22\n', '200\n', '9\n'] })

t({ lv: 973, concept: '数論: ゼッケンドルフ表現の項数', title: 'フィボナッチ和で表す最小項数', tags: ['数論', '貪欲'], io: '正整数 n が1行で与えられます。', ask: 'n を相異なる(連続しない)フィボナッチ数の和で表したときの項数(ゼッケンドルフ表現)を出力してください。', h1: 'n 以下の最大フィボナッチ数を貪欲に引く。', h2: '使った個数を数える。', ref: 'n=int(input())\nfib=[1,2]\nwhile fib[-1]<=n:\n    fib.append(fib[-1]+fib[-2])\ncnt=0\nfor f in reversed(fib):\n    if f<=n:\n        n-=f\n        cnt+=1\nprint(cnt)', tip: 'ゼッケンドルフの定理: 任意の正整数は連続しないフィボナッチ数の和で一意に表せる。貪欲で最大から引く。', ins: ['10\n', '1\n', '100\n', '4\n', '12\n', '50\n'] })

t({ lv: 974, concept: '数論: 立方数の判定', title: '完全立方数かどうか', tags: ['数論', '二分探索'], io: '非負整数 n が1行で与えられます。', ask: 'n が完全立方数(ある非負整数の3乗)なら yes、そうでなければ no を出力してください。', h1: '立方根を二分探索する。', h2: 'mid³ と n を比べる(浮動小数を避ける)。', ref: 'n=int(input())\nlo=0\nhi=max(2,n)\nans=False\nwhile lo<=hi:\n    mid=(lo+hi)//2\n    cube=mid*mid*mid\n    if cube==n:\n        ans=True\n        break\n    elif cube<n:\n        lo=mid+1\n    else:\n        hi=mid-1\nprint("yes" if ans else "no")', tip: '立方数判定は二分探索で mid³ を比較する。浮動小数の cbrt は誤差が出るので整数演算が安全。', ins: ['8\n', '9\n', '27\n', '0\n', '64\n', '10\n'] })

t({ lv: 975, concept: '数論: ピサノ周期', title: 'フィボナッチ数列のmod周期', tags: ['数論'], io: '正整数 m が1行で与えられます(m>=1)。', ask: 'フィボナッチ数列を m で割った余りの周期(ピサノ周期)の長さを出力してください。', h1: '(0,1) が再び現れるまで回す。', h2: '周期は必ず存在する。', ref: 'm=int(input())\nif m==1:\n    print(1)\nelse:\n    a,b=0,1\n    period=0\n    while True:\n        a,b=b,(a+b)%m\n        period+=1\n        if a==0 and b==1:\n            break\n    print(period)', tip: 'ピサノ周期はフィボナッチ mod m の周期。(0,1)のペアが再出現するまでの長さで、必ず有限。', ins: ['2\n', '1\n', '3\n', '5\n', '10\n', '7\n'] })

t({ lv: 976, concept: '数え上げ: k個の部分への合成', title: 'nをk個の正整数の順序付き和にする数', tags: ['数え上げ'], io: 'n k が空白区切りで与えられます。', ask: 'n を順序を区別する k 個の正整数の和(合成)で表す方法の数を出力してください。', h1: '仕切り棒で考える。', h2: 'C(n-1, k-1)。', ref: 'import math\nn,k=map(int,input().split())\nif k<=0 or k>n:\n    print(0)\nelse:\n    print(math.comb(n-1,k-1))', tip: 'n をちょうど k 個の正整数の順序付き和にする合成数は C(n-1,k-1)。n-1個の隙間から k-1個選ぶ。', ins: ['4 2\n', '5 1\n', '5 5\n', '3 4\n', '6 3\n', '10 5\n'] })

t({ lv: 977, concept: '数え上げ: 固定点がk個の順列の数', title: 'ちょうどk個の固定点を持つ順列の数', tags: ['数え上げ'], io: 'n k が空白区切りで与えられます。', ask: '1..n の順列でちょうど k 個の固定点(p[i]=i)を持つものの数を出力してください。', h1: 'k個の固定点を選ぶ。', h2: '残り n-k 個は完全順列 D(n-k)。', ref: 'import math\nn,k=map(int,input().split())\ndef derange(m):\n    if m==0:\n        return 1\n    if m==1:\n        return 0\n    a,b=1,0\n    for i in range(2,m+1):\n        a,b=b,(i-1)*(a+b)\n    return b\nif k>n:\n    print(0)\nelse:\n    print(math.comb(n,k)*derange(n-k))', tip: 'ちょうどk個の固定点を持つ順列数(rencontres数)は C(n,k)·D(n-k)。固定点を選び残りを撹乱する。', ins: ['4 2\n', '3 0\n', '3 3\n', '1 1\n', '5 1\n', '4 4\n'] })

t({ lv: 978, concept: '数え上げ: 1要素の組がない分割', title: '全ブロックが2要素以上の集合分割数', tags: ['数え上げ', 'dp'], io: '非負整数 n が1行で与えられます。', ask: 'n 要素の集合を、どのブロックも2要素以上になるように分割する方法の数を出力してください。', h1: 'a(n)=Σ_{k=2}^{n} C(n-1,k-1)·a(n-k)。', h2: '要素nを含むブロックのサイズkで場合分け。', ref: 'import math\nn=int(input())\na=[0]*(n+1)\na[0]=1\nfor i in range(1,n+1):\n    s=0\n    for k in range(2,i+1):\n        s+=math.comb(i-1,k-1)*a[i-k]\n    a[i]=s\nprint(a[n])', tip: '単集合を含まない集合分割数(随伴ベル数)。要素nの属すブロックのサイズで場合分けする。', ins: ['4\n', '0\n', '1\n', '2\n', '6\n', '5\n'] })

t({ lv: 979, concept: '数え上げ: ラー数', title: 'ラー数L(n,k)', tags: ['数え上げ'], io: 'n k が空白区切りで与えられます。', ask: 'ラー数 L(n,k)=C(n-1,k-1)·n!/k! を出力してください(n要素をk個の空でない順序付きリストに分ける数)。', h1: '組合せと階乗の比で計算。', h2: 'L(n,k)=C(n-1,k-1)·n!/k!。', ref: 'import math\nn,k=map(int,input().split())\nif k<1 or k>n:\n    print(1 if n==0 and k==0 else 0)\nelse:\n    print(math.comb(n-1,k-1)*math.factorial(n)//math.factorial(k))', tip: 'ラー数は n 個を k 個の順序付き非空リストに分ける数。上昇/下降階乗の変換係数としても現れる。', ins: ['4 2\n', '1 1\n', '3 3\n', '3 1\n', '5 2\n', '4 4\n'] })

t({ lv: 980, concept: '数え上げ: カタラン三角形', title: 'カタラン三角形(バリュー数)', tags: ['数え上げ'], io: 'n k が空白区切りで与えられます(k<=n)。', ask: 'C(n+k,k)-C(n+k,k-1)(カタラン三角形の項、k票差以内を保つ経路数)を出力してください。', h1: '2つの二項係数の差。', h2: 'k=n のときカタラン数になる。', ref: 'import math\nn,k=map(int,input().split())\nif k<0 or k>n:\n    print(0)\nelse:\n    a=math.comb(n+k,k)\n    b=math.comb(n+k,k-1) if k-1>=0 else 0\n    print(a-b)', tip: 'カタラン三角形は反射原理(バリュー)で「常にリードを保つ経路数」。対角成分がカタラン数になる。', ins: ['2 2\n', '3 0\n', '4 2\n', '1 1\n', '5 5\n', '3 1\n'] })

t({ lv: 981, concept: 'DP: 歩幅{1,3,4}での上り方', title: '1,3,4歩で階段を上る方法数', tags: ['dp'], io: '非負整数 n が1行で与えられます。', ask: '1段・3段・4段ずつ上って n 段に達する方法(順序を区別)の数を出力してください。', h1: 'dp[x]=dp[x-1]+dp[x-3]+dp[x-4]。', h2: '範囲外の項は0。', ref: 'n=int(input())\ndp=[0]*(n+1)\ndp[0]=1\nfor x in range(1,n+1):\n    for s in (1,3,4):\n        if x-s>=0:\n            dp[x]+=dp[x-s]\nprint(dp[n])', tip: '歩幅集合での上り方は線形漸化式 dp[x]=Σdp[x-s]。{1,3,4} は特定の格子経路数列を生む。', ins: ['4\n', '0\n', '1\n', '5\n', '10\n', '3\n'] })

t({ lv: 982, concept: 'DP: k色で家を塗る最小費用', title: 'k色で家を塗る最小費用', tags: ['dp'], io: '1行目に家の数 n と色数 c、続く n 行に c 個のコスト(各色)が与えられます(隣家は別色)。', ask: '隣り合う家が異色になるように塗る最小費用を出力してください。', h1: 'dp[i][色]=i番目をその色で塗る最小費用。', h2: '前の家の最小・次点を使えば O(n·c)。', ref: 'first=input().split()\nn=int(first[0])\nc=int(first[1])\nif n==0:\n    print(0)\nelse:\n    cost=[list(map(int,input().split())) for _ in range(n)]\n    dp=cost[0][:]\n    for i in range(1,n):\n        ndp=[0]*c\n        for col in range(c):\n            best=float("inf")\n            for pcol in range(c):\n                if pcol!=col and dp[pcol]<best:\n                    best=dp[pcol]\n            ndp[col]=cost[i][col]+best\n        dp=ndp\n    print(min(dp))', tip: 'k色の塗り分けDPは「前の家の最小と2番目の最小」を持てば O(n·c) に高速化できる。', ins: ['3 3\n17 2 17\n16 16 5\n14 3 19\n', '1 2\n5 8\n', '2 2\n1 2\n3 4\n', '2 3\n1 1 1\n1 1 1\n', '0 3\n', '3 2\n1 5\n2 9\n6 1\n'] })

t({ lv: 983, concept: 'ゲーム: 平方数を引くゲーム', title: '平方数を引く石取りの勝者', tags: ['ゲーム', 'dp'], io: '山の石の数 n が1行で与えられます。', ask: '各手番で平方数(1,4,9,...)の個数を引く操作を交互に行い、引けなくなった(0になった)方の相手が勝ちます。先手必勝なら First、後手必勝なら Second を出力してください。', h1: 'dp[i]=石iで手番の人が勝てるか。', h2: 'ある平方数sでdp[i-s]が負け局面なら勝ち。', ref: 'n=int(input())\nwin=[False]*(n+1)\nfor i in range(1,n+1):\n    s=1\n    while s*s<=i:\n        if not win[i-s*s]:\n            win[i]=True\n            break\n        s+=1\nprint("First" if win[n] else "Second")', tip: '平方数を引くゲームは「ある手で相手を負け局面にできれば勝ち」のDP(後退解析)。Sprague-Grundyの基本形。', ins: ['1\n', '2\n', '4\n', '7\n', '0\n', '17\n'] })

t({ lv: 984, concept: 'グラフ: 推移閉包の到達対数', title: '到達可能な順序対の数(推移閉包)', tags: ['グラフ'], io: '1行目に n m、続く m 行に有向辺 u v が与えられます。', ask: '推移閉包で u から v へ到達可能(u≠v)な順序対 (u,v) の個数を出力してください。', h1: '各頂点からBFS/DFSで到達集合を求める。', h2: '到達できた頂点数(自分を除く)を合計。', ref: 'first=input().split()\nn=int(first[0])\nm=int(first[1])\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\ntotal=0\nfor s in range(1,n+1):\n    seen=[False]*(n+1)\n    seen[s]=True\n    stack=[s]\n    cnt=0\n    while stack:\n        x=stack.pop()\n        for y in g[x]:\n            if not seen[y]:\n                seen[y]=True\n                cnt+=1\n                stack.append(y)\n    total+=cnt\nprint(total)', tip: '推移閉包の到達対数は各頂点からの到達数の合計。密グラフはビットセット(Warshall)で O(n³/64) に。', ins: ['3 2\n1 2\n2 3\n', '3 0\n', '4 4\n1 2\n2 3\n3 4\n4 1\n', '1 0\n', '3 3\n1 2\n1 3\n2 3\n', '2 1\n1 2\n'] })

t({ lv: 985, concept: 'グラフ: 負辺ありの最短路', title: 'ベルマンフォードの最短距離', tags: ['グラフ'], io: '1行目に n m s t、続く m 行に有向辺 u v w(負の重みあり)が与えられます。', ask: 's から t への最短距離を出力してください。到達不能なら INF、負閉路の影響で下限が無いなら NEG を出力してください。', h1: 'ベルマンフォードで n-1 回緩和。', h2: 'n 回目に t へ伝わる更新があれば負閉路の影響。', ref: 'first=input().split()\nn=int(first[0])\nm=int(first[1])\ns=int(first[2])\ntt=int(first[3])\nedges=[]\nfor _ in range(m):\n    u,v,w=map(int,input().split())\n    edges.append((u,v,w))\nINF=float("inf")\ndist=[INF]*(n+1)\ndist[s]=0\nfor _ in range(n-1):\n    for u,v,w in edges:\n        if dist[u]!=INF and dist[u]+w<dist[v]:\n            dist[v]=dist[u]+w\nneg=set()\nfor _ in range(n):\n    for u,v,w in edges:\n        if dist[u]!=INF and dist[u]+w<dist[v]:\n            dist[v]=dist[u]+w\n            neg.add(v)\nfrom collections import deque\nbad=set(neg)\ndq=deque(neg)\nadj=[[] for _ in range(n+1)]\nfor u,v,w in edges:\n    adj[u].append(v)\nwhile dq:\n    x=dq.popleft()\n    for y in adj[x]:\n        if y not in bad:\n            bad.add(y)\n            dq.append(y)\nif tt in bad:\n    print("NEG")\nelif dist[tt]==INF:\n    print("INF")\nelse:\n    print(dist[tt])', tip: 'ベルマンフォードは負辺対応の最短路。n回目で更新される頂点から到達できる先は負閉路の影響下(下限なし)。', ins: ['4 4 1 4\n1 2 1\n2 3 -2\n3 4 1\n1 4 5\n', '2 1 1 2\n1 2 -3\n', '3 3 1 3\n1 2 1\n2 1 -2\n2 3 1\n', '2 0 1 2\n', '1 0 1 1\n', '3 2 1 3\n1 2 4\n2 3 -1\n'] })

t({ lv: 986, concept: 'グラフ: 根付き木の同型判定', title: '2つの根付き木が同型か', tags: ['グラフ', '木'], io: '1行目に n、続く n-1 行に木Aの辺(根は1)、次に n-1 行に木Bの辺(根は1)が与えられます。', ask: '木Aと木Bが根付き木として同型なら yes、そうでなければ no を出力してください。', h1: '各部分木を正規形(子の正規形をソート)にする。', h2: '根の正規形が一致するか比較。', ref: 'import sys\nsys.setrecursionlimit(500000)\nn=int(input())\ndef build():\n    g=[[] for _ in range(n+1)]\n    for _ in range(n-1):\n        u,v=map(int,input().split())\n        g[u].append(v)\n        g[v].append(u)\n    return g\ndef canon(g):\n    parent=[0]*(n+1)\n    order=[]\n    seen=[False]*(n+1)\n    seen[1]=True\n    stack=[1]\n    while stack:\n        x=stack.pop()\n        order.append(x)\n        for y in g[x]:\n            if not seen[y]:\n                seen[y]=True\n                parent[y]=x\n                stack.append(y)\n    sig=[""]*(n+1)\n    for x in reversed(order):\n        kids=sorted(sig[y] for y in g[x] if y!=parent[x])\n        sig[x]="("+"".join(kids)+")"\n    return sig[1]\ngA=build()\ngB=build()\nprint("yes" if canon(gA)==canon(gB) else "no")', tip: '根付き木の同型判定は「各部分木の正規形=子の正規形をソートして括弧で囲む」を再帰的に作り根で比較する(AHUアルゴリズム)。', ins: ['4\n1 2\n1 3\n3 4\n1 2\n2 3\n1 4\n', '3\n1 2\n2 3\n1 2\n1 3\n', '1\n1\n', '4\n1 2\n2 3\n3 4\n1 2\n2 3\n3 4\n', '5\n1 2\n1 3\n2 4\n2 5\n1 2\n1 3\n3 4\n3 5\n', '2\n1 2\n1 2\n'] })

t({ lv: 987, concept: 'グラフ: プリューファー列の復元', title: 'プリューファー列から次数列', tags: ['グラフ', '木'], io: '1行目に頂点数 n、2行目に長さ n-2 のプリューファー列(n>=2、n=2 のときは空行)が与えられます。', ask: 'プリューファー列が表す木の各頂点(1..n)の次数を、昇順に並べて空白区切りで出力してください。', h1: '頂点 v の次数は「列中の出現回数 + 1」。', h2: '出現回数を数えて+1する。', ref: 'n=int(input())\nline=input().split()\nseq=list(map(int,line)) if line else []\ndeg=[1]*(n+1)\nfor x in seq:\n    deg[x]+=1\nresult=sorted(deg[1:n+1])\nprint(*result)', tip: 'プリューファー列では頂点vの次数=列中の出現回数+1。木とのn^(n-2)通りの全単射の核心。', ins: ['4\n1 1\n', '2\n\n', '5\n3 3 3\n', '6\n2 4 4 6\n', '3\n2\n', '4\n2 3\n'] })

t({ lv: 988, concept: 'DP: 長さkの相異なる部分列の数', title: '長さkの相異なる部分列の数', tags: ['dp', '文字列'], io: '1行目に文字列 s、2行目に長さ k が与えられます。', ask: '長さ k の相異なる部分列の数を 1000000007 で割った余りで出力してください。', h1: 'dp[j]=長さjの相異なる部分列数。', h2: '各文字で後ろから dp[j]+=dp[j-1]、同じ文字の前回寄与を引く。', ref: `s=input()\nk=int(input())\nMOD=${MOD}\nn=len(s)\ndp=[0]*(k+1)\ndp[0]=1\nlast={}\nfor i in range(n):\n    c=s[i]\n    prev=last.get(c,None)\n    add=[0]*(k+1)\n    for j in range(1,k+1):\n        add[j]=dp[j-1]\n    for j in range(1,k+1):\n        dp[j]=(dp[j]+add[j])%MOD\n    if prev is not None:\n        for j in range(1,k+1):\n            dp[j]=(dp[j]-prev[j-1])%MOD\n    last[c]=add[:]\nprint(dp[k]%MOD)`, tip: '長さ別の相異なる部分列数DP。各文字の「前回追加した寄与」を引いて重複を防ぐのが要点。', ins: ['abc\n2\n', 'aaa\n2\n', 'aba\n2\n', 'abc\n3\n', 'aabb\n2\n', 'abcd\n1\n'] })

t({ lv: 989, concept: 'DP: 括弧を釣り合わせる最小挿入', title: '括弧列を正しくする最小挿入数', tags: ['文字列', '貪欲'], io: '( と ) からなる文字列が1行で与えられます。', ask: '正しく対応した括弧列にするために挿入すべき括弧の最小数を出力してください。', h1: '開き括弧の数を追う。', h2: '閉じ過ぎたら開きを挿入、最後に余った開きの分だけ閉じを挿入。', ref: 's=input()\nopen_cnt=0\ninsert=0\nfor c in s:\n    if c=="(":\n        open_cnt+=1\n    else:\n        if open_cnt>0:\n            open_cnt-=1\n        else:\n            insert+=1\nprint(insert+open_cnt)', tip: '最小挿入は「閉じ過ぎたら開きを補い、最後に余った開きの数だけ閉じを補う」貪欲。スタック高で追う。', ins: ['())\n', '(((\n', '()\n', ')(\n', '\n', '(()))(\n'] })

t({ lv: 990, concept: 'DP: 括弧を反転する最小回数', title: '括弧列を釣り合わせる最小反転数', tags: ['文字列', '貪欲'], io: '{ と } からなる文字列が1行で与えられます。', ask: '一部の括弧を反転して全体を正しく対応させる最小反転数を出力してください。奇数長なら -1。', h1: '対応済みを消し、余った "}...{" を数える。', h2: '余り m 個の開き・c 個の閉じから ⌈m/2⌉+⌈c/2⌉。', ref: 's=input()\nif len(s)%2==1:\n    print(-1)\nelse:\n    op=0\n    cl=0\n    for c in s:\n        if c=="{":\n            op+=1\n        else:\n            if op>0:\n                op-=1\n            else:\n                cl+=1\n    print((op+1)//2+(cl+1)//2)', tip: '釣り合わせる最小反転は、対応を取った後に残る「閉じ余りcl・開き余りop」から ⌈cl/2⌉+⌈op/2⌉。', ins: ['}{\n', '{{\n', '{}\n', '{{{{\n', '}}{{\n', '{}{}}{\n'] })

t({ lv: 991, concept: '数え上げ: 自己共役な分割の数', title: '相異なる奇数への分割の数', tags: ['dp', '数え上げ'], io: '非負整数 n が1行で与えられます。', ask: 'n を相異なる奇数の和で表す方法(=自己共役なヤング図形の数)を出力してください。', h1: '部品を奇数 1,3,5,... に限定する。', h2: '各奇数を高々1回使う0/1ナップサック。', ref: 'n=int(input())\ndp=[0]*(n+1)\ndp[0]=1\nk=1\nwhile k<=n:\n    for x in range(n,k-1,-1):\n        dp[x]+=dp[x-k]\n    k+=2\nprint(dp[n])', tip: '相異なる奇数への分割数=自己共役な分割の数(ヤング図形が対角線対称)。各奇数を高々1回の0/1ナップサック。', ins: ['8\n', '0\n', '1\n', '10\n', '5\n', '20\n'] })

t({ lv: 992, concept: '数列: スターンの数列', title: 'スターンの二進数列a(n)', tags: ['数学'], io: '非負整数 n が1行で与えられます。', ask: 'a(0)=0, a(1)=1, a(2n)=a(n), a(2n+1)=a(n)+a(n+1) で定まる n 番目のスターン数列を出力してください。', h1: '配列で順に計算する。', h2: '偶数添字は半分、奇数は隣接2項の和。', ref: 'n=int(input())\nif n==0:\n    print(0)\nelif n==1:\n    print(1)\nelse:\n    a=[0,1]\n    for i in range(2,n+1):\n        if i%2==0:\n            a.append(a[i//2])\n        else:\n            a.append(a[i//2]+a[i//2+1])\n    print(a[n])', tip: 'スターンの二進数列(diatomic)は隣接項の比が全ての既約分数を一度ずつ生む(Stern-Brocot木に対応)。', ins: ['0\n', '1\n', '5\n', '10\n', '2\n', '15\n'] })

t({ lv: 993, concept: 'bit演算: 同じ立ちビット数の次の整数', title: '同じ1の数を持つ次に大きい整数', tags: ['bit演算'], io: '正整数 n が1行で与えられます。', ask: 'n と同じ個数の立っているビットを持つ、n より大きい最小の整数を出力してください。', h1: '最下位の1のブロックを操作する。', h2: 'Gosperのハック(snoob)で1命令的に求める。', ref: 'n=int(input())\nc=n&(-n)\nr=n+c\nnxt=r|(((n^r)>>2)//c)\nprint(nxt)', tip: 'Gosperのハック(snoob): 最下位の1の塊を繰り上げ、余った1を最下位へ詰めて同じビット数の次の数を作る。', ins: ['5\n', '6\n', '3\n', '1\n', '7\n', '12\n'] })

t({ lv: 994, concept: 'bit演算: 連続する1の最大長', title: '2進表記で連続する1の最大長', tags: ['bit演算'], io: '非負整数 n が1行で与えられます。', ask: 'n の2進表記で1が連続する最大の長さを出力してください。', h1: '下位ビットから走査する。', h2: '1が続く長さを数え最大を更新。', ref: 'n=int(input())\nbest=0\ncur=0\nwhile n>0:\n    if n&1:\n        cur+=1\n        if cur>best:\n            best=cur\n    else:\n        cur=0\n    n>>=1\nprint(best)', tip: '連続1の最大長は下位から走査して数える。n&(n>>1) を繰り返し0になる回数でも求まる。', ins: ['7\n', '0\n', '5\n', '13\n', '15\n', '8\n'] })

t({ lv: 995, concept: '数え上げ: 円の弦が作る領域数', title: '円周上のn点の弦が作る領域数', tags: ['数え上げ'], io: '非負整数 n が1行で与えられます。', ask: '円周上に一般の位置で n 点を取り全ての弦を引いたとき、円が分割される領域の最大数(モーザーの円)を出力してください。', h1: 'オイラーの多面体公式から導く。', h2: 'C(n,4)+C(n,2)+1。', ref: 'import math\nn=int(input())\nprint(math.comb(n,4)+math.comb(n,2)+1)', tip: 'モーザーの円問題: 領域数は C(n,4)+C(n,2)+1。n=1..6 で 1,2,4,8,16,31 と「2のべきに見えて違う」有名な罠。', ins: ['1\n', '2\n', '3\n', '4\n', '5\n', '6\n'] })

t({ lv: 996, concept: '数え上げ: 直線がn本で作る領域数', title: 'n本の直線が平面を分ける最大領域数', tags: ['数え上げ'], io: '非負整数 n が1行で与えられます。', ask: '平面に n 本の直線を一般の位置で引いたときの最大領域数を出力してください。', h1: 'k 本目の直線は最大 k 個の領域を増やす。', h2: 'n(n+1)/2 + 1(怠け仕出し屋の数列)。', ref: 'n=int(input())\nprint(n*(n+1)//2+1)', tip: '怠け仕出し屋の数列: n本の直線が作る最大領域は n(n+1)/2+1。k本目が既存k本と交わりk領域増やす。', ins: ['0\n', '1\n', '2\n', '3\n', '5\n', '10\n'] })

t({ lv: 997, concept: '数え上げ: n平面が空間を分ける領域数', title: 'n枚の平面が空間を分ける最大領域数', tags: ['数え上げ'], io: '非負整数 n が1行で与えられます。', ask: '空間に n 枚の平面を一般の位置で置いたときの最大領域数(ケーキ数)を出力してください。', h1: 'C(n,3)+C(n,2)+C(n,1)+C(n,0)。', h2: '怠け仕出し屋の3次元版。', ref: 'import math\nn=int(input())\nprint(math.comb(n,3)+math.comb(n,2)+math.comb(n,1)+1)', tip: 'ケーキ数: n枚の平面が空間を分ける最大領域は C(n,3)+C(n,2)+C(n,1)+1。怠け仕出し屋の3次元版。', ins: ['0\n', '1\n', '2\n', '3\n', '5\n', '10\n'] })

t({ lv: 998, concept: '数論: 素数の原始根の個数', title: '素数の原始根の個数', tags: ['数論'], io: '素数 p が1行で与えられます。', ask: 'p の原始根の個数を出力してください。', h1: '原始根の個数は φ(p-1)。', h2: 'p-1 のトーシェントを求める。', ref: 'p=int(input())\nif p==2:\n    print(1)\nelse:\n    n=p-1\n    res=n\n    m=n\n    q=2\n    while q*q<=m:\n        if m%q==0:\n            while m%q==0:\n                m//=q\n            res-=res//q\n        q+=1\n    if m>1:\n        res-=res//m\n    print(res)', tip: '素数 p の原始根の個数は φ(p-1)。原始根が1つ存在すれば、その φ(p-1) 乗が全ての原始根を与える。', ins: ['7\n', '2\n', '5\n', '11\n', '13\n', '23\n'] })

export const CATALOG = TASKS
