// 生成タスク 第79波：各レベル3問化フェーズ(6)。lv280〜328 の薄い49段に3問目を追加。
// 文字列/グラフ/DP/数え上げ/区間帯。クラスタ3問まで可・言い換え水増し禁止。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 280, concept: '文字列: ランの回数が最も多い文字', title: '一番細切れにされた文字', tags: ['文字列'], io: '英小文字の文字列が1行で与えられます。', ask: '連続の切れ目で数えて「かたまり(ラン)の回数」が最も多い文字を出力してください(同数なら辞書順で小さい方)。', h1: 'ランの先頭だけ文字ごとに数える。', h2: '前と違う文字が現れた位置がランの開始。', ref: 'from collections import Counter\ns=input()\nc=Counter()\nfor i,ch in enumerate(s):\n    if i==0 or s[i-1]!=ch:\n        c[ch]+=1\nprint(min(c.items(),key=lambda kv:(-kv[1],kv[0]))[0])', tip: 'ランレングス圧縮(同レベル既出)の集計をひねった量で、「出現回数が多い」と「分断されている」は別の性質。aabaa なら a は3回現れず2ラン、と数える切り口の練習。', ins: ['aabaa\n', 'abab\n', 'zzz\n', 'abc\n', 'bbaacbb\n', 'cabac\n'] })

t({ lv: 281, concept: 'スタック: 対応する括弧の位置', title: 'この括弧はどこで閉じる', tags: ['スタック'], io: '1行目に正しい括弧列、2行目に開き括弧の位置 p (1始まり) が与えられます。', ask: 'p の開き括弧に対応する閉じ括弧の位置(1始まり)を出力してください。', h1: '深さを数えながら右へ進む。', h2: 'pから始めて深さが0に戻った場所が対応点。', ref: 's=input()\np=int(input())\ndepth=0\nfor i in range(p-1,len(s)):\n    if s[i]=="(":\n        depth+=1\n    else:\n        depth-=1\n    if depth==0:\n        print(i+1)\n        break', tip: 'エディタの「対応する括弧へジャンプ」機能の中身そのもの。全対応表を作るならスタックで一括、1点だけなら深さカウンタで十分、と問いの規模が実装を選ぶ。', ins: ['(())\n2\n', '()\n1\n', '(()())\n1\n', '(()())\n4\n', '((()))\n2\n', '()()\n3\n'] })

t({ lv: 282, concept: 'リスト: 累積和が最小になる位置', title: 'どこまでで一番沈むか', tags: ['リスト', '累積和'], io: '整数列が1行で空白区切りで与えられます。', ask: '先頭から i 項の和(i は1以上)が最小になる最小の i を出力してください。', h1: '最大になる位置(同レベル既出)の鏡像。', h2: '「より小さいときだけ」更新すれば最小のiが残る。', ref: 'a=list(map(int,input().split()))\nbest=None\nbi=0\ns=0\nfor i,x in enumerate(a,1):\n    s+=x\n    if best is None or s<best:\n        best=s\n        bi=i\nprint(bi)', tip: '株価の「底」を探す操作で、最大ドローダウンの計算にも顔を出す。argminは同点処理の規約(最初か最後か)を仕様に書かないと答えが揺れる。', ins: ['1 -3 2\n', '-1 -2 3\n', '5\n', '2 2 2\n', '3 -1 -1 4\n', '-5 10 -6\n'] })

t({ lv: 283, concept: '文字列: 2回目に現れる位置', title: '再会の場所', tags: ['文字列'], io: '1行目に文字列、2行目に文字(その文字列に2回以上現れる)が与えられます。', ask: 'その文字が2回目に現れる位置(1始まり)を出力してください。', h1: 'findは開始位置を指定できる。', h2: '1回目の位置+1から探し直す。', ref: 's=input()\nc=input()\nfirst=s.find(c)\nprint(s.find(c,first+1)+1)', tip: 'find の第2引数(開始位置)を知っていれば2行で済む。ループでk回目の出現に一般化するとき、この「前回の次から探す」形がそのまま骨組みになる。', ins: ['banana\na\n', 'aabb\nb\n', 'abcabc\nc\n', 'xx\nx\n', 'hello\nl\n', 'mississippi\ns\n'] })

t({ lv: 284, concept: '文字列: 辞書順で最大になる回転', title: '回して作る一番強い並び', tags: ['文字列'], io: '文字列が1行で与えられます。', ask: '文字列の回転(あるところで切って前後を入れ替えたもの)のうち、辞書順で最大のものを出力してください。', h1: '最小になる回転(同レベル既出)の鏡像。', h2: '全回転を作ってmax。', ref: 's=input()\nprint(max(s[i:]+s[:i] for i in range(len(s))))', tip: '最小回転はブースの線形アルゴリズムが有名だが、maxへの書き換えも同型でできる。全生成のO(n²)版を正解の基準に置くのが安全な進め方。', ins: ['bca\n', 'aaa\n', 'ab\n', 'cba\n', 'zaz\n', 'dabc\n'] })

t({ lv: 285, concept: 'リスト: 最小値が現れる回数', title: '最下位タイは何人', tags: ['リスト'], io: '整数列が1行で空白区切りで与えられます。', ask: '最小値が現れる回数を出力してください。', h1: '最大値版(同レベル既出)の鏡像。', h2: 'a.count(min(a))。', ref: 'a=list(map(int,input().split()))\nprint(a.count(min(a)))', tip: '2パス(minを求めてからcount)の素直さと、1パスで最小値と回数を同時更新する書き方の対比が学べる。ストリーム処理では1パス版しか選べない。', ins: ['3 1 2 1\n', '5\n', '2 2 2\n', '9 8 7\n', '0 0 1\n', '4 4 5 4\n'] })

t({ lv: 286, concept: '文字列: 母音と子音が交互な最長区間', title: 'リズムよく読める区間', tags: ['文字列'], io: '英小文字の文字列が1行で与えられます。', ask: '母音(a,i,u,e,o)と子音が交互に並ぶ最長の連続区間の長さを出力してください。', h1: '「種類が切り替わったら伸ばす」型の走査。', h2: '前の文字と母音/子音の種別が違えばrun+1、同じなら1にリセット。', ref: 's=input()\ndef v(c):\n    return c in "aiueo"\nbest=1\nrun=1\nfor i in range(1,len(s)):\n    if v(s[i])!=v(s[i-1]):\n        run+=1\n        if run>best:\n            best=run\n    else:\n        run=1\nprint(best)', tip: '0/1交互・偶奇交互と同じ骨格を「文字を2クラスに射影してから」適用する合成。判定関数を差し替えるだけで無数の変種が作れることを体感したい。', ins: ['banana\n', 'aab\n', 'xyz\n', 'aiueo\n', 'ba\n', 'aba\n'] })

t({ lv: 287, concept: '数え上げ: 等比の3つ組の数', title: '掛け算でつながる3人', tags: ['数え上げ'], io: '正整数の列が1行で空白区切りで与えられます。', ask: 'i<j<k で a[j]÷a[i] と a[k]÷a[j] の比が等しい(a[j]²=a[i]×a[k])3つ組の個数を出力してください。', h1: '等差の3つ組(既出)の掛け算版。', h2: '割り算を使わず a[j]*a[j]==a[i]*a[k] で比べると誤差も整数制約も気にならない。', ref: 'a=list(map(int,input().split()))\nn=len(a)\ncnt=0\nfor i in range(n):\n    for j in range(i+1,n):\n        for k in range(j+1,n):\n            if a[j]*a[j]==a[i]*a[k]:\n                cnt+=1\nprint(cnt)', tip: '比の等しさを積の等しさに直す変形は、浮動小数を避ける整数算法の基本技。幾何平均が真ん中に立つ、等差の算術平均との美しい対応がある。', ins: ['1 2 4\n', '1 1 1\n', '2 4 8 16\n', '1 2 3\n', '1 3 9 27\n', '3 3 3 3\n'] })

t({ lv: 288, concept: 'ハッシュ: 最頻値が複数あるか', title: '首位は単独か同率か', tags: ['ハッシュ'], io: '整数列が1行で空白区切りで与えられます。', ask: '最も多く現れる値が2種類以上あるなら yes、単独なら no を出力してください。', h1: '最大の出現回数を先に求める。', h2: 'その回数を持つ値の種類を数える。', ref: 'from collections import Counter\nc=Counter(input().split())\nm=max(c.values())\nprint("yes" if sum(1 for v in c.values() if v==m)>=2 else "no")', tip: '統計の最頻値(モード)は「一意に決まらないことがある」代表選手。モードが複数ある分布(多峰性)の検出は、データのクラスタ構造を疑う最初のシグナルになる。', ins: ['1 1 2 2 3\n', '1 1 2\n', '5\n', '1 2\n', '3 3 3\n', '1 1 2 2 3 3\n'] })

t({ lv: 289, concept: '整数: 区間内のゾロ目の個数', title: 'ぞろ目を拾い集める', tags: ['整数'], io: 'L R が空白区切りで1行で与えられます (1≤L≤R)。', ask: 'L 以上 R 以下で、全ての桁が同じ数字である数(ゾロ目)の個数を出力してください(1桁の数もゾロ目とみなします)。', h1: 'ゾロ目の判定(既出)を範囲に適用。', h2: 'len(set(str(x)))==1。', ref: 'l,r=map(int,input().split())\nprint(sum(1 for x in range(l,r+1) if len(set(str(x)))==1))', tip: 'ゾロ目は d×(10^k−1)/9 の形で、各桁数にちょうど9個しかない。総当たりの答えを「桁数×9から数える」賢い方法で検算すると二重に安心できる。', ins: ['1 100\n', '10 40\n', '5 5\n', '100 999\n', '12 21\n', '1 9\n'] })

t({ lv: 290, concept: 'DP: 回文に分割する方法の数', title: '回文だけの切り分け方', tags: ['DP', '文字列'], io: '英小文字の文字列が1行で与えられます。', ask: '文字列を1個以上の回文の連続した断片に切り分ける方法の総数を出力してください。', h1: '最小カット数(同レベル既出)の数え上げ版。', h2: 'dp[i] は先頭i文字の分け方の数。末尾の断片が回文になる切れ目から足し込む。', ref: 's=input()\nn=len(s)\ndp=[0]*(n+1)\ndp[0]=1\nfor i in range(1,n+1):\n    for j in range(i):\n        p=s[j:i]\n        if p==p[::-1]:\n            dp[i]+=dp[j]\nprint(dp[n])', tip: '最適化(最小カット)と数え上げは同じ遷移で、初期値とmin/加算だけが違う。1文字は必ず回文なので方法数は必ず1以上、という下限も自動で保証される。', ins: ['aab\n', 'ab\n', 'aaa\n', 'abc\n', 'aba\n', 'aabb\n'] })

t({ lv: 291, concept: '貪欲: 交互に大きい方を取る得点差', title: '大きい順に取り合ったら', tags: ['貪欲', 'ソート'], io: '整数列が1行で空白区切りで与えられます。', ask: '2人が交互に「残っている中で最大の値」を取っていくとき、先手の合計から後手の合計を引いた値を出力してください。', h1: '降順に並べて交互に配る。', h2: '偶数番目の和−奇数番目の和。', ref: 'a=sorted(map(int,input().split()),reverse=True)\nprint(sum(a[::2])-sum(a[1::2]))', tip: '両端からしか取れないゲーム(同レベル既出)は区間DPが要ったが、どこからでも取れるなら貪欲が最適になる。ルールの自由度が上がると解法が簡単になる逆転が起きている。', ins: ['3 1 2\n', '5 5\n', '1 2 3 4\n', '7\n', '1 1 1\n', '10 1\n'] })

t({ lv: 292, concept: 'リスト: 各要素の最大桁の合計', title: 'それぞれの一番大きな桁', tags: ['リスト', '整数'], io: '正整数の列が1行で空白区切りで与えられます。', ask: '各要素について十進表記の最大の桁を求め、その合計を出力してください。', h1: '文字列にすればmaxが桁の最大。', h2: 'max(str(x)) を int にして足す。', ref: 'print(sum(int(max(str(x))) for x in input().split()))', tip: '文字の比較 "9">"1" が数字の大小と一致するASCIIの性質を使うと、intへの変換は最後の1回で済む。偶数桁の合計(同レベル既出)と同じ「要素→桁集計→総和」の型。', ins: ['19 25 7\n', '100\n', '11 22\n', '999 5\n', '10 20 30\n', '48372\n'] })

t({ lv: 293, concept: '整数: 桁の並べ替えで作る最大の偶数', title: '並べ替えて一番大きな偶数に', tags: ['整数', '貪欲'], io: '偶数の桁を1つ以上含む正整数が1行で与えられます。', ask: '桁を並べ替えてできる数のうち、最大の偶数を出力してください(先頭の0は現れないものとします)。', h1: '最大(同レベル既出)に「末尾が偶数」の制約を足す。', h2: '一番小さい偶数の桁を末尾に固定し、残りを降順に並べる。', ref: 's=input()\nd=sorted(s,reverse=True)\nev=min(c for c in d if int(c)%2==0)\nd.remove(ev)\nprint("".join(d)+ev)', tip: '制約つき最大化は「犠牲を最小にする」発想で解く: 末尾に回して一番損しないのは最小の偶数桁。貪欲の正しさを一言で説明できる形にしておくと応用が利く。', ins: ['1234\n', '121\n', '2\n', '302\n', '988\n', '2711\n'] })

t({ lv: 294, concept: 'グラフ: 入次数と出次数が等しい頂点の数', title: '出入りが釣り合う頂点', tags: ['グラフ'], io: '1行目に頂点数 n と辺数 m、続く m 行に有向辺 u v が与えられます。', ask: '入次数と出次数が等しい頂点の個数を出力してください(辺のない頂点は0=0で等しいとみなします)。', h1: '2本の次数配列を作る。', h2: '辺 u→v で out[u] と in[v] を増やす。', ref: 'n,m=map(int,input().split())\nind=[0]*(n+1)\noutd=[0]*(n+1)\nfor _ in range(m):\n    u,v=map(int,input().split())\n    outd[u]+=1\n    ind[v]+=1\nprint(sum(1 for v in range(1,n+1) if ind[v]==outd[v]))', tip: '全頂点で入次数と出次数が等しいことは、有向グラフにオイラー閉路がある条件の片翼(もう片翼は連結性)。閉路判定(同レベル既出)と並べて学ぶと位置づけが見える。', ins: ['3 3\n1 2\n2 3\n3 1\n', '2 1\n1 2\n', '3 2\n1 2\n2 1\n', '4 3\n1 2\n1 3\n1 4\n', '1 0\n', '4 4\n1 2\n2 3\n3 4\n4 2\n'] })

t({ lv: 295, concept: 'グラフ: 多重辺の組数', title: 'だぶって張られた辺', tags: ['グラフ'], io: '1行目に頂点数 n と辺数 m、続く m 行に無向辺 u v が与えられます。', ask: '同じ2頂点を結ぶ辺のペア(i<j)の個数を出力してください(u vとv uは同じ辺とみなします)。', h1: '辺を(小さい方, 大きい方)に正規化する。', h2: '辺ごとの本数cから C(c,2) を足す。', ref: 'from collections import Counter\nn,m=map(int,input().split())\nc=Counter()\nfor _ in range(m):\n    u,v=map(int,input().split())\n    c[(min(u,v),max(u,v))]+=1\nprint(sum(v*(v-1)//2 for v in c.values()))', tip: '多重辺の検出は入力データの検疫として実務でも最初にやる処理。無向辺の正規化(ソートしてタプル化)は、辺を集合や辞書のキーにする際の定番の下ごしらえ。', ins: ['3 3\n1 2\n2 1\n1 3\n', '2 3\n1 2\n1 2\n1 2\n', '3 2\n1 2\n2 3\n', '2 2\n1 2\n2 1\n', '4 5\n1 2\n3 4\n1 2\n3 4\n1 2\n', '1 0\n'] })

t({ lv: 296, concept: 'グラフ: 相互に到達できる頂点対の数', title: 'お互いに行き来できる2頂点', tags: ['グラフ', 'DFS'], io: '1行目に頂点数 n と辺数 m、続く m 行に有向辺 u v が与えられます。', ask: 'u から v へも v から u へも到達できる頂点対(u<v)の個数を出力してください。', h1: '各頂点から到達できる集合を求める。', h2: '両方向の到達可能性をペアごとに確かめる。', ref: 'n,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\nreach=[]\nfor s in range(n+1):\n    seen=[False]*(n+1)\n    if s>0:\n        seen[s]=True\n        st=[s]\n        while st:\n            x=st.pop()\n            for y in g[x]:\n                if not seen[y]:\n                    seen[y]=True\n                    st.append(y)\n    reach.append(seen)\ncnt=0\nfor u in range(1,n+1):\n    for v in range(u+1,n+1):\n        if reach[u][v] and reach[v][u]:\n            cnt+=1\nprint(cnt)', tip: '相互到達は同値関係で、その類が強連結成分(SCC)。この対の数は各成分サイズsのC(s,2)の和に等しく、TarjanのSCC分解の答え合わせに使える。', ins: ['3 3\n1 2\n2 3\n3 1\n', '2 1\n1 2\n', '4 4\n1 2\n2 1\n3 4\n4 3\n', '3 2\n1 2\n2 3\n', '2 2\n1 2\n2 1\n', '5 5\n1 2\n2 3\n3 1\n4 5\n5 4\n'] })

t({ lv: 297, concept: 'グラフ: 片方向だけの頂点対の数', title: '一方通行の関係', tags: ['グラフ'], io: '1行目に頂点数 n と辺数 m、続く m 行に有向辺 u v が与えられます(同じ辺の重複はありません)。', ask: '2頂点の組 {u,v} のうち、u→v と v→u のどちらか一方の辺だけが存在する組の個数を出力してください。', h1: '双方向の対(同レベル既出)の補集合ではなく、辺の有無の組合せで数える。', h2: '辺集合に (u,v) があって (v,u) が無いものを数え、向きの重複に注意。', ref: 'n,m=map(int,input().split())\nE=set()\nfor _ in range(m):\n    u,v=map(int,input().split())\n    E.add((u,v))\ncnt=0\nfor u,v in E:\n    if (v,u) not in E:\n        cnt+=1\nprint(cnt)', tip: 'SNSのフォロー関係で「片思い」を数える集計そのもの。(u,v)と(v,u)を両方数えないのは、片方向なら逆向きが集合に無いので二重計上が起きない、という理屈まで言えると強い。', ins: ['3 3\n1 2\n2 1\n1 3\n', '2 1\n1 2\n', '2 2\n1 2\n2 1\n', '3 2\n1 2\n2 3\n', '4 3\n1 2\n2 1\n3 4\n', '3 4\n1 2\n2 1\n2 3\n3 2\n'] })

t({ lv: 298, concept: 'グラフ: 自己ループの数', title: '自分自身への辺', tags: ['グラフ'], io: '1行目に頂点数 n と辺数 m、続く m 行に辺 u v が与えられます。', ask: '両端が同じ頂点である辺(自己ループ)の本数を出力してください。', h1: 'u==v を数えるだけ。', h2: '読み込みながらカウント。', ref: 'n,m=map(int,input().split())\ncnt=0\nfor _ in range(m):\n    u,v=map(int,input().split())\n    if u==v:\n        cnt+=1\nprint(cnt)', tip: '自己ループは次数に2を足すのか1なのか、隣接行列の対角に何を書くのか、と定義の流儀が分かれる厄介者。単純グラフの判定(同レベル既出の次数列の話)でも最初に除外される。', ins: ['3 3\n1 1\n1 2\n2 2\n', '2 1\n1 2\n', '1 1\n1 1\n', '3 4\n1 1\n1 1\n2 3\n3 3\n', '2 0\n', '4 2\n2 2\n4 4\n'] })

t({ lv: 299, concept: 'bit演算: 2進表記が回文の数の個数', title: 'ビットで読んでも回文', tags: ['bit演算'], io: '正整数 N が1行で与えられます。', ask: '1 以上 N 以下で、2進表記(先頭の1から)が回文になっている数の個数を出力してください。', h1: 'binで文字列にして判定。', h2: 's==s[::-1] を全数に適用。', ref: 'n=int(input())\ncnt=0\nfor x in range(1,n+1):\n    b=bin(x)[2:]\n    if b==b[::-1]:\n        cnt+=1\nprint(cnt)', tip: '十進の回文数(既出)の2進版。基数を変えると回文になる数はまるで別物になり、全ての基数で回文になる数はほとんど無い、という研究テーマまで地続き。', ins: ['10\n', '1\n', '3\n', '20\n', '5\n', '63\n'] })

t({ lv: 300, concept: 'DP: 辞書順最小のLCSの復元', title: '最長のうち一番若い共通列', tags: ['DP', '文字列'], io: '1行目と2行目に英小文字の文字列が与えられます。', ask: '2つの文字列の最長共通部分列(LCS)のうち辞書順最小のものを出力してください(長さ0なら - を出力)。', h1: '長さのDP(既出)を作ってから前から貪欲に文字を選ぶ。', h2: '各ステップで小さい文字から試し、その文字を両方の最も早い位置で使っても残り長が足りるか dp で確かめる。', ref: 's=input()\nt=input()\nm,n=len(s),len(t)\ndp=[[0]*(n+1) for _ in range(m+1)]\nfor i in range(m-1,-1,-1):\n    for j in range(n-1,-1,-1):\n        if s[i]==t[j]:\n            dp[i][j]=dp[i+1][j+1]+1\n        else:\n            dp[i][j]=max(dp[i+1][j],dp[i][j+1])\nL=dp[0][0]\nres=[]\ni=j=0\nfor step in range(L):\n    need=L-step\n    for c in sorted(set(s[i:])&set(t[j:])):\n        p=s.index(c,i)\n        q=t.index(c,j)\n        if dp[p+1][q+1]>=need-1:\n            res.append(c)\n            i=p+1\n            j=q+1\n            break\nprint("".join(res) if res else "-")', tip: '「値のDP+前からの貪欲復元」はDP構成問題の王道パターン。文字を早い位置で使うほど残りの選択肢が広がる(dpが大きくなる)ので、最早出現で試すのが正当化される。', ins: ['abc\nacb\n', 'abcd\nefgh\n', 'ba\nab\n', 'banana\natana\n', 'aa\naa\n', 'abab\nbaba\n'] })

t({ lv: 301, concept: '数論: 過剰度', title: '約数の余り具合を測る', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: 'n の約数の総和から 2n を引いた値(過剰度)を出力してください。', h1: '約数の総和(同レベル既出)から引くだけ。', h2: '完全数なら0、不足数なら負になる。', ref: 'n=int(input())\ns=0\ni=1\nwhile i*i<=n:\n    if n%i==0:\n        s+=i\n        if i!=n//i:\n            s+=n//i\n    i+=1\nprint(s-2*n)', tip: '過剰数・完全数・不足数の3分類を1つの数直線に並べたのが過剰度。過剰度がちょうど+1やー1の数(準完全数・概完全数)は存在が未解決という深い沼が広がっている。', ins: ['12\n', '6\n', '8\n', '1\n', '20\n', '7\n'] })

t({ lv: 302, concept: '数論: 区間内の素数の和', title: '区間の素数を全部足す', tags: ['数論'], io: 'L R が空白区切りで1行で与えられます。', ask: 'L 以上 R 以下の素数の総和を出力してください(無ければ 0)。', h1: '個数(同レベル既出)を和に変える。', h2: '判定関数+sum。', ref: 'l,r=map(int,input().split())\ndef isp(x):\n    if x<2:\n        return False\n    i=2\n    while i*i<=x:\n        if x%i==0:\n            return False\n        i+=1\n    return True\nprint(sum(x for x in range(l,r+1) if isp(x)))', tip: 'プロジェクトオイラーの初期問題にも登場する定番集計。エラトステネスの篩に切り替えると全区間分の判定が一括で済む、という高速化の入り口でもある。', ins: ['1 10\n', '10 20\n', '14 16\n', '2 2\n', '1 100\n', '90 97\n'] })

t({ lv: 303, concept: '数え上げ: 円卓で隣り合わない選び方の数', title: '円卓の席の選び方', tags: ['数え上げ', 'DP'], io: '3以上の整数 n が1行で与えられます。', ask: '円形に並んだ n 席から、隣り合う2席を同時に選ばないように席の部分集合を選ぶ方法の総数(誰も選ばない場合も含む)を出力してください。', h1: '席1を選ぶ場合と選ばない場合に分けると円が直線になる。', h2: '直線 k 席の選び方 f(k)=f(k−1)+f(k−2) (f(0)=1, f(1)=2) を使い、f(n−1)+f(n−3)。', ref: 'n=int(input())\ndef line(k):\n    a,b=1,2\n    if k==0:\n        return 1\n    for _ in range(k-1):\n        a,b=b,a+b\n    return b\nprint(line(n-1)+line(n-3))', tip: '円環の数え上げは「1点の状態で場合分けして直線に開く」のが定石。答えはリュカ数列そのもので、直線版のフィボナッチと円環版のリュカという美しい対応がある。', ins: ['3\n', '4\n', '5\n', '6\n', '8\n', '10\n'] })

t({ lv: 304, concept: '窓: 和が最大の窓の開始位置', title: '一番稼げる区間はどこから', tags: ['窓'], io: '1行目に k、2行目に整数列(長さk以上)が与えられます。', ask: '長さ k の連続区間のうち和が最大のものの開始位置(1始まり、同点なら最小)を出力してください。', h1: '最大和(同レベル既出)のargmax版。', h2: 'ずらしながら「より大きいときだけ」位置を更新。', ref: 'k=int(input())\na=list(map(int,input().split()))\ns=sum(a[:k])\nbest=s\npos=1\nfor i in range(k,len(a)):\n    s+=a[i]-a[i-k]\n    if s>best:\n        best=s\n        pos=i-k+2\nprint(pos)', tip: '移動平均が最高になる期間を特定する、時系列レポートの頻出クエリ。値とargの二重更新では「更新条件の等号の有無」がそのままタイブレーク規則になる。', ins: ['2\n1 3 2 4\n', '1\n5 9 3\n', '3\n1 1 1\n', '2\n4 0 0 4\n', '2\n-1 -2 -3\n', '3\n2 1 3 4 1\n'] })

t({ lv: 305, concept: '累積和: 区間和の絶対値の最小', title: 'ゼロに一番近い区間', tags: ['累積和', 'ソート'], io: '整数列が1行で空白区切りで与えられます。', ask: '連続部分配列(長さ1以上)の和の絶対値の最小値を出力してください。', h1: '区間和は累積和の差。', h2: '0を含む累積和の列をソートし、隣どうしの差の最小を取る。', ref: 'a=list(map(int,input().split()))\nps=[0]\nfor x in a:\n    ps.append(ps[-1]+x)\nps.sort()\nprint(min(ps[i+1]-ps[i] for i in range(len(ps)-1)))', tip: '「差の絶対値の最小はソートすると隣接に現れる」という定理を累積和に適用した合成技。2つの部品(累積和・ソート隣接)がどちらも既習でも、組合せは新しい発想になる。', ins: ['2 -3 2\n', '1 2 3\n', '-5 5\n', '3 -1\n', '10\n', '4 -2 -2\n'] })

t({ lv: 306, concept: '貪欲: すべて作れるようにする最小の追加枚数', title: '足りない額を埋める最少の追加', tags: ['貪欲'], io: '1行目に目標 M、2行目に昇順の正整数列(手持ちの硬貨)が与えられます。', ask: '1 から M までの全ての金額を部分集合の和で作れるようにするために追加する硬貨の最小枚数を出力してください(追加する硬貨の額面は自由)。', h1: '作れる上限 reach を持ち回る。', h2: '次の硬貨が reach+1 以下なら取り込み、超えていたら reach+1 を追加する。', ref: 'M=int(input())\na=list(map(int,input().split()))\nreach=0\ni=0\nadd=0\nwhile reach<M:\n    if i<len(a) and a[i]<=reach+1:\n        reach+=a[i]\n        i+=1\n    else:\n        add+=1\n        reach+=reach+1\nprint(add)', tip: '「作れない最小の正整数」(同レベル既出)の観察を逆手に取り、穴が空いたらその値自体を追加するのが最適という美しい貪欲。追加のたびに到達範囲が倍以上に伸びる。', ins: ['6\n1 3\n', '20\n1 2 5\n', '5\n1 1 1\n', '1\n2\n', '10\n1 2 3\n', '7\n1 5 10\n'] })

t({ lv: 307, concept: '数え上げ: 1を使わない分割数', title: '端数なしの分け方', tags: ['DP'], io: '2以上の整数 n が1行で与えられます。', ask: 'n を「全ての項が2以上」の正整数の和に分ける方法の総数を出力してください(順序は区別しない。n 自身1個も1通り)。', h1: '部品を2以上に制限した分割DP。', h2: '実は p(n)−p(n−1) にも等しい(1を含む分割と p(n−1) が1対1)。', ref: 'n=int(input())\ndp=[0]*(n+1)\ndp[0]=1\nfor part in range(2,n+1):\n    for s in range(part,n+1):\n        dp[s]+=dp[s-part]\nprint(dp[n])', tip: '「1を1つ取り除く」対応で 1入り分割 ↔ p(n−1) の全単射ができ、答えが p(n)−p(n−1) と分かる。DPの答えと差分公式の二重検算が気持ちいい。', ins: ['6\n', '2\n', '4\n', '10\n', '7\n', '15\n'] })

t({ lv: 308, concept: 'DP: グリッドを斜めに下る最大の和', title: '斜め下りの一番の実り', tags: ['DP', 'グリッド'], io: '1行目に H W、続く H 行に整数の格子が与えられます。1行目のどこかから出発し、毎行「真下・左下・右下」のいずれかへ降りて最終行まで進みます。', ask: '通ったマスの合計の最大値を出力してください。', h1: '最小の和(同レベル既出)のmax版。', h2: '行ごとに「上3方向のmax+自分」を計算する。', ref: 'h,w=map(int,input().split())\ng=[list(map(int,input().split())) for _ in range(h)]\ndp=g[0][:]\nfor i in range(1,h):\n    nd=[0]*w\n    for j in range(w):\n        best=dp[j]\n        if j>0 and dp[j-1]>best:\n            best=dp[j-1]\n        if j<w-1 and dp[j+1]>best:\n            best=dp[j+1]\n        nd[j]=g[i][j]+best\n    dp=nd\nprint(max(dp))', tip: '出発列も到着列も自由という「両端フリー」の設定では、初期化を1行目全体、答えを最終行のmaxにする。境界の扱いが仕様のどこに現れるかを読む練習になる。', ins: ['2 2\n1 2\n3 4\n', '2 3\n1 2 3\n4 5 6\n', '1 1\n7\n', '3 3\n1 1 1\n1 9 1\n1 1 1\n', '2 2\n-1 -2\n-3 -4\n', '3 2\n5 1\n1 5\n5 1\n'] })

t({ lv: 309, concept: '区間: 区間が覆う長さの合計', title: '塗られた長さは合計いくつ', tags: ['区間'], io: '1行目に n、続く n 行に区間 l r (l<r) が与えられます。', ask: '数直線上で1つ以上の区間に覆われている部分の長さの合計を出力してください。', h1: 'ソートして重なりをまとめながら長さを足す。', h2: '今のまとまりの右端を超えたら長さを確定して新しいまとまりへ。', ref: 'n=int(input())\niv=sorted(tuple(map(int,input().split())) for _ in range(n))\ntotal=0\ncl,cr=iv[0]\nfor l,r in iv[1:]:\n    if l>cr:\n        total+=cr-cl\n        cl,cr=l,r\n    elif r>cr:\n        cr=r\ntotal+=cr-cl\nprint(total)', tip: '「ちょうど1回だけ覆われた長さ」(既出)の単純版で、ペンキ塗り問題とも呼ばれる。ループを抜けた後の最後のまとまりの加算を忘れるのが定番のバグ。', ins: ['3\n1 3\n2 4\n6 7\n', '2\n1 2\n3 4\n', '2\n1 2\n2 5\n', '1\n0 10\n', '4\n1 10\n2 3\n4 5\n11 12\n', '3\n5 6\n1 2\n3 4\n'] })

t({ lv: 310, concept: 'DP: 山型の最長部分列', title: '登って下る最長の道(飛び石版)', tags: ['DP'], io: '整数列が1行で空白区切りで与えられます。', ask: '部分列(連続でなくてよい)で「厳密に増加してから厳密に減少する」形の最長の長さを出力してください(増加だけ・減少だけでもよい)。', h1: '連続版の山型(既出)を部分列に広げる。', h2: '各位置で「そこで終わる最長増加」と「そこから始まる最長減少」を求め、和−1の最大。', ref: 'a=list(map(int,input().split()))\nn=len(a)\ninc=[1]*n\nfor i in range(n):\n    for j in range(i):\n        if a[j]<a[i] and inc[j]+1>inc[i]:\n            inc[i]=inc[j]+1\ndec=[1]*n\nfor i in range(n-1,-1,-1):\n    for j in range(i+1,n):\n        if a[j]<a[i] and dec[j]+1>dec[i]:\n            dec[i]=dec[j]+1\nprint(max(inc[i]+dec[i]-1 for i in range(n)))', tip: 'LISを前後両方向から求めて頂上で継ぐ、双方向DPの代表例。両側の配列を先に全部作ってから合成する設計は、回文や谷型など多くの形状問題に転用できる。', ins: ['1 11 2 10 4 5 2 1\n', '1 2 3\n', '5\n', '3 2 1\n', '1 2 1 2\n', '2 4 3 5 1\n'] })

t({ lv: 311, concept: 'DP: 最少の単語数で分割', title: 'なるべく少ない単語で言い切る', tags: ['DP', '文字列'], io: '1行目に文字列、2行目に辞書の単語が空白区切りで与えられます。', ask: '文字列を辞書の単語(何度でも使える)の連結に分解するときの最少単語数を出力してください(分解できなければ -1)。', h1: '分割できるか(既出)・方法の数(同レベル既出)の最適化版。', h2: 'dp[i] は先頭i文字の最少数。届かない状態は大きな番兵で。', ref: 's=input()\nws=set(input().split())\nn=len(s)\nINF=10**9\ndp=[INF]*(n+1)\ndp[0]=0\nfor i in range(1,n+1):\n    for j in range(i):\n        if s[j:i] in ws and dp[j]+1<dp[i]:\n            dp[i]=dp[j]+1\nprint(dp[n] if dp[n]<INF else -1)', tip: '判定・数え上げ・最適化の3兄弟が同じ遷移で書ける、word breakはその見本市。トークナイザ(形態素解析)の最少分割コストモデルの原型でもある。', ins: ['abcd\nab cd abcd\n', 'aaa\na aa\n', 'abc\nab bc\n', 'x\nx\n', 'abab\nab a b\n', 'aaaa\naa\n'] })

t({ lv: 312, concept: '文字列: 1文字までの置換で回文にできるか', title: '一箇所直せば回文', tags: ['文字列'], io: '英小文字の文字列が1行で与えられます。', ask: '高々1文字を別の文字に置き換えることで回文にできるなら yes、できなければ no を出力してください(既に回文でもyes)。', h1: '削除版(同レベル既出)と違い長さは変わらない。', h2: '対称な位置のペアで食い違う箇所を数え、1以下ならyes。', ref: 's=input()\nn=len(s)\nbad=sum(1 for i in range(n//2) if s[i]!=s[n-1-i])\nprint("yes" if bad<=1 else "no")', tip: '削除は「ずれ」が伝播するので場合分けが要ったが、置換は位置が固定なのでミスマッチ数を数えるだけ。同じ「1回の編集」でも操作の種類で難度が段違いになる。', ins: ['abca\n', 'abc\n', 'abcd\n', 'aba\n', 'ab\n', 'abcda\n'] })

t({ lv: 313, concept: 'ハッシュ: 記号列と単語列の対応', title: 'パターン通りに並んでいるか', tags: ['ハッシュ', '文字列'], io: '1行目に英小文字のパターン、2行目に単語が空白区切りで与えられます。', ask: 'パターンの各文字と単語が1対1に対応する(同じ文字は常に同じ単語、違う文字は違う単語)なら yes、そうでなければ no を出力してください。', h1: '2つの文字列の同型判定(同レベル既出)の文字対単語版。', h2: '両方向の辞書で対応を確かめる。長さ違いは即no。', ref: 'p=input()\nws=input().split()\nif len(p)!=len(ws):\n    print("no")\nelse:\n    f={}\n    g={}\n    ok=True\n    for c,w in zip(p,ws):\n        if c in f and f[c]!=w:\n            ok=False\n        if w in g and g[w]!=c:\n            ok=False\n        f[c]=w\n        g[w]=c\n    print("yes" if ok else "no")', tip: '単射を片方向の辞書だけで確かめると a→foo, b→foo を見逃す。全単射は「行き」と「帰り」の2つの写像で挟むのが確実、という同型判定の共通原則。', ins: ['abba\ndog cat cat dog\n', 'abba\ndog cat cat fish\n', 'aaa\nx y z\n', 'ab\nfoo foo\n', 'abc\nred blue green\n', 'ab\nx\n'] })

t({ lv: 314, concept: '木: 最深の葉と最浅の葉の差', title: '木の凸凹を測る', tags: ['木'], io: '1行目に頂点数 n (n≥2)、2行目に頂点2〜nの親が与えられます(根は頂点1)。', ask: '最も深い葉の深さから最も浅い葉の深さを引いた値を出力してください(根の深さは0)。', h1: '葉の深さの集合を作る。', h2: 'maxとminの差。', ref: 'n=int(input())\npar=list(map(int,input().split()))\ndepth=[0]*(n+1)\nhaskid=[False]*(n+1)\nfor i in range(2,n+1):\n    p=par[i-2]\n    depth[i]=depth[p]+1\n    haskid[p]=True\nls=[depth[v] for v in range(2,n+1) if not haskid[v]]\nprint(max(ls)-min(ls))', tip: '差が0の木は全ての葉が同じ深さで、B木のような平衡データ構造の不変条件そのもの。凸凹の大きさは探索コストのばらつきの指標になる。', ins: ['5\n1 1 2 2\n', '3\n1 2\n', '2\n1\n', '7\n1 1 2 2 3 3\n', '6\n1 2 3 3 4\n', '8\n1 1 1 2 3 4 7\n'] })

t({ lv: 315, concept: 'グリッド: 外に触れない水域の数', title: '陸に閉じ込められた湖', tags: ['グリッド', 'DFS'], io: '1行目に H W、続く H 行に 0/1 の文字列(1が陸、0が水)が与えられます。', ask: '上下左右でつながる水(0)のまとまりのうち、盤面の外周に一切触れていないもの(湖)の個数を出力してください。', h1: '島の数え方(既出)を水側に適用し、条件を1つ足す。', h2: '成分を塗りながら外周のマスを含んだかを記録する。', ref: 'h,w=map(int,input().split())\ng=[list(input()) for _ in range(h)]\ncnt=0\nfor si in range(h):\n    for sj in range(w):\n        if g[si][sj]=="0":\n            g[si][sj]="1"\n            st=[(si,sj)]\n            inner=True\n            while st:\n                i,j=st.pop()\n                if i==0 or i==h-1 or j==0 or j==w-1:\n                    inner=False\n                for di,dj in ((1,0),(-1,0),(0,1),(0,-1)):\n                    ni,nj=i+di,j+dj\n                    if 0<=ni<h and 0<=nj<w and g[ni][nj]=="0":\n                        g[ni][nj]="1"\n                        st.append((ni,nj))\n            if inner:\n                cnt+=1\nprint(cnt)', tip: '成分ごとの真偽フラグを探索と一緒に運ぶ型。外周から水を先に塗りつぶして「残った水=湖」とする逆転の解法もあり、両方書くと理解が立体になる。', ins: ['3 3\n111\n101\n111\n', '3 3\n111\n100\n111\n', '1 3\n000\n', '5 5\n11111\n10101\n11111\n10001\n11111\n', '3 4\n1111\n1001\n1111\n', '2 2\n00\n00\n'] })

t({ lv: 316, concept: 'BFS: 時間内に広がる範囲のマス数', title: '時間切れまでに染まる範囲', tags: ['BFS', 'グリッド'], io: '1行目に H W t、続く H 行に盤面(S が発生源、. が空き、# が壁)が与えられます。広がりは1分に上下左右1マスです。', ask: 't 分以内に届く(発生源自身も含む)マスの個数を出力してください。', h1: '最も近い発生源までの距離(同レベル既出)を求めてからtで絞る。', h2: '全てのSを距離0でキューに入れる多始点BFS。', ref: 'from collections import deque\nfirst=input().split()\nh,w,t=int(first[0]),int(first[1]),int(first[2])\ng=[input() for _ in range(h)]\ndist=[[-1]*w for _ in range(h)]\nq=deque()\nfor i in range(h):\n    for j in range(w):\n        if g[i][j]=="S":\n            dist[i][j]=0\n            q.append((i,j))\nwhile q:\n    i,j=q.popleft()\n    for di,dj in ((1,0),(-1,0),(0,1),(0,-1)):\n        ni,nj=i+di,j+dj\n        if 0<=ni<h and 0<=nj<w and g[ni][nj]!="#" and dist[ni][nj]<0:\n            dist[ni][nj]=dist[i][j]+1\n            q.append((ni,nj))\nprint(sum(1 for i in range(h) for j in range(w) if 0<=dist[i][j]<=t))', tip: '感染や延焼のシミュレーションはこの形の多始点BFSで、時刻tの等高線が「同時に広がる波」を表す。距離を求めてから閾値で数える2段構えが仕様変更に強い。', ins: ['1 5 2\nS....\n', '3 3 1\nS..\n...\n..S\n', '2 2 0\nS.\n..\n', '3 3 4\nS#.\n.#.\n.#.\n', '2 3 1\nS.S\n...\n', '1 4 9\nS###\n'] })

t({ lv: 317, concept: 'DAG: 最長経路に乗れる頂点の数', title: '最長ルートの通り道', tags: ['グラフ', 'DP'], io: '1行目に頂点数 n と辺数 m、続く m 行に有向辺 u v (閉路なし) が与えられます。', ask: '辺数最長の経路(いずれか)に含まれ得る頂点の個数を出力してください。', h1: '各頂点から先の最長と、各頂点までの最長を両方求める。', h2: '「までの長さ+からの長さ」が全体の最長に等しい頂点が乗れる頂点。', ref: 'import sys\nsys.setrecursionlimit(100000)\nn,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nrg=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    rg[v].append(u)\ndef mk(adj):\n    memo={}\n    def f(v):\n        if v in memo:\n            return memo[v]\n        best=0\n        for w in adj[v]:\n            c=f(w)+1\n            if c>best:\n                best=c\n        memo[v]=best\n        return best\n    return f\ndown=mk(g)\nup=mk(rg)\nL=max(down(v) for v in range(1,n+1))\nprint(sum(1 for v in range(1,n+1) if up(v)+down(v)==L))', tip: 'プロジェクト工程表のクリティカルパス解析そのもの: 前向きと後ろ向きの2回のDPで「余裕のない工程」を特定する。up+downが全長に届かない頂点には遊び(スラック)がある。', ins: ['4 3\n1 2\n2 3\n2 4\n', '3 2\n1 2\n1 3\n', '5 4\n1 2\n2 3\n3 4\n1 5\n', '2 0\n', '6 6\n1 2\n2 3\n1 4\n4 5\n5 6\n2 6\n', '3 3\n1 2\n2 3\n1 3\n'] })

t({ lv: 318, concept: 'グラフ: 中心となる頂点の数', title: '街の中心はいくつある', tags: ['グラフ', 'BFS'], io: '1行目に頂点数 n と辺数 m、続く m 行に辺 u v が与えられます(連結)。', ask: '離心数(最も遠い頂点までの距離)が最小である頂点(中心)の個数を出力してください。', h1: '半径(同レベル既出)を求める過程の副産物。', h2: '全頂点からBFSして離心数を求め、最小値と同じものを数える。', ref: 'from collections import deque\nn,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\necc=[]\nfor s in range(1,n+1):\n    dist=[-1]*(n+1)\n    dist[s]=0\n    q=deque([s])\n    while q:\n        x=q.popleft()\n        for y in g[x]:\n            if dist[y]<0:\n                dist[y]=dist[x]+1\n                q.append(y)\n    ecc.append(max(dist[1:n+1]))\nr=min(ecc)\nprint(sum(1 for e in ecc if e==r))', tip: '木の中心は1個か2個しかないと証明できるが、一般のグラフ(閉路あり)では何個でもあり得る。施設配置(どこに救急署を置くか)の理論はこの離心数最小化から始まる。', ins: ['4 3\n1 2\n2 3\n2 4\n', '2 1\n1 2\n', '5 4\n1 2\n2 3\n3 4\n4 5\n', '3 3\n1 2\n2 3\n1 3\n', '1 0\n', '6 5\n1 2\n2 3\n3 4\n4 5\n5 6\n'] })

t({ lv: 319, concept: 'クエリ: 一点更新つき区間の最大', title: '更新が混ざる区間の最大', tags: ['クエリ'], io: '1行目に n q、2行目に長さ n の列、続く q 行に「U i x」(i番目をxに変更) か「Q l r」(区間の最大を出力) が与えられます。', ask: '各 Q クエリに対して区間 [l, r] の最大値を1行ずつ出力してください。', h1: '区間の積の更新つき(同レベル既出)の最大版。', h2: 'この規模なら素直に書き換えとmaxで正しく動く。', ref: 'n,q=map(int,input().split())\na=list(map(int,input().split()))\nfor _ in range(q):\n    parts=input().split()\n    if parts[0]=="U":\n        a[int(parts[1])-1]=int(parts[2])\n    else:\n        l,r=int(parts[1]),int(parts[2])\n        print(max(a[l-1:r]))', tip: '更新と質問が混ざると累積の前計算が崩れる、という区間クエリ最大の壁を体験する問題。セグメント木はこの素朴解を「正しさの基準」にして検証しながら書くのが定石。', ins: ['3 3\n1 5 2\nQ 1 3\nU 3 9\nQ 2 3\n', '2 2\n4 4\nQ 1 1\nQ 1 2\n', '4 4\n1 2 3 4\nU 1 10\nQ 1 2\nU 4 0\nQ 3 4\n', '1 3\n7\nQ 1 1\nU 1 3\nQ 1 1\n', '5 3\n3 1 4 1 5\nQ 2 4\nU 3 0\nQ 2 4\n', '3 2\n9 9 9\nU 2 1\nQ 1 3\n'] })

t({ lv: 320, concept: 'クエリ: 区間の2番目の最小値', title: '区間の準優勝を答える', tags: ['クエリ'], io: '1行目に n q、2行目に長さ n の列、続く q 行に区間 l r (長さ2以上) が与えられます。', ask: '各区間について小さい方から2番目の値(重複を区別する)を1行ずつ出力してください。', h1: '区間最小クエリ(同レベル既出)の2番目版。', h2: '切り出してソートし[1]を取るのが基準解。', ref: 'n,q=map(int,input().split())\na=list(map(int,input().split()))\nfor _ in range(q):\n    l,r=map(int,input().split())\n    print(sorted(a[l-1:r])[1])', tip: '最小だけならスパーステーブルでO(1)だが、2番目は「各ブロックの最小2つ」を持てば同じ枠組みで解ける。統計量を拡張すると前計算に何を足すべきかを考える良い題材。', ins: ['4 2\n3 1 4 1\n1 4\n2 3\n', '2 1\n5 7\n1 2\n', '5 2\n2 2 2 2 2\n1 5\n2 3\n', '3 1\n9 1 5\n1 3\n', '6 2\n4 6 1 3 9 2\n2 5\n1 6\n', '4 1\n8 3 5 3\n1 4\n'] })

t({ lv: 321, concept: '窓: 各窓の幅(最大と最小の差)の合計', title: '窓ごとの振れ幅を合計する', tags: ['窓'], io: '1行目に k、2行目に整数列(長さk以上)が与えられます。', ask: '長さ k の各窓について最大値と最小値の差を求め、その合計を出力してください。', h1: '最小の合計(同レベル既出)と最大の合計を別々に求めてもよい。', h2: 'この規模なら窓ごとにmaxとminを直接取って足す。', ref: 'k=int(input())\na=list(map(int,input().split()))\nprint(sum(max(a[i:i+k])-min(a[i:i+k]) for i in range(len(a)-k+1)))', tip: '窓内のレンジ(振れ幅)はボラティリティの素朴な推定量。単調デックを2本(max用とmin用)並走させるとO(n)になり、既出の部品の合成で高速化が完成する。', ins: ['2\n1 3 2\n', '3\n1 2 3\n', '1\n4 5\n', '2\n5 5 5\n', '3\n4 1 7 2\n', '2\n10 1 10\n'] })

t({ lv: 322, concept: 'ヒープ: 最小値を2倍にするk回操作後の和', title: '一番弱いところを倍にする', tags: ['ヒープ'], io: '1行目に k、2行目に正整数の列が与えられます。', ask: '「最小の要素を2倍にする」操作を k 回行った後の総和を出力してください。', h1: '最大を半分にする問題(同レベル既出)の鏡像。', h2: 'heappopして2倍してheappush。', ref: 'import heapq\nk=int(input())\na=list(map(int,input().split()))\nheapq.heapify(a)\nfor _ in range(k):\n    x=heapq.heappop(a)\n    heapq.heappush(a,x*2)\nprint(sum(a))', tip: '毎回の対象が操作によって入れ替わるため、ソート1回では済まずヒープが本領を発揮する。最小を持ち上げる操作は「底上げ」戦略の数理モデルになっている。', ins: ['2\n1 2 3\n', '1\n5\n', '3\n1 1 1\n', '2\n4 6\n', '1\n2 3\n', '4\n1 2\n'] })

t({ lv: 323, concept: '数え上げ: 0がk個以下の区間の数', title: 'ゼロを我慢できる区間', tags: ['数え上げ', '二点法'], io: '1行目に k、2行目に0と1の列が与えられます。', ask: '含まれる0の個数が k 個以下である連続部分配列の個数を出力してください。', h1: 'k回反転で作る最長(同レベル既出)の数え上げ版。', h2: '右端ごとに条件を満たす最左を二点法で保ち、窓の長さを足す。', ref: 'k=int(input())\na=list(map(int,input().split()))\nl=0\nzeros=0\ncnt=0\nfor r,x in enumerate(a):\n    if x==0:\n        zeros+=1\n    while zeros>k:\n        if a[l]==0:\n            zeros-=1\n        l+=1\n    cnt+=r-l+1\nprint(cnt)', tip: '「r を右端とする有効な区間は l..r の r−l+1 個」という数え方が二点法カウントの核。最長を求める問題と同じ窓の動きから、maxを取るか足すかだけが違う。', ins: ['1\n0 1 0\n', '0\n1 1\n', '2\n0 0\n', '1\n1 1 1\n', '1\n0 0 1\n', '2\n0 1 0 1\n'] })

t({ lv: 324, concept: 'DP: 部分集合の和で目標に最も近い値', title: '選んで作る一番近い合計', tags: ['DP'], io: '1行目に目標 T、2行目に正整数の列が与えられます。', ask: '部分集合(空でもよい)の和のうち T に最も近い値を出力してください(同じ近さなら小さい方)。', h1: '作れる和の集合(既出)を作ってから選ぶ。', h2: 'min(集合, key=(Tとの差, 値))。', ref: 'T=int(input())\na=list(map(int,input().split()))\ns={0}\nfor x in a:\n    s|={y+x for y in s}\nprint(min(s,key=lambda v:(abs(v-T),v)))', tip: '「判定できるなら最適化もできる」の実演で、到達可能集合さえあれば絞り込みはワンライナー。keyをタプルにして同着処理まで宣言的に書けるのがPythonのminの強み。', ins: ['10\n3 4 6\n', '5\n2 8\n', '1\n5 5\n', '7\n1 2 3\n', '100\n1\n', '6\n4 4\n'] })

t({ lv: 325, concept: '文字列: 括弧つき繰り返しの展開', title: '圧縮された文字列を開封する', tags: ['文字列', 'スタック'], io: '数字[文字列] の形の繰り返し記法(入れ子あり)を含む文字列が1行で与えられます。', ask: '記法を展開した文字列を出力してください(例: 3[ab] は ababab、2[a3[b]] は abbbabbb)。', h1: '展開後の長さだけ求める問題(既出)の実体版。', h2: '[ で(それまでの文字列, 回数)をスタックに退避し、] で復元して連結する。', ref: 's=input()\nst=[]\ncur=""\nnum=0\nfor c in s:\n    if c.isdigit():\n        num=num*10+int(c)\n    elif c=="[":\n        st.append((cur,num))\n        cur=""\n        num=0\n    elif c=="]":\n        prev,k=st.pop()\n        cur=prev+cur*k\n    else:\n        cur+=c\nprint(cur)', tip: '入れ子の構造は再帰かスタックの二択で、これはスタック版の教科書例。複数桁の回数(10[a]など)を桁ごとに組み立てる処理を忘れると9回までしか動かない。', ins: ['3[ab]\n', '2[a3[b]]\n', 'abc\n', '2[x]y\n', '10[a]\n', 'a2[bc]d\n'] })

t({ lv: 326, concept: 'グラフ: 全ての頂点と隣接する頂点の数', title: 'みんなと友達の人', tags: ['グラフ', '行列'], io: '1行目に n、続く n 行に n×n の隣接行列(0/1、対角は0)が与えられます。', ask: '自分以外の全ての頂点と隣接している頂点の個数を出力してください。', h1: '行の和が n−1 の行を数える。', h2: 'sum(row)==n−1。', ref: 'n=int(input())\ncnt=0\nfor _ in range(n):\n    row=list(map(int,input().split()))\n    if sum(row)==n-1:\n        cnt+=1\nprint(cnt)', tip: '全員と隣接する頂点はユニバーサル頂点と呼ばれ、SNSでは全員と繋がるハブ。行の和=次数という隣接行列の基本性質だけで判定でき、行列を保存せず行ごとに処理できる。', ins: ['3\n0 1 1\n1 0 1\n1 1 0\n', '3\n0 1 0\n1 0 1\n0 1 0\n', '2\n0 1\n1 0\n', '1\n0\n', '4\n0 1 1 1\n1 0 0 1\n1 0 0 1\n1 1 1 0\n', '3\n0 0 0\n0 0 0\n0 0 0\n'] })

t({ lv: 327, concept: '組合せ: 二項係数の末尾の0の個数', title: '組合せの数の末尾のゼロ', tags: ['組合せ'], io: 'n k が空白区切りで1行で与えられます (0≤k≤n)。', ask: 'C(n, k) の十進表記の末尾に並ぶ 0 の個数を出力してください。', h1: '階乗の末尾の0(同レベル既出)の二項係数版。', h2: 'combで厳密に計算し、文字列の末尾の0を数えるのが確実。', ref: 'from math import comb\nn,k=map(int,input().split())\ns=str(comb(n,k))\nprint(len(s)-len(s.rstrip("0")))', tip: 'クンマーの定理によれば、この値は「10進…ではなく素数ごとの繰り上がり回数のmin(2と5)」で決まる。厳密計算との突き合わせで定理を「実験」できるのが楽しい。', ins: ['25 12\n', '5 2\n', '10 5\n', '100 50\n', '16 8\n', '40 20\n'] })

t({ lv: 328, concept: '文字列: 数字のモールス符号', title: 'トンツーで数を送る', tags: ['文字列'], io: '数字だけの文字列が1行で与えられます。', ask: '各数字をモールス符号(0:-----, 1:.----, 2:..---, 3:...--, 4:....-, 5:....., 6:-...., 7:--..., 8:---.., 9:----.)に変換し、空白区切りで出力してください。', h1: '対応表を辞書かリストで持つ。', h2: '数字dの符号は「点d個+線(5−d)個」(d≤5)の規則性がある。', ref: 'code=["-----",".----","..---","...--","....-",".....","-....","--...","---..","----."]\ns=input()\nprint(" ".join(code[int(c)] for c in s))', tip: '数字のモールスは点と線の本数が規則的に切り替わる美しい設計で、表を持たず式で生成することもできる。変換表のデータ化はエンコーダ実装の第一歩。', ins: ['12\n', '0\n', '505\n', '999\n', '2026\n', '7\n'] })

export const CATALOG = TASKS
