// 生成タスク 第47波：各レベル2問化フェーズ(2)。lv73〜139 に2問目を追加。
// 上位問題(行列/データ処理/数論アルゴリズム)の「要素」をピュアPythonで配置。
// 重複なし・決定的・採点一意。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 73, concept: '配列: 最大絶対値成分', title: 'ベクトルの最大絶対値(L∞ノルム)', tags: ['配列'], io: 'ベクトル(整数列)が1行で与えられます。', ask: '成分の絶対値の最大値(L∞ノルム)を出力してください。', h1: '各成分の絶対値を取る。', h2: 'その最大。', ref: 'a=list(map(int,input().split()))\nprint(max(abs(x) for x in a))', tip: 'L∞ノルムは成分の絶対値の最大。max(abs(x) for x in a)。L1/L2と並ぶ基本ノルム。', ins: ['3 -4\n', '1 0\n', '-1 -1 -1\n', '5\n', '-7 2\n', '2 2 2\n'] })

t({ lv: 74, concept: '配列: 行列の転置', title: '行列を転置する', tags: ['配列'], io: '1行目に R C、続く R 行に C 個の整数が与えられます。', ask: '転置した行列(C行R列)を各行空白区切りで出力してください。', h1: 'zip(*行) で列を行にする。', h2: '各列を1行として出力。', ref: 'first=input().split()\nR=int(first[0])\nC=int(first[1])\ng=[list(map(int,input().split())) for _ in range(R)]\nfor col in zip(*g):\n    print(*col)', tip: '行列の転置は zip(*g) で列を取り出すのが定石。numpy なら g.T。', ins: ['2 3\n1 2 3\n4 5 6\n', '1 1\n5\n', '2 2\n1 2\n3 4\n', '3 1\n1\n2\n3\n', '2 2\n1 0\n0 1\n', '1 3\n7 8 9\n'] })

t({ lv: 75, concept: '配列: 行ごとの和', title: '行列の各行の和', tags: ['配列'], io: '1行目に R C、続く R 行に C 個の整数が与えられます。', ask: '各行の要素の和を空白区切りで出力してください。', h1: '各行に sum を適用。', h2: '結果を並べる。', ref: 'first=input().split()\nR=int(first[0])\nC=int(first[1])\ng=[list(map(int,input().split())) for _ in range(R)]\nprint(*[sum(row) for row in g])', tip: '行和は各行に sum。numpy なら g.sum(axis=1) に相当する。', ins: ['2 3\n1 2 3\n4 5 6\n', '1 1\n5\n', '2 2\n1 2\n3 4\n', '3 2\n0 0\n1 1\n2 2\n', '1 4\n1 2 3 4\n', '2 2\n-1 1\n-2 2\n'] })

t({ lv: 76, concept: '配列: 列ごとの和', title: '行列の各列の和', tags: ['配列'], io: '1行目に R C、続く R 行に C 個の整数が与えられます。', ask: '各列の要素の和を空白区切りで出力してください。', h1: 'zip(*行) で列を取る。', h2: '各列に sum。', ref: 'first=input().split()\nR=int(first[0])\nC=int(first[1])\ng=[list(map(int,input().split())) for _ in range(R)]\nprint(*[sum(col) for col in zip(*g)])', tip: '列和は zip(*g) で列を作って sum。numpy なら g.sum(axis=0)。', ins: ['2 3\n1 2 3\n4 5 6\n', '1 1\n5\n', '2 2\n1 2\n3 4\n', '3 2\n0 0\n1 1\n2 2\n', '1 4\n1 2 3 4\n', '2 2\n-1 1\n-2 2\n'] })

t({ lv: 77, concept: '配列: 行列とベクトルの積', title: '行列×ベクトル', tags: ['配列'], io: '1行目に R C、続く R 行に行列、最後の行に長さ C のベクトルが与えられます。', ask: '行列とベクトルの積(長さ R)を空白区切りで出力してください。', h1: '各行とベクトルの内積。', h2: 'zip で積和。', ref: 'first=input().split()\nR=int(first[0])\nC=int(first[1])\ng=[list(map(int,input().split())) for _ in range(R)]\nv=list(map(int,input().split()))\nprint(*[sum(g[i][j]*v[j] for j in range(C)) for i in range(R)])', tip: '行列ベクトル積は各行とベクトルの内積を並べたもの。線形変換・順伝播の基本。', ins: ['2 3\n1 2 3\n4 5 6\n1 0 1\n', '1 1\n5\n2\n', '2 2\n1 0\n0 1\n3 4\n', '2 2\n1 1\n1 1\n1 1\n', '1 3\n1 2 3\n1 1 1\n', '3 1\n2\n3\n4\n5\n'] })

t({ lv: 78, concept: '配列: 行列の対角和', title: '正方行列の対角成分の和(トレース)', tags: ['配列'], io: '1行目に n、続く n 行に n 個の整数が与えられます。', ask: '主対角成分(i行i列)の和(トレース)を出力してください。', h1: 'g[i][i] を足す。', h2: '対角のみ走査。', ref: 'n=int(input())\ng=[list(map(int,input().split())) for _ in range(n)]\nprint(sum(g[i][i] for i in range(n)))', tip: 'トレースは主対角成分の和 Σg[i][i]。行列の固有値の和に等しい不変量。', ins: ['2\n1 2\n3 4\n', '1\n5\n', '3\n1 0 0\n0 2 0\n0 0 3\n', '2\n0 1\n1 0\n', '3\n1 1 1\n1 1 1\n1 1 1\n', '2\n-1 2\n3 -4\n'] })

t({ lv: 79, concept: '配列: しきい値超えの個数(行列)', title: '行列でしきい値を超える要素数', tags: ['配列'], io: '1行目に R C t、続く R 行に行列が与えられます。', ask: '値が t より大きい要素の個数を出力してください。', h1: '全要素を走査する。', h2: 't より大きいものを数える。', ref: 'first=input().split()\nR=int(first[0])\nC=int(first[1])\nth=int(first[2])\ng=[list(map(int,input().split())) for _ in range(R)]\nprint(sum(1 for row in g for x in row if x>th))', tip: '二重ループの内包表記 (x for row in g for x in row) で行列を平坦に走査できる。', ins: ['2 2 3\n1 4\n5 2\n', '1 1 0\n5\n', '2 3 0\n-1 -2 -3\n1 2 3\n', '2 2 10\n1 2\n3 4\n', '1 4 2\n1 2 3 4\n', '2 2 0\n0 0\n0 0\n'] })

t({ lv: 81, concept: '統計: 中点値', title: '最大と最小の中点(小数2桁)', tags: ['統計'], io: '整数列が1行で与えられます。', ask: '最大値と最小値の中点 (max+min)/2 を小数第2位まで出力してください。', h1: 'max と min を求める。', h2: '(max+min)/2 を整形。', ref: 'a=list(map(int,input().split()))\nprint(f"{(max(a)+min(a))/2:.2f}")', tip: '中点値(midrange)は (max+min)/2。外れ値に敏感だが計算が軽い代表値。', ins: ['1 2 3 4\n', '5\n', '1 2\n', '10 20 30\n', '1 1 1\n', '0 5\n'] })

t({ lv: 82, concept: '統計: 最頻値の出現回数', title: '最も多い値の出現回数', tags: ['統計', 'ハッシュ'], io: '整数列が1行で与えられます。', ask: '最も多く現れる値の出現回数を出力してください。', h1: '出現回数を数える。', h2: 'その最大を取る。', ref: 'from collections import Counter\na=list(map(int,input().split()))\nprint(max(Counter(a).values()))', tip: '最頻値の回数は Counter の値の最大。データの偏りや最頻カテゴリの規模を測る。', ins: ['1 2 2 3 3 3\n', '5\n', '1 1 1\n', '1 2 3\n', '4 4 5 5\n', '7 8 8 8 9\n'] })

t({ lv: 83, concept: '統計: 最頻値', title: 'リストの最頻値', tags: ['統計', 'ハッシュ'], io: '整数列が1行で与えられます。', ask: '最も多く現れる値を出力してください。複数あれば最小の値。', h1: '出現回数を数える。', h2: '(回数降順, 値昇順)で選ぶ。', ref: 'from collections import Counter\na=list(map(int,input().split()))\ncnt=Counter(a)\nbest=None\nbestc=-1\nfor v in sorted(cnt):\n    if cnt[v]>bestc:\n        bestc=cnt[v]\n        best=v\nprint(best)', tip: '最頻値(モード)の同点は最小値で割る。sorted してから最大回数を探すと安定する。', ins: ['1 2 2 3\n', '5\n', '1 1 2 2\n', '3 3 3\n', '4 4 5 5 5\n', '1 2 3\n'] })

t({ lv: 84, concept: '統計: 2番目に小さい値', title: '2番目に小さい要素', tags: ['統計', 'ソート'], io: '相異なる整数の列が1行で与えられます(2個以上)。', ask: '2番目に小さい値を出力してください。', h1: '昇順にソートする。', h2: '添字1を取る。', ref: 'a=sorted(map(int,input().split()))\nprint(a[1])', tip: '昇順ソート後の添字1が2番目に小さい値。最大版(降順の添字1)と対称。', ins: ['3 1 4 5\n', '10 20\n', '5 3 8 1\n', '100 50 75\n', '-1 -2 -3\n', '7 9 2 6\n'] })

t({ lv: 86, concept: '配列: マンハッタン距離', title: '2点のマンハッタン距離', tags: ['配列', '幾何'], io: '1行目に点A(x y)、2行目に点B(x y)が与えられます。', ask: 'マンハッタン距離 |x1-x2|+|y1-y2| を出力してください。', h1: '各座標の差の絶対値。', h2: 'それらの和。', ref: 'ax,ay=map(int,input().split())\nbx,by=map(int,input().split())\nprint(abs(ax-bx)+abs(ay-by))', tip: 'マンハッタン距離は各軸の差の絶対値の和。L1距離とも呼ばれ格子上の移動距離に対応する。', ins: ['0 0\n3 4\n', '1 1\n1 1\n', '-1 -1\n1 1\n', '5 0\n0 5\n', '2 3\n2 7\n', '0 0\n0 0\n'] })

t({ lv: 87, concept: '配列: ユークリッド距離の2乗', title: '2点のユークリッド距離の2乗', tags: ['配列', '幾何'], io: '1行目に点A(x y)、2行目に点B(x y)が与えられます。', ask: 'ユークリッド距離の2乗 (x1-x2)²+(y1-y2)² を出力してください。', h1: '各座標の差を2乗。', h2: 'その和(平方根は取らない)。', ref: 'ax,ay=map(int,input().split())\nbx,by=map(int,input().split())\nprint((ax-bx)**2+(ay-by)**2)', tip: '距離は2乗のまま扱うと整数演算で誤差なし。大小比較や最近傍探索では平方根不要。', ins: ['0 0\n3 4\n', '1 1\n1 1\n', '-1 -1\n1 1\n', '5 0\n0 5\n', '2 3\n2 7\n', '0 0\n0 0\n'] })

t({ lv: 88, concept: '配列: 累積積', title: '累積積の列', tags: ['配列'], io: '整数列が1行で与えられます。', ask: '先頭からの累積積の列を空白区切りで出力してください。', h1: '走りながら掛けていく。', h2: '途中結果を記録。', ref: 'a=list(map(int,input().split()))\np=1\nres=[]\nfor x in a:\n    p*=x\n    res.append(p)\nprint(*res)', tip: '累積積は走査しながら掛け、各段階を記録する。itertools.accumulate(a, mul) でも作れる。', ins: ['1 2 3 4\n', '5\n', '2 2 2\n', '1 0 5\n', '-1 -2 -3\n', '10 1 1\n'] })

t({ lv: 89, concept: '配列: 増加する隣接ペアの数', title: '隣り合って増加するペアの数', tags: ['配列'], io: '整数列が1行で与えられます。', ask: 'a[i]<a[i+1] となる隣接ペアの個数を出力してください。', h1: '隣接要素を比べる。', h2: '前<後 を数える。', ref: 'a=list(map(int,input().split()))\nprint(sum(1 for i in range(len(a)-1) if a[i]<a[i+1]))', tip: '隣接の増加回数は連続性の指標。zip(a, a[1:]) でペアを作って数えてもよい。', ins: ['1 2 1 3\n', '1 2 3\n', '3 2 1\n', '5\n', '1 1 1\n', '2 1 2 1 2\n'] })

t({ lv: 91, concept: 'ハッシュ: キー別の合計', title: 'キーごとの値の合計', tags: ['ハッシュ'], io: '1行目に件数 n、続く n 行に "key value"(key は文字列)が与えられます。', ask: 'キーごとに値を合計し、キーの辞書順に "key sum" を各行出力してください。', h1: '辞書で合計を貯める。', h2: 'キーをソートして出力。', ref: 'from collections import defaultdict\nn=int(input())\nd=defaultdict(int)\nfor _ in range(n):\n    k,v=input().split()\n    d[k]+=int(v)\nfor k in sorted(d):\n    print(k,d[k])', tip: 'キー別集計は defaultdict(int) で加算。pandas の groupby().sum() に相当する基本操作。', ins: ['3\na 1\nb 2\na 3\n', '1\nx 5\n', '2\nk 1\nk 2\n', '3\nc 1\nb 1\na 1\n', '2\np 10\nq 20\n', '4\na 1\na 1\nb 1\nb 1\n'] })

t({ lv: 92, concept: 'ハッシュ: 値の出現回数表', title: '各値の出現回数(昇順)', tags: ['ハッシュ'], io: '整数列が1行で与えられます。', ask: '相異なる値を昇順に、各値について "値 回数" を各行出力してください。', h1: 'Counter で数える。', h2: 'キーをソートして出力。', ref: 'from collections import Counter\na=list(map(int,input().split()))\ncnt=Counter(a)\nfor v in sorted(cnt):\n    print(v,cnt[v])', tip: '頻度表は Counter＋sorted。pandas の value_counts() に相当する集計。', ins: ['1 2 2 3 3 3\n', '5\n', '1 1 1\n', '3 1 2\n', '7 7 8\n', '0 0 0 1\n'] })

t({ lv: 93, concept: 'ハッシュ: 和が目標の2数の存在', title: '和が目標になる2数があるか', tags: ['ハッシュ'], io: '1行目に目標 target、2行目に整数列が与えられます。', ask: '異なる2要素の和が target になる組があれば yes、なければ no を出力してください。', h1: '既出の値を集合に貯める。', h2: 'target-x が既出か見る。', ref: 'target=int(input())\na=list(map(int,input().split()))\nseen=set()\nfound=False\nfor x in a:\n    if target-x in seen:\n        found=True\n        break\n    seen.add(x)\nprint("yes" if found else "no")', tip: 'Two Sum は「target-x が既出か」を集合で確認する1パス O(n)。ハッシュの典型応用。', ins: ['9\n2 7 11 15\n', '6\n3 3\n', '5\n1 2\n', '10\n5\n', '0\n-1 1\n', '8\n1 2 3\n'] })

t({ lv: 94, concept: 'DP: 最小連続部分和', title: '最小の連続部分和', tags: ['dp'], io: '整数列が1行で与えられます。', ask: '空でない連続部分配列の和の最小値を出力してください。', h1: 'Kadane の最小版。', h2: 'cur=min(x, cur+x)。', ref: 'a=list(map(int,input().split()))\ncur=a[0]\nbest=a[0]\nfor x in a[1:]:\n    cur=min(x,cur+x)\n    if cur<best:\n        best=cur\nprint(best)', tip: '最小部分和は Kadane の max を min に変えるだけ。最大部分和と対称な線形DP。', ins: ['1 -2 3 -4\n', '1 2 3\n', '-1 -2 -3\n', '5\n', '-5\n', '3 -2 -2 5\n'] })

t({ lv: 96, concept: '配列: 前方累積最大', title: '前からの累積最大の列', tags: ['配列'], io: '整数列が1行で与えられます。', ask: '各位置までの最大値(前方累積最大)の列を空白区切りで出力してください。', h1: 'これまでの最大を保持。', h2: '各位置で更新して記録。', ref: 'a=list(map(int,input().split()))\nm=a[0]\nres=[]\nfor x in a:\n    m=max(m,x)\n    res.append(m)\nprint(*res)', tip: '累積最大(running max)は単調非減少列になる。株価の「これまでの高値」などに使う。', ins: ['1 3 2 5 4\n', '5\n', '5 4 3\n', '1 2 3\n', '-1 -2 0\n', '3 3 3\n'] })

t({ lv: 97, concept: '配列: 前方累積最小', title: '前からの累積最小の列', tags: ['配列'], io: '整数列が1行で与えられます。', ask: '各位置までの最小値(前方累積最小)の列を空白区切りで出力してください。', h1: 'これまでの最小を保持。', h2: '各位置で更新して記録。', ref: 'a=list(map(int,input().split()))\nm=a[0]\nres=[]\nfor x in a:\n    m=min(m,x)\n    res.append(m)\nprint(*res)', tip: '累積最小は単調非増加列。株の「これまでの安値」や利益計算の前処理に使う。', ins: ['5 3 4 1 2\n', '5\n', '3 4 5\n', '3 2 1\n', '-1 0 -2\n', '7 7 7\n'] })

t({ lv: 98, concept: 'ハッシュ: カテゴリ数', title: '相異なるカテゴリの数', tags: ['ハッシュ'], io: '1行目に件数 n、続く n 行にカテゴリ名(文字列)が与えられます。', ask: '相異なるカテゴリの種類数を出力してください。', h1: '集合に入れる。', h2: '要素数を取る。', ref: 'n=int(input())\ncats=set()\nfor _ in range(n):\n    cats.add(input())\nprint(len(cats))', tip: 'カテゴリ数は集合の要素数。one-hot エンコードの列数や nunique() に相当する。', ins: ['3\ncat\ndog\ncat\n', '1\nx\n', '2\na\nb\n', '4\nz\nz\nz\nz\n', '3\nred\ngreen\nblue\n', '2\nsame\nsame\n'] })

t({ lv: 99, concept: '配列: 欠けている整数の数', title: '1からmaxまでで欠けている数', tags: ['配列', '集合'], io: '正整数の列が1行で与えられます。', ask: '1から「列の最大値」までの整数のうち、列に現れないものの個数を出力してください。', h1: '集合にする。', h2: '1..max で未出現を数える。', ref: 'a=list(map(int,input().split()))\ns=set(a)\nmx=max(a)\nprint(sum(1 for x in range(1,mx+1) if x not in s))', tip: '欠番の数は「範囲の大きさ - 出現した種類数」。集合の in 判定で高速に数える。', ins: ['1 2 4 5\n', '1 2 3\n', '5\n', '2 2 2\n', '1 3 5\n', '3 1 2\n'] })

t({ lv: 101, concept: '配列: 行列の90度回転', title: '行列を時計回りに90度回転', tags: ['配列'], io: '1行目に n、続く n 行に n 個の整数が与えられます。', ask: '時計回りに90度回転した行列を各行空白区切りで出力してください。', h1: '転置してから各行を反転。', h2: 'zip(*g) の各列を逆順に。', ref: 'n=int(input())\ng=[list(map(int,input().split())) for _ in range(n)]\nfor row in zip(*g[::-1]):\n    print(*row)', tip: '時計回り90度回転は「行を反転して転置」= zip(*g[::-1])。画像処理の基本変換。', ins: ['2\n1 2\n3 4\n', '1\n5\n', '3\n1 2 3\n4 5 6\n7 8 9\n', '2\n1 0\n0 1\n', '3\n1 1 1\n2 2 2\n3 3 3\n', '2\n-1 2\n3 -4\n'] })

t({ lv: 102, concept: '配列: 行列の螺旋順', title: '行列を螺旋順に並べる', tags: ['配列'], io: '1行目に R C、続く R 行に行列が与えられます。', ask: '左上から時計回りの螺旋順に要素を空白区切りで出力してください。', h1: '上行→右列→下行→左列を剥がす。', h2: '境界を縮めながら繰り返す。', ref: 'first=input().split()\nR=int(first[0])\nC=int(first[1])\ng=[list(map(int,input().split())) for _ in range(R)]\nres=[]\ntop,bot,left,right=0,R-1,0,C-1\nwhile top<=bot and left<=right:\n    for j in range(left,right+1):\n        res.append(g[top][j])\n    top+=1\n    for i in range(top,bot+1):\n        res.append(g[i][right])\n    right-=1\n    if top<=bot:\n        for j in range(right,left-1,-1):\n            res.append(g[bot][j])\n        bot-=1\n    if left<=right:\n        for i in range(bot,top-1,-1):\n            res.append(g[i][left])\n        left+=1\nprint(*res)', tip: '螺旋順は4辺を順に剥がして境界を縮める。境界が交差したら停止する典型的なシミュレーション。', ins: ['3 3\n1 2 3\n4 5 6\n7 8 9\n', '1 1\n5\n', '2 2\n1 2\n3 4\n', '1 4\n1 2 3 4\n', '4 1\n1\n2\n3\n4\n', '2 3\n1 2 3\n4 5 6\n'] })

t({ lv: 103, concept: '配列: 主対角成分', title: '行列の主対角成分', tags: ['配列'], io: '1行目に n、続く n 行に n 個の整数が与えられます。', ask: '主対角成分(g[0][0],g[1][1],...)を空白区切りで出力してください。', h1: 'g[i][i] を並べる。', h2: '内包表記で。', ref: 'n=int(input())\ng=[list(map(int,input().split())) for _ in range(n)]\nprint(*[g[i][i] for i in range(n)])', tip: '主対角成分は g[i][i]。反対角は g[i][n-1-i]。行列の構造を取り出す基本。', ins: ['2\n1 2\n3 4\n', '1\n5\n', '3\n1 2 3\n4 5 6\n7 8 9\n', '2\n0 1\n1 0\n', '3\n9 0 0\n0 8 0\n0 0 7\n', '2\n-1 2\n3 -4\n'] })

t({ lv: 104, concept: '配列: 行列の最大要素', title: '行列の最大の要素', tags: ['配列'], io: '1行目に R C、続く R 行に行列が与えられます。', ask: '行列全体の最大要素を出力してください。', h1: '各行の最大を取る。', h2: 'その最大。', ref: 'first=input().split()\nR=int(first[0])\nC=int(first[1])\ng=[list(map(int,input().split())) for _ in range(R)]\nprint(max(max(row) for row in g))', tip: '行列の最大は max(max(row) for row in g)。平坦化 max(x for row in g for x in row) でも同じ。', ins: ['2 2\n1 2\n3 4\n', '1 1\n5\n', '2 3\n-1 -2 -3\n-4 -5 -6\n', '2 2\n9 1\n1 1\n', '1 4\n1 2 3 4\n', '3 1\n7\n8\n9\n'] })

t({ lv: 106, concept: 'マージ: 2つのソート列の併合', title: '2つのソート済み列をマージ', tags: ['二ポインタ'], io: '1行目にソート済み列A、2行目にソート済み列Bが与えられます(空行可)。', ask: '全体を昇順に並べた列を空白区切りで出力してください。', h1: '2つのポインタで小さい方を取る。', h2: '片方が尽きたら残りを追加。', ref: 'la=input()\na=list(map(int,la.split())) if la.strip() else []\nlb=input()\nb=list(map(int,lb.split())) if lb.strip() else []\ni=j=0\nres=[]\nwhile i<len(a) and j<len(b):\n    if a[i]<=b[j]:\n        res.append(a[i])\n        i+=1\n    else:\n        res.append(b[j])\n        j+=1\nres+=a[i:]\nres+=b[j:]\nprint(*res)', tip: '2列マージは二ポインタで先頭の小さい方を取る O(n+m)。マージソートの核心部分。', ins: ['1 3 5\n2 4 6\n', '1 2\n3 4\n', '1 2 3\n\n', '\n5\n', '1 1 1\n1 1\n', '5\n1 2 3\n'] })

t({ lv: 107, concept: '集合: 共通要素の合計', title: '2列に共通する値の合計', tags: ['集合'], io: '1行目に列A、2行目に列Bが与えられます。', ask: '両方に現れる相異なる値の合計を出力してください(無ければ0)。', h1: '集合の積を取る。', h2: 'その合計。', ref: 'a=set(map(int,input().split()))\nb=set(map(int,input().split()))\nprint(sum(a&b))', tip: '共通要素の合計は sum(a&b)。空集合の sum は0を返すので例外処理不要。', ins: ['1 2 3\n2 3 4\n', '1 2\n3 4\n', '5 5\n5\n', '1 2 3\n1 2 3\n', '1\n2\n', '4 5 6\n5 6 7\n'] })

t({ lv: 108, concept: '集合: 和集合(昇順)', title: '2つの集合の和集合', tags: ['集合'], io: '1行目に列A、2行目に列Bが与えられます。', ask: 'いずれかに現れる値を昇順・重複なしで空白区切り出力してください。', h1: '集合の | を取る。', h2: 'ソートして出力。', ref: 'a=set(map(int,input().split()))\nb=set(map(int,input().split()))\nprint(*sorted(a|b))', tip: '和集合は a|b。集合は重複を自動で除くので、ソートすれば昇順ユニーク列になる。', ins: ['1 2 3\n2 3 4\n', '1 2\n3 4\n', '5 5\n5\n', '1\n1\n', '1 2 3\n1 2 3\n', '7\n8 9\n'] })

t({ lv: 109, concept: '集合: 差集合(昇順)', title: 'AにありBにない要素', tags: ['集合'], io: '1行目に列A、2行目に列Bが与えられます。', ask: 'A に現れて B に現れない値を昇順・重複なしで空白区切り出力してください(無ければ空行)。', h1: '集合の - を取る。', h2: 'ソートして出力。', ref: 'a=set(map(int,input().split()))\nb=set(map(int,input().split()))\nprint(*sorted(a-b))', tip: '差集合 a-b は「A にあって B にない」要素。フィルタリングや除外処理に使う。', ins: ['1 2 3\n2 3 4\n', '1 2\n3 4\n', '5 5\n5\n', '1 2 3\n1 2 3\n', '1 2 3\n\n', '4 5\n4 5\n'] })

t({ lv: 111, concept: '集合: 共通要素の数', title: '2列に共通する値の種類数', tags: ['集合'], io: '1行目に列A、2行目に列Bが与えられます。', ask: '両方に現れる相異なる値の種類数を出力してください。', h1: '集合の積を取る。', h2: '要素数を数える。', ref: 'a=set(map(int,input().split()))\nb=set(map(int,input().split()))\nprint(len(a&b))', tip: '共通要素数は len(a&b)。Jaccard係数など類似度計算の分子になる。', ins: ['1 2 3\n2 3 4\n', '1 2\n3 4\n', '5 5\n5\n', '1 2 3\n1 2 3\n', '1\n2\n', '4 5 6\n5 6 7\n'] })

t({ lv: 112, concept: '集合: 対称差の数', title: '片方だけに現れる値の数', tags: ['集合'], io: '1行目に列A、2行目に列Bが与えられます。', ask: 'どちらか一方にだけ現れる相異なる値の種類数(対称差)を出力してください。', h1: '集合の ^ を取る。', h2: '要素数を数える。', ref: 'a=set(map(int,input().split()))\nb=set(map(int,input().split()))\nprint(len(a^b))', tip: '対称差 a^b は「片方だけ」の要素。|a|+|b|-2|a∩b| にも等しい。', ins: ['1 2 3\n2 3 4\n', '1 2\n3 4\n', '5 5\n5\n', '1 2 3\n1 2 3\n', '1\n2\n', '4 5 6\n5 6 7\n'] })

t({ lv: 113, concept: 'ハッシュ: 多重集合の共通要素数', title: '重複を考慮した共通要素数', tags: ['ハッシュ'], io: '1行目に列A、2行目に列Bが与えられます。', ask: '各値について min(Aでの個数, Bでの個数) を合計した値(多重集合の積の大きさ)を出力してください。', h1: '各列の出現回数を数える。', h2: '共通キーで min を足す。', ref: 'from collections import Counter\na=Counter(map(int,input().split()))\nb=Counter(map(int,input().split()))\nprint(sum(min(a[k],b[k]) for k in a if k in b))', tip: '多重集合の積は各要素で min(個数A, 個数B) を足す。Counter の & 演算でも得られる。', ins: ['1 1 2\n1 2 2\n', '1 2 3\n4 5 6\n', '1 1 1\n1 1\n', '5\n5\n', '1 2 2 3\n2 2 4\n', '7 7\n7\n'] })

t({ lv: 114, concept: '集合: AのみのサイズとBのみのサイズ', title: 'AのみとBのみの要素数', tags: ['集合'], io: '1行目に列A、2行目に列Bが与えられます。', ask: '「Aにのみある値の数」と「Bにのみある値の数」を空白区切りで出力してください。', h1: '差集合を両方向で取る。', h2: 'それぞれの要素数。', ref: 'a=set(map(int,input().split()))\nb=set(map(int,input().split()))\nprint(len(a-b),len(b-a))', tip: 'a-b と b-a で「片側だけ」を両方向に取れる。ベン図の左右の領域に対応する。', ins: ['1 2 3\n2 3 4\n', '1 2\n3 4\n', '1 2 3\n1 2 3\n', '5 5\n5\n', '1\n2 3\n', '4 5 6\n6\n'] })

t({ lv: 118, concept: '累積和: 単一区間和', title: '区間和を1回求める', tags: ['累積和'], io: '1行目に数列、2行目に l r(0始まり両端含む)が与えられます。', ask: '区間[l,r]の和を出力してください。', h1: '累積和を作る。', h2: 'pre[r+1]-pre[l]。', ref: 'a=list(map(int,input().split()))\nl,r=map(int,input().split())\npre=[0]*(len(a)+1)\nfor i in range(len(a)):\n    pre[i+1]=pre[i]+a[i]\nprint(pre[r+1]-pre[l])', tip: '区間和は累積和の差 pre[r+1]-pre[l] で O(1)。複数クエリでも前計算1回で済む。', ins: ['1 2 3 4 5\n1 3\n', '5\n0 0\n', '1 1 1 1\n0 3\n', '10 20 30\n1 2\n', '-1 -2 -3\n0 2\n', '5 5 5 5\n2 3\n'] })

t({ lv: 119, concept: '数論: 配列全体のGCD', title: '配列全体の最大公約数', tags: ['数論'], io: '正整数の列が1行で与えられます。', ask: '全要素の最大公約数を出力してください。', h1: '順に gcd を畳み込む。', h2: 'math.gcd で2数ずつ。', ref: 'import math\nfrom functools import reduce\na=list(map(int,input().split()))\nprint(reduce(math.gcd,a))', tip: '配列のGCDは reduce(gcd, a) で畳み込む。gcd は結合的なので順序に依らない。', ins: ['12 18 24\n', '7\n', '5 10 15\n', '17 13\n', '100 100\n', '6 9 15\n'] })

t({ lv: 121, concept: '数論: 倍数の総和', title: '1からnでkの倍数の総和', tags: ['数論'], io: 'n k が空白区切りで与えられます。', ask: '1以上 n 以下で k の倍数になる整数の総和を出力してください。', h1: '倍数の個数 m=n//k。', h2: 'k(1+2+...+m)=k·m(m+1)/2。', ref: 'n,k=map(int,input().split())\nm=n//k\nprint(k*m*(m+1)//2)', tip: '倍数の和は k·(1+2+...+m) と等差和に帰着。m=⌊n/k⌋ で O(1) に計算できる。', ins: ['10 3\n', '10 1\n', '100 7\n', '5 10\n', '1 1\n', '20 4\n'] })

t({ lv: 122, concept: '数論: 3か5の倍数の和', title: 'n未満で3か5の倍数の和', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: 'n 未満で3または5の倍数になる整数の総和を出力してください。', h1: '1からn-1を調べる。', h2: '3か5で割り切れる数を足す。', ref: 'n=int(input())\nprint(sum(x for x in range(1,n) if x%3==0 or x%5==0))', tip: '「3または5の倍数の和」は包除原理(3の倍数和+5の倍数和-15の倍数和)でも O(1) に解ける有名問題。', ins: ['10\n', '1\n', '16\n', '100\n', '3\n', '6\n'] })

t({ lv: 123, concept: '数論: 最小素因数', title: 'nの最小の素因数', tags: ['数論'], io: '2以上の整数 n が1行で与えられます。', ask: 'n の最小の素因数を出力してください。', h1: '2から順に割れるか試す。', h2: '最初に割れた数が最小素因数。', ref: 'n=int(input())\nd=2\nwhile d*d<=n:\n    if n%d==0:\n        print(d)\n        break\n    d+=1\nelse:\n    print(n)', tip: '最小素因数は2から√nまで試し割り。割れなければ n 自身が素数。素因数分解の第一歩。', ins: ['12\n', '7\n', '15\n', '2\n', '100\n', '97\n'] })

t({ lv: 124, concept: '数論: 最大の真の約数', title: 'nの最大の真の約数', tags: ['数論'], io: '2以上の整数 n が1行で与えられます。', ask: 'n 自身を除く最大の約数を出力してください。', h1: 'n の最小素因数 p を求める。', h2: '最大真約数は n/p。', ref: 'n=int(input())\nd=2\np=n\nwhile d*d<=n:\n    if n%d==0:\n        p=d\n        break\n    d+=1\nprint(n//p)', tip: '最大の真約数は n を最小素因数で割った値。素数なら1になる。', ins: ['12\n', '7\n', '15\n', '2\n', '100\n', '49\n'] })

t({ lv: 125, concept: '数論: 過剰数の判定', title: '過剰数かどうか', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: '真の約数の和が n より大きい(過剰数)なら yes、そうでなければ no を出力してください。', h1: '真約数の和を求める。', h2: '和 > n か判定。', ref: 'n=int(input())\nif n==1:\n    print("no")\nelse:\n    s=1\n    d=2\n    while d*d<=n:\n        if n%d==0:\n            s+=d\n            if d!=n//d:\n                s+=n//d\n        d+=1\n    print("yes" if s>n else "no")', tip: '過剰数は真約数和>n(12が最小)。和=nが完全数、和<nが不足数。約数和の応用。', ins: ['12\n', '6\n', '10\n', '1\n', '18\n', '7\n'] })

t({ lv: 126, concept: '数論: べき乗の下2桁', title: 'a^b の下2桁', tags: ['数論'], io: 'a b が空白区切りで与えられます(a>=0, b>=0)。', ask: 'a^b の下2桁(100で割った余り)を出力してください。', h1: 'mod 100 で累乗する。', h2: 'pow(a,b,100)。', ref: 'a,b=map(int,input().split())\nprint(pow(a,b,100))', tip: '下2桁は pow(a,b,100)。3引数 pow は繰り返し2乗法で巨大な指数でも高速にmod冪を計算する。', ins: ['2 10\n', '3 3\n', '7 0\n', '0 5\n', '5 100\n', '12 2\n'] })

t({ lv: 127, concept: 'bit演算: 末尾の0ビット数', title: '2進表記末尾の連続0の数', tags: ['bit演算'], io: '正整数 n が1行で与えられます。', ask: 'n の2進表記で末尾に連続する0の個数を出力してください。', h1: '最下位ビットを見る。', h2: '1が出るまで右シフト。', ref: 'n=int(input())\ncnt=0\nwhile n%2==0:\n    n//=2\n    cnt+=1\nprint(cnt)', tip: '末尾0の数=nを割り切る2の最大べき=(n & -n).bit_length()-1。2の因数の個数を表す。', ins: ['8\n', '12\n', '7\n', '1\n', '16\n', '6\n'] })

t({ lv: 128, concept: 'bit演算: n以上の最小の2のべき', title: 'n以上で最小の2のべき乗', tags: ['bit演算'], io: '正整数 n が1行で与えられます。', ask: 'n 以上で最小の2のべき乗(1,2,4,8,...)を出力してください。', h1: '1から2倍していく。', h2: 'n 以上になったら止める。', ref: 'n=int(input())\np=1\nwhile p<n:\n    p*=2\nprint(p)', tip: 'n以上の最小の2のべきは、配列サイズをべき乗に切り上げるときに使う(セグ木の確保など)。', ins: ['10\n', '1\n', '16\n', '17\n', '7\n', '1000\n'] })

t({ lv: 129, concept: 'bit演算: いずれかで立つビット数', title: '2整数の和集合のビット数', tags: ['bit演算'], io: 'a b が空白区切りで与えられます(非負整数)。', ask: 'a または b のどちらかで1になっているビットの個数を出力してください。', h1: 'OR を取る。', h2: 'OR の立っているビット数。', ref: 'a,b=map(int,input().split())\nprint(bin(a|b).count("1"))', tip: 'いずれかで立つビット数は a|b の立ちビット数。OR は片方でも1なら1になる。', ins: ['6 3\n', '7 7\n', '0 5\n', '12 10\n', '1 2\n', '8 4\n'] })

t({ lv: 131, concept: '数: 交代桁和', title: '桁の交代和', tags: ['数学'], io: '非負整数 n が1行で与えられます。', ask: '一の位から +,-,+,- と交互に符号を付けた桁の和を出力してください(11の倍数判定に使う値)。', h1: '一の位から見る。', h2: '位ごとに符号を反転。', ref: 'n=input().strip()\ntotal=0\nsign=1\nfor c in reversed(n):\n    total+=sign*int(c)\n    sign=-sign\nprint(total)', tip: '交代桁和は11の倍数判定に使う(交代和が11の倍数⇔元の数が11の倍数)。一の位から符号反転。', ins: ['121\n', '0\n', '9\n', '1234\n', '11\n', '99\n'] })

t({ lv: 132, concept: '数: 桁の最大-最小', title: '最大桁と最小桁の差', tags: ['数学'], io: '非負整数 n が1行で与えられます。', ask: 'n の桁のうち最大の数字と最小の数字の差を出力してください。', h1: '各桁を見る。', h2: 'max-min。', ref: 'n=input().strip()\nds=[int(c) for c in n]\nprint(max(ds)-min(ds))', tip: '桁の範囲は max-min。桁を整数リストに変換してから集計するのが扱いやすい。', ins: ['123\n', '5\n', '90\n', '111\n', '4070\n', '987\n'] })

t({ lv: 133, concept: '数: 偶数桁の個数', title: '偶数の桁の個数', tags: ['数学'], io: '非負整数 n が1行で与えられます。', ask: 'n の桁のうち偶数(0,2,4,6,8)である桁の個数を出力してください。', h1: '各桁の偶奇を見る。', h2: '偶数を数える。', ref: 'n=input().strip()\nprint(sum(1 for c in n if int(c)%2==0))', tip: '桁の偶奇カウントは文字を int 化して %2 で判定。0 は偶数として数える。', ins: ['1234\n', '0\n', '13579\n', '2468\n', '5\n', '102\n'] })

t({ lv: 134, concept: '整数: 桁の積が平方数か', title: '桁を掛けたら平方数か', tags: ['数学'], io: '非負整数 n が1行で与えられます。', ask: 'n の各桁の数字をすべて掛けた値が平方数なら yes、そうでなければ no を出力してください(0 は平方数として扱います)。', h1: 'まず各桁の積を求める。', h2: '整数の平方根を取り、2乗して元に戻るか確かめる。', ref: 'import math\nn=input().strip()\np=1\nfor c in n:\n    p*=int(c)\nprint("yes" if math.isqrt(p)**2==p else "no")', tip: '桁の積(既出)に平方数判定を重ねた組合せ。平方かどうかは浮動小数の sqrt でなく isqrt の2乗が元に戻るかで見ると誤差なく決まる。0 を含む数は積が 0 になり、0 は 0 の2乗なので平方数に入る。', ins: ['49\n', '23\n', '7\n', '19\n', '405\n', '1234\n'] })

t({ lv: 135, concept: '数: 回文数の判定', title: '回文数かどうか', tags: ['数学'], io: '非負整数 n が1行で与えられます。', ask: 'n が回文数(逆から読んでも同じ)なら yes、違うなら no を出力してください。', h1: '文字列で反転と比較。', h2: 's==s[::-1]。', ref: 'n=input().strip()\nprint("yes" if n==n[::-1] else "no")', tip: '回文数判定は文字列化して s==s[::-1]。数値演算で桁を反転して比較してもよい。', ins: ['121\n', '123\n', '0\n', '1221\n', '10\n', '7\n'] })

t({ lv: 136, concept: '数: 特定の桁の個数', title: '指定した数字の出現回数(桁)', tags: ['数学'], io: 'n d が空白区切りで与えられます(0<=d<=9)。', ask: 'n の桁のうち d である桁の個数を出力してください。', h1: '文字列で count。', h2: 'str(n).count(str(d))。', ref: 'n,d=input().split()\nprint(n.count(d))', tip: '特定数字の出現回数は文字列の count。桁ごとの統計やチェックディジット計算に使う。', ins: ['1213 1\n', '5 5\n', '100 0\n', '777 7\n', '123 9\n', '0 0\n'] })

t({ lv: 137, concept: '整数: 桁が交互に増減するか', title: '数字が上下に跳ねる数か', tags: ['数学'], io: '正の整数 n が1行で与えられます。', ask: '隣り合う桁が「増える」と「減る」を交互に繰り返しているなら yes、そうでなければ no を出力してください。同じ数字が隣り合う場合は no とし、1桁の数は yes とします。', h1: '隣同士の大小関係を先頭から順に見る。', h2: '差の符号が1つ前と逆かを確かめる。差が0になったらその時点で崩れる。', ref: 's=input().strip()\nok=True\nprev=0\nfor i in range(1,len(s)):\n    d=int(s[i])-int(s[i-1])\n    if d==0 or (prev!=0 and d*prev>0):\n        ok=False\n        break\n    prev=d\nprint("yes" if ok else "no")', tip: '桁が単調に増える・減る(同レベル既出)の対極が交互増減。差の符号を1つ前と比べ、同符号か0が出た時点で崩れる。数列のジグザグ判定をそのまま桁に持ち込んだ形。', ins: ['121\n', '123\n', '1\n', '112\n', '1324\n', '9876\n'] })

t({ lv: 138, concept: '数: アームストロング数の判定', title: 'アームストロング数かどうか', tags: ['数学'], io: '正整数 n が1行で与えられます。', ask: '各桁を「桁数」乗した和が n に等しい(アームストロング数/ナルシシスト数)なら yes、違うなら no を出力してください。', h1: '桁数 k を求める。', h2: '各桁の k 乗の和と比較。', ref: 'n=input().strip()\nk=len(n)\ns=sum(int(c)**k for c in n)\nprint("yes" if s==int(n) else "no")', tip: 'アームストロング数は各桁の(桁数)乗の和が自分自身(153=1³+5³+3³)。桁数をべき指数に使う。', ins: ['153\n', '154\n', '9\n', '370\n', '10\n', '407\n'] })

t({ lv: 139, concept: '数: 素数の桁の個数', title: '素数である桁の個数', tags: ['数学'], io: '非負整数 n が1行で与えられます。', ask: 'n の桁のうち素数(2,3,5,7)である桁の個数を出力してください。', h1: '素数の桁集合を用意する。', h2: '各桁が集合にあるか数える。', ref: 'n=input().strip()\nprimes=set("2357")\nprint(sum(1 for c in n if c in primes))', tip: '1桁の素数は 2,3,5,7 の4つ。集合 in 判定で桁ごとにフィルタする。', ins: ['2357\n', '1486\n', '0\n', '23\n', '999\n', '5\n'] })

export const CATALOG = TASKS
