// 生成タスク 第84波：各レベル3問化フェーズ(11)。lv526〜549, 551〜575 の薄い49段に3問目を追加。
// 貪欲/シミュレーション/バックトラック/BFS帯。クラスタ3問まで可・言い換え水増し禁止。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 526, concept: '統計: パーセンタイル(順位法)', title: '上から下から何パーセント', tags: ['統計', 'ソート'], io: '1行目に p (1〜100)、2行目に整数列が与えられます。', ask: '順位法によるpパーセンタイル、すなわち昇順に並べたときの ⌈p×n÷100⌉ 番目の値を出力してください。', h1: 'ソートして順位を計算するだけ。', h2: '切り上げは −(−a//b) か math.ceil。', ref: 'import math\np=int(input())\na=sorted(map(int,input().split()))\nidx=math.ceil(p*len(a)/100)\nprint(a[idx-1])', tip: 'パーセンタイルには補間法など複数の流儀があり、numpyのpercentileだけでも9種類のmethodがある。順位法(nearest-rank)は必ず実在の値を返すのが持ち味。', ins: ['50\n1 2 3 4\n', '100\n5 1 3\n', '25\n1 2 3 4\n', '90\n1 2 3 4 5 6 7 8 9 10\n', '50\n7\n', '75\n10 20 30 40\n'] })

t({ lv: 527, concept: 'いもす: 最も混雑する最初の時刻', title: 'ピークはいつ来るか', tags: ['いもす', '区間'], io: '1行目に n、続く n 行に滞在区間 l r (時刻lに入り時刻rに出る。滞在は [l, r) ) が与えられます。', ask: '滞在人数が最大になる最初の時刻(整数)を出力してください。', h1: '同時に必要なホーム数(同レベル既出)のargmax版。', h2: '入で+1、出で−1のいもす法を累積して最初の最大を探す。', ref: 'n=int(input())\nevents=[]\nmx=0\nfor _ in range(n):\n    l,r=map(int,input().split())\n    events.append((l,1))\n    events.append((r,-1))\n    if r>mx:\n        mx=r\nimos=[0]*(mx+2)\nfor t2,d in events:\n    imos[t2]+=d\ncur=0\nbest=-1\nbt=0\nfor t2 in range(mx+1):\n    cur+=imos[t2]\n    if cur>best:\n        best=cur\n        bt=t2\nprint(bt)', tip: '最大値そのもの(人数)と最大を実現する時刻はいもす1本から両方出る。店舗のピークタイム分析はこの計算のそのままの応用。', ins: ['3\n1 5\n2 6\n0 3\n', '2\n0 1\n5 6\n', '1\n3 7\n', '3\n0 4\n1 2\n1 3\n', '2\n0 5\n0 5\n', '3\n2 3\n2 4\n3 5\n'] })

t({ lv: 528, concept: 'リスト: 自分以外の合計の一覧', title: '自分を除いたみんなの合計', tags: ['リスト'], io: '整数列が1行で空白区切りで与えられます。', ask: '各要素について「自分以外の全要素の和」を空白区切りで出力してください。', h1: '自分以外の積(同レベル既出)の和版。', h2: '総和から自分を引くだけ(和には逆元がある)。', ref: 'a=list(map(int,input().split()))\ns=sum(a)\nprint(" ".join(str(s-x) for x in a))', tip: '積の版は0の存在で「割り算で戻す」が破綻し左右からの累積が要ったが、和は引き算で常に戻せる。演算に逆元があるかどうかが解法の複雑さを決める、対比の教材。', ins: ['1 2 3\n', '5\n', '2 2\n', '1 -1 4\n', '10 20 30 40\n', '0 0 7\n'] })

t({ lv: 529, concept: 'スタック: 連続して自分以下だった日数の一覧', title: '連勝記録の長さを毎日きく', tags: ['スタック'], io: '株価の列が1行で空白区切りで与えられます。', ask: '各日について「その日以前で、その日の値以下の値が連続していた日数(その日を含む)」を空白区切りで出力してください。', h1: '株価のスパンと呼ばれる古典問題。', h2: '単調スタックに(値, スパン)を積み、自分以下をまとめて吸収する。', ref: 'a=list(map(int,input().split()))\nst=[]\nout=[]\nfor x in a:\n    span=1\n    while st and st[-1][0]<=x:\n        span+=st.pop()[1]\n    st.append((x,span))\n    out.append(span)\nprint(" ".join(map(str,out)))', tip: 'ポップした要素のスパンを吸収して積み直すのがミソで、全体でO(n)。「次に大きい要素」(同レベル既出)の距離版を左向きに畳んだ形になっている。', ins: ['100 80 60 70 60 75 85\n', '1 2 3\n', '3 2 1\n', '5\n', '2 2\n', '4 1 4\n'] })

t({ lv: 530, concept: 'バックトラック: Nクイーンの辞書順最小の解', title: '最初に見つかる女王の配置', tags: ['バックトラック'], io: '整数 n (解が存在する値) が1行で与えられます。', ask: 'n×n 盤の Nクイーンの解のうち、各行のクイーンの列番号(1始まり)を並べた列が辞書順最小になるものを空白区切りで出力してください。', h1: '配置数(同レベル既出)の構成版。', h2: '各行で列番号の小さい順に試すバックトラックの最初の解がそのまま辞書順最小。', ref: 'n=int(input())\ncols=[0]*n\nused=set()\nd1=set()\nd2=set()\nans=None\ndef bt(r):\n    global ans\n    if ans:\n        return\n    if r==n:\n        ans=cols[:]\n        return\n    for c in range(1,n+1):\n        if c not in used and r+c not in d1 and r-c not in d2:\n            used.add(c)\n            d1.add(r+c)\n            d2.add(r-c)\n            cols[r]=c\n            bt(r+1)\n            used.discard(c)\n            d1.discard(r+c)\n            d2.discard(r-c)\nbt(0)\nprint(" ".join(map(str,ans)))', tip: '「候補を昇順に試す深さ優先の最初の解=辞書順最小」はバックトラック一般の便利な性質。数える問題と構成する問題が探索器1つで済む理由でもある。', ins: ['4\n', '1\n', '5\n', '6\n', '8\n', '7\n'] })

t({ lv: 531, concept: 'バックトラック: 辞書順最小のラテン方陣', title: '一番若いラテン方陣', tags: ['バックトラック'], io: '整数 n が1行で与えられます。', ask: '各行・各列に1〜nがちょうど1回ずつ現れるn×nの方陣のうち、行を上から順に読んだ列が辞書順最小のものを、1行ずつ空白区切りで出力してください。', h1: '数える問題(同レベル既出)の構成版。', h2: 'マスを行優先に埋め、小さい数から試す最初の解。答えは巡回シフトの形になる。', ref: 'n=int(input())\ng=[[0]*n for _ in range(n)]\ndef ok(r,c,v):\n    for i in range(n):\n        if g[r][i]==v or g[i][c]==v:\n            return False\n    return True\ndef bt(pos):\n    if pos==n*n:\n        return True\n    r,c=divmod(pos,n)\n    for v in range(1,n+1):\n        if ok(r,c,v):\n            g[r][c]=v\n            if bt(pos+1):\n                return True\n            g[r][c]=0\n    return False\nbt(0)\nfor row in g:\n    print(" ".join(map(str,row)))', tip: '辞書順最小のラテン方陣は「各行を1つずつ巡回シフトした形」になると知られている。貪欲な埋め込みが破綻しない構造があるからこそ、最初の解が一瞬で見つかる。', ins: ['3\n', '1\n', '2\n', '4\n', '5\n'] })

t({ lv: 532, concept: '数え上げ: 積が目標になる部分集合の数', title: '掛けてぴったりの選び方', tags: ['数え上げ', 'バックトラック'], io: '1行目に目標 T、2行目に正整数の列が与えられます。', ask: '空でない部分集合で、要素の積がちょうど T になるものの個数を出力してください。', h1: '和の版(同レベル既出)の積版。', h2: 'Tを割り切らない積は枝刈りできる。総当たりでもよい。', ref: 'T=int(input())\na=list(map(int,input().split()))\nn=len(a)\ncnt=0\nfor mask in range(1,1<<n):\n    p=1\n    for i in range(n):\n        if mask>>i&1:\n            p*=a[i]\n            if p>T:\n                break\n    if p==T:\n        cnt+=1\nprint(cnt)', tip: '和のDPは値の範囲で配列が張れたが、積は爆発するので集合や辞書がDPの土台になる。1が混ざると答えが2倍ずつ増える(1は入れても積が変わらない)のも積ならではの現象。', ins: ['6\n1 2 3\n', '4\n2 2\n', '1\n1 1\n', '10\n2 5 10\n', '7\n2 3\n', '12\n2 2 3\n'] })

t({ lv: 533, concept: 'DP: 両方のグループの和を奇数にできるか', title: '奇数と奇数に割り勝つ', tags: ['DP'], io: '正整数の列(2個以上)が1行で空白区切りで与えられます。', ask: '列を2つの空でないグループに分けて、両方の和を奇数にできるなら yes、できなければ no を出力してください。', h1: '奇数+奇数=偶数、という必要条件から絞る。', h2: '合計が偶数で、かつ奇数の要素が1つでもあればよい。', ref: 'a=list(map(int,input().split()))\ntotal=sum(a)\nprint("yes" if total%2==0 and any(x%2==1 for x in a) else "no")', tip: 'DPを書き始める前に偶奇の議論だけで答えが決まる「見せかけの分割問題」。必要条件を詰めたら十分条件にもなっていた、という証明の快感を短いコードで味わえる。', ins: ['1 3\n', '2 4\n', '1 2 3\n', '1 1 1\n', '3 5 2 4\n', '2 2\n'] })

t({ lv: 534, concept: 'バックトラック: 演算子で作れる値の種類数', title: '記号の差し替えで何通りの答え', tags: ['バックトラック'], io: '数字だけの文字列(2文字以上)が1行で与えられます。', ask: '各数字の間に + − × のいずれかを1つずつ入れ、左から順に計算(優先順位なし)した結果として現れる値の種類数を出力してください。', h1: '目標を作る問題(同レベル既出)の全数版。', h2: '途中結果の集合を桁ごとに広げていく。', ref: 's=input()\nvals={int(s[0])}\nfor c in s[1:]:\n    d=int(c)\n    nv=set()\n    for v in vals:\n        nv.add(v+d)\n        nv.add(v-d)\n        nv.add(v*d)\n    vals=nv\nprint(len(vals))', tip: '左から順の評価なら「今の値の集合」だけ持てばよく、指数的な式の本数が値の種類数(ずっと小さい)に圧縮される。状態の同一視が探索を救う典型。', ins: ['12\n', '11\n', '55\n', '22\n', '123\n', '99\n'] })

t({ lv: 535, concept: 'バックトラック: 単語を全部並べて一致するか', title: '断片を全部使って復元', tags: ['バックトラック'], io: '1行目に文字列 s、2行目に単語たちが空白区切りで与えられます。', ask: '単語を全部ちょうど1回ずつ並べ替えて連結し、s に一致させられるなら yes、できなければ no を出力してください。', h1: '辞書の単語で分割(同レベル既出)と違い「全部1回ずつ」。', h2: '先頭に一致する未使用の単語を選んで再帰。', ref: 's=input()\nws=input().split()\nn=len(ws)\nused=[False]*n\ndef bt(pos):\n    if pos==len(s):\n        return all(used)\n    for i in range(n):\n        if not used[i] and s.startswith(ws[i],pos):\n            used[i]=True\n            if bt(pos+len(ws[i])):\n                return True\n            used[i]=False\n    return False\nprint("yes" if bt(0) else "no")', tip: '長さの合計が一致しなければ即no、という前哨チェックが強力な枝刈りになる。startswithの第2引数(開始位置)を使うとスライスのコピーが消えて速い。', ins: ['abcd\ncd ab\n', 'abc\nab d\n', 'aab\na ab\n', 'xy\ny x\n', 'aaa\naa a\n', 'ab\nba\n'] })

t({ lv: 536, concept: '数え上げ: ナイトが利き合うマスのペア数', title: '騎士がにらみ合う席', tags: ['数え上げ'], io: '盤の一辺 n が1行で与えられます。', ask: 'n×n 盤のマスの組で、ナイトの1手で互いに移動できる位置関係にあるペアの数を出力してください。', h1: '全マスから8方向のナイト移動を数えて2で割る。', h2: '答えは 4(n−1)(n−2) になる(n≥2)。', ref: 'n=int(input())\nmoves=((1,2),(2,1),(-1,2),(-2,1),(1,-2),(2,-1),(-1,-2),(-2,-1))\ncnt=0\nfor i in range(n):\n    for j in range(n):\n        for di,dj in moves:\n            if 0<=i+di<n and 0<=j+dj<n:\n                cnt+=1\nprint(cnt//2)', tip: '有向に数えて2で割る「握手の数え方」。2×3の長方形1つにナイトペアが2組、という数え方をすると閉じた式 4(n−1)(n−2) が自力で導ける。', ins: ['3\n', '1\n', '2\n', '4\n', '5\n', '8\n'] })

t({ lv: 537, concept: '数え上げ: 斜め移動だけで右下へ行く経路数', title: 'ビショップの下り道', tags: ['数え上げ', 'DP'], io: 'H W が空白区切りで1行で与えられます。', ask: 'マス(1,1)から毎回「右下(行+1,列+1)か左下(行+1,列−1)」に動いて盤内だけを通り、マス(H,W)に至る経路の数を出力してください(0の場合もある)。', h1: '行ごとに1段ずつ降りるDP。', h2: '列が盤外に出る遷移を弾く。', ref: 'h,w=map(int,input().split())\ndp=[0]*(w+2)\ndp[1]=1\nfor _ in range(h-1):\n    nd=[0]*(w+2)\n    for c in range(1,w+1):\n        if dp[c]:\n            if c+1<=w:\n                nd[c+1]+=dp[c]\n            if c-1>=1:\n                nd[c-1]+=dp[c]\n    dp=nd\nprint(dp[w])', tip: '列の偶奇が1歩ごとに反転するので、(H+W)の偶奇が合わないと経路数は0。壁での反射を除けばパスカルの三角形と同じ加算構造をしている。', ins: ['3 3\n', '2 2\n', '3 1\n', '4 2\n', '5 3\n', '2 5\n'] })

t({ lv: 538, concept: '数え上げ: 両端が違う文字の並べ方', title: '最初と最後は別の顔', tags: ['数え上げ'], io: '英小文字の文字列(2文字以上)が1行で与えられます。', ask: 'この文字たち全部の並べ替え(同じ文字は区別しない)のうち、先頭と末尾が異なる文字であるものの数を出力してください。', h1: '重複順列(同レベル既出)から「両端が同じ」を引く。', h2: '両端が文字cのものは、cを2個除いた残りの重複順列。', ref: 'from math import factorial\nfrom collections import Counter\ns=input()\nc=Counter(s)\nn=len(s)\ndef perms(cnt):\n    total=factorial(sum(cnt.values()))\n    for v in cnt.values():\n        total//=factorial(v)\n    return total\nans=perms(c)\nfor ch,k in c.items():\n    if k>=2:\n        c2=Counter(c)\n        c2[ch]-=2\n        ans-=perms(c2)\nprint(ans)', tip: '補集合を文字ごとに引く、包除の一歩手前の形。両端固定で「中身は自由」に落ちるのは、条件が端にしか触れないおかげで、内部条件だと一気に難しくなる。', ins: ['aab\n', 'ab\n', 'aa\n', 'aabb\n', 'abc\n', 'aaab\n'] })

t({ lv: 539, concept: 'DP: 符号の付け方で作れる値の種類数', title: 'プラスマイナスの実験室', tags: ['DP'], io: '正整数の列が1行で空白区切りで与えられます。', ask: '各要素に + か − を付けて全部足すとき、結果として作れる値の種類数を出力してください。', h1: '目標を作る方法の数(同レベル既出)の全数版。', h2: '到達可能な値の集合を要素ごとに±で広げる。', ref: 'a=list(map(int,input().split()))\ns={0}\nfor x in a:\n    s={y+x for y in s}|{y-x for y in s}\nprint(len(s))', tip: '全ての結果は総和と偶奇が一致する(±の切替は2xずつ動く)ので、種類数は高々(総和÷最小刻み)程度に収まる。集合DPの膨張が算術的に抑えられている。', ins: ['1 2\n', '1 1\n', '5\n', '1 2 3\n', '2 2\n', '1 1 1\n'] })

t({ lv: 540, concept: '数え上げ: ちょうどk歩で階段を上る方法', title: '歩数まで決められた階段', tags: ['数え上げ'], io: 'n k が空白区切りで1行で与えられます。', ask: '1段か2段ずつ、ちょうど k 歩で n 段を上り切る方法の数を出力してください(不可能なら 0)。', h1: '2段を使う回数が n−k 回と確定する。', h2: 'C(k, n−k)。ただし 0≤n−k≤k のときだけ。', ref: 'from math import comb\nn,k=map(int,input().split())\nt2=n-k\nprint(comb(k,t2) if 0<=t2<=k else 0)', tip: '歩数を固定すると「どの歩で2段にするか」の選択だけが残り、DPが二項係数1個に潰れる。フィボナッチ(歩数自由)をkで層別すると Σ C(k,n−k) の恒等式が出る。', ins: ['3 2\n', '4 2\n', '3 3\n', '5 3\n', '2 3\n', '10 6\n'] })

t({ lv: 541, concept: '数え上げ: 隣へしか動かせないハノイの手数', title: '飛び越し禁止のハノイ', tags: ['数え上げ', '再帰'], io: '円盤の枚数 n が1行で与えられます。', ask: '3本の杭が一列に並び、円盤は隣の杭にしか動かせない(左端から右端へ直接は不可)とき、n枚を左端から右端へ移す最小手数を出力してください。', h1: '普通のハノイ(同レベル既出)の漸化式 2T+1 がどう変わるか。', h2: 'T(n)=3T(n−1)+2、解くと 3^n−1。', ref: 'n=int(input())\nprint(3**n-1)', tip: '端から端へは「右へ寄せる→戻す→また寄せる」と3回の再帰が要り、2^n−1が3^n−1に跳ね上がる。制約1つで指数の底が変わる、再帰解析の名教材。', ins: ['1\n', '2\n', '3\n', '5\n', '4\n', '7\n'] })

t({ lv: 542, concept: '再帰: 竹内関数の値', title: 'たらい回しの関数', tags: ['再帰'], io: 'x y z が空白区切りで1行で与えられます (0≤x,y,z≤10)。', ask: '竹内関数 tak(x,y,z) = 「x≤y なら y、さもなくば tak(tak(x−1,y,z), tak(y−1,z,x), tak(z−1,x,y))」の値を出力してください。', h1: 'アッカーマン(同レベル既出)と並ぶ再帰ベンチマークの古典。', h2: 'メモ化しないと呼び出しが爆発する。辞書でメモ。', ref: 'import sys\nsys.setrecursionlimit(100000)\nx,y,z=map(int,input().split())\nmemo={}\ndef tak(a,b,c):\n    if a<=b:\n        return b\n    k=(a,b,c)\n    if k in memo:\n        return memo[k]\n    r=tak(tak(a-1,b,c),tak(b-1,c,a),tak(c-1,a,b))\n    memo[k]=r\n    return r\nprint(tak(x,y,z))', tip: '「たらい回し関数」の通称で、Lispの処理系ベンチマークとして歴史に名を残す。値自体は y か z か x に潰れる(McCarthy版)のに、呼び出し回数だけが莫大という皮肉。', ins: ['10 5 0\n', '1 2 3\n', '5 3 1\n', '3 2 4\n', '0 0 0\n', '7 4 2\n'] })

t({ lv: 543, concept: '数列: ファン・エック数列の第n項', title: '前に会ったのはいつだっけ', tags: ['数列', 'シミュレーション'], io: '正整数 n が1行で与えられます。', ask: 'ファン・エック数列(初項0。直前の項が初出なら次は0、再出なら「前回現れてから何項あとか」)の第 n 項を出力してください。', h1: '各値の「最後に現れた位置」を辞書で覚える。', h2: '次項を決めてから辞書を更新する順序が肝。', ref: 'n=int(input())\nlast={}\ncur=0\nfor i in range(1,n):\n    nxt=i-last[cur] if cur in last else 0\n    last[cur]=i\n    cur=nxt\nprint(cur)', tip: '2019年にOEISで話題になった数列で、無限に新しい値が現れることは証明済みだが、同じ値が2回続くかなど未解決問題が残る現役の研究対象。', ins: ['1\n', '5\n', '6\n', '10\n', '4\n', '8\n'] })

t({ lv: 544, concept: '整数: 桁和を繰り返す回数', title: '一桁になるまでの手数', tags: ['整数'], io: '正整数 n が1行で与えられます。', ask: '「各桁の和を取る」操作を n が1桁になるまで繰り返す回数を出力してください(最初から1桁なら0)。', h1: '数字根(同レベル既出)は最終値、こちらは回数。', h2: 'whileで数えるだけ。', ref: 'n=int(input())\nc=0\nwhile n>=10:\n    n=sum(int(d) for d in str(n))\n    c+=1\nprint(c)', tip: '加法的持続度(additive persistence)と呼ばれ、回数2が最初に必要なのは19、3は199、4は19999999999999999999999(23桁)と爆発的に遠くなる。', ins: ['199\n', '9\n', '10\n', '99\n', '1234\n', '5\n'] })

t({ lv: 545, concept: 'bit演算: 最上位ビットの値の総和', title: '一番上の位だけ集める', tags: ['bit演算'], io: '正整数 N が1行で与えられます。', ask: '1 から N までの各整数について「最上位ビットの値(その数以下で最大の2のべき乗)」を求め、その総和を出力してください。', h1: '1ビットの総数(同レベル既出)と同じ範囲集計。', h2: '各xの寄与は 2^(bit_length−1)。区間 [2^k, 2^(k+1)) でまとめ数えもできる。', ref: 'n=int(input())\nprint(sum(1<<(x.bit_length()-1) for x in range(1,n+1)))', tip: '最上位ビットが 2^k の数はちょうど 2^k 個並ぶので、ブロックごとの寄与は 4^k。等比数列の和でO(log N)の閉じた式にできる、範囲集計の練習台。', ins: ['1\n', '3\n', '7\n', '10\n', '16\n', '100\n'] })

t({ lv: 546, concept: '数え上げ: 01の切り替わりがk回の列', title: '立ち上がりの回数を指定して', tags: ['数え上げ', 'DP'], io: 'n k が空白区切りで1行で与えられます。', ask: '長さ n の0/1列のうち、部分文字列「01」(0の直後に1が来る形)がちょうど k 回現れるものの数を出力してください。', h1: '状態は「今何文字目か・最後の文字・01の回数」。', h2: '1を置くとき直前が0なら回数+1。', ref: 'n,k=map(int,input().split())\ndp={(0,0):1,(1,0):1}\nfor _ in range(n-1):\n    nd={}\n    for (last,c),v in dp.items():\n        for b in (0,1):\n            nc=c+(1 if last==0 and b==1 else 0)\n            if nc<=k:\n                key=(b,nc)\n                nd[key]=nd.get(key,0)+v\n    dp=nd\nprint(sum(v for (last,c),v in dp.items() if c==k))', tip: '答えは C(n+1, 2k+1) という驚きの閉形式を持つ(立ち上がり位置の仕切りの数え上げで証明できる)。DPの数表からこの二項係数を「発見」するのも一興。', ins: ['3 1\n', '3 0\n', '4 1\n', '4 2\n', '5 2\n', '6 1\n'] })

t({ lv: 547, concept: '数列: n番目のレピュニット', title: '1だけを並べた数', tags: ['数列'], io: '正整数 n が1行で与えられます。', ask: 'レピュニット(1, 11, 111, …。1がn個並ぶ数)の第 n 項を整数として出力してください。', h1: '文字列で作るか、漸化式で作るか。', h2: 'R(n)=10×R(n−1)+1、または (10^n−1)//9。', ref: 'n=int(input())\nprint((10**n-1)//9)', tip: 'レピュニットが素数になる n は 2, 19, 23, 317, 1031… と稀にしか現れず、無限にあるかは未解決。(10^n−1)/9 という閉じた式は「9で割ると1が並ぶ」の逆読み。', ins: ['1\n', '2\n', '3\n', '5\n', '4\n', '7\n'] })

t({ lv: 548, concept: '数え上げ: 曲がる回数がちょうどkの経路', title: '曲がり角の数まで指定して', tags: ['数え上げ', 'DP'], io: 'a b k が空白区切りで1行で与えられます。', ask: '(0,0)から右か上に1ずつ進んで(a,b)へ行く経路のうち、進行方向が変わる回数がちょうど k のものの数を出力してください。', h1: '状態に「最後の向き」と「曲がった回数」を足す。', h2: 'dp[位置][向き][回数] の4次元DP。', ref: 'a,b,k=map(int,input().split())\ndp={}\nif a>0:\n    dp[(1,0,0,0)]=1\nif b>0:\n    dp[(0,1,1,0)]=1\nfor _ in range(a+b-1):\n    nd={}\n    for (x,y,d,t),c in dp.items():\n        if x<a:\n            key=(x+1,y,0,t+(1 if d==1 else 0))\n            nd[key]=nd.get(key,0)+c\n        if y<b:\n            key=(x,y+1,1,t+(1 if d==0 else 0))\n            nd[key]=nd.get(key,0)+c\n    dp=nd or dp\nprint(sum(c for (x,y,d,t),c in dp.items() if x==a and y==b and t==k))', tip: '曲がり回数固定の経路は「RとUの連(ラン)の個数」の指定と同値で、仕切りを使った閉じた式 2C(a−1,⌈k/2⌉)C(b−1,⌊k/2⌋) 系に畳める。DPは公式の実験台。', ins: ['3 2 1\n', '4 3 2\n', '6 3 3\n', '5 3 4\n', '4 4 3\n', '5 5 4\n'] })

t({ lv: 549, concept: '組合せ: 三角形に現れる回数', title: 'パスカルの三角形での出席回数', tags: ['組合せ'], io: '2以上の整数 v が1行で与えられます。', ask: 'パスカルの三角形全体(全ての C(n,k))の中に値 v が現れる回数を出力してください。', h1: 'vより下の行には現れない(C(n,1)=n)。', h2: '0〜v行目までを走査して数える。', ref: 'from math import comb\nv=int(input())\ncnt=0\nfor n in range(v+1):\n    for k in range(n+1):\n        if comb(n,k)==v:\n            cnt+=1\nprint(cnt)', tip: 'どの数も現れる回数は有限で、無限回現れるのは1だけ。3003は8回現れる現在の記録保持者で、あらゆる数の出現回数が12回以下かはシングマスター予想として未解決。', ins: ['6\n', '2\n', '4\n', '10\n', '3\n', '120\n'] })

t({ lv: 551, concept: '貪欲: 区間で線分を覆う最小本数', title: '足りない所なく毛布を掛ける', tags: ['貪欲', '区間'], io: '1行目に T と n、続く n 行に区間 l r が与えられます。', ask: '区間をいくつか選んで [0, T] 全体を覆うときの最小本数を出力してください(覆えなければ -1)。', h1: '今届いている右端から先へ、最も遠くまで届く区間を選ぶ。', h2: '左端が現カバー以下の区間の中で右端最大を貪欲に取る。', ref: 'first=input().split()\nT,n=int(first[0]),int(first[1])\niv=[tuple(map(int,input().split())) for _ in range(n)]\niv.sort()\ncover=0\ncnt=0\ni=0\nok=True\nwhile cover<T:\n    best=cover\n    while i<len(iv) and iv[i][0]<=cover:\n        if iv[i][1]>best:\n            best=iv[i][1]\n        i+=1\n    if best==cover:\n        ok=False\n        break\n    cover=best\n    cnt+=1\nprint(cnt if ok else -1)', tip: '「届く範囲で最遠へ」はジャンプゲームの最小ジャンプ数(既出)と同じ骨格で、区間被覆はその区間版。重ならない区間選び(既出)とは目的が真逆なのに、どちらもソート+貪欲。', ins: ['5 3\n0 3\n2 5\n1 2\n', '10 2\n0 4\n5 10\n', '4 1\n0 4\n', '6 4\n0 2\n1 4\n3 6\n5 6\n', '3 3\n0 1\n1 2\n2 3\n', '8 3\n0 5\n4 8\n2 6\n'] })

t({ lv: 552, concept: 'シミュレーション: エレベーターの一往復の移動距離', title: '上へ回ってから下へ', tags: ['シミュレーション'], io: '1行目に現在の階 c、2行目にリクエストされた階の列が与えられます(cと同じ階は含まない)。', ask: 'SCAN方式(まず上にあるリクエストを全て処理してから、下にあるリクエストを処理する)で全てを回るときの総移動距離を出力してください。', h1: '上の最大と下の最小だけで距離が決まる。', h2: '上があれば (最上−c)、さらに下があれば (最上−最下) を足す。', ref: 'c=int(input())\nfs=list(map(int,input().split()))\nup=[f for f in fs if f>c]\ndown=[f for f in fs if f<c]\nif up:\n    d=max(up)-c+((max(up)-min(down)) if down else 0)\nelse:\n    d=c-min(down)\nprint(d)', tip: 'ディスクのヘッドスケジューリングで有名なSCAN(エレベーターアルゴリズム)。途中の階は「ついでに」処理されるので、距離は両端の折り返しだけで決まる。', ins: ['5\n8 3 10 1\n', '3\n5 7\n', '10\n2 5\n', '4\n9\n', '6\n1 2 3\n', '5\n8 1\n'] })

t({ lv: 553, concept: 'シミュレーション: 印刷キューの完了順', title: '割り込みありの印刷待ち', tags: ['シミュレーション'], io: '1行目にジョブ数 n、2行目に各ジョブの優先度が与えられます(ジョブは1〜nの順で列に並んでいます)。', ask: '「先頭を見て、自分より優先度の高いジョブが列にあれば末尾へ回し、なければ印刷する」を繰り返すときの印刷順を空白区切りで出力してください。', h1: 'dequeで先頭を回すか印刷するか。', h2: '「より高い」の判定は残りの最大と比べる。', ref: 'from collections import deque\nn=int(input())\npr=list(map(int,input().split()))\nq=deque(range(1,n+1))\nout=[]\nwhile q:\n    j=q[0]\n    if any(pr[x-1]>pr[j-1] for x in q):\n        q.rotate(-1)\n    else:\n        q.popleft()\n        out.append(j)\nprint(" ".join(map(str,out)))', tip: 'プリンタスプーラの古典モデル。同じ優先度は先着順が保たれる(安定)ことと、毎回最大を探すO(n²)を優先度ごとのカウンタでO(n log n)にできることが観察ポイント。', ins: ['3\n1 3 2\n', '2\n5 5\n', '4\n2 1 4 3\n', '1\n9\n', '3\n3 3 1\n', '3\n1 2 3\n'] })

t({ lv: 554, concept: 'DP: 最小枚数の払い方が2通り以上ある最小金額', title: '最適解がひとつに決まらない金額', tags: ['DP'], io: '1行目に探索上限 L、2行目に硬貨の額面(1を含む)が与えられます(答えはL以下に存在)。', ask: '最小枚数で払う硬貨の組合せ(多重集合)が2通り以上ある最小の金額を出力してください。', h1: '最小枚数と「最小を達成する組合せの数」を同時にDPする。', h2: '額面ごとの外側ループにすると組合せ(順序なし)が数えられる。', ref: 'L=int(input())\ncoins=list(map(int,input().split()))\nINF=10**9\nbest=[INF]*(L+1)\nways=[0]*(L+1)\nbest[0]=0\nways[0]=1\nfor c in coins:\n    for s in range(c,L+1):\n        if best[s-c]+1<best[s]:\n            best[s]=best[s-c]+1\n            ways[s]=ways[s-c]\n        elif best[s-c]+1==best[s]:\n            ways[s]+=ways[s-c]\nprint(next(s for s in range(1,L+1) if ways[s]>=2))', tip: '正準硬貨系(同レベル既出)でも最適の「一意性」までは保証されない。順序を区別しない数え方は硬貨外側ループ、区別するなら金額外側——両替DPの2大流儀の使い分けが試される。', ins: ['10\n2 3 4\n', '10\n1 2 3\n', '6\n2 3 4\n', '7\n1 2 3\n', '12\n1 2 3\n', '8\n2 3 4\n'] })

t({ lv: 555, concept: '貪欲: 間に合わない仕事の最小数', title: 'あきらめる仕事は最少に', tags: ['貪欲', 'ヒープ'], io: '1行目に仕事数 n、続く n 行に「所要時間 締切」が与えられます。1つずつ順に処理します(所要の合計時刻が締切以下なら間に合う)。', ask: '順序を自由に選べるとき、締切に間に合わない仕事の最小数を出力してください。', h1: 'ムーアの定理: 締切順に入れて、溢れたら一番重い仕事を捨てる。', h2: '捨てる候補は最大ヒープで管理。', ref: 'import heapq\nn=int(input())\njobs=[tuple(map(int,input().split())) for _ in range(n)]\njobs.sort(key=lambda td:td[1])\nh=[]\ntime=0\nfor t2,d in jobs:\n    heapq.heappush(h,-t2)\n    time+=t2\n    if time>d:\n        time+=heapq.heappop(h)\nprint(n-len(h))', tip: 'ムーア=ホジソンのアルゴリズム。締切に遅れる仕事の「数」の最小化は貪欲+ヒープで解けるが、遅れの「量」の最小化はNP困難になる——目的関数1つで世界が変わる。', ins: ['3\n2 3\n1 2\n3 6\n', '3\n3 3\n3 4\n3 5\n', '2\n5 4\n1 6\n', '1\n2 2\n', '4\n2 2\n2 4\n2 6\n2 8\n', '4\n4 4\n4 5\n4 6\n1 7\n'] })

t({ lv: 556, concept: 'シミュレーション: バスの定員オーバー判定', title: '積み残しなく運べるか', tags: ['シミュレーション'], io: '1行目に定員 C、2行目に各停留所で乗る人数、3行目に各停留所で降りる人数(先に降車)が与えられます。', ask: 'どの区間でも乗客数が定員を超えないなら yes、超える瞬間があれば no を出力してください。', h1: '停留所ごとに降ろしてから乗せる。', h2: '累計を持ち回って毎回Cと比較。', ref: 'C=int(input())\nons=list(map(int,input().split()))\noffs=list(map(int,input().split()))\ncur=0\nok=True\nfor on,off in zip(ons,offs):\n    cur-=off\n    cur+=on\n    if cur>C:\n        ok=False\nprint("yes" if ok else "no")', tip: '「降車が先」という処理順の仕様が答えを分けることがある(同じ停留所で入れ替わる場合)。現実の系のシミュレーションでは、イベントの順序の明文化が仕様の半分を占める。', ins: ['3\n2 3 1\n0 2 3\n', '2\n2 1\n0 0\n', '5\n5 0\n0 5\n', '1\n1 1\n0 1\n', '4\n3 2 2\n0 1 4\n', '2\n1 2\n0 0\n'] })

t({ lv: 557, concept: 'シミュレーション: 早い者勝ちの区間受付', title: '申込順に会場を貸す', tags: ['シミュレーション', '区間'], io: '1行目に n、続く n 行に申込順の区間 l r が与えられます。', ask: '申込順に「すでに受け付けた区間のどれとも共有点を持たなければ受け付ける」とき、受け付けられる件数を出力してください。', h1: '最適な選び方(区間スケジューリング)との違いを観察する問題。', h2: '受理済みリストと重なり判定 max(l)≤min(r)。', ref: 'n=int(input())\nacc=[]\nfor _ in range(n):\n    l,r=map(int,input().split())\n    if all(max(l,al)>min(r,ar) for al,ar in acc):\n        acc.append((l,r))\nprint(len(acc))', tip: '終了時刻順の貪欲(既出)が最適を保証するのに対し、先着順は「早くて長い」予約に場所を食われて損をし得る。同じ入力で両者を比べると貪欲の設計の意味が立ち上がる。', ins: ['3\n1 5\n2 3\n6 8\n', '2\n1 2\n3 4\n', '3\n5 9\n1 4\n4 6\n', '1\n0 10\n', '4\n1 3\n2 5\n4 7\n8 9\n', '3\n1 10\n2 3\n4 5\n'] })

t({ lv: 558, concept: 'スタック: 積み降ろしで作る辞書順最小', title: '貨車の入れ替えで一番若い並び', tags: ['スタック', '貪欲'], io: '英小文字の文字列が1行で与えられます。', ask: '文字を左から順にスタックへ押し込み、任意のタイミングでポップして出力列に加えるとき、作れる辞書順最小の出力を出力してください。', h1: 'ポップしてよいのは「スタックの頭が、残りのどの文字よりも大きくない」とき。', h2: '残り部分の最小文字を前計算しておく。', ref: 's=input()\nn=len(s)\nsuf=[chr(127)]*(n+1)\nfor i in range(n-1,-1,-1):\n    suf[i]=min(s[i],suf[i+1])\nst=[]\nout=[]\nfor i,c in enumerate(s):\n    st.append(c)\n    while st and st[-1]<=suf[i+1]:\n        out.append(st.pop())\nwhile st:\n    out.append(st.pop())\nprint("".join(out))', tip: '操車場の貨車並べ替えとして知られる古典。「今出すか、後の小ささに賭けるか」の判断を接尾辞最小値の前計算が支える、貪欲と前処理の good コンビ。', ins: ['cab\n', 'bca\n', 'abc\n', 'cba\n', 'bab\n', 'dcab\n'] })

t({ lv: 559, concept: '貪欲: 間隔d以上で座れる最大人数', title: 'ソーシャルディスタンスの席選び', tags: ['貪欲'], io: '1行目に間隔 d、2行目に座れる位置(昇順)が与えられます。', ask: 'どの2人の位置の差も d 以上になるように座るときの最大人数を出力してください。', h1: '左端から貪欲に座るのが最適。', h2: '最後に座った位置+d 以上の最初の席へ。', ref: 'd=int(input())\npos=list(map(int,input().split()))\ncnt=0\nlast=None\nfor p in pos:\n    if last is None or p-last>=d:\n        cnt+=1\n        last=p\nprint(cnt)', tip: '「左端貪欲が最適」は交換論法で一行証明できる(より左に座って損しない)。間隔dを二分探索の判定関数に使うと、牛の配置問題(既出)の中身がこれだと分かる。', ins: ['3\n1 2 4 6 9\n', '2\n1 2 3\n', '1\n5 6\n', '10\n1 5\n', '3\n0 3 6 9\n', '4\n1 2 3 4 5 6 7 8 9\n'] })

t({ lv: 560, concept: 'シミュレーション: 跳んだ足あとの一覧', title: '通ったマスの記録', tags: ['シミュレーション'], io: '各マスに書かれたジャンプ距離(正整数)の列が1行で空白区切りで与えられます。', ask: '先頭のマスから始めて「書かれた数だけ右へ跳ぶ」を繰り返し、列の外に出るまでに踏んだマスの位置(1始まり)を順に空白区切りで出力してください。', h1: '最後尾に届くか(同レベル既出)の経路記録版。', h2: '位置を更新しながらリストに積む。', ref: 'a=list(map(int,input().split()))\npos=0\nout=[]\nwhile pos<len(a):\n    out.append(pos+1)\n    pos+=a[pos]\nprint(" ".join(map(str,out)))', tip: '正のジャンプなので必ず停止する(停止性が自明)。関数グラフの軌道(既出)と同じ「行き先を辿る」型だが、こちらは外に出るという明確な終端がある。', ins: ['2 3 1 1\n', '1 1 1\n', '3 9 9\n', '5\n', '2 9 2 9\n', '1 2 1 2\n'] })

t({ lv: 561, concept: 'グラフ: 星形の成分の数', title: 'スター型のグループを探す', tags: ['グラフ'], io: '1行目に頂点数 n と辺数 m、続く m 行に無向辺 u v が与えられます。', ask: '連結成分のうち「中心の1頂点に他の全頂点(1個以上)がぶら下がり、他に辺がない」星形の個数を出力してください。', h1: 'クリーク成分(同レベル既出)と同じ「成分ごとの形判定」。', h2: '成分のサイズsに対して辺数がs−1、最大次数がs−1なら星。', ref: 'n,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\nseen=[False]*(n+1)\ncnt=0\nfor s in range(1,n+1):\n    if seen[s]:\n        continue\n    seen[s]=True\n    comp=[s]\n    st=[s]\n    while st:\n        x=st.pop()\n        for y in g[x]:\n            if not seen[y]:\n                seen[y]=True\n                comp.append(y)\n                st.append(y)\n    size=len(comp)\n    edges=sum(len(g[v]) for v in comp)//2\n    mx=max(len(g[v]) for v in comp)\n    if size>=2 and edges==size-1 and mx==size-1:\n        cnt+=1\nprint(cnt)', tip: '辺数s−1は木、最大次数s−1は中心の存在——2条件の合わせ技で星形が特徴づけられる。ハブ&スポーク構造の検出はネットワーク解析の頻出パターン。', ins: ['6 4\n1 2\n1 3\n1 4\n5 6\n', '3 3\n1 2\n2 3\n1 3\n', '4 3\n1 2\n2 3\n3 4\n', '2 1\n1 2\n', '7 5\n1 2\n1 3\n4 5\n4 6\n4 7\n', '5 2\n1 2\n3 4\n'] })

t({ lv: 562, concept: 'ハッシュ: 1文字違いの単語ペアの数', title: '一字違いの隣人たち', tags: ['ハッシュ', '文字列'], io: '単語が空白区切りで1行に与えられます。', ask: '同じ長さでちょうど1文字だけ違う単語のペア (i<j) の個数を出力してください。', h1: '1文字ずつ変えて届くか(同レベル既出)の辺の本数にあたる。', h2: '全ペアで長さ一致と相違数1を確かめる。', ref: 'ws=input().split()\nn=len(ws)\ncnt=0\nfor i in range(n):\n    for j in range(i+1,n):\n        a,b=ws[i],ws[j]\n        if len(a)==len(b) and sum(1 for x,y in zip(a,b) if x!=y)==1:\n            cnt+=1\nprint(cnt)', tip: 'ワードラダーの盤面(グラフ)の辺数を数えている。高速化はワイルドカード化(c_tをc*tにしてグループ化)で、同じ発想が近似検索のインデックスにも使われる。', ins: ['cat bat hat cap\n', 'ab cd\n', 'a b\n', 'abc abd abe\n', 'x xy\n', 'aa ab ba\n'] })

t({ lv: 563, concept: 'BFS: ワープつき迷路の最短歩数', title: '瞬間移動の扉がある迷路', tags: ['BFS', 'グリッド'], io: '1行目に H W、続く H 行に盤面(S 開始、G 目標、# 壁、. 通路、P ワープ地点が0個か2個)が与えられます。P のマスからはもう一方の P へ1歩で跳べます。', ask: 'S から G までの最短歩数を出力してください(到達不能なら -1)。', h1: '普通の4方向移動にワープの辺を1本足すだけ。', h2: 'PからPへのコスト1の特別な隣接を追加してBFS。', ref: 'from collections import deque\nh,w=map(int,input().split())\ng=[input() for _ in range(h)]\nps=[(i,j) for i in range(h) for j in range(w) if g[i][j]=="P"]\nstart=next((i,j) for i in range(h) for j in range(w) if g[i][j]=="S")\ndist=[[-1]*w for _ in range(h)]\ndist[start[0]][start[1]]=0\nq=deque([start])\nans=-1\nwhile q:\n    i,j=q.popleft()\n    if g[i][j]=="G":\n        ans=dist[i][j]\n        break\n    nbrs=[(i+di,j+dj) for di,dj in ((1,0),(-1,0),(0,1),(0,-1))]\n    if g[i][j]=="P":\n        other=ps[0] if ps[1]==(i,j) else ps[1]\n        nbrs.append(other)\n    for ni,nj in nbrs:\n        if 0<=ni<h and 0<=nj<w and g[ni][nj]!="#" and dist[ni][nj]<0:\n            dist[ni][nj]=dist[i][j]+1\n            q.append((ni,nj))\nprint(ans)', tip: 'ワープはグラフに「遠くへの1本の辺」を足すだけ、とモデル化できればBFS本体は無傷で済む。盤面をグラフに読み替える柔軟さが問われる拡張で、複数ペアや片方向化も同じ枠で書ける。', ins: ['1 7\nS.P#P.G\n', '1 5\nS...G\n', '2 3\nS#G\nP.P\n', '1 6\nSP##PG\n', '3 3\nS#G\n.#.\nP#P\n', '1 3\nS#G\n'] })

t({ lv: 564, concept: 'ダイクストラ: 待ち合わせの最小合計距離', title: 'どこで落ち合うのが一番楽か', tags: ['ダイクストラ', 'グラフ'], io: '1行目に n m a b、続く m 行に無向辺 u v w が与えられます(連結)。', ask: '頂点 a の人と頂点 b の人がある頂点で待ち合わせるとき、2人の移動距離の合計の最小を出力してください。', h1: '両方から1回ずつダイクストラ。', h2: '各頂点で da+db の最小。', ref: 'import heapq\nfirst=input().split()\nn,m,a,b=map(int,first)\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v,w=map(int,input().split())\n    g[u].append((v,w))\n    g[v].append((u,w))\ndef dij(s):\n    INF=float("inf")\n    dist=[INF]*(n+1)\n    dist[s]=0\n    pq=[(0,s)]\n    while pq:\n        d,v=heapq.heappop(pq)\n        if d>dist[v]:\n            continue\n        for to,w in g[v]:\n            if d+w<dist[to]:\n                dist[to]=d+w\n                heapq.heappush(pq,(d+w,to))\n    return dist\nda=dij(a)\ndb=dij(b)\nprint(min(da[v]+db[v] for v in range(1,n+1)))', tip: '合計最小の待ち合わせ点は a-b 間の最短路上のどこでもよい(答えは最短距離そのもの)——と気づくと1回のダイクストラで済む。3人以上になると本当に全点走査が要る。', ins: ['3 2 1 3\n1 2 2\n2 3 2\n', '2 1 1 2\n1 2 5\n', '4 4 1 4\n1 2 1\n2 4 1\n1 3 5\n3 4 5\n', '3 3 1 2\n1 2 10\n1 3 1\n3 2 1\n', '1 0 1 1\n', '5 4 2 5\n1 2 1\n2 3 1\n3 4 1\n4 5 1\n'] })

t({ lv: 565, concept: 'BFS: 火が回る前に脱出できるか', title: '炎とかけっこ', tags: ['BFS', 'グリッド'], io: '1行目に H W、続く H 行に盤面(S 人、G 出口、F 火元、# 壁、. 通路)が与えられます。毎分、人が1歩動き(待機も可)、火は上下左右に1マス広がります。', ask: '人がどのマスにも「火より先に」入り続けて G に到達できるなら yes、できなければ no を出力してください(時刻tに入るマスは火の到達時刻がtより後であること)。', h1: '先に火の到達時刻を全マスで計算する。', h2: '人のBFSでは「到着時刻 < 火の時刻」のマスだけ通す。', ref: 'from collections import deque\nh,w=map(int,input().split())\ng=[input() for _ in range(h)]\nINF=10**9\nfire=[[INF]*w for _ in range(h)]\nq=deque()\nfor i in range(h):\n    for j in range(w):\n        if g[i][j]=="F":\n            fire[i][j]=0\n            q.append((i,j))\nwhile q:\n    i,j=q.popleft()\n    for di,dj in ((1,0),(-1,0),(0,1),(0,-1)):\n        ni,nj=i+di,j+dj\n        if 0<=ni<h and 0<=nj<w and g[ni][nj]!="#" and fire[ni][nj]==INF:\n            fire[ni][nj]=fire[i][j]+1\n            q.append((ni,nj))\nstart=next((i,j) for i in range(h) for j in range(w) if g[i][j]=="S")\nseen=[[False]*w for _ in range(h)]\nseen[start[0]][start[1]]=True\nq=deque([(start[0],start[1],0)])\nok=False\nwhile q:\n    i,j,t2=q.popleft()\n    if g[i][j]=="G":\n        ok=True\n        break\n    for di,dj in ((1,0),(-1,0),(0,1),(0,-1)):\n        ni,nj=i+di,j+dj\n        if 0<=ni<h and 0<=nj<w and g[ni][nj]!="#" and not seen[ni][nj] and t2+1<fire[ni][nj]:\n            seen[ni][nj]=True\n            q.append((ni,nj,t2+1))\nprint("yes" if ok else "no")', tip: '動く障害物との競走は「障害物の時刻表を先に確定→自分の探索で参照」の2段BFSが定石。人と火を同時に進めるより、時刻表方式の方がバグの居場所が少ない。', ins: ['2 4\nS..G\nF...\n', '1 5\nS.F.G\n', '1 4\nS..G\n', '2 5\nS...G\n.F...\n', '3 3\nS.G\n...\nF..\n', '1 2\nSG\n'] })

t({ lv: 566, concept: 'グラフ: マッチングの検証', title: 'そのペア表は成立しているか', tags: ['グラフ'], io: '1行目に n m k、続く m 行に無向辺、続く k 行に主張されたペア u v が与えられます。', ask: 'k 個のペアが正しいマッチング(全て実在の辺で、どの頂点も高々1つのペアにしか現れない)なら yes、そうでなければ no を出力してください。', h1: '最大マッチングを解く前の検算器。', h2: '辺集合への所属と、使用頂点の重複を確かめる。', ref: 'first=input().split()\nn,m,k=map(int,first)\nE=set()\nfor _ in range(m):\n    u,v=map(int,input().split())\n    E.add((min(u,v),max(u,v)))\nused=set()\nok=True\nfor _ in range(k):\n    u,v=map(int,input().split())\n    if (min(u,v),max(u,v)) not in E or u in used or v in used:\n        ok=False\n    used.add(u)\n    used.add(v)\nprint("yes" if ok else "no")', tip: '「解くのは難しくても検証は簡単」の典型で、マッチングアルゴリズムのテストハーネスがこの数行。検証器を先に書いてから本体に挑むのは実務の鉄則でもある。', ins: ['4 3 2\n1 2\n3 4\n1 3\n1 2\n3 4\n', '4 2 2\n1 2\n2 3\n1 2\n2 3\n', '3 2 1\n1 2\n2 3\n1 3\n', '2 1 1\n1 2\n1 2\n', '5 4 2\n1 2\n3 4\n4 5\n1 5\n1 2\n4 5\n', '4 4 2\n1 2\n2 3\n3 4\n4 1\n1 2\n3 4\n'] })

t({ lv: 567, concept: 'バックトラック: 森にするための最小頂点除去', title: '閉路を断つ最少の立ち退き', tags: ['バックトラック'], io: '1行目に頂点数 n と辺数 m、続く m 行に無向辺 u v が与えられます。', ask: 'いくつかの頂点(とそれに接続する辺)を取り除いて閉路を全て無くすときの、取り除く頂点数の最小を出力してください。', h1: '閉路があるかの判定(同レベル既出)を部品にする。', h2: '除去数の少ない順に頂点の組合せを試す。', ref: 'from itertools import combinations\nn,m=map(int,input().split())\nes=[tuple(map(int,input().split())) for _ in range(m)]\ndef forest(removed):\n    p=list(range(n+1))\n    def find(x):\n        while p[x]!=x:\n            p[x]=p[p[x]]\n            x=p[x]\n        return x\n    for u,v in es:\n        if u in removed or v in removed:\n            continue\n        ru,rv=find(u),find(v)\n        if ru==rv:\n            return False\n        p[ru]=rv\n    return True\ndef solve():\n    for k in range(n+1):\n        for combo in combinations(range(1,n+1),k):\n            if forest(set(combo)):\n                return k\nprint(solve())', tip: 'フィードバック頂点集合と呼ばれるNP困難問題で、辺を消す版(m−n+c本で確定)が簡単なのと対照的。小さいkから試す反復深化が「最小」の保証を担う。', ins: ['3 3\n1 2\n2 3\n1 3\n', '4 3\n1 2\n2 3\n3 4\n', '4 5\n1 2\n2 3\n3 4\n4 1\n1 3\n', '6 6\n1 2\n2 3\n3 1\n4 5\n5 6\n6 4\n', '2 1\n1 2\n', '4 6\n1 2\n1 3\n1 4\n2 3\n2 4\n3 4\n'] })

t({ lv: 568, concept: 'グラフ: 1辺消して閉路を無くせるか', title: 'あと1本で無限ループが消える', tags: ['グラフ'], io: '1行目に頂点数 n と辺数 m、続く m 行に有向辺 u v が与えられます。', ask: '高々1本の辺を取り除いて閉路のないグラフにできるなら yes、できなければ no を出力してください。', h1: '有向閉路の判定(同レベル既出)を全辺除去で試す。', h2: 'もともと閉路が無ければそのままyes。', ref: 'n,m=map(int,input().split())\nes=[tuple(map(int,input().split())) for _ in range(m)]\ndef acyclic(skip):\n    ind=[0]*(n+1)\n    g=[[] for _ in range(n+1)]\n    for i,(u,v) in enumerate(es):\n        if i!=skip:\n            g[u].append(v)\n            ind[v]+=1\n    st=[v for v in range(1,n+1) if ind[v]==0]\n    cnt=0\n    while st:\n        x=st.pop()\n        cnt+=1\n        for y in g[x]:\n            ind[y]-=1\n            if ind[y]==0:\n                st.append(y)\n    return cnt==n\nprint("yes" if acyclic(-1) or any(acyclic(i) for i in range(m)) else "no")', tip: '全ての有向閉路が1本の辺を共有するか、という問いに等しい。デッドロック解消で「どの依存を1つ切れば直るか」を探す診断がまさにこの計算。', ins: ['3 3\n1 2\n2 3\n3 1\n', '4 4\n1 2\n2 1\n3 4\n4 3\n', '3 2\n1 2\n2 3\n', '2 2\n1 2\n2 1\n', '4 5\n1 2\n2 3\n3 1\n2 4\n4 1\n', '6 6\n1 2\n2 3\n3 1\n4 5\n5 6\n6 4\n'] })

t({ lv: 569, concept: 'グラフ: タダで行ける頂点の数', title: '無料区間だけの小旅行', tags: ['グラフ'], io: '1行目に頂点数 n と辺数 m、続く m 行に無向辺 u v w (wは0か1) が与えられます。', ask: '頂点1から重み0の辺だけを通って行ける頂点の数(頂点1自身を含む)を出力してください。', h1: '0-1BFS(同レベル既出)の前半だけを取り出した形。', h2: 'w==0の辺だけでDFS/BFS。', ref: 'n,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v,w=map(int,input().split())\n    if w==0:\n        g[u].append(v)\n        g[v].append(u)\nseen=[False]*(n+1)\nseen[1]=True\nst=[1]\ncnt=0\nwhile st:\n    x=st.pop()\n    cnt+=1\n    for y in g[x]:\n        if not seen[y]:\n            seen[y]=True\n            st.append(y)\nprint(cnt)', tip: '0-1BFSは「0辺で繋がる塊を1つの超頂点に潰す」と普通のBFSになる——その塊のサイズを1つ数えているのがこの問題。縮約(contraction)の感覚を掴む入り口。', ins: ['3 2\n1 2 0\n2 3 1\n', '3 2\n1 2 0\n2 3 0\n', '2 1\n1 2 1\n', '4 3\n1 2 0\n1 3 1\n3 4 0\n', '1 0\n', '5 4\n1 2 0\n2 3 0\n3 4 1\n4 5 0\n'] })

t({ lv: 570, concept: 'BFS: 最寄りの拠点の番号', title: '一番近い基地はどこ', tags: ['BFS', 'グリッド'], io: '1行目に H W、続く H 行に盤面(S 現在地、英大文字 A〜C が拠点、# 壁、. 通路)が与えられます。', ask: 'S から最も近い拠点の文字を出力してください(同距離ならアルファベット順で先のもの、どこにも行けなければ none)。', h1: 'Sから1回BFSして拠点の距離を集める。', h2: '(距離, 文字)の最小を選ぶ。', ref: 'from collections import deque\nh,w=map(int,input().split())\ng=[input() for _ in range(h)]\nstart=next((i,j) for i in range(h) for j in range(w) if g[i][j]=="S")\ndist=[[-1]*w for _ in range(h)]\ndist[start[0]][start[1]]=0\nq=deque([start])\nbest=None\nwhile q:\n    i,j=q.popleft()\n    if g[i][j].isupper() and g[i][j]!="S":\n        cand=(dist[i][j],g[i][j])\n        if best is None or cand<best:\n            best=cand\n    for di,dj in ((1,0),(-1,0),(0,1),(0,-1)):\n        ni,nj=i+di,j+dj\n        if 0<=ni<h and 0<=nj<w and g[ni][nj]!="#" and dist[ni][nj]<0:\n            dist[ni][nj]=dist[i][j]+1\n            q.append((ni,nj))\nprint(best[1] if best else "none")', tip: 'カーナビの「最寄り検索」の骨格。逆に全拠点から同時に広げる多始点BFS(既出)なら全マスの最寄りが一度に出る——問いの向きで始点を選ぶ設計判断が学べる。', ins: ['1 5\nA.S.B\n', '1 3\nS.B\n', '2 2\nSA\nB.\n', '3 3\nA.B\n...\n.S.\n', '1 4\nS..B\n', '2 3\nS#A\n###\n'] })

t({ lv: 571, concept: 'グラフ: 行けるが帰れない頂点の数', title: '片道切符の行き先', tags: ['グラフ', 'DFS'], io: '1行目に頂点数 n と辺数 m、続く m 行に有向辺 u v が与えられます。', ask: '頂点1から到達できるが、そこから頂点1へは戻って来られない頂点の数を出力してください。', h1: '到達可能(同レベル既出)と相互到達(同レベル既出)の差。', h2: '正向きの到達集合と、逆グラフでの到達集合の差集合。', ref: 'n,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nrg=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    rg[v].append(u)\ndef reach(adj):\n    seen=[False]*(n+1)\n    seen[1]=True\n    st=[1]\n    while st:\n        x=st.pop()\n        for y in adj[x]:\n            if not seen[y]:\n                seen[y]=True\n                st.append(y)\n    return seen\nf=reach(g)\nb=reach(rg)\nprint(sum(1 for v in range(1,n+1) if f[v] and not b[v]))', tip: '「行き」は正グラフ、「帰り」は逆グラフのBFSと、向きの反転が探索を再利用させる。この差集合が空でないことは、頂点1の強連結成分の外に流出があることの証。', ins: ['3 3\n1 2\n2 3\n3 1\n', '2 1\n1 2\n', '4 4\n1 2\n2 1\n1 3\n3 4\n', '3 2\n1 2\n2 3\n', '1 0\n', '5 5\n1 2\n2 3\n3 1\n1 4\n4 5\n'] })

t({ lv: 572, concept: 'DAG: トポロジカル順序の検証', title: 'その並びは筋が通っているか', tags: ['DAG'], io: '1行目に頂点数 n と辺数 m、続く m 行に有向辺 u v (uが先)、最終行に順序(1〜nの並び)が与えられます。', ask: 'この並びが全ての辺の向きと矛盾しない(uが必ずvより前)なら yes、そうでなければ no を出力してください。', h1: '構成(同レベル既出)より検証は簡単。', h2: '各頂点の位置を配列にして辺ごとに比較。', ref: 'n,m=map(int,input().split())\nes=[tuple(map(int,input().split())) for _ in range(m)]\norder=list(map(int,input().split()))\npos=[0]*(n+1)\nfor i,v in enumerate(order):\n    pos[v]=i\nprint("yes" if all(pos[u]<pos[v] for u,v in es) else "no")', tip: '位置の逆引き配列を1回作れば全辺O(1)判定、の前計算パターン。ビルドシステムやマイグレーションの実行計画のバリデーションがこの数行と同型。', ins: ['3 2\n1 2\n2 3\n1 2 3\n', '3 2\n1 2\n2 3\n2 1 3\n', '2 0\n2 1\n', '4 3\n1 2\n1 3\n3 4\n1 3 2 4\n', '4 3\n1 2\n1 3\n3 4\n4 1 2 3\n', '3 3\n1 2\n1 3\n2 3\n1 2 3\n'] })

t({ lv: 573, concept: '木: 一本道かどうか', title: 'その木はただの一本道か', tags: ['木'], io: '1行目に頂点数 n (n≥2)、続く n−1 行に木の辺 u v が与えられます。', ask: 'この木が一本道(パス。全ての頂点が1列に並ぶ)なら yes、そうでなければ no を出力してください。', h1: '分岐が1つでもあれば一本道でない。', h2: '全頂点の次数が2以下か。', ref: 'n=int(input())\ndeg=[0]*(n+1)\nfor _ in range(n-1):\n    u,v=map(int,input().split())\n    deg[u]+=1\n    deg[v]+=1\nprint("yes" if max(deg[1:n+1])<=2 else "no")', tip: '木という前提があるから次数だけで判定できる(一般グラフなら閉路の可能性が混ざる)。前提が判定条件をどこまで軽くするか、を意識する練習。', ins: ['4\n1 2\n2 3\n3 4\n', '4\n1 2\n1 3\n1 4\n', '2\n1 2\n', '5\n1 2\n2 3\n3 4\n4 5\n', '5\n1 2\n2 3\n2 4\n4 5\n', '3\n1 3\n3 2\n'] })

t({ lv: 574, concept: '木: 同じ大きさの部分木のペア数', title: 'サイズが同じ枝のペア', tags: ['木'], io: '1行目に頂点数 n (n≥2)、2行目に頂点2〜nの親が与えられます(根は頂点1)。', ask: '部分木のサイズ(自分を含む頂点数)が等しい頂点のペア (u<v) の個数を出力してください。', h1: '部分木サイズの総和(同レベル既出)の分布版。', h2: 'サイズごとの個数cから C(c,2) を足す。', ref: 'from collections import Counter\nn=int(input())\npar=list(map(int,input().split()))\nsize=[1]*(n+1)\nfor v in range(n,1,-1):\n    size[par[v-2]]+=size[v]\nc=Counter(size[1:n+1])\nprint(sum(v*(v-1)//2 for v in c.values()))', tip: '親リストを番号の大きい順に畳むだけで全部分木サイズが揃う(子が親より大きい番号という規約の恩恵)。サイズの分布は木の均整の指標で、平衡木の解析にも通じる。', ins: ['5\n1 1 2 2\n', '2\n1\n', '3\n1 1\n', '7\n1 1 2 2 3 3\n', '4\n1 2 3\n', '6\n1 1 1 2 2\n'] })

t({ lv: 575, concept: 'グラフ: 輪だけの集まりか', title: '全部が輪っかでできているか', tags: ['グラフ'], io: '1行目に頂点数 n と辺数 m、続く m 行に無向辺 u v (自己ループ・多重辺なし) が与えられます。', ask: 'グラフの全ての連結成分が単純な閉路(輪)なら yes、そうでなければ no を出力してください。', h1: 'ひとつの輪か(同レベル既出)の複数成分版。', h2: '全頂点の次数がちょうど2なら、単純グラフでは自動的に輪の集まりになる。', ref: 'n,m=map(int,input().split())\ndeg=[0]*(n+1)\nfor _ in range(m):\n    u,v=map(int,input().split())\n    deg[u]+=1\n    deg[v]+=1\nprint("yes" if all(deg[v]==2 for v in range(1,n+1)) else "no")', tip: '2-正則グラフ=互いに素な閉路の和、という構造定理のおかげで連結性の検査すら不要になる。次数列だけでどこまで形が決まるか、の好例(次数列の実現可能性は同帯の既出)。', ins: ['3 3\n1 2\n2 3\n1 3\n', '6 6\n1 2\n2 3\n3 1\n4 5\n5 6\n6 4\n', '4 3\n1 2\n2 3\n3 4\n', '4 4\n1 2\n2 3\n3 4\n4 1\n', '3 2\n1 2\n2 3\n', '7 7\n1 2\n2 3\n3 4\n4 1\n5 6\n6 7\n7 5\n'] })

export const CATALOG = TASKS
