// 生成タスク 第32波：lv361〜390。
// より上級の踏み段。LIS(二分探索)・桁DP・bitDP・LCA(ダブリング)・木DP・マナカー・
// セグメント木・二部マッチング・SCC・最大流・ワーシャルフロイド周辺など。
// 再帰は prereq の土台カテゴリ外なので使用可。重複なし・決定的・採点一意。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 361, concept: 'DP: 最長増加部分列(二分探索)', title: '最長増加部分列の長さ', tags: ['dp'], io: '整数列が1行で与えられます。', ask: '狭義単調増加な部分列 (連続でなくてよい) の最大の長さを出力してください。', h1: '各長さで「末尾の最小値」を保つ配列を持つ。', h2: 'bisect で挿入位置を求めて更新すると O(n log n)。', ref: 'import bisect\na=list(map(int,input().split()))\ntails=[]\nfor x in a:\n    i=bisect.bisect_left(tails,x)\n    if i==len(tails):\n        tails.append(x)\n    else:\n        tails[i]=x\nprint(len(tails))', tip: '末尾最小値の配列の長さがそのままLISの長さになる。', ins: ['10 9 2 5 3 7 101 18\n', '0 1 0 3 2 3\n', '7 7 7\n', '1 2 3\n', '5\n', '3 1 2 1 8\n'] })

t({ lv: 362, concept: 'DP: 増加列にする最小削除数', title: '増加列にするための最小削除数', tags: ['dp'], io: '整数列が1行で与えられます。', ask: 'いくつか要素を削除して狭義単調増加列にするときの、削除回数の最小値を出力してください。', h1: '残すべきは最長増加部分列。', h2: '答えは n − LIS。', ref: 'import bisect\na=list(map(int,input().split()))\ntails=[]\nfor x in a:\n    i=bisect.bisect_left(tails,x)\n    if i==len(tails):\n        tails.append(x)\n    else:\n        tails[i]=x\nprint(len(a)-len(tails))', tip: '「最大で残せる数」を求めて全体から引く、は最適化問題の常套手段。', ins: ['3 1 2 1 8\n', '1 2 3\n', '5 4 3\n', '1\n', '3 2 1 4 5\n', '10 1 2 3\n'] })

t({ lv: 363, concept: 'DP: 3連続を避ける最大和', title: '3つ連続では選べない最大和', tags: ['dp'], io: '非負整数列が1行で与えられます。', ask: '連続する3要素を同時には選べないという条件で、選んだ要素の和の最大値を出力してください。', h1: '末尾の「連続選択数」を状態に持つ。', h2: '0個/1個/2個連続の3状態を更新。', ref: 'a=list(map(int,input().split()))\ndp0=0\ndp1=0\ndp2=0\nfor x in a:\n    ndp0=max(dp0,dp1,dp2)\n    ndp1=dp0+x\n    ndp2=dp1+x\n    dp0,dp1,dp2=ndp0,ndp1,ndp2\nprint(max(dp0,dp1,dp2))', tip: '「直前に何個連続で取ったか」を状態に持つのが連続制約DPの基本。', ins: ['1 2 3 4 5\n', '5\n', '1 1 1\n', '0 0 0 0\n', '10 20 30\n', '3 7 4 5 8 9 1\n'] })

t({ lv: 364, concept: 'DP: 回文部分列の個数', title: '回文になる部分列の個数', tags: ['区間DP', 'dp'], io: '文字列 s が1行で与えられます。', ask: '空でない部分列 (連続でなくてよい) のうち回文になっているものの個数を出力してください (位置の異なる選び方は別に数えます)。', h1: '区間 [i,j] の回文部分列数を区間DPで求める。', h2: '両端一致なら内側の数 + 内側 + 1、違えば包除で重複を引く。', ref: 's=input()\nn=len(s)\nif n==0:\n    print(0)\nelse:\n    dp=[[0]*n for _ in range(n)]\n    for i in range(n):\n        dp[i][i]=1\n    for length in range(2,n+1):\n        for i in range(n-length+1):\n            j=i+length-1\n            if s[i]==s[j]:\n                dp[i][j]=dp[i+1][j]+dp[i][j-1]+1\n            else:\n                dp[i][j]=dp[i+1][j]+dp[i][j-1]-dp[i+1][j-1]\n    print(dp[0][n-1])', tip: '区間DP＋包除原理。両端が一致するときに新しい回文が増える。', ins: ['bccb\n', 'aaa\n', 'abc\n', 'a\n', 'aba\n', 'aabb\n'] })

t({ lv: 365, concept: '桁DP: 桁和がS以下の数の個数', title: '桁和がS以下の数の個数', tags: ['桁DP', 'dp'], io: 'N S が空白区切りで与えられます。', ask: '1 以上 N 以下の整数のうち、各桁の和が S 以下であるものの個数を出力してください。', h1: '上位桁から「上限に張り付いているか」と「桁和」を状態に。', h2: '0〜N を数えて 0 の分を引く。', ref: 'line=input().split()\nN=int(line[0])\nS=int(line[1])\ndigits=[int(c) for c in str(N)]\nL=len(digits)\nfrom collections import defaultdict\ncur={(True,0):1}\nfor pos in range(L):\n    nxt=defaultdict(int)\n    d_lim=digits[pos]\n    for (tight,ssum),cnt in cur.items():\n        top=d_lim if tight else 9\n        for d in range(0,top+1):\n            ns=ssum+d\n            if ns>S:\n                continue\n            ntight=tight and (d==d_lim)\n            nxt[(ntight,ns)]+=cnt\n    cur=nxt\ntotal=sum(cnt for (tight,ssum),cnt in cur.items())\nprint(total-1)', tip: '「上限に張り付いているか」のフラグが桁DPの核心。', ins: ['20 3\n', '9 9\n', '100 1\n', '5 0\n', '15 5\n', '99 18\n'] })

t({ lv: 366, concept: 'bitDP: 割当の最小コスト', title: '割当問題の最小コスト', tags: ['bitDP', 'dp'], io: '1行目に n、続く n 行に n 個のコスト (作業者 i に仕事 j を割り当てるコスト) が与えられます。各作業者に異なる仕事を1つずつ割り当てます。', ask: 'コストの合計の最小値を出力してください。', h1: '使った仕事の集合をビットで表す。', h2: 'dp[mask]=mask の仕事を埋めた最小コスト。次の作業者は popcount。', ref: 'n=int(input())\ncost=[list(map(int,input().split())) for _ in range(n)]\nINF=float("inf")\ndp=[INF]*(1<<n)\ndp[0]=0\nfor mask in range(1<<n):\n    if dp[mask]==INF:\n        continue\n    i=bin(mask).count("1")\n    if i>=n:\n        continue\n    for j in range(n):\n        if not (mask>>j)&1:\n            nm=mask|(1<<j)\n            if dp[mask]+cost[i][j]<dp[nm]:\n                dp[nm]=dp[mask]+cost[i][j]\nprint(dp[(1<<n)-1])', tip: '割り当て済み集合をビットマスクで持つと O(2^n · n) で解ける。', ins: ['2\n1 2\n3 4\n', '1\n7\n', '3\n1 2 3\n4 5 6\n7 8 9\n', '2\n5 5\n5 5\n', '3\n9 9 1\n9 1 9\n1 9 9\n', '2\n0 10\n10 0\n'] })

t({ lv: 367, concept: 'bitDP: k等分割が可能か', title: '和が等しいk組に分けられるか', tags: ['bitDP', 'dp'], io: '1行目に n k、2行目に n 個の正整数が与えられます。', ask: '全要素を和が等しい k 個のグループに分けられるなら yes、できないなら no を出力してください。', h1: '総和が k で割り切れ、最大要素が目標以下であること。', h2: 'dp[mask]=mask を使ったとき現在のグループの埋まり (目標で割った余り)。', ref: 'n,k=map(int,input().split())\na=list(map(int,input().split()))\ntotal=sum(a)\nif total%k!=0 or max(a)>total//k:\n    print("no")\nelse:\n    target=total//k\n    full=(1<<n)-1\n    dp=[-1]*(1<<n)\n    dp[0]=0\n    for mask in range(1<<n):\n        if dp[mask]<0:\n            continue\n        for j in range(n):\n            if not (mask>>j)&1 and dp[mask]+a[j]<=target:\n                dp[mask|(1<<j)]=(dp[mask]+a[j])%target\n    print("yes" if dp[full]>=0 else "no")', tip: '「現在のバケツの埋まり具合」を mod で持つと多数グループへの分割が1つのDPに乗る。', ins: ['4 2\n1 1 1 1\n', '4 2\n1 2 3 4\n', '3 2\n1 1 1\n', '5 3\n2 2 2 2 2\n', '4 4\n3 3 3 3\n', '6 2\n1 2 3 4 5 6\n'] })

t({ lv: 368, concept: '数論: 完全順列の数', title: '完全順列 (撹乱順列) の数', tags: ['数論', 'dp'], io: '整数 n (>=0) が1行で与えられます。', ask: '1〜n のどの要素も元の位置に来ない並べ替え (完全順列) の総数を出力してください。', h1: '漸化式 D(n)=(n-1)(D(n-1)+D(n-2))。', h2: 'D(0)=1, D(1)=0 から積み上げる。', ref: 'n=int(input())\nif n==0:\n    print(1)\nelse:\n    d0,d1=1,0\n    for i in range(2,n+1):\n        d0,d1=d1,(i-1)*(d1+d0)\n    print(d1)', tip: '完全順列の数は n!/e に最も近い整数になることでも知られる。', ins: ['1\n', '2\n', '3\n', '4\n', '5\n', '0\n'] })

t({ lv: 369, concept: '数論: 一次不定方程式の可解性', title: 'ax+by=c に整数解があるか', tags: ['数論'], io: 'a b c が空白区切りで与えられます。', ask: 'ax+by=c を満たす整数 x,y が存在するなら yes、存在しないなら no を出力してください。', h1: '解が存在するのは gcd(a,b) が c を割り切るとき。', h2: 'a=b=0 のときは c=0 のみ可。', ref: 'a,b,c=map(int,input().split())\ndef gcd(x,y):\n    while y:\n        x,y=y,x%y\n    return x\ng=gcd(abs(a),abs(b))\nif g==0:\n    print("yes" if c==0 else "no")\nelse:\n    print("yes" if c%g==0 else "no")', tip: 'ベズーの補題: ax+by は gcd(a,b) の倍数全体をちょうど表せる。', ins: ['2 4 6\n', '2 4 5\n', '3 5 1\n', '6 9 3\n', '0 0 0\n', '0 0 5\n'] })

t({ lv: 370, concept: '数論: 連立合同式(複数)', title: '複数の合同式を満たす最小の数', tags: ['数論'], io: '1行目に式の個数 k、続く k 行に r m (x≡r mod m) が与えられます (法は互いに素とは限らない)。', ask: 'すべてを満たす最小の非負整数を出力してください。解が無ければ none を出力してください。', h1: '2つずつ合成 (一般化された中国剰余定理)。', h2: '差が gcd で割り切れなければ解なし。', ref: 'k=int(input())\ndef ext(a,b):\n    old_r,r=a,b\n    old_s,s=1,0\n    while r:\n        q=old_r//r\n        old_r,r=r,old_r-q*r\n        old_s,s=s,old_s-q*s\n    return old_r,old_s\nR=0\nM=1\nok=True\nfor _ in range(k):\n    r,m=map(int,input().split())\n    g,p=ext(M,m)\n    if (r-R)%g!=0:\n        ok=False\n        continue\n    lcm=M//g*m\n    tmp=((r-R)//g*p)%(m//g)\n    R=(R+M*tmp)%lcm\n    M=lcm\nprint(R%M if ok else "none")', tip: '法が互いに素でなくても、整合条件さえ満たせば合成できる。', ins: ['2\n2 3\n3 5\n', '2\n0 2\n0 3\n', '2\n1 2\n0 2\n', '3\n2 3\n3 5\n2 7\n', '1\n5 7\n', '2\n1 4\n3 6\n'] })

t({ lv: 371, concept: 'グラフ: 最近共通祖先(ダブリング)', title: '最近共通祖先の総和', tags: ['グラフ', 'ダブリング'], io: '1行目に n q、続く n-1 行に木の無向辺 u v (根は1)、続く q 行にクエリ a b が与えられます。', ask: '各クエリの a と b の最近共通祖先 (LCA) を求め、その総和を出力してください。', h1: '2^k 先の祖先表 (ダブリング) を作る。', h2: '深さを揃えてから一斉に登る。', ref: 'from collections import deque\nn,q=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(n-1):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\nLOG=1\nwhile (1<<LOG)<n:\n    LOG+=1\nLOG+=1\nup=[[0]*(n+1) for _ in range(LOG)]\ndepth=[0]*(n+1)\nseen=[False]*(n+1)\nseen[1]=True\nup[0][1]=1\ndq=deque([1])\nwhile dq:\n    x=dq.popleft()\n    for y in g[x]:\n        if not seen[y]:\n            seen[y]=True\n            up[0][y]=x\n            depth[y]=depth[x]+1\n            dq.append(y)\nfor k in range(1,LOG):\n    for v in range(1,n+1):\n        up[k][v]=up[k-1][up[k-1][v]]\ndef lca(a,b):\n    if depth[a]<depth[b]:\n        a,b=b,a\n    diff=depth[a]-depth[b]\n    for k in range(LOG):\n        if (diff>>k)&1:\n            a=up[k][a]\n    if a==b:\n        return a\n    for k in range(LOG-1,-1,-1):\n        if up[k][a]!=up[k][b]:\n            a=up[k][a]\n            b=up[k][b]\n    return up[0][a]\ntotal=0\nfor _ in range(q):\n    a,b=map(int,input().split())\n    total+=lca(a,b)\nprint(total)', tip: 'ダブリングで 2^k 先の祖先を持つと LCA が O(log n)/クエリ。', ins: ['3 1\n1 2\n1 3\n2 3\n', '4 2\n1 2\n2 3\n2 4\n3 4\n2 4\n', '2 1\n1 2\n1 2\n', '5 1\n1 2\n2 3\n2 4\n4 5\n3 5\n', '1 1\n1 1\n', '6 2\n1 2\n1 3\n3 4\n3 5\n5 6\n4 6\n5 2\n'] })

t({ lv: 372, concept: '木DP: 最大独立集合', title: '木の最大独立集合の大きさ', tags: ['木', 'dp'], io: '1行目に頂点数 n、続く n-1 行に木の無向辺 u v が与えられます。', ask: 'どの2頂点も辺で結ばれていないように選べる頂点の最大個数を出力してください。', h1: '各頂点で「自分を含む/含まない」の2状態を持つ。', h2: '含むなら子は含まない、含まないなら子は大きい方。', ref: 'from collections import deque\nn=int(input())\ng=[[] for _ in range(n+1)]\nfor _ in range(n-1):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\nparent=[0]*(n+1)\norder=[]\nseen=[False]*(n+1)\nseen[1]=True\nstack=[1]\nwhile stack:\n    x=stack.pop()\n    order.append(x)\n    for y in g[x]:\n        if not seen[y]:\n            seen[y]=True\n            parent[y]=x\n            stack.append(y)\ninc=[1]*(n+1)\nexc=[0]*(n+1)\nfor x in reversed(order):\n    for y in g[x]:\n        if y!=parent[x]:\n            inc[x]+=exc[y]\n            exc[x]+=max(inc[y],exc[y])\nprint(max(inc[1],exc[1]))', tip: '木DPは「行きがけ順を逆にたどる」と再帰なしで子から親へ集約できる。', ins: ['3\n1 2\n2 3\n', '1\n', '4\n1 2\n1 3\n1 4\n', '5\n1 2\n2 3\n3 4\n4 5\n', '2\n1 2\n', '7\n1 2\n1 3\n2 4\n2 5\n3 6\n3 7\n'] })

t({ lv: 373, concept: '文字列: 最長回文(マナカー)', title: '最長回文部分文字列の長さ', tags: ['文字列'], io: '文字列 s が1行で与えられます。', ask: '連続部分文字列のうち回文になっている最長のものの長さを出力してください。', h1: '文字間に番兵 # を挿入し、奇数長に統一。', h2: '既知の回文半径を使い回して線形時間で求める。', ref: 's=input()\nif not s:\n    print(0)\nelse:\n    tt="#"+"#".join(s)+"#"\n    m=len(tt)\n    p=[0]*m\n    c=0\n    r=0\n    for i in range(m):\n        if i<r:\n            p[i]=min(r-i,p[2*c-i])\n        while i-p[i]-1>=0 and i+p[i]+1<m and tt[i-p[i]-1]==tt[i+p[i]+1]:\n            p[i]+=1\n        if i+p[i]>r:\n            c=i\n            r=i+p[i]\n    print(max(p))', tip: 'マナカー法は対称性を使い回し、全中心の回文半径を O(n) で求める。', ins: ['babad\n', 'cbbd\n', 'a\n', 'abacabad\n', 'racecar\n', 'aaaa\n'] })

t({ lv: 374, concept: 'データ構造: セグメント木の区間最小', title: '更新つき区間最小 (セグメント木)', tags: ['データ構造'], io: '1行目に n q、2行目に n 個の値、続く q 行に "upd i x" (位置 i を x に更新) または "min l r" (区間 [l,r] の最小) が与えられます。', ask: 'すべての "min" の結果の合計を出力してください。', h1: '葉に値を置き、親は子の min を持つ。', h2: '更新は葉から根へ、クエリは区間を分割して min。', ref: 'n,q=map(int,input().split())\na=list(map(int,input().split()))\nsize=1\nwhile size<n:\n    size*=2\nINF=float("inf")\ntree=[INF]*(2*size)\nfor i in range(n):\n    tree[size+i]=a[i]\nfor i in range(size-1,0,-1):\n    tree[i]=min(tree[2*i],tree[2*i+1])\ndef update(pos,val):\n    pos+=size\n    tree[pos]=val\n    pos//=2\n    while pos>=1:\n        tree[pos]=min(tree[2*pos],tree[2*pos+1])\n        pos//=2\ndef query(l,r):\n    l+=size\n    r+=size+1\n    res=INF\n    while l<r:\n        if l&1:\n            res=min(res,tree[l])\n            l+=1\n        if r&1:\n            r-=1\n            res=min(res,tree[r])\n        l//=2\n        r//=2\n    return res\ntotal=0\nfor _ in range(q):\n    op=input().split()\n    if op[0]=="upd":\n        update(int(op[1]),int(op[2]))\n    else:\n        total+=query(int(op[1]),int(op[2]))\nprint(total)', tip: 'セグメント木は更新もクエリも O(log n)。BITより一般的な区間演算に対応。', ins: ['5 3\n5 2 8 1 9\nmin 0 4\nupd 3 10\nmin 0 4\n', '3 2\n3 1 2\nmin 0 2\nmin 0 0\n', '1 1\n7\nmin 0 0\n', '4 3\n4 3 2 1\nupd 0 0\nmin 0 1\nmin 2 3\n', '5 1\n1 2 3 4 5\nmin 1 3\n', '4 2\n10 20 30 40\nupd 2 5\nmin 0 3\n'] })

t({ lv: 375, concept: 'グラフ: 二部マッチングの最大数', title: '二部グラフの最大マッチング', tags: ['グラフ'], io: '1行目に L R E (左頂点数・右頂点数・辺数)、続く E 行に u v (左 u と右 v を結ぶ辺、ともに1始まり) が与えられます。', ask: '同じ頂点を2度使わないように選べる辺の最大本数 (最大マッチング) を出力してください。', h1: '各左頂点から増加道を探す (ハンガリアン/Kuhn法)。', h2: '相手が埋まっていても、その相手が別へ移れるなら奪える。', ref: 'import sys\nsys.setrecursionlimit(100000)\nL,R,E=map(int,input().split())\ng=[[] for _ in range(L+1)]\nfor _ in range(E):\n    u,v=map(int,input().split())\n    g[u].append(v)\nmatchR=[0]*(R+1)\ndef try_kuhn(u,visited):\n    for v in g[u]:\n        if not visited[v]:\n            visited[v]=True\n            if matchR[v]==0 or try_kuhn(matchR[v],visited):\n                matchR[v]=u\n                return True\n    return False\nres=0\nfor u in range(1,L+1):\n    visited=[False]*(R+1)\n    if try_kuhn(u,visited):\n        res+=1\nprint(res)', tip: '増加道が見つかる限りマッチングを1本ずつ増やせる (König の定理の基礎)。', ins: ['3 3 4\n1 1\n1 2\n2 1\n3 3\n', '2 2 1\n1 1\n', '3 2 3\n1 1\n2 1\n3 2\n', '2 2 4\n1 1\n1 2\n2 1\n2 2\n', '1 1 0\n', '4 4 4\n1 1\n2 2\n3 3\n4 4\n'] })

t({ lv: 376, concept: 'グラフ: 複数始点ダイクストラ', title: '最寄り始点までの最大の最短距離', tags: ['グラフ', 'heapq'], io: '1行目に n m、続く m 行に u v w (無向、w>=0)、最後の行に始点数 k と k 個の始点番号が与えられます。', ask: '各頂点について最寄りの始点までの最短距離を求め、有限なものの最大値を出力してください (全て不可達なら -1)。', h1: '全始点を距離0でヒープに入れて同時にダイクストラ。', h2: '一度に広げると各頂点の最寄り距離が出る。', ref: 'import heapq\nfirst=input().split()\nn=int(first[0])\nm=int(first[1])\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v,w=map(int,input().split())\n    g[u].append((v,w))\n    g[v].append((u,w))\nsrc=list(map(int,input().split()))\nk=src[0]\nsources=src[1:1+k]\nINF=float("inf")\ndist=[INF]*(n+1)\npq=[]\nfor s in sources:\n    dist[s]=0\n    heapq.heappush(pq,(0,s))\nwhile pq:\n    d,x=heapq.heappop(pq)\n    if d>dist[x]:\n        continue\n    for y,w in g[x]:\n        if d+w<dist[y]:\n            dist[y]=d+w\n            heapq.heappush(pq,(d+w,y))\nbest=-1\nfor i in range(1,n+1):\n    if dist[i]<INF and dist[i]>best:\n        best=dist[i]\nprint(best)', tip: '複数始点でも、まとめてヒープに入れれば単一始点と同じ計算量。', ins: ['4 3\n1 2 1\n2 3 1\n3 4 1\n1 1\n', '3 2\n1 2 5\n2 3 5\n2 1 3\n', '2 1\n1 2 7\n2 1 2\n', '3 0\n1 1\n', '5 4\n1 2 2\n2 3 2\n3 4 2\n4 5 2\n1 1\n', '4 2\n1 2 1\n3 4 1\n2 1 3\n'] })

t({ lv: 377, concept: 'DP: 平方数の和で表す最小個数', title: '平方数の和で表す最小の項数', tags: ['dp'], io: '整数 n (>=0) が1行で与えられます。', ask: 'n を平方数 (1,4,9,16,…) の和で表すときの、最小の項数を出力してください。', h1: 'dp[i]=i を作る最小項数。', h2: 'j*j<=i の各 j で dp[i-j*j]+1 の最小。', ref: 'n=int(input())\nINF=float("inf")\ndp=[0]+[INF]*n\nfor i in range(1,n+1):\n    j=1\n    while j*j<=i:\n        if dp[i-j*j]+1<dp[i]:\n            dp[i]=dp[i-j*j]+1\n        j+=1\nprint(dp[n])', tip: '答えは必ず1〜4 (ラグランジュの四平方定理) になるが、DPでも素直に解ける。', ins: ['12\n', '13\n', '1\n', '0\n', '7\n', '100\n'] })

t({ lv: 378, concept: 'DP: インターリーブ文字列の判定', title: '2文字列を混ぜて作れるか', tags: ['dp', '文字列'], io: '3行に a, b, c が与えられます。', ask: 'c が a と b をそれぞれの順序を保ったまま交互に混ぜたものになっているなら yes、なっていないなら no を出力してください。', h1: 'dp[i][j]=a の i 文字と b の j 文字で c の i+j 文字を作れるか。', h2: 'c の次の文字を a 側か b 側のどちらから取れるか。', ref: 'a=input()\nb=input()\nc=input()\nla,lb,lc=len(a),len(b),len(c)\nif la+lb!=lc:\n    print("no")\nelse:\n    dp=[[False]*(lb+1) for _ in range(la+1)]\n    dp[0][0]=True\n    for i in range(la+1):\n        for j in range(lb+1):\n            if i>0 and dp[i-1][j] and a[i-1]==c[i+j-1]:\n                dp[i][j]=True\n            if j>0 and dp[i][j-1] and b[j-1]==c[i+j-1]:\n                dp[i][j]=True\n    print("yes" if dp[la][lb] else "no")', tip: '2つの文字列の進み具合を2次元の状態にするのがインターリーブDP。', ins: ['abc\ndef\nadbecf\n', 'abc\ndef\nabcdef\n', 'aa\nab\naaba\n', 'abc\ndef\nabcdef\n', 'ab\ncd\nacbe\n', 'a\nb\nba\n'] })

t({ lv: 379, concept: 'グラフ: 最小の閉路長(無向)', title: '無向グラフの最小閉路の長さ', tags: ['グラフ', 'BFS'], io: '1行目に n m、続く m 行に無向辺 u v (単純グラフ) が与えられます。', ask: '最小の閉路の長さ (辺数) を出力してください。閉路が無ければ -1 を出力してください。', h1: '各頂点を始点にBFSし、横辺を見つけたら閉路長を計算。', h2: 'dist[x]+dist[y]+1 が候補。', ref: 'from collections import deque\nn,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\nINF=float("inf")\nbest=INF\nfor s in range(1,n+1):\n    dist=[-1]*(n+1)\n    par=[-1]*(n+1)\n    dist[s]=0\n    dq=deque([s])\n    while dq:\n        x=dq.popleft()\n        for y in g[x]:\n            if dist[y]<0:\n                dist[y]=dist[x]+1\n                par[y]=x\n                dq.append(y)\n            elif par[x]!=y:\n                c=dist[x]+dist[y]+1\n                if c<best:\n                    best=c\nprint(best if best<INF else -1)', tip: '各点からのBFSで非木辺を見れば最小閉路 (内周) が求まる。', ins: ['3 3\n1 2\n2 3\n1 3\n', '4 4\n1 2\n2 3\n3 4\n4 1\n', '3 2\n1 2\n2 3\n', '5 6\n1 2\n2 3\n3 1\n3 4\n4 5\n5 3\n', '4 2\n1 2\n3 4\n', '6 6\n1 2\n2 3\n3 4\n4 5\n5 6\n6 1\n'] })

t({ lv: 380, concept: '数論: 複数の二項係数 mod 素数', title: '複数の組合せを素数で割った余りの和', tags: ['数論'], io: '1行目に素数 p とクエリ数 q、続く q 行に n k (0<=n<p) が与えられます。', ask: '各 C(n,k) mod p を求め、その総和を出力してください。', h1: '階乗とその逆元を前計算する。', h2: 'C(n,k)=fact[n]*inv[k]*inv[n-k] mod p。', ref: 'line=input().split()\np=int(line[0])\nq=int(line[1])\nfact=[1]*p\nfor i in range(1,p):\n    fact[i]=fact[i-1]*i%p\ninv=[1]*p\ninv[p-1]=pow(fact[p-1],p-2,p)\nfor i in range(p-2,-1,-1):\n    inv[i]=inv[i+1]*(i+1)%p\ntotal=0\nfor _ in range(q):\n    n,k=map(int,input().split())\n    if k<0 or k>n:\n        c=0\n    else:\n        c=fact[n]*inv[k]%p*inv[n-k]%p\n    total+=c\nprint(total)', tip: '逆元を末尾から漸化式で一括前計算すると、多数のクエリが O(1) ずつになる。', ins: ['7 2\n5 2\n6 3\n', '11 1\n10 5\n', '5 3\n4 0\n4 4\n3 1\n', '13 1\n12 6\n', '7 2\n3 5\n0 0\n', '101 1\n100 50\n'] })

t({ lv: 381, concept: '累積和: 2次元差分(矩形加算)', title: '矩形加算をまとめて処理 (2次元)', tags: ['累積和'], io: '1行目に H W Q、続く Q 行に r1 c1 r2 c2 x (矩形 [r1..r2]×[c1..c2] に x を加算、0始まり) が与えられます。', ask: '全クエリ適用後のグリッドの最大値を出力してください。', h1: '4隅に +x, -x を置く2次元差分。', h2: '2次元累積和で復元する。', ref: 'first=input().split()\nh=int(first[0])\nw=int(first[1])\nq=int(first[2])\ndiff=[[0]*(w+1) for _ in range(h+1)]\nfor _ in range(q):\n    r1,c1,r2,c2,x=map(int,input().split())\n    diff[r1][c1]+=x\n    diff[r2+1][c1]-=x\n    diff[r1][c2+1]-=x\n    diff[r2+1][c2+1]+=x\nfor i in range(h):\n    for j in range(w):\n        if i>0:\n            diff[i][j]+=diff[i-1][j]\n        if j>0:\n            diff[i][j]+=diff[i][j-1]\n        if i>0 and j>0:\n            diff[i][j]-=diff[i-1][j-1]\nbest=0\nfor i in range(h):\n    for j in range(w):\n        if diff[i][j]>best:\n            best=diff[i][j]\nprint(best)', tip: '1次元のいもす法を2次元に拡張。4隅に符号つきで記録する。', ins: ['3 3 1\n0 0 1 1 5\n', '2 2 2\n0 0 1 1 1\n0 0 0 0 10\n', '1 1 1\n0 0 0 0 7\n', '3 3 0\n', '4 4 2\n0 0 3 3 1\n1 1 2 2 2\n', '2 3 1\n0 1 1 2 4\n'] })

t({ lv: 382, concept: 'データ構造: セグメント木の区間最大', title: '更新つき区間最大 (セグメント木)', tags: ['データ構造'], io: '1行目に n q、2行目に n 個の値、続く q 行に "upd i x" または "max l r" が与えられます。', ask: 'すべての "max" の結果の合計を出力してください。', h1: '親が子の max を持つセグメント木。', h2: '更新は葉から、クエリは区間を分割して max を集める。', ref: 'n,q=map(int,input().split())\na=list(map(int,input().split()))\nsize=1\nwhile size<n:\n    size*=2\nNEG=-(10**18)\ntree=[NEG]*(2*size)\nfor i in range(n):\n    tree[size+i]=a[i]\nfor i in range(size-1,0,-1):\n    tree[i]=max(tree[2*i],tree[2*i+1])\ndef update(pos,val):\n    pos+=size\n    tree[pos]=val\n    pos//=2\n    while pos>=1:\n        tree[pos]=max(tree[2*pos],tree[2*pos+1])\n        pos//=2\ndef query(l,r):\n    l+=size\n    r+=size+1\n    res=NEG\n    while l<r:\n        if l&1:\n            res=max(res,tree[l])\n            l+=1\n        if r&1:\n            r-=1\n            res=max(res,tree[r])\n        l//=2\n        r//=2\n    return res\ntotal=0\nfor _ in range(q):\n    op=input().split()\n    if op[0]=="upd":\n        update(int(op[1]),int(op[2]))\n    else:\n        total+=query(int(op[1]),int(op[2]))\nprint(total)', tip: '区間最小と同じ骨格で、集約を max に差し替えるだけ。', ins: ['5 3\n5 2 8 1 9\nmax 0 4\nupd 3 10\nmax 1 3\n', '3 2\n3 1 2\nmax 0 2\nmax 0 0\n', '1 1\n7\nmax 0 0\n', '4 3\n4 3 2 1\nupd 0 100\nmax 0 1\nmax 2 3\n', '5 1\n1 2 3 4 5\nmax 1 3\n', '4 2\n10 20 30 40\nupd 2 5\nmax 0 3\n'] })

t({ lv: 383, concept: 'ヒープ: 複数列のマージ', title: '複数の昇順列をマージ', tags: ['heapq'], io: '1行目に列の本数 k、続く k 行に各列 (先頭に長さ、続けて昇順の値) が与えられます。', ask: '全要素を昇順にマージした列を空白区切りで出力してください。', h1: '各列の先頭をヒープに入れる。', h2: '最小を取り出し、その列の次を補充。', ref: 'import heapq\nk=int(input())\nlists=[]\npq=[]\nfor idx in range(k):\n    row=list(map(int,input().split()))\n    cnt=row[0]\n    arr=row[1:1+cnt]\n    lists.append(arr)\n    if arr:\n        heapq.heappush(pq,(arr[0],idx,0))\nres=[]\nwhile pq:\n    val,li,pos=heapq.heappop(pq)\n    res.append(val)\n    if pos+1<len(lists[li]):\n        heapq.heappush(pq,(lists[li][pos+1],li,pos+1))\nprint(*res)', tip: 'k本のマージはヒープで O(N log k)。外部ソートの基本でもある。', ins: ['2\n3 1 3 5\n2 2 4\n', '3\n1 1\n1 2\n1 3\n', '1\n3 5 6 7\n', '2\n0\n2 1 2\n', '2\n2 1 1\n2 1 1\n', '3\n2 1 4\n2 2 5\n2 3 6\n'] })

t({ lv: 384, concept: 'DP: 最長の山型部分配列', title: '最長の山型 (増加して減少) 区間', tags: ['dp'], io: '整数列が1行で与えられます。', ask: '厳密に増加してから厳密に減少する連続部分配列 (山型) の最大の長さを出力してください (山が無ければ0)。', h1: '各「ピーク」から左右に広げる。', h2: '増加側と減少側の両方が1以上必要。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nbest=0\ni=1\nwhile i<n-1:\n    if a[i-1]<a[i]>a[i+1]:\n        l=i-1\n        r=i+1\n        while l>0 and a[l-1]<a[l]:\n            l-=1\n        while r<n-1 and a[r+1]<a[r]:\n            r+=1\n        if r-l+1>best:\n            best=r-l+1\n        i=r\n    else:\n        i+=1\nprint(best)', tip: 'ピークを見つけてから両側に伸ばすと各要素を高々2回しか見ない。', ins: ['2 1 4 7 3 2 5\n', '2 2 2\n', '1 2 3 4\n', '0 1 0\n', '5\n', '1 3 2 1 4 5 2\n'] })

t({ lv: 385, concept: 'DP: 正規表現一致(.と*)', title: 'ドットとアスタリスクの一致判定', tags: ['dp', '文字列'], io: '1行目に文字列 s、2行目にパターン p が与えられます。p の . は任意の1文字、* は直前の文字の0回以上の繰り返しを表します。', ask: 's 全体が p に一致するなら yes、しなければ no を出力してください。', h1: 'dp[i][j]=s の前 i 文字と p の前 j 文字が一致するか。', h2: '* は「0回 (2つ前)」か「1回以上 (直前と一致なら上に伸ばす)」。', ref: 's=input()\np=input()\nm,n=len(s),len(p)\ndp=[[False]*(n+1) for _ in range(m+1)]\ndp[0][0]=True\nfor j in range(1,n+1):\n    if p[j-1]=="*" and j>=2:\n        dp[0][j]=dp[0][j-2]\nfor i in range(1,m+1):\n    for j in range(1,n+1):\n        if p[j-1]=="*":\n            dp[i][j]=dp[i][j-2]\n            if p[j-2]=="." or p[j-2]==s[i-1]:\n                dp[i][j]=dp[i][j] or dp[i-1][j]\n        elif p[j-1]=="." or p[j-1]==s[i-1]:\n            dp[i][j]=dp[i-1][j-1]\nprint("yes" if dp[m][n] else "no")', tip: '* は「直前文字とのセット」で扱う。0回と1回以上の2分岐がポイント。', ins: ['aa\na*\n', 'ab\n.*\n', 'aab\nc*a*b\n', 'mississippi\nmis*is*p*.\n', 'abc\nabc\n', 'a\nab*\n'] })

t({ lv: 386, concept: 'グラフ: 強連結成分の個数', title: '強連結成分の数', tags: ['グラフ'], io: '1行目に n m、続く m 行に有向辺 u v が与えられます。', ask: '強連結成分 (互いに行き来できる頂点の極大集合) の個数を出力してください。', h1: '帰りがけ順を求め、逆グラフを順に探索 (Kosaraju法)。', h2: '逆グラフでの各探索木が1つの強連結成分。', ref: 'n,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nrg=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    rg[v].append(u)\nvisited=[False]*(n+1)\norder=[]\nfor s in range(1,n+1):\n    if not visited[s]:\n        stack=[(s,0)]\n        visited[s]=True\n        while stack:\n            node,idx=stack.pop()\n            if idx<len(g[node]):\n                stack.append((node,idx+1))\n                nx=g[node][idx]\n                if not visited[nx]:\n                    visited[nx]=True\n                    stack.append((nx,0))\n            else:\n                order.append(node)\ncomp=[0]*(n+1)\nc=0\nfor s in reversed(order):\n    if comp[s]==0:\n        c+=1\n        stack=[s]\n        comp[s]=c\n        while stack:\n            x=stack.pop()\n            for y in rg[x]:\n                if comp[y]==0:\n                    comp[y]=c\n                    stack.append(y)\nprint(c)', tip: 'Kosaraju は2回のDFS。帰りがけ順の逆で逆グラフを塗ると成分が出る。', ins: ['3 3\n1 2\n2 3\n3 1\n', '3 2\n1 2\n2 3\n', '5 5\n1 2\n2 3\n3 1\n4 5\n5 4\n', '1 0\n', '4 4\n1 2\n2 1\n3 4\n4 3\n', '6 7\n1 2\n2 3\n3 1\n3 4\n4 5\n5 6\n6 4\n'] })

t({ lv: 387, concept: '数論: 線形篩の最小素因数', title: '最小素因数の総和', tags: ['数論'], io: '整数 n (>=2) が1行で与えられます。', ask: '2 から n までの各整数について最小の素因数を求め、その総和を出力してください。', h1: '篩で各合成数に最小素因数を記録。', h2: 'spf[i]==i のままなら素数。', ref: 'n=int(input())\nspf=list(range(n+1))\ni=2\nwhile i*i<=n:\n    if spf[i]==i:\n        for j in range(i*i,n+1,i):\n            if spf[j]==j:\n                spf[j]=i\n    i+=1\nprint(sum(spf[2:n+1]))', tip: '最小素因数テーブルがあれば任意の数を O(log) で素因数分解できる。', ins: ['10\n', '2\n', '3\n', '5\n', '20\n', '100\n'] })

t({ lv: 388, concept: 'DP: 金額の作り方 mod', title: '金額の作り方の総数を法で', tags: ['dp'], io: '1行目に金額 X、硬貨の種類数 n、法 MOD、2行目に n 種類の額面が与えられます。各額面は何枚でも使えます。', ask: 'X を作る組合せの総数を MOD で割った余りを出力してください (順序は区別しません)。', h1: '額面を外ループにして順不同で数える。', h2: '各加算で MOD を取る。', ref: 'x,n,MOD=map(int,input().split())\ncoins=list(map(int,input().split()))\ndp=[0]*(x+1)\ndp[0]=1\nfor c in coins:\n    for v in range(c,x+1):\n        dp[v]=(dp[v]+dp[v-c])%MOD\nprint(dp[x]%MOD)', tip: '数え上げDPは大きくなりがちなので、各ステップで mod を取るのが定石。', ins: ['5 3 1000000007\n1 2 5\n', '100 2 1000\n1 2\n', '0 1 7\n3\n', '10 2 3\n2 5\n', '50 4 100\n1 5 10 25\n', '4 1 1000\n2\n'] })

t({ lv: 389, concept: 'bitDP: トポロジカル順序の数', title: 'トポロジカル順序の総数', tags: ['bitDP', 'グラフ'], io: '1行目に n m、続く m 行に有向辺 u v (閉路なし) が与えられます。', ask: '可能なトポロジカル順序の総数を出力してください。', h1: '「すでに並べた頂点集合」をビットで表す。', h2: '前提が全て集合内にある頂点だけ次に置ける。', ref: 'n,m=map(int,input().split())\nneed=[0]*n\nfor _ in range(m):\n    u,v=map(int,input().split())\n    need[v-1]|=(1<<(u-1))\ndp=[0]*(1<<n)\ndp[0]=1\nfor mask in range(1<<n):\n    if dp[mask]==0:\n        continue\n    for v in range(n):\n        if not (mask>>v)&1 and (need[v]&mask)==need[v]:\n            dp[mask|(1<<v)]+=dp[mask]\nprint(dp[(1<<n)-1])', tip: '「並べた集合」を状態にすると順序の数え上げが 2^n のDPになる。', ins: ['3 2\n1 2\n2 3\n', '3 0\n', '3 1\n1 2\n', '4 3\n1 2\n1 3\n1 4\n', '2 1\n1 2\n', '4 4\n1 2\n1 3\n2 4\n3 4\n'] })

t({ lv: 390, concept: 'グラフ: 最大流', title: 's-t間の最大流', tags: ['グラフ', 'BFS'], io: '1行目に n m s t、続く m 行に u v cap (有向辺と容量) が与えられます。', ask: 's から t への最大流量を出力してください。', h1: '残余グラフ上で増加道をBFSで探す (エドモンズ・カープ)。', h2: '増加道の最小容量だけ流し、逆辺に戻せる量を足す。', ref: 'from collections import deque\nfirst=input().split()\nn=int(first[0])\nm=int(first[1])\ns=int(first[2])\nt=int(first[3])\ncap=[[0]*(n+1) for _ in range(n+1)]\nadj=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v,c=map(int,input().split())\n    if cap[u][v]==0 and cap[v][u]==0:\n        adj[u].append(v)\n        adj[v].append(u)\n    cap[u][v]+=c\nflow=0\nwhile True:\n    par=[-1]*(n+1)\n    par[s]=s\n    dq=deque([s])\n    while dq:\n        x=dq.popleft()\n        for y in adj[x]:\n            if par[y]==-1 and cap[x][y]>0:\n                par[y]=x\n                dq.append(y)\n    if par[t]==-1:\n        break\n    aug=float("inf")\n    v=t\n    while v!=s:\n        u=par[v]\n        if cap[u][v]<aug:\n            aug=cap[u][v]\n        v=u\n    v=t\n    while v!=s:\n        u=par[v]\n        cap[u][v]-=aug\n        cap[v][u]+=aug\n        v=u\n    flow+=aug\nprint(flow)', tip: '最大流は最小カットに等しい (最大流最小カット定理)。マッチングなどの土台。', ins: ['4 5 1 4\n1 2 3\n1 3 2\n2 3 1\n2 4 2\n3 4 3\n', '2 1 1 2\n1 2 10\n', '3 2 1 3\n1 2 5\n2 3 3\n', '4 4 1 4\n1 2 100\n2 4 1\n1 3 100\n3 4 1\n', '2 0 1 2\n', '3 3 1 3\n1 2 2\n1 3 2\n2 3 2\n'] })

export const CATALOG = TASKS
