// 生成タスク 第31波：lv331〜360。
// 上級の踏み段。Bellman-Ford・Floyd-Warshall・2D Kadane・中置式評価・区間DP(石合体)・
// ヒストグラム最大長方形・重み付き編集距離・流れる中央値系の周辺など。
// lv500未満なので再帰なし(反復)。重複なし・決定的・採点一意。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 331, concept: '数論: 三角数か判定', title: '三角数かどうか', tags: ['数論'], io: '整数 n (>=1) が1行で与えられます。', ask: 'n が三角数 (1+2+…+k の形) であれば yes、なければ no を出力してください。', h1: '8n+1 が平方数なら三角数。', h2: 'math.isqrt で平方判定。', ref: 'import math\nn=int(input())\nx=8*n+1\nr=math.isqrt(x)\nprint("yes" if r*r==x else "no")', tip: '三角数 T_k=k(k+1)/2 を逆に解くと 8n+1 の平方性に帰着する。', ins: ['6\n', '10\n', '5\n', '1\n', '15\n', '7\n'] })

t({ lv: 332, concept: '数論: k進法での桁和', title: 'k進法に直したときの桁和', tags: ['数論'], io: 'n k が空白区切りで与えられます (n>=0, k>=2)。', ask: 'n を k 進法で表したときの各桁の和を出力してください。', h1: 'n%k が最下位の桁。', h2: 'n//=k を繰り返す。', ref: 'n,k=map(int,input().split())\nif n==0:\n    print(0)\nelse:\n    s=0\n    while n>0:\n        s+=n%k\n        n//=k\n    print(s)', tip: '基数変換は「余りを取って割る」を繰り返すだけ。', ins: ['255 16\n', '10 2\n', '0 5\n', '100 10\n', '7 2\n', '255 2\n'] })

t({ lv: 333, concept: '数論: フィボナッチ数か判定', title: 'フィボナッチ数かどうか', tags: ['数論'], io: '整数 n (>=0) が1行で与えられます。', ask: 'n がフィボナッチ数列 (0,1,1,2,3,5,…) に現れる数なら yes、なければ no を出力してください。', h1: '5n²+4 か 5n²−4 のどちらかが平方数ならフィボナッチ数。', h2: 'math.isqrt で平方判定。', ref: 'import math\nn=int(input())\ndef is_sq(x):\n    if x<0:\n        return False\n    r=math.isqrt(x)\n    return r*r==x\nprint("yes" if is_sq(5*n*n+4) or is_sq(5*n*n-4) else "no")', tip: 'フィボナッチ数には「5n²±4 が平方数」という美しい判定式がある。', ins: ['8\n', '5\n', '4\n', '13\n', '1\n', '7\n'] })

t({ lv: 334, concept: '数論: 自己同型数か', title: '自己同型数かどうか', tags: ['数論'], io: '整数 n (>=0) が1行で与えられます。', ask: 'n の2乗が n で終わる (例: 25²=625) なら yes、なければ no を出力してください。', h1: '文字列化して末尾を比較。', h2: 'str(n*n).endswith(str(n))。', ref: 'n=int(input())\nsq=str(n*n)\nprint("yes" if sq.endswith(str(n)) else "no")', tip: '数を文字列として末尾比較すると桁演算より簡潔。', ins: ['5\n', '6\n', '25\n', '7\n', '76\n', '1\n'] })

t({ lv: 335, concept: '数論: N以下で約数最多の数', title: 'N以下で約数が最も多い数の約数個数', tags: ['数論'], io: '整数 N (>=1) が1行で与えられます。', ask: '1 以上 N 以下の整数のうち、約数の個数が最大となるものの約数の個数を出力してください。', h1: '各数の約数個数を平方根まで数える。', h2: 'その最大を取る。', ref: 'n=int(input())\nbest=0\nfor x in range(1,n+1):\n    c=0\n    d=1\n    while d*d<=x:\n        if x%d==0:\n            c+=1 if d==x//d else 2\n        d+=1\n    if c>best:\n        best=c\nprint(best)', tip: '約数が多い数 (高度合成数) は素因数を小さい順にバランスよく持つ。', ins: ['10\n', '1\n', '12\n', '20\n', '100\n', '6\n'] })

t({ lv: 336, concept: 'ソート: k番目に小さい値', title: 'k番目に小さい値', tags: ['ソート'], io: '1行目に k、2行目に整数列が与えられます。', ask: '小さい方から k 番目 (1始まり) の値を出力してください。', h1: 'ソートする。', h2: 'a[k-1] が答え。', ref: 'k=int(input())\na=sorted(map(int,input().split()))\nprint(a[k-1])', tip: '順位統計はソートで即解ける (大規模ではクイックセレクトで O(n))。', ins: ['2\n3 1 2\n', '1\n5 4 3\n', '3\n1 1 1\n', '4\n10 20 30 40 50\n', '1\n7\n', '5\n5 4 3 2 1\n'] })

t({ lv: 337, concept: '二点法: 目標に最も近い3数の和', title: '目標に最も近い3要素の和', tags: ['二点法', 'ソート'], io: '1行目に目標値 target、2行目に整数列 (3個以上) が与えられます。', ask: '3要素の和のうち target に最も近いものの値を出力してください (同じ近さが複数ある場合はどれでも一意になる入力とします)。', h1: 'ソートして1要素を固定。', h2: '残りを二点法で寄せ、和と target の差を更新。', ref: 'target=int(input())\na=sorted(map(int,input().split()))\nn=len(a)\nbest=a[0]+a[1]+a[2]\nfor i in range(n):\n    l=i+1\n    r=n-1\n    while l<r:\n        s=a[i]+a[l]+a[r]\n        if abs(s-target)<abs(best-target):\n            best=s\n        if s<target:\n            l+=1\n        elif s>target:\n            r-=1\n        else:\n            l+=1\n            r-=1\nprint(best)', tip: '「最も近い」も二点法で、差を縮める方向にポインタを動かす。', ins: ['1\n-1 2 1 -4\n', '0\n0 0 0\n', '10\n1 2 3 4\n', '100\n1 2 3\n', '-5\n-1 -2 -3 -4\n', '5\n1 1 1 1 1\n'] })

t({ lv: 338, concept: '累積和: 左右の和が等しい位置の数', title: '左右の和が釣り合う位置の数', tags: ['累積和'], io: '整数列が1行で与えられます。', ask: 'ある位置 i について「i より左の和」と「i より右の和」が等しくなる i の個数を出力してください。', h1: '総和を先に求める。', h2: '左から走査し left==total-left-a[i] を判定。', ref: 'a=list(map(int,input().split()))\ntotal=sum(a)\nleft=0\ncnt=0\nfor i in range(len(a)):\n    if left==total-left-a[i]:\n        cnt+=1\n    left+=a[i]\nprint(cnt)', tip: '右の和は total − left − 自分、と一発で出せる。', ins: ['1 7 3 6 5 6\n', '1 2 3\n', '2 1 -1\n', '0 0 0\n', '-1 -1 0 1 1\n', '5\n'] })

t({ lv: 339, concept: '累積和: 最大部分矩形和', title: '部分矩形の和の最大値', tags: ['累積和', 'dp'], io: '1行目に H W、続く H 行に W 個の整数 (負を含む) が与えられます。', ask: '空でない部分矩形の要素和の最大値を出力してください。', h1: '上下の行を固定し、列ごとの和を1次元配列に潰す。', h2: 'その1次元で最大部分和 (カダネ) を取る。', ref: 'h,w=map(int,input().split())\ng=[list(map(int,input().split())) for _ in range(h)]\nbest=g[0][0]\nfor top in range(h):\n    col=[0]*w\n    for bot in range(top,h):\n        for j in range(w):\n            col[j]+=g[bot][j]\n        cur=col[0]\n        m=col[0]\n        for j in range(1,w):\n            cur=max(col[j],cur+col[j])\n            if cur>m:\n                m=cur\n        if m>best:\n            best=m\nprint(best)', tip: '行の組を固定して列方向に潰すと、2次元問題が1次元カダネに落ちる。', ins: ['2 2\n1 2\n3 4\n', '1 1\n-5\n', '2 3\n1 -2 3\n-4 5 -6\n', '3 3\n-1 -2 -3\n-4 -5 -6\n-7 -8 -9\n', '2 2\n-1 2\n3 -4\n', '1 4\n1 -2 3 4\n'] })

t({ lv: 340, concept: 'スタック: 中置式の計算', title: '四則 (＋−×) と括弧の式を計算', tags: ['スタック'], io: '空白区切りのトークンからなる式が1行で与えられます (整数、+ - *、( ) を含む)。', ask: '式の値を計算して出力してください。', h1: '値スタックと演算子スタックを使う。', h2: '優先度の高い演算を先に適用し、) で ( まで畳む。', ref: 'expr=input().split()\nvals=[]\nops=[]\ndef prec(op):\n    return 2 if op=="*" else 1\ndef apply():\n    b=vals.pop()\n    a=vals.pop()\n    op=ops.pop()\n    if op=="+":\n        vals.append(a+b)\n    elif op=="-":\n        vals.append(a-b)\n    else:\n        vals.append(a*b)\nfor tk in expr:\n    if tk=="(":\n        ops.append(tk)\n    elif tk==")":\n        while ops[-1]!="(":\n            apply()\n        ops.pop()\n    elif tk in ("+","-","*"):\n        while ops and ops[-1]!="(" and prec(ops[-1])>=prec(tk):\n            apply()\n        ops.append(tk)\n    else:\n        vals.append(int(tk))\nwhile ops:\n    apply()\nprint(vals[0])', tip: '2本のスタックで優先順位つき式を評価する操車場アルゴリズム。', ins: ['2 + 3 * 4\n', '( 2 + 3 ) * 4\n', '10 - 2 - 3\n', '5\n', '2 * 3 + 4 * 5\n', '( 1 + 2 ) * ( 3 + 4 )\n'] })

t({ lv: 341, concept: '文字列: 重複しない文字の最長部分文字列', title: '同じ文字を含まない最長部分文字列', tags: ['スライディングウィンドウ', '文字列'], io: '文字列が1行で与えられます。', ask: '同じ文字を2回含まない連続部分文字列の最大の長さを出力してください。', h1: '各文字の最後の位置を辞書で持つ。', h2: '重複したら左端をその次へ飛ばす。', ref: 's=input()\nseen={}\nl=0\nbest=0\nfor r in range(len(s)):\n    ch=s[r]\n    if ch in seen and seen[ch]>=l:\n        l=seen[ch]+1\n    seen[ch]=r\n    if r-l+1>best:\n        best=r-l+1\nprint(best)', tip: '左端を「飛ばす」尺取りは重複系ウィンドウの定石。', ins: ['abcabcbb\n', 'bbbbb\n', 'pwwkew\n', '\n', 'abcdef\n', 'abba\n'] })

t({ lv: 342, concept: '文字列: 長さkの辞書順最小部分列', title: 'k文字選ぶ辞書順最小の部分列', tags: ['文字列', 'スタック'], io: '1行目に文字列 s と整数 k が空白区切りで与えられます (k<=|s|)。', ask: 's から順序を保って k 文字選んだ部分列のうち、辞書順で最小のものを出力してください。', h1: 'スタックに積み、後ろに十分残るなら大きい文字を捨てる。', h2: 'スタックの長さが k を超えないように積む。', ref: 'line=input().split()\ns=line[0]\nk=int(line[1])\nst=[]\nn=len(s)\nfor i in range(n):\n    ch=s[i]\n    while st and st[-1]>ch and len(st)-1+(n-i)>=k:\n        st.pop()\n    if len(st)<k:\n        st.append(ch)\nprint("".join(st))', tip: '「後ろに残る文字数」で捨ててよいか判断するのが単調スタック貪欲の肝。', ins: ['bcabc 3\n', 'cba 2\n', 'abc 2\n', 'edcba 1\n', 'bdca 2\n', 'xyz 3\n'] })

t({ lv: 343, concept: 'DP: 円環の最大部分和', title: '円環状に並んだ列の最大部分和', tags: ['dp'], io: '整数列 (円環状に繋がっているとみなす) が1行で与えられます。', ask: '連続する1個以上の要素 (末尾と先頭も連続) の和の最大値を出力してください。', h1: '通常の最大部分和と、全体和−最小部分和の大きい方。', h2: '全要素が負のときは通常の最大部分和を使う。', ref: 'a=list(map(int,input().split()))\ndef kadane_max(arr):\n    cur=best=arr[0]\n    for x in arr[1:]:\n        cur=max(x,cur+x)\n        if cur>best:\n            best=cur\n    return best\nmax_lin=kadane_max(a)\nif max_lin<0:\n    print(max_lin)\nelse:\n    total=sum(a)\n    cur=best=a[0]\n    for x in a[1:]:\n        cur=min(x,cur+x)\n        if cur<best:\n            best=cur\n    print(max(max_lin,total-best))', tip: '円環の最大和は「全体和 − 最小部分和」を併用する発想転換が要点。', ins: ['1 -2 3 -2\n', '5 -3 5\n', '-3 -2 -3\n', '3 -1 2 -1\n', '5\n', '-2 4 -5 4 -5 9 4\n'] })

t({ lv: 344, concept: 'DP: 2分割の差の最小', title: '2グループに分けた和の差の最小', tags: ['dp'], io: '正整数列が1行で与えられます。', ask: '全要素を2グループに分けるとき、2グループの和の差の絶対値の最小値を出力してください。', h1: '部分集合で作れる和の集合を求める (部分和DP)。', h2: '総和の半分に最も近い和を探す。', ref: 'a=list(map(int,input().split()))\ntotal=sum(a)\ndp=[False]*(total+1)\ndp[0]=True\nfor x in a:\n    for v in range(total,x-1,-1):\n        if dp[v-x]:\n            dp[v]=True\nbest=total\nfor s in range(total+1):\n    if dp[s]:\n        diff=abs(total-2*s)\n        if diff<best:\n            best=diff\nprint(best)', tip: '等和分割の最適化版。半分に最も近い部分和を探す。', ins: ['1 2 3 4\n', '1 2 3\n', '1 6 11 5\n', '5\n', '8 7 5 3\n', '2 2 2\n'] })

t({ lv: 345, concept: 'DP: 作れる金額の種類数', title: '硬貨で作れる金額の種類数', tags: ['dp'], io: '1行目に上限 X と硬貨の種類数 n、2行目に n 種類の額面が与えられます。各額面は何枚でも使えます。', ask: '1 以上 X 以下のうち、硬貨の組合せで作れる金額の種類数を出力してください。', h1: '到達可能性DP ok[v]。', h2: '1..X で True の個数を数える。', ref: 'x,n=map(int,input().split())\ncoins=list(map(int,input().split()))\nok=[False]*(x+1)\nok[0]=True\nfor c in coins:\n    for v in range(c,x+1):\n        if ok[v-c]:\n            ok[v]=True\nprint(sum(1 for v in range(1,x+1) if ok[v]))', tip: '「何通り作れるか」ではなく「どの金額が作れるか」を bool で追う。', ins: ['10 2\n2 5\n', '5 1\n3\n', '6 2\n1 2\n', '0 1\n5\n', '7 2\n3 5\n', '4 1\n1\n'] })

t({ lv: 346, concept: 'DP: 0/1行列の最大長方形', title: '1だけで作る最大の長方形の面積', tags: ['dp', 'スタック'], io: '1行目に H W、続く H 行に 0/1 のグリッドが与えられます。', ask: '1 だけからなる最大の長方形の面積を出力してください。', h1: '各行を底とするヒストグラムの高さを更新。', h2: '各ヒストグラムの最大長方形をスタックで求める。', ref: 'h,w=map(int,input().split())\ng=[input().split() for _ in range(h)]\nheight=[0]*w\nbest=0\nfor i in range(h):\n    for j in range(w):\n        if g[i][j]=="1":\n            height[j]+=1\n        else:\n            height[j]=0\n    st=[]\n    for j in range(w+1):\n        cur=height[j] if j<w else 0\n        while st and height[st[-1]]>=cur:\n            hh=height[st.pop()]\n            left=st[-1] if st else -1\n            area=hh*(j-left-1)\n            if area>best:\n                best=area\n        st.append(j)\nprint(best)', tip: '行ごとにヒストグラム化＋最大長方形で、2次元問題を1次元に分解できる。', ins: ['2 2\n1 1\n1 1\n', '3 4\n1 0 1 1\n1 0 1 1\n1 1 1 1\n', '1 4\n1 1 0 1\n', '2 2\n0 0\n0 0\n', '3 3\n1 1 1\n1 1 1\n1 1 1\n', '2 3\n1 0 1\n1 1 1\n'] })

t({ lv: 347, concept: '区間DP: 石の合体の最小コスト', title: '隣接する山を合体する最小コスト', tags: ['区間DP', 'dp'], io: '正整数列が1行で与えられます (各山の石の数)。隣り合う2つの山を合体でき、コストは合体後の石数です。', ask: '全部を1つの山にするまでの合計コストの最小値を出力してください。', h1: '区間 [i,j] を1山にする最小コストをDP。', h2: 'dp[i][j]=min over k (dp[i][k]+dp[k+1][j]) + (区間の総和)。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nif n<=1:\n    print(0)\nelse:\n    pre=[0]*(n+1)\n    for i in range(n):\n        pre[i+1]=pre[i]+a[i]\n    INF=float("inf")\n    dp=[[0]*n for _ in range(n)]\n    for length in range(2,n+1):\n        for i in range(n-length+1):\n            j=i+length-1\n            best=INF\n            for k in range(i,j):\n                c=dp[i][k]+dp[k+1][j]\n                if c<best:\n                    best=c\n            dp[i][j]=best+pre[j+1]-pre[i]\n    print(dp[0][n-1])', tip: '区間の総和は合体の順序に依らず必ず加算される＝分割点だけ最適化する。', ins: ['1 2 3\n', '4 1 1 4\n', '1\n', '3 4 3\n', '5 5\n', '1 1 1 1\n'] })

t({ lv: 348, concept: 'グラフ: 負辺ありの最短距離', title: '負の重みを含む最短距離', tags: ['グラフ', 'dp'], io: '1行目に n m、続く m 行に有向辺 u v w (w は負も可)、最後の行に s t が与えられます (負閉路はないものとします)。', ask: 's から t への最短距離を出力してください。到達不能なら INF を出力してください。', h1: '全辺の緩和を n-1 回繰り返す (ベルマン・フォード)。', h2: 'dist[v]=min(dist[v], dist[u]+w)。', ref: 'n,m=map(int,input().split())\nedges=[]\nfor _ in range(m):\n    u,v,w=map(int,input().split())\n    edges.append((u,v,w))\ns,t=map(int,input().split())\nINF=float("inf")\ndist=[INF]*(n+1)\ndist[s]=0\nfor _ in range(n-1):\n    for u,v,w in edges:\n        if dist[u]<INF and dist[u]+w<dist[v]:\n            dist[v]=dist[u]+w\nprint(dist[t] if dist[t]<INF else "INF")', tip: '負の辺があるとダイクストラは使えない。緩和を繰り返すのが基本。', ins: ['3 3\n1 2 5\n2 3 -2\n1 3 4\n1 3\n', '2 1\n1 2 -3\n1 2\n', '3 0\n1 3\n', '1 0\n1 1\n', '4 4\n1 2 1\n2 3 1\n3 4 1\n1 4 10\n1 4\n', '3 2\n1 2 -1\n2 3 -1\n1 3\n'] })

t({ lv: 349, concept: 'グラフ: 全点対最短距離の最大', title: '全頂点対の最短距離の最大', tags: ['グラフ', 'dp'], io: '1行目に n m、続く m 行に無向辺 u v w (w>=0) が与えられます。', ask: 'すべての頂点対の最短距離のうち、有限なものの最大値を出力してください (辺が無い等で全て孤立なら0)。', h1: '全点対最短距離を求める (ワーシャル・フロイド)。', h2: '経由点 k を全部試して距離を更新。', ref: 'n,m=map(int,input().split())\nINF=float("inf")\ndist=[[INF]*(n+1) for _ in range(n+1)]\nfor i in range(1,n+1):\n    dist[i][i]=0\nfor _ in range(m):\n    u,v,w=map(int,input().split())\n    if w<dist[u][v]:\n        dist[u][v]=w\n        dist[v][u]=w\nfor k in range(1,n+1):\n    for i in range(1,n+1):\n        for j in range(1,n+1):\n            if dist[i][k]+dist[k][j]<dist[i][j]:\n                dist[i][j]=dist[i][k]+dist[k][j]\nbest=0\nfor i in range(1,n+1):\n    for j in range(1,n+1):\n        if dist[i][j]<INF and dist[i][j]>best:\n            best=dist[i][j]\nprint(best)', tip: '経由点を外ループにするのがワーシャル・フロイドの肝。', ins: ['3 3\n1 2 1\n2 3 1\n1 3 5\n', '2 1\n1 2 7\n', '4 3\n1 2 1\n2 3 1\n3 4 1\n', '3 0\n', '4 4\n1 2 2\n2 3 2\n3 4 2\n1 4 1\n', '1 0\n'] })

t({ lv: 350, concept: 'グラフ: 独立サイクルの数', title: '独立な閉路の数 (サイクル空間の次元)', tags: ['データ構造', 'グラフ'], io: '1行目に n m、続く m 行に無向辺 u v が与えられます。', ask: 'グラフのサイクル空間の次元 (= 辺数 − 頂点数 + 連結成分数) を出力してください。', h1: '連結成分数を Union-Find で求める。', h2: 'm - n + (成分数) が独立サイクルの数。', ref: 'n,m=map(int,input().split())\npar=list(range(n+1))\ndef find(x):\n    while par[x]!=x:\n        par[x]=par[par[x]]\n        x=par[x]\n    return x\nfor _ in range(m):\n    u,v=map(int,input().split())\n    ru=find(u)\n    rv=find(v)\n    if ru!=rv:\n        par[ru]=rv\ncomps=len(set(find(i) for i in range(1,n+1)))\nprint(m-n+comps)', tip: '全域森の辺は n−成分数 本。残りの辺の数だけ独立な閉路ができる。', ins: ['3 3\n1 2\n2 3\n1 3\n', '4 2\n1 2\n3 4\n', '4 4\n1 2\n2 3\n3 4\n4 1\n', '5 6\n1 2\n2 3\n3 1\n3 4\n4 5\n5 3\n', '1 0\n', '6 7\n1 2\n2 3\n3 1\n1 3\n4 5\n5 6\n4 6\n'] })

t({ lv: 351, concept: 'DP: 偶奇が交互の最長連続部分列', title: '偶数奇数が交互に並ぶ最長区間', tags: ['dp'], io: '整数列が1行で与えられます。', ask: '隣り合う要素の偶奇が必ず異なる連続部分配列の最大の長さを出力してください。', h1: '偶奇が前と違えば伸ばす。', h2: '同じなら1に戻す。', ref: 'a=list(map(int,input().split()))\nbest=0\ncur=0\nprev=-1\nfor x in a:\n    p=x%2\n    if cur==0 or p!=prev:\n        cur+=1\n    else:\n        cur=1\n    prev=p\n    if cur>best:\n        best=cur\nprint(best)', tip: '直前の状態 (偶奇) だけ覚えれば1パスで判定できる。', ins: ['1 2 3 4\n', '2 4 6\n', '1 3 2 4\n', '5\n', '1 2 2 3\n', '2 1 2 1 2\n'] })

t({ lv: 352, concept: 'スタック: 括弧を有効にする最小削除', title: '正しい括弧列にする最小削除数', tags: ['スタック', '文字列'], io: '( と ) とその他の文字を含む文字列が1行で与えられます。', ask: '正しく対応した括弧列にするために削除すべき括弧の最小数を出力してください。', h1: '開き括弧の数を数えながら走査。', h2: '対応しない ) と、最後に余った ( を数える。', ref: 's=input()\nopen_cnt=0\nremove=0\nfor ch in s:\n    if ch=="(":\n        open_cnt+=1\n    elif ch==")":\n        if open_cnt>0:\n            open_cnt-=1\n        else:\n            remove+=1\nprint(remove+open_cnt)', tip: '対応しない ) はその場で、余った ( は最後に数えるのがコツ。', ins: ['())\n', '(((\n', '()\n', ')(\n', '(()(\n', '\n'] })

t({ lv: 353, concept: '文字列: 最初の一意な文字の位置', title: '1度だけ現れる最初の文字の位置', tags: ['文字列', 'ハッシュ'], io: '文字列が1行で与えられます。', ask: 'ちょうど1回だけ出現する文字のうち、最も左にあるものの位置 (0始まり) を出力してください。無ければ -1 を出力してください。', h1: 'まず各文字の出現回数を数える。', h2: '前から見て出現回数1の最初を返す。', ref: 'from collections import Counter\ns=input()\ncnt=Counter(s)\nans=-1\nfor i,ch in enumerate(s):\n    if cnt[ch]==1:\n        ans=i\n        break\nprint(ans)', tip: '頻度を先に集計しておけば1パスで一意文字が見つかる。', ins: ['leetcode\n', 'aabb\n', 'abca\n', 'z\n', 'aabbc\n', 'swiss\n'] })

t({ lv: 354, concept: 'BFS: 始点から到達できるマス数', title: '指定した始点から行けるマスの数', tags: ['BFS', 'グリッド'], io: '1行目に H W、続く H 行に 0(道)/1(壁) のグリッド、最後の行に始点 sy sx (0始まり) が与えられます。4方向に移動します。', ask: '始点から到達できる道マスの数を出力してください (始点が壁なら0)。', h1: '始点から幅優先で塗りつぶす。', h2: '訪問したマスの数を数える。', ref: 'from collections import deque\nh,w=map(int,input().split())\ng=[input().split() for _ in range(h)]\nsy,sx=map(int,input().split())\nif g[sy][sx]=="1":\n    print(0)\nelse:\n    seen=[[False]*w for _ in range(h)]\n    seen[sy][sx]=True\n    dq=deque([(sy,sx)])\n    c=0\n    while dq:\n        y,x=dq.popleft()\n        c+=1\n        for dy,dx in ((1,0),(-1,0),(0,1),(0,-1)):\n            ny,nx=y+dy,x+dx\n            if 0<=ny<h and 0<=nx<w and g[ny][nx]=="0" and not seen[ny][nx]:\n                seen[ny][nx]=True\n                dq.append((ny,nx))\n    print(c)', tip: '到達可能領域のサイズは塗りつぶしBFSの訪問数。', ins: ['3 3\n0 0 0\n1 1 0\n0 0 0\n0 0\n', '2 2\n0 1\n1 0\n0 0\n', '1 3\n0 0 0\n0 0\n', '2 2\n1 0\n0 0\n0 0\n', '3 3\n0 0 0\n0 0 0\n0 0 0\n1 1\n', '2 3\n0 1 0\n0 0 0\n0 0\n'] })

t({ lv: 355, concept: '数論: 1からNの約数個数の総和', title: '1〜Nの約数の個数の総和', tags: ['数論'], io: '整数 N (>=1) が1行で与えられます。', ask: '1 から N までの各整数の約数の個数を合計した値を出力してください。', h1: 'i を約数に持つ N 以下の数は N//i 個。', h2: '総和は Σ (N//i)。', ref: 'n=int(input())\ntotal=0\ni=1\nwhile i<=n:\n    total+=n//i\n    i+=1\nprint(total)', tip: '「各数の約数を数える」より「各約数が何回現れるか」を数える方が速い。', ins: ['1\n', '6\n', '10\n', '100\n', '3\n', '5\n'] })

t({ lv: 356, concept: 'DP: 1にする最小操作', title: '1にするための最小操作回数', tags: ['dp'], io: '整数 n (>=1) が1行で与えられます。', ask: '「1を引く」「2で割る (2の倍数のとき)」「3で割る (3の倍数のとき)」のいずれかを繰り返して n を1にする最小操作回数を出力してください。', h1: 'dp[i]=i を1にする最小回数。', h2: 'i-1, i/2, i/3 の中の最小+1。', ref: 'n=int(input())\ndp=[0]*(n+1)\nfor i in range(2,n+1):\n    best=dp[i-1]+1\n    if i%2==0 and dp[i//2]+1<best:\n        best=dp[i//2]+1\n    if i%3==0 and dp[i//3]+1<best:\n        best=dp[i//3]+1\n    dp[i]=best\nprint(dp[n] if n>=1 else 0)', tip: '貪欲では誤る (例: 10)。全状態を埋めるDPが必要。', ins: ['10\n', '1\n', '6\n', '7\n', '2\n', '15\n'] })

t({ lv: 357, concept: '二点法: 和がKのペア数', title: '和がKになるペアの個数', tags: ['ハッシュ'], io: '1行目に n K、2行目に n 個の整数が与えられます。', ask: 'i<j かつ a[i]+a[j]=K となるペアの個数を出力してください (同じ値の重複もそれぞれ数えます)。', h1: '左から走査し、K-x が既に何個現れたかを足す。', h2: '辞書に出現回数を貯める。', ref: 'from collections import defaultdict\nn,k=map(int,input().split())\na=list(map(int,input().split()))\ncnt=defaultdict(int)\nres=0\nfor x in a:\n    res+=cnt[k-x]\n    cnt[x]+=1\nprint(res)', tip: '「右から見て相方が何個あったか」を辞書で数える1パス法。', ins: ['4 5\n1 4 2 3\n', '3 4\n2 2 2\n', '5 10\n1 2 3 4 5\n', '1 5\n5\n', '4 0\n-1 1 -1 1\n', '6 7\n1 6 2 5 3 4\n'] })

t({ lv: 358, concept: 'スタック: k個連続で消す', title: 'k個連続したら消す操作の後の長さ', tags: ['スタック', '文字列'], io: '1行目に文字列 s と整数 k が空白区切りで与えられます。', ask: '同じ文字が k 個連続したら取り除く操作を繰り返せなくなるまで行い、残った文字列の長さを出力してください。', h1: '(文字, 連続数) をスタックで持つ。', h2: '連続数が k に達したら取り除く。', ref: 'line=input().split()\ns=line[0]\nk=int(line[1])\nst=[]\nfor ch in s:\n    if st and st[-1][0]==ch:\n        st[-1][1]+=1\n        if st[-1][1]==k:\n            st.pop()\n    else:\n        st.append([ch,1])\nprint(sum(c for _,c in st))', tip: '連続数をスタックに圧縮して持つと「k個消し」を1パスで処理できる。', ins: ['aaabbbacc 3\n', 'abcd 2\n', 'aabb 2\n', 'aaa 3\n', 'aaabbaa 2\n', 'x 5\n'] })

t({ lv: 359, concept: 'グラフ: 依存タスクの最短完了時間', title: '依存関係つきタスクの最短完了時間', tags: ['トポロジカル', 'dp'], io: '1行目に n m、2行目に n 個の所要時間 (タスク1..n)、続く m 行に依存 a b (a の完了後に b を開始できる、閉路なし) が与えられます。並列実行に制限はありません。', ask: '全タスクを完了できる最短時間を出力してください。', h1: 'finish[v]=v が完了する最早時刻。', h2: 'トポロジカル順に finish[v]=max(前提の finish)+d[v]。', ref: 'from collections import deque\nn,m=map(int,input().split())\nd=list(map(int,input().split()))\ng=[[] for _ in range(n+1)]\nindeg=[0]*(n+1)\nfor _ in range(m):\n    a,b=map(int,input().split())\n    g[a].append(b)\n    indeg[b]+=1\nfinish=[0]*(n+1)\ndq=deque()\nfor i in range(1,n+1):\n    if indeg[i]==0:\n        finish[i]=d[i-1]\n        dq.append(i)\nans=0\nwhile dq:\n    x=dq.popleft()\n    if finish[x]>ans:\n        ans=finish[x]\n    for y in g[x]:\n        if finish[x]+d[y-1]>finish[y]:\n            finish[y]=finish[x]+d[y-1]\n        indeg[y]-=1\n        if indeg[y]==0:\n            dq.append(y)\nprint(ans)', tip: '並列無制限なら完了時刻＝依存パス上の所要時間の最大 (クリティカルパス)。', ins: ['3 2\n3 2 4\n1 2\n2 3\n', '3 0\n1 2 3\n', '1 0\n5\n', '4 3\n1 1 1 1\n1 2\n1 3\n2 4\n', '2 1\n10 5\n1 2\n', '5 4\n2 2 2 2 2\n1 2\n2 3\n3 4\n4 5\n'] })

t({ lv: 360, concept: 'DP: 重み付き編集距離', title: 'コスト指定の編集距離', tags: ['dp', '文字列'], io: '1行目に挿入・削除・置換のコスト3整数、2行目に文字列 a、3行目に文字列 b が与えられます。', ask: 'a を b に変換する最小の総コストを出力してください。', h1: 'dp[i][j]=a の前 i 文字を b の前 j 文字にする最小コスト。', h2: '一致なら据え置き、違えば3操作のコスト最小。', ref: 'ci,cd,cr=map(int,input().split())\na=input()\nb=input()\nm,n=len(a),len(b)\ndp=[[0]*(n+1) for _ in range(m+1)]\nfor i in range(1,m+1):\n    dp[i][0]=i*cd\nfor j in range(1,n+1):\n    dp[0][j]=j*ci\nfor i in range(1,m+1):\n    for j in range(1,n+1):\n        if a[i-1]==b[j-1]:\n            dp[i][j]=dp[i-1][j-1]\n        else:\n            dp[i][j]=min(dp[i-1][j]+cd,dp[i][j-1]+ci,dp[i-1][j-1]+cr)\nprint(dp[m][n])', tip: '置換が高コストなら「削除＋挿入」で迂回する選択が最適になることもある。', ins: ['1 1 1\nhorse\nros\n', '1 1 5\nabc\nabd\n', '2 3 1\nabc\nabc\n', '1 1 1\na\n\n', '5 5 1\nab\ncd\n', '1 2 3\nkitten\nsitting\n'] })

export const CATALOG = TASKS
