// 生成タスク 第67波：各レベル2問化フェーズ(22)。lv841〜849, lv851〜865 に2問目を追加。
// 上級データ構造/畳み込み/行列累乗/数論帯。重複なし・決定的・採点一意。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 841, concept: 'オフライン: しきい値以下の要素の合計', title: 'x以下の要素の合計クエリ', tags: ['オフライン', '二分探索'], io: '1行目に整数列、2行目に問い合わせの値が空白区切りで与えられます。', ask: '各問い合わせ x について、x 以下の要素の合計を空白区切りで出力してください。', h1: 'ソートと累積和を前計算する。', h2: 'bisect_right で「x以下の個数」を出し、接頭辞和を引く。', ref: 'import bisect\na=sorted(map(int,input().split()))\npre=[0]\nfor x in a:\n    pre.append(pre[-1]+x)\nqs=list(map(int,input().split()))\nprint(*[pre[bisect.bisect_right(a,x)] for x in qs])', tip: '「個数」のbisectに接頭辞和を重ねるだけで「合計」クエリになる。集計の種類を増やすときは前計算の配列を1本ずつ足していけばよい。', ins: ['3 1 4 1 5\n2 4 0\n', '10 20\n15 5 30\n', '5\n5\n', '1 1 1\n1\n', '-3 2 7\n0 10\n', '100\n99\n'] })

t({ lv: 842, concept: 'データ構造: 区間の交代和', title: 'プラスマイナス交互の区間和', tags: ['データ構造'], io: '1行目に n q、2行目に整数列、続く q 行に「1 i x」(i番目をxに変更)または「2 l r」(質問)が与えられます。', ask: '各質問について交代和 a_l − a_{l+1} + a_{l+2} − … を出力してください。', h1: '符号は区間の先頭からの相対位置で決まる。', h2: '「偶数位置に+、奇数位置に−を付けた列」の接頭辞和を使うと、lの偶奇で符号を反転するだけで求まる(セグ木なら±付き和を2本)。', ref: 'n,q=map(int,input().split())\na=list(map(int,input().split()))\nfor _ in range(q):\n    t,x,y=map(int,input().split())\n    if t==1:\n        a[x-1]=y\n    else:\n        s=0\n        sign=1\n        for i in range(x-1,y):\n            s+=sign*a[i]\n            sign=-sign\n        print(s)', tip: '交代和は「絶対位置の偶奇で符号を固定した配列」の普通の区間和に帰着し、クエリ側の偶奇で全体を±1倍するだけ。位置依存の重みは前もって焼き込む。', ins: ['4 2\n1 2 3 4\n2 1 4\n2 2 3\n', '3 3\n5 5 5\n2 1 3\n1 2 0\n2 1 3\n', '2 1\n7 3\n2 1 2\n', '5 2\n1 1 1 1 1\n2 1 5\n2 2 4\n', '1 2\n9\n2 1 1\n1 1 4\n', '4 1\n10 -10 10 -10\n2 1 4\n'] })

t({ lv: 843, concept: '数え上げ: 各窓の転倒数', title: '窓の中の乱れ具合を並べる', tags: ['数え上げ', '窓'], io: '1行目に窓の長さ k、2行目に整数列が与えられます。', ask: '長さ k の各窓について、窓内の転倒数(i<j で a[i]>a[j] のペア数)を空白区切りで出力してください。', h1: '窓ごとに2重ループで数えてよい。', h2: '大規模ではBITを窓と一緒にスライドさせ、出る要素・入る要素の寄与を差分更新する。', ref: 'k=int(input())\na=list(map(int,input().split()))\nout=[]\nfor s in range(len(a)-k+1):\n    w=a[s:s+k]\n    inv=0\n    for i in range(k):\n        for j in range(i+1,k):\n            if w[i]>w[j]:\n                inv+=1\n    out.append(inv)\nprint(*out)', tip: '窓のスライドでは「出る要素より右にある小さい値の数」を引き、「入る要素より左にある大きい値の数」を足す。統計量の差分更新はソート性の指標にも応用できる。', ins: ['3\n3 1 2 4\n', '2\n2 1 2 1\n', '4\n4 3 2 1\n', '1\n5 5 5\n', '3\n1 2 3 4 5\n', '2\n9 9\n'] })

t({ lv: 844, concept: '数え上げ: 入れ替えるたびの転倒数の偶奇', title: 'スワップのたびに偶奇を答える', tags: ['数え上げ'], io: '1行目に n q、2行目に 1..n の順列、続く q 行に交換する2位置 i j (i≠j) が与えられます。', ask: '各交換の後の転倒数の偶奇を even / odd で1行ずつ出力してください。', h1: '転倒数を毎回数え直す必要はない。', h2: 'どんな2要素の交換(互換)も転倒数の偶奇を必ず反転させる。初期の偶奇だけ数えれば以降はO(1)。', ref: 'n,q=map(int,input().split())\na=list(map(int,input().split()))\ninv=0\nfor i in range(n):\n    for j in range(i+1,n):\n        if a[i]>a[j]:\n            inv+=1\np=inv%2\nfor _ in range(q):\n    i,j=map(int,input().split())\n    a[i-1],a[j-1]=a[j-1],a[i-1]\n    p^=1\n    print("even" if p==0 else "odd")', tip: '「互換は奇置換」という群論の基本事実が、クエリをO(1)にする。値の中身に関係なく偶奇が反転する…のは順列(相異なる値)だからこそ。', ins: ['3 2\n1 2 3\n1 2\n1 2\n', '2 1\n2 1\n1 2\n', '4 3\n1 2 3 4\n1 4\n2 3\n1 2\n', '3 1\n3 1 2\n2 3\n', '5 2\n1 2 3 4 5\n1 5\n2 4\n', '2 2\n1 2\n1 2\n1 2\n'] })

t({ lv: 845, concept: 'データ構造: 最も左の0の位置クエリ', title: '一番左の空きはどこか', tags: ['データ構造'], io: '1行目に n q、2行目に整数列、続く q 行に「1 i x」(i番目をxに変更)または「2」(質問)が与えられます。', ask: '各質問に対し、値が0である最も左の位置(1始まり)を出力してください。無ければ -1。', h1: '素朴に先頭から探してもよい。', h2: 'セグ木に「区間の最小値」を持てば、最小が0の側へ木を降りることでO(log n)で見つかる。', ref: 'n,q=map(int,input().split())\na=list(map(int,input().split()))\nfor _ in range(q):\n    parts=list(map(int,input().split()))\n    if parts[0]==1:\n        a[parts[1]-1]=parts[2]\n    else:\n        for i in range(n):\n            if a[i]==0:\n                print(i+1)\n                break\n        else:\n            print(-1)', tip: '「条件を満たす最左の位置」はセグ木の上をルートから降りる二分探索(segment tree descent)の代表的な使い所。空き席・空きIDの管理はみなこの形。', ins: ['3 3\n1 0 2\n2\n1 2 5\n2\n', '2 2\n0 0\n2\n2\n', '3 2\n1 2 3\n2\n1 3 0\n', '1 3\n0\n2\n1 1 1\n2\n', '4 2\n1 1 0 0\n2\n2\n', '2 3\n5 5\n2\n1 1 0\n2\n'] })

t({ lv: 846, concept: '数え上げ: 両側から見える要素', title: '左右どちらからも見える高さ', tags: ['数え上げ'], io: '相異なる高さの列が1行で空白区切りで与えられます。', ask: '「自分より左は全て低い」かつ「自分より右も全て低い」要素の個数を出力してください。', h1: '左からの最大記録と右からの最大記録を前計算する。', h2: '両方の記録更新点の共通部分…つまり全体の最大だけ、ではない理由も考えてみる(実は全体最大のみ)。', ref: 'a=list(map(int,input().split()))\nn=len(a)\npre=[False]*n\nmx=float("-inf")\nfor i in range(n):\n    if a[i]>mx:\n        pre[i]=True\n        mx=a[i]\nmx=float("-inf")\ncnt=0\nfor i in range(n-1,-1,-1):\n    if a[i]>mx:\n        if pre[i]:\n            cnt+=1\n        mx=a[i]\nprint(cnt)', tip: '相異なる高さなら両側から見えるのは全体の最大の1つだけ、と論理的には即答できる。同値を許すと途端に複数になり得る、前提が答えを変える好例。', ins: ['1 3 2\n', '5\n', '1 2 3\n', '3 2 1\n', '2 5 1 4\n', '1 4 2 5 3\n'] })

t({ lv: 847, concept: 'データ構造: 区間の絶対値最小', title: '0にいちばん近い値のクエリ', tags: ['データ構造'], io: '1行目に n q、2行目に整数列、続く q 行に「1 i x」(変更)または「2 l r」(質問)が与えられます。', ask: '各質問について、区間内で絶対値が最小の値(同絶対値なら小さい方)を出力してください。', h1: '比較キーを(絶対値, 値)にする。', h2: 'min(区間, key=...) で書ける。セグ木ならこのキーのままマージすればよい。', ref: 'n,q=map(int,input().split())\na=list(map(int,input().split()))\nfor _ in range(q):\n    t,x,y=map(int,input().split())\n    if t==1:\n        a[x-1]=y\n    else:\n        print(min(a[x-1:y],key=lambda v:(abs(v),v)))', tip: '「最小」の定義はkey次第でいくらでも差し替えられる。タプルキーが全順序を与える限り、同じセグ木がそのまま流用できる。', ins: ['4 2\n3 -1 2 -5\n2 1 4\n2 3 4\n', '2 2\n-2 2\n2 1 2\n1 1 0\n', '3 1\n5 5 5\n2 1 3\n', '3 3\n-1 1 3\n2 1 2\n1 2 -1\n2 1 2\n', '1 1\n-7\n2 1 1\n', '5 1\n10 -3 4 -3 9\n2 2 5\n'] })

t({ lv: 848, concept: 'データ構造: 挿入と順位のクエリ', title: '何位に入るかを逐次答える', tags: ['データ構造', '二分探索'], io: '1行目にクエリ数 q、続く q 行に「add x」(xを追加)または「rank x」(質問)が与えられます。', ask: '各 rank x に対し「これまでに追加された x 以下の値の個数」を出力してください。', h1: 'ソート済みリストを維持する。', h2: 'bisect.insort で挿入し、bisect_right で順位を得る。大量ならBIT+座標圧縮。', ref: 'import bisect\nq=int(input())\na=[]\nfor _ in range(q):\n    parts=input().split()\n    x=int(parts[1])\n    if parts[0]=="add":\n        bisect.insort(a,x)\n    else:\n        print(bisect.bisect_right(a,x))', tip: 'insortはO(n)の挿入だが「順位を保った列」を最短の記述で維持できる。挿入と順位が交互に来る動的な問題はBITでの1点加算+接頭辞和が本命。', ins: ['5\nadd 3\nadd 1\nrank 2\nadd 2\nrank 2\n', '3\nrank 5\nadd 5\nrank 5\n', '4\nadd 1\nadd 1\nrank 1\nrank 0\n', '2\nadd 9\nrank 8\n', '6\nadd 5\nadd 3\nadd 8\nrank 5\nrank 7\nrank 10\n', '3\nadd -1\nrank -1\nrank -2\n'] })

t({ lv: 849, concept: '数え上げ: ソートによる移動距離の総和', title: '整列で全員が動く距離', tags: ['数え上げ', 'ソート'], io: '整数列が1行で空白区切りで与えられます。', ask: '安定ソート(同値は元の順)したとき、各要素の移動距離(元の位置と新しい位置の差の絶対値)の総和を出力してください。', h1: '「安定ソート後の並び順」は(値, 元位置)のソートで決まる。', h2: '新しい位置と元の位置の差を合計する。', ref: 'a=list(map(int,input().split()))\norder=sorted(range(len(a)),key=lambda i:(a[i],i))\nprint(sum(abs(new-old) for new,old in enumerate(order)))', tip: 'argsort(添字のソート)は「どこへ行くか」を一発で与える万能の道具。安定性はキーに元位置を添えるだけで機械的に表現できる。', ins: ['3 1 2\n', '1 2 3\n', '2 2 1\n', '5\n', '3 3 3\n', '4 1 3 2\n'] })

t({ lv: 851, concept: '数学: 多項式の合成', title: '多項式に多項式を代入する', tags: ['数学'], io: '1行目に多項式 P の係数(低次から)、2行目に多項式 Q の係数(低次から)が与えられます。', ask: 'P(Q(x)) を展開した係数を低次から空白区切りで出力してください。', h1: 'Qのべき乗を順に作りながらPの係数を掛けて足す。', h2: '多項式の積(畳み込み)の関数を1つ書けば、ホーナー法の形でも合成できる。', ref: 'P=list(map(int,input().split()))\nQ=list(map(int,input().split()))\ndef mul(A,B):\n    C=[0]*(len(A)+len(B)-1)\n    for i,x in enumerate(A):\n        for j,y in enumerate(B):\n            C[i+j]+=x*y\n    return C\nres=[0]\ncur=[1]\nfor c in P:\n    add=[c*v for v in cur]\n    if len(add)>len(res):\n        res=res+[0]*(len(add)-len(res))\n    for i,v in enumerate(add):\n        res[i]+=v\n    cur=mul(cur,Q)\nwhile len(res)>1 and res[-1]==0:\n    res.pop()\nprint(*res)', tip: '積(畳み込み)を部品に、合成・べき乗・逆関数展開が組み上がる。末尾の0を刈って正規形にするのは多項式表現の作法。', ins: ['1 1\n0 1\n', '0 0 1\n1 1\n', '2\n5 7\n', '1 2 1\n0 2\n', '0 1\n3\n', '1 0 1\n1 1\n'] })

t({ lv: 852, concept: 'bit演算: 全部分集合XORの総和', title: '全部の部分集合のXORを足すと', tags: ['bit演算', '数学'], io: '非負整数の列(1個以上)が1行で空白区切りで与えられます。', ask: '全ての部分集合(空集合はXOR 0)について要素のXORを計算し、その総和を出力してください。', h1: 'ビットごとに「そのビットが1になる部分集合の数」を数える。', h2: 'あるビットを持つ要素が1個でもあれば、そのビットが立つ部分集合はちょうど半分(2^(n−1))。答えは (全要素のOR) × 2^(n−1)。', ref: 'a=list(map(int,input().split()))\nn=len(a)\no=0\nfor x in a:\n    o|=x\nprint(o*(1<<(n-1)))', tip: '2^n個の和が閉形式に潰れるのは「対称性で半々」の議論のおかげ。ビット独立+対称性の合わせ技は、XOR系の総和問題の第一手。', ins: ['1 2\n', '5\n', '1 1\n', '1 2 4\n', '0 0\n', '7 7 7\n'] })

t({ lv: 853, concept: 'bit演算: 全ペアANDの総和', title: '全ペアのANDを足し合わせる', tags: ['bit演算'], io: '非負整数の列(2個以上)が1行で空白区切りで与えられます。', ask: '全てのペア (i<j) について AND を計算し、その総和を出力してください。', h1: 'ビットごとに独立に数える。', h2: 'ビット b を持つ要素が c 個なら、寄与は C(c,2)×2^b。', ref: 'a=list(map(int,input().split()))\ntotal=0\nfor b in range(32):\n    c=sum(v>>b&1 for v in a)\n    total+=c*(c-1)//2*(1<<b)\nprint(total)', tip: 'ペアの総和はO(n²)をビット別の頻度O(32n)へ。ANDは「両方1」、ORは「どちらか1」、XORは「片方だけ1」と、条件の違いが組合せの式の違いになる。', ins: ['1 2 3\n', '5 5\n', '0 7\n', '3 3 3\n', '8 4 2\n', '6 6 6 6\n'] })

t({ lv: 854, concept: 'bit演算: 全ペアORの総和', title: '全ペアのORを足し合わせる', tags: ['bit演算'], io: '非負整数の列(2個以上)が1行で空白区切りで与えられます。', ask: '全てのペア (i<j) について OR を計算し、その総和を出力してください。', h1: 'ANDの数え方の裏返し。', h2: 'ビット b が立つペアは「全ペア − 両方0のペア」= C(n,2) − C(n−c,2)。', ref: 'a=list(map(int,input().split()))\nn=len(a)\ntotal=0\nfor b in range(32):\n    c=sum(v>>b&1 for v in a)\n    z=n-c\n    total+=(n*(n-1)//2-z*(z-1)//2)*(1<<b)\nprint(total)', tip: '「少なくとも一方」は補集合(両方とも無い)で数えるのが確実。AND+OR=和+…のような恒等式 (a&b)+(a|b)=a+b での検算もできる。', ins: ['1 2 3\n', '5 5\n', '0 7\n', '3 3 3\n', '8 4 2\n', '1 1 1 1\n'] })

t({ lv: 855, concept: '数学: アフィン漸化式の第n項', title: 'かけて足す漸化式の遠い項', tags: ['数学'], io: 'x0 a b n m が1行で与えられます(漸化式 x_{k+1} は (a·x_k + b) mod m)。', ask: 'x_n (mod m) を出力してください。', h1: 'nが大きくても1歩ずつ回さない方法がある。', h2: 'アフィン変換 (a,b) の合成は (a2·a1, a2·b1+b2)。二乗しながらn回分を合成する(繰り返し二乗法の一般化)。', ref: 'x0,a,b,n,m=map(int,input().split())\nA,B=1,0\np,q=a%m,b%m\nk=n\nwhile k:\n    if k&1:\n        A,B=p*A%m,(p*B+q)%m\n    p,q=p*p%m,(p*q+q)%m\n    k>>=1\nprint((A*x0+B)%m)', tip: '「関数の合成」も結合的なので二乗法で飛ばせる。行列 [[a,b],[0,1]] のべき乗と同じことを、2つの数だけで済ませた形。', ins: ['1 2 3 1 100\n', '1 2 3 3 100\n', '5 1 1 10 7\n', '0 3 1 4 1000\n', '2 2 0 10 1000000007\n', '7 1 0 100 13\n'] })

t({ lv: 856, concept: 'DP: 隣接禁止ペアつき文字列の数', title: '続けて置けない文字がある文字列', tags: ['DP'], io: '1行目に 文字種数 k と長さ n と禁止ペア数 m、続く m 行に「a b」(文字aの直後に文字bを置けない。文字は1..k)が与えられます。', ask: '長さ n の文字列で禁止された隣接が現れないものの総数を出力してください。', h1: '最後の文字を状態に持つ。', h2: 'dp[c] を1文字ずつ遷移。許される遷移だけ足す(遷移行列のべき乗にもなる)。', ref: 'k,n,m=map(int,input().split())\nbad=set()\nfor _ in range(m):\n    a,b=map(int,input().split())\n    bad.add((a,b))\ndp=[1]*(k+1)\ndp[0]=0\nfor _ in range(n-1):\n    nd=[0]*(k+1)\n    for prev in range(1,k+1):\n        if dp[prev]:\n            for c in range(1,k+1):\n                if (prev,c) not in bad:\n                    nd[c]+=dp[prev]\n    dp=nd\nprint(sum(dp))', tip: '言語モデルの遷移制約の最小模型。nが巨大なら遷移行列のn−1乗に切り替える、というDP→行列累乗の階段が典型ルート。', ins: ['2 2 1\n1 1\n', '2 3 0\n', '3 2 2\n1 2\n2 1\n', '1 3 0\n', '2 4 1\n1 2\n', '3 1 3\n1 1\n2 2\n3 3\n'] })

t({ lv: 857, concept: '数論: トーシェントを繰り返して1まで', title: 'φを何回で1になるか', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: 'n にオイラーのトーシェント関数 φ を繰り返し適用して1になるまでの適用回数を出力してください(n=1なら0)。', h1: 'φを素直に計算する関数を用意する。', h2: '2以上なら φ(n) は必ず減るので有限回で1に落ちる。', ref: 'n=int(input())\ndef phi(x):\n    r=x\n    p=2\n    while p*p<=x:\n        if x%p==0:\n            while x%p==0:\n                x//=p\n            r-=r//p\n        p+=1\n    if x>1:\n        r-=r//x\n    return r\nc=0\nwhile n>1:\n    n=phi(n)\n    c+=1\nprint(c)', tip: 'φの反復は毎回ほぼ半減するので回数はO(log n)。この「反復回数」は乗法群の塔の高さに対応し、繰り返し累乗の指数タワーの計算にも顔を出す。', ins: ['1\n', '2\n', '10\n', '100\n', '7\n', '97\n'] })

t({ lv: 858, concept: '数論: トーシェントの逆引き', title: 'φ(n)=kになる最小のn', tags: ['数論'], io: '正整数 k が1行で与えられます(解が存在する k のみ)。', ask: 'φ(n) が k に等しい最小の正整数 n を出力してください。', h1: '小さい n から順に φ を確かめる。', h2: 'φ(n)≥√n/2 程度なので探索は打ち切れる(小さい入力なら上限 4k+4 まで見れば十分)。', ref: 'k=int(input())\ndef phi(x):\n    r=x\n    p=2\n    while p*p<=x:\n        if x%p==0:\n            while x%p==0:\n                x//=p\n            r-=r//p\n        p+=1\n    if x>1:\n        r-=r//x\n    return r\nn=1\nwhile True:\n    if phi(n)==k:\n        print(n)\n        break\n    n+=1', tip: '逆像が空になる k (奇数の3以上など)や、逆像が有限個しかないことの証明はCarmichaelの予想として現役の未解決問題に繋がっている。', ins: ['1\n', '2\n', '4\n', '8\n', '6\n', '16\n'] })

t({ lv: 859, concept: '数論: 平方部分と無平方部分への分解', title: 'nを a²×b に分ける', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: 'n = a²×b (b は平方因子を持たない)となる a b を空白区切りで出力してください。', h1: '素因数分解して指数を2で割る。', h2: '指数の半分(切り捨て)が a 側、余り(0か1)が b 側に入る。', ref: 'n=int(input())\na=1\nb=1\np=2\nwhile p*p<=n:\n    if n%p==0:\n        e=0\n        while n%p==0:\n            n//=p\n            e+=1\n        a*=p**(e//2)\n        if e%2:\n            b*=p\n    p+=1\nif n>1:\n    b*=n\nprint(a,b)', tip: '√nの簡約(√12を2√3にする)はこの分解そのもの。指数の偶奇に情報を割る発想は平方剰余や無平方数の議論の土台になる。', ins: ['12\n', '1\n', '49\n', '360\n', '7\n', '100\n'] })

t({ lv: 860, concept: '数論: パワフル数の判定', title: 'どの素因数も2乗以上か', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: 'n の全ての素因数 p について p² も n を割り切る(パワフル数)なら yes、そうでなければ no を出力してください(1はyes)。', h1: '素因数分解して指数を見る。', h2: '指数が1の素因数が1つでもあれば no。', ref: 'n=int(input())\nok=True\np=2\nwhile p*p<=n:\n    if n%p==0:\n        e=0\n        while n%p==0:\n            n//=p\n            e+=1\n        if e<2:\n            ok=False\n    p+=1\nif n>1:\n    ok=False\nprint("yes" if ok else "no")', tip: 'パワフル数は必ず a²b³ の形に書ける。試し割りの後に残った n>1 は「指数1の大きな素因数」なので即 no、という残り物の扱いが実装の急所。', ins: ['8\n', '12\n', '1\n', '36\n', '72\n', '25\n'] })

t({ lv: 861, concept: '数論: k番目の醜数', title: '2と3と5だけの数のk番目', tags: ['数論', 'DP'], io: '正整数 k が1行で与えられます。', ask: '素因数が2,3,5のみからなる数(醜数、1を含む)を小さい順に並べたときの k 番目を出力してください。', h1: '次の醜数は既出の醜数×2,×3,×5のどれか。', h2: '3本のポインタで「次の候補」を持ち、最小を採用したポインタだけ進める(重複に注意)。', ref: 'k=int(input())\nu=[1]\ni2=i3=i5=0\nwhile len(u)<k:\n    c2,c3,c5=u[i2]*2,u[i3]*3,u[i5]*5\n    x=min(c2,c3,c5)\n    u.append(x)\n    if x==c2:\n        i2+=1\n    if x==c3:\n        i3+=1\n    if x==c5:\n        i5+=1\nprint(u[k-1])', tip: '「生成規則から小さい順に並べる」3ポインタ法はハミング数(Dijkstraが論じた)として有名。重複を全ポインタ同時進行で潰すのが要点。', ins: ['1\n', '7\n', '10\n', '15\n', '2\n', '20\n'] })

t({ lv: 862, concept: '数論: リウヴィル関数', title: '素因数の個数の偶奇λ(n)', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: '重複込みの素因数の個数 Ω(n) が偶数なら 1、奇数なら -1(リウヴィル関数 λ(n))を出力してください。', h1: 'Ωを試し割りで数える。', h2: '(−1)^Ω を返すだけ。', ref: 'n=int(input())\nc=0\np=2\nwhile p*p<=n:\n    while n%p==0:\n        n//=p\n        c+=1\n    p+=1\nif n>1:\n    c+=1\nprint(1 if c%2==0 else -1)', tip: 'λはメビウス関数の親戚(平方因子があっても消えない版)。λの部分和が常に非正というポリア予想は反例が10^8台で見つかった、有名な「大きな反例」の物語を持つ。', ins: ['1\n', '2\n', '4\n', '12\n', '30\n', '36\n'] })

t({ lv: 863, concept: '数論: アリコット数列の追跡', title: '約数和で飛び続けた行き先', tags: ['数論'], io: 'n k が空白区切りで1行で与えられます。', ask: 'n から始めて「自分以外の約数の和」への置き換えを k 回行った値を出力してください(0になったらそのまま0が続きます)。', h1: '真の約数和 s(n)=σ(n)−n を関数にする。', h2: 'k回のループで適用。0の扱いだけ特別に。', ref: 'n,k=map(int,input().split())\ndef s(x):\n    if x==0:\n        return 0\n    total=0\n    i=1\n    while i*i<=x:\n        if x%i==0:\n            if i<x:\n                total+=i\n            j=x//i\n            if j!=i and j<x:\n                total+=j\n        i+=1\n    return total\nfor _ in range(k):\n    n=s(n)\nprint(n)', tip: '完全数は不動点、友愛数は2周期。276から始まる列は有界かどうかすら未解決(カタラン=ディクソン予想)という、遊べる未解決問題の入り口。', ins: ['12 1\n', '6 5\n', '220 1\n', '284 2\n', '8 3\n', '95 2\n'] })

t({ lv: 864, concept: '数論: 商の種類数', title: 'n割るiの値は何種類か', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: 'i を 1 から n まで動かしたとき、⌊n/i⌋ として現れる相異なる値の個数を出力してください。', h1: '素直に集合へ入れても数えられる。', h2: '答えはおよそ 2√n 個。商が同じ区間をまとめて飛ぶ「商の分割」で O(√n) でも数えられる。', ref: 'n=int(input())\ni=1\ncnt=0\nwhile i<=n:\n    v=n//i\n    cnt+=1\n    i=n//v+1\nprint(cnt)', tip: '「⌊n/i⌋が一定の区間の右端は n//(n//i)」という飛び方は約数和・floor和の高速化の共通部品。√n個しか値が無いことが全ての出発点。', ins: ['1\n', '10\n', '100\n', '6\n', '36\n', '1000\n'] })

t({ lv: 865, concept: '数論: 範囲内で条件が同時に成り立つ回数', title: '2つの周期が同時に当たる回数', tags: ['数論'], io: 'N a r1 b r2 が1行で与えられます。', ask: '0 以上 N 未満の t のうち、t を a で割った余りが r1、かつ b で割った余りが r2 であるものの個数を出力してください。', h1: '両方を満たす t は(あれば)lcm(a,b) ごとに現れる。', h2: '最小解を見つけて (N−t0−1)//lcm + 1。小さい範囲なら全数チェックでもよい。', ref: 'N,a,r1,b,r2=map(int,input().split())\nprint(sum(1 for t in range(N) if t%a==r1 and t%b==r2))', tip: '中国剰余定理は「解の存在と一意性(mod lcm)」を言う定理で、回数はその周期性から等差数列の数え上げに落ちる。全数チェックはその検算器。', ins: ['20 3 1 4 2\n', '10 2 0 3 0\n', '1 2 1 3 2\n', '100 5 3 7 4\n', '50 6 1 4 3\n', '30 2 1 4 2\n'] })

export const CATALOG = TASKS
