// 生成タスク 第65波：各レベル2問化フェーズ(20)。lv791〜799, lv801〜815 に2問目を追加。
// 文字列/データ構造(セグ木・BIT帯の応用)。重複なし・決定的・採点一意。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 791, concept: '文字列: 前方一致で数えるオートコンプリート', title: '入力候補は何件あるか', tags: ['文字列'], io: '1行目に単語が空白区切りで、2行目に問い合わせの接頭辞が空白区切りで与えられます。', ask: '各接頭辞について、その接頭辞で始まる単語の数を空白区切りで出力してください。', h1: 'startswith で数えるだけでも動く。', h2: '大量なら単語をソートして bisect で「接頭辞区間」の両端を探すか、トライ木に通過数を持たせる。', ref: 'words=input().split()\nqs=input().split()\nprint(*[sum(1 for w in words if w.startswith(q)) for q in qs])', tip: 'ソート済みならば接頭辞に合致する単語は連続区間に固まる。bisect_left(q) と bisect_left(q+"\\uffff") で区間の幅が一発で出る。', ins: ['apple app apply banana\napp ban x\n', 'a ab abc\na\n', 'dog cat\nd c a\n', 'x\nx\n', 'aa ab ba\na b\n', 'hello help hell\nhel hell\n'] })

t({ lv: 792, concept: '数え上げ: ヒストグラムの外周', title: '棒グラフのまわりの長さ', tags: ['数学'], io: '各バー(幅1)の高さの列が1行で空白区切りで与えられます。', ask: 'バーを隙間なく並べた図形の外周の長さを出力してください。', h1: '上辺と底辺は本数ぶんある。', h2: '縦線は「左端の高さ+右端の高さ+隣接の高低差の絶対値の合計」。', ref: 'h=list(map(int,input().split()))\nn=len(h)\nper=2*n+h[0]+h[-1]\nfor i in range(1,n):\n    per+=abs(h[i]-h[i-1])\nprint(per)', tip: 'シルエットの縦成分は「高さの変化量の総和」に置き換わる。差分で図形量を測る発想は、微分で長さを測る考え方の離散版。', ins: ['3\n', '1 1 1\n', '1 3 1\n', '5 5\n', '2 0 2\n', '1 2 3 4\n'] })

t({ lv: 793, concept: 'スタック: ファイルパスの正規化', title: 'パスをきれいに直す', tags: ['スタック', '文字列'], io: 'Unix形式の絶対パス(/で始まり、. や .. を含みうる)が1行で与えられます。', ask: '「.」は無視、「..」は1つ上へ、連続する / は1つに、を適用した正規化パスを出力してください(結果がルートなら /)。', h1: '/ で分割して部品ごとに処理する。', h2: '普通の名前はスタックへ、「..」はスタックからpop(空なら無視)、最後に / で連結。', ref: 's=input()\nst=[]\nfor part in s.split("/"):\n    if part=="" or part==".":\n        continue\n    if part=="..":\n        if st:\n            st.pop()\n    else:\n        st.append(part)\nprint("/"+"/".join(st))', tip: 'OSのパス解決そのもの。「..」を後から遡って消すのではなく、積みながらpopで処理するとワンパスで済む。', ins: ['/home/\n', '/../\n', '/home//foo/\n', '/a/./b/../../c/\n', '/a/b/c\n', '/...\n'] })

t({ lv: 794, concept: '二分探索: 未満で最大の値クエリ', title: 'xより小さい最大の要素', tags: ['二分探索'], io: '1行目にソート済みでない整数列、2行目に問い合わせの値が空白区切りで与えられます。', ask: '各問い合わせ x について、列の中で x より厳密に小さい最大の要素を出力してください(無ければ none)。答えは空白区切りで。', h1: 'ソートしてから二分探索する。', h2: 'bisect_left(a, x) の1つ左が答えの位置。', ref: 'import bisect\na=sorted(map(int,input().split()))\nqs=list(map(int,input().split()))\nout=[]\nfor x in qs:\n    i=bisect.bisect_left(a,x)\n    out.append(str(a[i-1]) if i>0 else "none")\nprint(*out)', tip: 'predecessor(先行者)クエリはbisect_leftの位置−1。successorはbisect_rightの位置。この2つの向きを混同しないことが bisect 習熟の壁。', ins: ['3 1 4 1 5\n2 4 1\n', '10 20 30\n25 10 40\n', '5\n5 6\n', '1 3 5 7\n0\n', '2 2 2\n3 2\n', '100\n1000\n'] })

t({ lv: 795, concept: '文字列: 単語の均等割り付け', title: '幅ぴったりに空白を配る', tags: ['文字列'], io: '1行目に行の幅 W、2行目に単語(2語以上、合計文字数+語間1つずつでW以下)が与えられます。', ask: '単語間の空白をできるだけ均等に(余りは左の隙間から1つずつ多く)配り、幅ちょうど W の1行を出力してください。', h1: '配るべき空白の総数を先に計算する。', h2: '隙間の数で割った商が基本の空白数、余りを左から1つずつ上乗せ。', ref: 'W=int(input())\nwords=input().split()\ngaps=len(words)-1\ntotal=W-sum(len(w) for w in words)\nbase=total//gaps\nextra=total%gaps\nres=words[0]\nfor i in range(1,len(words)):\n    sp=base+(1 if i<=extra else 0)\n    res+=" "*sp+words[i]\nprint(res)', tip: '割り切れない余りを「左から1つずつ」という規約で一意化するのが実装のポイント。テキストの両端揃え(justify)の中心処理そのもの。', ins: ['16\nThis is an\n', '5\na b\n', '10\nab cd\n', '7\nx y z\n', '9\nfoo bar\n', '12\na bb ccc\n'] })

t({ lv: 796, concept: 'ハッシュ: 3回以上現れる最小の値', title: '3回以上出てくる一番小さい数', tags: ['ハッシュ'], io: '整数列が1行で空白区切りで与えられます。', ask: '3回以上現れる値のうち最小のものを出力してください。無ければ none。', h1: 'Counterで頻度を数える。', h2: '条件を満たす値だけ集めて min を取る。', ref: 'from collections import Counter\nc=Counter(map(int,input().split()))\ncand=[v for v,k in c.items() if k>=3]\nprint(min(cand) if cand else "none")', tip: '「条件付きの最小」は、フィルタ→min の2段が最短。候補が空のときの既定値は min(cand, default=…) でも書ける。', ins: ['1 2 1 2 1\n', '3 3 3 2 2 2\n', '1 2 3\n', '5 5\n', '0 0 0 0\n', '9 9 9 1 1 1 4\n'] })

t({ lv: 797, concept: '窓: 各窓の2番目に大きい値', title: '窓の中の2位を並べる', tags: ['窓'], io: '1行目に窓の長さ k (k≥2)、2行目に整数列が与えられます。', ask: '長さ k の各窓について「2番目に大きい値」(最大が複数ならそれも2番目になりうる)を空白区切りで出力してください。', h1: '各窓をソートして後ろから2番目。', h2: '大きな入力では2本の単調構造や(最大,2位)のマージで持つ。', ref: 'k=int(input())\na=list(map(int,input().split()))\nout=[]\nfor i in range(len(a)-k+1):\n    w=sorted(a[i:i+k])\n    out.append(w[-2])\nprint(*out)', tip: '(最大, 2位)のペアは「2つのペアのマージ」が定義できるのでセグ木にも載る。上位k位固定の統計は小さなヒープの維持でも追える。', ins: ['2\n3 1 4 1\n', '3\n1 2 3 4\n', '2\n5 5 5\n', '4\n9 7 8 6\n', '2\n1 2\n', '3\n2 8 2 8 2\n'] })

t({ lv: 798, concept: '文字列: 最長の連続2回繰り返し', title: '隣どうしで同じ形の最長', tags: ['文字列'], io: '英小文字の文字列が1行で与えられます。', ask: '同じ文字列が2回続けて並ぶ部分(スクエア、例 abab の中の abab 全体)の最大の長さ(2回分の合計)を出力してください。無ければ 0。', h1: '半分の長さ L を全て試す。', h2: '各開始位置で s[i:i+L]==s[i+L:i+2L] を確かめる。', ref: 's=input()\nn=len(s)\nbest=0\nfor L in range(n//2,0,-1):\n    for i in range(n-2*L+1):\n        if s[i:i+L]==s[i+L:i+2*L]:\n            best=2*L\n            break\n    if best:\n        break\nprint(best)', tip: 'スクエア(タンデム反復)はDNAの反復配列解析にも現れる語の組合せ論の基本語彙。O(n log n)のMain-Lorentz法まで先がある。', ins: ['abab\n', 'aaaa\n', 'abcd\n', 'aabaabaa\n', 'xy\n', 'abcabcab\n'] })

t({ lv: 799, concept: '累積和: 破産しない最長の日数', title: '残高がプラスのままの最長日数', tags: ['累積和'], io: '毎日の収支(整数)の列が1行で空白区切りで与えられます。残高は0から始まります。', ask: '初日から連続で「毎日の終わりの残高が正」である最長の日数を出力してください(初日から破産なら0)。', h1: '先頭からの累積和を追う。', h2: '累積が0以下になった時点で止める。', ref: 'a=list(map(int,input().split()))\ns=0\ndays=0\nfor x in a:\n    s+=x\n    if s<=0:\n        break\n    days+=1\nprint(days)', tip: '「最初に条件が破れる位置」は breakつき走査が最速で最簡。条件を式でこねるより、素直にシミュレーションで止まる方が読みやすいこともある。', ins: ['3 -1 -1 -1 4\n', '-1 5\n', '1 1 1\n', '2 -2 3\n', '5\n', '1 -1\n'] })

t({ lv: 801, concept: 'データ構造: 座席予約と空き確認', title: '連続席の予約システム', tags: ['データ構造'], io: '1行目に 席数 n とクエリ数 q、続く q 行に「1 l r」(l..r を予約試行)または「2 l r」(空き確認)が与えられます。', ask: '「1 l r」は全席空きなら予約成立で ok、1つでも埋まっていれば ng を出力し予約しません。「2 l r」は全席空きなら yes、そうでなければ no を出力してください。', h1: '席の状態を配列で持つ。', h2: '大規模なら区間和のセグ木で「区間の予約数が0か」を見る。', ref: 'n,q=map(int,input().split())\nseat=[0]*(n+1)\nfor _ in range(q):\n    t,l,r=map(int,input().split())\n    free=all(seat[i]==0 for i in range(l,r+1))\n    if t==1:\n        if free:\n            for i in range(l,r+1):\n                seat[i]=1\n            print("ok")\n        else:\n            print("ng")\n    else:\n        print("yes" if free else "no")', tip: '「区間が全部空きか」は区間和が0かと同値。素朴配列→セグ木→区間代入の遅延伝播、と同じ仕様のまま実装だけ成長させられる題材。', ins: ['5 4\n1 1 2\n1 2 3\n2 3 5\n1 3 5\n', '3 2\n2 1 3\n1 1 3\n', '4 3\n1 1 4\n2 2 3\n1 2 2\n', '2 2\n1 2 2\n2 1 1\n', '1 3\n2 1 1\n1 1 1\n1 1 1\n', '6 3\n1 1 3\n1 4 6\n2 1 6\n'] })

t({ lv: 802, concept: 'データ構造: 区間の上位2つの和', title: '区間で1位と2位の合計', tags: ['データ構造'], io: '1行目に n q、2行目に整数列、続く q 行に「1 i x」(i番目をxに変更)または「2 l r」(質問、区間は2要素以上)が与えられます。', ask: '各質問について、区間内の最大値と2番目の最大値(同値も可)の和を出力してください。', h1: '素朴には区間をソートして上2つ。', h2: 'セグ木なら各ノードに(最大,2位)のペアを持ち、2ペアの4値から上2つを選んでマージする。', ref: 'n,q=map(int,input().split())\na=list(map(int,input().split()))\nfor _ in range(q):\n    t,x,y=map(int,input().split())\n    if t==1:\n        a[x-1]=y\n    else:\n        w=sorted(a[x-1:y])\n        print(w[-1]+w[-2])', tip: '「マージできる要約」ならセグ木に載る、の練習台。(最大,2位)の結合は4候補から上位2つを取るだけで結合律を満たす。', ins: ['5 3\n1 5 3 2 4\n2 1 5\n1 3 6\n2 2 3\n', '2 1\n7 7\n2 1 2\n', '4 2\n1 2 3 4\n2 1 2\n2 3 4\n', '3 3\n5 1 5\n2 1 3\n1 2 9\n2 1 3\n', '2 2\n1 2\n1 1 10\n2 1 2\n', '6 1\n3 1 4 1 5 9\n2 2 5\n'] })

t({ lv: 803, concept: 'データ構造: 区間掛け算と一点の値', title: '区間まるごと倍にして1点を読む', tags: ['データ構造'], io: '1行目に n q、2行目に整数列、続く q 行に「1 l r k」(l..r を k 倍)または「2 i」(i番目の値を質問)が与えられます。', ask: '各質問に対し、その時点の i 番目の値を出力してください。', h1: '素朴に区間を掛けても正しい。', h2: '一点取得だけなら「掛けた履歴」を差分的に持つ工夫(対数構造)もできる。Pythonの多倍長整数なら桁あふれの心配がない。', ref: 'n,q=map(int,input().split())\na=list(map(int,input().split()))\nfor _ in range(q):\n    parts=list(map(int,input().split()))\n    if parts[0]==1:\n        _,l,r,k=parts\n        for i in range(l-1,r):\n            a[i]*=k\n    else:\n        print(a[parts[1]-1])', tip: '加算の区間更新は差分配列で済むが、乗算は「積の差分」に置き換わる(割り算が要るのでゼロに注意)。演算が変わると使える道具が変わる好例。', ins: ['3 3\n1 2 3\n1 1 2 3\n2 1\n2 3\n', '2 2\n5 5\n1 1 1 0\n2 1\n', '4 3\n1 1 1 1\n1 1 4 2\n1 2 3 3\n2 2\n', '1 2\n7\n1 1 1 10\n2 1\n', '3 2\n2 4 6\n2 2\n2 3\n', '5 3\n1 2 3 4 5\n1 3 5 2\n2 4\n2 1\n'] })

t({ lv: 804, concept: 'データ構造: 区間chmaxと一点取得', title: '「最低保証」を区間にかける', tags: ['データ構造'], io: '1行目に n q、2行目に整数列、続く q 行に「1 l r x」(l..r の各値を max(自分, x) に更新)または「2 i」(質問)が与えられます。', ask: '各質問に対し、その時点の i 番目の値を出力してください。', h1: '各要素は上がるだけで下がらない。', h2: '素朴更新で正しい。大規模では遅延セグ木に「保留中のchmax値」を持たせる(単調なので合成は max だけ)。', ref: 'n,q=map(int,input().split())\na=list(map(int,input().split()))\nfor _ in range(q):\n    parts=list(map(int,input().split()))\n    if parts[0]==1:\n        _,l,r,x=parts\n        for i in range(l-1,r):\n            if a[i]<x:\n                a[i]=x\n    else:\n        print(a[parts[1]-1])', tip: 'chmax同士は「maxで合成できる」ので遅延伝播に素直に載る。加算と混ざると一気に難しくなり、Segment Tree Beatsという発展領域が待っている。', ins: ['3 3\n1 5 2\n1 1 3 3\n2 1\n2 2\n', '2 2\n4 4\n1 1 1 2\n2 1\n', '4 3\n0 0 0 0\n1 2 3 7\n2 2\n2 4\n', '1 2\n9\n1 1 1 1\n2 1\n', '5 3\n1 2 3 4 5\n1 1 5 3\n2 1\n2 5\n', '3 2\n5 5 5\n2 3\n2 1\n'] })

t({ lv: 805, concept: 'データ構造: 一点更新と接頭辞最大', title: '先頭からの最高記録クエリ', tags: ['データ構造'], io: '1行目に n q、2行目に整数列、続く q 行に「1 i x」(i番目をxに変更)または「2 k」(先頭k個の最大を質問)が与えられます。', ask: '各質問に対し、その時点の先頭 k 個の最大値を出力してください。', h1: '素朴に max(a[:k]) でよい。', h2: '接頭辞最大は「和」と違い引き算で戻せないので、更新があるならセグ木(区間max)が本命。', ref: 'n,q=map(int,input().split())\na=list(map(int,input().split()))\nfor _ in range(q):\n    t,x,*rest=map(int,input().split())\n    if t==1:\n        a[x-1]=rest[0]\n    else:\n        print(max(a[:x]))', tip: 'BITは「逆元のある演算(和・XOR)」の接頭辞に強く、maxのような戻せない演算は苦手(更新が増加方向のみなら可)。構造と演算の相性表を持とう。', ins: ['4 3\n1 3 2 4\n2 3\n1 2 0\n2 3\n', '2 2\n5 1\n2 1\n2 2\n', '3 3\n1 1 1\n1 3 9\n2 3\n2 2\n', '1 2\n4\n1 1 7\n2 1\n', '5 2\n5 4 3 2 1\n2 5\n2 1\n', '3 2\n2 9 4\n2 2\n2 3\n'] })

t({ lv: 806, concept: 'データ構造: 区間XORと一点取得', title: '区間まとめてXORして1点を読む', tags: ['データ構造', 'bit演算'], io: '1行目に n q、2行目に非負整数列、続く q 行に「1 l r x」(l..r の各値に x をXOR)または「2 i」(質問)が与えられます。', ask: '各質問に対し、その時点の i 番目の値を出力してください。', h1: 'XORは自分が自分の逆元。', h2: '差分配列のXOR版が成立する: d[l]^=x, d[r+1]^=x とし、接頭辞XORが各点の累積作用になる。', ref: 'n,q=map(int,input().split())\na=list(map(int,input().split()))\nd=[0]*(n+2)\nout=[]\nfor _ in range(q):\n    parts=list(map(int,input().split()))\n    if parts[0]==1:\n        _,l,r,x=parts\n        d[l]^=x\n        d[r+1]^=x\n    else:\n        i=parts[1]\n        acc=0\n        for j in range(1,i+1):\n            acc^=d[j]\n        out.append(a[i-1]^acc)\nprint(*out,sep="\\n")', tip: '「加算の差分配列」の成立条件は演算が可換群であること。XORもそうなので同じ形が動く。maxやANDでは崩れる、と対比すると理解が締まる。', ins: ['3 3\n1 2 3\n1 1 2 1\n2 1\n2 3\n', '2 2\n0 0\n1 1 2 5\n2 2\n', '4 4\n7 7 7 7\n1 2 3 7\n2 1\n2 2\n2 4\n', '1 2\n9\n1 1 1 9\n2 1\n', '5 3\n1 2 3 4 5\n1 1 5 1\n2 3\n2 5\n', '3 2\n4 4 4\n2 2\n2 1\n'] })

t({ lv: 807, concept: 'オフライン: 後勝ちペンキ塗りの最終盤面', title: '重ね塗りの最終的な色', tags: ['オフライン'], io: '1行目に 長さ n と回数 q、続く q 行に「l r c」(l..r を色 c で塗る。後の塗りが上書き)が与えられます。', ask: '全て塗り終えた後の各マスの色(初期は0)を空白区切りで出力してください。', h1: '素直に前から塗ると O(nq)。', h2: '逆順に処理して「まだ無色のマスだけ塗る」と各マスは1回しか塗られない(未処理位置の管理で高速化できる)。', ref: 'n,q=map(int,input().split())\nqs=[tuple(map(int,input().split())) for _ in range(q)]\na=[0]*(n+1)\nfor l,r,c in qs:\n    for i in range(l,r+1):\n        a[i]=c\nprint(*a[1:])', tip: '「後勝ち」は逆から見れば「先勝ち」。時間反転で上書きが確定塗りに変わり、Union-Findで“次の未塗り位置”へ飛べばO(nα)まで落ちる。', ins: ['5 2\n1 3 1\n2 4 2\n', '3 1\n1 3 9\n', '4 3\n1 4 1\n2 3 2\n3 3 3\n', '2 2\n1 1 5\n2 2 6\n', '1 1\n1 1 1\n', '6 2\n2 5 7\n1 1 4\n'] })

t({ lv: 808, concept: 'データ構造: 下位k個の合計の維持', title: '常に安い方からk個の合計', tags: ['ヒープ'], io: '1行目に k、2行目に到着する数の列が与えられます。', ask: '数が届くたびに「これまでの中で小さい方から高々k個の合計」を空白区切りで出力してください。', h1: '小さいk個だけ覚える。', h2: 'サイズkの最大ヒープ+合計変数。あふれたら最大を捨てて合計から引く。', ref: 'import heapq\nk=int(input())\na=list(map(int,input().split()))\nh=[]\ns=0\nout=[]\nfor x in a:\n    heapq.heappush(h,-x)\n    s+=x\n    if len(h)>k:\n        s+=heapq.heappop(h)\n    out.append(s)\nprint(*out)', tip: '「下位k個の門番」は最大ヒープ。合計を差分で保守すれば毎回の集計はO(log k)。上位k個版と対で書けるようにしたい。', ins: ['2\n5 1 3\n', '1\n4 2 9\n', '3\n1 2 3 4\n', '2\n2 2 2\n', '1\n7\n', '2\n9 8 7 6\n'] })

t({ lv: 809, concept: 'データ構造: 区間の最頻値クエリ', title: '区間で一番多い値はどれ', tags: ['データ構造'], io: '1行目に n q、2行目に整数列、続く q 行に区間 l r が与えられます。', ask: '各区間の最頻値を出力してください(同数なら値の小さい方)。', h1: '各クエリでCounterを作る。', h2: '区間最頻値(range mode)は和や最大と違いマージできないため、大規模では平方分割+前計算という重い道具が要る。', ref: 'from collections import Counter\nn,q=map(int,input().split())\na=list(map(int,input().split()))\nfor _ in range(q):\n    l,r=map(int,input().split())\n    c=Counter(a[l-1:r])\n    best=min(c.items(),key=lambda kv:(-kv[1],kv[0]))\n    print(best[0])', tip: '最頻値は「部分の答えから全体の答えが出ない」代表例で、セグ木に載らない。載る統計と載らない統計の境界を知ると構造選びが速くなる。', ins: ['5 2\n1 2 2 3 3\n1 5\n1 2\n', '3 1\n7 7 7\n1 3\n', '4 2\n1 2 3 4\n2 3\n1 4\n', '6 2\n5 5 1 1 1 5\n1 6\n1 4\n', '2 1\n9 3\n1 2\n', '5 1\n2 2 8 8 1\n2 5\n'] })

t({ lv: 810, concept: 'データ構造: 区間LCMクエリ', title: '区間の最小公倍数', tags: ['データ構造', '数論'], io: '1行目に n q、2行目に正整数列、続く q 行に区間 l r が与えられます。', ask: '各区間の全要素の最小公倍数を出力してください。', h1: 'lcm(a,b) は a×b÷gcd(a,b)。', h2: '結合的で冪等なので、更新なしならSparse Tableにも載る。Pythonなら値の爆発も気にしなくてよい。', ref: 'import math\nn,q=map(int,input().split())\na=list(map(int,input().split()))\nfor _ in range(q):\n    l,r=map(int,input().split())\n    v=1\n    for x in a[l-1:r]:\n        v=v*x//math.gcd(v,x)\n    print(v)', tip: 'gcdの区間クエリと双対の関係。lcmは値が急速に大きくなるので、固定長整数の言語ではmod付きや素因数の最大指数管理に切り替える。', ins: ['4 2\n2 3 4 5\n1 2\n1 4\n', '3 1\n6 10 15\n1 3\n', '2 2\n7 7\n1 1\n1 2\n', '5 1\n1 2 3 4 5\n2 4\n', '3 2\n8 12 18\n1 2\n2 3\n', '1 1\n9\n1 1\n'] })

t({ lv: 811, concept: '累積和: 区間の偶数の個数クエリ', title: '区間に偶数はいくつあるか', tags: ['累積和'], io: '1行目に n q、2行目に整数列、続く q 行に区間 l r が与えられます。', ask: '各区間に含まれる偶数の個数を出力してください。', h1: '偶数を1、奇数を0とみなす。', h2: '0/1の接頭辞和を作れば各クエリO(1)。', ref: 'n,q=map(int,input().split())\na=list(map(int,input().split()))\npre=[0]\nfor x in a:\n    pre.append(pre[-1]+(1 if x%2==0 else 0))\nfor _ in range(q):\n    l,r=map(int,input().split())\n    print(pre[r]-pre[l-1])', tip: '「条件を満たす個数の区間クエリ」は条件を0/1に写して和にするのが第一手。条件が動的に変わるならBITやウェーブレット行列の世界へ。', ins: ['5 2\n1 2 3 4 5\n1 5\n2 4\n', '3 1\n2 4 6\n1 3\n', '4 2\n1 3 5 7\n1 4\n2 3\n', '2 1\n0 1\n1 2\n', '6 2\n2 2 1 1 2 2\n2 5\n1 6\n', '1 1\n8\n1 1\n'] })

t({ lv: 812, concept: '累積和: 区間積の末尾ゼロの数', title: '区間の積の末尾に並ぶ0', tags: ['累積和', '数論'], io: '1行目に n q、2行目に正整数列、続く q 行に区間 l r が与えられます。', ask: '各区間の全要素の積を10進表記したとき、末尾に並ぶ0の個数を出力してください。', h1: '末尾の0は因数の10、つまり2と5のペアの数。', h2: '各要素の因数2と因数5の個数を接頭辞和にし、区間ごとに min(2の合計, 5の合計)。', ref: 'n,q=map(int,input().split())\na=list(map(int,input().split()))\ndef cnt(x,p):\n    c=0\n    while x%p==0:\n        x//=p\n        c+=1\n    return c\np2=[0]\np5=[0]\nfor x in a:\n    p2.append(p2[-1]+cnt(x,2))\n    p5.append(p5[-1]+cnt(x,5))\nfor _ in range(q):\n    l,r=map(int,input().split())\n    print(min(p2[r]-p2[l-1],p5[r]-p5[l-1]))', tip: '巨大な積を作らず因数の個数だけ数えるのが本質(階乗の末尾0のルジャンドル式と同じ思想)。積の性質は素因数の帳簿で追う。', ins: ['3 2\n4 5 6\n1 2\n1 3\n', '2 1\n10 10\n1 2\n', '4 2\n2 5 2 5\n1 4\n2 3\n', '1 1\n7\n1 1\n', '5 1\n8 125 3 1 1\n1 5\n', '3 1\n20 50 4\n1 3\n'] })

t({ lv: 813, concept: '数え上げ: 全て相異なる固定長の窓', title: '重複のない窓を数える', tags: ['数え上げ', 'ハッシュ'], io: '1行目に窓の長さ k、2行目に整数列が与えられます。', ask: '長さ k の連続区間のうち、要素が全て相異なるものの個数を出力してください。', h1: '窓内の頻度を差分更新する。', h2: '「重複ペアの数」を窓のスライドで保守し、0のときだけ数える。', ref: 'from collections import Counter\nk=int(input())\na=list(map(int,input().split()))\nn=len(a)\nif n<k:\n    print(0)\nelse:\n    c=Counter(a[:k])\n    dup=sum(1 for v in c.values() if v>1)\n    cnt=1 if dup==0 else 0\n    for i in range(k,n):\n        out=a[i-k]\n        c[out]-=1\n        if c[out]==1:\n            dup-=1\n        x=a[i]\n        if c[x]==1:\n            dup+=1\n        c[x]+=1\n        if dup==0:\n            cnt+=1\n    print(cnt)', tip: '窓の性質は作り直さず「出る1個・入る1個」の影響だけで保守する。違反数(dup)という補助カウンタを持つのが定数時間更新のコツ。', ins: ['3\n1 2 3 2 1\n', '2\n1 1 1\n', '1\n5 5\n', '3\n1 2 3\n', '2\n1 2 1 2\n', '4\n1 2 3 4 1\n'] })

t({ lv: 814, concept: '配列: 右がすべて低いビルの数', title: '海が見えるビルの数', tags: ['配列'], io: 'ビルの高さの列(左が内陸、右が海)が1行で空白区切りで与えられます。', ask: '自分より右にあるビルが全て自分より低い(海が見える)ビルの数を出力してください。', h1: '右から見ると簡単になる。', h2: '右からの最大値を更新しながら、それを超えるたびに数える。', ref: 'a=list(map(int,input().split()))\nmx=0\ncnt=0\nfor x in reversed(a):\n    if x>mx:\n        cnt+=1\n        mx=x\nprint(cnt)', tip: '「右側全部との比較」は右からの走査で接尾辞最大1個に潰れる。左右どちらから読むかで計算量が変わる問題は多い。', ins: ['4 2 3 1\n', '1 2 3\n', '3 3 3\n', '5\n', '10 1 10 1\n', '2 2 1\n'] })

t({ lv: 815, concept: 'データ構造: 全体加算できるスタック', title: '全要素に一括で足せるスタック', tags: ['データ構造', 'スタック'], io: '1行目にクエリ数 q、続く q 行に「push x」「pop」(取り出した値を出力)「addall d」(全要素に d を加算)のいずれかが与えられます(popは空に対して来ない)。', ask: '各 pop に対して取り出した値を出力してください。', h1: '毎回全要素に足すと遅い。', h2: '「これまでの全体加算の合計 offset」を1つ持ち、pushは x−offset を積み、popは +offset して返す。', ref: 'q=int(input())\nst=[]\noffset=0\nfor _ in range(q):\n    parts=input().split()\n    if parts[0]=="push":\n        st.append(int(parts[1])-offset)\n    elif parts[0]=="pop":\n        print(st.pop()+offset)\n    else:\n        offset+=int(parts[1])', tip: '「全体への一様な作用は代表値1つに遅延させる」発想は、遅延セグ木のlazyの最小模型。作用が可換群なら何にでも応用できる。', ins: ['5\npush 1\npush 2\naddall 10\npop\npop\n', '3\npush 5\npop\npush 7\n', '4\npush 0\naddall 3\naddall 4\npop\n', '6\npush 1\naddall 1\npush 1\npop\npop\naddall 5\n', '2\npush 9\npop\n', '5\naddall 100\npush 1\npop\npush 2\npop\n'] })

export const CATALOG = TASKS
