// 生成タスク 第76波：各レベル3問化フェーズ(3)。lv132〜182 の薄い49段に3問目を追加。
// 数論入門/進数/bit/リスト/文字列帯。クラスタ3問まで可・言い換え水増し禁止。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 132, concept: '数論: 素因数の平均', title: '素因数をならすと', tags: ['数論'], io: '2以上の整数 n が1行で与えられます。', ask: 'n の素因数(重複込み)の平均を小数第1位まで出力してください。', h1: '試し割りで素因数を全部集める。', h2: '合計と個数を持てばリストは不要。', ref: 'n=int(input())\ns=0\nc=0\np=2\nwhile p*p<=n:\n    while n%p==0:\n        s+=p\n        c+=1\n        n//=p\n    p+=1\nif n>1:\n    s+=n\n    c+=1\nprint(f"{s/c:.1f}")', tip: '素因数の和(sopfr)は「整数の対数」とも呼ばれ、乗法を加法に写す性質 sopfr(ab)=sopfr(a)+sopfr(b) を持つ。平均はそれをΩで割った量。', ins: ['12\n', '8\n', '7\n', '30\n', '100\n', '9\n'] })

t({ lv: 133, concept: '数論: n番目の過剰数', title: '過剰数を順に数えてn番目', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: '過剰数(真の約数の和が自分より大きい数)を小さい順に並べたときの n 番目を出力してください。', h1: '判定関数を作って順に数える。', h2: '真の約数和は√までの試し割りで。', ref: 'n=int(input())\ndef s(x):\n    total=1 if x>1 else 0\n    i=2\n    while i*i<=x:\n        if x%i==0:\n            total+=i\n            if i!=x//i:\n                total+=x//i\n        i+=1\n    return total\nc=0\nx=1\nwhile c<n:\n    x+=1\n    if s(x)>x:\n        c+=1\nprint(x)', tip: '最小の過剰数は12、奇数の過剰数は945まで現れない。判定→n番目への昇格は「数える関数+while」の定型で、どの数クラスにも使い回せる。', ins: ['1\n', '2\n', '5\n', '10\n', '3\n', '21\n'] })

t({ lv: 134, concept: '整数: 桁和が素数か', title: '桁を足したら素数になるか', tags: ['整数', '数論'], io: '正整数 n が1行で与えられます。', ask: 'n の各桁の和が素数なら yes、そうでなければ no を出力してください。', h1: 'まず桁和を作る。', h2: '桁和は高々小さい値なので試し割り判定で十分。', ref: 'n=input()\ns=sum(int(c) for c in n)\ndef isp(x):\n    if x<2:\n        return False\n    i=2\n    while i*i<=x:\n        if x%i==0:\n            return False\n        i+=1\n    return True\nprint("yes" if isp(s) else "no")', tip: '「変換してから判定」の2段合成の最小形。桁和は9の剰余と合同なので、3の倍数の桁和は3の倍数、という数論の接点も見える。', ins: ['12\n', '29\n', '10\n', '999\n', '1\n', '47\n'] })

t({ lv: 135, concept: '数論: エマープの判定', title: '逆から読んでも素数、でも別の素数', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: 'n が素数で、桁を逆順にした数も素数で、かつ両者が異なる(エマープ)なら yes、そうでなければ no を出力してください。', h1: '逆順の数を作って両方判定する。', h2: '回文素数(逆順が同じ)はエマープではない。', ref: 'n=int(input())\ndef isp(x):\n    if x<2:\n        return False\n    i=2\n    while i*i<=x:\n        if x%i==0:\n            return False\n        i+=1\n    return True\nr=int(str(n)[::-1])\nprint("yes" if isp(n) and isp(r) and n!=r else "no")', tip: '13↔31、17↔71 などがエマープ(emirpはprimeの逆綴り)。「両方とも○○、ただし同一は除く」という3条件の合成は仕様の読み落としが出やすい形。', ins: ['13\n', '17\n', '11\n', '23\n', '19\n', '10\n'] })

t({ lv: 136, concept: 'bit演算: 1のかたまりの数(2進)', title: '2進数の1のグループを数える', tags: ['bit演算'], io: '正整数 n が1行で与えられます。', ask: '2進表記で連続する1の塊(グループ)の個数を出力してください。', h1: '「1が始まる瞬間」を数える。', h2: 'bin文字列で今が1・前が0(または先頭)の位置をカウント。ビット演算なら popcount(n & ~(n>>1)) でも。', ref: 's=bin(int(input()))[2:]\ncnt=0\nfor i,c in enumerate(s):\n    if c=="1" and (i==0 or s[i-1]=="0"):\n        cnt+=1\nprint(cnt)', tip: 'n & ~(n>>1) は「各1の塊の最上位だけ」を残すマスク演算。文字列で数える素朴版とビット演算版の答え合わせは良い練習になる。', ins: ['5\n', '7\n', '10\n', '1\n', '89\n', '240\n'] })

t({ lv: 137, concept: '整数: 桁が厳密増加か', title: '桁がずっと増え続けるか', tags: ['整数'], io: '正整数 n が1行で与えられます。', ask: '十進の桁が左から右へ厳密に増加している(同じ桁も許さない)なら yes、そうでなければ no を出力してください。', h1: '隣接する桁を比べる。', h2: 'all(s[i]<s[i+1]) の1行。', ref: 's=input()\nprint("yes" if all(s[i]<s[i+1] for i in range(len(s)-1)) else "no")', tip: '「単調増加(広義)」と「厳密増加」は等号1つの違いで別の集合になる。厳密増加の数は桁の部分集合と1対1なので高々2^9−1個しかない。', ins: ['123\n', '1223\n', '135\n', '9\n', '321\n', '12345\n'] })

t({ lv: 138, concept: '数論: ミュンヒハウゼン数の判定', title: '桁が自分自身を持ち上げる数', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: '各桁 d について d の d 乗(桁0の寄与は0)を合計した値が n 自身に等しい(ミュンヒハウゼン数)なら yes、そうでなければ no を出力してください。', h1: 'アームストロング数の指数を「桁自身」に変えた仲間。', h2: 'd**d を足すだけ(d=0は0)。', ref: 'n=input()\ns=sum(int(c)**int(c) if c!="0" else 0 for c in n)\nprint("yes" if s==int(n) else "no")', tip: '3435=3³+4⁴+3³+5⁵ が(1以外で)唯一のミュンヒハウゼン数。ほら吹き男爵が自分の髪を引っ張って沼から脱出した逸話が名前の由来。', ins: ['3435\n', '1\n', '153\n', '100\n', '3436\n', '55\n'] })

t({ lv: 139, concept: '整数: 最も多く現れる桁', title: '一番よく出てくる数字', tags: ['整数'], io: '正整数 n が1行で与えられます。', ask: '十進表記で最も多く現れる桁を出力してください(同数なら小さい方)。', h1: '桁を数えるのは文字のCounter。', h2: '(−回数, 桁) の最小で同数処理。', ref: 'from collections import Counter\nc=Counter(input())\nprint(min(c.items(),key=lambda kv:(-kv[1],kv[0]))[0])', tip: '数を文字列として集計する常套手段。ベンフォードの法則(先頭桁は1が多い)のような統計遊びへの入り口にもなる。', ins: ['112233\n', '9\n', '10203\n', '777123\n', '123123\n', '55550\n'] })

t({ lv: 140, concept: 'リスト: 最大ドローダウン', title: '高値からの最大の下落幅', tags: ['リスト'], io: '株価の列が1行で空白区切りで与えられます。', ask: 'i<j で 価格[i] − 価格[j] の最大値(高値から安値への最大下落幅、下落がなければ0)を出力してください。', h1: '1回売買の最大利益の鏡像。', h2: 'ここまでの最大値を持ち回り、そこからの下落を測る。', ref: 'a=list(map(int,input().split()))\npeak=a[0]\nbest=0\nfor x in a[1:]:\n    if peak-x>best:\n        best=peak-x\n    if x>peak:\n        peak=x\nprint(best)', tip: '投資のリスク指標として現役の量。最大利益(min持ち回り)と最大下落(max持ち回り)は完全に対称で、片方書ければもう片方は写経になる。', ins: ['7 1 5 3 6 4\n', '1 2 3\n', '9 5 8 2\n', '5\n', '3 3 3\n', '10 4 12 2\n'] })

t({ lv: 141, concept: '数論: n以上で最小のフィボナッチ数', title: '次のフィボナッチ数はどれ', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: 'n 以上で最小のフィボナッチ数(1,1,2,3,5,…)を出力してください。', h1: '生成しながら初めてn以上になった項を返す。', h2: '2変数の持ち回りで十分。', ref: 'n=int(input())\na,b=1,1\nwhile a<n:\n    a,b=b,a+b\nprint(a)', tip: '「以下で最大」と「以上で最小」は探索の止め時が違うだけの双子。丸め・切り上げ・スナップ処理の考え方はどの数列でも同じ。', ins: ['10\n', '13\n', '1\n', '100\n', '4\n', '90\n'] })

t({ lv: 142, concept: '整数: n以上で最小の平方数', title: '次の平方数まで', tags: ['整数'], io: '正整数 n が1行で与えられます。', ask: 'n 以上で最小の平方数を出力してください。', h1: '√nの切り上げを2乗する。', h2: 'isqrt(n−1)+1 の2乗、または isqrt で場合分け。', ref: 'import math\nn=int(input())\nr=math.isqrt(n)\nprint(r*r if r*r==n else (r+1)*(r+1))', tip: 'isqrtは切り捨てなので「ちょうど平方数か」の場合分けが要る。天井の平方根は isqrt(n−1)+1 という引き算トリックでも書ける。', ins: ['10\n', '16\n', '1\n', '99\n', '50\n', '2\n'] })

t({ lv: 143, concept: 'リスト: つり合いの位置の個数', title: 'バランスが取れる場所は何箇所', tags: ['リスト', '累積和'], io: '整数列が1行で空白区切りで与えられます。', ask: '「その位置より左の総和と右の総和が等しい」位置の個数を出力してください。', h1: '最初の1箇所を探す問題の全数版。', h2: '左の和を走らせ、右の和は全体から引いて比べる。', ref: 'a=list(map(int,input().split()))\ntotal=sum(a)\nleft=0\ncnt=0\nfor x in a:\n    if left==total-left-x:\n        cnt+=1\n    left+=x\nprint(cnt)', tip: '「最初の1つ」を「全部数える」に変えるとbreakが消えて走査が最後まで進む。仕様変更に強いのはどちらの形かを考える練習にもなる。', ins: ['1 7 3 6 5 6\n', '0 0 0\n', '1 2 3\n', '2 0 2\n', '5\n', '1 -1 1 -1 1\n'] })

t({ lv: 144, concept: '進数: k進法での桁数', title: 'k進法に直すと何桁か', tags: ['進数'], io: 'n k が空白区切りで1行で与えられます (n≥1, k≥2)。', ask: 'n を k 進法で表したときの桁数を出力してください。', h1: 'kで割り続けた回数。', h2: 'whileで割りながら数える(logは誤差の罠)。', ref: 'n,k=map(int,input().split())\nc=0\nwhile n:\n    n//=k\n    c+=1\nprint(c)', tip: 'math.log(n,k)は浮動小数の誤差でちょうど累乗の境目を踏み外すことがある。桁数は整数の割り算ループが最も信頼できる。', ins: ['10 2\n', '8 2\n', '80 3\n', '1 5\n', '255 16\n', '1000 10\n'] })

t({ lv: 145, concept: '進数: k進法での最大の桁', title: 'k進法で一番大きい桁', tags: ['進数'], io: 'n k が空白区切りで1行で与えられます (n≥1, k≥2)。', ask: 'n を k 進法で表したときの最大の桁の値を出力してください。', h1: '余りを集めながら最大を取る。', h2: 'n%k の最大値を while で。', ref: 'n,k=map(int,input().split())\nbest=0\nwhile n:\n    if n%k>best:\n        best=n%k\n    n//=k\nprint(best)', tip: '進数変換の余り列は「下の桁から」出てくる。桁の最大・和・種類など集計だけなら並べ替え不要で、変換と集計が1つのループに融合できる。', ins: ['10 2\n', '100 3\n', '255 16\n', '7 8\n', '26 5\n', '999 10\n'] })

t({ lv: 146, concept: 'bit演算: 最下位の1を消す', title: '一番下の旗を降ろす', tags: ['bit演算'], io: '正整数 n が1行で与えられます。', ask: 'n の2進表記で最下位の立っているビットを0にした値を出力してください。', h1: '有名な1行のトリックがある。', h2: 'n & (n−1)。', ref: 'n=int(input())\nprint(n&(n-1))', tip: 'n&(n−1) はKernighanのpopcount、2べき判定、Fenwick木の添字操作と、ビット界の万能ナイフ。n−1が下位ビットをどう変えるかを紙で追うと腑に落ちる。', ins: ['6\n', '8\n', '7\n', '1\n', '12\n', '255\n'] })

t({ lv: 147, concept: '文字列: 奇数番目の文字', title: '1つおきに読む(奇数側)', tags: ['文字列'], io: '文字列が1行で与えられます。', ask: '奇数番目(1,3,5,…文字目)の文字を順につなげて出力してください。', h1: '0始まりの添字では偶数位置。', h2: 'スライス s[::2]。', ref: 'print(input()[::2])', tip: '偶数番目版とペアで覚えるステップスライス。[1::2]と[::2]で文字列が2つの位相に分解できる、と見ると信号処理のダウンサンプリングに繋がる。', ins: ['abcdef\n', 'python\n', 'a\n', 'xy\n', 'hello world\n', '12345\n'] })

t({ lv: 148, concept: '文字列: 最長連続の文字はどれ', title: '一番長く続いた文字', tags: ['文字列'], io: '英小文字の文字列が1行で与えられます。', ask: '同じ文字が連続する最長の塊を作っている文字を出力してください(同長なら先に現れた方)。', h1: '長さだけでなく文字も記録する。', h2: '「より長いときだけ」更新すれば先勝ちになる。', ref: 's=input()\nbest=1\nbc=s[0]\nrun=1\nfor i in range(1,len(s)):\n    if s[i]==s[i-1]:\n        run+=1\n    else:\n        run=1\n    if run>best:\n        best=run\n        bc=s[i]\nprint(bc)', tip: '「最大値そのもの」と「最大を実現したもの」を対で追うargmaxの文字列版。タイブレークは更新の不等号(>か>=)で制御する。', ins: ['aabbbcc\n', 'abc\n', 'zzz\n', 'abbcccbb\n', 'q\n', 'aabbaa\n'] })

t({ lv: 149, concept: '数論: スフェニック数の判定', title: '3つの異なる素数の積か', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: 'n が相異なる3つの素数の積(スフェニック数、例 30=2×3×5)なら yes、そうでなければ no を出力してください。', h1: '素因数分解して形を見る。', h2: '素因数がちょうど3種類で、それぞれ指数1。', ref: 'n=int(input())\nps=[]\np=2\nwhile p*p<=n:\n    if n%p==0:\n        e=0\n        while n%p==0:\n            n//=p\n            e+=1\n        ps.append(e)\n    p+=1\nif n>1:\n    ps.append(1)\nprint("yes" if len(ps)==3 and all(e==1 for e in ps) else "no")', tip: '半素数(2素数の積)の3素数版。指数のリスト(素因数の型)で数を分類する見方は、約数の個数の公式や平方因子の議論すべての土台になる。', ins: ['30\n', '60\n', '105\n', '8\n', '42\n', '15\n'] })

t({ lv: 151, concept: '行列: 反対称行列の判定', title: '転置すると符号が反転する行列', tags: ['行列'], io: '1行目に n、続く n 行に n×n の行列が与えられます。', ask: '全ての i,j で A[j][i] が −A[i][j] に等しい(反対称行列、対角は0)なら yes、そうでなければ no を出力してください。', h1: '対称判定の符号を変えるだけ。', h2: '対角成分が0であることも条件に含まれる(自動的に)。', ref: 'n=int(input())\nA=[list(map(int,input().split())) for _ in range(n)]\nok=all(A[j][i]==-A[i][j] for i in range(n) for j in range(n))\nprint("yes" if ok else "no")', tip: '反対称は対称の双子で、任意の正方行列は対称+反対称に一意分解できる。外積・回転の生成子など物理にも顔を出す構造。', ins: ['2\n0 2\n-2 0\n', '2\n0 2\n2 0\n', '1\n0\n', '3\n0 1 -2\n-1 0 3\n2 -3 0\n', '2\n1 0\n0 -1\n', '3\n0 5 0\n-5 0 0\n0 0 0\n'] })

t({ lv: 152, concept: '行列: 対角行列の判定', title: '対角以外はぜんぶ0か', tags: ['行列'], io: '1行目に n、続く n 行に n×n の行列が与えられます。', ask: '対角成分以外が全て0(対角行列)なら yes、そうでなければ no を出力してください(対角の値は何でもよい)。', h1: 'i≠j の場所だけ確かめる。', h2: 'all(A[i][j]==0 for i≠j)。', ref: 'n=int(input())\nA=[list(map(int,input().split())) for _ in range(n)]\nok=all(A[i][j]==0 for i in range(n) for j in range(n) if i!=j)\nprint("yes" if ok else "no")', tip: '単位行列は「対角行列かつ対角が全部1」。行列の特別な形(対角・上三角・置換)の判定を並べて書くと、条件式のパターンが身につく。', ins: ['2\n3 0\n0 5\n', '2\n1 1\n0 2\n', '1\n7\n', '3\n1 0 0\n0 0 0\n0 0 9\n', '2\n0 0\n0 0\n', '3\n1 0 1\n0 1 0\n0 0 1\n'] })

t({ lv: 153, concept: '行列: 非ゼロ要素の位置一覧', title: '疎行列の中身だけ書き出す', tags: ['行列'], io: '1行目に H W、続く H 行に行列が与えられます。', ask: '0でない要素を行優先(上から下、左から右)の順に「行 列 値」(1始まり)で1行ずつ出力してください(1つも無ければ none)。', h1: '二重ループで0以外を拾う。', h2: '見つからなかったときの none をフラグか件数で。', ref: 'h,w=map(int,input().split())\ng=[list(map(int,input().split())) for _ in range(h)]\nfound=False\nfor i in range(h):\n    for j in range(w):\n        if g[i][j]!=0:\n            print(i+1,j+1,g[i][j])\n            found=True\nif not found:\n    print("none")', tip: 'ほとんど0の行列は(行,列,値)の3つ組リスト(COO形式)で持つのが疎行列表現の第一歩。scipy.sparseの内部もこの発想でできている。', ins: ['2 2\n0 3\n0 0\n', '2 3\n1 0 2\n0 0 3\n', '2 2\n0 0\n0 0\n', '1 1\n5\n', '3 1\n0\n7\n0\n', '2 2\n1 2\n3 4\n'] })

t({ lv: 154, concept: '数論: 素数階乗(プリモリアル)', title: '素数だけの階乗', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: '小さい方から n 個の素数の積(プリモリアル)を出力してください。', h1: '素数を順に見つけながら掛ける。', h2: '試し割り判定で次の素数へ進む。', ref: 'n=int(input())\ndef isp(x):\n    if x<2:\n        return False\n    i=2\n    while i*i<=x:\n        if x%i==0:\n            return False\n        i+=1\n    return True\np=1\nx=1\nc=0\nwhile c<n:\n    x+=1\n    if isp(x):\n        p*=x\n        c+=1\nprint(p)', tip: 'ユークリッドの素数無限性の証明に出てくる「素数の積+1」の部品。階乗より速く増え、n#+1が素数になるかは今も個別に探索されている。', ins: ['1\n', '2\n', '3\n', '5\n', '4\n', '8\n'] })

t({ lv: 155, concept: '数論: n番目の合成数', title: '合成数だけを数えていく', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: '合成数(1でも素数でもない数)を小さい順に並べたときの n 番目を出力してください。', h1: '4から順に判定して数える。', h2: '素数判定の否定+1除外。', ref: 'n=int(input())\ndef isp(x):\n    if x<2:\n        return False\n    i=2\n    while i*i<=x:\n        if x%i==0:\n            return False\n        i+=1\n    return True\nc=0\nx=3\nwhile c<n:\n    x+=1\n    if not isp(x):\n        c+=1\nprint(x)', tip: 'n番目の素数と対をなす1問。素数の密度が薄くなるにつれ合成数の密度は1に近づく、という補集合の視点で眺めると味がある。', ins: ['1\n', '2\n', '5\n', '10\n', '3\n', '20\n'] })

t({ lv: 156, concept: '数論: n以下の完全べき乗の個数', title: '累乗の形の数を数える', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: '1 以上 n 以下で a^b (a≥2, b≥2) の形に書ける数(1は含めない)の個数を出力してください(16=2⁴=4²のような重複は1回だけ数える)。', h1: '重複が出るので集合に入れる。', h2: 'bを2から、aを2から回して n 以下を集める。', ref: 'n=int(input())\ns=set()\nb=2\nwhile 2**b<=n:\n    a=2\n    while a**b<=n:\n        s.add(a**b)\n        a+=1\n    b+=1\nprint(len(s))', tip: '「数える前に集合で重複を潰す」のが完全べきの定石。個数は√n+∛n−(共通)…と包除でも書けるが、集合の方が間違えない。', ins: ['10\n', '16\n', '1\n', '100\n', '3\n', '64\n'] })

t({ lv: 157, concept: '数論: 奇数の約数の総和', title: '奇数の約数だけ足す', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: 'n の約数のうち奇数であるものの総和を出力してください。', h1: '約数を列挙して奇数だけ足す。', h2: '√nまでの対で列挙し、それぞれ奇数か確かめる。', ref: 'n=int(input())\ns=0\ni=1\nwhile i*i<=n:\n    if n%i==0:\n        if i%2==1:\n            s+=i\n        j=n//i\n        if j!=i and j%2==1:\n            s+=j\n    i+=1\nprint(s)', tip: '奇数約数の和は「nから2を全部取り除いた奇部のσ」と一致する。偶数約数の和(既出)との合計がσ(n)になる検算もできる。', ins: ['12\n', '9\n', '16\n', '30\n', '1\n', '45\n'] })

t({ lv: 158, concept: 'DP: グリッドの最大経路和', title: '右と下だけで進む最大の収穫', tags: ['DP'], io: '1行目に H W、続く H 行に整数の格子が与えられます。左上から右下へ、右か下にだけ進みます。', ask: '通ったマスの合計の最大を出力してください。', h1: '最小経路和のmax版。', h2: 'dp[i][j] = g[i][j] + max(上, 左)。', ref: 'h,w=map(int,input().split())\ng=[list(map(int,input().split())) for _ in range(h)]\ndp=[[0]*w for _ in range(h)]\nfor i in range(h):\n    for j in range(w):\n        best=0\n        if i>0 and j>0:\n            best=max(dp[i-1][j],dp[i][j-1])\n        elif i>0:\n            best=dp[i-1][j]\n        elif j>0:\n            best=dp[i][j-1]\n        dp[i][j]=g[i][j]+best\nprint(dp[h-1][w-1])', tip: 'min↔maxの入れ替えでDPの骨格が不変なことを確かめる鏡像問題。maxだと「負のマスを避ける」判断が自動で入るのが面白い違い。', ins: ['2 2\n1 2\n3 4\n', '2 3\n1 -5 3\n2 4 -1\n', '1 1\n7\n', '3 3\n1 1 1\n1 9 1\n1 1 1\n', '2 2\n-1 -2\n-3 -4\n', '1 4\n1 2 3 4\n'] })

t({ lv: 159, concept: '数論: ルース=アーロン・ペアの判定', title: '714と715の秘密', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: 'n と n+1 の「素因数の和(重複込み)」が等しい(ルース=アーロン・ペア)なら yes、そうでなければ no を出力してください。', h1: '素因数の和を関数にする。', h2: '2つの数に同じ関数を適用して比較。', ref: 'n=int(input())\ndef sopfr(x):\n    s=0\n    p=2\n    while p*p<=x:\n        while x%p==0:\n            s+=p\n            x//=p\n        p+=1\n    if x>1:\n        s+=x\n    return s\nprint("yes" if sopfr(n)==sopfr(n+1) else "no")', tip: '714(ベーブ・ルースの本塁打記録)と715(ハンク・アーロンが更新した数)から命名。エルデシュがこの遊びに本気の論文を書いた逸話つき。', ins: ['714\n', '5\n', '8\n', '15\n', '77\n', '20\n'] })

t({ lv: 160, concept: '最適化: 粗密2段階のグリッドサーチ', title: 'ざっくり探してから細かく', tags: ['最適化'], io: '1行目に a b c (二次関数 f(x)=a(x−b)²+c)、2行目に探索範囲 lo hi が与えられます(a>0、bは整数で範囲内)。', ask: 'まず10刻みで範囲を粗く探索して最良点を見つけ、その±10の範囲を1刻みで細かく探索して f を最小にする整数 x を出力してください。', h1: '2回のループで段階的に絞る。', h2: '粗探索の最良点の近傍だけ細かく見る(この問題設定では厳密最小に一致する)。', ref: 'a,b,c=map(int,input().split())\nlo,hi=map(int,input().split())\ndef f(x):\n    return a*(x-b)**2+c\nbest=lo\nx=lo\nwhile x<=hi:\n    if f(x)<f(best):\n        best=x\n    x+=10\nlo2=max(lo,best-10)\nhi2=min(hi,best+10)\nans=lo2\nfor x in range(lo2,hi2+1):\n    if f(x)<f(ans):\n        ans=x\nprint(ans)', tip: '粗→密の2段階は、単峰性があるときに探索回数を劇的に減らす実務ワザ。ハイパーパラメータ探索でも「対数スケールで粗く→線形で細かく」が定番。', ins: ['1 37 5\n0 100\n', '2 8 0\n0 50\n', '1 0 3\n-20 20\n', '3 95 1\n0 100\n', '1 50 0\n0 100\n', '5 13 2\n0 30\n'] })

t({ lv: 161, concept: '数列: 単調性の分類', title: '上り坂か下り坂か平らか', tags: ['数列'], io: '整数列(2個以上)が1行で空白区切りで与えられます。', ask: '厳密増加なら increasing、厳密減少なら decreasing、全要素が等しいなら constant、どれでもなければ none を出力してください。', h1: '3つの述語を順に確かめる。', h2: 'all(...)を3回書くのが素直。', ref: 'a=list(map(int,input().split()))\nif all(x<y for x,y in zip(a,a[1:])):\n    print("increasing")\nelif all(x>y for x,y in zip(a,a[1:])):\n    print("decreasing")\nelif all(x==y for x,y in zip(a,a[1:])):\n    print("constant")\nelse:\n    print("none")', tip: '分類問題は「排他的な述語を優先順に並べる」と読みやすい。時系列データの傾向ラベリングの最小版でもある。', ins: ['1 2 3\n', '3 2 1\n', '5 5 5\n', '1 3 2\n', '1 2\n', '2 2 3\n'] })

t({ lv: 162, concept: '数え上げ: 絶対値が同じペアの数', title: '符号違いのそっくりさん', tags: ['数え上げ'], io: '整数列が1行で空白区切りで与えられます。', ask: 'i<j で |a[i]| と |a[j]| が等しいペアの個数を出力してください。', h1: '絶対値で集計する。', h2: '絶対値ごとの個数 c から C(c,2) を足す。', ref: 'from collections import Counter\nc=Counter(abs(x) for x in map(int,input().split()))\nprint(sum(v*(v-1)//2 for v in c.values()))', tip: '「変換してからペア数え」の合成。キーを絶対値・偶奇・mod kに替えるだけで別の問題になる、Counterペア勘定の応用形。', ins: ['1 -1 2\n', '3 3 -3\n', '1 2 3\n', '-5 5\n', '0 0\n', '2 -2 2 -2\n'] })

t({ lv: 163, concept: 'ソート: マージの比較回数', title: '合流にかかった比較の数', tags: ['ソート'], io: '1行目と2行目にソート済みの整数列が与えられます。', ask: '標準的なマージ(両先頭を比較し小さい方を取る。どちらかが尽きたら残りは比較なしで移す)で2列を併合するときの比較回数を出力してください。', h1: '比較のたびにカウンタを増やす。', h2: 'whileの条件が両方生きている間だけ比較が発生する。', ref: 'a=list(map(int,input().split()))\nb=list(map(int,input().split()))\ni=j=c=0\nwhile i<len(a) and j<len(b):\n    c+=1\n    if a[i]<=b[j]:\n        i+=1\n    else:\n        j+=1\nprint(c)', tip: '比較回数は最良で min(m,n)、最悪で m+n−1。マージソートの計算量解析の「n log n」はこの数の積み上げでできている。', ins: ['1 3 5\n2 4 6\n', '1 2 3\n4 5 6\n', '4 5 6\n1 2 3\n', '1\n2\n', '1 5\n2 3 4\n', '2 2\n2 2\n'] })

t({ lv: 164, concept: 'リスト: 2要素の整数商の最大', title: '割って一番大きくなるペア', tags: ['リスト'], io: '正整数の列(2個以上)が1行で空白区切りで与えられます。', ask: '異なる位置の2要素 a[i], a[j] について a[i]//a[j] (切り捨て商)の最大値を出力してください。', h1: '大きい数÷小さい数が有利。', h2: '答えは max(a)//min(a)。', ref: 'a=list(map(int,input().split()))\nprint(max(a)//min(a))', tip: '積の最大は負数の罠があったが、正の商は「最大÷最小」で即断できる。前提(正整数)が結論の単純さを買っている、を意識したい。', ins: ['2 10 3\n', '5 5\n', '1 100\n', '7 2 14\n', '9 4\n', '6 6 6\n'] })

t({ lv: 165, concept: '文字列: 文字の在庫で作れるか', title: '手持ちの文字で単語を組めるか', tags: ['文字列', 'ハッシュ'], io: '1行目に手持ちの文字(文字列)、2行目に作りたい単語が与えられます。', ask: '手持ちの文字を(それぞれ在庫の数まで)並べ替えて単語を作れるなら yes、足りない文字があれば no を出力してください。', h1: '文字ごとの在庫と必要数を比べる。', h2: 'Counter同士の包含(必要 ≤ 在庫)。', ref: 'from collections import Counter\nstock=Counter(input())\nneed=Counter(input())\nprint("yes" if all(stock[c]>=k for c,k in need.items()) else "no")', tip: '身代金要求書問題(ransom note)として知られる形。Counterの引き算 need−stock が空になるか、でも書ける多重集合の包含判定。', ins: ['aabbc\nabc\n', 'abc\naabb\n', 'xyz\nzyx\n', 'aa\naaa\n', 'hello\nhole\n', 'q\nq\n'] })

t({ lv: 166, concept: 'リスト: 中央2要素の和', title: '真ん中ふたりの合計', tags: ['リスト'], io: '偶数個の整数列が1行で空白区切りで与えられます。', ask: 'ソートしたときの中央の2要素の和を出力してください。', h1: '中央の位置は n//2 とその1つ前。', h2: 'sorted(a)[n//2-1] + sorted(a)[n//2]。', ref: 'a=sorted(map(int,input().split()))\nn=len(a)\nprint(a[n//2-1]+a[n//2])', tip: '偶数長の中央値は「中央2要素の平均」— その分子がこの値。中央値を小数にしたくない場面では2倍値(=この和)のまま扱うのが定石。', ins: ['1 2 3 4\n', '5 5\n', '9 1 8 2\n', '1 1 1 1\n', '-3 3 -1 1\n', '10 20 30 40 50 60\n'] })

t({ lv: 167, concept: 'リスト: 値と添字の和の最大', title: '得点+位置ボーナスの最大', tags: ['リスト'], io: '整数列が1行で空白区切りで与えられます。', ask: '各要素について「値 + その位置(0始まり)」を計算し、その最大値を出力してください。', h1: 'enumerateで同時に回す。', h2: 'max(x+i for i,x in enumerate(a))。', ref: 'a=list(map(int,input().split()))\nprint(max(x+i for i,x in enumerate(a)))', tip: '観光名所ペア問題(a[i]+a[j]+i−j の最大)は、この「値+添字」の走行最大を部品にしてO(n)で解ける。単純な量の前計算が上位問題の鍵になる例。', ins: ['1 2 3\n', '5 0 0\n', '-10 -10\n', '3 1 4 1 5\n', '7\n', '0 0 0 10\n'] })

t({ lv: 168, concept: 'リスト: 倍数への切り上げコスト合計', title: '全部kの倍数に揃える最小の追加', tags: ['リスト'], io: '1行目に k、2行目に正整数の列が与えられます。', ask: '各要素を k の倍数まで切り上げるときの増加量の合計を出力してください。', h1: '1要素の切り上げは既習のイディオム。', h2: '(-x) % k が「切り上げまでの距離」になる。', ref: 'k=int(input())\na=list(map(int,input().split()))\nprint(sum((-x)%k for x in a))', tip: '(-x)%k はPythonの剰余が常に非負であることを使った距離の1行。C系言語では負の剰余の符号が違うため通用しない、言語仕様の見どころ。', ins: ['3\n1 2 3\n', '5\n5 10\n', '4\n7\n', '2\n1 1 1\n', '10\n11 21 31\n', '7\n13 27\n'] })

t({ lv: 169, concept: 'ハッシュ: 出現回数の種類数', title: '頻度のバリエーション', tags: ['ハッシュ'], io: '整数列が1行で空白区切りで与えられます。', ask: '各値の出現回数を集めたとき、相異なる回数が何種類あるかを出力してください。', h1: 'Counterの値側を集計する。', h2: 'len(set(Counter(a).values()))。', ref: 'from collections import Counter\nc=Counter(input().split())\nprint(len(set(c.values())))', tip: 'Counter→values→set と、集計結果をさらに集計する2段パイプ。頻度の頻度(メタ集計)はジップの法則の観察などデータ分析でも実際に登場する。', ins: ['1 1 2 2 3\n', '1 2 3\n', '5 5 5\n', '1 1 2 2 2 3\n', '7\n', '1 1 1 2 2 3 4\n'] })

t({ lv: 171, concept: '文字列: 共通接頭辞を取り除いた残り', title: '共通の出だしを削った残り', tags: ['文字列'], io: '1行目と2行目に文字列が与えられます。', ask: '2つの文字列の最長共通接頭辞を両方から取り除いた残りを、1行ずつ出力してください(空になったら - を出力)。', h1: '共通接頭辞の長さを先に求める。', h2: 'その長さでスライスするだけ。', ref: 's=input()\nt=input()\ni=0\nwhile i<len(s) and i<len(t) and s[i]==t[i]:\n    i+=1\nprint(s[i:] if s[i:] else "-")\nprint(t[i:] if t[i:] else "-")', tip: '長さを求める問題(既出)の「構成版」。diffツールが変更点だけ表示する前処理はまさに共通接頭辞・接尾辞の削り出しから始まる。', ins: ['flower\nflow\n', 'abc\nabd\n', 'same\nsame\n', 'x\ny\n', 'prefix\npre\n', 'ab\nabab\n'] })

t({ lv: 172, concept: '文字列: 共通の2文字連続があるか', title: '同じ並びの2文字を共有するか', tags: ['文字列'], io: '1行目と2行目に文字列(各2文字以上)が与えられます。', ask: '両方に現れる「連続する2文字」(バイグラム)が1つでもあれば yes、なければ no を出力してください。', h1: '2文字の窓を全部集める。', h2: '両者のバイグラム集合の共通部分が空でないか。', ref: 's=input()\nt=input()\nA=set(s[i:i+2] for i in range(len(s)-1))\nB=set(t[i:i+2] for i in range(len(t)-1))\nprint("yes" if A&B else "no")', tip: 'n-gram集合の重なりは文書の類似度・盗用検出の基本特徴量。窓幅2を3,4…に上げるだけで精度と厳しさが変わる。', ins: ['hello\nworld\n', 'abc\ncab\n', 'xy\nyx\n', 'aabb\nbbaa\n', 'ab\nab\n', 'ace\nbdf\n'] })

t({ lv: 173, concept: '文字列: 子音で始まる単語の数', title: '母音以外で始まる単語', tags: ['文字列'], io: '英小文字の単語が空白区切りで1行に与えられます。', ask: '子音(a,i,u,e,o 以外)で始まる単語の個数を出力してください。', h1: '母音判定の否定。', h2: 'w[0] not in "aiueo"。', ref: 'ws=input().split()\nprint(sum(1 for w in ws if w[0] not in "aiueo"))', tip: '母音始まり(既出)の補集合。全体数から引いても求まるので、直接数えと補集合の2通りで答え合わせできる。', ins: ['apple banana cherry\n', 'ice ocean\n', 'dog cat\n', 'a b c\n', 'umbrella\n', 'kite egg owl pen\n'] })

t({ lv: 174, concept: '文字列: 最長と最短の単語の差', title: '一番長い単語と短い単語の差', tags: ['文字列'], io: '単語が空白区切りで1行に与えられます。', ask: '最長の単語の文字数から最短の単語の文字数を引いた値を出力してください。', h1: '長さのリストに変換する。', h2: 'max−min を len の列で。', ref: 'ws=input().split()\nls=[len(w) for w in ws]\nprint(max(ls)-min(ls))', tip: 'map(len, ws) で「文字列の列」を「数の列」に写してから集計する2段構え。写像→集約はデータ処理の最小パターン。', ins: ['a bb ccc\n', 'hello world\n', 'x\n', 'one three seven\n', 'ab ab ab\n', 'hi supercalifragilistic\n'] })

t({ lv: 175, concept: '文字列: 奇数回の文字はどれ', title: '回文の真ん中に座る文字', tags: ['文字列'], io: '英小文字の文字列(奇数回現れる文字がちょうど1種類)が1行で与えられます。', ask: '奇数回現れる文字を出力してください。', h1: 'Counterで回数の偶奇を見る。', h2: 'XORで文字コードを畳み込む1行の別解もある。', ref: 'from collections import Counter\nc=Counter(input())\nfor ch,k in c.items():\n    if k%2==1:\n        print(ch)\n        break', tip: '回文並べ替え(既出)の中央に来る文字を特定する構成版。全文字コードのXOR畳み込みでも求まるのは「1つだけ奇数回」の前提のおかげ。', ins: ['aabbc\n', 'abcba\n', 'z\n', 'aabbbcc\n', 'xxyyz\n', 'racecar\n'] })

t({ lv: 176, concept: '文字列: 末尾k文字を大文字に', title: '締めだけ大声で', tags: ['文字列'], io: '1行目に k、2行目に英小文字の文字列(k文字以上)が与えられます。', ask: '末尾の k 文字だけを大文字にした文字列を出力してください。', h1: '負のスライスで末尾を切り出す。', h2: 's[:-k] + s[-k:].upper()(k=0の罠に注意、ここではk≥1)。', ref: 'k=int(input())\ns=input()\nprint(s[:-k]+s[-k:].upper())', tip: 's[:-k]とs[-k:]で過不足なく2分割できるのは半開区間の恩恵。ただしk=0だとs[:-0]が空になる有名な罠があり、条件分岐かk≥1の保証が要る。', ins: ['2\nhello\n', '1\nabc\n', '5\nworld\n', '3\npython\n', '1\nx\n', '4\nabcdef\n'] })

t({ lv: 177, concept: '文字列: 奇数長の単語の数', title: '文字数が奇数の単語', tags: ['文字列'], io: '単語が空白区切りで1行に与えられます。', ask: '文字数が奇数の単語の個数を出力してください。', h1: 'len(w)%2 を見るだけ。', h2: 'sumとgenexpで1行。', ref: 'ws=input().split()\nprint(sum(1 for w in ws if len(w)%2==1))', tip: '偶数長版(既出)と合わせて総数になる、補集合ペアの練習。条件を「素数長」「回文」に差し替えても骨格は不変。', ins: ['a bb ccc\n', 'hello world\n', 'ab cd\n', 'x y z\n', 'four\n', 'one two three four five\n'] })

t({ lv: 178, concept: 'bit演算: 1と0どちらが多い', title: '2進数の多数派はどっち', tags: ['bit演算'], io: '正整数 n が1行で与えられます。', ask: '2進表記(先頭の1から)で、1の方が多ければ one、0の方が多ければ zero、同数なら equal を出力してください。', h1: 'bin(n)で数える。', h2: 'count("1") と count("0") の比較で3分岐。', ref: 's=bin(int(input()))[2:]\na=s.count("1")\nb=s.count("0")\nprint("one" if a>b else "zero" if a<b else "equal")', tip: '同数判定(既出)を3値分類に広げた形。多数決の結果は「符号」のようなもので、比較演算の連鎖 if-elif で書くのが読みやすい。', ins: ['7\n', '8\n', '10\n', '1\n', '36\n', '5\n'] })

t({ lv: 179, concept: 'bit演算: ビットの広がり', title: '一番上と一番下の距離', tags: ['bit演算'], io: '正整数 n が1行で与えられます。', ask: '2進表記で最上位の立っているビットの位置から最下位の立っているビットの位置を引いた値(位置は0始まり)を出力してください。', h1: '最上位は bit_length−1。', h2: '最下位は (n & −n).bit_length()−1。', ref: 'n=int(input())\nhi=n.bit_length()-1\nlo=(n&-n).bit_length()-1\nprint(hi-lo)', tip: 'n&−n が最下位ビットだけを残す2の補数の魔法。広がり0は「2のべき乗」と同値、という判定の言い換えにもなっている。', ins: ['6\n', '8\n', '9\n', '1\n', '20\n', '255\n'] })

t({ lv: 180, concept: '数え上げ: 和がKを超えるペア数', title: '合計が基準を超える2人組', tags: ['数え上げ', '二点法'], io: '1行目に K、2行目に整数列が与えられます。', ask: 'i<j で a[i]+a[j] が K を厳密に超えるペアの個数を出力してください。', h1: 'ソートして両端から。', h2: 'a[l]+a[r]>K なら (r−l) 組が一気に確定して r を縮める。', ref: 'k=int(input())\na=sorted(map(int,input().split()))\nl,r=0,len(a)-1\ncnt=0\nwhile l<r:\n    if a[l]+a[r]>k:\n        cnt+=r-l\n        r-=1\n    else:\n        l+=1\nprint(cnt)', tip: '「K未満のペア数」(既出)の鏡像で、二点法の縮め方が左右逆になる。全ペア数 C(n,2) から未満・ちょうどを引く検算も効く。', ins: ['5\n1 2 3 4\n', '10\n1 2 3\n', '0\n1 1 1\n', '3\n2 2\n', '6\n1 5 2 4\n', '100\n50 51\n'] })

t({ lv: 181, concept: '数え上げ: 隣接和の種類数', title: '隣どうしの和は何種類', tags: ['数え上げ'], io: '整数列(2個以上)が1行で空白区切りで与えられます。', ask: '隣り合う2要素の和として現れる値の種類数を出力してください。', h1: '隣接和を集合に入れる。', h2: 'set(x+y for zip)。', ref: 'a=list(map(int,input().split()))\nprint(len(set(x+y for x,y in zip(a,a[1:]))))', tip: 'zipペア→変換→setという3段の合成。和を差・積・maxに替えるだけの姉妹問題が量産できる、集計パイプの基本形。', ins: ['1 2 3 4\n', '1 1 1\n', '2 2 2 2\n', '1 3\n', '5 0 5 0\n', '1 2 1 2 1\n'] })

t({ lv: 182, concept: 'しゃくとり: 重複なし最長区間の開始位置', title: '一番長いユニーク区間はどこから', tags: ['しゃくとり'], io: '整数列が1行で空白区切りで与えられます。', ask: '要素が全て相異なる最長の連続区間のうち、最も左のものの開始位置(1始まり)を出力してください。', h1: '長さを求めるしゃくとり(既出)に位置の記録を足す。', h2: '「より長いときだけ」開始位置を更新すれば最左が残る。', ref: 'a=list(map(int,input().split()))\nlast={}\nl=0\nbest=0\nstart=1\nfor r,x in enumerate(a):\n    if x in last and last[x]>=l:\n        l=last[x]+1\n    last[x]=r\n    if r-l+1>best:\n        best=r-l+1\n        start=l+1\nprint(start)', tip: '長さだけの問題に「どこで達成したか」を足すのは、実務レポートで必ず要求される拡張。更新条件の等号の有無がタイブレークを決める。', ins: ['1 2 1 3 2\n', '1 1 1\n', '1 2 3\n', '5\n', '2 2 3 4 2\n', '1 2 3 1 2 3 4\n'] })

export const CATALOG = TASKS
