// 生成タスク 第56波：各レベル2問化フェーズ(11)。lv541〜549, lv551〜590 に2問目を追加。
// 再帰/数列/組合せ/貪欲/BFS/グラフ帯。重複なし・決定的・採点一意。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 541, concept: '再帰: ハノイのk手目に動く円盤', title: 'ハノイの塔でk手目に動く円盤', tags: ['再帰', 'bit演算'], io: '正整数 k が1行で与えられます。', ask: '最短手順でハノイの塔を解くとき、k 手目に動かす円盤の番号(最小の円盤が1)を出力してください。', h1: '手順の列は「1,2,1,3,1,2,1,…」という自己相似な形をしている。', h2: 'k 手目に動く円盤は「k を2で割り切れる回数+1」、つまり k の最下位の1ビットの位置。', ref: 'k=int(input())\nd=1\nwhile k%2==0:\n    k//=2\n    d+=1\nprint(d)', tip: 'ハノイの手順は2進カウンタと同型で、k手目の円盤は二進法でkの末尾の0の個数+1。再帰構造が数の構造に写る美しい例。', ins: ['1\n', '2\n', '3\n', '4\n', '12\n', '7\n'] })

t({ lv: 542, concept: '再帰: マッカーシーの91関数', title: 'マッカーシーの91関数', tags: ['再帰'], io: '正整数 n が1行で与えられます。', ask: 'M(n) を「n が100より大きければ n−10、そうでなければ M(M(n+11))」と定義するとき、M(n) の値を出力してください。', h1: '定義どおりに再帰で書く。', h2: '二重再帰 M(M(n+11)) をそのまま書けばよい(必ず停止する)。', ref: 'import sys\nsys.setrecursionlimit(100000)\ndef m(n):\n    if n>100:\n        return n-10\n    return m(m(n+11))\nprint(m(int(input())))', tip: '100以下の入力では答えが常に91になる不思議な関数。「入れ子の再帰」の停止性検証のベンチマークとして形式検証の分野で有名。', ins: ['1\n', '100\n', '101\n', '150\n', '99\n', '200\n'] })

t({ lv: 543, concept: 'シミュレーション: 最長コラッツの開始値', title: 'コラッツ列が最長になる開始値', tags: ['シミュレーション'], io: '正整数 N が1行で与えられます。', ask: '1 以上 N 以下の開始値のうち、コラッツ操作(偶数なら半分、奇数なら3倍+1)で1に至るまでの列が最も長いものを出力してください。同じ長さなら小さい方。', h1: '各開始値について列の長さを数える。', h2: '「より長いときだけ」更新すれば同長のとき小さい方が残る。', ref: 'n=int(input())\nbest=0\nbl=0\nfor s in range(1,n+1):\n    x=s\n    l=1\n    while x!=1:\n        x=3*x+1 if x%2 else x//2\n        l+=1\n    if l>bl:\n        bl=l\n        best=s\nprint(best)', tip: '「>」で更新すれば先勝ち(小さい方優先)、「>=」なら後勝ち。タイブレークはこの1文字で決まる。長さの記憶(メモ化)で大幅に高速化できる。', ins: ['1\n', '10\n', '20\n', '5\n', '100\n', '2\n'] })

t({ lv: 544, concept: '数: 乗法的持続度', title: '1桁になるまで桁の積を取る回数', tags: ['整数', 'ループ'], io: '非負整数 n が1行で与えられます。', ask: '「各桁の積で置き換える」操作を1桁になるまで繰り返すときの操作回数(乗法的持続度)を出力してください。', h1: '1桁になるまでループする。', h2: '桁の積は文字列化して掛け込む。', ref: 'n=int(input())\nc=0\nwhile n>=10:\n    p=1\n    for ch in str(n):\n        p*=int(ch)\n    n=p\n    c+=1\nprint(c)', tip: '持続度11の最小数は277777788888899。12以上の数は存在しないと予想されているが未証明という、遊びに見えて未解決の問題。', ins: ['39\n', '4\n', '999\n', '10\n', '77\n', '25\n'] })

t({ lv: 545, concept: 'bit演算: 全ペアのハミング距離の総和', title: '全ペアのハミング距離の合計', tags: ['bit演算'], io: '非負整数の列が1行で空白区切りで与えられます。', ask: '全てのペア (i<j) について2進表現のハミング距離(異なるビット数)を求め、その総和を出力してください。', h1: 'ペアごとに数えるとO(n²)。ビットごとに考える。', h2: 'あるビットで1がc個なら、そのビットの寄与は c×(n−c)。', ref: 'a=list(map(int,input().split()))\nn=len(a)\ntotal=0\nfor b in range(32):\n    c=sum(v>>b&1 for v in a)\n    total+=c*(n-c)\nprint(total)', tip: '「ペアの総和」を「ビット(次元)ごとの寄与の和」に組み替えると次元×nで済む。距離が座標ごとに分解できるとき共通に効く変形。', ins: ['4 14 2\n', '1 2 3\n', '5\n', '0 7\n', '1 1 1\n', '8 1 2 4\n'] })

t({ lv: 546, concept: 'DP: 円環の隣接違い塗り分け数', title: '円卓をk色で塗り分ける方法の数', tags: ['DP', '数学'], io: 'n k が空白区切りで1行で与えられます (n≥3)。', ask: '円形に並んだ n 個の席を k 色で塗り、隣どうしが必ず違う色になる塗り方の数を出力してください。', h1: '一列なら k×(k−1)^(n−1)。円は両端が隣り合うのが違い。', h2: '答えは (k−1)^n + (−1)^n (k−1)。彩色多項式の閉形式。', ref: 'n,k=map(int,input().split())\nprint((k-1)**n+(-1 if n%2 else 1)*(k-1))', tip: '「先頭と末尾が同色/異色」の2状態DPを解くとこの閉形式が出る。閉路グラフの彩色多項式として知られ、包除原理でも導ける。', ins: ['3 3\n', '4 2\n', '3 2\n', '4 3\n', '5 3\n', '6 2\n'] })

t({ lv: 547, concept: '数列: シルベスターの数列', title: 'シルベスターの数列の第k項', tags: ['数学'], io: '正整数 k が1行で与えられます。', ask: '「2から始め、次の項は 前の項×(前の項−1)+1」で定まるシルベスターの数列の第 k 項を出力してください(第1項は2)。', h1: '定義どおり反復する。', h2: 'a を a²−a+1 で置き換える。急激に大きくなるがPythonの整数は桁あふれしない。', ref: 'k=int(input())\na=2\nfor _ in range(k-1):\n    a=a*a-a+1\nprint(a)', tip: '2,3,7,43,1807,…は「どの項も前の全項の積+1」でもあり、互いに素。1/2+1/3+1/7+…が最速で1に近づく貪欲エジプト分数を与える。', ins: ['1\n', '2\n', '3\n', '4\n', '5\n', '6\n'] })

t({ lv: 548, concept: '組合せ: 3次元格子の最短経路数', title: '3次元格子の最短経路の数', tags: ['数学'], io: 'a b c が空白区切りで1行で与えられます。', ask: '原点から (a,b,c) まで、x・y・z のいずれかの正方向に1ずつ進む最短経路の数を出力してください。', h1: '移動の列は a個のx、b個のy、c個のzの並べ方。', h2: '多項係数 (a+b+c)! / (a!·b!·c!)。', ref: 'from math import factorial\na,b,c=map(int,input().split())\nprint(factorial(a+b+c)//(factorial(a)*factorial(b)*factorial(c)))', tip: '2次元の二項係数が3次元では多項係数になる。「経路数=文字列の並べ替え数」という同一視は次元が増えても揺らがない。', ins: ['1 1 1\n', '2 0 0\n', '2 1 0\n', '2 2 2\n', '3 1 1\n', '0 0 0\n'] })

t({ lv: 549, concept: '組合せ: ホッケースティックの和', title: '二項係数の斜めの和', tags: ['数学'], io: 'n r が空白区切りで1行で与えられます (0≤r≤n)。', ask: 'C(r,r) + C(r+1,r) + … + C(n,r) の値を出力してください。', h1: 'パスカルの三角形で斜めに足していく。', h2: '和は C(n+1, r+1) に一致する(ホッケースティック恒等式)。逐次和でも閉形式でもよい。', ref: 'from math import comb\nn,r=map(int,input().split())\nprint(sum(comb(i,r) for i in range(r,n+1)))', tip: '三角形上で斜めの列とその答えがホッケースティックの形に並ぶことが名前の由来。累積和がひとつ右下の係数に畳み込まれる、と読める。', ins: ['5 2\n', '4 0\n', '3 3\n', '6 1\n', '10 4\n', '2 2\n'] })

t({ lv: 551, concept: '貪欲: 1日1件の最大参加数', title: '1日1つ選んで出られる最大イベント数', tags: ['貪欲', 'ヒープ'], io: '1行目にイベント数 n、続く n 行に開催期間 s e (s日からe日まで、その中の1日だけ出席できる)が与えられます。', ask: '1日に1件しか出られないとき、出席できるイベント数の最大を出力してください。', h1: '日を1日ずつ進め、その日に開催中のイベントから選ぶ。', h2: '締切(終了日)が最も早いものから出るのが最善。終了日の最小ヒープで管理し、過ぎたものは捨てる。', ref: 'import heapq\nn=int(input())\nev=[tuple(map(int,input().split())) for _ in range(n)]\nev.sort()\nh=[]\ni=0\ncnt=0\nmaxd=max(e for s,e in ev)\nfor day in range(1,maxd+1):\n    while i<n and ev[i][0]<=day:\n        heapq.heappush(h,ev[i][1])\n        i+=1\n    while h and h[0]<day:\n        heapq.heappop(h)\n    if h:\n        heapq.heappop(h)\n        cnt+=1\nprint(cnt)', tip: '「資源(日)を時系列に進め、使えるものから締切最短を取る」貪欲。区間スケジューリングと違い1区間から1点だけ選ぶ点が新しい。', ins: ['3\n1 2\n2 3\n3 4\n', '4\n1 2\n2 3\n3 4\n1 2\n', '2\n1 1\n1 1\n', '3\n1 1\n1 2\n1 3\n', '1\n5 5\n', '4\n1 1\n1 1\n1 1\n2 2\n'] })

t({ lv: 552, concept: 'ヒープ: 給油回数の最小化', title: '目的地までの最小給油回数', tags: ['ヒープ', '貪欲'], io: '1行目に目的地までの距離 T と初期燃料 F、2行目にスタンド数 n、続く n 行に「位置 燃料量」が与えられます(位置昇順とは限らない)。', ask: '燃料1で距離1進めます。目的地に届くための最小の給油回数を出力してください。届かなければ -1。', h1: '通過したスタンドでは「後から給油したことにする」ことができる。', h2: '届かなくなったら、通過済みのうち最大の燃料を最大ヒープから取り出して補給する(後悔貪欲)。', ref: 'import heapq\nt,f=map(int,input().split())\nn=int(input())\nst=[tuple(map(int,input().split())) for _ in range(n)]\nst.sort()\nh=[]\nreach=f\nstops=0\nok=True\nfor p,g in st+[(t,0)]:\n    while reach<p:\n        if not h:\n            ok=False\n            break\n        reach+=-heapq.heappop(h)\n        stops+=1\n    if not ok:\n        break\n    heapq.heappush(h,-g)\nprint(stops if ok else -1)', tip: '「必要になった瞬間に、過去の選択肢から最良を採用する」後悔方式。未来を知らずに最適を出せるのは、給油の順番が結果に影響しないから。', ins: ['1 1\n0\n', '100 10\n4\n10 60\n20 30\n30 30\n60 40\n', '100 1\n1\n10 100\n', '10 3\n1\n3 7\n', '10 10\n2\n5 5\n7 3\n', '20 5\n2\n5 10\n10 4\n'] })

t({ lv: 553, concept: '貪欲: 2工程流れ作業のジョンソン法', title: '2台の機械を流れる最短完了時刻', tags: ['貪欲'], io: '1行目に仕事数 n、続く n 行に各仕事の「機械1の時間 機械2の時間」が与えられます。全仕事は機械1→機械2の順に処理されます。', ask: '仕事の並び順を最適に選んだときの全完了時刻(メイクスパン)の最小を出力してください。', h1: 'ジョンソンの規則: 機械1の方が短い仕事は前に(その時間の昇順)、そうでない仕事は後ろに(機械2の時間の降順)。', h2: '並びを決めたら、機械1の完了時刻を累積し、機械2は max(自分の空き, 機械1完了) から処理する。', ref: 'n=int(input())\njobs=[tuple(map(int,input().split())) for _ in range(n)]\ng1=sorted([j for j in jobs if j[0]<j[1]])\ng2=sorted([j for j in jobs if j[0]>=j[1]],key=lambda x:-x[1])\nt1=0\nt2=0\nfor a,b in g1+g2:\n    t1+=a\n    t2=max(t2,t1)+b\nprint(t2)', tip: '2機械フローショップは貪欲(ジョンソン法)で厳密最適が出る希少ケース。3機械以上になると途端にNP困難になる、境界線上の問題。', ins: ['3\n3 2\n1 4\n2 3\n', '1\n5 7\n', '2\n1 100\n100 1\n', '2\n2 2\n2 2\n', '4\n5 2\n1 6\n9 7\n3 8\n', '3\n1 1\n1 1\n1 1\n'] })

t({ lv: 554, concept: '貪欲: 硬貨貪欲の最適性検証', title: '貪欲法が損をする最小金額', tags: ['貪欲', 'DP'], io: '1行目に上限 N、2行目に硬貨の種類(1を含む)が与えられます。', ask: '「大きい硬貨から貪欲に払う」方法が最小枚数にならない最小の金額(N以下)を出力してください。存在しなければ -1。', h1: '本当の最小枚数はDPで求まる。', h2: '各金額で貪欲の枚数とDPの枚数を比べ、最初に食い違う金額を探す。', ref: 'n=int(input())\ncoins=sorted(map(int,input().split()),reverse=True)\nINF=10**9\ndp=[0]+[INF]*n\nfor v in range(1,n+1):\n    for c in coins:\n        if c<=v and dp[v-c]+1<dp[v]:\n            dp[v]=dp[v-c]+1\nans=-1\nfor v in range(1,n+1):\n    g=0\n    r=v\n    for c in coins:\n        g+=r//c\n        r%=c\n    if g>dp[v]:\n        ans=v\n        break\nprint(ans)', tip: '日本円やドルの額面では貪欲が常に最適だが {1,3,4} では6円が反例。貪欲が安全な硬貨系(canonical coin system)の判定は今も研究対象。', ins: ['15\n1 5 10\n', '15\n1 3 4\n', '30\n1 10 25\n', '10\n1 2 5\n', '12\n1 5 8\n', '8\n1 4 6\n'] })

t({ lv: 555, concept: '貪欲: 最大遅延の最小化', title: '締切超過の最大を最小にする', tags: ['貪欲'], io: '1行目に仕事数 n、続く n 行に「所要時間 締切」が与えられます。時刻0から1台の機械で順に処理します。', ask: '仕事の順序を最適化して「完了時刻−締切」の最大値(遅延の最大、負なら0)を最小化した値を出力してください。', h1: '締切の早い順(EDD)に並べるのが最適。', h2: '交換論法: 締切の遅い仕事を先にしても得しない。並べて累積時刻と締切の差の最大を取る。', ref: 'n=int(input())\njobs=sorted([tuple(map(int,input().split())) for _ in range(n)],key=lambda x:x[1])\nt=0\nlate=0\nfor d,dl in jobs:\n    t+=d\n    if t-dl>late:\n        late=t-dl\nprint(late)', tip: '「最大遅延」はEDD、「遅れる仕事の本数」はムーア法、「重み付き完了時刻の和」は比率順、と目的関数ごとに最適規則が変わるのがスケジューリングの面白さ。', ins: ['3\n3 6\n2 8\n1 9\n', '2\n5 3\n2 10\n', '1\n4 4\n', '3\n2 2\n2 3\n2 4\n', '2\n1 10\n1 1\n', '4\n1 1\n2 2\n3 3\n4 4\n'] })

t({ lv: 556, concept: '貪欲: お釣りを切らさない販売', title: 'お釣りを払い続けられるか', tags: ['貪欲'], io: '客が順に支払う紙幣(5, 10, 20 のいずれか)の列が1行で与えられます。商品は1つ5円で、手持ちのお釣りは最初0です。', ask: '受け取った紙幣だけでお釣りを払いながら全員に売れるなら yes、途中で払えなくなるなら no を出力してください。', h1: '10には5を1枚、20には「10+5」か「5×3」を返す。', h2: '20のお釣りは10を優先して使う(5は万能なので温存)。', ref: 'bills=list(map(int,input().split()))\nf=t=0\nok=True\nfor b in bills:\n    if b==5:\n        f+=1\n    elif b==10:\n        if f==0:\n            ok=False\n            break\n        f-=1\n        t+=1\n    else:\n        if t>0 and f>0:\n            t-=1\n            f-=1\n        elif f>=3:\n            f-=3\n        else:\n            ok=False\n            break\nprint("yes" if ok else "no")', tip: '「使い道が広い資源(5)ほど温存する」のが貪欲の一般則。両替・お釣り系のシミュレーションは、資源の汎用性順に優先度を付けると正しくなる。', ins: ['5 5 5 10 20\n', '5 5 10 10 20\n', '5 10 5 20\n', '10\n', '5 5 5 20\n', '5 10 10\n'] })

t({ lv: 557, concept: '貪欲: クッキー配りの満足人数', title: 'クッキーで満足させられる子どもの数', tags: ['貪欲', '二点法'], io: '1行目に各子どもの必要サイズ、2行目に各クッキーのサイズが与えられます。', ask: '子ども1人にクッキー1枚(サイズが必要量以上)を配るとき、満足させられる最大人数を出力してください。', h1: '両方ソートする。', h2: '小さいクッキーから、満たせる中で最も要求の小さい子に配る(二本の指を進める)。', ref: 'g=sorted(map(int,input().split()))\ns=sorted(map(int,input().split()))\ni=0\nfor c in s:\n    if i<len(g) and c>=g[i]:\n        i+=1\nprint(i)', tip: '両方をソートしてポインタを進めるだけのマッチング貪欲。「小さい資源は要求の小さい相手へ」の交換論法で最適性が示せる。', ins: ['1 2 3\n1 1\n', '1 2\n1 2 3\n', '5\n1 2\n', '1 1\n10\n', '2 3 4\n1 2 3\n', '1\n1\n'] })

t({ lv: 558, concept: '貪欲: 全種類1回ずつの辞書順最小', title: '各文字を1回だけ残す辞書順最小', tags: ['貪欲', 'スタック'], io: '英小文字の文字列が1行で与えられます。', ask: '文字をいくつか削除して「現れる文字種を全てちょうど1回ずつ含む」文字列を作るとき、辞書順最小のものを出力してください。', h1: 'スタックに積みながら、後ろにまだ出てくる大きい文字は捨てられる。', h2: '各文字の最後の出現位置を控えておき、「スタックの天辺より小さい文字が来た & 天辺はまだ後で拾える」なら天辺を捨てる。', ref: 's=input()\nlast={c:i for i,c in enumerate(s)}\nst=[]\nseen=set()\nfor i,c in enumerate(s):\n    if c in seen:\n        continue\n    while st and st[-1]>c and last[st[-1]]>i:\n        seen.discard(st.pop())\n    st.append(c)\n    seen.add(c)\nprint("".join(st))', tip: '単調スタック貪欲に「後でまだ拾えるか」という条件が加わる発展形。捨ててよい条件を1つ見落とすと正しさが崩れる、詰めの練習に良い問題。', ins: ['bcabc\n', 'cbacdcbc\n', 'a\n', 'abab\n', 'zyx\n', 'edebbed\n'] })

t({ lv: 559, concept: '貪欲: 最も遠い席', title: '隣から最も離れられる席', tags: ['貪欲'], io: '0(空席)と1(着席)の列が1行で空白区切りで与えられます(空席と着席が1つ以上ずつ)。', ask: '空席の中で「最も近い着席者への距離」が最大になるよう座るときの、その距離を出力してください。', h1: '端の空きと、着席者に挟まれた空きで計算が違う。', h2: '挟まれた区間は (幅)//2、端の区間は幅そのもの。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nbest=0\nprev=-1\nfor i,v in enumerate(a):\n    if v==1:\n        if prev<0:\n            best=i\n        else:\n            d=(i-prev)//2\n            if d>best:\n                best=d\n        prev=i\nd=n-1-prev\nif d>best:\n    best=d\nprint(best)', tip: '最適な席は必ず「区間の真ん中」か「端」。連続する空席の走査は、区間が端に接しているかの場合分けが定番の落とし穴。', ins: ['1 0 0 0 1 0 1\n', '1 0 0 0\n', '0 1\n', '1 0 1\n', '0 0 1\n', '1 0 0 1 0 0 0 1\n'] })

t({ lv: 560, concept: 'BFS: 値ぶん跳んで端へ', title: '書かれた数だけ跳んで最後尾へ', tags: ['BFS'], io: '整数列が1行で空白区切りで与えられます。位置 i からは i+a[i] か i−a[i] へ跳べます(範囲内のみ)。', ask: '先頭(位置0)から最後尾の位置への最小ジャンプ回数を出力してください。届かなければ -1。', h1: '各位置を頂点、跳び先を辺と見なす。', h2: '重みなしグラフの最短路なのでBFS。', ref: 'from collections import deque\na=list(map(int,input().split()))\nn=len(a)\ndist=[-1]*n\ndist[0]=0\nq=deque([0])\nwhile q:\n    x=q.popleft()\n    for y in (x+a[x],x-a[x]):\n        if 0<=y<n and dist[y]<0:\n            dist[y]=dist[x]+1\n            q.append(y)\nprint(dist[n-1])', tip: '配列も「移動規則を辺と読む」と即グラフになる。貪欲で解けるジャンプ問題(常に前進)と違い、後退がある時点でBFSの出番。', ins: ['2 3 1 1 4\n', '1 1 1\n', '3 1 1 0\n', '2 1\n', '0 1\n', '1 2 3 4 0\n'] })

t({ lv: 561, concept: 'グラフ: 完全な連結成分の数', title: 'クリークになっている成分の数', tags: ['グラフ', 'BFS'], io: '1行目に n m、続く m 行に無向辺が与えられます。', ask: '連結成分のうち、どの2頂点も直接辺で結ばれている(完全グラフになっている)成分の数を出力してください。', h1: '成分を BFS で取り出す。', h2: 'サイズ k の成分が完全 ⇔ 成分内の全頂点の次数が k−1。', ref: 'from collections import deque\nn,m=map(int,input().split())\nadj=[set() for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    adj[u].add(v)\n    adj[v].add(u)\nseen=[False]*(n+1)\ncnt=0\nfor s in range(1,n+1):\n    if seen[s]:\n        continue\n    comp=[]\n    seen[s]=True\n    q=deque([s])\n    while q:\n        x=q.popleft()\n        comp.append(x)\n        for y in adj[x]:\n            if not seen[y]:\n                seen[y]=True\n                q.append(y)\n    k=len(comp)\n    if all(len(adj[v])==k-1 for v in comp):\n        cnt+=1\nprint(cnt)', tip: '完全性の検査は辺を数え直さなくても「次数がサイズ−1」で言い切れる。孤立点はサイズ1の完全グラフとして数える。', ins: ['6 5\n1 2\n2 3\n1 3\n4 5\n5 6\n', '3 0\n', '4 6\n1 2\n1 3\n1 4\n2 3\n2 4\n3 4\n', '2 1\n1 2\n', '5 4\n1 2\n2 3\n3 4\n4 1\n', '4 2\n1 2\n3 4\n'] })

t({ lv: 562, concept: 'BFS: 単語はしご', title: '1文字ずつ変えて届く最短手数', tags: ['BFS', '文字列'], io: '1行目に開始単語と目標単語、2行目に辞書の単語(同じ長さ)が空白区切りで与えられます。', ask: '1文字だけ変えて辞書の単語を経由しながら目標単語に変換するとき、列の長さ(開始単語を含む単語数)の最小を出力してください。不可能なら 0。', h1: '1文字違いの単語どうしを辺で結んだグラフのBFS。', h2: '各位置を a〜z に置き換えた候補が辞書にあるか、で隣接を作ると速い。', ref: 'from collections import deque\nbegin,end=input().split()\nwords=set(input().split())\nif end not in words:\n    print(0)\nelse:\n    q=deque([(begin,1)])\n    seen={begin}\n    ans=0\n    while q:\n        w,d=q.popleft()\n        if w==end:\n            ans=d\n            break\n        for i in range(len(w)):\n            for c in "abcdefghijklmnopqrstuvwxyz":\n                nw=w[:i]+c+w[i+1:]\n                if nw in words and nw not in seen:\n                    seen.add(nw)\n                    q.append((nw,d+1))\n    print(ans)', tip: '辞書との照合は「隣接候補を生成して集合に聞く」方が、全単語と比較するより桁違いに速い。文字数×26の生成量は辞書サイズと無関係。', ins: ['hit cog\nhot dot dog lot log cog\n', 'hit cog\nhot dot dog lot log\n', 'a c\na b c\n', 'ab cd\nad cd\n', 'hot dog\nhot dog\n', 'aa bb\nab bb\n'] })

t({ lv: 563, concept: 'BFS: 滑る床の最短手数', title: '氷の上を滑って進む最短手数', tags: ['BFS'], io: '1行目に H W、続く H 行に盤面(S:開始, G:目標, #:壁, .:床)が与えられます。', ask: '一度動くと壁か端にぶつかるまで滑り続けます。S から G の位置で止まれる…ではなく、G のマスに「止まった」時点で到達とみなします。最小の移動回数を出力してください。到達できなければ -1。', h1: '「止まれるマス」だけが状態になる。', h2: '各方向へ while で滑らせ、止まった位置を隣接としてBFS。', ref: 'from collections import deque\nh,w=map(int,input().split())\ng=[input() for _ in range(h)]\nfor i in range(h):\n    for j in range(w):\n        if g[i][j]=="S":\n            sr,sc=i,j\n        if g[i][j]=="G":\n            gr,gc=i,j\ndist=[[-1]*w for _ in range(h)]\ndist[sr][sc]=0\nq=deque([(sr,sc)])\nwhile q:\n    r,c=q.popleft()\n    for dr,dc in ((1,0),(-1,0),(0,1),(0,-1)):\n        nr,nc=r,c\n        while 0<=nr+dr<h and 0<=nc+dc<w and g[nr+dr][nc+dc]!="#":\n            nr+=dr\n            nc+=dc\n        if dist[nr][nc]<0:\n            dist[nr][nc]=dist[r][c]+1\n            q.append((nr,nc))\nprint(dist[gr][gc])', tip: '「1歩」の定義が変わってもBFSの骨格は不変で、変わるのは隣接の作り方だけ。滑走・ワープ・回転など特殊移動は全部この形で吸収できる。', ins: ['3 4\nS...\n.#..\n...G\n', '2 2\nS.\n.G\n', '3 3\nS#.\n.#.\n..G\n', '1 4\nS..G\n', '3 3\nS..\n###\n..G\n', '4 4\nS...\n...#\n.#..\n...G\n'] })

t({ lv: 564, concept: 'グラフ: 経由回数制限の最安経路', title: '乗り継ぎk回以内の最安運賃', tags: ['グラフ', 'DP'], io: '1行目に n m k s t、続く m 行に有向辺「u v 運賃」が与えられます。', ask: '経由地が k 箇所以内(使う辺が k+1 本以内)で s から t へ行く最小運賃を出力してください。不可能なら -1。', h1: 'ダイクストラは経由数の制限を扱えない。', h2: 'ベルマンフォードを k+1 ラウンドだけ回す。各ラウンドで「前ラウンドの表」から緩和するのがポイント。', ref: 'n,m,k,s,t=map(int,input().split())\nedges=[tuple(map(int,input().split())) for _ in range(m)]\nINF=float("inf")\ndist=[INF]*(n+1)\ndist[s]=0\nfor _ in range(k+1):\n    nd=dist[:]\n    for u,v,w in edges:\n        if dist[u]+w<nd[v]:\n            nd[v]=dist[u]+w\n    dist=nd\nprint(dist[t] if dist[t]<INF else -1)', tip: '同じ配列を更新すると1ラウンドで複数辺を進んでしまう。コピーしてから緩和する「2枚持ち」が回数制限DPの要。', ins: ['4 4 1 1 4\n1 2 100\n1 3 500\n2 4 100\n3 4 1\n', '3 2 0 1 3\n1 2 1\n2 3 1\n', '3 3 1 1 3\n1 2 1\n2 3 1\n1 3 5\n', '2 1 0 1 2\n1 2 7\n', '4 3 2 1 4\n1 2 1\n2 3 1\n3 4 1\n', '3 2 1 1 3\n1 2 1\n2 3 1\n'] })

t({ lv: 565, concept: 'BFS: 鍵と扉の最短手数', title: '全ての鍵を集める最短手数', tags: ['BFS', 'bit演算'], io: '1行目に H W、続く H 行に盤面(@:開始, a〜c:鍵, A〜C:対応する扉, #:壁, .:床)が与えられます。', ask: '対応する鍵を持っていないと扉は通れません。全ての鍵を集める最小歩数を出力してください。不可能なら -1。', h1: '位置だけでは状態が足りない。', h2: '「位置+持っている鍵の集合(ビットマスク)」を状態にBFS。', ref: 'from collections import deque\nh,w=map(int,input().split())\ng=[input() for _ in range(h)]\nallk=0\nfor i in range(h):\n    for j in range(w):\n        c=g[i][j]\n        if c=="@":\n            sr,sc=i,j\n        if c.islower():\n            allk|=1<<(ord(c)-97)\nseen={(sr,sc,0)}\nq=deque([(sr,sc,0,0)])\nans=-1\nwhile q:\n    r,c,k,d=q.popleft()\n    if k==allk:\n        ans=d\n        break\n    for dr,dc in ((1,0),(-1,0),(0,1),(0,-1)):\n        nr,nc=r+dr,c+dc\n        if not(0<=nr<h and 0<=nc<w):\n            continue\n        ch=g[nr][nc]\n        if ch=="#":\n            continue\n        if ch.isupper() and not k>>(ord(ch)-65)&1:\n            continue\n        nk=k\n        if ch.islower():\n            nk|=1<<(ord(ch)-97)\n        if (nr,nc,nk) not in seen:\n            seen.add((nr,nc,nk))\n            q.append((nr,nc,nk,d+1))\nprint(ans)', tip: '「同じマスでも持ち物が違えば別の状態」。状態空間をマス×2^鍵数に広げるだけで、BFSの正しさはそのまま保たれる。', ins: ['1 3\n@aA\n', '1 5\n@.a.b\n', '1 5\n@Aa.b\n', '2 3\n@.a\nb..\n', '1 2\n@a\n', '3 3\n@.a\n###\nb..\n'] })

t({ lv: 566, concept: 'グラフ: 2チーム分けの人数差最小', title: '仲の悪い2人を分けて人数差最小', tags: ['グラフ', 'DP'], io: '1行目に n m、続く m 行に「同じチームにできない」ペアが与えられます。', ask: '全員を2チームに分ける(敵対ペアは必ず別チーム)とき、チーム人数差の最小値を出力してください。分けられなければ -1。', h1: '成分ごとに2色に塗ると (a人, b人) の2択になる。', h2: '各成分でどちらの側を採るかは部分和DP。作れる片側人数の集合を持ち回る。', ref: 'from collections import deque\nn,m=map(int,input().split())\nadj=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    adj[u].append(v)\n    adj[v].append(u)\ncolor=[0]*(n+1)\nparts=[]\nok=True\nfor s in range(1,n+1):\n    if color[s]:\n        continue\n    color[s]=1\n    q=deque([s])\n    a,b=1,0\n    while q:\n        x=q.popleft()\n        for y in adj[x]:\n            if color[y]==0:\n                color[y]=3-color[x]\n                if color[y]==1:\n                    a+=1\n                else:\n                    b+=1\n                q.append(y)\n            elif color[y]==color[x]:\n                ok=False\n    parts.append((a,b))\nif not ok:\n    print(-1)\nelse:\n    poss={0}\n    for a,b in parts:\n        poss={p+a for p in poss}|{p+b for p in poss}\n    print(min(abs(2*p-n) for p in poss))', tip: '「二部グラフ判定」と「部分和DP」の合成問題。成分ごとの自由度(どちら側か)を数に落としてDPに渡す、2段構えの設計を練習できる。', ins: ['4 2\n1 2\n3 4\n', '3 2\n1 2\n1 3\n', '3 3\n1 2\n2 3\n1 3\n', '5 2\n1 2\n3 4\n', '2 1\n1 2\n', '6 3\n1 2\n1 3\n1 4\n'] })

t({ lv: 567, concept: 'グラフ: 関数グラフの閉路頂点数', title: '関数グラフで閉路上にある頂点数', tags: ['グラフ'], io: '1行目に n、2行目に写像 f(1) … f(n) が与えられます(各頂点から f(v) へ辺が出る)。', ask: 'いずれかの閉路の上に乗っている頂点の総数を出力してください。', h1: '各頂点から f をたどると必ずどこかの閉路に落ちる。', h2: '訪問中(1)・確定(2)の2段階の印を付け、たどった道中で「訪問中」に再会したらそこから先が閉路。', ref: 'n=int(input())\nf=list(map(int,input().split()))\nincyc=[False]*(n+1)\nstate=[0]*(n+1)\nfor s in range(1,n+1):\n    if state[s]:\n        continue\n    path=[]\n    x=s\n    while state[x]==0:\n        state[x]=1\n        path.append(x)\n        x=f[x-1]\n    if state[x]==1:\n        i=path.index(x)\n        for v in path[i:]:\n            incyc[v]=True\n    for v in path:\n        state[v]=2\nprint(sum(incyc))', tip: '出次数1のグラフ(関数グラフ)は「ρの形」の集まりで、閉路の集合は f を n 回合成した像とも一致する。3色マーキングは有向閉路検出の標準装備。', ins: ['3\n2 3 1\n', '4\n2 3 2 3\n', '1\n1\n', '5\n2 3 4 5 3\n', '6\n2 1 2 3 4 5\n', '4\n1 1 1 1\n'] })

t({ lv: 568, concept: 'グラフ: 閉路に到達しない頂点数', title: 'どこを通っても行き止まる頂点の数', tags: ['グラフ', '再帰'], io: '1行目に n m、続く m 行に有向辺が与えられます。', ask: 'そこから出発してどう進んでも(どの経路を選んでも)有限回で行き止まりに到達する頂点、つまり閉路に決して巻き込まれない頂点の数を出力してください。', h1: '閉路に到達し得る頂点が「危険」、それ以外が「安全」。', h2: 'DFSで訪問中に再会したら閉路。行き先が全て安全なときだけ安全と確定できる(3色法)。', ref: 'import sys\nsys.setrecursionlimit(100000)\nn,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\ncolor=[0]*(n+1)\ndef safe(x):\n    if color[x]>0:\n        return color[x]==2\n    color[x]=1\n    ok=True\n    for y in g[x]:\n        if not safe(y):\n            ok=False\n            break\n    if ok:\n        color[x]=2\n    return ok\nprint(sum(1 for v in range(1,n+1) if safe(v)))', tip: '「訪問中(灰)に戻ってきたら危険」の判定が閉路検出を兼ねる。逆辺を張って行き止まりから遡るトポロジカルな解法もあり、両方書けると強い。', ins: ['4 4\n1 2\n2 3\n3 2\n3 4\n', '3 3\n1 2\n2 3\n3 1\n', '3 0\n', '5 4\n1 2\n2 3\n3 4\n4 5\n', '4 3\n1 2\n2 1\n3 4\n', '6 6\n1 2\n2 3\n3 1\n4 5\n5 6\n4 6\n'] })

t({ lv: 569, concept: 'グラフ: 逆走する辺の最小本数', title: '逆走を最小限にして目的地へ', tags: ['グラフ', 'BFS'], io: '1行目に n m s t、続く m 行に一方通行の道(有向辺)が与えられます。', ask: '道は順方向ならそのまま、逆方向にも(違反して)通れます。s から t まで行くときの逆走の最小回数を出力してください。到達不能なら -1。', h1: '順方向をコスト0、逆方向をコスト1の辺にする。', h2: '重みが0/1だけの最短路は、0辺は先頭へ・1辺は末尾へ入れる deque のBFS(0-1 BFS)で解ける。', ref: 'from collections import deque\nn,m,s,t=map(int,input().split())\nadj=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    adj[u].append((v,0))\n    adj[v].append((u,1))\nINF=float("inf")\ndist=[INF]*(n+1)\ndist[s]=0\ndq=deque([s])\nwhile dq:\n    x=dq.popleft()\n    for y,w in adj[x]:\n        if dist[x]+w<dist[y]:\n            dist[y]=dist[x]+w\n            if w:\n                dq.append(y)\n            else:\n                dq.appendleft(y)\nprint(dist[t] if dist[t]<INF else -1)', tip: '「変えたい向きの辺に1、そのままの辺に0」を張るモデル化は、辺の反転・スイッチ切替・壁破壊などあらゆる“例外行動の最小化”に流用できる。', ins: ['3 2 1 3\n1 2\n3 2\n', '2 1 1 2\n1 2\n', '2 1 2 1\n1 2\n', '4 3 1 4\n1 2\n2 3\n4 3\n', '3 2 1 3\n2 1\n2 3\n', '1 0 1 1\n'] })

t({ lv: 570, concept: 'BFS: 最寄りの0への距離行列', title: '各マスから最も近い0までの距離', tags: ['BFS'], io: '1行目に H W、続く H 行に0/1の格子が与えられます(0が1つ以上ある)。', ask: '各マスについて最も近い0までの距離(上下左右移動)を求め、H行の空白区切りで出力してください。', h1: '各マスからBFSすると遅い。', h2: '全ての0を距離0として同時にキューへ入れる多始点BFSなら1回で全マス分求まる。', ref: 'from collections import deque\nh,w=map(int,input().split())\ng=[list(map(int,input().split())) for _ in range(h)]\ndist=[[-1]*w for _ in range(h)]\nq=deque()\nfor i in range(h):\n    for j in range(w):\n        if g[i][j]==0:\n            dist[i][j]=0\n            q.append((i,j))\nwhile q:\n    r,c=q.popleft()\n    for dr,dc in ((1,0),(-1,0),(0,1),(0,-1)):\n        nr,nc=r+dr,c+dc\n        if 0<=nr<h and 0<=nc<w and dist[nr][nc]<0:\n            dist[nr][nc]=dist[r][c]+1\n            q.append((nr,nc))\nfor row in dist:\n    print(*row)', tip: '多始点BFSは「仮想の超始点から全0へ距離0の辺」と思うと1回のBFSに見える。距離変換(distance transform)として画像処理でも頻出。', ins: ['3 3\n0 0 0\n0 1 0\n1 1 1\n', '1 3\n0 1 1\n', '2 2\n0 0\n0 0\n', '2 3\n1 1 0\n1 1 1\n', '1 1\n0\n', '3 1\n1\n0\n1\n'] })

t({ lv: 571, concept: 'グラフ: 互いに到達できるか', title: '2頂点は互いに行き来できるか', tags: ['グラフ', 'BFS'], io: '1行目に n m、続く m 行に有向辺、最後の行に2頂点 u v が与えられます。', ask: 'u から v へも v から u へも到達できる(同じ強連結成分にある)なら yes、そうでなければ no を出力してください。', h1: '片方向ずつBFSで確かめる。', h2: '2回のBFS(uから、vから)の両方で相手に届けばよい。', ref: 'from collections import deque\nn,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    a,b=map(int,input().split())\n    g[a].append(b)\nu,v=map(int,input().split())\ndef reach(s,t):\n    seen=[False]*(n+1)\n    seen[s]=True\n    q=deque([s])\n    while q:\n        x=q.popleft()\n        for y in g[x]:\n            if not seen[y]:\n                seen[y]=True\n                q.append(y)\n    return seen[t]\nprint("yes" if reach(u,v) and reach(v,u) else "no")', tip: '相互到達は同値関係で、その同値類が強連結成分。クエリが大量ならSCC分解を前計算して「同じ成分番号か」のO(1)判定に変える。', ins: ['3 3\n1 2\n2 3\n3 1\n1 3\n', '3 2\n1 2\n2 3\n1 3\n', '2 2\n1 2\n2 1\n1 2\n', '4 4\n1 2\n2 1\n3 4\n4 3\n1 3\n', '1 0\n1 1\n', '5 5\n1 2\n2 3\n3 1\n3 4\n4 5\n2 1\n'] })

t({ lv: 572, concept: 'グラフ: 未知の文字順の復元', title: '並び順から文字の序列を復元', tags: ['グラフ', '文字列'], io: '1行目に単語数 n、続く n 行に「未知のアルファベット順でソートされた」単語が与えられます。', ask: '単語の並びと矛盾しない文字の順序のうち、通常のabc順で辞書順最小のものを1つの文字列として出力してください。矛盾する場合は -1。', h1: '隣り合う単語の最初の不一致が「前の文字<後の文字」という制約になる。', h2: '制約の有向グラフをトポロジカルソート。候補が複数あるときは最小の文字を選ぶ(ヒープ)。前が後の真の延長なら矛盾。', ref: 'import heapq\nn=int(input())\nwords=[input() for _ in range(n)]\nletters=sorted(set("".join(words)))\nadj={c:set() for c in letters}\nindeg={c:0 for c in letters}\nbad=False\nfor a,b in zip(words,words[1:]):\n    i=0\n    while i<len(a) and i<len(b) and a[i]==b[i]:\n        i+=1\n    if i<len(a) and i<len(b):\n        if b[i] not in adj[a[i]]:\n            adj[a[i]].add(b[i])\n            indeg[b[i]]+=1\n    elif len(a)>len(b):\n        bad=True\nif bad:\n    print(-1)\nelse:\n    h=[c for c in letters if indeg[c]==0]\n    heapq.heapify(h)\n    out=[]\n    while h:\n        c=heapq.heappop(h)\n        out.append(c)\n        for y in sorted(adj[c]):\n            indeg[y]-=1\n            if indeg[y]==0:\n                heapq.heappush(h,y)\n    print("".join(out) if len(out)==len(letters) else -1)', tip: 'データから制約を抽出する前処理と、トポロジカルソートの後処理の2段構成。「abc が ab より前に来る」だけで矛盾になる境界ケースが要注意。', ins: ['3\nba\nbc\nac\n', '2\nab\nba\n', '2\nabc\nab\n', '1\nzyx\n', '3\nc\nb\na\n', '2\naa\nab\n'] })

t({ lv: 573, concept: '木: 各部分木の高さ', title: '全頂点の部分木の高さ', tags: ['木', '再帰'], io: '1行目に頂点数 n(根は1、n≥2)、2行目に頂点2..nの親が与えられます。', ask: '各頂点 v を根とする部分木の高さ(vから最も深い子孫までの頂点数)を、頂点1から順に空白区切りで出力してください。', h1: '葉の高さは1。', h2: '内部頂点の高さは「子の高さの最大+1」。帰りがけ順(子を先に確定)で計算する。', ref: 'import sys\nsys.setrecursionlimit(100000)\nn=int(input())\npar=[0,0]+list(map(int,input().split()))\nch=[[] for _ in range(n+1)]\nfor v in range(2,n+1):\n    ch[par[v]].append(v)\nht=[0]*(n+1)\ndef dfs(v):\n    best=0\n    for c in ch[v]:\n        dfs(c)\n        if ht[c]>best:\n            best=ht[c]\n    ht[v]=best+1\ndfs(1)\nprint(*ht[1:])', tip: '「子の答えから親の答えを合成する」帰りがけ順は木DPの原型。高さを部分木サイズや最大値に替えるだけで多くの木の集計問題に化ける。', ins: ['5\n1 1 2 2\n', '3\n1 2\n', '4\n1 1 1\n', '6\n1 2 2 1 5\n', '2\n1\n', '7\n1 1 2 2 3 3\n'] })

t({ lv: 574, concept: '木: 最も浅い葉の深さ', title: '根から最も近い葉までの深さ', tags: ['木', 'BFS'], io: '1行目に頂点数 n(根は1、n≥2)、2行目に頂点2..nの親が与えられます。', ask: '根の深さを1として、最も浅い葉(子を持たない頂点)の深さを出力してください。', h1: '深さ順に見るならBFS。', h2: '最初に見つかった葉の深さが答え(BFSは浅い順に訪れる)。', ref: 'from collections import deque\nn=int(input())\npar=[0,0]+list(map(int,input().split()))\nch=[[] for _ in range(n+1)]\nfor v in range(2,n+1):\n    ch[par[v]].append(v)\nq=deque([(1,1)])\nwhile q:\n    x,d=q.popleft()\n    if not ch[x]:\n        print(d)\n        break\n    for c in ch[x]:\n        q.append((c,d+1))', tip: '最大深さ(高さ)はDFSでもBFSでも同じ手間だが、最小深さはBFSなら最初の葉で打ち切れる。「最小」と「早期終了」はBFSの得意分野。', ins: ['5\n1 1 2 2\n', '2\n1\n', '4\n1 2 3\n', '6\n1 1 2 2 3\n', '3\n1 1\n', '7\n1 2 2 1 5 5\n'] })

t({ lv: 575, concept: 'グラフ: 単一の閉路グラフか', title: 'グラフはひとつの輪か', tags: ['グラフ'], io: '1行目に n m、続く m 行に無向辺が与えられます(自己ループ・多重辺なし)。', ask: 'グラフ全体がちょうど1つの閉路(輪)になっているなら yes、そうでなければ no を出力してください。', h1: '輪の条件を数で言い換える。', h2: '「連結」かつ「辺数と頂点数が等しい」かつ「全頂点の次数が2」。', ref: 'n,m=map(int,input().split())\ndeg=[0]*(n+1)\npar=list(range(n+1))\ndef find(x):\n    while par[x]!=x:\n        par[x]=par[par[x]]\n        x=par[x]\n    return x\ncomps=n\nfor _ in range(m):\n    u,v=map(int,input().split())\n    deg[u]+=1\n    deg[v]+=1\n    ru,rv=find(u),find(v)\n    if ru!=rv:\n        par[ru]=rv\n        comps-=1\nprint("yes" if n>=3 and m==n and comps==1 and all(d==2 for d in deg[1:]) else "no")', tip: '形の判定は「探索でなぞる」より「不変量(次数列・辺数・連結性)の一致」で言い切る方が短く正確。木(m と n−1)も同じ発想で判定できる。', ins: ['3 3\n1 2\n2 3\n3 1\n', '4 4\n1 2\n2 3\n3 4\n4 1\n', '4 4\n1 2\n2 3\n3 1\n1 4\n', '3 2\n1 2\n2 3\n', '6 6\n1 2\n2 3\n3 1\n4 5\n5 6\n6 4\n', '5 5\n1 2\n2 3\n3 4\n4 5\n5 1\n'] })

t({ lv: 576, concept: 'グラフ: 2番目の最短路長', title: '2番目に短い道のりの長さ', tags: ['グラフ', 'BFS'], io: '1行目に n m s t、続く m 行に無向辺が与えられます(全ての辺の長さは1)。', ask: 's から t への歩き方(同じ頂点や辺を再訪してよい)のうち、最短より真に長い2番目の長さを出力してください。存在しなければ -1。', h1: '各頂点に「最短」と「2番目(真に長い)」の2つの距離を持たせる。', h2: '更新のとき、より短ければ最短を押し出して2番目に回す。優先度付きキューで小さい順に確定させる。', ref: 'import heapq\nn,m,s,t=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\nINF=float("inf")\nd1=[INF]*(n+1)\nd2=[INF]*(n+1)\nd1[s]=0\nh=[(0,s)]\nwhile h:\n    d,x=heapq.heappop(h)\n    if d>d2[x]:\n        continue\n    for y in g[x]:\n        nd=d+1\n        if nd<d1[y]:\n            d1[y],d2[y]=nd,d1[y]\n            heapq.heappush(h,(d1[y],y))\n            if d2[y]<INF:\n                heapq.heappush(h,(d2[y],y))\n        elif d1[y]<nd<d2[y]:\n            d2[y]=nd\n            heapq.heappush(h,(nd,y))\nprint(d2[t] if d2[t]<INF else -1)', tip: '「k番目の最短路」は距離表をk本持つだけでダイクストラが一般化する。往復(+2)で作る2番目があるため、無向グラフでは答えが必ず存在に近い。', ins: ['3 3 1 3\n1 2\n2 3\n1 3\n', '2 1 1 2\n1 2\n', '4 4 1 4\n1 2\n2 4\n1 3\n3 4\n', '4 3 1 4\n1 2\n2 3\n3 4\n', '3 2 1 3\n1 2\n2 3\n', '5 6 1 5\n1 2\n2 5\n1 3\n3 4\n4 5\n2 3\n'] })

t({ lv: 577, concept: '木: オイラーツアーの行き掛け順', title: '行きがけ順の頂点列', tags: ['木'], io: '1行目に頂点数 n(根は1、n≥2)、2行目に頂点2..nの親が与えられます。', ask: '根から深さ優先で木をたどる行きがけ順(子は番号の小さい順に訪問)の頂点列を空白区切りで出力してください。', h1: 'スタックで深さ優先をシミュレートする。', h2: '子を番号の大きい順に積むと、取り出しが小さい順になる。', ref: 'n=int(input())\npar=[0,0]+list(map(int,input().split()))\nch=[[] for _ in range(n+1)]\nfor v in range(2,n+1):\n    ch[par[v]].append(v)\nout=[]\nst=[1]\nwhile st:\n    x=st.pop()\n    out.append(x)\n    for c in sorted(ch[x],reverse=True):\n        st.append(c)\nprint(*out)', tip: '行きがけ順で部分木は連続区間になる。この性質(オイラーツアー)が「部分木への区間クエリ」を可能にし、セグ木と木を接続する橋になる。', ins: ['5\n1 1 2 2\n', '3\n1 2\n', '4\n1 1 1\n', '6\n1 2 2 1 5\n', '2\n1\n', '7\n1 1 2 2 3 3\n'] })

t({ lv: 578, concept: 'グリッド: 外に出られない領域の数', title: '外周に触れない領域を数える', tags: ['BFS'], io: '1行目に H W、続く H 行に0(陸)/1(水)の格子が与えられます。', ask: '陸(0)の連結領域のうち、盤面の外周のマスを1つも含まないものの数を出力してください。', h1: '普通の領域数えに「外周に触れたか」のフラグを足す。', h2: '領域のBFS中に外周マスを見つけたら閉じていない、と記録する。', ref: 'from collections import deque\nh,w=map(int,input().split())\ng=[list(map(int,input().split())) for _ in range(h)]\nseen=[[False]*w for _ in range(h)]\ncnt=0\nfor i in range(h):\n    for j in range(w):\n        if g[i][j]==0 and not seen[i][j]:\n            seen[i][j]=True\n            q=deque([(i,j)])\n            closed=True\n            while q:\n                r,c=q.popleft()\n                if r in (0,h-1) or c in (0,w-1):\n                    closed=False\n                for dr,dc in ((1,0),(-1,0),(0,1),(0,-1)):\n                    nr,nc=r+dr,c+dc\n                    if 0<=nr<h and 0<=nc<w and g[nr][nc]==0 and not seen[nr][nc]:\n                        seen[nr][nc]=True\n                        q.append((nr,nc))\n            if closed:\n                cnt+=1\nprint(cnt)', tip: '「外周から到達できる陸を先に消す」逆転の発想でも解ける。フラグの集約(1個でも外周ならFalse)は探索中に畳み込むとメモリ要らず。', ins: ['3 3\n1 1 1\n1 0 1\n1 1 1\n', '3 3\n0 1 1\n1 0 1\n1 1 1\n', '1 3\n0 0 0\n', '5 5\n1 1 1 1 1\n1 0 0 0 1\n1 0 1 0 1\n1 0 0 0 1\n1 1 1 1 1\n', '3 4\n1 1 1 1\n1 0 1 0\n1 1 1 1\n', '2 2\n0 0\n0 0\n'] })

t({ lv: 579, concept: 'BFS: 水差しパズル', title: '2つの水差しで測れるか', tags: ['数学'], io: '容量 a b と目標量 c が空白区切りで1行で与えられます (a,b≥1)。', ask: '容量 a と b の水差し(満たす・空にする・移し替えが自由)を使って、ちょうど c の水を(合計として)量れるなら yes、量れなければ no を出力してください。', h1: '状態のBFSでも解けるが、数論で言い切れる。', h2: '量れる ⇔ c が a+b 以下で、かつ c が gcd(a,b) の倍数。', ref: 'import math\na,b,c=map(int,input().split())\nprint("yes" if c<=a+b and (c==0 or c%math.gcd(a,b)==0) else "no")', tip: '操作で作れる量は必ず ax+by の形になり、ベズーの等式から gcd の倍数が全て作れる。探索問題が数論の1行に潰れる名例(映画ダイ・ハード3の問題)。', ins: ['3 5 4\n', '2 6 5\n', '1 2 3\n', '4 6 8\n', '3 5 9\n', '7 11 1\n'] })

t({ lv: 580, concept: 'グラフ: 1辺を無料にできる最短路', title: 'どれか1本タダで通れる最短路', tags: ['グラフ', 'ダイクストラ'], io: '1行目に n m s t、続く m 行に無向辺 u v w が与えられます。', ask: 'どれか1本の辺を無料(重み0)にしてよいときの s から t への最短距離を出力してください。到達不能なら -1。', h1: '「無料権を使ったか」の0/1を状態に足す。', h2: '(頂点, 使用済みフラグ) の2層グラフでダイクストラ。辺を渡るとき「普通に渡る」「無料権を使って渡る」の2遷移。', ref: 'import heapq\nn,m,s,t=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v,w=map(int,input().split())\n    g[u].append((v,w))\n    g[v].append((u,w))\nINF=float("inf")\ndist=[[INF]*2 for _ in range(n+1)]\ndist[s][0]=0\nh=[(0,s,0)]\nwhile h:\n    d,x,u=heapq.heappop(h)\n    if d>dist[x][u]:\n        continue\n    for y,w in g[x]:\n        if d+w<dist[y][u]:\n            dist[y][u]=d+w\n            heapq.heappush(h,(d+w,y,u))\n        if u==0 and d<dist[y][1]:\n            dist[y][1]=d\n            heapq.heappush(h,(d,y,1))\nans=min(dist[t])\nprint(ans if ans<INF else -1)', tip: 'クーポン・ワープ・壁破壊など「1回だけの特典」は層を複製したグラフ(layered graph)で機械的に扱える。層の数=特典の残回数。', ins: ['3 2 1 3\n1 2 5\n2 3 5\n', '2 1 1 2\n1 2 100\n', '4 4 1 4\n1 2 1\n2 4 10\n1 3 3\n3 4 3\n', '3 3 1 3\n1 2 2\n2 3 2\n1 3 10\n', '2 0 1 2\n', '4 3 1 4\n1 2 4\n2 3 4\n3 4 4\n'] })

t({ lv: 581, concept: 'グリッド: 水位を上げた島の数', title: '水位Lのときの島の数', tags: ['BFS'], io: '1行目に H W L、続く H 行に各マスの標高が与えられます。', ask: '標高が L より大きいマスだけが陸として残るとき、陸の連結成分(島)の数を出力してください。', h1: '条件付きのフラッドフィル。', h2: '「高さ>L」のマスだけを通って広がる。', ref: 'from collections import deque\nh,w,L=map(int,input().split())\ng=[list(map(int,input().split())) for _ in range(h)]\nseen=[[False]*w for _ in range(h)]\ncnt=0\nfor i in range(h):\n    for j in range(w):\n        if g[i][j]>L and not seen[i][j]:\n            cnt+=1\n            seen[i][j]=True\n            q=deque([(i,j)])\n            while q:\n                r,c=q.popleft()\n                for dr,dc in ((1,0),(-1,0),(0,1),(0,-1)):\n                    nr,nc=r+dr,c+dc\n                    if 0<=nr<h and 0<=nc<w and g[nr][nc]>L and not seen[nr][nc]:\n                        seen[nr][nc]=True\n                        q.append((nr,nc))\nprint(cnt)', tip: '水位を段階的に上げながら何度も聞かれる場合は、マスを標高順に足していくUnion-Findのオフライン処理に切り替えると全クエリが一気に片づく。', ins: ['3 3 1\n2 1 2\n1 1 1\n2 1 3\n', '2 2 0\n1 1\n1 1\n', '2 2 5\n1 2\n3 4\n', '1 5 2\n1 3 1 3 3\n', '3 3 0\n1 0 1\n0 0 0\n1 0 1\n', '2 3 1\n2 2 1\n1 2 2\n'] })

t({ lv: 582, concept: 'グラフ: BFSの訪問順', title: '幅優先探索の訪問順序', tags: ['グラフ', 'BFS'], io: '1行目に n m s、続く m 行に無向辺が与えられます。', ask: '頂点 s から幅優先探索(隣接は番号の小さい順に訪問)したときの訪問順を空白区切りで出力してください(到達できる頂点のみ)。', h1: '隣接リストをソートしておく。', h2: 'キューに入れた順=訪問順になる。', ref: 'from collections import deque\nn,m,s=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\nfor a in g:\n    a.sort()\nseen=[False]*(n+1)\nseen[s]=True\nq=deque([s])\nout=[]\nwhile q:\n    x=q.popleft()\n    out.append(x)\n    for y in g[x]:\n        if not seen[y]:\n            seen[y]=True\n            q.append(y)\nprint(*out)', tip: '訪問順を一意にするには走査順の規約(小さい順)が必須。アルゴリズムの「出力を検証できる形」に固定する習慣はテストのしやすさに直結する。', ins: ['5 4 1\n1 3\n1 2\n2 4\n3 5\n', '4 3 2\n1 2\n2 3\n3 4\n', '3 0 1\n', '6 5 3\n3 6\n3 1\n1 2\n6 5\n5 4\n', '4 4 1\n1 2\n1 3\n2 4\n3 4\n', '2 1 2\n1 2\n'] })

t({ lv: 583, concept: 'グラフ: 頂点コストの最短路', title: '通行料が頂点にかかる最短路', tags: ['グラフ', 'ダイクストラ'], io: '1行目に n m s t、2行目に各頂点の通行料、続く m 行に無向辺が与えられます。', ask: '通るたびに頂点の通行料を払う(出発点・到着点も払う)ときの、s から t への最小合計を出力してください。到達不能なら -1。', h1: '辺の重みではなく頂点の重み。', h2: '「辺を渡って y に入るときに cost[y] を払う」と読み替えれば普通のダイクストラになる(初期値は cost[s])。', ref: 'import heapq\nn,m,s,t=map(int,input().split())\ncost=list(map(int,input().split()))\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\nINF=float("inf")\ndist=[INF]*(n+1)\ndist[s]=cost[s-1]\nh=[(dist[s],s)]\nwhile h:\n    d,x=heapq.heappop(h)\n    if d>dist[x]:\n        continue\n    for y in g[x]:\n        nd=d+cost[y-1]\n        if nd<dist[y]:\n            dist[y]=nd\n            heapq.heappush(h,(nd,y))\nprint(dist[t] if dist[t]<INF else -1)', tip: '頂点重みは「入る辺に付け替える」だけで辺重みに帰着する。逆に辺重みを頂点に割るのは一般に不可能、という非対称も覚えておきたい。', ins: ['4 4 1 4\n1 10 1 1\n1 2\n2 4\n1 3\n3 4\n', '2 1 1 2\n5 7\n1 2\n', '3 1 1 3\n1 1 1\n1 2\n', '3 3 1 3\n1 100 1\n1 2\n2 3\n1 3\n', '1 0 1 1\n9\n', '5 5 1 5\n1 2 2 2 1\n1 2\n2 5\n1 3\n3 4\n4 5\n'] })

t({ lv: 584, concept: 'グラフ: 同じ隣接を持つ頂点対', title: '双子の頂点ペアを数える', tags: ['グラフ'], io: '1行目に n m、続く m 行に無向辺が与えられます。', ask: '2頂点 u,v で「互いを除いた隣接集合が完全に一致する」ペア(双子)の個数を出力してください。', h1: '隣接を集合で持つ。', h2: 'ペアごとに adj[u]−{v} と adj[v]−{u} を比較する。', ref: 'n,m=map(int,input().split())\nadj=[set() for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    adj[u].add(v)\n    adj[v].add(u)\ncnt=0\nfor u in range(1,n+1):\n    for v in range(u+1,n+1):\n        if adj[u]-{v}==adj[v]-{u}:\n            cnt+=1\nprint(cnt)', tip: '双子(モジュール)の縮約はグラフを小さくする前処理として強力。大規模では「隣接集合のハッシュでグループ化」してO(n+m)に落とす。', ins: ['3 2\n1 3\n2 3\n', '4 4\n1 2\n2 3\n3 4\n4 1\n', '2 1\n1 2\n', '3 0\n', '4 3\n1 2\n1 3\n1 4\n', '3 3\n1 2\n2 3\n1 3\n'] })

t({ lv: 585, concept: 'グラフ: 往復の最短距離', title: '行って帰る最短の総距離', tags: ['グラフ', 'ダイクストラ'], io: '1行目に n m s t、続く m 行に有向辺 u v w が与えられます。', ask: 's から t へ行き、t から s へ帰る(経路は別でよい)ときの総距離の最小を出力してください。どちらかが不可能なら -1。', h1: '行きと帰りは独立に最短でよい。', h2: 's からのダイクストラと t からのダイクストラを1回ずつ。', ref: 'import heapq\nn,m,s,t=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v,w=map(int,input().split())\n    g[u].append((v,w))\ndef dij(src):\n    INF=float("inf")\n    dist=[INF]*(n+1)\n    dist[src]=0\n    h=[(0,src)]\n    while h:\n        d,x=heapq.heappop(h)\n        if d>dist[x]:\n            continue\n        for y,w in g[x]:\n            if d+w<dist[y]:\n                dist[y]=d+w\n                heapq.heappush(h,(d+w,y))\n    return dist\na=dij(s)[t]\nb=dij(t)[s]\nprint(a+b if a<float("inf") and b<float("inf") else -1)', tip: '有向グラフでは行きと帰りが別問題になる。多数の頂点から1点への最短が要るときは「辺を逆向きにした逆グラフで1回」も定石。', ins: ['3 4 1 3\n1 2 1\n2 3 1\n3 2 1\n2 1 1\n', '2 2 1 2\n1 2 3\n2 1 5\n', '2 1 1 2\n1 2 3\n', '4 5 1 4\n1 2 1\n2 4 1\n4 3 1\n3 1 1\n1 4 5\n', '1 0 1 1\n', '3 3 1 2\n1 2 2\n2 3 2\n3 1 2\n'] })

t({ lv: 586, concept: 'BFS: 全ての宝を集める最短', title: '宝を全部拾う最短歩数', tags: ['BFS', 'bit演算'], io: '1行目に H W、続く H 行に盤面(@:開始, *:宝, #:壁, .:床)が与えられます(宝は4個以下)。', ask: '全ての宝を拾う最小歩数を出力してください。不可能なら -1。', h1: '拾った宝の集合をビットマスクで状態に足す。', h2: '(位置, 集めた集合) のBFS。宝マスに入ったらビットを立てる。', ref: 'from collections import deque\nh,w=map(int,input().split())\ng=[input() for _ in range(h)]\nts=[]\nfor i in range(h):\n    for j in range(w):\n        if g[i][j]=="@":\n            sr,sc=i,j\n        if g[i][j]=="*":\n            ts.append((i,j))\nidx={p:i for i,p in enumerate(ts)}\nfull=(1<<len(ts))-1\nseen={(sr,sc,0)}\nq=deque([(sr,sc,0,0)])\nans=-1\nwhile q:\n    r,c,k,d=q.popleft()\n    if k==full:\n        ans=d\n        break\n    for dr,dc in ((1,0),(-1,0),(0,1),(0,-1)):\n        nr,nc=r+dr,c+dc\n        if 0<=nr<h and 0<=nc<w and g[nr][nc]!="#":\n            nk=k\n            if (nr,nc) in idx:\n                nk|=1<<idx[(nr,nc)]\n            if (nr,nc,nk) not in seen:\n                seen.add((nr,nc,nk))\n                q.append((nr,nc,nk,d+1))\nprint(ans)', tip: '宝が多いときは宝間の最短距離を前計算して巡回セールスマンのbitDPへ2段化する。少なければ状態BFS一発の方が実装が軽い。', ins: ['1 4\n@..*\n', '1 5\n*.@.*\n', '2 2\n@#\n#*\n', '3 3\n@.*\n.#.\n*..\n', '1 1\n@\n', '2 3\n@.*\n..*\n'] })

t({ lv: 587, concept: '木: キャタピラ木の判定', title: '葉を取ると一本道になるか', tags: ['木'], io: '1行目に頂点数 n、続く n−1 行に木の辺が与えられます。', ask: '全ての葉(次数1の頂点)を取り除いた残りが一本道(または空・1頂点)になる木をキャタピラ木といいます。yes / no で判定してください。', h1: '葉を除いた「背骨」の頂点集合を作る。', h2: '背骨の各頂点について、背骨内の隣接が2以下なら一本道。', ref: 'n=int(input())\ndeg=[0]*(n+1)\nadj=[[] for _ in range(n+1)]\nfor _ in range(n-1):\n    u,v=map(int,input().split())\n    deg[u]+=1\n    deg[v]+=1\n    adj[u].append(v)\n    adj[v].append(u)\ncore=set(v for v in range(1,n+1) if deg[v]>1)\nok=True\nfor v in core:\n    if sum(1 for y in adj[v] if y in core)>2:\n        ok=False\nprint("yes" if ok else "no")', tip: 'キャタピラ木は「区間グラフになる木」と特徴付けられ、化学のベンゼン系分子の骨格表現にも現れる。背骨+足という分解は木の形の言語化に便利。', ins: ['5\n1 2\n2 3\n3 4\n2 5\n', '7\n1 2\n2 3\n3 4\n4 5\n3 6\n6 7\n', '2\n1 2\n', '4\n1 2\n1 3\n1 4\n', '6\n1 2\n2 3\n3 4\n4 5\n5 6\n', '7\n1 2\n2 3\n1 4\n4 5\n1 6\n6 7\n'] })

t({ lv: 588, concept: 'グラフ: 完全二部グラフの判定', title: '完全二部グラフになっているか', tags: ['グラフ', 'BFS'], io: '1行目に n m、続く m 行に連結な無向グラフの辺が与えられます。', ask: 'グラフが完全二部グラフ(2つの組に分かれ、組をまたぐ全てのペアに辺がある)なら yes、そうでなければ no を出力してください。', h1: 'まず2彩色できるか(二部性)を確かめる。', h2: '二部なら片側 a 人・もう片側 b 人として、辺数がちょうど a×b か見る。', ref: 'from collections import deque\nn,m=map(int,input().split())\nadj=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    adj[u].append(v)\n    adj[v].append(u)\ncolor=[0]*(n+1)\ncolor[1]=1\nq=deque([1])\nok=True\na,b=1,0\nvis=1\nwhile q:\n    x=q.popleft()\n    for y in adj[x]:\n        if color[y]==0:\n            color[y]=3-color[x]\n            vis+=1\n            if color[y]==1:\n                a+=1\n            else:\n                b+=1\n            q.append(y)\n        elif color[y]==color[x]:\n            ok=False\nprint("yes" if ok and vis==n and m==a*b else "no")', tip: '「全ペアに辺があるか」を1本ずつ調べる代わりに辺数の勘定 a×b で言い切る。数え上げによる構造判定は次数列・辺数だけで済むことが多い。', ins: ['4 4\n1 3\n1 4\n2 3\n2 4\n', '3 2\n1 2\n1 3\n', '4 3\n1 3\n1 4\n2 3\n', '3 3\n1 2\n2 3\n1 3\n', '2 1\n1 2\n', '5 6\n1 4\n1 5\n2 4\n2 5\n3 4\n3 5\n'] })

t({ lv: 589, concept: 'グラフ: 有名人探し', title: '全員が知っている人を探す', tags: ['グラフ'], io: '1行目に人数 n、続く n 行に n×n の行列(i行j列が1なら「iはjを知っている」、対角は0)が与えられます。', ask: '自分は誰も知らないが、他の全員から知られている人(有名人)の番号を出力してください。いなければ -1。', h1: '2人を比べると片方は必ず候補から外れる(iがjを知っていればiは有名人でない)。', h2: '1回の走査で候補を1人に絞り、最後に候補が本物か検証する。', ref: 'n=int(input())\nk=[list(map(int,input().split())) for _ in range(n)]\nc=0\nfor i in range(1,n):\n    if k[c][i]:\n        c=i\nok=all((not k[c][j]) and (k[j][c] or j==c) for j in range(n))\nprint(c+1 if ok else -1)', tip: '「1対1の比較で必ず片方が脱落する」構造ならトーナメント式にO(n)で絞れる。過半数投票のボイヤー–ムーアと同じ設計思想。', ins: ['3\n0 1 0\n0 0 0\n1 1 0\n', '2\n0 1\n0 0\n', '2\n0 0\n0 0\n', '3\n0 0 1\n0 0 1\n0 0 0\n', '3\n0 1 1\n1 0 1\n1 1 0\n', '1\n0\n'] })

t({ lv: 590, concept: 'グラフ: 1辺追加で最短を縮める', title: '新しい道を1本引いた最短距離', tags: ['グラフ', 'ダイクストラ'], io: '1行目に n m k s t、続く m 行に既存の無向辺 u v w、続く k 行に建設候補の辺 u v w が与えられます。', ask: '候補から高々1本を追加できるとき、s から t への最短距離の最小を出力してください。到達不能なら -1。', h1: '候補ごとに最短路を計算し直すと遅い。', h2: 's からの距離と t からの距離を前計算すれば、候補 (u,v,w) の効果は ds[u]+w+dt[v] と ds[v]+w+dt[u] で O(1)。', ref: 'import heapq\nn,m,k,s,t=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v,w=map(int,input().split())\n    g[u].append((v,w))\n    g[v].append((u,w))\ndef dij(src):\n    INF=float("inf")\n    dist=[INF]*(n+1)\n    dist[src]=0\n    h=[(0,src)]\n    while h:\n        d,x=heapq.heappop(h)\n        if d>dist[x]:\n            continue\n        for y,w in g[x]:\n            if d+w<dist[y]:\n                dist[y]=d+w\n                heapq.heappush(h,(d+w,y))\n    return dist\nds=dij(s)\ndt=dij(t)\nbest=ds[t]\nfor _ in range(k):\n    u,v,w=map(int,input().split())\n    best=min(best,ds[u]+w+dt[v],ds[v]+w+dt[u])\nprint(best if best<float("inf") else -1)', tip: '両端からの距離表を前計算して候補をO(1)評価する「s側+新辺+t側」の分解は、道路建設・辺の重み変更・迂回路解析で繰り返し使う型。', ins: ['4 3 1 1 4\n1 2 1\n2 3 5\n3 4 1\n2 3 1\n', '2 0 1 1 2\n1 2 5\n', '3 2 1 1 3\n1 2 2\n2 3 2\n1 3 10\n', '2 1 1 1 2\n1 2 3\n1 2 1\n', '4 2 1 1 4\n1 2 1\n3 4 1\n2 3 1\n', '3 1 2 1 3\n1 2 1\n2 3 1\n1 3 4\n'] })

export const CATALOG = TASKS
