// 生成タスク 第24波：lv131〜149 の空き段を別計算で埋める。既存と重複しない概念のみ。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 131, concept: '数論: n以下の立方数', title: 'n以下の立方数の個数', tags: ['数論'], io: '正の整数 n が与えられます。', ask: '1 以上 n 以下の立方数 (1,8,27,…) の個数を出力してください。', h1: 'i³<=n の最大 i。', h2: 'i を増やす。', ref: 'n=int(input())\ni=1\nwhile i**3<=n:\n    i+=1\nprint(i-1)', ins: ['10\n', '27\n', '1\n', '100\n', '7\n', '64\n'] })
t({ lv: 132, concept: '数論: 約数の平均', title: '約数の平均', tags: ['数論'], io: '正の整数 n が与えられます。', ask: 'n の正の約数の平均を小数2桁で出力してください。', h1: '約数を集める。', h2: '和÷個数。', ref: 'n=int(input())\nd=[i for i in range(1,n+1) if n%i==0]\nprint(f"{sum(d)/len(d):.2f}")', ins: ['6\n', '12\n', '1\n', '28\n', '7\n', '100\n'] })
t({ lv: 133, concept: '数論: 過剰/完全/不足', title: '過剰数・完全数・不足数の判定', tags: ['数論'], io: '正の整数 n が与えられます。', ask: '真の約数の和が n より大きければ1、等しければ0、小さければ-1を出力してください。', h1: '真の約数の和を出す。', h2: 'n との大小。', ref: 'n=int(input())\ns=sum(i for i in range(1,n) if n%i==0)\nprint((s>n)-(s<n))', ins: ['12\n', '6\n', '8\n', '28\n', '10\n', '1\n'] })
t({ lv: 134, concept: '整数: 桁和が桁数で割れるか', title: '桁和が桁数の倍数か', tags: ['整数'], io: '非負整数 n が与えられます。', ask: '各桁の和が桁数で割り切れれば yes、違えば no を出力してください。', h1: '桁和と桁数。', h2: '余り0か。', ref: 'n=input()\nds=sum(int(c) for c in n)\nprint("yes" if ds%len(n)==0 else "no")', ins: ['12\n', '123\n', '5\n', '36\n', '99\n', '10\n'] })
t({ lv: 135, concept: '整数: 2進回文', title: '2進数で回文か', tags: ['ビット演算'], io: '正の整数 n が与えられます。', ask: 'n を2進数にしたとき回文なら yes、違えば no を出力してください。', h1: 'bin(n)[2:]。', h2: '反転と一致。', ref: 'n=int(input())\nb=bin(n)[2:]\nprint("yes" if b==b[::-1] else "no")', ins: ['5\n', '6\n', '9\n', '7\n', '10\n', '1\n'] })
t({ lv: 136, concept: '整数: 2進の0の数', title: '2進数の0の個数', tags: ['ビット演算'], io: '非負整数 n が与えられます。', ask: 'n の2進表現に含まれる0の個数を出力してください。', h1: 'bin(n)[2:]。', h2: "'0' を数える。", ref: 'n=int(input())\nprint(bin(n)[2:].count("0"))', ins: ['8\n', '5\n', '0\n', '255\n', '10\n', '16\n'] })
t({ lv: 137, concept: '整数: 桁が単調増加', title: '各桁が単調増加か', tags: ['整数'], io: '非負整数 n が与えられます。', ask: '上の桁から見て各桁が単調非減少なら yes、違えば no を出力してください。', h1: '隣の桁を比較。', h2: 'all で確認。', ref: 'n=input()\nprint("yes" if all(n[i]<=n[i+1] for i in range(len(n)-1)) else "no")', ins: ['123\n', '1357\n', '321\n', '112\n', '5\n', '1213\n'] })
t({ lv: 138, concept: '整数: 桁が全て異なる', title: '各桁がすべて異なるか', tags: ['整数', 'set'], io: '非負整数 n が与えられます。', ask: 'すべての桁が異なれば yes、重複があれば no を出力してください。', h1: 'set の大きさと比較。', h2: '等しければ全て異なる。', ref: 'n=input()\nprint("yes" if len(set(n))==len(n) else "no")', ins: ['123\n', '112\n', '1234\n', '9\n', '1213\n', '10\n'] })
t({ lv: 139, concept: '整数: 数字の種類数', title: '使われている数字の種類数', tags: ['set'], io: '非負整数 n が与えられます。', ask: 'n に使われている相異なる数字の種類数を出力してください。', h1: '文字の集合。', h2: 'len(set)。', ref: 'print(len(set(input())))', ins: ['1223\n', '111\n', '1234\n', '9\n', '1010\n', '505\n'] })
t({ lv: 140, concept: '整数: 最大桁と最小桁の差', title: '最大の桁と最小の桁の差', tags: ['整数'], io: '非負整数 n が与えられます。', ask: '最大の桁の数字と最小の桁の数字の差を出力してください。', h1: '文字の max と min。', h2: 'int にして差。', ref: 'n=input()\nprint(int(max(n))-int(min(n)))', ins: ['1234\n', '999\n', '5\n', '90\n', '321\n', '405\n'] })
t({ lv: 141, concept: '数列: n以下の最大フィボ', title: 'n を超えない最大のフィボナッチ数', tags: ['数列'], io: '正の整数 n が与えられます。', ask: 'n 以下で最大のフィボナッチ数を出力してください (1,1,2,3,5,…)。', h1: 'フィボを n まで進める。', h2: '超える直前の値。', ref: 'n=int(input())\na,b=0,1\nwhile b<=n:\n    a,b=b,a+b\nprint(a)', ins: ['10\n', '1\n', '100\n', '4\n', '21\n', '7\n'] })
t({ lv: 142, concept: '数論: 平方根以下の最大平方数', title: 'n以下の最大の平方数', tags: ['数論'], io: '正の整数 n が与えられます。', ask: 'n 以下で最大の平方数を出力してください。', h1: 'isqrt(n)。', h2: 'その2乗。', ref: 'import math\nn=int(input())\nprint(math.isqrt(n)**2)', ins: ['10\n', '16\n', '1\n', '99\n', '50\n', '7\n'] })
t({ lv: 143, concept: 'ビット: 2の最大の冪指数', title: 'n以下の最大の2のべきの指数', tags: ['ビット演算'], io: '正の整数 n が与えられます。', ask: '2^k <= n となる最大の k を出力してください。', h1: 'bit_length。', h2: 'bit_length-1。', ref: 'n=int(input())\nprint(n.bit_length()-1)', ins: ['8\n', '7\n', '1\n', '1024\n', '5\n', '100\n'] })
t({ lv: 144, concept: '進数: 3進数の桁数', title: '3進数で表した桁数', tags: ['進数変換'], io: '正の整数 n が与えられます。', ask: 'n を3進数で表したときの桁数を出力してください。', h1: '3 で割り続ける。', h2: '回数を数える。', ref: 'n=int(input())\nc=0\nwhile n>0:\n    n//=3\n    c+=1\nprint(c)', ins: ['1\n', '3\n', '9\n', '26\n', '27\n', '100\n'] })
t({ lv: 145, concept: '進数: 3進数の桁和', title: '3進数の各桁の和', tags: ['進数変換'], io: '正の整数 n が与えられます。', ask: 'n を3進数で表したときの各桁の和を出力してください。', h1: '%3 と //3。', h2: '余りを足す。', ref: 'n=int(input())\ns=0\nwhile n>0:\n    s+=n%3\n    n//=3\nprint(s)', ins: ['1\n', '5\n', '9\n', '26\n', '100\n', '8\n'] })
t({ lv: 146, concept: 'ビット: 最下位の1の位置', title: '最下位の立っているビットの位置', tags: ['ビット演算'], io: '正の整数 n が与えられます。', ask: '最下位の1が下から何番目か (0始まり) を出力してください。', h1: 'n&-n で最下位ビット。', h2: 'その桁位置。', ref: 'n=int(input())\nprint((n&-n).bit_length()-1)', ins: ['12\n', '8\n', '1\n', '6\n', '1024\n', '7\n'] })
t({ lv: 147, concept: 'ビット: 2進の連続0の最長', title: '2進数の連続する0の最長', tags: ['ビット演算'], io: '正の整数 n が与えられます。', ask: 'n の2進表現で0が連続する最長の長さを出力してください (なければ0)。', h1: 'bin を 1 で分割。', h2: '0の塊の最大長。', ref: 'n=int(input())\nprint(max(len(z) for z in bin(n)[2:].split("1")))', ins: ['8\n', '5\n', '1\n', '255\n', '1001\n', '16\n'] })
t({ lv: 148, concept: '数論: 約数の個数が素数か', title: '約数の個数が素数か', tags: ['数論'], io: '正の整数 n が与えられます。', ask: 'n の約数の個数が素数なら yes、違えば no を出力してください。', h1: '約数の個数 d を出す。', h2: 'd が素数か判定。', ref: 'n=int(input())\nd=sum(1 for i in range(1,n+1) if n%i==0)\nprint("yes" if d>1 and all(d%i for i in range(2,int(d**0.5)+1)) else "no")', ins: ['4\n', '6\n', '12\n', '1\n', '16\n', '7\n'] })
t({ lv: 149, concept: '数論: 半素数', title: '半素数か (2つの素数の積)', tags: ['数論', '素数'], io: '2以上の整数 n が与えられます。', ask: 'n が「(重複を許す)2個の素数の積」なら yes、違えば no を出力してください。', h1: '素因数を重複込みで数える。', h2: '総数がちょうど2か。', ref: 'n=int(input())\nc=0\nm=n\nd=2\nwhile d*d<=m:\n    while m%d==0:\n        c+=1\n        m//=d\n    d+=1\nif m>1:\n    c+=1\nprint("yes" if c==2 else "no")', ins: ['6\n', '4\n', '12\n', '15\n', '7\n', '9\n'] })

export const CATALOG = TASKS
