// 生成タスク 第82波：各レベル3問化フェーズ(9)。lv427〜475 の薄い49段に3問目を追加。
// 最上級帯: 数論/文字列アルゴ/幾何/数え上げ/ゲーム。クラスタ3問まで可・言い換え水増し禁止。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 427, concept: '数論: 原始根かどうか', title: 'その底は全部を生むか', tags: ['数論'], io: 'g p (pは素数、1≤g<p) が空白区切りで1行で与えられます。', ask: 'g が p の原始根(gのべき乗が 1〜p−1 を全て生成する)なら yes、そうでなければ no を出力してください。', h1: 'gの位数がp−1に等しいか。', h2: 'べき乗を順に掛けて初めて1に戻る回数を数える。', ref: 'g,p=map(int,input().split())\nx=1\nk=0\nwhile True:\n    x=x*g%p\n    k+=1\n    if x==1:\n        break\nprint("yes" if k==p-1 else "no")', tip: '最小原始根(同レベル既出)を探すときの内側の判定を独立させた形。高速化はp−1の素因数qごとに g^((p−1)/q)≠1 を確かめる方法で、位数の約数性が効いている。', ins: ['3 7\n', '2 7\n', '2 5\n', '4 5\n', '5 23\n', '1 5\n'] })

t({ lv: 428, concept: '数論: 法pでのk乗根の最小解', title: 'k乗して合同になる最小の数', tags: ['数論'], io: 'k a p (pは素数、解が存在する入力のみ) が空白区切りで1行で与えられます。', ask: 'x^k ≡ a (mod p) を満たす最小の非負整数 x を出力してください。', h1: '解の個数(同レベル既出)の構成版。', h2: 'xを0からp−1まで試す。powの3引数が速い。', ref: 'k,a,p=map(int,input().split())\nx=0\nwhile pow(x,k,p)!=a%p:\n    x+=1\nprint(x)', tip: '平方根(Tonelli)のk乗一般化は原始根と離散対数を経由して解ける。総当たりO(p)は、その高度な解法の正しさを確かめる最小の対照実験になる。', ins: ['2 4 7\n', '3 1 7\n', '2 2 7\n', '5 0 11\n', '3 6 7\n', '2 9 11\n'] })

t({ lv: 429, concept: '文字列: 辞書順最大の接尾辞の位置', title: '一番強い後半戦', tags: ['文字列'], io: '文字列が1行で与えられます。', ask: '辞書順で最大の接尾辞の開始位置(1始まり)を出力してください。', h1: '最小の接尾辞(同レベル既出)の鏡像。', h2: '全接尾辞を比較するのが基準解。', ref: 's=input()\nbest=0\nfor i in range(1,len(s)):\n    if s[i:]>s[best:]:\n        best=i\nprint(best+1)', tip: '最大接尾辞はリョンドン分解(Lyndon分解)の要で、線形時間のデュヴァル法が知られる。スライスの比較1発で書ける素朴版はその検証台として最適。', ins: ['banana\n', 'abc\n', 'zab\n', 'aa\n', 'abab\n', 'cba\n'] })

t({ lv: 430, concept: '文字列: 隣接接尾辞のLCP配列の出力', title: '隣どうしの一致の表', tags: ['文字列'], io: '文字列が1行で与えられます。', ask: '全ての接尾辞を辞書順に並べ、隣り合う接尾辞どうしの最長共通接頭辞の長さを順に空白区切りで出力してください(接尾辞が1つなら空ではなく 0 を出力)。', h1: '総和(同レベル既出)の中身をそのまま見せる版。', h2: 'ソートした隣接ペアで先頭一致を数える。', ref: 's=input()\nsuf=sorted(s[i:] for i in range(len(s)))\nout=[]\nfor i in range(len(suf)-1):\n    a,b=suf[i],suf[i+1]\n    k=0\n    while k<len(a) and k<len(b) and a[k]==b[k]:\n        k+=1\n    out.append(k)\nprint(" ".join(map(str,out)) if out else "0")', tip: 'LCP配列は接尾辞配列の相棒で、部分文字列の種類数や最長重複部分文字列がこの表の読み取りだけで出る。カサイ法なら線形時間で構築できる。', ins: ['banana\n', 'aaa\n', 'abc\n', 'abab\n', 'zz\n', 'ab\n'] })

t({ lv: 431, concept: '文字列: 最初に見つかるパターン', title: '一番早く現れる合図', tags: ['文字列'], io: '1行目にテキスト、2行目に複数のパターンが空白区切りで与えられます。', ask: 'テキスト中で最も早い位置に現れるパターンを出力してください(同じ位置なら先に書かれたもの、どれも現れなければ none)。', h1: 'findで各パターンの初出位置を取る。', h2: '(位置, 入力順)の最小を選ぶ。見つからない印の−1に注意。', ref: 'text=input()\npats=input().split()\nbest=None\nans="none"\nfor i,p in enumerate(pats):\n    pos=text.find(p)\n    if pos>=0 and (best is None or pos<best):\n        best=pos\n        ans=p\nprint(ans)', tip: '複数パターンの総出現(同レベル既出)が全部数える問題なら、こちらは最初の1件で打ち切れる問題。ログ監視で「最初に出たエラー種別」を特定する処理そのもの。', ins: ['abcde\ncd bc\n', 'hello\nxyz lo he\n', 'aaaa\naa a\n', 'abc\nxy z\n', 'mississippi\nssi issi\n', 'test\nt est\n'] })

t({ lv: 432, concept: 'グラフ: 一筆書きの始点になれる頂点の数', title: 'どこからなら描き切れるか', tags: ['グラフ'], io: '1行目に頂点数 n と辺数 m (m≥1)、続く m 行に無向辺 u v が与えられます。', ask: '全ての辺をちょうど1回ずつなぞる歩き方(オイラー路)の始点になれる頂点の個数を出力してください(不可能なら 0)。', h1: '奇数次数の頂点の数で場合分け。', h2: '奇数次数が0個なら辺に触れる全頂点、2個ならその2つ、他は0。辺のある頂点が連結でなければ0。', ref: 'n,m=map(int,input().split())\ndeg=[0]*(n+1)\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    deg[u]+=1\n    deg[v]+=1\n    g[u].append(v)\n    g[v].append(u)\nstart=next(v for v in range(1,n+1) if deg[v]>0)\nseen=[False]*(n+1)\nseen[start]=True\nst=[start]\nwhile st:\n    x=st.pop()\n    for y in g[x]:\n        if not seen[y]:\n            seen[y]=True\n            st.append(y)\nif any(deg[v]>0 and not seen[v] for v in range(1,n+1)):\n    print(0)\nelse:\n    odd=[v for v in range(1,n+1) if deg[v]%2==1]\n    if len(odd)==0:\n        print(sum(1 for v in range(1,n+1) if deg[v]>0))\n    elif len(odd)==2:\n        print(2)\n    else:\n        print(0)', tip: 'オイラーの定理の「存在するか」を「どこから始められるか」に言い換えた版。閉路型なら任意の点、路型なら奇数次数の2点だけ、という非対称が答えの形に現れる。', ins: ['3 3\n1 2\n2 3\n3 1\n', '4 3\n1 2\n2 3\n3 4\n', '4 4\n1 2\n1 3\n1 4\n2 3\n', '2 1\n1 2\n', '4 2\n1 2\n3 4\n', '6 5\n1 2\n2 3\n3 4\n4 5\n5 6\n'] })

t({ lv: 433, concept: '論理: 割当でCNFを評価', title: 'その答案で全条件を満たすか', tags: ['論理'], io: '1行目に変数の数 n と節の数 m、2行目に各変数の値(0か1)、続く m 行に節(正の整数iは変数i、負の−iは変数iの否定。節の中はOR)が与えられます。', ask: '全ての節が満たされる(各節に真のリテラルが1つ以上ある)なら yes、そうでなければ no を出力してください。', h1: 'リテラルの真偽は符号で分岐。', h2: 'any と all の入れ子で書ける。', ref: 'n,m=map(int,input().split())\nval=list(map(int,input().split()))\nok=True\nfor _ in range(m):\n    lits=list(map(int,input().split()))\n    if not any((val[l-1]==1) if l>0 else (val[-l-1]==0) for l in lits):\n        ok=False\nprint("yes" if ok else "no")', tip: 'SATは解くのがNP完全でも、検算はこの通り線形時間。2-SAT(同レベル既出)のソルバを書いたら、返ってきた割当をこの評価器に通すのが正しい開発手順になる。', ins: ['2 2\n1 0\n1 2\n-1 -2\n', '1 1\n0\n1\n', '2 1\n0 1\n-1 2\n', '3 2\n1 1 0\n-3 1\n2 3\n', '1 2\n1\n1\n-1\n', '2 2\n0 0\n-1 -2\n1 -2\n'] })

t({ lv: 434, concept: 'bit演算: ORが目標になるペアの数', title: '合わせてぴったりのビット', tags: ['bit演算', '数え上げ'], io: '1行目に目標 T、2行目に整数列が与えられます。', ask: 'i<j で a[i] OR a[j] が T になるペアの個数を出力してください。', h1: 'ANDが0のペア(同レベル既出)の仲間。', h2: '総当たりが基準解。両者ともTの部分集合ビットであることが必要条件。', ref: 't=int(input())\na=list(map(int,input().split()))\nn=len(a)\ncnt=0\nfor i in range(n):\n    for j in range(i+1,n):\n        if a[i]|a[j]==t:\n            cnt+=1\nprint(cnt)', tip: '高速化は「Tの部分集合だけ残して、ORがTちょうど(真部分集合を除く)を包除で数える」SOS DPの出番。総当たりの答えとの一致確認が包除の符号ミスを炙り出す。', ins: ['7\n1 2 5 3\n', '3\n1 2 3\n', '1\n1 1\n', '4\n1 2\n', '6\n2 4 6\n', '5\n5 5 1\n'] })

t({ lv: 435, concept: '貪欲: 隣接同値を消す最小の書き換え数', title: '連続を断ち切る最少の修正', tags: ['貪欲'], io: '整数列が1行で空白区切りで与えられます。', ask: 'いくつかの要素を好きな値に書き換えて「隣り合う要素が等しい箇所」を無くすときの、書き換えの最小回数を出力してください。', h1: '同じ値の連続だけを見ればよい。', h2: '長さLの連続からは L//2 個を書き換えれば断ち切れる。', ref: 'a=list(map(int,input().split()))\nans=0\ni=0\nn=len(a)\nwhile i<n:\n    j=i\n    while j<n and a[j]==a[i]:\n        j+=1\n    ans+=(j-i)//2\n    i=j\nprint(ans)', tip: '1つおきに書き換えれば十分で、それ未満では鳩の巣的に不可能、という下限と上限が一致する貪欲。書き換え先は「両隣と違う値」が常に取れる(値域が3以上あれば)ことも正当性の一部。', ins: ['1 1 1\n', '1 2 3\n', '2 2 2 2\n', '5 5 1 1 1\n', '7\n', '3 3 3 3 3\n'] })

t({ lv: 436, concept: '区間: すべての区間の共通部分の長さ', title: '全員の都合が合う時間', tags: ['区間'], io: '1行目に n、続く n 行に区間 l r (l≤r、両端を含む整数区間) が与えられます。', ask: '全ての区間に共通して含まれる整数の個数を出力してください(無ければ 0)。', h1: '共通部分は「最大の左端」から「最小の右端」まで。', h2: 'max(l) と min(r) を集めて引き算。', ref: 'n=int(input())\nls=[]\nrs=[]\nfor _ in range(n):\n    l,r=map(int,input().split())\n    ls.append(l)\n    rs.append(r)\nprint(max(0,min(rs)-max(ls)+1))', tip: '区間の積集合は max と min の1組で決まり、n個でも計算は変わらない。和集合(マージが要る)との対称性で、積の方が圧倒的に簡単という非対称が面白い。', ins: ['3\n1 5\n2 6\n0 4\n', '2\n1 2\n3 4\n', '1\n5 9\n', '2\n1 10\n5 5\n', '3\n0 3\n3 8\n2 5\n', '2\n-2 2\n-1 3\n'] })

t({ lv: 437, concept: 'DP: 両者がP以上もらえる分け方があるか', title: '二人とも満足の山分け', tags: ['DP'], io: '1行目に P、2行目に正整数の列が与えられます。', ask: '列を2つのグループに分けて、両方のグループの和を P 以上にできるなら yes、できなければ no を出力してください。', h1: '片方の和が決まればもう片方は残り。', h2: '作れる和の集合から s≥P かつ 合計−s≥P を探す。', ref: 'P=int(input())\na=list(map(int,input().split()))\ntotal=sum(a)\ns={0}\nfor x in a:\n    s|={y+x for y in s}\nprint("yes" if any(x>=P and total-x>=P for x in s) else "no")', tip: '合計が2P未満なら即noという事前チェックが枝刈りになる。2制約ナップサック(同レベル既出)と同じく「もう片方は引き算で決まる」構造が計算を1次元に保つ。', ins: ['3\n2 2 3\n', '5\n4 4\n', '1\n1 1\n', '10\n5 5 5 5\n', '6\n5 5\n', '4\n8 1 3\n'] })

t({ lv: 438, concept: '木DP: マッチングの総数', title: '木の中のペアの作り方', tags: ['木DP'], io: '1行目に頂点数 n (n≥2)、2行目に頂点2〜nの親が与えられます(根は頂点1)。', ask: '辺の部分集合で「どの頂点も高々1本にしか使われない」もの(マッチング。空集合も含む)の総数を出力してください。', h1: '最大マッチング(同レベル既出)の数え上げ版。', h2: '各頂点で「親と組む準備ができた状態」と「組まない状態」の2つの数を持つ。', ref: 'n=int(input())\npar=list(map(int,input().split()))\nch=[[] for _ in range(n+1)]\nfor i in range(2,n+1):\n    ch[par[i-2]].append(i)\nfree=[1]*(n+1)\nmat=[0]*(n+1)\nfor v in range(n,0,-1):\n    f=1\n    for c in ch[v]:\n        f*=free[c]+mat[c]\n    m=0\n    for c in ch[v]:\n        rest=1\n        for c2 in ch[v]:\n            if c2!=c:\n                rest*=free[c2]+mat[c2]\n        m+=free[c]*rest\n    free[v]=f\n    mat[v]=m\nprint(free[1]+mat[1])', tip: '一般グラフのマッチング数え上げは#P困難だが、木ならこの2状態DPで多項式時間。パス(一直線の木)ではフィボナッチ数が現れる、という検算用の身元も持っている。', ins: ['2\n1\n', '3\n1 1\n', '3\n1 2\n', '4\n1 2 3\n', '4\n1 1 1\n', '7\n1 1 2 2 3 3\n'] })

t({ lv: 439, concept: 'グラフ: 支配集合かどうかの検証', title: 'その見張り配置で全域カバーか', tags: ['グラフ'], io: '1行目に頂点数 n、辺数 m、集合の大きさ k、続く m 行に無向辺 u v、最終行に k 個の頂点が与えられます。', ask: 'その頂点集合が支配集合(どの頂点も、集合に入っているか集合のどれかと隣接している)なら yes、そうでなければ no を出力してください。', h1: '最小支配集合(同レベル既出)を解く前の検算器。', h2: '集合とその隣人を全部マークして、全頂点が塗れたか見る。', ref: 'first=input().split()\nn,m,k=int(first[0]),int(first[1]),int(first[2])\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\nS=list(map(int,input().split()))\ncov=[False]*(n+1)\nfor v in S:\n    cov[v]=True\n    for w in g[v]:\n        cov[w]=True\nprint("yes" if all(cov[1:]) else "no")', tip: '最適化がNP困難な問題ほど、検証器を先に書くのが定石(解の正しさだけは一瞬で確かめられる)。監視カメラや消防署の配置チェックがこの計算そのもの。', ins: ['4 3 1\n1 2\n1 3\n1 4\n1\n', '4 3 1\n1 2\n1 3\n1 4\n2\n', '3 2 2\n1 2\n2 3\n1 3\n', '5 4 1\n1 2\n2 3\n3 4\n4 5\n3\n', '2 1 1\n1 2\n1\n', '6 6 2\n1 2\n1 3\n4 5\n4 6\n2 3\n1 4\n1 4\n'] })

t({ lv: 440, concept: '幾何: 最大の三角形の面積の2倍', title: '3点で張る最大の帆', tags: ['幾何'], io: '1行目に点の数 n (n≥3)、続く n 行に座標 x y が与えられます。', ask: '3点を選んで作る三角形の面積の最大値の2倍(整数)を出力してください。', h1: '最小の三角形(同レベル既出)の鏡像。', h2: '外積の絶対値が面積の2倍。', ref: 'from itertools import combinations\nn=int(input())\npts=[tuple(map(int,input().split())) for _ in range(n)]\nbest=0\nfor a,b,c in combinations(pts,3):\n    s=abs((b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]))\n    if s>best:\n        best=s\nprint(best)', tip: '最大三角形の3頂点は必ず凸包の上に乗る、という観察がO(n³)からの高速化の入り口。2倍のまま整数で扱えば面積の比較に誤差が入り込まない。', ins: ['4\n0 0\n4 0\n0 4\n1 1\n', '3\n0 0\n1 0\n0 1\n', '4\n0 0\n2 0\n1 1\n1 2\n', '3\n0 0\n5 0\n5 5\n', '5\n0 0\n1 0\n2 0\n0 3\n1 1\n', '3\n-1 -1\n1 -1\n0 2\n'] })

t({ lv: 441, concept: '幾何: 原点から最も遠い点', title: '一番の旅人はどれ', tags: ['幾何'], io: '1行目に点の数 n、続く n 行に座標 x y が与えられます。', ask: '原点からの距離が最大の点の番号(1始まり、同距離なら最小の番号)を出力してください。', h1: '距離の2乗で比べる。', h2: '「より大きいときだけ」更新で先勝ち。', ref: 'n=int(input())\nbest=-1\nbd=-1\nfor i in range(n):\n    x,y=map(int,input().split())\n    d=x*x+y*y\n    if d>bd:\n        bd=d\n        best=i\nprint(best+1)', tip: '最遠ペア(同レベル既出)が全対を見るのに対し、基準点固定なら1パスで済む。ノルム最大の点は正規化やスケーリングの前処理で毎回探す実務の常連。', ins: ['3\n1 1\n3 4\n2 2\n', '1\n5 0\n', '2\n3 4\n4 3\n', '3\n0 0\n-5 0\n3 3\n', '2\n1 2\n2 1\n', '4\n1 0\n0 1\n-1 0\n0 -1\n'] })

t({ lv: 442, concept: '幾何: 二等辺三角形になる3点の数', title: '釣り合いの取れた三人組', tags: ['幾何'], io: '1行目に点の数 n、続く n 行に相異なる座標 x y が与えられます。', ask: '3点の組で「三角形を成し(一直線上でなく)、少なくとも2辺の長さが等しい」ものの個数を出力してください。', h1: '距離の2乗の比較で等辺を判定。', h2: '外積で退化(一直線)を除外。', ref: 'from itertools import combinations\nn=int(input())\npts=[tuple(map(int,input().split())) for _ in range(n)]\ndef d2(p,q):\n    return (p[0]-q[0])**2+(p[1]-q[1])**2\ncnt=0\nfor a,b,c in combinations(pts,3):\n    if (b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0])==0:\n        continue\n    x,y,z=d2(a,b),d2(a,c),d2(b,c)\n    if x==y or y==z or x==z:\n        cnt+=1\nprint(cnt)', tip: '距離の2乗どうしの等号比較は浮動小数なしの完全判定。直角三角形の3点組(同レベル既出)と同じ骨格で、条件式の1行だけが違う姉妹問題になっている。', ins: ['4\n0 0\n2 0\n1 2\n5 5\n', '3\n0 0\n1 0\n0 1\n', '3\n0 0\n1 0\n2 0\n', '4\n0 0\n2 0\n1 1\n1 3\n', '3\n0 0\n4 0\n2 3\n', '3\n0 0\n3 1\n1 3\n'] })

t({ lv: 443, concept: '数論: 平方の差で表す方法の数', title: '平方引く平方の作り方', tags: ['数論'], io: '正整数 N が1行で与えられます。', ask: 'N を x²−y² (x>y≥0 の整数) の形で表す方法の数を出力してください。', h1: 'x²−y²=(x−y)(x+y) と因数分解する。', h2: 'N=d×e (d≤e) で d と e の偶奇が一致する組を数える。', ref: 'n=int(input())\ncnt=0\nd=1\nwhile d*d<=n:\n    if n%d==0:\n        e=n//d\n        if (d+e)%2==0:\n            cnt+=1\n    d+=1\nprint(cnt)', tip: 'x=(d+e)/2, y=(e−d)/2 と復元できるので、方法の数は「偶奇の揃った約数ペア」の数に一致する。4で割って2余る数だけが表せない、という綺麗な特徴づけも導ける。', ins: ['15\n', '4\n', '1\n', '6\n', '16\n', '45\n'] })

t({ lv: 444, concept: '数論: 負のペル方程式の可解性', title: 'マイナス1に届くか', tags: ['数論'], io: '平方数でない正整数 D が1行で与えられます。', ask: 'x²−Dy²=−1 に正整数解があるなら yes、無ければ no を出力してください。', h1: '√Dの連分数の周期(既出)が鍵を握る。', h2: '周期が奇数のとき、そしてそのときに限り解がある。', ref: 'import math\nD=int(input())\na0=math.isqrt(D)\nm,d,a=0,1,a0\nperiod=0\nwhile a!=2*a0:\n    m=d*a-m\n    d=(D-m*m)//d\n    a=(a0+m)//d\n    period+=1\nprint("yes" if period%2==1 else "no")', tip: '通常のペル方程式(=+1)は常に解けるのに、−1側は周期の偶奇という繊細な条件で決まる。D=3は解けずD=2,5,10,13は解ける、と試すだけでも非自明さが伝わる。', ins: ['2\n', '5\n', '3\n', '13\n', '7\n', '10\n'] })

t({ lv: 445, concept: '数論: 3乗剰余かどうか', title: '3乗して届く値か', tags: ['数論'], io: 'a p (pは素数、0≤a<p) が空白区切りで1行で与えられます。', ask: 'x³ ≡ a (mod p) となる x が存在するなら yes、しなければ no を出力してください。', h1: '平方剰余の判定(同レベル既出)の3乗版。', h2: '全てのxを試すのが基準解。', ref: 'a,p=map(int,input().split())\nprint("yes" if any(pow(x,3,p)==a for x in range(p)) else "no")', tip: 'p≡2 (mod 3) なら3乗写像は全単射で全てが3乗剰余、p≡1 (mod 3) なら (p−1)/3 個しかない。オイラーの規準の3乗版 a^((p−1)/3) の値で判定する高速版もある。', ins: ['1 7\n', '2 7\n', '6 7\n', '0 5\n', '2 5\n', '3 7\n'] })

t({ lv: 446, concept: '文字列: 長さLで辞書順最大の窓', title: '一番強いL文字', tags: ['文字列'], io: '1行目に L、2行目に文字列(長さL以上)が与えられます。', ask: '長さ L の連続部分文字列のうち辞書順最大のものを出力してください。', h1: '最小版(同レベル既出)の鏡像。', h2: '全ての窓のmax。', ref: 'L=int(input())\ns=input()\nprint(max(s[i:i+L] for i in range(len(s)-L+1)))', tip: 'maxをジェネレータ式に直接かける1行解。窓の個数はn−L+1個で、L=1なら最大文字、L=nなら全体そのもの、と両端の退化ケースが検算に使える。', ins: ['2\nbanana\n', '1\nabc\n', '3\nabcabd\n', '2\nzz\n', '3\naaab\n', '2\nxyxz\n'] })

t({ lv: 447, concept: 'クエリ: 区間のANDとOR', title: '区間のビットの共通点と総和', tags: ['クエリ', 'bit演算'], io: '1行目に n q、2行目に長さ n の列、続く q 行に区間 l r が与えられます。', ask: '各区間について、全要素のビットANDとビットORを「AND OR」の形で1行ずつ出力してください。', h1: 'どちらも結合的な畳み込み。', h2: 'reduceで2回畳むか、ループで同時に。', ref: 'n,q=map(int,input().split())\na=list(map(int,input().split()))\nfor _ in range(q):\n    l,r=map(int,input().split())\n    x=a[l-1]\n    y=a[l-1]\n    for v in a[l:r]:\n        x&=v\n        y|=v\n    print(x,y)', tip: 'ANDは狭まる一方、ORは広がる一方、という単調性がある(伸ばすほどANDは減りORは増える)。この性質はスパーステーブルでの高速化と「区間の種類数がO(n log A)」の議論の土台。', ins: ['3 2\n6 3 5\n1 3\n2 3\n', '2 1\n4 4\n1 2\n', '4 2\n1 2 4 8\n1 4\n2 3\n', '1 1\n9\n1 1\n', '3 1\n7 7 7\n1 3\n', '5 2\n12 10 14 8 15\n1 3\n3 5\n'] })

t({ lv: 448, concept: 'クエリ: 追加と削除つきのk番目', title: '出入りする集団のk番目', tags: ['クエリ'], io: '1行目に操作数 q、続く q 行に「A x」(xを追加)、「D x」(xを1つ削除。存在は保証)、「Q k」(k番目に小さい値を出力) が与えられます。', ask: '各 Q に対して現在の多重集合で k 番目に小さい値を1行ずつ出力してください。', h1: 'リストで持ってソートするのが基準解。', h2: '削除はremoveで1個だけ。', ref: 'q=int(input())\na=[]\nfor _ in range(q):\n    parts=input().split()\n    if parts[0]=="A":\n        a.append(int(parts[1]))\n    elif parts[0]=="D":\n        a.remove(int(parts[1]))\n    else:\n        print(sorted(a)[int(parts[1])-1])', tip: '追加だけならヒープ、削除も混ざるとBIT上の二分探索や平衡木が本命になる、動的順位クエリの入り口。素朴解のO(q² log q)を基準に高速版を検証する。', ins: ['5\nA 3\nA 1\nQ 1\nD 1\nQ 1\n', '4\nA 5\nA 5\nQ 2\nQ 1\n', '6\nA 2\nA 7\nA 4\nQ 2\nD 4\nQ 2\n', '3\nA 9\nA 1\nQ 2\n', '7\nA 1\nA 2\nA 3\nD 2\nA 0\nQ 1\nQ 3\n', '2\nA 4\nQ 1\n'] })

t({ lv: 449, concept: '数え上げ: プリューファー列から木へ', title: '暗号から木を再建する', tags: ['数え上げ', 'グラフ'], io: '1行目に頂点数 n (n≥3)、2行目にプリューファー列(n−2個の1〜nの整数)が与えられます。', ask: '木を復元し、辺を追加した順(各ステップで「次数が残り1で番号最小の頂点」と列の先頭を結び、最後に残った2頂点を結ぶ)に「小さい番号 大きい番号」で1行ずつ出力してください。', h1: '各頂点の次数は「列に現れる回数+1」。', h2: '葉(次数1)の最小をヒープか走査で取り出す。', ref: 'n=int(input())\nseq=list(map(int,input().split()))\ndeg=[1]*(n+1)\nfor x in seq:\n    deg[x]+=1\nused=[False]*(n+1)\nfor x in seq:\n    leaf=next(v for v in range(1,n+1) if deg[v]==1 and not used[v])\n    print(min(leaf,x),max(leaf,x))\n    used[leaf]=True\n    deg[x]-=1\nrest=[v for v in range(1,n+1) if not used[v]]\nprint(rest[0],rest[1])', tip: 'プリューファー列と木の1対1対応こそがケイリーの公式 n^(n−2) の証明の心臓部。全域木の数(同レベル既出)の「なぜその数か」に、復元アルゴリズムで触れる。', ins: ['4\n2 2\n', '3\n1\n', '3\n3\n', '5\n1 1 1\n', '5\n2 3 4\n', '6\n3 3 4 4\n'] })

t({ lv: 450, concept: '木: 3頂点を結ぶ枝の最小辺数', title: '三叉路の合流点', tags: ['木', 'BFS'], io: '1行目に頂点数 n、続く n−1 行に辺 u v、最終行に3頂点 a b c が与えられます。', ask: '3頂点すべてを繋ぐために必要な辺の最小本数(3頂点を含む最小の部分木の辺数)を出力してください。', h1: '3頂点間の距離3つで表せる。', h2: '(d(a,b)+d(b,c)+d(a,c))÷2。', ref: 'from collections import deque\nn=int(input())\ng=[[] for _ in range(n+1)]\nfor _ in range(n-1):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\na,b,c=map(int,input().split())\ndef bfs(s):\n    dist=[-1]*(n+1)\n    dist[s]=0\n    q=deque([s])\n    while q:\n        x=q.popleft()\n        for y in g[x]:\n            if dist[y]<0:\n                dist[y]=dist[x]+1\n                q.append(y)\n    return dist\nda=bfs(a)\ndb=bfs(b)\nprint((da[b]+da[c]+db[c])//2)', tip: '3頂点のシュタイナー木は必ず「1つの合流点から3方向に伸びる形」になり、距離の和の半分という閉じた式で書ける。一般のシュタイナー木がNP困難なのと対照的な特例。', ins: ['5\n1 2\n2 3\n2 4\n4 5\n1 3 5\n', '3\n1 2\n2 3\n1 2 3\n', '4\n1 2\n1 3\n1 4\n2 3 4\n', '5\n1 2\n2 3\n3 4\n4 5\n1 3 5\n', '6\n1 2\n1 3\n2 4\n2 5\n3 6\n4 5 6\n', '3\n1 2\n1 3\n2 3 1\n'] })

t({ lv: 451, concept: '文字列: 回転一致の出現回数', title: '回した姿でもいいから探す', tags: ['文字列'], io: '1行目にテキスト、2行目にパターン(長さm)が与えられます。', ask: 'テキストの長さ m の窓のうち、パターンをいくつか回転させたものと一致する窓の個数を出力してください。', h1: '回転の全体はパターンを2つ繋げた文字列に隠れている。', h2: '窓が p+p の部分文字列(長さm)なら回転一致。', ref: 't=input()\np=input()\nm=len(p)\npp=p+p\nprint(sum(1 for i in range(len(t)-m+1) if t[i:i+m] in pp))', tip: '「sの回転 ⇔ s+s の長さ|s|の部分文字列」は回転問題の万能変換。最小シフト量(既出)や回転判定も全部この1本の橋を渡って文字列検索に帰着する。', ins: ['aabab\nab\n', 'aaaa\naa\n', 'abcabc\nbca\n', 'xyz\nab\n', 'aba\nab\n', 'hello\nlo\n'] })

t({ lv: 452, concept: '文字列: すべての周期の一覧', title: 'ずらして重なる幅の全部', tags: ['文字列'], io: '文字列(長さn)が1行で与えられます。', ask: '「全ての有効な i で s[i]==s[i+p]」となる周期 p (1≤p≤n、p=nは常に成立) を昇順に空白区切りで出力してください。', h1: '最小周期(同レベル既出)の全数版。', h2: '各pをずらし比較で確かめる。', ref: 's=input()\nn=len(s)\nout=[]\nfor p in range(1,n+1):\n    if all(s[i]==s[i+p] for i in range(n-p)):\n        out.append(p)\nprint(" ".join(map(str,out)))', tip: '周期の集合は「n−ボーダー長」の集合と一致する(周期とボーダーの双対)。細かい周期定理(Fine and Wilf)は2つの周期からより細かい周期を導く、この一覧の構造定理。', ins: ['ababab\n', 'aaa\n', 'abc\n', 'abab\n', 'aabaab\n', 'x\n'] })

t({ lv: 453, concept: '文字列: 最長回文の現れる回数', title: 'チャンピオン回文は何箇所', tags: ['文字列'], io: '文字列が1行で与えられます。', ask: '最長の回文である連続部分文字列の長さを L として、長さ L の回文部分文字列が現れる位置の数を出力してください。', h1: '最長の長さ(同レベル既出)を求めてから数え直す。', h2: '長さLの窓を全部回文判定。', ref: 's=input()\nn=len(s)\nL=1\nfor i in range(n):\n    for j in range(i,n):\n        t=s[i:j+1]\n        if t==t[::-1] and j-i+1>L:\n            L=j-i+1\ncnt=sum(1 for i in range(n-L+1) if s[i:i+L]==s[i:i+L][::-1])\nprint(cnt)', tip: '最適値を出してから「最適を実現するものの数」を数える2段構えは、最短経路の本数などと同じ構図。Manacher法(同レベル既出)なら半径配列から一撃で数えられる。', ins: ['ababa\n', 'aabaa\n', 'abab\n', 'aaa\n', 'abcd\n', 'xxyy\n'] })

t({ lv: 454, concept: '文字列: 相異なる回転の個数', title: '回して見える違う顔', tags: ['文字列'], io: '文字列が1行で与えられます。', ask: '文字列の回転(0文字ずらしも含む)として得られる相異なる文字列の個数を出力してください。', h1: '全回転を集合に入れる。', h2: '答えは長さの約数になる(最小周期)。', ref: 's=input()\nn=len(s)\nprint(len(set(s[i:]+s[:i] for i in range(n))))', tip: '答えは n/(nを割り切る最小周期) で、文字列の「対称性の位数」にあたる。ネックレスの数え上げ(バーンサイドの補題)で軌道の大きさとして顔を出す量。', ins: ['abab\n', 'aaa\n', 'abc\n', 'abba\n', 'xyxy\n', 'aabaab\n'] })

t({ lv: 455, concept: '文字列: 片方だけの部分文字列の種類数', title: '独自のフレーズを数える', tags: ['文字列'], io: '1行目と2行目に文字列が与えられます。', ask: 'どちらか一方だけに現れる(連続)部分文字列の種類数を出力してください。', h1: '共通の種類数(同レベル既出)の対称差版。', h2: '部分文字列の集合を2つ作って ^ を取る。', ref: 's=input()\nt=input()\ndef subs(x):\n    return {x[i:j] for i in range(len(x)) for j in range(i+1,len(x)+1)}\nprint(len(subs(s)^subs(t)))', tip: '集合の対称差1発で書ける贅沢なO(n³)解。一般化接尾辞オートマトンなら線形近くで数えられる領域で、素朴解が持つ「仕様の直訳」としての価値が際立つ。', ins: ['ab\nb\n', 'aa\naa\n', 'abc\nabd\n', 'a\nb\n', 'ab\nba\n', 'xy\nxyz\n'] })

t({ lv: 456, concept: 'DP: 交互和が最大の連続区間', title: '足して引いてを繰り返す区間', tags: ['DP'], io: '整数列が1行で空白区切りで与えられます。', ask: '連続部分配列 [l..r] の交互和 a[l]−a[l+1]+a[l+2]−… の最大値を出力してください。', h1: 'カダネ法(最大部分和)の符号つき版。', h2: '「+で終わる最大」と「−で終わる最大」の2状態を持ち回る。', ref: 'a=list(map(int,input().split()))\nNEG=-(10**18)\nf=NEG\ng=NEG\nans=NEG\nfor x in a:\n    f2=x+max(0,g)\n    g2=(f-x) if f>NEG else NEG\n    f,g=f2,g2\n    if f>ans:\n        ans=f\nprint(ans)', tip: '状態を2本に増やしたカダネ法。「区間はプラスで始まる」制約が f(+で終わる)だけ新規開始を許し g は必ず延長、という非対称な遷移に表れている。', ins: ['1 2 3\n', '5 1 5\n', '3 3\n', '4\n', '2 1 2 1 2\n', '1 9 1\n'] })

t({ lv: 457, concept: '貪欲: 等しい和に切る最大の個数', title: '同じ重さの塊に切り分ける', tags: ['貪欲'], io: '正整数の列が1行で空白区切りで与えられます。', ask: '列を連続した塊に切り、全ての塊の和が等しくなるようにするときの塊の最大個数を出力してください。', h1: '塊の数kは合計の約数分しか候補がない。', h2: '大きいkから貪欲に「目標に達したら切る」を試す。', ref: 'a=list(map(int,input().split()))\nn=len(a)\ntotal=sum(a)\nfor k in range(n,0,-1):\n    if total%k:\n        continue\n    target=total//k\n    run=0\n    parts=0\n    ok=True\n    for x in a:\n        run+=x\n        if run==target:\n            parts+=1\n            run=0\n        elif run>target:\n            ok=False\n            break\n    if ok and parts==k:\n        print(k)\n        break', tip: '正整数なら累積和が単調なので「目標ちょうどで切る」貪欲が失敗しない。和が減らないように切る問題(同レベル既出)と同じ走査で、条件だけが等号に締まっている。', ins: ['2 2 2\n', '1 2 3\n', '5\n', '1 1 1 1\n', '3 1 2 3 3\n', '2 3\n'] })

t({ lv: 458, concept: 'ソート: 並べ替えて等比数列にできるか', title: '掛け算の階段に並び直せるか', tags: ['ソート'], io: '正整数の列(2個以上)が1行で空白区切りで与えられます。', ask: '並べ替えて等比数列(隣の比が一定)にできるなら yes、できなければ no を出力してください。', h1: '等差版(既出)の掛け算版。', h2: 'ソートして隣接3項で b²=ac を確かめる(割り算不要)。', ref: 'a=sorted(map(int,input().split()))\nok=all(a[i+1]*a[i+1]==a[i]*a[i+2] for i in range(len(a)-2))\nprint("yes" if ok else "no")', tip: '正の数ならソート順がそのまま等比の順になる。比の一致を積の等式に直すのは誤差回避の定石で、幾何平均の検算 b=√(ac) を整数の世界に持ち込んでいる。', ins: ['2 8 4\n', '1 2 3\n', '9 3 1\n', '5 5 5\n', '1 2 4 8\n', '3 7\n'] })

t({ lv: 459, concept: '文字列: 両側が回文になる切れ目の数', title: '回文と回文に真っ二つ', tags: ['文字列'], io: '文字列(長さ2以上)が1行で与えられます。', ask: '文字列を空でない前半と後半に切ったとき、両方が回文になる切れ目の個数を出力してください。', h1: '切れ目はn−1箇所しかない。', h2: 'スライス2つをそれぞれ判定。', ref: 's=input()\nn=len(s)\ncnt=0\nfor k in range(1,n):\n    if s[:k]==s[:k][::-1] and s[k:]==s[k:][::-1]:\n        cnt+=1\nprint(cnt)', tip: '回文分割の中でも「ちょうど2つ」に固定した特殊形で、O(n²)の素朴解が許される。全ての接頭辞・接尾辞の回文性を前計算すれば判定が表引きになる、という高速化も自然。', ins: ['abba\n', 'aab\n', 'aaa\n', 'ab\n', 'racecarx\n', 'xxyx\n'] })

t({ lv: 460, concept: '区間DP: 括弧の付け方で式の値を最小に', title: '一番小さくなる計算順', tags: ['区間DP'], io: '1桁の数字と + * だけからなる式(空白なし)が1行で与えられます。', ask: '括弧を自由に付けたときの式の値の最小を出力してください。', h1: '最大化(同レベル既出)の鏡像。', h2: '区間[i..j]の最小値をDPで。最後に使う演算子の位置で分割。', ref: 's=input()\nnums=[int(c) for c in s[::2]]\nops=[c for c in s[1::2]]\nn=len(nums)\nINF=10**18\ndp=[[INF]*n for _ in range(n)]\nfor i in range(n):\n    dp[i][i]=nums[i]\nfor length in range(2,n+1):\n    for i in range(n-length+1):\n        j=i+length-1\n        for k in range(i,j):\n            v=dp[i][k]+dp[k+1][j] if ops[k]=="+" else dp[i][k]*dp[k+1][j]\n            if v<dp[i][j]:\n                dp[i][j]=v\nprint(dp[0][n-1])', tip: '非負の数だけなら最小どうしの合成が最小、と単純に言えるが、負数が混ざると最大×最小の組合せも要る(最大版と同時に持つ)。前提が遷移の簡潔さを買っている。', ins: ['2+3*4\n', '1*2+3\n', '5\n', '2*3\n', '1+2+3\n', '9*0+5\n'] })

t({ lv: 461, concept: '数え上げ: 硬貨2枚で作れる金額の種類', title: '2枚だけの組合せ表', tags: ['数え上げ'], io: '硬貨の額面が空白区切りで1行で与えられます(同じ額面は2枚以上あるとみなします)。', ask: '同じ額面2枚も許して「ちょうど2枚」で作れる金額が何種類あるかを出力してください。', h1: '2重ループ(i≤j)の和を集合へ。', h2: 'len(set)。', ref: 'c=list(map(int,input().split()))\nn=len(c)\ns={c[i]+c[j] for i in range(n) for j in range(i,n)}\nprint(len(s))', tip: '和集合 A+A の大きさは、加法的組合せ論で「和集合が小さい⇔等差構造がある」と特徴づけられる深い量。額面設計(どの2枚でいくら払えるか)の実務にも直結する。', ins: ['1 5 10\n', '1 1\n', '5\n', '1 2 3\n', '10 20\n', '1 4 5\n'] })

t({ lv: 462, concept: 'DP: 日本の硬貨でおつり込み最小枚数', title: 'おつりも数える最小の枚数', tags: ['DP', '貪欲'], io: '価格 P (1以上) が1行で与えられます。硬貨は 1, 5, 10, 50, 100, 500 円で、支払い側もおつり側も好きな枚数使えます。', ask: '「支払いに使う枚数+おつりの枚数」の合計の最小を出力してください。', h1: '支払額 m は P 以上 P+499 以下だけ試せば足りる。', h2: '日本の硬貨は貪欲で最小枚数になる(額面系の性質)。', ref: 'P=int(input())\ncoins=[500,100,50,10,5,1]\ndef cnt(m):\n    c=0\n    for x in coins:\n        c+=m//x\n        m%=x\n    return c\nprint(min(cnt(m)+cnt(m-P) for m in range(P,P+500)))', tip: '999円に1000円出す(2枚+おつり1枚)のような「多めに払って枚数を減らす」判断の最適化。おつりが500円を超える支払いは無駄と証明でき、探索範囲の上限が正当化される。', ins: ['999\n', '4\n', '99\n', '500\n', '273\n', '86\n'] })

t({ lv: 463, concept: '数え上げ: 左右対称な和の分け方', title: '鏡うつしの足し算', tags: ['数え上げ'], io: '正整数 n が1行で与えられます。', ask: 'n を正整数の和として順序を区別して書く(合成)とき、左右を反転しても同じになるものの数を出力してください(n 自身1個も1通り)。', h1: '前半を決めれば後半は鏡で決まる。', h2: '答えは 2^⌊n/2⌋ になる。総当たりでも確かめられる。', ref: 'n=int(input())\nprint(2**(n//2))', tip: '回文合成の数が2のべき乗になるのは「半分の合成+中央の余り」の全単射から。合成が2^(n−1)通り(既出)なのと合わせ、対称条件が指数をほぼ半分にする様子が見える。', ins: ['1\n', '2\n', '3\n', '4\n', '7\n', '10\n'] })

t({ lv: 464, concept: 'スタック: 釣り合いに必要な最小追加数', title: '足りない括弧を数える', tags: ['スタック'], io: '括弧列(正しいとは限らない)が1行で与えられます。', ask: '好きな位置に括弧を追加して正しい括弧列にするための、追加の最小数を出力してください。', h1: '相殺できるペアを消した残りが答え。', h2: '対応の取れない開きと閉じの合計。', ref: 's=input()\no=0\nc=0\nfor ch in s:\n    if ch=="(":\n        o+=1\n    else:\n        if o>0:\n            o-=1\n        else:\n            c+=1\nprint(o+c)', tip: '削除で直す(既出)と追加で直す本問は同じ「未対応の数」を数えている——直し方が違っても壊れ具合の測り方は同じ、という距離の考え方の入り口。', ins: ['())\n', '(((\n', '()\n', ')(\n', '((())\n', ')))(((\n'] })

t({ lv: 465, concept: '数え上げ: 列を連続グループに分ける方法の数', title: '列の切れ目の入れ方', tags: ['数え上げ'], io: '正整数 n が1行で与えられます。', ask: '1列に並んだ n 人を、隣り合った人だけからなる1つ以上のグループに分ける方法の総数を出力してください。', h1: '人と人の間の隙間ごとに「切る・切らない」。', h2: '隙間は n−1 箇所なので 2^(n−1)。', ref: 'n=int(input())\nprint(2**(n-1))', tip: '自由な分割がベル数(同レベル既出)という複雑な数になるのに対し、「連続」の制約が付くだけで2のべき乗に単純化する。整数の合成(composition)と同じ数え方。', ins: ['3\n', '1\n', '4\n', '2\n', '5\n', '10\n'] })

t({ lv: 466, concept: '数え上げ: 山型の並べ方の数', title: '登って下る隊列は何通り', tags: ['数え上げ'], io: '正整数 n が1行で与えられます。', ask: '1〜n の並べ替えのうち、単峰(あるところまで厳密増加し、その後厳密減少。増加だけ・減少だけも含む)のものの数を出力してください。', h1: '最大値nの位置で左右が決まる。', h2: 'n以外の各要素は「左の上り側か右の下り側か」の2択で 2^(n−1)。', ref: 'n=int(input())\nprint(1<<(n-1))', tip: '最大値を頂上に固定すると、残り各要素の左右の割り振りだけで並びが一意に決まる——2^(n−1)の全単射証明が一行で書ける、数え上げの小さな宝石。', ins: ['1\n', '2\n', '3\n', '4\n', '5\n', '10\n'] })

t({ lv: 467, concept: 'バックトラック: 美しい並べ方の数', title: '割り切りの良い席順', tags: ['バックトラック'], io: '正整数 n が1行で与えられます。', ask: '1〜n の並べ替えのうち、全ての位置 i (1始まり)で「値が i で割り切れる、または i が値で割り切れる」ものの数を出力してください。', h1: '位置ごとに置ける値を試す再帰。', h2: '深い位置から埋めると枝刈りが効く。', ref: 'n=int(input())\nused=[False]*(n+1)\ndef bt(i):\n    if i>n:\n        return 1\n    c=0\n    for v in range(1,n+1):\n        if not used[v] and (v%i==0 or i%v==0):\n            used[v]=True\n            c+=bt(i+1)\n            used[v]=False\n    return c\nprint(bt(1))', tip: 'LeetCodeの「美しい配列」として知られる整除制約つき順列。位置1は全値OK、素数の大きい位置は選択肢が激減する——制約の強い場所から埋める枝刈りの教材。', ins: ['1\n', '2\n', '3\n', '4\n', '5\n', '6\n'] })

t({ lv: 468, concept: '数え上げ: 3集合の和集合の大きさ', title: '三つの輪の包除', tags: ['数え上げ'], io: '|A| |B| |C| |A∩B| |A∩C| |B∩C| |A∩B∩C| の7つの数が空白区切りで1行で与えられます。', ask: '|A∪B∪C| を包除原理で計算して出力してください。', h1: '2集合の包除の拡張。', h2: '単独の和 − ペアの積集合の和 + 三重の積集合。', ref: 'a,b,c,ab,ac,bc,abc=map(int,input().split())\nprint(a+b+c-ab-ac-bc+abc)', tip: '符号が +−+ と交互になるのが包除原理の骨格で、n集合なら (−1)^(サイズ+1) に一般化される。全射の数(同レベル既出)の公式もこの原理から導かれる。', ins: ['10 10 10 5 5 5 2\n', '5 3 2 1 1 0 0\n', '1 1 1 1 1 1 1\n', '4 4 0 2 0 0 0\n', '7 0 0 0 0 0 0\n', '6 5 4 2 1 3 1\n'] })

t({ lv: 469, concept: '整数: 隣の桁と差1の数の個数', title: '階段のような数', tags: ['整数'], io: '正整数 N が1行で与えられます。', ask: '1 以上 N 以下で、隣り合うどの桁も差がちょうど1である数(1桁の数も含む)の個数を出力してください。', h1: '隣接桁が異なる数(同レベル既出)の強い版。', h2: '文字列にして隣接差を確かめる。', ref: 'n=int(input())\ncnt=0\nfor x in range(1,n+1):\n    s=str(x)\n    if all(abs(int(s[i])-int(s[i+1]))==1 for i in range(len(s)-1)):\n        cnt+=1\nprint(cnt)', tip: 'ステッピング数と呼ばれ、桁DPまたは「各桁からBFSで次の桁を±1」で巨大なNにも数えられる。総当たりの答えを頼りに桁DPを組む、良い練習台。', ins: ['25\n', '9\n', '100\n', '11\n', '1\n', '50\n'] })

t({ lv: 470, concept: 'バックトラック: 最大クリークの大きさ', title: '全員が顔見知りの最大集団', tags: ['バックトラック'], io: '1行目に頂点数 n と辺数 m、続く m 行に無向辺 u v が与えられます。', ask: 'どの2頂点も隣接している頂点集合(クリーク)の最大サイズを出力してください(1頂点もクリーク)。', h1: '大きいサイズから部分集合を試す。', h2: 'combinationsで全候補、全ペア隣接を確認。', ref: 'from itertools import combinations\nn,m=map(int,input().split())\nE=set()\nfor _ in range(m):\n    u,v=map(int,input().split())\n    E.add((min(u,v),max(u,v)))\ndef solve():\n    for size in range(n,0,-1):\n        for sub in combinations(range(1,n+1),size):\n            if all((sub[i],sub[j]) in E for i in range(size) for j in range(i+1,size)):\n                return size\nprint(solve())', tip: '最大クリークは最大独立集合(同レベル既出)の補グラフ版で、どちらもNP困難。上から試す全探索は「見つかった瞬間が最適」という打ち切りの正当性を持つ。', ins: ['4 6\n1 2\n1 3\n1 4\n2 3\n2 4\n3 4\n', '4 5\n1 2\n1 3\n1 4\n2 3\n2 4\n', '3 0\n', '5 4\n1 2\n2 3\n3 4\n4 5\n', '2 1\n1 2\n', '6 7\n1 2\n1 3\n2 3\n3 4\n4 5\n4 6\n5 6\n'] })

t({ lv: 471, concept: 'グラフ: 距離の合計が最小の頂点', title: '町のいちばん便利な場所', tags: ['グラフ', 'ダイクストラ'], io: '1行目に頂点数 n と辺数 m、続く m 行に無向辺 u v w が与えられます(連結)。', ask: '他の全頂点への最短距離の合計が最小となる頂点の番号(同点なら最小)を出力してください。', h1: '全頂点対の距離(同レベル既出)を頂点ごとに集計。', h2: 'ワーシャルフロイドで距離表を作り行の和を比べる。', ref: 'n,m=map(int,input().split())\nINF=10**18\nd=[[INF]*(n+1) for _ in range(n+1)]\nfor v in range(1,n+1):\n    d[v][v]=0\nfor _ in range(m):\n    u,v,w=map(int,input().split())\n    if w<d[u][v]:\n        d[u][v]=w\n        d[v][u]=w\nfor k in range(1,n+1):\n    for i in range(1,n+1):\n        for j in range(1,n+1):\n            if d[i][k]+d[k][j]<d[i][j]:\n                d[i][j]=d[i][k]+d[k][j]\nbest=1\nbs=sum(d[1][1:n+1])\nfor v in range(2,n+1):\n    s=sum(d[v][1:n+1])\n    if s<bs:\n        bs=s\n        best=v\nprint(best)', tip: '距離和最小の頂点はグラフのメディアンと呼ばれ、配送センターの立地問題の答えにあたる。離心数最小の中心(既出)とは別物で、両者がずれるグラフも珍しくない。', ins: ['3 2\n1 2 1\n2 3 1\n', '2 1\n1 2 5\n', '4 3\n1 2 1\n2 3 1\n3 4 1\n', '3 3\n1 2 1\n2 3 1\n1 3 5\n', '4 4\n1 2 2\n2 3 2\n3 4 2\n4 1 2\n', '5 4\n1 2 1\n1 3 1\n1 4 1\n1 5 1\n'] })

t({ lv: 472, concept: 'グラフ: 辺数k以下の最短距離', title: '乗り継ぎ回数に上限あり', tags: ['グラフ', 'DP'], io: '1行目に頂点数 n、辺数 m、上限 k、続く m 行に有向辺 u v w が与えられます。', ask: '頂点1から頂点nへ、辺を k 本以下しか使わずに行く最短距離を出力してください(不可能なら -1)。', h1: 'ベルマンフォード(同レベル既出)の反復回数を制限した形。', h2: 'dp[i][v] = i本以下でvに着く最短。1本ずつ緩和する。', ref: 'first=input().split()\nn,m,k=int(first[0]),int(first[1]),int(first[2])\nes=[tuple(map(int,input().split())) for _ in range(m)]\nINF=10**18\ndp=[INF]*(n+1)\ndp[1]=0\nfor _ in range(k):\n    nd=dp[:]\n    for u,v,w in es:\n        if dp[u]+w<nd[v]:\n            nd[v]=dp[u]+w\n    dp=nd\nprint(dp[n] if dp[n]<INF else -1)', tip: '「経由地k回まで」の航空券検索そのもの。前ラウンドの配列をコピーしてから緩和するのが肝で、同一ラウンド内で2辺進んでしまう混線を防いでいる。', ins: ['3 3 1\n1 2 1\n2 3 1\n1 3 5\n', '3 3 2\n1 2 1\n2 3 1\n1 3 5\n', '4 4 2\n1 2 1\n2 3 1\n3 4 1\n1 4 10\n', '4 4 3\n1 2 1\n2 3 1\n3 4 1\n1 4 10\n', '2 1 1\n1 2 7\n', '3 1 5\n1 2 3\n'] })

t({ lv: 473, concept: 'DAG: 辞書順最大のトポロジカル順序', title: '後回しにできるものは後で', tags: ['DAG'], io: '1行目に頂点数 n と辺数 m、続く m 行に有向辺 u v (uがvより先) が与えられます(閉路なし)。', ask: '辞書順で最大のトポロジカル順序を空白区切りで出力してください。', h1: '最小版(同レベル既出)の鏡像。', h2: '入次数0の候補から常に最大の番号を選ぶ。', ref: 'n,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nind=[0]*(n+1)\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    ind[v]+=1\navail=[v for v in range(1,n+1) if ind[v]==0]\nout=[]\nwhile avail:\n    v=max(avail)\n    avail.remove(v)\n    out.append(v)\n    for w in g[v]:\n        ind[w]-=1\n        if ind[w]==0:\n            avail.append(w)\nprint(" ".join(map(str,out)))', tip: '最小はmin-ヒープ、最大はmax-ヒープ、と貪欲の選択関数だけ差し替える対称形。ただし「辞書順最大 ≠ 逆グラフの辞書順最小の逆読み」という罠があり、素直に作り直すのが安全。', ins: ['3 2\n1 2\n1 3\n', '3 0\n', '4 3\n1 2\n3 2\n2 4\n', '2 1\n2 1\n', '4 2\n4 3\n2 1\n', '5 4\n1 3\n2 3\n3 4\n3 5\n'] })

t({ lv: 474, concept: '数え上げ: マッチングの総数', title: 'ペアの選び方ぜんぶ', tags: ['数え上げ', 'バックトラック'], io: '1行目に頂点数 n と辺数 m、続く m 行に無向辺 u v が与えられます。', ask: '辺の部分集合で「どの頂点も高々1本にしか使われない」もの(マッチング。空集合も含む)の総数を出力してください。', h1: '木の場合(既出)と違い一般グラフは探索で。', h2: '番号最小の頂点について「使わない」か「どの隣人と組むか」で分岐。', ref: 'n,m=map(int,input().split())\nadj=[set() for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    adj[u].add(v)\n    adj[v].add(u)\ndef f(rest):\n    if not rest:\n        return 1\n    v=min(rest)\n    total=f(rest-{v})\n    for u in adj[v]:\n        if u in rest and u!=v:\n            total+=f(rest-{v,u})\n    return total\nprint(f(frozenset(range(1,n+1))))', tip: 'マッチングの総数の母関数はマッチング多項式と呼ばれ、統計物理の単量体・二量体模型と同じもの。パスグラフで数えるとフィボナッチ数が現れる。', ins: ['2 1\n1 2\n', '3 3\n1 2\n2 3\n1 3\n', '3 0\n', '4 4\n1 2\n2 3\n3 4\n4 1\n', '4 6\n1 2\n1 3\n1 4\n2 3\n2 4\n3 4\n', '5 4\n1 2\n2 3\n3 4\n4 5\n'] })

t({ lv: 475, concept: 'グラフ: 辺の彩色数', title: '同じ頂点で色がぶつからないように', tags: ['グラフ', 'バックトラック'], io: '1行目に頂点数 n と辺数 m (m≥1)、続く m 行に無向辺 u v が与えられます。', ask: '同じ頂点に接続する辺どうしが必ず違う色になるように全ての辺を塗るときの、色数の最小を出力してください。', h1: '頂点彩色(同レベル既出)の辺版。', h2: 'c色でのバックトラックをc=最大次数から順に試す(ヴィジングの定理でΔかΔ+1)。', ref: 'n,m=map(int,input().split())\nes=[]\ndeg=[0]*(n+1)\nfor _ in range(m):\n    u,v=map(int,input().split())\n    es.append((u,v))\n    deg[u]+=1\n    deg[v]+=1\nadj=[[] for _ in range(m)]\nfor i in range(m):\n    for j in range(i+1,m):\n        if set(es[i])&set(es[j]):\n            adj[i].append(j)\n            adj[j].append(i)\ncolor=[0]*m\ndef ok(c):\n    def bt(i):\n        if i==m:\n            return True\n        for col in range(1,c+1):\n            if all(color[j]!=col for j in adj[i] if j<i):\n                color[i]=col\n                if bt(i+1):\n                    return True\n        color[i]=0\n        return False\n    return bt(0)\nc=max(deg)\nwhile not ok(c):\n    c+=1\nprint(c)', tip: 'ヴィジングの定理により答えは最大次数Δか Δ+1 の二択に絞られる(どちらかの判定はNP完全)。辺彩色は「ラインラフの頂点彩色」でもあり、変換して解く道筋も見える。', ins: ['3 3\n1 2\n2 3\n1 3\n', '4 3\n1 2\n2 3\n3 4\n', '2 1\n1 2\n', '5 4\n1 2\n1 3\n1 4\n1 5\n', '4 4\n1 2\n2 3\n3 4\n4 1\n', '4 5\n1 2\n2 3\n3 4\n4 1\n1 3\n'] })

export const CATALOG = TASKS
