// 生成タスク 第33波：lv391〜420。
// 競プロ上級帯の踏み段。遅延セグ木・2次元BIT・平方分割・計算幾何(面積/外積/凸包/交差/内外)・
// 関節点/橋/2辺連結成分・最小費用流・線形漸化式の行列累乗・桁DP・区間DPなど。
// 再帰は prereq の土台外なので使用可。重複なし・決定的・採点一意。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 391, concept: 'DP: 最長増加部分列の個数', title: '最長増加部分列の個数', tags: ['dp'], io: '整数列が1行で与えられます。', ask: '最長の狭義増加部分列の長さを達成する部分列が何通りあるかを出力してください。', h1: '各位置で「最長長さ」と「その通り数」を持つ。', h2: '長さが伸びたら通り数を引き継ぎ、同じなら足す。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nif n==0:\n    print(0)\nelse:\n    length=[1]*n\n    count=[1]*n\n    for i in range(n):\n        for j in range(i):\n            if a[j]<a[i]:\n                if length[j]+1>length[i]:\n                    length[i]=length[j]+1\n                    count[i]=count[j]\n                elif length[j]+1==length[i]:\n                    count[i]+=count[j]\n    best=max(length)\n    print(sum(count[i] for i in range(n) if length[i]==best))', tip: '長さと個数を同時に管理するのが「最適解の数え上げ」の定石。', ins: ['1 3 5 4 7\n', '2 2 2\n', '1 2 3\n', '5\n', '1 3 2 3\n', '3 1 2 4 3\n'] })

t({ lv: 392, concept: 'DP: 最長双調部分列', title: '最長の山型 (双調) 部分列', tags: ['dp'], io: '整数列が1行で与えられます。', ask: '増加してから減少する部分列 (連続でなくてよい) の最大の長さを出力してください。', h1: '各位置までの最長増加長と、その位置からの最長減少長。', h2: '頂点 i で inc[i]+dec[i]-1 の最大。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nif n==0:\n    print(0)\nelse:\n    inc=[1]*n\n    for i in range(n):\n        for j in range(i):\n            if a[j]<a[i] and inc[j]+1>inc[i]:\n                inc[i]=inc[j]+1\n    dec=[1]*n\n    for i in range(n-1,-1,-1):\n        for j in range(i+1,n):\n            if a[j]<a[i] and dec[j]+1>dec[i]:\n                dec[i]=dec[j]+1\n    best=0\n    for i in range(n):\n        if inc[i]+dec[i]-1>best:\n            best=inc[i]+dec[i]-1\n    print(best)', tip: '左からのLISと右からのLISを合成すると山型の最長が出る。', ins: ['1 11 2 10 4 5 2 1\n', '1 2 3 4\n', '4 3 2 1\n', '5\n', '1 2 1\n', '10 20 30 25 15 5\n'] })

t({ lv: 393, concept: 'DP: 部分集合和の作り方の数', title: '和がTになる部分集合の数', tags: ['dp'], io: '1行目に n T、2行目に n 個の非負整数が与えられます。', ask: '部分集合の和がちょうど T になる選び方の数を出力してください (空集合も1通りとして数えます)。', h1: 'dp[v]=和vを作る部分集合の数。', h2: '各要素で大きい容量から dp[v]+=dp[v-x]。', ref: 'n,T=map(int,input().split())\na=list(map(int,input().split()))\ndp=[0]*(T+1)\ndp[0]=1\nfor x in a:\n    for v in range(T,x-1,-1):\n        dp[v]+=dp[v-x]\nprint(dp[T])', tip: '「作れるか (bool)」を「何通り (整数)」に変えた数え上げ版。', ins: ['4 4\n1 1 2 2\n', '3 0\n1 2 3\n', '3 6\n1 2 3\n', '2 5\n5 5\n', '1 1\n1\n', '4 3\n0 1 1 1\n'] })

t({ lv: 394, concept: 'DP: 卵落とし最小試行', title: '卵割り問題の最小試行回数', tags: ['dp'], io: 'k n が空白区切りで与えられます (卵の数 k、階数 n)。', ask: '最悪の場合でも卵が割れ始める境界の階を特定するのに必要な、最小の試行回数を出力してください。', h1: 'm 回・e 個で判定できる最大階数 f(e,m)=f(e-1,m-1)+f(e,m-1)+1。', h2: 'f(k,m)>=n となる最小の m。', ref: 'k,n=map(int,input().split())\nmoves=0\ndp=[0]*(k+1)\nwhile dp[k]<n:\n    moves+=1\n    new=[0]*(k+1)\n    for e in range(1,k+1):\n        new[e]=dp[e-1]+dp[e]+1\n    dp=new\nprint(moves)', tip: '「m回で測れる最大階数」を増やす向きに考えると O(k log n)。', ins: ['1 10\n', '2 6\n', '2 36\n', '3 14\n', '2 100\n', '1 1\n'] })

t({ lv: 395, concept: '区間DP: 最適二分探索木', title: '最適二分探索木の最小コスト', tags: ['区間DP', 'dp'], io: '1行目に n、2行目に n 個の頻度 (ソート済みキーのアクセス頻度) が与えられます。', ask: '各キーの (深さ × 頻度) の総和を最小化したときの値を出力してください (根の深さを1とします)。', h1: 'dp[i][j]=区間 [i,j] を木にする最小コスト。', h2: '根 r を全探索し、左右の最小に区間の総頻度を足す。', ref: 'n=int(input())\nf=list(map(int,input().split()))\nif n==0:\n    print(0)\nelse:\n    pre=[0]*(n+1)\n    for i in range(n):\n        pre[i+1]=pre[i]+f[i]\n    INF=float("inf")\n    dp=[[0]*n for _ in range(n)]\n    for i in range(n):\n        dp[i][i]=f[i]\n    for length in range(2,n+1):\n        for i in range(n-length+1):\n            j=i+length-1\n            s=pre[j+1]-pre[i]\n            best=INF\n            for r in range(i,j+1):\n                left=dp[i][r-1] if r>i else 0\n                right=dp[r+1][j] if r<j else 0\n                if left+right<best:\n                    best=left+right\n            dp[i][j]=best+s\n    print(dp[0][n-1])', tip: '根を全探索する区間DP。深さが1増えるので区間の総頻度が必ず加算される。', ins: ['3\n34 8 50\n', '1\n5\n', '2\n10 20\n', '3\n10 10 10\n', '4\n1 1 1 1\n', '2\n1 100\n'] })

t({ lv: 396, concept: '桁DP: 隣接が異なる数の個数', title: '隣り合う桁が異なる数の個数', tags: ['桁DP', 'dp'], io: '整数 N (>=1) が1行で与えられます。', ask: '1 以上 N 以下の整数のうち、隣り合う桁がすべて異なるものの個数を出力してください。', h1: '状態に「上限張り付き」「開始済み」「直前の桁」を持つ。', h2: '直前と同じ桁は選べない。', ref: 'N=int(input())\ns=str(N)\nL=len(s)\nfrom collections import defaultdict\ncur={(True,False,-1):1}\nfor pos in range(L):\n    nxt=defaultdict(int)\n    lim=int(s[pos])\n    for (tight,started,last),cnt in cur.items():\n        top=lim if tight else 9\n        for d in range(0,top+1):\n            if started and d==last:\n                continue\n            nstarted=started or d>0\n            nlast=d if (started or d>0) else -1\n            ntight=tight and (d==lim)\n            nxt[(ntight,nstarted,nlast)]+=cnt\n    cur=nxt\nprint(sum(cnt for (tight,started,last),cnt in cur.items() if started))', tip: '「直前の桁」を状態に持つと隣接条件つきの数え上げが桁DPで書ける。', ins: ['12\n', '11\n', '5\n', '100\n', '22\n', '1\n'] })

t({ lv: 397, concept: '貪欲: ハフマン符号の総コスト', title: 'ハフマン符号化の総コスト', tags: ['貪欲', 'heapq'], io: '各記号の出現頻度の列が1行で与えられます。', ask: '最適な接頭符号 (ハフマン符号) を作ったときの「頻度 × 符号長」の総和を出力してください (記号が1個なら0)。', h1: '最小ヒープから2つ取り出して合体。', h2: '合体コスト (和) を総コストに足し、ヒープに戻す。', ref: 'import heapq\nfreq=list(map(int,input().split()))\nif len(freq)==1:\n    print(0)\nelse:\n    heapq.heapify(freq)\n    total=0\n    while len(freq)>1:\n        a=heapq.heappop(freq)\n        b=heapq.heappop(freq)\n        total+=a+b\n        heapq.heappush(freq,a+b)\n    print(total)', tip: '毎回最小2つを併合する貪欲が最適符号長を与える (ハフマンの定理)。', ins: ['5 9 12 13 16 45\n', '1 1\n', '5\n', '1 2 3\n', '10 10 10 10\n', '2 3 4\n'] })

t({ lv: 398, concept: '貪欲: 締切つき仕事の最大利益', title: '締切を守って得る最大利益', tags: ['貪欲', 'ソート'], io: '1行目に仕事数 n、続く n 行に締切 d と利益 p が与えられます。各仕事は1単位時間かかり、時刻スロット 1,2,… に割り当てます。', ask: '締切を守れるように仕事を選んだときの利益の最大値を出力してください。', h1: '利益の高い順に処理する。', h2: '締切以下で最も遅い空きスロットに入れる。', ref: 'n=int(input())\njobs=[tuple(map(int,input().split())) for _ in range(n)]\njobs.sort(key=lambda x:-x[1])\nmaxd=max((d for d,p in jobs),default=0)\nslot=[False]*(maxd+1)\ntotal=0\nfor d,p in jobs:\n    tt=min(d,maxd)\n    while tt>=1 and slot[tt]:\n        tt-=1\n    if tt>=1:\n        slot[tt]=True\n        total+=p\nprint(total)', tip: '高利益から遅いスロットへ詰めると、後続の自由度を最大化できる。', ins: ['4\n4 20\n1 10\n1 40\n1 30\n', '2\n1 100\n2 50\n', '1\n1 5\n', '3\n1 1\n1 1\n1 1\n', '3\n3 10\n3 20\n3 30\n', '2\n1 10\n1 20\n'] })

t({ lv: 399, concept: 'ビット: XOR基底の最大値', title: '線形基底で作る最大XOR', tags: ['bit'], io: '整数列が1行で与えられます。', ask: '部分集合のXORで作れる最大値を出力してください (空集合は0)。', h1: '掃き出し法でXORの線形基底を作る。', h2: '基底を上位ビットから貪欲にXORして最大化。', ref: 'a=list(map(int,input().split()))\nbasis=[]\nfor x in a:\n    cur=x\n    for b in basis:\n        if cur^b<cur:\n            cur^=b\n    if cur>0:\n        basis.append(cur)\n        basis.sort(reverse=True)\nres=0\nfor b in basis:\n    if res^b>res:\n        res^=b\nprint(res)', tip: 'XOR基底 (線形基底) は全列挙せず最大XORを O(n log V) で出す。', ins: ['1 2 3\n', '8 4 2\n', '5\n', '0 0\n', '1 2 4 8\n', '7 3 5\n'] })

t({ lv: 400, concept: 'Trie: 最大XORペア', title: '2要素のXORの最大値', tags: ['Trie', 'bit'], io: '非負整数列が1行で与えられます。', ask: '異なる2要素の排他的論理和の最大値を出力してください (要素が1個なら0)。', h1: '各数を2進でトライ木に挿入する。', h2: '各数について、できるだけ反対のビットへ進むと最大XAORが得られる。', ref: 'a=list(map(int,input().split()))\nBITS=30\ntrie=[[-1,-1]]\ndef insert(x):\n    node=0\n    for i in range(BITS,-1,-1):\n        b=(x>>i)&1\n        if trie[node][b]==-1:\n            trie.append([-1,-1])\n            trie[node][b]=len(trie)-1\n        node=trie[node][b]\ndef query(x):\n    node=0\n    res=0\n    for i in range(BITS,-1,-1):\n        b=(x>>i)&1\n        want=1-b\n        if trie[node][want]!=-1:\n            res|=(1<<i)\n            node=trie[node][want]\n        else:\n            node=trie[node][b]\n    return res\nbest=0\ninsert(a[0])\nfor x in a[1:]:\n    q=query(x)\n    if q>best:\n        best=q\n    insert(x)\nprint(best)', tip: '2進トライで「反対ビットへ進む」と最大XORの相手を O(ビット数) で探せる。', ins: ['3 10 5 25 2 8\n', '1 2\n', '0\n', '8 8\n', '1 2 3 4\n', '14 70 53 83 12 20 27\n'] })

t({ lv: 401, concept: 'データ構造: 遅延セグ木(区間加算・区間和)', title: '区間加算と区間和 (遅延評価)', tags: ['データ構造'], io: '1行目に n q、2行目に n 個の値、続く q 行に "add l r x" (区間 [l,r] に x を加算) または "sum l r" (区間和) が与えられます。', ask: 'すべての "sum" の結果の合計を出力してください。', h1: '各ノードに保留中の加算量 (lazy) を持つ。', h2: '降りるときに子へ伝播し、戻るときに集約。', ref: 'n,q=map(int,input().split())\na=list(map(int,input().split()))\nsize=1\nwhile size<n:\n    size*=2\ntree=[0]*(2*size)\nlazy=[0]*(2*size)\nlength=[1]*(2*size)\nfor i in range(size-1,0,-1):\n    length[i]=length[2*i]+length[2*i+1]\nfor i in range(n):\n    tree[size+i]=a[i]\nfor i in range(size-1,0,-1):\n    tree[i]=tree[2*i]+tree[2*i+1]\ndef push(node):\n    if lazy[node]:\n        for ch in (2*node,2*node+1):\n            lazy[ch]+=lazy[node]\n            tree[ch]+=lazy[node]*length[ch]\n        lazy[node]=0\ndef update(node,nl,nr,l,r,x):\n    if r<nl or nr<l:\n        return\n    if l<=nl and nr<=r:\n        tree[node]+=x*length[node]\n        lazy[node]+=x\n        return\n    push(node)\n    mid=(nl+nr)//2\n    update(2*node,nl,mid,l,r,x)\n    update(2*node+1,mid+1,nr,l,r,x)\n    tree[node]=tree[2*node]+tree[2*node+1]\ndef query(node,nl,nr,l,r):\n    if r<nl or nr<l:\n        return 0\n    if l<=nl and nr<=r:\n        return tree[node]\n    push(node)\n    mid=(nl+nr)//2\n    return query(2*node,nl,mid,l,r)+query(2*node+1,mid+1,nr,l,r)\ntotal=0\nfor _ in range(q):\n    op=input().split()\n    if op[0]=="add":\n        update(1,0,size-1,int(op[1]),int(op[2]),int(op[3]))\n    else:\n        total+=query(1,0,size-1,int(op[1]),int(op[2]))\nprint(total)', tip: '遅延評価で「区間まるごと更新」を O(log n) に保つのがセグ木の真価。', ins: ['5 3\n1 2 3 4 5\nsum 0 4\nadd 1 3 10\nsum 0 4\n', '3 2\n0 0 0\nadd 0 2 5\nsum 0 2\n', '1 1\n7\nsum 0 0\n', '4 3\n1 1 1 1\nadd 0 1 2\nadd 2 3 3\nsum 0 3\n', '5 2\n1 2 3 4 5\nadd 0 4 1\nsum 2 2\n', '4 2\n0 0 0 0\nadd 1 2 10\nsum 0 3\n'] })

t({ lv: 402, concept: 'データ構造: 2次元BITの矩形和', title: '点更新つき2次元矩形和', tags: ['データ構造'], io: '1行目に H W Q、続く Q 行に "add r c x" (点 (r,c) に x を加算) または "sum r1 c1 r2 c2" (矩形和) が与えられます (0始まり)。', ask: 'すべての "sum" の結果の合計を出力してください。', h1: '1次元BITを2次元に重ねる。', h2: '矩形和は4つの累積和の組合せ。', ref: 'first=input().split()\nH=int(first[0])\nW=int(first[1])\nQ=int(first[2])\nbit=[[0]*(W+1) for _ in range(H+1)]\ndef update(r,c,x):\n    i=r+1\n    while i<=H:\n        j=c+1\n        while j<=W:\n            bit[i][j]+=x\n            j+=j&(-j)\n        i+=i&(-i)\ndef pref(r,c):\n    s=0\n    i=r+1\n    while i>0:\n        j=c+1\n        while j>0:\n            s+=bit[i][j]\n            j-=j&(-j)\n        i-=i&(-i)\n    return s\ndef rect(r1,c1,r2,c2):\n    return pref(r2,c2)-pref(r1-1,c2)-pref(r2,c1-1)+pref(r1-1,c1-1)\ntotal=0\nfor _ in range(Q):\n    op=input().split()\n    if op[0]=="add":\n        update(int(op[1]),int(op[2]),int(op[3]))\n    else:\n        total+=rect(int(op[1]),int(op[2]),int(op[3]),int(op[4]))\nprint(total)', tip: 'BITを次元の数だけ入れ子にすると多次元の累積和が更新つきで扱える。', ins: ['2 2 2\nadd 0 0 5\nsum 0 0 1 1\n', '3 3 3\nadd 1 1 10\nadd 2 2 20\nsum 0 0 2 2\n', '1 1 2\nadd 0 0 7\nsum 0 0 0 0\n', '2 2 3\nadd 0 0 1\nadd 1 1 1\nsum 0 0 0 0\n', '3 3 2\nadd 0 0 5\nsum 1 1 2 2\n', '2 3 2\nadd 1 2 4\nsum 0 0 1 2\n'] })

t({ lv: 403, concept: 'データ構造: 平方分割の区間和', title: '点更新つき区間和 (平方分割)', tags: ['データ構造'], io: '1行目に n q、2行目に n 個の値、続く q 行に "upd i x" (位置 i を x に) または "sum l r" (区間和) が与えられます。', ask: 'すべての "sum" の結果の合計を出力してください。', h1: '配列を √n 個ずつのブロックに分け、各ブロック和を持つ。', h2: '端は要素単位、内部はブロック単位で足す。', ref: 'import math\nn,q=map(int,input().split())\na=list(map(int,input().split()))\nB=max(1,int(math.isqrt(n)))\nnb=(n+B-1)//B\nblock=[0]*nb\nfor i in range(n):\n    block[i//B]+=a[i]\ntotal=0\nfor _ in range(q):\n    op=input().split()\n    if op[0]=="upd":\n        i=int(op[1])\n        x=int(op[2])\n        block[i//B]+=x-a[i]\n        a[i]=x\n    else:\n        l=int(op[1])\n        r=int(op[2])\n        s=0\n        i=l\n        while i<=r:\n            if i%B==0 and i+B-1<=r:\n                s+=block[i//B]\n                i+=B\n            else:\n                s+=a[i]\n                i+=1\n        total+=s\nprint(total)', tip: '√n ブロックに分けるだけで更新もクエリも O(√n)。実装が軽い万能技。', ins: ['5 3\n1 2 3 4 5\nsum 0 4\nupd 2 10\nsum 0 4\n', '3 2\n1 1 1\nsum 0 2\nsum 0 0\n', '1 1\n7\nsum 0 0\n', '4 3\n1 2 3 4\nupd 0 0\nsum 0 1\nsum 2 3\n', '6 1\n1 2 3 4 5 6\nsum 1 4\n', '5 2\n5 4 3 2 1\nupd 4 100\nsum 0 4\n'] })

t({ lv: 404, concept: '幾何: 多角形の面積', title: '多角形の面積の2倍', tags: ['幾何'], io: '1行目に頂点数 n、続く n 行に頂点座標 x y (多角形の周に沿った順) が与えられます。', ask: '多角形の面積の2倍を出力してください (整数で一意になります)。', h1: '靴ひも (シューレース) の公式。', h2: 'Σ(x_i·y_{i+1} − x_{i+1}·y_i) の絶対値。', ref: 'n=int(input())\npts=[tuple(map(int,input().split())) for _ in range(n)]\ns=0\nfor i in range(n):\n    x1,y1=pts[i]\n    x2,y2=pts[(i+1)%n]\n    s+=x1*y2-x2*y1\nprint(abs(s))', tip: '面積の2倍を出せば整数のまま扱え、誤差も向きの問題も避けられる。', ins: ['4\n0 0\n4 0\n4 3\n0 3\n', '3\n0 0\n4 0\n0 3\n', '3\n0 0\n1 0\n0 1\n', '4\n0 0\n2 0\n2 2\n0 2\n', '5\n0 0\n2 0\n3 1\n1 3\n0 2\n', '4\n0 0\n0 3\n4 3\n4 0\n'] })

t({ lv: 405, concept: '幾何: 点の進行方向(外積)', title: '3点の曲がり方', tags: ['幾何'], io: '6個の整数 ax ay bx by cx cy が1行で与えられます。', ask: 'a→b→c と進むときの曲がり方を、反時計回り (左折) なら 1、時計回り (右折) なら -1、一直線なら 0 で出力してください。', h1: 'ベクトル ab と ac の外積の符号。', h2: '(bx-ax)(cy-ay) − (by-ay)(cx-ax)。', ref: 'ax,ay,bx,by,cx,cy=map(int,input().split())\ncross=(bx-ax)*(cy-ay)-(by-ay)*(cx-ax)\nprint(1 if cross>0 else (-1 if cross<0 else 0))', tip: '外積の符号は計算幾何の最も基本的な判定 (向き付け)。', ins: ['0 0 1 0 1 1\n', '0 0 1 0 1 -1\n', '0 0 1 1 2 2\n', '0 0 0 1 1 1\n', '0 0 2 0 1 5\n', '0 0 1 0 2 0\n'] })

t({ lv: 406, concept: '幾何: 凸包の頂点数', title: '凸包の頂点数', tags: ['幾何', 'ソート'], io: '1行目に点数 n、続く n 行に点 x y が与えられます。', ask: '凸包 (すべての点を含む最小の凸多角形) の頂点数を出力してください (辺上の点は頂点に数えません)。', h1: 'x,y でソートして下側・上側の鎖を作る。', h2: '外積が非正なら頂点を取り除く (アンドリューの単調鎖)。', ref: 'n=int(input())\npts=sorted(set(tuple(map(int,input().split())) for _ in range(n)))\ndef cross(o,a,b):\n    return (a[0]-o[0])*(b[1]-o[1])-(a[1]-o[1])*(b[0]-o[0])\nif len(pts)<=2:\n    print(len(pts))\nelse:\n    lower=[]\n    for p in pts:\n        while len(lower)>=2 and cross(lower[-2],lower[-1],p)<=0:\n            lower.pop()\n        lower.append(p)\n    upper=[]\n    for p in reversed(pts):\n        while len(upper)>=2 and cross(upper[-2],upper[-1],p)<=0:\n            upper.pop()\n        upper.append(p)\n    hull=lower[:-1]+upper[:-1]\n    print(len(hull))', tip: 'ソート＋外積判定で凸包が O(n log n)。多くの幾何問題の前処理になる。', ins: ['4\n0 0\n4 0\n4 4\n0 4\n', '3\n0 0\n1 0\n2 0\n', '5\n0 0\n4 0\n4 4\n0 4\n2 2\n', '1\n0 0\n', '3\n0 0\n1 1\n2 0\n', '6\n0 0\n2 0\n4 0\n4 4\n2 4\n0 4\n'] })

t({ lv: 407, concept: '幾何: 線分の交差判定', title: '2線分が交わるか', tags: ['幾何'], io: '8個の整数 x1 y1 x2 y2 x3 y3 x4 y4 が1行で与えられます (線分 12 と線分 34)。', ask: '2つの線分が交わる (端点での接触や重なりを含む) なら yes、交わらないなら no を出力してください。', h1: '各端点が相手の線分に対してどちら側かを外積で判定。', h2: '符号が両側に分かれる、または端点が線分上にある場合に交差。', ref: 'v=list(map(int,input().split()))\nx1,y1,x2,y2,x3,y3,x4,y4=v\ndef cross(ox,oy,ax,ay,bx,by):\n    return (ax-ox)*(by-oy)-(ay-oy)*(bx-ox)\ndef sgn(z):\n    return 1 if z>0 else (-1 if z<0 else 0)\ndef on_seg(px,py,qx,qy,rx,ry):\n    return min(px,rx)<=qx<=max(px,rx) and min(py,ry)<=qy<=max(py,ry)\nd1=sgn(cross(x3,y3,x4,y4,x1,y1))\nd2=sgn(cross(x3,y3,x4,y4,x2,y2))\nd3=sgn(cross(x1,y1,x2,y2,x3,y3))\nd4=sgn(cross(x1,y1,x2,y2,x4,y4))\nans=False\nif d1!=d2 and d3!=d4:\n    ans=True\nelif d1==0 and on_seg(x3,y3,x1,y1,x4,y4):\n    ans=True\nelif d2==0 and on_seg(x3,y3,x2,y2,x4,y4):\n    ans=True\nelif d3==0 and on_seg(x1,y1,x3,y3,x2,y2):\n    ans=True\nelif d4==0 and on_seg(x1,y1,x4,y4,x2,y2):\n    ans=True\nprint("yes" if ans else "no")', tip: '外積の符号＋端点の上判定が線分交差の定石 (浮動小数を使わず整数で安全)。', ins: ['0 0 2 2 0 2 2 0\n', '0 0 1 1 2 2 3 3\n', '0 0 2 0 1 0 1 5\n', '0 0 1 0 0 1 1 1\n', '0 0 2 2 1 1 3 3\n', '0 0 1 1 2 0 3 -1\n'] })

t({ lv: 408, concept: '幾何: 点が多角形の内部か', title: '点が多角形の内部にあるか', tags: ['幾何'], io: '1行目に頂点数 n、続く n 行に多角形の頂点 x y (周回順)、最後の行に判定する点 px py が与えられます。', ask: '点が多角形の内部または境界上にあれば yes、外部なら no を出力してください。', h1: 'まず境界 (辺上) かを判定。', h2: '内部判定は点から伸ばした半直線と辺の交差数の偶奇。', ref: 'n=int(input())\npoly=[tuple(map(int,input().split())) for _ in range(n)]\npx,py=map(int,input().split())\ndef on_seg(ax,ay,bx,by,qx,qy):\n    cr=(bx-ax)*(qy-ay)-(by-ay)*(qx-ax)\n    if cr!=0:\n        return False\n    return min(ax,bx)<=qx<=max(ax,bx) and min(ay,by)<=qy<=max(ay,by)\non=False\nfor i in range(n):\n    ax,ay=poly[i]\n    bx,by=poly[(i+1)%n]\n    if on_seg(ax,ay,bx,by,px,py):\n        on=True\n        break\nif on:\n    print("yes")\nelse:\n    inside=False\n    for i in range(n):\n        ax,ay=poly[i]\n        bx,by=poly[(i+1)%n]\n        if (ay>py)!=(by>py):\n            xint=ax+(bx-ax)*(py-ay)/(by-ay)\n            if px<xint:\n                inside=not inside\n    print("yes" if inside else "no")', tip: '半直線と辺の交差数が奇数なら内部 (レイキャスティング法)。', ins: ['4\n0 0\n4 0\n4 4\n0 4\n2 2\n', '4\n0 0\n4 0\n4 4\n0 4\n5 5\n', '4\n0 0\n4 0\n4 4\n0 4\n0 0\n', '3\n0 0\n4 0\n0 4\n1 1\n', '3\n0 0\n4 0\n0 4\n3 3\n', '4\n0 0\n4 0\n4 4\n0 4\n4 2\n'] })

t({ lv: 409, concept: '数論: 重複組合せ', title: '重複を許す組合せの数', tags: ['数論'], io: 'n k が空白区切りで与えられます。', ask: 'n 種類から重複を許して k 個選ぶ組合せの数 (重複組合せ) を出力してください。', h1: '重複組合せは C(n+k-1, k)。', h2: '仕切りと玉の並べ方 (重複組合せ＝ stars and bars)。', ref: 'n,k=map(int,input().split())\ntop=n+k-1\nr=min(k,n-1)\nres=1\nfor i in range(r):\n    res=res*(top-i)//(i+1)\nprint(res)', tip: '「玉と仕切り」に置き換えると重複組合せが普通の組合せに化ける。', ins: ['3 2\n', '5 0\n', '2 3\n', '1 5\n', '4 2\n', '3 3\n'] })

t({ lv: 410, concept: '数論: 直線下の格子点の数', title: '直線の下にある格子点の数', tags: ['数論'], io: 'n a b m が空白区切りで与えられます (n,m>=1、a,b>=0)。', ask: 'i=0,1,…,n-1 について floor((a·i+b)/m) を求め、その総和を出力してください。', h1: '各 i について床関数の値を足す。', h2: 'これは直線 y=(a x+b)/m の下の格子点数に対応する。', ref: 'n,a,b,m=map(int,input().split())\ntotal=0\nfor i in range(n):\n    total+=(a*i+b)//m\nprint(total)', tip: 'floor sum は格子点の数え上げや有理数の和に頻出する基本量。', ins: ['5 2 3 4\n', '1 0 0 1\n', '3 1 0 1\n', '4 3 1 2\n', '2 5 5 5\n', '10 1 0 3\n'] })

t({ lv: 411, concept: '数論: 区間のオイラーφの和', title: '1からNまでのオイラー関数の和', tags: ['数論'], io: '整数 N (>=1) が1行で与えられます。', ask: 'φ(1)+φ(2)+…+φ(N) を出力してください (φ はオイラーのトーシェント関数)。', h1: '篩の要領で各素数の寄与を引く。', h2: 'phi[i] を i で初期化し、素数 p の倍数から p の寄与を引く。', ref: 'n=int(input())\nphi=list(range(n+1))\nfor i in range(2,n+1):\n    if phi[i]==i:\n        for j in range(i,n+1,i):\n            phi[j]-=phi[j]//i\nprint(sum(phi[1:n+1]))', tip: '篩でトーシェント関数を一括計算できる (各素数で 1−1/p を掛ける形)。', ins: ['1\n', '5\n', '10\n', '2\n', '6\n', '100\n'] })

t({ lv: 412, concept: '数論: 線形漸化式の高速計算', title: '線形漸化式のn項目を法で', tags: ['数論'], io: '1行目に項数 k と法 MOD、2行目に係数 c0..c_{k-1} (a[n]=Σ c_i·a[n-1-i])、3行目に初期値 a[0..k-1]、4行目に n が与えられます。', ask: 'a[n] を MOD で割った余りを出力してください。', h1: 'コンパニオン行列を作る。', h2: '行列を繰り返し二乗法で n 乗する。', ref: 'line=input().split()\nk=int(line[0])\nMOD=int(line[1])\nc=list(map(int,input().split()))\ninit=list(map(int,input().split()))\nn=int(input())\nif n<k:\n    print(init[n]%MOD)\nelse:\n    def matmul(A,B):\n        ra=len(A)\n        rb=len(B)\n        cb=len(B[0])\n        R=[[0]*cb for _ in range(ra)]\n        for i in range(ra):\n            for tt in range(rb):\n                if A[i][tt]:\n                    ait=A[i][tt]\n                    Bt=B[tt]\n                    Ri=R[i]\n                    for j in range(cb):\n                        Ri[j]=(Ri[j]+ait*Bt[j])%MOD\n        return R\n    M=[[0]*k for _ in range(k)]\n    for j in range(k):\n        M[0][j]=c[j]%MOD\n    for i in range(1,k):\n        M[i][i-1]=1\n    R=[[1 if i==j else 0 for j in range(k)] for i in range(k)]\n    e=n-(k-1)\n    base=M\n    while e>0:\n        if e&1:\n            R=matmul(R,base)\n        base=matmul(base,base)\n        e//=2\n    state=[init[k-1-i] for i in range(k)]\n    ans=0\n    for j in range(k):\n        ans=(ans+R[0][j]*state[j])%MOD\n    print(ans%MOD)', tip: '任意の線形漸化式は行列累乗で O(k³ log n)。巨大な n でも瞬時。', ins: ['2 1000\n1 1\n0 1\n10\n', '2 1000000007\n1 1\n0 1\n1\n', '3 1000\n1 1 1\n0 0 1\n5\n', '2 100\n2 0\n1 0\n3\n', '1 1000\n3\n5\n4\n', '2 7\n1 1\n0 1\n20\n'] })

t({ lv: 413, concept: '木: 2頂点間の距離', title: '木の2頂点間の重み付き距離', tags: ['グラフ', 'BFS'], io: '1行目に n q、続く n-1 行に重み付き辺 u v w、続く q 行にクエリ a b が与えられます。', ask: '各クエリの a と b の間の経路の重みの合計を求め、その総和を出力してください。', h1: '木では2頂点間の経路は一意。', h2: '始点から幅優先で重み付き距離を求める。', ref: 'from collections import deque\nn,q=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(n-1):\n    u,v,w=map(int,input().split())\n    g[u].append((v,w))\n    g[v].append((u,w))\ntotal=0\nfor _ in range(q):\n    a,b=map(int,input().split())\n    dist=[-1]*(n+1)\n    dist[a]=0\n    dq=deque([a])\n    while dq:\n        x=dq.popleft()\n        for y,w in g[x]:\n            if dist[y]<0:\n                dist[y]=dist[x]+w\n                dq.append(y)\n    total+=dist[b]\nprint(total)', tip: '木は閉路がないので、距離はBFS/DFS一発で一意に決まる。', ins: ['3 1\n1 2 5\n2 3 3\n1 3\n', '4 2\n1 2 1\n2 3 2\n3 4 3\n1 4\n2 4\n', '2 1\n1 2 7\n1 2\n', '1 1\n1 1\n', '5 1\n1 2 2\n1 3 3\n3 4 1\n3 5 4\n4 5\n', '3 2\n1 2 10\n1 3 20\n2 3\n1 1\n'] })

t({ lv: 414, concept: '木: 重み付き直径', title: '木の重み付き直径', tags: ['グラフ', 'BFS'], io: '1行目に頂点数 n、続く n-1 行に重み付き辺 u v w が与えられます。', ask: '最も離れた2頂点間の距離 (重みの和) を出力してください。', h1: '任意の点から最遠点 u を求める。', h2: 'u から最遠点までの距離が直径。', ref: 'from collections import deque\nn=int(input())\ng=[[] for _ in range(n+1)]\nfor _ in range(n-1):\n    u,v,w=map(int,input().split())\n    g[u].append((v,w))\n    g[v].append((u,w))\ndef far(s):\n    dist=[-1]*(n+1)\n    dist[s]=0\n    dq=deque([s])\n    while dq:\n        x=dq.popleft()\n        for y,w in g[x]:\n            if dist[y]<0:\n                dist[y]=dist[x]+w\n                dq.append(y)\n    bd=0\n    bn=s\n    for i in range(1,n+1):\n        if dist[i]>bd:\n            bd=dist[i]\n            bn=i\n    return bn,bd\nu,_=far(1)\nv,d=far(u)\nprint(d)', tip: '「最遠点から最遠点」を2回探索する直径アルゴリズムは重み付きでも有効。', ins: ['4\n1 2 1\n2 3 2\n3 4 3\n', '1\n', '3\n1 2 5\n1 3 5\n', '2\n1 2 7\n', '5\n1 2 2\n2 3 2\n2 4 3\n4 5 5\n', '4\n1 2 10\n1 3 1\n1 4 1\n'] })

t({ lv: 415, concept: '関数グラフ: ρの周期', title: '関数を辿って入る閉路の長さ', tags: ['アルゴリズム'], io: '1行目に n x (頂点数、開始頂点)、2行目に n 個の f (各頂点の次の頂点、1始まり) が与えられます。', ask: '開始 x から f を辿り続けたとき、最終的に入る閉路の長さを出力してください。', h1: '亀と兎 (フロイドの循環検出) で出会う点を探す。', h2: '出会った後、一周回って長さを数える。', ref: 'line=input().split()\nn=int(line[0])\nx=int(line[1])\nf=list(map(int,input().split()))\ndef nxt(v):\n    return f[v-1]\nslow=nxt(x)\nfast=nxt(nxt(x))\nwhile slow!=fast:\n    slow=nxt(slow)\n    fast=nxt(nxt(fast))\nlength=1\ncur=nxt(slow)\nwhile cur!=slow:\n    cur=nxt(cur)\n    length+=1\nprint(length)', tip: 'フロイドの循環検出はO(1)メモリで関数グラフの周期を見つける。', ins: ['4 1\n2 3 4 2\n', '3 1\n1 1 1\n', '5 1\n2 3 1 5 4\n', '2 1\n2 1\n', '6 1\n2 3 4 5 6 4\n', '1 1\n1\n'] })

t({ lv: 416, concept: '幾何: マンハッタン距離の最大', title: '点集合のマンハッタン距離の最大', tags: ['幾何'], io: '1行目に点数 n、続く n 行に点 x y が与えられます。', ask: '任意の2点のマンハッタン距離 |dx|+|dy| の最大値を出力してください。', h1: '|dx|+|dy| は max((x+y) の差, (x−y) の差)。', h2: 'x+y と x−y それぞれの最大−最小を取る。', ref: 'n=int(input())\npts=[tuple(map(int,input().split())) for _ in range(n)]\nsu=[x+y for x,y in pts]\ndi=[x-y for x,y in pts]\nprint(max(max(su)-min(su),max(di)-min(di)))', tip: '座標を45度回転 (x±y) するとマンハッタン距離がチェビシェフ距離になる。', ins: ['3\n0 0\n1 1\n2 0\n', '2\n0 0\n3 4\n', '1\n5 5\n', '4\n0 0\n0 5\n5 0\n5 5\n', '3\n-1 -1\n1 1\n0 0\n', '2\n1 2\n3 4\n'] })

t({ lv: 417, concept: 'グラフ: 関節点の数', title: '関節点 (切断点) の数', tags: ['グラフ'], io: '1行目に n m、続く m 行に無向辺 u v が与えられます。', ask: '取り除くと連結成分が増える頂点 (関節点) の個数を出力してください。', h1: 'DFSで訪問時刻 disc と最小到達 low を求める。', h2: '子の low が自分の disc 以上なら関節点 (根は子2つ以上で関節点)。', ref: 'import sys\nsys.setrecursionlimit(300000)\nn,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\ndisc=[0]*(n+1)\nlow=[0]*(n+1)\nvisited=[False]*(n+1)\ntimer=[1]\nis_art=[False]*(n+1)\ndef dfs(u,parent):\n    visited[u]=True\n    disc[u]=low[u]=timer[0]\n    timer[0]+=1\n    children=0\n    for v in g[u]:\n        if v==parent:\n            continue\n        if visited[v]:\n            low[u]=min(low[u],disc[v])\n        else:\n            children+=1\n            dfs(v,u)\n            low[u]=min(low[u],low[v])\n            if parent!=0 and low[v]>=disc[u]:\n                is_art[u]=True\n    if parent==0 and children>1:\n        is_art[u]=True\nfor s in range(1,n+1):\n    if not visited[s]:\n        dfs(s,0)\nprint(sum(1 for i in range(1,n+1) if is_art[i]))', tip: 'disc と low の比較が関節点・橋を見つける lowlink 法の核心。', ins: ['5 4\n1 2\n2 3\n3 4\n4 5\n', '3 3\n1 2\n2 3\n1 3\n', '1 0\n', '5 5\n1 2\n2 3\n3 1\n3 4\n4 5\n', '4 3\n1 2\n1 3\n1 4\n', '2 1\n1 2\n'] })

t({ lv: 418, concept: 'グラフ: 橋の数', title: '橋 (切断辺) の数', tags: ['グラフ'], io: '1行目に n m、続く m 行に無向辺 u v (多重辺なし) が与えられます。', ask: '取り除くと連結成分が増える辺 (橋) の本数を出力してください。', h1: 'DFSで disc と low を求める。', h2: '子の low が自分の disc より大きければその辺は橋。', ref: 'import sys\nsys.setrecursionlimit(300000)\nn,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\ndisc=[0]*(n+1)\nlow=[0]*(n+1)\nvisited=[False]*(n+1)\ntimer=[1]\nbridges=[0]\ndef dfs(u,parent):\n    visited[u]=True\n    disc[u]=low[u]=timer[0]\n    timer[0]+=1\n    for v in g[u]:\n        if v==parent:\n            continue\n        if visited[v]:\n            low[u]=min(low[u],disc[v])\n        else:\n            dfs(v,u)\n            low[u]=min(low[u],low[v])\n            if low[v]>disc[u]:\n                bridges[0]+=1\nfor s in range(1,n+1):\n    if not visited[s]:\n        dfs(s,0)\nprint(bridges[0])', tip: '橋は「子から親側へ戻る別経路がない辺」。low>disc で判定する。', ins: ['5 4\n1 2\n2 3\n3 4\n4 5\n', '3 3\n1 2\n2 3\n1 3\n', '5 5\n1 2\n2 3\n3 1\n3 4\n4 5\n', '1 0\n', '4 3\n1 2\n1 3\n1 4\n', '6 6\n1 2\n2 3\n3 1\n4 5\n5 6\n6 4\n'] })

t({ lv: 419, concept: 'グラフ: 2辺連結成分の数', title: '橋を除いた連結成分の数', tags: ['グラフ'], io: '1行目に n m、続く m 行に無向辺 u v が与えられます。', ask: 'すべての橋を取り除いたときにできる連結成分 (2辺連結成分) の個数を出力してください。', h1: 'まず lowlink で橋を特定する。', h2: '橋以外の辺だけで連結成分を数える。', ref: 'import sys\nsys.setrecursionlimit(300000)\nfrom collections import deque\nn,m=map(int,input().split())\nadj=[[] for _ in range(n+1)]\nfor idx in range(m):\n    u,v=map(int,input().split())\n    adj[u].append((v,idx))\n    adj[v].append((u,idx))\ndisc=[0]*(n+1)\nlow=[0]*(n+1)\nvisited=[False]*(n+1)\ntimer=[1]\nis_bridge=[False]*m\ndef dfs(u,pe):\n    visited[u]=True\n    disc[u]=low[u]=timer[0]\n    timer[0]+=1\n    for v,ei in adj[u]:\n        if ei==pe:\n            continue\n        if visited[v]:\n            low[u]=min(low[u],disc[v])\n        else:\n            dfs(v,ei)\n            low[u]=min(low[u],low[v])\n            if low[v]>disc[u]:\n                is_bridge[ei]=True\nfor s in range(1,n+1):\n    if not visited[s]:\n        dfs(s,-1)\nseen=[False]*(n+1)\ncomp=0\nfor s in range(1,n+1):\n    if not seen[s]:\n        comp+=1\n        seen[s]=True\n        dq=deque([s])\n        while dq:\n            x=dq.popleft()\n            for y,ei in adj[x]:\n                if not is_bridge[ei] and not seen[y]:\n                    seen[y]=True\n                    dq.append(y)\nprint(comp)', tip: '橋で繋がれた塊が2辺連結成分。橋を消すと木状に分解される。', ins: ['5 4\n1 2\n2 3\n3 4\n4 5\n', '3 3\n1 2\n2 3\n1 3\n', '5 5\n1 2\n2 3\n3 1\n3 4\n4 5\n', '1 0\n', '6 6\n1 2\n2 3\n3 1\n4 5\n5 6\n6 4\n', '4 3\n1 2\n1 3\n1 4\n'] })

t({ lv: 420, concept: 'グラフ: 最小費用最大流', title: '最大流を流す最小費用', tags: ['グラフ'], io: '1行目に n m s t、続く m 行に u v cap cost (有向辺・容量・単位コスト) が与えられます。', ask: 's から t へ最大流を流すときの最小の総コストを出力してください。', h1: '残余グラフ上で最小コストの増加道を探す (SPFA/ベルマンフォード)。', h2: '逆辺はコストを符号反転して持つ。', ref: 'from collections import deque\nfirst=input().split()\nn=int(first[0])\nm=int(first[1])\ns=int(first[2])\nt=int(first[3])\ngraph=[[] for _ in range(n+1)]\ndef add_edge(u,v,cap,cost):\n    graph[u].append([v,cap,cost,len(graph[v])])\n    graph[v].append([u,0,-cost,len(graph[u])-1])\nfor _ in range(m):\n    u,v,cap,cost=map(int,input().split())\n    add_edge(u,v,cap,cost)\nINF=float("inf")\ntotal_cost=0\nwhile True:\n    dist=[INF]*(n+1)\n    inq=[False]*(n+1)\n    prevv=[-1]*(n+1)\n    preve=[-1]*(n+1)\n    dist[s]=0\n    dq=deque([s])\n    inq[s]=True\n    while dq:\n        u=dq.popleft()\n        inq[u]=False\n        for i in range(len(graph[u])):\n            v,cap,cost,rev=graph[u][i]\n            if cap>0 and dist[u]+cost<dist[v]:\n                dist[v]=dist[u]+cost\n                prevv[v]=u\n                preve[v]=i\n                if not inq[v]:\n                    dq.append(v)\n                    inq[v]=True\n    if dist[t]==INF:\n        break\n    d=INF\n    v=t\n    while v!=s:\n        d=min(d,graph[prevv[v]][preve[v]][1])\n        v=prevv[v]\n    v=t\n    while v!=s:\n        graph[prevv[v]][preve[v]][1]-=d\n        rev=graph[prevv[v]][preve[v]][3]\n        graph[v][rev][1]+=d\n        v=prevv[v]\n    total_cost+=d*dist[t]\nprint(total_cost)', tip: '最小費用の増加道を繰り返す。逆辺の負コストでフローのやり直しを表す。', ins: ['4 5 1 4\n1 2 2 1\n1 3 2 2\n2 4 2 3\n3 4 2 1\n2 3 1 1\n', '2 1 1 2\n1 2 5 3\n', '3 2 1 3\n1 2 3 2\n2 3 3 4\n', '2 0 1 2\n', '4 4 1 4\n1 2 1 5\n1 3 1 1\n2 4 1 1\n3 4 1 5\n', '3 3 1 3\n1 2 2 1\n1 3 1 5\n2 3 2 1\n'] })

export const CATALOG = TASKS
