// 生成タスク 第44波：lv901〜949。最高峰帯。
// 高度な数え上げ/ゲーム理論(Sprague-Grundy)/数論/グラフ/区間DP。
// (実在の定番問題の定義を確認しオリジナル化。tipは出典なしの解説。)
// 重複なし・決定的・採点一意。無限ループ無し。
const MOD = 1000000007
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 901, concept: 'DP: 大小条件を満たす順列の数', title: '<>パターンを満たす順列の数', tags: ['dp', '数え上げ'], io: '1行目に n、2行目に長さ n-1 の "<"と">" からなる文字列 s が与えられます。', ask: '1..n の順列で、s[i]が"<"なら p[i]<p[i+1]、">"なら p[i]>p[i+1] を満たすものの数を 1000000007 で割った余りで出力してください。', h1: 'dp[i][j]=長さiで末尾がj番目に小さい順列の数。', h2: '"<"なら ndp[j]=Σ_{k<j}dp[k]、">"なら Σ_{k>=j}dp[k]。', ref: `n=int(input())\ns=input().strip()\nMOD=${MOD}\ndp=[1]\nfor i in range(1,n):\n    c=s[i-1]\n    ndp=[0]*(i+1)\n    for j in range(i+1):\n        if c=="<":\n            tot=0\n            for k in range(0,j):\n                tot+=dp[k]\n            ndp[j]=tot%MOD\n        else:\n            tot=0\n            for k in range(j,i):\n                tot+=dp[k]\n            ndp[j]=tot%MOD\n    dp=ndp\nprint(sum(dp)%MOD)`, tip: '末尾の相対順位を状態にすると、累積和で O(n²) に高速化できる典型的な順列DP。', ins: ['4\n<><\n', '2\n<\n', '2\n>\n', '3\n<<\n', '3\n>>\n', '4\n<<<\n'] })

t({ lv: 902, concept: 'bitDP: 集合分割の最大スコア', title: 'グループ分けの最大スコア', tags: ['bitDP', 'dp'], io: '1行目に n、続く n 行に n×n の対称行列 a(同じグループの i,j で a[i][j] 点)が与えられます。', ask: 'n 個を任意個のグループに分けたときの合計スコアの最大値を出力してください(n<=16)。', h1: '各部分集合を1グループとしたスコアを前計算。', h2: 'dp[集合]=部分集合に分けた最大、部分集合で遷移。', ref: 'n=int(input())\na=[list(map(int,input().split())) for _ in range(n)]\nfull=1<<n\ngroup=[0]*full\nfor mask in range(full):\n    s=0\n    members=[i for i in range(n) if (mask>>i)&1]\n    for x in range(len(members)):\n        for y in range(x+1,len(members)):\n            s+=a[members[x]][members[y]]\n    group[mask]=s\nNEG=float("-inf")\ndp=[NEG]*full\ndp[0]=0\nfor mask in range(full):\n    if dp[mask]==NEG:\n        continue\n    rest=(full-1)^mask\n    sub=rest\n    while sub>0:\n        if dp[mask]+group[sub]>dp[mask|sub]:\n            dp[mask|sub]=dp[mask]+group[sub]\n        sub=(sub-1)&rest\nprint(dp[full-1])', tip: '各部分集合のスコアを前計算し、部分集合列挙のbitDPで O(3^n)。集合を1グループずつ確定させる。', ins: ['3\n0 10 20\n10 0 -100\n20 -100 0\n', '1\n0\n', '2\n0 5\n5 0\n', '2\n0 -5\n-5 0\n', '3\n0 0 0\n0 0 0\n0 0 0\n', '4\n0 1 1 1\n1 0 1 1\n1 1 0 1\n1 1 1 0\n'] })

t({ lv: 903, concept: '数え上げ: 壁を避けるグリッド経路数', title: '壁を避ける格子経路数(包除)', tags: ['数え上げ', 'dp'], io: '1行目に H W k、続く k 行に壁の座標 r c(1始まり)が与えられます。', ask: '(1,1)から(H,W)へ右・下のみで進み壁を通らない経路数を 1000000007 で割った余りで出力してください。', h1: '壁を行優先でソートし、各壁への壁無し経路数を求める。', h2: 'dp[i]=壁iで初めて止まる経路数=全経路-(手前の壁経由)。', ref: `first=input().split()\nH=int(first[0])\nW=int(first[1])\nk=int(first[2])\nMOD=${MOD}\nwalls=[tuple(map(int,input().split())) for _ in range(k)]\nN=H+W+10\nfact=[1]*(N+1)\nfor i in range(1,N+1):\n    fact[i]=fact[i-1]*i%MOD\ninv=[1]*(N+1)\ninv[N]=pow(fact[N],MOD-2,MOD)\nfor i in range(N-1,-1,-1):\n    inv[i]=inv[i+1]*(i+1)%MOD\ndef paths(r1,c1,r2,c2):\n    if r2<r1 or c2<c1:\n        return 0\n    dr=r2-r1\n    dc=c2-c1\n    return fact[dr+dc]*inv[dr]%MOD*inv[dc]%MOD\npts=sorted(walls)\npts.append((H,W))\nm=len(pts)\ndp=[0]*m\nfor i in range(m):\n    dp[i]=paths(1,1,pts[i][0],pts[i][1])\n    for j in range(i):\n        if pts[j][0]<=pts[i][0] and pts[j][1]<=pts[i][1]:\n            dp[i]=(dp[i]-dp[j]*paths(pts[j][0],pts[j][1],pts[i][0],pts[i][1]))%MOD\nprint(dp[m-1]%MOD)`, tip: '壁が少なければ「各壁で初めて止まる経路数」を包除で引く O(k²)。格子全体のDPは大きすぎて不可。', ins: ['3 4 2\n2 2\n1 4\n', '2 2 1\n1 2\n', '5 5 0\n', '2 2 1\n2 1\n', '3 3 1\n2 2\n', '10 7 0\n'] })

t({ lv: 904, concept: 'DP: 転倒数がkの順列の数', title: '転倒数がちょうどkの順列の数', tags: ['dp', '数え上げ'], io: 'n k が空白区切りで与えられます。', ask: '1..n の順列で転倒数がちょうど k のものの数を 1000000007 で割った余りで出力してください。', h1: 'dp[i][j]=長さiで転倒数jの数。', h2: 'i番目の挿入で0..i-1個の転倒が増える(累積和で高速化)。', ref: `n,k=map(int,input().split())\nMOD=${MOD}\ndp=[0]*(k+1)\ndp[0]=1\nfor i in range(2,n+1):\n    ndp=[0]*(k+1)\n    pre=[0]*(k+2)\n    for j in range(k+1):\n        pre[j+1]=(pre[j]+dp[j])%MOD\n    for j in range(k+1):\n        lo=max(0,j-(i-1))\n        ndp[j]=(pre[j+1]-pre[lo])%MOD\n    dp=ndp\nprint(dp[k]%MOD)`, tip: '新要素の挿入で0..i-1個の転倒が増えるDP。区間和になるので累積和で O(nk)。', ins: ['4 3\n', '3 0\n', '3 3\n', '1 0\n', '5 5\n', '4 6\n'] })

t({ lv: 905, concept: 'DP: 2×nの塔の数', title: '幅2・高さnの塔の数', tags: ['dp', '数え上げ'], io: '非負整数 n が1行で与えられます。', ask: '幅2・高さ n の塔(各段は左右に分かれるか1ブロック)の構造数を 1000000007 で割った余りで出力してください。', h1: 'dp[i][2状態]=i段目が2分割か1ブロックか。', h2: '同状態は前段の和、状態切替は限定的。', ref: `n=int(input())\nMOD=${MOD}\nif n==0:\n    print(1)\nelse:\n    one=1\n    two=1\n    for _ in range(2,n+1):\n        none=(one+two)%MOD\n        ntwo=(one+2*two)%MOD\n        one=none\n        two=ntwo\n    print((one+two)%MOD)`, tip: '各段を「1ブロック/2分割」の2状態に分け、段の境界が揃うかで遷移係数が変わる漸化式DP。', ins: ['1\n', '2\n', '6\n', '3\n', '0\n', '10\n'] })

t({ lv: 906, concept: 'ゲーム: 不等分割ゲーム', title: '山を不等な2つに割るゲームの勝者', tags: ['ゲーム', 'dp'], io: '山の石の数 n が1行で与えられます。', ask: '1つの山を「異なる個数の2つの空でない山」に分ける操作を交互に行い、動けなくなった方が負けです。先手必勝なら First、後手必勝なら Second を出力してください。', h1: '各 n の Grundy 数を mex で計算。', h2: '分割 (a,n-a) の Grundy の XOR を集めて mex を取る。', ref: 'n=int(input())\ngrundy=[0]*(n+1)\nfor i in range(1,n+1):\n    reach=set()\n    for a in range(1,i):\n        b=i-a\n        if a!=b:\n            reach.add(grundy[a]^grundy[b])\n    g=0\n    while g in reach:\n        g+=1\n    grundy[i]=g\nprint("First" if grundy[n]!=0 else "Second")', tip: '山を不等な2つに割る操作のGrundy数を mex で求めるSprague-Grundy理論。分割後は2山のXOR。', ins: ['6\n', '7\n', '8\n', '1\n', '2\n', '10\n'] })

t({ lv: 907, concept: 'DP: 等和2分割の方法数', title: '1..nを等和2集合に分ける方法数', tags: ['dp', '数え上げ'], io: '正整数 n が1行で与えられます。', ask: '{1,2,...,n} を和が等しい2つの集合に分ける方法の数を 1000000007 で割った余りで出力してください(分け方は2集合の順序を区別しない)。総和が奇数なら0。', h1: '総和の半分を作る部分集合数を数える。', h2: '対称性で2で割る(dp[half]/2)。', ref: `n=int(input())\nMOD=${MOD}\ntotal=n*(n+1)//2\nif total%2==1:\n    print(0)\nelse:\n    half=total//2\n    dp=[0]*(half+1)\n    dp[0]=1\n    for v in range(1,n+1):\n        for s in range(half,v-1,-1):\n            dp[s]=(dp[s]+dp[s-v])%MOD\n    inv2=pow(2,MOD-2,MOD)\n    print(dp[half]*inv2%MOD)`, tip: '半分の和を作る部分集合数を数え、2集合の対称性で2で割る(modなので逆元を掛ける)。', ins: ['7\n', '3\n', '1\n', '4\n', '6\n', '100\n'] })

t({ lv: 908, concept: 'DP: 長方形を正方形に切る最小数', title: 'a×bを正方形に切る最小回数', tags: ['dp'], io: 'a b が空白区切りで与えられます。', ask: 'a×b の長方形を正方形のみに分割するのに必要な最小の切断回数を出力してください。', h1: 'dp[i][j]=i×jを切る最小回数。', h2: '横切り・縦切りの全分割点で最小を取る(正方形は0)。', ref: 'a,b=map(int,input().split())\ndp=[[0]*(b+1) for _ in range(a+1)]\nfor i in range(1,a+1):\n    for j in range(1,b+1):\n        if i==j:\n            dp[i][j]=0\n            continue\n        best=float("inf")\n        for k in range(1,i//2+1):\n            best=min(best,dp[k][j]+dp[i-k][j]+1)\n        for k in range(1,j//2+1):\n            best=min(best,dp[i][k]+dp[i][j-k]+1)\n        dp[i][j]=best\nprint(dp[a][b])', tip: '縦横の全切断位置で2つに分けるDP。正方形になったら切断不要(0)。', ins: ['3 5\n', '1 1\n', '2 2\n', '4 6\n', '2 3\n', '5 5\n'] })

t({ lv: 909, concept: '数え上げ: 回転で同一視するネックレス', title: 'ネックレスの数(バーンサイド)', tags: ['数え上げ', '数論'], io: 'n m が空白区切りで与えられます(n 個のビーズ、m 色)。', ask: '回転で一致するものを同一とみなしたネックレスの数を 1000000007 で割った余りで出力してください。', h1: '各約数 d について φ(d)·m^(n/d)。', h2: 'バーンサイドの補題で n で割る(mod逆元)。', ref: `n,m=map(int,input().split())\nMOD=${MOD}\nif n==0:\n    print(1)\nelse:\n    def phi(x):\n        res=x\n        mm=x\n        p=2\n        while p*p<=mm:\n            if mm%p==0:\n                while mm%p==0:\n                    mm//=p\n                res-=res//p\n            p+=1\n        if mm>1:\n            res-=res//mm\n        return res\n    total=0\n    d=1\n    while d*d<=n:\n        if n%d==0:\n            total=(total+phi(d)*pow(m,n//d,MOD))%MOD\n            if d!=n//d:\n                total=(total+phi(n//d)*pow(m,d,MOD))%MOD\n        d+=1\n    print(total*pow(n,MOD-2,MOD)%MOD)`, tip: 'バーンサイドの補題: 回転群の不動点平均 (1/n)Σφ(d)·m^(n/d)。各回転d周期の不動点を数える。', ins: ['3 2\n', '1 5\n', '2 2\n', '4 2\n', '5 3\n', '6 2\n'] })

t({ lv: 910, concept: '数論: 2要素以上を割る最大の数', title: '最大の公約数になり得る数', tags: ['数論'], io: '正整数の列が1行で与えられます。', ask: '配列の2つ以上の要素を割り切る最大の数を出力してください。', h1: '各数の約数の出現回数を数える。', h2: '2回以上現れる最大の約数。', ref: 'a=list(map(int,input().split()))\nmx=max(a)\ncnt=[0]*(mx+1)\nfor x in a:\n    d=1\n    while d*d<=x:\n        if x%d==0:\n            cnt[d]+=1\n            if d!=x//d:\n                cnt[x//d]+=1\n        d+=1\nbest=1\nfor d in range(1,mx+1):\n    if cnt[d]>=2:\n        best=d\nprint(best)', tip: '各要素の約数を列挙して数え、2回以上現れる最大の約数を探す。約数列挙は√xで。', ins: ['3 12 6 9\n', '1 1\n', '5 7\n', '2 4 8\n', '10 20 30\n', '6 6\n'] })

t({ lv: 911, concept: '数論: りんごの分配(重複組合せ)', title: 'n個のりんごをk人に配る方法数', tags: ['数論', '数え上げ'], io: 'n k が空白区切りで与えられます。', ask: 'n 個の同じりんごを k 人に配る(0個可)方法の数を 1000000007 で割った余りで出力してください。', h1: '仕切り棒(stars and bars)で考える。', h2: 'C(n+k-1, n) を mod で計算。', ref: `n,k=map(int,input().split())\nMOD=${MOD}\nN=n+k\nfact=[1]*(N+1)\nfor i in range(1,N+1):\n    fact[i]=fact[i-1]*i%MOD\ninv=[1]*(N+1)\ninv[N]=pow(fact[N],MOD-2,MOD)\nfor i in range(N-1,-1,-1):\n    inv[i]=inv[i+1]*(i+1)%MOD\ndef comb(a,b):\n    if b<0 or b>a:\n        return 0\n    return fact[a]*inv[b]%MOD*inv[a-b]%MOD\nprint(comb(n+k-1,n))`, tip: '区別しないものの分配は重複組合せ(stars and bars) C(n+k-1, n)。仕切りk-1本と品n個の並べ方。', ins: ['3 2\n', '0 5\n', '5 1\n', '10 3\n', '1 1\n', '7 4\n'] })

t({ lv: 912, concept: 'DP: サイコロで合計nを作る方法数', title: 'サイコロを振って合計nになる場合の数', tags: ['dp', '数え上げ'], io: '非負整数 n が1行で与えられます。', ask: 'サイコロ(出目1〜6)を何回でも振り、出目を順に並べて合計が n になる場合の数を 1000000007 で割った余りで出力してください。', h1: 'dp[x]=合計xを作る場合の数。', h2: 'dp[x]=Σ_{f=1}^{6} dp[x-f]。', ref: `n=int(input())\nMOD=${MOD}\ndp=[0]*(n+1)\ndp[0]=1\nfor x in range(1,n+1):\n    for f in range(1,7):\n        if x-f>=0:\n            dp[x]=(dp[x]+dp[x-f])%MOD\nprint(dp[n]%MOD)`, tip: '順序を区別する合成数の数え上げ(6項の線形漸化式)。大きいnは行列累乗で O(log n)。', ins: ['3\n', '0\n', '1\n', '6\n', '10\n', '2\n'] })

t({ lv: 913, concept: '桁DP: 隣接する桁が異なる数の個数', title: '隣接桁が同じにならない数の個数', tags: ['桁DP', 'dp'], io: 'N が1行で与えられます(大きくてよい)。', ask: '1以上 N 以下の整数で、隣り合う桁が同じにならないものの個数を出力してください。', h1: '上位桁から tight・直前の桁・開始済みかを状態に持つ。', h2: '直前と異なる桁だけ置ける(先頭の0は未開始扱い)。', ref: 'import sys\nsys.setrecursionlimit(10000)\nfrom functools import lru_cache\nN=input().strip()\ndigits=[int(c) for c in N]\nL=len(digits)\n@lru_cache(maxsize=None)\ndef rec(pos,tight,prev,started):\n    if pos==L:\n        return 1 if started else 0\n    hi=digits[pos] if tight else 9\n    total=0\n    for d in range(hi+1):\n        if started and d==prev:\n            continue\n        total+=rec(pos+1,tight and d==hi,d,started or d>0)\n    return total\nprint(rec(0,True,-1,False))', tip: '桁DPで「直前の桁」と「開始フラグ」を状態に持つ。先頭の連続する0を未開始として扱うのがコツ。', ins: ['20\n', '9\n', '100\n', '11\n', '0\n', '55\n'] })

t({ lv: 914, concept: 'ゲーム: 階段Nim', title: '階段Nimの勝者', tags: ['ゲーム'], io: '1行目に n、2行目に各段のコイン数 p[1..n] が与えられます。', ask: '段 k のコインを段 k-1 へ任意個動かす操作を交互に行い(段1からは外へ捨てる)、動けない方が負けです。先手必勝なら First、後手必勝なら Second を出力してください。', h1: '奇数番目の段のコイン数だけを見る。', h2: 'それらのXORが非ゼロなら先手必勝。', ref: 'n=int(input())\np=list(map(int,input().split()))\nx=0\nfor i in range(n):\n    if (i+1)%2==1:\n        x^=p[i]\nprint("First" if x!=0 else "Second")', tip: '階段Nimは奇数段のコイン数のXORで勝敗が決まる。偶数段への移動は相手が打ち消せるため無効手になる。', ins: ['2\n3 5\n', '1\n0\n', '3\n1 2 3\n', '2\n0 7\n', '1\n5\n', '4\n1 1 1 1\n'] })

t({ lv: 915, concept: 'ゲーム: 2山の引き算ゲーム', title: '2山の同時引きありゲームの勝者', tags: ['ゲーム', '数学'], io: 'a b が空白区切りで与えられます(2山の石の数)。', ask: '「1つの山から任意個」または「両方から同数」取る操作を交互に行い、取れなくなった方が負けです。先手必勝なら First、後手必勝なら Second を出力してください。', h1: '差 d=|a-b| を取る。', h2: '小さい方が floor(d·黄金比) なら後手必勝(P局面)。', ref: 'import math\na,b=map(int,input().split())\nif a>b:\n    a,b=b,a\nd=b-a\nphi=(1+math.sqrt(5))/2\nk=int(d*phi)\nif a==k:\n    print("Second")\nelse:\n    print("First")', tip: 'P局面(後手必勝)は (⌊kφ⌋,⌊kφ²⌋) の形で、黄金比φで特徴づけられる。Beatty列に対応する。', ins: ['0 0\n', '1 2\n', '3 5\n', '2 2\n', '1 0\n', '4 7\n'] })

t({ lv: 916, concept: '数え上げ: 上昇数で分類する順列の数', title: '上昇がちょうどk個の順列の数', tags: ['数え上げ', 'dp'], io: 'n k が空白区切りで与えられます。', ask: 'ちょうど k 個の上昇(a[i]<a[i+1])を持つ 1..n の順列の数を出力してください。', h1: 'A(n,k)=(k+1)A(n-1,k)+(n-k)A(n-1,k-1)。', h2: 'DPで表を埋める。', ref: 'n,k=map(int,input().split())\ndp=[[0]*(n+1) for _ in range(n+1)]\ndp[1][0]=1\nfor i in range(2,n+1):\n    for j in range(0,i):\n        dp[i][j]=(j+1)*dp[i-1][j]+(i-j)*dp[i-1][j-1] if j>=1 else (j+1)*dp[i-1][j]\nif n==0:\n    print(1 if k==0 else 0)\nelse:\n    print(dp[n][k] if k<n else 0)', tip: '順列の上昇数の分布(オイラー数)。漸化式 A(n,k)=(k+1)A(n-1,k)+(n-k)A(n-1,k-1)。', ins: ['4 2\n', '3 0\n', '3 1\n', '1 0\n', '5 2\n', '4 0\n'] })

t({ lv: 917, concept: '数え上げ: 括弧列の山の数で分類', title: '山がk個の括弧列の数(ナラヤナ)', tags: ['数え上げ'], io: 'n k が空白区切りで与えられます。', ask: '長さ 2n の正しい括弧列で「()」の形(山)がちょうど k 個現れるものの数 N(n,k)=(1/n)·C(n,k)·C(n,k-1) を出力してください。', h1: '二項係数2つの積をnで割る。', h2: 'kの和を取るとカタラン数になる。', ref: 'import math\nn,k=map(int,input().split())\nif n==0 or k<1 or k>n:\n    print(0)\nelse:\n    print(math.comb(n,k)*math.comb(n,k-1)//n)', tip: 'ナラヤナ数 N(n,k)=(1/n)C(n,k)C(n,k-1)。k で和を取るとカタラン数になる細分。', ins: ['4 2\n', '1 1\n', '3 1\n', '3 3\n', '5 2\n', '4 4\n'] })

t({ lv: 918, concept: '数え上げ: モツキン数', title: 'モツキン数M(n)', tags: ['数え上げ', 'dp'], io: '非負整数 n が1行で与えられます。', ask: 'n 番目のモツキン数 M(n) を出力してください。', h1: '漸化式 M(n)=((2n+1)M(n-1)+(3n-3)M(n-2))/(n+2)。', h2: '初期値 M(0)=M(1)=1。', ref: 'n=int(input())\nif n==0:\n    print(1)\nelse:\n    M=[0]*(n+1)\n    M[0]=1\n    if n>=1:\n        M[1]=1\n    for i in range(2,n+1):\n        M[i]=((2*i+1)*M[i-1]+(3*i-3)*M[i-2])//(i+2)\n    print(M[n])', tip: '円周上の交差しない弦の数などを数える数列。カタラン数と近縁で、漸化式で O(n) に計算できる。', ins: ['4\n', '0\n', '1\n', '10\n', '3\n', '8\n'] })

t({ lv: 919, concept: '数え上げ: シュレーダー数', title: '大シュレーダー数', tags: ['数え上げ', 'dp'], io: '非負整数 n が1行で与えられます。', ask: 'n 番目の大シュレーダー数を出力してください(格子で(0,0)から(n,n)へ対角線を超えず東・北・北東に進む経路数)。', h1: '漸化式 a(n)=(3(2n-1)a(n-1)-(n-2)a(n-2))/(n+1)。', h2: '初期値 a(0)=1, a(1)=2。', ref: 'n=int(input())\nif n==0:\n    print(1)\nelse:\n    a=[0]*(n+1)\n    a[0]=1\n    if n>=1:\n        a[1]=2\n    for i in range(2,n+1):\n        a[i]=(3*(2*i-1)*a[i-1]-(i-2)*a[i-2])//(i+1)\n    print(a[n])', tip: '対角線を超えない斜め歩許可の格子経路数。カタラン数の拡張で、漸化式で求まる。', ins: ['3\n', '0\n', '1\n', '6\n', '2\n', '8\n'] })

t({ lv: 920, concept: '数え上げ: 巡回数で分類する順列の数', title: '巡回がちょうどk個の順列の数', tags: ['数え上げ', 'dp'], io: 'n k が空白区切りで与えられます。', ask: 'ちょうど k 個の巡回を持つ 1..n の順列の数(符号なし第一種スターリング数)を出力してください。', h1: 'c(n,k)=c(n-1,k-1)+(n-1)·c(n-1,k)。', h2: 'DPで表を埋める。', ref: 'n,k=map(int,input().split())\ndp=[[0]*(k+1) for _ in range(n+1)]\ndp[0][0]=1\nfor i in range(1,n+1):\n    for j in range(1,k+1):\n        dp[i][j]=dp[i-1][j-1]+(i-1)*dp[i-1][j]\nprint(dp[n][k] if k<=n else 0)', tip: '順列の巡回数の分布(第一種スターリング数)。新要素を新しい巡回にするか既存の巡回に挿入する。', ins: ['4 2\n', '3 3\n', '3 1\n', '0 0\n', '5 2\n', '4 1\n'] })

t({ lv: 921, concept: '数え上げ: 順序付きベル数', title: '順序付きベル数(弱順序の数)', tags: ['数え上げ', 'dp'], io: '非負整数 n が1行で与えられます。', ask: 'n 要素の順序付き分割(同順位を許す順位付け)の数を出力してください。', h1: 'a(n)=Σ_{k=1}^{n} C(n,k)·a(n-k)。', h2: '第二種スターリング数×k! の和でもある。', ref: 'import math\nn=int(input())\na=[0]*(n+1)\na[0]=1\nfor i in range(1,n+1):\n    s=0\n    for k in range(1,i+1):\n        s+=math.comb(i,k)*a[i-k]\n    a[i]=s\nprint(a[n])', tip: '弱順序(同順位可の順位付け)の総数=Fubini数。最上位グループの選び方で再帰する。', ins: ['3\n', '0\n', '1\n', '4\n', '2\n', '6\n'] })

t({ lv: 922, concept: '数論: 階乗の末尾の0の数', title: 'n!の末尾の0の個数', tags: ['数論'], io: '非負整数 n が1行で与えられます。', ask: 'n! の末尾に並ぶ0の個数を出力してください。', h1: '末尾の0は因数10=2·5の数。', h2: '5の方が少ないので5の指数を数える(ルジャンドル)。', ref: 'n=int(input())\ncount=0\np=5\nwhile p<=n:\n    count+=n//p\n    p*=5\nprint(count)', tip: 'n!の末尾0は5の指数=Σ⌊n/5^k⌋。2より5の因数が少ないので5だけ数えればよい。', ins: ['10\n', '0\n', '5\n', '25\n', '100\n', '4\n'] })

t({ lv: 923, concept: '数論: 階乗に含まれる素数pの指数', title: 'n!に含まれる素数pの指数', tags: ['数論'], io: 'n p が空白区切りで与えられます(p は素数)。', ask: 'n! を割り切る p の最大の指数(ルジャンドルの公式)を出力してください。', h1: 'Σ_{k>=1} ⌊n/p^k⌋。', h2: 'p^k が n を超えたら終了。', ref: 'n,p=map(int,input().split())\ncount=0\npk=p\nwhile pk<=n:\n    count+=n//pk\n    pk*=p\nprint(count)', tip: 'ルジャンドルの公式 v_p(n!)=Σ⌊n/p^k⌋。二項係数のmod計算やKummerの定理の基礎になる。', ins: ['10 2\n', '10 5\n', '6 3\n', '100 7\n', '1 2\n', '25 5\n'] })

t({ lv: 924, concept: '数論: 乗法的位数', title: 'a の法n での位数', tags: ['数論'], io: 'a n が空白区切りで与えられます(gcd(a,n)=1)。', ask: 'a^k≡1 (mod n) を満たす最小の正整数 k(乗法的位数)を出力してください。', h1: '位数は φ(n) の約数。', h2: 'φ(n) の各約数を小さい順に試す。', ref: 'import math\na,n=map(int,input().split())\nif n==1:\n    print(1)\nelse:\n    def phi(x):\n        res=x\n        m=x\n        p=2\n        while p*p<=m:\n            if m%p==0:\n                while m%p==0:\n                    m//=p\n                res-=res//p\n            p+=1\n        if m>1:\n            res-=res//m\n        return res\n    ph=phi(n)\n    divs=[]\n    d=1\n    while d*d<=ph:\n        if ph%d==0:\n            divs.append(d)\n            divs.append(ph//d)\n        d+=1\n    divs.sort()\n    for k in divs:\n        if pow(a,k,n)==1:\n            print(k)\n            break', tip: '乗法的位数は必ず φ(n) の約数。約数を小さい順に試して最初に a^k≡1 となる k を返す。', ins: ['2 7\n', '3 7\n', '2 5\n', '1 9\n', '10 13\n', '4 15\n'] })

t({ lv: 925, concept: '数論: ヤコビ記号', title: 'ヤコビ記号(a/n)', tags: ['数論'], io: 'a n が空白区切りで与えられます(n は正の奇数)。', ask: 'ヤコビ記号 (a/n) の値(-1,0,1)を出力してください。', h1: '相互法則と補充法則で簡約する。', h2: 'ユークリッド的に a と n を縮約する。', ref: 'a,n=map(int,input().split())\na%=n\nresult=1\nwhile a!=0:\n    while a%2==0:\n        a//=2\n        r=n%8\n        if r==3 or r==5:\n            result=-result\n    a,n=n,a\n    if a%4==3 and n%4==3:\n        result=-result\n    a%=n\nif n==1:\n    print(result)\nelse:\n    print(0)', tip: '平方剰余の相互法則を用いてユークリッド的に簡約する。素数の法なら平方剰余判定になる。', ins: ['2 15\n', '1 1\n', '3 7\n', '5 21\n', '0 5\n', '7 9\n'] })

t({ lv: 926, concept: '数論: カーマイケル関数', title: 'カーマイケル関数λ(n)', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: 'gcd(a,n)=1 なる全ての a で a^λ≡1 (mod n) となる最小の λ(n) を出力してください。', h1: '素因数べきごとの λ を求める。', h2: '全体は各 λ の最小公倍数。', ref: 'import math\nn=int(input())\ndef lam_pk(p,e):\n    if p==2:\n        if e==1:\n            return 1\n        if e==2:\n            return 2\n        return 2**(e-2)\n    return (p**(e-1))*(p-1)\nm=n\nres=1\np=2\nwhile p*p<=m:\n    if m%p==0:\n        e=0\n        while m%p==0:\n            m//=p\n            e+=1\n        res=res*lam_pk(p,e)//math.gcd(res,lam_pk(p,e))\n    p+=1\nif m>1:\n    l=lam_pk(m,1)\n    res=res*l//math.gcd(res,l)\nprint(res if n>1 else 1)', tip: 'カーマイケル関数は素数べきごとのλのLCM。λ(n)|φ(n) で、乗法群の最大位数を与える。', ins: ['1\n', '8\n', '15\n', '7\n', '12\n', '100\n'] })

t({ lv: 927, concept: '数論: 素数の倍数の個数(包除)', title: '与えた素数のいずれかの倍数の個数', tags: ['数論', '包除原理'], io: '1行目に n と素数の個数 k、2行目に k 個の相異なる素数が与えられます。', ask: '1以上 n 以下で、与えられた素数のいずれかで割り切れる整数の個数を出力してください。', h1: '素数の部分集合で包除する。', h2: '奇数個なら加算、偶数個なら減算(積>nで打ち切り)。', ref: 'first=input().split()\nn=int(first[0])\nk=int(first[1])\nprimes=list(map(int,input().split())) if k>0 else []\ntotal=0\nfor mask in range(1,1<<k):\n    prod=1\n    bits=0\n    ok=True\n    for i in range(k):\n        if (mask>>i)&1:\n            prod*=primes[i]\n            bits+=1\n            if prod>n:\n                ok=False\n                break\n    if not ok:\n        continue\n    if bits%2==1:\n        total+=n//prod\n    else:\n        total-=n//prod\nprint(total)', tip: '包除原理で「少なくとも1つの素数で割れる数」を数える。積がnを超える部分集合は寄与0で打ち切れる。', ins: ['20 2\n2 3\n', '10 1\n5\n', '100 3\n2 3 5\n', '7 0\n', '50 2\n7 11\n', '1 1\n2\n'] })

t({ lv: 928, concept: '数論: mと互いに素な数の個数', title: 'n以下でmと互いに素な数の個数', tags: ['数論', '包除原理'], io: 'n m が空白区切りで与えられます。', ask: '1以上 n 以下で m と互いに素な整数の個数を出力してください。', h1: 'm の相異なる素因数を求める。', h2: '素因数で包除する(n=mのときφ(m))。', ref: 'n,m=map(int,input().split())\nprimes=[]\nmm=m\np=2\nwhile p*p<=mm:\n    if mm%p==0:\n        primes.append(p)\n        while mm%p==0:\n            mm//=p\n    p+=1\nif mm>1:\n    primes.append(mm)\nk=len(primes)\ntotal=0\nfor mask in range(1<<k):\n    prod=1\n    bits=0\n    for i in range(k):\n        if (mask>>i)&1:\n            prod*=primes[i]\n            bits+=1\n    if bits%2==0:\n        total+=n//prod\n    else:\n        total-=n//prod\nprint(total)', tip: '包除原理でmの素因数のどれかで割れる数を除く。n=m のとき φ(m) に一致する一般化。', ins: ['10 6\n', '12 12\n', '100 10\n', '1 5\n', '20 7\n', '30 30\n'] })

t({ lv: 929, concept: '数論: 約数和関数の総和', title: 'Σσ(i)の値', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: 'Σ_{i=1}^{n} σ(i)(各 i の約数の総和の合計)を出力してください。', h1: '各 d は d の倍数すべてに約数として寄与する。', h2: 'Σ_{d=1}^{n} d·⌊n/d⌋。', ref: 'n=int(input())\ntotal=0\nd=1\nwhile d<=n:\n    total+=d*(n//d)\n    d+=1\nprint(total)', tip: 'Σσ(i)=Σ_d d·⌊n/d⌋(各dがその倍数に約数として寄与)。⌊n/d⌋の同値区間でO(√n)化できる。', ins: ['5\n', '1\n', '10\n', '2\n', '100\n', '3\n'] })

t({ lv: 930, concept: '数論: 1の平方根の個数', title: 'x²≡1 (mod n) の解の個数', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: '0以上 n 未満で x²≡1 (mod n) を満たす x の個数を出力してください。', h1: '素因数べきごとに解数(2/1/4)を求める。', h2: '中国剰余定理で各素数べきの解数の積。', ref: 'n=int(input())\nif n==1:\n    print(1)\nelse:\n    m=n\n    res=1\n    e2=0\n    while m%2==0:\n        m//=2\n        e2+=1\n    if e2==1:\n        res*=1\n    elif e2==2:\n        res*=2\n    elif e2>=3:\n        res*=4\n    p=3\n    while p*p<=m:\n        if m%p==0:\n            while m%p==0:\n                m//=p\n            res*=2\n        p+=2\n    if m>1:\n        res*=2\n    print(res)', tip: 'x²≡1の解数は中国剰余で各素数べきの解数(奇素数べきは2, 2^kは1/2/4)の積になる。', ins: ['8\n', '1\n', '2\n', '12\n', '15\n', '7\n'] })

t({ lv: 931, concept: '数え上げ: 回転対称な格子の塗り分け', title: '回転で同一視する2色グリッドの数', tags: ['数え上げ', '数論'], io: '正整数 n が1行で与えられます(n×n グリッドを2色で塗る)。', ask: '90度回転で一致するものを同一とみなした塗り分けの数を 1000000007 で割った余りで出力してください。', h1: '4つの回転の不動点を数える。', h2: 'バーンサイドで (f0+f90+f180+f270)/4。', ref: `n=int(input())\nMOD=${MOD}\ntotal_cells=n*n\ndef orbits(rot):\n    seen=[[False]*n for _ in range(n)]\n    cnt=0\n    for i in range(n):\n        for j in range(n):\n            if not seen[i][j]:\n                cnt+=1\n                x,y=i,j\n                for _ in range(4):\n                    seen[x][y]=True\n                    if rot==90:\n                        x,y=y,n-1-x\n                    elif rot==180:\n                        x,y=n-1-x,n-1-y\n                    else:\n                        x,y=n-1-y,x\n    return cnt\no90=orbits(90)\no180=orbits(180)\no270=orbits(270)\nval=(pow(2,total_cells,MOD)+pow(2,o90,MOD)+pow(2,o180,MOD)+pow(2,o270,MOD))%MOD\nprint(val*pow(4,MOD-2,MOD)%MOD)`, tip: 'バーンサイドの補題で4回転の不動点(=各回転の軌道数だけ自由に塗れる2べき)を平均する。', ins: ['1\n', '2\n', '3\n', '4\n', '5\n', '6\n'] })

t({ lv: 932, concept: '数え上げ: 反転も含むブレスレット', title: 'ブレスレットの数(二面体群)', tags: ['数え上げ', '数論'], io: 'n m が空白区切りで与えられます(n ビーズ、m 色)。', ask: '回転と反転で一致するものを同一とみなしたブレスレットの数を出力してください。', h1: '回転分はネックレス公式。', h2: '反転分を加えて 2n で割る(バーンサイド)。', ref: 'n,m=map(int,input().split())\nif n==0:\n    print(1)\nelse:\n    def phi(x):\n        res=x\n        mm=x\n        p=2\n        while p*p<=mm:\n            if mm%p==0:\n                while mm%p==0:\n                    mm//=p\n                res-=res//p\n            p+=1\n        if mm>1:\n            res-=res//mm\n        return res\n    rot=0\n    d=1\n    while d<=n:\n        if n%d==0:\n            rot+=phi(d)*(m**(n//d))\n        d+=1\n    if n%2==1:\n        refl=n*(m**((n+1)//2))\n    else:\n        refl=(n//2)*(m**(n//2))+(n//2)*(m**(n//2+1))\n    print((rot+refl)//(2*n))', tip: '二面体群=回転n通り＋反転n通り。Polya/バーンサイドで全対称の不動点を平均する。', ins: ['3 2\n', '1 3\n', '4 2\n', '2 2\n', '6 2\n', '5 3\n'] })

t({ lv: 933, concept: '数え上げ: 対合の数', title: '対合(自己逆順列)の数', tags: ['数え上げ', 'dp'], io: '非負整数 n が1行で与えられます。', ask: '2乗が恒等になる順列(対合)の数を出力してください。', h1: 'a(n)=a(n-1)+(n-1)·a(n-2)。', h2: 'n番目を固定点にするか1つと交換する。', ref: 'n=int(input())\nif n==0:\n    print(1)\nelse:\n    a=1\n    b=1\n    for i in range(2,n+1):\n        c=b+(i-1)*a\n        a=b\n        b=c\n    print(b)', tip: '対合(自分が逆順列)の数。n番目を固定点にするか、誰かと2-巡回にするかで漸化式が立つ。', ins: ['4\n', '0\n', '1\n', '5\n', '3\n', '10\n'] })

t({ lv: 934, concept: '数論: 2つの平方数の和の表し方の数', title: 'nを2平方数の和で表す方法の数', tags: ['数論'], io: '非負整数 n が1行で与えられます。', ask: 'n=a²+b² (0<=a<=b) と表す方法の組 {a,b} の個数を出力してください。', h1: 'a を 0..√(n/2) まで試す。', h2: 'n-a² が平方数なら1つ数える。', ref: 'import math\nn=int(input())\ncnt=0\na=0\nwhile a*a*2<=n:\n    rem=n-a*a\n    b=int(math.isqrt(rem))\n    if b*b==rem:\n        cnt+=1\n    a+=1\nprint(cnt)', tip: 'a<=bの順序で数えると重複なし。フェルマーの二平方定理(p≡1 mod 4 で表せる)に関連する。', ins: ['25\n', '1\n', '0\n', '50\n', '5\n', '100\n'] })

t({ lv: 935, concept: '数論: 二項係数を割る素数の指数', title: 'C(n,k)を割る素数pの指数', tags: ['数論'], io: 'n k p が空白区切りで与えられます(p は素数, k<=n)。', ask: 'C(n,k) を割り切る p の最大の指数を出力してください。', h1: 'ルジャンドルで v_p(n!),v_p(k!),v_p((n-k)!) を求める。', h2: 'v_p(C(n,k))=v_p(n!)-v_p(k!)-v_p((n-k)!)。', ref: 'n,k,p=map(int,input().split())\ndef vp(n,p):\n    c=0\n    pk=p\n    while pk<=n:\n        c+=n//pk\n        pk*=p\n    return c\nprint(vp(n,p)-vp(k,p)-vp(n-k,p))', tip: 'Kummerの定理: v_p(C(n,k))は p 進法での k+(n-k) の繰り上がり回数に等しい。', ins: ['6 3 2\n', '10 5 2\n', '4 2 3\n', '7 3 7\n', '100 50 5\n', '5 0 2\n'] })

t({ lv: 936, concept: '数論: 原始ピタゴラス数の組数', title: '斜辺がn以下の原始ピタゴラス数の組数', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: '斜辺が n 以下の原始ピタゴラス数 (a,b,c) (a²+b²=c², gcd(a,b)=1) の組数を出力してください。', h1: 'ユークリッドの公式 c=m²+k² を使う。', h2: 'm>k, 互いに素, 偶奇が異なる組を数える。', ref: 'import math\nn=int(input())\ncnt=0\nm=2\nwhile m*m<=n:\n    for k in range(1,m):\n        if (m-k)%2==1 and math.gcd(m,k)==1:\n            c=m*m+k*k\n            if c<=n:\n                cnt+=1\n    m+=1\nprint(cnt)', tip: 'ユークリッドの公式で原始解は m>k, gcd(m,k)=1, m-k 奇数 から一意に生成される。', ins: ['5\n', '4\n', '25\n', '100\n', '1\n', '50\n'] })

t({ lv: 937, concept: 'DP: ちょうどk個の相異なる部分への分割', title: 'k個の相異なる正整数の和で表す方法数', tags: ['dp', '数え上げ'], io: 'n k が空白区切りで与えられます。', ask: 'n を「ちょうど k 個の相異なる正整数」の和で表す方法(順不同)の数を出力してください。', h1: '最小の k 個 1+2+...+k を引く。', h2: '残りを k 個以下の分割に対応させる。', ref: 'n,k=map(int,input().split())\nbase=k*(k+1)//2\nif base>n:\n    print(0)\nelse:\n    r=n-base\n    dp=[0]*(r+1)\n    dp[0]=1\n    for part in range(1,k+1):\n        for x in range(part,r+1):\n            dp[x]+=dp[x-part]\n    print(dp[r])', tip: '1+2+..+k を引いてから「部分がk個以下の分割」に帰着する全単射が鍵。', ins: ['9 3\n', '6 3\n', '5 2\n', '10 1\n', '3 3\n', '15 4\n'] })

t({ lv: 938, concept: '数え上げ: 斜め歩ありの格子経路', title: '東・北・北東に進む格子経路数', tags: ['数え上げ', 'dp'], io: 'm n が空白区切りで与えられます。', ask: '(0,0)から(m,n)へ東・北・北東の3方向で進む格子経路数を出力してください。', h1: 'D(i,j)=D(i-1,j)+D(i,j-1)+D(i-1,j-1)。', h2: '境界は1。', ref: 'm,n=map(int,input().split())\ndp=[[0]*(n+1) for _ in range(m+1)]\nfor i in range(m+1):\n    dp[i][0]=1\nfor j in range(n+1):\n    dp[0][j]=1\nfor i in range(1,m+1):\n    for j in range(1,n+1):\n        dp[i][j]=dp[i-1][j]+dp[i][j-1]+dp[i-1][j-1]\nprint(dp[m][n])', tip: '斜め移動を許した格子経路数(ドゥラノイ数)。3方向からの和で2次元DPする。', ins: ['3 3\n', '0 0\n', '1 1\n', '2 2\n', '3 1\n', '4 4\n'] })

t({ lv: 939, concept: 'DP: k個連続の1を含まない2進列', title: '1がk個連続しない長さnの2進列', tags: ['dp'], io: 'n k が空白区切りで与えられます(k>=1)。', ask: '長さ n の2進文字列で1が k 個以上連続しないものの数を出力してください。', h1: 'dp[末尾の連続1の数]を持つ。', h2: '次が0なら0へ、1なら+1(k未満まで)。', ref: 'n,k=map(int,input().split())\nif n==0:\n    print(1)\nelse:\n    dp=[0]*k\n    dp[0]=1\n    for _ in range(1,n+1):\n        ndp=[0]*k\n        s=sum(dp)\n        ndp[0]=s\n        for j in range(1,k):\n            ndp[j]=dp[j-1]\n        dp=ndp\n    print(sum(dp))', tip: '末尾の連続1の数を状態に持つDP。k=2ならフィボナッチ、kを増やすと一般化フィボナッチになる。', ins: ['3 2\n', '4 2\n', '3 3\n', '1 1\n', '5 1\n', '5 3\n'] })

t({ lv: 940, concept: '数論: ラベル付き木の数', title: 'n頂点のラベル付き木の数', tags: ['数論', '数え上げ'], io: '正整数 n が1行で与えられます。', ask: 'n 個のラベル付き頂点上の異なる木の数を 1000000007 で割った余りで出力してください。', h1: 'ケイリーの公式 n^(n-2)。', h2: 'n=1, n=2 は1。', ref: `n=int(input())\nMOD=${MOD}\nif n==1:\n    print(1)\nelif n==2:\n    print(1)\nelse:\n    print(pow(n,n-2,MOD))`, tip: 'ケイリーの公式: n頂点のラベル付き木は n^(n-2) 個。Prüferシーケンスとの全単射で証明できる。', ins: ['1\n', '2\n', '3\n', '4\n', '5\n', '10\n'] })

t({ lv: 941, concept: '数え上げ: 常にリードする票の並べ方', title: '常にリードを保つ開票順の数', tags: ['数え上げ'], io: 'p q が空白区切りで与えられます(p>=q、候補Aがp票、Bがq票)。', ask: '票を1枚ずつ開票するとき、常にAの得票がBより真に多い並べ方の数を出力してください。', h1: 'バリューの定理を使う。', h2: '(p-q)/(p+q)·C(p+q,p)。', ref: 'import math\np,q=map(int,input().split())\nif p<=q:\n    print(0)\nelse:\n    total=math.comb(p+q,p)\n    print((p-q)*total//(p+q))', tip: 'バリューの定理: 常にリードする並べ方は (p-q)/(p+q)·C(p+q,p)。カタラン数の一般化。', ins: ['3 2\n', '2 2\n', '1 0\n', '5 3\n', '4 1\n', '3 0\n'] })

t({ lv: 942, concept: 'グラフ: オイラー閉路の構成', title: 'オイラー閉路の辞書順最小経路', tags: ['グラフ'], io: '1行目に n m、続く m 行に無向辺 u v が与えられます。', ask: 'オイラー閉路が存在すれば、頂点1から始め辞書順最小の閉路を頂点列(空白区切り)で出力してください。存在しなければ -1。', h1: '全頂点が偶数次数かつ辺が連結か確認。', h2: 'Hierholzer法でスタックを用いて構成する。', ref: 'import sys\nfirst=input().split()\nn=int(first[0])\nm=int(first[1])\nfrom collections import defaultdict,deque\ndeg=[0]*(n+1)\nedges=[]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    edges.append((u,v))\n    deg[u]+=1\n    deg[v]+=1\nokparity=all(deg[i]%2==0 for i in range(1,n+1))\nstart=1\nfor i in range(1,n+1):\n    if deg[i]>0:\n        start=i\n        break\nseen=[False]*(n+1)\ng2=defaultdict(list)\nfor u,v in edges:\n    g2[u].append(v)\n    g2[v].append(u)\nif m>0:\n    seen[start]=True\n    dq=deque([start])\n    while dq:\n        x=dq.popleft()\n        for y in g2[x]:\n            if not seen[y]:\n                seen[y]=True\n                dq.append(y)\nconnected=all(seen[i] for i in range(1,n+1) if deg[i]>0)\nif not okparity or not connected or m==0:\n    print(-1)\nelse:\n    used=[False]*m\n    adjlist=defaultdict(list)\n    for idx,(u,v) in enumerate(edges):\n        adjlist[u].append((v,idx))\n        adjlist[v].append((u,idx))\n    for kk in adjlist:\n        adjlist[kk].sort()\n    ptr=defaultdict(int)\n    stack=[1]\n    circuit=[]\n    while stack:\n        x=stack[-1]\n        advanced=False\n        while ptr[x]<len(adjlist[x]):\n            y,idx=adjlist[x][ptr[x]]\n            ptr[x]+=1\n            if not used[idx]:\n                used[idx]=True\n                stack.append(y)\n                advanced=True\n                break\n        if not advanced:\n            circuit.append(stack.pop())\n    circuit.reverse()\n    print(*circuit)', tip: 'オイラー閉路は「連結＋全偶数次数」で存在し、Hierholzer法(辺を使い切るDFS+スタック)で構成する。', ins: ['3 3\n1 2\n2 3\n1 3\n', '4 4\n1 2\n2 3\n3 4\n4 1\n', '3 2\n1 2\n2 3\n', '1 0\n', '5 6\n1 2\n2 3\n3 1\n3 4\n4 5\n5 3\n', '2 2\n1 2\n1 2\n'] })

t({ lv: 943, concept: 'ゲーム: 逆Nim(ミゼール)', title: 'ミゼールNimの勝者', tags: ['ゲーム'], io: '各山の石の数の列が1行で与えられます。', ask: '通常のNimだが「最後に取った方が負け」(ミゼール)のとき、先手必勝なら First、後手必勝なら Second を出力してください。', h1: '全ての山が1個以下かで場合分け。', h2: '全山1なら山数の偶奇、そうでなければ通常Nim(XOR)と同じ。', ref: 'a=list(map(int,input().split()))\nx=0\nfor v in a:\n    x^=v\nall_small=all(v<=1 for v in a)\nif all_small:\n    cnt=sum(a)\n    print("Second" if cnt%2==1 else "First")\nelse:\n    print("First" if x!=0 else "Second")', tip: 'ミゼールNimは「全山が1個以下」の特殊ケースだけ偶奇判定、それ以外は通常Nim(XOR)と同じ勝敗。', ins: ['1 1 1\n', '1 2 3\n', '1\n', '2 2\n', '1 1\n', '3 4 5\n'] })

t({ lv: 944, concept: 'ゲーム: 複数山の石取りGrundy', title: '複数山の石取りゲームの勝者', tags: ['ゲーム'], io: '1行目に山数 n と取れる個数の種類 m、2行目に取れる個数の集合 S、3行目に各山の石数が与えられます。', ask: '各山から S のいずれかの個数を取れる石取りゲームで、取れない方が負けです。先手必勝なら First、後手必勝なら Second を出力してください。', h1: '1山のGrundy数を mex で前計算。', h2: '全山のGrundy数のXORが非ゼロなら先手必勝。', ref: 'first=input().split()\nn=int(first[0])\nm=int(first[1])\nS=list(map(int,input().split())) if m>0 else []\npiles=list(map(int,input().split()))\nmaxp=max(piles) if piles else 0\ngrundy=[0]*(maxp+1)\nfor i in range(1,maxp+1):\n    reach=set()\n    for s in S:\n        if s<=i:\n            reach.add(grundy[i-s])\n    g=0\n    while g in reach:\n        g+=1\n    grundy[i]=g\nx=0\nfor p in piles:\n    x^=grundy[p]\nprint("First" if x!=0 else "Second")', tip: '独立な複数ゲームの和は各GrundyのXOR(Sprague-Grundy)。1山のGrundyを mex で求めて合成する。', ins: ['2 2\n1 2\n3 4\n', '1 1\n2\n5\n', '3 2\n1 3\n2 2 2\n', '2 1\n1\n1 1\n', '1 2\n2 3\n7\n', '2 2\n2 3\n4 4\n'] })

t({ lv: 945, concept: '数え上げ: n体の非攻撃ビショップ', title: 'n×n盤に置く非攻撃ビショップの数', tags: ['数え上げ', 'dp'], io: '正整数 n が1行で与えられます。', ask: 'n×n のチェス盤に n 個のビショップを互いに利きが当たらないように置く方法の数を出力してください。', h1: '黒マス対角線群と白マス対角線群に分ける。', h2: '各群で「k個置く方法」をDPし、合計 n になる組合せを足す。', ref: 'n=int(input())\nif n==1:\n    print(1)\nelse:\n    diag_black=[]\n    diag_white=[]\n    for d in range(2*n-1):\n        cnt=0\n        for i in range(n):\n            j=d-i\n            if 0<=j<n:\n                cnt+=1\n        if d%2==0:\n            diag_black.append(cnt)\n        else:\n            diag_white.append(cnt)\n    def ways(diags):\n        diags.sort()\n        dp=[1]\n        for c in diags:\n            ndp=[0]*(len(dp)+1)\n            for kk in range(len(dp)):\n                if dp[kk]==0:\n                    continue\n                ndp[kk]+=dp[kk]\n                avail=c-kk\n                if avail>0:\n                    ndp[kk+1]+=dp[kk]*avail\n            dp=ndp\n        return dp\n    wb=ways(diag_black)\n    ww=ways(diag_white)\n    total=0\n    for kk in range(len(wb)):\n        if 0<=n-kk<len(ww):\n            total+=wb[kk]*ww[n-kk]\n    print(total)', tip: '45度回転で黒/白マスのビショップが独立な2つのルーク配置問題になる。各群でk個置く方法をDPして合成。', ins: ['2\n', '1\n', '3\n', '4\n', '5\n', '8\n'] })

t({ lv: 946, concept: '区間DP: 真になる括弧付けの数', title: 'ブール式を真にする括弧付けの数', tags: ['区間DP', 'dp'], io: '真偽値(T/F)と演算子(&|^)が交互に並んだ文字列が1行で与えられます。', ask: '式に括弧を付けて評価したとき結果が真(T)になる括弧付けの数を出力してください。', h1: 'dp_true[i][j], dp_false[i][j] を区間DPで。', h2: '各演算子で左右の真偽の積を分配する。', ref: 's=input()\nvals=s[::2]\nops=s[1::2]\nn=len(vals)\nT=[[0]*n for _ in range(n)]\nF=[[0]*n for _ in range(n)]\nfor i in range(n):\n    if vals[i]=="T":\n        T[i][i]=1\n    else:\n        F[i][i]=1\nfor length in range(2,n+1):\n    for i in range(n-length+1):\n        j=i+length-1\n        for k in range(i,j):\n            op=ops[k]\n            lt=T[i][k]\n            lf=F[i][k]\n            rt=T[k+1][j]\n            rf=F[k+1][j]\n            tot=(lt+lf)*(rt+rf)\n            if op=="&":\n                T[i][j]+=lt*rt\n                F[i][j]+=tot-lt*rt\n            elif op=="|":\n                F[i][j]+=lf*rf\n                T[i][j]+=tot-lf*rf\n            else:\n                T[i][j]+=lt*rf+lf*rt\n                F[i][j]+=lt*rt+lf*rf\nprint(T[0][n-1])', tip: '区間DPで真/偽になる括弧付け数を演算子ごとに左右の真偽の積として分配する。', ins: ['T|F&T\n', 'T\n', 'F\n', 'T^F^F\n', 'T&F|T\n', 'F&F&F\n'] })

t({ lv: 947, concept: 'DP: 卵落としの最小試行回数', title: '卵落とし問題の最小試行回数', tags: ['dp'], io: 'k n が空白区切りで与えられます(k 個の卵、n 階)。', ask: '最悪の場合に「割れる境界の階」を必ず特定するのに必要な最小の試行回数を出力してください。', h1: 'dp[m][k]=m回・k個で判定できる最大階数。', h2: 'dp[m][k]=dp[m-1][k-1]+dp[m-1][k]+1 が n 以上になる最小 m。', ref: 'k,n=map(int,input().split())\nif n==0:\n    print(0)\nelse:\n    dp=[0]*(k+1)\n    m=0\n    while dp[k]<n:\n        m+=1\n        for j in range(k,0,-1):\n            dp[j]=dp[j]+dp[j-1]+1\n    print(m)', tip: 'dp[m][k]=「m回・k個で判別できる最大階数」を増やし、n以上になる最小mを探す逆向きDP。', ins: ['2 6\n', '1 5\n', '2 100\n', '3 14\n', '1 1\n', '10 1000\n'] })

t({ lv: 948, concept: 'DP: 正規表現マッチング', title: 'ドット・スターの正規表現マッチング', tags: ['dp', '文字列'], io: '1行目に文字列 s、2行目にパターン p(. は任意1文字、* は直前文字の0回以上の繰り返し)が与えられます。', ask: 's が p に完全一致するなら yes、しないなら no を出力してください。', h1: 'dp[i][j]=s[:i]とp[:j]が一致するか。', h2: '* は「0回(j-2へ)」または「1回以上(直前と一致でi-1へ)」。', ref: 's=input()\np=input()\nn=len(s)\nm=len(p)\ndp=[[False]*(m+1) for _ in range(n+1)]\ndp[0][0]=True\nfor j in range(1,m+1):\n    if p[j-1]=="*" and j>=2:\n        dp[0][j]=dp[0][j-2]\nfor i in range(1,n+1):\n    for j in range(1,m+1):\n        if p[j-1]=="*":\n            dp[i][j]=dp[i][j-2]\n            if p[j-2]=="." or p[j-2]==s[i-1]:\n                dp[i][j]=dp[i][j] or dp[i-1][j]\n        elif p[j-1]=="." or p[j-1]==s[i-1]:\n            dp[i][j]=dp[i-1][j-1]\nprint("yes" if dp[n][m] else "no")', tip: '* は「0回(j-2)」か「直前と一致して1回以上(i-1)」の2分岐DP。ワイルドカードの*とは意味が異なる。', ins: ['aa\na\n', 'aa\na*\n', 'ab\n.*\n', 'aab\nc*a*b\n', 'mississippi\nmis*is*p*.\n', 'abc\nabc\n'] })

t({ lv: 949, concept: '累積和: k×kの部分正方形の最大和', title: 'k×kの部分正方形の最大和', tags: ['累積和', 'dp'], io: '1行目に R C k、続く R 行に C 個の整数が与えられます(k<=min(R,C))。', ask: 'k×k の部分正方形の要素和の最大値を出力してください。', h1: '2次元累積和を前計算する。', h2: '各左上位置で k×k の和を O(1) で求め最大を取る。', ref: 'first=input().split()\nR=int(first[0])\nC=int(first[1])\nk=int(first[2])\ng=[list(map(int,input().split())) for _ in range(R)]\npre=[[0]*(C+1) for _ in range(R+1)]\nfor i in range(R):\n    for j in range(C):\n        pre[i+1][j+1]=pre[i][j+1]+pre[i+1][j]-pre[i][j]+g[i][j]\nbest=None\nfor i in range(R-k+1):\n    for j in range(C-k+1):\n        s=pre[i+k][j+k]-pre[i][j+k]-pre[i+k][j]+pre[i][j]\n        if best is None or s>best:\n            best=s\nprint(best)', tip: 'k×k窓の和を2次元累積和の包除で O(1) にして全位置を走査する固定窓最大化。', ins: ['3 3 2\n1 2 3\n4 5 6\n7 8 9\n', '1 1 1\n5\n', '2 2 2\n-1 -2\n-3 -4\n', '3 4 2\n1 1 1 1\n1 9 9 1\n1 1 1 1\n', '2 3 1\n1 5 2\n4 3 6\n', '4 4 3\n1 1 1 1\n1 1 1 1\n1 1 1 1\n1 1 1 1\n'] })

export const CATALOG = TASKS
