// 生成タスク 第53波：各レベル2問化フェーズ(8)。lv393〜441 に2問目を追加。
// 幾何/数論/ゲーム/フロー/木DP帯。重複なし・決定的・採点一意。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 393, concept: 'DP: k個選んで和Tにする選び方', title: 'k個選んで和をTにする方法の数', tags: ['DP'], io: '1行目に T k、2行目に整数列が与えられます。', ask: 'ちょうど k 個の要素を選んで(各要素は1回まで)和を T にする選び方の数を出力してください。', h1: 'dp[和][個数] の2次元0/1ナップサック。', h2: '要素ごとに和と個数を降順に更新。', ref: 't,k=map(int,input().split())\na=list(map(int,input().split()))\ndp=[[0]*(k+1) for _ in range(t+1)]\ndp[0][0]=1\nfor x in a:\n    for v in range(t,x-1,-1):\n        for j in range(k,0,-1):\n            dp[v][j]+=dp[v-x][j-1]\nprint(dp[t][k])', tip: '部分集合和に「選んだ個数」の次元を足す拡張。0/1なので降順走査で上書きを防ぐのは1次元のときと同じ。', ins: ['5 2\n1 2 3 4\n', '6 3\n1 2 3 4\n', '0 0\n1 2\n', '4 2\n2 2 2\n', '10 1\n3 10 5\n', '7 2\n1 2 3\n'] })

t({ lv: 394, concept: 'DP: コピー&ペーストの最小操作', title: '文字Aをn個にする最小操作回数', tags: ['DP', '数論'], io: '正整数 n が1行で与えられます。', ask: '画面に A が1個ある。操作は「全選択コピー」と「貼り付け」のみ。ちょうど n 個の A にする最小操作回数を出力してください。', h1: 'k倍に増やすには「コピー1回+貼り付けk-1回」=k回かかる。', h2: '答えは n の素因数(重複込み)の総和。', ref: 'n=int(input())\nops=0\nf=2\nwhile n>1:\n    while n%f==0:\n        ops+=f\n        n//=f\n    f+=1\nprint(ops)', tip: '増殖操作の合成は積になるので、操作回数の和を最小化するには合成数を素因数に割るのが常に得。素因数分解が隠れた答え。', ins: ['3\n', '1\n', '6\n', '9\n', '12\n', '35\n'] })

t({ lv: 395, concept: 'DP: 長さk以下の塊分割で和最大', title: '長さk以下の塊に分けて和を最大化', tags: ['DP'], io: '1行目に k、2行目に正整数列が与えられます。', ask: '列を長さ k 以下の連続した塊に分割し、各塊の値を「塊内の最大値×塊の長さ」とするとき、全塊の値の合計の最大値を出力してください。', h1: 'dp[i]=先頭i要素の最大値。', h2: '最後の塊の長さ L=1..k を試し、塊内最大を更新しながら遷移。', ref: 'k=int(input())\na=list(map(int,input().split()))\nn=len(a)\ndp=[0]*(n+1)\nfor i in range(1,n+1):\n    mx=0\n    for L in range(1,min(k,i)+1):\n        if a[i-L]>mx:\n            mx=a[i-L]\n        v=dp[i-L]+mx*L\n        if v>dp[i]:\n            dp[i]=v\nprint(dp[n])', tip: '「最後の塊を全部試す」DPの典型。塊内最大を後ろから伸ばしながら更新すると O(nk) で済む。', ins: ['3\n1 15 7 9 2 5 10\n', '1\n1 2 3\n', '2\n1 4 1 5 7 3 6 1 9 9 3\n', '4\n1\n', '2\n5 5\n', '3\n2 1 4\n'] })

t({ lv: 396, concept: '数学: 桁和が桁数の倍数の数の個数', title: '桁和が桁数で割り切れる数', tags: ['数学'], io: '正整数 N が1行で与えられます。', ask: '1 以上 N 以下で、桁の和が桁数で割り切れる数の個数を出力してください。', h1: '各数の桁和と桁数を求める。', h2: '余りが0のものを数える。', ref: 'n=int(input())\ncnt=0\nfor x in range(1,n+1):\n    s=str(x)\n    ds=sum(int(c) for c in s)\n    if ds%len(s)==0:\n        cnt+=1\nprint(cnt)', tip: '1桁の数は必ず条件を満たす。大きなNでは「桁数・桁和・余り」を状態に持つ桁DPに発展する。', ins: ['20\n', '9\n', '100\n', '1\n', '50\n', '11\n'] })

t({ lv: 397, concept: '貪欲: 重量制限ボートの最小隻数', title: '2人乗りボートの最小数', tags: ['貪欲', '二点法'], io: '1行目に重量制限 W、2行目に人々の体重が与えられます(各自W以下)。', ask: '1隻に最大2人まで、合計 W 以下で乗せるとき、全員を運ぶ最小のボート数を出力してください。', h1: 'ソートして最軽と最重を組ませてみる。', h2: '乗れなければ最重は1人で乗せる。両端から狭める。', ref: 'limit=int(input())\na=sorted(map(int,input().split()))\ni,j=0,len(a)-1\nboats=0\nwhile i<=j:\n    if a[i]+a[j]<=limit:\n        i+=1\n    j-=1\n    boats+=1\nprint(boats)', tip: '「最重の相棒になれるのは最軽だけ」という交換論法で両端貪欲が最適になる。3人乗り以上になると一気に難しくなる。', ins: ['3\n1 2\n', '3\n3 2 2 1\n', '5\n3 5 3 4\n', '10\n5 5\n', '4\n4\n', '6\n1 2 3 4 5\n'] })

t({ lv: 398, concept: 'ヒープ: 締切までに受けられる最大講座数', title: '期限内に修了できる最大コース数', tags: ['ヒープ', '貪欲'], io: '1行目にコース数 n、続く n 行に「所要日数 d 締切日 e」が与えられます。', ask: '時刻0から順にコースを受ける(同時受講不可)とき、各コースを締切までに終えられるように選べる最大コース数を出力してください。', h1: '締切順に仮で受講し、所要日数をヒープに入れる。', h2: '締切を超えたら、これまでで最長のコースを捨てる(後悔貪欲)。', ref: 'import heapq\nn=int(input())\ncs=[tuple(map(int,input().split())) for _ in range(n)]\ncs.sort(key=lambda x:x[1])\nh=[]\ntime=0\nfor d,e in cs:\n    heapq.heappush(h,-d)\n    time+=d\n    if time>e:\n        time+=heapq.heappop(h)\nprint(len(h))', tip: '一度選んだものを「最悪の1つだけ取り消す」後悔(regret)貪欲。締切ソート+最大ヒープの組合せはスケジューリングの強力な型。', ins: ['4\n100 200\n200 1300\n1000 1250\n2000 3200\n', '1\n1 2\n', '1\n3 2\n', '2\n5 5\n5 5\n', '3\n2 2\n2 4\n2 6\n', '3\n3 3\n3 4\n1 4\n'] })

t({ lv: 399, concept: 'ビット: k番目の部分集合XOR', title: 'k番目に小さい部分集合XOR', tags: ['bit演算'], io: '1行目に k、2行目に非負整数列が与えられます。', ask: '部分集合(空集合含む)のXORとして作れる相異なる値のうち、小さい方から k 番目(1始まり、kは種類数以下)を出力してください。', h1: 'XOR基底を作ると、作れる値は基底の組合せで尽きる。', h2: '基底を簡約(掃き出し)すると、k-1 のビットがそのまま選択になる。', ref: 'k=int(input())\na=list(map(int,input().split()))\nbasis=[0]*60\nfor x in a:\n    for i in range(59,-1,-1):\n        if not x>>i&1:\n            continue\n        if basis[i]==0:\n            basis[i]=x\n            break\n        x^=basis[i]\nfor i in range(60):\n    if basis[i]:\n        for j in range(i+1,60):\n            if basis[j]>>i&1:\n                basis[j]^=basis[i]\nbs=[basis[i] for i in range(60) if basis[i]]\nans=0\nk-=1\nfor idx,b in enumerate(bs):\n    if k>>idx&1:\n        ans^=b\nprint(ans)', tip: '完全簡約した基底は「各ビット位置の主元が他の基底に現れない」ので、基底の選び方と値の大小が単調に対応する。', ins: ['1\n1 2\n', '4\n1 2\n', '3\n5 5 2\n', '2\n7\n', '8\n1 2 4\n', '4\n3 1\n'] })

t({ lv: 400, concept: '文字列: 接頭辞関係にあるペア数', title: '接頭辞になっている単語ペアの数', tags: ['文字列'], io: '相異なるとは限らない単語列が1行で空白区切りで与えられます。', ask: '単語の組 (i,j) (i≠j) で、i 番目の単語が j 番目の単語の真の接頭辞(より短く先頭一致)になっているものの個数を出力してください。', h1: '全ペアを startswith で確認。', h2: '長さが厳密に短いことも条件。', ref: 'ws=input().split()\nn=len(ws)\ncnt=0\nfor i in range(n):\n    for j in range(n):\n        if i!=j and len(ws[i])<len(ws[j]) and ws[j].startswith(ws[i]):\n            cnt+=1\nprint(cnt)', tip: '大量の単語ならトライ木に挿入しながら「通過したノードにある単語数」を数えるとO(総文字数)になる。オートコンプリートの基礎。', ins: ['a ab abc\n', 'x y\n', 'ab a b\n', 'a a\n', 'p pq pr p\n', 'do dog door doors\n'] })

t({ lv: 401, concept: 'データ構造: 区間反転と1の個数', title: '区間の0/1反転と1のカウント', tags: ['データ構造'], io: '1行目に n q、2行目に長さnの0/1文字列、続く q 行に「1 l r」(区間を反転)または「2 l r」(1の数を質問)が与えられます。', ask: '各「2 l r」に対し区間内の1の個数を1行ずつ出力してください。', h1: '小さい入力なら素直に反転してよい。', h2: '大きい入力は遅延セグ木で「反転フラグ」と「1の数=長さ-1の数」を管理。', ref: 'n,q=map(int,input().split())\na=list(map(int,input()))\nfor _ in range(q):\n    t,l,r=map(int,input().split())\n    if t==1:\n        for i in range(l-1,r):\n            a[i]^=1\n    else:\n        print(sum(a[l-1:r]))', tip: '反転の遅延伝播は「2回で打ち消す」XOR型。区間代入や加算と違い、適用順に依らない可換な作用なので扱いやすい。', ins: ['5 3\n01011\n2 1 5\n1 2 4\n2 1 5\n', '3 2\n111\n1 1 3\n2 1 3\n', '4 2\n0000\n1 1 2\n2 1 4\n', '2 1\n10\n2 2 2\n', '6 3\n101010\n1 1 6\n2 1 3\n2 4 6\n', '1 2\n1\n1 1 1\n2 1 1\n'] })

t({ lv: 402, concept: 'データ構造: 逐次追加でのmex', title: '値を追加するたびのmex', tags: ['データ構造'], io: '非負整数の列が1行で空白区切りで与えられます。', ask: '値を先頭から順に集合へ追加し、そのたびに mex(集合に無い最小の非負整数)を空白区切りで出力してください。', h1: 'mexは単調に増えるしかない。', h2: '追加のたびに「mexが集合にある間だけ」前に進める(全体でO(n))。', ref: 'a=list(map(int,input().split()))\nseen=set()\nmex=0\nout=[]\nfor x in a:\n    seen.add(x)\n    while mex in seen:\n        mex+=1\n    out.append(mex)\nprint(*out)', tip: 'mexのポインタは戻らないので while で進めても全体で線形時間(償却解析)。Grundy数の計算や割当問題で頻出の道具。', ins: ['0 1 2\n', '1 0 5 2\n', '3 3 3\n', '0\n', '2 1 0\n', '0 2 4 1 3\n'] })

t({ lv: 403, concept: 'データ構造: 区間内でK以下の個数', title: '区間にあるK以下の要素数', tags: ['データ構造'], io: '1行目に n q K、2行目に整数列、続く q 行に区間 l r が与えられます。', ask: '各区間 [l,r] に含まれる K 以下の要素の個数を1行ずつ出力してください。', h1: '小さい入力なら区間を見て数える。', h2: '大きい入力は平方分割(ブロック内をソートして二分探索)やマージソート木で。', ref: 'n,q,k=map(int,input().split())\na=list(map(int,input().split()))\nfor _ in range(q):\n    l,r=map(int,input().split())\n    print(sum(1 for v in a[l-1:r] if v<=k))', tip: 'ブロック内をソートしておく平方分割では、端数ブロックは素朴に・完全ブロックは bisect で数えて O((√n)log n)/クエリ。', ins: ['5 2 3\n1 4 2 5 3\n1 5\n2 4\n', '3 1 0\n1 0 0\n1 3\n', '4 2 10\n1 2 3 4\n1 2\n3 4\n', '2 1 1\n2 2\n1 2\n', '6 2 2\n2 2 2 3 1 4\n1 6\n4 6\n', '1 1 5\n5\n1 1\n'] })

t({ lv: 404, concept: '幾何: 多角形の向きの判定', title: '多角形は反時計回りか', tags: ['幾何'], io: '1行目に頂点数 n、続く n 行に単純多角形の頂点座標(順に並ぶ)が与えられます。', ask: '頂点の並びが反時計回りなら ccw、時計回りなら cw を出力してください。', h1: '符号付き面積(靴ひも公式)の符号を見る。', h2: 'Σ(x_i·y_{i+1} - x_{i+1}·y_i) が正なら反時計回り。', ref: 'n=int(input())\npts=[tuple(map(int,input().split())) for _ in range(n)]\ns=0\nfor i in range(n):\n    x1,y1=pts[i]\n    x2,y2=pts[(i+1)%n]\n    s+=x1*y2-x2*y1\nprint("ccw" if s>0 else "cw")', tip: '靴ひも公式は面積だけでなく向きも教えてくれる。凸包や多角形アルゴリズムの前処理で向きの正規化に使う。', ins: ['3\n0 0\n1 0\n0 1\n', '3\n0 0\n0 1\n1 0\n', '4\n0 0\n2 0\n2 2\n0 2\n', '4\n0 0\n0 2\n2 2\n2 0\n', '3\n0 0\n4 0\n2 3\n', '5\n0 0\n3 0\n4 2\n2 4\n-1 2\n'] })

t({ lv: 405, concept: '幾何: 点が線分上にあるか', title: '点は線分の上に乗っているか', tags: ['幾何'], io: 'x1 y1 x2 y2 px py が1行で与えられます(線分の両端と点、全て整数)。', ask: '点 (px,py) が線分上(端点含む)にあるなら yes、なければ no を出力してください。', h1: 'まず外積が0(一直線上)を確認。', h2: 'さらに座標が両端の範囲内にあること。', ref: 'x1,y1,x2,y2,px,py=map(int,input().split())\ncross=(x2-x1)*(py-y1)-(y2-y1)*(px-x1)\non=cross==0 and min(x1,x2)<=px<=max(x1,x2) and min(y1,y2)<=py<=max(y1,y2)\nprint("yes" if on else "no")', tip: '「共線性(外積=0)」と「範囲(バウンディングボックス)」の2条件に分けるのが整数幾何の基本。浮動小数を使わず厳密に判定できる。', ins: ['0 0 4 4 2 2\n', '0 0 4 4 5 5\n', '0 0 4 0 2 1\n', '0 0 4 0 4 0\n', '1 1 1 5 1 3\n', '0 0 2 2 1 0\n'] })

t({ lv: 406, concept: '幾何: 凸包の内部にある点の数', title: '凸包の厳密に内側にある点の数', tags: ['幾何'], io: '1行目に点数 n、続く n 行に相異なる点の座標が与えられます。', ask: '点集合の凸包の厳密な内部(境界上を除く)にある点の個数を出力してください。', h1: 'アンドリューの単調鎖で凸包を作る。', h2: '各点について全ての辺の外積が正(厳密に左側)なら内部。', ref: 'n=int(input())\npts=[tuple(map(int,input().split())) for _ in range(n)]\nP=sorted(set(pts))\ndef cross(o,a,b):\n    return (a[0]-o[0])*(b[1]-o[1])-(a[1]-o[1])*(b[0]-o[0])\ndef hull(P):\n    if len(P)<=2:\n        return P\n    lo=[]\n    for p in P:\n        while len(lo)>=2 and cross(lo[-2],lo[-1],p)<=0:\n            lo.pop()\n        lo.append(p)\n    up=[]\n    for p in reversed(P):\n        while len(up)>=2 and cross(up[-2],up[-1],p)<=0:\n            up.pop()\n        up.append(p)\n    return lo[:-1]+up[:-1]\nH=hull(P)\ndef inside(q):\n    m=len(H)\n    if m<3:\n        return False\n    for i in range(m):\n        if cross(H[i],H[(i+1)%m],q)<=0:\n            return False\n    return True\nprint(sum(1 for q in pts if inside(q)))', tip: '凸多角形の内外判定は「全辺に対して同じ側」を見るだけでよい(一般多角形の交差数法より単純)。境界を含むかは不等号の等号で制御。', ins: ['4\n0 0\n4 0\n0 4\n1 1\n', '3\n0 0\n1 0\n0 1\n', '5\n0 0\n4 0\n4 4\n0 4\n2 2\n', '5\n0 0\n4 0\n4 4\n0 4\n2 0\n', '6\n0 0\n5 0\n5 5\n0 5\n1 2\n3 3\n', '4\n0 0\n2 0\n4 0\n1 1\n'] })

t({ lv: 407, concept: '幾何: 凸包の層の数', title: '凸包の層はいくつあるか', tags: ['幾何'], io: '1行目に点数 n、続く n 行に相異なる点の座標が与えられます。', ask: '「凸包の境界上にある点を全て取り除く」操作を、点が無くなるまで繰り返します。操作を行う回数(凸包の層の数)を出力してください。', h1: '凸包を作り、厳密に内部の点だけを残す。', h2: '全点が一直線上なら全て境界上、つまり1回で消える。残った点で繰り返す。', ref: 'n=int(input())\npts=[tuple(map(int,input().split())) for _ in range(n)]\ndef cross(o,a,b):\n    return (a[0]-o[0])*(b[1]-o[1])-(a[1]-o[1])*(b[0]-o[0])\ndef hull(P):\n    P=sorted(P)\n    if len(P)<=2:\n        return P\n    lo=[]\n    for p in P:\n        while len(lo)>=2 and cross(lo[-2],lo[-1],p)<=0:\n            lo.pop()\n        lo.append(p)\n    up=[]\n    for p in reversed(P):\n        while len(up)>=2 and cross(up[-2],up[-1],p)<=0:\n            up.pop()\n        up.append(p)\n    return lo[:-1]+up[:-1]\nlayers=0\nwhile pts:\n    layers+=1\n    H=hull(pts)\n    if len(H)<3:\n        pts=[]\n    else:\n        m=len(H)\n        pts=[q for q in pts if all(cross(H[i],H[(i+1)%m],q)>0 for i in range(m))]\nprint(layers)', tip: '玉ねぎの皮むき(onion peeling)と呼ばれる分解。層の数は点集合の「深さ」を表し、統計のデータ深度や外れ値検出にも使われる。', ins: ['5\n0 0\n4 0\n4 4\n0 4\n2 2\n', '3\n0 0\n1 0\n0 1\n', '4\n0 0\n1 1\n2 2\n3 3\n', '8\n0 0\n4 0\n4 4\n0 4\n1 1\n3 1\n3 3\n1 3\n', '9\n0 0\n4 0\n4 4\n0 4\n1 1\n3 1\n3 3\n1 3\n2 2\n', '1\n5 5\n'] })

t({ lv: 408, concept: '幾何: 多角形の周上の格子点数', title: '多角形の辺上にある格子点の数', tags: ['幾何', '数論'], io: '1行目に頂点数 n、続く n 行に格子点を頂点とする多角形の座標が与えられます。', ask: '多角形の周(辺)上にある格子点の総数を出力してください(頂点も数える)。', h1: '1辺 (dx,dy) 上の格子点は端点を除いて gcd(|dx|,|dy|)-1 個。', h2: '全辺の gcd を合計すると頂点込みの周上点数になる。', ref: 'import math\nn=int(input())\npts=[tuple(map(int,input().split())) for _ in range(n)]\nb=0\nfor i in range(n):\n    x1,y1=pts[i]\n    x2,y2=pts[(i+1)%n]\n    b+=math.gcd(abs(x2-x1),abs(y2-y1))\nprint(b)', tip: '辺上の格子点数=gcd は「ベクトルを何等分できるか」そのもの。ピックの定理 A=i+b/2-1 の b を与える部品になる。', ins: ['3\n0 0\n4 0\n0 4\n', '4\n0 0\n2 0\n2 2\n0 2\n', '3\n0 0\n1 0\n0 1\n', '3\n0 0\n6 0\n0 3\n', '4\n0 0\n3 0\n3 1\n0 1\n', '3\n0 0\n2 1\n1 2\n'] })

t({ lv: 409, concept: '数論: 二項係数の部分和', title: 'C(n,0)からC(n,m)までの和', tags: ['数学'], io: 'n m が空白区切りで1行で与えられます (0≤m≤n)。', ask: '二項係数の部分和 C(n,0)+C(n,1)+…+C(n,m) を出力してください。', h1: 'C(n,k+1)=C(n,k)·(n-k)/(k+1) で順に作る。', h2: '足しながら更新する。', ref: 'n,m=map(int,input().split())\nc=1\ns=0\nfor k in range(m+1):\n    s+=c\n    c=c*(n-k)//(k+1)\nprint(s)', tip: '二項係数の部分和には閉じた式が無い(超幾何的に簡約不能)ことが知られている。隣接項の比で逐次計算するのが正攻法。', ins: ['5 2\n', '4 4\n', '10 0\n', '6 3\n', '8 1\n', '20 10\n'] })

t({ lv: 410, concept: '幾何: 格子上の正方形の総数', title: '格子点が作る正方形の総数', tags: ['幾何', '数学'], io: '正整数 n が1行で与えられます。', ask: 'n×n の格子点 (座標 0〜n-1) を頂点とする正方形(軸に平行なものも斜めのものも)の総数を出力してください。', h1: '辺ベクトル (a,b) (a≥1, b≥0) で正方形が一意に決まる。', h2: 'その正方形の外接箱は (a+b)×(a+b)。置ける位置は (n-a-b)² 通り。', ref: 'n=int(input())\ncnt=0\nfor a in range(1,n):\n    for b in range(0,n-a):\n        cnt+=(n-a-b)**2\nprint(cnt)', tip: '斜めの正方形も「外接する軸平行正方形」と「傾きベクトル」の組で数えると重複なく列挙できる。総数は n²(n²-1)/12 の閉形式になる。', ins: ['2\n', '3\n', '1\n', '4\n', '5\n', '10\n'] })

t({ lv: 411, concept: '数論: 算術数の個数', title: '約数の平均が整数の数を数える', tags: ['数論'], io: '正整数 N が1行で与えられます。', ask: '1 以上 N 以下で、全約数の平均(約数和÷約数個数)が整数になる数(算術数)の個数を出力してください。', h1: '各数の約数和と約数個数を√xまでの試し割りで求める。', h2: '約数和 % 約数個数 == 0 を数える。', ref: 'n=int(input())\ncnt=0\nfor x in range(1,n+1):\n    s=0\n    d=0\n    i=1\n    while i*i<=x:\n        if x%i==0:\n            s+=i\n            d+=1\n            if i!=x//i:\n                s+=x//i\n                d+=1\n        i+=1\n    if s%d==0:\n        cnt+=1\nprint(cnt)', tip: '算術数(1,3,5,6,7,11,…)は密度1を持つ=ほとんどの数が算術数になることが証明されている。奇素数は全て算術数。', ins: ['10\n', '1\n', '20\n', '50\n', '100\n', '2\n'] })

t({ lv: 412, concept: '数論: 分数の連分数展開', title: '分数を連分数に展開する', tags: ['数論'], io: '正整数 p q が空白区切りで1行で与えられます。', ask: 'p/q の連分数展開 [a0; a1, a2, …] の係数を空白区切りで出力してください(ユークリッドの互除法の商の列)。', h1: '整数部分を取り出して逆数を繰り返す。', h2: 'p//q を記録し (p,q)←(q,p%q)。q=0 で終了。', ref: 'p,q=map(int,input().split())\nres=[]\nwhile q:\n    res.append(p//q)\n    p,q=q,p%q\nprint(*res)', tip: '連分数の係数列=互除法の商の列。355/113→[3;7,16] は円周率の名高い近似。係数を途中で打ち切ると最良有理近似が得られる。', ins: ['7 3\n', '355 113\n', '1 1\n', '10 4\n', '0 1\n', '13 11\n'] })

t({ lv: 413, concept: '木: パス上の最大頂点番号', title: '2頂点を結ぶ道の最大番号', tags: ['グラフ'], io: '1行目に頂点数 n、続く n-1 行に木の辺、最後の行に2頂点 s t が与えられます。', ask: 's から t への(木ではただ1つの)パス上に現れる頂点番号の最大値を出力してください。', h1: 'BFS/DFSで親をたどる配列を作る。', h2: 't から親を遡って s までの頂点を集める。', ref: 'from collections import deque\nn=int(input())\ng=[[] for _ in range(n+1)]\nfor _ in range(n-1):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\ns,t=map(int,input().split())\npar=[0]*(n+1)\nseen=[False]*(n+1)\nseen[s]=True\nq=deque([s])\nwhile q:\n    x=q.popleft()\n    for y in g[x]:\n        if not seen[y]:\n            seen[y]=True\n            par[y]=x\n            q.append(y)\nmx=t\nx=t\nwhile x!=s:\n    x=par[x]\n    if x>mx:\n        mx=x\nprint(mx)', tip: '木のパス復元は「親ポインタを遡る」だけ。パス上の集約(最大・和・XOR)はすべてこの形で書ける。大規模ならLCA+前計算へ。', ins: ['5\n1 2\n2 3\n3 4\n3 5\n4 5\n', '3\n1 2\n2 3\n1 3\n', '2\n1 2\n1 2\n', '6\n1 6\n6 3\n3 2\n2 4\n4 5\n5 1\n', '4\n1 2\n1 3\n1 4\n2 3\n', '7\n1 2\n2 3\n2 4\n1 5\n5 6\n6 7\n3 7\n'] })

t({ lv: 414, concept: '木: 重み付き半径', title: '重み付きの木の半径', tags: ['グラフ'], io: '1行目に頂点数 n、続く n-1 行に辺 u v w (重み)が与えられます。', ask: '各頂点の離心数(最も遠い頂点への重み付き距離)のうち最小の値(半径)を出力してください。', h1: '各頂点からDFS/BFSで重み付き距離を求める。', h2: '各頂点の最大距離のうち最小を取る。', ref: 'n=int(input())\ng=[[] for _ in range(n+1)]\nfor _ in range(n-1):\n    u,v,w=map(int,input().split())\n    g[u].append((v,w))\n    g[v].append((u,w))\nbest=None\nfor s in range(1,n+1):\n    dist=[-1]*(n+1)\n    dist[s]=0\n    st=[s]\n    while st:\n        x=st.pop()\n        for y,w in g[x]:\n            if dist[y]<0:\n                dist[y]=dist[x]+w\n                st.append(y)\n    ecc=max(dist[1:n+1])\n    if best is None or ecc<best:\n        best=ecc\nprint(best)', tip: '半径を実現する頂点(中心)は直径パスの中点付近にある。重み付きでは中心が「辺の途中」に落ちることもある(頂点制約なら端の頂点)。', ins: ['3\n1 2 5\n2 3 3\n', '2\n1 2 7\n', '4\n1 2 1\n1 3 1\n1 4 1\n', '5\n1 2 2\n2 3 2\n3 4 2\n4 5 2\n', '1\n', '6\n1 2 3\n2 3 1\n3 4 4\n2 5 2\n5 6 5\n'] })

t({ lv: 415, concept: '関数グラフ: 閉路に入るまでの距離', title: '関数を辿って閉路に入るまでの歩数', tags: ['グラフ'], io: '1行目に n と開始点 s、2行目に写像 f(1) f(2) … f(n) が与えられます。', ask: 's から f を繰り返し適用するとき、初めて閉路上の頂点に到達するまでの歩数(s が既に閉路上なら0)を出力してください。', h1: '訪問順を記録しながら進む。', h2: '初めて再訪した頂点が閉路の入口。その初訪問時刻が答え。', ref: 'n,s=map(int,input().split())\nf=list(map(int,input().split()))\npos={}\nx=s\ni=0\nwhile x not in pos:\n    pos[x]=i\n    x=f[x-1]\n    i+=1\nprint(pos[x])', tip: 'ρ(ロー)の形の「尻尾」の長さ。フロイドの循環検出ではμと呼ばれ、周期λと並ぶ基本量。擬似乱数の解析にも現れる。', ins: ['5 1\n2 3 4 5 3\n', '3 1\n2 3 1\n', '4 2\n2 2 2 2\n', '6 1\n2 3 4 2 6 5\n', '1 1\n1\n', '7 7\n2 3 1 5 6 4 1\n'] })

t({ lv: 416, concept: '幾何: マンハッタン距離の総和', title: '全ペアのマンハッタン距離の合計', tags: ['幾何', 'ソート'], io: '1行目に点数 n、続く n 行に座標 x y が与えられます。', ask: '全ての点対のマンハッタン距離の総和を出力してください。', h1: 'x成分とy成分は独立に足せる。', h2: '各軸でソートし、Σ(v_i·i - 接頭和) で O(n log n)。', ref: 'n=int(input())\nxs=[]\nys=[]\nfor _ in range(n):\n    x,y=map(int,input().split())\n    xs.append(x)\n    ys.append(y)\ndef f(a):\n    a.sort()\n    s=0\n    pre=0\n    for i,v in enumerate(a):\n        s+=v*i-pre\n        pre+=v\n    return s\nprint(f(xs)+f(ys))', tip: 'L1距離は座標ごとに分離できるのが最大の特徴。ソート後の「自分より左の個数×自分-接頭和」は距離総和の万能パターン。', ins: ['3\n0 0\n1 1\n2 2\n', '2\n0 0\n3 4\n', '1\n5 5\n', '4\n0 0\n0 1\n1 0\n1 1\n', '3\n-1 0\n0 0\n1 0\n', '2\n2 3\n2 3\n'] })

t({ lv: 417, concept: 'グラフ: 1頂点除去後の最大成分数', title: '1頂点を消して成分数を最大に', tags: ['グラフ'], io: '1行目に n m (n≥2)、続く m 行に無向辺が与えられます。', ask: 'ちょうど1頂点(とその接続辺)を取り除いたときの連結成分数の最大値を出力してください。', h1: '各頂点を除いてみて成分数を数える。', h2: 'Union-FindかBFSで残りの成分数を計算。', ref: 'n,m=map(int,input().split())\nedges=[]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    edges.append((u,v))\nbest=0\nfor rm in range(1,n+1):\n    par=list(range(n+1))\n    def find(x):\n        while par[x]!=x:\n            par[x]=par[par[x]]\n            x=par[x]\n        return x\n    for u,v in edges:\n        if u!=rm and v!=rm:\n            ru,rv=find(u),find(v)\n            if ru!=rv:\n                par[ru]=rv\n    comps=len(set(find(v) for v in range(1,n+1) if v!=rm))\n    if comps>best:\n        best=comps\nprint(best)', tip: '関節点の中でも「除くと最も多くの成分に割れる」頂点が最重要拠点。木なら次数最大の頂点(星の中心は n-1 成分に割る)。', ins: ['5 4\n1 2\n2 3\n2 4\n4 5\n', '3 3\n1 2\n2 3\n1 3\n', '4 3\n1 2\n2 3\n3 4\n', '2 1\n1 2\n', '7 6\n1 2\n1 3\n1 4\n1 5\n1 6\n1 7\n', '6 6\n1 2\n2 3\n3 1\n4 5\n5 6\n6 4\n'] })

t({ lv: 418, concept: 'グラフ: s-t切断辺の数', title: '取り除くとs-tが切れる辺の数', tags: ['グラフ', 'BFS'], io: '1行目に n m s t、続く m 行に無向辺が与えられます(sとtは連結)。', ask: 'その1辺を取り除くと s から t へ到達できなくなる辺の本数を出力してください。', h1: '各辺を1本ずつ除いて到達性を確認する。', h2: '答えはs-tパス上の橋の数に等しい(橋でも別経路があれば対象外)。', ref: 'from collections import deque\nn,m,s,t=map(int,input().split())\nedges=[]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    edges.append((u,v))\ndef conn(skip):\n    g=[[] for _ in range(n+1)]\n    for i,(u,v) in enumerate(edges):\n        if i!=skip:\n            g[u].append(v)\n            g[v].append(u)\n    seen=[False]*(n+1)\n    seen[s]=True\n    q=deque([s])\n    while q:\n        x=q.popleft()\n        for y in g[x]:\n            if not seen[y]:\n                seen[y]=True\n                q.append(y)\n    return seen[t]\nprint(sum(1 for i in range(m) if not conn(i)))', tip: '「全部の橋」ではなく「s-t間の橋」だけが答えになるのがポイント。橋木(block-cut tree)上のs-tパスに乗る橋と一致する。', ins: ['4 3 1 4\n1 2\n2 3\n3 4\n', '4 4 1 4\n1 2\n2 4\n1 3\n3 4\n', '5 5 1 5\n1 2\n2 3\n3 4\n4 5\n2 4\n', '2 1 1 2\n1 2\n', '3 3 1 3\n1 2\n2 3\n1 3\n', '6 6 1 6\n1 2\n2 3\n3 6\n2 4\n4 5\n5 3\n'] })

t({ lv: 419, concept: 'グラフ: 距離2の頂点数の最大', title: '友達の友達が最も多い人', tags: ['グラフ', 'BFS'], io: '1行目に n m、続く m 行に無向辺が与えられます。', ask: '各頂点について「距離がちょうど2の頂点数」を数え、その最大値を出力してください。', h1: '各頂点からBFSして距離を求める。', h2: 'dist==2 を数えて最大を取る。', ref: 'from collections import deque\nn,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\nbest=0\nfor s in range(1,n+1):\n    dist=[-1]*(n+1)\n    dist[s]=0\n    q=deque([s])\n    while q:\n        x=q.popleft()\n        for y in g[x]:\n            if dist[y]<0:\n                dist[y]=dist[x]+1\n                q.append(y)\n    c=sum(1 for v in range(1,n+1) if dist[v]==2)\n    if c>best:\n        best=c\nprint(best)', tip: 'SNSの「知り合いかも」は距離2の頂点集合。隣接の隣接から直接の隣接と自分を引く集合演算でも数えられる。', ins: ['5 4\n1 2\n2 3\n2 4\n2 5\n', '3 2\n1 2\n2 3\n', '4 6\n1 2\n1 3\n1 4\n2 3\n2 4\n3 4\n', '2 1\n1 2\n', '6 5\n1 2\n2 3\n3 4\n4 5\n5 6\n', '7 6\n1 2\n1 3\n2 4\n2 5\n3 6\n3 7\n'] })

t({ lv: 420, concept: 'フロー: 容量つき割当の最大数', title: '受け持ち上限つきの仕事割当', tags: ['グラフ', 'フロー'], io: '1行目に 作業者数 n 仕事数 m 適合ペア数 e、2行目に各作業者の上限、続く e 行に「作業者 u が仕事 v をできる」ペアが与えられます。', ask: '各仕事は1人まで、各作業者は自分の上限まで受けられるとき、割り当てられる仕事数の最大を出力してください。', h1: '源→作業者(容量=上限)、作業者→仕事(1)、仕事→汇(1)のフロー。', h2: '増加道を繰り返し流す(Edmonds-Karp)。', ref: 'from collections import deque,defaultdict\nn,m,e=map(int,input().split())\ncaps=list(map(int,input().split()))\ncap=defaultdict(int)\nadj=defaultdict(list)\ndef add(u,v,c):\n    if v not in adj[u]:\n        adj[u].append(v)\n    if u not in adj[v]:\n        adj[v].append(u)\n    cap[(u,v)]+=c\nS=0\nT=n+m+1\nfor i in range(1,n+1):\n    add(S,i,caps[i-1])\nfor j in range(1,m+1):\n    add(n+j,T,1)\nfor _ in range(e):\n    u,v=map(int,input().split())\n    add(u,n+v,1)\nflow=0\nwhile True:\n    par={S:None}\n    q=deque([S])\n    while q:\n        x=q.popleft()\n        if x==T:\n            break\n        for y in adj[x]:\n            if y not in par and cap[(x,y)]>0:\n                par[y]=x\n                q.append(y)\n    if T not in par:\n        break\n    x=T\n    while par[x] is not None:\n        p=par[x]\n        cap[(p,x)]-=1\n        cap[(x,p)]+=1\n        x=p\n    flow+=1\nprint(flow)', tip: '1対1のマッチングを「容量」で多対1へ一般化するのはフローの得意技。源・汇側の辺容量を変えるだけで様々な制約が表せる。', ins: ['2 3 4\n2 1\n1 1\n1 2\n2 2\n2 3\n', '1 2 2\n1\n1 1\n1 2\n', '2 2 2\n1 1\n1 1\n2 1\n', '1 1 1\n5\n1 1\n', '3 3 3\n1 1 1\n1 1\n2 2\n3 3\n', '2 4 4\n2 2\n1 1\n1 2\n2 3\n2 4\n'] })

t({ lv: 421, concept: 'ゲーム: Nimの必勝手の数', title: 'Nimで勝ちを確定させる初手の数', tags: ['ゲーム'], io: '各山の石の数が1行で空白区切りで与えられます。', ask: '通常のNim(最後に取ったら勝ち)で、先手が「ある山からいくつか取る」初手のうち、相手を必敗形にできる手が何つの山に対して存在するか(=必勝の初手を打てる山の数)を出力してください。負け形なら0。', h1: '全体のXOR(X)が0なら必勝手なし。', h2: 'a_i XOR X < a_i となる山だけが「X=0 に直せる」山。', ref: 'a=list(map(int,input().split()))\nx=0\nfor v in a:\n    x^=v\nif x==0:\n    print(0)\nelse:\n    print(sum(1 for v in a if v^x<v))', tip: '必勝手は「a_i を a_i⊕X に減らす」。a_i⊕X<a_i ⇔ Xの最上位ビットがa_iで立っている、と言い換えられる。', ins: ['3 4 5\n', '1 1\n', '1 2 3\n', '5\n', '7 7 7\n', '2 4 7\n'] })

t({ lv: 422, concept: 'ゲーム: 負け局面の個数', title: '後手必勝になる石の数を数える', tags: ['ゲーム', 'DP'], io: '1行目に N、2行目に1手で取れる個数の集合 S が与えられます。', ask: '石が n 個 (1≤n≤N) の石取りゲーム(Sの要素だけ取れる、取れない人の負け)で、先手が負ける n の個数を出力してください。', h1: 'win[n] = ある s∈S で win[n-s] が負け、なら勝ち。', h2: '小さい方からDPして負けを数える。', ref: 'n=int(input())\nS=list(map(int,input().split()))\nwin=[False]*(n+1)\nfor i in range(1,n+1):\n    win[i]=any(i>=s and not win[i-s] for s in S)\nprint(sum(1 for i in range(1,n+1) if not win[i]))', tip: '減算ゲームの勝敗列は必ず周期的になる(状態有限+決定的)。P局面の分布を見ると周期が浮かび上がる。', ins: ['10\n1 2 3\n', '10\n2 3\n', '5\n1\n', '7\n1 4\n', '12\n3 5\n', '6\n2 4\n'] })

t({ lv: 423, concept: 'ゲーム: 指定Grundy数の最小局面', title: 'Grundy数がgになる最小の石数', tags: ['ゲーム', 'DP'], io: '1行目に目標の Grundy 数 g、2行目に取れる個数の集合 S が与えられます(達成可能な g のみ与えられる)。', ask: '石取りゲーム(Sの要素だけ取れる)で Grundy 数がちょうど g になる最小の石数 n≥0 を出力してください。', h1: 'g(n)=mex{ g(n-s) : s∈S, s≤n }。', h2: '小さい方から計算して最初に g になった n。', ref: 'g=int(input())\nS=list(map(int,input().split()))\ngr=[0]\nn=0\nwhile gr[n]!=g:\n    n+=1\n    s=set(gr[n-x] for x in S if n>=x)\n    m=0\n    while m in s:\n        m+=1\n    gr.append(m)\nprint(n)', tip: 'S={1..k}ならGrundy数は n mod (k+1) になる。一般のSでも列は最終的に周期的で、欲しい値は必ず早期に現れる。', ins: ['2\n1 2\n', '0\n1 2\n', '1\n1\n', '2\n1 2 3\n', '1\n2 3\n', '3\n1 2 3\n'] })

t({ lv: 424, concept: '数論: フェルマーテストを騙す底の数', title: 'フェルマーテストに合格する底の数', tags: ['数論'], io: '2以上の整数 n が1行で与えられます。', ask: '1≤a≤n-1 のうち a^(n-1)≡1 (mod n) を満たす a の個数を出力してください。', h1: '各 a で pow(a, n-1, n) を計算。', h2: '素数なら全ての 1≤a≤n-1 (フェルマーの小定理)。合成数では一部だけ。', ref: 'n=int(input())\nprint(sum(1 for a in range(1,n) if pow(a,n-1,n)==1))', tip: '合成数でも合格する底を「フェルマーの嘘つき」と呼ぶ。561のようなカーマイケル数は互いに素な全ての底を騙すため、ミラーラビンが必要になる。', ins: ['9\n', '15\n', '561\n', '21\n', '10\n', '25\n'] })

t({ lv: 425, concept: '数論: 素数べきの判定', title: '素数のべき乗かどうか', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: 'n が p^k (pは素数, k≥1) の形なら yes、そうでなければ no を出力してください。', h1: '最小の素因数 p を見つける。', h2: 'p で割り切れるだけ割って1になれば素数べき。', ref: 'n=int(input())\nans="no"\nif n>1:\n    m=n\n    f=2\n    while f*f<=m:\n        if m%f==0:\n            while m%f==0:\n                m//=f\n            ans="yes" if m==1 else "no"\n            break\n        f+=1\n    else:\n        ans="yes"\nprint(ans)', tip: '素数べきの判定は「最小素因数で割り尽くす」だけで決まる。while-else(breakしなかったら素数)はPythonらしい書き方。', ins: ['8\n', '12\n', '7\n', '1\n', '81\n', '100\n'] })

t({ lv: 426, concept: '数論: カタラン数の偶奇', title: 'カタラン数は奇数か偶数か', tags: ['数論'], io: '非負整数 n が1行で与えられます。', ask: 'カタラン数 C_n が奇数なら odd、偶数なら even を出力してください。', h1: 'クンマーの定理から C_n が奇数 ⇔ n+1 が2のべき。', h2: '(n+1)&n==0 で判定できる。', ref: 'n=int(input())\nprint("odd" if (n+1)&n==0 else "even")', tip: 'カタラン数が奇数になるのは n=2^k-1 のときだけ(1,1,5,429,…)。二項係数の素因数はクンマーの定理「繰り上がりの回数」で読める。', ins: ['0\n', '1\n', '2\n', '3\n', '4\n', '7\n'] })

t({ lv: 427, concept: '数論: (n-1)! mod n', title: '(n-1)の階乗をnで割った余り', tags: ['数論'], io: '2以上の整数 n が1行で与えられます。', ask: '(n-1)! を n で割った余りを出力してください。', h1: '順に掛けながら mod を取る。', h2: 'ウィルソンの定理: n が素数なら n-1、合成数なら 4 を除き 0。', ref: 'n=int(input())\nf=1\nfor i in range(1,n):\n    f=f*i%n\nprint(f)', tip: 'ウィルソンの定理 (p-1)!≡-1 (mod p) は素数の特徴付けそのもの(ただし判定法としては遅い)。合成数では n=4 だけが例外的に 2 になる。', ins: ['7\n', '4\n', '10\n', '11\n', '2\n', '9\n'] })

t({ lv: 428, concept: '数論: べき乗合同式の解の個数', title: 'x^k≡a (mod p) の解の個数', tags: ['数論'], io: '素数 p と k a が空白区切りで1行で与えられます。', ask: '0≤x<p で x^k ≡ a (mod p) を満たす x の個数を出力してください。', h1: '全ての x を試す。', h2: 'a≠0 のとき解の個数は 0 か gcd(k, p-1)(原始根の理論)。', ref: 'p,k,a=map(int,input().split())\nprint(sum(1 for x in range(p) if pow(x,k,p)==a%p))', tip: '乗法群が巡回群なので、解があれば個数は必ず gcd(k,p-1)。離散対数に直すと ky≡log(a) という一次合同式になる。', ins: ['7 2 4\n', '7 2 3\n', '5 3 2\n', '11 2 1\n', '13 4 1\n', '2 5 0\n'] })

t({ lv: 429, concept: '文字列: 辞書順最小の接尾辞', title: '辞書順で最小の接尾辞の開始位置', tags: ['文字列'], io: '英小文字の文字列が1行で与えられます。', ask: '全ての接尾辞のうち辞書順最小のものの開始位置(1始まり)を出力してください。', h1: '接尾辞同士をスライスで比較。', h2: '接尾辞配列の先頭要素に相当する。', ref: 's=input()\nbest=0\nfor i in range(1,len(s)):\n    if s[i:]<s[best:]:\n        best=i\nprint(best+1)', tip: '最小接尾辞は接尾辞配列 SA[0]。実は Duval の Lyndon 分解の最後の因子の開始位置とも一致する。', ins: ['banana\n', 'abc\n', 'cba\n', 'baba\n', 'zzz\n', 'ab\n'] })

t({ lv: 430, concept: '文字列: 全ペアのLCPの総和', title: '接尾辞の全ペアのLCP総和', tags: ['文字列'], io: '英小文字の文字列が1行で与えられます。', ask: '全ての接尾辞の組(順序なし)について最長共通接頭辞(LCP)の長さを求め、その総和を出力してください。', h1: '小さい入力なら全ペアを直接比較。', h2: '大規模は接尾辞配列+LCP配列で「隣接LCPの区間最小の総和」に帰着する。', ref: 's=input()\nn=len(s)\ntotal=0\nfor i in range(n):\n    for j in range(i+1,n):\n        a,b=s[i:],s[j:]\n        k=0\n        while k<len(a) and k<len(b) and a[k]==b[k]:\n            k+=1\n        total+=k\nprint(total)', tip: '全ペアLCP和は「s の相異なる部分文字列の数」と表裏一体(総部分文字列数-LCP和)。SA+LCP+単調スタックでO(n)になる。', ins: ['aa\n', 'aaa\n', 'ab\n', 'abab\n', 'abc\n', 'banana\n'] })

t({ lv: 431, concept: '文字列: 出現するパターンの種類数', title: 'テキストに現れるパターンの種類数', tags: ['文字列'], io: '1行目にテキスト、2行目に相異なるパターンが空白区切りで与えられます。', ask: 'テキストに(連続部分文字列として)1回以上現れるパターンの種類数を出力してください。', h1: '各パターンを in 演算子で確認。', h2: 'パターン数が多いときは Aho-Corasick で一括検索。', ref: 's=input()\npats=input().split()\nprint(sum(1 for p in pats if p in s))', tip: '「総出現回数」と「現れる種類数」は集計が違うだけで探索は同じ。Aho-Corasickなら出力リンクを種類フラグにする。', ins: ['ababc\nab bc ca\n', 'hello\nxyz\n', 'aaaa\na aa aaa\n', 'mississippi\nssi issi ppi miss\n', 'abc\nabc abcd\n', 'xyxy\nxy yx yy\n'] })

t({ lv: 432, concept: 'グラフ: 最長単純閉路の長さ', title: '最も長い単純サイクルの頂点数', tags: ['グラフ', 'bitDP'], io: '1行目に n m (n≤10)、続く m 行に無向辺が与えられます。', ask: '同じ頂点を2度通らない閉路のうち最長のものの頂点数を出力してください(閉路が無ければ0)。', h1: '(訪問集合, 現在地) のbitDP。', h2: '集合の最小頂点を始点に固定し、始点に戻れたら長さを更新(長さ3以上)。', ref: 'n,m=map(int,input().split())\nadj=[[False]*n for _ in range(n)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    adj[u-1][v-1]=True\n    adj[v-1][u-1]=True\nbest=0\ndp=[[False]*n for _ in range(1<<n)]\nfor s in range(n):\n    dp[1<<s][s]=True\nfor mask in range(1<<n):\n    low=(mask&-mask).bit_length()-1\n    for last in range(n):\n        if dp[mask][last]:\n            k=bin(mask).count("1")\n            if k>=3 and adj[last][low] and k>best:\n                best=k\n            for j in range(low+1,n):\n                if not mask>>j&1 and adj[last][j]:\n                    dp[mask|1<<j][j]=True\nprint(best)', tip: '閉路の重複列挙は「集合の最小頂点を始点に固定」で防ぐ。ハミルトン路系bitDPの定番テクニック。', ins: ['3 3\n1 2\n2 3\n3 1\n', '4 4\n1 2\n2 3\n3 4\n4 1\n', '4 3\n1 2\n2 3\n3 4\n', '5 6\n1 2\n2 3\n3 1\n3 4\n4 5\n5 3\n', '6 7\n1 2\n2 3\n3 4\n4 5\n5 6\n6 1\n3 6\n', '5 5\n1 2\n2 3\n3 4\n4 1\n1 3\n'] })

t({ lv: 433, concept: '論理: CNFの充足割当の数', title: '論理式を満たす割当の数', tags: ['全探索', '論理'], io: '1行目に変数の数 n と節の数 m、続く m 行に「リテラル数 k と k 個のリテラル(正=変数番号そのまま、負=否定)」が与えられます。', ask: '全ての節(リテラルのOR)を真にする真偽割当の個数を出力してください。', h1: '2^n 通りをビットマスクで全探索。', h2: '各節は1つでも真のリテラルがあればOK。', ref: 'n,m=map(int,input().split())\nclauses=[]\nfor _ in range(m):\n    parts=list(map(int,input().split()))\n    clauses.append(parts[1:])\ncnt=0\nfor mask in range(1<<n):\n    ok=True\n    for cl in clauses:\n        sat=False\n        for lit in cl:\n            v=abs(lit)-1\n            val=mask>>v&1\n            if (lit>0 and val) or (lit<0 and not val):\n                sat=True\n                break\n        if not sat:\n            ok=False\n            break\n    if ok:\n        cnt+=1\nprint(cnt)', tip: '充足可能性(SAT)はNP完全、数え上げ(#SAT)はさらに難しい#P完全。n≤20程度ならビット全探索が最も確実。', ins: ['2 1\n2 1 2\n', '2 2\n1 1\n1 -1\n', '1 1\n1 1\n', '3 2\n2 1 -2\n2 2 3\n', '2 0\n', '3 1\n3 1 2 3\n'] })

t({ lv: 434, concept: 'ビット: ANDが0のペア数', title: 'ANDが0になるペアの個数', tags: ['bit演算'], io: '非負整数の列が1行で空白区切りで与えられます。', ask: 'a[i] AND a[j] = 0 となる組 (i<j) の個数を出力してください。', h1: '全ペアの & を確認。', h2: '大規模はSOS(部分集合和)DPで「補集合の部分集合にある数」を数える。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nprint(sum(1 for i in range(n) for j in range(i+1,n) if a[i]&a[j]==0))', tip: 'AND=0 ⇔ ビット集合が互いに素 ⇔ 片方が他方の補集合の部分集合。SOS DPに乗る形の代表例。', ins: ['1 2 3\n', '0 0\n', '5 2 8\n', '7 7\n', '4 3 8 16\n', '1 1 1\n'] })

t({ lv: 435, concept: '配列: 回文にする最小変更数', title: '回文にするための最小の書き換え数', tags: ['配列', '二点法'], io: '整数列が1行で空白区切りで与えられます。', ask: '要素を好きな値に書き換える操作だけで列を回文にするときの最小の書き換え回数を出力してください。', h1: '対になる位置 (i, n-1-i) を比べる。', h2: '違うペアの数がそのまま答え(片方を書き換えれば直る)。', ref: 'a=input().split()\nn=len(a)\nprint(sum(1 for i in range(n//2) if a[i]!=a[n-1-i]))', tip: '挿入(LCS系DP)や削除と違い「書き換え」の回文化はペアの不一致数を数えるだけ。許す操作によって難易度が激変する好例。', ins: ['1 2 3\n', '1 2 2 1\n', '1 2 3 4\n', '7\n', '1 1 2\n', '5 6 5\n'] })

t({ lv: 436, concept: 'シミュレーション: 上塗り後に見える色の数', title: 'ペンキの上塗り後に見える色数', tags: ['シミュレーション'], io: '1行目にマス数 n と操作数 m、続く m 行に「l r c」(区間[l,r]を色cで上塗り)が与えられます。', ask: '全操作後に1マス以上で見えている色の種類数を出力してください(無色のマスは数えない)。', h1: '操作を順に適用して最終状態を作る。', h2: '0以外の色の種類数を集合で数える。', ref: 'n,m=map(int,input().split())\na=[0]*n\nfor _ in range(m):\n    l,r,c=map(int,input().split())\n    for i in range(l-1,r):\n        a[i]=c\nprint(len(set(x for x in a if x!=0)))', tip: '逆順に走査して「まだ塗られていないマスだけ塗る」と各マス1回で済む(O(n+m))。後勝ちの上書きは逆から見ると先勝ちになる。', ins: ['5 2\n1 3 1\n2 4 2\n', '3 2\n1 3 1\n1 3 2\n', '4 0\n', '6 3\n1 6 5\n2 3 7\n2 3 5\n', '5 3\n1 2 1\n3 4 2\n5 5 3\n', '3 2\n1 2 9\n2 3 9\n'] })

t({ lv: 437, concept: 'DP: 2制約ナップサック', title: '2つの重さ制限のナップサック', tags: ['DP'], io: '1行目に品数 n と2種類の容量 W1 W2、続く n 行に「重さ1 重さ2 価値」が与えられます。', ask: '両方の重さ制限を同時に満たすように選ぶときの価値の最大を出力してください。', h1: 'dp[残り容量1][残り容量2] の2次元。', h2: '0/1なので両方の容量を降順に更新。', ref: 'n,W1,W2=map(int,input().split())\ndp=[[0]*(W2+1) for _ in range(W1+1)]\nfor _ in range(n):\n    w1,w2,v=map(int,input().split())\n    for x in range(W1,w1-1,-1):\n        for y in range(W2,w2-1,-1):\n            cand=dp[x-w1][y-w2]+v\n            if cand>dp[x][y]:\n                dp[x][y]=cand\nprint(dp[W1][W2])', tip: '制約が増えたら次元を増やすのがナップサックの応用法則。重さとコスト、時間と燃料など2リソース問題は実務にも多い。', ins: ['3 5 5\n4 4 10\n2 3 6\n3 2 7\n', '1 1 1\n2 2 5\n', '2 10 10\n5 5 8\n5 5 8\n', '2 3 3\n3 1 5\n1 3 5\n', '1 5 5\n5 5 9\n', '4 4 4\n1 1 1\n1 1 1\n1 1 1\n1 1 1\n'] })

t({ lv: 438, concept: '木DP: 木の最大マッチング', title: '木の最大マッチングの本数', tags: ['木DP'], io: '1行目に頂点数 n、続く n-1 行に木の辺が与えられます。', ask: '端点を共有しない辺集合(マッチング)の最大本数を出力してください。', h1: '各頂点で「自分が未マッチ」「マッチ済み」の2状態DP。', h2: '子のどれか1つと組むときは、その子が未マッチである必要がある。', ref: 'import sys\nsys.setrecursionlimit(10000)\nn=int(input())\ng=[[] for _ in range(n+1)]\nfor _ in range(n-1):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\ndef dfs(x,par):\n    free=0\n    childs=[]\n    for y in g[x]:\n        if y!=par:\n            f,b=dfs(y,x)\n            free+=b\n            childs.append((f,b))\n    best=free\n    for f,b in childs:\n        cand=free-b+f+1\n        if cand>best:\n            best=cand\n    return (free,best)\nif n==1:\n    print(0)\nelse:\n    print(dfs(1,0)[1])', tip: '木のマッチングは「葉から貪欲に組む」だけでも最適になるが、2状態DPの形は重み付きや数え上げへそのまま拡張できる。', ins: ['2\n1 2\n', '3\n1 2\n1 3\n', '4\n1 2\n2 3\n3 4\n', '5\n1 2\n1 3\n2 4\n2 5\n', '7\n1 2\n1 3\n2 4\n2 5\n3 6\n3 7\n', '6\n1 2\n2 3\n3 4\n4 5\n5 6\n'] })

t({ lv: 439, concept: '木DP: 木の3色塗りの最小コスト', title: '隣接異色の3色塗りの最小コスト', tags: ['木DP'], io: '1行目に頂点数 n、続く n 行に頂点ごとの3色のコスト c1 c2 c3、続く n-1 行に木の辺が与えられます。', ask: '隣接する頂点が異なる色になるように3色で塗るときの総コストの最小を出力してください。', h1: 'dp[頂点][色] = その部分木の最小コスト。', h2: '子は親と違う2色のうち安い方を選ぶ。', ref: 'import sys\nsys.setrecursionlimit(10000)\nn=int(input())\ncost=[tuple(map(int,input().split())) for _ in range(n)]\ng=[[] for _ in range(n+1)]\nfor _ in range(n-1):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\ndef dfs(x,par):\n    res=list(cost[x-1])\n    for y in g[x]:\n        if y!=par:\n            cy=dfs(y,x)\n            for c in range(3):\n                res[c]+=min(cy[d] for d in range(3) if d!=c)\n    return res\nprint(min(dfs(1,0)))', tip: '家塗りDP(直線)を木に一般化した形。木は2色で必ず塗り分けられるが、コスト最小化では3色目が安くつくことがある。', ins: ['2\n1 10 10\n10 1 10\n1 2\n', '1\n5 3 7\n', '3\n1 1 1\n5 1 5\n5 5 1\n1 2\n1 3\n', '3\n3 2 1\n3 2 1\n3 2 1\n1 2\n2 3\n', '4\n1 100 100\n100 1 100\n1 100 100\n100 1 100\n1 2\n2 3\n3 4\n', '2\n5 5 5\n5 5 5\n1 2\n'] })

t({ lv: 440, concept: '幾何: 最小の三角形面積の2倍', title: '3点が作る最小の三角形 (面積2倍)', tags: ['幾何'], io: '1行目に点数 n、続く n 行に座標が与えられます。', ask: '3点を選んで作る三角形のうち面積が正で最小のものの面積の2倍を出力してください(全て同一直線上なら0)。', h1: '全ての3点組の外積の絶対値を取る。', h2: '0(退化)を除いた最小。', ref: 'n=int(input())\npts=[tuple(map(int,input().split())) for _ in range(n)]\nbest=None\nfor i in range(n):\n    for j in range(i+1,n):\n        for k in range(j+1,n):\n            ax,ay=pts[i]\n            bx,by=pts[j]\n            cx,cy=pts[k]\n            ar=abs((bx-ax)*(cy-ay)-(by-ay)*(cx-ax))\n            if ar>0 and (best is None or ar<best):\n                best=ar\nprint(best if best is not None else 0)', tip: '格子点の三角形の面積2倍は必ず整数(外積)。最小値1の三角形は内部にも辺上にも格子点を持たない(ピックの定理)。', ins: ['3\n0 0\n2 0\n0 2\n', '4\n0 0\n1 0\n2 0\n0 1\n', '3\n0 0\n1 1\n2 2\n', '4\n0 0\n3 0\n0 3\n1 1\n', '5\n0 0\n5 0\n0 5\n1 0\n0 1\n', '3\n0 0\n10 0\n0 10\n'] })

t({ lv: 441, concept: '幾何: 距離の2乗の総和', title: '全ペアの距離の2乗の合計', tags: ['幾何'], io: '1行目に点数 n、続く n 行に座標が与えられます。', ask: '全ての点対のユークリッド距離の2乗の総和を出力してください。', h1: '(dx²+dy²) を全ペアで足す。', h2: '展開すると n·Σx² - (Σx)² の形になり O(n) でも計算できる。', ref: 'n=int(input())\npts=[tuple(map(int,input().split())) for _ in range(n)]\ntotal=0\nfor i in range(n):\n    for j in range(i+1,n):\n        dx=pts[i][0]-pts[j][0]\n        dy=pts[i][1]-pts[j][1]\n        total+=dx*dx+dy*dy\nprint(total)', tip: 'Σ_{i<j}(x_i-x_j)² = n·Σx²-(Σx)² は分散の n²倍。距離2乗の総和は重心からの距離に分解できる(平行軸の定理)。', ins: ['2\n0 0\n3 4\n', '3\n0 0\n1 0\n0 1\n', '1\n7 7\n', '3\n0 0\n2 0\n4 0\n', '4\n0 0\n1 1\n2 2\n3 3\n', '2\n-1 -1\n1 1\n'] })

export const CATALOG = TASKS
