// 生成タスク 第39波：lv651〜699。lv650(グラフ応用)とlv700(DP)の橋渡し。
// 最大流/最小カット/二部マッチング応用/古典DP入口(ナップサック・LCS族・部分和)の本物の別問題。
// 重複なし・決定的・採点一意(整数/文字列/列出力のみ)。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 651, concept: 'フロー: 最大流(Edmonds-Karp)', title: '最大流の値', tags: ['グラフ', 'フロー'], io: '1行目に n m s t、続く m 行に有向辺 u v c(容量)が与えられます。', ask: 's から t への最大流の値を出力してください。', h1: 'BFSで増加道を探す(Edmonds-Karp)。', h2: '残余グラフに逆辺を作り流せなくなるまで繰り返す。', ref: 'import sys\nfrom collections import deque\nfirst=input().split()\nn=int(first[0])\nm=int(first[1])\ns=int(first[2])\nt=int(first[3])\nif s==t:\n    print(0)\n    sys.exit()\ncap=[[0]*(n+1) for _ in range(n+1)]\nadj=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v,c=map(int,input().split())\n    if v not in adj[u]:\n        adj[u].append(v)\n    if u not in adj[v]:\n        adj[v].append(u)\n    cap[u][v]+=c\nflow=0\nwhile True:\n    parent=[-1]*(n+1)\n    parent[s]=s\n    dq=deque([s])\n    while dq:\n        x=dq.popleft()\n        for y in adj[x]:\n            if parent[y]==-1 and cap[x][y]>0:\n                parent[y]=x\n                dq.append(y)\n    if parent[t]==-1:\n        break\n    aug=float("inf")\n    v=t\n    while v!=s:\n        u=parent[v]\n        aug=min(aug,cap[u][v])\n        v=u\n    v=t\n    while v!=s:\n        u=parent[v]\n        cap[u][v]-=aug\n        cap[v][u]+=aug\n        v=u\n    flow+=aug\nprint(flow)', tip: 'Edmonds-Karpは「最短の増加道をBFSで探す」最大流。残余グラフの逆辺が流れの取り消しを表す。', ins: ['4 5 1 4\n1 2 3\n1 3 2\n2 3 1\n2 4 2\n3 4 3\n', '2 1 1 2\n1 2 5\n', '3 2 1 3\n1 2 4\n2 3 2\n', '1 0 1 1\n', '4 4 1 4\n1 2 1\n1 3 1\n2 4 1\n3 4 1\n', '6 8 1 6\n1 2 10\n1 3 10\n2 4 4\n2 5 8\n3 5 9\n4 6 10\n5 6 10\n5 4 6\n'] })

t({ lv: 652, concept: 'フロー: 辺素なパスの最大数', title: '辺を共有しないs-tパスの最大本数', tags: ['グラフ', 'フロー'], io: '1行目に n m s t、続く m 行に有向辺 u v が与えられます(容量は各1)。', ask: 's から t への、辺を共有しないパスの最大本数を出力してください。', h1: '各辺の容量を1として最大流を流す。', h2: 'メンガーの定理より最大流＝辺素パス数。', ref: 'import sys\nfrom collections import deque\nfirst=input().split()\nn=int(first[0])\nm=int(first[1])\ns=int(first[2])\nt=int(first[3])\nif s==t:\n    print(0)\n    sys.exit()\ncap=[[0]*(n+1) for _ in range(n+1)]\nadj=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    if v not in adj[u]:\n        adj[u].append(v)\n    if u not in adj[v]:\n        adj[v].append(u)\n    cap[u][v]+=1\nflow=0\nwhile True:\n    parent=[-1]*(n+1)\n    parent[s]=s\n    dq=deque([s])\n    while dq:\n        x=dq.popleft()\n        for y in adj[x]:\n            if parent[y]==-1 and cap[x][y]>0:\n                parent[y]=x\n                dq.append(y)\n    if parent[t]==-1:\n        break\n    v=t\n    while v!=s:\n        u=parent[v]\n        cap[u][v]-=1\n        cap[v][u]+=1\n        v=u\n    flow+=1\nprint(flow)', tip: 'メンガーの定理: 辺素な s-t パスの最大数 = s-t 最小カットの辺数 = 単位容量での最大流。', ins: ['4 5 1 4\n1 2\n1 3\n2 4\n3 4\n2 3\n', '2 1 1 2\n1 2\n', '3 2 1 3\n1 2\n2 3\n', '1 0 1 1\n', '4 4 1 4\n1 2\n1 3\n2 4\n3 4\n', '5 6 1 5\n1 2\n1 3\n2 5\n3 5\n2 4\n4 5\n'] })

t({ lv: 653, concept: 'フロー: 最大二部マッチング(フロー)', title: '最大二部マッチング(最大流で)', tags: ['グラフ', 'フロー'], io: '1行目に L R E、続く E 行に辺 a b(左 a・右 b)が与えられます。', ask: '最大二部マッチングのサイズを、超源点・超汇点を足した最大流として求めて出力してください。', h1: '源点→左、右→汇点の容量1の辺を張る。', h2: '最大流が最大マッチング。', ref: 'from collections import deque\nfirst=input().split()\nL=int(first[0])\nR=int(first[1])\nE=int(first[2])\nN=L+R+2\nS=0\nT=L+R+1\ncap=[[0]*N for _ in range(N)]\nadj=[[] for _ in range(N)]\ndef add(u,v):\n    if v not in adj[u]:\n        adj[u].append(v)\n    if u not in adj[v]:\n        adj[v].append(u)\n    cap[u][v]+=1\nfor i in range(1,L+1):\n    add(S,i)\nfor j in range(1,R+1):\n    add(L+j,T)\nfor _ in range(E):\n    a,b=map(int,input().split())\n    add(a,L+b)\nflow=0\nwhile True:\n    parent=[-1]*N\n    parent[S]=S\n    dq=deque([S])\n    while dq:\n        x=dq.popleft()\n        for y in adj[x]:\n            if parent[y]==-1 and cap[x][y]>0:\n                parent[y]=x\n                dq.append(y)\n    if parent[T]==-1:\n        break\n    v=T\n    while v!=S:\n        u=parent[v]\n        cap[u][v]-=1\n        cap[v][u]+=1\n        v=u\n    flow+=1\nprint(flow)', tip: '二部マッチングは「源点→左→右→汇点」を容量1で繋いだ最大流に帰着する。', ins: ['2 2 2\n1 1\n2 2\n', '3 3 4\n1 1\n1 2\n2 1\n3 3\n', '2 2 1\n1 1\n', '1 1 0\n', '3 2 4\n1 1\n2 1\n3 2\n2 2\n', '2 3 3\n1 1\n1 2\n2 3\n'] })

t({ lv: 654, concept: 'DP: 0/1ナップサック最大価値', title: '0/1ナップサックの最大価値', tags: ['dp'], io: '1行目に n W、続く n 行に重さ w と価値 v が与えられます。', ask: '容量 W を超えない範囲で価値の合計の最大を出力してください。', h1: 'dp[w]=容量wでの最大価値。', h2: '各品で容量を後ろから更新。', ref: 'first=input().split()\nn=int(first[0])\nW=int(first[1])\ndp=[0]*(W+1)\nfor _ in range(n):\n    w,v=map(int,input().split())\n    for c in range(W,w-1,-1):\n        if dp[c-w]+v>dp[c]:\n            dp[c]=dp[c-w]+v\nprint(dp[W])', tip: '0/1ナップサックは「容量を後ろから更新」して各品を1回だけ使う。前から回すと無制限版になる。', ins: ['3 4\n1 2\n3 4\n4 5\n', '1 0\n5 10\n', '2 5\n5 10\n5 20\n', '3 6\n2 3\n3 4\n4 5\n', '1 10\n5 7\n', '4 10\n5 10\n4 40\n6 30\n3 50\n'] })

t({ lv: 655, concept: 'DP: 無制限ナップサック最大価値', title: '個数無制限ナップサックの最大価値', tags: ['dp'], io: '1行目に n W、続く n 行に重さ w と価値 v が与えられます(各品は何個でも使える)。', ask: '容量 W を超えない最大価値を出力してください。', h1: 'dp[w]=容量wでの最大価値。', h2: '各品で容量を前から更新(同じ品を再利用)。', ref: 'first=input().split()\nn=int(first[0])\nW=int(first[1])\nitems=[tuple(map(int,input().split())) for _ in range(n)]\ndp=[0]*(W+1)\nfor w,v in items:\n    for c in range(w,W+1):\n        if dp[c-w]+v>dp[c]:\n            dp[c]=dp[c-w]+v\nprint(dp[W])', tip: '無制限ナップサックは「容量を前から更新」して同じ品を何度も詰められるようにする。', ins: ['2 5\n2 3\n3 4\n', '1 10\n3 5\n', '3 6\n1 1\n2 5\n3 8\n', '1 0\n5 10\n', '2 7\n3 4\n4 5\n', '3 10\n2 3\n3 4\n5 6\n'] })

t({ lv: 656, concept: 'DP: 部分和の可否', title: '部分和が作れるか', tags: ['dp'], io: '1行目に target、2行目に正整数列が与えられます。', ask: '部分集合の和をちょうど target にできるなら yes、できないなら no を出力してください。', h1: 'bool DP で到達可能な和を持つ。', h2: 'dp[s] が真なら dp[s+x] も真。', ref: 'target=int(input())\na=list(map(int,input().split()))\ndp=[False]*(target+1)\ndp[0]=True\nfor x in a:\n    for s in range(target,x-1,-1):\n        if dp[s-x]:\n            dp[s]=True\nprint("yes" if dp[target] else "no")', tip: '部分和判定はboolナップサック。集合(set)で持っても良いが配列の方が定数倍が速い。', ins: ['5\n1 2 3\n', '11\n1 5 5\n', '0\n1 2\n', '7\n2 4\n', '6\n1 2 3\n', '10\n3 3 3\n'] })

t({ lv: 657, concept: 'DP: 部分和の通り数', title: '和が目標になる部分集合の数(DP)', tags: ['dp'], io: '1行目に target、2行目に正整数列が与えられます。', ask: '部分集合の和が target になる選び方の数を出力してください。', h1: 'dp[s]=和 s を作る通り数。', h2: '各要素を後ろから加える(0/1)。', ref: 'target=int(input())\na=list(map(int,input().split()))\ndp=[0]*(target+1)\ndp[0]=1\nfor x in a:\n    for s in range(target,x-1,-1):\n        dp[s]+=dp[s-x]\nprint(dp[target])', tip: '通り数版はbool DPを整数加算に変えるだけ。0/1なので容量を後ろから回す。', ins: ['5\n1 2 3 4 5\n', '0\n1 2 3\n', '6\n1 2 3\n', '4\n1 1 1 1\n', '10\n2 3 5\n', '3\n3\n'] })

t({ lv: 658, concept: 'DP: 平方数の最小個数', title: '完全平方数の和で表す最小個数', tags: ['dp'], io: '非負整数 n が1行で与えられます。', ask: 'n を完全平方数の和で表すときの最小個数を出力してください。', h1: 'dp[x]=x を作る最小個数。', h2: 'dp[x]=min(dp[x-平方数]+1)。', ref: 'n=int(input())\nINF=float("inf")\ndp=[0]+[INF]*n\nsquares=[]\ni=1\nwhile i*i<=n:\n    squares.append(i*i)\n    i+=1\nfor x in range(1,n+1):\n    for sq in squares:\n        if sq<=x and dp[x-sq]+1<dp[x]:\n            dp[x]=dp[x-sq]+1\nprint(dp[n])', tip: '平方数の最小個数は無制限ナップサックの最小化版。ラグランジュの定理より答えは必ず4以下。', ins: ['12\n', '13\n', '1\n', '0\n', '100\n', '7\n'] })

t({ lv: 659, concept: 'DP: 1にする最小操作回数', title: '1にするまでの最小操作回数', tags: ['dp'], io: '正整数 n が1行で与えられます。', ask: '操作「-1」「偶数なら/2」「3の倍数なら/3」を使って n を1にする最小操作回数を出力してください。', h1: 'メモ化再帰で各値の最小手数を求める。', h2: 'solve(x)=1+min(solve(x-1), 可能なら solve(x/2), solve(x/3))。', ref: 'import sys\nsys.setrecursionlimit(1000000)\nfrom functools import lru_cache\nn=int(input())\n@lru_cache(maxsize=None)\ndef solve(x):\n    if x<=1:\n        return 0\n    best=solve(x-1)+1\n    if x%2==0:\n        best=min(best,solve(x//2)+1)\n    if x%3==0:\n        best=min(best,solve(x//3)+1)\n    return best\nprint(solve(n))', tip: '「1にする最小操作」はメモ化再帰DP。割り算を優先する貪欲は誤る(例: 10)。', ins: ['10\n', '1\n', '2\n', '7\n', '15\n', '100\n'] })

t({ lv: 660, concept: 'DP: 価値あたり重さ最小(双対ナップサック)', title: '価値V以上の最小重さ', tags: ['dp'], io: '1行目に n V、続く n 行に重さ w と価値 v が与えられます。', ask: '価値合計が V 以上になる選び方の最小重さを出力してください。不可能なら -1。', h1: '価値を添字、重さを最小化する。', h2: 'dp[value]=その価値を作る最小重さ。', ref: 'first=input().split()\nn=int(first[0])\nV=int(first[1])\nitems=[tuple(map(int,input().split())) for _ in range(n)]\nINF=float("inf")\nmaxv=sum(v for w,v in items)\ndp=[INF]*(maxv+1)\ndp[0]=0\nfor w,v in items:\n    for val in range(maxv,v-1,-1):\n        if dp[val-v]+w<dp[val]:\n            dp[val]=dp[val-v]+w\nbest=INF\nfor val in range(V,maxv+1):\n    if dp[val]<best:\n        best=dp[val]\nprint(best if best<INF else -1)', tip: '価値が大きく重さが小さいときは「価値を添字、重さを最小化」する双対ナップサックが有効。', ins: ['3 5\n2 3\n3 4\n4 5\n', '1 10\n1 5\n', '2 0\n5 1\n3 1\n', '3 6\n1 2\n1 2\n1 2\n', '2 3\n10 3\n1 1\n', '1 5\n2 5\n'] })

t({ lv: 661, concept: 'スライディングウィンドウ: 最大最小差≤kの最長', title: '最大-最小がk以下の最長部分配列', tags: ['配列'], io: '1行目に k、2行目に整数列が与えられます。', ask: '区間内の最大値と最小値の差が k 以下になる最長の連続部分配列の長さを出力してください。', h1: '最大・最小を単調デックで管理する。', h2: '差が k を超えたら左端を縮める。', ref: 'from collections import deque\nk=int(input())\na=list(map(int,input().split()))\nn=len(a)\nmaxd=deque()\nmind=deque()\nleft=0\nbest=0\nfor right in range(n):\n    while maxd and a[maxd[-1]]<=a[right]:\n        maxd.pop()\n    maxd.append(right)\n    while mind and a[mind[-1]]>=a[right]:\n        mind.pop()\n    mind.append(right)\n    while a[maxd[0]]-a[mind[0]]>k:\n        left+=1\n        if maxd[0]<left:\n            maxd.popleft()\n        if mind[0]<left:\n            mind.popleft()\n    if right-left+1>best:\n        best=right-left+1\nprint(best)', tip: '区間の最大・最小を単調デックで O(1) 取得しつつ窓を伸縮させる典型。', ins: ['2\n1 3 2 5 4\n', '0\n1 1 1\n', '1\n1 2 3 4\n', '10\n5\n', '3\n1 5 9\n', '2\n8 2 4 7\n'] })

t({ lv: 662, concept: 'DP: 最大の正方形の面積', title: '0/1行列の最大正方形の面積', tags: ['dp'], io: '1行目に R C、続く R 行に C 個の 0/1 が与えられます。', ask: 'すべて1で埋まった最大正方形の面積を出力してください。', h1: 'dp[i][j]=右下が(i,j)の最大正方形の辺。', h2: '辺の最大の2乗が面積。', ref: 'first=input().split()\nR=int(first[0])\nC=int(first[1])\nmat=[list(map(int,input().split())) for _ in range(R)]\ndp=[[0]*C for _ in range(R)]\nbest=0\nfor i in range(R):\n    for j in range(C):\n        if mat[i][j]==1:\n            if i==0 or j==0:\n                dp[i][j]=1\n            else:\n                dp[i][j]=min(dp[i-1][j],dp[i][j-1],dp[i-1][j-1])+1\n            if dp[i][j]>best:\n                best=dp[i][j]\nprint(best*best)', tip: '最大正方形の「辺」を求め2乗すれば面積。lv499は辺を答えるので別計算。', ins: ['3 3\n1 1 0\n1 1 1\n0 1 1\n', '2 2\n1 1\n1 1\n', '2 2\n0 0\n0 0\n', '1 4\n1 1 1 1\n', '3 3\n1 0 1\n0 1 0\n1 0 1\n', '4 4\n1 1 1 1\n1 1 1 1\n1 1 1 0\n1 1 1 1\n'] })

t({ lv: 663, concept: 'DP: グリッドの最小経路和', title: 'グリッドの最小経路和(右下移動)', tags: ['dp'], io: '1行目に R C、続く R 行に C 個の非負整数が与えられます。', ask: '左上から右下へ右・下だけに進み、通ったマスの和の最小値を出力してください。', h1: 'dp[i][j]=そこまでの最小和。', h2: 'dp[i][j]=grid+min(上,左)。', ref: 'first=input().split()\nR=int(first[0])\nC=int(first[1])\ngrid=[list(map(int,input().split())) for _ in range(R)]\nINF=float("inf")\ndp=[[INF]*C for _ in range(R)]\ndp[0][0]=grid[0][0]\nfor i in range(R):\n    for j in range(C):\n        if i==0 and j==0:\n            continue\n        up=dp[i-1][j] if i>0 else INF\n        left=dp[i][j-1] if j>0 else INF\n        dp[i][j]=grid[i][j]+min(up,left)\nprint(dp[R-1][C-1])', tip: '最小経路和は単純な2次元DP。右・下のみなので上か左の小さい方に自分を足す。', ins: ['2 3\n1 3 1\n1 5 1\n', '1 1\n5\n', '3 3\n1 2 3\n4 5 6\n7 8 9\n', '1 4\n1 2 3 4\n', '2 2\n1 2\n1 1\n', '3 1\n1\n2\n3\n'] })

t({ lv: 664, concept: 'DP: 三角形の最大下降経路', title: '三角形の最大経路和', tags: ['dp'], io: '1行目に行数 n、続く n 行に i 行目は i 個の整数(三角形)が与えられます。', ask: '頂点から底辺まで、隣接する下の要素へ降りる経路の和の最大値を出力してください。', h1: '下から上へDPする。', h2: 'dp[i][j]=a+max(dp[i+1][j], dp[i+1][j+1])。', ref: 'n=int(input())\ntri=[list(map(int,input().split())) for _ in range(n)]\ndp=tri[-1][:]\nfor i in range(n-2,-1,-1):\n    for j in range(i+1):\n        dp[j]=tri[i][j]+max(dp[j],dp[j+1])\nprint(dp[0])', tip: '三角形の最大経路も下の行から畳み込む。各位置は直下2つの大きい方に自分を足す。', ins: ['4\n2\n3 4\n6 5 7\n4 1 8 3\n', '1\n5\n', '2\n1\n2 3\n', '3\n1\n2 2\n3 3 3\n', '3\n5\n1 1\n1 1 1\n', '2\n-1\n-2 -3\n'] })

t({ lv: 665, concept: 'DP: 最大連続部分和(Kadane)', title: 'Kadaneの最大部分和', tags: ['dp'], io: '整数列が1行で空白区切りで与えられます。', ask: '空でない連続部分配列の和の最大値を出力してください。', h1: 'cur=max(x, cur+x)。', h2: '途中の最大を保持する。', ref: 'a=list(map(int,input().split()))\ncur=a[0]\nbest=a[0]\nfor x in a[1:]:\n    cur=max(x,cur+x)\n    if cur>best:\n        best=cur\nprint(best)', tip: 'Kadaneは「ここで切るか繋ぐか」を各位置で決める線形DP。全負でも最大1要素を返す。', ins: ['-2 1 -3 4 -1 2 1 -5 4\n', '1 2 3\n', '-1 -2 -3\n', '5\n', '-5\n', '3 -2 5 -1\n'] })

t({ lv: 666, concept: 'DP: 円環の最大連続部分和', title: '環状配列の最大部分和', tags: ['dp'], io: '整数列が1行で与えられます(末尾と先頭が繋がる環)。', ask: '環状に連続する部分配列の和の最大値を出力してください(空は不可)。', h1: '通常のKadane最大と、全体和-最小部分和を比べる。', h2: '全要素が負なら通常Kadaneを使う。', ref: 'a=list(map(int,input().split()))\ntotal=sum(a)\ncur=a[0]\nmax_sum=a[0]\nfor x in a[1:]:\n    cur=max(x,cur+x)\n    max_sum=max(max_sum,cur)\ncur=a[0]\nmin_sum=a[0]\nfor x in a[1:]:\n    cur=min(x,cur+x)\n    min_sum=min(min_sum,cur)\nif max_sum<0:\n    print(max_sum)\nelse:\n    print(max(max_sum,total-min_sum))', tip: '環状最大和は「普通の最大」と「全体−最小部分和(=ラップした和)」の大きい方。全負は例外。', ins: ['1 -2 3 -2\n', '5 -3 5\n', '-3 -2 -3\n', '3 -1 2 -1\n', '-2 4 -5 4 -5 9 4\n', '1 2 3\n'] })

t({ lv: 667, concept: 'DP: 連続部分積が正になる最長長さ', title: '積が正になる最長部分配列', tags: ['dp'], io: '0を含まない整数列が1行で与えられます。', ask: '要素の積が正になる最長の連続部分配列の長さを出力してください(0は含まれない)。', h1: '各位置で「正で終わる最長」「負で終わる最長」を持つ。', h2: '符号で pos/neg を入れ替える。', ref: 'a=list(map(int,input().split()))\npos=0\nneg=0\nbest=0\nfor x in a:\n    if x>0:\n        pos=pos+1\n        neg=neg+1 if neg>0 else 0\n    else:\n        npos=neg+1 if neg>0 else 0\n        nneg=pos+1\n        pos=npos\n        neg=nneg\n    if pos>best:\n        best=pos\nprint(best)', tip: '符号だけ追えばよい。負数1個で pos/neg が入れ替わるDPで O(n)。', ins: ['1 -2 -3 4\n', '-1 2 3\n', '-1\n', '1 2 3\n', '-1 -1 -1 -1\n', '-5 2 -1 3 -2\n'] })

t({ lv: 668, concept: 'DP: 家を選ぶ最大金額(隣接禁止)', title: '隣接を選べない最大和(House Robber)', tags: ['dp'], io: '非負整数の列が1行で与えられます。', ask: '隣り合う要素を同時に選べない条件で、選んだ要素の和の最大値を出力してください。', h1: 'dp[i]=i番目までの最大。', h2: 'dp[i]=max(dp[i-1], dp[i-2]+a[i])。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nif n==0:\n    print(0)\nelse:\n    prev2=0\n    prev1=0\n    for x in a:\n        cur=max(prev1,prev2+x)\n        prev2=prev1\n        prev1=cur\n    print(prev1)', tip: 'House Robberは「取る/取らない」の1次元DP。隣接禁止は dp[i-2] から遷移して表す。', ins: ['1 2 3 1\n', '2 7 9 3 1\n', '5\n', '2 1 1 2\n', '0 0 0\n', '10 1 1 10\n'] })

t({ lv: 669, concept: 'DP: 環状の隣接禁止最大和', title: '環状House Robber', tags: ['dp'], io: '非負整数の列が1行で与えられます(先頭と末尾が隣接する環)。', ask: '環状で隣接を同時に選べないときの最大和を出力してください。', h1: '先頭を使う場合と使わない場合に分ける。', h2: '[0..n-2] と [1..n-1] の直線版の大きい方。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nif n==0:\n    print(0)\nelif n==1:\n    print(a[0])\nelse:\n    def rob(arr):\n        p2=0\n        p1=0\n        for x in arr:\n            cur=max(p1,p2+x)\n            p2=p1\n            p1=cur\n        return p1\n    print(max(rob(a[:-1]),rob(a[1:])))', tip: '環状版は「先頭を含む/含まない」で直線House Robberを2回解いて大きい方を取る。', ins: ['2 3 2\n', '1 2 3 1\n', '5\n', '1 2 3\n', '0 0 0 0\n', '6 6 4 8 4 3 3 10\n'] })

t({ lv: 670, concept: 'DP: 最長共通部分列(3文字列)', title: '3つの文字列の最長共通部分列', tags: ['dp', '文字列'], io: '1行目に文字列 a、2行目に b、3行目に c が与えられます。', ask: '3つの文字列すべてに共通する最長部分列の長さを出力してください。', h1: '3次元DP dp[i][j][k]。', h2: '末尾3文字が一致なら+1、違えば3方向の最大。', ref: 'a=input()\nb=input()\nc=input()\nL1=len(a)\nL2=len(b)\nL3=len(c)\ndp=[[[0]*(L3+1) for _ in range(L2+1)] for _ in range(L1+1)]\nfor i in range(1,L1+1):\n    for j in range(1,L2+1):\n        for k in range(1,L3+1):\n            if a[i-1]==b[j-1]==c[k-1]:\n                dp[i][j][k]=dp[i-1][j-1][k-1]+1\n            else:\n                dp[i][j][k]=max(dp[i-1][j][k],dp[i][j-1][k],dp[i][j][k-1])\nprint(dp[L1][L2][L3])', tip: '3列LCSは2列LCSの自然な拡張で3次元DP。一致は3つ同時のときだけ+1。', ins: ['abcde\nace\nace\n', 'abc\nabc\nabc\n', 'abc\ndef\nghi\n', 'aaa\naa\na\n', 'abcd\nbcd\ncd\n', 'xyz\nxz\nyz\n'] })

t({ lv: 671, concept: 'DP: 編集距離(挿入削除のみ)', title: '挿入削除だけの最小操作', tags: ['dp', '文字列'], io: '1行目に文字列 a、2行目に b が与えられます。', ask: '挿入と削除だけで a を b に変える最小操作数を出力してください(置換は不可)。', h1: '共通部分列を最大化する。', h2: '答え = |a|+|b|-2·LCS。', ref: 'a=input()\nb=input()\nn=len(a)\nm=len(b)\ndp=[[0]*(m+1) for _ in range(n+1)]\nfor i in range(1,n+1):\n    for j in range(1,m+1):\n        if a[i-1]==b[j-1]:\n            dp[i][j]=dp[i-1][j-1]+1\n        else:\n            dp[i][j]=max(dp[i-1][j],dp[i][j-1])\nlcs=dp[n][m]\nprint(n+m-2*lcs)', tip: '挿入削除のみの編集距離は |a|+|b|-2·LCS。残す部分(LCS)以外を消して足す。', ins: ['sea\neat\n', 'leetcode\netco\n', 'abc\nabc\n', 'abc\ndef\n', 'a\n\n', 'abcd\nbd\n'] })

t({ lv: 672, concept: 'DP: 最長共通部分文字列(2文字列)', title: '最長共通連続部分文字列', tags: ['dp', '文字列'], io: '1行目に文字列 a、2行目に b が与えられます。', ask: '両者に共通する最長の連続部分文字列の長さを出力してください。', h1: 'dp[i][j]=a[i-1],b[j-1]で終わる共通接尾辞長。', h2: '一致で左上+1、不一致で0、最大を取る。', ref: 'a=input()\nb=input()\nn=len(a)\nm=len(b)\nprev=[0]*(m+1)\nbest=0\nfor i in range(1,n+1):\n    cur=[0]*(m+1)\n    for j in range(1,m+1):\n        if a[i-1]==b[j-1]:\n            cur[j]=prev[j-1]+1\n            if cur[j]>best:\n                best=cur[j]\n    prev=cur\nprint(best)', tip: '部分文字列(連続)は不一致で0にリセットする点が部分列と違う。1行DPで省メモリ化できる。', ins: ['abcde\nbcdf\n', 'abc\nabc\n', 'abc\ndef\n', 'aaa\naa\n', 'xyzabc\nabcxyz\n', 'a\n\n'] })

t({ lv: 673, concept: 'DP: 最長交互増減(連続)部分配列', title: '連続するジグザグの最長長さ', tags: ['dp'], io: '整数列が1行で与えられます。', ask: '隣接差の符号が交互になる最長の連続部分配列の長さを出力してください(要素1個は長さ1)。', h1: '直前の差の符号を持つ。', h2: '符号が反転したら伸ばし、そうでなければリセット。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nif n==0:\n    print(0)\nelif n==1:\n    print(1)\nelse:\n    best=1\n    cur=1\n    prev=0\n    for i in range(1,n):\n        d=a[i]-a[i-1]\n        if d>0 and prev<=0:\n            cur=cur+1 if prev<0 else 2\n            prev=1\n        elif d<0 and prev>=0:\n            cur=cur+1 if prev>0 else 2\n            prev=-1\n        else:\n            cur=2 if d!=0 else 1\n            prev=1 if d>0 else (-1 if d<0 else 0)\n        if cur>best:\n            best=cur\n    print(best)', tip: '連続版ジグザグは直前の差の符号だけを状態に持つ。等しい(差0)で切れる点に注意。', ins: ['1 7 4 9 2 5\n', '1 4 7 2 5\n', '1 1 1\n', '5\n', '1 2 3 2 1\n', '3 3 2 5 1\n'] })

t({ lv: 674, concept: 'DP: 重みつき区間スケジューリング', title: '重み付き区間スケジューリングの最大重み', tags: ['dp'], io: '1行目に n、続く n 行に区間 l r w(重み)が与えられます。', ask: '互いに重ならないよう選んだ区間の重みの合計の最大値を出力してください。', h1: '終点でソートし二分探索で前の両立区間を探す。', h2: 'dp[i]=max(取らない, w_i+dp[最後に両立する区間])。', ref: 'import bisect\nn=int(input())\nivs=[tuple(map(int,input().split())) for _ in range(n)]\nivs.sort(key=lambda x:x[1])\nends=[x[1] for x in ivs]\ndp=[0]*(n+1)\nfor i in range(1,n+1):\n    l,r,w=ivs[i-1]\n    j=bisect.bisect_right(ends,l)\n    take=w+dp[j]\n    dp[i]=max(dp[i-1],take)\nprint(dp[n] if n>0 else 0)', tip: '重み付き区間スケジューリングは終点ソート＋二分探索のDP。貪欲では解けない。', ins: ['3\n1 2 50\n2 3 10\n1 3 70\n', '1\n0 10 5\n', '2\n1 2 1\n3 4 1\n', '3\n1 3 20\n2 5 20\n4 6 20\n', '2\n1 5 100\n2 3 50\n', '4\n1 2 1\n2 3 2\n3 4 3\n1 4 5\n'] })

t({ lv: 675, concept: 'DP: 最長等比でない…最長連続増加', title: '最長連続増加部分列の長さ', tags: ['dp'], io: '整数列が1行で与えられます。', ask: '狭義単調増加する最長の連続部分配列の長さを出力してください。', h1: '直前より大きければ伸ばす。', h2: 'そうでなければ1にリセット。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nif n==0:\n    print(0)\nelse:\n    best=1\n    cur=1\n    for i in range(1,n):\n        if a[i]>a[i-1]:\n            cur+=1\n            if cur>best:\n                best=cur\n        else:\n            cur=1\n    print(best)', tip: '連続増加(LCIS的でなく連続)はリセット型の線形走査。部分列のLISとは別物。', ins: ['1 3 5 4 7\n', '2 2 2\n', '1 2 3 4\n', '5 4 3 2 1\n', '1\n', '1 3 2 3 4 5\n'] })

t({ lv: 676, concept: 'DP: 切り分けの最大利益(棒切り)', title: '棒の切り分けの最大利益', tags: ['dp'], io: '1行目に長さ n、2行目に長さ 1..n の価格 p1..pn が与えられます。', ask: '長さ n の棒を切り分けて得られる価格合計の最大値を出力してください。', h1: 'dp[x]=長さxの最大利益。', h2: 'dp[x]=max(p[i]+dp[x-i])。', ref: 'n=int(input())\np=list(map(int,input().split()))\ndp=[0]*(n+1)\nfor x in range(1,n+1):\n    best=0\n    for i in range(1,x+1):\n        if p[i-1]+dp[x-i]>best:\n            best=p[i-1]+dp[x-i]\n    dp[x]=best\nprint(dp[n])', tip: '棒切り問題は無制限ナップサックの一種。長さを資源、各切片を品物と見る。', ins: ['4\n1 5 8 9\n', '1\n5\n', '8\n1 5 8 9 10 17 17 20\n', '3\n2 5 7\n', '5\n2 3 7 8 9\n', '2\n1 1\n'] })

t({ lv: 677, concept: 'DP: 階段を上る方法(1か2段)', title: '階段の上り方(1か2段)', tags: ['dp'], io: '段数 n が1行で与えられます。', ask: '1段か2段ずつ上って n 段に達する方法の数を出力してください。', h1: 'フィボナッチ漸化式。', h2: 'f(n)=f(n-1)+f(n-2)。', ref: 'n=int(input())\nif n<=1:\n    print(1)\nelse:\n    a=1\n    b=1\n    for _ in range(2,n+1):\n        a,b=b,a+b\n    print(b)', tip: '1か2段の階段はフィボナッチ。最後の1歩が1段か2段かで2項に分かれる。', ins: ['4\n', '0\n', '1\n', '2\n', '5\n', '10\n'] })

t({ lv: 678, concept: 'DP: 最小コストで階段を上る', title: '階段上りの最小コスト', tags: ['dp'], io: '各段のコスト列が1行で与えられます(0段目の手前から開始、1か2段進める)。', ask: '最上段(配列の外)に到達する最小コストを出力してください。', h1: 'dp[i]=段iに来る最小コスト。', h2: 'dp[i]=cost[i]+min(dp[i-1],dp[i-2])。', ref: 'cost=list(map(int,input().split()))\nn=len(cost)\nif n==0:\n    print(0)\nelse:\n    prev2=0\n    prev1=0\n    for i in range(2,n+1):\n        cur=min(prev1+cost[i-1],prev2+cost[i-2])\n        prev2=prev1\n        prev1=cur\n    print(prev1)', tip: '頂上は配列の外。各段に来る最小コストを1次元DPで持ち、最後に1段か2段で抜ける。', ins: ['10 15 20\n', '1 100 1 1 1 100 1 1 100 1\n', '0 0\n', '5\n', '1 2\n', '0 1 2 2\n'] })

t({ lv: 679, concept: 'DP: 重複組合せでk段を上る', title: '歩幅集合で階段を上る方法(順序あり)', tags: ['dp'], io: '1行目に段数 n、2行目に歩幅集合が与えられます。', ask: '指定された歩幅で順序を区別して n 段上る方法の数を出力してください。', h1: 'dp[x]=x段に達する方法。', h2: '段 x を外側に、歩幅を内側に回す。', ref: 'n=int(input())\nsteps=set(map(int,input().split()))\ndp=[0]*(n+1)\ndp[0]=1\nfor x in range(1,n+1):\n    for s in steps:\n        if s<=x:\n            dp[x]+=dp[x-s]\nprint(dp[n])', tip: '順序ありの上り方は段を外側に回す合成数の数え上げ。lv540と入力形式(集合)が違う別問題。', ins: ['4\n1 2\n', '3\n1 2 3\n', '0\n1 2\n', '5\n1 3 5\n', '6\n2 3\n', '10\n1 2 3\n'] })

t({ lv: 680, concept: 'DP: 最大の和の長方形(K以下)', title: 'K以下で最大の部分長方形和', tags: ['dp'], io: '1行目に R C K、続く R 行に C 個の整数が与えられます。', ask: '部分長方形の和のうち K 以下で最大のものを出力してください(常に存在すると仮定)。', h1: '上下端を固定し列和を圧縮。', h2: '1次元で「和がK以下最大」を累積和の全探索で。', ref: 'first=input().split()\nR=int(first[0])\nC=int(first[1])\nK=int(first[2])\nmat=[list(map(int,input().split())) for _ in range(R)]\nbest=float("-inf")\nfor top in range(R):\n    col=[0]*C\n    for bottom in range(top,R):\n        for j in range(C):\n            col[j]+=mat[bottom][j]\n        for i in range(C):\n            s=0\n            for j in range(i,C):\n                s+=col[j]\n                if s<=K and s>best:\n                    best=s\nprint(best)', tip: '「K以下で最大」は上下端固定＋1次元の累積和全探索。Cが大きいなら平衡木で O(C log C)。', ins: ['2 2 2\n1 0\n0 1\n', '1 1 5\n3\n', '2 2 0\n-1 -2\n-3 -4\n', '2 3 4\n1 2 3\n-1 -2 -3\n', '1 4 6\n1 2 3 4\n', '3 3 8\n1 2 3\n4 5 6\n7 8 9\n'] })

t({ lv: 681, concept: 'DP: 文字列のパターン照合(?と*)', title: 'ワイルドカード照合', tags: ['dp', '文字列'], io: '1行目に文字列 s、2行目にパターン p(? は任意1文字、* は任意長)が与えられます。', ask: 's が p に完全一致するなら yes、しないなら no を出力してください。', h1: 'dp[i][j]=s[:i]とp[:j]が一致するか。', h2: '* は0文字以上、? は任意1文字。', ref: 's=input()\np=input()\nn=len(s)\nm=len(p)\ndp=[[False]*(m+1) for _ in range(n+1)]\ndp[0][0]=True\nfor j in range(1,m+1):\n    if p[j-1]=="*":\n        dp[0][j]=dp[0][j-1]\nfor i in range(1,n+1):\n    for j in range(1,m+1):\n        if p[j-1]=="*":\n            dp[i][j]=dp[i-1][j] or dp[i][j-1]\n        elif p[j-1]=="?" or p[j-1]==s[i-1]:\n            dp[i][j]=dp[i-1][j-1]\nprint("yes" if dp[n][m] else "no")', tip: 'ワイルドカード照合は2次元DP。* は「使わない(dp[i][j-1])か1文字消費(dp[i-1][j])」。', ins: ['aa\na\n', 'aa\n*\n', 'cb\n?a\n', 'adceb\n*a*b\n', 'acdcb\na*c?b\n', 'abc\nabc\n'] })

t({ lv: 682, concept: 'DP: 連続する1の最大長(反転k回)', title: 'k回反転で得る最長の連続1', tags: ['dp'], io: '1行目に k、2行目に 0/1 の列が与えられます。', ask: '高々 k 個の0を1に変えてよいとき、得られる連続した1の最大長を出力してください。', h1: 'スライディングウィンドウで0の数を k 以下に保つ。', h2: '窓の最大幅が答え。', ref: 'k=int(input())\na=list(map(int,input().split()))\nn=len(a)\nleft=0\nzeros=0\nbest=0\nfor right in range(n):\n    if a[right]==0:\n        zeros+=1\n    while zeros>k:\n        if a[left]==0:\n            zeros-=1\n        left+=1\n    if right-left+1>best:\n        best=right-left+1\nprint(best)', tip: '「k個まで0を許す最長窓」はスライディングウィンドウ。0の数で窓を縮める。', ins: ['2\n1 1 0 0 1 1 1 0 1\n', '0\n1 1 0 1 1\n', '1\n0 0 0\n', '3\n0 0 0\n', '2\n1 1 1\n', '1\n1 0 1 0 1\n'] })

t({ lv: 683, concept: 'DP: 最長の和が等しい二分割点', title: '左右の和が等しくなる位置の数', tags: ['配列'], io: '整数列が1行で与えられます。', ask: 'ある位置 i について「i より前の和」と「i より後の和」が等しくなるような i(0始まり)の個数を出力してください。', h1: '総和と左和を持つ。', h2: '左和 == 総和-左和-a[i] なら一致。', ref: 'a=list(map(int,input().split()))\ntotal=sum(a)\nleft=0\ncnt=0\nfor i in range(len(a)):\n    right=total-left-a[i]\n    if left==right:\n        cnt+=1\n    left+=a[i]\nprint(cnt)', tip: 'ピボット位置は左和と右和(=総和-左和-自分)の比較。累積和を1パスで更新する。', ins: ['1 7 3 6 5 6\n', '1 2 3\n', '2 1 -1\n', '0 0 0\n', '1\n', '-1 -1 -1 0 1 1\n'] })

t({ lv: 684, concept: 'DP: 最長の連続部分列で和がS', title: '和がSの最長連続部分配列の長さ', tags: ['ハッシュ'], io: '1行目に S、2行目に整数列が与えられます。', ask: '和がちょうど S になる最長の連続部分配列の長さを出力してください。無ければ0。', h1: '累積和の最初の出現位置を記録する。', h2: 's-S が出ていれば長さを更新。', ref: 'S=int(input())\na=list(map(int,input().split()))\nfirst={0:-1}\ns=0\nbest=0\nfor i,x in enumerate(a):\n    s+=x\n    if s-S in first:\n        if i-first[s-S]>best:\n            best=i-first[s-S]\n    if s not in first:\n        first[s]=i\nprint(best)', tip: '最長は「累積和の最初の出現」を記録する。最短や個数とは持つ情報が違う。', ins: ['3\n1 2 1 1 1\n', '0\n1 -1 1 -1\n', '5\n5\n', '10\n1 2 3\n', '6\n1 2 3 3\n', '4\n4 1 1 2 4\n'] })

t({ lv: 685, concept: 'DP: 最小の分割でパリンドローム', title: '回文分割の最小カット数', tags: ['dp', '文字列'], io: '文字列 s が1行で与えられます。', ask: 's を回文の連結に分割するときの最小カット数を出力してください。', h1: '部分文字列が回文かを2次元で前計算。', h2: 'dp[i]=先頭i文字の最小カット。', ref: 's=input()\nn=len(s)\nif n==0:\n    print(0)\nelse:\n    pal=[[False]*n for _ in range(n)]\n    for i in range(n):\n        pal[i][i]=True\n    for length in range(2,n+1):\n        for i in range(n-length+1):\n            j=i+length-1\n            if s[i]==s[j] and (length==2 or pal[i+1][j-1]):\n                pal[i][j]=True\n    INF=float("inf")\n    dp=[0]*(n+1)\n    for i in range(1,n+1):\n        if pal[0][i-1]:\n            dp[i]=0\n        else:\n            best=INF\n            for j in range(1,i):\n                if pal[j][i-1] and dp[j]+1<best:\n                    best=dp[j]+1\n            dp[i]=best\n    print(dp[n])', tip: '回文分割の最小カットは「回文判定の前計算＋接頭辞DP」。一気に回文なら0カット。', ins: ['aab\n', 'a\n', 'ab\n', 'aba\n', 'abccba\n', 'noonabbad\n'] })

t({ lv: 686, concept: 'DP: 最大の和をもつ部分列(隣接k離す)', title: 'k以上離して選ぶ最大和', tags: ['dp'], io: '1行目に k、2行目に整数列が与えられます。', ask: '選んだ添字どうしが k 以上離れるように選び、要素の和を最大化した値を出力してください(空選択は0)。', h1: 'dp[i]=i番目までの最大和。', h2: 'dp[i]=max(dp[i-1], a[i]+dp[i-k])。', ref: 'k=int(input())\na=list(map(int,input().split()))\nn=len(a)\ndp=[0]*(n+1)\nfor i in range(1,n+1):\n    take=a[i-1]+(dp[i-k] if i-k>=0 else 0)\n    if a[i-1]<0:\n        take=dp[i-1]\n    dp[i]=max(dp[i-1],take)\nprint(dp[n])', tip: '「k離す」制約は dp[i-k] から遷移する1次元DP。隣接禁止(k=2)の一般化。', ins: ['2\n1 2 3 1\n', '2\n2 7 9 3 1\n', '1\n1 2 3\n', '3\n5 1 1 5\n', '2\n-1 -2 -3\n', '2\n10 1 1 10\n'] })

t({ lv: 687, concept: 'DP: 文字列の連結で作れるか', title: '2文字列の交互混合で作れるか', tags: ['dp', '文字列'], io: '1行目に s1、2行目に s2、3行目に s3 が与えられます。', ask: 's3 が s1 と s2 の文字順序を保った交互混合(インターリーブ)で作れるなら yes、できないなら no を出力してください。', h1: 'dp[i][j]=s1のi文字とs2のj文字でs3のi+j文字を作れるか。', h2: 's3の次文字がs1かs2のどちらに一致するかで遷移。', ref: 's1=input()\ns2=input()\ns3=input()\nn=len(s1)\nm=len(s2)\nif n+m!=len(s3):\n    print("no")\nelse:\n    dp=[[False]*(m+1) for _ in range(n+1)]\n    dp[0][0]=True\n    for i in range(n+1):\n        for j in range(m+1):\n            if i>0 and dp[i-1][j] and s1[i-1]==s3[i+j-1]:\n                dp[i][j]=True\n            if j>0 and dp[i][j-1] and s2[j-1]==s3[i+j-1]:\n                dp[i][j]=True\n    print("yes" if dp[n][m] else "no")', tip: 'インターリーブ判定は2次元DP。s3の各文字をs1かs2のどちらから取るかを表す。', ins: ['aab\naxy\naaxaby\n', 'ab\ncd\nacbd\n', 'ab\ncd\nabdc\n', '\nabc\nabc\n', 'a\nb\nba\n', 'aa\nab\naaba\n'] })

t({ lv: 688, concept: 'DP: 最長の重複部分文字列長', title: '繰り返し現れる最長部分文字列長', tags: ['dp', '文字列'], io: '文字列 s が1行で与えられます。', ask: '2回以上(位置をずらして)現れる最長の連続部分文字列の長さを出力してください。無ければ0。', h1: '長さで二分探索する。', h2: 'その長さの部分文字列を集合で重複検出。', ref: 's=input()\nn=len(s)\ndef has_dup(L):\n    if L==0:\n        return True\n    seen=set()\n    for i in range(n-L+1):\n        sub=s[i:i+L]\n        if sub in seen:\n            return True\n        seen.add(sub)\n    return False\nlo=0\nhi=n-1 if n>0 else 0\nans=0\nwhile lo<=hi:\n    mid=(lo+hi)//2\n    if has_dup(mid):\n        ans=mid\n        lo=mid+1\n    else:\n        hi=mid-1\nprint(ans)', tip: '最長重複部分文字列は「長さで二分探索＋集合で重複検出」。接尾辞配列でも解ける。', ins: ['banana\n', 'abcd\n', 'aaaa\n', 'a\n', 'abcabc\n', 'mississippi\n'] })

t({ lv: 689, concept: 'DP: 連続する部分列の積の最大(0含む)', title: '0を含む配列の最大部分積', tags: ['dp'], io: '整数列が1行で与えられます(0を含み得る)。', ask: '空でない連続部分配列の積の最大値を出力してください。', h1: '0でリセットされる。', h2: '最大積と最小積を同時に追う(負×負対策)。', ref: 'a=list(map(int,input().split()))\nbest=a[0]\ncur_max=a[0]\ncur_min=a[0]\nfor x in a[1:]:\n    cand=(x,cur_max*x,cur_min*x)\n    cur_max=max(cand)\n    cur_min=min(cand)\n    if cur_max>best:\n        best=cur_max\nprint(best)', tip: '0を含む場合も最大/最小積を追えば自然に処理される(0で実質リセットされる)。', ins: ['2 3 -2 4\n', '-2 0 -1\n', '0 2\n', '-2 0 -3 0 -4\n', '2 -5 -2 -4 3\n', '0\n'] })

t({ lv: 690, concept: 'スライディングウィンドウ: 和≤Sの最長', title: '和がS以下の最長連続部分配列', tags: ['配列'], io: '1行目に S、2行目に非負整数列が与えられます。', ask: '和が S 以下になる最長の連続部分配列の長さを出力してください。', h1: '右端を伸ばしながら和を加える。', h2: '和が S を超えたら左端を縮める。', ref: 'S=int(input())\na=list(map(int,input().split()))\nn=len(a)\nleft=0\ncur=0\nbest=0\nfor right in range(n):\n    cur+=a[right]\n    while cur>S and left<=right:\n        cur-=a[left]\n        left+=1\n    if right-left+1>best:\n        best=right-left+1\nprint(best)', tip: '非負配列で「和≤Sの最長窓」は単調性があるのでスライディングウィンドウで O(n)。', ins: ['5\n1 2 1 0 3\n', '0\n0 0 0\n', '3\n4 1 1\n', '10\n1 2 3\n', '2\n3 3 3\n', '7\n1 2 3 4\n'] })

t({ lv: 691, concept: 'DP: 最大の正方形の周囲(1の枠)', title: '1の枠で囲まれた最大正方形の面積', tags: ['dp'], io: '1行目に R C、続く R 行に C 個の 0/1 が与えられます。', ask: '辺がすべて1の(中は問わない)最大の正方形の面積を出力してください。無ければ0。', h1: '各セルから左・上に連続する1の数を前計算。', h2: '右下を固定し、辺長を縮めながら枠が1か確認。', ref: 'first=input().split()\nR=int(first[0])\nC=int(first[1])\ng=[list(map(int,input().split())) for _ in range(R)]\nleft=[[0]*C for _ in range(R)]\nup=[[0]*C for _ in range(R)]\nfor i in range(R):\n    for j in range(C):\n        if g[i][j]==1:\n            left[i][j]=(left[i][j-1] if j>0 else 0)+1\n            up[i][j]=(up[i-1][j] if i>0 else 0)+1\nbest=0\nfor i in range(R):\n    for j in range(C):\n        if g[i][j]==1:\n            maxside=min(left[i][j],up[i][j])\n            for side in range(maxside,0,-1):\n                if side*side<=best:\n                    break\n                ti=i-side+1\n                tj=j-side+1\n                if up[i][tj]>=side and left[ti][j]>=side:\n                    best=side*side\n                    break\nprint(best)', tip: '枠だけ1の正方形は「左連続・上連続」を前計算し、右下から辺長を縮めて枠4辺を検査する。', ins: ['3 3\n1 1 1\n1 0 1\n1 1 1\n', '2 2\n1 1\n1 1\n', '2 2\n1 0\n0 1\n', '1 1\n1\n', '3 4\n1 1 1 0\n1 0 1 0\n1 1 1 0\n', '3 3\n0 0 0\n0 0 0\n0 0 0\n'] })

t({ lv: 692, concept: 'DP: 文字列を回文にする最小挿入', title: '回文にする最小挿入数', tags: ['dp', '文字列'], io: '文字列 s が1行で与えられます。', ask: '文字を挿入して s を回文にするのに必要な最小挿入数を出力してください。', h1: '最長回文部分列(LPS)を求める。', h2: '答え = |s| - LPS。', ref: 's=input()\nn=len(s)\nif n==0:\n    print(0)\nelse:\n    dp=[[0]*n for _ in range(n)]\n    for i in range(n):\n        dp[i][i]=1\n    for length in range(2,n+1):\n        for i in range(n-length+1):\n            j=i+length-1\n            if s[i]==s[j]:\n                dp[i][j]=(dp[i+1][j-1] if i+1<=j-1 else 0)+2\n            else:\n                dp[i][j]=max(dp[i+1][j],dp[i][j-1])\n    print(n-dp[0][n-1])', tip: '回文にする最小挿入数は |s| − 最長回文部分列。残せる回文以外を補えばよい。', ins: ['ab\n', 'aa\n', 'abc\n', 'aba\n', 'abcda\n', 'leetcode\n'] })

t({ lv: 693, concept: 'DP: 最大スコアの掛け算順', title: '配列とマルチプライヤの最大スコア', tags: ['dp'], io: '1行目に n m、2行目に長さ n の数列、3行目に長さ m のマルチプライヤが与えられます(m<=n)。', ask: '各操作で配列の左端か右端を取り、i 番目のマルチプライヤと掛けて加算します。m 操作後のスコアの最大値を出力してください。', h1: 'dp[i][l]=i回操作・左から l 個取った最大。', h2: '左端か右端を取る2択で遷移。', ref: 'first=input().split()\nn=int(first[0])\nm=int(first[1])\na=list(map(int,input().split()))\nmul=list(map(int,input().split()))\nNEG=float("-inf")\ndp=[[NEG]*(m+1) for _ in range(m+1)]\ndp[0][0]=0\nfor i in range(1,m+1):\n    for l in range(0,i+1):\n        r=i-l\n        best=NEG\n        if l>0 and dp[i-1][l-1]!=NEG:\n            best=max(best,dp[i-1][l-1]+mul[i-1]*a[l-1])\n        if r>0 and dp[i-1][l]!=NEG:\n            best=max(best,dp[i-1][l]+mul[i-1]*a[n-r])\n        dp[i][l]=best\nprint(max(dp[m][l] for l in range(m+1)))', tip: '両端取りは「操作回数 i と左から取った数 l」を状態にするDP。右から取った数は i-l で決まる。', ins: ['3 2\n1 2 3\n3 2\n', '5 3\n-5 -3 -3 -2 7\n-10 -5 3 4 6\n', '1 1\n5\n2\n', '2 2\n1 2\n1 1\n', '4 2\n-1 -2 -3 -4\n1 1\n', '3 3\n1 2 3\n1 1 1\n'] })

t({ lv: 694, concept: 'DP: ビット全探索での部分集合最大', title: '条件を満たす部分集合の最大和(全探索)', tags: ['bit演算'], io: '1行目に n と上限 W、2行目に n 個の重さが与えられます。', ask: '部分集合の重さ合計が W 以下になるもののうち最大の合計を出力してください(n<=20)。', h1: '全 2^n 通りを列挙する。', h2: 'W 以下の最大和を取る。', ref: 'first=input().split()\nn=int(first[0])\nW=int(first[1])\na=list(map(int,input().split()))\nbest=0\nfor mask in range(1<<n):\n    s=0\n    for i in range(n):\n        if (mask>>i)&1:\n            s+=a[i]\n    if s<=W and s>best:\n        best=s\nprint(best)', tip: 'n<=20 程度なら 2^n のビット全探索が単純で確実。半分全列挙で n<=40 まで伸ばせる。', ins: ['3 5\n2 3 4\n', '1 0\n5\n', '4 10\n3 3 3 3\n', '3 100\n1 2 3\n', '2 1\n5 5\n', '5 7\n1 2 3 4 5\n'] })

t({ lv: 695, concept: 'DP: 最長の連続同符号区間', title: '最長の同符号連続区間の長さ', tags: ['配列'], io: '0を含まない整数列が1行で与えられます。', ask: '符号が変わらず続く最長の連続区間の長さを出力してください。', h1: '直前と符号が同じかを見る。', h2: '同じなら伸ばし、違えば1にリセット。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nif n==0:\n    print(0)\nelse:\n    best=1\n    cur=1\n    for i in range(1,n):\n        if (a[i]>0)==(a[i-1]>0):\n            cur+=1\n            if cur>best:\n                best=cur\n        else:\n            cur=1\n    print(best)', tip: '同符号区間はリセット型の線形走査。符号の真偽(>0)を比べるだけ。', ins: ['1 2 -1 -2 -3 1\n', '1 1 1\n', '-1 -2 -3\n', '1 -1 1 -1\n', '5\n', '-1 -1 2 2 2 -3\n'] })

t({ lv: 696, concept: 'DP: 最小の遷移コスト(数直線ジャンプ)', title: '数直線のジャンプ最小コスト', tags: ['dp'], io: '高さの列が1行で与えられます(カエルが i から i+1 または i+2 へ跳ぶ、コストは高さの差の絶対値)。', ask: '最初の足場から最後の足場までの最小総コストを出力してください。', h1: 'dp[i]=足場iまでの最小コスト。', h2: 'dp[i]=min(dp[i-1]+|h-h|, dp[i-2]+|h-h|)。', ref: 'h=list(map(int,input().split()))\nn=len(h)\nif n<=1:\n    print(0)\nelse:\n    dp=[0]*n\n    dp[1]=abs(h[1]-h[0])\n    for i in range(2,n):\n        dp[i]=min(dp[i-1]+abs(h[i]-h[i-1]),dp[i-2]+abs(h[i]-h[i-2]))\n    print(dp[n-1])', tip: 'カエル跳びは典型的な1次元DP(AtCoder EDPC A)。1歩か2歩の遷移を min で取る。', ins: ['10 30 40 20\n', '10 10\n', '30 10 60 10 60 50\n', '5\n', '1 2 3 4 5\n', '0 100 0 100\n'] })

t({ lv: 697, concept: 'DP: k回まで跳べるカエル', title: 'k歩まで跳べる数直線の最小コスト', tags: ['dp'], io: '1行目に k、2行目に高さの列が与えられます(i から最大 k 先まで跳べる、コストは高さの差の絶対値)。', ask: '最初から最後の足場までの最小総コストを出力してください。', h1: 'dp[i]=min over 1..k の dp[i-j]+|h差|。', h2: '範囲外を避けて遷移する。', ref: 'k=int(input())\nh=list(map(int,input().split()))\nn=len(h)\nif n<=1:\n    print(0)\nelse:\n    INF=float("inf")\n    dp=[INF]*n\n    dp[0]=0\n    for i in range(1,n):\n        for j in range(1,k+1):\n            if i-j>=0:\n                c=dp[i-j]+abs(h[i]-h[i-j])\n                if c<dp[i]:\n                    dp[i]=c\n    print(dp[n-1])', tip: 'k歩版カエル跳び(EDPC B)。遷移数が増えるだけで構造は同じ O(nk)。', ins: ['3\n10 30 40 50 20\n', '2\n10 30 40 20\n', '1\n10 20 30\n', '2\n10 10\n', '4\n40 10 20 70 80 10\n', '3\n1\n'] })

t({ lv: 698, concept: 'DP: 区切り文字列の最大スコア', title: '文字列を数に区切る最大和(桁)', tags: ['dp', '文字列'], io: '1行目に数字文字列 s、2行目に1片の最大桁数 k が与えられます。', ask: 's を高々 k 桁の連続片に区切り、各片を整数とみなした和を最大化した値を出力してください。', h1: 'dp[i]=先頭i文字の最大和。', h2: 'dp[i]=max(dp[i-len]+片の値)。', ref: 's=input()\nk=int(input())\nn=len(s)\nNEG=float("-inf")\ndp=[NEG]*(n+1)\ndp[0]=0\nfor i in range(1,n+1):\n    for length in range(1,k+1):\n        if i-length>=0 and dp[i-length]!=NEG:\n            val=int(s[i-length:i])\n            if dp[i-length]+val>dp[i]:\n                dp[i]=dp[i-length]+val\nprint(dp[n])', tip: '文字列の区切りDPは「最後の片の長さ」で場合分け。最大k桁なので遷移は高々k通り。', ins: ['1234\n2\n', '99\n1\n', '5\n3\n', '111\n2\n', '1010\n2\n', '987\n1\n'] })

t({ lv: 699, concept: 'DP: 最大の連続和(2次元1列圧縮)', title: '各行最大の連続和の合計', tags: ['dp'], io: '1行目に R C、続く R 行に C 個の整数が与えられます。', ask: '各行について「空でない連続部分配列の最大和」を求め、その合計を出力してください。', h1: '行ごとにKadaneを適用する。', h2: '各行の最大部分和を足す。', ref: 'first=input().split()\nR=int(first[0])\nC=int(first[1])\ntotal=0\nfor _ in range(R):\n    row=list(map(int,input().split()))\n    cur=row[0]\n    best=row[0]\n    for x in row[1:]:\n        cur=max(x,cur+x)\n        if cur>best:\n            best=cur\n    total+=best\nprint(total)', tip: '行ごとに独立してKadaneを適用し合計するだけ。2次元の最大部分長方形とは別問題。', ins: ['2 3\n1 -2 3\n-1 2 -1\n', '1 1\n5\n', '2 2\n-1 -2\n-3 -4\n', '3 3\n1 2 3\n-1 -1 -1\n4 -2 4\n', '1 4\n-1 2 3 -1\n', '2 2\n5 5\n5 5\n'] })

export const CATALOG = TASKS
