// 生成タスク 第74波：各レベル3問化フェーズ(2)。lv071〜131 の薄い49段に3問目を追加。
// 基礎〜入門帯: 数/行列/ベクトル/集合/評価指標/数論入門。重複なし・決定的・採点一意。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 71, concept: 'リスト: 最初の負の数の位置', title: '最初のマイナスはどこ', tags: ['リスト'], io: '整数列が1行で空白区切りで与えられます。', ask: '最初に現れる負の数の位置(1始まり)を出力してください。負の数が無ければ none。', h1: '順に見て最初の該当で止める。', h2: 'enumerate と break、見つからなければ else 節。', ref: 'a=list(map(int,input().split()))\nfor i,x in enumerate(a,1):\n    if x<0:\n        print(i)\n        break\nelse:\n    print("none")', tip: 'forのelse節は「breakせずに完走したとき」に走る、Python独特の構文。線形探索の「見つからなかった」を旗変数なしで書ける。', ins: ['3 1 -4 1\n', '1 2 3\n', '-5\n', '0 0 -1 -2\n', '7 8 9 -1\n', '2\n'] })

t({ lv: 72, concept: '整数: ゾロ目の判定', title: '全部同じ数字か', tags: ['整数'], io: '正整数 n が1行で与えられます。', ask: '十進表記の全ての桁が同じ数字(ゾロ目)なら yes、そうでなければ no を出力してください。', h1: '文字の種類数を見る。', h2: 'set(str(n)) のサイズが1か。', ref: 'n=input()\nprint("yes" if len(set(n))==1 else "no")', tip: 'setに潰して種類を数えるのは「全部同じ/全部違う」の両方に効く万能ワザ。ゾロ目 111…1 はレピュニットと呼ばれ素数性の研究対象でもある。', ins: ['777\n', '123\n', '5\n', '1111\n', '100\n', '99\n'] })

t({ lv: 73, concept: '整数: 繰り上がりを無視した足し算', title: '繰り上がらない不思議な筆算', tags: ['整数'], io: '非負整数 a b が空白区切りで1行で与えられます。', ask: '筆算の各桁で「繰り上がりを無視して」足した結果(各桁 (x+y) mod 10)を整数として出力してください。', h1: '桁数を揃えて桁ごとに処理する。', h2: 'zfillで0埋めしてからペアごとに(mod 10)、先頭の0は int() が消してくれる。', ref: 'a,b=input().split()\nw=max(len(a),len(b))\na=a.zfill(w)\nb=b.zfill(w)\nprint(int("".join(str((int(x)+int(y))%10) for x,y in zip(a,b))))', tip: '繰り上がり無視の加算は「10進のXOR」にあたる演算。ニム値の計算(2進)や誤り検出の桁演算に通じる、桁独立の世界の入り口。', ins: ['17 25\n', '99 11\n', '5 5\n', '123 456\n', '999 1\n', '0 7\n'] })

t({ lv: 74, concept: '行列: 鞍点の探索', title: '行では最小、列では最大の場所', tags: ['行列'], io: '1行目に H W、続く H 行に相異なる整数の行列が与えられます。', ask: '「自分の行で最小、かつ自分の列で最大」の要素(鞍点)があればその値を、無ければ none を出力してください。', h1: '各行の最小値の候補だけ調べれば足りる。', h2: 'その候補が自分の列の最大かを確かめる。', ref: 'h,w=map(int,input().split())\ng=[list(map(int,input().split())) for _ in range(h)]\nans="none"\nfor i in range(h):\n    v=min(g[i])\n    j=g[i].index(v)\n    if all(g[k][j]<=v for k in range(h)):\n        ans=v\nprint(ans)', tip: 'ゲーム理論のミニマックスの原風景。行プレイヤーと列プレイヤーの利害が釣り合う点で、相異なる値なら鞍点は高々1つしかない。', ins: ['2 2\n1 2\n3 4\n', '2 2\n4 3\n2 1\n', '3 3\n7 8 9\n4 5 6\n1 2 3\n', '2 3\n5 1 9\n8 2 7\n', '1 1\n5\n', '2 2\n1 4\n2 3\n'] })

t({ lv: 75, concept: '行列: 行を合計の昇順に並べ替え', title: '行を売上順に並べ直す', tags: ['行列', 'ソート'], io: '1行目に H W、続く H 行に行列が与えられます。', ask: '各行をその合計の昇順(同点は元の順)に並べ替え,各行を1行ずつ出力してください。', h1: '行のリストをキーつきでソートする。', h2: 'sorted(rows, key=sum)。Pythonのソートは安定なので同点は元の順のまま。', ref: 'h,w=map(int,input().split())\ng=[list(map(int,input().split())) for _ in range(h)]\nfor row in sorted(g,key=sum):\n    print(*row)', tip: '「行そのもの」を要素としてソートできるのがリストのリストの強み。key=sum のように関数を渡す発想はDataFrameのsort_valuesへ直結する。', ins: ['3 2\n3 4\n1 1\n2 2\n', '2 3\n1 1 1\n0 0 0\n', '2 2\n5 5\n5 5\n', '3 1\n9\n1\n5\n', '2 2\n-1 -2\n0 0\n', '3 3\n1 2 3\n3 2 1\n0 0 1\n'] })

t({ lv: 76, concept: '数: 下1桁の繰り返し周期', title: '一の位はいつ一巡するか', tags: ['数'], io: '正整数 a が1行で与えられます。', ask: 'a¹, a², a³, … の一の位の並びが繰り返す最小の周期を出力してください。', h1: '一の位だけ追えばよい。', h2: '最初の値に戻るまで掛け続ける。周期は必ず4以下。', ref: 'a=int(input())\nstart=a%10\nx=start\nc=1\nwhile True:\n    x=x*a%10\n    if x==start:\n        break\n    c+=1\nprint(c)', tip: '2,3,7,8は周期4、4,9は周期2、0,1,5,6は周期1。この表が「巨大な指数の一の位」を暗算にする(896の a^(b^c) 問題の土台)。', ins: ['2\n', '5\n', '7\n', '4\n', '9\n', '10\n'] })

t({ lv: 77, concept: '行列: 行列どうしの足し算', title: '2つの表を重ねて足す', tags: ['行列'], io: '1行目に H W、続く H 行に行列A、さらに H 行に行列Bが与えられます。', ask: 'A+B(要素ごとの和)を H 行で出力してください。', h1: '同じ位置どうしを足す。', h2: 'zipで行のペアを作り、さらにzipで要素のペアを作る。', ref: 'h,w=map(int,input().split())\nA=[list(map(int,input().split())) for _ in range(h)]\nB=[list(map(int,input().split())) for _ in range(h)]\nfor ra,rb in zip(A,B):\n    print(*[x+y for x,y in zip(ra,rb)])', tip: '要素ごとの演算(element-wise)はzipの2重使いが素直。numpyなら A+B の1式になる、という高級化の階段の1段目。', ins: ['2 2\n1 2\n3 4\n10 20\n30 40\n', '1 3\n1 1 1\n2 2 2\n', '2 1\n5\n-5\n1\n1\n', '1 1\n0\n0\n', '2 2\n1 0\n0 1\n0 1\n1 0\n', '3 2\n1 2\n3 4\n5 6\n6 5\n4 3\n2 1\n'] })

t({ lv: 78, concept: '行列: 四隅の合計', title: '四つ角を足す', tags: ['行列'], io: '1行目に H W (どちらも2以上)、続く H 行に行列が与えられます。', ask: '行列の四隅(左上・右上・左下・右下)の合計を出力してください。', h1: '負の添字で端に触れる。', h2: 'g[0][0]+g[0][-1]+g[-1][0]+g[-1][-1]。', ref: 'h,w=map(int,input().split())\ng=[list(map(int,input().split())) for _ in range(h)]\nprint(g[0][0]+g[0][-1]+g[-1][0]+g[-1][-1])', tip: '負の添字は2次元でも各軸で独立に効く。端・隅への言及が多い行列処理では [0] と [-1] の対で書く癖が読みやすさを生む。', ins: ['2 2\n1 2\n3 4\n', '3 3\n1 0 2\n0 0 0\n3 0 4\n', '2 3\n1 2 3\n4 5 6\n', '3 2\n-1 -2\n0 0\n-3 -4\n', '2 2\n5 5\n5 5\n', '4 4\n9 0 0 8\n0 0 0 0\n0 0 0 0\n7 0 0 6\n'] })

t({ lv: 79, concept: '行列: 行ごとの最大の合計', title: '各行のエースの合計', tags: ['行列'], io: '1行目に H W、続く H 行に行列が与えられます。', ask: '各行の最大値を合計した値を出力してください。', h1: '行ごとにmaxを取る。', h2: 'sum(max(row) for row in g)。', ref: 'h,w=map(int,input().split())\ng=[list(map(int,input().split())) for _ in range(h)]\nprint(sum(max(r) for r in g))', tip: 'map/genexpで「各行に集計→さらに集計」の2段が1行に潰れる。行を列に変えたければzip(*g)で転置してから同じ式、が対になる技。', ins: ['2 2\n1 2\n3 4\n', '1 3\n5 1 5\n', '3 1\n1\n2\n3\n', '2 3\n-1 -2 -3\n-4 -5 -6\n', '2 2\n0 0\n0 0\n', '3 3\n1 9 1\n9 1 1\n1 1 9\n'] })

t({ lv: 81, concept: 'ベクトル: 2次元の外積', title: '2つの矢印の外積', tags: ['ベクトル'], io: '2つのベクトル x1 y1 x2 y2 が空白区切りで1行で与えられます。', ask: '2次元の外積 x1·y2 − y1·x2 を出力してください。', h1: 'たすき掛けの差。', h2: '符号が「左回りか右回りか」を表す。', ref: 'x1,y1,x2,y2=map(int,input().split())\nprint(x1*y2-y1*x2)', tip: '外積の絶対値は平行四辺形の面積、符号は回転の向き。凸包・線分交差・面積計算と、計算幾何のほぼ全てがこの1行の上に建つ。', ins: ['1 0 0 1\n', '0 1 1 0\n', '2 3 4 6\n', '1 2 3 4\n', '-1 2 2 1\n', '3 0 0 5\n'] })

t({ lv: 82, concept: '幾何: 二等辺三角形の判定', title: '二等辺か、それとも不等辺か', tags: ['幾何'], io: '三角形の3辺 a b c が空白区切りで1行で与えられます(三角形は成立します)。', ask: '2辺以上が等しい(二等辺、正三角形も含む)なら yes、3辺すべて異なるなら no を出力してください。', h1: '等しいペアが1組でもあるか。', h2: '集合にして要素数が3未満か見る。', ref: 'a,b,c=map(int,input().split())\nprint("yes" if len({a,b,c})<3 else "no")', tip: '「どれか2つが等しい」は3つの比較を or で並べるより set の大きさが簡潔。正三角形はサイズ1、二等辺は2、不等辺は3と分類まで読める。', ins: ['5 5 3\n', '3 4 5\n', '7 7 7\n', '2 3 2\n', '6 5 5\n', '9 10 11\n'] })

t({ lv: 83, concept: 'ハッシュ: 最頻値はただ1つか', title: '1位タイはいるか', tags: ['ハッシュ'], io: '整数列が1行で空白区切りで与えられます。', ask: '最も多く現れる値がただ1つなら yes、最多が複数の値で並んでいるなら no を出力してください。', h1: '最大の出現回数を求める。', h2: 'その回数を持つ値がいくつあるか数える。', ref: 'from collections import Counter\nc=Counter(input().split())\nm=max(c.values())\nprint("yes" if sum(1 for v in c.values() if v==m)==1 else "no")', tip: '「1位が一意か」は最大値を2回使う集計(最大→その個数)。モードの一意性は統計でも重要で、多峰分布の検出の第一歩になる。', ins: ['1 1 2\n', '1 1 2 2\n', '5\n', '3 3 3 1\n', '1 2 3\n', '7 7 8 8 8\n'] })

t({ lv: 84, concept: 'ハッシュ: 値×出現回数の最大', title: '存在感が最大の値', tags: ['ハッシュ'], io: '正整数の列が1行で空白区切りで与えられます。', ask: '各値について「値×出現回数」を計算し、その最大値を出力してください。', h1: 'Counterで回数を得る。', h2: 'v*c の最大を取る。', ref: 'from collections import Counter\nc=Counter(map(int,input().split()))\nprint(max(v*k for v,k in c.items()))', tip: '頻度と値の積は「削除して稼ぐ」系DPの前処理でも登場する重み付けの基本。items()でキーと値を同時に回すのが辞書集計の定番形。', ins: ['1 2 2 3\n', '5 5 5\n', '10 1 1 1 1 1 1 1 1 1 1 1\n', '7\n', '3 3 2 2 2\n', '4 4 6\n'] })

t({ lv: 86, concept: '幾何: 点が長方形の内側か', title: '的の中に入っているか', tags: ['幾何'], io: '長方形の対角 x1 y1 x2 y2 (x1<x2, y1<y2) と点 px py が空白区切りで1行で与えられます。', ask: '点が長方形の内側(境界を含む)にあるなら yes、外なら no を出力してください。', h1: 'xとyを別々に範囲チェック。', h2: 'x1<=px<=x2 の連鎖比較が2本。', ref: 'x1,y1,x2,y2,px,py=map(int,input().split())\nprint("yes" if x1<=px<=x2 and y1<=py<=y2 else "no")', tip: '軸に平行な矩形の内外は座標ごとに独立、が2次元を2つの1次元に分ける第一歩。当たり判定・クリッピングの最小部品。', ins: ['0 0 10 10 5 5\n', '0 0 10 10 10 0\n', '0 0 10 10 11 5\n', '1 1 3 3 0 2\n', '-5 -5 5 5 0 0\n', '0 0 1 1 1 1\n'] })

t({ lv: 87, concept: '幾何: 平行四辺形の4つ目の頂点', title: '残り1つの角はどこか', tags: ['幾何'], io: '平行四辺形の連続する3頂点 A B C の座標 ax ay bx by cx cy が空白区切りで1行で与えられます。', ask: '4つ目の頂点 D (ABCDの順で平行四辺形になる点)の座標を空白区切りで出力してください。', h1: '対角線は互いの中点で交わる。', h2: 'D = A + C − B。', ref: 'ax,ay,bx,by,cx,cy=map(int,input().split())\nprint(ax+cx-bx,ay+cy-by)', tip: '「中点が一致する」条件をベクトルの式に直すと足し引きだけになる。図形の性質を座標の等式に翻訳する解析幾何の入り口。', ins: ['0 0 1 0 1 1\n', '0 0 2 1 3 4\n', '1 1 2 2 3 1\n', '0 0 0 3 4 3\n', '-1 -1 1 -1 1 1\n', '2 3 5 7 11 13\n'] })

t({ lv: 88, concept: 'リスト: 最大値を除いた合計', title: 'エース抜きの合計点', tags: ['リスト'], io: '整数列(2個以上)が1行で空白区切りで与えられます。', ask: '最大値を1つだけ除いた残りの合計を出力してください。', h1: '全体の和から最大を引く。', h2: 'sum(a) − max(a)。', ref: 'a=list(map(int,input().split()))\nprint(sum(a)-max(a))', tip: '「除いてから足す」より「足してから引く」方が短くて速い。最大が複数あっても1つだけ引く、という仕様の確認が地味に大事。', ins: ['1 2 3\n', '5 5 5\n', '10 1\n', '-1 -2 -3\n', '0 0 7\n', '4 9 2 9\n'] })

t({ lv: 89, concept: 'リスト: 3つおきの和', title: '3人ごとの代表の合計', tags: ['リスト'], io: '整数列が1行で空白区切りで与えられます。', ask: '先頭(0番目)から3つおき(0,3,6,…番目)の要素の合計を出力してください。', h1: 'ステップつきスライス。', h2: 'a[::3] の和。', ref: 'a=list(map(int,input().split()))\nprint(sum(a[::3]))', tip: 'スライスの第3引数(ステップ)は飛び飛びアクセスの最短表現。a[1::3] a[2::3] と開始をずらせば3グループへの分配も1行ずつで書ける。', ins: ['1 2 3 4 5 6 7\n', '5\n', '1 1 1 1 1 1\n', '10 0 0 20 0 0 30\n', '-1 2 3 -4\n', '0 9 9\n'] })

t({ lv: 91, concept: '辞書: 合計が最大のキー', title: '売上トップの商品はどれ', tags: ['辞書'], io: '1行目に件数 n、続く n 行に「商品名 数値」が与えられます(同じ商品名は合算)。', ask: '数値の合計が最大の商品名を出力してください(同点なら辞書順で最小の名前)。', h1: '辞書に足し込んでから最大を探す。', h2: 'min(items, key=lambda kv:(−合計, 名前)) のタプルキー。', ref: 'n=int(input())\nd={}\nfor _ in range(n):\n    k,v=input().split()\n    d[k]=d.get(k,0)+int(v)\nprint(min(d.items(),key=lambda kv:(-kv[1],kv[0]))[0])', tip: 'get(k,0)+x の足し込みは集計の頻出イディオム(defaultdictでも可)。集計→argmaxの2段構えはSQLの GROUP BY + ORDER BY と同じ思考。', ins: ['3\napple 3\nbanana 5\napple 4\n', '2\nx 1\ny 1\n', '1\nz 10\n', '4\na 2\nb 2\na 1\nb 1\n', '3\np 0\nq 0\nr 0\n', '2\ndog 7\ncat 7\n'] })

t({ lv: 92, concept: '統計: 度数分布のビン集計', title: '点数帯ごとの人数', tags: ['統計'], io: '1行目にビンの幅 w、2行目に非負整数の列が与えられます。', ask: '値 v が属すビン番号は v//w です。ビン0から最大ビンまで、各ビンの個数を空白区切りで出力してください。', h1: 'v//w でビン番号が決まる。', h2: '最大ビンまでのカウント配列に加算する。', ref: 'w=int(input())\na=list(map(int,input().split()))\nm=max(a)//w\ncnt=[0]*(m+1)\nfor v in a:\n    cnt[v//w]+=1\nprint(*cnt)', tip: 'ヒストグラムの土台。切り捨て割り算でビンに落とす発想は、バケットソート・ハッシュ分割・座標のグリッド化まで全部同じ。', ins: ['10\n5 15 25 12\n', '2\n0 1 2 3 4\n', '5\n4 4 4\n', '100\n99\n', '3\n0 8\n', '1\n2 2 0\n'] })

t({ lv: 93, concept: '数え上げ: 和が偶数のペア数', title: '足すと偶数になる2人組', tags: ['数え上げ'], io: '整数列が1行で空白区切りで与えられます。', ask: 'i<j で a[i]+a[j] が偶数になるペアの個数を出力してください。', h1: '和が偶数になるのは偶+偶か奇+奇。', h2: '偶数の個数 e と奇数の個数 o から C(e,2)+C(o,2)。', ref: 'a=list(map(int,input().split()))\ne=sum(1 for x in a if x%2==0)\no=len(a)-e\nprint(e*(e-1)//2+o*(o-1)//2)', tip: '全ペアを回さずに「クラス分け→組合せ」で数える。パリティで2クラス、mod kならkクラス、と一般化が一直線に見える形。', ins: ['1 2 3 4\n', '2 4 6\n', '1 3 5 7\n', '1 2\n', '5\n', '0 0 1\n'] })

t({ lv: 94, concept: '累積和: 半分を超える瞬間', title: '合計の半分を超えるのはいつ', tags: ['累積和'], io: '正整数の列が1行で空白区切りで与えられます。', ask: '先頭から足していき、累積が全体の合計の半分を初めて厳密に超える位置(1始まり)を出力してください。', h1: '合計を先に求める。', h2: '2×累積 > 合計 となる最初の i。', ref: 'a=list(map(int,input().split()))\ntotal=sum(a)\ns=0\nfor i,x in enumerate(a,1):\n    s+=x\n    if 2*s>total:\n        print(i)\n        break', tip: '「半分と比べる」は2倍して整数のまま比較すると誤差ゼロ。重みの中央値(weighted median)を求める操作そのもので、1次元の施設配置に直結する。', ins: ['1 1 1 1\n', '5 1 1\n', '1 2 3\n', '10\n', '1 1 5\n', '2 2 2\n'] })

t({ lv: 96, concept: '文字列: 部分列として拾える最長の接頭辞', title: 'お手本をどこまでなぞれるか', tags: ['文字列'], io: '1行目に文字列 S、2行目に目標 T が与えられます。', ask: 'S の文字を順に拾って T の接頭辞を作るとき、作れる最長の接頭辞の長さを出力してください。', h1: 'Tのポインタを1本持つ。', h2: 'Sを1周し、一致するたびにポインタを進める。', ref: 's=input()\nt=input()\nj=0\nfor c in s:\n    if j<len(t) and c==t[j]:\n        j+=1\nprint(j)', tip: '2ポインタの片側固定版。この「どこまで進めたか」の値は、Tを完成させるのに必要なSの周回数を求める問題(shuffled string)の部品になる。', ins: ['abcde\nace\n', 'abc\nxyz\n', 'aab\naaa\n', 'hello\nhello\n', 'xyz\n\n', 'ababab\nbbb\n'] })

t({ lv: 97, concept: '文字列: 共通の文字を取り除く', title: '相手にもある文字を消す', tags: ['文字列'], io: '1行目と2行目に英小文字の文字列が与えられます。', ask: '1つ目の文字列から「2つ目にも現れる文字」を全て取り除いた結果を出力してください(空になったら empty)。', h1: '2つ目を集合にする。', h2: '内包表記でフィルタして join。', ref: 's=input()\nt=set(input())\nres="".join(c for c in s if c not in t)\nprint(res if res else "empty")', tip: '「in 集合」はO(1)、「in 文字列」はO(長さ)。フィルタの相手は必ずsetにする、が文字列処理の速度と読みやすさの両取り。', ins: ['hello\nl\n', 'abcdef\nace\n', 'aaa\na\n', 'python\nxyz\n', 'test\nt\n', 'abc\nabc\n'] })

t({ lv: 98, concept: '文字列: 数字を英単語で読む', title: '数字を英語で読み上げる', tags: ['文字列'], io: '数字だけの文字列が1行で与えられます。', ask: '各桁を英単語(zero, one, two, three, four, five, six, seven, eight, nine)に置き換え、空白区切りで出力してください。', h1: '単語表をリストで持つ。', h2: '各桁で表を引いて join。', ref: 'words=["zero","one","two","three","four","five","six","seven","eight","nine"]\nprint(" ".join(words[int(c)] for c in input()))', tip: '変換表を「データ」として持てばifの列は要らない。表を差し替えるだけでモールス信号にも点字にも化ける、テーブル駆動の考え方。', ins: ['123\n', '0\n', '907\n', '55\n', '2468\n', '10\n'] })

t({ lv: 99, concept: '文字列: 抜けているアルファベット', title: 'パングラムまであと何文字', tags: ['文字列'], io: '英小文字と空白の文章が1行で与えられます。', ask: 'a〜z のうち文章に現れない文字を昇順に繋げて出力してください。全て現れていれば pangram。', h1: '文章の文字集合を作る。', h2: '全アルファベットとの差集合を並べる。', ref: 'import string\ns=set(input())\nmissing="".join(c for c in string.ascii_lowercase if c not in s)\nprint(missing if missing else "pangram")', tip: 'string.ascii_lowercase は自分で"abc…"と書かないための定数。集合の差で「足りないもの」を出す形は、在庫チェックや必須項目の検証と同型。', ins: ['the quick brown fox jumps over the lazy dog\n', 'hello world\n', 'abcdefghijklm\n', 'a\n', 'nopqrstuvwxyz abcdefghijklm\n', 'zzz\n'] })

t({ lv: 101, concept: '行列: 上下左右の和が最大のマス', title: '十字に足して一番大きい場所', tags: ['行列'], io: '1行目に H W、続く H 行に行列が与えられます。', ask: '各マスについて「自分+存在する上下左右の隣」の合計を計算し、その最大値を出力してください。', h1: '4方向を範囲チェックしながら足す。', h2: '方向のリスト [(1,0),(-1,0),(0,1),(0,-1)] でループする。', ref: 'h,w=map(int,input().split())\ng=[list(map(int,input().split())) for _ in range(h)]\nbest=None\nfor i in range(h):\n    for j in range(w):\n        s=g[i][j]\n        for di,dj in ((1,0),(-1,0),(0,1),(0,-1)):\n            ni,nj=i+di,j+dj\n            if 0<=ni<h and 0<=nj<w:\n                s+=g[ni][nj]\n        if best is None or s>best:\n            best=s\nprint(best)', tip: '方向ベクトルの表+範囲チェックは、グリッド処理の共通言語。畳み込みフィルタ(画像のぼかし・エッジ検出)のカーネルもこの形の親戚。', ins: ['2 2\n1 2\n3 4\n', '1 1\n5\n', '3 3\n0 1 0\n1 5 1\n0 1 0\n', '1 3\n1 2 3\n', '2 3\n-1 -1 -1\n-1 -1 -1\n', '3 2\n1 1\n1 9\n1 1\n'] })

t({ lv: 102, concept: 'リスト: 隣どうし全部違うか', title: '連続かぶりゼロの判定', tags: ['リスト'], io: '整数列が1行で空白区切りで与えられます。', ask: '隣り合う要素が全て異なるなら yes、同じ値が隣り合う箇所があれば no を出力してください。', h1: '隣接ペアを順に比べる。', h2: 'all(x!=y for x,y in zip(a,a[1:]))。', ref: 'a=input().split()\nprint("yes" if all(x!=y for x,y in zip(a,a[1:])) else "no")', tip: 'all+genexpは「全部〜か」を最短で書く定番。1つでも違反があれば途中で止まる(短絡)ので効率も良い。', ins: ['1 2 1 2\n', '1 1 2\n', '5\n', '3 4 4\n', '1 2 3 4 5\n', '7 8 7 8 8\n'] })

t({ lv: 103, concept: '行列: 対角優位の判定', title: '対角が牛耳っている行列か', tags: ['行列'], io: '1行目に n、続く n 行に n×n の行列が与えられます。', ask: '全ての行で「対角成分の絶対値 ≥ その行の他の成分の絶対値の和」が成り立つ(対角優位)なら yes、そうでなければ no を出力してください。', h1: '行ごとに対角とそれ以外を分けて足す。', h2: '|a[i][i]| と Σ|a[i][j]| (j≠i) を比較。', ref: 'n=int(input())\ng=[list(map(int,input().split())) for _ in range(n)]\nok=all(abs(g[i][i])>=sum(abs(g[i][j]) for j in range(n) if j!=i) for i in range(n))\nprint("yes" if ok else "no")', tip: '対角優位ならガウス消去がピボット選択なしで安定、ヤコビ法が収束、と数値計算の保証がいくつも付いてくる実用的な性質。', ins: ['2\n3 1\n1 3\n', '2\n1 2\n2 1\n', '1\n5\n', '3\n4 1 1\n1 5 2\n0 1 2\n', '2\n-3 2\n2 -3\n', '3\n2 1 1\n1 2 1\n1 1 2\n'] })

t({ lv: 104, concept: '行列: 最大要素の位置', title: '一番大きい値の場所', tags: ['行列'], io: '1行目に H W、続く H 行に行列が与えられます。', ask: '最大の要素がある位置を「行 列」(どちらも1始まり)で出力してください(複数なら行優先で最初のもの)。', h1: '走査しながら最大と位置を更新。', h2: '「より大きいときだけ」更新すれば最初の位置が残る。', ref: 'h,w=map(int,input().split())\ng=[list(map(int,input().split())) for _ in range(h)]\nbi,bj=0,0\nfor i in range(h):\n    for j in range(w):\n        if g[i][j]>g[bi][bj]:\n            bi,bj=i,j\nprint(bi+1,bj+1)', tip: 'argmax(値でなく場所)は「>」か「>=」かでタイブレークが決まる。numpyの unravel_index(argmax) に対応する手書き版。', ins: ['2 2\n1 2\n3 4\n', '2 2\n4 4\n4 4\n', '1 3\n5 9 1\n', '3 1\n1\n7\n3\n', '2 3\n-5 -1 -9\n-2 -8 -3\n', '1 1\n0\n'] })

t({ lv: 106, concept: 'ソート: 昇順にしてk個おきに選ぶ', title: '並べてから等間隔に抜き出す', tags: ['ソート'], io: '1行目に k、2行目に整数列が与えられます。', ask: '昇順にソートした列から、先頭を含めて k 個おき(0,k,2k,…番目)に選んだ要素を空白区切りで出力してください。', h1: 'ソートしてからスライス。', h2: 'sorted(a)[::k]。', ref: 'k=int(input())\na=sorted(map(int,input().split()))\nprint(*a[::k])', tip: 'ソート+ステップスライスで「分位点のサンプリング」の素朴版になる。百分位・中央値の一般化(quantile)への感覚づくり。', ins: ['2\n5 1 4 2 3\n', '1\n3 1 2\n', '3\n9 8 7 6 5 4 3\n', '2\n1 1\n', '4\n1 2 3\n', '2\n10 20 30 40\n'] })

t({ lv: 107, concept: '集合: 3つのうち2つ以上にある値の数', title: '多数決で残る値', tags: ['集合'], io: '3行にそれぞれ整数列が与えられます。', ask: '3つのリストのうち2つ以上に(その値が)現れる相異なる値の個数を出力してください。', h1: '集合3つの共通部分の組合せ。', h2: '(A∩B)∪(B∩C)∪(A∩C) の大きさ。', ref: 'A=set(input().split())\nB=set(input().split())\nC=set(input().split())\nprint(len((A&B)|(B&C)|(A&C)))', tip: '「k個以上に現れる」は共通部分の和で書ける(3つなら3項)。集合演算子の組合せで論理条件が式になる、集合代数の練習台。', ins: ['1 2 3\n2 3 4\n3 4 5\n', '1 2\n3 4\n5 6\n', '1\n1\n1\n', '1 2 3\n1 2 3\n4 5\n', '7 8\n8 9\n7 9\n', '1 1 2\n2\n3\n'] })

t({ lv: 108, concept: '集合: 部分集合かの判定', title: '品揃えは注文をカバーするか', tags: ['集合'], io: '1行目に集合A、2行目に集合Bの要素が空白区切りで与えられます。', ask: 'A の全要素が B に含まれる(AがBの部分集合)なら yes、そうでなければ no を出力してください。', h1: '差集合が空かどうかでも判定できる。', h2: 'set(A) <= set(B) の比較演算子が使える。', ref: 'A=set(input().split())\nB=set(input().split())\nprint("yes" if A<=B else "no")', tip: '集合の <= は包含関係。issubset/issuperset のメソッド名よりも数学記号に近い演算子で書けるのがPythonらしいところ。', ins: ['1 2\n1 2 3\n', '1 4\n1 2 3\n', '5\n5\n', '1 2 3\n1 2\n', '\n1 2\n', 'a b\nb a c\n'] })

t({ lv: 109, concept: '集合: ジャッカード係数', title: 'どれだけ似ている2つの集合', tags: ['集合'], io: '1行目と2行目に集合の要素が空白区切りで与えられます(どちらも空ではありません)。', ask: 'ジャッカード係数 |A∩B| / |A∪B| を小数第2位まで出力してください。', h1: '共通部分と和集合のサイズを数える。', h2: 'len(A&B)/len(A|B) を :.2f で。', ref: 'A=set(input().split())\nB=set(input().split())\nprint(f"{len(A&B)/len(A|B):.2f}")', tip: '文書の類似度・重複検出の定番指標。「共通÷全体」という定義は、タグ・購買履歴・n-gramどんな集合にもそのまま使える。', ins: ['1 2 3\n2 3 4\n', '1 2\n1 2\n', '1\n2\n', 'a b c d\nc d e f\n', 'x\nx y z\n', '1 2 3 4 5\n5\n'] })

t({ lv: 111, concept: '評価: 決定係数R2', title: '予測はどれだけ説明できたか', tags: ['評価'], io: '1行目に実測値、2行目に予測値(同じ個数)が与えられます。', ask: '決定係数 R² = 1 − SSE/SST (SSEは残差平方和、SSTは実測の平均からの平方和)を小数第2位まで出力してください(SSTは0になりません)。', h1: '2種類の平方和を計算する。', h2: 'SSE=Σ(実測−予測)²、SST=Σ(実測−平均)²。', ref: 'y=list(map(int,input().split()))\np=list(map(int,input().split()))\nm=sum(y)/len(y)\nsse=sum((a-b)**2 for a,b in zip(y,p))\nsst=sum((a-m)**2 for a in y)\nprint(f"{1-sse/sst:.2f}")', tip: '「平均で当てるだけのモデル」を基準(R²=0)に、どれだけ良いかを測る相対指標。負にもなり得る(平均より悪い)ことは意外と知られていない。', ins: ['1 2 3\n1 2 3\n', '1 2 3\n2 2 2\n', '1 2 3 4\n1 2 3 5\n', '10 20 30\n12 18 30\n', '4 5 6\n5 5 5\n', '0 10\n1 9\n'] })

t({ lv: 112, concept: '評価: 平均絶対パーセント誤差', title: '外れ具合をパーセントで', tags: ['評価'], io: '1行目に実測値(0を含まない)、2行目に予測値が与えられます。', ask: 'MAPE = 平均(|実測−予測| ÷ |実測|) × 100 を小数第1位まで出力してください。', h1: '各点の相対誤差を出して平均する。', h2: 'abs((a−b)/a) の平均に100を掛ける。', ref: 'y=list(map(int,input().split()))\np=list(map(int,input().split()))\nn=len(y)\nprint(f"{sum(abs((a-b)/a) for a,b in zip(y,p))/n*100:.1f}")', tip: '「実測が0だと定義できない」「小さい実測に過敏」というMAPEの弱点は実務の頻出論点。sMAPEやMAEとの使い分けの入り口になる。', ins: ['100 200\n90 220\n', '10 10\n10 10\n', '50\n60\n', '100 100 100\n99 101 100\n', '10 20\n12 25\n', '200 400\n150 500\n'] })

t({ lv: 113, concept: '評価: 適合率と再現率', title: '見つけた中の正解、正解の中の発見', tags: ['評価'], io: '1行目に正解ラベル(0/1)、2行目に予測ラベル(0/1)が空白区切りで与えられます(TPは0になりません…ではなく、予測の1と正解の1がそれぞれ1つ以上あります)。', ask: '適合率(precision = TP/(TP+FP))と再現率(recall = TP/(TP+FN))を、この順に空白区切りで小数第2位まで出力してください。', h1: 'TP/FP/FNを数える。', h2: 'zipで対にして (正解,予測) のパターンごとにカウント。', ref: 'y=list(map(int,input().split()))\np=list(map(int,input().split()))\ntp=sum(1 for a,b in zip(y,p) if a==1 and b==1)\nfp=sum(1 for a,b in zip(y,p) if a==0 and b==1)\nfn=sum(1 for a,b in zip(y,p) if a==1 and b==0)\nprint(f"{tp/(tp+fp):.2f} {tp/(tp+fn):.2f}")', tip: '「警報を絞れば適合率が上がり、緩めれば再現率が上がる」トレードオフの2指標。混同行列の4マスを手で数える経験が理解の土台になる。', ins: ['1 1 0 0\n1 0 1 0\n', '1 1 1\n1 1 1\n', '1 0 1 0 1\n1 1 1 0 0\n', '0 1\n1 1\n', '1 1 0\n1 0 1\n', '1 0 0 1\n1 0 0 1\n'] })

t({ lv: 114, concept: '評価: F1スコア', title: 'バランスの取れた1つの点数', tags: ['評価'], io: '1行目に正解ラベル(0/1)、2行目に予測ラベル(0/1)が与えられます(TPが1以上あります)。', ask: 'F1スコア(適合率と再現率の調和平均 = 2TP/(2TP+FP+FN))を小数第2位まで出力してください。', h1: 'TP/FP/FNから直接計算できる。', h2: '2TP/(2TP+FP+FN) の1本の式で書ける。', ref: 'y=list(map(int,input().split()))\np=list(map(int,input().split()))\ntp=sum(1 for a,b in zip(y,p) if a==1 and b==1)\nfp=sum(1 for a,b in zip(y,p) if a==0 and b==1)\nfn=sum(1 for a,b in zip(y,p) if a==1 and b==0)\nprint(f"{2*tp/(2*tp+fp+fn):.2f}")', tip: '調和平均は「低い方に強く引っ張られる」ため、片方だけ良いモデルを高評価しない。算術平均でなく調和平均を使う理由まで言えると一段深い。', ins: ['1 1 0 0\n1 0 1 0\n', '1 1 1\n1 1 1\n', '1 0 1 0 1\n1 1 1 0 0\n', '0 1\n1 1\n', '1 1 1 1\n1 0 0 0\n', '1 0 0 1\n1 0 0 1\n'] })

t({ lv: 118, concept: '数論: 回文数の約数の個数', title: '約数の中の回文たち', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: 'n の約数のうち十進表記が回文であるものの個数を出力してください(1桁も回文)。', h1: '約数を列挙して判定する。', h2: '文字列の反転比較を約数ごとに。', ref: 'n=int(input())\ncnt=0\ni=1\nwhile i*i<=n:\n    if n%i==0:\n        for d in {i,n//i}:\n            s=str(d)\n            if s==s[::-1]:\n                cnt+=1\n    i+=1\nprint(cnt)', tip: '√nまでの列挙で(d, n/d)を対で処理し、平方数のときの二重カウントをsetで潰す。列挙の骨格に判定を差し込む合成問題の型。', ins: ['12\n', '121\n', '7\n', '100\n', '66\n', '1\n'] })

t({ lv: 119, concept: '数論: 累積GCDの列', title: 'だんだん固まる公約数', tags: ['数論'], io: '正整数の列が1行で空白区切りで与えられます。', ask: '先頭からの累積GCD(1個目、1〜2個目のGCD、1〜3個目のGCD、…)を空白区切りで出力してください。', h1: 'GCDを畳み込みながら記録する。', h2: 'g = gcd(g, x) を繰り返す。', ref: 'import math\na=list(map(int,input().split()))\ng=0\nout=[]\nfor x in a:\n    g=math.gcd(g,x)\n    out.append(g)\nprint(*out)', tip: '累積GCDは単調に割る方向へしか動かず、一度1になったらずっと1。この「急速に安定する」性質が区間GCD種類数のO(log)の根拠だった。', ins: ['12 18 27\n', '4 8 16\n', '5 7\n', '9\n', '6 10 15\n', '100 75 50 25\n'] })

t({ lv: 121, concept: 'bit全探索: 和が素数の部分集合数', title: '足すと素数になる選び方', tags: ['bit全探索', '数論'], io: '正整数の列(10個以下)が1行で空白区切りで与えられます。', ask: '空でない部分集合のうち、要素の和が素数になるものの個数を出力してください。', h1: '部分集合をビットで全列挙。', h2: '和を作って素数判定にかける。', ref: 'a=list(map(int,input().split()))\nn=len(a)\ndef isp(x):\n    if x<2:\n        return False\n    i=2\n    while i*i<=x:\n        if x%i==0:\n            return False\n        i+=1\n    return True\ncnt=0\nfor mask in range(1,1<<n):\n    s=sum(a[i] for i in range(n) if mask>>i&1)\n    if isp(s):\n        cnt+=1\nprint(cnt)', tip: '2^n列挙+性質判定の合成は、bit全探索の応用の基本形。判定関数を差し替えるだけで平方数版・回文版が量産できる。', ins: ['1 2\n', '2 3\n', '1 1 1\n', '4 6\n', '2 2 2 2\n', '5\n'] })

t({ lv: 122, concept: '幾何: 点群の重心', title: 'みんなの真ん中の点', tags: ['幾何'], io: '1行目に点数 n、続く n 行に座標 x y が与えられます。', ask: 'n 個の点の重心(座標の平均)を「x座標 y座標」の順に小数第1位まで出力してください。', h1: 'xとyを別々に平均する。', h2: 'それぞれ合計÷個数。', ref: 'n=int(input())\nsx=sy=0\nfor _ in range(n):\n    x,y=map(int,input().split())\n    sx+=x\n    sy+=y\nprint(f"{sx/n:.1f} {sy/n:.1f}")', tip: '点の重心は座標ごとの独立な平均。クラスタの中心(k-means)や物体の質量中心と同じ計算で、面の重心(面積重み付き)とは別物という区別も大切。', ins: ['2\n0 0\n2 2\n', '3\n0 0\n3 0\n0 3\n', '1\n5 7\n', '4\n1 1\n1 3\n3 1\n3 3\n', '2\n-1 -1\n1 1\n', '3\n10 0\n0 10\n5 5\n'] })

t({ lv: 123, concept: '数論: 2番目に小さい素因数', title: '2種類目の素因数', tags: ['数論'], io: '相異なる素因数を2つ以上持つ正整数 n が1行で与えられます。', ask: 'n の相異なる素因数のうち2番目に小さいものを出力してください。', h1: '試し割りで素因数を順に見つける。', h2: '見つけた素因数で割り尽くしてから次を探すと、2つ目がそのまま答え。', ref: 'n=int(input())\np=2\nfound=0\nwhile True:\n    if n%p==0:\n        found+=1\n        if found==2:\n            print(p)\n            break\n        while n%p==0:\n            n//=p\n    p+=1\n    if p*p>n and n>1 and found==1:\n        print(n)\n        break', tip: '「割り尽くしてから進む」試し割りは素因数を昇順に吐き出す。残った n>1 が最後の大きな素因数、という後始末を2つ目にも適用する。', ins: ['6\n', '12\n', '15\n', '100\n', '21\n', '2310\n'] })

t({ lv: 124, concept: '数論: nと2nの間の素数', title: 'ベルトランの区間の素数', tags: ['数論'], io: '正整数 n (n≥1) が1行で与えられます。', ask: 'n より大きく 2n 以下の素数の個数を出力してください(ベルトランの仮説によれば必ず1個以上)。', h1: '範囲の各数を素数判定。', h2: '試し割り判定を n+1..2n に適用。', ref: 'n=int(input())\ndef isp(x):\n    if x<2:\n        return False\n    i=2\n    while i*i<=x:\n        if x%i==0:\n            return False\n        i+=1\n    return True\nprint(sum(1 for x in range(n+1,2*n+1) if isp(x)))', tip: '「nと2nの間に必ず素数がある」ベルトランの仮説はチェビシェフが証明し、エルデシュが18歳で初等的証明を与えた逸話つき。数値実験で1以上を体感できる。', ins: ['1\n', '2\n', '4\n', '10\n', '25\n', '100\n'] })

t({ lv: 125, concept: '数論: 区間で約数が最多の数', title: 'この範囲で一番割られ上手', tags: ['数論'], io: 'a b が空白区切りで1行で与えられます (a≤b)。', ask: 'a 以上 b 以下で約数の個数が最も多い数を出力してください(同数なら最小のもの)。', h1: '約数の個数を数える関数を作る。', h2: '「より多いときだけ」更新すれば同数のとき最小が残る。', ref: 'a,b=map(int,input().split())\ndef d(x):\n    c=0\n    i=1\n    while i*i<=x:\n        if x%i==0:\n            c+=2 if i*i!=x else 1\n        i+=1\n    return c\nbest=a\nbd=d(a)\nfor x in range(a+1,b+1):\n    dx=d(x)\n    if dx>bd:\n        best,bd=x,dx\nprint(best)', tip: 'argmaxのタイブレークは更新条件の等号ひとつで決まる。高度合成数(記録更新者)の区間版と考えると、探索と数論が繋がって見える。', ins: ['1 10\n', '10 20\n', '1 1\n', '50 60\n', '2 6\n', '90 100\n'] })

t({ lv: 126, concept: '数論: べき乗の大小比較', title: 'どちらのべき乗が大きい', tags: ['数論'], io: 'a b c d が空白区切りで1行で与えられます(全て正整数)。', ask: 'a^b と c^d を比べ、前者が大きければ first、後者なら second、等しければ equal を出力してください。', h1: 'Pythonなら直接計算できる。', h2: '多倍長整数なので a**b をそのまま比較してよい(対数を使うと誤差の罠がある)。', ref: 'a,b,c,d=map(int,input().split())\nx=a**b\ny=c**d\nprint("first" if x>y else "second" if x<y else "equal")', tip: '他言語では log比較(誤差あり)や工夫が要る問題が、Pythonでは厳密比較で終わる。「言語の得意を知って使う」もアルゴリズム力のうち。', ins: ['2 10 10 3\n', '2 3 3 2\n', '5 2 2 5\n', '4 3 8 2\n', '1 100 100 1\n', '6 6 6 6\n'] })

t({ lv: 127, concept: 'bit演算: 固定幅の左ローテート', title: 'ビットをぐるっと回す', tags: ['bit演算'], io: '幅 w、整数 x (0≤x<2^w)、回転量 k が空白区切りで1行で与えられます。', ask: 'x を w ビット幅で左に k 回転した値を出力してください(あふれたビットは右端に戻る)。', h1: '左シフトのあふれを右へ回す。', h2: '((x<<k)|(x>>(w−k))) & ((1<<w)−1)。kはw で剰余を取る。', ref: 'w,x,k=map(int,input().split())\nk%=w\nmask=(1<<w)-1\nprint(((x<<k)|(x>>(w-k)))&mask if k else x)', tip: 'ハッシュ関数や暗号(ChaChaなど)の心臓部で回り続けている演算。固定幅のマスクを忘れるとPythonの無限精度整数では「あふれない」ことがバグになる。', ins: ['8 1 1\n', '8 128 1\n', '4 9 2\n', '8 170 4\n', '5 1 5\n', '8 255 3\n'] })

t({ lv: 128, concept: 'bit演算: ビットが交互か判定', title: '0と1が交互に並ぶ数か', tags: ['bit演算'], io: '正整数 n が1行で与えられます。', ask: '2進表記で0と1が交互に並んでいる(例 101, 1010)なら yes、そうでなければ no を出力してください。', h1: '1つずらした自分とXORしてみる。', h2: 'x = n ^ (n>>1) が全ビット1になる ⇔ 交互。全1判定は x & (x+1) == 0。', ref: 'n=int(input())\nx=n^(n>>1)\nprint("yes" if x&(x+1)==0 else "no")', tip: '「ずらしてXOR」は隣接ビットの関係を一括で取り出す技。グレイコードの定義式と同じ形が判定にも使える、ビット演算の教科書的1行。', ins: ['5\n', '10\n', '7\n', '1\n', '11\n', '42\n'] })

t({ lv: 129, concept: '整数: 連続2数の積(矩形数)か', title: 'k×(k+1)の形の数か', tags: ['整数'], io: '正整数 n が1行で与えられます。', ask: 'n が連続する2つの正整数の積 k(k+1) の形(矩形数)なら k を出力し、違えば -1 を出力してください。', h1: 'kを1から試す。', h2: 'k(k+1) が n を超えたら打ち切り。isqrtから逆算する方法もある。', ref: 'n=int(input())\nk=1\nwhile k*(k+1)<n:\n    k+=1\nprint(k if k*(k+1)==n else -1)', tip: '矩形数は三角数の2倍。判定は√n近傍の1点チェックに落とせる(k=isqrt(n))ので、ループ版と式版の両方を書いて突き合わせたい。', ins: ['6\n', '12\n', '7\n', '2\n', '110\n', '90\n'] })

t({ lv: 131, concept: '数論: n以下の素数べきの個数', title: 'pのk乗の形の数を数える', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: '2 以上 n 以下で素数のべき乗 p^k (pは素数, k≥1) の形の数の個数を出力してください。', h1: '各数について素数べき判定をする。', h2: '最小素因数で割り尽くして1になるか。', ref: 'n=int(input())\ndef ispp(x):\n    if x<2:\n        return False\n    f=2\n    while f*f<=x:\n        if x%f==0:\n            while x%f==0:\n                x//=f\n            return x==1\n        f+=1\n    return True\nprint(sum(1 for x in range(2,n+1) if ispp(x)))', tip: '素数べきは「素因数が1種類だけ」の数。lcm(1..n) の素材でもあり、数論のあちこちで「素数の代わりに使える」便利なクラス。', ins: ['10\n', '2\n', '20\n', '31\n', '50\n', '100\n'] })

export const CATALOG = TASKS
