// 生成タスク 第85波：各レベル3問化フェーズ(12)。lv576〜599, 601〜625 の薄い49段に3問目を追加。
// グラフ応用帯+変化球。クラスタ3問まで可・言い換え水増し禁止。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 576, concept: 'BFS: 迷路の最短経路の本数', title: '最短の抜け道は何通り', tags: ['BFS', 'グリッド'], io: '1行目に H W、続く H 行に盤面(S 開始、G 目標、# 壁、. 通路)が与えられます。', ask: 'S から G への最短経路が何通りあるかを出力してください(到達不能なら 0)。', h1: 'グラフでの最短経路の本数(同レベル既出)の盤面版。', h2: 'BFSの距離順に本数を足し込む。', ref: 'from collections import deque\nh,w=map(int,input().split())\ng=[input() for _ in range(h)]\nstart=next((i,j) for i in range(h) for j in range(w) if g[i][j]=="S")\ngoal=next((i,j) for i in range(h) for j in range(w) if g[i][j]=="G")\ndist=[[-1]*w for _ in range(h)]\ncnt=[[0]*w for _ in range(h)]\ndist[start[0]][start[1]]=0\ncnt[start[0]][start[1]]=1\nq=deque([start])\nwhile q:\n    i,j=q.popleft()\n    for di,dj in ((1,0),(-1,0),(0,1),(0,-1)):\n        ni,nj=i+di,j+dj\n        if 0<=ni<h and 0<=nj<w and g[ni][nj]!="#":\n            if dist[ni][nj]<0:\n                dist[ni][nj]=dist[i][j]+1\n                cnt[ni][nj]=cnt[i][j]\n                q.append((ni,nj))\n            elif dist[ni][nj]==dist[i][j]+1:\n                cnt[ni][nj]+=cnt[i][j]\nprint(cnt[goal[0]][goal[1]])', tip: '距離が1増える遷移でだけ本数を加算する、BFS+DPの合成。障害物のない盤面なら二項係数に一致するので、格子経路の公式が検算に使える。', ins: ['2 2\nS.\n.G\n', '1 3\nS.G\n', '3 3\nS..\n...\n..G\n', '2 3\nS#G\n...\n', '2 2\nS#\n#G\n', '3 3\nS.#\n.#.\n#.G\n'] })

t({ lv: 577, concept: '木: 道の真ん中の頂点', title: '道のりのちょうど半分', tags: ['木'], io: '1行目に頂点数 n、続く n−1 行に木の辺 u v、最終行に2頂点 s t (道の頂点数は奇数) が与えられます。', ask: 's から t への道のちょうど真ん中にある頂点を出力してください。', h1: '道を実際に復元する。', h2: '親を記録するDFS/BFSでtからsへ遡る。', ref: 'from collections import deque\nn=int(input())\ng=[[] for _ in range(n+1)]\nfor _ in range(n-1):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\ns,t2=map(int,input().split())\npar=[0]*(n+1)\npar[s]=-1\nq=deque([s])\nwhile q:\n    x=q.popleft()\n    for y in g[x]:\n        if par[y]==0 and y!=s:\n            par[y]=x\n            q.append(y)\npath=[t2]\nwhile path[-1]!=s:\n    path.append(par[path[-1]])\nprint(path[len(path)//2])', tip: '2頂点の道の中点は「両端から等距離の頂点」で、木の中心の局所版。LCAを使えば深さの計算だけでO(log n)で特定できる、が素朴な復元が一番間違えない。', ins: ['3\n1 2\n2 3\n1 3\n', '5\n1 2\n2 3\n3 4\n4 5\n1 5\n', '3\n1 2\n1 3\n2 2\n', '5\n1 2\n1 3\n3 4\n3 5\n4 5\n', '7\n1 2\n2 3\n3 4\n4 5\n5 6\n6 7\n1 7\n', '3\n1 2\n2 3\n3 1\n'] })

t({ lv: 578, concept: 'グリッド: 塗りつぶした盤面の出力', title: 'バケツツールの中身', tags: ['グリッド', 'DFS'], io: '1行目に H W、続く H 行に数字の盤面、最終行に「r c v」(マス(r,c)から色vで塗りつぶす。1始まり)が与えられます。', ask: '(r,c) と同じ色で上下左右につながる領域全体を色 v に塗り替えた盤面を、1行ずつ出力してください。', h1: 'ペイントソフトのバケツ機能そのもの。', h2: '元の色と新しい色が同じときは何もしない(無限ループ防止)。', ref: 'h,w=map(int,input().split())\ng=[list(input()) for _ in range(h)]\nr,c,v=input().split()\nr=int(r)-1\nc=int(c)-1\nold=g[r][c]\nif old!=v:\n    st=[(r,c)]\n    g[r][c]=v\n    while st:\n        i,j=st.pop()\n        for di,dj in ((1,0),(-1,0),(0,1),(0,-1)):\n            ni,nj=i+di,j+dj\n            if 0<=ni<h and 0<=nj<w and g[ni][nj]==old:\n                g[ni][nj]=v\n                st.append((ni,nj))\nfor row in g:\n    print("".join(row))', tip: '「元の色と同じ色で塗る」と判定なしでは無限ループする、フラッドフィルの有名な罠。領域を数える問題群(既出)の探索がそのまま書き換えに転用できる。', ins: ['2 2\n11\n10\n1 1 2\n', '1 3\n121\n1 2 9\n', '2 2\n11\n11\n2 2 5\n', '3 3\n000\n010\n000\n2 2 3\n', '1 1\n7\n1 1 7\n', '2 3\n123\n123\n1 1 8\n'] })

t({ lv: 579, concept: 'BFS: どちらの偶奇でも行ける頂点の数', title: '偶数歩でも奇数歩でも', tags: ['BFS', 'グラフ'], io: '1行目に頂点数 n と辺数 m、続く m 行に無向辺 u v が与えられます。', ask: '頂点1から偶数歩でも奇数歩でも(歩数はちょうどその歩数の歩き方が存在すればよい)到達できる頂点の個数を出力してください。', h1: '偶数歩で到達(同レベル既出)の両立版。', h2: '(頂点, 偶奇)の2倍のグラフでBFSし、両方の状態に届く頂点を数える。', ref: 'from collections import deque\nn,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\nseen=[[False]*2 for _ in range(n+1)]\nseen[1][0]=True\nq=deque([(1,0)])\nwhile q:\n    v,p=q.popleft()\n    for to in g[v]:\n        if not seen[to][1-p]:\n            seen[to][1-p]=True\n            q.append((to,1-p))\nprint(sum(1 for v in range(1,n+1) if seen[v][0] and seen[v][1]))', tip: '両方の偶奇で届く頂点がある ⇔ その成分に奇閉路がある(二部でない)。頂点を2つに複製する「状態積グラフ」は偶奇に限らず mod k や所持品にも一般化する。', ins: ['3 3\n1 2\n2 3\n1 3\n', '2 1\n1 2\n', '4 4\n1 2\n2 3\n3 4\n4 1\n', '3 2\n1 2\n2 3\n', '4 5\n1 2\n2 3\n3 4\n4 1\n1 3\n', '1 0\n'] })

t({ lv: 580, concept: 'bit演算: 1ビット反転で作る最大', title: 'どのビットを裏返すと得か', tags: ['bit演算'], io: '正整数 n が1行で与えられます。', ask: 'n の2進表記(先頭の1から)のどれか1桁をちょうど1つ反転してできる値の最大を出力してください。', h1: '0を1にできるなら上位ほど得。', h2: '全ての桁を試す総当たりで十分。', ref: 'n=int(input())\nL=n.bit_length()\nprint(max(n^(1<<b) for b in range(L)))', tip: '最上位以外の最も高い0を立てるのが最善で、全部1(2^k−1)のときだけ仕方なく最下位を消す。XORによる「反転」の使い方と貪欲の境界例が同時に学べる。', ins: ['5\n', '7\n', '1\n', '10\n', '8\n', '6\n'] })

t({ lv: 581, concept: 'グリッド: 島がk個になる最小の水位', title: '潮位を合わせて島の数を注文', tags: ['グリッド', '二分探索'], io: '1行目に H W、続く H 行に高さの格子、最終行に k が与えられます(条件を満たす水位が存在)。', ask: '水位 L のとき「高さが L より大きいマス」が上下左右で作る島の数がちょうど k になる最小の非負整数 L を出力してください。', h1: '水位Lの島の数(同レベル既出)を関数にして探す。', h2: 'Lを0から順に試す。', ref: 'h,w=map(int,input().split())\ng=[list(map(int,input().split())) for _ in range(h)]\nk=int(input())\ndef islands(L):\n    seen=[[False]*w for _ in range(h)]\n    c=0\n    for si in range(h):\n        for sj in range(w):\n            if g[si][sj]>L and not seen[si][sj]:\n                c+=1\n                st=[(si,sj)]\n                seen[si][sj]=True\n                while st:\n                    i,j=st.pop()\n                    for di,dj in ((1,0),(-1,0),(0,1),(0,-1)):\n                        ni,nj=i+di,j+dj\n                        if 0<=ni<h and 0<=nj<w and g[ni][nj]>L and not seen[ni][nj]:\n                            seen[ni][nj]=True\n                            st.append((ni,nj))\n    return c\nL=0\nwhile islands(L)!=k:\n    L+=1\nprint(L)', tip: '水位を上げると島は「増えてから消える」ので単調ではなく、素朴な全探索が正義。単調でない指標に二分探索を使えない、という反面教師も学べる。', ins: ['1 3\n2 1 2\n2\n', '1 1\n5\n1\n', '2 2\n3 3\n3 3\n1\n', '1 5\n1 3 1 3 1\n2\n', '2 3\n2 1 2\n1 1 1\n2\n', '1 4\n4 2 4 2\n2\n'] })

t({ lv: 582, concept: 'DFS: 行きがけの訪問順序', title: '深追い探索の足取り', tags: ['DFS', 'グラフ'], io: '1行目に頂点数 n と辺数 m、続く m 行に無向辺 u v が与えられます。', ask: '頂点1から深さ優先探索(隣接頂点は番号の小さい順に訪ねる)をしたときの訪問順を空白区切りで出力してください(到達できる頂点のみ)。', h1: 'BFSの訪問順(同レベル既出)のDFS版。', h2: '再帰かスタックで。隣接リストのソートを忘れずに。', ref: 'import sys\nsys.setrecursionlimit(100000)\nn,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\nfor v in range(1,n+1):\n    g[v].sort()\nseen=[False]*(n+1)\nout=[]\ndef dfs(v):\n    seen[v]=True\n    out.append(v)\n    for to in g[v]:\n        if not seen[to]:\n            dfs(to)\ndfs(1)\nprint(" ".join(map(str,out)))', tip: 'BFSが波紋、DFSは一本槍。スタック実装で同じ順を出すには隣接を「逆順に積む」必要がある——再帰との等価性が崩れる定番の落とし穴がある。', ins: ['4 3\n1 2\n1 3\n2 4\n', '3 2\n1 3\n1 2\n', '5 4\n1 2\n2 3\n1 4\n4 5\n', '3 0\n', '4 4\n1 2\n2 3\n3 1\n3 4\n', '6 5\n1 3\n3 5\n1 2\n2 4\n4 6\n'] })

t({ lv: 583, concept: '窓: 各窓の和の一覧', title: 'ずらしながら合計を記録', tags: ['窓'], io: '1行目に k、2行目に整数列(長さk以上)が与えられます。', ask: '長さ k の各窓の和を左から順に空白区切りで出力してください。', h1: '最大値の列・最小値の列(既出)の和版。', h2: '出る要素を引き、入る要素を足す差分更新。', ref: 'k=int(input())\na=list(map(int,input().split()))\ns=sum(a[:k])\nout=[s]\nfor i in range(k,len(a)):\n    s+=a[i]-a[i-k]\n    out.append(s)\nprint(" ".join(map(str,out)))', tip: '移動合計(rolling sum)は移動平均の分子で、時系列の前処理の最頻出。差分更新O(1)と毎回総和O(k)の差は、窓が大きいほど劇的になる。', ins: ['2\n1 2 3\n', '1\n4 5\n', '3\n1 1 1 1\n', '2\n5 -1 2\n', '4\n1 2 3 4\n', '2\n0 0 0\n'] })

t({ lv: 584, concept: 'グラフ: 隣接が同じ頂点のグループ数', title: '同じ友達リストの持ち主', tags: ['グラフ', 'ハッシュ'], io: '1行目に頂点数 n と辺数 m、続く m 行に無向辺 u v が与えられます。', ask: '隣接する頂点の集合が完全に同じ頂点どうしを同じグループにまとめたとき、グループの総数を出力してください。', h1: '双子の頂点ペア(同レベル既出)の同値類版。', h2: 'frozensetにした隣接集合をキーに集める。', ref: 'n,m=map(int,input().split())\nnb=[set() for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    nb[u].add(v)\n    nb[v].add(u)\nprint(len(set(frozenset(nb[v]) for v in range(1,n+1))))', tip: '隣接が同じ頂点は「モジュール」としてまとめてもグラフの性質が保たれる(モジュラー分解)。集合をハッシュ可能にするfrozensetの出番の代表例。', ins: ['4 4\n1 3\n1 4\n2 3\n2 4\n', '3 2\n1 2\n2 3\n', '2 1\n1 2\n', '3 0\n', '4 2\n1 2\n3 4\n', '5 4\n1 2\n1 3\n1 4\n1 5\n'] })

t({ lv: 585, concept: 'リスト: 逆から読んでも同じ位置の数', title: '折り返しても揃う場所', tags: ['リスト'], io: '整数列が1行で空白区切りで与えられます。', ask: '位置 i (0始まり) の値と、逆から数えた同じ位置(n−1−i)の値が等しい i の個数を出力してください。', h1: '回文判定の「どこまで崩れているか」版。', h2: 'a[i]==a[n−1−i] を全部数える(中央も含む)。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nprint(sum(1 for i in range(n) if a[i]==a[n-1-i]))', tip: '答えがnなら回文。回文性を0/1でなく「対称一致率」として測ると、DNAの回文構造の検出のような度合いの議論につながる。', ins: ['1 2 1\n', '1 2\n', '5\n', '1 2 2 1\n', '1 2 3\n', '3 3\n'] })

t({ lv: 586, concept: '貪欲: 最近傍法の巡回距離', title: 'いちばん近い街から順に', tags: ['貪欲', '幾何'], io: '1行目に地点数 n、続く n 行に座標 x y が与えられます。地点1から出発します。', ask: '「まだ訪ねていない中で最も近い地点(マンハッタン距離、同距離なら番号最小)へ移動する」を繰り返して全地点を回り、最後に地点1へ戻る総移動距離を出力してください。', h1: '巡回セールスマンの有名ヒューリスティック。', h2: '訪問済み集合を持って素直にシミュレーション。', ref: 'n=int(input())\npts=[tuple(map(int,input().split())) for _ in range(n)]\ndef d(i,j):\n    return abs(pts[i][0]-pts[j][0])+abs(pts[i][1]-pts[j][1])\nvisited=[False]*n\nvisited[0]=True\ncur=0\ntotal=0\nfor _ in range(n-1):\n    best=-1\n    for j in range(n):\n        if not visited[j] and (best<0 or d(cur,j)<d(cur,best)):\n            best=j\n    total+=d(cur,best)\n    visited[best]=True\n    cur=best\ntotal+=d(cur,0)\nprint(total)', tip: '最近傍法は最適解の保証はない(最悪でO(log n)倍)が、直感的で速い基準線。厳密解(bitDP、既出)との差を測ることでヒューリスティック評価の作法が身につく。', ins: ['3\n0 0\n0 2\n3 0\n', '1\n5 5\n', '2\n0 0\n4 0\n', '4\n0 0\n1 0\n2 0\n3 0\n', '3\n0 0\n5 0\n1 1\n', '4\n0 0\n0 3\n3 0\n3 3\n'] })

t({ lv: 587, concept: '木: どの内部頂点も子が2つ以上か', title: '一人っ子のいない木', tags: ['木'], io: '1行目に頂点数 n (n≥2)、2行目に頂点2〜nの親が与えられます(根は頂点1)。', ask: '子を持つ全ての頂点の子の数が2以上なら yes、子が1つだけの頂点があれば no を出力してください。', h1: '親の出現回数がそのまま子の数。', h2: 'Counterの値に1が無いか。', ref: 'from collections import Counter\nn=int(input())\npar=list(map(int,input().split()))\nc=Counter(par)\nprint("no" if 1 in c.values() else "yes")', tip: 'この条件(full tree)を満たす木は「葉の数=内部頂点の数+1」(二分の場合)など綺麗な計数法則を持つ。構文木や決定木の正規形の検査でもある。', ins: ['3\n1 1\n', '3\n1 2\n', '7\n1 1 2 2 3 3\n', '2\n1\n', '5\n1 1 2 2\n', '6\n1 1 2 2 4\n'] })

t({ lv: 588, concept: 'グラフ: 二部性を保って足せる辺の数', title: 'まだ張れる橋は何本', tags: ['グラフ'], io: '1行目に頂点数 n と辺数 m、続く m 行に無向辺 u v が与えられます(連結な二部グラフ)。', ask: '二部グラフのまま追加できる辺の最大本数を出力してください。', h1: '2彩色して両側のサイズを数える。', h2: 'answer = 片側×もう片側 − m。', ref: 'from collections import deque\nn,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\ncolor=[-1]*(n+1)\ncolor[1]=0\nq=deque([1])\nwhile q:\n    x=q.popleft()\n    for y in g[x]:\n        if color[y]<0:\n            color[y]=1-color[x]\n            q.append(y)\na=sum(1 for v in range(1,n+1) if color[v]==0)\nprint(a*(n-a)-m)', tip: '連結なら2彩色は(色の入れ替えを除き)一意なので側のサイズが確定する。非連結だと成分ごとの側の割り振りで積を最大化する部分和問題が現れ、一気に難しくなる。', ins: ['4 3\n1 2\n2 3\n3 4\n', '2 1\n1 2\n', '6 5\n1 2\n2 3\n3 4\n4 5\n5 6\n', '5 4\n1 2\n1 3\n1 4\n1 5\n', '4 4\n1 2\n2 3\n3 4\n4 1\n', '6 5\n1 2\n1 3\n2 4\n2 5\n3 6\n'] })

t({ lv: 589, concept: 'グラフ: 互いに知らない2人組の数', title: '初対面のペアを数える', tags: ['グラフ'], io: '1行目に n、続く n 行に n×n の行列(i行j列が1なら人iは人jを知っている。対角は0)が与えられます。', ask: 'どちらも相手を知らない2人組 (i<j) の数を出力してください。', h1: '知り合い関係は向きがある(片思いあり)。', h2: '両方向とも0のペアを数える。', ref: 'n=int(input())\nA=[list(map(int,input().split())) for _ in range(n)]\nprint(sum(1 for i in range(n) for j in range(i+1,n) if A[i][j]==0 and A[j][i]==0))', tip: '有向の「知る」関係では、ペアは相互・片思い・無関係の3種に分類できる。3種の数を足すとC(n,2)になる検算が効く、関係行列の読み取り練習。', ins: ['3\n0 1 1\n1 0 1\n0 0 0\n', '2\n0 0\n0 0\n', '3\n0 1 0\n0 0 0\n1 1 0\n', '2\n0 1\n1 0\n', '4\n0 1 1 1\n0 0 0 0\n0 1 0 1\n1 1 1 0\n', '3\n0 0 0\n0 0 0\n0 0 0\n'] })

t({ lv: 590, concept: 'グラフ: 引いても無駄な新道の数', title: '効かないバイパス', tags: ['グラフ', 'ダイクストラ'], io: '1行目に n m k、続く m 行に既存の無向辺 u v w、続く k 行に新道の候補 u v w が与えられます(1からnへ到達可能)。', ask: '候補のうち「その1本を追加しても頂点1から頂点nへの最短距離が縮まらない」ものの個数を出力してください。', h1: '新しい道1本の効果(同レベル既出)の全候補版。', h2: '1からとnからの距離を前計算し、d1[u]+w+dn[v] と逆向きを最短と比べる。', ref: 'import heapq\nfirst=input().split()\nn,m,k=map(int,first)\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v,w=map(int,input().split())\n    g[u].append((v,w))\n    g[v].append((u,w))\ndef dij(s):\n    INF=float("inf")\n    dist=[INF]*(n+1)\n    dist[s]=0\n    pq=[(0,s)]\n    while pq:\n        d,v=heapq.heappop(pq)\n        if d>dist[v]:\n            continue\n        for to,w in g[v]:\n            if d+w<dist[to]:\n                dist[to]=d+w\n                heapq.heappush(pq,(d+w,to))\n    return dist\nd1=dij(1)\ndn=dij(n)\nD=d1[n]\ncnt=0\nfor _ in range(k):\n    u,v,w=map(int,input().split())\n    if min(d1[u]+w+dn[v],d1[v]+w+dn[u])>=D:\n        cnt+=1\nprint(cnt)', tip: '前計算2回で候補ごとの評価がO(1)になる「両端からの距離」の型。道路計画の費用対効果の一次スクリーニングと同じ計算で、増設の意思決定を支える。', ins: ['3 2 1\n1 2 4\n2 3 4\n1 3 10\n', '3 2 1\n1 2 4\n2 3 4\n1 3 5\n', '2 1 2\n1 2 3\n1 2 5\n1 2 2\n', '4 3 2\n1 2 1\n2 3 1\n3 4 1\n1 4 4\n1 3 1\n', '2 1 1\n1 2 1\n1 2 1\n', '3 3 1\n1 2 1\n2 3 1\n1 3 3\n1 3 1\n'] })

t({ lv: 591, concept: 'バックトラック: 連結して回文にできる並べ方', title: '単語をつないで鏡文字', tags: ['バックトラック', '文字列'], io: '単語が空白区切りで1行に与えられます。', ask: '単語を全部ちょうど1回ずつ、ある順に連結して回文にできるなら yes、できなければ no を出力してください。', h1: '全順列を試して十分な規模。', h2: 'permutationsとjoinで判定。', ref: 'from itertools import permutations\nws=input().split()\nans="no"\nfor p in permutations(ws):\n    s="".join(p)\n    if s==s[::-1]:\n        ans="yes"\n        break\nprint(ans)', tip: '高速化するなら「先頭の単語と末尾の単語が鏡像関係」で枝刈りする両端固定の再帰へ。回文ペア(既出)の判定関数がその部品としてそのまま活きる。', ins: ['ab ba\n', 'ab cd\n', 'a\n', 'abc x cba\n', 'aa b\n', 'ab b\n'] })

t({ lv: 592, concept: '貪欲: k回の+1で積を最大に', title: '肥料はどの株に与えるか', tags: ['貪欲', 'ヒープ'], io: '1行目に k、2行目に正整数の列が与えられます。', ask: '「どれか1つの要素に1を足す」操作を k 回行った後の全要素の積の最大を出力してください。', h1: '常に最小の要素に足すのが最適。', h2: 'ヒープでk回pop/push。', ref: 'import heapq\nk=int(input())\na=list(map(int,input().split()))\nheapq.heapify(a)\nfor _ in range(k):\n    heapq.heappush(a,heapq.heappop(a)+1)\np=1\nfor x in a:\n    p*=x\nprint(p)', tip: '積は「揃っているほど大きい」(相加相乗平均の不等式)ので、へこみを埋めるのが最善——貪欲の正しさが古典不等式で説明できる稀有な例。', ins: ['3\n1 2\n', '1\n3 3\n', '2\n1 1 1\n', '5\n1\n', '2\n5 5\n', '4\n1 2 3\n'] })

t({ lv: 593, concept: '木: 葉から最も遠い頂点', title: '木のいちばん奥座敷', tags: ['木', 'BFS'], io: '1行目に頂点数 n (n≥2)、続く n−1 行に木の辺 u v が与えられます。', ask: 'どの葉からも遠い、すなわち「最も近い葉までの距離」が最大の頂点を出力してください(同距離なら最小の番号)。', h1: '全ての葉を始点にした多始点BFS。', h2: '距離最大(同点は番号最小)を選ぶ。', ref: 'from collections import deque\nn=int(input())\ng=[[] for _ in range(n+1)]\ndeg=[0]*(n+1)\nfor _ in range(n-1):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\n    deg[u]+=1\n    deg[v]+=1\ndist=[-1]*(n+1)\nq=deque()\nfor v in range(1,n+1):\n    if deg[v]==1:\n        dist[v]=0\n        q.append(v)\nwhile q:\n    x=q.popleft()\n    for y in g[x]:\n        if dist[y]<0:\n            dist[y]=dist[x]+1\n            q.append(y)\nbest=max(dist[1:n+1])\nprint(next(v for v in range(1,n+1) if dist[v]==best))', tip: 'グリッドの「最も近い0までの距離」(既出)の木版で、答えは木の「内側の芯」。葉を同時に燃やして最後に燃える場所、と思うと多始点BFSの絵が浮かぶ。', ins: ['5\n1 2\n2 3\n3 4\n4 5\n', '2\n1 2\n', '4\n1 2\n1 3\n1 4\n', '7\n1 2\n2 3\n3 4\n4 5\n5 6\n6 7\n', '6\n1 2\n2 3\n2 4\n4 5\n4 6\n', '3\n1 2\n2 3\n'] })

t({ lv: 594, concept: 'DP: 2回までの売買の最大利益', title: '2度のチャンスを最大に', tags: ['DP'], io: '株価の列が1行で空白区切りで与えられます。', ask: '高々2回の売買(買って売る。同時保有は不可)で得られる利益の最大を出力してください(取引しなければ0)。', h1: '1回売買(既出)の状態を倍にする。', h2: '状態: 1回目買い・1回目売り・2回目買い・2回目売り、の4つの最良値を更新。', ref: 'a=list(map(int,input().split()))\nNEG=-(10**18)\nb1=b2=NEG\ns1=s2=0\nfor x in a:\n    b1=max(b1,-x)\n    s1=max(s1,b1+x)\n    b2=max(b2,s1-x)\n    s2=max(s2,b2+x)\nprint(s2)', tip: '状態機械DPの見本で、k回売買にもそのまま伸びる。1回目の利益を持ち越して2回目を買う遷移(s1−x)が「資金の連結」を表す急所。', ins: ['3 3 5 0 0 3 1 4\n', '1 2 3 4 5\n', '7 6 4 3 1\n', '5\n', '1 2 1 2\n', '2 1 4 1 7\n'] })

t({ lv: 595, concept: '区間: 長さLの窓に入る最大の点数', title: '網を1回だけ投げるなら', tags: ['区間', '二点法'], io: '1行目に L、2行目に数直線上の点の位置(昇順)が与えられます。', ask: '長さ L の閉区間 [x, x+L] をどこかに置くとき、含められる点の最大数を出力してください。', h1: '窓の左端は必ずどれかの点に合わせてよい。', h2: '各点を左端にして二点法で右端を伸ばす。', ref: 'L=int(input())\np=list(map(int,input().split()))\nn=len(p)\nbest=0\nj=0\nfor i in range(n):\n    if j<i:\n        j=i\n    while j+1<n and p[j+1]-p[i]<=L:\n        j+=1\n    if j-i+1>best:\n        best=j-i+1\nprint(best)', tip: '「窓の端を点にスナップしてよい」という離散化の一言が、連続無限の置き場所を高々n通りに落とす。固定長区間で点を覆う問題(既出)の1本だけ版。', ins: ['3\n1 2 5 6 7\n', '0\n1 1 2\n', '10\n1 5 9\n', '1\n1 3 5\n', '4\n1 2 3 8 9\n', '2\n1 2 3 4\n'] })

t({ lv: 596, concept: '文字列: 母音のローテーション', title: '母音の玉突き変換', tags: ['文字列'], io: '英小文字の文字列が1行で与えられます。', ask: '母音を a→i→u→e→o→a と1つずつずらし、子音はそのままにした文字列を出力してください。', h1: '変換表を辞書で作る。', h2: 'getのデフォルトで子音を素通し。', ref: 's=input()\nm={"a":"i","i":"u","u":"e","e":"o","o":"a"}\nprint("".join(m.get(c,c) for c in s))', tip: '置換暗号の最小構成で、辞書のget(c, c)による「該当なしは恒等」が定石。5回適用すると元に戻る(位数5の巡回置換)ことがテストの自己検証に使える。', ins: ['aiueo\n', 'hello\n', 'sky\n', 'banana\n', 'code\n', 'u\n'] })

t({ lv: 597, concept: 'BFS: 最速で会える場所の数', title: '待ち合わせ候補は何箇所', tags: ['BFS', 'グラフ'], io: '1行目に n m a b、続く m 行に無向辺 u v が与えられます(連結)。2人は毎ターン1歩ずつ動けます。', ask: '2人が同時に出発して合流するとき、「合流までのターン数(遠い方の移動距離)」を最小にする合流頂点の個数を出力してください。', h1: '2人が合流できる最短時刻(同レベル既出)のargmin数え上げ。', h2: '両者からBFSし、max(da,db) の最小値を達成する頂点を数える。', ref: 'from collections import deque\nfirst=input().split()\nn,m,a,b=map(int,first)\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\ndef bfs(s):\n    dist=[-1]*(n+1)\n    dist[s]=0\n    q=deque([s])\n    while q:\n        x=q.popleft()\n        for y in g[x]:\n            if dist[y]<0:\n                dist[y]=dist[x]+1\n                q.append(y)\n    return dist\nda=bfs(a)\ndb=bfs(b)\nbest=min(max(da[v],db[v]) for v in range(1,n+1))\nprint(sum(1 for v in range(1,n+1) if max(da[v],db[v])==best))', tip: '合計を最小化する待ち合わせ(既出)と最大値(待ち時間)を最小化する本問は、最適地点がずれることがある。目的関数の選び方が答えを変える、を体験する対問題。', ins: ['3 2 1 3\n1 2\n2 3\n', '2 1 1 2\n1 2\n', '4 3 1 4\n1 2\n2 3\n3 4\n', '5 4 1 5\n1 2\n2 3\n3 4\n4 5\n', '3 3 1 2\n1 2\n2 3\n1 3\n', '1 0 1 1\n'] })

t({ lv: 598, concept: '貪欲: 桁の入れ替え1回で最小の数', title: 'ひと交換でできる最小値', tags: ['貪欲'], io: '正整数が1行で与えられます。', ask: '2つの桁をちょうど1回入れ替えて(そのままでもよい=同じ桁どうしの交換とみなす)作れる最小の数を出力してください。ただし先頭が0になる交換は禁止です。', h1: '最大化(同レベル既出)の鏡像だが、先頭0の制約が非対称。', h2: '全ペアの交換を試して条件を満たす最小を取る。', ref: 's=list(input())\nn=len(s)\nbest=int("".join(s))\nfor i in range(n):\n    for j in range(i+1,n):\n        s[i],s[j]=s[j],s[i]\n        if s[0]!="0":\n            v=int("".join(s))\n            if v<best:\n                best=v\n        s[i],s[j]=s[j],s[i]\nprint(best)', tip: '最大化なら「先頭に一番大きい桁」で済むが、最小化は先頭0禁止が絡んで貪欲が一段複雑になる。O(n²)総当たりが仕様の非対称性を丸ごと吸収してくれる。', ins: ['310\n', '21\n', '102\n', '111\n', '54321\n', '90\n'] })

t({ lv: 599, concept: 'グラフ: 切れると遠回りになる辺の数', title: '失うと痛い道', tags: ['グラフ', 'BFS'], io: '1行目に頂点数 n と辺数 m、続く m 行に無向辺 u v が与えられます(1からnへ到達可能)。', ask: '取り除くと頂点1から頂点nへの最短距離が長くなる(または到達不能になる)辺の本数を出力してください。', h1: '1本ずつ取り除いてBFSし直す総当たりが基準解。', h2: '元の最短距離Dと比べる。', ref: 'from collections import deque\nn,m=map(int,input().split())\nes=[tuple(map(int,input().split())) for _ in range(m)]\ndef sp(skip):\n    g=[[] for _ in range(n+1)]\n    for i,(u,v) in enumerate(es):\n        if i!=skip:\n            g[u].append(v)\n            g[v].append(u)\n    dist=[-1]*(n+1)\n    dist[1]=0\n    q=deque([1])\n    while q:\n        x=q.popleft()\n        for y in g[x]:\n            if dist[y]<0:\n                dist[y]=dist[x]+1\n                q.append(y)\n    return dist[n]\nD=sp(-1)\ncnt=0\nfor i in range(m):\n    d=sp(i)\n    if d<0 or d>D:\n        cnt+=1\nprint(cnt)', tip: 'この辺たちは「全ての最短経路に共通して乗る辺」。最悪距離(同レベル既出)が値を問うのに対し本数を問う、道路網の脆弱性評価の相棒クエリ。', ins: ['3 2\n1 2\n2 3\n', '3 3\n1 2\n2 3\n1 3\n', '4 4\n1 2\n2 4\n1 3\n3 4\n', '2 1\n1 2\n', '4 3\n1 2\n2 3\n3 4\n', '5 5\n1 2\n2 5\n1 3\n3 4\n4 5\n'] })

t({ lv: 601, concept: 'Union-Find: 閉路を作る辺の一覧', title: '余計な輪を作った犯人一覧', tags: ['Union-Find'], io: '1行目に頂点数 n と辺数 m、続く m 行に辺 u v が順に与えられます。', ask: '順に辺を足すとき「すでに繋がっている2頂点を結ぶ」辺の番号(1始まり)を昇順に空白区切りで出力してください(なければ none)。', h1: '最初に閉路ができる辺(既出)の全部版。', h2: 'Union-Findで併合失敗した辺を記録。', ref: 'n,m=map(int,input().split())\np=list(range(n+1))\ndef find(x):\n    while p[x]!=x:\n        p[x]=p[p[x]]\n        x=p[x]\n    return x\nout=[]\nfor i in range(1,m+1):\n    u,v=map(int,input().split())\n    ru,rv=find(u),find(v)\n    if ru==rv:\n        out.append(str(i))\n    else:\n        p[ru]=rv\nprint(" ".join(out) if out else "none")', tip: 'クラスカル法で捨てられる辺のリストそのもの(重みなし版)。この辺の本数が独立閉路の数(サイクル空間の次元)に一致する、という理論との接点も美しい。', ins: ['4 4\n1 2\n2 3\n3 4\n4 1\n', '3 2\n1 2\n2 3\n', '3 3\n1 2\n2 1\n2 3\n', '5 6\n1 2\n2 3\n1 3\n3 4\n4 5\n3 5\n', '2 1\n1 2\n', '4 5\n1 2\n3 4\n1 3\n2 4\n1 4\n'] })

t({ lv: 602, concept: 'MST: 1辺を禁止した最小全域木', title: 'その道だけは使えないなら', tags: ['MST'], io: '1行目に n m b、続く m 行に辺 u v w が与えられます(b番目の辺は使用禁止)。', ask: 'b 番目の辺を使わない最小全域木の総重みを出力してください(全域木が作れなければ -1)。', h1: 'この辺を使うMST(同レベル既出)の鏡像。', h2: 'その辺を除いてクラスカル。', ref: 'first=input().split()\nn,m,b=map(int,first)\nes=[]\nfor i in range(1,m+1):\n    u,v,w=map(int,input().split())\n    if i!=b:\n        es.append((w,u,v))\nes.sort()\np=list(range(n+1))\ndef find(x):\n    while p[x]!=x:\n        p[x]=p[p[x]]\n        x=p[x]\n    return x\ntotal=0\ncnt=0\nfor w,u,v in es:\n    ru,rv=find(u),find(v)\n    if ru!=rv:\n        p[ru]=rv\n        total+=w\n        cnt+=1\nprint(total if cnt==n-1 else -1)', tip: '道路工事や障害のシナリオ分析で頻出の「制約つきMST」。禁止辺が橋だったときだけ-1になる、という連結性の議論が答えの場合分けに現れる。', ins: ['3 3 1\n1 2 1\n2 3 2\n1 3 3\n', '3 3 3\n1 2 1\n2 3 2\n1 3 3\n', '2 1 1\n1 2 5\n', '4 4 2\n1 2 1\n2 3 1\n3 4 1\n1 4 5\n', '4 5 5\n1 2 1\n2 3 1\n3 4 1\n1 3 4\n2 4 4\n', '3 2 2\n1 2 1\n2 3 1\n'] })

t({ lv: 603, concept: '幾何: 全点を囲う最小の長方形の面積', title: '全員が入る撮影フレーム', tags: ['幾何'], io: '1行目に点の数 n、続く n 行に座標 x y が与えられます。', ask: '全ての点を含む軸に平行な最小の長方形の面積を出力してください(一直線上なら0)。', h1: 'x座標とy座標を独立に考えられる。', h2: '(maxX−minX)×(maxY−minY)。', ref: 'n=int(input())\nxs=[]\nys=[]\nfor _ in range(n):\n    x,y=map(int,input().split())\n    xs.append(x)\n    ys.append(y)\nprint((max(xs)-min(xs))*(max(ys)-min(ys)))', tip: 'バウンディングボックスは衝突判定の一次フィルタや地図タイルの選択など、幾何計算の前処理として無数に呼ばれる。軸平行だからx方向とy方向が完全に分離する。', ins: ['3\n0 0\n2 3\n1 1\n', '1\n5 5\n', '2\n-1 -1\n1 1\n', '4\n0 0\n0 5\n5 0\n5 5\n', '2\n3 7\n3 9\n', '3\n-2 0\n2 1\n0 -3\n'] })

t({ lv: 604, concept: 'グラフ: 距離が閾値以下のペア数', title: '近距離ペアを数える', tags: ['グラフ'], io: '1行目に n m X、続く m 行に無向辺 u v w が与えられます。', ask: '最短距離が X 以下である頂点対 (u<v) の個数を出力してください(到達不能な対は数えません)。', h1: '全点対の距離が要る。', h2: 'ワーシャルフロイドで距離行列を作って数える。', ref: 'first=input().split()\nn,m,X=map(int,first)\nINF=10**18\nd=[[INF]*(n+1) for _ in range(n+1)]\nfor v in range(1,n+1):\n    d[v][v]=0\nfor _ in range(m):\n    u,v,w=map(int,input().split())\n    if w<d[u][v]:\n        d[u][v]=w\n        d[v][u]=w\nfor k in range(1,n+1):\n    for i in range(1,n+1):\n        for j in range(1,n+1):\n            if d[i][k]+d[k][j]<d[i][j]:\n                d[i][j]=d[i][k]+d[k][j]\nprint(sum(1 for i in range(1,n+1) for j in range(i+1,n+1) if d[i][j]<=X))', tip: '「配達網でX分以内に行き来できる拠点ペア」のような到達性の統計。距離行列を1度作れば、閾値を変えた問いには数え直しだけで答えられる。', ins: ['3 2 3\n1 2 2\n2 3 2\n', '3 3 10\n1 2 1\n2 3 1\n1 3 5\n', '2 1 1\n1 2 5\n', '4 3 2\n1 2 1\n2 3 1\n3 4 1\n', '3 1 100\n1 2 1\n', '4 4 4\n1 2 2\n2 3 2\n3 4 2\n4 1 2\n'] })

t({ lv: 605, concept: 'グラフ: 距離行列の三角不等式の検証', title: 'その距離表は本物か', tags: ['グラフ'], io: '1行目に n、続く n 行に n×n の距離表が与えられます。', ask: 'この表が「対角は0、対称、そして全ての i,j,k で d[i][j] ≤ d[i][k]+d[k][j]」を満たすなら yes、そうでなければ no を出力してください。', h1: '距離の公理のうち機械的に確かめられる3つ。', h2: '三重ループで三角不等式。', ref: 'n=int(input())\nd=[list(map(int,input().split())) for _ in range(n)]\nok=all(d[i][i]==0 for i in range(n))\nok=ok and all(d[i][j]==d[j][i] for i in range(n) for j in range(n))\nok=ok and all(d[i][j]<=d[i][k]+d[k][j] for i in range(n) for j in range(n) for k in range(n))\nprint("yes" if ok else "no")', tip: '三角不等式を満たさない「距離もどき」ではダイクストラの枝刈りやTSPの近似保証が崩れる。データ検疫としての公理チェックは、機械学習の距離行列にも毎回やる価値がある。', ins: ['2\n0 3\n3 0\n', '2\n0 3\n2 0\n', '3\n0 1 5\n1 0 1\n5 1 0\n', '3\n0 1 2\n1 0 1\n2 1 0\n', '1\n0\n', '3\n0 2 2\n2 1 2\n2 2 0\n'] })

t({ lv: 606, concept: '木: 根から葉までの最大コスト', title: '一番実り多い枝先へ', tags: ['木DP'], io: '1行目に頂点数 n (n≥2)、2行目に頂点2〜nの親、3行目に各頂点のコストが与えられます(根は頂点1)。', ask: '根から葉への道のコスト合計の最大を出力してください。', h1: '最小コスト経路(同レベル既出)の鏡像。', h2: '根からの累積を親リスト順に確定し、葉のmaxを取る。', ref: 'n=int(input())\npar=list(map(int,input().split()))\ncost=list(map(int,input().split()))\nacc=[0]*(n+1)\nacc[1]=cost[0]\nhaskid=[False]*(n+1)\nfor v in range(2,n+1):\n    p=par[v-2]\n    acc[v]=acc[p]+cost[v-1]\n    haskid[p]=True\nprint(max(acc[v] for v in range(1,n+1) if not haskid[v]))', tip: '親リストの番号規約(親<子)のおかげで、上から1パスで累積が確定する。負のコストが混ざると「浅い葉で止まる」のが最適になることもあり、maxの走査が正しさを守る。', ins: ['5\n1 1 2 2\n3 1 4 1 5\n', '2\n1\n2 3\n', '3\n1 1\n1 5 2\n', '4\n1 2 3\n1 1 1 1\n', '3\n1 2\n5 -2 10\n', '7\n1 1 2 2 3 3\n1 1 1 1 1 1 1\n'] })

t({ lv: 607, concept: '木: 半分に切れる辺の数', title: '木を真っ二つにする枝', tags: ['木'], io: '1行目に偶数の頂点数 n、2行目に頂点2〜nの親が与えられます(根は頂点1)。', ask: '取り除くと両側の頂点数がちょうど半分ずつになる辺の本数を出力してください。', h1: '両側が偶数になる切り方(同レベル既出)の強い版。', h2: '部分木サイズが n/2 の頂点(根以外)を数える。', ref: 'n=int(input())\npar=list(map(int,input().split()))\nsize=[1]*(n+1)\nfor v in range(n,1,-1):\n    size[par[v-2]]+=size[v]\nprint(sum(1 for v in range(2,n+1) if size[v]==n//2))', tip: '各辺は「子側の部分木」と1対1なので、辺の性質は部分木サイズの条件に翻訳できる。重心分解や木の分割統治の入り口となる読み替え。', ins: ['4\n1 1 2\n', '2\n1\n', '6\n1 2 3 1 5\n', '4\n1 1 1\n', '6\n1 1 2 2 3\n', '8\n1 1 2 2 3 3 4\n'] })

t({ lv: 608, concept: '貪欲: 直線上の配達の最短往復距離', title: '東奔西走のち帰宅', tags: ['貪欲'], io: '数直線上の配達先の位置(0以外の整数)が1行で空白区切りで与えられます。原点0から出発し、最後に原点へ戻ります。', ask: '全ての配達先を訪ねて原点に戻る最短の総移動距離を出力してください。', h1: '右端と左端まで1往復ずつすれば全部拾える。', h2: '2×(正の最大) + 2×(負の最小の絶対値)。', ref: 'a=list(map(int,input().split()))\nr=max([x for x in a if x>0],default=0)\nl=min([x for x in a if x<0],default=0)\nprint(2*r-2*l)', tip: '片側の途中の家は端への道すがら必ず通るので、費用は両端だけで決まる——1次元の巡回問題は退化して公式になる。maxのdefault引数が「その側に家がない」を綺麗に処理する。', ins: ['2 5 -3\n', '5\n', '-4\n', '1 2 3\n', '-2 -7\n', '3 -3\n'] })

t({ lv: 609, concept: '数え上げ: 一本道のラベル付き木の数', title: '一列に並べる木の数', tags: ['数え上げ'], io: '正整数 n が1行で与えられます。', ask: 'n 個のラベル付き頂点でできる「一本道(パス)の形の木」の個数を出力してください(n=1 は1)。', h1: '並べ方 n! から重複を割る。', h2: '左右をひっくり返した並びは同じ木なので n!/2 (n≥2)。', ref: 'import math\nn=int(input())\nprint(1 if n==1 else math.factorial(n)//2)', tip: 'ケイリーの公式 n^(n−2) 本の木のうちパスは n!/2 本、星は n 本——形を固定した数え上げは全体の内訳表になる。反転対称で2で割る処理は円順列の (n−1)!/2 と同じ発想。', ins: ['3\n', '2\n', '4\n', '1\n', '5\n', '6\n'] })

t({ lv: 610, concept: 'ソート: 大きな隙間で切ったグループ数', title: '離れたら別グループ', tags: ['ソート'], io: '1行目にしきい値 t、2行目に整数列が与えられます。', ask: '値を昇順に並べ、隣との差が t を超えるところで切ってグループ分けしたときのグループ数を出力してください。', h1: 'ソートして隣接差を見るだけ。', h2: '差>tの箇所の数+1。', ref: 't2=int(input())\na=sorted(map(int,input().split()))\nprint(1+sum(1 for i in range(len(a)-1) if a[i+1]-a[i]>t2))', tip: '単連結法(single-linkage)クラスタリングのしきい値版で、MSTの重い辺を切る操作(既出のクラスタ分離幅)と同じことを1次元でやっている。', ins: ['2\n1 2 5 6 10\n', '10\n1 5 9\n', '0\n3 3 4\n', '1\n7\n', '3\n1 5 9 13\n', '5\n2 4 20 22\n'] })

t({ lv: 611, concept: 'DAG: 辞書順最小の最長経路', title: '一番長い道の中で一番若い道', tags: ['DAG', 'DP'], io: '1行目に頂点数 n と辺数 m、続く m 行に有向辺 u v (閉路なし) が与えられます。', ask: '辺数が最長の経路のうち、頂点列が辞書順最小のものを空白区切りで出力してください。', h1: '各頂点から先の最長(同レベル既出)を前計算。', h2: '長さが保証される候補の中で番号最小を貪欲に選ぶ。', ref: 'import sys\nsys.setrecursionlimit(100000)\nn,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\nmemo={}\ndef down(v):\n    if v in memo:\n        return memo[v]\n    r=0\n    for w in g[v]:\n        c=down(w)+1\n        if c>r:\n            r=c\n    memo[v]=r\n    return r\nL=max(down(v) for v in range(1,n+1))\ncur=min(v for v in range(1,n+1) if down(v)==L)\npath=[cur]\nneed=L\nwhile need>0:\n    cur=min(w for w in g[cur] if down(w)==need-1)\n    path.append(cur)\n    need-=1\nprint(" ".join(map(str,path)))', tip: '「値のDP+前から貪欲復元」の三度目の登場(LCS・LISと同型)。downの値が「この先の保証」になっているから、目先の最小番号を選んでも長さを失わない。', ins: ['4 3\n1 2\n2 3\n2 4\n', '3 2\n2 1\n3 1\n', '2 0\n', '5 4\n1 3\n2 3\n3 4\n3 5\n', '4 4\n1 2\n1 3\n2 4\n3 4\n', '6 5\n1 2\n2 6\n1 4\n4 5\n5 6\n'] })

t({ lv: 612, concept: 'スタック: 括弧列の最上位ブロック数', title: '外側から見える括弧のまとまり', tags: ['スタック'], io: '正しい括弧列が1行で与えられます。', ask: '深さ0に戻る位置で区切ったときの、最上位のまとまりの個数を出力してください(例: (()())() は2つ)。', h1: '深さカウンタが0に戻った回数。', h2: '対応の判定は不要(正しい列が前提)。', ref: 's=input()\ndepth=0\ncnt=0\nfor c in s:\n    depth+=1 if c=="(" else -1\n    if depth==0:\n        cnt+=1\nprint(cnt)', tip: '正しい括弧列の「原始分解」の成分数で、カタラン数の漸化式 C(n)=ΣC(i)C(n−1−i) の分解単位がこれ。深さ0への帰還を数えるだけ、が構造の輪郭を捉えている。', ins: ['(()())()\n', '()\n', '((()))\n', '()()()\n', '(())()\n', '()(())\n'] })

t({ lv: 613, concept: 'Union-Find: 差し替えで全部繋げるか', title: '余った線をつなぎ直す', tags: ['Union-Find'], io: '1行目に頂点数 n と辺数 m、続く m 行にケーブル(無向辺) u v が与えられます。', ask: 'ケーブルを何本か抜いて別の場所に差し替えることで全頂点を連結にできるなら yes、できなければ no を出力してください(ケーブルの総数は変えられません)。', h1: '成分数と「余っている(閉路を作っている)ケーブル」の数を数える。', h2: '余りが 成分数−1 以上ならyes。', ref: 'n,m=map(int,input().split())\np=list(range(n+1))\ndef find(x):\n    while p[x]!=x:\n        p[x]=p[p[x]]\n        x=p[x]\n    return x\nextra=0\nfor _ in range(m):\n    u,v=map(int,input().split())\n    ru,rv=find(u),find(v)\n    if ru==rv:\n        extra+=1\n    else:\n        p[ru]=rv\nroots=len({find(v) for v in range(1,n+1)})\nprint("yes" if extra>=roots-1 else "no")', tip: '実は m≥n−1 と同値(辺が足りていれば必ず組み替えられる)なのだが、Union-Findで「余剰」と「分断」を数える解法はその理由を構造ごと見せてくれる。', ins: ['4 3\n1 2\n2 3\n1 3\n', '6 4\n1 2\n3 4\n1 2\n5 6\n', '4 2\n1 2\n3 4\n', '5 5\n1 2\n2 3\n1 3\n1 3\n4 5\n', '2 1\n1 2\n', '6 5\n1 2\n2 3\n3 1\n4 5\n5 6\n'] })

t({ lv: 614, concept: '統計: 重みつき中央値', title: '重みで釣り合う値', tags: ['統計', 'ソート'], io: '1行目に値の列、2行目に対応する正の重みの列が与えられます。', ask: '値を昇順に見て、そこまでの重みの累計の2倍が全体の重み以上になる最初の値(重みつき中央値)を出力してください。', h1: '(値, 重み)を値でソート。', h2: '累計×2 ≥ 総重量 の最初。', ref: 'vals=list(map(int,input().split()))\nws=list(map(int,input().split()))\npairs=sorted(zip(vals,ws))\ntotal=sum(ws)\nacc=0\nfor v,w in pairs:\n    acc+=w\n    if 2*acc>=total:\n        print(v)\n        break', tip: '重みつき中央値は「絶対偏差×重み」の総和を最小にする点で、1次元の施設配置(倉庫をどこに置くか)の厳密解。普通の中央値は全重み1の特別な場合にすぎない。', ins: ['1 2 3\n1 1 1\n', '10 20\n9 1\n', '1 5\n1 1\n', '3 1 2\n1 5 1\n', '7\n4\n', '1 2 3 4\n1 1 1 5\n'] })

t({ lv: 615, concept: 'シミュレーション: 移動経路が自分と交わるか', title: '自分の足跡を踏むか', tags: ['シミュレーション'], io: 'L R U D からなる移動列が1行で与えられます。原点から1文字ごとに1マス動きます。', ask: '移動の途中で一度でも「すでに訪れた点」に再び乗るなら yes、最後まで乗らなければ no を出力してください(出発点も訪問済みに含む)。', h1: '訪れた座標を集合に。', h2: 'タプル(x,y)をsetへ。', ref: 's=input()\nx=y=0\nseen={(0,0)}\nans="no"\nfor c in s:\n    if c=="L":\n        x-=1\n    elif c=="R":\n        x+=1\n    elif c=="U":\n        y+=1\n    else:\n        y-=1\n    if (x,y) in seen:\n        ans="yes"\n        break\n    seen.add((x,y))\nprint(ans)', tip: 'ヘビゲームの衝突判定そのもの。座標のタプルを集合に入れる管理は、盤面が広大でも訪問箇所だけ覚える「疎な表現」の基本形。', ins: ['LR\n', 'RRU\n', 'RULD\n', 'R\n', 'UDU\n', 'RRUULL\n'] })

t({ lv: 616, concept: '文字列: 繰り返し単位と回数の表記', title: '最小ユニットに畳む', tags: ['文字列'], io: '文字列が1行で与えられます。', ask: '文字列を「単位文字列の k 回繰り返し」として表すとき、単位が最短になる形を「単位 回数」の形で出力してください(繰り返しがなければ全体と 1)。', h1: '最小周期(既出)のうち長さを割り切るものを探す。', h2: '長さの約数 p を小さい順に試し、s[:p]*(n//p)==s か。', ref: 's=input()\nn=len(s)\nfor p in range(1,n+1):\n    if n%p==0 and s[:p]*(n//p)==s:\n        print(s[:p],n//p)\n        break', tip: 'スライスの掛け算での判定 s[:p]*(n//p)==s は素朴だが読みやすさ最強。有名な (s+s).find(s,1) による一撃判定と答え合わせすると、文字列の周期理論が二度おいしい。', ins: ['abcabc\n', 'aaa\n', 'abc\n', 'abab\n', 'aabaab\n', 'xy\n'] })

t({ lv: 617, concept: '木: ヒープ条件の検証', title: '親が子より小さいか総点検', tags: ['木'], io: '1行目に頂点数 n (n≥2)、2行目に頂点2〜nの親、3行目に各頂点の値が与えられます(根は頂点1)。', ask: '全ての親子関係で「親の値 ≤ 子の値」が成り立つ(最小ヒープ条件)なら yes、そうでなければ no を出力してください。', h1: '配列ヒープでなく一般の木での検証。', h2: '頂点2〜nそれぞれで親と比較するだけ。', ref: 'n=int(input())\npar=list(map(int,input().split()))\nval=list(map(int,input().split()))\nok=all(val[par[v-2]-1]<=val[v-1] for v in range(2,n+1))\nprint("yes" if ok else "no")', tip: 'ヒープ条件は「各辺で局所的に成り立てば、根が全体の最小」という局所→大域の推論の見本。heapqの内部不変条件を自分の目で検査する体験でもある。', ins: ['3\n1 1\n1 5 2\n', '3\n1 1\n5 1 2\n', '2\n1\n3 3\n', '5\n1 1 2 2\n1 2 3 4 5\n', '5\n1 1 2 2\n1 2 3 1 5\n', '4\n1 2 3\n2 2 2 2\n'] })

t({ lv: 618, concept: 'グラフ: 次数列の出力', title: '人脈の分布表', tags: ['グラフ'], io: '1行目に頂点数 n と辺数 m、続く m 行に無向辺 u v が与えられます。', ask: '全頂点の次数を昇順に並べて空白区切りで出力してください。', h1: '次数配列を作ってソート。', h2: '孤立点の0も含める。', ref: 'n,m=map(int,input().split())\ndeg=[0]*(n+1)\nfor _ in range(m):\n    u,v=map(int,input().split())\n    deg[u]+=1\n    deg[v]+=1\nprint(" ".join(map(str,sorted(deg[1:n+1]))))', tip: '次数列はグラフの指紋で、同じ次数列でも非同型なグラフがある(同型判定には足りない)。実現可能性の判定(既出のエルデシュ=ガライ)への入力がまさにこの列。', ins: ['3 2\n1 2\n2 3\n', '4 0\n', '3 3\n1 2\n2 3\n1 3\n', '2 1\n1 2\n', '5 4\n1 2\n1 3\n1 4\n1 5\n', '4 3\n1 2\n1 3\n2 3\n'] })

t({ lv: 619, concept: 'マッチング: もっと増やせるか', title: 'そのペア数で満足するな', tags: ['マッチング'], io: '1行目に n m k、続く m 行に無向辺、続く k 行に現在のマッチングのペアが与えられます(正しいマッチングであることは保証)。', ask: 'このグラフでペア数を k+1 以上にできる(現在のマッチングが最大でない)なら yes、これ以上増やせなければ no を出力してください。', h1: '最大マッチングのサイズを求めて比べる。', h2: '小規模なので全探索(各頂点を相手に割り当てる再帰)で最大サイズを出せる。', ref: 'first=input().split()\nn,m,k=map(int,first)\nadj=[set() for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    adj[u].add(v)\n    adj[v].add(u)\nfor _ in range(k):\n    input()\ndef best(rest):\n    if not rest:\n        return 0\n    v=min(rest)\n    r=best(rest-{v})\n    for u in adj[v]:\n        if u in rest and u!=v:\n            c=1+best(rest-{v,u})\n            if c>r:\n                r=c\n    return r\nprint("yes" if best(frozenset(range(1,n+1)))>k else "no")', tip: 'バーグの定理により「増やせる ⇔ 増加道がある」。この判定器は増加道探索アルゴリズムの停止条件の検証器で、与えられたペアの中身を読まなくても数だけで判定できる点も面白い。', ins: ['4 3 1\n1 2\n3 4\n2 3\n1 2\n', '2 1 1\n1 2\n1 2\n', '4 2 1\n1 2\n3 4\n1 2\n', '3 2 1\n1 2\n2 3\n1 2\n', '4 4 2\n1 2\n2 3\n3 4\n4 1\n1 2\n3 4\n', '6 5 2\n1 2\n3 4\n5 6\n2 3\n4 5\n1 2\n4 5\n'] })

t({ lv: 620, concept: 'MST: どれかの最小全域木に入れる辺の数', title: '採用の可能性がある辺', tags: ['MST'], io: '1行目に頂点数 n と辺数 m、続く m 行に辺 u v w が与えられます(連結)。', ask: '少なくとも1つの最小全域木に含まれ得る辺の本数を出力してください。', h1: '必ず使われる辺(既出)の緩い版。', h2: '各辺を「最初に採用してから」クラスカルし、総重みが変わらなければその辺は使える。', ref: 'n,m=map(int,input().split())\nes=[tuple(map(int,input().split())) for _ in range(m)]\ndef mst(force):\n    order=sorted(range(m),key=lambda i:es[i][2])\n    p=list(range(n+1))\n    def find(x):\n        while p[x]!=x:\n            p[x]=p[p[x]]\n            x=p[x]\n        return x\n    total=0\n    cnt=0\n    seq=([force]+order) if force>=0 else order\n    for i in seq:\n        u,v,w=es[i]\n        ru,rv=find(u),find(v)\n        if ru!=rv:\n            p[ru]=rv\n            total+=w\n            cnt+=1\n    return total if cnt==n-1 else None\nW=mst(-1)\nprint(sum(1 for i in range(m) if mst(i)==W))', tip: '辺eがどれかのMSTに入る ⇔ eを強制採用しても総重みが最小のまま、という交換の議論。「必ず入る辺」「入り得る辺」「絶対入らない辺」の3分類でMSTの自由度が見える。', ins: ['3 3\n1 2 1\n2 3 1\n1 3 2\n', '3 3\n1 2 1\n2 3 1\n1 3 1\n', '2 1\n1 2 5\n', '4 4\n1 2 1\n2 3 2\n3 4 1\n1 4 2\n', '3 3\n1 2 1\n2 3 2\n1 3 3\n', '4 5\n1 2 1\n2 3 1\n3 4 1\n1 3 5\n2 4 5\n'] })

t({ lv: 621, concept: '文字列: 時刻にn分を足す', title: '時計の針を進める', tags: ['文字列'], io: '1行目に「HH:MM」形式の時刻、2行目に加える分数 n (0以上) が与えられます。', ask: 'n 分後の時刻を「HH:MM」形式(24時間制、ゼロ埋め)で出力してください。', h1: '総分数に直して足し、24時間で剰余。', h2: 'divmodとゼロ埋めf文字列。', ref: 'hh,mm=map(int,input().split(":"))\nn=int(input())\ntotal=(hh*60+mm+n)%1440\nh,m2=divmod(total,60)\nprint(f"{h:02d}:{m2:02d}")', tip: '時刻演算は「一次元の値に直す→計算→戻す」の正規化パターンの代表。日付をまたぐ処理を剰余1発で済ませられるのは、1日=1440分という固定基数のおかげ。', ins: ['23:45\n30\n', '12:00\n90\n', '00:00\n1440\n', '09:59\n1\n', '10:30\n0\n', '22:10\n300\n'] })

t({ lv: 622, concept: 'DAG: 経路の長さの種類数', title: '道のりの長さは何種類', tags: ['DAG', 'DP'], io: '1行目に頂点数 n と辺数 m、続く m 行に有向辺 u v (閉路なし) が与えられます。', ask: '頂点1から頂点nへの経路の辺数として現れる値の種類数を出力してください(経路がなければ 0)。', h1: '経路数(同レベル既出)は総数、こちらは長さの集合。', h2: '各頂点から n への長さ集合をメモ化再帰で合成。', ref: 'import sys\nsys.setrecursionlimit(100000)\nn,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\nmemo={}\ndef lens(v):\n    if v==n:\n        return {0}\n    if v in memo:\n        return memo[v]\n    r=set()\n    for w in g[v]:\n        r|={x+1 for x in lens(w)}\n    memo[v]=r\n    return r\nprint(len(lens(1)))', tip: '数(カウント)でなく集合を運ぶDPで、値の合成が和から和集合に変わるだけ。種類数が多くなりすぎない(高々n)ことが計算量の保険になっている。', ins: ['4 4\n1 2\n2 4\n1 3\n3 4\n', '4 5\n1 2\n2 4\n1 3\n3 4\n1 4\n', '2 1\n1 2\n', '5 5\n1 2\n2 3\n3 5\n1 4\n4 5\n', '3 2\n1 2\n2 3\n', '6 7\n1 2\n2 6\n1 3\n3 4\n4 6\n1 6\n4 5\n'] })

t({ lv: 623, concept: 'ソート: 上位3つと下位3つの差', title: '表彰台とビリ3の開き', tags: ['ソート', 'リスト'], io: '整数列(3個以上)が1行で空白区切りで与えられます。', ask: '大きい方から3つの和と、小さい方から3つの和の差を出力してください。', h1: 'ソートしてスライス2つ。', h2: 'sum(a[-3:]) − sum(a[:3])。', ref: 'a=sorted(map(int,input().split()))\nprint(sum(a[-3:])-sum(a[:3]))', tip: '上位群と下位群の開きは格差の素朴な指標で、トリム平均(既出)が捨てる部分だけを見る裏返しの統計。n=3のときは差が0になる境界も確かめたい。', ins: ['1 2 3 4\n', '5 5 5\n', '1 1 1 10\n', '-5 0 5\n', '1 2 3 4 5 6\n', '9 1 1 1 9 9\n'] })

t({ lv: 624, concept: 'リスト: つなげてソート済みにできるか', title: 'どちらを先にすれば整列するか', tags: ['リスト'], io: '1行目と2行目に整数列が与えられます。', ask: '2つの列をこの順(1行目→2行目)か逆順(2行目→1行目)のどちらかで連結して、全体が広義単調増加にできるなら yes、できなければ no を出力してください(列の中身の並べ替えは不可)。', h1: '連結してソート済みかを2通り試す。', h2: '広義増加の判定は all(x<=y for 隣接)。', ref: 'a=list(map(int,input().split()))\nb=list(map(int,input().split()))\ndef ok(c):\n    return all(c[i]<=c[i+1] for i in range(len(c)-1))\nprint("yes" if ok(a+b) or ok(b+a) else "no")', tip: 'マージソートの併合が要らない特殊ケース(片方を丸ごと前に置ける)の検出。ログファイルの時系列連結など「並べ替えずに繋げてよいか」の事前チェックそのもの。', ins: ['1 2\n3 4\n', '3 4\n1 2\n', '1 3\n2 4\n', '5\n5\n', '2 2\n2 2\n', '1 4\n2 3\n'] })

t({ lv: 625, concept: 'リスト: 1回の交換で一致させられるか', title: 'ひと交換で瓜二つ', tags: ['リスト'], io: '1行目と2行目に同じ長さの整数列が与えられます。', ask: '1行目の列の中で高々1回、2要素を交換して2行目の列と完全に一致させられるなら yes、できなければ no を出力してください。', h1: '食い違う位置を集める。', h2: '0箇所ならそのままyes、ちょうど2箇所で互い違いならyes。', ref: 'a=list(map(int,input().split()))\nb=list(map(int,input().split()))\ndiff=[i for i in range(len(a)) if a[i]!=b[i]]\nif len(diff)==0:\n    print("yes")\nelif len(diff)==2 and a[diff[0]]==b[diff[1]] and a[diff[1]]==b[diff[0]]:\n    print("yes")\nelse:\n    print("no")', tip: '「差分を列挙してからパターン照合」は編集操作系の判定の定石で、1回の編集で一致(既出)の交換版。差分が2箇所ちょうど、かつクロス一致、という条件の絞りが気持ちいい。', ins: ['1 2 3\n1 3 2\n', '1 2 3\n1 2 3\n', '1 2\n2 1\n', '1 2 3\n3 2 1\n', '1 2 3\n1 1 3\n', '1 2 3 4\n4 3 2 1\n'] })

export const CATALOG = TASKS
