// 生成タスク 第72波：各レベル2問化フェーズ(27・最終)。lv971〜999 に2問目を追加。
// 最高峰帯後半: 数論/数え上げ/構成/パズル。重複なし・決定的・採点一意。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 971, concept: '数論: エジプト分数の貪欲分解', title: '単位分数の欲張り分解', tags: ['数論'], io: '既約分数の分子 a と分母 b (0<a<b) が空白区切りで1行で与えられます。', ask: 'a/b を「その時点で使える最大の単位分数を引く」貪欲法(フィボナッチ=シルベスター法)で単位分数の和に分解し、分母を順に空白区切りで出力してください。', h1: '次の単位分数の分母は ⌈b/a⌉。', h2: '引いた残り (a·d−b)/(b·d) を約分して繰り返す。分子は必ず減るので停止する。', ref: 'import math\na,b=map(int,input().split())\nout=[]\nwhile a>0:\n    d=-(-b//a)\n    out.append(d)\n    a,b=a*d-b,b*d\n    g=math.gcd(a,b) if a>0 else 1\n    if a>0:\n        a//=g\n        b//=g\nprint(*out)', tip: '貪欲で必ず有限分解になる(分子が厳密減少)のがフィボナッチの古典的証明。最短分解とは限らない(4/17など)ところに未解決のエルデシュ・シュトラウス予想が続く。', ins: ['2 3\n', '3 4\n', '4 5\n', '5 6\n', '2 7\n', '7 15\n'] })

t({ lv: 972, concept: '数論: 回文素数を数える', title: '回文でもある素数', tags: ['数論'], io: '正整数 N が1行で与えられます。', ask: '2 以上 N 以下で、素数かつ十進表記が回文である数の個数を出力してください。', h1: '2条件のANDで数える。', h2: '素数判定と文字列反転比較を組み合わせる。', ref: 'n=int(input())\ndef isp(x):\n    if x<2:\n        return False\n    i=2\n    while i*i<=x:\n        if x%i==0:\n            return False\n        i+=1\n    return True\ncnt=0\nfor x in range(2,n+1):\n    s=str(x)\n    if s==s[::-1] and isp(x):\n        cnt+=1\nprint(cnt)', tip: '偶数桁の回文は11の倍数なので、11以外の回文素数は必ず奇数桁。この観察だけで探索範囲が劇的に絞れる、性質の合わせ技の好例。', ins: ['10\n', '11\n', '100\n', '2\n', '200\n', '400\n'] })

t({ lv: 973, concept: '数論: ゼッケンドルフ表現の出力', title: 'フィボナッチ数の和に分解する', tags: ['数論', '貪欲'], io: '正整数 n が1行で与えられます。', ask: 'n を「連続しないフィボナッチ数の和」(ゼッケンドルフ表現)として、使うフィボナッチ数を大きい順に空白区切りで出力してください。', h1: 'n 以下の最大のフィボナッチ数を貪欲に引く。', h2: '貪欲に引くと自動的に「隣接するフィボナッチ数を使わない」一意な表現になる。', ref: 'n=int(input())\nfibs=[1,2]\nwhile fibs[-1]<=n:\n    fibs.append(fibs[-1]+fibs[-2])\nout=[]\nfor f in reversed(fibs):\n    if f<=n:\n        out.append(f)\n        n-=f\nprint(*out)', tip: '貪欲が一意性まで保証するのは「F(k+1)−1 = F(k)+F(k−2)+…」という上界のおかげ。フィボナッチ符号(データ圧縮)の理論的基盤でもある。', ins: ['10\n', '100\n', '1\n', '4\n', '19\n', '33\n'] })

t({ lv: 974, concept: '数論: タクシー数の判定', title: '1729は何通りに書けるか', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: 'n を2つの正の立方数の和 a³+b³ (a≤b) として表す方法の数を出力してください。', h1: 'a を1から立方が半分を超えるまで回す。', h2: '残り n−a³ が立方数かを整数の立方根で確かめる。', ref: 'n=int(input())\ncnt=0\na=1\nwhile 2*a**3<=n:\n    r=n-a**3\n    b=round(r**(1/3))\n    for bb in (b-1,b,b+1):\n        if bb>=a and bb**3==r:\n            cnt+=1\n    a+=1\nprint(cnt)', tip: '1729=1³+12³=9³+10³ はハーディとラマヌジャンのタクシー数。浮動小数の立方根は±1の検算を添えて整数で確定させるのが安全策。', ins: ['1729\n', '9\n', '4104\n', '10\n', '2\n', '20683\n'] })

t({ lv: 975, concept: '数論: フィボナッチ mod m に現れるか', title: 'その余りはフィボナッチに出てくるか', tags: ['数論'], io: 'm r が空白区切りで1行で与えられます (0≤r<m)。', ask: 'フィボナッチ数列を m で割った余りの列(周期的)に r が現れるなら yes、現れなければ no を出力してください。', h1: '余りの列はピサノ周期で循環する。', h2: '(前項, 今項) のペアが (0,1) に戻るまで生成して集合に集める。', ref: 'm,r=map(int,input().split())\nseen=set()\na,b=0,1\nwhile True:\n    seen.add(a)\n    a,b=b,(a+b)%m\n    if (a,b)==(0,1):\n        break\nprint("yes" if r in seen else "no")', tip: '周期の検出は「状態ペアの再訪」で判定するのが正確(値1つでは足りない)。m=8では余り4,6が現れない、など意外な欠番が見つかる。', ins: ['8 4\n', '8 1\n', '5 3\n', '7 5\n', '10 4\n', '4 3\n'] })

t({ lv: 976, concept: '数え上げ: 部分がm以下の合成の数', title: '一歩の上限つきで階段を作る', tags: ['数え上げ', 'DP'], io: 'n m が空白区切りで1行で与えられます。', ask: 'n を「1以上m以下の整数の順序つきの和(合成)」として表す方法の数を出力してください。', h1: '最後の項で場合分けする。', h2: 'dp[v] = dp[v−1]+…+dp[v−m]。', ref: 'n,m=map(int,input().split())\ndp=[0]*(n+1)\ndp[0]=1\nfor v in range(1,n+1):\n    dp[v]=sum(dp[max(0,v-m):v])\nprint(dp[n])', tip: 'm=2でフィボナッチ、m→∞で2^(n−1)。合成(順序あり)と分割(順序なし)の対比、および「直近m項の和」のスライド更新まで一続きに学べる。', ins: ['4 2\n', '5 3\n', '3 1\n', '6 6\n', '5 2\n', '10 3\n'] })

t({ lv: 977, concept: '数え上げ: 全サイクルが偶数長の順列', title: '偶数の輪だけでできた並べ替え', tags: ['数学'], io: '正整数 n が1行で与えられます。', ask: '1..n の順列でサイクルの長さが全て偶数のものの総数を出力してください(nが奇数なら0)。', h1: '奇数nでは総和が偶数にならないので不可能。', h2: 'n=2m のとき答えは ((2m−1)!!)²(二重階乗の平方)。', ref: 'n=int(input())\nif n%2==1:\n    print(0)\nelse:\n    r=1\n    for k in range(1,n,2):\n        r*=k\n    print(r*r)', tip: '全サイクル偶数長の順列数が二重階乗の平方になるのは、指数型母関数 1/√(1−x²) の係数から。奇数長のみ版は √((1+x)/(1−x)) と対になる。', ins: ['2\n', '3\n', '4\n', '6\n', '1\n', '8\n'] })

t({ lv: 978, concept: '数え上げ: 偶数人数の組だけの分割', title: 'ペア以上の偶数チームだけの分割', tags: ['数学', 'DP'], io: '正整数 n が1行で与えられます。', ask: 'n 人を「どの組も偶数人」になるように組に分ける方法(組に順序なし)の総数を出力してください(nが奇数なら0)。', h1: '1番の人が入る組の人数 2m で場合分け。', h2: 'e(n) = Σ C(n−1, 2m−1)·e(n−2m)。', ref: 'from math import comb\nn=int(input())\ne=[0]*(n+1)\ne[0]=1\nfor i in range(2,n+1):\n    total=0\n    for m in range(2,i+1,2):\n        total+=comb(i-1,m-1)*e[i-m]\n    e[i]=total\nprint(e[n])', tip: '「注目する1人の組で場合分け」はベル数の漸化式と同じ骨格で、組サイズの条件だけが総和の範囲に現れる。指数型母関数なら exp(cosh x −1) に対応。', ins: ['2\n', '4\n', '6\n', '3\n', '8\n', '1\n'] })

t({ lv: 979, concept: '数え上げ: 全単射でない写像の数', title: 'シャッフルにならない対応表', tags: ['数学'], io: '正整数 n が1行で与えられます。', ask: '集合 {1..n} から自分自身への写像のうち、全単射(並べ替え)に「ならない」ものの総数を出力してください。', h1: '写像は全部で nⁿ 個。', h2: '全単射は n! 個なので差を取る。', ref: 'from math import factorial\nn=int(input())\nprint(n**n-factorial(n))', tip: 'nが大きいとほぼ全ての写像が全単射でない(n!/nⁿ→0)。「ランダムな関数はまず衝突する」という誕生日のパラドックスの気分を式で確かめられる。', ins: ['1\n', '2\n', '3\n', '4\n', '5\n', '7\n'] })

t({ lv: 980, concept: '数え上げ: モツキン三角形', title: 'モツキンの三角形の一マス', tags: ['数学', 'DP'], io: 'n k が空白区切りで1行で与えられます (0≤k≤n)。', ask: 'モツキン三角形 T(n,k) (T(0,0)=1、T(n,k)=T(n−1,k−1)+T(n−1,k)+T(n−1,k+1)、範囲外は0)の値を出力してください。', h1: '3方向からの和で組み上がるパスカル型の三角形。', h2: '2次元表を埋めるだけ。T(n,0) がモツキン数になる。', ref: 'n,k=map(int,input().split())\nT=[[0]*(n+2) for _ in range(n+1)]\nT[0][0]=1\nfor i in range(1,n+1):\n    for j in range(0,i+1):\n        T[i][j]=T[i-1][j]+ (T[i-1][j-1] if j>0 else 0)+T[i-1][j+1]\nprint(T[n][k])', tip: '「高さkで終わるモツキン路の数」という歩道解釈を持ち、左端の列にモツキン数が並ぶ。パスカル・カタラン・モツキンの三角形ファミリーの一員。', ins: ['0 0\n', '2 0\n', '3 1\n', '4 0\n', '4 2\n', '5 3\n'] })

t({ lv: 981, concept: '数え上げ: 上下する歩みでnに立つ', title: '行ったり来たりでちょうど到達', tags: ['数え上げ', 'DP'], io: 'm n が空白区切りで1行で与えられます(m歩、目標位置n、負の位置も通ってよい)。', ask: '数直線の0から毎歩 +1 か −1 を選んで m 歩でちょうど位置 n に立つ方法の数を出力してください。', h1: '+1の回数 u と −1 の回数 d は u+d=m, u−d=n。', h2: '偶奇が合えば C(m, (m+n)/2)、合わなければ0。', ref: 'from math import comb\nm,n=map(int,input().split())\nif (m+n)%2!=0 or abs(n)>m:\n    print(0)\nelse:\n    print(comb(m,(m+n)//2))', tip: 'ランダムウォークの位置分布の分子そのもの。「制約なし歩き=二項係数1個」を土台に、非負制約を足すと鏡像原理、上限を足すと反射の繰り返しへ発展する。', ins: ['4 2\n', '4 3\n', '3 3\n', '5 -1\n', '6 0\n', '2 4\n'] })

t({ lv: 982, concept: 'DP: 2番目に安い塗り方', title: '次善の策の費用', tags: ['DP'], io: '1行目に 家の数 n と色数 k、続く n 行に各家の塗装費(k個)が与えられます(隣接する家は違う色)。', ask: '有効な塗り方すべての費用を小さい順に並べたとき、2番目の値を出力してください(同額の別の塗り方も数える。塗り方が2通り未満になる入力は与えられない)。', h1: '各(家,色)ごとに「上位2つの費用」を持てば足りる。', h2: '前の家の「自分と違う色の候補たち」の最小2つから遷移し、全体でも2つ保つ。', ref: 'import heapq\nn,k=map(int,input().split())\ncost=[list(map(int,input().split())) for _ in range(n)]\ndp=[[cost[0][c]] for c in range(k)]\nfor i in range(1,n):\n    nd=[]\n    for c in range(k):\n        cands=[]\n        for p in range(k):\n            if p!=c:\n                for v in dp[p]:\n                    cands.append(v+cost[i][c])\n        nd.append(sorted(cands)[:2])\n    dp=nd\nall_=[]\nfor c in range(k):\n    all_.extend(dp[c])\nall_.sort()\nprint(all_[1])', tip: 'k-best DPの最小形。「上位2つだけ運べば全体の上位2つが正しく出る」ことは、合成が単調(値の入替えで悪化しない)だから保証される。', ins: ['2 2\n1 10\n1 10\n', '1 3\n5 7 9\n', '2 3\n1 2 3\n1 2 3\n', '3 2\n1 1\n1 1\n1 1\n', '2 2\n3 4\n5 2\n', '3 3\n1 5 5\n5 1 5\n5 5 1\n'] })

t({ lv: 983, concept: 'ゲーム: Grundy列の周期を求める', title: 'ゲームの指紋の周期', tags: ['ゲーム', 'DP'], io: '1手で取れる個数の集合 S が1行で空白区切りで与えられます(周期は20以下であることが保証されます)。', ask: '取れる個数が S の石取りゲームのGrundy数の列 g(0),g(1),… は最終的に周期的になります。十分先での最小の周期を出力してください。', h1: 'まずGrundy列を十分先まで(例えば200項)計算する。', h2: '後半区間で g(i)=g(i+p) が全て成り立つ最小の p を探す。', ref: 'S=list(map(int,input().split()))\nN=200\ng=[0]*N\nfor i in range(1,N):\n    s=set(g[i-x] for x in S if i>=x)\n    r=0\n    while r in s:\n        r+=1\n    g[i]=r\np=1\nwhile True:\n    if all(g[i]==g[i+p] for i in range(100,N-p)):\n        print(p)\n        break\n    p+=1', tip: '有限の取り数集合なら Grundy 列は必ず最終的に周期的(状態が有限だから)。周期という「ゲームの指紋」を測ると、mod計算だけで巨大局面が読める。', ins: ['1 2\n', '1\n', '2 3\n', '1 4\n', '3\n', '1 2 3\n'] })

t({ lv: 984, concept: 'グラフ: 互いに行き来できるペアの総数', title: '相互到達ペアを全部数える', tags: ['グラフ', '再帰'], io: '1行目に n m、続く m 行に有向辺が与えられます。', ask: '順序を区別しないペア (u,v) (u<v) のうち、互いに到達し合える(同じ強連結成分に属す)ものの総数を出力してください。', h1: '強連結成分ごとに閉じた数え上げ。', h2: 'SCCを求め、各成分サイズ s から C(s,2) を合計する。', ref: 'import sys\nsys.setrecursionlimit(100000)\nn,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nrg=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    rg[v].append(u)\nseen=[False]*(n+1)\norder=[]\ndef dfs1(x):\n    seen[x]=True\n    for y in g[x]:\n        if not seen[y]:\n            dfs1(y)\n    order.append(x)\nfor v in range(1,n+1):\n    if not seen[v]:\n        dfs1(v)\ncomp=[0]*(n+1)\ndef dfs2(x,c):\n    comp[x]=c\n    for y in rg[x]:\n        if comp[y]==0:\n            dfs2(y,c)\nc=0\nfor v in reversed(order):\n    if comp[v]==0:\n        c+=1\n        dfs2(v,c)\nfrom collections import Counter\nsizes=Counter(comp[1:n+1])\nprint(sum(s*(s-1)//2 for s in sizes.values()))', tip: '「相互到達」は同値関係なので、答えは同値類(SCC)のサイズだけで決まる。1クエリの判定→全ペアの集計、と問いの粒度が上がってもSCC分解一発。', ins: ['3 3\n1 2\n2 3\n3 1\n', '3 2\n1 2\n2 3\n', '4 4\n1 2\n2 1\n3 4\n4 3\n', '2 0\n', '5 5\n1 2\n2 3\n3 1\n3 4\n4 5\n', '6 7\n1 2\n2 3\n3 1\n4 5\n5 6\n6 4\n1 4\n'] })

t({ lv: 985, concept: 'グラフ: ポテンシャルによる重みの非負化', title: '負の重みを消す魔法の高さ', tags: ['グラフ'], io: '1行目に n m、続く m 行に有向辺 u v w (負閉路なし)が与えられます。', ask: '全頂点に繋がる仮想始点からベルマンフォードで求めた最短距離 h(v) を、頂点1から順に空白区切りで出力してください(この h で w+h(u)−h(v) は全て非負になります)。', h1: '仮想頂点0から全頂点へ重み0の辺を張る。', h2: 'ベルマンフォードを n 回緩和すれば確定する。', ref: 'n,m=map(int,input().split())\nedges=[tuple(map(int,input().split())) for _ in range(m)]\nh=[0]*(n+1)\nfor _ in range(n):\n    for u,v,w in edges:\n        if h[u]+w<h[v]:\n            h[v]=h[u]+w\nprint(*h[1:])', tip: 'ジョンソンのアルゴリズムの前処理そのもの。h は物理のポテンシャルと同じ役割で、どの経路も出発と到着の h 差だけ補正される(経路和は不変)。', ins: ['3 3\n1 2 -2\n2 3 -1\n1 3 1\n', '2 1\n1 2 5\n', '3 2\n1 2 -1\n3 1 -1\n', '2 2\n1 2 -3\n2 1 4\n', '4 4\n1 2 1\n2 3 -2\n3 4 1\n1 4 -1\n', '1 0\n'] })

t({ lv: 986, concept: '木: 根なし木の同型判定', title: '植え替えても同じ木か', tags: ['木', '再帰'], io: '1行目に頂点数 n。続く n−1 行に1本目の木の辺、さらに n−1 行に2本目の木の辺が与えられます。', ask: '2つの木が(頂点番号を無視して)同型なら yes、そうでなければ no を出力してください。', h1: '根なし木は「中心」を根にすると標準形が定まる。', h2: '中心(1つか2つ)を根にAHU符号化し、候補どうしで一致を見る。', ref: 'import sys\nsys.setrecursionlimit(100000)\ndef read_tree(n):\n    g=[[] for _ in range(n+1)]\n    for _ in range(n-1):\n        u,v=map(int,input().split())\n        g[u].append(v)\n        g[v].append(u)\n    return g\ndef centers(g,n):\n    if n==1:\n        return [1]\n    deg=[len(g[v]) for v in range(n+1)]\n    leaves=[v for v in range(1,n+1) if deg[v]==1]\n    removed=len(leaves)\n    while removed<n:\n        nxt=[]\n        for v in leaves:\n            for u in g[v]:\n                deg[u]-=1\n                if deg[u]==1:\n                    nxt.append(u)\n        removed+=len(nxt)\n        leaves=nxt\n    return leaves\ndef enc(g,v,p):\n    subs=sorted(enc(g,c,v) for c in g[v] if c!=p)\n    return "("+"".join(subs)+")"\nn=int(input())\ng1=read_tree(n)\ng2=read_tree(n)\nc1=[enc(g1,c,0) for c in centers(g1,n)]\nc2=[enc(g2,c,0) for c in centers(g2,n)]\nprint("yes" if set(c1)&set(c2) else "no")', tip: '根の取り方の自由度を「中心は高々2つ」で潰すのが根なし版のポイント。AHU符号+ソートで子の順序の自由度も消え、木の同型は多項式時間で片付く。', ins: ['3\n1 2\n2 3\n1 3\n3 2\n', '4\n1 2\n1 3\n1 4\n1 2\n2 3\n2 4\n', '4\n1 2\n2 3\n3 4\n1 2\n1 3\n1 4\n', '2\n1 2\n2 1\n', '5\n1 2\n2 3\n3 4\n3 5\n5 4\n4 3\n3 2\n3 1\n', '5\n1 2\n1 3\n1 4\n1 5\n1 2\n2 3\n3 4\n4 5\n'] })

t({ lv: 987, concept: '木: プリューファー列への符号化', title: '木を数列に変換する', tags: ['木'], io: '1行目に頂点数 n (n≥3)、続く n−1 行に木の辺が与えられます。', ask: 'この木のプリューファー列(番号最小の葉を取り除き、その隣接頂点を記録、を n−2 回)を空白区切りで出力してください。', h1: '葉の中で最小の番号を効率よく取りたい。', h2: '次数配列と「現在の最小葉」を管理し、取り除いた隣が新たに葉になったら候補に加える。', ref: 'import heapq\nn=int(input())\ng=[[] for _ in range(n+1)]\ndeg=[0]*(n+1)\nfor _ in range(n-1):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\n    deg[u]+=1\n    deg[v]+=1\nremoved=[False]*(n+1)\nh=[v for v in range(1,n+1) if deg[v]==1]\nheapq.heapify(h)\nout=[]\nfor _ in range(n-2):\n    leaf=heapq.heappop(h)\n    removed[leaf]=True\n    for u in g[leaf]:\n        if not removed[u]:\n            out.append(u)\n            deg[u]-=1\n            if deg[u]==1:\n                heapq.heappush(h,u)\n            break\nprint(*out)', tip: '復元(列→木)と符号化(木→列)が互いに逆写像で、ケイリーの公式 n^(n−2) の全単射証明が完成する。最小葉のヒープ管理でO(n log n)。', ins: ['3\n1 2\n2 3\n', '4\n1 2\n1 3\n1 4\n', '4\n1 2\n2 3\n3 4\n', '5\n1 2\n2 3\n2 4\n4 5\n', '3\n1 3\n2 3\n', '6\n1 6\n2 6\n3 6\n4 6\n5 6\n'] })

t({ lv: 988, concept: '数え上げ: 全部分列の積の総和', title: '選び方すべての積を足すと', tags: ['数学'], io: '整数列が1行で空白区切りで与えられます。', ask: '空でない全ての部分列(添字の部分集合)について要素の積を計算し、その総和を出力してください。', h1: '2ⁿ個の積を展開すると綺麗な形になる。', h2: 'Π(1+aᵢ) − 1(各要素を「入れる/入れない」の展開そのもの)。', ref: 'a=list(map(int,input().split()))\np=1\nfor x in a:\n    p*=(1+x)\nprint(p-1)', tip: '積の展開 Π(1+aᵢ) = Σ(部分集合の積) は母関数の考え方の最小単位。−1が空集合の分、と対応まで言えると展開が「見える」ようになる。', ins: ['1 2\n', '1 2 3\n', '2\n', '0 5\n', '-1 3\n', '1 1 1 1\n'] })

t({ lv: 989, concept: '累積和: 釣り合う接頭辞の数', title: '途中経過が五分五分になる回数', tags: ['累積和'], io: '( と ) の文字列が1行で与えられます。', ask: '先頭からの部分文字列(接頭辞)のうち、( と ) の個数が等しいものの個数を出力してください(空の接頭辞は数えない)。', h1: 'バランスの値を走らせる。', h2: '(で+1、)で−1し、0に戻った回数を数える。', ref: 's=input()\nbal=0\ncnt=0\nfor c in s:\n    bal+=1 if c=="(" else -1\n    if bal==0:\n        cnt+=1\nprint(cnt)', tip: 'バランス0への回帰は「これ以上分解できない単位(プライム括弧列)」の境界。正しい括弧列ならこの回数が最大分解数になる。', ins: ['()()\n', '(())\n', '(()())()\n', ')(\n', '((((\n', '()\n'] })

t({ lv: 990, concept: '数え上げ: 1箇所の反転で正せる位置', title: 'どこを裏返せば直るか', tags: ['数え上げ'], io: '( と ) の文字列が1行で与えられます(正しい括弧列ではありません)。', ask: 'ちょうど1文字を反転( ( ↔ ) )して正しい括弧列にできる位置の個数を出力してください。', h1: '長さが奇数なら0。', h2: '各位置を反転して検証してもよいが、合計の過不足から反転すべき種類が決まり、候補が絞れる。', ref: 's=input()\nn=len(s)\ndef ok(t):\n    b=0\n    for c in t:\n        b+=1 if c=="(" else -1\n        if b<0:\n            return False\n    return b==0\ncnt=0\nfor i in range(n):\n    t=s[:i]+("(" if s[i]==")" else ")")+s[i+1:]\n    if ok(t):\n        cnt+=1\nprint(cnt)', tip: '全数検証O(n²)から始め ,「( が2個多い→反転は ( の中の特定範囲だけ」と絞ればO(n)にできる。答えの位置が連続することも観察できる。', ins: ['((()\n', ')(\n', '()((\n', '))((\n', ')\n', '()))\n'] })

t({ lv: 991, concept: '数え上げ: 分割の共役(転置)を求める', title: 'ヤング図形をひっくり返す', tags: ['数学'], io: '分割(広義単調減少の正整数列)が1行で空白区切りで与えられます。', ask: 'この分割の共役分割(ヤング図形の転置)を空白区切りで出力してください。', h1: '共役の第i項は「i以上の部分の個数」。', h2: 'i を1から最大値まで回して数える。', ref: 'a=list(map(int,input().split()))\nout=[]\nfor i in range(1,a[0]+1):\n    out.append(sum(1 for x in a if x>=i))\nprint(*out)', tip: '転置を2回すると元に戻る対合。分割の恒等式の多く(最大部分k以下⇔部分数k以下など)は、この転置で「無料で」証明できる。', ins: ['3 2 1\n', '4 4\n', '5\n', '2 2 2\n', '3 1 1\n', '1 1 1 1\n'] })

t({ lv: 992, concept: '数論: シュターン・ブロコ木の道から分数', title: '左右の道順が指す分数', tags: ['数論'], io: 'L と R からなる文字列(空文字列の場合は - 1文字)が1行で与えられます。', ask: 'シュターン・ブロコ木を根 1/1 から、L なら左(小さい方)、R なら右(大きい方)へ辿ったときに到達する分数を「分子 分母」で出力してください(- は根)。', h1: '区間 (0/1, 1/0) を狭めながらメディアントを取る。', h2: '左なら右端を、右なら左端を現在のメディアントに置き換える。', ref: 's=input()\nla,lb=0,1\nra,rb=1,0\nfor c in s:\n    ma,mb=la+ra,lb+rb\n    if c=="L":\n        ra,rb=ma,mb\n    elif c=="R":\n        la,lb=ma,mb\nprint(la+ra,lb+rb)', tip: '全ての正の既約分数がちょうど1回ずつ現れる魔法の木。道順の文字列は連分数展開と一対一に対応し、ユークリッドの互除法を木の上で歩いている。', ins: ['-\n', 'L\n', 'R\n', 'LR\n', 'RRL\n', 'LLLL\n'] })

t({ lv: 993, concept: '数え上げ: 立ちビットがk個の数の個数', title: '1がちょうどk個の数を数える', tags: ['数え上げ', 'bit演算'], io: 'N k が空白区切りで1行で与えられます。', ask: '0 以上 N 以下で、2進表記の1の個数がちょうど k である数の個数を出力してください。', h1: '小さいNなら全数チェックで十分。', h2: '大きなNでは上位ビットから「ここで0にした場合は残りが自由=二項係数」を足していく桁DPになる。', ref: 'N,k=map(int,input().split())\nprint(sum(1 for x in range(N+1) if bin(x).count("1")==k))', tip: '全数→二項係数の桁DPへの高速化は、10進の桁DPと全く同じ骨格を2進でやるだけ。popcount分布は組合せ論のパスカル三角形の別の顔。', ins: ['10 2\n', '15 4\n', '7 1\n', '0 0\n', '31 3\n', '100 3\n'] })

t({ lv: 994, concept: 'bit演算: 1に挟まれた0の最長', title: 'バイナリギャップの長さ', tags: ['bit演算'], io: '正整数 n が1行で与えられます。', ask: 'n の2進表記で、両端を1に挟まれた連続する0の並びの最大の長さを出力してください(存在しなければ0)。', h1: '末尾や先頭の0は挟まれていない。', h2: '最初の1以降、1に出会うたびに「直前の1からの距離−1」を候補にする。', ref: 'n=int(input())\ns=bin(n)[2:]\nbest=0\nprev=-1\nfor i,c in enumerate(s):\n    if c=="1":\n        if prev>=0 and i-prev-1>best:\n            best=i-prev-1\n        prev=i\nprint(best)', tip: '「挟まれている」条件は右端の処理を自然に排除する(最後の1以降は候補にならない)。文字列化せずビット演算だけで書く別解も良い練習。', ins: ['9\n', '529\n', '20\n', '15\n', '32\n', '1041\n'] })

t({ lv: 995, concept: '数え上げ: 交わり合う円の領域数', title: 'n個の円が平面を分ける数', tags: ['数学'], io: '正整数 n が1行で与えられます。', ask: 'どの2つの円も2点で交わり、3つ以上の円が1点で交わらないように n 個の円を描いたとき、平面が分かれる領域の数 n²−n+2 を出力してください。', h1: '円を1つ足すと既存の各円と2点で交わる。', h2: 'k個目の円は 2(k−1) 個の交点で 2(k−1) 個の弧に分かれ、その数だけ領域が増える。', ref: 'n=int(input())\nprint(n*n-n+2)', tip: 'オイラーの公式 V−E+F=2 からも導ける。直線の場合(1+n+C(n,2))と並べると「新入りが何回既存を横切るか」だけが領域の増分を決めると分かる。', ins: ['1\n', '2\n', '3\n', '4\n', '5\n', '10\n'] })

t({ lv: 996, concept: '数え上げ: 平行な束を含む直線の領域数', title: '平行線グループが作る領域', tags: ['数学'], io: '各平行グループの本数が1行で空白区切りで与えられます(異なるグループの直線どうしは必ず1点で交わり、3本以上は1点で交わらない)。', ask: '全ての直線が平面を分ける領域の数を出力してください。', h1: '領域数は 1 + 直線数 + 交点数。', h2: '交点は異なるグループの組ごとに 本数の積 だけできる。', ref: 'g=list(map(int,input().split()))\nL=sum(g)\ncross=0\nfor i in range(len(g)):\n    for j in range(i+1,len(g)):\n        cross+=g[i]*g[j]\nprint(1+L+cross)', tip: '一般位置の公式 1+n+C(n,2) の「交点が減ると領域も減る」補正版。平面分割は結局「交点の数勘定」に帰着する、が貫通する考え方。', ins: ['1\n', '2 1\n', '3\n', '2 2\n', '1 1 1\n', '3 2 1\n'] })

t({ lv: 997, concept: '数え上げ: d次元をn枚で分ける領域数', title: '高次元のケーキカット', tags: ['数学'], io: 'd n が空白区切りで1行で与えられます(一般の位置にある n 枚の超平面で d 次元空間を分割)。', ask: '分かれる領域の数 Σ C(n,k) (k=0..d) を出力してください。', h1: '1次元は n+1、2次元は 1+n+C(n,2)、の一般形。', h2: '二項係数の部分和を計算する。', ref: 'from math import comb\nd,n=map(int,input().split())\nprint(sum(comb(n,k) for k in range(d+1)))', tip: '次元での帰納法「切り口は1次元下の分割問題」で導ける美しい公式。n≤d なら 2ⁿ に一致し、超平面配置(アレンジメント)理論の入り口になる。', ins: ['1 3\n', '2 3\n', '3 3\n', '2 5\n', '3 6\n', '4 4\n'] })

t({ lv: 998, concept: '数論: 安全素数の判定', title: '暗号が好む安全素数', tags: ['数論'], io: '正整数 p が1行で与えられます。', ask: 'p が安全素数(p が素数で、(p−1)/2 も素数)なら yes、そうでなければ no を出力してください。', h1: '2つの素数判定の組合せ。', h2: '(p−1)/2 が整数になる(pが奇数)ことも含めて確かめる。', ref: 'p=int(input())\ndef isp(x):\n    if x<2:\n        return False\n    i=2\n    while i*i<=x:\n        if x%i==0:\n            return False\n        i+=1\n    return True\nprint("yes" if isp(p) and p%2==1 and isp((p-1)//2) else "no")', tip: '相方 (p−1)/2 はソフィー・ジェルマン素数。位数の大きな部分群を保証するためDiffie-Hellmanの法として好まれる、実用直結の素数クラス。', ins: ['7\n', '11\n', '13\n', '5\n', '23\n', '2\n'] })

t({ lv: 999, concept: 'パズル: 15パズルの可解判定', title: 'そのスライドパズルは解けるか', tags: ['パズル', '数え上げ'], io: '4行に4個ずつ、0(空きマス)と1〜15の数字が与えられます。', ask: 'スライド操作だけで正解配置(1..15を行順に並べ、右下が空き)にできるなら yes、できなければ no を出力してください。', h1: '不変量は「転倒数」と「空きマスの行」。', h2: '0を除いた並びの転倒数と、空きマスの下からの行番号の和の偶奇が一定。転倒数+空きの下からの行数が偶数なら可解(4×4の場合)。', ref: 'g=[]\nfor _ in range(4):\n    g.extend(map(int,input().split()))\nblank_row_from_bottom=4-(g.index(0)//4)\nseq=[x for x in g if x!=0]\ninv=0\nfor i in range(len(seq)):\n    for j in range(i+1,len(seq)):\n        if seq[i]>seq[j]:\n            inv+=1\nprint("yes" if (inv+blank_row_from_bottom)%2==0 else "no")', tip: 'サム・ロイドが「14と15の入替え」に賞金を懸けた歴史的パズル。1回のスライド=置換の互換+空き行の変化、で偶奇不変量が保存されるのが証明の芯。', ins: ['1 2 3 4\n5 6 7 8\n9 10 11 12\n13 14 15 0\n', '1 2 3 4\n5 6 7 8\n9 10 11 12\n13 15 14 0\n', '1 2 3 4\n5 6 7 8\n9 10 11 12\n13 14 0 15\n', '0 1 2 3\n5 6 7 4\n9 10 11 8\n13 14 15 12\n', '2 1 3 4\n5 6 7 8\n9 10 11 12\n13 14 15 0\n', '5 1 2 3\n9 6 7 4\n13 10 11 8\n14 15 0 12\n'] })

export const CATALOG = TASKS
