// 生成タスク 第48波：各レベル2問化フェーズ(3)。lv140〜192 に2問目を追加。
// LeetCode/AtCoder頻出パターンの「要素」を配置。重複なし・決定的・採点一意。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 140, concept: '配列: 1回の売買の最大利益', title: '株を1回売買する最大利益', tags: ['配列'], io: '価格の列が1行で与えられます。', ask: '1回だけ買って後で売るときの最大利益を出力してください(利益が出なければ0)。', h1: 'これまでの最安値を保持する。', h2: '各日で売った利益の最大を更新。', ref: 'a=list(map(int,input().split()))\nlow=a[0]\nbest=0\nfor x in a:\n    if x-low>best:\n        best=x-low\n    if x<low:\n        low=x\nprint(best)', tip: '1回売買の最大利益は「これまでの最安値」を追い、各日の利益を更新する O(n)。', ins: ['7 1 5 3 6 4\n', '7 6 4 3 1\n', '5\n', '1 2 3 4 5\n', '3 3 3\n', '2 4 1 7\n'] })

t({ lv: 141, concept: '数列: 隣り合うフィボナッチ数の比', title: 'フィボナッチの比が近づく先', tags: ['数列'], io: '正の整数 n (1以上) が1行で与えられます。', ask: 'F(1)を1、F(2)を1とするフィボナッチ数列について、F(n+1) を F(n) で割った値を小数第6位まで出力してください。', h1: 'F(n) と F(n+1) を同時に持って反復で進める。', h2: '出力は f"{x:.6f}" で桁を固定する。', ref: 'n=int(input())\na,b=1,1\nfor _ in range(n-1):\n    a,b=b,a+b\nprint(f"{b/a:.6f}")', tip: '隣り合う項の比は黄金比に急速に近づく。n が 30 も進めば小数6桁ではもう動かず、およそ 1.618034 に落ち着く。数列そのものは爆発的に増えるのに、比だけが静かに収束するのが面白いところ。', ins: ['1\n', '2\n', '3\n', '5\n', '10\n', '30\n'] })

t({ lv: 142, concept: '配列: 局所最大の数', title: '山(局所最大)の個数', tags: ['配列'], io: '整数列が1行で与えられます。', ask: '両隣より真に大きい要素(局所最大)の個数を出力してください(端は対象外)。', h1: '内側の各位置を見る。', h2: '左右より大きいか判定。', ref: 'a=list(map(int,input().split()))\ncnt=0\nfor i in range(1,len(a)-1):\n    if a[i]>a[i-1] and a[i]>a[i+1]:\n        cnt+=1\nprint(cnt)', tip: '局所最大(ピーク)は両隣より大きい内部要素。地形解析や極値検出の基本。', ins: ['1 3 2 4 1\n', '1 2 3\n', '3 2 1\n', '5\n', '1 2 1 2 1\n', '1 1 1\n'] })

t({ lv: 143, concept: '配列: 釣り合いの添字', title: '左右の和が等しい添字', tags: ['配列'], io: '整数列が1行で与えられます。', ask: '左側の和と右側の和が等しくなる最初の添字(0始まり)を出力してください。無ければ -1。', h1: '総和と左和を持つ。', h2: '左==総和-左-自分 で判定。', ref: 'a=list(map(int,input().split()))\ntotal=sum(a)\nleft=0\nans=-1\nfor i in range(len(a)):\n    if left==total-left-a[i]:\n        ans=i\n        break\n    left+=a[i]\nprint(ans)', tip: '釣り合い(pivot)添字は左和と右和(=総和-左和-自分)の比較を1パスで。', ins: ['1 7 3 6 5 6\n', '1 2 3\n', '2 1 -1\n', '0\n', '1 1 1\n', '-1 -1 -1 0 1 1\n'] })

t({ lv: 144, concept: '配列: リーダーの数', title: '右側のどれより大きい要素の数', tags: ['配列'], io: '整数列が1行で与えられます。', ask: '自分より右にあるすべての要素より大きい(または末尾)要素(リーダー)の個数を出力してください。', h1: '右から最大を追う。', h2: '今まで見た最大を超えたらリーダー。', ref: 'a=list(map(int,input().split()))\nbest=float("-inf")\ncnt=0\nfor x in reversed(a):\n    if x>best:\n        cnt+=1\n        best=x\nprint(cnt)', tip: 'リーダーは「右側の最大より大きい要素」。右から走査して累積最大を更新するだけ。', ins: ['16 17 4 3 5 2\n', '1 2 3\n', '3 2 1\n', '5\n', '1 1 1\n', '5 4 6 3 7\n'] })

t({ lv: 145, concept: 'ハッシュ: 和0の最長部分配列', title: '和が0の最長連続部分配列の長さ', tags: ['ハッシュ'], io: '整数列が1行で与えられます。', ask: '和が0になる最長の連続部分配列の長さを出力してください。無ければ0。', h1: '累積和の最初の出現位置を記録。', h2: '同じ累積和の再出現で長さ更新。', ref: 'a=list(map(int,input().split()))\nfirst={0:-1}\ns=0\nbest=0\nfor i,x in enumerate(a):\n    s+=x\n    if s in first:\n        best=max(best,i-first[s])\n    else:\n        first[s]=i\nprint(best)', tip: '和0の最長区間は「累積和が等しい最遠の2点」。最初の出現位置を辞書に残す。', ins: ['1 -1 3 -3 2\n', '1 2 3\n', '0 0 0\n', '5\n', '1 2 -3 4\n', '-1 1 -1 1\n'] })

t({ lv: 146, concept: '文字列: 各文字を次の文字へ', title: '各文字を次のアルファベットに', tags: ['文字列'], io: '英小文字の文字列が1行で与えられます。', ask: '各文字を次の文字に(z は a に巡回して)置き換えた文字列を出力してください。', h1: 'ord で数値化する。', h2: '+1して26で巡回。', ref: 's=input()\nprint("".join(chr((ord(c)-97+1)%26+97) for c in s))', tip: '次の文字への巡回は (文字-基準+1)%26+基準。z→a の折り返しがポイント。', ins: ['abc\n', 'xyz\n', 'hello\n', 'z\n', 'az\n', 'world\n'] })

t({ lv: 147, concept: '文字列: 1つ飛ばしで抽出', title: '偶数番目の文字を抜き出す', tags: ['文字列'], io: '文字列が1行で与えられます。', ask: '0,2,4,... 番目(偶数添字)の文字だけを抜き出した文字列を出力してください。', h1: 'スライスのステップを使う。', h2: 's[::2]。', ref: 's=input()\nprint(s[::2])', tip: 'ステップ付きスライス s[::2] で1つ飛ばし抽出。s[1::2] なら奇数番目になる。', ins: ['abcdef\n', 'abc\n', 'a\n', 'hello\n', 'python\n', 'xy\n'] })

t({ lv: 148, concept: '文字列: 最長の同一文字連続', title: '同じ文字が連続する最大長', tags: ['文字列'], io: '文字列が1行で与えられます。', ask: '同じ文字が連続する最大の長さを出力してください。', h1: '直前と同じか見る。', h2: '連続長の最大を取る。', ref: 's=input()\nif not s:\n    print(0)\nelse:\n    best=1\n    cur=1\n    for i in range(1,len(s)):\n        if s[i]==s[i-1]:\n            cur+=1\n            if cur>best:\n                best=cur\n        else:\n            cur=1\n    print(best)', tip: '同一文字の最長連続はリセット型走査。ランレングスの最大ラン長に等しい。', ins: ['aaabb\n', 'abc\n', 'aaaa\n', 'a\n', 'aabbbbcc\n', 'xy\n'] })

t({ lv: 149, concept: '文字列: 重なりありの出現回数', title: 'パターンの出現回数(重なり可)', tags: ['文字列'], io: '1行目に本文、2行目にパターンが与えられます。', ask: '本文中にパターンが現れる回数(重なりを許す)を出力してください。', h1: '各開始位置で一致を見る。', h2: 'スライスで比較する。', ref: 'text=input()\npat=input()\nm=len(pat)\ncnt=0\nfor i in range(len(text)-m+1):\n    if text[i:i+m]==pat:\n        cnt+=1\nprint(cnt)', tip: '重なり許容の出現回数は各開始位置でスライス比較。str.count は重なりを数えない点に注意。', ins: ['aaaa\naa\n', 'abcabc\nabc\n', 'abc\nd\n', 'aaa\na\n', 'banana\nana\n', 'xyz\nxyz\n'] })

t({ lv: 151, concept: '配列: 対称行列の判定', title: '対称行列かどうか', tags: ['配列'], io: '1行目に n、続く n 行に n 個の整数が与えられます。', ask: '行列が対称(g[i][j]==g[j][i])なら yes、違うなら no を出力してください。', h1: '転置と比較する。', h2: '全 i,j で確認。', ref: 'n=int(input())\ng=[list(map(int,input().split())) for _ in range(n)]\nok=all(g[i][j]==g[j][i] for i in range(n) for j in range(n))\nprint("yes" if ok else "no")', tip: '対称行列は g==g.T。転置と一致するかで判定する。共分散行列などで重要な性質。', ins: ['2\n1 2\n2 1\n', '2\n1 2\n3 4\n', '1\n5\n', '3\n1 0 0\n0 1 0\n0 0 1\n', '2\n0 1\n1 0\n', '3\n1 2 3\n2 4 5\n3 5 6\n'] })

t({ lv: 152, concept: '配列: 単位行列の判定', title: '単位行列かどうか', tags: ['配列'], io: '1行目に n、続く n 行に n 個の整数が与えられます。', ask: '単位行列(対角が1、他が0)なら yes、違うなら no を出力してください。', h1: '対角は1、非対角は0。', h2: '全要素を確認。', ref: 'n=int(input())\ng=[list(map(int,input().split())) for _ in range(n)]\nok=all(g[i][j]==(1 if i==j else 0) for i in range(n) for j in range(n))\nprint("yes" if ok else "no")', tip: '単位行列は対角1・他0。行列積の単位元で、判定は各位置を期待値と比較するだけ。', ins: ['2\n1 0\n0 1\n', '2\n1 1\n0 1\n', '1\n1\n', '1\n0\n', '3\n1 0 0\n0 1 0\n0 0 1\n', '2\n1 0\n0 2\n'] })

t({ lv: 153, concept: '配列: 行列の0の数', title: '行列中の0の個数', tags: ['配列'], io: '1行目に R C、続く R 行に行列が与えられます。', ask: '値が0の要素の個数を出力してください。', h1: '全要素を走査する。', h2: '0を数える。', ref: 'first=input().split()\nR=int(first[0])\nC=int(first[1])\ng=[list(map(int,input().split())) for _ in range(R)]\nprint(sum(1 for row in g for x in row if x==0))', tip: '疎行列の非ゼロ率などで使う。行列の平坦走査は二重の内包表記が簡潔。', ins: ['2 2\n0 1\n0 0\n', '1 1\n5\n', '2 3\n1 2 3\n4 5 6\n', '2 2\n0 0\n0 0\n', '1 4\n0 1 0 1\n', '3 1\n0\n0\n0\n'] })

t({ lv: 154, concept: '数論: n以下の素数の最大間隔', title: '素数と素数のいちばん広い隙間', tags: ['数論'], io: '2 以上の整数 n が1行で与えられます。', ask: 'n 以下の素数を小さい順に並べたとき、隣り合う2つの素数の差の最大値を出力してください。素数が1個以下しかないときは 0 を出力してください。', h1: 'まず篩で n 以下の素数を列挙する。', h2: '並んだ素数の隣同士の差を順に見て最大を取る。', ref: 'n=int(input())\nsieve=[True]*(n+1)\nsieve[0]=False\nsieve[1]=False\ni=2\nwhile i*i<=n:\n    if sieve[i]:\n        for j in range(i*i,n+1,i):\n            sieve[j]=False\n    i+=1\nps=[k for k in range(2,n+1) if sieve[k]]\nbest=0\nfor k in range(1,len(ps)):\n    d=ps[k]-ps[k-1]\n    if d>best:\n        best=d\nprint(best)', tip: '素数はだんだん疎になるが隙間の広がり方はゆっくりで、100以下では最大 8 にしかならない(89 と 97 の間)。篩で列挙してから隣接差を走査する、列挙と走査の二段構え。', ins: ['2\n', '3\n', '10\n', '30\n', '50\n', '100\n'] })

t({ lv: 155, concept: '数論: n番目の素数', title: 'n番目の素数', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: 'n 番目の素数を出力してください(1番目は2)。', h1: '素数を順に見つける。', h2: 'n 個目を返す。', ref: 'n=int(input())\ndef is_prime(x):\n    if x<2:\n        return False\n    d=2\n    while d*d<=x:\n        if x%d==0:\n            return False\n        d+=1\n    return True\ncnt=0\nnum=1\nwhile cnt<n:\n    num+=1\n    if is_prime(num):\n        cnt+=1\nprint(num)', tip: 'n番目の素数は2から順に素数判定して数える。大きいnは篩で上限を見積もる。', ins: ['1\n', '2\n', '5\n', '10\n', '3\n', '25\n'] })

t({ lv: 156, concept: '数論: n以下で約数がちょうど3個の数の個数', title: '約数がちょうど3つの数を数える', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: '1 以上 n 以下で、約数の個数がちょうど3個である数の個数を出力してください。', h1: '約数がちょうど3個になるのはどんな形の数か考える。', h2: '素数 p の2乗のときだけ、約数が 1 と p と p の2乗の3個になる。', ref: 'n=int(input())\ndef isp(x):\n    if x<2:\n        return False\n    i=2\n    while i*i<=x:\n        if x%i==0:\n            return False\n        i+=1\n    return True\ncnt=0\np=2\nwhile p*p<=n:\n    if isp(p):\n        cnt+=1\n    p+=1\nprint(cnt)', tip: '約数の個数がちょうど3個になるのは素数の2乗だけ。1 と p と p の2乗しか割り切れないからで、答えは「平方根以下の素数の個数」に一致する。個数という結果から数の形を逆算する練習。', ins: ['10\n', '1\n', '25\n', '3\n', '50\n', '1000\n'] })

t({ lv: 157, concept: '数論: 偶数の約数の和', title: '偶数である約数の総和', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: 'n の約数のうち偶数であるものの総和を出力してください。', h1: '約数を列挙する。', h2: '偶数のものを足す。', ref: 'n=int(input())\ns=0\nd=1\nwhile d*d<=n:\n    if n%d==0:\n        if d%2==0:\n            s+=d\n        e=n//d\n        if e!=d and e%2==0:\n            s+=e\n    d+=1\nprint(s)', tip: '約数を√nまでペアで列挙し、偶数のものだけ足す。奇数nなら偶約数は0。', ins: ['12\n', '7\n', '6\n', '1\n', '100\n', '8\n'] })

t({ lv: 158, concept: '数論: 偶数の約数の個数', title: '偶数である約数の個数', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: 'n の約数のうち偶数であるものの個数を出力してください。', h1: '約数を列挙する。', h2: '偶数のものを数える。', ref: 'n=int(input())\nc=0\nd=1\nwhile d*d<=n:\n    if n%d==0:\n        if d%2==0:\n            c+=1\n        e=n//d\n        if e!=d and e%2==0:\n            c+=1\n    d+=1\nprint(c)', tip: '偶約数の個数も√n列挙で。n=2^a·m(m奇)のとき a·d(m) 個という公式もある。', ins: ['12\n', '7\n', '6\n', '1\n', '16\n', '8\n'] })

t({ lv: 159, concept: '数論: 奇数の約数の個数', title: '奇数である約数の個数', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: 'n の約数のうち奇数であるものの個数を出力してください。', h1: '約数を列挙する。', h2: '奇数のものを数える。', ref: 'n=int(input())\nc=0\nd=1\nwhile d*d<=n:\n    if n%d==0:\n        if d%2==1:\n            c+=1\n        e=n//d\n        if e!=d and e%2==1:\n            c+=1\n    d+=1\nprint(c)', tip: '奇約数の個数は n から2の因数を全て除いた奇部分 m の約数の個数 d(m) に等しい。', ins: ['12\n', '7\n', '6\n', '1\n', '15\n', '8\n'] })

t({ lv: 161, concept: '配列: 最長の非増加連続', title: '非増加が続く最大長', tags: ['配列'], io: '整数列が1行で与えられます。', ask: '非増加(>=)が続く最長の連続部分配列の長さを出力してください。', h1: '直前以下なら伸ばす。', h2: '崩れたらリセット。', ref: 'a=list(map(int,input().split()))\nif not a:\n    print(0)\nelse:\n    best=1\n    cur=1\n    for i in range(1,len(a)):\n        if a[i]<=a[i-1]:\n            cur+=1\n            if cur>best:\n                best=cur\n        else:\n            cur=1\n    print(best)', tip: '非増加(>=)の最長連続はリセット型走査。降順の連続区間検出に使う。', ins: ['5 4 4 2 6\n', '1 2 3\n', '3 2 1\n', '5\n', '5 5 5\n', '9 7 8 6 5\n'] })

t({ lv: 162, concept: '配列: 相異なる絶対値の数', title: '相異なる絶対値の種類数', tags: ['配列', '集合'], io: '整数列が1行で与えられます。', ask: '絶対値の相異なる種類数を出力してください。', h1: '絶対値を集合に入れる。', h2: '要素数を取る。', ref: 'a=list(map(int,input().split()))\nprint(len(set(abs(x) for x in a)))', tip: '絶対値の種類数は set(abs(x) for x in a) のサイズ。±同値をまとめる集計。', ins: ['1 -1 2 -2\n', '1 2 3\n', '0 0\n', '-5 5 5\n', '1\n', '3 -3 4 -4 3\n'] })

t({ lv: 163, concept: 'マージ: 併合結果の出所の列', title: '合流した列の出どころ', tags: ['ソート'], io: '1行目に昇順の整数列 A、2行目に昇順の整数列 B が空白区切りで与えられます。', ask: 'A と B を昇順を保ってマージするとき、取り出した要素が A のものなら 1、B のものなら 2 を、取り出した順に空白区切りで出力してください。値が同じときは A を先に取り出します。', h1: '2つの添字を先頭に置き、小さい方から取り出す。', h2: '同じ値のときに A を優先すると出力が一意に決まる。片方が尽きたら残りをそのまま並べる。', ref: 'a=list(map(int,input().split()))\nb=list(map(int,input().split()))\ni=j=0\nres=[]\nwhile i<len(a) and j<len(b):\n    if a[i]<=b[j]:\n        res.append("1")\n        i+=1\n    else:\n        res.append("2")\n        j+=1\nwhile i<len(a):\n    res.append("1")\n    i+=1\nwhile j<len(b):\n    res.append("2")\n    j+=1\nprint(" ".join(res))', tip: '「同じ値なら左の列を先に取る」という約束が、マージソートを安定にしている正体。どちらから取ったかを記録すると、その約束が出力にそのまま現れる。', ins: ['1 3 5\n2 4 6\n', '1 2 3\n4 5 6\n', '5\n1 2\n', '1 1\n1\n', '2 4\n1 3 5 7\n', '10 20 30\n15 25\n'] })

t({ lv: 164, concept: '配列: 2要素の最小積', title: '2要素の積の最小', tags: ['配列'], io: '整数列が1行で与えられます(2個以上)。', ask: '異なる2要素の積の最小値を出力してください。', h1: 'ソートする。', h2: '最大×最小、または下位2つを比べる。', ref: 'a=sorted(map(int,input().split()))\nprint(min(a[0]*a[-1],a[0]*a[1],a[-1]*a[-2]))', tip: '最小積は「最小×最大(負×正)」が候補。両端の組合せを比較する。', ins: ['1 2 3 4\n', '-5 -4 1 2\n', '1 2\n', '-1 -2\n', '0 5 3\n', '-10 1 10\n'] })

t({ lv: 165, concept: '配列: 上位2要素の和', title: '最大2要素の和', tags: ['配列'], io: '整数列が1行で与えられます(2個以上)。', ask: '最も大きい2要素の和を出力してください。', h1: 'ソートする。', h2: '末尾2つを足す。', ref: 'a=sorted(map(int,input().split()))\nprint(a[-1]+a[-2])', tip: '上位2つの和は降順ソートの先頭2つ。heapq.nlargest(2,a) の和でも O(n)。', ins: ['1 2 3 4\n', '5 5\n', '-1 -2 -3\n', '10 1 5\n', '7 7 7\n', '0 100 50\n'] })

t({ lv: 166, concept: '配列: 下位2要素の和', title: '最小2要素の和', tags: ['配列'], io: '整数列が1行で与えられます(2個以上)。', ask: '最も小さい2要素の和を出力してください。', h1: 'ソートする。', h2: '先頭2つを足す。', ref: 'a=sorted(map(int,input().split()))\nprint(a[0]+a[1])', tip: '下位2つの和は昇順ソートの先頭2つ。heapq.nsmallest(2,a) でも求まる。', ins: ['1 2 3 4\n', '5 5\n', '-1 -2 -3\n', '10 1 5\n', '7 7 7\n', '0 100 50\n'] })

t({ lv: 167, concept: '配列: 値と添字が一致する数', title: '値が添字に等しい要素数', tags: ['配列'], io: '整数列が1行で与えられます。', ask: 'a[i]==i を満たす添字 i(0始まり)の個数を出力してください。', h1: '各位置で値と添字を比べる。', h2: '一致を数える。', ref: 'a=list(map(int,input().split()))\nprint(sum(1 for i,x in enumerate(a) if x==i))', tip: '固定点(a[i]==i)の数え上げ。enumerate で添字と値を同時に取る。', ins: ['0 1 2 3\n', '1 0 2\n', '5\n', '0 0 0\n', '3 2 1 0\n', '0 5 2 1\n'] })

t({ lv: 168, concept: '配列: 1..nの順列か', title: '1からnの順列かどうか', tags: ['配列', '集合'], io: '整数列が1行で与えられます。', ask: '1からn(nは要素数)までを過不足なく1個ずつ含むなら yes、違うなら no を出力してください。', h1: '集合と {1..n} を比べる。', h2: 'サイズと内容を確認。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nprint("yes" if set(a)==set(range(1,n+1)) else "no")', tip: '順列判定は集合一致 set(a)==set(1..n)。重複や欠番があれば偽になる。', ins: ['1 2 3\n', '1 3 3\n', '1\n', '2 1\n', '1 2 4\n', '3 1 2\n'] })

t({ lv: 169, concept: 'ハッシュ: 2回以上現れる値の数', title: '複数回現れる値の種類数', tags: ['ハッシュ'], io: '整数列が1行で与えられます。', ask: '2回以上現れる値の種類数を出力してください。', h1: '出現回数を数える。', h2: '回数2以上を数える。', ref: 'from collections import Counter\na=list(map(int,input().split()))\ncnt=Counter(a)\nprint(sum(1 for v in cnt.values() if v>=2))', tip: '重複して現れる値の種類数。Counter で頻度を集計し2以上を数える。', ins: ['1 1 2 3 3\n', '1 2 3\n', '1 1 1\n', '5\n', '4 4 5 5 6\n', '7 8 9\n'] })

t({ lv: 171, concept: '文字列: 最長共通接頭辞長(2文字列)', title: '2文字列の最長共通接頭辞の長さ', tags: ['文字列'], io: '1行目に文字列 a、2行目に文字列 b が与えられます。', ask: '先頭から一致する文字数(最長共通接頭辞長)を出力してください。', h1: '先頭から1文字ずつ比較。', h2: '不一致で止める。', ref: 'a=input()\nb=input()\ni=0\nwhile i<len(a) and i<len(b) and a[i]==b[i]:\n    i+=1\nprint(i)', tip: '共通接頭辞長は先頭から一致が続く限り進める。trie やオートコンプリートの基礎。', ins: ['flower\nflow\n', 'abc\nxyz\n', 'same\nsame\n', 'a\nab\n', 'pre\npremium\n', 'x\ny\n'] })

t({ lv: 172, concept: '文字列: 最長共通接尾辞長', title: '2文字列の最長共通接尾辞の長さ', tags: ['文字列'], io: '1行目に文字列 a、2行目に文字列 b が与えられます。', ask: '末尾から一致する文字数(最長共通接尾辞長)を出力してください。', h1: '末尾から1文字ずつ比較。', h2: '不一致で止める。', ref: 'a=input()\nb=input()\ni=0\nwhile i<len(a) and i<len(b) and a[-1-i]==b[-1-i]:\n    i+=1\nprint(i)', tip: '共通接尾辞長は末尾から比較する。負の添字 a[-1-i] で後ろから走査できる。', ins: ['testing\nrunning\n', 'abc\nxyz\n', 'same\nsame\n', 'a\nba\n', 'cat\nhat\n', 'x\ny\n'] })

t({ lv: 173, concept: '文字列: 一致する位置の数', title: '同じ位置で一致する文字の数', tags: ['文字列'], io: '1行目に文字列 a、2行目に同じ長さの文字列 b が与えられます。', ask: '同じ位置で文字が一致する箇所の数を出力してください。', h1: '対応文字を比べる。', h2: '一致するものを数える。', ref: 'a=input()\nb=input()\nprint(sum(1 for x,y in zip(a,b) if x==y))', tip: '一致位置の数は zip で対応文字を比べて等しい数を数える。類似度スコアの基礎。', ins: ['abc\nabd\n', 'aaa\naaa\n', 'abc\nxyz\n', 'a\nb\n', 'hello\nhallo\n', 'cat\ncot\n'] })

t({ lv: 174, concept: '集合: 2列を合わせた種類数', title: '2列を合わせた相異なる値の数', tags: ['集合'], io: '1行目に列A、2行目に列Bが与えられます。', ask: 'A と B を合わせたときの相異なる値の種類数を出力してください。', h1: '和集合を取る。', h2: '要素数を数える。', ref: 'a=set(map(int,input().split()))\nb=set(map(int,input().split()))\nprint(len(a|b))', tip: '合算の種類数は len(a|b)。重複を除いた全体の規模を測る。', ins: ['1 2 3\n3 4 5\n', '1 2\n1 2\n', '5\n6\n', '1 1 1\n2 2 2\n', '1 2 3\n4 5 6\n', '7\n7\n'] })

t({ lv: 175, concept: '文字列: 回文を作れるか', title: '並べ替えて回文にできるか', tags: ['文字列', 'ハッシュ'], io: '文字列が1行で与えられます。', ask: '文字を並べ替えて回文を作れるなら yes、作れないなら no を出力してください。', h1: '各文字の出現回数を数える。', h2: '奇数回の文字が1個以下なら可能。', ref: 'from collections import Counter\ns=input()\ncnt=Counter(s)\nodd=sum(1 for v in cnt.values() if v%2==1)\nprint("yes" if odd<=1 else "no")', tip: '回文を作れる条件は「奇数回出現する文字が高々1個」。中央に置ける文字は1つだけ。', ins: ['aabb\n', 'abc\n', 'aab\n', 'a\n', 'racecar\n', 'abcd\n'] })

t({ lv: 176, concept: '文字列: 文字列の左回転', title: '文字列をk回左回転', tags: ['文字列'], io: '1行目に文字列、2行目に回転数 k が与えられます。', ask: '左に k 回転した文字列を出力してください。', h1: 'スライスで前後を入れ替える。', h2: 'k を長さで割った余りを使う。', ref: 's=input()\nk=int(input())\nif s:\n    k%=len(s)\n    print(s[k:]+s[:k])\nelse:\n    print(s)', tip: '左k回転は s[k:]+s[:k]。長さで余りを取れば大きな k でも正しく回る。', ins: ['abcde\n2\n', 'abc\n0\n', 'abc\n3\n', 'ab\n1\n', 'hello\n5\n', 'xyz\n4\n'] })

t({ lv: 177, concept: '文字列: 偶数長の単語数', title: '長さが偶数の単語の数', tags: ['文字列'], io: '空白区切りの文章が1行で与えられます。', ask: '長さが偶数の単語の個数を出力してください。', h1: 'split で単語に分ける。', h2: '長さの偶奇を見る。', ref: 's=input()\nprint(sum(1 for w in s.split() if len(w)%2==0))', tip: '単語長のフィルタは split 後に len(w) を判定。文章処理の基本パターン。', ins: ['hi there world\n', 'a bb ccc\n', 'even four\n', 'x\n', 'ab cd ef\n', 'one two three four\n'] })

t({ lv: 178, concept: '文字列: 頭文字の連結(略語)', title: '各単語の頭文字を集める', tags: ['文字列'], io: '空白区切りの英小文字の文章が1行で与えられます。', ask: '各単語の先頭文字を大文字にして連結した略語を出力してください。', h1: 'split で単語に分ける。', h2: '先頭文字を大文字化して連結。', ref: 's=input()\nprint("".join(w[0].upper() for w in s.split() if w))', tip: '略語(acronym)生成は各単語の先頭文字を集める。NLPの前処理でよく使う。', ins: ['hyper text markup language\n', 'as soon as possible\n', 'python\n', 'a b c\n', 'world wide web\n', 'self contained\n'] })

t({ lv: 179, concept: '文字列: 重複文字の除去', title: '重複文字を除く(初出順)', tags: ['文字列'], io: '文字列が1行で与えられます。', ask: '各文字を初めて現れた順に1回だけ残した文字列を出力してください。', h1: '既出集合を持つ。', h2: '未出の文字だけ残す。', ref: 's=input()\nseen=set()\nres=[]\nfor c in s:\n    if c not in seen:\n        seen.add(c)\n        res.append(c)\nprint("".join(res))', tip: '初出順の重複除去は集合で既出管理。dict.fromkeys(s) を使うと1行で書ける。', ins: ['aabbcc\n', 'abc\n', 'banana\n', 'a\n', 'mississippi\n', 'abcabc\n'] })

t({ lv: 180, concept: '文字列: 隣接する同一文字のペア数', title: '隣り合う同じ文字のペア数', tags: ['文字列'], io: '文字列が1行で与えられます。', ask: '隣り合う2文字が同じになる箇所の数を出力してください。', h1: '隣接文字を比べる。', h2: '一致を数える。', ref: 's=input()\nprint(sum(1 for i in range(len(s)-1) if s[i]==s[i+1]))', tip: '隣接同一ペアは zip(s, s[1:]) で比較しても数えられる。連続の検出の基本。', ins: ['aabbc\n', 'abc\n', 'aaaa\n', 'a\n', 'abba\n', 'xxyyzz\n'] })

t({ lv: 181, concept: '配列: 隣接する異なるペア数', title: '隣り合う異なる要素のペア数', tags: ['配列'], io: '整数列が1行で与えられます。', ask: '隣り合う要素が異なる箇所の数を出力してください。', h1: '隣接要素を比べる。', h2: '異なるものを数える。', ref: 'a=list(map(int,input().split()))\nprint(sum(1 for i in range(len(a)-1) if a[i]!=a[i+1]))', tip: '隣接で値が変わる回数は「連続ブロック数-1」に等しい。ランの境界の数を表す。', ins: ['1 1 2 2 3\n', '1 2 3\n', '5 5 5\n', '1\n', '1 2 2 1\n', '7 7 8 8 8\n'] })

t({ lv: 182, concept: '文字列: 連続重複の圧縮', title: '連続する重複を1つにまとめる', tags: ['文字列'], io: '文字列が1行で与えられます。', ask: '連続する同じ文字を1つにまとめた文字列を出力してください(例 aaabb→ab)。', h1: '直前と違う文字だけ残す。', h2: '走査して追加。', ref: 's=input()\nres=[]\nfor c in s:\n    if not res or res[-1]!=c:\n        res.append(c)\nprint("".join(res))', tip: '連続重複の圧縮は「直前と違う文字だけ残す」。ランレングスの文字部分に相当する。', ins: ['aaabb\n', 'abc\n', 'aaaa\n', 'a\n', 'aabbaa\n', 'xyyzz\n'] })

t({ lv: 183, concept: 'ハッシュ: 最頻の単語', title: '文中で最も多い単語', tags: ['ハッシュ', '文字列'], io: '空白区切りの文章が1行で与えられます。', ask: '最も多く現れる単語を出力してください。複数あれば辞書順で最小。', h1: '単語の出現回数を数える。', h2: '(回数降順, 辞書順)で選ぶ。', ref: 'from collections import Counter\ns=input()\ncnt=Counter(s.split())\nbest=None\nbestc=-1\nfor w in sorted(cnt):\n    if cnt[w]>bestc:\n        bestc=cnt[w]\n        best=w\nprint(best)', tip: '最頻単語の同点は辞書順で割る。文書の頻出語抽出(TF)の最小版。', ins: ['a b a\n', 'one\n', 'cat dog cat dog cat\n', 'x y z\n', 'the the a\n', 'bb aa aa bb\n'] })

t({ lv: 184, concept: 'ハッシュ: 相異なる単語数', title: '文中の相異なる単語数', tags: ['ハッシュ', '文字列'], io: '空白区切りの文章が1行で与えられます。', ask: '相異なる単語の種類数を出力してください。', h1: '集合に入れる。', h2: '要素数を取る。', ref: 's=input()\nprint(len(set(s.split())))', tip: '語彙数(distinct words)は set(split()) のサイズ。テキストの多様性の指標。', ins: ['a b a c\n', 'one\n', 'cat dog cat\n', 'x y z\n', 'the the the\n', 'a b c d\n'] })

t({ lv: 185, concept: '統計: 平均単語長(小数2桁)', title: '単語の平均文字数(小数2桁)', tags: ['統計', '文字列'], io: '空白区切りの文章が1行で与えられます。', ask: '単語の平均文字数を小数第2位まで出力してください。', h1: '各単語の長さを合計。', h2: '単語数で割り整形。', ref: 's=input()\nws=s.split()\navg=sum(len(w) for w in ws)/len(ws)\nprint(f"{avg:.2f}")', tip: '平均単語長は総文字数÷単語数。読みやすさ指標などで使う。f"{:.2f}" で桁固定。', ins: ['a bb ccc\n', 'hello\n', 'one two\n', 'i am ok\n', 'x y z\n', 'cat dogs\n'] })

t({ lv: 186, concept: '文字列: 辞書順最大の単語', title: '辞書順で最後の単語', tags: ['文字列'], io: '空白区切りの文章が1行で与えられます。', ask: '辞書順で最も後ろにくる単語を出力してください。', h1: 'split で分ける。', h2: 'max を取る(辞書順)。', ref: 's=input()\nprint(max(s.split()))', tip: '辞書順最大は max(words)。文字列の比較は先頭文字から辞書順で行われる。', ins: ['banana apple cherry\n', 'one\n', 'a b c\n', 'zoo ant\n', 'cat car can\n', 'x y z\n'] })

t({ lv: 187, concept: '文字列: 最短の単語', title: '最も短い単語', tags: ['文字列'], io: '空白区切りの文章が1行で与えられます。', ask: '最も短い単語を出力してください。複数あれば最初のもの。', h1: 'split で分ける。', h2: 'min に key=len。', ref: 's=input()\nprint(min(s.split(),key=len))', tip: '最短単語は min(..., key=len)。最長版と対称で、同点は最初のものになる。', ins: ['the quick a\n', 'aa bb ccc\n', 'hello\n', 'one six i\n', 'x yy zzz\n', 'cat a dog\n'] })

t({ lv: 188, concept: '文字列: 大文字始まりの単語数', title: '大文字で始まる単語の数', tags: ['文字列'], io: '空白区切りの文章が1行で与えられます。', ask: '先頭が大文字の単語の個数を出力してください。', h1: '各単語の先頭を見る。', h2: 'isupper で判定。', ref: 's=input()\nprint(sum(1 for w in s.split() if w and w[0].isupper()))', tip: '固有名詞抽出などで使う。w[0].isupper() で先頭の大文字を判定する。', ins: ['Hello World\n', 'hello world\n', 'A b C\n', 'X\n', 'one Two three\n', 'AB cd\n'] })

t({ lv: 189, concept: '文字列: 記号の個数', title: '英数字でない文字の個数', tags: ['文字列'], io: '文字列が1行で与えられます。', ask: '英数字でない文字(記号や空白)の個数を出力してください。', h1: 'isalnum で英数字を判定。', h2: '英数字でないものを数える。', ref: 's=input()\nprint(sum(1 for c in s if not c.isalnum()))', tip: '記号や空白の数は not c.isalnum() で数える。テキストのクレンジング前処理に使う。', ins: ['a1!b2?\n', 'abc\n', 'a b c\n', '123\n', '!!!\n', 'x_y\n'] })

t({ lv: 190, concept: '文字列: 回文の単語数', title: '回文になっている単語の数', tags: ['文字列'], io: '空白区切りの文章が1行で与えられます。', ask: '回文(前後対称)になっている単語の個数を出力してください。', h1: '各単語を反転と比べる。', h2: '一致するものを数える。', ref: 's=input()\nprint(sum(1 for w in s.split() if w==w[::-1]))', tip: '回文単語の数は各単語で w==w[::-1] を判定。単語単位のフィルタの応用。', ins: ['level abc noon\n', 'hello\n', 'a bb cc\n', 'racecar\n', 'one two\n', 'mom dad sis\n'] })

t({ lv: 191, concept: '文字列: タイトルケースの判定', title: '各単語が大文字始まりか', tags: ['文字列'], io: '空白区切りの文章が1行で与えられます。', ask: 'すべての単語が大文字で始まっていれば yes、そうでなければ no を出力してください。', h1: '各単語の先頭を確認。', h2: 'すべて大文字始まりか。', ref: 's=input()\nprint("yes" if all(w[0].isupper() for w in s.split() if w) else "no")', tip: 'タイトルケース判定は all() と先頭大文字チェック。見出しの整形検証などに使う。', ins: ['Hello World\n', 'Hello world\n', 'A B C\n', 'x\n', 'One Two\n', 'one Two\n'] })

t({ lv: 192, concept: '文字列: 母音を含む単語数', title: '母音を含む単語の数', tags: ['文字列'], io: '空白区切りの英小文字の文章が1行で与えられます。', ask: '母音(a,e,i,o,u)を1つ以上含む単語の個数を出力してください。', h1: '各単語に母音があるか見る。', h2: '集合との交差で判定。', ref: 's=input()\nvowels=set("aeiou")\nprint(sum(1 for w in s.split() if any(c in vowels for c in w)))', tip: '単語が母音を含むかは any(c in vowels for c in w)。発音可能語の判定などに使う。', ins: ['cat dog xyz\n', 'a b c\n', 'sky try\n', 'hello\n', 'rhythm\n', 'one two brr\n'] })

export const CATALOG = TASKS
