// 生成タスク 第66波：各レベル2問化フェーズ(21)。lv816〜840 に2問目を追加。
// データ構造応用/シミュレーション帯。重複なし・決定的・採点一意。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 816, concept: 'ヒープ: 最も使われた会議室', title: '一番人気の会議室はどれ', tags: ['ヒープ', 'シミュレーション'], io: '1行目に 部屋数 k と会議数 n、続く n 行に会議の希望時間 s e (開始・終了、開始順に相異なる)が与えられます。', ask: '会議は開始時刻順に、空いている最小番号の部屋へ入ります。空きが無ければ最も早く空く部屋(同時なら番号最小)を待ち、所要時間を保ったまま遅れて開催します。開催数が最多の部屋の番号(同数なら最小)を出力してください。', h1: '「空き部屋の集合」と「使用中(終了時刻,部屋)」の2つのヒープで回す。', h2: '会議の開始時刻までに終わった部屋を空き側へ戻してから割り当てる。', ref: 'import heapq\nk,n=map(int,input().split())\nmeet=sorted([tuple(map(int,input().split())) for _ in range(n)])\nfree=list(range(k))\nheapq.heapify(free)\nbusy=[]\ncnt=[0]*k\nfor s,e in meet:\n    while busy and busy[0][0]<=s:\n        t_,room=heapq.heappop(busy)\n        heapq.heappush(free,room)\n    if free:\n        room=heapq.heappop(free)\n        heapq.heappush(busy,(e,room))\n    else:\n        t_,room=heapq.heappop(busy)\n        heapq.heappush(busy,(t_+(e-s),room))\n    cnt[room]+=1\nbest=max(range(k),key=lambda i:(cnt[i],-i))\nprint(best)', tip: '2つのヒープの間で資源を往復させる離散イベントシミュレーションの型。タプルの並び(終了時刻, 部屋番号)がタイブレークまで面倒を見てくれる。', ins: ['2 3\n0 10\n1 5\n2 7\n', '1 2\n0 10\n1 2\n', '2 2\n0 5\n5 10\n', '3 4\n0 2\n1 3\n2 4\n3 5\n', '1 1\n0 1\n', '2 4\n0 10\n1 2\n3 4\n5 6\n'] })

t({ lv: 817, concept: 'Union-Find: 3すくみの矛盾検出', title: '食物連鎖の嘘つき発言', tags: ['Union-Find'], io: '1行目に 動物の数 n と発言数 q、続く q 行に「1 x y」(xとyは同じ種類)または「2 x y」(xはyを食べる)が与えられます。', ask: 'それまでの正しい発言と矛盾する発言を「嘘」として無視しながら処理し、嘘の発言数を出力してください(3すくみ: AはBを食べ、BはCを食べ、CはAを食べる)。', h1: '「差 mod 3」を重みに持つUnion-Find。', h2: '同種は差0、食べる関係は差1として結合。既に同じ組なら差の整合を確かめる。', ref: 'import sys\nsys.setrecursionlimit(400000)\nn,q=map(int,input().split())\npar=list(range(n+1))\nrel=[0]*(n+1)\ndef find(x):\n    if par[x]==x:\n        return x\n    r=find(par[x])\n    rel[x]=(rel[x]+rel[par[x]])%3\n    par[x]=r\n    return r\nlies=0\nfor _ in range(q):\n    t,x,y=map(int,input().split())\n    d=0 if t==1 else 1\n    rx,ry=find(x),find(y)\n    if rx==ry:\n        if (rel[x]-rel[y])%3!=d:\n            lies+=1\n    else:\n        par[rx]=ry\n        rel[rx]=(d+rel[y]-rel[x])%3\nprint(lies)', tip: 'パリティUnion-Findの mod 3 版。「関係の差」を根への相対値として持つと、任意の巡回関係(mod k)の整合判定が同じ形で書ける。', ins: ['3 3\n1 1 2\n2 2 3\n2 3 1\n', '3 3\n1 1 2\n2 1 2\n1 1 2\n', '2 2\n2 1 2\n2 2 1\n', '5 4\n2 1 2\n2 2 3\n2 3 4\n2 4 1\n', '4 2\n1 1 2\n1 3 4\n', '3 4\n2 1 2\n2 2 3\n1 1 3\n2 3 1\n'] })

t({ lv: 818, concept: 'Union-Find: 合併後のグループ人数', title: '合流するたびの人数', tags: ['Union-Find'], io: '1行目に 人数 n と回数 q、続く q 行に「a b」(aのグループとbのグループが合流)が与えられます。', ask: '各回について、合流後の(aが属する)グループの人数を出力してください(既に同じグループならその人数)。', h1: '根にグループサイズを持たせる。', h2: '結合のとき小さい方を大きい方へ繋ぎ、サイズを足す。', ref: 'n,q=map(int,input().split())\npar=list(range(n+1))\nsize=[1]*(n+1)\ndef find(x):\n    while par[x]!=x:\n        par[x]=par[par[x]]\n        x=par[x]\n    return x\nfor _ in range(q):\n    a,b=map(int,input().split())\n    ra,rb=find(a),find(b)\n    if ra!=rb:\n        if size[ra]<size[rb]:\n            ra,rb=rb,ra\n        par[rb]=ra\n        size[ra]+=size[rb]\n    print(size[find(a)])', tip: 'サイズを根に集約する union by size は、実は経路圧縮と並ぶ計算量保証の片翼でもある。集約値は人数のほか合計・最大など何でも載る。', ins: ['4 3\n1 2\n3 4\n1 3\n', '2 2\n1 2\n1 2\n', '5 2\n1 2\n2 3\n', '3 1\n2 3\n', '6 4\n1 2\n3 4\n5 6\n2 5\n', '2 1\n1 1\n'] })

t({ lv: 819, concept: '区間: ちょうど1回だけ覆われた長さ', title: '一重にだけ覆われた部分の長さ', tags: ['区間'], io: '1行目に区間の数 n、続く n 行に区間 l r が与えられます。', ask: '数直線上でちょうど1つの区間だけに覆われている部分の長さの合計を出力してください。', h1: '端点でイベントを起こす(いもす法)。', h2: '座標順に走査し「重なり枚数が1」の区間の長さだけ足す。', ref: 'n=int(input())\nev=[]\nfor _ in range(n):\n    l,r=map(int,input().split())\n    ev.append((l,1))\n    ev.append((r,-1))\nev.sort()\ndepth=0\nprev=None\ntotal=0\nfor x,d in ev:\n    if prev is not None and depth==1:\n        total+=x-prev\n    depth+=d\n    prev=x\nprint(total)', tip: '「深さがちょうどkの長さ」はイベント走査の深さカウンタを見るだけで拾える。被覆総長(深さ≥1)と同じ走査で条件だけ差し替わる。', ins: ['2\n1 4\n2 6\n', '1\n0 5\n', '3\n0 3\n1 2\n5 7\n', '2\n1 3\n1 3\n', '3\n0 10\n2 4\n6 8\n', '2\n0 1\n1 2\n'] })

t({ lv: 820, concept: 'シミュレーション: 区間反転の繰り返し', title: '区間をひっくり返し続けた結果', tags: ['シミュレーション'], io: '1行目に n q、2行目に整数列、続く q 行に区間 l r (その並びを逆順にする)が与えられます。', ask: '全ての操作を行った後の配列を空白区切りで出力してください。', h1: 'スライスの反転代入で書ける。', h2: 'a[l-1:r]=a[l-1:r][::-1] を繰り返すだけ。大量クエリなら平衡二分木の世界。', ref: 'n,q=map(int,input().split())\na=list(map(int,input().split()))\nfor _ in range(q):\n    l,r=map(int,input().split())\n    a[l-1:r]=a[l-1:r][::-1]\nprint(*a)', tip: 'スライス代入は左辺も右辺も部分列を扱えるPythonらしい書き味。反転を高速に繰り返すには反転フラグ付きの平衡木(Treap)が必要になる。', ins: ['5 1\n1 2 3 4 5\n2 4\n', '3 2\n1 2 3\n1 3\n1 3\n', '4 2\n1 2 3 4\n1 2\n3 4\n', '2 1\n5 7\n1 2\n', '6 3\n1 2 3 4 5 6\n1 6\n2 5\n3 4\n', '1 1\n9\n1 1\n'] })

t({ lv: 821, concept: 'ソート: 安定ソートされているかの検証', title: 'その並べ替えは安定か', tags: ['ソート'], io: '1行目に n、2行目に元の列のキー、3行目に並べ替え結果(元の位置番号 1..n の並び)が与えられます。', ask: 'その並べ替えがキーの安定ソート(キーが昇順、同キーは元の順序を保存)になっているなら yes、そうでなければ no を出力してください。', h1: 'キーが非減少かをまず確認。', h2: '同じキーが続く区間では、元の位置番号が増えているかも確認。', ref: 'n=int(input())\nkey=list(map(int,input().split()))\nperm=list(map(int,input().split()))\nok=True\nfor i in range(n-1):\n    a,b=perm[i]-1,perm[i+1]-1\n    if key[a]>key[b]:\n        ok=False\n    elif key[a]==key[b] and perm[i]>perm[i+1]:\n        ok=False\nprint("yes" if ok else "no")', tip: '安定性は「同キー内で元の添字が昇順」と1行で言い換えられる。Pythonのsortedは常に安定、という言語仕様の検証器でもある。', ins: ['3\n2 1 2\n2 1 3\n', '3\n2 1 2\n2 3 1\n', '2\n1 1\n2 1\n', '4\n1 2 2 3\n1 2 3 4\n', '1\n5\n1\n', '4\n2 2 1 1\n3 4 1 2\n'] })

t({ lv: 822, concept: '木: 部分木の葉の数一覧', title: '各部門の末端メンバー数', tags: ['木', '再帰'], io: '1行目に頂点数 n (根は1、n≥2)、2行目に頂点2..nの親が与えられます。', ask: '各頂点について、その部分木に含まれる葉(子のない頂点)の数を頂点1から順に空白区切りで出力してください。', h1: '葉自身の値は1。', h2: '内部頂点は子の値の合計。帰りがけ順に集計する。', ref: 'import sys\nsys.setrecursionlimit(100000)\nn=int(input())\npar=[0,0]+list(map(int,input().split()))\nch=[[] for _ in range(n+1)]\nfor v in range(2,n+1):\n    ch[par[v]].append(v)\nleaf=[0]*(n+1)\ndef dfs(v):\n    if not ch[v]:\n        leaf[v]=1\n        return 1\n    s=0\n    for c in ch[v]:\n        s+=dfs(c)\n    leaf[v]=s\n    return s\ndfs(1)\nprint(*leaf[1:])', tip: '組織図の「実働人数」集計そのもの。集計値をサイズ・葉数・深さ最大と替えても、帰りがけ集計の骨格は1文字も変わらない。', ins: ['5\n1 1 2 2\n', '3\n1 2\n', '4\n1 1 1\n', '7\n1 1 2 2 3 3\n', '2\n1\n', '6\n1 2 2 1 5\n'] })

t({ lv: 823, concept: 'シミュレーション: LRUキャッシュのヒット数', title: 'キャッシュに何回当たるか', tags: ['シミュレーション'], io: '1行目に容量 c、2行目にアクセスするページ番号の列が与えられます。', ask: 'LRU(最も長く使われていないものを追い出す)方式のキャッシュで全アクセスを処理したときのヒット数を出力してください。', h1: 'キャッシュ内の「最近使った順」を管理する。', h2: 'ヒットしたらそのページを最新に移動、ミスしたら(満杯なら)最古を捨てて追加。リストやOrderedDictで書ける。', ref: 'c=int(input())\npages=list(map(int,input().split()))\ncache=[]\nhits=0\nfor p in pages:\n    if p in cache:\n        hits+=1\n        cache.remove(p)\n        cache.append(p)\n    else:\n        if len(cache)==c:\n            cache.pop(0)\n        cache.append(p)\nprint(hits)', tip: 'OSのページ置換・CDN・DBバッファの共通語彙。リスト実装O(n)→OrderedDict/連結リスト+辞書でO(1)へ、の改善ルートも定番の面接題。', ins: ['2\n1 2 1 3 1\n', '1\n1 1 2 2\n', '3\n1 2 3 1 2 3\n', '2\n1 2 3 1\n', '4\n5 5 5\n', '2\n1 1 1 1\n'] })

t({ lv: 824, concept: 'データ構造: スナップショット付き配列', title: '過去の時点の値を読む', tags: ['データ構造'], io: '1行目に 長さ n とクエリ数 q、続く q 行に「set i v」「snap」(その時点を保存し、保存番号 0,1,… を出力)「get i s」(保存番号 s の時点の i 番目を出力)が与えられます。', ask: 'snap と get の出力を順に行ってください(配列の初期値は全て0)。', h1: '全体をコピーすると重い。', h2: '各位置に (保存番号, 値) の履歴を持ち、getはbisectで「s以下の最新」を探すとコピー不要になる。', ref: 'n,q=map(int,input().split())\na=[0]*n\nsnaps=[]\nfor _ in range(q):\n    parts=input().split()\n    if parts[0]=="set":\n        a[int(parts[1])-1]=int(parts[2])\n    elif parts[0]=="snap":\n        snaps.append(a[:])\n        print(len(snaps)-1)\n    else:\n        i,s=int(parts[1]),int(parts[2])\n        print(snaps[s][i-1])', tip: '「履歴を持つ配列」は永続データ構造の入り口。全コピーO(n)/回から、位置ごとの差分履歴O(1)/setへの改善が本質的な一歩になる。', ins: ['2 5\nset 1 5\nsnap\nset 1 7\nsnap\nget 1 0\n', '1 3\nsnap\nset 1 9\nget 1 0\n', '3 6\nset 2 4\nsnap\nset 2 8\nget 2 0\nsnap\nget 2 1\n', '2 4\nsnap\nsnap\nget 1 0\nget 2 1\n', '1 4\nset 1 1\nsnap\nset 1 2\nget 1 0\n', '2 3\nset 2 3\nsnap\nget 2 0\n'] })

t({ lv: 825, concept: 'ヒープ: 期限つき在庫の廃棄数', title: '賞味期限切れを最小にする', tags: ['ヒープ', '貪欲'], io: '在庫それぞれの賞味期限(日)の列が1行で空白区切りで与えられます。1日1個だけ消費でき、1日目から始めます。', ask: '「期限の早いものから食べる」最適戦略で消費したとき、期限切れで廃棄する個数を出力してください(期限当日は消費可)。', h1: '期限順に食べるのが最適。', h2: 'ソートして日を進め、期限≥今日なら消費、そうでなければ廃棄。', ref: 'a=sorted(map(int,input().split()))\nday=1\nwaste=0\nfor e in a:\n    if e>=day:\n        day+=1\n    else:\n        waste+=1\nprint(waste)', tip: 'EDF(Earliest Deadline First)の正しさは交換論法の教科書例。締切系の貪欲は「早い締切を先に」でほぼ勝てるが、価値が絡むとヒープの後悔法に進化する。', ins: ['1 2 3\n', '1 1 1\n', '3 3 3\n', '2\n', '1 1 2 4\n', '5 1 1\n'] })

t({ lv: 826, concept: 'シミュレーション: ラウンドロビンの完了順', title: 'タイムスライスで回す完了順', tags: ['シミュレーション', 'デック'], io: '1行目にタイムスライス q、2行目に各ジョブの処理時間が与えられます(ジョブ番号は1から)。', ask: '先頭のジョブから q ずつ実行し、終わらなければ列の最後尾へ回すラウンドロビンで、完了したジョブ番号を順に空白区切りで出力してください。', h1: 'dequeに(番号, 残り時間)を入れて回す。', h2: '残り≤qなら完了、そうでなければ残りを減らして後ろへ。', ref: 'q=int(input())\na=list(map(int,input().split()))\nfrom collections import deque\ndq=deque((i+1,t) for i,t in enumerate(a))\nout=[]\nwhile dq:\n    i,t=dq.popleft()\n    if t<=q:\n        out.append(i)\n    else:\n        dq.append((i,t-q))\nprint(*out)', tip: 'OSのプロセススケジューラの基本形。タイムスライスを大きくするとFCFS、小さくすると公平だが切替オーバーヘッド増、というトレードオフの実験台になる。', ins: ['2\n5 3 2\n', '1\n1 1 1\n', '10\n3 6 1\n', '3\n7\n', '2\n4 4\n', '1\n2 3\n'] })

t({ lv: 827, concept: 'デック: 直近k個の移動合計', title: '直近k件の売上合計を逐次表示', tags: ['デック'], io: '1行目に k、2行目に届く数値の列が与えられます。', ask: '数値が届くたびに「直近高々k件の合計」を空白区切りで出力してください。', h1: '合計は差分で保守する。', h2: 'dequeに入れて、あふれたら左端を引く。', ref: 'from collections import deque\nk=int(input())\na=list(map(int,input().split()))\ndq=deque()\ns=0\nout=[]\nfor x in a:\n    dq.append(x)\n    s+=x\n    if len(dq)>k:\n        s-=dq.popleft()\n    out.append(s)\nprint(*out)', tip: 'ストリームの移動集計はdeque+差分が最小構成。moving averageのSNSダッシュボードも中身はこの数行と同じ。', ins: ['3\n1 2 3 4 5\n', '1\n5 6 7\n', '2\n10 20 30\n', '5\n1 1\n', '2\n0 0 0\n', '3\n7\n'] })

t({ lv: 828, concept: 'ソート: 頻度で並べ替える', title: '出現回数の少ない順に並べ替え', tags: ['ソート', 'ハッシュ'], io: '整数列が1行で空白区切りで与えられます。', ask: '出現回数の昇順、同数なら値の降順、で全要素を並べ替えて空白区切りで出力してください。', h1: '各値の頻度を先に数える。', h2: 'キーを (頻度, −値) にしたソート1発。', ref: 'from collections import Counter\na=list(map(int,input().split()))\nc=Counter(a)\na.sort(key=lambda x:(c[x],-x))\nprint(*a)', tip: '「集計結果をソートキーに使う」2段構え。keyに(第1基準, 第2基準)のタプルを渡すPythonの流儀は、SQLの ORDER BY 複数列と同じ感覚で読める。', ins: ['1 1 2 2 2 3\n', '2 3 1 3 2\n', '5\n', '4 4 4 4\n', '1 2 3\n', '9 9 1 1 2\n'] })

t({ lv: 829, concept: '単調スタック: 各長さの窓の最小値の最大', title: 'どの窓幅でも最強の最小値', tags: ['スタック'], io: '正整数列が1行で空白区切りで与えられます。', ask: '各窓幅 k=1..n について「長さkの全ての窓の最小値のうち最大」を、k=1から順に空白区切りで出力してください。', h1: '各要素が「最小」でいられる最大の幅を求める。', h2: '左右の「より小さい要素」までの距離(単調スタック)で幅が分かる。幅wでの候補を配り、後ろから最大を伝播する。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nleft=[-1]*n\nst=[]\nfor i in range(n):\n    while st and a[st[-1]]>=a[i]:\n        st.pop()\n    left[i]=st[-1] if st else -1\n    st.append(i)\nright=[n]*n\nst=[]\nfor i in range(n-1,-1,-1):\n    while st and a[st[-1]]>=a[i]:\n        st.pop()\n    right[i]=st[-1] if st else n\n    st.append(i)\nans=[0]*(n+1)\nfor i in range(n):\n    w=right[i]-left[i]-1\n    if a[i]>ans[w]:\n        ans[w]=a[i]\nfor k in range(n-1,0,-1):\n    if ans[k]<ans[k+1]:\n        ans[k]=ans[k+1]\nprint(*ans[1:])', tip: '「自分が最小の支配区間」を全要素に配ってから、答えの単調性(幅が狭いほど答えは大きい)で穴を埋める2段構成。単調スタックの集大成的な一問。', ins: ['1 2 3\n', '3 1 2\n', '5\n', '2 2 2\n', '1 3 1\n', '4 3 2 1\n'] })

t({ lv: 830, concept: 'スタック: ブラウザ履歴の戻ると進む', title: '戻る・進むボタンの実装', tags: ['スタック', 'シミュレーション'], io: '1行目にクエリ数 q、続く q 行に「visit X」(ページXへ移動)「back」「forward」「where」(現在地を出力)が与えられます。最初は home にいます。', ask: '各 where に対して現在のページ名を出力してください(戻れない/進めないときは無視。visitすると「進む」履歴は消えます)。', h1: '戻る用と進む用の2本のスタック。', h2: 'visitで進む側を空に。backは現在を進む側へ積んで戻る側から取り出す。', ref: 'q=int(input())\nback=[]\nfwd=[]\ncur="home"\nfor _ in range(q):\n    parts=input().split()\n    if parts[0]=="visit":\n        back.append(cur)\n        cur=parts[1]\n        fwd=[]\n    elif parts[0]=="back":\n        if back:\n            fwd.append(cur)\n            cur=back.pop()\n    elif parts[0]=="forward":\n        if fwd:\n            back.append(cur)\n            cur=fwd.pop()\n    else:\n        print(cur)', tip: 'アンドゥ・リドゥと同型の2スタック構造。「新しい操作でリドゥ履歴が消える」仕様まで含めて、エディタもブラウザも同じ骨格で動いている。', ins: ['6\nvisit a\nvisit b\nback\nwhere\nforward\nwhere\n', '3\nback\nwhere\nvisit x\n', '5\nvisit a\nback\nvisit b\nforward\nwhere\n', '2\nwhere\nwhere\n', '7\nvisit a\nvisit b\nback\nvisit c\nback\nwhere\nwhere\n', '4\nvisit p\nvisit q\nback\nwhere\n'] })

t({ lv: 831, concept: 'データ構造: 区間の最大接頭辞和', title: '区間の頭から読んだ最高の伸び', tags: ['データ構造'], io: '1行目に n q、2行目に整数列、続く q 行に区間 l r が与えられます。', ask: '各区間について「区間の先頭から途中まで(1個以上)を足したときの最大値(最大接頭辞和)」を出力してください。', h1: '区間内で累積しながら最大を追う。', h2: 'セグ木に載せるなら(区間和, 最大接頭辞和)のペアがマージ可能: 左のprefか、左の和+右のpref。', ref: 'n,q=map(int,input().split())\na=list(map(int,input().split()))\nfor _ in range(q):\n    l,r=map(int,input().split())\n    s=0\n    best=None\n    for x in a[l-1:r]:\n        s+=x\n        if best is None or s>best:\n            best=s\n    print(best)', tip: '(和, 最大接頭辞和)のペアは最大部分配列和セグ木(4値ノード)の部品。マージ則を1つずつ体で覚えると4値ノードが暗記でなく導出になる。', ins: ['5 2\n1 -2 3 -1 2\n1 5\n3 5\n', '3 1\n-1 -2 -3\n1 3\n', '4 2\n2 2 2 2\n2 3\n1 4\n', '1 1\n-5\n1 1\n', '6 1\n3 -4 5 -1 2 -6\n2 6\n', '2 2\n1 1\n1 2\n2 2\n'] })

t({ lv: 832, concept: 'データ構造: 取り消しできる合計', title: 'アンドゥつきの加算器', tags: ['データ構造', 'スタック'], io: '1行目にクエリ数 q、続く q 行に「add x」「undo」(直前のaddを取り消す)「sum」(合計を出力)が与えられます(undoは取り消せるaddがあるときだけ来ます)。', ask: '各 sum に対して現在の合計を出力してください。', h1: '取り消しは履歴が要る。', h2: 'addした値をスタックに積み、undoでpopして合計から引く。', ref: 'q=int(input())\nst=[]\ns=0\nfor _ in range(q):\n    parts=input().split()\n    if parts[0]=="add":\n        x=int(parts[1])\n        st.append(x)\n        s+=x\n    elif parts[0]=="undo":\n        s-=st.pop()\n    else:\n        print(s)', tip: '「操作の逆元を積む」のがundo設計の基本。逆元が無い操作(max更新など)は状態スナップショットを積む方式に切り替える、と整理できる。', ins: ['5\nadd 3\nadd 4\nsum\nundo\nsum\n', '3\nadd 5\nundo\nsum\n', '4\nadd 1\nadd 2\nundo\nsum\n', '2\nadd 7\nsum\n', '6\nadd 1\nsum\nadd 2\nsum\nundo\nsum\n', '3\nadd -5\nadd 5\nsum\n'] })

t({ lv: 833, concept: '数え上げ: m以上が過半数の区間数', title: '高評価が過半数の期間を数える', tags: ['数え上げ', '累積和'], io: '1行目に基準 m、2行目に整数列が与えられます。', ask: 'm 以上の要素の個数が m 未満の要素の個数より多い連続部分配列の個数を出力してください。', h1: 'm以上を+1、m未満を−1に変換する。', h2: '「和が正の区間数」に化ける。接頭辞和を並べ、pre[r]>pre[l-1] のペア数を数える(小さい入力なら2重ループ)。', ref: 'm=int(input())\na=list(map(int,input().split()))\nb=[1 if x>=m else -1 for x in a]\npre=[0]\nfor x in b:\n    pre.append(pre[-1]+x)\nn=len(a)\ncnt=0\nfor i in range(n+1):\n    for j in range(i+1,n+1):\n        if pre[j]>pre[i]:\n            cnt+=1\nprint(cnt)', tip: '「中央値がm以上の区間」の数え上げはこの±1変換で転倒数(BIT)の問題に化ける、有名な変換。閾値の条件を符号に潰すのが第一歩。', ins: ['2\n1 2 3\n', '5\n1 1 1\n', '1\n1 1 1\n', '3\n3 1 3\n', '2\n2\n', '4\n5 3 5 3\n'] })

t({ lv: 834, concept: '区間: 全長方形の共通部分の面積', title: '全部の紙が重なっている面積', tags: ['区間'], io: '1行目に枚数 n、続く n 行に長方形 x1 y1 x2 y2 (左下と右上)が与えられます。', ask: '全ての長方形に共通して含まれる領域の面積を出力してください(無ければ0)。', h1: '共通部分も長方形になる。', h2: 'x1の最大、y1の最大、x2の最小、y2の最小で決まる。', ref: 'n=int(input())\nrects=[tuple(map(int,input().split())) for _ in range(n)]\nx1=max(r[0] for r in rects)\ny1=max(r[1] for r in rects)\nx2=min(r[2] for r in rects)\ny2=min(r[3] for r in rects)\nprint(max(0,x2-x1)*max(0,y2-y1))', tip: '共通部分は各軸独立に「区間の交わり」を取ればよい(直積の性質)。max(0,·)で「交わらない」を無言で処理するのが実装の詰め。', ins: ['2\n0 0 4 4\n2 2 6 6\n', '1\n1 1 3 5\n', '2\n0 0 1 1\n2 2 3 3\n', '3\n0 0 10 10\n2 2 8 8\n4 4 6 6\n', '2\n0 0 5 5\n0 0 5 5\n', '3\n0 0 3 3\n1 0 4 3\n2 0 5 3\n'] })

t({ lv: 835, concept: '数え上げ: 右側の最小より大きい要素数', title: '後からもっと安くなる商品の数', tags: ['数え上げ'], io: '整数列が1行で空白区切りで与えられます。', ask: '自分より右側に自分より小さい値が存在する要素の個数を出力してください。', h1: '右からの最小値を持ち歩く。', h2: '右端から走査し、これまでの最小より大きければカウント。', ref: 'a=list(map(int,input().split()))\nINF=float("inf")\nmn=INF\ncnt=0\nfor x in reversed(a):\n    if x>mn:\n        cnt+=1\n    if x<mn:\n        mn=x\nprint(cnt)', tip: '「右に~が存在するか」は接尾辞の集約値(最小)1個で判定できる。存在の個数まで要る場合はBITへ、と要求に応じて重くする。', ins: ['5 3 4 1 2\n', '1 2 3\n', '3 2 1\n', '7\n', '2 2 2\n', '4 1 4 1\n'] })

t({ lv: 836, concept: 'ヒープ: k本ずつ束ねる最小コスト', title: 'k本まとめ結びの最小コスト', tags: ['ヒープ', '貪欲'], io: '1行目に一度に束ねる本数 k、2行目にロープの長さの列が与えられます。1回の操作でちょうど k 本を1本に束ね、コストは束ねた長さの合計です。', ask: '1本になるまで束ねる最小総コストを出力してください(そのままでは丁度1本にならない場合、長さ0のロープを最少本数だけ足してよい)。', h1: '2本ずつならハフマン法。', h2: 'k本版は (本数−1) が (k−1) で割り切れるようダミー(長さ0)を足し、毎回最小k本を束ねる。', ref: 'import heapq\nk=int(input())\na=list(map(int,input().split()))\nwhile len(a)>1 and (len(a)-1)%(k-1)!=0:\n    a.append(0)\nheapq.heapify(a)\ntotal=0\nwhile len(a)>1:\n    s=0\n    for _ in range(k):\n        s+=heapq.heappop(a)\n    total+=s\n    heapq.heappush(a,s)\nprint(total)', tip: 'k分ハフマン木の要点は「最初の1回だけ本数を調整する」ダミー挿入。これを忘れると大きい要素が深い位置に押し込まれて損をする。', ins: ['2\n1 2 3\n', '3\n1 2 3 4\n', '2\n5\n', '3\n1 1 1\n', '2\n4 4 4 4\n', '3\n2 2 2 2 2\n'] })

t({ lv: 837, concept: '統計: 四分位範囲', title: 'データの四分位範囲IQR', tags: ['統計'], io: '整数列(4個以上)が1行で空白区切りで与えられます。', ask: 'ソート後、下半分(全体の中央値を除く、偶数長ならそのまま半分)の中央値を Q1、上半分の中央値を Q3 とするとき、IQR(Q3−Q1)を小数1桁で出力してください。', h1: 'まず全体を下半分と上半分に切る。', h2: '奇数長は中央の1個を両方から除く。各半分の中央値は「偶数長なら中央2つの平均」。', ref: 'a=sorted(map(int,input().split()))\nn=len(a)\ndef med(x):\n    m=len(x)\n    if m%2==1:\n        return float(x[m//2])\n    return (x[m//2-1]+x[m//2])/2\nhalf=n//2\nq1=med(a[:half])\nq3=med(a[n-half:])\nprint(f"{q3-q1:.1f}")', tip: '箱ひげ図の箱の高さがIQR。外れ値の標準的な定義「Q1−1.5IQRより下、Q3+1.5IQRより上」もこの2値から出る、頑健統計の入り口。', ins: ['1 2 3 4\n', '1 2 3 4 5\n', '7 7 7 7\n', '1 1 10 10\n', '3 1 4 1 5 9 2 6\n', '2 4 6 8 10 12\n'] })

t({ lv: 838, concept: 'シミュレーション: 2配列の区間スワップ', title: '2本の列の区間まるごと交換', tags: ['シミュレーション'], io: '1行目に n q、2行目に配列A、3行目に配列B、続く q 行に区間 l r (AとBのその区間を丸ごと交換)が与えられます。', ask: '全操作後のAを1行目、Bを2行目に空白区切りで出力してください。', h1: 'スライスの同時代入で書ける。', h2: 'a[l:r],b[l:r]=b[l:r],a[l:r] の形が使える。', ref: 'n,q=map(int,input().split())\na=list(map(int,input().split()))\nb=list(map(int,input().split()))\nfor _ in range(q):\n    l,r=map(int,input().split())\n    a[l-1:r],b[l-1:r]=b[l-1:r],a[l-1:r]\nprint(*a)\nprint(*b)', tip: '同時代入は右辺を全部評価してから左辺へ入るので、スライス交換も一時変数なしで安全。参照でなく部分コピーが動いている点も意識したい。', ins: ['3 1\n1 2 3\n4 5 6\n1 2\n', '2 2\n1 1\n2 2\n1 1\n2 2\n', '4 1\n1 2 3 4\n5 6 7 8\n2 3\n', '1 1\n9\n0\n1 1\n', '5 2\n1 1 1 1 1\n2 2 2 2 2\n1 5\n3 3\n', '3 1\n7 8 9\n1 2 3\n3 3\n'] })

t({ lv: 839, concept: 'Union-Find: 繋がった時刻のクエリ', title: '2人が知り合いになったのはいつ', tags: ['Union-Find'], io: '1行目に 人数 n と友達成立の件数 m、続く m 行に時刻順の友達関係 a b、最後の行に質問のペア u v が与えられます。', ask: 'u と v が(友達の連鎖で)初めて繋がった時刻(何件目の友達成立か、1始まり)を出力してください。最後まで繋がらなければ -1。', h1: '辺を時刻順に追加しながら繋がりを見る。', h2: '各追加のあとに find(u)==find(v) を確かめ、最初に真になった時刻が答え。', ref: 'n,m=map(int,input().split())\nes=[tuple(map(int,input().split())) for _ in range(m)]\nu,v=map(int,input().split())\npar=list(range(n+1))\ndef find(x):\n    while par[x]!=x:\n        par[x]=par[par[x]]\n        x=par[x]\n    return x\nans=-1\nfor i,(a,b) in enumerate(es,1):\n    ra,rb=find(a),find(b)\n    if ra!=rb:\n        par[ra]=rb\n    if find(u)==find(v):\n        ans=i\n        break\nprint(ans)', tip: '「いつ繋がったか」の多クエリ版はマージの木(Kruskal復元木)でLCAに化ける、奥行きのあるテーマ。1クエリなら逐次チェックで十分。', ins: ['4 3\n1 2\n3 4\n2 3\n1 4\n', '3 1\n1 2\n1 3\n', '2 1\n1 2\n1 2\n', '5 4\n1 2\n2 3\n3 4\n4 5\n1 5\n', '4 2\n1 2\n3 4\n1 3\n', '3 3\n1 2\n2 3\n1 3\n1 3\n'] })

t({ lv: 840, concept: '二分探索: 最も近い値のクエリ', title: '一番近い在庫サイズを探す', tags: ['二分探索'], io: '1行目に整数列(在庫)、2行目に問い合わせの値が空白区切りで与えられます。', ask: '各問い合わせ x について、在庫の中で x に最も近い値を出力してください(同じ近さなら小さい方)。答えは空白区切りで。', h1: 'ソートして挿入位置の左右だけ見る。', h2: 'bisect_left の位置とその1つ左の2候補を比べる。', ref: 'import bisect\na=sorted(map(int,input().split()))\nqs=list(map(int,input().split()))\nout=[]\nfor x in qs:\n    i=bisect.bisect_left(a,x)\n    cand=[]\n    if i>0:\n        cand.append(a[i-1])\n    if i<len(a):\n        cand.append(a[i])\n    best=min(cand,key=lambda v:(abs(v-x),v))\n    out.append(best)\nprint(*out)', tip: '最近傍は「挿入位置の両隣の2候補」に必ず入る。タイブレークまでkeyのタプルに書けば、条件が変わっても1行の修正で済む。', ins: ['1 4 6\n5 0 9\n', '10\n3 100\n', '2 8\n5\n', '1 3\n2\n', '5 5 5\n7 5\n', '-5 0 5\n-3 3 6\n'] })

export const CATALOG = TASKS
