// 生成タスク 第27波：lv180 + lv211〜240。
// 方針: 最上級(lv999帯)へ至る「前提分解」の踏み段。高度DP/グラフ/数論/二点法/単調スタックの
// 土台となる別計算をオリジナル化して配置。問題文・サンプルは自前、プラットフォーム名は出さない。
// 重複(参照解・概念名)なし。出力は決定的・採点一意。
const TASKS = []
const t = (obj) => TASKS.push(obj)

// --- 二点法 (ソート + 左右ポインタ) ---
t({ lv: 180, concept: '二点法: 和がK未満のペア数', title: '和がK未満になるペアの数', tags: ['二点法', 'ソート'], io: '1行目に n K、2行目に n 個の整数が与えられます。', ask: 'i<j かつ a[i]+a[j] < K となる要素ペア (i,j) の個数を出力してください。', h1: 'まず昇順にソートする。', h2: '左右からポインタを寄せ、和が小さければ右までまとめて数える。', ref: 'n,k=map(int,input().split())\na=sorted(map(int,input().split()))\nl=0\nr=n-1\nc=0\nwhile l<r:\n    if a[l]+a[r]<k:\n        c+=r-l\n        l+=1\n    else:\n        r-=1\nprint(c)', tip: 'ソート済みなら二点法で O(n) 回の比較に落とせる。', ins: ['5 6\n1 2 3 4 5\n', '4 10\n5 5 5 5\n', '3 100\n1 2 3\n', '2 5\n2 2\n', '1 5\n9\n', '6 7\n1 1 2 3 4 5\n'] })

// --- DP の幹 ---
t({ lv: 211, concept: 'DP: 最小コイン枚数', title: '金額をちょうど作る最小硬貨枚数', tags: ['dp'], io: '1行目に金額 X と硬貨の種類数 n、2行目に n 種類の額面が与えられます。各額面は何枚でも使えます。', ask: 'X をちょうど支払う最小の硬貨枚数を出力してください。作れない場合は -1 を出力してください。', h1: 'dp[v]=金額vを作る最小枚数。', h2: '各額面cについて dp[v]=min(dp[v], dp[v-c]+1)。', ref: 'x,n=map(int,input().split())\ncoins=list(map(int,input().split()))\nINF=float("inf")\ndp=[0]+[INF]*x\nfor v in range(1,x+1):\n    for c in coins:\n        if c<=v and dp[v-c]+1<dp[v]:\n            dp[v]=dp[v-c]+1\nprint(dp[x] if dp[x]<INF else -1)', tip: '「最小◯◯」はしばしば最短経路型DPに落ちる。', ins: ['11 3\n1 2 5\n', '3 2\n2 4\n', '0 1\n5\n', '6 2\n1 3\n', '7 3\n1 2 5\n', '100 4\n1 5 10 25\n'] })

t({ lv: 212, concept: 'DP: 段の上り方', title: '1段か2段で上る方法の数', tags: ['dp'], io: '整数 n が1行で与えられます。', ask: '1段または2段ずつ上って n 段ちょうどに到達する方法の総数を出力してください。', h1: 'n段目に来る直前は n-1 段目か n-2 段目。', h2: 'f(n)=f(n-1)+f(n-2)。フィボナッチ。', ref: 'n=int(input())\na,b=1,1\nfor _ in range(n):\n    a,b=b,a+b\nprint(a)', tip: '漸化式が立てば配列すら要らず2変数で回せる。', ins: ['4\n', '1\n', '2\n', '0\n', '10\n', '30\n'] })

t({ lv: 213, concept: 'DP: 障害物ありの経路数', title: '壁を避けて右下へ行く経路数', tags: ['dp', 'グリッド'], io: '1行目に H W、続く H 行に 0(通れる)/1(壁) のグリッドが与えられます。左上から右下へ、右か下にのみ進みます。', ask: '右下マスへ到達する経路の総数を出力してください (壁は通れません)。', h1: 'dp[i][j]=そのマスへの経路数。', h2: '壁なら0、それ以外は上+左。', ref: 'h,w=map(int,input().split())\ng=[input().split() for _ in range(h)]\ndp=[[0]*w for _ in range(h)]\nfor i in range(h):\n    for j in range(w):\n        if g[i][j]=="1":\n            dp[i][j]=0\n        elif i==0 and j==0:\n            dp[i][j]=1\n        else:\n            up=dp[i-1][j] if i>0 else 0\n            left=dp[i][j-1] if j>0 else 0\n            dp[i][j]=up+left\nprint(dp[h-1][w-1])', tip: '経路数の基本形は「上+左」。障害物は0で塞ぐだけ。', ins: ['3 3\n0 0 0\n0 1 0\n0 0 0\n', '2 2\n0 0\n0 0\n', '1 1\n0\n', '2 2\n0 1\n1 0\n', '1 4\n0 0 0 0\n', '3 4\n0 0 0 0\n0 0 0 0\n0 0 0 0\n'] })

t({ lv: 214, concept: 'DP: グリッド最小経路和', title: '右下までのコスト最小の道', tags: ['dp', 'グリッド'], io: '1行目に H W、続く H 行に W 個の非負整数が与えられます。左上から右下へ右か下にのみ進みます。', ask: '通過したマスの値の合計が最小になるときの合計値を出力してください。', h1: 'dp[i][j]=そこまでの最小コスト。', h2: '上と左の小さい方 + 自分のコスト。', ref: 'h,w=map(int,input().split())\ng=[list(map(int,input().split())) for _ in range(h)]\nINF=float("inf")\ndp=[[INF]*w for _ in range(h)]\ndp[0][0]=g[0][0]\nfor i in range(h):\n    for j in range(w):\n        if i==0 and j==0:\n            continue\n        best=INF\n        if i>0:\n            best=min(best,dp[i-1][j])\n        if j>0:\n            best=min(best,dp[i][j-1])\n        dp[i][j]=best+g[i][j]\nprint(dp[h-1][w-1])', tip: '「経路数」と同じ形でmaxやminに置き換えれば最適化DPになる。', ins: ['3 3\n1 3 1\n1 5 1\n4 2 1\n', '1 1\n5\n', '2 2\n1 2\n1 1\n', '1 3\n1 2 3\n', '3 1\n1\n2\n3\n', '2 3\n1 2 3\n4 5 6\n'] })

t({ lv: 215, concept: '貪欲: 最大両立区間数', title: '重ならないように選べる区間の最大数', tags: ['貪欲', 'ソート'], io: '1行目に区間の個数 n、続く n 行に各区間の開始 s と終了 e が与えられます。', ask: '互いに重ならないように選べる区間の最大個数を出力してください (端が接するのは重ならないとみなします)。', h1: '終了時刻が早い順に選ぶと良い。', h2: '直前に選んだ終了以降に始まる区間だけ採用。', ref: 'n=int(input())\niv=[tuple(map(int,input().split())) for _ in range(n)]\niv.sort(key=lambda x:x[1])\ncnt=0\nlast=-float("inf")\nfor s,e in iv:\n    if s>=last:\n        cnt+=1\n        last=e\nprint(cnt)', tip: '区間スケジューリングは「終了が早い順」の貪欲が最適。', ins: ['3\n1 2\n2 3\n1 3\n', '1\n0 5\n', '4\n1 3\n2 4\n3 5\n4 6\n', '3\n1 10\n2 3\n4 5\n', '2\n1 2\n3 4\n', '5\n1 2\n1 2\n1 2\n1 2\n1 2\n'] })

t({ lv: 216, concept: '貪欲: 末尾へ到達可能か', title: '各地点の最大移動量で末尾へ届くか', tags: ['貪欲'], io: '整数列が1行で与えられます。各値は「その位置から前方へ進めるマス数の上限」です。', ask: '先頭から出発して末尾の位置へ到達できるなら yes、できなければ no を出力してください。', h1: '到達できる最も先の位置を更新していく。', h2: '現在地が到達範囲を超えたら不可能。', ref: 'a=list(map(int,input().split()))\nreach=0\nok=True\nfor i in range(len(a)):\n    if i>reach:\n        ok=False\n        break\n    if i+a[i]>reach:\n        reach=i+a[i]\nprint("yes" if ok and reach>=len(a)-1 else "no")', tip: '「届く範囲」を1変数で持つだけで判定できる。', ins: ['2 3 1 1 4\n', '3 2 1 0 4\n', '0\n', '1 0\n', '2 0 0\n', '1 1 0 1\n'] })

t({ lv: 217, concept: 'DP: 最小ジャンプ回数', title: '末尾へ着くための最小ジャンプ数', tags: ['貪欲', 'dp'], io: '整数列が1行で与えられます (末尾へ到達可能)。各値はその位置から前方へ進める最大マス数です。', ask: '先頭から末尾まで移動する最小のジャンプ回数を出力してください。', h1: '今のジャンプで届く範囲の中で、次に最も遠くへ行ける所まで進む。', h2: '範囲を使い切るたびに回数を1増やす。', ref: 'a=list(map(int,input().split()))\nn=len(a)\njumps=0\ncur=0\nfar=0\ni=0\nwhile cur<n-1:\n    while i<=cur:\n        if i+a[i]>far:\n            far=i+a[i]\n        i+=1\n    cur=far\n    jumps+=1\nprint(jumps)', tip: '区間を「層」として広げる発想は幅優先と同じ最短性を持つ。', ins: ['2 3 1 1 4\n', '0\n', '1 1 1 1\n', '5 1 1 1 1\n', '2 1 1 1\n', '2 3 0 1 4\n'] })

t({ lv: 218, concept: 'DP: 金額の作り方の総数', title: '硬貨で金額を作る組合せの数', tags: ['dp'], io: '1行目に金額 X と硬貨の種類数 n、2行目に n 種類の額面が与えられます。各額面は何枚でも使えます。', ask: 'X を作る硬貨の組合せの総数を出力してください (使う順序は区別しません)。', h1: '硬貨を1種類ずつ加えながら数え上げる。', h2: '額面cを外ループにすると順序の重複を防げる。', ref: 'x,n=map(int,input().split())\ncoins=list(map(int,input().split()))\ndp=[0]*(x+1)\ndp[0]=1\nfor c in coins:\n    for v in range(c,x+1):\n        dp[v]+=dp[v-c]\nprint(dp[x])', tip: '「最小枚数」と「組合せ数」はループの順序で別物になる。', ins: ['5 3\n1 2 5\n', '0 1\n3\n', '4 1\n2\n', '10 2\n2 5\n', '6 3\n1 2 3\n', '7 2\n1 7\n'] })

t({ lv: 219, concept: 'DP: 最大部分配列和', title: '連続部分列の和の最大値', tags: ['dp'], io: '整数列 (負を含む) が1行で与えられます。', ask: '連続する1個以上の要素の和として得られる最大値を出力してください。', h1: '各位置で「ここで終わる連続和の最大」を持つ。', h2: '直前の和に足すか、自分から始め直すかの大きい方。', ref: 'a=list(map(int,input().split()))\nbest=cur=a[0]\nfor x in a[1:]:\n    cur=max(x,cur+x)\n    if cur>best:\n        best=cur\nprint(best)', tip: '負が続いたら和をリセットするのがこの手法の要点。', ins: ['-2 1 -3 4 -1 2 1 -5 4\n', '1 2 3\n', '-1 -2 -3\n', '5\n', '-5 4 -1 7 8\n', '2 -1 2 -1 2\n'] })

t({ lv: 220, concept: 'DP: 増加部分列の最大和', title: '増加する部分列の和の最大値', tags: ['dp'], io: '整数列が1行で与えられます。', ask: '狭義単調増加な部分列 (連続でなくてよい) を選んだとき、その要素の和の最大値を出力してください。', h1: 'dp[i]=a[i]で終わる増加部分列の最大和。', h2: 'a[j]<a[i] となる j からの最大に a[i] を足す。', ref: 'a=list(map(int,input().split()))\nn=len(a)\ndp=a[:]\nfor i in range(n):\n    for j in range(i):\n        if a[j]<a[i] and dp[j]+a[i]>dp[i]:\n            dp[i]=dp[j]+a[i]\nprint(max(dp))', tip: '「最長増加部分列」の長さを和に置き換えた変種。', ins: ['1 101 2 3 100\n', '3 4 5 10\n', '10 5 4 3\n', '1 2 3\n', '5\n', '4 6 1 3 8 4 6\n'] })

t({ lv: 221, concept: 'DP: 編集距離', title: '2つの文字列の編集距離', tags: ['dp', '文字列'], io: '2つの文字列が各行で与えられます。', ask: '1文字の挿入・削除・置換を繰り返して一方を他方に変えるのに必要な最小操作回数を出力してください。', h1: 'dp[i][j]=前半 i 文字と j 文字を一致させる最小コスト。', h2: '末尾が同じなら据え置き、違えば挿入/削除/置換の最小+1。', ref: 'a=input()\nb=input()\nm,n=len(a),len(b)\ndp=[[0]*(n+1) for _ in range(m+1)]\nfor i in range(m+1):\n    dp[i][0]=i\nfor j in range(n+1):\n    dp[0][j]=j\nfor i in range(1,m+1):\n    for j in range(1,n+1):\n        if a[i-1]==b[j-1]:\n            dp[i][j]=dp[i-1][j-1]\n        else:\n            dp[i][j]=1+min(dp[i-1][j],dp[i][j-1],dp[i-1][j-1])\nprint(dp[m][n])', tip: '3方向の遷移が「挿入・削除・置換」に対応する。', ins: ['horse\nros\n', 'intention\nexecution\n', 'abc\nabc\n', 'a\n\n', 'kitten\nsitting\n', 'flaw\nlawn\n'] })

t({ lv: 222, concept: 'DP: 最長共通部分列', title: '2文字列の最長共通部分列の長さ', tags: ['dp', '文字列'], io: '2つの文字列が各行で与えられます。', ask: '両方に同じ順序で現れる共通の部分列 (連続でなくてよい) の最大の長さを出力してください。', h1: 'dp[i][j]=前半 i 文字と j 文字の共通部分列の最大長。', h2: '末尾一致で +1、不一致なら上か左の大きい方。', ref: 'a=input()\nb=input()\nm,n=len(a),len(b)\ndp=[[0]*(n+1) for _ in range(m+1)]\nfor i in range(1,m+1):\n    for j in range(1,n+1):\n        if a[i-1]==b[j-1]:\n            dp[i][j]=dp[i-1][j-1]+1\n        else:\n            dp[i][j]=max(dp[i-1][j],dp[i][j-1])\nprint(dp[m][n])', tip: '「部分文字列(連続)」とは別物。こちらは飛び飛びでよい。', ins: ['abcde\nace\n', 'abc\nabc\n', 'abc\ndef\n', 'aggtab\ngxtxayb\n', 'a\nb\n', 'abcbdab\nbdcab\n'] })

t({ lv: 223, concept: 'DP: 0/1ナップサック', title: '容量制限つきで価値を最大化', tags: ['dp'], io: '1行目に品物数 n と容量 W、続く n 行に各品物の重さ w と価値 v が与えられます。各品物は1個だけ使えます。', ask: '重さの合計が W を超えない範囲で、価値の合計の最大値を出力してください。', h1: 'dp[c]=容量cで得られる最大価値。', h2: '各品物で容量を大きい方から更新し1個制限を守る。', ref: 'n,W=map(int,input().split())\ndp=[0]*(W+1)\nfor _ in range(n):\n    w,v=map(int,input().split())\n    for c in range(W,w-1,-1):\n        if dp[c-w]+v>dp[c]:\n            dp[c]=dp[c-w]+v\nprint(dp[W])', tip: '容量を降順に更新するのが「1個だけ」を保証する鍵。', ins: ['3 4\n1 2\n3 4\n4 5\n', '1 5\n10 100\n', '2 3\n1 1\n2 2\n', '0 5\n', '3 10\n5 10\n4 40\n6 30\n', '2 4\n2 3\n2 3\n'] })

t({ lv: 224, concept: 'DP: 整数の分割数', title: '整数を和で表す方法の数', tags: ['dp'], io: '整数 n が1行で与えられます。', ask: 'n を1以上の整数の和で表す方法の数を出力してください (順序は区別しません。例: 4 → 4, 3+1, 2+2, 2+1+1, 1+1+1+1 の5通り)。', h1: '使える最大の部品を1から増やしながら数える。', h2: '部品kを外ループにすると組合せ (順不同) を数えられる。', ref: 'n=int(input())\ndp=[0]*(n+1)\ndp[0]=1\nfor k in range(1,n+1):\n    for v in range(k,n+1):\n        dp[v]+=dp[v-k]\nprint(dp[n])', tip: '「金額の作り方」と同じ骨格。部品が 1..n の硬貨だと思えばよい。', ins: ['4\n', '1\n', '5\n', '0\n', '7\n', '10\n'] })

t({ lv: 231, concept: 'DP: 作れない最大金額', title: '硬貨で作れない最大の金額', tags: ['dp'], io: '1行目に上限 L と硬貨の種類数 n、2行目に n 種類の額面が与えられます。各額面は何枚でも使えます。', ask: '1〜L のうち、硬貨の組合せで作れない最大の金額を出力してください。すべて作れるなら -1 を出力してください。', h1: 'ok[v]=金額vが作れるか、を下から埋める。', h2: 'いずれかの額面cで ok[v-c] が真なら ok[v] も真。', ref: 'L,n=map(int,input().split())\ncoins=list(map(int,input().split()))\nok=[False]*(L+1)\nok[0]=True\nfor v in range(1,L+1):\n    for c in coins:\n        if c<=v and ok[v-c]:\n            ok[v]=True\n            break\nans=-1\nfor v in range(1,L+1):\n    if not ok[v]:\n        ans=v\nprint(ans)', tip: '到達可能性DPは bool 配列で十分軽い。', ins: ['20 2\n3 5\n', '10 1\n2\n', '10 2\n1 2\n', '15 2\n4 7\n', '5 1\n1\n', '12 3\n3 4 5\n'] })

// --- 数論の幹 ---
t({ lv: 225, concept: '数論: 二項係数', title: '組合せの数 C(n,k)', tags: ['数論'], io: 'n と k が空白区切りで与えられます (0<=k<=n)。', ask: 'n 個から k 個を選ぶ組合せの数 C(n,k) を出力してください。', h1: 'C(n,k)=C(n,n-k)。小さい方で計算すると速い。', h2: '積を1つ掛けるたびに整数で割れる順序で計算する。', ref: 'n,k=map(int,input().split())\nk=min(k,n-k)\nres=1\nfor i in range(k):\n    res=res*(n-i)//(i+1)\nprint(res)', tip: 'res=res*(n-i)//(i+1) の順なら毎回割り切れて誤差なし。', ins: ['5 2\n', '10 0\n', '6 3\n', '52 5\n', '20 10\n', '1 1\n'] })

t({ lv: 226, concept: '数論: 繰り返し二乗法', title: 'べき乗を法で割った余り', tags: ['数論'], io: 'a b m が空白区切りで与えられます。', ask: 'a の b 乗を m で割った余りを出力してください。', h1: '指数を半分にしながら底を2乗していく。', h2: '指数が奇数のときだけ答えに掛ける。', ref: 'a,b,m=map(int,input().split())\nres=1%m\na%=m\nwhile b>0:\n    if b%2==1:\n        res=res*a%m\n    a=a*a%m\n    b//=2\nprint(res)', tip: '繰り返し二乗法で b 乗が O(log b) 回の掛け算になる。', ins: ['2 10 1000\n', '3 0 7\n', '5 3 13\n', '2 100 1000000007\n', '7 256 1000\n', '10 9 6\n'] })

t({ lv: 227, concept: '数論: 複数数の最小公倍数', title: '数列全体の最小公倍数', tags: ['数論'], io: '整数列が1行で与えられます (各値は1以上)。', ask: 'すべての要素の最小公倍数を出力してください。', h1: 'lcm(a,b)=a*b//gcd(a,b)。', h2: '先頭から畳み込むように lcm を取っていく。', ref: 'def gcd(a,b):\n    while b:\n        a,b=b,a%b\n    return a\na=list(map(int,input().split()))\nl=1\nfor x in a:\n    l=l*x//gcd(x,l)\nprint(l)', tip: 'ユークリッドの互除法は while 数行で書ける。', ins: ['4 6\n', '2 3 4\n', '5\n', '1 1 1\n', '6 8 12\n', '7 14 21\n'] })

t({ lv: 228, concept: '数論: 複数数の最大公約数', title: '数列全体の最大公約数', tags: ['数論'], io: '整数列が1行で与えられます (各値は1以上)。', ask: 'すべての要素の最大公約数を出力してください。', h1: 'gcd(a,b,c)=gcd(gcd(a,b),c)。', h2: '先頭を初期値にして順に gcd を取る。', ref: 'def gcd(a,b):\n    while b:\n        a,b=b,a%b\n    return a\na=list(map(int,input().split()))\ng=a[0]\nfor x in a[1:]:\n    g=gcd(g,x)\nprint(g)', tip: 'gcd は結合的なので畳み込みで全体のgcdが出る。', ins: ['12 18\n', '4 8 16\n', '7\n', '5 7 11\n', '100 80 60\n', '9 6 3\n'] })

t({ lv: 229, concept: '数論: k番目の素数', title: 'k番目に小さい素数', tags: ['数論'], io: '整数 k が1行で与えられます (1始まり)。', ask: 'k 番目に小さい素数を出力してください。', h1: '2から順に素数判定し、見つけた素数を貯める。', h2: '判定は「これまでの素数のうち平方根以下」で割れるか見れば十分。', ref: 'k=int(input())\nprimes=[]\nx=2\nwhile len(primes)<k:\n    is_p=True\n    for p in primes:\n        if p*p>x:\n            break\n        if x%p==0:\n            is_p=False\n            break\n    if is_p:\n        primes.append(x)\n    x+=1\nprint(primes[-1])', tip: '既出の素数だけで割れば試し割りがぐっと速くなる。', ins: ['1\n', '5\n', '10\n', '2\n', '25\n', '100\n'] })

// --- ハッシュ / 二点法 / 単調スタック ---
t({ lv: 230, concept: '文字列: アナグラムのグループ数', title: '並べ替えで一致する単語のグループ数', tags: ['文字列', 'ハッシュ'], io: '1行目に単語数 n、続く n 行に小文字英単語が与えられます。', ask: '文字を並べ替えると互いに一致する単語を同じグループにまとめたとき、グループの個数を出力してください。', h1: '各単語の文字をソートした文字列を「指紋」にする。', h2: '指紋の種類数を数える。', ref: 'n=int(input())\ngroups=set()\nfor _ in range(n):\n    w=input()\n    groups.add("".join(sorted(w)))\nprint(len(groups))', tip: 'ソート済み文字列はアナグラム判定の手軽な正規形。', ins: ['3\neat\ntea\ntan\n', '1\nabc\n', '4\nabc\nbca\ncab\nxyz\n', '2\naa\nbb\n', '3\nlisten\nsilent\nenlist\n', '4\na\nb\na\nb\n'] })

t({ lv: 232, concept: '二点法: 最大の貯水量', title: '2本の縦線で挟める最大の水量', tags: ['二点法'], io: '整数列 (各値は0以上) が1行で与えられます。各値は縦線の高さです。', ask: '2本の線 i, j と横軸で囲める面積 min(h[i],h[j])*(j-i) の最大値を出力してください。', h1: '左右の端から内側へ寄せる。', h2: '低い方の線を動かすと面積が増える可能性がある。', ref: 'h=list(map(int,input().split()))\nl=0\nr=len(h)-1\nbest=0\nwhile l<r:\n    area=min(h[l],h[r])*(r-l)\n    if area>best:\n        best=area\n    if h[l]<h[r]:\n        l+=1\n    else:\n        r-=1\nprint(best)', tip: '低い方を動かすのが正しいのは、幅が縮む損を高さの得で上回り得るから。', ins: ['1 8 6 2 5 4 8 3 7\n', '1 1\n', '4 3 2 1 4\n', '1 2 1\n', '2 3 4 5 18 17 6\n', '0 0\n'] })

t({ lv: 233, concept: '二点法: 和が0の三つ組の数', title: '和が0になる3要素の組の種類数', tags: ['二点法', 'ソート'], io: '整数列が1行で与えられます。', ask: '位置の異なる3要素の値の組で和が0になるものを、値の組として重複を除いて数え、その個数を出力してください。', h1: 'ソートして1つ固定し、残りを二点法で探す。', h2: '同じ値の組を二重に数えないよう集合で管理。', ref: 'a=sorted(map(int,input().split()))\nn=len(a)\nres=set()\nfor i in range(n):\n    l=i+1\n    r=n-1\n    while l<r:\n        s=a[i]+a[l]+a[r]\n        if s==0:\n            res.add((a[i],a[l],a[r]))\n            l+=1\n            r-=1\n        elif s<0:\n            l+=1\n        else:\n            r-=1\nprint(len(res))', tip: '1要素を固定し残りを二点法にすると三重ループを1つ減らせる。', ins: ['-1 0 1 2 -1 -4\n', '0 0 0 0\n', '1 2 3\n', '-2 0 1 1 2\n', '3 -1 -2\n', '0 0 0\n'] })

t({ lv: 234, concept: 'ハッシュ: 和がKの部分配列の数', title: '和がちょうどKの連続部分配列の個数', tags: ['累積和', 'ハッシュ'], io: '1行目に n K、2行目に n 個の整数 (負を含む) が与えられます。', ask: '和がちょうど K になる連続部分配列の個数を出力してください。', h1: '累積和 s について s-K がこれまで何回現れたかを数える。', h2: '辞書に累積和の出現回数を貯める。', ref: 'from collections import defaultdict\nn,k=map(int,input().split())\na=list(map(int,input().split()))\ncnt=defaultdict(int)\ncnt[0]=1\ns=0\nres=0\nfor x in a:\n    s+=x\n    res+=cnt[s-k]\n    cnt[s]+=1\nprint(res)', tip: '累積和+辞書は「和が条件を満たす区間」を O(n) で数える定石。', ins: ['4 2\n1 1 1 1\n', '3 0\n1 -1 0\n', '1 5\n5\n', '4 0\n0 0 0 0\n', '5 3\n1 2 3 -1 1\n', '6 5\n1 2 1 2 1 2\n'] })

t({ lv: 235, concept: 'ハッシュ: 最長連続整数列', title: '値が連続する最長の並びの長さ', tags: ['ハッシュ'], io: '整数列が1行で与えられます。', ask: '値が1ずつ連続して繋がる最長の並びの長さを出力してください (元の順序や重複は無視します)。', h1: '集合に入れ、各連の先頭からだけ伸ばす。', h2: 'x-1 が無い x を起点に x+1, x+2 ... と数える。', ref: 'a=set(map(int,input().split()))\nbest=0\nfor x in a:\n    if x-1 not in a:\n        y=x\n        while y+1 in a:\n            y+=1\n        if y-x+1>best:\n            best=y-x+1\nprint(best)', tip: '起点だけから伸ばすので全体でも O(n) で済む。', ins: ['100 4 200 1 3 2\n', '1 2 0 1\n', '5\n', '10 30 20\n', '1 2 3 4 5\n', '9 1 4 7 3 2 6 5\n'] })

t({ lv: 236, concept: '単調スタック: 次に大きい要素までの距離和', title: '右で初めて大きくなるまでの距離の合計', tags: ['単調スタック'], io: '整数列が1行で与えられます。', ask: '各位置について「右側で初めて自分より大きい値が現れるまでの距離」を求め (無ければ0)、その総和を出力してください。', h1: 'まだ答えが決まっていない位置をスタックに積む。', h2: '今の値がスタック頂より大きいなら、その位置の距離が確定する。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nans=[0]*n\nst=[]\nfor i in range(n):\n    while st and a[st[-1]]<a[i]:\n        j=st.pop()\n        ans[j]=i-j\n    st.append(i)\nprint(sum(ans))', tip: '単調スタックは各要素が一度だけ出入りするので全体 O(n)。', ins: ['73 74 75 71 69 72 76 73\n', '1 2 3\n', '3 2 1\n', '5\n', '2 1 2 1 2\n', '1 3 2 4\n'] })

t({ lv: 237, concept: 'スタック: 隣接重複の消去後の長さ', title: '隣り合う同字を消し切った後の長さ', tags: ['スタック', '文字列'], io: '小文字英字の文字列が1行で与えられます。', ask: '隣り合う同じ文字2つを取り除く操作を、できなくなるまで繰り返した後の文字列の長さを出力してください。', h1: 'スタックに1文字ずつ積む。', h2: '頂と同じ文字が来たら積まずに頂を取り除く。', ref: 's=input()\nst=[]\nfor ch in s:\n    if st and st[-1]==ch:\n        st.pop()\n    else:\n        st.append(ch)\nprint(len(st))', tip: '「隣接ペア消去」はスタックで1パスに畳める典型。', ins: ['abbaca\n', 'aabb\n', 'abc\n', 'a\n', 'aaa\n', 'abccba\n'] })

// --- グラフの幹 ---
t({ lv: 238, concept: 'グラフ: 二部グラフ判定', title: '2色で塗り分けられるか', tags: ['グラフ', 'BFS'], io: '1行目に n m、続く m 行に無向辺 u v (頂点は1..n) が与えられます。', ask: '隣り合う頂点が必ず別の色になるよう2色で塗り分けられる (二部グラフである) なら yes、できなければ no を出力してください。', h1: '幅優先で交互に色を塗る。', h2: '既に塗った隣が同色なら二部グラフでない。', ref: 'from collections import deque\nn,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\ncolor=[-1]*(n+1)\nok=True\nfor s in range(1,n+1):\n    if color[s]==-1:\n        color[s]=0\n        dq=deque([s])\n        while dq:\n            x=dq.popleft()\n            for y in g[x]:\n                if color[y]==-1:\n                    color[y]=1-color[x]\n                    dq.append(y)\n                elif color[y]==color[x]:\n                    ok=False\nprint("yes" if ok else "no")', tip: '二部グラフ ⇔ 奇数長の閉路を持たない、と同値。', ins: ['4 4\n1 2\n2 3\n3 4\n4 1\n', '3 3\n1 2\n2 3\n1 3\n', '2 1\n1 2\n', '1 0\n', '5 4\n1 2\n2 3\n3 4\n4 5\n', '6 4\n1 2\n3 4\n4 5\n5 3\n'] })

t({ lv: 239, concept: 'グラフ: 最大連結成分のサイズ', title: '最も大きい連結成分の頂点数', tags: ['グラフ', 'BFS'], io: '1行目に n m、続く m 行に無向辺 u v (頂点は1..n) が与えられます。', ask: '連結成分のうち、最も頂点数が多いものの頂点数を出力してください。', h1: '未訪問の頂点から幅優先で成分を1つ塗る。', h2: '各成分のサイズの最大を取る。', ref: 'from collections import deque\nn,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\nseen=[False]*(n+1)\nbest=0\nfor s in range(1,n+1):\n    if not seen[s]:\n        seen[s]=True\n        dq=deque([s])\n        sz=0\n        while dq:\n            x=dq.popleft()\n            sz+=1\n            for y in g[x]:\n                if not seen[y]:\n                    seen[y]=True\n                    dq.append(y)\n        if sz>best:\n            best=sz\nprint(best)', tip: '連結成分はBFS/DFSで1つずつ塗りつぶして数えるのが基本。', ins: ['6 3\n1 2\n2 3\n4 5\n', '4 0\n', '5 4\n1 2\n2 3\n3 4\n4 5\n', '1 0\n', '6 2\n1 2\n3 4\n', '7 3\n1 2\n1 3\n1 4\n'] })

t({ lv: 240, concept: 'グラフ: 三角形の個数', title: '三角形 (3頂点が相互に隣接) の数', tags: ['グラフ'], io: '1行目に n m、続く m 行に無向辺 u v (頂点は1..n、多重辺なし) が与えられます。', ask: '3頂点が互いに辺で結ばれている三角形の個数を出力してください。', h1: '隣接の有無を表で持つ。', h2: 'i<j<k の3つ組が全て隣接かを調べる。', ref: 'n,m=map(int,input().split())\nadj=[[False]*(n+1) for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    adj[u][v]=True\n    adj[v][u]=True\ncnt=0\nfor i in range(1,n+1):\n    for j in range(i+1,n+1):\n        if adj[i][j]:\n            for k in range(j+1,n+1):\n                if adj[i][k] and adj[j][k]:\n                    cnt+=1\nprint(cnt)', tip: 'i<j<k の順で見れば各三角形をちょうど1回数えられる。', ins: ['3 3\n1 2\n2 3\n1 3\n', '4 6\n1 2\n1 3\n1 4\n2 3\n2 4\n3 4\n', '3 2\n1 2\n2 3\n', '4 0\n', '5 6\n1 2\n2 3\n1 3\n3 4\n4 5\n3 5\n', '6 9\n1 2\n2 3\n1 3\n4 5\n5 6\n4 6\n1 4\n2 5\n3 6\n'] })

export const CATALOG = TASKS
