// 生成タスク 第75波：データ分析トラック拡充(ユーザー要望)。numpy/pandas/scipy の実務APIを22問。
// lv085(numpy) / lv090(統計・scipy.stats) / lv095(pandas) / lv105(pandas応用) / lv110(scipy数値計算)。
// 出力は丸め・明示整形でバージョン差を吸収。matplotlibは標準出力採点と相性が悪いため対象外(ヒストグラム計算などで代替)。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 85, concept: 'numpy: 形の変更(reshape)', title: '1列のデータを表に組み直す', tags: ['numpy'], io: '1行目に 行数 r と列数 c、2行目に r×c 個の整数が与えられます。', ask: '数列を r 行 c 列に並べ直し、各行を空白区切りで出力してください。', h1: 'np.array してから形を変える。', h2: 'a.reshape(r, c) の各行を出力する。', ref: 'import numpy as np\nr,c=map(int,input().split())\na=np.array(list(map(int,input().split()))).reshape(r,c)\nfor row in a:\n    print(*row.tolist())', tip: 'reshapeは要素数が合わないと即エラーになる安全装置つき。-1 を1箇所だけ書くと「残りから自動計算」してくれるのが実戦での定番。', ins: ['2 3\n1 2 3 4 5 6\n', '3 2\n1 2 3 4 5 6\n', '1 4\n9 8 7 6\n', '4 1\n1 2 3 4\n', '2 2\n0 0 0 0\n', '3 3\n1 2 3 4 5 6 7 8 9\n'] })

t({ lv: 85, concept: 'numpy: 条件で置き換え(where)', title: 'マイナスをゼロに直す', tags: ['numpy'], io: '整数列が1行で空白区切りで与えられます。', ask: '負の要素を0に置き換えた列を空白区切りで出力してください。', h1: '条件・真のとき・偽のとき、の3つ組。', h2: 'np.where(a<0, 0, a)。', ref: 'import numpy as np\na=np.array(list(map(int,input().split())))\nprint(*np.where(a<0,0,a).tolist())', tip: 'whereはif文をベクトルに広げた演算子。ReLU(負を0に)はニューラルネットの活性化関数そのもので、np.maximum(a,0) とも書ける。', ins: ['1 -2 3 -4\n', '-1 -1\n', '5 6 7\n', '0\n', '-10 10 -10\n', '3 -3 0 -7 7\n'] })

t({ lv: 85, concept: 'numpy: 並べ替えの添字(argsort)', title: '順位表の並び順を知る', tags: ['numpy'], io: '相異なる整数の列が1行で空白区切りで与えられます。', ask: '昇順に並べたとき「元のどの位置の要素が来るか」(argsort)を空白区切りで出力してください(位置は0始まり)。', h1: '値でなく添字の並びが欲しい。', h2: 'np.argsort(a)。', ref: 'import numpy as np\na=np.array(list(map(int,input().split())))\nprint(*np.argsort(a).tolist())', tip: '「値のソート」と「添字のソート」の区別がデータ分析の急所。argsortの結果で他の列を並べ替えれば、表全体のソートになる。', ins: ['3 1 2\n', '10 20 30\n', '5 4 3 2 1\n', '7\n', '2 8 1 9\n', '100 -100 0\n'] })

t({ lv: 85, concept: 'numpy: 行列積(@)', title: '行列のかけ算を1発で', tags: ['numpy'], io: '1行目に n、続く n 行に行列A、さらに n 行に行列Bが与えられます。', ask: '行列積 A×B を計算し、各行を空白区切りで出力してください。', h1: '要素ごとの積(*)とは別物。', h2: 'A @ B が行列積。', ref: 'import numpy as np\nn=int(input())\nA=np.array([list(map(int,input().split())) for _ in range(n)])\nB=np.array([list(map(int,input().split())) for _ in range(n)])\nC=A@B\nfor row in C:\n    print(*row.tolist())', tip: '* は要素ごと、@ は行列積、と演算子で意味が変わるのがnumpyの流儀。3重ループの手書き実装と突き合わせると @ のありがたみが分かる。', ins: ['2\n1 2\n3 4\n5 6\n7 8\n', '2\n1 0\n0 1\n9 8\n7 6\n', '1\n3\n4\n', '2\n1 1\n1 1\n1 1\n1 1\n', '3\n1 0 0\n0 1 0\n0 0 1\n1 2 3\n4 5 6\n7 8 9\n', '2\n2 0\n0 2\n1 2\n3 4\n'] })

t({ lv: 85, concept: 'numpy: 百分位点(percentile)', title: '上位何パーセントの境目', tags: ['numpy'], io: '1行目にパーセント q (0〜100)、2行目に整数列が与えられます。', ask: 'q パーセンタイル(線形補間)を小数第2位まで出力してください。', h1: '中央値の一般化。', h2: 'np.percentile(a, q)。', ref: 'import numpy as np\nq=int(input())\na=np.array(list(map(int,input().split())))\nprint(f"{np.percentile(a,q):.2f}")', tip: 'p50は中央値、p95はレイテンシSLOの定番。補間方法(linear/nearest…)で値が変わるので、レポートには方式を明記する習慣を。', ins: ['50\n1 2 3 4\n', '0\n5 1 9\n', '100\n5 1 9\n', '25\n1 2 3 4 5\n', '90\n1 2 3 4 5 6 7 8 9 10\n', '50\n7\n'] })

t({ lv: 85, concept: 'numpy: ヒストグラムのビン集計(histogram)', title: 'グラフを描く前の集計', tags: ['numpy'], io: '1行目に ビン数 k と範囲 lo hi、2行目に整数列が与えられます。', ask: 'np.histogram で範囲 [lo, hi] を k 等分したビンの度数を空白区切りで出力してください。', h1: 'matplotlibのヒストグラムの中身はこの計算。', h2: 'np.histogram(a, bins=k, range=(lo,hi)) の第1戻り値。', ref: 'import numpy as np\nk,lo,hi=map(int,input().split())\na=np.array(list(map(int,input().split())))\nh,_=np.histogram(a,bins=k,range=(lo,hi))\nprint(*h.tolist())', tip: 'グラフ描画(matplotlib)と集計(numpy)は分離できる。最後のビンだけ右端を含む、という境界規約はヒストグラムのバグの名所。', ins: ['2 0 10\n1 2 8 9\n', '5 0 5\n0 1 2 3 4\n', '3 0 9\n0 0 9 9 9\n', '1 0 100\n50 60 70\n', '4 0 8\n1 3 5 7\n', '2 0 4\n2 2 2\n'] })

t({ lv: 90, concept: '統計: 幾何平均', title: '成長率の正しい平均', tags: ['統計'], io: '正整数の列が1行で空白区切りで与えられます。', ask: '幾何平均(積の n 乗根)を小数第2位まで出力してください。', h1: '算術平均とは別物。', h2: 'statistics.geometric_mean が使える。', ref: 'import statistics\na=list(map(int,input().split()))\nprint(f"{statistics.geometric_mean(a):.2f}")', tip: '「2倍になって半分に戻った」の平均成長率は算術平均だと1.25倍に見えるが幾何平均なら正しく1倍。比率・成長率の平均は幾何平均が正解。', ins: ['2 8\n', '1 1 1\n', '4 9\n', '1 10 100\n', '3 3 3\n', '2 4 8\n'] })

t({ lv: 90, concept: '統計: 最頻値の全列挙(multimode)', title: '1位タイをぜんぶ挙げる', tags: ['統計'], io: '整数列が1行で空白区切りで与えられます。', ask: '最頻値をすべて昇順に空白区切りで出力してください。', h1: 'modeは1つしか返さない。', h2: 'statistics.multimode が同率1位を全部返す(ソートして出力)。', ref: 'import statistics\na=list(map(int,input().split()))\nprint(*sorted(statistics.multimode(a)))', tip: 'mode は多峰のとき最初の1つだけ返す仕様(3.8以降)。タイの扱いはライブラリごとに違うので、multimodeの存在を知っていると事故が減る。', ins: ['1 1 2 2 3\n', '5 5 5\n', '1 2 3\n', '4 4 2 2 4\n', '7\n', '9 8 9 8 7\n'] })

t({ lv: 90, concept: '統計: 四分位数(quantiles)', title: 'データを4等分する3つの境界', tags: ['統計'], io: '整数列(4個以上)が1行で空白区切りで与えられます。', ask: 'statistics.quantiles(既定の排他的方式)で四分位数 Q1 Q2 Q3 を空白区切りで小数第2位まで出力してください。', h1: '4等分の境界は3つ。', h2: 'statistics.quantiles(a, n=4)。', ref: 'import statistics\na=list(map(int,input().split()))\nqs=statistics.quantiles(a,n=4)\nprint(*[f"{q:.2f}" for q in qs])', tip: '四分位の定義は9種類以上あり(排他/包含/最近傍…)、ExcelとRとPythonで値が違うことも。方式を固定して比較する、が分析の作法。', ins: ['1 2 3 4\n', '1 2 3 4 5 6 7 8\n', '10 20 30 40 50\n', '1 1 1 1\n', '2 4 6 8 10 12\n', '5 1 9 3\n'] })

t({ lv: 90, concept: 'scipy: 順位相関(スピアマン)', title: '順位で測るつながりの強さ', tags: ['scipy', '統計'], io: '1行目と2行目に同じ個数の整数列(それぞれ同順位なし)が与えられます。', ask: 'スピアマンの順位相関係数を小数第2位まで出力してください。', h1: '値でなく順位の相関。', h2: 'scipy.stats.spearmanr の第1戻り値。', ref: 'from scipy import stats\na=list(map(int,input().split()))\nb=list(map(int,input().split()))\nprint(f"{stats.spearmanr(a,b).statistic:.2f}")', tip: '外れ値や非線形な単調関係に強いのが順位相関。ピアソンとの差が大きいときは「直線でない関係」か「外れ値」を疑うシグナルになる。', ins: ['1 2 3\n10 20 30\n', '1 2 3\n30 20 10\n', '1 2 3 4\n1 3 2 4\n', '5 10 15 20\n1 2 4 3\n', '1 2\n2 1\n', '3 1 2\n30 10 20\n'] })

t({ lv: 90, concept: 'scipy: t検定の統計量', title: '2群の差は偶然か', tags: ['scipy', '統計'], io: '1行目にA群、2行目にB群の整数列が与えられます(各群2個以上)。', ask: '独立2標本のt検定(等分散を仮定)のt統計量を小数第2位まで出力してください。', h1: '平均の差を標準誤差で割った量。', h2: 'scipy.stats.ttest_ind の statistic。', ref: 'from scipy import stats\na=list(map(int,input().split()))\nb=list(map(int,input().split()))\nprint(f"{stats.ttest_ind(a,b).statistic:.2f}")', tip: 'tの絶対値が大きいほど「差が偶然でない」証拠が強い。p値と対で読むのが本来で、有意水準の議論へ進む入り口の1問。', ins: ['1 2 3\n4 5 6\n', '1 2 1 2\n2 3 2 3\n', '1 2\n3 4\n', '5 6 7 8\n1 2 3 4\n', '1 3 5\n2 4 6\n', '2 4\n8 10\n'] })

t({ lv: 95, concept: 'pandas: 上位k行の抽出(nlargest)', title: '売上トップkを取り出す', tags: ['pandas'], io: '1行目に k、2行目に整数列が与えられます。', ask: 'Series にして値の大きい順に k 個(同値は先に現れた方が先)を空白区切りで出力してください。', h1: 'ソートして先頭k個でもよいが専用メソッドがある。', h2: 's.nlargest(k) の値を並べる。', ref: 'import pandas as pd\nk=int(input())\ns=pd.Series(list(map(int,input().split())))\nprint(*s.nlargest(k).tolist())', tip: 'nlargest/nsmallest は全体ソートより速く、実務の「トップN抽出」を意図が伝わる名前で書ける。keep引数でタイの扱いも選べる。', ins: ['2\n3 1 4 1 5\n', '1\n9 8 7\n', '3\n5 5 5 5\n', '2\n10 20\n', '1\n0\n', '3\n2 8 6 4\n'] })

t({ lv: 95, concept: 'pandas: 欠損の数を数える(isna)', title: '空欄はいくつあるか', tags: ['pandas'], io: '値の列が1行で空白区切りで与えられます(欠損は "na" と書かれています)。', ask: '欠損(NaN)の個数を出力してください。', h1: 'naをNaNに読み替えてSeriesを作る。', h2: 'pd.to_numeric(..., errors="coerce") でnaがNaNになり、isna().sum() で数えられる。', ref: 'import pandas as pd\nraw=input().split()\ns=pd.to_numeric(pd.Series(raw),errors="coerce")\nprint(int(s.isna().sum()))', tip: '現実のデータはまず欠損の把握から。coerce(強制変換で失敗はNaN)は汚いデータの一次処理の定番オプション。', ins: ['1 na 3 na\n', '1 2 3\n', 'na na na\n', '5\n', 'na 1\n', '1 na 2 na 3 na\n'] })

t({ lv: 95, concept: 'pandas: 重複行の除去(drop_duplicates)', title: 'ダブり登録を消す', tags: ['pandas'], io: '整数列が1行で空白区切りで与えられます。', ask: '最初の出現だけ残して重複を除いた列を空白区切りで出力してください。', h1: '順序は保たれる。', h2: 's.drop_duplicates()。', ref: 'import pandas as pd\ns=pd.Series(list(map(int,input().split())))\nprint(*s.drop_duplicates().tolist())', tip: '素のPythonなら dict.fromkeys で書く処理が、表データでは drop_duplicates の一語になる。subset引数で「特定列だけ見て重複判定」もできる。', ins: ['1 2 1 3 2\n', '5 5 5\n', '1 2 3\n', '9\n', '3 1 3 1 3\n', '2 2 1 1 2\n'] })

t({ lv: 95, concept: 'pandas: ランク付け(rank)', title: '得点に順位をつける', tags: ['pandas'], io: '整数列が1行で空白区切りで与えられます。', ask: '各要素の順位(大きい方が1位、同点は最小順位方式 method="min")を整数で空白区切りで出力してください。', h1: '自分でソートしなくてよい。', h2: 's.rank(ascending=False, method="min")。', ref: 'import pandas as pd\ns=pd.Series(list(map(int,input().split())))\nr=s.rank(ascending=False,method="min").astype(int)\nprint(*r.tolist())', tip: 'rankのmethod(min/max/dense/average/first)は同点処理の方針そのもの。競技の順位表はmin、偏差値の計算はaverage、と使い分ける。', ins: ['100 90 90 80\n', '1 2 3\n', '5 5 5\n', '7\n', '10 30 20\n', '3 1 4 1 5\n'] })

t({ lv: 105, concept: 'pandas応用: ピボットテーブル', title: '縦持ちデータをクロス集計', tags: ['pandas応用'], io: '1行目に件数 n、続く n 行に「行キー 列キー 数値」が与えられます。', ask: '行キー×列キーで数値を合計するクロス集計を作り、行キー昇順・列キー昇順で「行キー 列キー 合計」を1行ずつ出力してください(存在する組のみ)。', h1: 'pivot_table(aggfunc="sum") で表になる。', h2: 'stackして並べ替えれば「存在する組」だけ順に取り出せる。', ref: 'import pandas as pd\nn=int(input())\nrows=[input().split() for _ in range(n)]\ndf=pd.DataFrame(rows,columns=["r","c","v"])\ndf["v"]=df["v"].astype(int)\ng=df.groupby(["r","c"])["v"].sum()\nfor (r,c),v in g.items():\n    print(r,c,v)', tip: 'pivot_tableとgroupby(複数キー)は同じ集計の縦横違い。BIツールのクロス集計の裏側はこの2行で説明できる。', ins: ['3\na x 1\na y 2\na x 3\n', '2\nb x 5\na x 7\n', '4\np q 1\np q 1\nq p 2\nq q 3\n', '1\nz z 9\n', '3\nm n 1\nn m 2\nm n 3\n', '2\na b 0\na b 0\n'] })

t({ lv: 105, concept: 'pandas応用: 複数の集計を一度に(agg)', title: '合計と最大をまとめて出す', tags: ['pandas応用'], io: '1行目に件数 n、続く n 行に「グループ名 数値」が与えられます。', ask: 'グループごとに合計と最大値を求め、グループ名の昇順に「名前 合計 最大」を1行ずつ出力してください。', h1: 'groupbyのあとに複数の関数を渡せる。', h2: '.agg(["sum","max"]) で一度に計算できる。', ref: 'import pandas as pd\nn=int(input())\nrows=[input().split() for _ in range(n)]\ndf=pd.DataFrame(rows,columns=["k","v"])\ndf["v"]=df["v"].astype(int)\ng=df.groupby("k")["v"].agg(["sum","max"]).sort_index()\nfor k,row in g.iterrows():\n    print(k,int(row["sum"]),int(row["max"]))', tip: '集計関数を「文字列のリスト」で渡すインターフェースがpandas流。名前つき集計 agg(total=("v","sum")) まで覚えると実務のレポートが速い。', ins: ['3\na 1\nb 5\na 3\n', '2\nx 7\nx 2\n', '4\np 1\nq 2\np 3\nq 4\n', '1\nz 0\n', '5\na 2\nb 2\na 2\nb 3\nc 1\n', '2\nm 10\nn 20\n'] })

t({ lv: 105, concept: 'pandas応用: 文字列を含む行の数(str.contains)', title: 'キーワードを含む行を数える', tags: ['pandas応用'], io: '1行目に検索語、2行目以降...ではなく2行目に件数 n、続く n 行に文字列が与えられます。', ask: '検索語を部分文字列として含む行の数を出力してください。', h1: '列全体への文字列操作は .str 経由。', h2: 's.str.contains(word, regex=False).sum()。', ref: 'import pandas as pd\nword=input()\nn=int(input())\ns=pd.Series([input() for _ in range(n)])\nprint(int(s.str.contains(word,regex=False).sum()))', tip: '.str アクセサはSeriesの各要素へ文字列メソッドを一斉適用する門。regex=False を明示すると記号入りの検索語で事故らない。', ins: ['ab\n3\nabc\nxyz\ncab\n', 'q\n2\nqq\npp\n', 'on\n4\npython\njson\nc\ncondition\n', 'z\n1\nzzz\n', 'aa\n3\na\naa\naaa\n', 'x\n2\ny\nz\n'] })

t({ lv: 110, concept: 'scipy: 数値積分(quad)', title: '面積を関数から直接求める', tags: ['scipy'], io: '積分区間 a b が空白区切りで1行で与えられます。', ask: '関数 f(x)=x² を a から b まで数値積分した値を小数第2位まで出力してください。', h1: '台形則を自分で書かなくてよい。', h2: 'scipy.integrate.quad(lambda x: x*x, a, b) の第1戻り値。', ref: 'from scipy import integrate\na,b=map(int,input().split())\nv,_=integrate.quad(lambda x:x*x,a,b)\nprint(f"{v:.2f}")', tip: 'quadは誤差推定つきの適応積分で、手書きの台形則・シンプソン則の到達点にあたる。戻り値が(値, 誤差見積り)のタプルな点に注意。', ins: ['0 1\n', '0 3\n', '1 2\n', '-1 1\n', '0 10\n', '2 5\n'] })

t({ lv: 110, concept: 'scipy: 行列式(linalg.det)', title: '行列式をライブラリで', tags: ['scipy'], io: '1行目に n、続く n 行に n×n の整数行列が与えられます。', ask: '行列式を小数第1位まで出力してください。', h1: '余因子展開を自分で書かなくてよい。', h2: 'scipy.linalg.det(A)。', ref: 'from scipy import linalg\nn=int(input())\nA=[list(map(int,input().split())) for _ in range(n)]\nprint(f"{linalg.det(A):.1f}")', tip: 'LU分解経由の行列式は浮動小数なので「-0.0」や微小誤差が出うる。整数の厳密値が要るときは分数計算やmod計算に切り替える、の使い分けが肝要。', ins: ['2\n1 2\n3 4\n', '2\n2 0\n0 3\n', '3\n1 0 0\n0 1 0\n0 0 1\n', '2\n1 1\n1 1\n', '3\n2 0 1\n1 1 0\n0 3 1\n', '1\n7\n'] })

t({ lv: 110, concept: 'scipy: 最近点対の距離(pdist)', title: '一番近い2点をライブラリで', tags: ['scipy'], io: '1行目に点数 n、続く n 行に座標 x y が与えられます。', ask: '最も近い2点間の距離の2乗を整数で出力してください。', h1: '全ペアの距離行列を一撃で作れる。', h2: "scipy.spatial.distance.pdist(P, metric='sqeuclidean') の最小値。", ref: "from scipy.spatial.distance import pdist\nn=int(input())\nP=[list(map(int,input().split())) for _ in range(n)]\nd=pdist(P,metric='sqeuclidean')\nprint(int(round(d.min())))", tip: 'pdistは全ペア距離を密ベクトルで返す(n²/2個)。数千点まではこれで十分で、それ以上はKD木(scipy.spatial.cKDTree)へ、が実務の分水嶺。', ins: ['3\n0 0\n3 4\n1 1\n', '2\n0 0\n1 0\n', '4\n0 0\n10 0\n0 10\n1 1\n', '3\n5 5\n5 6\n9 9\n', '2\n-3 -4\n0 0\n', '3\n0 0\n2 0\n5 0\n'] })

t({ lv: 110, concept: 'scipy: 統計量の一括計算(describe)', title: 'データの顔つきを一目で', tags: ['scipy', '統計'], io: '整数列(2個以上)が1行で空白区切りで与えられます。', ask: 'scipy.stats.describe を使い、最小値・最大値・平均(小数2桁)を「min max mean」の順で空白区切りで出力してください。', h1: '基本統計量をまとめて返す関数がある。', h2: 'describe(a) の minmax と mean。', ref: 'from scipy import stats\na=list(map(int,input().split()))\nd=stats.describe(a)\nprint(int(d.minmax[0]),int(d.minmax[1]),f"{d.mean:.2f}")', tip: '名前つきタプルで統計量一式(分散・歪度・尖度まで)が返る。pandasの describe() と役割が同じで、EDAの最初の一手にあたる。', ins: ['1 2 3 4\n', '5 5\n', '10 0 5\n', '-1 1\n', '2 4 6 8\n', '7 7 7\n'] })

export const CATALOG = TASKS
