// 生成タスク 第81波：各レベル3問化フェーズ(8)。lv378〜426 の薄い49段に3問目を追加。
// 上級帯: フロー/幾何/ゲーム/数論/クエリ。クラスタ3問まで可・言い換え水増し禁止。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 378, concept: 'DP: 混ぜて作る方法の数', title: 'シャッフルの仕方は何通り', tags: ['DP', '文字列'], io: '1〜3行目に文字列 s, t, u が与えられます(uの長さはsとtの長さの和)。', ask: 's と t をそれぞれの文字順を保ったまま混ぜて u を作る方法の総数を出力してください。', h1: '作れるか(同レベル既出)の数え上げ版。', h2: 'dp[i][j] は sをi文字・tをj文字使って u の先頭 i+j 文字を作る方法の数。', ref: 's=input()\nt=input()\nu=input()\nm,n=len(s),len(t)\ndp=[[0]*(n+1) for _ in range(m+1)]\ndp[0][0]=1\nfor i in range(m+1):\n    for j in range(n+1):\n        if i<m and s[i]==u[i+j]:\n            dp[i+1][j]+=dp[i][j]\n        if j<n and t[j]==u[i+j]:\n            dp[i][j+1]+=dp[i][j]\nprint(dp[m][n])', tip: '判定DPのTrue/Falseを加算に替えると方法の数になる、3兄弟対応のインターリーブ版。同じ文字が両列にあると数が膨らむ、が数え上げならではの現象。', ins: ['ab\ncd\nacbd\n', 'aa\naa\naaaa\n', 'ab\nab\nabab\n', 'a\nb\nba\n', 'a\nb\nab\n', 'ab\ncd\nabcd\n'] })

t({ lv: 379, concept: 'グラフ: 1辺が支える三角形の最大数', title: '一番人気の辺', tags: ['グラフ'], io: '1行目に頂点数 n と辺数 m (m≥1)、続く m 行に無向辺 u v が与えられます。', ask: '1本の辺を含む三角形の個数として最大の値を出力してください。', h1: '辺(u,v)を含む三角形は u と v の共通の隣人の数。', h2: '隣接集合の積集合のサイズを全辺で取る。', ref: 'n,m=map(int,input().split())\nnb=[set() for _ in range(n+1)]\nes=[]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    nb[u].add(v)\n    nb[v].add(u)\n    es.append((u,v))\nprint(max(len(nb[u]&nb[v]) for u,v in es))', tip: '辺の「サポート」と呼ばれる量で、k-トラス分解(密なコミュニティ抽出)の基本部品。三角形の総数(既出)が辺ごとの内訳に分解された姿でもある。', ins: ['4 5\n1 2\n1 3\n2 3\n1 4\n2 4\n', '3 3\n1 2\n2 3\n1 3\n', '3 2\n1 2\n2 3\n', '5 6\n1 2\n1 3\n2 3\n3 4\n4 5\n3 5\n', '2 1\n1 2\n', '5 8\n1 2\n1 3\n1 4\n1 5\n2 3\n2 4\n2 5\n3 4\n'] })

t({ lv: 380, concept: '組合せ: 行の二項係数のGCD', title: '行に潜む共通の約数', tags: ['組合せ', '数論'], io: '2以上の整数 n が1行で与えられます。', ask: 'C(n,1), C(n,2), …, C(n,n−1) の最大公約数を出力してください。', h1: 'combとgcdを畳む。', h2: 'reduceかループで。', ref: 'from math import comb,gcd\nn=int(input())\ng=0\nfor k in range(1,n):\n    g=gcd(g,comb(n,k))\nprint(g)', tip: '答えは n が素数 p のべき乗 p^e なら p、そうでなければ 1、という美しい定理(クンマーの定理の帰結)。「素数 p なら C(p,k) は全て p の倍数」の一般化になっている。', ins: ['4\n', '7\n', '6\n', '9\n', '8\n', '5\n'] })

t({ lv: 381, concept: 'クエリ: 矩形領域の最大値', title: '長方形の中のチャンピオン', tags: ['クエリ', '行列'], io: '1行目に H W、続く H 行に行列、次に q、続く q 行に矩形 r1 c1 r2 c2 (1始まり、両端含む) が与えられます。', ask: '各矩形内の最大値を1行ずつ出力してください。', h1: '矩形和(既出)のmax版は累積和の引き算が使えない。', h2: 'この規模なら二重ループで素直に走査。', ref: 'h,w=map(int,input().split())\ng=[list(map(int,input().split())) for _ in range(h)]\nq=int(input())\nfor _ in range(q):\n    r1,c1,r2,c2=map(int,input().split())\n    print(max(max(g[i][c1-1:c2]) for i in range(r1-1,r2)))', tip: 'maxには逆元がないので2次元累積の差し引きが効かない、というのが和との本質的な違い。高速化にはスパーステーブルの2次元版や矩形分割が要る、その素朴な出発点。', ins: ['2 3\n1 5 2\n4 0 3\n2\n1 1 2 2\n1 3 2 3\n', '1 1\n7\n1\n1 1 1 1\n', '2 2\n1 2\n3 4\n1\n1 1 2 2\n', '3 3\n1 2 3\n4 5 6\n7 8 9\n2\n2 2 3 3\n1 1 1 3\n', '2 2\n-1 -5\n-3 -2\n1\n1 1 2 2\n', '1 4\n4 1 3 2\n2\n1 2 1 4\n1 1 1 1\n'] })

t({ lv: 382, concept: 'クエリ: 一点更新つき区間のGCD', title: '区間の公約数は更新に耐えるか', tags: ['クエリ', '数論'], io: '1行目に n q、2行目に長さ n の列、続く q 行に「U i x」(i番目をxに変更) か「Q l r」(区間のGCDを出力) が与えられます。', ask: '各 Q クエリに対して区間 [l, r] の最大公約数を1行ずつ出力してください。', h1: '更新つき区間最大(同レベル既出)の演算違い。', h2: 'gcdはmath.gcdをreduceで畳む。', ref: 'from math import gcd\nfrom functools import reduce\nn,q=map(int,input().split())\na=list(map(int,input().split()))\nfor _ in range(q):\n    parts=input().split()\n    if parts[0]=="U":\n        a[int(parts[1])-1]=int(parts[2])\n    else:\n        l,r=int(parts[1]),int(parts[2])\n        print(reduce(gcd,a[l-1:r]))', tip: 'gcdは結合的なのでセグメント木に載る演算の代表格。max・和・gcd と演算を差し替えても木の骨格が変わらない、という抽象化の入り口が素朴解の段階から見えている。', ins: ['3 3\n4 6 8\nQ 1 3\nU 2 3\nQ 1 3\n', '2 2\n10 15\nQ 1 2\nQ 1 1\n', '4 3\n12 18 24 8\nQ 1 3\nU 4 30\nQ 2 4\n', '1 3\n7\nQ 1 1\nU 1 9\nQ 1 1\n', '3 2\n5 10 20\nU 1 40\nQ 1 3\n', '2 1\n6 9\nQ 1 2\n'] })

t({ lv: 383, concept: '数え上げ: 2列またぎの逆転ペア数', title: '列をまたぐ追い越しの数', tags: ['数え上げ'], io: '1行目と2行目に整数列が与えられます。', ask: '1列目の要素 a と2列目の要素 b の組で a > b となるものの個数を出力してください。', h1: '転倒数(既出)の2列またぎ版。', h2: '総当たりが基準解。片方をソートして二分探索でも数えられる。', ref: 'a=list(map(int,input().split()))\nb=list(map(int,input().split()))\nprint(sum(1 for x in a for y in b if x>y))', tip: 'マージソートで転倒数を数えるとき、まさにこの「またぎペア」が併合のたびに加算される。分割統治の心臓部を単独の問題として取り出した形。', ins: ['3 1\n2 2\n', '1 2\n3 4\n', '5 5\n1 1\n', '1\n1\n', '4 2 6\n3 5\n', '2 2\n2 2\n'] })

t({ lv: 384, concept: 'リスト: 最長の谷型区間', title: '一番深く長い谷', tags: ['リスト'], io: '整数列が1行で空白区切りで与えられます。', ask: '厳密に減少してから厳密に増加する(両側とも1歩以上)連続区間の最長の長さを出力してください(存在しなければ 0)。', h1: '山型の最長区間(同レベル既出)の鏡像。', h2: '各点で「そこで終わる減少の長さ」と「そこから始まる増加の長さ」を求めて継ぐ。', ref: 'a=list(map(int,input().split()))\nn=len(a)\ndown=[1]*n\nfor i in range(1,n):\n    if a[i]<a[i-1]:\n        down[i]=down[i-1]+1\nup=[1]*n\nfor i in range(n-2,-1,-1):\n    if a[i]>a[i+1]:\n        up[i]=up[i+1]+1\nbest=0\nfor i in range(n):\n    if down[i]>=2 and up[i]>=2 and down[i]+up[i]-1>best:\n        best=down[i]+up[i]-1\nprint(best)', tip: '両方向の走査を谷底で継ぐ双方向DP。「両側とも1歩以上」の条件をdown≥2かつup≥2に翻訳するところが仕様読解の要点になる。', ins: ['5 3 1 4 6\n', '1 2 3\n', '3 1 2 0 5\n', '9 7 5\n', '5 1 5 1 5\n', '8 6 4 5 7 9 2 3\n'] })

t({ lv: 385, concept: 'シミュレーション: カーソル移動つき入力の結果', title: 'カーソルが動くエディタ', tags: ['シミュレーション', '文字列'], io: '英小文字と <(カーソルを左へ)、>(カーソルを右へ) からなる入力列が1行で与えられます。', ask: '空のテキストに対して入力を順に処理した(文字はカーソル位置に挿入)最終的なテキストを出力してください(端でのカーソル移動は無視)。', h1: 'テキストとカーソル位置を持って1文字ずつ処理。', h2: 'リストのinsertで素直に書ける。', ref: 's=input()\ntext=[]\npos=0\nfor c in s:\n    if c=="<":\n        if pos>0:\n            pos-=1\n    elif c==">":\n        if pos<len(text):\n            pos+=1\n    else:\n        text.insert(pos,c)\n        pos+=1\nprint("".join(text))', tip: 'バックスペース版(同レベル既出)より状態が1つ増えた(位置)エディタの模型。効率化するなら「カーソルの左右を2本のスタックで持つ」有名テクへ進化する。', ins: ['ab<c\n', 'abc\n', 'a<<b\n', 'ab>c\n', 'x<y<z\n', '<a>b\n'] })

t({ lv: 386, concept: 'グラフ: 最大の強連結成分のサイズ', title: '一番大きな相互到達のかたまり', tags: ['グラフ', 'DFS'], io: '1行目に頂点数 n と辺数 m、続く m 行に有向辺 u v が与えられます。', ask: '強連結成分(互いに行き来できる頂点のかたまり)のうち最大のものの頂点数を出力してください。', h1: '強連結成分の数(同レベル既出)のサイズ集計版。', h2: '各頂点から到達できる集合を求め、相互到達で同じ組にまとめる。', ref: 'n,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\nreach=[]\nfor s in range(n+1):\n    seen=[False]*(n+1)\n    if s>0:\n        seen[s]=True\n        st=[s]\n        while st:\n            x=st.pop()\n            for y in g[x]:\n                if not seen[y]:\n                    seen[y]=True\n                    st.append(y)\n    reach.append(seen)\nbest=0\nfor v in range(1,n+1):\n    size=sum(1 for u in range(1,n+1) if reach[v][u] and reach[u][v])\n    if size>best:\n        best=size\nprint(best)', tip: 'Webのリンク構造では最大SCCが「中核」で、そこから出る側と入る側で蝶ネクタイ型になる、という有名な観測がある。O(n²)の素朴解はTarjan法の検証台。', ins: ['3 3\n1 2\n2 3\n3 1\n', '2 1\n1 2\n', '4 4\n1 2\n2 1\n3 4\n4 3\n', '5 5\n1 2\n2 3\n3 1\n3 4\n4 5\n', '3 2\n1 2\n2 3\n', '6 7\n1 2\n2 3\n3 1\n4 5\n5 6\n6 4\n3 4\n'] })

t({ lv: 387, concept: '数論: 最大素因数の総和', title: '一番大きな素因数を集めて', tags: ['数論'], io: '2以上の整数 N が1行で与えられます。', ask: '2 から N までの各整数の最大素因数の総和を出力してください。', h1: '最小素因数の総和(同レベル既出)の鏡像。', h2: '試し割りで割り切った最後に残る素因数が最大。', ref: 'n=int(input())\ntotal=0\nfor x in range(2,n+1):\n    m=x\n    p=2\n    last=1\n    while p*p<=m:\n        while m%p==0:\n            last=p\n            m//=p\n        p+=1\n    if m>1:\n        last=m\n    total+=last\nprint(total)', tip: '最大素因数の平均的な大きさは n に比例する(係数はゴロム・ディクマン定数まわりの理論)。最小素因数がほぼ2や3で占められるのと対照的な、重い裾の分布。', ins: ['5\n', '2\n', '10\n', '3\n', '4\n', '6\n'] })

t({ lv: 388, concept: '数え上げ: 2人が隣り合わない並び方', title: 'けんか中の2人の席順', tags: ['数え上げ'], io: '2以上の整数 n が1行で与えられます。', ask: 'n 人を1列に並べるとき、特定の2人が隣り合わない並べ方の総数を出力してください。', h1: '全体から「隣り合う場合」を引く。', h2: '隣り合う場合は2人を1塊にして 2×(n−1)!。', ref: 'import math\nn=int(input())\nprint(math.factorial(n)-2*math.factorial(n-1))', tip: '補集合+塊(くくり出し)の合わせ技は順列の数え上げの二大定石。答えは (n−2)×(n−1)! と因数分解でき、検算の別ルートになる。', ins: ['3\n', '2\n', '4\n', '5\n', '6\n', '7\n'] })

t({ lv: 389, concept: 'バックトラック: ペア分けの総数', title: 'バディの組み方は何通り', tags: ['バックトラック'], io: '1行目に偶数の頂点数 n と辺数 m、続く m 行に無向辺 u v が与えられます。', ask: '全頂点を「辺で結ばれた2頂点のペア」に分け切る方法の総数を出力してください。', h1: '番号最小の未処理の頂点の相手を辺の中から試す。', h2: '相手を固定して再帰し、数を足し合わせる。', ref: 'n,m=map(int,input().split())\nadj=[set() for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    adj[u].add(v)\n    adj[v].add(u)\ndef f(rest):\n    if not rest:\n        return 1\n    i=min(rest)\n    total=0\n    for j in adj[i]:\n        if j in rest and j!=i:\n            total+=f(rest-{i,j})\n    return total\nprint(f(frozenset(range(1,n+1))))', tip: '完全マッチングの数え上げは一般グラフでは#P困難(パーマネント計算)で、多項式時間解法は知られていない。最小番号を固定する枝刈りが指数の底を(n−1)!!に抑える。', ins: ['2 1\n1 2\n', '4 6\n1 2\n1 3\n1 4\n2 3\n2 4\n3 4\n', '4 2\n1 2\n3 4\n', '4 3\n1 2\n1 3\n1 4\n', '4 4\n1 2\n2 3\n3 4\n4 1\n', '6 5\n1 2\n3 4\n5 6\n2 3\n4 5\n'] })

t({ lv: 390, concept: 'グラフ: フローの保存則の検算', title: 'その流れ、帳尻は合っているか', tags: ['グラフ'], io: '1行目に頂点数 n と辺数 m (源は頂点1、吸込みは頂点n)、続く m 行に「u v f」(uからvへ流量f)が与えられます。', ask: '源と吸込み以外の全ての頂点で流入量と流出量が等しい(保存則を満たす)なら yes、そうでなければ no を出力してください。', h1: '頂点ごとに入る量と出る量を集計する。', h2: '検査対象は 2〜n−1 の頂点だけ。', ref: 'n,m=map(int,input().split())\ninf=[0]*(n+1)\nout=[0]*(n+1)\nfor _ in range(m):\n    u,v,f=map(int,input().split())\n    out[u]+=f\n    inf[v]+=f\nprint("yes" if all(inf[v]==out[v] for v in range(2,n)) else "no")', tip: '最大流(同レベル既出)を求めるアルゴリズムの答えが正しいかは、この保存則と容量制約の2つで機械的に検証できる。「解くより検算は簡単」というNP的な非対称の好例。', ins: ['3 2\n1 2 5\n2 3 5\n', '3 2\n1 2 5\n2 3 4\n', '4 4\n1 2 3\n1 3 2\n2 4 3\n3 4 2\n', '4 3\n1 2 1\n2 3 1\n2 4 1\n', '2 1\n1 2 9\n', '5 6\n1 2 2\n1 3 3\n2 4 2\n3 4 1\n3 5 2\n4 5 3\n'] })

t({ lv: 391, concept: 'DP: 辞書順最小のLISの復元', title: '最長のうち一番つつましい増加列', tags: ['DP'], io: '整数列が1行で空白区切りで与えられます。', ask: '最長増加部分列(LIS)のうち、値の列として辞書順最小のものを空白区切りで出力してください。', h1: '各位置から始まるLISの長さを先に求める。', h2: '前から「残り長がまかなえる候補のうち最小の値(同値なら早い位置)」を選ぶ。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nf=[1]*n\nfor i in range(n-1,-1,-1):\n    for j in range(i+1,n):\n        if a[j]>a[i] and f[j]+1>f[i]:\n            f[i]=f[j]+1\nL=max(f)\nres=[]\nprev=-1\nlast=None\nneed=L\nwhile need>0:\n    best=-1\n    for i in range(prev+1,n):\n        if f[i]==need and (last is None or a[i]>last):\n            if best<0 or a[i]<a[best]:\n                best=i\n    res.append(a[best])\n    prev=best\n    last=a[best]\n    need-=1\nprint(" ".join(map(str,res)))', tip: '「後ろ向きに長さを前計算 → 前向きに貪欲で復元」はLCS復元(既出)と同じ設計。長さの配列fが「この先どれだけ伸ばせるか」の保証書として機能する。', ins: ['3 1 2\n', '1 3 2\n', '5 4 3\n', '2 1 4 3\n', '1 2 3\n', '3 1 4 1 5\n'] })

t({ lv: 392, concept: 'DP: 割り切りでつながる最長の部分列', title: '割り切れる者だけの鎖', tags: ['DP', '数論'], io: '正整数の列が1行で空白区切りで与えられます。', ask: 'ソートしてから選んだとき、隣り合うどの2つも「後の数が前の数で割り切れる」ように選べる最長の個数を出力してください。', h1: 'ソートすればLISと同じ形になる。', h2: 'dp[i] は a[i] で終わる鎖の最長。a[i]%a[j]==0 の j から伸ばす。', ref: 'a=sorted(map(int,input().split()))\nn=len(a)\ndp=[1]*n\nfor i in range(n):\n    for j in range(i):\n        if a[i]%a[j]==0 and dp[j]+1>dp[i]:\n            dp[i]=dp[j]+1\nprint(max(dp))', tip: '整除関係は推移的(a|b, b|c → a|c)なので「隣どうし」の条件だけで鎖全体が整合する。半順序の最長チェーン問題としてLISの親戚にあたる。', ins: ['1 2 4 8\n', '2 3 6\n', '3 5 7\n', '1 3 9 27 4\n', '2 4 6 12\n', '5\n'] })

t({ lv: 393, concept: 'DP: 和をTにする最小の個数', title: '最少の人数で目標額を作る', tags: ['DP'], io: '1行目に目標 T、2行目に正整数の列(和をTにする選び方が存在)が与えられます。', ask: '各要素を高々1回使って和をちょうど T にするときの、使う要素数の最小を出力してください。', h1: '数える版(同レベル既出)の最適化版。', h2: 'dp[s] は和sを作る最小個数。0/1制約なので逆順ループ。', ref: 'T=int(input())\na=list(map(int,input().split()))\nINF=10**9\ndp=[INF]*(T+1)\ndp[0]=0\nfor x in a:\n    for s in range(T,x-1,-1):\n        if dp[s-x]+1<dp[s]:\n            dp[s]=dp[s-x]+1\nprint(dp[T])', tip: '硬貨の最小枚数(無限に使える)と違い、各要素1回の制約は「逆順ループ」の1点だけでDPに現れる。順ループに変えた瞬間、同じ要素の使い回しが混入する。', ins: ['6\n1 2 3 4\n', '5\n5 1 4\n', '7\n3 3 1\n', '10\n5 5 5\n', '1\n1 1\n', '9\n4 5 2\n'] })

t({ lv: 394, concept: 'BFS: 2つの水差しで目標の量', title: '水差しパズルの最短手数', tags: ['BFS'], io: 'a b t が空白区切りで1行で与えられます(容量aとbの水差し、目標t。達成可能な入力のみ)。', ask: '「満たす」「空にする」「片方からもう片方へ移す」を1操作として、どちらかの水差しにちょうど t を作る最小操作回数を出力してください。', h1: '状態は(水差しAの量, Bの量)の組。', h2: '6種類の操作でBFS。', ref: 'from collections import deque\na,b,t=map(int,input().split())\nseen={(0,0)}\nq=deque([(0,0,0)])\nwhile True:\n    x,y,d=q.popleft()\n    if x==t or y==t:\n        print(d)\n        break\n    for nx,ny in ((a,y),(x,b),(0,y),(x,0),(max(0,x-(b-y)),min(b,y+x)),(min(a,x+y),max(0,y-(a-x)))):\n        if (nx,ny) not in seen:\n            seen.add((nx,ny))\n            q.append((nx,ny,d+1))', tip: '映画ダイ・ハード3の「4ガロンを作れ」で有名な問題。到達できる量が gcd(a,b) の倍数に限られることはベズーの等式そのもので、パズルと数論が直結する。', ins: ['4 3 2\n', '2 6 4\n', '5 3 4\n', '1 1 1\n', '8 3 5\n', '9 6 3\n'] })

t({ lv: 395, concept: 'DP: ちょうどk個の塊に分けた最大値の和の最小', title: 'k班に分けて代表の合計を抑える', tags: ['DP'], io: '1行目に k、2行目に整数列(長さはk以上)が与えられます。', ask: '列を連続した k 個の空でない塊に分け、各塊の最大値の合計を最小にした値を出力してください。', h1: '長さ制限つき分割(同レベル既出)の「個数指定」版。', h2: 'dp[i][j] = 先頭i要素をj塊に分ける最小。最後の塊の開始位置を全部試す。', ref: 'k=int(input())\na=list(map(int,input().split()))\nn=len(a)\nINF=10**9\ndp=[[INF]*(k+1) for _ in range(n+1)]\ndp[0][0]=0\nfor i in range(1,n+1):\n    for j in range(1,k+1):\n        mx=0\n        for s in range(i-1,j-2,-1):\n            if a[s]>mx:\n                mx=a[s]\n            if dp[s][j-1]+mx<dp[i][j]:\n                dp[i][j]=dp[s][j-1]+mx\nprint(dp[n][k])', tip: '「最後の塊をどこから始めるか」を総当たりしながら塊内の最大を後ろ向きに更新すると、maxの再計算がループに溶けて1段速くなる。区間分割DPの定番の書き味。', ins: ['2\n1 3 2\n', '1\n5 1\n', '3\n1 2 3\n', '2\n4 4\n', '2\n5 1 1 5\n', '3\n2 9 3 5\n'] })

t({ lv: 396, concept: '整数: 全ての桁が奇数の数の個数', title: '奇数の桁しか持たない数', tags: ['整数'], io: '正整数 N が1行で与えられます。', ask: '1 以上 N 以下で、十進の全ての桁が奇数(1,3,5,7,9)である数の個数を出力してください。', h1: '桁を文字で調べる。', h2: 'all(c in "13579")。', ref: 'n=int(input())\nprint(sum(1 for x in range(1,n+1) if all(c in "13579" for c in str(x))))', tip: 'd桁の該当数はちょうど 5^d 個、と組合せで数えれば巨大なNにも即答できる。総当たりと公式の答え合わせは桁DPへの入り口として最良の練習。', ins: ['20\n', '9\n', '100\n', '35\n', '1\n', '60\n'] })

t({ lv: 397, concept: '貪欲: 大きい順の詰め込みで必要な箱数', title: '大物から順に箱詰め', tags: ['貪欲'], io: '1行目に箱の容量 C、2行目に品物の大きさの列(各値はC以下)が与えられます。', ask: '品物を大きい順に並べ、順に「入る最初の箱」(なければ新しい箱)に入れていくとき、使う箱の個数を出力してください。', h1: '指定どおりのシミュレーション。', h2: '各箱の残り容量のリストを走査する。', ref: 'C=int(input())\nitems=sorted(map(int,input().split()),reverse=True)\nboxes=[]\nfor x in items:\n    for i in range(len(boxes)):\n        if boxes[i]+x<=C:\n            boxes[i]+=x\n            break\n    else:\n        boxes.append(x)\nprint(len(boxes))', tip: 'ビンパッキングはNP困難だが、この first-fit decreasing は最適の11/9倍+定数に収まる保証つきの名ヒューリスティック。for-elseの else が「入る箱がなかった」を綺麗に表す。', ins: ['10\n5 4 3 7\n', '10\n6 6 6\n', '5\n5 5\n', '10\n1 2 3 4\n', '8\n4 4 4 4\n', '7\n5 3 3 2\n'] })

t({ lv: 398, concept: '貪欲: 重みつき完了時刻の総和の最小', title: '大事な仕事ほど待たせない', tags: ['貪欲', 'ソート'], io: '1行目に仕事数 n、続く n 行に「所要時間 重み」が与えられます(所要/重みの比は全て相異なります)。', ask: '1台の機械で順に処理するとき、Σ(重み×完了時刻) の最小値を出力してください。', h1: '完了時刻の総和最小(既出)の重みつき一般化。', h2: '所要時間÷重みが小さい順(スミスの規則)。比較は分数で厳密に。', ref: 'from fractions import Fraction\nn=int(input())\njobs=[tuple(map(int,input().split())) for _ in range(n)]\njobs.sort(key=lambda tw:Fraction(tw[0],tw[1]))\ntime=0\ntotal=0\nfor t,w in jobs:\n    time+=t\n    total+=w*time\nprint(total)', tip: '隣り合う2仕事の交換で得か損かを比べると t1/w1 < t2/w2 の順が最適と示せる(交換論法)。浮動小数の比でソートすると同率で壊れるのでFractionで厳密に。', ins: ['2\n3 1\n1 1\n', '2\n2 1\n1 3\n', '1\n5 2\n', '3\n2 1\n1 2\n4 1\n', '2\n5 2\n5 1\n', '3\n1 4\n3 1\n2 2\n'] })

t({ lv: 399, concept: 'bit演算: 部分集合XORの種類数', title: 'XORで作れる値は何種類', tags: ['bit演算'], io: '正整数の列が1行で空白区切りで与えられます。', ask: '部分集合(空集合も含む、空はXOR 0)のXORとして作れる値の種類数を出力してください。', h1: '最大XOR(同レベル既出)で作った線形基底が使える。', h2: '基底の本数(ランク)を r として 2^r 種類。', ref: 'a=list(map(int,input().split()))\nbasis=[]\nfor x in a:\n    for b in basis:\n        x=min(x,x^b)\n    if x:\n        basis.append(x)\n        basis.sort(reverse=True)\nprint(2**len(basis))', tip: 'XORで作れる集合はGF(2)上の線形空間なので、種類数は必ず2のべき乗。ORで作れる種類数(既出)が不規則なのと対照的で、演算の代数構造が答えの形を決めている。', ins: ['1 2\n', '1 1\n', '5\n', '1 2 3\n', '7 7 7\n', '1 2 4\n'] })

t({ lv: 400, concept: '文字列: 他の単語に含まれる単語の数', title: 'よその単語に居候する単語', tags: ['文字列'], io: '単語が空白区切りで1行に与えられます。', ask: '自分以外のいずれかの単語の連続部分文字列になっている単語の個数を出力してください。', h1: '接頭辞ペア(同レベル既出)の条件を部分文字列に広げる。', h2: 'in演算子の総当たり。', ref: 'ws=input().split()\nn=len(ws)\nprint(sum(1 for i in range(n) if any(i!=j and ws[i] in ws[j] for j in range(n))))', tip: '同じ単語が2回あればお互いに含まれる、という自明ケースの扱いが仕様の隅。実務では冗長なキーワードの間引き(部分文字列除去)としてよく書く処理。', ins: ['a ab abc\n', 'cat dog\n', 'x xx xxx\n', 'ab ba aba\n', 'same same\n', 'hello ell he lo\n'] })

t({ lv: 401, concept: 'クエリ: 区間加算と一点の値', title: '積み重なる加算の一点を覗く', tags: ['クエリ'], io: '1行目に n q、2行目に長さ n の初期列、続く q 行に「A l r x」(区間[l,r]にxを加算) か「Q i」(i番目の値を出力) が与えられます。', ask: '各 Q クエリに対して現在の i 番目の値を1行ずつ出力してください。', h1: '素直に区間へ足し込むのが基準解。', h2: '高速化するなら差分配列(いもす)を遅延で保つ。', ref: 'n,q=map(int,input().split())\na=list(map(int,input().split()))\nfor _ in range(q):\n    parts=input().split()\n    if parts[0]=="A":\n        l,r,x=int(parts[1]),int(parts[2]),int(parts[3])\n        for i in range(l-1,r):\n            a[i]+=x\n    else:\n        print(a[int(parts[1])-1])', tip: '「まとめて一括処理」のいもす法(既出)と違い、質問が途中に挟まると差分の畳み込みを遅延させる工夫が要る。BITの区間加算・一点取得はこの問題の高速版。', ins: ['3 3\n1 1 1\nA 1 2 5\nQ 1\nQ 3\n', '2 2\n0 0\nA 1 2 3\nQ 2\n', '4 4\n1 2 3 4\nA 2 4 10\nQ 3\nA 1 1 1\nQ 1\n', '1 3\n5\nQ 1\nA 1 1 5\nQ 1\n', '5 2\n1 1 1 1 1\nA 1 5 2\nQ 5\n', '3 3\n2 4 6\nQ 2\nA 2 3 1\nQ 2\n'] })

t({ lv: 402, concept: 'リスト: 含まれない最小の非負整数', title: '空いている一番小さな番号', tags: ['リスト', 'ハッシュ'], io: '非負整数の列が1行で空白区切りで与えられます。', ask: '列に含まれない最小の非負整数(mex)を出力してください。', h1: '0から順に「あるか」を確かめる。', h2: '集合に入れれば各判定がO(1)。', ref: 's=set(map(int,input().split()))\nx=0\nwhile x in s:\n    x+=1\nprint(x)', tip: 'mexはゲーム理論のGrundy数の定義に現れる中核演算。答えは高々n(要素数)なので、whileが暴走しない上限保証つきのループになっている。', ins: ['0 1 3\n', '1 2\n', '0 0 1\n', '5\n', '0 1 2 3\n', '2 0 1 4\n'] })

t({ lv: 403, concept: 'クエリ: 区間の中央値', title: '区間の真ん中の値', tags: ['クエリ'], io: '1行目に n q、2行目に長さ n の列、続く q 行に奇数長の区間 l r が与えられます。', ask: '各区間の中央値を1行ずつ出力してください。', h1: '切り出してソートするのが基準解。', h2: 'sorted(a[l−1:r])[長さ//2]。', ref: 'n,q=map(int,input().split())\na=list(map(int,input().split()))\nfor _ in range(q):\n    l,r=map(int,input().split())\n    b=sorted(a[l-1:r])\n    print(b[len(b)//2])', tip: '区間中央値は「マージソート木+二分探索」やウェーブレット木が本命の難しめクエリ。素朴解O(q·n log n)を正解の基準に置いてから挑むのが常道。', ins: ['5 2\n3 1 4 1 5\n1 3\n1 5\n', '3 1\n9 2 7\n1 3\n', '1 1\n4\n1 1\n', '5 1\n1 2 3 4 5\n2 4\n', '7 2\n5 5 5 1 1 1 9\n1 7\n3 5\n', '4 1\n8 6 4 2\n2 4\n'] })

t({ lv: 404, concept: '幾何: 多角形の周の長さ', title: '外周をぐるりと測る', tags: ['幾何'], io: '1行目に頂点数 n、続く n 行に多角形の頂点座標 x y (順回り) が与えられます。', ask: '多角形の周の長さを小数第2位まで出力してください。', h1: '隣り合う頂点間の距離の和。最後は先頭に戻る。', h2: 'math.dist か sqrt((dx)²+(dy)²)。', ref: 'import math\nn=int(input())\npts=[tuple(map(int,input().split())) for _ in range(n)]\ntotal=0.0\nfor i in range(n):\n    x1,y1=pts[i]\n    x2,y2=pts[(i+1)%n]\n    total+=math.hypot(x2-x1,y2-y1)\nprint(f"{total:.2f}")', tip: '面積(同レベル既出)は外積の和で整数のまま計算できたが、周長は平方根が避けられず初めて浮動小数が要る。(i+1)%n の巡回インデックスは多角形処理の定番イディオム。', ins: ['3\n0 0\n3 0\n0 4\n', '4\n0 0\n1 0\n1 1\n0 1\n', '3\n0 0\n1 0\n0 1\n', '4\n0 0\n2 0\n2 2\n0 2\n', '3\n0 0\n6 8\n6 0\n', '5\n0 0\n2 0\n3 1\n1 3\n0 2\n'] })

t({ lv: 405, concept: '幾何: 2つの長方形が重なるか', title: '長方形どうしの縄張り争い', tags: ['幾何'], io: '1行目と2行目に軸に平行な長方形が「x1 y1 x2 y2」(左下と右上、x1<x2, y1<y2) で与えられます。', ask: '2つの長方形が正の面積で重なるなら yes、そうでなければ no を出力してください(辺や点で接するだけは no)。', h1: '重ならない条件(完全に左・右・上・下)の否定が簡単。', h2: 'x方向とy方向それぞれで区間が正の長さで交わるか。', ref: 'a=list(map(int,input().split()))\nb=list(map(int,input().split()))\nok=max(a[0],b[0])<min(a[2],b[2]) and max(a[1],b[1])<min(a[3],b[3])\nprint("yes" if ok else "no")', tip: '2次元の重なりは各軸の1次元区間の重なりのANDに分解できる(軸平行の特権)。当たり判定の最速コードがこの4比較で、ゲーム開発では毎フレーム走る式。', ins: ['0 0 2 2\n1 1 3 3\n', '0 0 1 1\n1 0 2 1\n', '0 0 5 5\n1 1 2 2\n', '0 0 1 1\n2 2 3 3\n', '0 0 3 1\n1 -1 2 4\n', '-2 -2 0 0\n-1 -1 1 1\n'] })

t({ lv: 406, concept: '幾何: 重心に最も近い点の番号', title: '群れの中心にいるのは誰', tags: ['幾何'], io: '1行目に点の数 n、続く n 行に座標 x y が与えられます。', ask: '点集合の重心(座標の平均)に最も近い点の番号(1始まり、同距離なら最小)を出力してください。', h1: '平均を分数のまま扱うと誤差が出ない。', h2: '各点との距離は (n·x−Σx)²+(n·y−Σy)² で比べれば整数だけで済む。', ref: 'n=int(input())\npts=[tuple(map(int,input().split())) for _ in range(n)]\nsx=sum(p[0] for p in pts)\nsy=sum(p[1] for p in pts)\nbest=-1\nbd=None\nfor i,(x,y) in enumerate(pts):\n    d=(n*x-sx)**2+(n*y-sy)**2\n    if bd is None or d<bd:\n        bd=d\n        best=i\nprint(best+1)', tip: '重心との比較を「n倍の座標系」で行えば割り算も小数も不要になる。クラスタリングで各クラスタの代表点(メドイド)を選ぶ操作の1クラスタ版にあたる。', ins: ['3\n0 0\n3 0\n0 3\n', '1\n5 5\n', '2\n0 0\n2 2\n', '4\n0 0\n4 0\n0 4\n4 4\n', '3\n1 1\n5 1\n3 4\n', '5\n0 0\n10 0\n5 5\n0 10\n10 10\n'] })

t({ lv: 407, concept: '幾何: 交差する線分のペア数', title: '交わる線分は何組', tags: ['幾何'], io: '1行目に線分の数 n、続く n 行に線分「x1 y1 x2 y2」が与えられます。', ask: '共有点を持つ(端点で触れる場合や重なる場合も含む)線分のペア(i<j)の個数を出力してください。', h1: '2線分の交差判定(同レベル既出)を全ペアに適用。', h2: '向き(符号つき面積)4つと、一直線上の場合の範囲チェック。', ref: 'def sgn(x):\n    return (x>0)-(x<0)\ndef cross(o,a,b):\n    return (a[0]-o[0])*(b[1]-o[1])-(a[1]-o[1])*(b[0]-o[0])\ndef onseg(a,b,p):\n    return min(a[0],b[0])<=p[0]<=max(a[0],b[0]) and min(a[1],b[1])<=p[1]<=max(a[1],b[1])\ndef inter(p1,p2,p3,p4):\n    d1=sgn(cross(p3,p4,p1))\n    d2=sgn(cross(p3,p4,p2))\n    d3=sgn(cross(p1,p2,p3))\n    d4=sgn(cross(p1,p2,p4))\n    if d1*d2<0 and d3*d4<0:\n        return True\n    if d1==0 and onseg(p3,p4,p1):\n        return True\n    if d2==0 and onseg(p3,p4,p2):\n        return True\n    if d3==0 and onseg(p1,p2,p3):\n        return True\n    if d4==0 and onseg(p1,p2,p4):\n        return True\n    return False\nn=int(input())\nsegs=[]\nfor _ in range(n):\n    x1,y1,x2,y2=map(int,input().split())\n    segs.append(((x1,y1),(x2,y2)))\ncnt=0\nfor i in range(n):\n    for j in range(i+1,n):\n        if inter(segs[i][0],segs[i][1],segs[j][0],segs[j][1]):\n            cnt+=1\nprint(cnt)', tip: '全ペアO(n²)の先には走査線+平衡木のO(n log n)交差検出がある。端点接触・一直線の縮退ケースを漏らさない判定関数を一度書けば、一生の資産になる。', ins: ['2\n0 0 2 2\n0 2 2 0\n', '2\n0 0 1 1\n2 2 3 3\n', '3\n0 0 4 0\n1 -1 1 1\n3 -1 3 1\n', '2\n0 0 2 0\n1 0 3 0\n', '2\n0 0 1 0\n1 0 2 0\n', '3\n0 0 1 1\n0 1 1 0\n5 5 6 6\n'] })

t({ lv: 408, concept: '幾何: 多角形が凸か', title: 'へこみのない形か', tags: ['幾何'], io: '1行目に頂点数 n (n≥3)、続く n 行に多角形の頂点座標が順回りで与えられます(自己交差なし)。', ask: '多角形が凸(全ての内角が180度以下)なら yes、そうでなければ no を出力してください。', h1: '連続する3頂点の曲がり方(既出)を全周で調べる。', h2: '外積の符号が正と負の両方現れたら凸でない。', ref: 'n=int(input())\npts=[tuple(map(int,input().split())) for _ in range(n)]\npos=False\nneg=False\nfor i in range(n):\n    o=pts[i]\n    a=pts[(i+1)%n]\n    b=pts[(i+2)%n]\n    c=(a[0]-o[0])*(b[1]-a[1])-(a[1]-o[1])*(b[0]-a[0])\n    if c>0:\n        pos=True\n    if c<0:\n        neg=True\nprint("no" if (pos and neg) else "yes")', tip: '凸性は「曲がる向きが一貫している」ことの言い換えで、外積の符号が全周で混ざらないかに帰着する。凸なら点の内外判定も二分探索でO(log n)になる、性質の配当が大きい判定。', ins: ['4\n0 0\n2 0\n2 2\n0 2\n', '4\n0 0\n2 0\n1 1\n2 2\n', '3\n0 0\n1 0\n0 1\n', '5\n0 0\n2 0\n2 2\n1 1\n0 2\n', '4\n0 0\n1 0\n2 0\n1 1\n', '6\n0 0\n2 0\n3 1\n2 2\n0 2\n-1 1\n'] })

t({ lv: 409, concept: '組合せ: 指定の点を通る格子経路の数', title: '検問所を通るルート', tags: ['組合せ'], io: '1行目に目的地 W H、2行目に経由点 a b (0≤a≤W, 0≤b≤H) が与えられます。', ask: '(0,0) から右か上に1ずつ進んで (W,H) へ行く経路のうち、(a,b) を通るものの数を出力してください。', h1: '経由点で旅を2つに分ける。', h2: '前半の経路数×後半の経路数。', ref: 'from math import comb\nw,h=map(int,input().split())\na,b=map(int,input().split())\nprint(comb(a+b,a)*comb(w-a+h-b,w-a))', tip: '「途中でここを通る」は積の法則で2区間に分解するのが定石。通らない経路数なら全体から引く補集合で、包除原理の最初の一歩がこの設定から始まる。', ins: ['2 2\n1 1\n', '3 3\n1 1\n', '2 1\n1 0\n', '5 5\n0 0\n', '4 2\n2 1\n', '3 2\n3 2\n'] })

t({ lv: 410, concept: '幾何: 軸に平行な長方形の総数', title: '格子から選べる長方形', tags: ['幾何', '組合せ'], io: 'W H が空白区切りで1行で与えられます(格子は (W+1)×(H+1) 個の点)。', ask: '格子点を頂点とし辺が軸に平行な長方形(正方形も含む)の総数を出力してください。', h1: '縦線2本と横線2本を選べば長方形が1つ決まる。', h2: 'C(W+1,2)×C(H+1,2)。', ref: 'from math import comb\nw,h=map(int,input().split())\nprint(comb(w+1,2)*comb(h+1,2))', tip: '図形の数え上げが「線の選び方」の積に化ける代表例。正方形の総数(同レベル既出)が幅の揃った選び方の和になるのと比べると、制約が消えると式も簡単になると分かる。', ins: ['2 2\n', '1 1\n', '3 1\n', '2 3\n', '4 4\n', '1 5\n'] })

t({ lv: 411, concept: '数論: 相異なる素因数の数の最大', title: '一番よくばりな数', tags: ['数論'], io: '正整数 N が1行で与えられます。', ask: '1 から N までの整数の中での「相異なる素因数の個数」の最大値を出力してください(1は0個)。', h1: 'ωの総和(同レベル既出)のmax版。', h2: '試し割りで種類を数える。', ref: 'n=int(input())\nbest=0\nfor x in range(2,n+1):\n    m=x\n    c=0\n    p=2\n    while p*p<=m:\n        if m%p==0:\n            c+=1\n            while m%p==0:\n                m//=p\n        p+=1\n    if m>1:\n        c+=1\n    if c>best:\n        best=c\nprint(best)', tip: '最大を実現するのは素数階乗(2·3·5·7…)で、2, 6, 30, 210, 2310 が階段の踏み板になる。ωの最大は log N / log log N 程度でしか育たない、意外に遅い成長。', ins: ['10\n', '5\n', '30\n', '1\n', '29\n', '210\n'] })

t({ lv: 412, concept: '数論: 分数への左右の道順', title: '分数の木をたどる道', tags: ['数論'], io: '互いに素な正整数 p q が空白区切りで1行で与えられます。', ask: 'シュテルン=ブロコ木で 1/1 から p/q に至る道を、大きい方へ進むとき R、小さい方へ進むとき L として文字列で出力してください(p/q が 1/1 なら - を出力)。手順は「p>q なら R を出力して p から q を引く、p<q なら L を出力して q から p を引く」を 1/1 になるまで繰り返すことと同じです。', h1: '互除法の引き算版をなぞる。', h2: 'p>q なら R、p<q なら L。', ref: 'p,q=map(int,input().split())\nres=[]\nwhile p!=q:\n    if p>q:\n        res.append("R")\n        p-=q\n    else:\n        res.append("L")\n        q-=p\nprint("".join(res) if res else "-")', tip: '全ての既約分数がこの木にちょうど1回現れ、道順の文字列が分数の「住所」になる。連分数展開(同レベル既出)のRとLの連の長さが商の列、という美しい対応がある。', ins: ['2 5\n', '1 1\n', '3 2\n', '1 2\n', '5 2\n', '3 4\n'] })

t({ lv: 413, concept: '木: 道の上の最小の辺の重み', title: '道中で一番細い橋', tags: ['木'], io: '1行目に頂点数 n、続く n−1 行に重みつきの辺 u v w、最終行に2頂点 s t が与えられます。', ask: 's から t への(木ではただ1つの)道に含まれる辺の重みの最小を出力してください。', h1: 'パス上の最大辺(既出)の鏡像。', h2: 'DFSで道を見つけながら最小を運ぶ。', ref: 'import sys\nsys.setrecursionlimit(100000)\nn=int(input())\ng=[[] for _ in range(n+1)]\nfor _ in range(n-1):\n    u,v,w=map(int,input().split())\n    g[u].append((v,w))\n    g[v].append((u,w))\ns,t=map(int,input().split())\nans=None\ndef dfs(v,par,mn):\n    global ans\n    if v==t:\n        ans=mn\n        return True\n    for to,w in g[v]:\n        if to!=par:\n            if dfs(to,v,w if mn is None or w<mn else mn):\n                return True\n    return False\ndfs(s,0,None)\nprint(ans)', tip: '木では2点間の道が一意なので「経路上の集計」が探索1回で決まる。最小辺は輸送路の隘路(ボトルネック)で、最大流の直感を木で先取りする量になっている。', ins: ['3\n1 2 5\n2 3 3\n1 3\n', '2\n1 2 7\n1 2\n', '4\n1 2 1\n2 3 9\n2 4 4\n3 4\n', '5\n1 2 2\n1 3 8\n3 4 1\n3 5 6\n4 5\n', '3\n1 2 10\n1 3 20\n2 3\n', '4\n1 2 3\n1 3 3\n1 4 3\n2 4\n'] })

t({ lv: 414, concept: '木: 最も使われる辺の通過ペア数', title: '交通量の一番多い橋', tags: ['木'], io: '1行目に頂点数 n、続く n−1 行に辺 u v が与えられます。', ask: '各辺について「その辺を通る頂点対の数」(辺を除いたときの両側の頂点数の積)を考え、その最大値を出力してください。', h1: '辺を消すと木は2つに割れる。', h2: '片側のサイズ s が分かれば積は s×(n−s)。部分木サイズで求まる。', ref: 'import sys\nsys.setrecursionlimit(100000)\nn=int(input())\ng=[[] for _ in range(n+1)]\nfor _ in range(n-1):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\nsize=[0]*(n+1)\ndef dfs(v,par):\n    size[v]=1\n    for to in g[v]:\n        if to!=par:\n            dfs(to,v)\n            size[v]+=size[to]\ndfs(1,0)\nprint(max(size[v]*(n-size[v]) for v in range(2,n+1)))', tip: '辺の「媒介中心性」の木版で、真ん中に近い辺ほど積が大きい。全頂点対距離の総和(既出)はこの積を全辺で足したものに等しい、という分解が背後で繋がっている。', ins: ['4\n1 2\n2 3\n2 4\n', '2\n1 2\n', '4\n1 2\n2 3\n3 4\n', '5\n1 2\n1 3\n1 4\n1 5\n', '6\n1 2\n2 3\n3 4\n4 5\n5 6\n', '7\n1 2\n2 3\n2 4\n4 5\n4 6\n4 7\n'] })

t({ lv: 415, concept: '関数グラフ: 一番人気の行き先', title: 'みんなが向かう場所', tags: ['関数グラフ'], io: '各頂点 i の行き先 f(i) を並べた列が1行で空白区切りで与えられます(頂点は1〜n)。', ask: '最も多くの頂点から行き先として指されている頂点を出力してください(同数なら最小の番号)。', h1: '行き先の列をそのまま集計する。', h2: 'Counterで(−回数, 番号)の最小。', ref: 'from collections import Counter\nc=Counter(map(int,input().split()))\nprint(min(c.items(),key=lambda kv:(-kv[1],kv[0]))[0])', tip: '関数グラフの入次数の最大は、リンク構造なら「最も参照されるページ」。全頂点の出次数が1に固定されているぶん、入次数の偏りが構造の個性になる。', ins: ['2 3 1\n', '1 1 1\n', '2 1 2\n', '3 3 3 1\n', '2 2 2 2\n', '5 4 3 2 1\n'] })

t({ lv: 416, concept: '幾何: マンハッタン距離の最小ペア', title: '碁盤の目で一番近い2人', tags: ['幾何'], io: '1行目に点の数 n (n≥2)、続く n 行に座標 x y が与えられます。', ask: '最も近い2点のマンハッタン距離(座標差の絶対値の和)を出力してください。', h1: '最大ペア(同レベル既出)の鏡像。', h2: '総当たりで |dx|+|dy| の最小。', ref: 'n=int(input())\npts=[tuple(map(int,input().split())) for _ in range(n)]\nbest=None\nfor i in range(n):\n    for j in range(i+1,n):\n        d=abs(pts[i][0]-pts[j][0])+abs(pts[i][1]-pts[j][1])\n        if best is None or d<best:\n            best=d\nprint(best)', tip: '最大は45度回転(チェビシェフ化)で座標独立に潰せたが、最小には効かず本質的に難しい。距離の種類で難易度の景色が変わる、幾何の面白い非対称。', ins: ['3\n0 0\n2 3\n1 1\n', '2\n0 0\n5 5\n', '4\n1 1\n4 4\n1 2\n9 9\n', '2\n-3 0\n3 0\n', '3\n0 0\n0 7\n7 0\n', '5\n2 2\n3 3\n5 5\n8 8\n2 3\n'] })

t({ lv: 417, concept: 'グラフ: 消すと誰かが孤立する頂点の数', title: '命綱になっている頂点', tags: ['グラフ'], io: '1行目に頂点数 n と辺数 m、続く m 行に無向辺 u v が与えられます(多重辺なし)。', ask: '「その頂点を取り除くと、隣人だった誰かが孤立点になってしまう」頂点の個数を出力してください。', h1: '次数1の頂点の唯一の隣人が該当。', h2: '次数1の頂点それぞれの隣人を集合に集める。', ref: 'n,m=map(int,input().split())\nnb=[set() for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    nb[u].add(v)\n    nb[v].add(u)\ncrit=set()\nfor v in range(1,n+1):\n    if len(nb[v])==1:\n        crit.add(next(iter(nb[v])))\nprint(len(crit))', tip: '関節点(同レベル既出)の判定条件の中でも最も単純な「葉の親」パターンだけを抜き出した量。ネットワークで末端ユーザーを支える唯一の接続点、という現実的な意味を持つ。', ins: ['3 2\n1 2\n2 3\n', '2 1\n1 2\n', '4 3\n1 2\n1 3\n1 4\n', '3 3\n1 2\n2 3\n1 3\n', '5 4\n1 2\n2 3\n3 4\n4 5\n', '4 2\n1 2\n3 4\n'] })

t({ lv: 418, concept: 'グラフ: s-tを分ける頂点の数', title: '通らざるを得ない中継地', tags: ['グラフ'], io: '1行目に頂点数 n と辺数 m、続く m 行に無向辺 u v が与えられます(頂点1と頂点nは連結)。', ask: '取り除くと頂点1から頂点nへ到達できなくなる頂点(1とn自身は除く)の個数を出力してください。', h1: 's-t切断辺(同レベル既出)の頂点版。', h2: '各頂点を除いた到達可能性を試す。', ref: 'n,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\ndef ok(banned):\n    seen=[False]*(n+1)\n    seen[1]=True\n    st=[1]\n    while st:\n        x=st.pop()\n        for y in g[x]:\n            if y!=banned and not seen[y]:\n                seen[y]=True\n                st.append(y)\n    return seen[n]\nprint(sum(1 for v in range(2,n) if not ok(v)))', tip: 'メンガーの定理により、この頂点が0個なら頂点を共有しない1-n道が2本引ける。全頂点試しのO(n(n+m))は、s-tカットや優越点(dominator)理論への入り口の素朴解。', ins: ['3 2\n1 2\n2 3\n', '4 4\n1 2\n2 4\n1 3\n3 4\n', '4 3\n1 2\n2 3\n3 4\n', '2 1\n1 2\n', '5 5\n1 2\n2 5\n1 3\n3 4\n4 5\n', '5 4\n1 2\n2 3\n3 4\n4 5\n'] })

t({ lv: 419, concept: 'グラフ: 共通の友人が最も多いペア', title: '最強の共通人脈', tags: ['グラフ'], io: '1行目に頂点数 n (n≥2) と辺数 m、続く m 行に無向辺 u v が与えられます。', ask: '2頂点の組(隣接していてもよい)の中での「共通の隣人の数」の最大値を出力してください。', h1: '共通の友人がいるペア数(既出)のmax版。', h2: '隣接集合の積集合を全ペアで。', ref: 'n,m=map(int,input().split())\nnb=[set() for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    nb[u].add(v)\n    nb[v].add(u)\nbest=0\nfor u in range(1,n+1):\n    for v in range(u+1,n+1):\n        c=len(nb[u]&nb[v])\n        if c>best:\n            best=c\nprint(best)', tip: 'SNSの「知り合いかも」推薦の最有力スコアがこの共通隣人数。行列で言えば A² の最大の非対角成分にあたり、疎グラフなら隣人の隣人だけ調べる高速化が効く。', ins: ['4 4\n1 3\n1 4\n2 3\n2 4\n', '3 2\n1 2\n2 3\n', '2 1\n1 2\n', '5 6\n1 2\n1 3\n2 3\n4 1\n4 2\n4 3\n', '6 4\n1 2\n3 2\n1 4\n3 4\n', '3 3\n1 2\n2 3\n1 3\n'] })

t({ lv: 420, concept: 'シミュレーション: 番号順の貪欲な席割り', title: '早い者勝ちの席取り', tags: ['シミュレーション'], io: '1行目に人数 n と席数 m、続く n 行に各人の希望する席の番号(空白区切り)が与えられます。', ask: '人1から順に「希望リストの中で最も番号の小さい空席」に座る(空きがなければ座れない)とき、座れた人数を出力してください。', h1: '空席の集合を持って順に処理。', h2: '希望をソートして最初の空席を探す。', ref: 'n,m=map(int,input().split())\ntaken=set()\ncnt=0\nfor _ in range(n):\n    wish=sorted(map(int,input().split()))\n    for s in wish:\n        if s not in taken:\n            taken.add(s)\n            cnt+=1\n            break\nprint(cnt)', tip: '二部マッチング(同レベル帯既出)の最適解と違い、早い者勝ちの貪欲は損をすることがある。両方を同じ入力で比べると増加道(譲り合い)の価値が具体的な数字で見える。', ins: ['2 2\n1 2\n1\n', '3 3\n1 2 3\n1 2 3\n1 2 3\n', '2 2\n2\n2\n', '2 1\n1\n1\n', '3 2\n1\n1 2\n2\n', '4 4\n4 1\n1\n2 3\n3\n'] })

t({ lv: 421, concept: 'ゲーム: ウィトフのゲームの必勝判定', title: '2つの山と黄金比', tags: ['ゲーム'], io: '2つの山の石の数 a b が空白区切りで1行で与えられます (0≤a,b)。', ask: '「片方の山から好きなだけ取る」か「両方の山から同じ数だけ取る」を交互に行い、取れなくなった(両山とも0で手番が来た)方が負けです。双方最善で先手が勝つなら first、後手なら second を出力してください。', h1: '小さい状態から勝ち負けを埋める。', h2: '負け状態は「そこから動けるどの先も勝ち状態」の否定。', ref: 'a,b=map(int,input().split())\nmemo={}\ndef win(x,y):\n    if x>y:\n        x,y=y,x\n    if (x,y) in memo:\n        return memo[(x,y)]\n    r=False\n    for k in range(1,y+1):\n        if k<=x and not win(x-k,y):\n            r=True\n            break\n        if not win(x,y-k):\n            r=True\n            break\n    if not r:\n        for k in range(1,x+1):\n            if not win(x-k,y-k):\n                r=True\n                break\n    memo[(x,y)]=r\n    return r\nprint("first" if win(a,b) else "second")', tip: '負け位置は (⌊kφ⌋, ⌊kφ²⌋)、つまり黄金比の整数部が並ぶという驚異の閉形式を持つ。DPの答えと黄金比の式を突き合わせる「実験数学」が味わえる名作ゲーム。', ins: ['1 2\n', '1 1\n', '0 0\n', '3 5\n', '2 2\n', '2 3\n'] })

t({ lv: 422, concept: 'ゲーム: 割って1にした方が勝ち', title: '素因数を削り合うゲーム', tags: ['ゲーム', '数論'], io: '2以上の整数 n が1行で与えられます。', ask: '2人が交互に「今の数をその素因数のどれかで割る」操作を行い、1 にした方が勝ちです。双方最善で先手が勝つなら first、後手なら second を出力してください。', h1: '1手で素因数が必ず1個減る。', h2: '素因数の総数(重複込み)の偶奇で決まる。', ref: 'n=int(input())\nc=0\np=2\nwhile p*p<=n:\n    while n%p==0:\n        c+=1\n        n//=p\n    p+=1\nif n>1:\n    c+=1\nprint("first" if c%2==1 else "second")', tip: 'どんな手を選んでもΩ(素因数の総数)がちょうど1減る、という「手数固定」型のゲームは偶奇だけで決まる。戦略が無意味になる構造を見抜くのがゲーム解析の第一歩。', ins: ['8\n', '6\n', '2\n', '12\n', '36\n', '7\n'] })

t({ lv: 423, concept: 'ゲーム: 2つの山の合成の勝敗', title: '2つの山を同時に遊ぶ', tags: ['ゲーム'], io: '1行目に一度に取れる個数の集合(空白区切り)、2行目に2つの山の石の数 a b が与えられます。手番では「どちらかの山から、集合にある個数だけ」取ります。', ask: '取れなくなった方が負けのとき、双方最善で先手が勝つなら first、後手なら second を出力してください。', h1: '各山のGrundy数を独立に求める。', h2: 'スプレイグ=グランディの定理: XORが0でなければ先手勝ち。', ref: 'S=list(map(int,input().split()))\na,b=map(int,input().split())\nlimit=max(a,b)\ng=[0]*(limit+1)\nfor x in range(1,limit+1):\n    s={g[x-k] for k in S if k<=x}\n    m=0\n    while m in s:\n        m+=1\n    g[x]=m\nprint("first" if g[a]^g[b]!=0 else "second")', tip: '独立なゲームの合成はGrundy数のXORで決まる、というスプレイグ=グランディ理論の実演。1山の勝敗(既出)からXOR1回で2山に届く、合成定理の威力が最短距離で体験できる。', ins: ['1 2\n3 4\n', '1\n2 2\n', '2 3\n5 5\n', '1 3 4\n2 7\n', '1 2 3\n4 4\n', '1\n1 2\n'] })

t({ lv: 424, concept: '数論: カーマイケル数か', title: 'テストをすり抜ける偽物', tags: ['数論'], io: '3以上の奇数 n が1行で与えられます。', ask: 'n が合成数なのに「n と互いに素な全ての底 a で a^(n−1) ≡ 1 (mod n)」となる(カーマイケル数)なら yes、そうでなければ no を出力してください。', h1: 'まず合成数であることを確かめる。', h2: '互いに素な底を全部試す(powの3引数で)。', ref: 'from math import gcd\nn=int(input())\ndef isp(x):\n    i=2\n    while i*i<=x:\n        if x%i==0:\n            return False\n        i+=1\n    return True\nif isp(n):\n    print("no")\nelse:\n    ok=all(pow(a,n-1,n)==1 for a in range(2,n) if gcd(a,n)==1)\n    print("yes" if ok else "no")', tip: '561=3·11·17が最小のカーマイケル数で、フェルマーテスト(同レベル既出)を全底で欺く。コルセルトの判定法(平方因子なし＆全素因数pでp−1|n−1)で一瞬で確かめる別解もある。', ins: ['561\n', '15\n', '1105\n', '7\n', '9\n', '1729\n'] })

t({ lv: 425, concept: '数論: 最大と最小の素因数の差', title: '素因数の両端の開き', tags: ['数論'], io: '2以上の整数 n が1行で与えられます。', ask: 'n の最大の素因数から最小の素因数を引いた値を出力してください(素因数が1種類なら 0)。', h1: '最小は試し割りの最初のヒット。', h2: '割り切った後に残る値が最大(1より大きければ)。', ref: 'n=int(input())\nsmall=None\nbig=None\np=2\nwhile p*p<=n:\n    while n%p==0:\n        if small is None:\n            small=p\n        big=p\n        n//=p\n    p+=1\nif n>1:\n    if small is None:\n        small=n\n    big=n\nprint(big-small)', tip: '最大素因数(同レベル既出)と最小素因数を一度の試し割りで同時に確保する集計の練習。差が0の数は素数のべき乗と一致し、判定問題(同レベル既出)と表裏になっている。', ins: ['12\n', '35\n', '7\n', '30\n', '100\n', '77\n'] })

t({ lv: 426, concept: '組合せ: パスカルの行の偶奇パターン', title: 'シェルピンスキーの一行', tags: ['組合せ'], io: '非負整数 n が1行で与えられます。', ask: 'C(n,0) から C(n,n) までの偶奇を、奇数なら 1、偶数なら 0 として連結した文字列を出力してください。', h1: '奇数の個数(既出)の位置まで示す版。', h2: 'リュカの定理: C(n,k)が奇数 ⇔ (n AND k)==k。', ref: 'n=int(input())\nprint("".join("1" if n&k==k else "0" for k in range(n+1)))', tip: 'この行を全部縦に並べるとシェルピンスキーのギャスケット(フラクタル)が浮かび上がる。二項係数の計算なしにビット演算だけで偶奇が決まるのがリュカの定理の切れ味。', ins: ['4\n', '0\n', '3\n', '5\n', '6\n', '7\n'] })

export const CATALOG = TASKS
