// 生成タスク 第69波：各レベル2問化フェーズ(24)。lv891〜915 に2問目を追加。
// 最上級帯: 木/線形代数/数え上げ/ゲーム理論。重複なし・決定的・採点一意。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 891, concept: '木: 各頂点を通る経路の本数', title: 'この駅を通る経路はいくつか', tags: ['木'], io: '1行目に頂点数 n、続く n−1 行に木の辺が与えられます。', ask: '各頂点 v について、v を通る(端点も含む)頂点対のパスの本数を、頂点1から順に空白区切りで出力してください。', h1: '「通らないペア」を数える方が楽。', h2: 'v を取り除いたときの各成分サイズ c_i から、C(n,2) − Σ C(c_i,2) が答え(v が端点のパスも通るに含む…定義に注意して、v を含むペア=全ペア−成分内ペア)。', ref: 'from collections import deque\nn=int(input())\ng=[[] for _ in range(n+1)]\nfor _ in range(n-1):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\nout=[]\nfor v in range(1,n+1):\n    seen=[False]*(n+1)\n    seen[v]=True\n    total=n*(n-1)//2\n    for s in g[v]:\n        if seen[s]:\n            continue\n        c=0\n        q=deque([s])\n        seen[s]=True\n        while q:\n            x=q.popleft()\n            c+=1\n            for y in g[x]:\n                if not seen[y]:\n                    seen[y]=True\n                    q.append(y)\n        total-=c*(c-1)//2\n    out.append(total)\nprint(*out)', tip: '「vを通るパス=全ペア−vを避けるペア」の補集合勘定。避けるペアは成分ごとに閉じるので、削除後の成分サイズだけで数え切れる。', ins: ['3\n1 2\n2 3\n', '4\n1 2\n1 3\n1 4\n', '2\n1 2\n', '5\n1 2\n2 3\n3 4\n4 5\n', '4\n1 2\n2 3\n2 4\n', '6\n1 2\n1 3\n2 4\n2 5\n3 6\n'] })

t({ lv: 892, concept: 'DP: 二乗コストのk分割', title: '仕事量の二乗ペナルティを最小に', tags: ['DP'], io: '1行目に k、2行目に正整数列が与えられます(k以上の長さ)。', ask: '列をちょうど k 個の連続ブロックに分け、各ブロックの(合計)²の総和を最小化した値を出力してください。', h1: 'dp[ブロック数][先頭からの個数]。', h2: '最後のブロックの開始位置を全て試す。接頭辞和で区間和はO(1)。', ref: 'k=int(input())\na=list(map(int,input().split()))\nn=len(a)\npre=[0]\nfor x in a:\n    pre.append(pre[-1]+x)\nINF=float("inf")\ndp=[[INF]*(n+1) for _ in range(k+1)]\ndp[0][0]=0\nfor g in range(1,k+1):\n    for j in range(g,n+1):\n        for i in range(g-1,j):\n            c=dp[g-1][i]+(pre[j]-pre[i])**2\n            if c<dp[g][j]:\n                dp[g][j]=c\nprint(dp[k][n])', tip: '二乗コストは「均等に割るほど得」な凸性を持ち、大規模ではCHT(Convex Hull Trick)や分割最適化(Knuth/D&C)でO(nk)〜へ落ちる入り口の形。', ins: ['2\n1 2 3\n', '1\n5 5\n', '3\n1 1 1\n', '2\n10 1 1\n', '2\n3 3 3 3\n', '4\n2 2 2 2\n'] })

t({ lv: 893, concept: '数論: 素数の最大の間隔', title: '素数の砂漠の広さ', tags: ['数論'], io: 'L R が空白区切りで1行で与えられます(区間内に素数が2つ以上)。', ask: 'L 以上 R 以下の素数を小さい順に並べたとき、隣り合う素数の差の最大を出力してください。', h1: '区間の素数を列挙する。', h2: '隣接差の最大を取るだけ。大きな区間では√R以下の素数で篩う「区間篩」。', ref: 'L,R=map(int,input().split())\ndef isp(x):\n    if x<2:\n        return False\n    i=2\n    while i*i<=x:\n        if x%i==0:\n            return False\n        i+=1\n    return True\nps=[x for x in range(L,R+1) if isp(x)]\nprint(max(ps[i+1]-ps[i] for i in range(len(ps)-1)))', tip: '素数ギャップは平均すればln n程度だが、いくらでも広い砂漠が作れる(n!+2..n!+n)。有界なギャップが無限回現れるかは双子素数予想に繋がる最前線。', ins: ['1 10\n', '10 30\n', '2 3\n', '20 50\n', '90 130\n', '2 20\n'] })

t({ lv: 894, concept: '線形代数: 主成分の列の位置', title: '掃き出しで残る主列はどこか', tags: ['数学'], io: '1行目に 行数 r 列数 c 素数 p、続く r 行に行列(mod p)が与えられます。', ask: '行簡約(mod p)したときのピボット(主成分)が立つ列番号(1始まり)を昇順に空白区切りで出力してください(ランク0なら none)。', h1: '列ごとに非零ピボットを探して掃き出す。', h2: 'ピボットに使った列番号を記録していく。', ref: 'r,c,p=map(int,input().split())\nA=[list(map(int,input().split())) for _ in range(r)]\nrow=0\npivs=[]\nfor col in range(c):\n    sel=-1\n    for i in range(row,r):\n        if A[i][col]%p!=0:\n            sel=i\n            break\n    if sel<0:\n        continue\n    A[row],A[sel]=A[sel],A[row]\n    inv=pow(A[row][col],p-2,p)\n    A[row]=[x*inv%p for x in A[row]]\n    for i in range(r):\n        if i!=row and A[i][col]%p!=0:\n            f=A[i][col]\n            A[i]=[(A[i][j]-f*A[row][j])%p for j in range(c)]\n    pivs.append(col+1)\n    row+=1\n    if row==r:\n        break\nprint(*pivs if pivs else ["none"])', tip: '主列は「独立な方向がどの変数に立っているか」を教える。非主列が自由変数、という対応が連立方程式の解の記述のすべてを決める。', ins: ['2 2 5\n1 2\n2 4\n', '2 3 7\n1 0 2\n0 1 3\n', '1 2 3\n0 0\n', '3 3 5\n1 1 1\n2 2 2\n3 3 3\n', '2 2 2\n1 1\n1 0\n', '3 2 3\n1 0\n0 1\n1 1\n'] })

t({ lv: 895, concept: '数え上げ: GF(2)の正則行列の数', title: '0/1行列で逆行列を持つものの数', tags: ['数学'], io: '正整数 n が1行で与えられます。', ask: 'GF(2)上(成分0/1、演算はmod 2)の n×n 行列のうち、正則(逆行列を持つ)なものの総数を出力してください。', h1: '1行ずつ「これまでの行の張る空間に入らないベクトル」を選ぶ。', h2: 'i行目の選び方は 2^n − 2^i 通り。積を取る。', ref: 'n=int(input())\nr=1\nfor i in range(n):\n    r*=(1<<n)-(1<<i)\nprint(r)', tip: '一般線形群 GL(n,2) の位数。行を順に選ぶ数え上げは基底の構成そのもので、q元体なら Π(qⁿ−qⁱ) に一般化される。', ins: ['1\n', '2\n', '3\n', '4\n', '5\n', '6\n'] })

t({ lv: 896, concept: '数論: a^(b^c)の一の位', title: '指数の指数の一の位', tags: ['数論'], io: 'a b c が空白区切りで1行で与えられます(全て正整数)。', ask: 'a の (b の c 乗) 乗の一の位を出力してください。', h1: '一の位は周期4以下で循環する。', h2: '指数 b^c を「周期4での位置」つまり mod 4 で求める(0なら4扱い)。pow(b,c,4) が使える。', ref: 'a,b,c=map(int,input().split())\ne=pow(b,c,4)\nif e==0:\n    e=4\nprint(pow(a,e,10))', tip: '「指数はmod周期で潰す」。ただし指数が0扱いになる罠を避けるため周期分を足す(e=4)。一般のmod mではオイラーの定理+累乗の塔の議論に育つ。', ins: ['2 3 1\n', '7 2 3\n', '9 9 9\n', '2 10 10\n', '3 4 5\n', '10 5 5\n'] })

t({ lv: 897, concept: '数え上げ: 同じ数を2回までの分割', title: '同じ部分は2回までの分割', tags: ['数え上げ', 'DP'], io: '正整数 n が1行で与えられます。', ask: 'n の分割のうち、どの数も高々2回しか使わないものの総数を出力してください。', h1: '部分ごとに「0回・1回・2回」の3択。', h2: '部分 p を順に処理し、dp[n] に p と 2p の寄与を足すDP。', ref: 'n=int(input())\ndp=[0]*(n+1)\ndp[0]=1\nfor p in range(1,n+1):\n    nd=dp[:]\n    for v in range(n+1):\n        if dp[v]:\n            if v+p<=n:\n                nd[v+p]+=dp[v]\n            if v+2*p<=n:\n                nd[v+2*p]+=dp[v]\n    dp=nd\nprint(dp[n])', tip: '母関数 Π(1+x^k+x^2k) の係数。「3で割り切れない部分への分割」と同数になることが母関数の恒等式から示せる、オイラー流の対応の一例。', ins: ['1\n', '3\n', '4\n', '5\n', '6\n', '10\n'] })

t({ lv: 898, concept: '数え上げ: 2のべき乗への分割数', title: '2のべき乗だけで作る分割', tags: ['数え上げ', 'DP'], io: '正整数 n が1行で与えられます。', ask: 'n を 1,2,4,8,… (2のべき乗)の和に分ける方法(順序なし)の総数を出力してください。', h1: '使える部分が 2のべき乗だけの分割DP。', h2: '部分を外側ループにする硬貨の組合せDPと同じ形。', ref: 'n=int(input())\ndp=[0]*(n+1)\ndp[0]=1\np=1\nwhile p<=n:\n    for v in range(p,n+1):\n        dp[v]+=dp[v-p]\n    p*=2\nprint(dp[n])', tip: '二進分割数(binary partition)。b(2n)=b(2n−1)+b(n) という美しい漸化式を持ち、増加の速さはChurchhouseが研究した古典的対象。', ins: ['1\n', '2\n', '4\n', '7\n', '10\n', '20\n'] })

t({ lv: 899, concept: '数学: 等差×等比の和', title: 'i×rのi乗を足し合わせる', tags: ['数学'], io: 'n r が空白区切りで1行で与えられます。', ask: 'Σ i·rⁱ (i=1..n) を出力してください。', h1: 'そのままループで足せる。', h2: '閉形式は S·(r−1)² = r((n)r^(n+1)−(n+1)rⁿ+1) の変形で得られる(r=1なら三角数)。', ref: 'n,r=map(int,input().split())\nprint(sum(i*r**i for i in range(1,n+1)))', tip: '等比の和を微分すると出てくる形(算術幾何級数)。期待値計算(幾何分布の平均)や償却解析で頻出する和のパターン。', ins: ['3 2\n', '1 5\n', '4 1\n', '5 3\n', '2 10\n', '10 2\n'] })

t({ lv: 900, concept: '数論: 連続する合成数の最初の区間', title: '素数のない区間の始まり', tags: ['数論'], io: '正整数 k が1行で与えられます。', ask: '連続する k 個の整数が全て合成数(素数でも1でもない)となる最初の開始位置 x (x≥2) を出力してください。', h1: '素数判定を用意して走査する。', h2: '連続合成数のランを数えながら進めば1回の走査で見つかる。', ref: 'k=int(input())\ndef isp(x):\n    if x<2:\n        return False\n    i=2\n    while i*i<=x:\n        if x%i==0:\n            return False\n        i+=1\n    return True\nrun=0\nx=1\nwhile True:\n    x+=1\n    if not isp(x) and x>1:\n        run+=1\n        if run==k:\n            print(x-k+1)\n            break\n    else:\n        run=0', tip: '(k+1)!+2 から k 個は必ず合成数、という構成的証明が上界を与えるが、実際の最初の砂漠はずっと手前にある。証明の上界と実際の値の差を体感できる。', ins: ['1\n', '2\n', '3\n', '5\n', '7\n', '13\n'] })

t({ lv: 901, concept: 'bitDP: 隣接差が範囲内の順列数', title: '隣の差が大きすぎない並べ方', tags: ['bitDP'], io: 'n k が空白区切りで1行で与えられます (n≤8)。', ask: '1..n の順列で、隣接する2数の差の絶対値が全て k 以下のものの総数を出力してください。', h1: '使用済み集合と直前の数を状態に。', h2: 'dp[mask][last] を遷移。差の条件だけ確かめる。', ref: 'n,k=map(int,input().split())\nfrom functools import lru_cache\nimport sys\nsys.setrecursionlimit(100000)\ndp={}\ndef f(mask,last):\n    if mask==(1<<n)-1:\n        return 1\n    key=(mask,last)\n    if key in dp:\n        return dp[key]\n    s=0\n    for v in range(1,n+1):\n        if not mask>>(v-1)&1 and (last==0 or abs(v-last)<=k):\n            s+=f(mask|1<<(v-1),v)\n    dp[key]=s\n    return s\nprint(f(0,0))', tip: '(集合, 直前)のbitDPは順列の隣接制約の万能形。差1以下だとフィボナッチ的に細る、kを緩めるとn!へ近づく、と制約の強さが数に現れる。', ins: ['3 1\n', '3 2\n', '4 1\n', '4 3\n', '2 1\n', '5 2\n'] })

t({ lv: 902, concept: 'グラフ: 最大カット', title: '2組に分けて橋渡しを最大に', tags: ['グラフ', '全探索'], io: '1行目に n m (n≤15)、続く m 行に無向辺が与えられます。', ask: '頂点を2つの組に分けたとき、組をまたぐ辺の本数の最大(最大カット)を出力してください。', h1: '片側の集合を全列挙する。', h2: '各分け方で「両端が別の組」の辺を数える。', ref: 'n,m=map(int,input().split())\nedges=[tuple(map(int,input().split())) for _ in range(m)]\nbest=0\nfor mask in range(1<<n):\n    c=0\n    for u,v in edges:\n        if (mask>>(u-1)&1)!=(mask>>(v-1)&1):\n            c+=1\n    if c>best:\n        best=c\nprint(best)', tip: '最小カットは多項式時間なのに最大カットはNP困難、という有名な非対称。近似(Goemans-Williamson)や物理(イジング模型)への接続も深い名門問題。', ins: ['3 3\n1 2\n2 3\n1 3\n', '2 1\n1 2\n', '4 4\n1 2\n2 3\n3 4\n4 1\n', '4 6\n1 2\n1 3\n1 4\n2 3\n2 4\n3 4\n', '3 2\n1 2\n2 3\n', '5 5\n1 2\n2 3\n3 4\n4 5\n5 1\n'] })

t({ lv: 903, concept: '数え上げ: 指定マスを通る経路数', title: '寄り道必須の経路を数える', tags: ['数え上げ'], io: 'h w r c が1行で与えられます(左上(1,1)から右下(h,w)へ右・下移動、必ず(r,c)を通る)。', ask: 'マス (r,c) を通る経路の総数を出力してください。', h1: '経路数は区間ごとの積に分解できる。', h2: '(1,1)→(r,c) の経路数 × (r,c)→(h,w) の経路数。それぞれ二項係数。', ref: 'from math import comb\nh,w,r,c=map(int,input().split())\nprint(comb(r-1+c-1,r-1)*comb(h-r+w-c,h-r))', tip: '「必ず通る」は通過点で分解して積、「通らない」は全体から引く補集合。経路の数え上げはこの2手の組合せでほとんど処理できる。', ins: ['2 2 1 2\n', '3 3 2 2\n', '3 3 1 1\n', '4 4 2 3\n', '2 5 2 2\n', '5 5 3 3\n'] })

t({ lv: 904, concept: '数え上げ: 全順列の転倒数の総和', title: '全部の並べ替えの乱れの合計', tags: ['数学'], io: '正整数 n が1行で与えられます。', ask: '1..n の全ての順列について転倒数を合計した値を出力してください。', h1: 'ペア (i,j) ごとに「転倒になっている順列の数」を数える。', h2: 'どのペアもちょうど半分の順列で転倒する。答えは C(n,2)·n!/2。', ref: 'from math import factorial,comb\nn=int(input())\nprint(comb(n,2)*factorial(n)//2)', tip: '対称性(あるペアが正順の順列と逆順の順列は1対1)で総和が瞬時に出る。平均転倒数 n(n−1)/4 はソートの平均計算量の解析にも登場する。', ins: ['1\n', '2\n', '3\n', '4\n', '5\n', '6\n'] })

t({ lv: 905, concept: '数え上げ: 2色ドミノの2×n敷き', title: '色つきドミノで壁を飾る', tags: ['数え上げ', 'DP'], io: '正整数 n が1行で与えられます。', ask: '2×n の壁を1×2のドミノ(縦横自由)で敷き詰め、さらに各ドミノを赤か青に塗るとき、敷き方と塗り方の組合せの総数を出力してください。', h1: '敷き方ごとにドミノ数が違う(塗り方は 2^枚数)。', h2: 'f(n) = 2·f(n−1) + 4·f(n−2)(縦1枚は2通り、横2枚は4通り)。', ref: 'n=int(input())\na,b=1,2\nfor _ in range(n-1):\n    a,b=b,2*b+4*a\nprint(b if n>=1 else 1)', tip: '重み付きタイル数え上げは「タイルごとの選択肢を係数に乗せる」だけで同じ漸化式に載る。係数を変数xにすれば枚数分布の母関数も得られる。', ins: ['1\n', '2\n', '3\n', '4\n', '5\n', '8\n'] })

t({ lv: 906, concept: 'ゲーム: 1×n盤のドミノ置き対戦', title: 'ドミノを置けなくなったら負け', tags: ['ゲーム', '再帰'], io: '正整数 n が1行で与えられます。', ask: '1×n の盤に2人交互に1×2のドミノを(空きマス2連続の場所に)置き、置けなくなった方が負けです。両者最善で先手が勝つなら first、負けるなら second を出力してください。', h1: '置くと盤が左右2つの独立な盤に割れる。', h2: 'Grundy数: g(n) = mex over 置き位置 of g(左)⊕g(右)。g(n)≠0 なら先手勝ち。', ref: 'import sys\nsys.setrecursionlimit(10000)\nn=int(input())\nmemo={}\ndef g(m):\n    if m<2:\n        return 0\n    if m in memo:\n        return memo[m]\n    s=set()\n    for i in range(m-1):\n        s.add(g(i)^g(m-i-2))\n    r=0\n    while r in s:\n        r+=1\n    memo[m]=r\n    return r\nprint("first" if g(n)!=0 else "second")', tip: '置くたびに盤が分裂する分割ゲームはGrundy数のXOR合成が本領を発揮する場面。この игра(Dawson系の八進ゲーム)のGrundy列は最終的に周期34を持つ。', ins: ['1\n', '2\n', '3\n', '5\n', '8\n', '15\n'] })

t({ lv: 907, concept: 'バックトラック: 積の等しい2分割', title: '掛け算で釣り合う2グループ', tags: ['バックトラック'], io: '正整数の列(12個以下)が1行で空白区切りで与えられます。', ask: '全要素を2つの空でないグループに分け、それぞれの積を等しくできるなら yes、できなければ no を出力してください。', h1: '部分集合を全列挙する。', h2: '総積が平方数でなければ即 no、という枝刈りも効く。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nok=False\nfor mask in range(1,(1<<n)-1):\n    p1=1\n    p2=1\n    for i in range(n):\n        if mask>>i&1:\n            p1*=a[i]\n        else:\n            p2*=a[i]\n    if p1==p2:\n        ok=True\n        break\nprint("yes" if ok else "no")', tip: '和の等分割のDPは値域で表を張れたが、積は爆発するので全列挙+必要条件(総積が平方数)の枝刈りが現実解。素因数の指数ベクトルで見る道もある。', ins: ['2 3 6\n', '1 2 3\n', '4 4\n', '2 2 2\n', '1 1\n', '2 8 4\n'] })

t({ lv: 908, concept: '数学: 貪欲な正方形切りの枚数', title: '一番大きい正方形から切ると何枚か', tags: ['数学'], io: 'w h が空白区切りで1行で与えられます(長方形の幅と高さ)。', ask: '「残りの長方形から最大の正方形を切り取る」を繰り返して全てを正方形にしたときの枚数を出力してください。', h1: '短い辺の正方形を切ると、残りも長方形。', h2: 'これはユークリッドの互除法そのもので、答えは商の合計。', ref: 'w,h=map(int,input().split())\ncnt=0\nwhile w and h:\n    if w>=h:\n        cnt+=w//h\n        w%=h\n    else:\n        cnt+=h//w\n        h%=w\nprint(cnt)', tip: '互除法の幾何的な姿。連分数の係数の和と一致し、フィボナッチ隣接比のときに枚数が最大になる(=互除法の最悪ケース)ことまで一続きに見える。', ins: ['5 3\n', '4 4\n', '6 4\n', '1 10\n', '13 8\n', '7 5\n'] })

t({ lv: 909, concept: '数え上げ: 色の個数を固定したネックレス', title: '黒ビーズちょうどk個の首飾り', tags: ['数学'], io: 'n k が空白区切りで1行で与えられます (0≤k≤n)。', ask: '白黒 n 個のビーズを円形に並べ(回転で同一視)、黒がちょうど k 個の首飾りの数を出力してください。', h1: 'バーンサイドの補題を「黒の個数固定」で使う。', h2: '回転 d|gcd(n,k) だけが黒を保存でき、(1/n)·Σ_{d|gcd(n,k)} φ(d)·C(n/d, k/d)。', ref: 'from math import comb,gcd\nn,k=map(int,input().split())\ndef phi(x):\n    r=x\n    p=2\n    while p*p<=x:\n        if x%p==0:\n            while x%p==0:\n                x//=p\n            r-=r//p\n        p+=1\n    if x>1:\n        r-=r//x\n    return r\ng=gcd(n,k) if k>0 else n\ntotal=0\nd=1\nwhile d<=g:\n    if g%d==0:\n        total+=phi(d)*comb(n//d,k//d)\n    d+=1\nprint(total//n)', tip: '固定点の数え上げが「d等分の各ブロックに黒k/d個」という整除条件に落ちる。属性つきバーンサイドは、条件が回転で保存されるかを見るのが肝。', ins: ['4 2\n', '3 1\n', '4 0\n', '6 3\n', '5 2\n', '6 2\n'] })

t({ lv: 910, concept: '数論: ペアの最小公倍数の最小', title: '一番小さく重なる2つの数', tags: ['数論'], io: '正整数の列(2個以上)が1行で空白区切りで与えられます。', ask: '2つの要素の最小公倍数(LCM)の最小値を出力してください。', h1: '全ペアで lcm を計算する。', h2: '大規模では「各値の倍数ごとに最小2つを集める」調和級数の走査で O(V log V)。', ref: 'import math\na=list(map(int,input().split()))\nn=len(a)\nbest=None\nfor i in range(n):\n    for j in range(i+1,n):\n        l=a[i]*a[j]//math.gcd(a[i],a[j])\n        if best is None or l<best:\n            best=l\nprint(best)', tip: '最小LCMのペアは「同じ値」か「倍数関係」が絡むことが多い。値域走査(各dの倍数のうち最小の2つ)への言い換えが高速化の定石。', ins: ['4 6 8\n', '2 3\n', '5 10 20\n', '7 7\n', '3 9 6\n', '13 17 19\n'] })

t({ lv: 911, concept: '数え上げ: 上限つきの分配', title: '1人m個までのりんご分配', tags: ['数え上げ', 'DP'], io: 'n k m が空白区切りで1行で与えられます。', ask: '区別のない n 個のりんごを k 人に配る(0個も可、ただし1人 m 個まで)方法の数を出力してください。', h1: '上限なしなら重複組合せ。', h2: '1人ずつ 0..m 個を配るDP、または包除原理 Σ(−1)ʲC(k,j)C(n−j(m+1)+k−1, k−1)。', ref: 'n,k,m=map(int,input().split())\ndp=[0]*(n+1)\ndp[0]=1\nfor _ in range(k):\n    nd=[0]*(n+1)\n    for v in range(n+1):\n        if dp[v]:\n            for add in range(0,min(m,n-v)+1):\n                nd[v+add]+=dp[v]\n    dp=nd\nprint(dp[n])', tip: '上限つき重複組合せは「はみ出す人を包除で引く」のが閉形式、「1人ずつ配る」のがDP。両方で同じ答えを出して検算する価値がある。', ins: ['5 3 2\n', '3 2 3\n', '4 2 2\n', '10 3 5\n', '2 5 1\n', '6 2 3\n'] })

t({ lv: 912, concept: 'DP: 跳ね返りすごろくの最少手数', title: '行き過ぎたら跳ね返るすごろく', tags: ['DP', 'BFS'], io: '正整数 n が1行で与えられます(マス0からマスnへ)。', ask: 'サイコロ(1〜6を自由に選べる)で進み、n を超えた分は跳ね返る(n+2 に着くなら n−2 へ)とき、ちょうど n に止まるまでの最少手数を出力してください。', h1: '各マスからの遷移は高々6通り。', h2: '跳ね返り先 2n−(pos+d) も含めてBFS。', ref: 'from collections import deque\nn=int(input())\ndist=[-1]*(n+1)\ndist[0]=0\nq=deque([0])\nwhile q:\n    x=q.popleft()\n    if x==n:\n        break\n    for d in range(1,7):\n        y=x+d\n        if y>n:\n            y=2*n-y\n        if 0<=y<=n and dist[y]<0:\n            dist[y]=dist[x]+1\n            q.append(y)\nprint(dist[n])', tip: '特殊ルールは遷移関数に閉じ込めればBFSの骨格は不変。跳ね返りのせいで「近いのに着きにくい」マスが生まれるのがこのルールの面白さ。', ins: ['6\n', '1\n', '7\n', '12\n', '2\n', '11\n'] })

t({ lv: 913, concept: '数え上げ: 桁の和と積が等しい数', title: '足しても掛けても同じ数', tags: ['数学'], io: '正整数 N が1行で与えられます。', ask: '1 以上 N 以下で、十進の桁の和と桁の積が等しい数(例 22, 123)の個数を出力してください。', h1: '各数の桁和と桁積を比べる。', h2: '1桁は常に条件を満たす。', ref: 'n=int(input())\ncnt=0\nfor x in range(1,n+1):\n    s=0\n    p=1\n    for ch in str(x):\n        d=int(ch)\n        s+=d\n        p*=d\n    if s==p:\n        cnt+=1\nprint(cnt)', tip: 'sum-product number と呼ばれる数の有界版。桁に0があると積が0に潰れる、桁数が増えると和は線形・積は指数的、という2つの観察が構造を教えてくれる。', ins: ['9\n', '25\n', '100\n', '150\n', '1\n', '1000\n'] })

t({ lv: 914, concept: 'ゲーム: ムーアのNim', title: '一度にk山まで触れるNim', tags: ['ゲーム'], io: '1行目に 一度に減らせる山の数の上限 k、2行目に各山の石の数が与えられます。', ask: '1手で最大 k 個の山から(それぞれ1個以上)石を取れるNimで、先手必勝なら first、後手必勝なら second を出力してください。', h1: '普通のNim(k=1)はXOR。一般kは?', h2: 'ムーアの定理: 各ビット位置について「そのビットが立つ山の数」を k+1 で割った余りが全て0なら後手必勝。', ref: 'k=int(input())\na=list(map(int,input().split()))\nok=True\nfor b in range(32):\n    c=sum(v>>b&1 for v in a)\n    if c%(k+1)!=0:\n        ok=False\nprint("second" if ok else "first")', tip: 'XOR(mod2の和)が「mod (k+1) の和」に一般化される鮮やかな定理(Moore 1910)。Nim_kと呼ばれ、k=1で普通のNimに退化する。', ins: ['1\n1 2 3\n', '2\n1 2 3\n', '1\n5 5\n', '2\n1 1 1\n', '3\n7 7 7 7\n', '2\n4 4 4\n'] })

t({ lv: 915, concept: 'ゲーム: ユークリッドの引き算ゲーム', title: '倍数を引き合うユークリッドゲーム', tags: ['ゲーム', '再帰'], io: '正整数 a b が空白区切りで1行で与えられます。', ask: '2つの正整数のうち大きい方から「小さい方の正の倍数」を引く(結果は0以上)。どちらかを0にした方が勝ち。両者最善で先手が勝つなら first、負けるなら second を出力してください。', h1: '大きい方が小さい方の2倍以上なら必勝(選択権がある)。', h2: 'a≥b で a//b≥2 か a%b==0 なら勝ち。そうでなければ強制手 (b, a−b) の相手の負けが自分の勝ち。', ref: 'a,b=map(int,input().split())\ndef win(a,b):\n    if a<b:\n        a,b=b,a\n    if a%b==0 or a//b>=2:\n        return True\n    return not win(b,a-b)\nprint("first" if win(a,b) else "second")', tip: '勝敗の境目は黄金比 φ: a/b>φ なら選択権が生まれて必勝。互除法の各ステップに意思決定が乗った、数論とゲーム理論の美しい交差点。', ins: ['3 1\n', '2 3\n', '5 3\n', '8 5\n', '10 4\n', '1 1\n'] })

export const CATALOG = TASKS
