// 生成タスク 第40波：lv701〜749。lv700(DP)とlv750(DP応用)の橋渡し。
// 区間DP/株取引DP/ゲームDP/桁DP/bitmask DP/グリッドDP の本物の別問題。
// 重複なし・決定的・採点一意(整数/文字列/列出力のみ)。無限ループ無し(全て有界ループ)。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 701, concept: '区間DP: 風船割りの最大コイン', title: '風船を割って得る最大コイン', tags: ['区間DP', 'dp'], io: '風船の数の列が1行で空白区切りで与えられます。', ask: '風船 i を割ると left·i·right コイン得られます(両端は1扱い)。全部割って得られる最大コインを出力してください。', h1: '「最後に割る風船」を区間DPで決める。', h2: 'dp[l][r]=区間(l,r)を割り尽くす最大、間にkを最後に割る。', ref: 'nums=list(map(int,input().split()))\na=[1]+nums+[1]\nn=len(a)\ndp=[[0]*n for _ in range(n)]\nfor length in range(2,n):\n    for l in range(0,n-length):\n        r=l+length\n        best=0\n        for k in range(l+1,r):\n            cand=dp[l][k]+a[l]*a[k]*a[r]+dp[k][r]\n            if cand>best:\n                best=cand\n        dp[l][r]=best\nprint(dp[0][n-1])', tip: '風船割りは「最後に割る1個」を固定する区間DP。両端に番兵1を置くのが定石。', ins: ['3 1 5 8\n', '1 5\n', '7\n', '2 2 2\n', '1 2 3 4\n', '9 76 64 21\n'] })

t({ lv: 702, concept: '区間DP: 石の併合最小コスト', title: '石を1山に併合する最小コスト', tags: ['区間DP', 'dp'], io: '各山の石の数の列が1行で与えられます(隣接2山を併合、コストは合計)。', ask: 'すべて1山に併合する最小総コストを出力してください。', h1: '区間の併合は最後の分割点で決まる。', h2: 'dp[l][r]=min(dp[l][k]+dp[k+1][r])+区間和。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nif n<=1:\n    print(0)\nelse:\n    pre=[0]*(n+1)\n    for i in range(n):\n        pre[i+1]=pre[i]+a[i]\n    INF=float("inf")\n    dp=[[0]*n for _ in range(n)]\n    for length in range(2,n+1):\n        for l in range(n-length+1):\n            r=l+length-1\n            best=INF\n            for k in range(l,r):\n                c=dp[l][k]+dp[k+1][r]\n                if c<best:\n                    best=c\n            dp[l][r]=best+pre[r+1]-pre[l]\n    print(dp[0][n-1])', tip: '隣接併合の最小コストは区間DP。各区間の併合コストに区間和を足す。', ins: ['1 2 3\n', '4 1 5 2\n', '7\n', '2 2\n', '1 1 1 1\n', '3 5 1 2 6\n'] })

t({ lv: 703, concept: '区間DP: 多角形分割の最小スコア', title: '凸多角形の三角形分割の最小スコア', tags: ['区間DP', 'dp'], io: '多角形の各頂点の値の列が1行で与えられます。', ask: '三角形に分割し、各三角形の3頂点値の積の和を最小化した値を出力してください。', h1: '区間[l,r]を頂点kで三角形に分ける。', h2: 'dp[l][r]=min(dp[l][k]+dp[k][r]+a[l]·a[k]·a[r])。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nif n<3:\n    print(0)\nelse:\n    INF=float("inf")\n    dp=[[0]*n for _ in range(n)]\n    for length in range(2,n):\n        for l in range(n-length):\n            r=l+length\n            best=INF\n            for k in range(l+1,r):\n                c=dp[l][k]+dp[k][r]+a[l]*a[k]*a[r]\n                if c<best:\n                    best=c\n            dp[l][r]=best\n    print(dp[0][n-1])', tip: '多角形分割は区間DP。区間の両端を結ぶ三角形の頂点kで分割する。', ins: ['1 2 3\n', '3 7 4 5\n', '1 3 1 4 1 5\n', '2 2 2 2\n', '5 5\n', '1 2 3 4\n'] })

t({ lv: 704, concept: '区間DP: 多角形分割の最大スコア', title: '凸多角形の三角形分割の最大スコア', tags: ['区間DP', 'dp'], io: '多角形の各頂点の値の列が1行で与えられます。', ask: '三角形に分割し、各三角形の3頂点値の積の和を最大化した値を出力してください。', h1: '区間[l,r]を頂点kで三角形に分ける。', h2: 'dp[l][r]=max(dp[l][k]+dp[k][r]+a[l]·a[k]·a[r])。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nif n<3:\n    print(0)\nelse:\n    dp=[[0]*n for _ in range(n)]\n    for length in range(2,n):\n        for l in range(n-length):\n            r=l+length\n            best=0\n            for k in range(l+1,r):\n                c=dp[l][k]+dp[k][r]+a[l]*a[k]*a[r]\n                if c>best:\n                    best=c\n            dp[l][r]=best\n    print(dp[0][n-1])', tip: '多角形分割の最大スコアは最小版と同じ区間DPで比較を max にするだけ。', ins: ['1 2 3\n', '3 7 4 5\n', '1 3 1 4 1 5\n', '2 2 2 2\n', '5 5\n', '1 2 3 4\n'] })

t({ lv: 705, concept: '株DP: k回取引の最大利益', title: '高々k回の株取引の最大利益', tags: ['dp'], io: '1行目に k、2行目に株価の列が与えられます。', ask: '高々 k 回(買って売るで1回)取引したときの最大利益を出力してください。', h1: 'dp[t][i]=t回・i日目までの最大利益。', h2: 'buy 状態を保持して O(nk) に。', ref: 'k=int(input())\nprices=list(map(int,input().split()))\nn=len(prices)\nif n==0 or k==0:\n    print(0)\nelse:\n    buy=[float("-inf")]*(k+1)\n    sell=[0]*(k+1)\n    for p in prices:\n        for j in range(1,k+1):\n            buy[j]=max(buy[j],sell[j-1]-p)\n            sell[j]=max(sell[j],buy[j]+p)\n    print(sell[k])', tip: '株のk回取引は「buy/sell状態×取引回数」のDP。各日に買い/売りの最善を更新する。', ins: ['2\n3 2 6 5 0 3\n', '1\n1 2 3\n', '2\n2 4 1\n', '0\n1 2 3\n', '3\n1 2 3 4 5\n', '2\n7 6 4 3 1\n'] })

t({ lv: 706, concept: '株DP: クールダウン付き取引', title: 'クールダウン付き株取引の最大利益', tags: ['dp'], io: '株価の列が1行で与えられます(売った翌日は買えない)。', ask: '取引回数無制限・売却翌日は休む条件での最大利益を出力してください。', h1: 'hold/sold/rest の3状態DP。', h2: 'sold→restのみ、rest/sold→holdは前日restから。', ref: 'prices=list(map(int,input().split()))\nif not prices:\n    print(0)\nelse:\n    hold=float("-inf")\n    sold=0\n    rest=0\n    for p in prices:\n        prev_sold=sold\n        sold=hold+p\n        hold=max(hold,rest-p)\n        rest=max(rest,prev_sold)\n    print(max(sold,rest))', tip: 'クールダウンは「保有/売却直後/待機」の3状態。売却直後の翌日は買えない制約を状態で表す。', ins: ['1 2 3 0 2\n', '1\n', '1 2 3 4 5\n', '5 4 3 2 1\n', '2 1 4\n', '6 1 3 2 4 7\n'] })

t({ lv: 707, concept: '株DP: 手数料付き取引', title: '手数料付き株取引の最大利益', tags: ['dp'], io: '1行目に手数料 fee、2行目に株価の列が与えられます(取引ごとに fee)。', ask: '取引回数無制限・1取引ごとに fee を払う条件での最大利益を出力してください。', h1: 'hold/cash の2状態DP。', h2: '売るときに fee を引く。', ref: 'fee=int(input())\nprices=list(map(int,input().split()))\nif not prices:\n    print(0)\nelse:\n    cash=0\n    hold=-prices[0]\n    for p in prices[1:]:\n        cash=max(cash,hold+p-fee)\n        hold=max(hold,cash-p)\n    print(cash)', tip: '手数料付きは2状態DP。売却時に fee を差し引くだけで貪欲的に最適化される。', ins: ['2\n1 3 2 8 4 9\n', '0\n1 2 3\n', '3\n1 2 3\n', '1\n5 4 3 2 1\n', '2\n1 3 7 5 10 3\n', '1\n1 4 2 8\n'] })

t({ lv: 708, concept: 'DP: 復号の方法数', title: '数字列の復号方法の数', tags: ['dp', '文字列'], io: '数字のみの文字列が1行で与えられます(1->A,...,26->Z)。', ask: 'その数字列を文字列に復号できる方法の数を出力してください。', h1: 'dp[i]=先頭i文字の復号数。', h2: '1桁(1-9)と2桁(10-26)の遷移を足す。', ref: 's=input()\nn=len(s)\nif n==0:\n    print(0)\nelse:\n    dp=[0]*(n+1)\n    dp[0]=1\n    dp[1]=1 if s[0]!="0" else 0\n    for i in range(2,n+1):\n        if s[i-1]!="0":\n            dp[i]+=dp[i-1]\n        two=int(s[i-2:i])\n        if 10<=two<=26:\n            dp[i]+=dp[i-2]\n    print(dp[n])', tip: '復号数DPは「1桁として読む/2桁として読む」の2遷移。0や27以上の扱いに注意。', ins: ['226\n', '12\n', '0\n', '06\n', '11106\n', '100\n'] })

t({ lv: 709, concept: 'DP: 部分列としての出現回数', title: 'tがsの部分列として現れる回数', tags: ['dp', '文字列'], io: '1行目に文字列 s、2行目に文字列 t が与えられます。', ask: 's の部分列として t が現れる場合の数を出力してください。', h1: 'dp[i][j]=s[:i]に現れるt[:j]の数。', h2: '文字一致なら dp[i-1][j-1] を足す。', ref: 's=input()\nt=input()\nn=len(s)\nm=len(t)\ndp=[[0]*(m+1) for _ in range(n+1)]\nfor i in range(n+1):\n    dp[i][0]=1\nfor i in range(1,n+1):\n    for j in range(1,m+1):\n        dp[i][j]=dp[i-1][j]\n        if s[i-1]==t[j-1]:\n            dp[i][j]+=dp[i-1][j-1]\nprint(dp[n][m])', tip: '部分列としての出現回数は2次元DP。一致時に「使う/使わない」を足し合わせる。', ins: ['rabbbit\nrabbit\n', 'babgbag\nbag\n', 'abc\nabc\n', 'abc\nd\n', 'aaa\na\n', 'aaa\naa\n'] })

t({ lv: 710, concept: '貪欲: 狭義増加にする最小増加量', title: '増やすだけで狭義増加にする最小コスト', tags: ['貪欲'], io: '整数列が1行で与えられます。', ask: '各要素を増やす操作だけで狭義単調増加列にするときの、増加量の合計の最小値を出力してください。', h1: '左から見て直前+1未満なら持ち上げる。', h2: '持ち上げた分を合計する。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nif n==0:\n    print(0)\nelse:\n    ops=0\n    prev=a[0]\n    for i in range(1,n):\n        need=prev+1\n        if a[i]<need:\n            ops+=need-a[i]\n            prev=need\n        else:\n            prev=a[i]\n    print(ops)', tip: '増加のみで狭義増加にする最小コストは「直前+1まで持ち上げる」貪欲。減らせない点が鍵。', ins: ['1 1 1\n', '1 5 2 4 1\n', '5\n', '1 2 3\n', '3 2 1\n', '8 4 6\n'] })

t({ lv: 711, concept: 'DP: 家の塗り分け最小費用', title: '3色で家を塗る最小費用', tags: ['dp'], io: '1行目に家の数 n、続く n 行に3色のコスト r g b が与えられます(隣家は別色)。', ask: '隣り合う家が異なる色になるように塗る最小費用を出力してください。', h1: 'dp[i][c]=i番目を色cで塗る最小費用。', h2: '隣は別色なので前の2色の小さい方を足す。', ref: 'n=int(input())\nif n==0:\n    print(0)\nelse:\n    costs=[list(map(int,input().split())) for _ in range(n)]\n    dp=costs[0][:]\n    for i in range(1,n):\n        ndp=[0,0,0]\n        ndp[0]=costs[i][0]+min(dp[1],dp[2])\n        ndp[1]=costs[i][1]+min(dp[0],dp[2])\n        ndp[2]=costs[i][2]+min(dp[0],dp[1])\n        dp=ndp\n    print(min(dp))', tip: '塗り分けDPは「各色で塗る最小費用」を持ち、隣は別色なので他2色の最小から遷移する。', ins: ['3\n17 2 17\n16 16 5\n14 3 19\n', '1\n5 8 6\n', '2\n1 2 3\n3 2 1\n', '2\n1 1 1\n1 1 1\n', '3\n1 1 1\n1 1 1\n1 1 1\n', '4\n1 5 3\n2 9 4\n6 1 7\n8 2 5\n'] })

t({ lv: 712, concept: 'DP: フェンスの塗り方', title: 'フェンスの塗り方の数', tags: ['dp'], io: 'n k が空白区切りで与えられます(n本の柱を k 色で塗る、同色は3本以上連続不可)。', ask: '塗り方の総数を出力してください。', h1: 'same(直前と同色)とdiff(別色)を持つ。', h2: 'same=前のdiff、diff=(same+diff)·(k-1)。', ref: 'n,k=map(int,input().split())\nif n==0:\n    print(0)\nelif n==1:\n    print(k)\nelse:\n    same=k\n    diff=k*(k-1)\n    for _ in range(3,n+1):\n        same,diff=diff,(same+diff)*(k-1)\n    print(same+diff)', tip: 'フェンス塗りは「直前と同色/別色」の2状態DP。同色は2連続まで(same=前のdiff)に制限する。', ins: ['3 2\n', '1 1\n', '2 4\n', '4 3\n', '0 5\n', '5 2\n'] })

t({ lv: 713, concept: 'DP: ドミノとトロミノの敷き詰め', title: '2×nをドミノとトロミノで敷く数', tags: ['dp'], io: '整数 n が1行で与えられます。', ask: '2×n の盤をドミノ(2×1)とトロミノ(L字)で敷き詰める方法の数を出力してください。', h1: '漸化式 f(n)=2·f(n-1)+f(n-3)。', h2: '初期値 f(0)=1,f(1)=1,f(2)=2。', ref: 'n=int(input())\nif n==0:\n    print(1)\nelif n==1:\n    print(1)\nelif n==2:\n    print(2)\nelse:\n    f=[1,1,2]\n    for i in range(3,n+1):\n        f.append(2*f[-1]+f[-3])\n    print(f[n])', tip: 'ドミノ＋トロミノの敷き詰めは f(n)=2f(n-1)+f(n-3) という漸化式に落ちる。', ins: ['3\n', '0\n', '1\n', '4\n', '5\n', '10\n'] })

t({ lv: 714, concept: 'DP: 3×nの完全タイル数', title: '3×nをドミノで敷く数', tags: ['dp'], io: '整数 n が1行で与えられます。', ask: '3×n の盤を 1×2 ドミノで完全に敷き詰める方法の数を出力してください(n が奇数なら0)。', h1: 'f(n)=4·f(n-2)-f(n-4)。', h2: '初期値 f(0)=1,f(2)=3。', ref: 'n=int(input())\nif n%2==1:\n    print(0)\nelif n==0:\n    print(1)\nelse:\n    f={0:1,2:3}\n    for i in range(4,n+1,2):\n        f[i]=4*f[i-2]-f[i-4]\n    print(f[n])', tip: '3×nの敷き詰めは f(n)=4f(n-2)-f(n-4)。奇数nは敷けない(面積が奇数)。', ins: ['2\n', '0\n', '1\n', '4\n', '6\n', '8\n'] })

t({ lv: 715, concept: 'DP: ダンジョンの最小初期体力', title: 'ダンジョンを抜ける最小初期HP', tags: ['dp'], io: '1行目に R C、続く R 行に各部屋の増減値(負は被ダメ)が与えられます。', ask: '左上から右下へ右・下に進み、常にHP>0を保つのに必要な最小初期HPを出力してください。', h1: '右下から後ろ向きDPする。', h2: 'dp[i][j]=max(1, min(右,下)-room)。', ref: 'first=input().split()\nR=int(first[0])\nC=int(first[1])\ng=[list(map(int,input().split())) for _ in range(R)]\nINF=float("inf")\ndp=[[INF]*(C+1) for _ in range(R+1)]\ndp[R][C-1]=1\ndp[R-1][C]=1\nfor i in range(R-1,-1,-1):\n    for j in range(C-1,-1,-1):\n        need=min(dp[i+1][j],dp[i][j+1])-g[i][j]\n        dp[i][j]=max(1,need)\nprint(dp[0][0])', tip: 'ダンジョンは「ゴールから逆算」するDP。各マスで必要最小HPを下流から決める。', ins: ['3 3\n-2 -3 3\n-5 -10 1\n10 30 -5\n', '1 1\n0\n', '1 1\n-5\n', '1 3\n1 -3 3\n', '2 2\n0 0\n0 0\n', '2 2\n-3 5\n1 -4\n'] })

t({ lv: 716, concept: 'DP: 最大の整除部分集合のサイズ', title: '整除関係をなす最大部分集合', tags: ['dp'], io: '相異なる正整数の列が1行で与えられます。', ask: '任意の2要素で一方が他方を割り切る最大の部分集合のサイズを出力してください。', h1: 'ソートしてLIS風DP。', h2: 'dp[i]=a[i]で終わる整除鎖の最大長。', ref: 'a=sorted(map(int,input().split()))\nn=len(a)\nif n==0:\n    print(0)\nelse:\n    dp=[1]*n\n    for i in range(n):\n        for j in range(i):\n            if a[i]%a[j]==0 and dp[j]+1>dp[i]:\n                dp[i]=dp[j]+1\n    print(max(dp))', tip: '整除部分集合はソートすると「割り切れる鎖」を作るLIS型DPになる。', ins: ['1 2 3\n', '1 2 4 8\n', '3 5 7\n', '1\n', '2 3 4 9 8\n', '4 8 10 240\n'] })

t({ lv: 717, concept: '配列: 最長の偶奇交互連続', title: '偶数と奇数が交互に続く最長連続', tags: ['配列'], io: '整数列が1行で与えられます。', ask: '隣接要素の偶奇(偶数/奇数)が交互に切り替わる最長の連続部分配列の長さを出力してください。', h1: '直前と偶奇が異なれば伸ばす。', h2: '同じならリセット。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nif n==0:\n    print(0)\nelse:\n    best=1\n    cur=1\n    for i in range(1,n):\n        if (a[i]%2)!=(a[i-1]%2):\n            cur+=1\n            if cur>best:\n                best=cur\n        else:\n            cur=1\n    print(best)', tip: '偶奇交互はリセット型の線形走査。値ではなく a%2 の切り替わりだけを見る。', ins: ['1 2 3 4\n', '1 3 5\n', '2 4 6\n', '1 2 2 3\n', '7\n', '1 2 3 3 4 5\n'] })

t({ lv: 718, concept: 'DP: 封筒のロシアンドール', title: '入れ子にできる封筒の最大数', tags: ['dp'], io: '1行目に n、続く n 行に封筒の幅 w・高さ h が与えられます。', ask: '(両方厳密に大きいとき入れ子可)入れ子にできる封筒の最大数を出力してください。', h1: '幅昇順・同幅は高さ降順にソート。', h2: '高さ列のLISの長さが答え。', ref: 'import bisect\nn=int(input())\nenv=[tuple(map(int,input().split())) for _ in range(n)]\nenv.sort(key=lambda x:(x[0],-x[1]))\ntails=[]\nfor w,h in env:\n    i=bisect.bisect_left(tails,h)\n    if i==len(tails):\n        tails.append(h)\n    else:\n        tails[i]=h\nprint(len(tails))', tip: '2次元の入れ子は「幅昇順・同幅は高さ降順」に並べて高さのLISに帰着する(同幅を入れ子にしない工夫)。', ins: ['4\n5 4\n6 4\n6 7\n2 3\n', '1\n1 1\n', '3\n1 1\n1 1\n1 1\n', '3\n1 2\n2 3\n3 4\n', '2\n4 5\n4 6\n', '5\n2 100\n3 200\n4 300\n5 250\n5 400\n'] })

t({ lv: 719, concept: 'DP: 石の最小残り重量', title: '石をぶつけ合った最小残り', tags: ['dp'], io: '石の重さの列が1行で与えられます。', ask: '2つずつぶつけて差を残す操作を繰り返したとき、最後に残る最小の重さを出力してください。', h1: '総和の半分以下で作れる最大和を求める。', h2: '答え = 総和 - 2·(その最大和)。', ref: 'a=list(map(int,input().split()))\ntotal=sum(a)\nhalf=total//2\ndp=[False]*(half+1)\ndp[0]=True\nfor x in a:\n    for s in range(half,x-1,-1):\n        if dp[s-x]:\n            dp[s]=True\nbest=0\nfor s in range(half,-1,-1):\n    if dp[s]:\n        best=s\n        break\nprint(total-2*best)', tip: '石の最小残りは「総和の半分に最も近い部分和」を作る問題(分割closest)に帰着する。', ins: ['2 7 4 1 8 1\n', '1\n', '1 1\n', '31 26 33 21 40\n', '2 2 2 2\n', '1 2 3 4 5\n'] })

t({ lv: 720, concept: 'DP: 0と1の予算ナップサック', title: '0と1の個数制限での最大文字列数', tags: ['dp'], io: '1行目に zeros ones、2行目に文字列数 n、続く n 行に "0"と"1"だけの文字列が与えられます。', ask: '使える0の数 zeros・1の数 ones を超えない範囲で選べる文字列の最大数を出力してください。', h1: '各文字列の0と1の個数を数える。', h2: '2次元(0の数,1の数)の0/1ナップサック。', ref: 'first=input().split()\nzeros=int(first[0])\nones=int(first[1])\nn=int(input())\nstrs=[input() for _ in range(n)]\ndp=[[0]*(ones+1) for _ in range(zeros+1)]\nfor s in strs:\n    c0=s.count("0")\n    c1=s.count("1")\n    for i in range(zeros,c0-1,-1):\n        for j in range(ones,c1-1,-1):\n            if dp[i-c0][j-c1]+1>dp[i][j]:\n                dp[i][j]=dp[i-c0][j-c1]+1\n    print\nprint(dp[zeros][ones])', tip: '2資源(0と1)の制約は2次元0/1ナップサック。各文字列の0・1個数を重さとみなす。', ins: ['5 3\n4\n10\n0001\n111001\n1\n', '1 1\n2\n10\n01\n', '0 0\n1\n0\n', '2 2\n3\n00\n11\n01\n', '3 0\n2\n0\n00\n', '1 1\n1\n10\n'] })

t({ lv: 721, concept: 'DP: 目標和になるサイコロの場合の数', title: 'd個のサイコロで目標和を作る数', tags: ['dp'], io: 'd f target が空白区切りで与えられます(d個の f 面サイコロ)。', ask: '出目の合計がちょうど target になる場合の数を出力してください。', h1: 'dp[i][s]=i個でsを作る数。', h2: '各サイコロで1..fを足す。', ref: 'd,f,target=map(int,input().split())\ndp=[0]*(target+1)\ndp[0]=1\nfor _ in range(d):\n    ndp=[0]*(target+1)\n    for s in range(target+1):\n        if dp[s]==0:\n            continue\n        for face in range(1,f+1):\n            if s+face<=target:\n                ndp[s+face]+=dp[s]\n    dp=ndp\nprint(dp[target])', tip: 'サイコロの和の場合の数は「個数を1つずつ増やす」DP。各段で1..f面分を配る。', ins: ['2 6 7\n', '1 6 3\n', '2 5 10\n', '1 2 3\n', '3 4 5\n', '2 6 1\n'] })

t({ lv: 722, concept: 'DP: ナイトダイヤルの番号数', title: 'ナイトが作る長さnの番号数', tags: ['dp'], io: '整数 n が1行で与えられます(電話キーパッド上をナイトが移動)。', ask: '長さ n の異なる番号(0-9の数字列)の数を出力してください。', h1: '各数字からナイトで行ける先を定義。', h2: 'dp[桁][数字]を遷移する。', ref: 'n=int(input())\nmoves={0:[4,6],1:[6,8],2:[7,9],3:[4,8],4:[0,3,9],5:[],6:[0,1,7],7:[2,6],8:[1,3],9:[2,4]}\nif n==0:\n    print(0)\nelse:\n    dp=[1]*10\n    for _ in range(n-1):\n        ndp=[0]*10\n        for d in range(10):\n            for nx in moves[d]:\n                ndp[nx]+=dp[d]\n        dp=ndp\n    print(sum(dp))', tip: 'ナイトダイヤルは「桁数×現在の数字」のDP。各数字からの桂馬移動先を遷移表にする。', ins: ['1\n', '2\n', '3\n', '4\n', '0\n', '6\n'] })

t({ lv: 723, concept: '桁DP: 桁和がmの倍数の数', title: '桁和がmの倍数になる数の個数', tags: ['桁DP', 'dp'], io: 'N m が空白区切りで与えられます(N は大きくてよい)。', ask: '0 以上 N 以下で、各桁の和が m の倍数になる整数の個数を出力してください。', h1: '上位桁から tight と桁和 mod m を状態に持つ。', h2: 'メモ化再帰で桁を決める。', ref: 'import sys\nsys.setrecursionlimit(10000)\nfrom functools import lru_cache\nN,m=input().split()\nm=int(m)\ndigits=[int(c) for c in N]\nL=len(digits)\n@lru_cache(maxsize=None)\ndef rec(pos,tight,mod):\n    if pos==L:\n        return 1 if mod==0 else 0\n    hi=digits[pos] if tight else 9\n    total=0\n    for d in range(hi+1):\n        total+=rec(pos+1,tight and d==hi,(mod+d)%m)\n    return total\nprint(rec(0,True,0))', tip: '桁和の倍数判定は桁DPで「桁和の mod m」を状態に持つ。0も桁和0で倍数に含まれる。', ins: ['20 3\n', '9 5\n', '100 1\n', '0 7\n', '50 9\n', '999 11\n'] })

t({ lv: 724, concept: 'DP: 連続0を含まない2進列', title: '00を含まない長さnの2進列', tags: ['dp'], io: '非負整数 n が1行で与えられます。', ask: '長さ n の2進文字列で "00"(0が2つ以上連続)を含まないものの数を出力してください。', h1: '末尾が0か1かで状態を持つ。', h2: 'end0=前のend1、end1=前のend0+end1。', ref: 'n=int(input())\nif n==0:\n    print(1)\nelse:\n    end0=1\n    end1=1\n    for _ in range(2,n+1):\n        end0,end1=end1,end0+end1\n    print(end0+end1)', tip: '「00禁止」は0の後は必ず1という制約。末尾の文字を状態にしたフィボナッチ型DP。', ins: ['1\n', '2\n', '3\n', '4\n', '5\n', '0\n'] })

t({ lv: 725, concept: 'DP: 削除して稼ぐ最大点', title: '同値を巻き込む削除の最大得点', tags: ['dp'], io: '整数列が1行で与えられます(値xを選ぶとx点、ただしx-1とx+1は全消去)。', ask: '得られる最大の合計点を出力してください。', h1: '値ごとの合計点を集計する。', h2: '値の数直線上でHouse Robber DP(隣を取れない)。', ref: 'from collections import Counter\na=list(map(int,input().split()))\nif not a:\n    print(0)\nelse:\n    cnt=Counter(a)\n    mx=max(a)\n    points=[0]*(mx+1)\n    for v,c in cnt.items():\n        points[v]=v*c\n    prev2=0\n    prev1=0\n    for v in range(mx+1):\n        cur=max(prev1,prev2+points[v])\n        prev2=prev1\n        prev1=cur\n    print(prev1)', tip: '「x-1とx+1が消える」制約は値の数直線上のHouse Robber。値ごとの合計点で隣接禁止DP。', ins: ['3 4 2\n', '2 2 3 3 3 4\n', '1\n', '1 1 1\n', '1 2 3 4 5\n', '5 5 5 5\n'] })

t({ lv: 726, concept: 'DP: 落下経路の最大和', title: '各列を遷移する最大落下和', tags: ['dp'], io: '1行目に n、続く n 行に n 個の整数(正方行列)が与えられます。', ask: '一番上の任意のマスから始め、各行で真下か斜め下に進み、底まで降りる経路和の最大値を出力してください。', h1: 'dp[i][j]=そのマスまでの最大和。', h2: '上の3マス(左上・上・右上)の最大から遷移。', ref: 'n=int(input())\ng=[list(map(int,input().split())) for _ in range(n)]\ndp=g[0][:]\nfor i in range(1,n):\n    ndp=[0]*n\n    for j in range(n):\n        best=dp[j]\n        if j>0 and dp[j-1]>best:\n            best=dp[j-1]\n        if j<n-1 and dp[j+1]>best:\n            best=dp[j+1]\n        ndp[j]=g[i][j]+best\n    dp=ndp\nprint(max(dp))', tip: '最大落下経路も各行で上3マスから遷移するDP。比較を max にするだけで最小版と双対。', ins: ['3\n2 1 3\n6 5 4\n7 8 9\n', '1\n5\n', '2\n1 2\n3 4\n', '3\n1 1 1\n1 1 1\n1 1 1\n', '2\n-1 -2\n-3 -4\n', '3\n10 10 10\n10 1 10\n10 10 10\n'] })

t({ lv: 727, concept: 'DP: ヒストグラム化で最大長方形', title: '0/1行列の最大全1長方形面積', tags: ['dp', 'スタック'], io: '1行目に R C、続く R 行に C 個の 0/1 が与えられます。', ask: 'すべて1で埋まった最大長方形の面積を出力してください。', h1: '各行を底とするヒストグラムの高さを累積。', h2: '行ごとに最大長方形(単調スタック)を求める。', ref: 'first=input().split()\nR=int(first[0])\nC=int(first[1])\nheights=[0]*C\nbest=0\nfor _ in range(R):\n    row=list(map(int,input().split()))\n    for j in range(C):\n        heights[j]=heights[j]+1 if row[j]==1 else 0\n    h=heights+[0]\n    stack=[]\n    for i in range(len(h)):\n        while stack and h[stack[-1]]>=h[i]:\n            ht=h[stack.pop()]\n            w=i if not stack else i-stack[-1]-1\n            if ht*w>best:\n                best=ht*w\n        stack.append(i)\nprint(best)', tip: '最大全1長方形は「各行を底にしたヒストグラムの最大長方形」をスタックで積み上げる。', ins: ['3 4\n1 0 1 0\n1 0 1 1\n1 1 1 1\n', '1 1\n1\n', '2 2\n0 0\n0 0\n', '1 4\n1 1 1 1\n', '3 3\n1 1 1\n1 1 1\n1 1 1\n', '2 3\n1 1 0\n1 1 0\n'] })

t({ lv: 728, concept: 'DP: 最長の正しい括弧列', title: '最長の対応する括弧の連続部分', tags: ['dp', '文字列'], io: '( と ) のみからなる文字列が1行で与えられます。', ask: '正しく対応がとれた最長の連続部分文字列の長さを出力してください。', h1: 'dp[i]=iで終わる最長の正しい括弧長。', h2: '直前の対応位置を辿って結合する。', ref: 's=input()\nn=len(s)\nif n==0:\n    print(0)\nelse:\n    dp=[0]*n\n    best=0\n    for i in range(1,n):\n        if s[i]==")":\n            if s[i-1]=="(":\n                dp[i]=(dp[i-2] if i>=2 else 0)+2\n            elif i-dp[i-1]-1>=0 and s[i-dp[i-1]-1]=="(":\n                dp[i]=dp[i-1]+2+(dp[i-dp[i-1]-2] if i-dp[i-1]-2>=0 else 0)\n            if dp[i]>best:\n                best=dp[i]\n    print(best)', tip: '最長の正しい括弧列は「)で終わる最長長」を持ち、直前の対応ブロックを連結するDP。', ins: ['(()\n', ')()())\n', '\n', '()(()\n', '()()\n', '((()))\n'] })

t({ lv: 729, concept: 'ゲームDP: 先手が勝てるか', title: '両端から取るゲームで先手が勝つか', tags: ['dp', 'ゲーム'], io: '得点の列が1行で与えられます(両端から交互に取る、合計が多い方が勝ち)。', ask: '最適戦略で先手が負けないなら yes、必ず負けるなら no を出力してください。', h1: 'dp[l][r]=先手の取り分-後手の取り分の最大。', h2: '両端どちらを取るかで a[l]-dp[l+1][r], a[r]-dp[l][r-1]。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nif n==0:\n    print("yes")\nelse:\n    dp=[[0]*n for _ in range(n)]\n    for i in range(n):\n        dp[i][i]=a[i]\n    for length in range(2,n+1):\n        for l in range(n-length+1):\n            r=l+length-1\n            dp[l][r]=max(a[l]-dp[l+1][r],a[r]-dp[l][r-1])\n    print("yes" if dp[0][n-1]>=0 else "no")', tip: 'ミニマックスは「自分の取り分−相手の取り分」を最大化する区間DPで表せる。差≥0なら先手は負けない。', ins: ['1 5 2\n', '1 5 233 7\n', '1 2\n', '5\n', '2 2 2 2\n', '3 9 1 2\n'] })

t({ lv: 730, concept: '区間DP: 棒を切る最小コスト', title: '棒を指定位置で切る最小コスト', tags: ['区間DP', 'dp'], io: '1行目に棒の長さ Lと切る回数 m、2行目に m 個の切断位置が与えられます(コストはその時の棒の長さ)。', ask: 'すべての位置で切る最小総コストを出力してください。', h1: '切断位置に0とLを加えてソート。', h2: 'dp[i][j]=区間(i,j)を切る最小コスト＝区間長+分割。', ref: 'first=input().split()\nL=int(first[0])\nm=int(first[1])\ncuts=sorted(map(int,input().split())) if m>0 else []\npts=[0]+cuts+[L]\nk=len(pts)\nINF=float("inf")\ndp=[[0]*k for _ in range(k)]\nfor length in range(2,k):\n    for i in range(k-length):\n        j=i+length\n        best=INF\n        for mid in range(i+1,j):\n            c=dp[i][mid]+dp[mid][j]\n            if c<best:\n                best=c\n        dp[i][j]=best+pts[j]-pts[i]\nprint(dp[0][k-1])', tip: '棒切りは区間DP。切る順序を「最初に切る位置」で場合分けし、区間長をコストに足す。', ins: ['7 3\n1 3 5\n', '10 1\n5\n', '5 0\n', '9 4\n5 6 1 8\n', '4 2\n1 3\n', '10 2\n2 8\n'] })

t({ lv: 731, concept: 'DP: 最長の語の連鎖', title: '最長の単語チェーンの長さ', tags: ['dp', '文字列'], io: '1行目に単語数 n、続く n 行に単語が与えられます(1文字挿入で次に繋がる)。', ask: '1文字挿入して別の語になる関係で繋がる最長チェーンの長さを出力してください。', h1: '短い順に並べる。', h2: '各語から1文字消した語が既知なら長さを更新。', ref: 'n=int(input())\nwords=[input() for _ in range(n)]\nwords.sort(key=len)\ndp={}\nbest=0\nfor w in words:\n    cur=1\n    for i in range(len(w)):\n        pred=w[:i]+w[i+1:]\n        if pred in dp and dp[pred]+1>cur:\n            cur=dp[pred]+1\n    dp[w]=cur\n    if cur>best:\n        best=cur\nprint(best)', tip: '語の連鎖は「1文字消した前駆」を辞書で引くDP。短い順に処理すると前駆が先に確定する。', ins: ['4\na\nba\nbca\nbda\n', '1\nx\n', '3\nxbc\npcxbcf\nxb\n', '2\nab\ncd\n', '5\na\nb\nba\nbca\nbdca\n', '3\nabcd\nab\nabc\n'] })

t({ lv: 732, concept: 'DP: 3つの非重複部分配列の最大和', title: '長さkの3つの非重複部分配列の最大和', tags: ['dp'], io: '1行目に k、2行目に整数列が与えられます。', ask: '長さ k の互いに重ならない3つの連続部分配列の和の最大合計を出力してください。', h1: '長さkの窓和を前計算。', h2: '左最良・右最良を持ち、中央の窓を全探索。', ref: 'k=int(input())\na=list(map(int,input().split()))\nn=len(a)\nW=[0]*(n-k+1)\ns=sum(a[:k])\nW[0]=s\nfor i in range(1,n-k+1):\n    s+=a[i+k-1]-a[i-1]\n    W[i]=s\nm=len(W)\nleft=[0]*m\nbest=0\nbi=0\nfor i in range(m):\n    if W[i]>W[bi]:\n        bi=i\n    left[i]=bi\nright=[0]*m\nbi=m-1\nfor i in range(m-1,-1,-1):\n    if W[i]>=W[bi]:\n        bi=i\n    right[i]=bi\nans=0\nfor j in range(k,m-k):\n    l=left[j-k]\n    r=right[j+k]\n    tot=W[l]+W[j]+W[r]\n    if tot>ans:\n        ans=tot\nprint(ans)', tip: '3つの非重複窓は「中央を固定し左右の最良窓」を前計算する。窓和はスライディングで O(n)。', ins: ['1\n1 2 1 2 6 7 5 1\n', '2\n1 2 1 2 6 7 5 1\n', '1\n1 1 1\n', '1\n7 1 7 1 7\n', '2\n4 5 10 6 11 17 4 11 1 3\n', '1\n1 2 3 4 5 6\n'] })

t({ lv: 733, concept: 'DP: 区切りで各片を最大値にした最大和', title: '長さk以下に区切る最大和', tags: ['dp'], io: '1行目に k、2行目に整数列が与えられます。', ask: '連続する長さ k 以下の片に分け、各片の全要素をその片の最大値に置き換えたときの総和の最大値を出力してください。', h1: 'dp[i]=先頭i個の最大和。', h2: '最後の片の長さを1..kで試し、片の最大値×長さを足す。', ref: 'k=int(input())\na=list(map(int,input().split()))\nn=len(a)\ndp=[0]*(n+1)\nfor i in range(1,n+1):\n    mx=0\n    best=0\n    for length in range(1,min(k,i)+1):\n        if a[i-length]>mx:\n            mx=a[i-length]\n        cand=dp[i-length]+mx*length\n        if cand>best:\n            best=cand\n    dp[i]=best\nprint(dp[n])', tip: '区切り最大化は「最後の片の長さ」で場合分けするDP。片の最大値を伸ばしながら更新する。', ins: ['3\n1 15 7 9 2 5 10\n', '1\n1 2 3\n', '4\n1 4 1 5 7 3 6 1 9 9 3\n', '2\n5\n', '3\n1 1 1\n', '2\n10 1 10 1\n'] })

t({ lv: 734, concept: 'DP: 本棚の最小高さ', title: '本を棚に並べる最小総高さ', tags: ['dp'], io: '1行目に棚幅 W と本の数 n、続く n 行に本の幅 w と高さ h が与えられます(順序は固定)。', ask: '本を順番通りに棚へ置き、各棚の幅 W を超えないようにしたときの棚の高さの合計の最小値を出力してください。', h1: 'dp[i]=先頭i冊の最小総高さ。', h2: '最後の棚に何冊置くかを後ろから試す。', ref: 'first=input().split()\nW=int(first[0])\nn=int(first[1])\nbooks=[tuple(map(int,input().split())) for _ in range(n)]\nINF=float("inf")\ndp=[0]+[INF]*n\nfor i in range(1,n+1):\n    width=0\n    height=0\n    j=i\n    while j>=1:\n        width+=books[j-1][0]\n        if width>W:\n            break\n        height=max(height,books[j-1][1])\n        if dp[j-1]+height<dp[i]:\n            dp[i]=dp[j-1]+height\n        j-=1\nprint(dp[n])', tip: '本棚DPは「最後の棚に入れる冊数」を後ろに伸ばしながら試す。順序固定が前提。', ins: ['4 3\n1 1\n2 3\n2 3\n', '10 1\n3 5\n', '5 4\n1 3\n2 4\n3 2\n1 5\n', '2 2\n1 10\n1 1\n', '6 3\n2 2\n2 2\n2 2\n', '3 2\n3 4\n3 2\n'] })

t({ lv: 735, concept: 'DP: 切符代の最小費用', title: '旅行日の切符代の最小費用', tags: ['dp'], io: '1行目に旅行日数 d と3つのパス料金 c1 c7 c30(1日/7日/30日券)、2行目に d 個の旅行日(昇順、1..365)が与えられます。', ask: 'すべての旅行日をカバーする最小費用を出力してください。', h1: 'dp[day]=その日までの最小費用。', h2: '旅行日でだけ更新し、1/7/30日前と比較。', ref: 'first=input().split()\nd=int(first[0])\nc1=int(first[1])\nc7=int(first[2])\nc30=int(first[3])\ndays=set(map(int,input().split())) if d>0 else set()\nif not days:\n    print(0)\nelse:\n    last=max(days)\n    dp=[0]*(last+1)\n    for day in range(1,last+1):\n        if day not in days:\n            dp[day]=dp[day-1]\n        else:\n            a=dp[day-1]+c1\n            b=dp[max(0,day-7)]+c7\n            c=dp[max(0,day-30)]+c30\n            dp[day]=min(a,b,c)\n    print(dp[last])', tip: '切符代DPは日付を軸に取り、旅行日でだけ1/7/30日券の選択肢を比較する。', ins: ['3 2 7 15\n1 4 6\n', '1 2 7 15\n1\n', '5 2 7 15\n1 2 3 4 5\n', '0 2 7 15\n', '8 2 7 15\n1 2 3 4 5 6 7 8\n', '2 5 7 15\n1 30\n'] })

t({ lv: 736, concept: 'DP: 3×nグリッドの彩色数', title: '3行n列を3色で塗る場合の数', tags: ['dp'], io: '整数 n が1行で与えられます(3行 n 列、上下左右の隣が異色)。', ask: '3色で隣接が異色になる塗り方の総数を出力してください。', h1: '1列の塗り方を「3色パターン」と「2色パターン」に分類。', h2: '列間遷移の係数(3->2が2,2->3が2,…)で漸化式。', ref: 'n=int(input())\nif n==0:\n    print(0)\nelse:\n    color3=6\n    color2=6\n    for _ in range(2,n+1):\n        ncolor3=color3*2+color2*2\n        ncolor2=color3*2+color2*3\n        color3=ncolor3\n        color2=ncolor2\n    print(color3+color2)', tip: '3×n彩色は1列を「3色使い/2色使い」に分けた2状態DP。遷移係数は次列の整合パターン数。', ins: ['1\n', '2\n', '3\n', '4\n', '0\n', '5\n'] })

t({ lv: 737, concept: 'DP: 非減少の母音文字列数', title: '辞書順非減少の母音文字列の数', tags: ['dp'], io: '整数 n が1行で与えられます(a<e<i<o<u の順、非減少に並べる)。', ask: '長さ n で母音が辞書順に非減少な文字列の数を出力してください。', h1: 'dp[母音]=その母音で終わる数。', h2: '次の文字はその母音以上だけ許す。', ref: 'n=int(input())\nif n==0:\n    print(0)\nelse:\n    dp=[1]*5\n    for _ in range(2,n+1):\n        ndp=[0]*5\n        for i in range(5):\n            for j in range(i,5):\n                ndp[j]+=dp[i]\n        dp=ndp\n    print(sum(dp))', tip: '非減少母音列は重複組合せ C(n+4,4) に等しいが、DPでも「末尾の母音」を状態に数えられる。', ins: ['1\n', '2\n', '3\n', '4\n', '5\n', '0\n'] })

t({ lv: 738, concept: 'DP: 最長の乱流部分配列', title: '符号が交互に変わる最長連続区間', tags: ['dp'], io: '整数列が1行で与えられます。', ask: '隣接比較(< と >)が交互に切り替わる最長の連続部分配列の長さを出力してください。', h1: 'up(直前が上昇)とdown(直前が下降)を持つ。', h2: '上昇なら up=down+1、下降なら down=up+1、等しいなら1。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nif n==0:\n    print(0)\nelse:\n    best=1\n    up=1\n    down=1\n    for i in range(1,n):\n        if a[i]>a[i-1]:\n            up=down+1\n            down=1\n        elif a[i]<a[i-1]:\n            down=up+1\n            up=1\n        else:\n            up=1\n            down=1\n        best=max(best,up,down)\n    print(best)', tip: '乱流(turbulent)は連続版ジグザグ。直前の比較向きで up/down を交互に伸ばす。', ins: ['9 4 2 10 7 8 8 1 9\n', '4 8 12 16\n', '100\n', '1 2 3 4\n', '2 0 2 4 2 5\n', '1 1 1\n'] })

t({ lv: 739, concept: 'DP: 等差連続部分列の数', title: '等差な連続部分配列の個数', tags: ['dp'], io: '整数列が1行で与えられます。', ask: '長さ3以上で公差一定の連続部分配列(arithmetic slice)の個数を出力してください。', h1: '連続して同じ差が続く長さを数える。', h2: '長さLの連続等差は (L-1)(L-2)/2 個の部分配列を生む(累積式)。', ref: 'a=list(map(int,input().split()))\nn=len(a)\ntotal=0\ncur=0\nfor i in range(2,n):\n    if a[i]-a[i-1]==a[i-1]-a[i-2]:\n        cur+=1\n        total+=cur\n    else:\n        cur=0\nprint(total)', tip: '等差連続部分列の数は「連続して同じ差が続くほど cur を増やして足す」累積カウントで O(n)。', ins: ['1 2 3 4\n', '1 3 5 7 9\n', '1 2 3\n', '1 2 4\n', '7\n', '2 4 6 8 10\n'] })

t({ lv: 740, concept: 'DP: 全1正方形の総数', title: '全1正方形の小行列の総数', tags: ['dp'], io: '1行目に R C、続く R 行に C 個の 0/1 が与えられます。', ask: 'すべて1で埋まった正方形(あらゆるサイズ)の総数を出力してください。', h1: 'dp[i][j]=右下が(i,j)の最大正方形の辺。', h2: '各dp値はその位置を右下とする正方形の個数に等しいので総和。', ref: 'first=input().split()\nR=int(first[0])\nC=int(first[1])\nmat=[list(map(int,input().split())) for _ in range(R)]\ndp=[[0]*C for _ in range(R)]\ntotal=0\nfor i in range(R):\n    for j in range(C):\n        if mat[i][j]==1:\n            if i==0 or j==0:\n                dp[i][j]=1\n            else:\n                dp[i][j]=min(dp[i-1][j],dp[i][j-1],dp[i-1][j-1])+1\n            total+=dp[i][j]\nprint(total)', tip: '正方形の「個数」は各dp値を足すだけ(右下が(i,j)の正方形は dp[i][j] 個)。最大辺問題の自然な拡張。', ins: ['3 4\n0 1 1 1\n1 1 1 1\n0 1 1 1\n', '1 1\n1\n', '2 2\n1 1\n1 1\n', '2 2\n0 0\n0 0\n', '1 4\n1 1 1 1\n', '3 3\n1 1 1\n1 1 1\n1 1 1\n'] })

t({ lv: 741, concept: 'DP: 指定XORの部分集合数', title: 'XORが目標になる部分集合の数', tags: ['dp', 'bit演算'], io: '1行目に target、2行目に非負整数列が与えられます。', ask: '部分集合のXORがちょうど target になる選び方の数を出力してください(空集合のXORは0)。', h1: 'dp[x]=XORがxになる部分集合の数。', h2: '各要素で dp[x] と dp[x^a] を合わせる。', ref: 'target=int(input())\na=list(map(int,input().split()))\nmaxx=1\nfor x in a:\n    while maxx<=x:\n        maxx<<=1\nif target>=maxx:\n    maxx=target+1\ndp=[0]*maxx\ndp[0]=1\nfor x in a:\n    ndp=[0]*maxx\n    for v in range(maxx):\n        if dp[v]:\n            ndp[v]+=dp[v]\n            ndp[v^x]+=dp[v]\n    dp=ndp\nprint(dp[target] if target<maxx else 0)', tip: 'XOR部分集合数はXOR値を添字にしたDP。各要素で「使う/使わない」を畳み込む。', ins: ['0\n1 2 3\n', '3\n1 2 3\n', '6\n1 2 3\n', '0\n0 0\n', '1\n1 1\n', '5\n1 4 5\n'] })

t({ lv: 742, concept: 'bit: 2要素の最大XOR', title: '2つの要素の最大XOR', tags: ['bit演算'], io: '非負整数の列が1行で与えられます。', ask: '2要素を選んだときのXORの最大値を出力してください(要素1個なら0)。', h1: '全ペアのXORを比べる。', h2: '最大を取る(高度にはトライ木で O(n log)).', ref: 'a=list(map(int,input().split()))\nn=len(a)\nbest=0\nfor i in range(n):\n    for j in range(i+1,n):\n        x=a[i]^a[j]\n        if x>best:\n            best=x\nprint(best)', tip: '2要素の最大XORは全ペアで O(n²)。ビットトライ木を使うと O(n·bit) に落ちる。', ins: ['3 10 5 25 2 8\n', '0\n', '1 2\n', '5 5 5\n', '8 1\n', '14 70 53 83 49 91 36 80 92 51 66 70\n'] })

t({ lv: 743, concept: 'DP: カエルの川渡り', title: '石を跳んで川を渡れるか', tags: ['dp'], io: '石の位置の昇順列が1行で与えられます(最初の一歩は1、以降は前回±1か同じ歩幅)。', ask: '最後の石に到達できるなら yes、できないなら no を出力してください。', h1: '各石に到達可能な歩幅集合を持つ。', h2: '各歩幅から k-1,k,k+1 先の石へ遷移。', ref: 's=list(map(int,input().split()))\nstones=set(s)\nlast=s[-1]\nif len(s)>=2 and s[1]!=1:\n    print("no")\nelse:\n    from collections import defaultdict\n    jumps=defaultdict(set)\n    jumps[s[0]].add(0)\n    reachable=False\n    for pos in s:\n        for k in list(jumps[pos]):\n            for nk in (k-1,k,k+1):\n                if nk>0 and pos+nk in stones:\n                    jumps[pos+nk].add(nk)\n    print("yes" if len(jumps[last])>0 and last!=s[0] or len(s)==1 else "no")', tip: 'カエルの川渡りは「各石に到達できる歩幅の集合」を持つDP。歩幅は前回の±1か同じ。', ins: ['0 1 3 5 6 8 12 17\n', '0 1 2 3 4 8 9 11\n', '0 1\n', '0 2\n', '0\n', '0 1 3 6 10 15 16 21\n'] })

t({ lv: 744, concept: '窓: 両端からk枚で最大得点', title: '両端からk枚取る最大得点', tags: ['配列'], io: '1行目に k、2行目に得点の列が与えられます。', ask: '左右どちらかの端からちょうど k 枚取るときの得点合計の最大値を出力してください。', h1: '取らずに残す中央の連続 n-k 枚を考える。', h2: '全体和 - (長さ n-k の最小窓和) が最大得点。', ref: 'k=int(input())\na=list(map(int,input().split()))\nn=len(a)\ntotal=sum(a)\nif k>=n:\n    print(total)\nelse:\n    w=n-k\n    cur=sum(a[:w])\n    mn=cur\n    for i in range(w,n):\n        cur+=a[i]-a[i-w]\n        if cur<mn:\n            mn=cur\n    print(total-mn)', tip: '両端からk枚は「残す中央の連続 n-k 枚を最小化」と同じ。最小窓和を引けばよい。', ins: ['3\n1 2 3 4 5 6 1\n', '1\n100\n', '2\n1 2 3 4 5 6\n', '6\n1 2 3 4 5 6\n', '1\n5 5 5\n', '4\n9 7 7 9 7 7 9\n'] })

t({ lv: 745, concept: 'bitmask: 重複なし連結の最大長', title: '文字が重複しない連結文字列の最大長', tags: ['bit演算', 'dp'], io: '1行目に単語数 n、続く n 行に英小文字の単語が与えられます。', ask: '一部を選んで連結し、文字が重複しない最大の長さを出力してください。', h1: '各単語を文字集合のビットマスクにする(重複文字を含む語は除外)。', h2: '互いに素なマスクだけ結合し最大長を探す。', ref: 'n=int(input())\nwords=[input() for _ in range(n)]\nmasks=[]\nfor w in words:\n    m=0\n    ok=True\n    for ch in w:\n        b=1<<(ord(ch)-97)\n        if m&b:\n            ok=False\n            break\n        m|=b\n    if ok:\n        masks.append((m,len(w)))\ndp=[(0,0)]\nbest=0\nfor m,l in masks:\n    new=[]\n    for em,el in dp:\n        if em&m==0:\n            nm=em|m\n            nl=el+l\n            new.append((nm,nl))\n            if nl>best:\n                best=nl\n    dp+=new\nprint(best)', tip: '文字集合をビットマスクで持ち、互いに素(AND=0)なものだけ結合する部分集合DP。', ins: ['3\ncha\nr\nact\n', '2\nun\niq\n', '1\naa\n', '2\nabc\nabc\n', '4\na\nb\nc\nd\n', '2\nyy\nbkhwmpbiisbldzknpm\n'] })

t({ lv: 746, concept: '貪欲: ラベルの分割数', title: '同じ文字を1区画に収める分割数', tags: ['貪欲'], io: '英小文字の文字列が1行で与えられます。', ask: '各文字が高々1つの区画にのみ現れるように分割するときの、区画の最大個数を出力してください。', h1: '各文字の最後の出現位置を記録する。', h2: '走査して現区画の終端を伸ばし、到達したら切る。', ref: 's=input()\nlast={ch:i for i,ch in enumerate(s)}\ncnt=0\nstart=0\nend=0\nfor i,ch in enumerate(s):\n    if last[ch]>end:\n        end=last[ch]\n    if i==end:\n        cnt+=1\n        end=i\nprint(cnt)', tip: 'ラベル分割は各文字の最終出現位置まで区画を伸ばす貪欲。区画末尾に到達したら切る。', ins: ['ababcbacadefegdehijhklij\n', 'a\n', 'abc\n', 'aaa\n', 'eccbbbbdec\n', 'abcabc\n'] })

t({ lv: 747, concept: 'DP: 単調な3つ組の数', title: '増加または減少する3つ組の数', tags: ['dp'], io: '相異なる整数の列が1行で与えられます。', ask: 'i<j<k で a[i]<a[j]<a[k] または a[i]>a[j]>a[k] となる組の数を出力してください。', h1: '各 j を中央とみなす。', h2: '左の小さい数×右の大きい数 + 左の大きい数×右の小さい数。', ref: 'a=list(map(int,input().split()))\nn=len(a)\ntotal=0\nfor j in range(n):\n    less_left=sum(1 for i in range(j) if a[i]<a[j])\n    greater_left=j-less_left\n    less_right=sum(1 for k in range(j+1,n) if a[k]<a[j])\n    greater_right=(n-j-1)-less_right\n    total+=less_left*greater_right+greater_left*less_right\nprint(total)', tip: '単調3つ組は「中央 j」を固定し、左右の大小個数の積を足す O(n²) の数え上げ。', ins: ['2 5 3 4 1\n', '2 1 3\n', '1 2 3\n', '3 2 1\n', '5\n', '1 5 2 4 3\n'] })

t({ lv: 748, concept: 'DP: 2列を増加にする最小スワップ', title: '2列を同時に増加させる最小交換', tags: ['dp'], io: '1行目に列A、2行目に列B(同じ長さ)が与えられます(同位置どうしを入れ替え可)。', ask: '両方を狭義増加にするための最小の位置交換回数を出力してください(常に可能と仮定)。', h1: 'keep(交換しない)/swap(交換する)の2状態。', h2: '直前との大小関係で許される遷移を選ぶ。', ref: 'A=list(map(int,input().split()))\nB=list(map(int,input().split()))\nn=len(A)\nINF=float("inf")\nkeep=0\nswap=1\nfor i in range(1,n):\n    nkeep=INF\n    nswap=INF\n    if A[i]>A[i-1] and B[i]>B[i-1]:\n        nkeep=min(nkeep,keep)\n        nswap=min(nswap,swap+1)\n    if A[i]>B[i-1] and B[i]>A[i-1]:\n        nkeep=min(nkeep,swap)\n        nswap=min(nswap,keep+1)\n    keep=nkeep\n    swap=nswap\nprint(min(keep,swap))', tip: '2列同時増加は「各位置で交換するか」の2状態DP。直前の大小2パターンで遷移を許可する。', ins: ['1 3 5 4\n1 2 3 7\n', '0 3 5 8 9\n2 1 4 6 9\n', '1\n2\n', '1 2\n3 4\n', '2 1\n1 2\n', '1 5 10 20\n5 10 15 20\n'] })

t({ lv: 749, concept: 'DP: 最小コストでn段目に到達', title: '飛び石の最小到達コスト(任意歩幅)', tags: ['dp'], io: '1行目に最大歩幅 k、2行目に各マスのコスト(マス0からn-1)が与えられます(マス i から最大 k 先へ、入ったマスのコストを払う)。', ask: 'マス0から最後のマスへ到達する最小総コスト(始点も含む)を出力してください。', h1: 'dp[i]=マスiに来る最小コスト。', h2: 'dp[i]=cost[i]+min(dp[i-1..i-k])。', ref: 'k=int(input())\ncost=list(map(int,input().split()))\nn=len(cost)\nINF=float("inf")\ndp=[INF]*n\ndp[0]=cost[0]\nfor i in range(1,n):\n    best=INF\n    for j in range(1,k+1):\n        if i-j>=0 and dp[i-j]<best:\n            best=dp[i-j]\n    dp[i]=cost[i]+best\nprint(dp[n-1])', tip: '任意歩幅の最小到達コストは「直前k個の最小」から遷移するDP。単調デックで O(n) 化もできる。', ins: ['2\n1 2 3 1 5\n', '1\n1 2 3\n', '3\n5 1 1 1 9\n', '2\n10\n', '2\n0 0 0\n', '3\n1 100 1 1 100 1\n'] })

export const CATALOG = TASKS
