// 生成タスク 第23波：lv106〜129 の空き段を別計算で埋める。既存と重複しない概念のみ。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 106, concept: 'リスト: 最大ギャップ', title: 'ソート後の隣接差の最大', tags: ['list', 'ソート'], io: '2個以上の整数列が1行で与えられます。', ask: '昇順に並べたとき隣り合う値の差の最大を出力してください。', h1: 'まずソート。', h2: '隣接差の最大。', ref: 'a=sorted(map(int,input().split()))\nprint(max(a[i+1]-a[i] for i in range(len(a)-1)))', ins: ['3 6 1 9\n', '1 2 3\n', '10 1\n', '5 5 5\n', '100 1 50\n', '4 2 8 6\n'] })
t({ lv: 107, concept: 'リスト: 過半数の有無', title: '過半数を占める値があるか', tags: ['collections'], io: '整数列が1行で与えられます。', ask: '半数より多く出現する値があれば yes、なければ no を出力してください。', h1: '最頻値の回数。', h2: '回数×2 > 個数 か。', ref: 'from collections import Counter\na=list(map(int,input().split()))\nc=Counter(a)\nprint("yes" if c.most_common(1)[0][1]*2>len(a) else "no")', ins: ['1 1 1 2\n', '1 2 3\n', '5 5\n', '7\n', '2 2 1 1 2\n', '3 3 4 4\n'] })
t({ lv: 108, concept: 'リスト: ペアの積の最大', title: '2要素の積の最大', tags: ['list', 'ソート'], io: '2個以上の整数列が1行で与えられます。', ask: '2要素を選んだ積の最大を出力してください (負×負も考慮)。', h1: '最小2つの積か最大2つの積。', h2: 'ソートして両端。', ref: 'a=sorted(map(int,input().split()))\nprint(max(a[0]*a[1],a[-1]*a[-2]))', ins: ['1 5 3 2\n', '-5 -4 1 2\n', '3 4\n', '-1 -2 -3\n', '0 0 5\n', '-10 1 2\n'] })
t({ lv: 109, concept: 'リスト: 積の符号', title: '全要素の積の符号', tags: ['list'], io: '整数列が1行で与えられます。', ask: '全要素の積が正なら1、負なら-1、0を含むなら0を出力してください。', h1: '0があれば0。', h2: '負の個数の偶奇。', ref: 'a=list(map(int,input().split()))\nneg=sum(1 for x in a if x<0)\nprint(0 if 0 in a else (-1 if neg%2 else 1))', ins: ['1 2 3\n', '-1 2 3\n', '-1 -2 3\n', '0 5\n', '-1 -2 -3\n', '2 -2\n'] })
t({ lv: 111, concept: '評価: 二乗誤差和', title: '二乗誤差の和 (SSE)', tags: ['データ分析'], io: '予測値の列と実測値の列が各行で与えられます (同じ長さ)。', ask: '対応する差の2乗の総和を出力してください。', h1: '(予測−実測)²。', h2: '合計。', ref: 'a=list(map(int,input().split()))\nb=list(map(int,input().split()))\nprint(sum((x-y)**2 for x,y in zip(a,b)))', ins: ['1 2 3\n1 2 3\n', '1 2 3\n2 2 2\n', '0 0\n3 4\n', '5\n5\n', '1 2\n4 6\n', '10 20\n12 18\n'] })
t({ lv: 112, concept: '評価: 平均絶対誤差', title: '平均絶対誤差 (MAE)', tags: ['データ分析'], io: '予測値の列と実測値の列が各行で与えられます。', ask: '対応する差の絶対値の平均を小数2桁で出力してください。', h1: '|予測−実測| の平均。', h2: '和÷個数。', ref: 'a=list(map(int,input().split()))\nb=list(map(int,input().split()))\nprint(f"{sum(abs(x-y) for x,y in zip(a,b))/len(a):.2f}")', ins: ['1 2 3\n1 2 3\n', '1 2 3\n2 2 2\n', '0 0\n3 4\n', '5\n8\n', '1 2\n4 6\n', '10 20\n12 18\n'] })
t({ lv: 113, concept: '評価: 正解率', title: '正解率 (accuracy)', tags: ['データ分析'], io: '予測ラベルの列と正解ラベルの列が各行で与えられます。', ask: '一致した割合を小数2桁で出力してください。', h1: '一致数を数える。', h2: '÷個数。', ref: 'a=input().split()\nb=input().split()\nprint(f"{sum(1 for x,y in zip(a,b) if x==y)/len(a):.2f}")', ins: ['1 0 1 1\n1 0 0 1\n', 'a b c\na b c\n', '1 1\n0 0\n', 'x\nx\n', '1 2 3\n1 9 3\n', 'yes no\nno no\n'] })
t({ lv: 114, concept: '評価: 最大絶対誤差', title: '最大絶対誤差', tags: ['データ分析'], io: '予測値の列と実測値の列が各行で与えられます。', ask: '対応する差の絶対値の最大を出力してください。', h1: '|予測−実測| の最大。', h2: 'max。', ref: 'a=list(map(int,input().split()))\nb=list(map(int,input().split()))\nprint(max(abs(x-y) for x,y in zip(a,b)))', ins: ['1 2 3\n1 2 3\n', '1 2 3\n2 2 2\n', '0 0\n3 4\n', '5\n9\n', '1 2\n4 6\n', '10 20\n12 30\n'] })
t({ lv: 118, concept: '数論: 平方数の約数', title: '平方数である約数の個数', tags: ['数論'], io: '正の整数 n が与えられます。', ask: 'n の約数のうち平方数 (1,4,9,…) であるものの個数を出力してください。', h1: '約数を調べる。', h2: 'isqrt で平方数判定。', ref: 'import math\nn=int(input())\nprint(sum(1 for i in range(1,n+1) if n%i==0 and math.isqrt(i)**2==i))', ins: ['12\n', '36\n', '1\n', '100\n', '7\n', '48\n'] })
t({ lv: 119, concept: '整数: 桁の交代和', title: '各桁の交代和', tags: ['整数'], io: '非負整数 n が与えられます。', ask: '上の桁から +,-,+,- と符号を交互につけた和を出力してください。', h1: 'enumerate で位置の偶奇。', h2: '(-1)^i を掛ける。', ref: 'n=input()\nprint(sum((-1)**i*int(c) for i,c in enumerate(n)))', ins: ['1234\n', '11\n', '5\n', '909\n', '1010\n', '98\n'] })
t({ lv: 121, concept: '全探索: 部分集合和の種類', title: '部分集合の和の種類数', tags: ['bit全探索'], io: '整数列が1行で与えられます。', ask: '部分集合 (空集合含む) の和として作れる相異なる値の個数を出力してください。', h1: '和の集合を育てる。', h2: '各要素で {s, s+x} に拡張。', ref: 'a=list(map(int,input().split()))\nsums={0}\nfor x in a:\n    sums|={s+x for s in sums}\nprint(len(sums))', ins: ['1 2 3\n', '1 1 1\n', '5\n', '2 4\n', '1 2 4\n', '3 3 3\n'] })
t({ lv: 122, concept: '全探索: 原点最近点', title: '原点に最も近い点', tags: ['全探索', '幾何'], io: '1行目に点数 N、続く N 行に座標 x y が与えられます。', ask: '原点に最も近い点の「距離の2乗」を出力してください。', h1: '各点 x²+y²。', h2: 'その最小。', ref: 'n=int(input())\nbest=10**18\nfor _ in range(n):\n    x,y=map(int,input().split())\n    best=min(best,x*x+y*y)\nprint(best)', ins: ['3\n1 1\n3 4\n0 5\n', '1\n5 12\n', '2\n-1 0\n0 -1\n', '2\n10 10\n1 1\n', '1\n0 0\n', '3\n3 4\n6 8\n1 1\n'] })
t({ lv: 123, concept: '全探索: 部分集合和=K', title: '和がKの部分集合の個数 (bit全探索)', tags: ['bit全探索'], io: '1行目に n k、2行目に n 個の整数が与えられます。', ask: '和がちょうど k になる部分集合 (空集合含む) の個数を出力してください。', h1: '2ⁿ 通りを全列挙。', h2: 'mask>>i&1 で採用判定。', ref: 'n,k=map(int,input().split())\na=list(map(int,input().split()))\ncnt=0\nfor m in range(1<<n):\n    s=sum(a[i] for i in range(n) if m>>i&1)\n    if s==k:\n        cnt+=1\nprint(cnt)', ins: ['3 3\n1 2 3\n', '4 5\n1 2 3 4\n', '3 0\n1 2 3\n', '2 10\n5 5\n', '3 6\n1 2 3\n', '4 4\n2 2 2 2\n'] })
t({ lv: 124, concept: '全探索: 差がKのペア', title: '差が K のペアの個数', tags: ['ハッシュ'], io: '1行目に n k (k>=0)、2行目に n 個の整数が与えられます。', ask: '差がちょうど k になる値の組 (順不同) の個数を出力してください (同じ値の組も数える)。', h1: 'Counter で個数。', h2: 'k=0 は同値の組合せ、それ以外は c[x]·c[x+k]。', ref: 'from collections import Counter\nn,k=map(int,input().split())\na=list(map(int,input().split()))\nc=Counter(a)\nif k==0:\n    print(sum(v*(v-1)//2 for v in c.values()))\nelse:\n    print(sum(c[x]*c[x+k] for x in c))', ins: ['5 1\n1 2 3 4 5\n', '4 0\n1 1 2 2\n', '3 2\n1 3 5\n', '3 5\n1 2 3\n', '4 1\n1 1 1 1\n', '5 2\n1 3 3 5 5\n'] })
t({ lv: 125, concept: '数論: 区間内の平方数', title: '区間内の平方数の個数', tags: ['数論'], io: '整数 a b (1<=a<=b) が空白区切りで与えられます。', ask: 'a 以上 b 以下の平方数の個数を出力してください。', h1: 'isqrt(b)-isqrt(a-1)。', h2: '平方根の差。', ref: 'import math\na,b=map(int,input().split())\nprint(math.isqrt(b)-math.isqrt(a-1))', ins: ['1 10\n', '4 9\n', '2 3\n', '1 100\n', '50 50\n', '10 20\n'] })
t({ lv: 126, concept: '数論: 奇数の約数', title: '奇数の約数の個数', tags: ['数論'], io: '正の整数 n が与えられます。', ask: 'n の正の約数のうち奇数のものの個数を出力してください。', h1: '約数を調べる。', h2: '奇数だけ数える。', ref: 'n=int(input())\nprint(sum(1 for i in range(1,n+1) if n%i==0 and i%2==1))', ins: ['12\n', '15\n', '8\n', '100\n', '7\n', '36\n'] })
t({ lv: 127, concept: '数論: 区間の総和', title: '区間 [a,b] の整数の和', tags: ['数論'], io: '整数 a b (a<=b) が空白区切りで与えられます。', ask: 'a 以上 b 以下の整数の総和を出力してください。', h1: '等差数列の和。', h2: '(a+b)(個数)/2。', ref: 'a,b=map(int,input().split())\nprint((a+b)*(b-a+1)//2)', ins: ['1 10\n', '5 5\n', '0 100\n', '3 7\n', '-2 2\n', '10 20\n'] })
t({ lv: 128, concept: '数論: 区間内の偶数の個数', title: '区間 [a,b] の偶数の個数', tags: ['数論'], io: '整数 a b (0<=a<=b) が空白区切りで与えられます。', ask: 'a 以上 b 以下の偶数の個数を出力してください。', h1: 'b までの偶数 − (a-1) までの偶数。', h2: 'b//2-(a-1)//2。', ref: 'a,b=map(int,input().split())\nprint(b//2-(a-1)//2)', ins: ['1 10\n', '2 8\n', '0 0\n', '5 5\n', '1 1\n', '3 9\n'] })
t({ lv: 129, concept: '数論: 区間内の倍数の和', title: '区間 [a,b] の k の倍数の和', tags: ['数論'], io: '整数 a b k が空白区切りで与えられます。', ask: 'a 以上 b 以下で k の倍数である数の総和を出力してください。', h1: 'a..b を調べる。', h2: 'k で割り切れるものを足す。', ref: 'a,b,k=map(int,input().split())\nprint(sum(x for x in range(a,b+1) if x%k==0))', ins: ['1 10 3\n', '1 20 5\n', '5 5 5\n', '1 100 7\n', '2 8 2\n', '10 30 10\n'] })

export const CATALOG = TASKS
