// 生成タスク 第57波：各レベル2問化フェーズ(12)。lv591〜599, lv601〜615 に2問目を追加。
// 貪欲/木/区間/MST/最短路帯。重複なし・決定的・採点一意。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 591, concept: '貪欲: 2列を織り交ぜて辞書順最小', title: '2つの文字列の最小マージ', tags: ['貪欲', '文字列'], io: '1行目と2行目に英小文字の文字列が与えられます。', ask: '2つの文字列を、それぞれの文字の順序を保ったまま織り交ぜてできる文字列のうち、辞書順最小のものを出力してください。', h1: '先頭の文字だけ比べると同点のとき壊れる。', h2: '「残りの接尾辞どうし」を比較して小さい方から1文字取る。', ref: 's=input()\nt=input()\nres=[]\ni=j=0\nwhile i<len(s) and j<len(t):\n    if s[i:]<t[j:]:\n        res.append(s[i])\n        i+=1\n    else:\n        res.append(t[j])\n        j+=1\nres.append(s[i:])\nres.append(t[j:])\nprint("".join(res))', tip: '先頭文字が同じときは先の文字まで見ないと決められない。接尾辞全体の比較に置き換えると貪欲が正しくなる、マージ系の有名な罠。', ins: ['ba\nbc\n', 'ab\nab\n', 'ca\ncb\n', 'b\na\n', 'aa\na\n', 'xy\nz\n'] })

t({ lv: 592, concept: '貪欲: k回の符号反転で和最大', title: 'ちょうどk回符号を反転して和最大', tags: ['貪欲'], io: '1行目に反転回数 k、2行目に整数列が与えられます。', ask: 'ちょうど k 回、要素を1つ選んで符号を反転する(同じ要素を複数回選んでもよい)ときの、合計の最大値を出力してください。', h1: '小さい順に負の数を正へ反転するのが得。', h2: '回数が余ったら、絶対値最小の要素に残り全部を使う(偶数回なら実質0回)。', ref: 'k=int(input())\na=sorted(map(int,input().split()))\ni=0\nwhile k>0 and i<len(a) and a[i]<0:\n    a[i]=-a[i]\n    i+=1\n    k-=1\nif k%2==1:\n    a.sort()\n    a[0]=-a[0]\nprint(sum(a))', tip: '「余った操作は同じ場所で往復して消化する」偶奇の吸収がポイント。0があれば残り回数は何回でも無害に消せる。', ins: ['1\n4 2 3\n', '3\n-1 -3 2\n', '2\n-1 -2 -3\n', '1\n0 5\n', '4\n1 1\n', '2\n-5 4\n'] })

t({ lv: 593, concept: '木: 葉と葉の最短距離', title: '最も近い葉どうしの距離', tags: ['木', 'BFS'], io: '1行目に頂点数 n (n≥2)、続く n−1 行に木の辺が与えられます。', ask: '葉(次数1の頂点)の組のうち、距離が最小のものの距離を出力してください。', h1: '葉を列挙し、それぞれからBFSする。', h2: '葉から他の葉への距離の最小を取る。', ref: 'from collections import deque\nn=int(input())\ng=[[] for _ in range(n+1)]\ndeg=[0]*(n+1)\nfor _ in range(n-1):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\n    deg[u]+=1\n    deg[v]+=1\nleaves=[v for v in range(1,n+1) if deg[v]==1]\nbest=None\nfor s in leaves:\n    dist=[-1]*(n+1)\n    dist[s]=0\n    q=deque([s])\n    while q:\n        x=q.popleft()\n        for y in g[x]:\n            if dist[y]<0:\n                dist[y]=dist[x]+1\n                q.append(y)\n    for tt in leaves:\n        if tt!=s and (best is None or dist[tt]<best):\n            best=dist[tt]\nprint(best)', tip: '最遠の葉ペア(直径)と対になる最近の葉ペア。大きな木では「各頂点で異なる子部分木の最浅の葉を2つ合成する」木DPでO(n)にできる。', ins: ['2\n1 2\n', '4\n1 2\n2 3\n3 4\n', '4\n1 2\n1 3\n1 4\n', '5\n1 2\n2 3\n2 4\n3 5\n', '6\n1 2\n2 3\n3 4\n4 5\n5 6\n', '5\n1 2\n2 3\n2 4\n4 5\n'] })

t({ lv: 594, concept: 'グラフ: 到達できる頂点の最大価値', title: 'たどり着ける場所の最高の価値', tags: ['グラフ', 'BFS'], io: '1行目に n m s、2行目に各頂点の価値、続く m 行に有向辺が与えられます。', ask: '頂点 s から到達できる頂点(s自身を含む)の価値の最大を出力してください。', h1: '到達可能集合をBFS/DFSで求める。', h2: '訪れた頂点の価値の最大を持ち回る。', ref: 'from collections import deque\nn,m,s=map(int,input().split())\nval=list(map(int,input().split()))\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\nseen=[False]*(n+1)\nseen[s]=True\nq=deque([s])\nbest=val[s-1]\nwhile q:\n    x=q.popleft()\n    for y in g[x]:\n        if not seen[y]:\n            seen[y]=True\n            if val[y-1]>best:\n                best=val[y-1]\n            q.append(y)\nprint(best)', tip: '「到達可能集合の上の集計」は探索しながら畳み込むとメモリも手間も最小。集計をmaxからsum・countに替えるだけで様々な問題になる。', ins: ['4 3 1\n1 5 3 9\n1 2\n2 3\n3 1\n', '3 2 2\n7 1 4\n2 3\n3 1\n', '1 0 1\n42\n', '5 4 1\n1 2 3 4 5\n1 2\n2 3\n3 4\n4 5\n', '4 2 3\n9 9 1 2\n3 4\n4 3\n', '3 1 1\n5 6 7\n2 3\n'] })

t({ lv: 595, concept: '区間: 2つのリストの交わり', title: '2つの区間リストの共通部分', tags: ['区間', '二点法'], io: '1行目に個数 n、続く n 行に互いに素で昇順の区間 l r。次に個数 m と同様の区間 m 行が与えられます。', ask: '2つのリストの共通部分となる区間を、1行に「l r」の形で順に出力してください。共通部分が無ければ none。', h1: '両リストにポインタを置き、先に終わる区間の側を進める。', h2: '交わりは [max(l1,l2), min(r1,r2)]。空でなければ出力。', ref: 'n=int(input())\nA=[tuple(map(int,input().split())) for _ in range(n)]\nm=int(input())\nB=[tuple(map(int,input().split())) for _ in range(m)]\ni=j=0\nout=[]\nwhile i<n and j<m:\n    l=max(A[i][0],B[j][0])\n    r=min(A[i][1],B[j][1])\n    if l<=r:\n        out.append(f"{l} {r}")\n    if A[i][1]<B[j][1]:\n        i+=1\n    else:\n        j+=1\nprint("\\n".join(out) if out else "none")', tip: '「早く閉じる方を進める」二点法はソート済み区間の合流の定石。カレンダーの空き時間検索はこれの補集合版にあたる。', ins: ['2\n0 2\n5 10\n2\n1 5\n8 12\n', '1\n1 3\n1\n4 6\n', '1\n0 10\n2\n2 3\n5 7\n', '1\n5 5\n1\n5 5\n', '2\n1 2\n3 4\n1\n0 10\n', '1\n0 1\n1\n2 3\n'] })

t({ lv: 596, concept: 'グラフ: 最遠ペアの組数', title: '最も遠い頂点ペアはいくつあるか', tags: ['グラフ', 'BFS'], io: '1行目に n m、続く m 行に連結な無向グラフの辺が与えられます(辺の長さは全て1)。', ask: '最短距離が最大(直径)になる頂点の組(順序なし)の個数を出力してください。', h1: '全頂点からBFSして全点対距離を得る。', h2: '最大値を更新したら個数を1に戻し、同じなら加算。', ref: 'from collections import deque\nn,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\nD=0\ncnt=0\nfor s in range(1,n+1):\n    dist=[-1]*(n+1)\n    dist[s]=0\n    q=deque([s])\n    while q:\n        x=q.popleft()\n        for y in g[x]:\n            if dist[y]<0:\n                dist[y]=dist[x]+1\n                q.append(y)\n    for tt in range(s+1,n+1):\n        if dist[tt]>D:\n            D=dist[tt]\n            cnt=1\n        elif dist[tt]==D:\n            cnt+=1\nprint(cnt)', tip: '「最大値とその個数」を対で持ち回る集計は、更新時のリセットを忘れると壊れる。s<tt の走査でペアの二重数えを防ぐのも基本形。', ins: ['4 3\n1 2\n2 3\n3 4\n', '4 4\n1 2\n2 3\n3 4\n4 1\n', '3 3\n1 2\n2 3\n1 3\n', '5 4\n1 2\n1 3\n1 4\n1 5\n', '2 1\n1 2\n', '6 5\n1 2\n2 3\n3 4\n4 5\n5 6\n'] })

t({ lv: 597, concept: 'グラフ: 2人が落ち合う最短時間', title: '2人が合流できる最短時刻', tags: ['グラフ', 'ダイクストラ'], io: '1行目に n m a b、続く m 行に無向辺 u v w が与えられます。2人は頂点 a と b から同時に出発します。', ask: 'どこかの頂点で落ち合うとき、「遅い方の到着時刻」の最小値を出力してください。合流できなければ -1。', h1: '合流地点 v を決めると所要は max(aからの距離, bからの距離)。', h2: '両者からダイクストラして全頂点で max を取り、その最小。', ref: 'import heapq\nn,m,a,b=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v,w=map(int,input().split())\n    g[u].append((v,w))\n    g[v].append((u,w))\ndef dij(src):\n    INF=float("inf")\n    dist=[INF]*(n+1)\n    dist[src]=0\n    h=[(0,src)]\n    while h:\n        d,x=heapq.heappop(h)\n        if d>dist[x]:\n            continue\n        for y,w in g[x]:\n            if d+w<dist[y]:\n                dist[y]=d+w\n                heapq.heappush(h,(d+w,y))\n    return dist\nda=dij(a)\ndb=dij(b)\nbest=min(max(da[v],db[v]) for v in range(1,n+1))\nprint(best if best<float("inf") else -1)', tip: '合流点を全探索し、評価を前計算した距離表2枚で済ませる。max(da,db)をda+dbに変えると総移動距離最小、と評価関数の差し替えも一瞬。', ins: ['3 2 1 3\n1 2 2\n2 3 4\n', '2 1 1 2\n1 2 10\n', '4 4 1 4\n1 2 1\n2 4 1\n1 3 1\n3 4 1\n', '2 0 1 2\n', '1 0 1 1\n', '5 4 1 5\n1 2 3\n2 3 3\n3 4 3\n4 5 3\n'] })

t({ lv: 598, concept: '貪欲: 1回の交換で最大の数', title: '1回だけ桁を入れ替えて最大に', tags: ['貪欲'], io: '正整数が1行で与えられます。', ask: '高々1回、2つの桁を入れ替えて作れる最大の数を出力してください。', h1: '桁数は少ないので全ペアの交換を試せる。', h2: '大きな数では「右側にあるより大きい数字のうち最大で最も右のもの」と、それより大きくできる最左の桁を交換する。', ref: 's=list(input())\nn=len(s)\nbest="".join(s)\nfor i in range(n):\n    for j in range(i+1,n):\n        s[i],s[j]=s[j],s[i]\n        c="".join(s)\n        if c>best:\n            best=c\n        s[i],s[j]=s[j],s[i]\nprint(best)', tip: '数値の大小は同じ桁数なら文字列比較と一致する。交換して比較して戻す、のスワップ往復で全候補を非破壊に試せる。', ins: ['2736\n', '9973\n', '98368\n', '1\n', '120\n', '1993\n'] })

t({ lv: 599, concept: 'グラフ: 1辺故障時の最悪最短距離', title: 'どこか1本が不通のときの最悪距離', tags: ['グラフ', 'ダイクストラ'], io: '1行目に n m s t、続く m 行に無向辺 u v w が与えられます(sとtは連結)。', ask: 'どれか1本の辺が使えなくなるとき、最悪のケースでの s から t への最短距離を出力してください。切断されて到達不能になり得るなら -1。', h1: '各辺を1本ずつ抜いて最短路を計算する。', h2: '不通で無限大になる辺があれば -1、なければ最大値。', ref: 'import heapq\nn,m,s,t=map(int,input().split())\nedges=[tuple(map(int,input().split())) for _ in range(m)]\ndef sp(skip):\n    g=[[] for _ in range(n+1)]\n    for i,(u,v,w) in enumerate(edges):\n        if i!=skip:\n            g[u].append((v,w))\n            g[v].append((u,w))\n    INF=float("inf")\n    dist=[INF]*(n+1)\n    dist[s]=0\n    h=[(0,s)]\n    while h:\n        d,x=heapq.heappop(h)\n        if d>dist[x]:\n            continue\n        for y,w in g[x]:\n            if d+w<dist[y]:\n                dist[y]=d+w\n                heapq.heappush(h,(d+w,y))\n    return dist[t]\nworst=0\nbad=False\nfor i in range(m):\n    d=sp(i)\n    if d==float("inf"):\n        bad=True\n        break\n    if d>worst:\n        worst=d\nprint(-1 if bad else worst)', tip: '耐障害性の評価は「最悪の1故障」を全列挙するのが出発点。最短路上に無い辺は消しても影響しないので、実は最短路上の辺だけ試せば足りる。', ins: ['3 3 1 3\n1 2 1\n2 3 1\n1 3 5\n', '2 1 1 2\n1 2 3\n', '4 4 1 4\n1 2 1\n2 4 1\n1 3 2\n3 4 2\n', '3 2 1 3\n1 2 1\n2 3 1\n', '4 5 1 4\n1 2 1\n2 4 1\n1 3 1\n3 4 1\n1 4 10\n', '2 2 1 2\n1 2 5\n1 2 7\n'] })

t({ lv: 601, concept: 'MST: 2番目に小さい全域木', title: '次に安い全域木', tags: ['MST'], io: '1行目に n m、続く m 行に連結な無向グラフの辺 u v w が与えられます。', ask: '最小全域木の次に総重みが小さい全域木(同じ重みで別の木も可)の総重みを出力してください。全域木が1つしか無ければ -1。', h1: '最良の木から辺を1本入れ替えた木の中に2番目が必ずある。', h2: 'MSTを作り、木に入らなかった各辺 e について「eを足してできる閉路上の最大辺を外す」候補の最小を取る。', ref: 'from collections import deque\nn,m=map(int,input().split())\nraw=[tuple(map(int,input().split())) for _ in range(m)]\nidx=sorted(range(m),key=lambda i:raw[i][2])\npar=list(range(n+1))\ndef find(x):\n    while par[x]!=x:\n        par[x]=par[par[x]]\n        x=par[x]\n    return x\ntree=[[] for _ in range(n+1)]\nused=[False]*m\ntotal=0\nfor i in idx:\n    u,v,w=raw[i]\n    ru,rv=find(u),find(v)\n    if ru!=rv:\n        par[ru]=rv\n        tree[u].append((v,w))\n        tree[v].append((u,w))\n        used[i]=True\n        total+=w\ndef maxedge(a,b):\n    par2=[0]*(n+1)\n    pw=[0]*(n+1)\n    seen=[False]*(n+1)\n    seen[a]=True\n    q=deque([a])\n    while q:\n        x=q.popleft()\n        for y,w in tree[x]:\n            if not seen[y]:\n                seen[y]=True\n                par2[y]=x\n                pw[y]=w\n                q.append(y)\n    mx=0\n    x=b\n    while x!=a:\n        if pw[x]>mx:\n            mx=pw[x]\n        x=par2[x]\n    return mx\nbest=None\nfor i in range(m):\n    if used[i]:\n        continue\n    u,v,w=raw[i]\n    cand=total-maxedge(u,v)+w\n    if best is None or cand<best:\n        best=cand\nprint(best if best is not None else -1)', tip: '「最適解の近傍に次善がある」交換論法の代表例。閉路上の最大辺との交換だけ調べれば全域木の空間を全部見なくてよい。', ins: ['3 3\n1 2 1\n2 3 2\n1 3 3\n', '2 1\n1 2 5\n', '4 5\n1 2 1\n2 3 1\n3 4 1\n1 4 4\n2 4 3\n', '3 3\n1 2 1\n2 3 1\n1 3 1\n', '4 4\n1 2 1\n2 3 2\n3 4 3\n1 4 10\n', '4 6\n1 2 2\n1 3 2\n1 4 2\n2 3 3\n2 4 3\n3 4 3\n'] })

t({ lv: 602, concept: 'MST: 指定辺を必ず使う全域木', title: 'この辺を使う最小全域木', tags: ['MST'], io: '1行目に n m、続く m 行に連結な無向グラフの辺 u v w、最後の行に必ず使う辺の番号 k(1始まり)が与えられます。', ask: 'k 番目の辺を必ず含む全域木の最小総重みを出力してください。', h1: '指定辺を先に採用してしまう。', h2: 'その2頂点を先にUnion-Findで結合してから、残りをクラスカル法で足す。', ref: 'n,m=map(int,input().split())\nraw=[tuple(map(int,input().split())) for _ in range(m)]\nk=int(input())\npar=list(range(n+1))\ndef find(x):\n    while par[x]!=x:\n        par[x]=par[par[x]]\n        x=par[x]\n    return x\nfu,fv,fw=raw[k-1]\npar[find(fu)]=find(fv)\ntotal=fw\nfor u,v,w in sorted(raw,key=lambda e:e[2]):\n    ru,rv=find(u),find(v)\n    if ru!=rv:\n        par[ru]=rv\n        total+=w\nprint(total)', tip: 'クラスカル法は「既に結ばれた状態」から始めても最適性が保たれる(マトロイドの性質)。必須辺・既設回線ありのネットワーク設計はこの形。', ins: ['3 3\n1 2 1\n2 3 2\n1 3 5\n3\n', '3 3\n1 2 1\n2 3 2\n1 3 5\n1\n', '4 5\n1 2 1\n2 3 1\n3 4 1\n1 4 10\n2 4 5\n4\n', '2 1\n1 2 7\n1\n', '4 4\n1 2 3\n2 3 3\n3 4 3\n1 3 1\n2\n', '3 2\n1 2 4\n2 3 6\n2\n'] })

t({ lv: 603, concept: 'MST: 井戸か水道管か', title: '井戸と水道管の最小費用', tags: ['MST'], io: '1行目に家の数 n と水道管候補数 m、2行目に各家に井戸を掘る費用、続く m 行に水道管 u v c が与えられます。', ask: '各家は「井戸を掘る」か「水道管で水のある家と繋がる」必要があります。全家に水を届ける最小費用を出力してください。', h1: '井戸は「仮想の水源0番と家を結ぶ辺」とみなせる。', h2: '仮想頂点を足してただの最小全域木にする。', ref: 'n,m=map(int,input().split())\nws=list(map(int,input().split()))\nedges=[]\nfor i in range(1,n+1):\n    edges.append((ws[i-1],0,i))\nfor _ in range(m):\n    u,v,c=map(int,input().split())\n    edges.append((c,u,v))\nedges.sort()\npar=list(range(n+1))\ndef find(x):\n    while par[x]!=x:\n        par[x]=par[par[x]]\n        x=par[x]\n    return x\ntotal=0\nfor c,u,v in edges:\n    ru,rv=find(u),find(v)\n    if ru!=rv:\n        par[ru]=rv\n        total+=c\nprint(total)', tip: '「頂点に付くコスト」は仮想頂点への辺に変換すると既存アルゴリズムがそのまま使える。発電所・サーバー設置など設備配置問題の定番モデル化。', ins: ['3 2\n1 2 2\n1 2 1\n2 3 1\n', '2 1\n5 5\n1 2 100\n', '2 1\n1 100\n1 2 1\n', '3 0\n3 4 5\n', '4 3\n10 1 1 1\n1 2 1\n2 3 1\n3 4 1\n', '1 0\n7\n'] })

t({ lv: 604, concept: 'ダイクストラ: k番目に近い頂点', title: 'k番目に近い頂点はどれか', tags: ['ダイクストラ'], io: '1行目に n m s k、続く m 行に無向辺 u v w が与えられます(到達可能な頂点はk個以上)。', ask: 's からの最短距離が k 番目に小さい頂点の番号を出力してください(s自身も距離0で数える。同距離は番号の小さい順)。', h1: 'ダイクストラで全頂点の距離を求める。', h2: '(距離, 番号) の組でソートして k 番目。', ref: 'import heapq\nn,m,s,k=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v,w=map(int,input().split())\n    g[u].append((v,w))\n    g[v].append((u,w))\nINF=float("inf")\ndist=[INF]*(n+1)\ndist[s]=0\nh=[(0,s)]\nwhile h:\n    d,x=heapq.heappop(h)\n    if d>dist[x]:\n        continue\n    for y,w in g[x]:\n        if d+w<dist[y]:\n            dist[y]=d+w\n            heapq.heappush(h,(d+w,y))\nlst=sorted((dist[v],v) for v in range(1,n+1) if dist[v]<INF)\nprint(lst[k-1][1])', tip: 'ダイクストラの確定順そのものが「近い順」。実は k 番目が確定した瞬間に打ち切れるので、大きなグラフでは早期終了が効く。', ins: ['4 4 1 2\n1 2 5\n1 3 2\n3 4 4\n2 4 1\n', '3 2 1 1\n1 2 1\n2 3 1\n', '3 2 1 3\n1 2 1\n2 3 1\n', '4 3 2 2\n2 1 4\n2 3 4\n2 4 1\n', '2 1 1 2\n1 2 9\n', '5 4 3 4\n3 1 1\n3 2 2\n3 4 3\n3 5 4\n'] })

t({ lv: 605, concept: 'グラフ: 遠回りより長い直通辺の数', title: '回り道の方が近い直通道路', tags: ['グラフ'], io: '1行目に n m、続く m 行に無向辺 u v w が与えられます。', ask: '「その辺を直接使うより、他の経路で行く方が厳密に短い」辺の本数を出力してください。', h1: '全点対最短距離をワーシャルフロイドで求める。', h2: '辺 (u,v,w) について w が dist[u][v] より大きければ無駄な辺。', ref: 'n,m=map(int,input().split())\nINF=float("inf")\nd=[[INF]*(n+1) for _ in range(n+1)]\nfor i in range(1,n+1):\n    d[i][i]=0\nes=[]\nfor _ in range(m):\n    u,v,w=map(int,input().split())\n    es.append((u,v,w))\n    if w<d[u][v]:\n        d[u][v]=w\n        d[v][u]=w\nfor k in range(1,n+1):\n    for i in range(1,n+1):\n        for j in range(1,n+1):\n            if d[i][k]+d[k][j]<d[i][j]:\n                d[i][j]=d[i][k]+d[k][j]\nprint(sum(1 for u,v,w in es if w>d[u][v]))', tip: '距離行列を作ってから辺を検査する2段構え。こうした辺を消しても全点対距離は不変で、グラフの簡約(スパナー)の第一歩になる。', ins: ['3 3\n1 2 1\n2 3 1\n1 3 5\n', '3 3\n1 2 1\n2 3 1\n1 3 2\n', '4 5\n1 2 1\n2 3 1\n3 4 1\n1 4 5\n1 3 3\n', '2 1\n1 2 9\n', '4 4\n1 2 2\n2 3 2\n3 4 2\n1 4 7\n', '3 2\n1 2 3\n2 3 3\n'] })

t({ lv: 606, concept: '木DP: 根から葉への最小の和', title: '根から葉までの最小コスト経路', tags: ['木DP', '再帰'], io: '1行目に頂点数 n (根は1、n≥2)、2行目に各頂点のコスト、3行目に頂点2..nの親が与えられます。', ask: '根から葉まで下りるとき、通る頂点のコスト合計の最小値を出力してください。', h1: '葉なら自分のコストだけ。', h2: '内部頂点は「自分+子の最小」。再帰で書ける。', ref: 'import sys\nsys.setrecursionlimit(100000)\nn=int(input())\nw=list(map(int,input().split()))\npar=[0,0]+list(map(int,input().split()))\nch=[[] for _ in range(n+1)]\nfor v in range(2,n+1):\n    ch[par[v]].append(v)\ndef f(v):\n    if not ch[v]:\n        return w[v-1]\n    return w[v-1]+min(f(c) for c in ch[v])\nprint(f(1))', tip: 'グリッドの最小経路和の木バージョン。maxに替えれば最重の根葉パス、和を積に替えれば確率の最尤経路と、同じ骨格が使い回せる。', ins: ['5\n1 2 3 4 5\n1 1 2 2\n', '2\n5 3\n1\n', '4\n1 10 1 10\n1 2 2\n', '3\n7 1 2\n1 1\n', '6\n3 1 1 5 5 0\n1 1 2 2 3\n', '4\n0 0 0 0\n1 2 3\n'] })

t({ lv: 607, concept: '木: 偶数サイズに切り分ける辺数', title: '両側が偶数になる切り方の数', tags: ['木'], io: '1行目に頂点数 n、2行目に頂点2..nの親(親の番号は自分より小さい)が与えられます。', ask: '木の辺のうち、取り除くと両側の成分がどちらも偶数個の頂点になるものの本数を出力してください。', h1: '辺 (親,v) を切ると片側は v の部分木。', h2: '部分木サイズを求め、サイズが偶数かつ残り n−サイズも偶数の頂点を数える。', ref: 'n=int(input())\npar=[0,0]+list(map(int,input().split()))\nsize=[1]*(n+1)\nfor v in range(n,1,-1):\n    size[par[v]]+=size[v]\nprint(sum(1 for v in range(2,n+1) if size[v]%2==0 and (n-size[v])%2==0))', tip: '親番号が常に小さい入力なら、番号の降順に size を親へ足すだけで部分木サイズが全部求まる(再帰不要)。nが奇数なら答えは必ず0。', ins: ['4\n1 2 3\n', '2\n1\n', '6\n1 2 3 4 5\n', '4\n1 1 1\n', '6\n1 1 2 2 3\n', '8\n1 2 1 4 5 4 7\n'] })

t({ lv: 608, concept: 'グラフ: 全ての道を歩く最短(郵便配達)', title: '全部の道を通って戻る最短距離', tags: ['グラフ', 'bitDP'], io: '1行目に n m、続く m 行に連結な無向グラフの辺 u v w が与えられます(奇数次数の頂点は8個以下)。', ask: '全ての辺を少なくとも1回通って出発点に戻る閉路の最小総距離(中華郵便配達問題)を出力してください。', h1: '全頂点の次数が偶数ならオイラー閉路があり、答えは辺の総和。', h2: '奇数次数の頂点どうしを最短距離でペアにし、その総和を上乗せする(ビットマスクの最小マッチング)。', ref: 'n,m=map(int,input().split())\nINF=float("inf")\nd=[[INF]*(n+1) for _ in range(n+1)]\nfor i in range(1,n+1):\n    d[i][i]=0\ndeg=[0]*(n+1)\ntotal=0\nfor _ in range(m):\n    u,v,w=map(int,input().split())\n    total+=w\n    deg[u]+=1\n    deg[v]+=1\n    if w<d[u][v]:\n        d[u][v]=w\n        d[v][u]=w\nfor k in range(1,n+1):\n    for i in range(1,n+1):\n        for j in range(1,n+1):\n            if d[i][k]+d[k][j]<d[i][j]:\n                d[i][j]=d[i][k]+d[k][j]\nodds=[v for v in range(1,n+1) if deg[v]%2]\nk=len(odds)\nmemo={}\ndef match(mask):\n    if mask==(1<<k)-1:\n        return 0\n    if mask in memo:\n        return memo[mask]\n    i=0\n    while mask>>i&1:\n        i+=1\n    best=INF\n    for j in range(i+1,k):\n        if not mask>>j&1:\n            r=d[odds[i]][odds[j]]+match(mask|1<<i|1<<j)\n            if r<best:\n                best=r\n    memo[mask]=best\n    return best\nprint(total+(match(0) if odds else 0))', tip: '除雪車・ゴミ収集・巡回点検のルート設計そのもの。奇数次数点のペアリングに全体の巧拙が凝縮される、オイラー閉路の美しい応用。', ins: ['3 3\n1 2 1\n2 3 1\n1 3 1\n', '2 1\n1 2 5\n', '4 4\n1 2 1\n2 3 1\n3 4 1\n4 1 1\n', '3 2\n1 2 2\n2 3 3\n', '4 5\n1 2 1\n2 3 1\n3 4 1\n4 1 1\n1 3 1\n', '4 3\n1 2 1\n1 3 1\n1 4 1\n'] })

t({ lv: 609, concept: '数え上げ: 次数指定のラベル付き木', title: '次数を指定した木の数', tags: ['数学'], io: '1行目に頂点数 n (n≥2)、2行目に各頂点の次数 d1 … dn が与えられます。', ask: '頂点 i の次数がちょうど di になるラベル付きの木の総数を出力してください(不可能なら0)。', h1: '木の次数の合計は 2(n−1)。', h2: 'プリューファー列で頂点 i は di−1 回現れる。答えは多項係数 (n−2)! / Π(di−1)!。', ref: 'from math import factorial\nn=int(input())\nd=list(map(int,input().split()))\nif sum(d)!=2*n-2 or any(x<1 for x in d):\n    print(0)\nelse:\n    r=factorial(n-2)\n    for x in d:\n        r//=factorial(x-1)\n    print(r)', tip: 'プリューファー対応は「木の数え上げ」を「文字列の数え上げ」に翻訳する辞書。全部足すとケイリーの公式 n^(n-2) が復元される。', ins: ['4\n1 2 2 1\n', '3\n1 1 2\n', '4\n3 1 1 1\n', '4\n1 1 1 1\n', '5\n2 2 2 1 1\n', '2\n1 1\n'] })

t({ lv: 610, concept: 'MST: k個の集団に分ける最大間隔', title: 'k個のクラスタの分離幅', tags: ['MST'], io: '1行目に n m k (2≤k≤n)、続く m 行に連結な無向グラフの辺 u v w が与えられます。', ask: '辺の短い順に頂点をまとめていき、ちょうど k 個のグループになった時点で止めます。異なるグループを結ぶ最短の辺の重み(クラスタ間の分離幅)を出力してください。', h1: 'クラスカル法を途中で止める。', h2: 'グループ数が k のとき、次に採用されるはずだった(別グループを結ぶ)最小の辺が答え。', ref: 'n,m,k=map(int,input().split())\nedges=sorted([tuple(map(int,input().split())) for _ in range(m)],key=lambda e:e[2])\npar=list(range(n+1))\ndef find(x):\n    while par[x]!=x:\n        par[x]=par[par[x]]\n        x=par[x]\n    return x\ncomps=n\nans=None\nfor u,v,w in edges:\n    ru,rv=find(u),find(v)\n    if ru==rv:\n        continue\n    if comps>k:\n        par[ru]=rv\n        comps-=1\n    else:\n        ans=w\n        break\nprint(ans)', tip: '単連結法(single-linkage)クラスタリングの分離幅最大化はMSTの停止と等価。機械学習の階層クラスタリングとクラスカル法が同じものだと分かる。', ins: ['4 6 2\n1 2 1\n3 4 1\n1 3 5\n1 4 6\n2 3 7\n2 4 8\n', '3 3 2\n1 2 1\n2 3 2\n1 3 3\n', '2 1 2\n1 2 4\n', '5 4 3\n1 2 1\n2 3 1\n4 5 1\n3 4 9\n', '6 7 3\n1 2 1\n2 3 1\n4 5 2\n5 6 2\n1 4 10\n3 6 11\n2 5 12\n', '4 3 2\n1 2 1\n2 3 2\n3 4 3\n'] })

t({ lv: 611, concept: 'グラフ: 最長路の本数(DAG)', title: 'DAGの最長経路は何本あるか', tags: ['グラフ', 'DP'], io: '1行目に n m、続く m 行に閉路のない有向辺が与えられます。', ask: '辺数が最大の経路(始点・終点は自由)の本数を出力してください。', h1: '各頂点で「ここで終わる最長の長さ」と「その本数」を対で持つ。', h2: 'トポロジカル順に、より長ければ上書き、同じ長さなら本数を加算。', ref: 'from collections import deque\nn,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nindeg=[0]*(n+1)\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    indeg[v]+=1\nL=[0]*(n+1)\nC=[1]*(n+1)\nq=deque(v for v in range(1,n+1) if indeg[v]==0)\norder=[]\nwhile q:\n    x=q.popleft()\n    order.append(x)\n    for y in g[x]:\n        indeg[y]-=1\n        if indeg[y]==0:\n            q.append(y)\nfor x in order:\n    for y in g[x]:\n        if L[x]+1>L[y]:\n            L[y]=L[x]+1\n            C[y]=C[x]\n        elif L[x]+1==L[y]:\n            C[y]+=C[x]\nbest=max(L[1:n+1])\nprint(sum(C[v] for v in range(1,n+1) if L[v]==best))', tip: '「最適値とその個数」のペアDP。更新式は最短路の本数と同型で、max/minと等号のときの加算という2本立ての遷移が共通の骨格。', ins: ['4 4\n1 2\n1 3\n2 4\n3 4\n', '3 2\n1 2\n2 3\n', '3 0\n', '5 4\n1 3\n2 3\n3 4\n3 5\n', '2 1\n1 2\n', '6 6\n1 2\n2 3\n4 5\n5 6\n1 6\n4 3\n'] })

t({ lv: 612, concept: 'グラフ: 二重連結成分の数', title: 'ブロックの個数', tags: ['グラフ', '再帰'], io: '1行目に n m、続く m 行に無向辺が与えられます(自己ループなし)。', ask: '辺を1本以上含む二重連結成分(ブロック: 関節点で分けられない極大部分)の個数を出力してください。', h1: 'DFSで発見時刻 disc と、戻れる最小時刻 low を計算する。', h2: '子 v が low[v]≥disc[u] を満たすたびに、辺スタックからブロックが1つ取り出せる。', ref: 'import sys\nsys.setrecursionlimit(100000)\nn,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor i in range(m):\n    u,v=map(int,input().split())\n    g[u].append((v,i))\n    g[v].append((u,i))\ndisc=[0]*(n+1)\nlow=[0]*(n+1)\ntimer=[1]\nst=[]\ncnt=[0]\ndef dfs(u,pe):\n    disc[u]=low[u]=timer[0]\n    timer[0]+=1\n    for v,ei in g[u]:\n        if ei==pe:\n            continue\n        if disc[v]:\n            if disc[v]<disc[u]:\n                st.append(ei)\n                if disc[v]<low[u]:\n                    low[u]=disc[v]\n        else:\n            st.append(ei)\n            dfs(v,ei)\n            if low[v]<low[u]:\n                low[u]=low[v]\n            if low[v]>=disc[u]:\n                cnt[0]+=1\n                while st and st[-1]!=ei:\n                    st.pop()\n                st.pop()\nfor s in range(1,n+1):\n    if not disc[s]:\n        dfs(s,-1)\nprint(cnt[0])', tip: '橋は「1辺だけのブロック」、関節点は「複数ブロックの継ぎ目」。低リンク値1本で橋・関節点・ブロックが全部読めるのがDFS木の凄み。', ins: ['3 3\n1 2\n2 3\n1 3\n', '3 2\n1 2\n2 3\n', '5 5\n1 2\n2 3\n3 1\n3 4\n4 5\n', '2 1\n1 2\n', '4 4\n1 2\n2 3\n3 4\n4 1\n', '6 6\n1 2\n2 3\n3 1\n4 5\n5 6\n6 4\n'] })

t({ lv: 613, concept: 'グラフ: 閉路を作った最後の辺', title: '余分な1本のケーブル', tags: ['グラフ'], io: '1行目に頂点数 n、続く n 行に無向辺が与えられます(木に1本余分な辺が加わったグラフ)。', ask: '取り除くと木に戻る辺のうち、入力で最も後に現れるものを「u v」の形(入力のまま)で出力してください。', h1: '辺を順に足しながら連結を管理する。', h2: '両端が既に同じグループの辺こそが閉路を作る辺(Union-Findで即判定)。', ref: 'n=int(input())\npar=list(range(n+1))\ndef find(x):\n    while par[x]!=x:\n        par[x]=par[par[x]]\n        x=par[x]\n    return x\nfor _ in range(n):\n    u,v=map(int,input().split())\n    ru,rv=find(u),find(v)\n    if ru==rv:\n        print(u,v)\n        break\n    par[ru]=rv', tip: '辺を時系列に足んでいくオンライン処理では、Union-Findの「もう繋がっている」判定がそのまま閉路検出になる。木+1辺なら答えは必ず1本。', ins: ['3\n1 2\n1 3\n2 3\n', '4\n1 2\n2 3\n3 4\n1 4\n', '4\n1 2\n1 3\n2 3\n3 4\n', '3\n1 2\n2 3\n1 3\n', '5\n1 2\n2 3\n3 4\n4 5\n2 5\n', '2\n1 2\n1 2\n'] })

t({ lv: 614, concept: '木: 辺で切る2分割の差最小', title: '1辺を切って人数差を最小に', tags: ['木'], io: '1行目に頂点数 n (n≥2)、2行目に頂点2..nの親(親の番号は自分より小さい)が与えられます。', ask: '木の辺を1本切って2つの成分に分けるとき、頂点数の差の最小値を出力してください。', h1: '辺 (親,v) を切ると片側は v の部分木サイズ。', h2: '差は |n − 2×size[v]|。全ての v で最小を取る。', ref: 'n=int(input())\npar=[0,0]+list(map(int,input().split()))\nsize=[1]*(n+1)\nfor v in range(n,1,-1):\n    size[par[v]]+=size[v]\nprint(min(abs(n-2*size[v]) for v in range(2,n+1)))', tip: '負荷分散のための木の分割は部分木サイズの一覧に帰着する。重み付き版・k分割版に拡張しても「部分木の集計」という芯は変わらない。', ins: ['4\n1 2 3\n', '2\n1\n', '5\n1 1 1 1\n', '6\n1 2 2 1 5\n', '3\n1 1\n', '7\n1 1 2 2 3 3\n'] })

t({ lv: 615, concept: 'グラフ: 辞書順最小の最短路', title: '番号の並びが最小の最短経路', tags: ['グラフ', 'BFS'], io: '1行目に n m s t、続く m 行に無向辺が与えられます(辺の長さは全て1)。', ask: 's から t への最短経路のうち、頂点列が辞書順最小のものを空白区切りで出力してください。到達できなければ -1。', h1: 't からのBFSで各頂点の「残り距離」を求める。', h2: 's から進むとき「残り距離がちょうど1減る隣」の中で最小番号を選び続ける。', ref: 'from collections import deque\nn,m,s,t=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\ndt=[-1]*(n+1)\ndt[t]=0\nq=deque([t])\nwhile q:\n    x=q.popleft()\n    for y in g[x]:\n        if dt[y]<0:\n            dt[y]=dt[x]+1\n            q.append(y)\nif dt[s]<0:\n    print(-1)\nelse:\n    path=[s]\n    cur=s\n    while cur!=t:\n        cur=min(y for y in g[cur] if dt[y]==dt[cur]-1)\n        path.append(cur)\n    print(*path)', tip: '「ゴール側からの距離表」を作ると、スタートからは貪欲に降りるだけで最短性が保証される。復元と辞書順最小化を同時に叶える逆向き前計算。', ins: ['4 4 1 4\n1 2\n2 4\n1 3\n3 4\n', '2 1 1 2\n1 2\n', '5 5 1 5\n1 3\n3 5\n1 2\n2 4\n4 5\n', '1 0 1 1\n', '4 2 1 4\n1 2\n3 4\n', '6 7 1 6\n1 2\n1 3\n2 5\n3 5\n5 6\n2 4\n4 6\n'] })

export const CATALOG = TASKS
