// 生成タスク 第52波：各レベル2問化フェーズ(7)。lv344〜392 に2問目を追加。
// 上位問題(AtCoder/LeetCode/古典)の要素分解。重複なし・決定的・採点一意。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 344, concept: 'DP: 3の倍数の最大部分和', title: '3で割り切れる最大の部分和', tags: ['DP'], io: '正整数の列が1行で空白区切りで与えられます。', ask: '要素をいくつか選んで(0個でもよい)、和が3の倍数になる最大の和を出力してください。', h1: '余り0,1,2ごとの最大和を持つDP。', h2: '各要素で全余り状態から遷移し、(和+x)%3 の状態を更新。', ref: 'a=list(map(int,input().split()))\nNEG=float("-inf")\ndp=[0,NEG,NEG]\nfor x in a:\n    ndp=dp[:]\n    for r in range(3):\n        if dp[r]!=NEG:\n            v=dp[r]+x\n            if v>ndp[v%3]:\n                ndp[v%3]=v\n    dp=ndp\nprint(dp[0])', tip: '「和を法で分類して各類の最良値を持つ」DPは合計値そのものを持つより状態が激減する。mod kならk状態で足りる。', ins: ['3 6 5 1 8\n', '4\n', '1 2 3 4 4\n', '2 2\n', '3 3 3\n', '5 5 5 5\n'] })

t({ lv: 345, concept: 'DP: ちょうどk枚の硬貨で作る方法数', title: 'ちょうどk枚で金額を作る組合せ数', tags: ['DP'], io: '1行目に金額 T と枚数 k、2行目に硬貨の額面(各無制限)が与えられます。', ask: 'ちょうど k 枚の硬貨で金額 T を作る組合せ(順序は区別しない)の数を出力してください。', h1: 'dp[金額][枚数] の2次元DP。', h2: '硬貨ごとに外側ループを回すと順序の区別が消える。', ref: 'target,k=map(int,input().split())\ncoins=list(map(int,input().split()))\ndp=[[0]*(k+1) for _ in range(target+1)]\ndp[0][0]=1\nfor c in coins:\n    for v in range(c,target+1):\n        for j in range(1,k+1):\n            dp[v][j]+=dp[v-c][j-1]\nprint(dp[target][k])', tip: '硬貨問題に「枚数」の次元を足すと制約付き数え上げになる。硬貨を外側ループにするのが組合せ(順序なし)の鉄則。', ins: ['5 2\n1 2 3\n', '4 2\n1 2 3\n', '6 3\n1 2 3\n', '3 3\n1 2\n', '10 4\n2 5\n', '0 0\n5\n'] })

t({ lv: 346, concept: '行列: 1で作る最大の十字', title: '1だけで作る最大の十字マーク', tags: ['行列', 'DP'], io: '1行目に h w、続く h 行に 0/1 の文字列が与えられます。', ask: '中心から上下左右に長さ k-1 の腕が伸びる十字(全て1)の最大の k を出力してください(1がなければ0)。', h1: '各マスについて上下左右に連続する1の長さを前計算。', h2: '4方向の最小値の最大が答え。', ref: 'h,w=map(int,input().split())\ng=[input() for _ in range(h)]\nup=[[0]*w for _ in range(h)]\ndown=[[0]*w for _ in range(h)]\nleft=[[0]*w for _ in range(h)]\nright=[[0]*w for _ in range(h)]\nfor i in range(h):\n    for j in range(w):\n        if g[i][j]=="1":\n            up[i][j]=(up[i-1][j] if i>0 else 0)+1\n            left[i][j]=(left[i][j-1] if j>0 else 0)+1\nfor i in range(h-1,-1,-1):\n    for j in range(w-1,-1,-1):\n        if g[i][j]=="1":\n            down[i][j]=(down[i+1][j] if i<h-1 else 0)+1\n            right[i][j]=(right[i][j+1] if j<w-1 else 0)+1\nbest=0\nfor i in range(h):\n    for j in range(w):\n        k=min(up[i][j],down[i][j],left[i][j],right[i][j])\n        if k>best:\n            best=k\nprint(best)', tip: '「各方向に連続する1の数」の4枚のDP表を作って合成する。最大正方形とは別の形のグリッドDP。', ins: ['3 3\n010\n111\n010\n', '1 1\n1\n', '2 2\n11\n11\n', '3 3\n000\n000\n000\n', '5 5\n00100\n00100\n11111\n00100\n00100\n', '3 4\n0110\n1111\n0110\n'] })

t({ lv: 347, concept: '区間DP: 回文除去の最小回数', title: '回文区間の除去で空にする最小回数', tags: ['区間DP'], io: '整数列が1行で空白区切りで与えられます。', ask: '1回の操作で「回文になっている連続部分列」を取り除ける(残りは詰める)とき、列を空にする最小操作回数を出力してください。', h1: 'dp[i][j]=区間[i,j]を消す最小回数。1要素は1回。', h2: '先頭を単独で消すか、先頭と同じ値の位置kと一緒に内側を先に消すかで遷移。', ref: 'a=input().split()\nn=len(a)\nINF=10**9\nD=[[INF]*n for _ in range(n)]\nfor i in range(n):\n    D[i][i]=1\nfor L in range(2,n+1):\n    for i in range(0,n-L+1):\n        j=i+L-1\n        best=D[i+1][j]+1\n        if a[i]==a[i+1]:\n            t=(D[i+2][j] if i+2<=j else 0)+1\n            if t<best:\n                best=t\n        for k in range(i+2,j+1):\n            if a[i]==a[k]:\n                t=D[i+1][k-1]+(D[k+1][j] if k+1<=j else 0)\n                if t<best:\n                    best=t\n        D[i][j]=best\nprint(D[0][n-1])', tip: '「端の文字を将来の対と一緒に消す」遷移が肝。風船割りと同じく除去系の区間DPは消す順序を最後に消すもので場合分けする。', ins: ['1 2\n', '1 3 4 1 5\n', '1\n', '1 2 1\n', '1 1 2 2 1 1\n', '3 3 3\n'] })

t({ lv: 348, concept: 'グラフ: 予算内で到達できる頂点数', title: '予算内で行ける頂点の数', tags: ['グラフ', 'ダイクストラ'], io: '1行目に n m s B、続く m 行に無向辺 u v w(コスト)が与えられます。', ask: '頂点 s から総コスト B 以下で到達できる頂点の数(s 自身も含む)を出力してください。', h1: 'ダイクストラで最短コストを求める。', h2: 'dist ≤ B の頂点を数える。', ref: 'import heapq\nn,m,s,b=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v,w=map(int,input().split())\n    g[u].append((v,w))\n    g[v].append((u,w))\nINF=float("inf")\ndist=[INF]*(n+1)\ndist[s]=0\npq=[(0,s)]\nwhile pq:\n    d,x=heapq.heappop(pq)\n    if d>dist[x]:\n        continue\n    for y,w in g[x]:\n        nd=d+w\n        if nd<dist[y]:\n            dist[y]=nd\n            heapq.heappush(pq,(nd,y))\nprint(sum(1 for v in range(1,n+1) if dist[v]<=b))', tip: '「コスト制限つき到達範囲」は最短距離を求めてから閾値で数えるだけ。配達圏・通勤圏の分析と同じ発想。', ins: ['4 4 1 5\n1 2 3\n2 3 3\n1 3 5\n3 4 1\n', '2 1 1 1\n1 2 5\n', '3 3 2 10\n1 2 2\n2 3 4\n1 3 10\n', '1 0 1 0\n', '5 4 1 2\n1 2 1\n2 3 1\n3 4 1\n4 5 1\n', '4 2 1 100\n1 2 1\n3 4 1\n'] })

t({ lv: 349, concept: 'グラフ: 迂回した方が近い辺の数', title: '回り道の方が近い辺の数', tags: ['グラフ'], io: '1行目に n m、続く m 行に無向辺 u v w が与えられます。', ask: 'その辺を直接通るより、他の経路を通った方が厳密に短い辺の本数を出力してください。', h1: 'ワーシャルフロイドで全点対最短距離を求める。', h2: '辺 (u,v,w) について dist[u][v] < w なら回り道の方が近い。', ref: 'n,m=map(int,input().split())\nINF=float("inf")\nd=[[INF]*(n+1) for _ in range(n+1)]\nfor i in range(1,n+1):\n    d[i][i]=0\nes=[]\nfor _ in range(m):\n    u,v,w=map(int,input().split())\n    es.append((u,v,w))\n    if w<d[u][v]:\n        d[u][v]=w\n        d[v][u]=w\nfor k in range(1,n+1):\n    for i in range(1,n+1):\n        for j in range(1,n+1):\n            if d[i][k]+d[k][j]<d[i][j]:\n                d[i][j]=d[i][k]+d[k][j]\nprint(sum(1 for u,v,w in es if d[u][v]<w))', tip: '最短路に一度も使われない「冗長な辺」の検出。ネットワークの無駄な回線を見つける分析に対応する。', ins: ['3 3\n1 2 1\n2 3 1\n1 3 5\n', '3 3\n1 2 1\n2 3 1\n1 3 2\n', '2 1\n1 2 7\n', '4 5\n1 2 1\n2 3 1\n3 4 1\n1 4 10\n1 3 3\n', '3 2\n1 2 4\n2 3 4\n', '4 4\n1 2 2\n2 3 2\n3 1 3\n3 4 1\n'] })

t({ lv: 350, concept: 'グラフ: 補グラフの辺数', title: '補グラフの辺の本数', tags: ['グラフ', '数学'], io: '1行目に n m、続く m 行に単純無向グラフの辺 u v が与えられます。', ask: '補グラフ(元のグラフに無い頂点対だけを辺で結んだグラフ)の辺数を出力してください。', h1: '完全グラフの辺数は n(n-1)/2。', h2: 'そこから m を引く。', ref: 'n,m=map(int,input().split())\nfor _ in range(m):\n    input()\nprint(n*(n-1)//2-m)', tip: '補グラフは「無い辺を考える」発想の転換。クリークと独立集合は補グラフで入れ替わる。', ins: ['4 3\n1 2\n2 3\n3 4\n', '3 0\n', '2 1\n1 2\n', '5 4\n1 2\n1 3\n1 4\n1 5\n', '1 0\n', '6 7\n1 2\n2 3\n3 4\n4 5\n5 6\n6 1\n1 4\n'] })

t({ lv: 351, concept: '貪欲: ジグザグ化の最小コスト', title: 'ジグザグ列にする最小の減らし数', tags: ['貪欲', '配列'], io: '正整数の列が1行で空白区切りで与えられます。', ask: '要素を1減らす操作(任意回)だけで、偶数番目が両隣より小さいか、奇数番目が両隣より小さいジグザグ列(0始まり)にするための操作回数の最小値を出力してください。', h1: '「谷にする側」を偶数番目か奇数番目かの2通り試す。', h2: '谷にする位置は min(両隣)-1 まで下げればよく、他は触らないのが最適。', ref: 'a=list(map(int,input().split()))\nn=len(a)\ndef cost(p):\n    s=0\n    for i in range(p,n,2):\n        lo=min(a[i-1] if i>0 else float("inf"), a[i+1] if i<n-1 else float("inf"))\n        if lo!=float("inf") and a[i]>=lo:\n            s+=a[i]-lo+1\n    return s\nprint(min(cost(0),cost(1)))', tip: '減らす操作だけなら「山を削るより谷を掘る」のが常に得。2パターンの全探索+独立な局所最適で解ける。', ins: ['1 2 3\n', '9 6 1 6 2\n', '1\n', '2 2\n', '5 5 5\n', '1 1000\n'] })

t({ lv: 352, concept: 'スタック: 括弧列の得点', title: '正しい括弧列の得点', tags: ['スタック'], io: '正しい括弧列が1行で与えられます。', ask: '() は1点、AB(連結)は A+B 点、(A) は 2×A 点とするときの得点を出力してください。', h1: 'スタックに「現在の深さの得点」を積む。', h2: '閉じ括弧で pop した値 v に対し max(2v, 1) を1つ上の階層に加算。', ref: 's=input()\nst=[0]\nfor c in s:\n    if c=="(":\n        st.append(0)\n    else:\n        v=st.pop()\n        st[-1]+=max(2*v,1)\nprint(st[0])', tip: '入れ子構造の評価はスタックが自然。max(2v,1) の1行で「空の対は1点」「包むと2倍」を同時に処理できる。', ins: ['()\n', '(())\n', '()()\n', '(()(()))\n', '((()))\n', '()(())\n'] })

t({ lv: 353, concept: 'ハッシュ: 最初に繰り返す文字の位置', title: '最初に2回目が現れる位置', tags: ['ハッシュ', '文字列'], io: '英小文字の文字列が1行で与えられます。', ask: 'はじめて「既に出た文字がもう一度現れる」位置(0始まり)を出力してください。重複がなければ -1。', h1: '見た文字を集合に入れながら走査。', h2: '集合にある文字に出会った瞬間の添字が答え。', ref: 's=input()\nseen=set()\nans=-1\nfor i,c in enumerate(s):\n    if c in seen:\n        ans=i\n        break\n    seen.add(c)\nprint(ans)', tip: '「最初の重複」は集合に入れつつ最初のヒットで打ち切る。最初の一意文字(別問題)と対になる走査パターン。', ins: ['abca\n', 'abc\n', 'aa\n', 'abba\n', 'xxy\n', 'abcdb\n'] })

t({ lv: 354, concept: 'BFS: 壁を1枚壊せる最短路', title: '壁を1枚まで壊せる最短経路', tags: ['BFS', 'グリッド'], io: '1行目に h w、続く h 行に 0(床)/1(壁) の文字列が与えられます。左上は床です。', ask: '左上から右下へ、壁を高々1枚だけ壊して通れるときの最短移動回数を出力してください。到達できなければ -1。', h1: '状態を (位置, 壊した枚数) に拡張してBFS。', h2: '壁マスへは「まだ壊していない」ときだけ入れる。', ref: 'from collections import deque\nh,w=map(int,input().split())\ng=[input() for _ in range(h)]\ndist=[[[-1]*2 for _ in range(w)] for _ in range(h)]\ndist[0][0][0]=0\nq=deque([(0,0,0)])\nwhile q:\n    i,j,b=q.popleft()\n    for di,dj in ((1,0),(-1,0),(0,1),(0,-1)):\n        ni,nj=i+di,j+dj\n        if 0<=ni<h and 0<=nj<w:\n            nb=b+(1 if g[ni][nj]=="1" else 0)\n            if nb<2 and dist[ni][nj][nb]<0:\n                dist[ni][nj][nb]=dist[i][j][b]+1\n                q.append((ni,nj,nb))\nans=[d for d in dist[h-1][w-1] if d>=0]\nprint(min(ans) if ans else -1)', tip: '「あとk回だけ特別な行動ができる」探索は状態にカウンタを足して層を分ける。グラフが (マス×状態) に膨らむだけでBFSの形は同じ。', ins: ['3 3\n010\n010\n000\n', '2 2\n01\n10\n', '1 3\n011\n', '3 3\n011\n111\n110\n', '1 1\n0\n', '2 3\n000\n110\n'] })

t({ lv: 355, concept: '数論: 約数関数σの総和', title: '1からNの約数の和の総和', tags: ['数論'], io: '正整数 N が1行で与えられます。', ask: 'σ(i) を i の全約数の和とするとき、σ(1)+σ(2)+…+σ(N) を出力してください。', h1: '「d を約数に持つ数」は N//d 個ある。', h2: '答えは Σ d×(N//d)。各約数 d の寄与をまとめて数える。', ref: 'n=int(input())\nprint(sum(d*(n//d) for d in range(1,n+1)))', tip: '二重ループを「各 d の寄与 d×⌊N/d⌋」に組み替えると O(N) になる。約数系の総和はこの視点の転換が定石。', ins: ['5\n', '1\n', '10\n', '3\n', '100\n', '2\n'] })

t({ lv: 356, concept: '貪欲: 2倍と-1でaをbにする最小手数', title: '2倍と減算1でaをbにする最小回数', tags: ['貪欲'], io: 'a b が空白区切りで1行で与えられます。', ask: '「2倍する」「1引く」の2操作だけで a を b にする最小操作回数を出力してください。', h1: '前からは分岐が爆発する。b から逆にたどる。', h2: '逆操作は「偶数なら半分」「奇数なら+1」。b≤a になったら残りは引き算。', ref: 'a,b=map(int,input().split())\nops=0\nwhile b>a:\n    if b%2==0:\n        b//=2\n    else:\n        b+=1\n    ops+=1\nprint(ops+a-b)', tip: '操作問題は「逆向きの貪欲」が決定打になることが多い。逆から見ると各ステップの最適手が一意に決まる。', ins: ['2 3\n', '5 8\n', '3 10\n', '10 1\n', '1 1\n', '1 1000000\n'] })

t({ lv: 357, concept: 'ハッシュ: 積がKのペア数', title: '積がKになるペアの個数', tags: ['配列'], io: '1行目に K、2行目に整数列が与えられます。', ask: 'a[i]×a[j]=K となる添字の組 (i<j) の個数を出力してください。', h1: '全ペアを試す素朴解でよい。', h2: '大規模なら出現回数の辞書で K/a[i] を引く(0や負に注意)。', ref: 'k=int(input())\na=list(map(int,input().split()))\nn=len(a)\ncnt=0\nfor i in range(n):\n    for j in range(i+1,n):\n        if a[i]*a[j]==k:\n            cnt+=1\nprint(cnt)', tip: '和のペア(two sum)の積バージョン。ハッシュで高速化する場合は K=0 と割り切れない場合の処理が罠になる。', ins: ['6\n1 2 3 6\n', '4\n2 2 2\n', '10\n1 2 5\n', '0\n0 1 2\n', '12\n3 4 2 6\n', '7\n1 1\n'] })

t({ lv: 358, concept: 'スタック: 出庫順序の実現可能性', title: 'スタックで作れる出力順か', tags: ['スタック'], io: '1行目に n、2行目に 1〜n の順列が与えられます。', ask: '1,2,…,n をこの順にスタックへ push し、任意のタイミングで pop できるとき、与えられた順列を pop 列として実現できるなら yes、できなければ no を出力してください。', h1: '出したい値までを順に push する。', h2: 'スタックの頂上が出したい値と違ったら実現不可能。', ref: 'n=int(input())\np=list(map(int,input().split()))\nst=[]\nnxt=1\nok=True\nfor x in p:\n    while nxt<=x:\n        st.append(nxt)\n        nxt+=1\n    if st and st[-1]==x:\n        st.pop()\n    else:\n        ok=False\n        break\nprint("yes" if ok else "no")', tip: 'スタックで実現できる順列はカタラン数個。実現不可能な最小パターンは「3,1,2 型」(231回避パターンの理論)。', ins: ['3\n2 1 3\n', '3\n3 1 2\n', '1\n1\n', '4\n1 2 3 4\n', '4\n4 3 2 1\n', '5\n2 4 1 3 5\n'] })

t({ lv: 359, concept: 'グラフ: 余裕ゼロのタスク数', title: 'クリティカルなタスクの数', tags: ['グラフ', 'DP'], io: '1行目に n m、2行目に各タスクの所要時間、続く m 行に依存 u v(uの後にv)が与えられます。', ask: '全体の最短完了時間を変えずに開始を遅らせる余裕が全くない(クリティカルな)タスクの数を出力してください。', h1: 'トポロジカル順に最早開始時刻を、逆順に最遅完了時刻を計算。', h2: '最遅開始-最早開始=0 のタスクがクリティカル。', ref: 'from collections import deque\nn,m=map(int,input().split())\ndur=list(map(int,input().split()))\ng=[[] for _ in range(n+1)]\nindeg=[0]*(n+1)\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    indeg[v]+=1\nq=deque(v for v in range(1,n+1) if indeg[v]==0)\nes=[0]*(n+1)\norder=[]\ndeg=indeg[:]\nwhile q:\n    x=q.popleft()\n    order.append(x)\n    for y in g[x]:\n        if es[x]+dur[x-1]>es[y]:\n            es[y]=es[x]+dur[x-1]\n        deg[y]-=1\n        if deg[y]==0:\n            q.append(y)\nT=max(es[v]+dur[v-1] for v in range(1,n+1))\nlf=[T]*(n+1)\nfor x in reversed(order):\n    for y in g[x]:\n        if lf[y]-dur[y-1]<lf[x]:\n            lf[x]=lf[y]-dur[y-1]\nprint(sum(1 for v in range(1,n+1) if lf[v]-dur[v-1]==es[v]))', tip: 'PERT/CPM のクリティカルパス分析。最早と最遅の両方向DPを取り、差(スラック)が0の工程が全体の納期を支配する。', ins: ['3 2\n2 3 2\n1 2\n2 3\n', '3 2\n2 1 2\n1 2\n1 3\n', '1 0\n5\n', '4 4\n1 1 1 1\n1 2\n1 3\n2 4\n3 4\n', '4 4\n1 2 1 1\n1 2\n1 3\n2 4\n3 4\n', '2 1\n3 4\n1 2\n'] })

t({ lv: 360, concept: 'DP: 等しくする最小削除コスト', title: '文字コスト最小で2文字列を等しく', tags: ['DP', '文字列'], io: '2行に英小文字の文字列 s と t が与えられます。', ask: '文字を削除して2つを同じ文字列にするとき、削除する文字の文字コード(ord)の合計の最小値を出力してください。', h1: '残す部分は共通部分列。残す ord 和を最大化する。', h2: 'LCSのDPで「長さ」の代わりに「ordの和」を最大化し、全体から2倍引く。', ref: 's=input()\nt=input()\nn,m=len(s),len(t)\ndp=[[0]*(m+1) for _ in range(n+1)]\nfor i in range(n):\n    for j in range(m):\n        if s[i]==t[j]:\n            dp[i+1][j+1]=dp[i][j]+ord(s[i])\n        else:\n            dp[i+1][j+1]=max(dp[i][j+1],dp[i+1][j])\ntotal=sum(ord(c) for c in s)+sum(ord(c) for c in t)\nprint(total-2*dp[n][m])', tip: 'LCSの「長さ最大」を「重み最大」に替えるだけで削除コスト最小化に化ける。DPの目的関数の差し替えの好例。', ins: ['sea\neat\n', 'delete\nleet\n', 'a\na\n', 'a\nb\n', 'abc\nabc\n', 'ab\nba\n'] })

t({ lv: 361, concept: '貪欲: 増加列への最小分割数', title: '厳密増加列に分ける最小本数', tags: ['DP', '貪欲'], io: '整数列が1行で空白区切りで与えられます。', ask: '列を(順序を保って)いくつかの厳密増加部分列に分割するときの最小本数を出力してください。', h1: 'ディルワースの定理: 最小の鎖分割数=最長の反鎖。', h2: '答えは最長の非増加部分列の長さに等しい。O(n²)DPで求める。', ref: 'a=list(map(int,input().split()))\nn=len(a)\ndp=[1]*n\nfor i in range(n):\n    for j in range(i):\n        if a[j]>=a[i]:\n            if dp[j]+1>dp[i]:\n                dp[i]=dp[j]+1\nprint(max(dp))', tip: 'ディルワースの定理「最小鎖分割=最大反鎖」はトランプのソリティア(patience sorting)の山の数とLISの関係の裏返し。', ins: ['3 1 2\n', '1 2 3\n', '3 2 1\n', '5\n', '2 2 2\n', '4 1 5 2 6 3\n'] })

t({ lv: 362, concept: 'ソート: 位置が変わらない要素数', title: 'ソートしても動かない要素の数', tags: ['ソート'], io: '整数列が1行で空白区切りで与えられます。', ask: '昇順にソートしたとき、元と同じ位置に同じ値が残る添字の個数を出力してください。', h1: 'ソート済みの列を作って位置ごとに比較。', h2: 'zip で並走して数える。', ref: 'a=list(map(int,input().split()))\nb=sorted(a)\nprint(sum(1 for x,y in zip(a,b) if x==y))', tip: 'ソート前後の比較は「どこが乱れているか」の基本診断。全要素一致ならソート済み判定にもなる。', ins: ['1 3 2 4\n', '1 2 3\n', '3 2 1\n', '5\n', '2 1 3 5 4\n', '1 1 2\n'] })

t({ lv: 363, concept: '貪欲: 連続同値の解消コスト', title: '隣り合う同色を消す最小コスト', tags: ['貪欲'], io: '1行目に色の列(空白区切り)、2行目に各位置の除去コストが与えられます。', ask: '同じ色が隣り合わないように要素を取り除くとき、取り除く要素のコスト合計の最小値を出力してください。', h1: '同色が k 個連続する区間からは k-1 個取り除くしかない。', h2: '各連続区間で最大コストの1個だけ残すのが最適(区間の合計-最大)。', ref: 'c=input().split()\nw=list(map(int,input().split()))\ntotal=0\ni=0\nn=len(c)\nwhile i<n:\n    j=i\n    s=0\n    mx=0\n    while j<n and c[j]==c[i]:\n        s+=w[j]\n        if w[j]>mx:\n            mx=w[j]\n        j+=1\n    total+=s-mx\n    i=j\nprint(total)', tip: '「連続区間ごとに独立して貪欲」できるのは区間同士が干渉しないから。合計-最大=残す1個以外を払う、の言い換え。', ins: ['a a b\n3 5 2\n', 'a b c\n1 2 3\n', 'a a a\n1 2 3\n', 'b b b b\n7 1 1 1\n', 'a a b b a\n1 2 3 4 5\n', 'x\n9\n'] })

t({ lv: 364, concept: '文字列: 長さ3の回文部分列の種類数', title: '長さ3の回文部分列の種類数', tags: ['文字列'], io: '英小文字の文字列が1行で与えられます。', ask: '部分列として作れる長さ3の回文(xyx型)の相異なる種類数を出力してください。', h1: '外側の文字 x ごとに最初と最後の出現位置を見る。', h2: 'その間にある文字の種類数が、x を外側に持つ回文の数。', ref: 's=input()\nans=0\nfor c in set(s):\n    i=s.find(c)\n    j=s.rfind(c)\n    if j-i>1:\n        ans+=len(set(s[i+1:j]))\nprint(ans)', tip: '「外側の文字で場合分けして内側を集合で数える」と全列挙が26×O(n)で済む。両端を最も外側に取るのが常に最適。', ins: ['aabca\n', 'adc\n', 'bbcbaba\n', 'aaa\n', 'abcba\n', 'aa\n'] })

t({ lv: 365, concept: '桁DP: 桁が非減少の数の個数', title: '桁が左から非減少の数の個数', tags: ['数学'], io: '正整数 N が1行で与えられます。', ask: '1 以上 N 以下で、10進の桁が左から右へ非減少(例: 1224)である数の個数を出力してください。', h1: '各数の桁を文字列で見て隣接比較。', h2: '大きな N では桁DP(直前の桁を状態に持つ)で数える。', ref: 'n=int(input())\ncnt=0\nfor x in range(1,n+1):\n    s=str(x)\n    if all(s[i]<=s[i+1] for i in range(len(s)-1)):\n        cnt+=1\nprint(cnt)', tip: '桁が非減少の数は重複組合せと一対一対応する(d桁ならH(9,d)通り)。数え上げの言い換えの練習台。', ins: ['100\n', '10\n', '25\n', '9\n', '1000\n', '500\n'] })

t({ lv: 366, concept: 'bitDP: 適合割当の場合の数', title: '全員に仕事を割り当てる場合の数', tags: ['bitDP'], io: '1行目に n、続く n 行に n×n の適合行列(人iが仕事jをできるなら1)が与えられます。', ask: '全員に相異なる仕事を1つずつ割り当てる方法の数を出力してください。', h1: '使った仕事の集合をビットマスクで持つ。', h2: 'dp[mask]=先頭 popcount(mask) 人に mask の仕事を割り当てる場合の数。', ref: 'n=int(input())\na=[list(map(int,input().split())) for _ in range(n)]\ndp=[0]*(1<<n)\ndp[0]=1\nfor mask in range(1<<n):\n    i=bin(mask).count("1")\n    if i>=n:\n        continue\n    for j in range(n):\n        if not mask>>j&1 and a[i][j]:\n            dp[mask|1<<j]+=dp[mask]\nprint(dp[(1<<n)-1])', tip: 'これは0/1行列のパーマネントの計算。行列式と違い符号がないためNP困難で、bitDPのO(2^n·n)が実用解。', ins: ['2\n1 1\n1 1\n', '2\n1 0\n0 1\n', '2\n0 1\n0 1\n', '3\n1 1 1\n1 1 1\n1 1 1\n', '3\n1 1 0\n0 1 1\n1 0 1\n', '1\n1\n'] })

t({ lv: 367, concept: 'bitDP: 隣接和が平方数の順列数', title: '隣り合う和が平方数になる並べ方', tags: ['bitDP', '数論'], io: '相異なる非負整数の列が1行で空白区切りで与えられます。', ask: '全要素を一列に並べ、隣り合う2数の和が全て完全平方数になる並べ方の総数を出力してください。', h1: '和が平方数になるペアを辺としたグラフのハミルトン路を数える。', h2: 'dp[使った集合][最後の要素] で遷移。', ref: 'import math\na=list(map(int,input().split()))\nn=len(a)\nok=[[False]*n for _ in range(n)]\nfor i in range(n):\n    for j in range(n):\n        if i!=j:\n            s=a[i]+a[j]\n            r=math.isqrt(s)\n            ok[i][j]=r*r==s\ndp=[[0]*n for _ in range(1<<n)]\nfor i in range(n):\n    dp[1<<i][i]=1\nfor mask in range(1<<n):\n    for last in range(n):\n        if dp[mask][last]:\n            for j in range(n):\n                if not mask>>j&1 and ok[last][j]:\n                    dp[mask|1<<j][j]+=dp[mask][last]\nprint(sum(dp[(1<<n)-1][i] for i in range(n)) if n>1 else 1)', tip: '条件を満たす隣接関係をグラフ化するとハミルトン路の数え上げに帰着する。「並べ方の制約」→「グラフの辺」は強力な変換。', ins: ['1 17 8\n', '1 3\n', '5\n', '1 2 3\n', '0 4 5\n', '2 7 9 16\n'] })

t({ lv: 368, concept: '数論: 順列の位数', title: '順列を何回で恒等に戻せるか', tags: ['数論'], io: '1〜n の順列 p が1行で空白区切りで与えられます。', ask: '順列を k 回合成すると恒等順列(全員が元の位置)になる最小の k≥1 を出力してください。', h1: '順列をサイクルに分解する。', h2: '答えは全サイクル長の最小公倍数。', ref: 'import math\np=list(map(int,input().split()))\nn=len(p)\nseen=[False]*n\nans=1\nfor i in range(n):\n    if not seen[i]:\n        l=0\n        j=i\n        while not seen[j]:\n            seen[j]=True\n            j=p[j]-1\n            l+=1\n        ans=ans*l//math.gcd(ans,l)\nprint(ans)', tip: '順列の位数=サイクル長のLCM。シャッフルを繰り返すと必ず元に戻る(52枚のリフルシャッフルは8回)のはこの性質。', ins: ['2 3 1\n', '1 2 3\n', '2 1 4 3\n', '2 3 1 5 4\n', '1\n', '3 1 2 5 6 4\n'] })

t({ lv: 369, concept: '数論: 一次不定方程式の非負解の個数', title: 'ax+by=cの非負整数解の個数', tags: ['数論'], io: '正整数 a b c が空白区切りで1行で与えられます。', ask: 'ax+by=c を満たす非負整数の組 (x,y) の個数を出力してください。', h1: 'x を 0 から c//a まで動かす。', h2: '残り c-ax が b で割り切れるか確認。', ref: 'a,b,c=map(int,input().split())\ncnt=0\nfor x in range(c//a+1):\n    r=c-a*x\n    if r%b==0:\n        cnt+=1\nprint(cnt)', tip: '可解性(gcdの判定)の次は解の個数。解は等差(xがb/g刻み)に並ぶので、範囲の長さから個数が読める。', ins: ['2 3 12\n', '3 5 7\n', '1 1 5\n', '2 4 7\n', '5 7 35\n', '2 2 8\n'] })

t({ lv: 370, concept: '数論: 逆元の総和 mod p', title: '1からnの逆元の和', tags: ['数論'], io: 'n と素数 p (n<p) が空白区切りで1行で与えられます。', ask: '1⁻¹+2⁻¹+…+n⁻¹ を p で割った余りを出力してください(逆元は mod p)。', h1: '逆元を1つずつ pow で求めてもよいが O(n log p)。', h2: '線形漸化式 inv[i]=-(p//i)·inv[p%i] mod p なら O(n)。', ref: 'n,p=map(int,input().split())\ninv=[0]*(n+1)\ninv[1]=1\nfor i in range(2,n+1):\n    inv[i]=(-(p//i)*inv[p%i])%p\nprint(sum(inv[1:n+1])%p)', tip: 'p=qi+r と書くと qi+r≡0 から inv(i)≡-q·inv(r) が出る。逆元表の線形構築は階乗逆元の前計算と並ぶ定石。', ins: ['3 7\n', '1 5\n', '4 13\n', '6 7\n', '10 101\n', '2 3\n'] })

t({ lv: 371, concept: '木: 行きがけ順の出力', title: '木の行きがけ順 (preorder)', tags: ['グラフ', '再帰'], io: '1行目に頂点数 n、続く n-1 行に木の辺 u v が与えられます。根は1、子は番号の小さい順に訪れます。', ask: '行きがけ順(訪れた順)で頂点番号を空白区切りで出力してください。', h1: '根からDFSし、入った瞬間に記録する。', h2: '隣接リストをソートして親以外を再帰。', ref: 'import sys\nsys.setrecursionlimit(10000)\nn=int(input())\ng=[[] for _ in range(n+1)]\nfor _ in range(n-1):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\nres=[]\ndef dfs(x,par):\n    res.append(x)\n    for y in sorted(g[x]):\n        if y!=par:\n            dfs(y,x)\ndfs(1,0)\nprint(*res)', tip: '行きがけ(pre)/帰りがけ(post)の時刻は部分木が連続区間になる性質を持ち、オイラーツアーや部分木クエリの土台になる。', ins: ['5\n1 2\n1 3\n2 4\n2 5\n', '1\n', '3\n1 3\n1 2\n', '4\n1 2\n2 3\n3 4\n', '6\n1 4\n1 2\n2 5\n2 3\n4 6\n', '2\n2 1\n'] })

t({ lv: 372, concept: '木: 直径と同じ長さのパスの本数', title: '最長距離になる頂点対の数', tags: ['グラフ', 'BFS'], io: '1行目に頂点数 n(2以上)、続く n-1 行に木の辺が与えられます。', ask: '木の直径(最遠頂点対の距離)と同じ距離になる頂点対 {u,v} の個数を出力してください。', h1: '各頂点からBFSで全頂点への距離を求める。', h2: '全ペアの距離の最大値と、その出現回数を数える(u<vで1回ずつ)。', ref: 'from collections import deque\nn=int(input())\ng=[[] for _ in range(n+1)]\nfor _ in range(n-1):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\nbest=0\ncnt=0\nfor s in range(1,n+1):\n    dist=[-1]*(n+1)\n    dist[s]=0\n    q=deque([s])\n    while q:\n        x=q.popleft()\n        for y in g[x]:\n            if dist[y]<0:\n                dist[y]=dist[x]+1\n                q.append(y)\n    for v in range(s+1,n+1):\n        if dist[v]>best:\n            best=dist[v]\n            cnt=1\n        elif dist[v]==best:\n            cnt+=1\nprint(cnt)', tip: '直径の端点対は複数あり得る(星形ならC(葉,2)個)。最大値と個数を同時に追うパターンはここでも使える。', ins: ['4\n1 2\n2 3\n3 4\n', '4\n1 2\n1 3\n1 4\n', '2\n1 2\n', '5\n1 2\n2 3\n3 4\n3 5\n', '6\n1 2\n1 3\n2 4\n2 5\n3 6\n', '3\n1 2\n2 3\n'] })

t({ lv: 373, concept: '文字列: 最長の回文接頭辞', title: '回文である最長の接頭辞', tags: ['文字列'], io: '文字列が1行で与えられます。', ask: '回文になっている接頭辞のうち最長のものの長さを出力してください。', h1: '長い方から順に接頭辞を試す。', h2: '先頭1文字は必ず回文なので答えは1以上。', ref: 's=input()\nfor L in range(len(s),0,-1):\n    t=s[:L]\n    if t==t[::-1]:\n        print(L)\n        break', tip: '最長回文接頭辞は「s+逆順(s)」の接頭辞関数(KMP)でO(n)でも求まる。文字列を最小追加で回文化する問題の核。', ins: ['ababa\n', 'abac\n', 'abc\n', 'aabaax\n', 'z\n', 'abb\n'] })

t({ lv: 374, concept: 'データ構造: 区間最小の値の個数', title: '区間の最小値とその個数', tags: ['データ構造'], io: '1行目に n q、2行目に整数列、続く q 行に区間 l r が与えられます。', ask: '各区間 [l,r] の最小値と、その区間内での出現回数を空白区切りで1行ずつ出力してください。', h1: '小さい入力なら区間を切り出して min と count。', h2: 'セグメント木なら (最小値, 個数) のペアをマージする。', ref: 'n,q=map(int,input().split())\na=list(map(int,input().split()))\nfor _ in range(q):\n    l,r=map(int,input().split())\n    seg=a[l-1:r]\n    m=min(seg)\n    print(m,seg.count(m))', tip: 'セグメント木のノードに(値,個数)の組を載せると「最小値の個数」も対数時間で答えられる。モノイドの拡張の典型例。', ins: ['5 2\n3 1 2 1 5\n1 5\n3 5\n', '3 1\n7 7 7\n1 3\n', '4 2\n4 3 2 1\n2 3\n1 1\n', '2 1\n5 5\n1 2\n', '6 2\n1 2 1 2 1 2\n1 6\n2 4\n', '1 1\n9\n1 1\n'] })

t({ lv: 375, concept: '貪欲: 区間と点の最大マッチング', title: '区間に点を割り当てる最大数', tags: ['貪欲'], io: '1行目に区間数 n と点数 m、続く n 行に区間 l r、最後の行に m 個の点の座標が与えられます。', ask: '各区間には範囲内の点を高々1つ、各点は高々1つの区間に割り当てるとき、割り当ての最大数を出力してください。', h1: '区間を右端の昇順に処理する。', h2: '各区間には使える点のうち最小の座標を割り当てるのが最適。', ref: 'n,m=map(int,input().split())\niv=[tuple(map(int,input().split())) for _ in range(n)]\npts=sorted(map(int,input().split()))\nused=[False]*m\niv.sort(key=lambda t:(t[1],t[0]))\ncnt=0\nfor l,r in iv:\n    for i in range(m):\n        if not used[i] and l<=pts[i]<=r:\n            used[i]=True\n            cnt+=1\n            break\nprint(cnt)', tip: '二部マッチングだが区間の構造があるのでフロー不要の貪欲で最適になる。「右端が早い区間ほど選択肢が減る」順に処理する交換論法。', ins: ['2 2\n1 3\n2 5\n2 4\n', '2 1\n1 2\n1 2\n1\n', '1 2\n5 6\n1 2\n', '3 3\n1 10\n2 3\n5 6\n2 6 7\n', '2 2\n1 1\n1 1\n1 1\n', '3 2\n1 2\n2 3\n3 4\n2 3\n'] })

t({ lv: 376, concept: 'グラフ: 成功確率最大の経路', title: '成功確率が最大の経路', tags: ['グラフ', 'ダイクストラ'], io: '1行目に n m s t、続く m 行に無向辺 u v p(通行成功確率、小数)が与えられます。', ask: 's から t へ行くとき、通る辺の確率の積の最大値を小数第4位まで出力してください(到達不能なら 0.0000)。', h1: '和の最小化を積の最大化に置き換えたダイクストラ。', h2: '確率が大きい順に確定させる(負号をつけてヒープへ)。', ref: 'import heapq\nn,m,s,t=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    parts=input().split()\n    u=int(parts[0])\n    v=int(parts[1])\n    p=float(parts[2])\n    g[u].append((v,p))\n    g[v].append((u,p))\nprob=[0.0]*(n+1)\nprob[s]=1.0\npq=[(-1.0,s)]\nwhile pq:\n    np_,x=heapq.heappop(pq)\n    cur=-np_\n    if cur<prob[x]:\n        continue\n    for y,p in g[x]:\n        q=cur*p\n        if q>prob[y]:\n            prob[y]=q\n            heapq.heappush(pq,(-q,y))\nprint(f"{prob[t]:.4f}")', tip: '辺重みの積は log を取れば和になる=ダイクストラがそのまま使える(確率≤1なので「距離」は単調減少)。', ins: ['3 3 1 3\n1 2 0.5\n2 3 0.5\n1 3 0.2\n', '3 3 1 3\n1 2 0.5\n2 3 0.5\n1 3 0.3\n', '3 1 1 3\n1 2 0.5\n', '2 1 1 2\n1 2 0.9\n', '4 4 1 4\n1 2 0.9\n2 4 0.9\n1 3 0.5\n3 4 0.5\n', '2 2 1 2\n1 2 0.4\n1 2 0.6\n'] })

t({ lv: 377, concept: '数論: 三つの平方数の和で表せるか', title: '3個の平方数の和で表せるか', tags: ['数論'], io: '非負整数 n が1行で与えられます。', ask: 'n を3個以下の平方数(0²も可)の和で表せるなら yes、表せなければ no を出力してください。', h1: 'ルジャンドルの三平方定理を使う。', h2: '表せないのは 4^a(8b+7) の形の数だけ。4で割れるだけ割って mod 8 を見る。', ref: 'n=int(input())\nm=n\nwhile m%4==0 and m>0:\n    m//=4\nprint("no" if m%8==7 else "yes")', tip: 'ルジャンドルの三平方定理(1798): n=4^a(8b+7) だけが三平方和で表せない。四平方和なら全ての自然数が表せる(ラグランジュ)。', ins: ['7\n', '6\n', '28\n', '33\n', '0\n', '112\n'] })

t({ lv: 378, concept: '貪欲: マージで辞書順最大', title: '2列を混ぜて作る辞書順最大の文字列', tags: ['貪欲', '文字列'], io: '2行に英小文字の文字列 s と t が与えられます。', ask: '両方の文字列から先頭の文字を交互任意に取り(相対順序は保つ)、全文字を使って作れる辞書順最大の文字列を出力してください。', h1: '先頭文字が大きい方から取る。', h2: '先頭が同じときは残り全体(接尾辞)を比較して大きい方から取る。', ref: 's=input()\nt=input()\nres=[]\ni=j=0\nwhile i<len(s) or j<len(t):\n    if s[i:]>t[j:]:\n        res.append(s[i])\n        i+=1\n    else:\n        res.append(t[j])\n        j+=1\nprint("".join(res))', tip: '先頭が同じ文字のときに接尾辞ごと比較するのが正解(片方だけ見ると反例がある)。Pythonはスライス比較1発で書ける。', ins: ['cabaa\nbcaaa\n', 'abcabc\nabdcaba\n', 'a\nb\n', 'aa\naa\n', 'zz\nz\n', 'b\nab\n'] })

t({ lv: 379, concept: 'グラフ: 長さ4の閉路の数', title: '長さ4のサイクルの個数', tags: ['グラフ'], io: '1行目に n m、続く m 行に単純無向グラフの辺が与えられます。', ask: '長さ4の単純サイクル(C4)の個数を出力してください。', h1: 'C4は「2頂点と、その共通隣接点2つ」でできる。', h2: '各頂点対の共通隣接数 c から C(c,2) を足し、最後に2で割る(対角の重複)。', ref: 'n,m=map(int,input().split())\nadj=[set() for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    adj[u].add(v)\n    adj[v].add(u)\ntotal=0\nfor u in range(1,n+1):\n    for v in range(u+1,n+1):\n        c=len(adj[u]&adj[v])\n        total+=c*(c-1)//2\nprint(total//2)', tip: 'C4の数え上げは「対角線で分解」する。三角形(C3)の次に基本のモチーフカウントで、SNS分析などにも現れる。', ins: ['4 4\n1 2\n2 3\n3 4\n4 1\n', '4 6\n1 2\n1 3\n1 4\n2 3\n2 4\n3 4\n', '3 3\n1 2\n2 3\n3 1\n', '5 4\n1 2\n2 3\n3 4\n4 5\n', '6 7\n1 2\n2 3\n3 4\n4 1\n4 5\n5 6\n6 1\n', '2 1\n1 2\n'] })

t({ lv: 380, concept: '数論: 二項係数の奇数の個数', title: 'パスカル三角形n行目の奇数の数', tags: ['数論'], io: '非負整数 n が1行で与えられます。', ask: '二項係数 C(n,0),…,C(n,n) のうち奇数であるものの個数を出力してください。', h1: 'リュカの定理より C(n,k) が奇数 ⇔ k のビットが n のビットに含まれる。', h2: '答えは 2^(nの立っているビット数)。', ref: 'n=int(input())\nprint(2**bin(n).count("1"))', tip: 'パスカルの三角形を奇数だけ塗るとシェルピンスキーのギャスケット(フラクタル)が現れる。その行ごとの個数が 2^popcount(n)。', ins: ['4\n', '0\n', '7\n', '10\n', '100\n', '1\n'] })

t({ lv: 381, concept: 'いもす法: 対角線への区間加算', title: '斜めの区間加算を重ねた最大値', tags: ['累積和'], io: '1行目に盤の大きさ n と操作数 m、続く m 行に「r c L」(マス(r,c)から右下方向にL個のマスへ1を加算、1始まり)が与えられます。', ask: '全操作後の盤面の最大値を出力してください。', h1: '斜め方向にも差分(いもす法)が使える。', h2: '開始マスに+1、(r+L,c+L)に-1 を置き、各対角線に沿って累積する。', ref: 'n,m=map(int,input().split())\nd=[[0]*(n+2) for _ in range(n+2)]\nfor _ in range(m):\n    r,c,L=map(int,input().split())\n    d[r][c]+=1\n    d[r+L][c+L]-=1\nans=0\nfor i in range(1,n+1):\n    for j in range(1,n+1):\n        if i>1 and j>1:\n            d[i][j]+=d[i-1][j-1]\n        if d[i][j]>ans:\n            ans=d[i][j]\nprint(ans)', tip: 'いもす法は走る方向に沿って差分を置くのが本質で、縦横だけでなく斜め45度にも適用できる。', ins: ['3 2\n1 1 3\n2 2 2\n', '2 1\n1 2 1\n', '4 3\n1 1 2\n2 2 2\n3 3 2\n', '3 3\n1 1 1\n1 1 1\n1 1 1\n', '3 1\n3 1 1\n', '5 2\n1 2 4\n2 3 3\n'] })

t({ lv: 382, concept: 'データ構造: 更新つき区間の最大部分和', title: '更新つき区間内の最大部分和', tags: ['データ構造'], io: '1行目に n q、2行目に整数列、続く q 行に「1 i x」(i番目をxに変更)または「2 l r」が与えられます。', ask: '各「2 l r」に対し、区間 [l,r] の中の空でない連続部分列の和の最大値を1行ずつ出力してください。', h1: '小さい入力なら区間ごとにKadane法。', h2: 'セグメント木なら(総和,最大接頭辞,最大接尾辞,最大部分和)の4つ組を持つとマージできる。', ref: 'n,q=map(int,input().split())\na=list(map(int,input().split()))\nfor _ in range(q):\n    t,x,y=map(int,input().split())\n    if t==1:\n        a[x-1]=y\n    else:\n        best=-10**18\n        cur=-10**18\n        for v in a[x-1:y]:\n            cur=max(v,cur+v)\n            best=max(best,cur)\n        print(best)', tip: 'セグメント木に「総和・接頭辞最大・接尾辞最大・部分和最大」の4値を載せると区間Kadaneが対数時間になる。合成できる情報設計の代表例。', ins: ['5 3\n1 -2 3 -1 4\n2 1 5\n1 2 5\n2 1 5\n', '3 1\n-5 -2 -7\n2 1 3\n', '4 2\n2 2 2 2\n2 2 3\n2 1 4\n', '2 2\n1 1\n1 1 -3\n2 1 2\n', '6 2\n1 2 -10 3 4 -1\n2 1 6\n2 4 6\n', '1 1\n5\n2 1 1\n'] })

t({ lv: 383, concept: 'ヒープ: 最小のペア和k個', title: '2列から作るペア和の小さい方からk個', tags: ['ヒープ'], io: '1行目に k、2行目に昇順の列 a、3行目に昇順の列 b が与えられます。', ask: 'a の要素と b の要素のペア和すべてのうち、小さい方から k 個(総数未満なら全部)を昇順に空白区切りで出力してください。', h1: '各 a[i] について b[0] とのペアをヒープに入れて開始。', h2: '取り出したペア (i,j) の次は (i,j+1) を入れる。', ref: 'import heapq\nk=int(input())\na=list(map(int,input().split()))\nb=list(map(int,input().split()))\npq=[(a[i]+b[0],i,0) for i in range(len(a))]\nheapq.heapify(pq)\nres=[]\nwhile pq and len(res)<k:\n    s,i,j=heapq.heappop(pq)\n    res.append(s)\n    if j+1<len(b):\n        heapq.heappush(pq,(a[i]+b[j+1],i,j+1))\nprint(*res)', tip: 'n×m個の候補を全列挙せず「各行の先頭だけ」をヒープに入れて1つずつ進める。k番目の最小を扱う問題の汎用フレーム。', ins: ['3\n1 7 11\n2 4 6\n', '2\n1 1 2\n1 2 3\n', '4\n1 2\n3 4\n', '1\n5\n5\n', '5\n1 3\n2 4\n', '3\n0 0\n0 0\n'] })

t({ lv: 384, concept: '二分探索: 山型配列の頂上', title: '山型配列の頂上の位置', tags: ['二分探索'], io: '厳密に増加してから厳密に減少する山型の列が1行で与えられます。', ask: '最大値(頂上)の位置(0始まり)を出力してください。線形走査ではなく二分探索で解ける形です。', h1: 'a[mid] と a[mid+1] を比べる。', h2: '増加中なら頂上は右側、減少中なら mid 以左にある。', ref: 'a=list(map(int,input().split()))\nlo,hi=0,len(a)-1\nwhile lo<hi:\n    mid=(lo+hi)//2\n    if a[mid]<a[mid+1]:\n        lo=mid+1\n    else:\n        hi=mid\nprint(lo)', tip: 'ソート済みでなくても「単調な判定関数」(登り坂か?)が作れれば二分探索できる。峰探索(peak finding)はその代表。', ins: ['1 3 2\n', '0 2 5 7 4 1\n', '1 5 2 1 0\n', '0 1 0\n', '1 2 3 4 2\n', '3 9 8 7 6 5\n'] })

t({ lv: 385, concept: 'スタック: バックスペース処理後の比較', title: 'バックスペースを含む文字列の比較', tags: ['スタック', '文字列'], io: '2行に # をバックスペースとみなす文字列が与えられます。', ask: '両者をエディタで打ち込んだ結果が等しければ yes、違えば no を出力してください。', h1: '# が来たらスタックから1文字消す(空なら何もしない)。', h2: '両方を処理して比較。', ref: 'def proc(s):\n    st=[]\n    for c in s:\n        if c=="#":\n            if st:\n                st.pop()\n        else:\n            st.append(c)\n    return "".join(st)\nprint("yes" if proc(input())==proc(input()) else "no")', tip: '「取り消し」操作の再現はスタックの十八番。後ろから走査して残す文字を決めるO(1)空間解もある。', ins: ['ab#c\nad#c\n', 'ab##\nc#d#\n', 'a#c\nb\n', 'a##c\n#a#c\n', 'bxj##tw\nbxo#j##tw\n', 'bxj##tw\nbxj###tw\n'] })

t({ lv: 386, concept: 'グラフ: SCC縮約後の辺数', title: '強連結成分に縮めた後の辺の数', tags: ['グラフ'], io: '1行目に n m、続く m 行に有向辺 u v が与えられます。', ask: '強連結成分を1頂点に縮約したDAGの辺数(多重辺は1本と数える)を出力してください。', h1: 'Kosaraju法: 行きDFSの帰りがけ順 → 逆グラフでDFS。', h2: '成分番号が異なる辺を (成分u,成分v) の集合に入れて数える。', ref: 'import sys\nsys.setrecursionlimit(100000)\nn,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nrg=[[] for _ in range(n+1)]\nes=[]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    rg[v].append(u)\n    es.append((u,v))\nseen=[False]*(n+1)\norder=[]\ndef dfs(x):\n    seen[x]=True\n    for y in g[x]:\n        if not seen[y]:\n            dfs(y)\n    order.append(x)\nfor v in range(1,n+1):\n    if not seen[v]:\n        dfs(v)\ncomp=[-1]*(n+1)\ndef rdfs(x,c):\n    comp[x]=c\n    for y in rg[x]:\n        if comp[y]<0:\n            rdfs(y,c)\nc=0\nfor v in reversed(order):\n    if comp[v]<0:\n        rdfs(v,c)\n        c+=1\nprint(len(set((comp[u],comp[v]) for u,v in es if comp[u]!=comp[v])))', tip: 'SCC縮約後は必ずDAGになる。「成分数」の次は「成分間の辺」— 依存グラフの粗視化はコンパイラやパッケージ管理の基礎。', ins: ['4 4\n1 2\n2 1\n2 3\n3 4\n', '3 3\n1 2\n2 3\n3 1\n', '2 1\n1 2\n', '5 6\n1 2\n2 1\n3 4\n4 3\n1 3\n2 4\n', '3 2\n1 2\n1 3\n', '6 7\n1 2\n2 3\n3 1\n4 5\n5 6\n6 4\n3 4\n'] })

t({ lv: 387, concept: '数論: 相異なる素因数の個数の総和', title: 'ω(2)+…+ω(N) を求める', tags: ['数論'], io: '正整数 N が1行で与えられます。', ask: 'ω(i) を i の相異なる素因数の個数とするとき、Σω(i) (i=1..N) を出力してください。', h1: '篩の要領で各素数 p の倍数すべてに+1する。', h2: 'まだ印のない数が素数(その時点でカウント0)。', ref: 'n=int(input())\nw=[0]*(n+1)\nfor p in range(2,n+1):\n    if w[p]==0:\n        for q in range(p,n+1,p):\n            w[q]+=1\nprint(sum(w))', tip: 'Σω(i)≈N·ln(ln N)+BN(メルテンスの定理)。「各素数が何回数えられるか」に視点を変えると篩1回で済む。', ins: ['10\n', '2\n', '1\n', '30\n', '100\n', '6\n'] })

t({ lv: 388, concept: '数論: 交代順列の数', title: '上下に交互の順列の数 (ジグザグ数)', tags: ['数論', 'DP'], io: '非負整数 n が1行で与えられます。', ask: '1〜n の順列のうち p1<p2>p3<p4>… と上下交互(up-down)になるものの個数を出力してください(n=0,1 は 1 とします)。', h1: 'ザイデルの三角形(ブストロフェドン変換)で計算できる。', h2: '行を交互方向に累積する: new[k]=new[k-1]+row[i-k]。', ref: 'n=int(input())\nrow=[1]\nfor i in range(1,n+1):\n    new=[0]*(i+1)\n    for k in range(1,i+1):\n        new[k]=new[k-1]+row[i-k]\n    row=new\nprint(row[n] if n>0 else 1)', tip: '交代順列の数(1,1,1,2,5,16,61,272,…)はタンジェント数・セカント数と呼ばれ、tan x + sec x のテイラー係数に現れる(Andréの定理)。', ins: ['4\n', '1\n', '2\n', '5\n', '7\n', '3\n'] })

t({ lv: 389, concept: 'bitDP: 最小集合被覆', title: '全要素を覆う最小の集合数', tags: ['bitDP'], io: '1行目に要素数 n と集合数 m、続く m 行に「個数 k と k 個の要素(1〜n)」が与えられます。', ask: '選んだ集合の和集合が全要素 {1..n} になる最小の集合数を出力してください。不可能なら -1。', h1: '各集合をビットマスクにする。', h2: 'dp[覆った集合]=最小個数 を全状態で更新。', ref: 'n,m=map(int,input().split())\nmasks=[]\nfor _ in range(m):\n    parts=list(map(int,input().split()))\n    msk=0\n    for x in parts[1:]:\n        msk|=1<<(x-1)\n    masks.append(msk)\nfull=(1<<n)-1\nINF=10**9\ndp=[INF]*(1<<n)\ndp[0]=0\nfor s in range(1<<n):\n    if dp[s]==INF:\n        continue\n    for msk in masks:\n        t=s|msk\n        if dp[s]+1<dp[t]:\n            dp[t]=dp[s]+1\nprint(dp[full] if dp[full]<INF else -1)', tip: '集合被覆はNP困難の代表だが n≤20 なら 2^n のbitDPで厳密に解ける。貪欲(最大カバー優先)は ln n 倍の近似にしかならない。', ins: ['3 3\n2 1 2\n2 2 3\n1 3\n', '3 2\n2 1 2\n1 2\n', '2 1\n2 1 2\n', '4 3\n2 1 2\n2 3 4\n3 1 3 4\n', '3 4\n1 1\n1 2\n1 3\n3 1 2 3\n', '1 1\n1 1\n'] })

t({ lv: 390, concept: 'グラフ: 点素なs-t経路の最大本数', title: '頂点を共有しない経路の最大本数', tags: ['グラフ', 'フロー'], io: '1行目に n m s t、続く m 行に無向辺 u v が与えられます(s≠t)。', ask: 's と t を結ぶ、途中の頂点を互いに共有しない経路の最大本数を出力してください。', h1: '各頂点を入口と出口に分裂させ、間に容量1の辺を張る(s,tは無制限)。', h2: 'あとは最大流。辺素(メンガーの定理の辺版)との違いは頂点分裂。', ref: 'from collections import deque,defaultdict\nn,m,s,t=map(int,input().split())\nedges=[]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    edges.append((u,v))\nif s==t:\n    print(0)\nelse:\n    cap=defaultdict(int)\n    adj=defaultdict(list)\n    def add(u,v,c):\n        if v not in adj[u]:\n            adj[u].append(v)\n        if u not in adj[v]:\n            adj[v].append(u)\n        cap[(u,v)]+=c\n    for v in range(1,n+1):\n        add(2*v,2*v+1,10**9 if v in (s,t) else 1)\n    for u,v in edges:\n        add(2*u+1,2*v,1)\n        add(2*v+1,2*u,1)\n    S,T=2*s,2*t+1\n    flow=0\n    while True:\n        par={S:None}\n        q=deque([S])\n        while q:\n            x=q.popleft()\n            if x==T:\n                break\n            for y in adj[x]:\n                if y not in par and cap[(x,y)]>0:\n                    par[y]=x\n                    q.append(y)\n        if T not in par:\n            break\n        x=T\n        while par[x] is not None:\n            p=par[x]\n            cap[(p,x)]-=1\n            cap[(x,p)]+=1\n            x=p\n        flow+=1\n    print(flow)', tip: '頂点容量は「入口→出口」の分裂で辺容量に変換する。メンガーの定理: 点素経路の最大本数=s-tを分離する最小頂点数。', ins: ['4 4 1 4\n1 2\n2 4\n1 3\n3 4\n', '4 3 1 4\n1 2\n2 3\n3 4\n', '2 1 1 2\n1 2\n', '5 6 1 5\n1 2\n2 5\n1 3\n3 5\n1 4\n4 5\n', '4 5 1 4\n1 2\n2 4\n1 3\n3 4\n2 3\n', '3 1 1 3\n1 2\n'] })

t({ lv: 391, concept: 'DP: 増加部分列の総数', title: '厳密増加部分列の総数', tags: ['DP'], io: '整数列が1行で空白区切りで与えられます。', ask: '空でない厳密増加部分列(長さ1も含む)の総数を出力してください。', h1: 'f[i]=iで終わる増加部分列の数。', h2: 'f[i]=1+Σf[j] (j<i, a[j]<a[i])。答えは総和。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nf=[1]*n\nfor i in range(n):\n    for j in range(i):\n        if a[j]<a[i]:\n            f[i]+=f[j]\nprint(sum(f))', tip: '「最長」を求めるLISのDPで max を sum に替えると「総数」になる。最適化と数え上げはDPの双子。', ins: ['1 2 3\n', '3 2 1\n', '1 3 2\n', '5\n', '2 2\n', '1 2 1 2\n'] })

t({ lv: 392, concept: 'DP: 隣接差がちょうど1の最長部分列', title: '差1でつながる最長の部分列', tags: ['DP', 'ハッシュ'], io: '整数列が1行で空白区切りで与えられます。', ask: '選んだ要素が順に「直前との差がちょうど1(±1)」になる部分列の最長の長さを出力してください。', h1: '値ごとに「その値で終わる最長」を辞書で持つ。', h2: 'dp[x]=max(dp[x-1],dp[x+1])+1 を要素順に更新。', ref: 'a=list(map(int,input().split()))\ndp={}\nbest=1\nfor x in a:\n    v=max(dp.get(x-1,0),dp.get(x+1,0))+1\n    if v>dp.get(x,0):\n        dp[x]=v\n    if dp[x]>best:\n        best=dp[x]\nprint(best)', tip: '添字でなく「値」をキーにするDPは、遷移相手が値±1のように限られるとき劇的に速い。', ins: ['1 2 3 4\n', '4 12 10 13 12 11 14 13\n', '1 3 2 2\n', '5 5 5\n', '7 8 7 8\n', '2 4 6\n'] })

export const CATALOG = TASKS
