// 生成タスク 第68波：各レベル2問化フェーズ(23)。lv866〜890 に2問目を追加。
// 数論応用/文字列上級/マッチング・フロー帯。重複なし・決定的・採点一意。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 866, concept: '数論: 非負の組合せで払えるか', title: '2種の硬貨で釣りなしで払えるか', tags: ['数論'], io: 'a b c が空白区切りで1行で与えられます。', ask: '非負整数 x, y を使って a·x + b·y = c にできるなら yes、できなければ no を出力してください。', h1: 'まず gcd(a,b) が c を割るかが必要条件。', h2: 'x を 0 から c//a まで試し、残りが b で割り切れるか見る(拡張ユークリッドで一発の解法もある)。', ref: 'a,b,c=map(int,input().split())\nok=False\nx=0\nwhile a*x<=c:\n    if (c-a*x)%b==0:\n        ok=True\n        break\n    x+=1\nprint("yes" if ok else "no")', tip: 'ベズーの等式は整数解、こちらは非負解という一段厳しい条件。gcd|c でも非負では作れない金額があり、その最大がフロベニウス数。', ins: ['3 5 7\n', '3 5 8\n', '2 4 7\n', '6 9 12\n', '5 7 23\n', '4 6 2\n'] })

t({ lv: 867, concept: '数論: 一次合同式の最小解', title: 'ax≡b を満たす最小のx', tags: ['数論'], io: 'a b m が空白区切りで1行で与えられます(解が存在する組のみ)。', ask: 'a·x ≡ b (mod m) を満たす最小の非負整数 x を出力してください。', h1: 'g=gcd(a,m) で割って互いに素な形に直す。', h2: '(a/g)x ≡ b/g (mod m/g) の解は x = (b/g)·(a/g)⁻¹ mod (m/g)。小さい m なら全数チェックでよい。', ref: 'a,b,m=map(int,input().split())\nfor x in range(m):\n    if a*x%m==b%m:\n        print(x)\n        break', tip: '解は g=gcd(a,m) 個あり、mod m/g で等間隔に並ぶ。最小解を求めたら残りは +m/g ずつ、という構造まで見えると1次合同式は卒業。', ins: ['3 6 9\n', '2 4 6\n', '5 3 7\n', '4 0 8\n', '1 5 10\n', '6 4 10\n'] })

t({ lv: 868, concept: '数論: 逆元テーブルの一括計算', title: '1からnまでの逆元を一気に', tags: ['数論'], io: 'n p が空白区切りで1行で与えられます(pは素数、n<p)。', ask: '1,2,…,n の mod p での逆元を順に空白区切りで出力してください。', h1: '1つずつ pow(i, p−2, p) でも求まるが、まとめてならもっと速い。', h2: '恒等式 inv[i] = −(p//i)·inv[p%i] mod p で線形時間の漸化式になる。', ref: 'n,p=map(int,input().split())\ninv=[0]*(n+1)\ninv[1]=1\nfor i in range(2,n+1):\n    inv[i]=(-(p//i)*inv[p%i])%p\nprint(*inv[1:])', tip: 'p = (p//i)·i + p%i を移項して割るだけで出る漸化式。階乗テーブルと組んで二項係数の前計算O(n)を支える、競技数論の基本装備。', ins: ['5 7\n', '1 2\n', '6 13\n', '4 5\n', '10 11\n', '3 1000000007\n'] })

t({ lv: 869, concept: '数論: フス・カタラン数', title: 'k分木はいくつあるか', tags: ['数学'], io: 'n k が空白区切りで1行で与えられます (k≥2)。', ask: '内部頂点が n 個の完全 k 分木(各内部頂点がちょうど k 個の子を持つ)の形の数、フス・カタラン数 C(kn, n)/((k−1)n+1) を出力してください。', h1: 'k=2 が普通のカタラン数。', h2: '公式 comb(k·n, n) を (k−1)n+1 で割る(割り切れる)。', ref: 'from math import comb\nn,k=map(int,input().split())\nprint(comb(k*n,n)//((k-1)*n+1))', tip: 'カタラン数の k 分木版。分割公式 C(kn,n)/((k−1)n+1) が整数になること自体が巡回補題(cycle lemma)の帰結で、投票問題とも根が同じ。', ins: ['0 2\n', '3 2\n', '2 3\n', '3 3\n', '1 5\n', '4 2\n'] })

t({ lv: 870, concept: '数論: 多項係数 mod p', title: 'グループ分けの数を素数で割った余り', tags: ['数論'], io: '1行目に素数 p、2行目にグループの大きさ k1 k2 … が与えられます(合計n)。', ask: 'n 個の区別できる物を大きさ k1, k2, … のグループに分ける方法の数 n!/(k1!k2!…) を p で割った余りを出力してください。', h1: '階乗を mod p で前計算する。', h2: '割り算はフェルマーの小定理の逆元 pow(x, p−2, p) で。', ref: 'p=int(input())\nks=list(map(int,input().split()))\nn=sum(ks)\nf=[1]*(n+1)\nfor i in range(1,n+1):\n    f[i]=f[i-1]*i%p\nr=f[n]\nfor k in ks:\n    r=r*pow(f[k],p-2,p)%p\nprint(r)', tip: '二項係数は多項係数の特殊形。分母の階乗を全部逆元で払う形にすると、引数が何個でも同じコードで済む。', ins: ['1000000007\n2 1\n', '7\n1 1 1\n', '13\n2 2\n', '5\n3 1\n', '1000000007\n3 3 3\n', '11\n4\n'] })

t({ lv: 871, concept: '数え上げ: 順列の位数', title: '何回繰り返すと元に戻るか', tags: ['数え上げ', '数論'], io: '1..n の順列が1行で空白区切りで与えられます。', ask: 'この並べ替え操作を繰り返して初めて元の並びに戻る回数(順列の位数)を出力してください。', h1: 'サイクルに分解する。', h2: '位数は全サイクル長の最小公倍数。', ref: 'import math\na=list(map(int,input().split()))\nn=len(a)\nseen=[False]*n\nans=1\nfor i in range(n):\n    if seen[i]:\n        continue\n    L=0\n    j=i\n    while not seen[j]:\n        seen[j]=True\n        j=a[j]-1\n        L+=1\n    ans=ans*L//math.gcd(ans,L)\nprint(ans)', tip: 'シャッフルの復元回数(完全シャッフル)を一般化した量。n人の順列の位数の最大値はランダウ関数と呼ばれ、e^√(n ln n) 程度まで伸びる。', ins: ['2 3 1\n', '1 2 3\n', '2 1 4 3\n', '2 3 1 5 4\n', '5 4 3 2 1\n', '3 1 2 5 6 4\n'] })

t({ lv: 872, concept: '数論: 完全二部グラフの全域木数', title: 'K(m,n)の全域木を数える', tags: ['数論'], io: 'm n p が空白区切りで1行で与えられます(pは素数)。', ask: '完全二部グラフ K(m,n) の全域木の総数 m^(n−1)·n^(m−1) を p で割った余りを出力してください。', h1: '公式に当てはめる。', h2: 'pow の3引数版で高速べき乗。', ref: 'm,n,p=map(int,input().split())\nprint(pow(m,n-1,p)*pow(n,m-1,p)%p)', tip: 'ケイリーの公式 n^(n−2) の二部版で、行列木定理(ラプラシアンの余因子)から導ける。数え上げの公式は「証明の道具」ごと覚えると応用が利く。', ins: ['2 2 1000000007\n', '1 5 7\n', '3 2 1000000007\n', '3 3 13\n', '4 2 101\n', '2 1 5\n'] })

t({ lv: 873, concept: '数論: 中心つき六角数の判定', title: 'ハチの巣の輪の数', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: 'n が中心つき六角数(1, 7, 19, 37, … 中心の1個の周りに六角形の輪を重ねた総数)なら、その輪の数+1(項番号 k)を出力してください。違えば -1。', h1: 'k番目は 3k(k−1)+1。', h2: 'k を1から増やして確かめる(または二次方程式を解く)。', ref: 'n=int(input())\nk=1\nwhile 3*k*(k-1)+1<n:\n    k+=1\nprint(k if 3*k*(k-1)+1==n else -1)', tip: '中心つき多角数は「外周が一定差で増える」等差の積み重ね。六角形は差6なので3k(k−1)+1。ボードゲームの六角盤のマス数はまさにこれ。', ins: ['1\n', '7\n', '19\n', '10\n', '37\n', '61\n'] })

t({ lv: 874, concept: '数え上げ: 冪等な写像の数', title: '2回やっても同じ操作の数', tags: ['数学'], io: '正整数 n が1行で与えられます。', ask: '集合 {1..n} から自分自身への写像 f で f(f(x)) が常に f(x) に等しい(冪等)ものの総数を出力してください。', h1: '冪等写像は「不動点の集合を選び、残りを不動点のどれかに送る」形。', h2: '不動点が k 個なら C(n,k)·k^(n−k)。k で総和を取る。', ref: 'from math import comb\nn=int(input())\nprint(sum(comb(n,k)*k**(n-k) for k in range(1,n+1)))', tip: '「像=不動点集合」という構造の言い換えが数え上げを2段(選ぶ×写す)に分解する。射影・正規化・丸めなど冪等な操作はプログラミングにも遍在する。', ins: ['1\n', '2\n', '3\n', '4\n', '5\n', '7\n'] })

t({ lv: 875, concept: '文字列: フィボナッチ語のk文字目', title: '無限に伸びる語の1文字を言い当てる', tags: ['文字列', '再帰'], io: '正整数 k が1行で与えられます。', ask: 'S1="a", S2="ab", 以降 Sn = S(n−1)+S(n−2) と定まるフィボナッチ語の(十分大きい項での)k 文字目を出力してください。', h1: '文字列を実際に作ると爆発する。', h2: '長さはフィボナッチ数。kが前半なら S(n−1) の中、後半なら S(n−2) の中、と長さで降りていく。', ref: 'k=int(input())\nlens=[1,2]\nwhile lens[-1]<k:\n    lens.append(lens[-1]+lens[-2])\ni=len(lens)-1\nwhile i>=2:\n    if k>lens[i-1]:\n        k-=lens[i-1]\n        i-=2\n    else:\n        i-=1\nprint("a" if k==1 else "b")\n' , tip: '「作らずに辿る」長さ配列の降下は、巨大な再帰的文字列(展開表記・ドラゴン曲線)全般に効く。フィボナッチ語は黄金比の切り捨て数列とも一致する。', ins: ['1\n', '2\n', '3\n', '5\n', '10\n', '100\n'] })

t({ lv: 876, concept: '数論: gcdがちょうどdのペア数', title: '最大公約数がぴったりdの2人組', tags: ['数論'], io: '1行目に d、2行目に正整数列が与えられます。', ask: 'i<j で gcd(a[i], a[j]) が d に等しいペアの個数を出力してください。', h1: 'まず d の倍数だけに絞る。', h2: '各値を d で割ってから「gcdが1のペア」を数える(全ペアgcd計算でもよい)。', ref: 'import math\nd=int(input())\na=list(map(int,input().split()))\nn=len(a)\ncnt=0\nfor i in range(n):\n    for j in range(i+1,n):\n        if math.gcd(a[i],a[j])==d:\n            cnt+=1\nprint(cnt)', tip: '「ちょうどd」は「dの倍数のペア」から「2d,3d,…の倍数のペア」を引くメビウス式の包除で大規模化できる。倍数で数えて篩で戻す、が数論数え上げの定石。', ins: ['2\n2 4 6\n', '1\n2 3 4\n', '3\n3 9 6\n', '5\n5 10\n', '1\n7 7\n', '4\n4 8 12 16\n'] })

t({ lv: 877, concept: '数論: 互いに素な数の総和', title: 'nと互いに素な数を全部足す', tags: ['数論'], io: '2以上の整数 n が1行で与えられます。', ask: '1 以上 n 以下で n と互いに素な数の総和を出力してください。', h1: 'gcdで確かめながら足しても求まる。', h2: 'kが互いに素なら n−k も互いに素、のペアリングから総和は n·φ(n)/2 になる。', ref: 'import math\nn=int(input())\nprint(sum(k for k in range(1,n+1) if math.gcd(k,n)==1))', tip: '対称ペア (k, n−k) の平均が n/2 なので総和は個数×n/2。対称性で総和を潰す小技は、証明にも検算にも使える二刀流。', ins: ['2\n', '6\n', '10\n', '7\n', '12\n', '9\n'] })

t({ lv: 878, concept: '数論: リウヴィル関数の部分和', title: 'λを足し続けるとどうなるか', tags: ['数論'], io: '正整数 N が1行で与えられます。', ask: 'L(N) = λ(1)+λ(2)+…+λ(N) (λは素因数の個数の偶奇による±1)を出力してください。', h1: '各数のΩの偶奇を求めて足す。', h2: '篩で最小素因数を持てば全部まとめて計算できる。', ref: 'N=int(input())\nom=[0]*(N+1)\nfor p in range(2,N+1):\n    if om[p]==0:\n        for q in range(p,N+1,p):\n            x=q\n            while x%p==0:\n                om[q]+=1\n                x//=p\ntotal=0\nfor i in range(1,N+1):\n    total+=1 if om[i]%2==0 else -1\nprint(total)', tip: 'L(N)が常に0以下というポリア予想は N=906150257 で崩れた。素朴な数値実験が「ずっと成り立ちそう」でも証明にならない、を体現する数列。', ins: ['1\n', '2\n', '10\n', '9\n', '24\n', '100\n'] })

t({ lv: 879, concept: '数学: 次の回文数', title: '次に現れる回文の数字', tags: ['数学'], io: '正整数 n が1行で与えられます。', ask: 'n より大きい最小の回文数(十進表記が回文)を出力してください。', h1: '1ずつ増やして確かめても解ける。', h2: '大きな n では「前半を反転して貼る」構成で一気に作る(前半を+1する繰り上がりに注意)。', ref: 'n=int(input())\nx=n+1\nwhile True:\n    s=str(x)\n    if s==s[::-1]:\n        print(x)\n        break\n    x+=1', tip: '回文数は前半で全体が決まるので、構成的には「前半のインクリメント」の問題になる。総当たりでも隣の回文までの距離は高々10^(桁/2)程度。', ins: ['8\n', '9\n', '10\n', '123\n', '99\n', '808\n'] })

t({ lv: 880, concept: '文字列: 1文字消して回文にできるか', title: '1文字だけ消して回文に', tags: ['文字列', '二点法'], io: '英小文字の文字列が1行で与えられます。', ask: '高々1文字削除して回文にできるなら yes、できなければ no を出力してください。', h1: '両端から比べ、食い違ったところで分岐する。', h2: '左を消すか右を消すかの2通りだけ試せばよい。', ref: 's=input()\ndef pal(l,r):\n    while l<r:\n        if s[l]!=s[r]:\n            return False\n        l+=1\n        r-=1\n    return True\nl,r=0,len(s)-1\nans="yes"\nwhile l<r:\n    if s[l]!=s[r]:\n        ans="yes" if pal(l+1,r) or pal(l,r-1) else "no"\n        break\n    l+=1\n    r-=1\nprint(ans)', tip: '最初の不一致での2分岐だけで全ケースを尽くせるのは、それ以前の部分が対称と確定しているから。k文字許す一般化は再帰でO(2^k n)。', ins: ['aba\n', 'abca\n', 'abc\n', 'a\n', 'deeee\n', 'abcdba\n'] })

t({ lv: 881, concept: '数え上げ: 長さnの二進ネックレス語の数', title: '長さnのLyndon語を数える', tags: ['数え上げ', '数論'], io: '正整数 n が1行で与えられます。', ask: '0/1からなる長さ n のLyndon語(自分のどの回転よりも辞書順で真に小さい語)の個数を出力してください。', h1: '全列挙でも小さいnなら数えられる。', h2: '公式は (1/n)·Σ_{d|n} μ(d)·2^(n/d)(メビウスの反転)。', ref: 'n=int(input())\ndef mob(x):\n    r=1\n    p=2\n    while p*p<=x:\n        if x%p==0:\n            x//=p\n            if x%p==0:\n                return 0\n            r=-r\n        p+=1\n    if x>1:\n        r=-r\n    return r\ntotal=0\nd=1\nwhile d<=n:\n    if n%d==0:\n        total+=mob(d)*2**(n//d)\n    d+=1\nprint(total//n)', tip: '2^n個の語を「原始的な首飾り」に束ね直すとメビウス反転が現れる。Lyndon語の連結で全ての語が一意に書ける(CFL分解)世界の入り口。', ins: ['1\n', '2\n', '3\n', '4\n', '6\n', '10\n'] })

t({ lv: 882, concept: '文字列: 部分文字列の一致クエリ', title: '2つの区間は同じ文字列か', tags: ['文字列'], io: '1行目に文字列、2行目にクエリ数 q、続く q 行に「a b c d」(s[a..b] と s[c..d]、1始まり両端含む)が与えられます。', ask: '各クエリについて2つの部分文字列が一致するなら yes、しなければ no を出力してください。', h1: 'スライスの比較で正しく判定できる。', h2: '大量クエリ・巨大文字列ではローリングハッシュか接尾辞配列で O(1)/クエリ に落とす。', ref: 's=input()\nq=int(input())\nfor _ in range(q):\n    a,b,c,d=map(int,input().split())\n    print("yes" if s[a-1:b]==s[c-1:d] else "no")', tip: 'ハッシュ比較は衝突と隣り合わせなので、基数と法を2組使うのが実戦の作法。正しさ最優先ならスライス比較→遅ければハッシュ、の順で進化させる。', ins: ['abcabc\n2\n1 3 4 6\n1 2 2 3\n', 'aaaa\n1\n1 2 3 4\n', 'abab\n2\n1 2 3 4\n1 3 2 4\n', 'z\n1\n1 1 1 1\n', 'abcde\n1\n1 5 1 5\n', 'xyxy\n1\n1 1 2 2\n'] })

t({ lv: 883, concept: '文字列: 1文字違いまで許す出現回数', title: 'ほぼ一致の出現を数える', tags: ['文字列'], io: '1行目にテキスト、2行目にパターンが与えられます。', ask: 'テキストの各位置で、パターンと「不一致が高々1文字」で重なる開始位置の個数を出力してください。', h1: '各開始位置で不一致数を数える。', h2: '2つ目の不一致が出たら打ち切ると速い。ビット並列や畳み込みでの高速化が先にある。', ref: 's=input()\np=input()\nn,m=len(s),len(p)\ncnt=0\nfor i in range(n-m+1):\n    miss=0\n    for j in range(m):\n        if s[i+j]!=p[j]:\n            miss+=1\n            if miss>1:\n                break\n    if miss<=1:\n        cnt+=1\nprint(cnt)', tip: '「k不一致マッチング」はDNA照合の基本形。k=1でも、FFT畳み込み(文字ごとの一致数の総和)を使うとO(σ n log n)に落とせる奥行きがある。', ins: ['abcabc\nabc\n', 'aaaa\nab\n', 'abcde\nxyz\n', 'aaa\na\n', 'abab\nbab\n', 'zzzz\nzz\n'] })

t({ lv: 884, concept: '文字列: 最頻のk文字部分列', title: '一番よく出るk文字のかたまり', tags: ['文字列', 'ハッシュ'], io: '1行目に k、2行目に文字列が与えられます (k≤長さ)。', ask: '長さ k の連続部分文字列のうち出現回数が最大のもの(同数なら辞書順最小)を出力してください。', h1: '全ての開始位置から k 文字を切り出して数える。', h2: 'Counterで数え、(−回数, 文字列) の最小を選ぶ。', ref: 'k=int(input())\ns=input()\nfrom collections import Counter\nc=Counter(s[i:i+k] for i in range(len(s)-k+1))\nprint(min(c.items(),key=lambda kv:(-kv[1],kv[0]))[0])', tip: 'ゲノム解析のk-mer頻度解析そのもの。kが大きい実データではハッシュ化(ローリングハッシュ)とメモリ設計が主戦場になる。', ins: ['2\nababab\n', '1\nmississippi\n', '3\naaaa\n', '2\nabcd\n', '4\nabababab\n', '1\nzz\n'] })

t({ lv: 885, concept: '文字列: 回転一致の最小シフト量', title: '何文字ずらせば一致するか', tags: ['文字列'], io: '1行目と2行目に同じ長さの文字列 s, t が与えられます。', ask: 's を左に d 文字回転すると t に一致する最小の d (0以上)を出力してください。一致させられなければ -1。', h1: 's+s の中に t を探す。', h2: 'find の位置がそのまま最小シフト量。', ref: 's=input()\nt=input()\nif len(s)!=len(t):\n    print(-1)\nelse:\n    d=(s+s).find(t)\n    print(d if d!=-1 and d<len(s) else (0 if s==t else -1))', tip: '「2倍に連結して検索」は回転問題の万能変換。findの位置=シフト量という対応まで取れるので、判定から構成まで一気に済む。', ins: ['abcde\ncdeab\n', 'abc\nabc\n', 'ab\nba\n', 'aa\naa\n', 'abc\nacb\n', 'abab\nbaba\n'] })

t({ lv: 886, concept: '文字列: 文字パターンの同型判定', title: '同じ形の文字列か', tags: ['文字列', 'ハッシュ'], io: '1行目と2行目に文字列が与えられます。', ask: '一方の文字を一貫した一対一の対応で置き換えて他方にできる(同型、例 egg と add)なら yes、そうでなければ no を出力してください。', h1: '各文字を「初出の位置」で置き換えた正規形を作る。', h2: '両方の正規形が一致すれば同型(一対一なので両方向を確認する意味も込みで初出番号化が効く)。', ref: 's=input()\nt=input()\ndef norm(x):\n    first={}\n    out=[]\n    for c in x:\n        if c not in first:\n            first[c]=len(first)\n        out.append(first[c])\n    return out\nprint("yes" if norm(s)==norm(t) else "no")', tip: '初出番号化は「名前を消して構造だけ残す」正規形。変数名を無視したコードクローン検出も同じ発想で書ける。', ins: ['egg\nadd\n', 'foo\nbar\n', 'paper\ntitle\n', 'ab\naa\n', 'abc\nabc\n', 'abab\ncdcd\n'] })

t({ lv: 887, concept: 'bitDP: 割当の最大コスト最小化', title: '一番重い担当を軽くする割り当て', tags: ['bitDP'], io: '1行目に n (n≤10)、続く n 行に n×n のコスト行列(行=作業者、列=仕事)が与えられます。', ask: '作業者と仕事を1対1に割り当て、「最大の担当コスト」を最小化した値を出力してください。', h1: '合計最小(ハンガリー法)とは目的が違う。', h2: 'dp[使った仕事の集合] を「最小化された最大コスト」とし、次の作業者の割り当てで max を取りながら遷移。', ref: 'n=int(input())\nc=[list(map(int,input().split())) for _ in range(n)]\nINF=float("inf")\ndp=[INF]*(1<<n)\ndp[0]=0\nfor mask in range(1<<n):\n    if dp[mask]==INF:\n        continue\n    i=bin(mask).count("1")\n    if i==n:\n        continue\n    for j in range(n):\n        if not mask>>j&1:\n            v=max(dp[mask],c[i][j])\n            if v<dp[mask|1<<j]:\n                dp[mask|1<<j]=v\nprint(dp[(1<<n)-1])', tip: 'ボトルネック割当問題。合計でなくmaxの最適化は「コストを閾値で0/1化して完全マッチングがあるか」の二分探索でも解け、2つの解法の対応が美しい。', ins: ['2\n1 2\n2 1\n', '2\n5 9\n9 5\n', '3\n1 2 3\n2 3 1\n3 1 2\n', '1\n7\n', '3\n4 4 4\n4 4 4\n4 4 4\n', '2\n1 10\n1 10\n'] })

t({ lv: 888, concept: 'フロー: 増強で得する辺の数', title: '容量を1増やす価値のある辺', tags: ['フロー'], io: '1行目に n m s t、続く m 行に有向辺 u v c が与えられます。', ask: 'どれか1本の辺の容量を1増やしたとき最大流が増える、そのような辺の本数を出力してください。', h1: '各辺で試して最大流を再計算しても正しい。', h2: '実は「最小カットを構成する全てのカットに共通して入る辺」だけが効く(残余グラフの到達性で判定できる)。', ref: 'from collections import deque,defaultdict\nn,m,s,t=map(int,input().split())\nedges=[tuple(map(int,input().split())) for _ in range(m)]\ndef maxflow(extra):\n    cap=defaultdict(int)\n    adj=defaultdict(list)\n    def add(u,v,c):\n        if v not in adj[u]:\n            adj[u].append(v)\n        if u not in adj[v]:\n            adj[v].append(u)\n        cap[(u,v)]+=c\n    for i,(u,v,c) in enumerate(edges):\n        add(u,v,c+(1 if i==extra else 0))\n    flow=0\n    while True:\n        par={s:None}\n        q=deque([s])\n        while q:\n            x=q.popleft()\n            if x==t:\n                break\n            for y in adj[x]:\n                if y not in par and cap[(x,y)]>0:\n                    par[y]=x\n                    q.append(y)\n        if t not in par:\n            break\n        b=float("inf")\n        x=t\n        while par[x] is not None:\n            p=par[x]\n            if cap[(p,x)]<b:\n                b=cap[(p,x)]\n            x=p\n        x=t\n        while par[x] is not None:\n            p=par[x]\n            cap[(p,x)]-=b\n            cap[(x,p)]+=b\n            x=p\n        flow+=b\n    return flow\nbase=maxflow(-1)\nprint(sum(1 for i in range(m) if maxflow(i)>base))', tip: '感度分析(どこがボトルネックか)は最適値そのものより実務価値が高いことが多い。全再計算→残余グラフの構造利用、と精度を保ったまま高速化できる。', ins: ['3 2 1 3\n1 2 1\n2 3 2\n', '2 1 1 2\n1 2 5\n', '4 4 1 4\n1 2 1\n1 3 1\n2 4 1\n3 4 1\n', '3 3 1 3\n1 2 1\n2 3 1\n1 3 1\n', '4 3 1 4\n1 2 2\n2 3 1\n3 4 2\n', '2 2 1 2\n1 2 1\n1 2 1\n'] })

t({ lv: 889, concept: 'グラフ: 2部グラフの辺彩色数', title: '同じ人の授業が重ならない時間割', tags: ['グラフ'], io: '1行目に 講師数 a クラス数 b 授業数 m、続く m 行に「講師 u がクラス v に行う授業」が与えられます(同じ組が複数回もあり)。', ask: '1コマには各講師・各クラスとも高々1授業。全授業を行うのに必要な最小コマ数を出力してください。', h1: 'これは2部グラフの辺彩色数。', h2: 'ケーニヒの定理(2部グラフの辺彩色数は最大次数に等しい)より、答えは「最も忙しい講師またはクラスの授業数」。', ref: 'a,b,m=map(int,input().split())\ndu=[0]*(a+1)\ndv=[0]*(b+1)\nfor _ in range(m):\n    u,v=map(int,input().split())\n    du[u]+=1\n    dv[v]+=1\nprint(max(max(du),max(dv)))', tip: '時間割問題の核心が「最大次数=必要コマ数」という一行の定理に潰れる(2部グラフ限定。一般グラフはΔ+1のこともある=ヴィジングの定理)。', ins: ['2 2 3\n1 1\n1 2\n2 1\n', '1 1 4\n1 1\n1 1\n1 1\n1 1\n', '2 2 2\n1 1\n2 2\n', '3 1 3\n1 1\n2 1\n3 1\n', '1 2 2\n1 1\n1 2\n', '2 3 5\n1 1\n1 2\n1 3\n2 1\n2 2\n'] })

t({ lv: 890, concept: '木: パスのGCDクエリ', title: '道すがらのGCD', tags: ['木', '数論'], io: '1行目に頂点数 n、2行目に各頂点の値、続く n−1 行に木の辺、次の行にクエリ数 q、続く q 行に頂点対 u v が与えられます。', ask: '各クエリについて、u から v へのパス上の頂点の値全てのGCDを出力してください。', h1: 'パスを親ポインタで復元する。', h2: 'BFSで親を作り、uとvから根へ遡ってパスを合成し、gcdを畳み込む。', ref: 'import math\nfrom collections import deque\nn=int(input())\nval=list(map(int,input().split()))\ng=[[] for _ in range(n+1)]\nfor _ in range(n-1):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\npar=[0]*(n+1)\ndepth=[0]*(n+1)\nseen=[False]*(n+1)\nseen[1]=True\nq=deque([1])\nwhile q:\n    x=q.popleft()\n    for y in g[x]:\n        if not seen[y]:\n            seen[y]=True\n            par[y]=x\n            depth[y]=depth[x]+1\n            q.append(y)\nqn=int(input())\nfor _ in range(qn):\n    u,v=map(int,input().split())\n    r=0\n    while depth[u]>depth[v]:\n        r=math.gcd(r,val[u-1])\n        u=par[u]\n    while depth[v]>depth[u]:\n        r=math.gcd(r,val[v-1])\n        v=par[v]\n    while u!=v:\n        r=math.gcd(r,val[u-1])\n        r=math.gcd(r,val[v-1])\n        u=par[u]\n        v=par[v]\n    r=math.gcd(r,val[u-1])\n    print(r)', tip: 'パス集約は「深さを揃えて同時に登る」LCAの歩き方そのもの。集約演算がgcd・max・XORと替わっても骨格は不変で、大規模ではダブリング表に載せる。', ins: ['3\n4 6 8\n1 2\n2 3\n1\n1 3\n', '2\n5 10\n1 2\n2\n1 2\n2 2\n', '4\n6 3 9 12\n1 2\n1 3\n3 4\n2\n2 4\n4 4\n', '5\n2 4 8 16 32\n1 2\n2 3\n3 4\n4 5\n1\n1 5\n', '3\n7 7 7\n1 2\n1 3\n1\n2 3\n', '4\n10 15 6 20\n1 2\n2 3\n2 4\n2\n1 3\n3 4\n'] })

export const CATALOG = TASKS
