// 生成タスク 第83波：各レベル3問化フェーズ(10)。lv476〜499, 501〜525 の薄い49段に3問目を追加。
// グラフ応用/幾何/二分探索/ソート帯。クラスタ3問まで可・言い換え水増し禁止。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 476, concept: 'グラフ: 葉むしりで残る頂点数', title: '端をむしり続けた芯', tags: ['グラフ'], io: '1行目に頂点数 n と辺数 m、続く m 行に無向辺 u v が与えられます。', ask: '「次数が1以下の頂点を取り除く」操作を、取り除ける頂点が無くなるまで繰り返した後に残る頂点数を出力してください。', h1: '取り除くと隣の次数も減る。', h2: 'キューに次数1以下を入れて伝播させる(トポロジカルソートの亜種)。', ref: 'from collections import deque\nn,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\ndeg=[0]*(n+1)\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\n    deg[u]+=1\n    deg[v]+=1\nremoved=[False]*(n+1)\nq=deque(v for v in range(1,n+1) if deg[v]<=1)\nfor v in q:\n    removed[v]=True\nwhile q:\n    v=q.popleft()\n    for w in g[v]:\n        if not removed[w]:\n            deg[w]-=1\n            if deg[w]<=1:\n                removed[w]=True\n                q.append(w)\nprint(sum(1 for v in range(1,n+1) if not removed[v]))', tip: '残るのは2-コアと呼ばれる「全員が2本以上で支え合う」部分。閉路を含まない枝(ぶら下がり)が全部落ちる操作で、SNSの活性ユーザー抽出(k-コア分解)の最初の一歩。', ins: ['5 5\n1 2\n2 3\n3 1\n3 4\n4 5\n', '3 2\n1 2\n2 3\n', '4 4\n1 2\n2 3\n3 4\n4 1\n', '6 6\n1 2\n2 3\n3 1\n4 5\n5 6\n6 4\n', '1 0\n', '7 6\n1 2\n2 3\n3 1\n1 4\n4 5\n5 6\n'] })

t({ lv: 477, concept: 'Union-Find: 最初に閉路ができる辺', title: '輪が閉じた瞬間の1本', tags: ['Union-Find'], io: '1行目に頂点数 n と辺数 m、続く m 行に辺 u v が順に追加されます。', ask: '初めて閉路ができる(すでに繋がっている2頂点を結ぶ)辺は何本目かを出力してください(最後まで閉路ができなければ none)。', h1: '同じ組の2頂点を結ぶ辺が閉路を作る。', h2: 'Union-Findで順に併合し、最初の失敗を報告。', ref: 'n,m=map(int,input().split())\np=list(range(n+1))\ndef find(x):\n    while p[x]!=x:\n        p[x]=p[p[x]]\n        x=p[x]\n    return x\nans="none"\nfor i in range(1,m+1):\n    u,v=map(int,input().split())\n    ru,rv=find(u),find(v)\n    if ru==rv and ans=="none":\n        ans=str(i)\n    else:\n        p[ru]=rv\nprint(ans)', tip: '森の判定(既出)が「あるか」を問うのに対し、こちらは「いつか」。オンラインに流れてくる辺を検疫するリアルタイム性が、Union-Findの得意分野そのもの。', ins: ['4 4\n1 2\n2 3\n3 4\n4 1\n', '3 2\n1 2\n2 3\n', '3 3\n1 2\n2 1\n2 3\n', '5 5\n1 2\n3 4\n2 3\n4 5\n5 1\n', '2 1\n1 2\n', '4 3\n1 2\n1 3\n2 3\n'] })

t({ lv: 478, concept: 'グラフ: 1辺消して二部にできるか', title: 'あと1本で塗り分けられる', tags: ['グラフ'], io: '1行目に頂点数 n と辺数 m、続く m 行に無向辺 u v が与えられます。', ask: '高々1本の辺を取り除いて2部グラフ(2色で隣接異色に塗れる)にできるなら yes、できなければ no を出力してください。', h1: 'もともと2部ならそのままyes。', h2: '各辺を除いた2部判定を全部試す。', ref: 'n,m=map(int,input().split())\nes=[]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    es.append((u,v))\ndef bip(skip):\n    g=[[] for _ in range(n+1)]\n    for i,(u,v) in enumerate(es):\n        if i!=skip:\n            g[u].append(v)\n            g[v].append(u)\n    color=[-1]*(n+1)\n    for s in range(1,n+1):\n        if color[s]<0:\n            color[s]=0\n            st=[s]\n            while st:\n                x=st.pop()\n                for y in g[x]:\n                    if color[y]<0:\n                        color[y]=1-color[x]\n                        st.append(y)\n                    elif color[y]==color[x]:\n                        return False\n    return True\nprint("yes" if bip(-1) or any(bip(i) for i in range(m)) else "no")', tip: '奇数長の閉路が2部性の唯一の敵なので、「全ての奇閉路が共有する1辺」があるかという問いに等しい。奇閉路が2つ独立にあると1本ではどうにもならない。', ins: ['3 3\n1 2\n2 3\n1 3\n', '6 6\n1 2\n2 3\n3 1\n4 5\n5 6\n6 4\n', '2 1\n1 2\n', '4 4\n1 2\n2 3\n3 4\n4 1\n', '5 5\n1 2\n2 3\n3 1\n3 4\n4 5\n', '5 6\n1 2\n2 3\n3 1\n3 4\n4 5\n5 3\n'] })

t({ lv: 479, concept: 'ハッシュ: 相思相愛のペア数', title: '両想いを数える', tags: ['ハッシュ'], io: '1行目に n、2行目にA組の各人が指名するB組の相手(n個)、3行目にB組の各人が指名するA組の相手(n個)が与えられます。', ask: 'お互いを指名し合っているペアの数を出力してください。', h1: 'A側のiが指す相手bについて、bの指名がiに戻るか。', h2: 'b[a[i]]==i を数える。添字の1始まりに注意。', ref: 'n=int(input())\na=list(map(int,input().split()))\nb=list(map(int,input().split()))\nprint(sum(1 for i in range(1,n+1) if b[a[i-1]-1]==i))', tip: '「行って戻る」合成写像の固定点を数えている(b∘aの固定点)。安定マッチング(同レベル帯既出)の前段として、素朴な両想いから始めるのが物語として綺麗。', ins: ['2\n1 2\n1 2\n', '2\n2 1\n2 1\n', '3\n1 1 1\n1 2 3\n', '2\n1 1\n2 2\n', '3\n2 3 1\n3 1 2\n', '1\n1\n1\n'] })

t({ lv: 480, concept: '木: 2つの葉を結ぶ最も軽い道', title: '末端どうしの最短連絡', tags: ['木'], io: '1行目に頂点数 n、続く n−1 行に重みつきの辺 u v w が与えられます(葉が2枚以上)。', ask: '葉(次数1の頂点)どうしを結ぶ道の重みの合計の最小を出力してください。', h1: '重い直径(同レベル既出)の裏返しで、軽い方の極値。', h2: '各葉からの距離をDFS/BFSで求め、葉ペアの最小を取る。', ref: 'n=int(input())\ng=[[] for _ in range(n+1)]\ndeg=[0]*(n+1)\nfor _ in range(n-1):\n    u,v,w=map(int,input().split())\n    g[u].append((v,w))\n    g[v].append((u,w))\n    deg[u]+=1\n    deg[v]+=1\nleaves=[v for v in range(1,n+1) if deg[v]==1]\nbest=None\nfor s in leaves:\n    dist={s:0}\n    st=[s]\n    while st:\n        x=st.pop()\n        for to,w in g[x]:\n            if to not in dist:\n                dist[to]=dist[x]+w\n                st.append(to)\n    for t2 in leaves:\n        if t2!=s and (best is None or dist[t2]<best):\n            best=dist[t2]\nprint(best)', tip: '直径(最遠の葉ペア)が2回BFSで求まるのと違い、最近の葉ペアには同じ近道がなく全葉からの探索が素直。maxとminで解法の対称性が崩れる好例。', ins: ['4\n1 2 5\n2 3 2\n2 4 3\n', '2\n1 2 9\n', '5\n1 2 1\n2 3 1\n3 4 1\n4 5 1\n', '4\n1 2 10\n1 3 1\n1 4 2\n', '6\n1 2 2\n1 3 3\n2 4 1\n2 5 4\n3 6 1\n', '3\n1 2 4\n2 3 6\n'] })

t({ lv: 481, concept: '木: 深さごとの頂点数の一覧', title: '各階の人口調査', tags: ['木'], io: '1行目に頂点数 n (n≥2)、2行目に頂点2〜nの親が与えられます(根は頂点1)。', ask: '深さ0(根)から最も深い階まで、各深さの頂点数を空白区切りで出力してください。', h1: '親の深さ+1で各頂点の深さが決まる。', h2: 'Counterか配列で集計して順に出力。', ref: 'n=int(input())\npar=list(map(int,input().split()))\ndepth=[0]*(n+1)\nfor i in range(2,n+1):\n    depth[i]=depth[par[i-2]]+1\nmx=max(depth[1:n+1])\ncnt=[0]*(mx+1)\nfor v in range(1,n+1):\n    cnt[depth[v]]+=1\nprint(" ".join(map(str,cnt)))', tip: '深さ別の分布(プロファイル)は木の形の要約統計で、B木やヒープの解析に登場する。最も混んだ深さ(既出)はこの一覧のargmaxにあたる。', ins: ['5\n1 1 2 2\n', '2\n1\n', '6\n1 2 3 4 5\n', '7\n1 1 1 2 2 2\n', '4\n1 1 1\n', '9\n1 1 2 2 3 3 4 4\n'] })

t({ lv: 482, concept: '木: 祖先かどうかの判定', title: '家系図をさかのぼると', tags: ['木'], io: '1行目に頂点数 n (n≥2)、2行目に頂点2〜nの親、3行目に u v が与えられます(根は頂点1)。', ask: 'u が v の祖先(u==v の場合も含む)なら yes、そうでなければ no を出力してください。', h1: 'vから親を辿って根まで登る。', h2: '途中でuに出会うか。', ref: 'n=int(input())\npar=list(map(int,input().split()))\nu,v=map(int,input().split())\nx=v\nwhile True:\n    if x==u:\n        print("yes")\n        break\n    if x==1:\n        print("no")\n        break\n    x=par[x-2]', tip: '素朴には深さ分の登りでO(木の高さ)。行きがけ順の入時刻・出時刻を前計算すると in[u]≤in[v]<out[u] のO(1)判定になる、オイラーツアーの入り口。', ins: ['5\n1 1 2 2\n1 4\n', '5\n1 1 2 2\n3 4\n', '3\n1 2\n1 3\n', '3\n1 2\n3 3\n', '4\n1 1 3\n3 4\n', '4\n1 1 3\n2 4\n'] })

t({ lv: 483, concept: 'グラフ: 島の大きさの掛け算', title: '島のサイズの相乗効果', tags: ['Union-Find'], io: '1行目に頂点数 n と辺数 m、続く m 行に無向辺 u v が与えられます。', ask: '全ての連結成分のサイズ(頂点数)の積を出力してください。', h1: '成分ごとのサイズを集める。', h2: 'サイズつきUnion-Findか探索で。', ref: 'n,m=map(int,input().split())\np=list(range(n+1))\nsz=[1]*(n+1)\ndef find(x):\n    while p[x]!=x:\n        p[x]=p[p[x]]\n        x=p[x]\n    return x\nfor _ in range(m):\n    u,v=map(int,input().split())\n    ru,rv=find(u),find(v)\n    if ru!=rv:\n        p[ru]=rv\n        sz[rv]+=sz[ru]\nans=1\nfor v in range(1,n+1):\n    if find(v)==v:\n        ans*=sz[v]\nprint(ans)', tip: 'サイズの積は「各島から代表を1人ずつ選ぶ方法の数」という数え上げの意味を持つ。和(全頂点数)や最大(既出)と並べると、同じ集計から違う統計が生える様子が見える。', ins: ['5 2\n1 2\n3 4\n', '3 0\n', '4 3\n1 2\n2 3\n3 4\n', '6 2\n1 2\n1 3\n', '2 1\n1 2\n', '7 3\n1 2\n3 4\n4 5\n'] })

t({ lv: 484, concept: 'クエリ: 区間の値域の幅', title: '区間の振れ幅を問う', tags: ['クエリ'], io: '1行目に n q、2行目に長さ n の列、続く q 行に区間 l r が与えられます。', ask: '各区間の最大値と最小値の差を1行ずつ出力してください。', h1: '最小クエリ(同レベル既出)と最大クエリの合成。', h2: 'max−minをスライスで。', ref: 'n,q=map(int,input().split())\na=list(map(int,input().split()))\nfor _ in range(q):\n    l,r=map(int,input().split())\n    seg=a[l-1:r]\n    print(max(seg)-min(seg))', tip: '2つのスパーステーブル(max用とmin用)を並走させればO(1)クエリになる、前計算の合成の練習台。株価の期間ボラティリティの照会がまさにこの形。', ins: ['5 2\n3 1 4 1 5\n1 3\n2 4\n', '3 1\n7 7 7\n1 3\n', '4 2\n1 2 3 4\n1 4\n2 3\n', '2 1\n5 2\n1 2\n', '6 2\n4 6 1 3 9 2\n2 5\n1 6\n', '1 1\n8\n1 1\n'] })

t({ lv: 485, concept: '行列: 各行の最大値の合計', title: '行ごとのエースを集める', tags: ['行列'], io: '1行目に H W、続く H 行に整数の行列が与えられます。', ask: '各行の最大値の合計を出力してください。', h1: '行ごとにmaxを取って足す。', h2: 'sum(max(row))の1行。', ref: 'h,w=map(int,input().split())\nprint(sum(max(map(int,input().split())) for _ in range(h)))', tip: '行を読みながら集計すれば行列を保存する必要がない、ストリーム処理の基本形。列版はzip(*g)を挟むだけで、軸ごとの集約の対称性が確かめられる。', ins: ['2 3\n1 5 2\n4 0 3\n', '1 1\n7\n', '3 2\n1 2\n5 5\n-3 -1\n', '2 2\n0 0\n0 0\n', '2 4\n1 2 3 4\n8 7 6 5\n', '3 3\n9 1 1\n1 9 1\n1 1 9\n'] })

t({ lv: 486, concept: '幾何: 4点は正方形か', title: '四つの点の正体', tags: ['幾何'], io: '4行に点の座標 x y が与えられます(相異なる4点)。', ask: '4点を並べ替えて正方形の頂点にできるなら yes、できなければ no を出力してください。', h1: '6本のペア距離を調べる。', h2: '距離の2乗を昇順にすると [辺,辺,辺,辺,対角,対角] で対角=辺×2。', ref: 'pts=[tuple(map(int,input().split())) for _ in range(4)]\nds=[]\nfor i in range(4):\n    for j in range(i+1,4):\n        dx=pts[i][0]-pts[j][0]\n        dy=pts[i][1]-pts[j][1]\n        ds.append(dx*dx+dy*dy)\nds.sort()\nok=ds[0]>0 and ds[0]==ds[3] and ds[4]==ds[5] and ds[4]==2*ds[0]\nprint("yes" if ok else "no")', tip: '順序不明の4点でも距離の多重集合が正方形を特徴づける、不変量による判定。ひし形(4辺等しい)との違いは対角線の条件1つで、そこを落とすと偽陽性が出る。', ins: ['0 0\n0 1\n1 0\n1 1\n', '0 0\n0 2\n2 0\n2 2\n', '0 0\n1 0\n2 0\n3 0\n', '0 0\n1 2\n3 1\n2 -1\n', '0 0\n0 1\n1 0\n1 2\n', '0 0\n2 1\n1 3\n-1 2\n'] })

t({ lv: 487, concept: '幾何: 円と直線の共有点の数', title: '円を横切るか、かすめるか', tags: ['幾何'], io: '1行目に円の中心と半径 cx cy r、2行目に直線上の相異なる2点 x1 y1 x2 y2 が与えられます。', ask: '円と直線の共有点の個数(0, 1, 2)を出力してください。', h1: '中心から直線までの距離と半径を比べる。', h2: '距離の2乗 = 外積² ÷ 方向ベクトルの長さ² を、通分して整数のまま比較。', ref: 'cx,cy,r=map(int,input().split())\nx1,y1,x2,y2=map(int,input().split())\ncross=(x2-x1)*(cy-y1)-(y2-y1)*(cx-x1)\nlen2=(x2-x1)**2+(y2-y1)**2\nleft=cross*cross\nright=r*r*len2\nif left>right:\n    print(0)\nelif left==right:\n    print(1)\nelse:\n    print(2)', tip: '距離d と r の比較を d²·len² の形に通分すると、平方根なしの整数演算で接する場合まで厳密に判れる。2円の共有点(同レベル既出)と同じ「比較の整数化」の技。', ins: ['0 0 2\n-5 0 5 0\n', '0 0 2\n-5 2 5 2\n', '0 0 2\n-5 3 5 3\n', '1 1 1\n0 0 4 0\n', '0 0 5\n3 -10 3 10\n', '2 2 1\n0 5 5 5\n'] })

t({ lv: 488, concept: '幾何: 多角形の対角線の本数', title: '頂点を結ぶ隠れた線', tags: ['幾何'], io: '多角形の頂点数 n (n≥3) が1行で与えられます。', ask: '対角線(隣り合わない2頂点を結ぶ線分)の本数を出力してください。', h1: '全ペアから辺を除く。', h2: 'C(n,2)−n、すなわち n(n−3)/2。', ref: 'n=int(input())\nprint(n*(n-3)//2)', tip: '全ペアC(n,2)からn本の辺を引く、という導出をたどると公式の丸暗記が不要になる。凸多角形の三角形分割(既出)ではこのうちn−3本を交差なしに選ぶ。', ins: ['4\n', '3\n', '5\n', '6\n', '10\n', '8\n'] })

t({ lv: 489, concept: '幾何: 円周上の格子点の数', title: '円周ぴったりの点', tags: ['幾何'], io: '正整数 r が1行で与えられます。', ask: 'x²+y²=r² を満たす格子点 (x,y) の個数を出力してください。', h1: '円内の格子点(同レベル既出)の境界だけ版。', h2: 'xを−rからrまで動かし、r²−x²が平方数か調べる。', ref: 'import math\nr=int(input())\ncnt=0\nfor x in range(-r,r+1):\n    y2=r*r-x*x\n    y=math.isqrt(y2)\n    if y*y==y2:\n        cnt+=2 if y>0 else 1\nprint(cnt)', tip: 'r=5で12個(3-4-5の直角三角形の名残)など、個数はr²の素因数のうち4k+1型の素数に支配される(2平方和定理)。数論と幾何が円周上で握手する問題。', ins: ['5\n', '1\n', '2\n', '3\n', '10\n', '25\n'] })

t({ lv: 490, concept: 'bit演算: 部分集合XORの正の最小', title: 'XORで作れる一番小さな正の値', tags: ['bit演算'], io: '正整数の列が1行で空白区切りで与えられます(XORが0でない部分集合が存在)。', ask: '空でない部分集合のXORとして作れる正の値の最小を出力してください。', h1: '作れる値の集合を育てる(既出のパターン)。', h2: '集合から正の最小を選ぶ。', ref: 'a=list(map(int,input().split()))\ns={0}\nfor x in a:\n    s|={y^x for y in s}\nprint(min(v for v in s if v>0))', tip: '線形基底を完全簡約すると最小の基底ベクトルが答えになる、と理論は言う。集合を全部育てる素朴解はその定理の実験装置で、2^ランク個で必ず頭打ちになるから爆発しない。', ins: ['3 5\n', '4 4\n', '1 2 3\n', '8\n', '6 10\n', '7 3 4\n'] })

t({ lv: 491, concept: 'BFS: スイッチで全点灯する最小回数', title: 'スイッチの組合せで全部つける', tags: ['BFS', 'bit演算'], io: '1行目に電球数 n とスイッチ数 m、2行目に初期状態(0/1の文字列)、続く m 行に各スイッチが反転させる電球の番号列が与えられます。', ask: '全ての電球を点灯(全て1)させる最小のスイッチ操作回数を出力してください(不可能なら -1)。', h1: '状態をビットマスクで持つ。', h2: '同じスイッチを2回押すのは無駄なので、状態BFSで最短を探す。', ref: 'from collections import deque\nn,m=map(int,input().split())\nstart=int(input()[::-1],2)\nmasks=[]\nfor _ in range(m):\n    mk=0\n    for b in map(int,input().split()):\n        mk|=1<<(b-1)\n    masks.append(mk)\ngoal=(1<<n)-1\ndist={start:0}\nq=deque([start])\nwhile q:\n    s=q.popleft()\n    if s==goal:\n        break\n    for mk in masks:\n        t2=s^mk\n        if t2 not in dist:\n            dist[t2]=dist[s]+1\n            q.append(t2)\nprint(dist.get(goal,-1))', tip: 'XORの可換性から押す順序は無関係で、各スイッチは押すか押さないかの2択。だからGF(2)の連立方程式(同レベル既出の階数)でも解け、BFSはその答え合わせになる。', ins: ['2 2\n00\n1\n2\n', '2 1\n01\n1\n', '3 2\n000\n1 2\n2 3\n', '2 1\n11\n1\n', '3 3\n010\n1\n3\n1 2 3\n', '4 2\n0000\n1 2\n3 4\n'] })

t({ lv: 492, concept: '行列: 2元連立方程式を解く', title: 'クラメルで一撃', tags: ['行列'], io: '1行目に a b e (ax+by=e)、2行目に c d f (cx+dy=f) が与えられます(解は一意で整数)。', ask: '解 x y を空白区切りで出力してください。', h1: '行列式 ad−bc で割る。', h2: 'x=(ed−bf)/det, y=(af−ec)/det。', ref: 'a,b,e=map(int,input().split())\nc,d,f=map(int,input().split())\ndet=a*d-b*c\nprint((e*d-b*f)//det,(a*f-e*c)//det)', tip: 'クラメルの公式は「右辺の列で置き換えた行列式の比」。2×2の逆行列(同レベル既出)を掛けるのと同じことで、detが0なら解なしか無数、の分岐点も共有している。', ins: ['1 1 3\n1 -1 1\n', '2 1 5\n1 1 3\n', '1 0 4\n0 1 -2\n', '3 2 8\n1 1 3\n', '2 3 12\n1 -1 1\n', '4 6 10\n2 2 4\n'] })

t({ lv: 493, concept: 'bit演算: kビットの逆順読み', title: 'ビット列を鏡に映す', tags: ['bit演算'], io: 'n k (0≤n<2^k) が空白区切りで1行で与えられます。', ask: 'n を k 桁の2進数とみなし、ビット列を逆順に読んだ値を出力してください。', h1: '下位から1ビットずつ取り出して積み直す。', h2: '文字列でやるなら zfill してから [::-1]。', ref: 'n,k=map(int,input().split())\nr=0\nfor _ in range(k):\n    r=(r<<1)|(n&1)\n    n>>=1\nprint(r)', tip: '高速フーリエ変換のビット反転置換や、ハッシュの拡散処理で現役の操作。「k桁とみなす」という幅の指定がないと先頭の0が消えて逆順が定まらない、仕様の要。', ins: ['6 3\n', '1 4\n', '5 3\n', '0 5\n', '12 4\n', '10 4\n'] })

t({ lv: 494, concept: '順列: 辞書順で1つ前の順列', title: '一歩だけ巻き戻す', tags: ['順列'], io: '1〜n の並べ替えが1行で空白区切りで与えられます。', ask: '辞書順でこの順列の1つ前の順列を出力してください(先頭=辞書順最小なら、最大である降順を出力)。', h1: '次の順列(既出)の鏡像: 後ろから「昇順が崩れる場所」を探す。', h2: 'a[i]>a[i+1] となる最大のiを見つけ、後ろの中でa[i]未満の最大と交換し、以降を降順に。', ref: 'a=list(map(int,input().split()))\nn=len(a)\ni=n-2\nwhile i>=0 and a[i]<=a[i+1]:\n    i-=1\nif i<0:\n    a.sort(reverse=True)\nelse:\n    j=n-1\n    while a[j]>=a[i]:\n        j-=1\n    a[i],a[j]=a[j],a[i]\n    a[i+1:]=sorted(a[i+1:],reverse=True)\nprint(" ".join(map(str,a)))', tip: '次の順列の <, 昇順ソート を >, 降順ソート に置き換えた完全な鏡像。両方書いて往復すると元に戻る、という性質そのものが最強のテストケースになる。', ins: ['1 3 2\n', '1 2 3\n', '3 1 2\n', '2 1\n', '1 2\n', '2 3 1\n'] })

t({ lv: 495, concept: '順列: 置換をk回適用した並び', title: 'シャッフルをk回重ねたら', tags: ['順列'], io: '1行目に k、2行目に置換 p (i番目の値は「iの行き先」) が与えられます。', ask: 'この置換を k 回合成した置換を空白区切りで出力してください。', h1: 'kが大きくてもサイクルの長さで割った余りだけ進めばよい。', h2: '各要素についてサイクルを見つけ、k mod 長さ だけ辿る。', ref: 'k=int(input())\np=list(map(int,input().split()))\nn=len(p)\nres=[0]*(n+1)\nseen=[False]*(n+1)\nfor s in range(1,n+1):\n    if seen[s]:\n        continue\n    cyc=[]\n    x=s\n    while not seen[x]:\n        seen[x]=True\n        cyc.append(x)\n        x=p[x-1]\n    L=len(cyc)\n    for idx,v in enumerate(cyc):\n        res[v]=cyc[(idx+k)%L]\nprint(" ".join(str(res[i]) for i in range(1,n+1)))', tip: '恒等に戻る回数(既出)がサイクル長のLCMだったのと同じ分解で、kをサイクルごとに剰余で潰せばkが天文学的でも一瞬。置換の累乗は「サイクルの回転」に分解される。', ins: ['2\n2 3 1\n', '1\n2 1\n', '4\n2 3 1\n', '3\n1 2 3\n', '2\n2 1 4 3\n', '5\n3 1 2 5 4\n'] })

t({ lv: 496, concept: 'マッチング: 不満なペアの数', title: '駆け落ち予備軍を数える', tags: ['マッチング'], io: '1行目に n、続く n 行にA組各人の希望順(B組の並び)、続く n 行にB組各人の希望順、最終行にマッチング(A組iの相手)が与えられます。', ask: '「互いに現在の相手より好き」なペア(ブロッキングペア)の数を出力してください。', h1: '安定かの判定(同レベル既出)の数え上げ版。', h2: '順位表を前計算して全ペアを確かめる。', ref: 'n=int(input())\nap=[list(map(int,input().split())) for _ in range(n)]\nbp=[list(map(int,input().split())) for _ in range(n)]\nmatch=list(map(int,input().split()))\narank=[[0]*(n+1) for _ in range(n)]\nbrank=[[0]*(n+1) for _ in range(n)]\nfor i in range(n):\n    for r,x in enumerate(ap[i]):\n        arank[i][x]=r\n    for r,x in enumerate(bp[i]):\n        brank[i][x]=r\nbmatch=[0]*(n+1)\nfor i in range(n):\n    bmatch[match[i]]=i+1\ncnt=0\nfor i in range(n):\n    for w in range(1,n+1):\n        if w!=match[i] and arank[i][w]<arank[i][match[i]] and brank[w-1][i+1]<brank[w-1][bmatch[w]]:\n            cnt+=1\nprint(cnt)', tip: 'ブロッキングペア0個が安定性の定義そのもの。Gale-Shapley(同レベル既出)の出力でこの数が必ず0になることを検証するのが、アルゴリズムの一番説得力ある試験になる。', ins: ['2\n1 2\n2 1\n1 2\n2 1\n1 2\n', '2\n2 1\n1 2\n2 1\n1 2\n1 2\n', '1\n1\n1\n1\n', '3\n1 2 3\n1 2 3\n1 2 3\n1 2 3\n1 2 3\n1 2 3\n1 2 3\n', '3\n1 2 3\n1 2 3\n1 2 3\n1 2 3\n1 2 3\n1 2 3\n3 2 1\n', '2\n1 2\n1 2\n2 1\n2 1\n2 1\n'] })

t({ lv: 497, concept: 'ハッシュ: 最も多くの単語に現れる文字', title: 'みんなに好かれる文字', tags: ['ハッシュ', '文字列'], io: '英小文字の単語が空白区切りで1行に与えられます。', ask: '最も多くの単語に(重複を数えず)現れる文字を出力してください(同数なら辞書順で小さい方)。', h1: '単語ごとに集合化してから数える。', h2: '文字ごとの「出現単語数」をCounterで。', ref: 'from collections import Counter\nc=Counter()\nfor w in input().split():\n    for ch in set(w):\n        c[ch]+=1\nprint(min(c.items(),key=lambda kv:(-kv[1],kv[0]))[0])', tip: '「文書頻度(DF)」の1文字版で、検索エンジンのTF-IDFのDF側と同じ集計。単語内の重複をsetで潰してから数えるのが「回数」との違いの一点。', ins: ['cat dog cow\n', 'ab ba\n', 'x\n', 'abc def\n', 'zoo cool moon\n', 'hi his hit\n'] })

t({ lv: 498, concept: 'スタック: 左隣で最初に小さい値の一覧', title: '各自の目の前の低い壁', tags: ['スタック'], io: '整数列が1行で空白区切りで与えられます。', ask: '各要素について「左方向で最初に現れる自分より小さい値」を求め、無ければ −1 として、空白区切りで出力してください。', h1: 'ヒストグラム最大長方形(同レベル既出)の中核部品。', h2: '自分以上をポップした後のスタックの先頭が答え。', ref: 'a=list(map(int,input().split()))\nst=[]\nout=[]\nfor x in a:\n    while st and st[-1]>=x:\n        st.pop()\n    out.append(st[-1] if st else -1)\n    st.append(x)\nprint(" ".join(map(str,out)))', tip: '距離の合計(既出)が集約値なら、こちらは配列そのものを見せる部品化。この一覧を左右両方向で作って幅を決めるのがヒストグラム問題の全実装で、部品の在庫が完成品を近くする。', ins: ['3 1 4 2\n', '1 2 3\n', '5 4 3\n', '2 2\n', '1 5 2 4\n', '9\n'] })

t({ lv: 499, concept: '行列: 90度回転で自分と一致するか', title: '回しても変わらない模様', tags: ['行列'], io: '1行目に n、続く n 行に n×n の格子が与えられます。', ask: '時計回りに90度回転させたとき元の格子と一致するなら yes、しなければ no を出力してください。', h1: '回転の構成(既出)と比較を組み合わせる。', h2: 'zip(*g[::-1]) が時計回り90度回転。', ref: 'n=int(input())\ng=[input().split() for _ in range(n)]\nr=[list(row) for row in zip(*g[::-1])]\nprint("yes" if r==g else "no")', tip: '90度回転で不変なら180度・270度でも不変(回転群の生成元)。模様の対称性は群論の言葉で分類でき、この判定は位数4の巡回対称の検出にあたる。', ins: ['2\n1 1\n1 1\n', '2\n1 2\n3 4\n', '1\n7\n', '3\n1 2 1\n2 3 2\n1 2 1\n', '2\n1 2\n2 1\n', '3\n0 1 0\n1 0 1\n0 1 0\n'] })

t({ lv: 501, concept: '二分探索: x·2^xがN以上になる最小のx', title: '爆発的に増える関数の境目', tags: ['二分探索'], io: '正整数 N が1行で与えられます。', ask: 'x×2^x が N 以上になる最小の非負整数 x を出力してください。', h1: 'f(x)=x·2^x は単調増加(x≥1)。', h2: '小さい方から試しても、答えの上限で二分探索してもよい。', ref: 'n=int(input())\nx=0\nwhile x*(1<<x)<n:\n    x+=1\nprint(x)', tip: 'f(x)=x·2^x の逆関数はランベルトのW関数の親戚で、解析的に書けない。単調性さえあれば逆関数が無くても二分探索が逆算してくれる、という発想の見本。', ins: ['10\n', '1\n', '100\n', '2\n', '64\n', '1000\n'] })

t({ lv: 502, concept: '整数: 範囲内の平方数の個数', title: '区間に潜む平方数', tags: ['整数', '二分探索'], io: 'L R が空白区切りで1行で与えられます (1≤L≤R)。', ask: 'L 以上 R 以下の平方数の個数を出力してください。', h1: '個数は平方根の床の差で書ける。', h2: 'isqrt(R) − isqrt(L−1)。', ref: 'import math\nl,r=map(int,input().split())\nprint(math.isqrt(r)-math.isqrt(l-1))', tip: '「範囲内の個数=累積の差」という発想はここでも有効で、f(x)=x以下の平方数の個数=⌊√x⌋ が累積関数になる。1つずつ判定するO(R−L)から一気にO(1)へ跳ぶ。', ins: ['1 10\n', '4 9\n', '10 20\n', '1 1\n', '50 100\n', '2 3\n'] })

t({ lv: 503, concept: '貪欲: 大きい順に軽い機械へ(LPT)の最大負荷', title: '大物から順に空いた機械へ', tags: ['貪欲', 'ヒープ'], io: '1行目に機械の台数 k、2行目に仕事の所要時間の列が与えられます。', ask: '仕事を所要時間の大きい順に並べ、順に「現時点で最も負荷の軽い機械(同点なら番号最小)」へ割り当てたときの、最も重い機械の負荷を出力してください。', h1: '指定どおりのシミュレーション。', h2: 'ヒープに(負荷, 機械番号)を入れて回す。', ref: 'import heapq\nk=int(input())\njobs=sorted(map(int,input().split()),reverse=True)\nh=[(0,i) for i in range(1,k+1)]\nheapq.heapify(h)\nfor t in jobs:\n    load,i=heapq.heappop(h)\n    heapq.heappush(h,(load+t,i))\nprint(max(load for load,i in h))', tip: 'LPT法は最適解の4/3倍以内を保証する古典ヒューリスティック(Graham 1969)。最適(bitDPで既出)との差を同じ入力で見比べると、保証つき近似の意味が体感できる。', ins: ['2\n3 3 2 2\n', '2\n5 1 1\n', '3\n4 4 4\n', '1\n2 3\n', '2\n6 4 3 2\n', '2\n1 1 1 1\n'] })

t({ lv: 504, concept: '窓: 初めて閾値を超える窓の位置', title: '警報が最初に鳴る区間', tags: ['窓'], io: '1行目に k t、2行目に整数列(長さk以上)が与えられます。', ask: '長さ k の窓の和が初めて t を厳密に超える窓の開始位置(1始まり)を出力してください(どの窓も超えなければ none)。', h1: '超える窓の数(既出)の「最初だけ」版。', h2: 'ずらしながら最初の該当でbreak。', ref: 'k,t=map(int,input().split())\na=list(map(int,input().split()))\ns=sum(a[:k])\nans="none"\nif s>t:\n    ans="1"\nelse:\n    for i in range(k,len(a)):\n        s+=a[i]-a[i-k]\n        if s>t:\n            ans=str(i-k+2)\n            break\nprint(ans)', tip: '移動合計の閾値監視はアラートシステムの基本形。全部数える問題と違いbreakできるので、平均的には早く終わる——最悪は同じ、という計算量の期待値の話にも繋がる。', ins: ['2 5\n1 2 3 4\n', '3 100\n1 2 3\n', '1 0\n0 1\n', '2 3\n2 2 2\n', '3 5\n1 1 1 4 1\n', '2 10\n5 5 5\n'] })

t({ lv: 505, concept: '整数: 銀行家の丸めで10分の1に', title: '五は偶数の味方', tags: ['整数'], io: '非負整数 n が1行で与えられます。', ask: 'n を10で割った値を「端数が5未満なら切り捨て、5超なら切り上げ、ちょうど5なら結果が偶数になる方へ丸める」(銀行家の丸め)で整数にして出力してください。', h1: '商と余りに分けて場合分け。', h2: '余りが5のときだけ商の偶奇を見る。', ref: 'n=int(input())\nq,r=divmod(n,10)\nif r>5 or (r==5 and q%2==1):\n    q+=1\nprint(q)', tip: '四捨五入は.5を常に上へ送るため統計が微妙に膨らむ。偶数丸め(round half to even)はその偏りを打ち消す方式で、Pythonのround()やIEEE754の既定もこれ。25→2, 35→4 となる。', ins: ['25\n', '35\n', '24\n', '26\n', '100\n', '15\n'] })

t({ lv: 506, concept: '整数: 平方根の床の総和', title: 'ルートの階段を足し上げる', tags: ['整数'], io: '正整数 N が1行で与えられます。', ask: '⌊√1⌋+⌊√2⌋+…+⌊√N⌋ を出力してください。', h1: '整数平方根(同レベル既出)を全部足す。', h2: 'math.isqrtの和。値が変わる境目は平方数。', ref: 'import math\nn=int(input())\nprint(sum(math.isqrt(x) for x in range(1,n+1)))', tip: '⌊√x⌋=k となる x はちょうど 2k+1 個(k²から(k+1)²−1)なので、Σk(2k+1)の形の閉じた式でO(√N)にできる。階段関数の総和は「段の幅×高さ」で数え直すのが定石。', ins: ['10\n', '1\n', '4\n', '16\n', '2\n', '25\n'] })

t({ lv: 507, concept: '数論: べき乗表現の最大指数', title: 'どこまで高いべきで書けるか', tags: ['数論'], io: '2以上の整数 n が1行で与えられます。', ask: 'n = m^k (mは2以上の整数) と書ける最大の k を出力してください(どのべき乗でも書けなければ 1)。', h1: 'べき乗で書けるか(同レベル既出)の最大化版。', h2: 'kを大きい方から試し、k乗根の整数部のk乗がnに戻るか確かめる。', ref: 'n=int(input())\ndef iroot(x,k):\n    lo,hi=1,x\n    while lo<hi:\n        mid=(lo+hi+1)//2\n        if mid**k<=x:\n            lo=mid\n        else:\n            hi=mid-1\n    return lo\nans=1\nfor k in range(2,n.bit_length()+1):\n    r=iroot(n,k)\n    if r>=2 and r**k==n:\n        ans=k\nprint(ans)', tip: '最大指数は素因数分解の指数たちのGCDに等しい(64=2⁶でgcd(6)=6、36=2²3²でgcd(2,2)=2)。2つの解法が別の理屈で同じ答えに至る、検算に最適な二重構造。', ins: ['64\n', '36\n', '7\n', '16\n', '12\n', '729\n'] })

t({ lv: 508, concept: '行列: 両方向ソート行列から目的値を探す', title: '階段を降りながら探す', tags: ['行列', '二分探索'], io: '1行目に H W と目的値 t、続く H 行に「各行も各列も昇順」の行列が与えられます。', ask: 't が行列に含まれるなら yes、含まれなければ no を出力してください。', h1: '右上の角から始めると1歩ごとに行か列が捨てられる。', h2: '今の値が大きすぎたら左へ、小さすぎたら下へ。', ref: 'first=input().split()\nh,w,t=int(first[0]),int(first[1]),int(first[2])\ng=[list(map(int,input().split())) for _ in range(h)]\ni,j=0,w-1\nans="no"\nwhile i<h and j>=0:\n    if g[i][j]==t:\n        ans="yes"\n        break\n    if g[i][j]>t:\n        j-=1\n    else:\n        i+=1\nprint(ans)', tip: '右上からの階段探索はO(H+W)で、各行に二分探索するO(H log W)より速いことも多い。負の数を数える問題(同レベル既出)と同じ「角から単調に削る」思想。', ins: ['2 2 3\n1 2\n3 4\n', '2 2 5\n1 2\n3 4\n', '3 3 7\n1 3 5\n2 6 9\n4 8 11\n', '1 1 4\n4\n', '2 3 6\n1 4 6\n2 5 8\n', '3 2 0\n1 2\n3 4\n5 6\n'] })

t({ lv: 509, concept: 'リスト: 右にある小さい要素の数の一覧', title: '自分より小さい後続を数えて', tags: ['リスト', '数え上げ'], io: '整数列が1行で空白区切りで与えられます。', ask: '各要素について「自分より右にある、自分より小さい要素の個数」を空白区切りで出力してください。', h1: '転倒数(既出)の内訳の配列。', h2: '総当たりが基準解。BITや併合で高速化できる。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nprint(" ".join(str(sum(1 for j in range(i+1,n) if a[j]<a[i])) for i in range(n)))', tip: 'この一覧の総和がちょうど転倒数。マージソートで数える高速版では、併合のたびにこの内訳が部分的に確定していく様子が見える。', ins: ['3 1 2\n', '1 2 3\n', '3 2 1\n', '5\n', '2 2 1\n', '4 1 3 2\n'] })

t({ lv: 510, concept: 'ソート: 偶数番目と奇数番目を別々に整列', title: '白マスと黒マスを別々に', tags: ['ソート'], io: '整数列が1行で空白区切りで与えられます。', ask: '奇数番目(1,3,5,…)の要素たちと偶数番目(2,4,…)の要素たちを、それぞれの位置の中で昇順に並べ替えた列を出力してください。', h1: 'スライスのステップで2系統に分ける。', h2: 'a[::2]とa[1::2]をソートして書き戻す。', ref: 'a=list(map(int,input().split()))\na[::2]=sorted(a[::2])\na[1::2]=sorted(a[1::2])\nprint(" ".join(map(str,a)))', tip: 'スライス代入 a[::2]=... は左辺に飛び飛びの位置を指定できるPythonの強力な機能。値の偶奇で分けるソート(既出)と対で、「位置」と「値」のフィルタの違いを体で覚える。', ins: ['5 4 3 2 1\n', '4 3 2 1\n', '1 2 3\n', '9 8\n', '3 1 4 1 5\n', '6 5 4 3 2 1\n'] })

t({ lv: 511, concept: '整数: 掛け算表で最も多く現れる値', title: '九九の人気者', tags: ['整数', 'ハッシュ'], io: '正整数 n が1行で与えられます。', ask: 'n×n の掛け算表(i×j、1≤i,j≤n)に最も多く現れる値を出力してください(同数なら最小の値)。', h1: '全マスをCounterへ。', h2: '(−回数, 値)の最小。', ref: 'from collections import Counter\nn=int(input())\nc=Counter(i*j for i in range(1,n+1) for j in range(1,n+1))\nprint(min(c.items(),key=lambda kv:(-kv[1],kv[0]))[0])', tip: '値vの出現回数は「vの約数でn以下、かつ相方もn以下」の個数。表の種類数(同レベル既出)と最頻値は、同じ表を種類側と度数側から見た双子の統計。', ins: ['3\n', '1\n', '4\n', '2\n', '5\n', '6\n'] })

t({ lv: 512, concept: '整数: k等分の各サイズ', title: 'なるべく均等に山分け', tags: ['整数'], io: 'n k が空白区切りで1行で与えられます (1≤k≤n)。', ask: 'n 個を k グループにできるだけ均等に分けるときの各グループのサイズを、大きい順に空白区切りで出力してください。', h1: '基本は n//k、余りの分だけ+1。', h2: '前から余り個のグループが1つ多い。', ref: 'n,k=map(int,input().split())\nq,r=divmod(n,k)\nprint(" ".join([str(q+1)]*r+[str(q)]*(k-r)))', tip: 'divmodの商と余りが「基本サイズ」と「大きい組の数」にそのまま対応する。ページネーションやシャーディングの割り付けで無数に書く、地味だが実務最頻出の計算。', ins: ['10 3\n', '7 7\n', '5 2\n', '9 3\n', '1 1\n', '8 5\n'] })

t({ lv: 513, concept: 'リスト: 消えている数の一覧', title: '出席簿の空欄すべて', tags: ['リスト', 'ハッシュ'], io: '1行目に n、2行目に 1〜n の範囲の整数 n 個(重複あり)が与えられます。', ask: '1 から n のうち列に現れない数を昇順に空白区切りで出力してください(全て揃っていれば none)。', h1: 'k番目に欠けている数(同レベル既出)の全部版。', h2: '集合との差を取る。', ref: 'n=int(input())\ns=set(map(int,input().split()))\nmiss=[str(x) for x in range(1,n+1) if x not in s]\nprint(" ".join(miss) if miss else "none")', tip: 'O(1)追加メモリでやるなら「値を添字とみなして符号を反転」する印つけ法が有名。集合との差という宣言的な書き方と、破壊的な省メモリ技の対比が学べる。', ins: ['5\n1 2 2 4 5\n', '3\n1 2 3\n', '4\n1 1 1 1\n', '5\n5 4 3 2 1\n', '6\n2 2 3 3 4 4\n', '2\n2 2\n'] })

t({ lv: 514, concept: 'ソート: 選択ソートの交換回数', title: '最小値を連れてくる回数', tags: ['ソート'], io: '整数列が1行で空白区切りで与えられます。', ask: '選択ソート(各位置について未整列部分の最小値と交換。最小値が既にその位置なら交換しない)で発生する交換の回数を出力してください。', h1: 'アルゴリズムを素直に実装して数える。', h2: '最小値の位置が自分自身なら交換ゼロ。', ref: 'a=list(map(int,input().split()))\nn=len(a)\ncnt=0\nfor i in range(n):\n    m=i\n    for j in range(i+1,n):\n        if a[j]<a[m]:\n            m=j\n    if m!=i:\n        a[i],a[m]=a[m],a[i]\n        cnt+=1\nprint(cnt)', tip: '選択ソートの交換は高々n−1回で、バブルソートの交換回数(=転倒数)と対照的に少ない。「書き込みが高価なメモリ」では今も選択ソートが選ばれる理由がこの回数にある。', ins: ['3 1 2\n', '1 2 3\n', '2 1\n', '3 2 1\n', '5 1 4 2 3\n', '4 4 4\n'] })

t({ lv: 515, concept: '整数: フィボナッチ数の桁数', title: '兎の数は何桁まで増えた', tags: ['整数'], io: '正整数 n が1行で与えられます。', ask: 'フィボナッチ数 F(n) (F(1)=F(2)=1) の十進の桁数を出力してください。', h1: '多倍長整数で作ってlen(str())。', h2: '2変数の持ち回りで十分速い。', ref: 'n=int(input())\na,b=1,1\nfor _ in range(n-1):\n    a,b=b,a+b\nprint(len(str(a)))', tip: '桁数は n·log10(φ)−log10(√5) にほぼ一致し、n=100で21桁。カラツバ法(同レベル既出)が効いてくるのはこうした多倍長の積からで、大きさの感覚を持つ入り口になる。', ins: ['10\n', '1\n', '100\n', '20\n', '7\n', '50\n'] })

t({ lv: 516, concept: 'ヒープ: 全列をカバーする最小の範囲', title: '全チームから1人ずつ入る幅', tags: ['ヒープ'], io: '1行目に列の数 k、続く k 行に各列の整数たちが与えられます。', ask: '各列から1つずつ値を選ぶとき、選んだ値の最大と最小の差の最小値を出力してください。', h1: 'k個のソート済み列のマージ(同レベル既出)の親戚。', h2: '全組合せを試すのが基準解。ヒープで最小を進める貪欲がO(N log k)。', ref: 'from itertools import product\nk=int(input())\nrows=[list(map(int,input().split())) for _ in range(k)]\nbest=None\nfor combo in product(*rows):\n    d=max(combo)-min(combo)\n    if best is None or d<best:\n        best=d\nprint(best)', tip: '有名な「smallest range covering k lists」。高速版は常に最小の要素を持つ列だけを進める貪欲で、その正しさは「最小を動かさない限り幅は縮まない」の一言に尽きる。', ins: ['2\n1 5 9\n4 10\n', '3\n1\n2\n3\n', '2\n1 2\n2 3\n', '3\n4 10\n1 9\n5 14\n', '2\n7\n7\n', '3\n1 5\n2 6\n3 7\n'] })

t({ lv: 517, concept: '数え上げ: 全区間の長さの合計', title: 'すべての区間の長さを足すと', tags: ['数え上げ'], io: '正整数 n が1行で与えられます。', ask: '長さ n の列の全ての連続部分配列(l≤r の組)について長さ r−l+1 を足した総和を出力してください。', h1: '長さLの区間は n−L+1 個ある。', h2: 'Σ L×(n−L+1)。閉じた式は n(n+1)(n+2)/6。', ref: 'n=int(input())\nprint(sum(L*(n-L+1) for L in range(1,n+1)))', tip: '答えは三角数の累積(四面体数)n(n+1)(n+2)/6 になる。全区間の和の合計(同レベル既出)で各要素の寄与が i×(n−i+1) 回だったのは、この長さ勘定の要素側から見た姿。', ins: ['1\n', '2\n', '3\n', '4\n', '10\n', '100\n'] })

t({ lv: 518, concept: 'ソート: 山型に並べ替える', title: '真ん中を頂上にする整列', tags: ['ソート'], io: '整数列が1行で空白区切りで与えられます。', ask: '昇順に並べたとき、小さい方から数えて奇数番目(1,3,5,…)の要素を左から順に置き、偶数番目(2,4,…)の要素を右端から順に置いた列を出力してください。', h1: 'ソートして交互に左右へ配る。', h2: '左に置く分と右に置く分をスライスで分ける。', ref: 'a=sorted(map(int,input().split()))\nleft=a[::2]\nright=a[1::2]\nprint(" ".join(map(str,left+right[::-1])))', tip: 'オルガンパイプ配列と呼ばれる形で、値が単峰(上って下る)になる。ジグザグ並べ替え(同レベル既出)と並ぶ「形を指定した整列」の代表例。', ins: ['1 2 3 4 5\n', '5 5\n', '3 1 2\n', '4\n', '9 1 8 2 7 3\n', '1 1 2 2\n'] })

t({ lv: 519, concept: '数え上げ: 和が正の区間の数', title: 'プラス収支の期間を数える', tags: ['数え上げ', '累積和'], io: '整数列が1行で空白区切りで与えられます。', ask: '要素の和が正になる連続部分配列の個数を出力してください。', h1: '区間和は累積和の差。', h2: '総当たりが基準解。累積和の「後の値が大きいペア」の数として転倒数系で高速化できる。', ref: 'a=list(map(int,input().split()))\nn=len(a)\ncnt=0\nfor i in range(n):\n    s=0\n    for j in range(i,n):\n        s+=a[j]\n        if s>0:\n            cnt+=1\nprint(cnt)', tip: '累積和の列で「i<jかつP[i]<P[j]」のペア数に等しく、これは転倒数の裏返し。BITで数えればO(n log n)になる、と数え上げの世界が地続きになる。', ins: ['1 -2 3\n', '1 1\n', '-1 -1\n', '2 -1 2\n', '0 1\n', '5\n'] })

t({ lv: 520, concept: '数え上げ: 差がkの倍数のペア数', title: '同じ余りの仲間分け', tags: ['数え上げ', 'ハッシュ'], io: '1行目に k、2行目に整数列が与えられます。', ask: 'i<j で a[i]−a[j] が k の倍数になるペアの個数を出力してください。', h1: '和がkの倍数のペア(同レベル既出)の差版。', h2: '差がkの倍数 ⇔ 余りが同じ。余りごとの個数から C(c,2)。', ref: 'from collections import Counter\nk=int(input())\nc=Counter(x%k for x in map(int,input().split()))\nprint(sum(v*(v-1)//2 for v in c.values()))', tip: '和の場合は余りrの相方がk−rだったが、差は「同じ余りどうし」と条件が締まる。合同式 a≡b (mod k) の同値類ごとの組合せ、という言い換えが一番見通しがよい。', ins: ['3\n1 4 7 2\n', '2\n1 3 5\n', '5\n1 2 3\n', '2\n2 4 6 8\n', '4\n1 5 9 2 6\n', '3\n3 3\n'] })

t({ lv: 521, concept: '数え上げ: 水たまりの個数', title: 'いくつの水たまりができるか', tags: ['数え上げ'], io: '高さの列が1行で空白区切りで与えられます。', ask: '雨が降ったとき、水が溜まる「連続したひとまとまり」の個数を出力してください。', h1: '溜まる水量(同レベル既出)の分布を見る。', h2: '各位置の水の深さ(min(左の最大, 右の最大)−高さ)が正の連続区間を数える。', ref: 'h=list(map(int,input().split()))\nn=len(h)\nlm=[0]*n\nrm=[0]*n\nm=0\nfor i in range(n):\n    m=max(m,h[i])\n    lm[i]=m\nm=0\nfor i in range(n-1,-1,-1):\n    m=max(m,h[i])\n    rm[i]=m\ncnt=0\nprev=False\nfor i in range(n):\n    wet=min(lm[i],rm[i])-h[i]>0\n    if wet and not prev:\n        cnt+=1\n    prev=wet\nprint(cnt)', tip: '総量(合計)と個数(連結成分)は同じ「深さ配列」から出る別の統計。深さを可視化してから数える2段構えは、導出物を部品化する設計の練習になる。', ins: ['2 0 2\n', '1 2 3\n', '3 0 1 0 3\n', '2 0 2 0 2\n', '5\n', '4 1 1 4 1 4\n'] })

t({ lv: 522, concept: '二点法: 最大の水量になる2本の位置', title: 'どの2本で水を囲うか', tags: ['二点法'], io: '縦線の高さの列が1行で空白区切りで与えられます(2本以上)。', ask: '2本の線で挟む水量(距離×低い方の高さ)が最大になる2本の位置(1始まり)を「左 右」で出力してください(最大が複数なら左が最小、それも同じなら右が最小のもの)。', h1: '最大値(同レベル既出)のargmax版。', h2: 'タイブレークを厳密にするなら総当たりが安全。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nbest=-1\nbl=br=0\nfor i in range(n):\n    for j in range(i+1,n):\n        v=(j-i)*min(a[i],a[j])\n        if v>best:\n            best=v\n            bl,br=i+1,j+1\nprint(bl,br)', tip: '値だけなら二点法O(n)で求まるが、「同点の中で位置が最小」の保証には走査順の議論が要る。タイブレーク仕様が入った瞬間に総当たりの安全性が光る、実務あるある。', ins: ['1 8 6 2 5 4 8 3 7\n', '1 1\n', '4 3 2 1 4\n', '1 2 1\n', '2 2 2\n', '3 9 3 4 7 2 12 6\n'] })

t({ lv: 523, concept: 'bit演算: 3回の中のただ1つ', title: '三つ子の中の一人っ子', tags: ['bit演算'], io: '整数列が1行で空白区切りで与えられます(1つの値だけが1回、他は全てちょうど3回現れます)。', ask: '1回だけ現れる値を出力してください。', h1: 'Counterでも解けるがビットで数えると面白い。', h2: '各ビット位置の立った回数を3で割った余りが答えのビット。', ref: 'a=list(map(int,input().split()))\nans=0\nfor b in range(32):\n    c=sum((x>>b)&1 for x in a)\n    if c%3:\n        ans|=1<<b\nprint(ans)', tip: '2回ずつならXOR一発、3回ずつなら「ビットごとの mod 3」と、消える仕組みを剰余に一般化する。k回ずつ+1つ、のどんなkでも通用する骨格になっている。', ins: ['2 2 3 2\n', '0 1 0 1 0 1 99\n', '7\n', '5 5 5 8\n', '1 1 1 2 2 2 3\n', '10 10 4 10\n'] })

t({ lv: 524, concept: 'ソート: 偶数を前に奇数を後ろに(安定)', title: '偶数が先、順序はそのまま', tags: ['ソート'], io: '整数列が1行で空白区切りで与えられます。', ask: '偶数を全て前に、奇数を全て後ろに移した列を出力してください(偶数どうし・奇数どうしの元の順序は保つ)。', h1: '2本のリストに振り分けて連結。', h2: 'フィルタ2回でも安定パーティションになる。', ref: 'a=list(map(int,input().split()))\nev=[x for x in a if x%2==0]\nod=[x for x in a if x%2==1]\nprint(" ".join(map(str,ev+od)))', tip: 'オランダ国旗(同レベル既出)のin-place交換は順序を壊すが、こちらは安定。安定性が要るときは追加メモリを払う、というトレードオフの典型が2問並びで見える。', ins: ['3 2 5 4 1\n', '2 4 6\n', '1 3 5\n', '1 2 3 4\n', '7\n', '4 1 2 3 6 5\n'] })

t({ lv: 525, concept: 'ソート: 1回の区間反転でソートできるか', title: 'ひっくり返すのは一度だけ', tags: ['ソート'], io: '整数列が1行で空白区切りで与えられます。', ask: 'ある連続区間を1回だけ反転して(何もしない選択も可)、全体を昇順にできるなら yes、できなければ no を出力してください。', h1: 'ソート済みの列と食い違う範囲を特定する。', h2: '最初と最後の不一致位置の間を反転して一致するか確かめる。', ref: 'a=list(map(int,input().split()))\nb=sorted(a)\nn=len(a)\nl=0\nwhile l<n and a[l]==b[l]:\n    l+=1\nif l==n:\n    print("yes")\nelse:\n    r=n-1\n    while a[r]==b[r]:\n        r-=1\n    a[l:r+1]=a[l:r+1][::-1]\n    print("yes" if a==b else "no")', tip: '不一致の両端は反転してもそこに残るので、候補区間は1つに絞られる——探索が要らない判定問題の典型。パンケーキソート(同レベル既出)の1手番の可否判定でもある。', ins: ['1 4 3 2 5\n', '1 2 3\n', '3 1 2\n', '2 1\n', '1 5 4 3 2 6\n', '5 4 1 2\n'] })

export const CATALOG = TASKS
