// 生成タスク 第78波：各レベル3問化フェーズ(5)。lv210, lv232〜279 の薄い49段に3問目を追加。
// bit/スタック/グラフ/DP/数論/文字列帯。クラスタ3問まで可・言い換え水増し禁止。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 210, concept: 'ジェネレータ: 素数を順にyieldする', title: '素数の蛇口をひねる', tags: ['ジェネレータ', '数論'], io: '正整数 n が1行で与えられます。', ask: '素数を無限に生成するジェネレータ関数を定義し、最初の n 個の素数を空白区切りで出力してください。', h1: 'while True と yield で無限に生成できる。', h2: '受け取る側は n 個取ったら break する。', ref: 'def primes():\n    x=1\n    while True:\n        x+=1\n        ok=x>1\n        i=2\n        while i*i<=x:\n            if x%i==0:\n                ok=False\n                break\n            i+=1\n        if ok:\n            yield x\nn=int(input())\nout=[]\nfor p in primes():\n    out.append(str(p))\n    if len(out)==n:\n        break\nprint(" ".join(out))', tip: '「無限の列を作る側」と「必要なだけ取る側」を分離できるのがジェネレータの真価。リストで先に全部作る書き方では無限列は原理的に表現できない。', ins: ['5\n', '1\n', '3\n', '10\n', '2\n', '8\n'] })

t({ lv: 232, concept: 'bit演算: 2要素のORの最大値', title: 'ORで作る最大の合成', tags: ['bit演算'], io: '整数列(2個以上)が1行で空白区切りで与えられます。', ask: '異なる位置の2要素のビットORの最大値を出力してください。', h1: '全ペアを試して十分。', h2: 'max(a[i]|a[j])。', ref: 'a=list(map(int,input().split()))\nbest=0\nn=len(a)\nfor i in range(n):\n    for j in range(i+1,n):\n        if a[i]|a[j]>best:\n            best=a[i]|a[j]\nprint(best)', tip: 'XOR最大(既出)はトライ木が要る難問だが、OR最大は「立つビットは消えない」ので上位2値の組が有力候補になり性質が全く違う。同じ形の問いでも演算で難度が跳ねる。', ins: ['1 2 4\n', '5 3\n', '8 8\n', '1 1 1\n', '6 10 3\n', '7 0\n'] })

t({ lv: 233, concept: 'bit演算: 立ちビットが奇数個の要素数', title: 'ビットの数が奇数のものたち', tags: ['bit演算'], io: '正整数の列が1行で空白区切りで与えられます。', ask: '2進表記で立っているビットの個数が奇数である要素の個数を出力してください。', h1: 'bin(x).count("1") の偶奇。', h2: 'sumとgenexpで1行。', ref: 'a=list(map(int,input().split()))\nprint(sum(1 for x in a if bin(x).count("1")%2==1))', tip: 'popcountが奇数の数はodious数、偶数はevil数と呼ばれ、交互ゲームの必勝判定やパリティ符号(誤り検出)の土台になる由緒ある分類。', ins: ['1 2 3\n', '7 8 4\n', '3 5 6\n', '1\n', '15 2\n', '11 13 14\n'] })

t({ lv: 234, concept: '数え上げ: 2進の桁数が同じペア数', title: '2進で同じ長さの数どうし', tags: ['数え上げ', 'bit演算'], io: '正整数の列が1行で空白区切りで与えられます。', ask: 'i<j で2進表記の桁数が等しいペアの個数を出力してください。', h1: '2進の桁数は bit_length。', h2: '桁数ごとの個数cから C(c,2) を足す。', ref: 'from collections import Counter\nc=Counter(x.bit_length() for x in map(int,input().split()))\nprint(sum(v*(v-1)//2 for v in c.values()))', tip: 'bit_lengthが等しいのは「同じ2のべき乗の区間 [2^k, 2^(k+1)) にいる」ことと同値。キーを変えてペアを数えるCounterの定石が、ここでは数の桁スケールで効いている。', ins: ['1 2 3 4\n', '5 6 7\n', '1 2 4 8\n', '3 2\n', '9 12 10 15\n', '1\n'] })

t({ lv: 235, concept: 'ハッシュ: 連続値のかたまりの個数', title: '飛び石はいくつの島か', tags: ['ハッシュ'], io: '相異なる整数の列が1行で空白区切りで与えられます。', ask: '値の集合を「連続する整数のかたまり」に分けると何個になるかを出力してください。', h1: '最長の連続並び(同レベル既出)と同じ着眼。', h2: 'x−1 が集合に無い x が、各かたまりの先頭。', ref: 's=set(map(int,input().split()))\nprint(sum(1 for x in s if x-1 not in s))', tip: '「かたまりの先頭だけ数える」と、かたまりを実際に構成せずに個数が出る。最長版では先頭から伸ばして長さを測ったのと同じ観察の、集計だけ版。', ins: ['1 2 4 5 6\n', '3\n', '1 3 5\n', '1 2 3 4\n', '10 11 20 21 22 30\n', '5 6\n'] })

t({ lv: 236, concept: 'スタック: 左で初めて小さくなるまでの距離の合計', title: '左を振り返って格下を探す', tags: ['スタック'], io: '整数列が1行で空白区切りで与えられます。', ask: '各要素について「左方向に見て初めて自分より小さい要素」までの距離を求め、その合計を出力してください(存在しない要素の寄与は0)。', h1: '右で初めて大きくなる版(同レベル既出)の鏡像。', h2: '自分以上の要素をポップしてから、残った先頭までの距離を足す。', ref: 'a=list(map(int,input().split()))\nst=[]\ntotal=0\nfor i,x in enumerate(a):\n    while st and a[st[-1]]>=x:\n        st.pop()\n    if st:\n        total+=i-st[-1]\n    st.append(i)\nprint(total)', tip: '単調スタックの4方位(左右×大小)は全て同じ骨格。ヒストグラム最大長方形は左右の「初めて小さい」を両方使う合成技で、この鏡像練習がその部品になる。', ins: ['3 1 4 2\n', '1 2 3\n', '5 4 3\n', '2 2 2\n', '1 5 2 4\n', '9\n'] })

t({ lv: 237, concept: 'スタック: 大文字小文字のペア消し', title: '反応して消える文字たち', tags: ['スタック', '文字列'], io: '英字の文字列が1行で与えられます。', ask: '「同じ文字の大文字と小文字が隣り合ったら両方消える」反応を起こせなくなるまで繰り返した後の長さを出力してください(例: aA や Bb は消える。aa や AB は消えない)。', h1: '同じ文字ペア消し(同レベル既出)の条件違い。', h2: 'スタックの頭と「同じ文字で大小が逆」ならポップ。', ref: 's=input()\nst=[]\nfor c in s:\n    if st and st[-1]!=c and st[-1].lower()==c.lower():\n        st.pop()\n    else:\n        st.append(c)\nprint(len(st))', tip: '消える条件を「swapcaseで一致」と読み替えるのが肝。ポリマー反応の名で知られる問題で、消去系はどれも合流性のおかげでスタック1パスに落ちる。', ins: ['aA\n', 'abBA\n', 'abAB\n', 'aabAAB\n', 'dabAcCaCBAcCcaDA\n', 'x\n'] })

t({ lv: 238, concept: 'BFS: 偶数距離にある頂点の数', title: '偶数歩で着ける頂点', tags: ['グラフ', 'BFS'], io: '1行目に頂点数 n と辺数 m、続く m 行に辺 u v が与えられます(連結)。', ask: '頂点1からの最短距離が偶数(0を含む)である頂点の個数を出力してください。', h1: 'BFSで距離を求めて偶奇で分類。', h2: 'dist%2==0 を数える。', ref: 'from collections import deque\nn,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\ndist=[-1]*(n+1)\ndist[1]=0\nq=deque([1])\nwhile q:\n    x=q.popleft()\n    for y in g[x]:\n        if dist[y]<0:\n            dist[y]=dist[x]+1\n            q.append(y)\nprint(sum(1 for v in range(1,n+1) if dist[v]%2==0))', tip: '2色塗り分け(同レベル既出)が可能なグラフでは、この偶奇分類がそのまま色になる。閉路に奇数長があると「最短距離の偶奇」と「彩色」がずれる、という対比も面白い。', ins: ['4 3\n1 2\n2 3\n2 4\n', '2 1\n1 2\n', '3 3\n1 2\n2 3\n1 3\n', '5 4\n1 2\n2 3\n3 4\n4 5\n', '1 0\n', '6 5\n1 2\n1 3\n2 4\n2 5\n3 6\n'] })

t({ lv: 239, concept: 'グラフ: 連結成分サイズの一覧', title: '島の大きさを小さい順に', tags: ['グラフ'], io: '1行目に頂点数 n と辺数 m、続く m 行に辺 u v が与えられます。', ask: '各連結成分の頂点数を昇順に空白区切りで出力してください。', h1: '最大の成分(同レベル既出)の全成分版。', h2: '未訪問の頂点から探索してサイズを集め、最後にソート。', ref: 'n,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\nseen=[False]*(n+1)\nsizes=[]\nfor s in range(1,n+1):\n    if seen[s]:\n        continue\n    seen[s]=True\n    st=[s]\n    c=0\n    while st:\n        x=st.pop()\n        c+=1\n        for y in g[x]:\n            if not seen[y]:\n                seen[y]=True\n                st.append(y)\n    sizes.append(c)\nprint(" ".join(map(str,sorted(sizes))))', tip: '成分数・最大サイズ・サイズ分布は同じ1回の走査から全部出る。集計を「一覧を返す」形で書いておくと、後からどんな統計でも取れる汎用部品になる。', ins: ['5 2\n1 2\n3 4\n', '3 0\n', '4 3\n1 2\n2 3\n3 4\n', '6 2\n1 2\n1 3\n', '2 1\n1 2\n', '7 3\n1 2\n3 4\n4 5\n'] })

t({ lv: 240, concept: 'グラフ: 4頂点の完全部分グラフの数', title: '全員が知り合いの4人組', tags: ['グラフ'], io: '1行目に頂点数 n と辺数 m、続く m 行に辺 u v が与えられます。', ask: 'どの2頂点間にも辺がある4頂点の組(K4)の個数を出力してください。', h1: '三角形の数(同レベル既出)の4頂点版。', h2: '4頂点の組合せを全部試し、6本の辺の存在を確かめる。', ref: 'from itertools import combinations\nn,m=map(int,input().split())\nE=set()\nfor _ in range(m):\n    u,v=map(int,input().split())\n    E.add((min(u,v),max(u,v)))\ncnt=0\nfor q in combinations(range(1,n+1),4):\n    if all((min(x,y),max(x,y)) in E for x,y in combinations(q,2)):\n        cnt+=1\nprint(cnt)', tip: 'K3(三角形)→K4と上がるたび総当たりの次数が1つ増える。クリーク数えは一般にNP困難で、小さいnの総当たりが「正しい基準実装」として意味を持つ領域。', ins: ['4 6\n1 2\n1 3\n1 4\n2 3\n2 4\n3 4\n', '4 5\n1 2\n1 3\n1 4\n2 3\n2 4\n', '5 10\n1 2\n1 3\n1 4\n1 5\n2 3\n2 4\n2 5\n3 4\n3 5\n4 5\n', '4 0\n', '5 7\n1 2\n1 3\n2 3\n1 4\n2 4\n3 4\n4 5\n', '6 6\n1 2\n2 3\n3 1\n4 5\n5 6\n6 4\n'] })

t({ lv: 241, concept: '整数: 桁の積を繰り返した最後の1桁', title: '掛け続けたら何になる', tags: ['整数'], io: '正整数 n が1行で与えられます。', ask: '各桁の積を求める操作を1桁になるまで繰り返し、最後に残る1桁の値を出力してください。', h1: '桁和の繰り返し(同レベル既出)の積版。', h2: '10未満になるまでwhile。', ref: 'n=int(input())\nwhile n>=10:\n    p=1\n    for c in str(n):\n        p*=int(c)\n    n=p\nprint(n)', tip: '桁和の繰り返しはmod 9の綺麗な公式に潰れるが、積の繰り返しには公式がない。0の桁が1つでも混ざると一気に0へ落ちる、非対称な力学が観察できる。', ins: ['39\n', '10\n', '7\n', '25\n', '99\n', '77\n'] })

t({ lv: 242, concept: '整数: 半分と+1で1にする手数', title: '半分にするか1を足すか', tags: ['整数', 'シミュレーション'], io: '正整数 n が1行で与えられます。', ask: '「偶数なら2で割る、奇数なら1を足す」を繰り返して 1 にするまでの操作回数を出力してください。', h1: '規則どおりにシミュレーションする。', h2: 'whileで1になるまで数える。', ref: 'n=int(input())\nc=0\nwhile n>1:\n    if n%2==0:\n        n//=2\n    else:\n        n+=1\n    c+=1\nprint(c)', tip: 'コラッツ(3n+1)と違い、この規則は必ず止まると証明できる(奇数→偶数→半分で確実に減る)。似た見た目の反復でも停止性の難しさが天と地ほど違う好例。', ins: ['3\n', '1\n', '8\n', '5\n', '7\n', '10\n'] })

t({ lv: 243, concept: 'リスト: 奇数の最大と最小の差', title: '奇数たちの幅', tags: ['リスト'], io: '整数列(奇数を1つ以上含む)が1行で空白区切りで与えられます。', ask: '奇数の要素だけを見たときの最大値と最小値の差を出力してください。', h1: '偶数版(同レベル既出)の奇数版。', h2: '奇数だけのリストを作ってmax−min。', ref: 'odds=[x for x in map(int,input().split()) if x%2==1]\nprint(max(odds)-min(odds))', tip: 'フィルタしてから集計する2段構えの練習。対象が1つもない場合にmaxが例外を投げる問題は、ここでは前提(奇数1つ以上)で回避しているが、実務では必ず考える点。', ins: ['1 2 3 4 5\n', '7\n', '2 9 4 3\n', '5 5\n', '1 8 11\n', '13 2 7 6\n'] })

t({ lv: 244, concept: '数え上げ: 桁和が同じペア数', title: '桁の合計が同じ数どうし', tags: ['数え上げ', 'ハッシュ'], io: '正整数の列が1行で空白区切りで与えられます。', ask: 'i<j で各桁の和が等しいペアの個数を出力してください。', h1: '桁和をキーにCounterへ。', h2: 'キーごとの個数cから C(c,2) を足す。', ref: 'from collections import Counter\nc=Counter(sum(int(d) for d in w) for w in input().split())\nprint(sum(v*(v-1)//2 for v in c.values()))', tip: 'キーが絶対値でも2進桁数でも桁和でも、「変換→Counter→C(c,2)」の骨格は同じ。この形を1つ覚えると同型の問題が全部1行で書けるようになる。', ins: ['12 21 3 40\n', '1 2 3\n', '11 2 20\n', '19 91\n', '5 14 23 6\n', '10 100\n'] })

t({ lv: 245, concept: '数論: n番目の星型数', title: '星のかたちに並べた点', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: 'n 番目の星型数(中心の1点の周りに六芒星の形に点を並べた総数、6n(n−1)+1)を出力してください。', h1: '公式に代入するだけ。', h2: '6n(n−1)+1。', ref: 'n=int(input())\nprint(6*n*(n-1)+1)', tip: '中心つき六角数(同レベル既出)が六角形の詰め込みなのに対し、星型数は六芒星。中国跳びチェッカーの盤面の穴の数(121)は星型数の4番目にあたる。', ins: ['1\n', '2\n', '3\n', '5\n', '4\n', '10\n'] })

t({ lv: 246, concept: 'リスト: 連続して減少する最長区間', title: '一番長い下り坂', tags: ['リスト'], io: '整数列が1行で空白区切りで与えられます。', ask: '隣がひとつ前より厳密に小さい状態が続く、最長の連続区間の長さを出力してください。', h1: '増加版(同レベル既出)の鏡像。', h2: '前より小さければ伸ばし、そうでなければ1にリセット。', ref: 'a=list(map(int,input().split()))\nbest=1\nrun=1\nfor i in range(1,len(a)):\n    if a[i]<a[i-1]:\n        run+=1\n        if run>best:\n            best=run\n    else:\n        run=1\nprint(best)', tip: '株価の連続下落日数、気温の連続低下など「単調な連なりの長さ」は時系列の基本統計。増加版と共通の骨格を持つことをdiffで確かめると理解が固まる。', ins: ['5 3 4 2 1\n', '1 2 3\n', '9 7 5 3\n', '4\n', '2 2 1\n', '8 6 7 5 4 6 2\n'] })

t({ lv: 247, concept: 'DP: 連続部分列の積の最小', title: '掛け算で一番沈む区間', tags: ['DP'], io: '整数列が1行で空白区切りで与えられます。', ask: '連続部分列(長さ1以上)の積の最小値を出力してください。', h1: '積の最大(同レベル既出)の鏡像だが、最大も一緒に持つ。', h2: '負数を掛けると最大と最小が入れ替わるので、両方を持ち回る。', ref: 'a=list(map(int,input().split()))\nhi=lo=ans=a[0]\nfor x in a[1:]:\n    c1,c2,c3=x,hi*x,lo*x\n    hi=max(c1,c2,c3)\n    lo=min(c1,c2,c3)\n    if lo<ans:\n        ans=lo\nprint(ans)', tip: '最小を求めるのに最大の追跡が不可欠、という依存の絡み合いがこの問題の核。負数×負数の符号反転が、maxとminを毎ステップ交換させる。', ins: ['2 -3 4\n', '1 2 3\n', '-2\n', '-1 -2 -3\n', '0 5 -2\n', '3 4\n'] })

t({ lv: 248, concept: 'DP: 三角形を下る最大の和', title: '実りの多い下り道', tags: ['DP'], io: '1行目に段数 n、続く n 行に三角形の数(i行目はi個)が与えられます。頂上から真下か右下へ降ります。', ask: '通った数の合計の最大値を出力してください。', h1: '最小の和(同レベル既出)のmax版。', h2: '下の段から dp[j]=v+max(下2つ) で畳む。', ref: 'n=int(input())\nrows=[list(map(int,input().split())) for _ in range(n)]\ndp=rows[-1][:]\nfor i in range(n-2,-1,-1):\n    dp=[rows[i][j]+max(dp[j],dp[j+1]) for j in range(i+1)]\nprint(dp[0])', tip: '下から畳むと境界処理が消えて1次元配列で済む。上から降ろすDPと下から上げるDPの書き味の差を、min版とmax版の両方で見比べたい。', ins: ['2\n1\n2 3\n', '3\n1\n2 3\n4 5 6\n', '1\n5\n', '3\n7\n3 8\n8 1 0\n', '4\n1\n1 1\n1 1 1\n1 1 1 1\n', '3\n2\n-1 -2\n5 1 1\n'] })

t({ lv: 249, concept: 'リスト: 素数番目の要素の和', title: '素数の席だけ集金', tags: ['リスト', '数論'], io: '整数列が1行で空白区切りで与えられます。', ask: '位置(1始まり)が素数である要素の合計を出力してください(該当がなければ 0)。', h1: '添字を素数判定にかける。', h2: 'enumerateを1始まりで回す。', ref: 'def isp(x):\n    if x<2:\n        return False\n    i=2\n    while i*i<=x:\n        if x%i==0:\n            return False\n        i+=1\n    return True\na=list(map(int,input().split()))\nprint(sum(x for i,x in enumerate(a,1) if isp(i)))', tip: '値ではなく「位置」に条件をかける切り口の練習。enumerate(a,1) の第2引数で1始まりにできることを知らないと、全体に+1の補正が散らばってしまう。', ins: ['1 2 3 4 5\n', '10 20\n', '1 1 1 1\n', '4\n', '5 6 7 8 9 10 11\n', '2 4 6 8 10 12\n'] })

t({ lv: 250, concept: 'DP: 部分集合で作れる和の種類数', title: '作れる金額は何通り', tags: ['DP'], io: '正整数の列が1行で空白区切りで与えられます。', ask: '空でない部分集合の和として作れる値が何種類あるかを出力してください。', h1: '目標和の判定(同レベル既出)の全数版。', h2: '作れる和の集合を持ち、要素ごとに「+x した集合」を合流させる。', ref: 'a=list(map(int,input().split()))\ns={0}\nfor x in a:\n    s|={y+x for y in s}\nprint(len(s)-1)', tip: '判定DPのbool配列は実は「作れる和の集合」の符号化だった、と種明かしする問題。集合のまま持つとコードが仕様の直訳になり、0(空集合)を除く後処理だけが残る。', ins: ['1 2\n', '1 1\n', '5\n', '1 2 4\n', '2 2 2\n', '3 5\n'] })

t({ lv: 251, concept: 'リスト: 桁数が奇数の要素の和', title: '奇数桁の数だけ合計', tags: ['リスト'], io: '正整数の列が1行で空白区切りで与えられます。', ask: '十進の桁数が奇数である要素の合計を出力してください(該当がなければ 0)。', h1: '桁数は len(str(x))。', h2: 'フィルタつきsumで1行。', ref: 'print(sum(x for x in map(int,input().split()) if len(str(x))%2==1))', tip: '桁数が偶数の個数(同レベル既出)の相方。数を文字列に変えて長さを測るのは邪道に見えて、桁数の定義そのものに最も忠実な実装でもある。', ins: ['5 12 345 6789\n', '10\n', '1 2 3\n', '100 200\n', '99 100\n', '12345 12 7\n'] })

t({ lv: 252, concept: '文字列: 片方にしか無い文字の一覧', title: 'どちらか一方だけの文字', tags: ['文字列', 'ハッシュ'], io: '1行目と2行目に英小文字の文字列が与えられます。', ask: '一方の文字列だけに現れる文字を、辞書順につなげて出力してください(1つも無ければ - を出力)。', h1: '集合の対称差。', h2: 'set(s)^set(t) をsortedしてjoin。', ref: 's=set(input())\nt=set(input())\nd=sorted(s^t)\nprint("".join(d) if d else "-")', tip: '共通の文字(積集合)を数える問題(同レベル既出)の裏側で、^(対称差)は「XORの集合版」。和・積・差・対称差の4演算はビット演算と完全に対応している。', ins: ['abc\nbcd\n', 'abc\nabc\n', 'xy\nab\n', 'aab\nb\n', 'hello\nworld\n', 'a\nz\n'] })

t({ lv: 253, concept: 'ヒープ: k回取り出した残りの合計', title: '安い順にk個抜いた残高', tags: ['ヒープ'], io: '1行目に k、2行目に整数列(k個より多い)が与えられます。', ask: '最小値を k 回取り除いた後に残る要素の合計を出力してください。', h1: 'heapifyしてheappopをk回。', h2: '残りの合計は「全体の合計−取り出した合計」でもよい。', ref: 'import heapq\nk=int(input())\na=list(map(int,input().split()))\nheapq.heapify(a)\nfor _ in range(k):\n    heapq.heappop(a)\nprint(sum(a))', tip: 'この問題だけならソートして先頭k個を捨てても同じだが、ヒープは「取り除きながら途中で要素が追加される」状況で差がつく。両方の解を書いて損はない。', ins: ['2\n5 1 3 2\n', '1\n4 4\n', '3\n1 2 3 9\n', '1\n10 20 30\n', '2\n7 3 9 1\n', '2\n6 6 6\n'] })

t({ lv: 254, concept: '区間: 統合してできる区間の数', title: '重なりをまとめたら何本になる', tags: ['区間', 'ソート'], io: '1行目に n、続く n 行に区間 l r (l≤r) が与えられます。', ask: '重なるか端が接する区間を全てまとめたとき、何本の区間になるかを出力してください。', h1: '左端でソートして左から舐める。', h2: '今の右端以下で始まる区間は同じまとまり。右端はmaxで更新。', ref: 'n=int(input())\niv=sorted(tuple(map(int,input().split())) for _ in range(n))\ncnt=0\nend=None\nfor l,r in iv:\n    if end is None or l>end:\n        cnt+=1\n        end=r\n    elif r>end:\n        end=r\nprint(cnt)', tip: '区間マージはカレンダーの予定統合やIPレンジの集約で日常的に使う操作。「ソートしてから一筆書き」は区間問題の背骨で、全区間を刺す点の問題(同レベル既出)と対をなす。', ins: ['3\n1 3\n2 4\n6 7\n', '2\n1 2\n3 4\n', '2\n1 2\n2 5\n', '1\n0 10\n', '4\n1 10\n2 3\n4 5\n11 12\n', '3\n5 6\n1 2\n3 4\n'] })

t({ lv: 255, concept: '貪欲: k文字消して作る最大の数', title: 'k桁捨てて一番大きく', tags: ['貪欲', 'スタック'], io: '1行目に数字だけの文字列、2行目に k (文字数未満) が与えられます。', ask: 'ちょうど k 文字消して残りを元の順でつなげた数のうち、最大のものを出力してください。', h1: '最小を作る問題(同レベル既出)の鏡像。', h2: '前の桁が今の桁より小さければ、消せる回数の許す限り前を消す。', ref: 's=input()\nk=int(input())\nst=[]\nfor c in s:\n    while k>0 and st and st[-1]<c:\n        st.pop()\n        k-=1\n    st.append(c)\nif k:\n    st=st[:-k]\nprint("".join(st))', tip: '最小版との違いは比較の向き1つ。消し残しのkを末尾から切り落とす後始末は、単調増加のまま終わったとき(たとえば4321から最大を作るとき)にだけ発火する見落としポイント。', ins: ['1924\n1\n', '13245\n2\n', '999\n2\n', '4321\n1\n', '56412\n2\n', '10\n1\n'] })

t({ lv: 256, concept: '文字列: 文字が閉じる位置での分割', title: 'もう出てこなくなったら区切る', tags: ['文字列', '貪欲'], io: '英小文字の文字列が1行で与えられます。', ask: '「その区画に現れた文字が後ろの区画に一切現れない」ように文字列をできるだけ多くの区画に分け、各区画の長さを空白区切りで出力してください。', h1: '各文字の最後の出現位置を先に調べる。', h2: '区画は「今まで見た文字の最終出現の最大」まで伸びる。そこで閉じる。', ref: 's=input()\nlast={c:i for i,c in enumerate(s)}\nout=[]\nstart=0\nend=0\nfor i,c in enumerate(s):\n    if last[c]>end:\n        end=last[c]\n    if i==end:\n        out.append(i-start+1)\n        start=i+1\nprint(" ".join(map(str,out)))', tip: '「最後の出現」の辞書内包と、伸びる右端に追いつくまで待つ走査の組合せ。会議の時間帯マージを文字の生存区間でやっている、と見ると区間問題との血縁が見える。', ins: ['ababcbacadefegdehijhklij\n', 'abc\n', 'aaa\n', 'abab\n', 'aabbc\n', 'caedbdedda\n'] })

t({ lv: 257, concept: '文字列: 回文になっている窓の数', title: '回文の窓を数える', tags: ['文字列'], io: '1行目に k、2行目に文字列(長さk以上)が与えられます。', ask: '長さ k の連続部分文字列のうち回文であるものの個数を出力してください。', h1: '窓を全部切り出して判定。', h2: 'スライスと[::-1]の比較。', ref: 'k=int(input())\ns=input()\nprint(sum(1 for i in range(len(s)-k+1) if s[i:i+k]==s[i:i+k][::-1]))', tip: '固定長の窓なら素朴なO(nk)で十分に速い。任意長の回文を数える問題(Manacher法やDPが要る)との計算量の断絶を知ると、仕様の「長さ固定」の有難みが分かる。', ins: ['3\nababa\n', '2\naabb\n', '1\nxyz\n', '3\nabcba\n', '4\naaaa\n', '2\nabab\n'] })

t({ lv: 258, concept: '数え上げ: 全ペアの積の総和', title: 'すべての2人組の掛け算を足すと', tags: ['数え上げ'], io: '整数列(2個以上)が1行で空白区切りで与えられます。', ask: 'i<j の全てのペアについて a[i]×a[j] を足した総和を出力してください。', h1: '和の2乗と2乗和の差(同レベル既出)が使える。', h2: '(S²−Q)/2。Sは総和、Qは2乗和。', ref: 'a=list(map(int,input().split()))\nS=sum(a)\nQ=sum(x*x for x in a)\nprint((S*S-Q)//2)', tip: '(Σx)² を展開すると対角(x²)と非対角(2xy)に分かれる、という恒等式の直用。O(n²)の総当たりがO(n)の代数に潰れる、数式変形の威力が最も分かりやすく出る問題。', ins: ['1 2 3\n', '2 2\n', '1 1 1 1\n', '5\n', '-1 2 3\n', '0 4 5\n'] })

t({ lv: 259, concept: '文字列: 先頭との一致長の合計', title: '出だしとどれだけ揃うか', tags: ['文字列'], io: '文字列が1行で与えられます。', ask: '2文字目以降の各開始位置について「そこから始めた場合に文字列の先頭と一致し続ける最長の長さ」を求め、その合計を出力してください。', h1: 'Z配列の最大(同レベル既出)の合計版。', h2: '各開始位置から先頭と1文字ずつ比べる素朴な二重ループで正しく書ける。', ref: 's=input()\nn=len(s)\ntotal=0\nfor i in range(1,n):\n    k=0\n    while i+k<n and s[k]==s[i+k]:\n        k+=1\n    total+=k\nprint(total)', tip: 'この各位置の値がZ配列そのもので、素朴版はO(n²)、Zアルゴリズムは既に調べた区間を再利用してO(n)にする。合計はパターン検索の「自己相関」の強さを表す量になる。', ins: ['aaa\n', 'abab\n', 'aaaa\n', 'abc\n', 'aabaa\n', 'z\n'] })

t({ lv: 260, concept: 'Union-Find: 全体が1つになる瞬間', title: 'みんながつながった瞬間', tags: ['Union-Find'], io: '1行目に頂点数 n と操作数 m、続く m 行に併合 u v が与えられます。', ask: '何回目の併合の直後に全頂点が1つの組になったかを出力してください(最後までならなければ never、はじめから1つ(n=1)なら 0)。', h1: '成分数を数えながら併合する。', h2: '実際に併合が起きたときだけ成分数が1減る。', ref: 'n,m=map(int,input().split())\np=list(range(n+1))\ndef find(x):\n    while p[x]!=x:\n        p[x]=p[p[x]]\n        x=p[x]\n    return x\ncnt=n\nans="never" if n>1 else "0"\nfor i in range(1,m+1):\n    u,v=map(int,input().split())\n    ru,rv=find(u),find(v)\n    if ru!=rv:\n        p[ru]=rv\n        cnt-=1\n        if cnt==1 and ans=="never":\n            ans=str(i)\nprint(ans)', tip: 'ネットワークの全体接続がいつ成立したかを問う、時刻つきUnion-Find。既に同じ組の併合では成分数が減らない、という区別がこの問題の採点ポイントになる。', ins: ['3 2\n1 2\n2 3\n', '4 3\n1 2\n3 4\n1 3\n', '2 1\n1 2\n', '3 1\n1 2\n', '4 4\n1 2\n2 1\n3 4\n2 3\n', '1 0\n'] })

t({ lv: 261, concept: '木: 最も頂点が多い深さ', title: '木の一番にぎやかな階', tags: ['木'], io: '1行目に頂点数 n (n≥2)、2行目に頂点2〜nの親が与えられます(根は頂点1)。', ask: '同じ深さにいる頂点数が最大となる深さを出力してください(根の深さは0、同数なら浅い方)。', h1: '各頂点の深さは親の深さ+1。', h2: '深さごとにCounterで数え、(−個数, 深さ)の最小。', ref: 'n=int(input())\npar=list(map(int,input().split()))\ndepth=[0]*(n+1)\nfor i in range(2,n+1):\n    depth[i]=depth[par[i-2]]+1\nfrom collections import Counter\nc=Counter(depth[1:n+1])\nprint(min(c.items(),key=lambda kv:(-kv[1],kv[0]))[0])', tip: '深さ別の頂点数の分布は木の「幅」で、高さ(同レベル既出)と対をなす形状指標。親リスト形式は親が必ず自分より小さい番号なので、1パスで深さが確定する。', ins: ['5\n1 1 2 2\n', '3\n1 2\n', '7\n1 1 1 2 2 2\n', '2\n1\n', '6\n1 2 3 4 5\n', '9\n1 1 2 2 3 3 4 4\n'] })

t({ lv: 262, concept: '整数: 同じ桁和を持つ次の数', title: '桁の合計はそのままで次へ', tags: ['整数'], io: '正整数 n が1行で与えられます。', ask: 'n より大きい整数のうち、各桁の和が n と等しい最小の数を出力してください。', h1: '桁和の関数を作って総当たり。', h2: 'n+1から順に桁和を比べる。', ref: 'n=int(input())\ndef ds(x):\n    return sum(int(c) for c in str(x))\nt=ds(n)\nx=n+1\nwhile ds(x)!=t:\n    x+=1\nprint(x)', tip: '答えは意外に近い(繰り上がりで桁和は激変するが、+9は桁和を保つことが多い)。9を足すと十の位+1・一の位−1になる性質に気づくと探索の意味が見えてくる。', ins: ['12\n', '1\n', '19\n', '100\n', '5\n', '21\n'] })

t({ lv: 263, concept: 'リスト: 隣接gcdの最大', title: '隣どうしで一番大きい公約数', tags: ['リスト', '数論'], io: '正整数の列(2個以上)が1行で空白区切りで与えられます。', ask: '隣り合う2要素の最大公約数のうち最大の値を出力してください。', h1: 'zipで隣接ペアへ。', h2: 'max(gcd(x,y) for ...)。', ref: 'from math import gcd\na=list(map(int,input().split()))\nprint(max(gcd(x,y) for x,y in zip(a,a[1:])))', tip: '隣接gcdの和(同レベル既出)が全体の傾向を測るのに対し、最大は「最も相性のよい隣人」を探す。集約関数を差し替えるだけで問いの性格が変わる。', ins: ['4 6 8\n', '3 9\n', '5 7\n', '10 15 20\n', '8 12 18\n', '6 6\n'] })

t({ lv: 264, concept: 'bit演算: 全ビットが1の要素の個数', title: 'ぎっしり詰まったビット', tags: ['bit演算'], io: '正整数の列が1行で空白区切りで与えられます。', ask: '2進表記が全て1である(1, 3, 7, 15, …のような)要素の個数を出力してください。', h1: '2のべき乗判定(同レベル既出)の親戚。', h2: 'x&(x+1)==0 が全ビット1の判定。', ref: 'a=list(map(int,input().split()))\nprint(sum(1 for x in a if x&(x+1)==0))', tip: '2のべき乗は x&(x−1)==0、全ビット1は x&(x+1)==0 と、±1の対で覚える。全ビット1の数は 2^k−1 のメルセンヌ形で、素数ならメルセンヌ素数になる。', ins: ['1 2 3 4\n', '7 8\n', '2 4 6\n', '15 15\n', '1\n', '31 5 3\n'] })

t({ lv: 265, concept: 'グリッド: 8方向移動の最短歩数', title: '斜めもありなら何歩か', tags: ['グリッド', 'BFS'], io: '1行目に H W、続く H 行に盤面(. が通れる、# が壁)が与えられます。左上と右下は通れます。', ask: '左上から右下まで、8方向(縦横斜め)に1マスずつ動くときの最短歩数を出力してください(到達できなければ -1)。', h1: '4方向BFSの近傍を8つに増やすだけ。', h2: '斜めの候補は(±1,±1)の4つ。', ref: 'from collections import deque\nh,w=map(int,input().split())\ng=[input() for _ in range(h)]\ndist=[[-1]*w for _ in range(h)]\ndist[0][0]=0\nq=deque([(0,0)])\nwhile q:\n    i,j=q.popleft()\n    for di in (-1,0,1):\n        for dj in (-1,0,1):\n            if di==0 and dj==0:\n                continue\n            ni,nj=i+di,j+dj\n            if 0<=ni<h and 0<=nj<w and g[ni][nj]=="." and dist[ni][nj]<0:\n                dist[ni][nj]=dist[i][j]+1\n                q.append((ni,nj))\nprint(dist[h-1][w-1])', tip: '障害物が無ければ答えはチェビシェフ距離 max(H−1,W−1) に一致する。壁があるとその公式が崩れてBFSが必要になる、幾何とグラフ探索の分水嶺。', ins: ['2 2\n..\n..\n', '1 3\n...\n', '3 3\n...\n.#.\n...\n', '2 3\n.#.\n...\n', '2 2\n.#\n#.\n', '3 4\n....\n####\n....\n'] })

t({ lv: 266, concept: '木: 子どもの数の最大', title: '一番の大所帯', tags: ['木'], io: '1行目に頂点数 n (n≥2)、2行目に頂点2〜nの親が与えられます(根は頂点1)。', ask: '直接の子の数が最も多い頂点の、その子の数を出力してください。', h1: '親リストは「子の数」の集計そのもの。', h2: '親の出現回数のmax。', ref: 'from collections import Counter\nn=int(input())\npar=list(map(int,input().split()))\nc=Counter(par)\nprint(max(c.values()))', tip: '最大の子数は木の「分岐度(branching factor)」で、B木やトライの設計パラメータ。親リスト形式なら木を組み立てずCounter一発で出るのが気持ちいい。', ins: ['5\n1 1 2 2\n', '3\n1 2\n', '2\n1\n', '7\n1 1 1 2 2 2\n', '4\n1 1 1\n', '6\n1 2 3 3 4\n'] })

t({ lv: 267, concept: '数論: 素因数分解の指数の最大', title: '一番働いている素因数', tags: ['数論'], io: '2以上の整数 n が1行で与えられます。', ask: 'n の素因数分解に現れる指数の最大値を出力してください。', h1: '指数つき分解(同レベル既出)の集計版。', h2: '割り切れる回数の最大を追う。', ref: 'n=int(input())\nbest=0\np=2\nwhile p*p<=n:\n    if n%p==0:\n        e=0\n        while n%p==0:\n            n//=p\n            e+=1\n        if e>best:\n            best=e\n    p+=1\nif n>1 and best<1:\n    best=1\nprint(best)', tip: '指数の最大が1なら平方因子を持たない(squarefree)。メビウス関数が生きる条件そのもので、「分解してから性質を集計する」型の代表例。', ins: ['12\n', '8\n', '30\n', '72\n', '7\n', '100\n'] })

t({ lv: 268, concept: '数論: 乗法の位数', title: '掛け続けて1に戻るまで', tags: ['数論'], io: 'a m (aとmは互いに素、m≥2) が空白区切りで1行で与えられます。', ask: 'a^k を m で割った余りが初めて 1 になる最小の正整数 k (乗法の位数)を出力してください。', h1: '余りを掛けながら1に戻るまで数える。', h2: 'x=a%m から始めて x=x*a%m を繰り返す。', ref: 'a,m=map(int,input().split())\nx=a%m\nk=1\nwhile x!=1:\n    x=x*a%m\n    k+=1\nprint(k)', tip: '位数はオイラーのφ(m)の約数になる(ラグランジュの定理)。RSAの安全性も原始根の存在もこの概念の上に建っていて、モジュラ逆元(同レベル既出)の隣人にあたる。', ins: ['2 7\n', '3 10\n', '1 5\n', '2 9\n', '5 6\n', '7 10\n'] })

t({ lv: 269, concept: '数論: リュカ数を法で割った余り', title: 'フィボナッチの陰の兄弟', tags: ['数論'], io: 'n m が空白区切りで1行で与えられます (n≥0, m≥2)。', ask: 'リュカ数 L(n) (L(0)=2, L(1)=1, 以後は直前2項の和)を m で割った余りを出力してください。', h1: 'フィボナッチを法で(同レベル既出)の初期値違い。', h2: '2変数の持ち回りで、毎回mod を取る。', ref: 'n,m=map(int,input().split())\na,b=2,1\nfor _ in range(n):\n    a,b=b,(a+b)%m\nprint(a%m)', tip: '同じ漸化式でも初期値(2,1)に変えるとリュカ数列になり、L(n)=F(n−1)+F(n+1) の関係で結ばれる。黄金比のべき乗 φ^n に最も近い整数もリュカ数。', ins: ['0 10\n', '5 100\n', '7 10\n', '10 1000\n', '1 5\n', '12 100\n'] })

t({ lv: 270, concept: 'リスト: 負・ゼロ・正の個数', title: '符号で三つの山に分ける', tags: ['リスト'], io: '整数列が1行で空白区切りで与えられます。', ask: '負の数、ゼロ、正の数の個数をこの順に空白区切りで出力してください。', h1: '3つのカウンタを回す。', h2: '比較で分岐して数えるだけ。', ref: 'a=list(map(int,input().split()))\nneg=sum(1 for x in a if x<0)\nzero=sum(1 for x in a if x==0)\nprint(neg,zero,len(a)-neg-zero)', tip: '3分類の集計は符号関数のヒストグラム。3つ目を「全体から引く」形にすると走査が1回減り、合計の検算(3値の和=n)も自然に組み込まれる。', ins: ['-1 0 2 3\n', '0 0\n', '1 2\n', '-5\n', '-1 -2 3 0 0\n', '7 -7\n'] })

t({ lv: 271, concept: '数論: 約数の総和の偶奇', title: '約数を全部足すと奇数か偶数か', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: 'n の約数の総和が奇数なら odd、偶数なら even を出力してください。', h1: '約数の総和(同レベル既出)を求めて2で割る。', h2: '実は平方数か平方数の2倍のときだけ奇数になる。', ref: 'n=int(input())\ns=0\ni=1\nwhile i*i<=n:\n    if n%i==0:\n        s+=i\n        if i!=n//i:\n            s+=n//i\n    i+=1\nprint("odd" if s%2==1 else "even")', tip: 'σ(n)が奇数 ⇔ nが平方数または平方数の2倍、という美しい特徴づけがある(奇素数の指数が全て偶数)。総和を計算せず判定する別解と突き合わせると理論の検算になる。', ins: ['9\n', '6\n', '1\n', '2\n', '10\n', '16\n'] })

t({ lv: 272, concept: '整数: 1からNまでに数字dが現れる回数', title: 'その数字は何回書かれるか', tags: ['整数'], io: 'N d が空白区切りで1行で与えられます (dは0〜9の1桁)。', ask: '1 から N までの整数を全部書き出したとき、数字 d が現れる総回数を出力してください。', h1: '各数を文字列にして数える。', h2: 'str(i).count(str(d)) の合計。', ref: 'n,d=input().split()\nn=int(n)\nprint(sum(str(i).count(d) for i in range(1,n+1)))', tip: '桁DPで O(log N) にできる古典題の、正しさ最優先の素朴版。ページ番号の印字に必要な活字「7」の本数、のような形で古くからパズルに登場する。', ins: ['13 1\n', '5 7\n', '100 0\n', '25 2\n', '9 9\n', '50 5\n'] })

t({ lv: 273, concept: 'リスト: mod kで現れない余りの数', title: '空席になっている余り', tags: ['リスト', 'ハッシュ'], io: '1行目に k、2行目に非負整数の列が与えられます。', ask: '0 から k−1 の余りのうち、どの要素の mod k としても現れないものの個数を出力してください。', h1: '現れた余りの種類数(同レベル既出)の補集合。', h2: 'k − len(集合)。', ref: 'k=int(input())\ns=set(x%k for x in map(int,input().split()))\nprint(k-len(s))', tip: '「現れる種類」と「現れない種類」は全体kを挟んだ表裏で、どちらを数える方が短いかは問い方次第。鳩の巣原理の問題では空席の有無が主役になる。', ins: ['3\n1 2 4\n', '2\n2 4 6\n', '4\n0 1 2 3\n', '5\n10\n', '3\n7 8\n', '2\n1 3 5\n'] })

t({ lv: 274, concept: '整数: 階乗の桁和', title: '階乗をぜんぶ足し崩す', tags: ['整数'], io: '正整数 n が1行で与えられます。', ask: 'n! の十進表記の各桁の和を出力してください。', h1: '多倍長で階乗を作って桁を足す。', h2: 'str経由でsum。', ref: 'import math\nn=int(input())\nprint(sum(int(c) for c in str(math.factorial(n))))', tip: 'プロジェクトオイラー第20問の骨格。100!の桁和は648で、末尾に並ぶ大量の0が桁和に一切寄与しないのが数字の風景として面白い。', ins: ['5\n', '1\n', '10\n', '7\n', '15\n', '100\n'] })

t({ lv: 275, concept: '組合せ: 中央二項係数', title: '真ん中のふくらみ', tags: ['組合せ'], io: '正整数 n が1行で与えられます。', ask: '中央二項係数 C(2n, n) を出力してください。', h1: 'math.combが使える。', h2: 'comb(2n, n)。', ref: 'from math import comb\nn=int(input())\nprint(comb(2*n,n))', tip: '2n歩のランダムウォークが原点に戻る場合の数であり、カタラン数は C(2n,n)/(n+1)。パスカルの三角形の各行で最大の値でもあり、およそ 4^n/√(πn) で育つ。', ins: ['1\n', '2\n', '3\n', '5\n', '4\n', '10\n'] })

t({ lv: 276, concept: 'リスト: 中央値より大きい要素の数', title: '真ん中を超えているのは何人', tags: ['リスト', 'ソート'], io: '奇数個の整数列が1行で空白区切りで与えられます。', ask: '中央値より厳密に大きい要素の個数を出力してください。', h1: 'ソートして中央値を特定。', h2: '同値がなければ答えは n//2 だが、同値があると減る。', ref: 'a=sorted(map(int,input().split()))\nm=a[len(a)//2]\nprint(sum(1 for x in a if x>m))', tip: '相異なる値ならちょうど半分(n//2)になるが、中央値と同じ値が複数あると減る。「定義上そうなるはず」が同値の存在で崩れる、統計の足元を見る1問。', ins: ['1 2 3\n', '5\n', '1 1 1\n', '3 1 4 1 5\n', '9 2 7\n', '2 2 3 3 5\n'] })

t({ lv: 277, concept: '二点法: 2つの昇順列の最初の共通値', title: '二列を並走して最初の一致', tags: ['二点法'], io: '1行目と2行目に昇順の整数列が与えられます。', ask: '両方の列に現れる値のうち最小のものを出力してください(無ければ none)。', h1: '両列の先頭に指を置く。', h2: '小さい方の指を進め、一致したらそれが答え。', ref: 'a=list(map(int,input().split()))\nb=list(map(int,input().split()))\ni=j=0\nans="none"\nwhile i<len(a) and j<len(b):\n    if a[i]==b[j]:\n        ans=str(a[i])\n        break\n    if a[i]<b[j]:\n        i+=1\n    else:\n        j+=1\nprint(ans)', tip: '集合の積を取れば1行だが、ソート済みという前提を使う二点法はメモリO(1)で、マージソートの併合と同じ足取り。前提が道具を変える好例。', ins: ['1 3 5\n2 3 4\n', '1 2\n3 4\n', '5 5\n5\n', '1 4 7\n2 4 6\n', '1 2 3\n3\n', '2 4 6 8\n1 3 8\n'] })

t({ lv: 278, concept: 'リスト: 谷型配列の底の位置', title: '谷底はどこにある', tags: ['リスト'], io: '先頭からしばらく厳密に減少し、その後厳密に増加する整数列(両部分とも1要素以上)が1行で与えられます。', ask: '最小値の位置(1始まり)を出力してください。', h1: '谷型かの判定(同レベル既出)の位置特定版。', h2: '減少が止まった場所が底。', ref: 'a=list(map(int,input().split()))\ni=0\nwhile i+1<len(a) and a[i+1]<a[i]:\n    i+=1\nprint(i+1)', tip: '厳密な谷型なら底は一意で、二分探索でO(log n)にもできる(山型配列の頂上と鏡像)。線形版を正とし二分版を試すのが安全な開発順。', ins: ['5 3 1 4 6\n', '3 1 2\n', '5 4 3 2 9\n', '9 1 2 3\n', '7 3 8\n', '10 5 2 6\n'] })

t({ lv: 279, concept: 'bit演算: 部分集合ANDの種類数', title: 'ANDで残せる値のバリエーション', tags: ['bit演算', 'DP'], io: '正整数の列が1行で空白区切りで与えられます。', ask: '空でない部分集合のビットANDとして作れる値が何種類あるかを出力してください。', h1: '作れる値の集合を要素ごとに育てる。', h2: '「今までの各値 & 新要素」と「新要素単独」を合流させる。', ref: 'a=list(map(int,input().split()))\ns=set()\nfor x in a:\n    s={y&x for y in s}|s|{x}\nprint(len(s))', tip: 'ANDは単調(ビットが減る一方)なので、各値から派生する系列は鎖になり集合が爆発しない。ORの種類数(既出)と対にすると、単調性の向きだけが違う双子だと分かる。', ins: ['1 2\n', '3 3\n', '1 2 4\n', '5\n', '7 5\n', '6 3 5\n'] })

export const CATALOG = TASKS
