// 生成タスク 第28波：lv241〜270。
// 前提分解の踏み段。累積和(差分/2次元)・DP変種・単調スタック・文字列アルゴ(KMP/Z/窓)・
// グラフ(0-1BFS/最短路数/木の重心)・数論(素因数分解/逆元/CRT/行列累乗)など。
// lv500未満なので再帰は使わず反復実装(prereqの穴を作らない)。重複なし・決定的・採点一意。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 241, concept: '数論: 数字根', title: '各桁の和を繰り返した値', tags: ['数論'], io: '整数 n (0以上) が1行で与えられます。', ask: '各桁の和を取る操作を、1桁になるまで繰り返した値を出力してください。', h1: 'str(n) の各文字を int に直して合計。', h2: '10以上の間ループ。', ref: 'n=int(input())\nwhile n>=10:\n    n=sum(int(c) for c in str(n))\nprint(n)', tip: '数字根は 9 で割った余り (0は9扱い) とも一致する。', ins: ['12345\n', '0\n', '9\n', '99\n', '10\n', '123456789\n'] })

t({ lv: 242, concept: '数論: コラッツの停止時間', title: '1に到達するまでの操作回数', tags: ['数論', 'シミュレーション'], io: '整数 n (1以上) が1行で与えられます。', ask: '偶数なら2で割り、奇数なら3倍して1を足す操作を、n が1になるまで繰り返したときの操作回数を出力してください。', h1: '1になるまで while ループ。', h2: '偶奇で分岐し、その都度カウント。', ref: 'n=int(input())\nc=0\nwhile n!=1:\n    if n%2==0:\n        n//=2\n    else:\n        n=3*n+1\n    c+=1\nprint(c)', tip: '全ての正整数で1に到達するかは未解決問題 (コラッツ予想)。', ins: ['6\n', '1\n', '7\n', '27\n', '2\n', '16\n'] })

t({ lv: 243, concept: '累積和: 差分配列(区間加算)', title: '区間加算をまとめて処理', tags: ['累積和'], io: '1行目に配列長 n とクエリ数 q、続く q 行に l r x (0始まり、閉区間 [l,r] に x を加える) が与えられます。', ask: 'すべてのクエリを適用した後の配列の最大値を出力してください。', h1: '差分配列に diff[l]+=x, diff[r+1]-=x。', h2: '最後に累積和を取れば各値が復元できる。', ref: 'n,q=map(int,input().split())\ndiff=[0]*(n+1)\nfor _ in range(q):\n    l,r,x=map(int,input().split())\n    diff[l]+=x\n    diff[r+1]-=x\narr=[0]*n\ncur=0\nfor i in range(n):\n    cur+=diff[i]\n    arr[i]=cur\nprint(max(arr))', tip: '区間加算を端点だけで記録する「いもす法」。q回の区間更新が O(n+q)。', ins: ['5 2\n0 2 1\n1 3 2\n', '3 1\n0 2 5\n', '1 1\n0 0 7\n', '4 0\n', '5 3\n0 4 1\n0 4 1\n0 4 1\n', '6 2\n0 1 10\n4 5 20\n'] })

t({ lv: 244, concept: '累積和: 2次元の矩形和', title: '矩形領域の和を高速に', tags: ['累積和'], io: '1行目に H W、続く H 行に W 個の整数、次の行にクエリ数 Q、続く Q 行に r1 c1 r2 c2 (0始まり、矩形 [r1..r2]×[c1..c2]) が与えられます。', ask: '各クエリの矩形和を求め、全クエリ分の合計を出力してください。', h1: '2次元累積和 S を作る。', h2: '矩形和は4つの累積和の足し引きで O(1)。', ref: 'h,w=map(int,input().split())\ng=[list(map(int,input().split())) for _ in range(h)]\nS=[[0]*(w+1) for _ in range(h+1)]\nfor i in range(h):\n    for j in range(w):\n        S[i+1][j+1]=S[i][j+1]+S[i+1][j]-S[i][j]+g[i][j]\nq=int(input())\nans=0\nfor _ in range(q):\n    r1,c1,r2,c2=map(int,input().split())\n    ans+=S[r2+1][c2+1]-S[r1][c2+1]-S[r2+1][c1]+S[r1][c1]\nprint(ans)', tip: '包除の形 (右下 − 上 − 左 + 左上) で矩形和が一発。', ins: ['2 2\n1 2\n3 4\n1\n0 0 1 1\n', '3 3\n1 1 1\n1 1 1\n1 1 1\n2\n0 0 0 0\n0 0 2 2\n', '1 1\n5\n1\n0 0 0 0\n', '2 3\n1 2 3\n4 5 6\n1\n0 1 1 2\n', '2 2\n1 1\n1 1\n3\n0 0 0 0\n1 1 1 1\n0 0 1 1\n', '3 3\n1 2 3\n4 5 6\n7 8 9\n1\n1 1 2 2\n'] })

t({ lv: 245, concept: 'DP: 隣接を選ばない最大和', title: '隣り合わずに選ぶ最大和', tags: ['dp'], io: '非負整数列が1行で与えられます。', ask: '隣り合う2要素を同時には選ばないという条件で、選んだ要素の和の最大値を出力してください。', h1: '「i番目を使う/使わない」の2状態を持つ。', h2: 'inc, exc を更新していく。', ref: 'a=list(map(int,input().split()))\ninc=0\nexc=0\nfor x in a:\n    inc,exc=exc+x,max(inc,exc)\nprint(max(inc,exc))', tip: '状態を2つの変数で持てば配列なしの O(1) 空間DPになる。', ins: ['1 2 3 1\n', '2 7 9 3 1\n', '5\n', '1 1 1 1\n', '0 0 0\n', '3 2 5 10 7\n'] })

t({ lv: 246, concept: 'DP: 最長連続増加部分列', title: '連続して増加する最長区間', tags: ['dp'], io: '整数列が1行で与えられます。', ask: '連続して狭義単調増加している最長の区間の長さを出力してください。', h1: '前より大きければ伸ばす。', h2: '途切れたら1に戻す。', ref: 'a=list(map(int,input().split()))\nbest=1\ncur=1\nfor i in range(1,len(a)):\n    if a[i]>a[i-1]:\n        cur+=1\n        if cur>best:\n            best=cur\n    else:\n        cur=1\nprint(best)', tip: '「連続」版は1パスで解ける。飛び飛び版 (最長増加部分列) とは別問題。', ins: ['1 3 5 4 7\n', '2 2 2\n', '1 2 3 4\n', '5\n', '5 4 3 2\n', '1 2 1 2 3 4\n'] })

t({ lv: 247, concept: '配列: 連続部分列の積の絶対値の最大', title: '符号を忘れて一番大きく掛ける', tags: ['配列'], io: '整数列 (負や0を含む) が1行で与えられます。', ask: '連続する1個以上の要素の積について、その絶対値の最大を出力してください。', h1: '符号を無視してよいなら、掛ける個数は多いほど得になる。', h2: '0 のところで列を区切り、区切られた各かたまりについて絶対値の総積を比べる。', ref: 'a=list(map(int,input().split()))\nbest=0\np=1\nhas=False\nfor x in a:\n    if x==0:\n        if has and p>best:\n            best=p\n        p=1\n        has=False\n    else:\n        p*=abs(x)\n        has=True\nif has and p>best:\n    best=p\nprint(best)', tip: '符号を捨てた途端に問題が単純になる。0 でない整数の絶対値は 1 以上なので、掛け足すほど値は下がらず、0 で切られたかたまりを丸ごと掛けるのが最善になる。積の最大(既出)で最大と最小を持ち回った苦労が消える対比が見どころ。', ins: ['2 3 -2 4\n', '-2 0 -1\n', '1 -3 0 2 -5\n', '0 0\n', '-1 -2 -3\n', '7\n'] })

t({ lv: 248, concept: 'DP: 三角形の最小下降経路', title: '三角形を下る最小の和', tags: ['dp', 'グリッド'], io: '1行目に行数 n、続く n 行に三角形 (i 行目に i 個の整数) が与えられます。各ステップで真下か右下のマスへ進みます。', ask: '頂点から最下段まで進むときの経路上の値の合計の最小値を出力してください。', h1: '下の段から上に向かってDP。', h2: 'dp[j]=tri[i][j]+min(dp[j],dp[j+1])。', ref: 'n=int(input())\ntri=[list(map(int,input().split())) for _ in range(n)]\ndp=tri[-1][:]\nfor i in range(n-2,-1,-1):\n    for j in range(len(tri[i])):\n        dp[j]=tri[i][j]+min(dp[j],dp[j+1])\nprint(dp[0])', tip: '下から上へ畳むと、その場で配列を上書きできてメモリが省ける。', ins: ['4\n2\n3 4\n6 5 7\n4 1 8 3\n', '1\n5\n', '2\n1\n2 3\n', '3\n1\n2 3\n4 5 6\n', '3\n5\n9 6\n4 6 8\n', '4\n3\n7 4\n2 4 6\n8 5 9 3\n'] })

t({ lv: 249, concept: 'DP: 個数無制限ナップサック', title: '何個でも使えるナップサック', tags: ['dp'], io: '1行目に品物数 n と容量 W、続く n 行に重さ w と価値 v が与えられます。各品物は何個でも使えます。', ask: '重さの合計が W を超えない範囲で、価値の合計の最大値を出力してください。', h1: 'dp[c]=容量cでの最大価値。', h2: '容量を小さい方から更新すると同じ品物を複数回使える。', ref: 'n,W=map(int,input().split())\nitems=[tuple(map(int,input().split())) for _ in range(n)]\ndp=[0]*(W+1)\nfor c in range(1,W+1):\n    for w,v in items:\n        if w<=c and dp[c-w]+v>dp[c]:\n            dp[c]=dp[c-w]+v\nprint(dp[W])', tip: '0/1版と違い容量を昇順に回すのが「無制限」のポイント。', ins: ['2 5\n2 3\n3 4\n', '1 10\n3 5\n', '0 5\n', '2 6\n1 1\n4 10\n', '3 8\n2 3\n3 4\n4 6\n', '1 7\n3 5\n'] })

t({ lv: 250, concept: 'DP: 部分和が作れるか', title: '部分集合で目標和を作れるか', tags: ['dp'], io: '1行目に n と目標 T、2行目に n 個の正整数が与えられます。', ask: 'いくつか選んで和をちょうど T にできるなら yes、できなければ no を出力してください。', h1: 'dp[v]=和vが作れるか。', h2: '各要素で大きい方の容量から更新。', ref: 'n,T=map(int,input().split())\na=list(map(int,input().split()))\ndp=[False]*(T+1)\ndp[0]=True\nfor x in a:\n    for v in range(T,x-1,-1):\n        if dp[v-x]:\n            dp[v]=True\nprint("yes" if dp[T] else "no")', tip: 'bool配列のDPは「作れる金額の集合」を効率よく持つ表現。', ins: ['4 9\n2 3 7 8\n', '3 11\n1 5 5\n', '2 10\n3 4\n', '1 5\n5\n', '3 6\n1 2 3\n', '4 0\n1 2 3 4\n'] })

t({ lv: 251, concept: 'DP: 単語辞書で分割可能か', title: '辞書の単語で文字列を分割できるか', tags: ['dp', '文字列'], io: '1行目に文字列 s、2行目に辞書の単語数 k、3行目に k 個の単語 (空白区切り) が与えられます。各単語は何回でも使えます。', ask: 's を辞書の単語の連結として表せるなら yes、できなければ no を出力してください。', h1: 'dp[i]=先頭 i 文字を分割できるか。', h2: 'dp[j] が真で s[j:i] が辞書にあれば dp[i] も真。', ref: 's=input()\nk=int(input())\nwords=set(input().split())\nn=len(s)\ndp=[False]*(n+1)\ndp[0]=True\nfor i in range(1,n+1):\n    for j in range(i):\n        if dp[j] and s[j:i] in words:\n            dp[i]=True\n            break\nprint("yes" if dp[n] else "no")', tip: '「ここまで分割できる」を前から積み上げる典型的な文字列DP。', ins: ['leetcode\n2\nleet code\n', 'applepenapple\n2\napple pen\n', 'catsandog\n5\ncats dog sand and cat\n', 'a\n1\na\n', 'aaaa\n1\naa\n', 'abcd\n2\na bc\n'] })

t({ lv: 252, concept: 'DP: 削除のみで一致', title: '削除だけで2文字列を一致させる最小回数', tags: ['dp', '文字列'], io: '2つの文字列が各行で与えられます。', ask: '両方から1文字ずつ削除する操作だけで2つを同じ文字列にするときの、削除回数の最小値を出力してください。', h1: '最長共通部分列 (LCS) を求める。', h2: '答えは len(a)+len(b)-2*LCS。', ref: 'a=input()\nb=input()\nm,n=len(a),len(b)\ndp=[[0]*(n+1) for _ in range(m+1)]\nfor i in range(1,m+1):\n    for j in range(1,n+1):\n        if a[i-1]==b[j-1]:\n            dp[i][j]=dp[i-1][j-1]+1\n        else:\n            dp[i][j]=max(dp[i-1][j],dp[i][j-1])\nprint(m+n-2*dp[m][n])', tip: '残すべきは共通部分列。それ以外を全部消す、と読み替えられる。', ins: ['sea\neat\n', 'leetcode\netco\n', 'abc\nabc\n', 'a\nb\n', 'abc\n\n', 'xyz\nxz\n'] })

t({ lv: 253, concept: 'スタック: 最小値つきスタック', title: '常に最小値が分かるスタック', tags: ['スタック'], io: '1行目に操作数 q、続く q 行に "push x" / "pop" / "min" のいずれかが与えられます。"min" は現在の最小値を読み取る操作です ("min" 時にスタックは空でないと保証)。', ask: 'すべての "min" 操作で得られた値の合計を出力してください。', h1: '各要素と「その時点の最小」を一緒に積む補助スタックを持つ。', h2: 'push 時に min(これまでの最小, x) を記録。', ref: 'q=int(input())\nst=[]\nmn=[]\ntotal=0\nfor _ in range(q):\n    op=input().split()\n    if op[0]=="push":\n        x=int(op[1])\n        st.append(x)\n        mn.append(x if not mn else min(mn[-1],x))\n    elif op[0]=="pop":\n        st.pop()\n        mn.pop()\n    else:\n        total+=mn[-1]\nprint(total)', tip: '補助スタックに最小値の履歴を持てば min が O(1) で取れる。', ins: ['5\npush 3\npush 1\nmin\npop\nmin\n', '3\npush 5\nmin\nmin\n', '4\npush 2\npush 4\npop\nmin\n', '6\npush 10\npush 5\nmin\npop\npush 7\nmin\n', '2\npush 1\nmin\n', '7\npush 3\npush 3\nmin\npop\nmin\npop\npush 9\n'] })

t({ lv: 254, concept: '貪欲: 区間を刺す最小の点数', title: '全区間を刺す最小の点の数', tags: ['貪欲', 'ソート'], io: '1行目に区間数 n、続く n 行に区間 s e (閉区間) が与えられます。', ask: 'すべての区間を少なくとも1点で「刺す」のに必要な点の最小数を出力してください (1点が複数区間を同時に刺してよい)。', h1: '終了が早い順に並べる。', h2: '刺せていない区間が来たらその終了点に打つ。', ref: 'n=int(input())\niv=[tuple(map(int,input().split())) for _ in range(n)]\niv.sort(key=lambda x:x[1])\npoints=0\nlast=-float("inf")\nfor s,e in iv:\n    if s>last:\n        points+=1\n        last=e\nprint(points)', tip: '「区間スケジューリング」の双対。点で刺す最小数＝両立しない区間の最大数。', ins: ['3\n1 3\n2 5\n4 6\n', '1\n0 10\n', '4\n1 2\n3 4\n5 6\n7 8\n', '3\n1 10\n2 3\n4 5\n', '2\n1 5\n2 6\n', '5\n1 2\n2 3\n3 4\n1 4\n2 2\n'] })

t({ lv: 255, concept: '貪欲: 削除でk文字消し辞書順最小', title: 'k文字消して作る最小の数', tags: ['貪欲', 'スタック'], io: '1行目に数字列 s と整数 k が空白区切りで与えられます。', ask: 's から k 文字を取り除いて作れる最小の数を出力してください (先頭の余分な0は取り除き、空になったら 0 を出力)。', h1: '左から積み、直前が今より大きければ消す。', h2: '消せる回数 k を使い切る。残ったら末尾から削る。', ref: 'line=input().split()\ns=line[0]\nk=int(line[1])\nst=[]\nfor ch in s:\n    while st and k>0 and st[-1]>ch:\n        st.pop()\n        k-=1\n    st.append(ch)\nst=st[:len(st)-k] if k>0 else st\nres="".join(st).lstrip("0")\nprint(res if res else "0")', tip: '単調増加を保つように消すのが辞書順最小の定石 (単調スタック貪欲)。', ins: ['1432219 3\n', '10200 1\n', '10 2\n', '112 1\n', '1234567 3\n', '9 1\n'] })

t({ lv: 256, concept: '文字列: 全文字を含む最小窓', title: '必要な文字を全て含む最短部分文字列', tags: ['スライディングウィンドウ', '文字列'], io: '2つの文字列 s と t が各行で与えられます。', ask: 's の連続部分文字列で、t の全文字を (重複も数えて) 含む最短のものの長さを出力してください。無ければ0を出力してください。', h1: '不足文字数 missing を管理する窓。', h2: 'missing が0の間、左を縮めて最短を更新。', ref: 'from collections import Counter\ns=input()\nt=input()\nneed=Counter(t)\nmissing=len(t)\nl=0\nbest=len(s)+1\nfor r,ch in enumerate(s):\n    if need[ch]>0:\n        missing-=1\n    need[ch]-=1\n    while missing==0:\n        if r-l+1<best:\n            best=r-l+1\n        need[s[l]]+=1\n        if need[s[l]]>0:\n            missing+=1\n        l+=1\nprint(best if best<=len(s) else 0)', tip: 'カウンタで「あと何文字足りないか」を1変数に圧縮するのが窓問題のコツ。', ins: ['ADOBECODEBANC\nABC\n', 'a\na\n', 'a\naa\n', 'aa\naa\n', 'abcabc\nabc\n', 'xyz\na\n'] })

t({ lv: 257, concept: '文字列: アナグラム窓の個数', title: 'アナグラムになる窓の数', tags: ['スライディングウィンドウ', '文字列'], io: '2つの文字列 s と p が各行で与えられます。', ask: 's の長さ |p| の連続部分文字列のうち、p のアナグラム (文字の並べ替えで一致) になっているものの個数を出力してください。', h1: '長さ|p|の窓の文字頻度を保つ。', h2: '窓の頻度が p の頻度と一致するかを毎回判定。', ref: 'from collections import Counter\ns=input()\np=input()\nk=len(p)\nif k>len(s):\n    print(0)\nelse:\n    need=Counter(p)\n    win=Counter(s[:k])\n    cnt=1 if win==need else 0\n    for i in range(k,len(s)):\n        win[s[i]]+=1\n        win[s[i-k]]-=1\n        if win[s[i-k]]==0:\n            del win[s[i-k]]\n        if win==need:\n            cnt+=1\n    print(cnt)', tip: '窓を1つずらすたびに頻度を1増1減で更新すれば全体 O(n)。', ins: ['cbaebabacd\nabc\n', 'abab\nab\n', 'a\nab\n', 'aaaa\naa\n', 'abcdef\nfed\n', 'aa\naa\n'] })

t({ lv: 258, concept: '文字列: パターンの出現回数(KMP)', title: 'パターンの出現回数を線形時間で', tags: ['文字列'], io: '2つの文字列 text と pat が各行で与えられます。', ask: 'text の中に pat が (重なりを許して) 出現する回数を出力してください。', h1: 'pat の「部分一致テーブル(失敗関数)」を作る。', h2: '不一致時に失敗関数で照合位置を戻し、後戻りせず走査。', ref: 'text=input()\npat=input()\nm=len(pat)\nlps=[0]*m\nk=0\nfor i in range(1,m):\n    while k>0 and pat[i]!=pat[k]:\n        k=lps[k-1]\n    if pat[i]==pat[k]:\n        k+=1\n    lps[i]=k\ncnt=0\nk=0\nfor ch in text:\n    while k>0 and ch!=pat[k]:\n        k=lps[k-1]\n    if ch==pat[k]:\n        k+=1\n    if k==m:\n        cnt+=1\n        k=lps[k-1]\nprint(cnt)', tip: '失敗関数 (LPS) のおかげで text を一度走るだけ＝O(n+m)。', ins: ['ababab\nab\n', 'aaaa\naa\n', 'abcabc\nxyz\n', 'aaa\na\n', 'mississippi\nissi\n', 'abcabcabc\nabcabc\n'] })

t({ lv: 259, concept: '文字列: Z配列の最大値', title: 'Z配列の最大値', tags: ['文字列'], io: '文字列 s が1行で与えられます。', ask: '各位置 i について「s[i:] と s の最長共通接頭辞の長さ」を Z[i] とし (Z[0] は0とする)、その最大値を出力してください。', h1: '既知の一致区間 [l,r] を使い回す。', h2: 'i<r なら min(r-i, Z[i-l]) から伸ばす。', ref: 's=input()\nn=len(s)\nz=[0]*n\nl=0\nr=0\nfor i in range(1,n):\n    if i<r:\n        z[i]=min(r-i,z[i-l])\n    while i+z[i]<n and s[z[i]]==s[i+z[i]]:\n        z[i]+=1\n    if i+z[i]>r:\n        l=i\n        r=i+z[i]\nprint(max(z) if n>0 else 0)', tip: 'Z配列は「自分自身とのずらし照合」を線形時間で全部求める道具。', ins: ['aabaab\n', 'aaaa\n', 'abc\n', 'a\n', 'ababab\n', 'aaabaaab\n'] })

t({ lv: 260, concept: 'Union-Find: 併合後の成分数', title: '併合を繰り返した後の連結成分数', tags: ['データ構造'], io: '1行目に n q、続く q 行に併合する2頂点 a b (1..n) が与えられます。', ask: 'すべての併合を処理した後の連結成分の個数を出力してください。', h1: '各頂点の代表元を持つ Union-Find。', h2: '異なる代表どうしを繋ぐたびに成分数を1減らす。', ref: 'n,q=map(int,input().split())\npar=list(range(n+1))\ndef find(x):\n    while par[x]!=x:\n        par[x]=par[par[x]]\n        x=par[x]\n    return x\ncomp=n\nfor _ in range(q):\n    a,b=map(int,input().split())\n    ra=find(a)\n    rb=find(b)\n    if ra!=rb:\n        par[ra]=rb\n        comp-=1\nprint(comp)', tip: '経路圧縮 (par[x]=par[par[x]]) を入れると find がほぼ定数時間。', ins: ['5 3\n1 2\n2 3\n4 5\n', '4 0\n', '3 3\n1 2\n2 3\n1 3\n', '6 2\n1 2\n3 4\n', '1 0\n', '5 4\n1 2\n2 3\n3 4\n4 5\n'] })

t({ lv: 261, concept: 'グラフ: 根付き木の高さ', title: '根からの木の高さ', tags: ['グラフ', 'BFS'], io: '1行目に頂点数 n、続く n-1 行に木の無向辺 u v (1..n) が与えられます。頂点1を根とします。', ask: '根から最も深い頂点までの辺数 (木の高さ) を出力してください。', h1: '根から幅優先で各頂点の深さを求める。', h2: '深さの最大値が高さ。', ref: 'from collections import deque\nn=int(input())\ng=[[] for _ in range(n+1)]\nfor _ in range(n-1):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\ndist=[-1]*(n+1)\ndist[1]=0\ndq=deque([1])\nh=0\nwhile dq:\n    x=dq.popleft()\n    for y in g[x]:\n        if dist[y]<0:\n            dist[y]=dist[x]+1\n            if dist[y]>h:\n                h=dist[y]\n            dq.append(y)\nprint(h)', tip: '木は閉路がないので、訪問済みフラグの代わりに親方向だけ避ければよい。', ins: ['4\n1 2\n2 3\n3 4\n', '4\n1 2\n1 3\n1 4\n', '2\n1 2\n', '1\n', '5\n1 2\n2 3\n2 4\n4 5\n', '6\n1 2\n1 3\n3 4\n3 5\n5 6\n'] })

t({ lv: 262, concept: 'グラフ: 最短経路の数', title: '最短経路の本数', tags: ['グラフ', 'BFS'], io: '1行目に n m、続く m 行に無向辺 u v、最後の行に s t が与えられます (頂点は1..n)。', ask: 's から t への最短経路の本数を出力してください (到達不能なら0)。', h1: '幅優先で距離と本数を同時に求める。', h2: '同じ最短距離で別経路から来たら本数を足す。', ref: 'from collections import deque\nn,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\ns,t=map(int,input().split())\ndist=[-1]*(n+1)\nways=[0]*(n+1)\ndist[s]=0\nways[s]=1\ndq=deque([s])\nwhile dq:\n    x=dq.popleft()\n    for y in g[x]:\n        if dist[y]<0:\n            dist[y]=dist[x]+1\n            ways[y]=ways[x]\n            dq.append(y)\n        elif dist[y]==dist[x]+1:\n            ways[y]+=ways[x]\nprint(ways[t])', tip: '最短路DAG上のDP。距離が確定した瞬間に本数も伝播する。', ins: ['4 4\n1 2\n1 3\n2 4\n3 4\n1 4\n', '2 1\n1 2\n1 2\n', '3 0\n1 3\n', '1 0\n1 1\n', '5 5\n1 2\n2 3\n1 3\n3 4\n4 5\n1 5\n', '4 5\n1 2\n1 3\n2 4\n3 4\n2 3\n1 4\n'] })

t({ lv: 263, concept: 'グラフ: DAGの経路数', title: 'DAG上の経路の本数', tags: ['トポロジカル', 'dp'], io: '1行目に n m、続く m 行に有向辺 u→v (閉路なし)、最後の行に s t が与えられます。', ask: 's から t への異なる経路の本数を出力してください。', h1: 'トポロジカル順序を求める。', h2: '逆順に dp[u]=Σ dp[子]、dp[t]=1。', ref: 'from collections import deque\nn,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nindeg=[0]*(n+1)\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    indeg[v]+=1\ns,t=map(int,input().split())\ndq=deque(i for i in range(1,n+1) if indeg[i]==0)\ntopo=[]\nwhile dq:\n    x=dq.popleft()\n    topo.append(x)\n    for y in g[x]:\n        indeg[y]-=1\n        if indeg[y]==0:\n            dq.append(y)\ndp=[0]*(n+1)\ndp[t]=1\nfor u in reversed(topo):\n    if u==t:\n        continue\n    r=0\n    for w in g[u]:\n        r+=dp[w]\n    dp[u]=r\nprint(dp[s])', tip: '閉路がないので順序を1列に並べれば再帰なしでDPできる。', ins: ['4 4\n1 2\n1 3\n2 4\n3 4\n1 4\n', '3 2\n1 2\n2 3\n1 3\n', '1 0\n1 1\n', '5 6\n1 2\n1 3\n2 4\n3 4\n4 5\n2 5\n1 5\n', '2 1\n1 2\n1 2\n', '4 3\n1 2\n2 3\n3 4\n1 4\n'] })

t({ lv: 264, concept: 'グラフ: トポロジカル順序の一意性', title: 'トポロジカル順序が一意か', tags: ['トポロジカル', 'グラフ'], io: '1行目に n m、続く m 行に有向辺 u→v (閉路なし) が与えられます。', ask: 'トポロジカル順序がただ1通りに定まるなら yes、複数あり得るなら no を出力してください。', h1: '入次数0の頂点を取り出していく (Kahn法)。', h2: '取り出せる候補が同時に2個以上ある瞬間があれば一意でない。', ref: 'from collections import deque\nn,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nindeg=[0]*(n+1)\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    indeg[v]+=1\ndq=deque(i for i in range(1,n+1) if indeg[i]==0)\nunique=True\nwhile dq:\n    if len(dq)>1:\n        unique=False\n    x=dq.popleft()\n    for y in g[x]:\n        indeg[y]-=1\n        if indeg[y]==0:\n            dq.append(y)\nprint("yes" if unique else "no")', tip: '一意 ⇔ 各段階で次に置ける頂点がちょうど1つ (ハミルトン的な一本道)。', ins: ['3 2\n1 2\n2 3\n', '3 1\n1 2\n', '4 3\n1 2\n2 3\n3 4\n', '3 3\n1 2\n1 3\n2 3\n', '4 2\n1 2\n3 4\n', '2 1\n1 2\n'] })

t({ lv: 265, concept: 'グラフ: 0-1重み最短路', title: '重みが0か1の最短距離', tags: ['グラフ', 'BFS'], io: '1行目に n m、続く m 行に u v w (w は 0 か 1、無向)、最後の行に s t が与えられます。', ask: 's から t への重みの合計の最小値を出力してください (到達不能なら -1)。', h1: '両端キュー (deque) を使う。', h2: '重み0の辺は前に、重み1の辺は後ろに入れる。', ref: 'from collections import deque\nn,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v,w=map(int,input().split())\n    g[u].append((v,w))\n    g[v].append((u,w))\ns,t=map(int,input().split())\nINF=float("inf")\ndist=[INF]*(n+1)\ndist[s]=0\ndq=deque([s])\nwhile dq:\n    x=dq.popleft()\n    for y,w in g[x]:\n        if dist[x]+w<dist[y]:\n            dist[y]=dist[x]+w\n            if w==0:\n                dq.appendleft(y)\n            else:\n                dq.append(y)\nprint(dist[t] if dist[t]<INF else -1)', tip: '0-1 BFS は重み0/1限定のダイクストラの軽量版 (両端キューで O(V+E))。', ins: ['4 4\n1 2 0\n2 3 1\n1 3 1\n3 4 0\n1 4\n', '3 0\n1 3\n', '2 1\n1 2 1\n1 2\n', '1 0\n1 1\n', '5 5\n1 2 1\n2 3 0\n3 4 0\n4 5 1\n1 5 1\n1 5\n', '4 3\n1 2 0\n2 3 0\n3 4 0\n1 4\n'] })

t({ lv: 266, concept: 'グラフ: 木の重心', title: '木の重心での最大部分木サイズ', tags: ['グラフ', '木'], io: '1行目に頂点数 n、続く n-1 行に木の無向辺 u v (1..n) が与えられます。', ask: 'ある頂点を取り除いたときにできる断片のうち最大のものの頂点数を、その頂点を変えて最小化した値を出力してください (重心での値)。', h1: '根を1として各頂点の部分木サイズを求める。', h2: '頂点 x を除くと、各子の部分木と (n - size[x]) に分かれる。', ref: 'n=int(input())\ng=[[] for _ in range(n+1)]\nfor _ in range(n-1):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\nsize=[1]*(n+1)\nparent=[0]*(n+1)\norder=[]\nvisited=[False]*(n+1)\nvisited[1]=True\nstack=[1]\nwhile stack:\n    x=stack.pop()\n    order.append(x)\n    for y in g[x]:\n        if not visited[y]:\n            visited[y]=True\n            parent[y]=x\n            stack.append(y)\nfor x in reversed(order):\n    for y in g[x]:\n        if y!=parent[x]:\n            size[x]+=size[y]\nbest=n\nfor x in range(1,n+1):\n    mx=n-size[x]\n    for y in g[x]:\n        if y!=parent[x] and size[y]>mx:\n            mx=size[y]\n    if mx<best:\n        best=mx\nprint(best)', tip: '部分木サイズは「行きがけ順を逆にたどる」と再帰なしで集計できる。', ins: ['4\n1 2\n2 3\n3 4\n', '1\n', '3\n1 2\n1 3\n', '5\n1 2\n1 3\n1 4\n1 5\n', '6\n1 2\n2 3\n2 4\n4 5\n4 6\n', '2\n1 2\n'] })

t({ lv: 267, concept: '数論: 素因数分解', title: '素因数分解を指数つきで出力', tags: ['数論'], io: '整数 n (>=2) が1行で与えられます。', ask: 'n を素因数分解し、"p^e" の形を小さい素数順に空白区切りで出力してください (指数が1でも ^1 を付ける。例: 12 → 2^2 3^1)。', h1: '2から順に割れるだけ割る。', h2: '割り切る回数が指数。最後に残った >1 の数も素因数。', ref: 'n=int(input())\nres=[]\nd=2\nwhile d*d<=n:\n    if n%d==0:\n        e=0\n        while n%d==0:\n            n//=d\n            e+=1\n        res.append(f"{d}^{e}")\n    d+=1\nif n>1:\n    res.append(f"{n}^1")\nprint(" ".join(res))', tip: 'd*d<=n まで試せば十分。残りは高々1個の大きな素因数。', ins: ['12\n', '2\n', '100\n', '17\n', '360\n', '64\n'] })

t({ lv: 268, concept: '数論: モジュラ逆元', title: 'モジュラ逆元 (拡張ユークリッド)', tags: ['数論'], io: 'a m が空白区切りで与えられます (gcd(a,m)=1 を保証)。', ask: 'a の m を法とする逆元 (a*x ≡ 1 (mod m) を満たす 0<=x<m) を出力してください。', h1: '拡張ユークリッドの互除法で係数を追う。', h2: 'a の係数を最後に m で正に直す。', ref: 'a,m=map(int,input().split())\na%=m\nold_r,r=a,m\nold_s,s=1,0\nwhile r!=0:\n    q=old_r//r\n    old_r,r=r,old_r-q*r\n    old_s,s=s,old_s-q*s\nprint(old_s%m)', tip: '逆元は割り算をmod世界で行うための要。組合せ mod 素数などで必須。', ins: ['3 11\n', '1 5\n', '2 7\n', '10 17\n', '7 13\n', '5 1\n'] })

t({ lv: 269, concept: '数論: フィボナッチ数(mod)', title: 'n番目のフィボナッチ数を法で', tags: ['数論'], io: 'n m が空白区切りで与えられます。', ask: 'n 番目のフィボナッチ数 (F(0)=0, F(1)=1) を m で割った余りを出力してください。', h1: '行列 [[1,1],[1,0]] の n 乗を使う。', h2: '繰り返し二乗法で行列累乗すれば O(log n)。', ref: 'n,m=map(int,input().split())\ndef mul(A,B):\n    return [[(A[0][0]*B[0][0]+A[0][1]*B[1][0])%m,(A[0][0]*B[0][1]+A[0][1]*B[1][1])%m],[(A[1][0]*B[0][0]+A[1][1]*B[1][0])%m,(A[1][0]*B[0][1]+A[1][1]*B[1][1])%m]]\nresult=[[1,0],[0,1]]\nbase=[[1,1],[1,0]]\ne=n\nwhile e>0:\n    if e%2==1:\n        result=mul(result,base)\n    base=mul(base,base)\n    e//=2\nprint(result[0][1]%m)', tip: '線形漸化式は行列累乗で対数時間に落ちる (巨大な n でも一瞬)。', ins: ['10 1000\n', '0 7\n', '1 7\n', '100 1000000007\n', '7 100\n', '50 1000\n'] })

t({ lv: 270, concept: '数論: 中国剰余定理', title: '2つの合同式を満たす最小の数', tags: ['数論'], io: 'r1 m1 r2 m2 が空白区切りで与えられます (m1 と m2 は互いに素)。', ask: 'x ≡ r1 (mod m1) かつ x ≡ r2 (mod m2) を満たす最小の非負整数 x を出力してください。', h1: 'm1 の m2 を法とする逆元を拡張ユークリッドで求める。', h2: 'x = r1 + m1 * ((r2-r1) * inv mod m2)。', ref: 'r1,m1,r2,m2=map(int,input().split())\nold_r,r=m1%m2,m2\nold_s,s=1,0\nwhile r!=0:\n    q=old_r//r\n    old_r,r=r,old_r-q*r\n    old_s,s=s,old_s-q*s\ninv=old_s%m2\nM=m1*m2\nx=(r1+m1*((r2-r1)*inv%m2))%M\nprint(x%M)', tip: '互いに素な法での連立合同式は、法の積を周期に持つ唯一解になる。', ins: ['2 3 3 5\n', '0 2 0 3\n', '1 2 2 3\n', '2 5 3 7\n', '1 4 0 9\n', '3 4 4 5\n'] })

export const CATALOG = TASKS
