// 生成タスク 第89波：各レベル3問化フェーズ(16)。lv775〜799, 801〜824 の薄い49段に3問目を追加。
// 文字列/データ構造クエリ帯。クラスタ3問まで可・言い換え水増し禁止。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 775, concept: 'シミュレーション: ライフゲームの1ステップ', title: '生と死の一世代', tags: ['シミュレーション', 'グリッド'], io: '1行目に H W、続く H 行に 0/1 の文字列(1が生)が与えられます。盤外は死とみなします。', ask: 'ライフゲームの規則(生きたセルは隣接する生が2か3なら生存、死んだセルは隣接する生がちょうど3なら誕生)で1世代進めた盤面を1行ずつ出力してください。', h1: '8近傍の生の数を数える。', h2: '全セルの次状態を別の盤面に書く(その場更新は不可)。', ref: 'h,w=map(int,input().split())\ng=[input() for _ in range(h)]\nres=[]\nfor i in range(h):\n    row=[]\n    for j in range(w):\n        c=sum(1 for di in (-1,0,1) for dj in (-1,0,1) if (di,dj)!=(0,0) and 0<=i+di<h and 0<=j+dj<w and g[i+di][j+dj]=="1")\n        if g[i][j]=="1":\n            row.append("1" if c in (2,3) else "0")\n        else:\n            row.append("1" if c==3 else "0")\n    res.append("".join(row))\nprint("\\n".join(res))', tip: 'ルール90(同レベル既出)の1次元セルオートマトンに対する、2次元の金字塔。「読みながら書き換えてはいけない」二重バッファの原則が最大の学び。', ins: ['3 3\n000\n111\n000\n', '2 2\n11\n11\n', '1 3\n111\n', '3 3\n010\n010\n010\n', '2 2\n10\n00\n', '3 3\n110\n110\n000\n'] })

t({ lv: 776, concept: 'ハッシュ: 奇数回現れる値の種類数', title: '奇数回組の顔ぶれ', tags: ['ハッシュ'], io: '整数列が1行で空白区切りで与えられます。', ask: '奇数回現れる値が何種類あるかを出力してください。', h1: 'ちょうど2回(同レベル既出)の述語違い。', h2: 'Counterの値の偶奇。', ref: 'from collections import Counter\nc=Counter(input().split())\nprint(sum(1 for v in c.values() if v%2==1))', tip: '全要素のXORが0でないこととの関係(奇数回の値が1種類ならXORで特定できる)や、回文並べ替えの可否(奇数回が1以下)と、偶奇の集計は多くの既出問題の土台になっている。', ins: ['1 1 2\n', '1 2 3\n', '5 5\n', '1 1 1\n', '2 2 3 3 3 4\n', '7\n'] })

t({ lv: 777, concept: '二点法: 重複なし最長区間の実体', title: '最長のユニーク区間、その中身', tags: ['二点法', '文字列'], io: '英小文字の文字列が1行で与えられます。', ask: '同じ文字を2度含まない最長の連続部分文字列を出力してください(最長が複数なら最も左のもの)。', h1: '長さを求める窓(既出)のargmax版。', h2: '「より長いときだけ」更新すれば最左が残る。', ref: 's=input()\nlast={}\nl=0\nbest=0\nstart=0\nfor r,c in enumerate(s):\n    if c in last and last[c]>=l:\n        l=last[c]+1\n    last[c]=r\n    if r-l+1>best:\n        best=r-l+1\n        start=l\nprint(s[start:start+best])', tip: '長さ・開始位置(いずれも既出)ときて実体の出力で三部作が完結する。値→位置→実体の順に仕様が重くなるが、走査は一度も変わらないのが二点法の懐の深さ。', ins: ['abcabcbb\n', 'bbbbb\n', 'pwwkew\n', 'a\n', 'abba\n', 'dvdf\n'] })

t({ lv: 778, concept: 'ハッシュ: すべて偶数回現れるか', title: 'ペアが組める在庫か', tags: ['ハッシュ'], io: '整数列が1行で空白区切りで与えられます。', ask: '全ての値がそれぞれ偶数回現れているなら yes、奇数回の値があれば no を出力してください。', h1: '2個ずつの束に完全に分けられる条件。', h2: 'Counterの値が全部偶数か。', ref: 'from collections import Counter\nc=Counter(input().split())\nprint("yes" if all(v%2==0 for v in c.values()) else "no")', tip: '靴下のペア組みやドミノの在庫確認の抽象形。全要素のXOR…では値の重複が混ざると判定できず、Counterが必要という「XORでは足りない」境界例にもなっている。', ins: ['1 1 2 2\n', '1 2\n', '3 3 3 3\n', '5\n', '1 2 1 2\n', '4 4 5\n'] })

t({ lv: 779, concept: 'ソート: ペアの差の最大を最小に', title: '一番差の大きい組を小さく', tags: ['ソート', '貪欲'], io: '偶数個の整数列が1行で空白区切りで与えられます。', ask: '全員を2人組に分けるとき、「ペア内の差の最大値」の最小を出力してください。', h1: 'ソートして隣どうしを組ませるのが最適。', h2: '交差するペアをほどくと最大差は悪化しない(交換論法)。', ref: 'a=sorted(map(int,input().split()))\nprint(max(a[i+1]-a[i] for i in range(0,len(a),2)))', tip: '差の合計の最小(既出)と同じ「ソート隣接ペア」が、最大値の最小化でも最適になる。目的関数が変わっても同じ構造が勝つ、貪欲のロバストさの見本。', ins: ['1 4 2 3\n', '5 5\n', '1 10 2 9\n', '1 2 3 8\n', '7 1\n', '3 1 4 1\n'] })

t({ lv: 780, concept: 'bit演算: 区間XORの種類数', title: 'XORが描く区間の色数', tags: ['bit演算'], io: '非負整数の列が1行で空白区切りで与えられます。', ask: '全ての連続部分配列のXORとして現れる値の種類数を出力してください。', h1: '区間XORは累積XORの2点の差。', h2: '累積XORの全ペアのXORを集合に。', ref: 'a=list(map(int,input().split()))\nps=[0]\nfor x in a:\n    ps.append(ps[-1]^x)\nn=len(ps)\ns=set()\nfor i in range(n):\n    for j in range(i+1,n):\n        s.add(ps[i]^ps[j])\nprint(len(s))', tip: '累積XORの列に情報が完全に圧縮される、区間XOR問題の共通の入り口。種類数・最大値(既出)・k個数(既出)が全部この前処理を共有する。', ins: ['1 2 3\n', '5\n', '1 1\n', '2 4\n', '0 0\n', '7 7 7\n'] })

t({ lv: 781, concept: '文字列: 大小文字を無視した回文判定', title: '声の大きさは気にしない回文', tags: ['文字列'], io: '英字の文字列が1行で与えられます。', ask: '大文字小文字の違いを無視して回文なら yes、そうでなければ no を出力してください。', h1: '正規化してから判定。', h2: 'lower()して[::-1]比較。', ref: 's=input().lower()\nprint("yes" if s==s[::-1] else "no")', tip: '英数字だけ見る回文(同レベル既出)と並ぶ「正規化+判定」の合成形。何を無視するか(大小・記号・空白)の宣言が仕様の本体で、判定自体は1行のまま変わらない。', ins: ['AbBa\n', 'Abc\n', 'A\n', 'NoOn\n', 'ab\n', 'RaCecAr\n'] })

t({ lv: 782, concept: 'ハッシュ: 追加で回文化する最小文字数', title: '足りないピースを数える', tags: ['ハッシュ', '文字列'], io: '英小文字の文字列が1行で与えられます。', ask: '好きな文字を好きな位置に追加して(並べ替えも自由)、全体を回文にできるようにするための最小の追加文字数を出力してください。', h1: '並べ替え自由なら奇数回の文字だけが問題。', h2: '奇数回の文字が k 種なら k−1 文字の追加で足りる(k=0なら0)。', ref: 'from collections import Counter\nc=Counter(input())\nodd=sum(1 for v in c.values() if v%2==1)\nprint(max(0,odd-1))', tip: '奇数回の文字は中央に1種類だけ置ける、という回文並べ替えの定理の応用。「1つは無料」の max(0, k−1) パターンは、連結・被覆系の数え上げに繰り返し現れる。', ins: ['aabb\n', 'abc\n', 'a\n', 'aab\n', 'abcde\n', 'aaabbbcc\n'] })

t({ lv: 783, concept: 'ハッシュ: 和がkのペアの種類数', title: '合計kになる顔合わせの種類', tags: ['ハッシュ'], io: '1行目に k、2行目に整数列が与えられます。', ask: '値の組 {a, b} (a+b=k、位置でなく値の組として区別。a=b の場合はその値が2回以上必要)が何種類あるかを出力してください。', h1: '差がkの種類数(同レベル既出)の和版。', h2: '集合に入れてa<k−a を数え、a=k/2 は個数2以上か確かめる。', ref: 'k=int(input())\nfrom collections import Counter\nc=Counter(map(int,input().split()))\ncnt=0\nfor a in c:\n    b=k-a\n    if a<b and b in c:\n        cnt+=1\n    elif a==b and c[a]>=2:\n        cnt+=1\nprint(cnt)', tip: '位置ペアの個数(既出)と値ペアの種類数では、重複の扱いが根本から違う。a=k−a の自己ペアの境界条件が、和系の数え上げに毎回顔を出す試金石。', ins: ['5\n1 4 2 3\n', '4\n2 2\n', '6\n3\n', '10\n5 5 5\n', '3\n1 2 1\n', '8\n1 7 2 6 3\n'] })

t({ lv: 784, concept: '数え上げ: 全種類を含む区間の数', title: 'フルコンプの区間を数える', tags: ['数え上げ', '二点法'], io: '整数列が1行で空白区切りで与えられます。', ask: '列に現れる全ての種類の値を含む連続部分配列の個数を出力してください。', h1: '最短(既出)と同じ窓で数えられる。', h2: '各lについて全種類が揃う最小のrを求めれば、r以降は全部有効。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nneed=len(set(a))\nfrom collections import defaultdict\ncnt=defaultdict(int)\nkinds=0\nr=0\ntotal=0\nfor l in range(n):\n    while r<n and kinds<need:\n        if cnt[a[r]]==0:\n            kinds+=1\n        cnt[a[r]]+=1\n        r+=1\n    if kinds==need:\n        total+=n-r+1\n    cnt[a[l]]-=1\n    if cnt[a[l]]==0:\n        kinds-=1\nprint(total)', tip: '「lごとに最小のrを求めて残り全部を足す」二点法カウントの完成形。窓が単調にしか動かないことがO(n)の根拠で、最短版と個数版が同じ骨格に収まる。', ins: ['1 2 1\n', '1 1\n', '1 2 3\n', '2 1 1 2\n', '5\n', '1 2 2 1 3\n'] })

t({ lv: 785, concept: '数え上げ: 下り坂の区間の数', title: '転がり落ちる区間', tags: ['数え上げ'], io: '整数列が1行で空白区切りで与えられます。', ask: '厳密に減少する連続部分配列(長さ1以上)の個数を出力してください。', h1: '右肩上がりを数える(同レベル既出)の鏡像。', h2: '減少ランごとに三角数を足す。', ref: 'a=list(map(int,input().split()))\ntotal=0\nrun=1\nfor i in range(len(a)):\n    if i>0 and a[i]<a[i-1]:\n        run+=1\n    else:\n        run=1\n    total+=run\nprint(total)', tip: '「各位置で終わる有効区間の数を足す」型の減少版。上りと下りの両方を数えて単調区間の総数(既出)と突き合わせる、と3問が相互に検算し合う。', ins: ['3 2 1\n', '1 2 3\n', '5\n', '2 1 2 1\n', '9 7 5 3\n', '1 1\n'] })

t({ lv: 786, concept: 'ソート: 真ん中k個の和', title: '外れ値を捨てた芯の合計', tags: ['ソート', '統計'], io: '1行目に k、2行目に整数列(nとkの差は偶数)が与えられます。', ask: '昇順に並べて上下 (n−k)/2 個ずつを取り除いた、真ん中 k 個の和を出力してください。', h1: 'ソートしてスライス。', h2: '両端から同数を落とす。', ref: 'k=int(input())\na=sorted(map(int,input().split()))\nd=(len(a)-k)//2\nprint(sum(a[d:d+k]))', tip: 'トリム平均の分子で、上位k個の和(同レベル既出)が「端」を見るのに対しこちらは「芯」を見る。採点競技の最高最低カットの一般形でもある。', ins: ['2\n1 2 3 4\n', '1\n5 1 9\n', '3\n1 2 3\n', '2\n10 1 1 10\n', '1\n7\n', '3\n9 1 5 3 7\n'] })

t({ lv: 787, concept: '文字列: 180度回した数字の表記', title: 'さかさま読みの答案', tags: ['文字列'], io: '0, 1, 6, 8, 9 だけからなる数字列が1行で与えられます。', ask: '紙を180度回したときに読める数字列を出力してください(6と9が入れ替わり、並びは逆になります)。', h1: '判定(同レベル既出)の構成版。', h2: '逆順+文字の対応表。', ref: 's=input()\nm={"0":"0","1":"1","6":"9","8":"8","9":"6"}\nprint("".join(m[c] for c in reversed(s)))', tip: 'ストロボグラマティック数の変換操作そのもの。「反転して同じか」の判定は、この変換の不動点かどうかの言い換えで、変換を部品化すると判定が1行になる。', ins: ['69\n', '818\n', '96\n', '1\n', '600\n', '9061\n'] })

t({ lv: 788, concept: '数え上げ: 積が平方数になるペア', title: '掛けたら平方数の縁', tags: ['数え上げ', '数論'], io: '正整数の列が1行で空白区切りで与えられます。', ask: 'i<j で a[i]×a[j] が平方数になるペアの個数を出力してください。', h1: '積が平方数 ⇔ 平方因子を取り除いた芯(スクエアフリー部分)が等しい。', h2: '各数の芯を求めてCounterのC(c,2)。', ref: 'from collections import Counter\na=list(map(int,input().split()))\ndef core(x):\n    d=2\n    while d*d<=x:\n        while x%(d*d)==0:\n            x//=d*d\n        d+=1\n    return x\nc=Counter(core(x) for x in a)\nprint(sum(v*(v-1)//2 for v in c.values()))', tip: '「変換してからペア数え」の変換部が数論的な正規化(平方因子の除去)になった深い一例。芯の一致という同値関係が、掛け算の性質をハッシュに落とし込む。', ins: ['2 8 3\n', '1 4 9\n', '2 3 5\n', '12 3\n', '6 6\n', '2 18 8 50\n'] })

t({ lv: 789, concept: '文字列: 子音だけを逆順に', title: '母音は動かず子音は回れ右', tags: ['文字列'], io: '英小文字の文字列が1行で与えられます。', ask: '母音(a,i,u,e,o)の位置は変えず、子音だけをそれらの位置の中で逆順にした文字列を出力してください。', h1: '母音の入れ替え(同レベル既出)の補集合版。', h2: '子音を集めて逆順にし、子音の位置へ戻す。', ref: 's=list(input())\nidx=[i for i,c in enumerate(s) if c not in "aiueo"]\nvals=[s[i] for i in idx][::-1]\nfor i,v in zip(idx,vals):\n    s[i]=v\nprint("".join(s))', tip: '「条件を満たす位置だけの部分列を操作して書き戻す」3段構えは、偶数だけソート(既出)と同じ部分操作の型。条件が母音/子音に変わっても骨格は不変。', ins: ['hello\n', 'aiueo\n', 'sky\n', 'ab\n', 'code\n', 'python\n'] })

t({ lv: 790, concept: '数え上げ: 和が平方数になる区間', title: '合計が平方数の期間', tags: ['数え上げ'], io: '正整数の列が1行で空白区切りで与えられます。', ask: '要素の和が平方数(1, 4, 9, …)になる連続部分配列の個数を出力してください。', h1: '素数になる区間(同レベル既出)の述語違い。', h2: '累積和の差とisqrtでの平方判定。', ref: 'import math\na=list(map(int,input().split()))\nn=len(a)\ncnt=0\nfor i in range(n):\n    s=0\n    for j in range(i,n):\n        s+=a[j]\n        r=math.isqrt(s)\n        if r*r==s:\n            cnt+=1\nprint(cnt)', tip: '区間和の性質判定は「累積和+述語」で述語だけ差し替え可能。素数・平方数・回文数と、述語のライブラリが揃うほど新しい問いが量産できる構造が見える。', ins: ['1 3 5\n', '4\n', '2 2\n', '1 1 1\n', '3 6\n', '5 4 7\n'] })

t({ lv: 791, concept: '文字列: 最も長く一致する出だしのペア', title: '書き出しがそっくりな2語', tags: ['文字列', 'ソート'], io: '単語(2個以上)が空白区切りで1行に与えられます。', ask: '2つの単語の共通接頭辞の長さとして最大の値を出力してください。', h1: '全ペアを見る必要はない。', h2: 'ソートすると最長の共通接頭辞は隣接ペアに現れる。', ref: 'ws=sorted(input().split())\ndef lcp(a,b):\n    k=0\n    while k<len(a) and k<len(b) and a[k]==b[k]:\n        k+=1\n    return k\nprint(max(lcp(ws[i],ws[i+1]) for i in range(len(ws)-1)))', tip: '「ソートすると最良ペアが隣接に来る」の接頭辞版で、XOR最小ペア(既出)と同じ論法。接尾辞配列のLCP配列(既出)の単語版ミニチュアでもある。', ins: ['flower flow flight\n', 'ab cd\n', 'aa aa\n', 'abc abd\n', 'x xy xyz\n', 'dog dot cat\n'] })

t({ lv: 792, concept: 'リスト: 均すのに動かす土の量', title: '山を削って谷を埋める', tags: ['リスト'], io: '整数列(合計は個数で割り切れる)が1行で空白区切りで与えられます。', ask: '全要素を平均に揃えるとき、移動する量の合計(=平均より高い分の合計)を出力してください。', h1: '高い所から低い所へ移すだけで揃えられる。', h2: 'Σ max(0, x−平均)。', ref: 'a=list(map(int,input().split()))\navg=sum(a)//len(a)\nprint(sum(x-avg for x in a if x>avg))', tip: '超過分の合計=不足分の合計、が保存量(総和)の帰結で、片側だけ数えれば済む。中央値に揃える(総和が変わる操作)との違いは「移動か変更か」のモデルの差。', ins: ['3 1 2\n', '5 5\n', '4 0\n', '1 2 3 6\n', '9\n', '0 0 6\n'] })

t({ lv: 793, concept: '文字列: クエリ文字列の値の取り出し', title: 'URLの荷ほどき', tags: ['文字列'], io: '1行目に「key=value&key=value…」形式の文字列、2行目に探すキーが与えられます。', ask: 'そのキーの値を出力してください(無ければ none)。', h1: '&で切ってから=で切る。', h2: 'splitの2段重ね。', ref: 'q=input()\nkey=input()\nans="none"\nfor pair in q.split("&"):\n    k,v=pair.split("=")\n    if k==key:\n        ans=v\nprint(ans)', tip: 'Webの実務で毎日触るパースの最小形。区切り文字の2段構造(レコード区切りとフィールド区切り)はCSVもログも同じで、splitを重ねる感覚が万能に効く。', ins: ['a=1&b=2\nb\n', 'x=10\nx\n', 'a=1&b=2\nc\n', 'k=v&k2=v2&k3=v3\nk2\n', 'name=py\nname\n', 'a=0&b=1\na\n'] })

t({ lv: 794, concept: '二分探索: 各クエリの挿入位置の一覧', title: '整列を保つ座席案内', tags: ['二分探索'], io: '1行目に昇順の整数列、2行目に問い合わせの値の列が与えられます。', ask: '各問い合わせの値を「等しい値があればその前に」挿入する位置(0始まり)を、順に空白区切りで出力してください。', h1: '挿入位置の総和(同レベル既出)の一覧版。', h2: 'bisect_leftを各クエリに。', ref: 'import bisect\na=list(map(int,input().split()))\nqs=list(map(int,input().split()))\nprint(" ".join(str(bisect.bisect_left(a,q)) for q in qs))', tip: 'bisect_leftの返り値そのものを出力する、二分探索APIの素振り問題。「等しい値の前」がleftで「後」がright、の1語の差が仕様として問われている。', ins: ['1 3 5\n2 3 6\n', '10\n5 15\n', '1 1 2\n1\n', '2 4 6 8\n8 1\n', '5 5\n5\n', '1 2 3\n0 4\n'] })

t({ lv: 795, concept: '文字列: 単語の中身だけ逆順', title: '単語は動かず文字だけ回転', tags: ['文字列'], io: '単語が空白区切りで1行に与えられます。', ask: '単語の並び順は保ったまま、各単語の中の文字だけを逆順にして出力してください。', h1: '単語ごとに[::-1]。', h2: 'split→変換→join。', ref: 'print(" ".join(w[::-1] for w in input().split()))', tip: '単語単位で逆順に並べる問題(同レベル既出)との合成で「全体を逆順にして各単語も逆順にすると単語順逆転」という綺麗な恒等式が成り立つ。分解→写像→結合の最短例。', ins: ['abc def\n', 'a\n', 'hello world\n', 'ab ba\n', 'xyz\n', 'hi yo hey\n'] })

t({ lv: 796, concept: 'ハッシュ: 隣り合わせにならない値の種類数', title: '密集しない律儀な値', tags: ['ハッシュ'], io: '整数列が1行で空白区切りで与えられます。', ask: '列に現れる値のうち「同じ値が隣り合う場所が一度もない」ものの種類数を出力してください。', h1: '隣接同値の位置の値を失格にする。', h2: '全種類から失格を引く。', ref: 'a=input().split()\nbad=set()\nfor i in range(len(a)-1):\n    if a[i]==a[i+1]:\n        bad.add(a[i])\nprint(len(set(a)-bad))', tip: '「一度でも起きたら失格」の集合演算(全体−違反)は、ログの健全性チェックの定番構造。違反の検出と種類の集計を分けて書くと仕様変更に強い。', ins: ['1 2 1 1\n', '1 2 3\n', '5 5\n', '1 2 1 2\n', '3 3 3\n', '1 1 2\n'] })

t({ lv: 797, concept: '窓: 各窓の種類数の一覧', title: '窓ごとの顔ぶれの数', tags: ['窓', 'ハッシュ'], io: '1行目に k、2行目に整数列(長さk以上)が与えられます。', ask: '長さ k の各窓に含まれる相異なる値の個数を、左から順に空白区切りで出力してください。', h1: 'Counterを差分更新する。', h2: '出る要素が0個になったら種類数を減らす。', ref: 'from collections import Counter\nk=int(input())\na=list(map(int,input().split()))\nc=Counter(a[:k])\nout=[len(c)]\nfor i in range(k,len(a)):\n    c[a[i]]+=1\n    c[a[i-k]]-=1\n    if c[a[i-k]]==0:\n        del c[a[i-k]]\n    out.append(len(c))\nprint(" ".join(map(str,out)))', tip: '窓のCounterの差分更新は「0になったら消す」の後始末が命で、忘れるとlenが嘘をつく。移動窓の統計は和→種類数→最頻値と難度が階段状に上がる、その2段目。', ins: ['2\n1 1 2\n', '3\n1 2 1 3\n', '1\n5 5\n', '2\n1 2 3\n', '4\n1 1 1 1\n', '2\n4 4 4\n'] })

t({ lv: 798, concept: 'ハッシュ: 同型パターンのグループ数', title: '形が同じ単語の仲間分け', tags: ['ハッシュ', '文字列'], io: '単語が空白区切りで1行に与えられます。', ask: '文字の出現パターンが同じ(1対1の文字の置き換えで互いに変換できる)単語を同じグループとみなし、グループの総数を出力してください。', h1: '同型判定(既出)のグループ化版。', h2: '各文字を「初めて現れた位置」に置き換えた正規形をキーにする。', ref: 'def norm(w):\n    first={}\n    out=[]\n    for c in w:\n        if c not in first:\n            first[c]=len(first)\n        out.append(first[c])\n    return tuple(out)\nws=input().split()\nprint(len(set(norm(w) for w in ws)))', tip: '「初出順の番号列」への正規化は換字式暗号のパターン解析そのもの。同値関係のグループ化は毎回「正規形を設計してキーにする」に帰着する、5度目の型稽古。', ins: ['aba cdc xy\n', 'ab ba\n', 'aa bb cd\n', 'x y\n', 'abc def gg\n', 'aab abb\n'] })

t({ lv: 799, concept: '累積和: 赤字に落ちた回数', title: '貯金がマイナスに沈む瞬間', tags: ['累積和'], io: '整数列(日ごとの収支)が1行で空白区切りで与えられます。残高は0から始まります。', ask: '残高が「マイナスでない状態からマイナス」へ変わった回数を出力してください。', h1: '累積和の符号の遷移を数える。', h2: '直前が≥0で今回<0の回数。', ref: 'a=list(map(int,input().split()))\ns=0\nprev=0\ncnt=0\nfor x in a:\n    s+=x\n    if prev>=0 and s<0:\n        cnt+=1\n    prev=s\nprint(cnt)', tip: '符号の「遷移」を数えるのは、水たまりの個数(既出)と同じ立ち上がり検出の型。累積の推移をグラフに描けば、0線を下に横切る回数を数えていることが一目で分かる。', ins: ['1 -2 3 -4\n', '-1 1 -1\n', '1 2 3\n', '-5\n', '2 -3 2 -3\n', '0 -1\n'] })

t({ lv: 801, concept: 'クエリ: 更新つき区間の平均', title: '変わりゆく区間の平均点', tags: ['クエリ'], io: '1行目に n q、2行目に長さ n の列、続く q 行に「U i x」(i番目をxに) か「Q l r」(区間の平均を切り捨てで出力) が与えられます。', ask: '各 Q に対して区間 [l, r] の平均(床関数)を1行ずつ出力してください。', h1: '和と個数から平均。', h2: '負の数の床割りはPythonの//がそのまま正しい。', ref: 'n,q=map(int,input().split())\na=list(map(int,input().split()))\nfor _ in range(q):\n    parts=input().split()\n    if parts[0]=="U":\n        a[int(parts[1])-1]=int(parts[2])\n    else:\n        l,r=int(parts[1]),int(parts[2])\n        print(sum(a[l-1:r])//(r-l+1))', tip: '平均クエリは区間和クエリの皮を被った同じ問題で、セグメント木に載せるのも和だけでよい。負数の//が数学的な床になるPythonの仕様が、ここでは味方になる。', ins: ['3 3\n1 2 3\nQ 1 3\nU 2 5\nQ 1 2\n', '2 1\n4 5\nQ 1 2\n', '4 2\n1 1 1 1\nU 4 9\nQ 1 4\n', '1 3\n7\nQ 1 1\nU 1 1\nQ 1 1\n', '5 2\n10 20 30 40 50\nQ 2 4\nQ 1 5\n', '3 2\n-1 -2 -3\nQ 1 3\nQ 1 2\n'] })

t({ lv: 802, concept: 'クエリ: 更新つき区間最大の位置', title: '首位の座席番号を答える', tags: ['クエリ'], io: '1行目に n q、2行目に長さ n の列、続く q 行に「U i x」か「Q l r」が与えられます。', ask: '各 Q に対して区間 [l, r] の最大値の位置(最も左のもの、1始まり)を出力してください。', h1: '値のクエリ(同レベル既出)のargmax版。', h2: 'index系はスライスとmaxの組合せで。', ref: 'n,q=map(int,input().split())\na=list(map(int,input().split()))\nfor _ in range(q):\n    parts=input().split()\n    if parts[0]=="U":\n        a[int(parts[1])-1]=int(parts[2])\n    else:\n        l,r=int(parts[1]),int(parts[2])\n        m=max(a[l-1:r])\n        print(a.index(m,l-1,r)+1)', tip: 'セグメント木で(値, 位置)のペアをノードに持てばargmaxもO(log n)——「載せる値の型を太らせる」拡張の練習台。listのindexの範囲指定引数も地味に便利。', ins: ['4 2\n1 3 3 2\nQ 1 4\nU 1 5\n', '2 1\n7 7\nQ 1 2\n', '3 2\n1 2 3\nQ 2 3\nU 3 0\n', '1 1\n9\nQ 1 1\n', '5 2\n5 1 5 1 5\nQ 2 4\nQ 1 5\n', '3 1\n2 9 4\nQ 1 3\n'] })

t({ lv: 803, concept: 'クエリ: 区間加算つき区間の最大', title: '足しながら頂点を問う', tags: ['クエリ'], io: '1行目に n q、2行目に長さ n の列、続く q 行に「A l r x」(区間にxを加算) か「Q l r」(区間の最大を出力) が与えられます。', ask: '各 Q に対して区間 [l, r] の最大値を1行ずつ出力してください。', h1: '加算+和(既出)の最大版。', h2: '素朴に足し込んでmaxを取るのが基準解。', ref: 'n,q=map(int,input().split())\na=list(map(int,input().split()))\nfor _ in range(q):\n    parts=input().split()\n    if parts[0]=="A":\n        l,r,x=int(parts[1]),int(parts[2]),int(parts[3])\n        for i in range(l-1,r):\n            a[i]+=x\n    else:\n        l,r=int(parts[1]),int(parts[2])\n        print(max(a[l-1:r]))', tip: '遅延伝播セグメント木の代表的な組合せ(区間add+区間max)の素朴版。maxは加算と可換(max+x = max(それぞれ+x))なので遅延が綺麗に流れる、という理論の入り口。', ins: ['3 3\n1 2 3\nQ 1 3\nA 1 2 10\nQ 1 3\n', '2 3\n0 0\nA 1 1 5\nQ 1 2\nQ 2 2\n', '4 2\n1 2 3 4\nA 1 4 1\nQ 2 3\n', '1 3\n-5\nQ 1 1\nA 1 1 10\nQ 1 1\n', '3 2\n1 1 1\nA 2 3 2\nQ 1 3\n', '2 1\n8 3\nQ 1 2\n'] })

t({ lv: 804, concept: 'クエリ: 上限キャップを区間にかける', title: '天井を下げる操作', tags: ['クエリ'], io: '1行目に n q、2行目に長さ n の列、続く q 行に「C l r x」(区間の各値をmin(値, x)に) か「Q i」(i番目を出力) が与えられます。', ask: '各 Q に対して現在の i 番目の値を1行ずつ出力してください。', h1: '最低保証(同レベル既出)の鏡像(chmin)。', h2: '素朴にminを適用。', ref: 'n,q=map(int,input().split())\na=list(map(int,input().split()))\nfor _ in range(q):\n    parts=input().split()\n    if parts[0]=="C":\n        l,r,x=int(parts[1]),int(parts[2]),int(parts[3])\n        for i in range(l-1,r):\n            if a[i]>x:\n                a[i]=x\n    else:\n        print(a[int(parts[1])-1])', tip: '区間chmin/chmaxはSegment Tree Beatsという発展技法の主戦場。素朴版で「上限は何度かけても下がるだけ」という単調性を掴むのが、その理解の第一歩。', ins: ['3 3\n5 6 7\nC 1 2 4\nQ 1\nQ 3\n', '2 3\n3 8\nC 1 2 5\nQ 2\nQ 1\n', '1 2\n9\nC 1 1 4\nQ 1\n', '4 3\n1 5 3 7\nC 2 4 4\nQ 2\nQ 4\n', '3 2\n2 2 2\nC 1 3 5\nQ 2\n', '2 2\n6 1\nC 1 1 3\nQ 1\n'] })

t({ lv: 805, concept: 'クエリ: 先頭からの最低記録', title: 'ワースト記録の照会', tags: ['クエリ'], io: '1行目に n q、2行目に長さ n の列、続く q 行に「U i x」か「Q k」(先頭k個の最小を出力) が与えられます。', ask: '各 Q に対して先頭 k 個の最小値を1行ずつ出力してください。', h1: '最高記録(同レベル既出)の鏡像。', h2: 'min(a[:k])。', ref: 'n,q=map(int,input().split())\na=list(map(int,input().split()))\nfor _ in range(q):\n    parts=input().split()\n    if parts[0]=="U":\n        a[int(parts[1])-1]=int(parts[2])\n    else:\n        print(min(a[:int(parts[1])]))', tip: '接頭辞クエリは区間クエリの特殊形で、BITが得意とする形(BITは本来は接頭辞の構造)。maxとminの鏡像がクエリの世界でも成り立つことを一往復で確認できる。', ins: ['3 3\n3 1 2\nQ 2\nU 2 5\nQ 3\n', '2 2\n4 4\nQ 1\nQ 2\n', '4 3\n5 4 3 2\nQ 4\nU 4 9\nQ 4\n', '1 1\n8\nQ 1\n', '3 2\n1 2 3\nU 1 10\nQ 2\n', '2 1\n7 3\nQ 2\n'] })

t({ lv: 806, concept: 'クエリ: 区間に階段を足して1点を読む', title: '傾いた足し算', tags: ['クエリ'], io: '1行目に n q、2行目に長さ n の列、続く q 行に「A l r」(位置l,l+1,…,rにそれぞれ1,2,3,…を加算) か「Q i」が与えられます。', ask: '各 Q に対して現在の i 番目の値を1行ずつ出力してください。', h1: '定数でなく等差数列を足す区間更新。', h2: '素朴に足すのが基準解。高速化は差分をもう1回差分する(2階差分)。', ref: 'n,q=map(int,input().split())\na=list(map(int,input().split()))\nfor _ in range(q):\n    parts=input().split()\n    if parts[0]=="A":\n        l,r=int(parts[1]),int(parts[2])\n        for k,i in enumerate(range(l-1,r),1):\n            a[i]+=k\n    else:\n        print(a[int(parts[1])-1])', tip: '等差数列の区間加算は「差分配列に定数の区間加算」に化け、それはさらに差分すると2点更新になる——2階差分(いもすの2段掛け)の入り口となる名変換。', ins: ['3 3\n0 0 0\nA 1 3\nQ 2\nQ 3\n', '2 3\n5 5\nA 1 2\nQ 1\nQ 2\n', '4 3\n0 0 0 0\nA 2 4\nQ 3\nQ 1\n', '1 2\n3\nA 1 1\nQ 1\n', '3 3\n1 1 1\nA 1 2\nA 2 3\nQ 2\n', '5 2\n0 0 0 0 0\nA 1 5\nQ 5\n'] })

t({ lv: 807, concept: 'シミュレーション: 塗り終わりの色数', title: '最後に見えている色は何色', tags: ['シミュレーション'], io: '1行目に 長さ L と操作数 n、続く n 行に「l r c」(区間[l,r]を色cで上塗り)が与えられます(色は正整数、初期は無色)。', ask: '全操作後に見えている相異なる色の数を出力してください(無色は数えない)。', h1: '最終的な色(同レベル既出)の集計版。', h2: '配列に上塗りして最後にset。', ref: 'first=input().split()\nL,n=int(first[0]),int(first[1])\na=[0]*(L+1)\nfor _ in range(n):\n    l,r,c=map(int,input().split())\n    for i in range(l,r+1):\n        a[i]=c\nprint(len(set(a[1:L+1])-{0}))', tip: '後の塗りが前を覆う「上書きの世界」では、逆順に処理して未確定の場所だけ塗る高速化が定石になる。塗った色の一部が完全に隠れて消える、が答えを非自明にする。', ins: ['5 2\n1 3 1\n2 4 2\n', '3 1\n1 3 7\n', '4 2\n1 4 1\n1 4 2\n', '5 2\n1 2 3\n4 5 3\n', '6 3\n1 6 1\n2 5 2\n3 4 3\n', '2 0\n'] })

t({ lv: 808, concept: 'クエリ: 点の追加と長方形内の数え上げ', title: '地図にピンを刺しながら数える', tags: ['クエリ'], io: '1行目に操作数 q、続く q 行に「A x y」(点を追加) か「Q x1 y1 x2 y2」(長方形[x1,x2]×[y1,y2]内の点数を出力) が与えられます。', ask: '各 Q に対して長方形内(境界含む)の点の個数を1行ずつ出力してください(同じ点の重複追加もそれぞれ数えます)。', h1: '点のリストを走査するのが基準解。', h2: '高速化は2次元BITや座標圧縮+マージソート木。', ref: 'q=int(input())\npts=[]\nfor _ in range(q):\n    parts=input().split()\n    if parts[0]=="A":\n        pts.append((int(parts[1]),int(parts[2])))\n    else:\n        x1,y1,x2,y2=map(int,parts[1:])\n        print(sum(1 for x,y in pts if x1<=x<=x2 and y1<=y<=y2))', tip: '動的な2次元計数は矩形和(同レベル既出)の追加つき版で、オンライン地図の「表示領域内の店舗数」そのもの。素朴O(qn)を正とし、kd木やBITの検証台にする。', ins: ['4\nA 1 1\nA 2 3\nQ 0 0 2 2\nQ 2 2 3 3\n', '3\nA 5 5\nQ 5 5 5 5\nQ 0 0 4 4\n', '5\nA 1 1\nA 1 1\nQ 1 1 1 1\nA 0 0\nQ 0 0 1 1\n', '2\nA 3 4\nQ 3 3 4 4\n', '4\nA 2 2\nQ 0 0 10 10\nA 7 7\nQ 5 5 9 9\n', '1\nQ 0 0 9 9\n'] })

t({ lv: 809, concept: 'クエリ: 区間の2番目の最大値', title: '区間の銀メダルを探す', tags: ['クエリ'], io: '1行目に n q、2行目に長さ n の列、続く q 行に区間 l r (長さ2以上) が与えられます。', ask: '各区間の大きい方から2番目の値(重複は区別する)を1行ずつ出力してください。', h1: '2番目の最小(既出)の鏡像。', h2: 'sorted(降順)[1]。', ref: 'n,q=map(int,input().split())\na=list(map(int,input().split()))\nfor _ in range(q):\n    l,r=map(int,input().split())\n    print(sorted(a[l-1:r],reverse=True)[1])', tip: 'スパーステーブルに「最大2つ」を載せれば O(1) クエリになる、統計量の拡張の練習。最大と2番目の対はトーナメントの決勝戦(最大に負けた最強)にも通じる。', ins: ['4 2\n3 1 4 1\n1 4\n2 3\n', '2 1\n5 7\n1 2\n', '5 2\n2 2 2 2 2\n1 5\n2 3\n', '3 1\n9 1 5\n1 3\n', '6 2\n4 6 1 3 9 2\n2 5\n1 6\n', '4 1\n8 3 5 3\n1 4\n'] })

t({ lv: 810, concept: 'クエリ: 区間が全部同じ値か', title: '足並みそろった区間か', tags: ['クエリ'], io: '1行目に n q、2行目に長さ n の列、続く q 行に区間 l r が与えられます。', ask: '各区間の要素が全て等しいなら yes、そうでなければ no を1行ずつ出力してください。', h1: 'minとmaxが等しいか、で判定できる。', h2: 'setにして大きさ1か、でもよい。', ref: 'n,q=map(int,input().split())\na=list(map(int,input().split()))\nfor _ in range(q):\n    l,r=map(int,input().split())\n    seg=a[l-1:r]\n    print("yes" if min(seg)==max(seg) else "no")', tip: 'min==maxへの言い換えで、既にあるminとmaxのスパーステーブル2本がそのまま流用できる——新しい木を作らず既存の前計算を組み合わせる、クエリ設計の節約術。', ins: ['4 2\n1 1 2 1\n1 2\n1 4\n', '3 1\n7 7 7\n1 3\n', '2 2\n1 2\n1 1\n1 2\n', '5 1\n3 3 3 4 3\n2 4\n', '1 1\n9\n1 1\n', '4 1\n5 5 5 5\n2 3\n'] })

t({ lv: 811, concept: 'クエリ: 区間の立ちビットの合計', title: '区間の点灯ランプ総数', tags: ['クエリ', 'bit演算'], io: '1行目に n q、2行目に長さ n の非負整数列、続く q 行に区間 l r が与えられます。', ask: '各区間の要素の2進表記の1の総数を1行ずつ出力してください。', h1: 'popcountの区間和。', h2: 'popcount列を先に作れば区間和クエリと同じ。', ref: 'n,q=map(int,input().split())\na=list(map(int,input().split()))\np=[bin(x).count("1") for x in a]\nfor _ in range(q):\n    l,r=map(int,input().split())\n    print(sum(p[l-1:r]))', tip: '「変換してから既存のクエリに帰着」の最小例で、popcount列の累積和を作れば全クエリO(1)。ビットごとの累積和を64本持つ発展形は区間AND/ORクエリの土台になる。', ins: ['3 2\n1 2 3\n1 3\n2 2\n', '2 1\n7 8\n1 2\n', '4 1\n0 0 0 15\n1 4\n', '1 1\n5\n1 1\n', '3 1\n3 3 3\n1 3\n', '5 2\n1 1 1 1 1\n1 5\n3 3\n'] })

t({ lv: 812, concept: 'クエリ: 区間の積の桁数', title: '掛け合わせは何桁になる', tags: ['クエリ'], io: '1行目に n q、2行目に長さ n の正整数列、続く q 行に区間 l r が与えられます。', ask: '各区間の要素の積の十進の桁数を1行ずつ出力してください。', h1: '多倍長で実際に掛けてlen(str())が確実。', h2: 'log10の和による近似は境界で誤差が出る。', ref: 'n,q=map(int,input().split())\na=list(map(int,input().split()))\nfor _ in range(q):\n    l,r=map(int,input().split())\n    p=1\n    for x in a[l-1:r]:\n        p*=x\n    print(len(str(p)))', tip: '桁数=floor(log10)+1だが、浮動小数のlog和は10のべき乗ちょうどの近くで嘘をつく。Pythonの多倍長整数で厳密に、が正しさ最優先の一手(階乗の桁数と同じ教訓)。', ins: ['3 2\n2 5 10\n1 2\n1 3\n', '2 1\n9 9\n1 2\n', '4 1\n10 10 10 10\n1 4\n', '1 1\n7\n1 1\n', '3 1\n99 99 99\n1 3\n', '2 1\n1 1\n1 2\n'] })

t({ lv: 813, concept: '窓: 各窓の最大と最小の和の総和', title: '両極の和を積み上げる', tags: ['窓'], io: '1行目に k、2行目に整数列(長さk以上)が与えられます。', ask: '長さ k の各窓について(最大値+最小値)を求め、その総和を出力してください。', h1: '最小の総和(同レベル既出)と最大の総和の合成。', h2: '窓ごとにmaxとminを取るのが基準解。デック2本でO(n)。', ref: 'k=int(input())\na=list(map(int,input().split()))\nprint(sum(max(a[i:i+k])+min(a[i:i+k]) for i in range(len(a)-k+1)))', tip: '(max+min)/2は窓のミッドレンジ(中点)で、外れ値に最も弱い代表値として統計の教材になる。max用とmin用の単調デックを並走させる高速化は既出部品の合体で書ける。', ins: ['2\n1 3 2\n', '1\n4 5\n', '3\n1 2 3\n', '2\n5 5 5\n', '3\n4 1 7 2\n', '2\n10 1\n'] })

t({ lv: 814, concept: '数え上げ: 区間の先頭たちの総和', title: 'すべての区間の第一走者', tags: ['数え上げ'], io: '整数列が1行で空白区切りで与えられます。', ask: '全ての連続部分配列について「先頭の要素」を足し合わせた総和を出力してください。', h1: '各要素が先頭になる区間の数を考える。', h2: '位置i(0始まり)の要素は n−i 個の区間の先頭。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nprint(sum(a[i]*(n-i) for i in range(n)))', tip: '「回数×値」の寄与計算のもっとも透明な例で、全区間の和の総和(既出)の i×(n−i+1) 倍がどこから来るかを分解して見せてくれる。', ins: ['1 2 3\n', '5\n', '2 4\n', '1 1 1 1\n', '3 1\n', '0 9\n'] })

t({ lv: 815, concept: '数え上げ: 全ペアの大きい方の総和', title: '勝者の得点だけ集める', tags: ['数え上げ', 'ソート'], io: '整数列(2個以上)が1行で空白区切りで与えられます。', ask: '全てのペア (i<j) について max(a[i], a[j]) を足した総和を出力してください。', h1: 'ソートすると各要素が「勝つ回数」が分かる。', h2: '昇順で位置i(0始まり)の要素はi回勝つ。', ref: 'a=sorted(map(int,input().split()))\nprint(sum(a[i]*i for i in range(len(a))))', tip: 'ソートで順序を確定させてから寄与を数える、O(n²)→O(n log n)の典型変換。minの総和は鏡像の Σa[i]×(n−1−i) で、2つ足すとペアの和の総和に一致する検算も効く。', ins: ['1 2 3\n', '5 5\n', '4 1\n', '1 2 3 4\n', '2 2 3\n', '0 10 5\n'] })

t({ lv: 816, concept: '数え上げ: 全ペアの差の合計', title: 'みんなの格差の総量', tags: ['数え上げ', 'ソート'], io: '整数列(2個以上)が1行で空白区切りで与えられます。', ask: '全てのペア (i<j) の |a[i]−a[j]| の総和を出力してください。', h1: 'ソートすれば絶対値が外れる。', h2: '昇順で位置iの要素の寄与は a[i]×(2i−n+1)。', ref: 'a=sorted(map(int,input().split()))\nn=len(a)\nprint(sum(a[i]*(2*i-n+1) for i in range(n)))', tip: 'ジニ係数の分子として経済統計に現れる由緒ある量。i番目は「i回引かれ、n−1−i回引く」の差し引きが係数2i−n+1に畳まれている、寄与計算の代表作。', ins: ['1 2 3\n', '5 5\n', '1 4\n', '1 2 3 4\n', '10\n', '0 5 10\n'] })

t({ lv: 817, concept: 'Union-Find: 班の代表番号を答える', title: 'まとめ役は誰だ', tags: ['Union-Find'], io: '1行目に人数 n と操作数 q、続く q 行に「U a b」(2人の班を併合) か「Q v」(vの班の最小番号を出力) が与えられます。', ask: '各 Q に対してその人の班の中で最小の番号を1行ずつ出力してください。', h1: '根に「班の最小番号」を持たせる。', h2: '併合時にminを取って引き継ぐ。', ref: 'n,q=map(int,input().split())\np=list(range(n+1))\nmn=list(range(n+1))\ndef find(x):\n    while p[x]!=x:\n        p[x]=p[p[x]]\n        x=p[x]\n    return x\nfor _ in range(q):\n    parts=input().split()\n    if parts[0]=="U":\n        a,b=int(parts[1]),int(parts[2])\n        ra,rb=find(a),find(b)\n        if ra!=rb:\n            p[ra]=rb\n            mn[rb]=min(mn[rb],mn[ra])\n    else:\n        print(mn[find(int(parts[1]))])', tip: 'サイズ(既出)に続き、根に載せる集約値をminに替えた変奏。併合で保てる情報(min/max/和/XOR)なら何でも載る、Union-Findの拡張性が見える1問。', ins: ['3 3\nU 1 3\nQ 3\nQ 2\n', '4 4\nU 3 4\nQ 4\nU 1 4\nQ 3\n', '2 3\nQ 2\nU 1 2\nQ 2\n', '5 3\nU 2 5\nU 5 4\nQ 4\n', '3 2\nU 2 3\nQ 3\n', '1 1\nQ 1\n'] })

t({ lv: 818, concept: 'Union-Find: つなぐたびの島の数', title: '橋を架けるたびの島勘定', tags: ['Union-Find'], io: '1行目に頂点数 n と辺数 m、続く m 行に辺 u v が順に与えられます。', ask: '各辺を追加した直後の連結成分数を、順に空白区切りで出力してください。', h1: '実際に併合できたときだけ成分数が減る。', h2: '成分数カウンタを持ち回る。', ref: 'n,m=map(int,input().split())\np=list(range(n+1))\ndef find(x):\n    while p[x]!=x:\n        p[x]=p[p[x]]\n        x=p[x]\n    return x\ncnt=n\nout=[]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    ru,rv=find(u),find(v)\n    if ru!=rv:\n        p[ru]=rv\n        cnt-=1\n    out.append(cnt)\nprint(" ".join(map(str,out)))', tip: '成分数の推移は「n から始まり、有効な辺で1ずつ減る」単調非増加の階段。逆に辺を消す問題(既出)が時間反転でこの形に帰着する、オフライン処理の定石も背後にある。', ins: ['3 2\n1 2\n2 3\n', '4 3\n1 2\n3 4\n1 3\n', '2 1\n1 2\n', '3 3\n1 2\n1 2\n2 3\n', '5 2\n1 5\n2 3\n', '4 4\n1 2\n2 3\n3 4\n4 1\n'] })

t({ lv: 819, concept: 'いもす: ちょうど二重の長さ', title: 'ぴったり二枚重ねの部分', tags: ['いもす', '区間'], io: '1行目に n、続く n 行に区間 l r ([l, r)) が与えられます。', ask: 'ちょうど2つの区間に覆われている部分の長さの合計を出力してください。', h1: '1回だけ・2回以上(いずれも既出)に続く「ちょうど2」。', h2: 'いもすの累積が2に等しい座標を数える。', ref: 'n=int(input())\nevents=[]\nmx=0\nfor _ in range(n):\n    l,r=map(int,input().split())\n    events.append((l,1))\n    events.append((r,-1))\n    if r>mx:\n        mx=r\nimos=[0]*(mx+2)\nfor t2,d in events:\n    imos[t2]+=d\ncur=0\ntotal=0\nfor t2 in range(mx+1):\n    cur+=imos[t2]\n    if cur==2:\n        total+=1\nprint(total)', tip: '重なり深度のヒストグラム(深さごとの長さ)を作れば「ちょうどk」「k以上」の全問いに一括で答えられる。閾値の読み替えだけで問題が量産される、いもすの器の大きさ。', ins: ['2\n1 4\n2 6\n', '3\n0 5\n1 4\n2 3\n', '1\n0 10\n', '3\n0 3\n0 3\n0 3\n', '2\n0 2\n3 5\n', '2\n1 5\n4 8\n'] })

t({ lv: 820, concept: 'シミュレーション: 区間回転を重ねた結果', title: 'ぐるぐる回した最終形', tags: ['シミュレーション'], io: '1行目に n q、2行目に長さ n の列、続く q 行に区間 l r が与えられます。', ask: '各操作で区間 [l, r] を右に1つ回転(末尾が先頭へ)させ、全操作後の列を空白区切りで出力してください。', h1: 'スライスの組み替えで回転を書く。', h2: 'a[l:r+1] = 最後の1個 + 残り。', ref: 'n,q=map(int,input().split())\na=input().split()\nfor _ in range(q):\n    l,r=map(int,input().split())\n    a[l-1:r]=[a[r-1]]+a[l-1:r-1]\nprint(" ".join(a))', tip: 'スライス代入による区間の書き換えはPythonの得意技で、rotate相当が1行になる。大量クエリでは平衡木やスキップリストが要る、操作系クエリの難所の入り口でもある。', ins: ['3 2\n1 2 3\n1 3\n1 2\n', '2 1\n5 6\n1 2\n', '4 1\n1 2 3 4\n2 4\n', '3 3\n1 2 3\n1 3\n1 3\n1 3\n', '5 1\n1 2 3 4 5\n2 3\n', '1 1\n7\n1 1\n'] })

t({ lv: 821, concept: 'ソート: 2つのキーで並べ替え', title: '第2キーは逆向きに', tags: ['ソート'], io: '1行目に n、続く n 行に「a b」の組が与えられます。', ask: 'a の昇順、a が同じなら b の降順に並べ替えて、1行ずつ「a b」で出力してください。', h1: '数値なら第2キーの符号反転で1回のソートに畳める。', h2: 'key=lambda t:(t[0], -t[1])。', ref: 'n=int(input())\nrows=[tuple(map(int,input().split())) for _ in range(n)]\nrows.sort(key=lambda t2:(t2[0],-t2[1]))\nfor a,b in rows:\n    print(a,b)', tip: '文字列キーでは符号反転が使えず「安定ソートを2回(第2キー→第1キー)」が定石になる。SQLのORDER BY a ASC, b DESC をPythonで書く、日常の技。', ins: ['3\n1 5\n1 9\n0 3\n', '2\n2 1\n1 2\n', '1\n4 4\n', '4\n1 1\n1 2\n2 1\n1 3\n', '3\n5 1\n5 2\n5 0\n', '2\n3 3\n3 4\n'] })

t({ lv: 822, concept: '木: 部分木の合計の一覧', title: '各部署の予算総額', tags: ['木'], io: '1行目に頂点数 n (n≥2)、2行目に頂点2〜nの親、3行目に各頂点の値が与えられます(根は頂点1)。', ask: '各頂点について「その部分木に含まれる値の合計」を、頂点1からnの順に空白区切りで出力してください。', h1: '部分木サイズの総和(同レベル既出)の値つき版。', h2: '番号の大きい順に親へ足し上げる。', ref: 'n=int(input())\npar=list(map(int,input().split()))\nval=list(map(int,input().split()))\nacc=val[:]\nacc=[0]+acc\nfor v in range(n,1,-1):\n    acc[par[v-2]]+=acc[v]\nprint(" ".join(str(acc[v]) for v in range(1,n+1)))', tip: '組織図の部門別集計そのもの。親リストの規約(親<子)による逆順ループの畳み込みが、再帰なしのボトムアップDPとして三たび登場する。', ins: ['3\n1 1\n1 2 3\n', '2\n1\n5 7\n', '4\n1 2 3\n1 1 1 1\n', '5\n1 1 2 2\n1 2 3 4 5\n', '4\n1 1 1\n0 1 2 3\n', '7\n1 1 2 2 3 3\n1 1 1 1 1 1 1\n'] })

t({ lv: 823, concept: 'シミュレーション: LRUの最終の中身', title: 'キャッシュに生き残った顔ぶれ', tags: ['シミュレーション'], io: '1行目に容量 C、2行目にアクセスするキーの列が与えられます。', ask: 'LRU方式(いっぱいのときは最も長く使われていないものを追い出す。アクセスは新しい順を更新する)で処理した後のキャッシュの中身を、新しい順に空白区切りで出力してください。', h1: 'ヒット数(同レベル既出)の中身版。', h2: 'リストで「使ったら末尾へ移す」を素直に。', ref: 'C=int(input())\nseq=input().split()\ncache=[]\nfor k in seq:\n    if k in cache:\n        cache.remove(k)\n    elif len(cache)==C:\n        cache.pop(0)\n    cache.append(k)\nprint(" ".join(reversed(cache)))', tip: 'OrderedDictやリンクリスト+辞書でO(1)化するのが本番実装だが、リスト素朴版は「新しさの順序」という不変量を最も読みやすく見せる。仕様の「新しい順に出力」が状態の向きの理解を試す。', ins: ['2\n1 2 3\n', '2\n1 2 1\n', '3\n1 2 3 2\n', '1\n5 6 5\n', '2\n1 1 1\n', '3\n4 5\n'] })

t({ lv: 824, concept: 'クエリ: これまでの最大値を答える', title: '殿堂入り記録の照会', tags: ['クエリ'], io: '1行目に操作数 q、続く q 行に「S x」(現在値をxにする) か「Q」(これまでに現在値が取った最大を出力) が与えられます(最初の操作はS)。', ask: '各 Q に対して、その時点までの現在値の履歴の最大を1行ずつ出力してください。', h1: '過去の時点の値を読む(同レベル既出)の集約版。', h2: '最大値を持ち回るだけ。', ref: 'q=int(input())\nbest=None\nfor _ in range(q):\n    parts=input().split()\n    if parts[0]=="S":\n        x=int(parts[1])\n        if best is None or x>best:\n            best=x\n    else:\n        print(best)', tip: '「履歴最大」はセグメント木の世界ではhistoric maximumと呼ばれる発展題材の赤ちゃん版。現在値と記録値の2変数を分けて持つ、状態設計の初歩が試される。', ins: ['4\nS 3\nQ\nS 1\nQ\n', '3\nS 5\nS 9\nQ\n', '5\nS 2\nQ\nS 7\nQ\nQ\n', '2\nS 0\nQ\n', '6\nS 4\nS 2\nQ\nS 6\nQ\nQ\n', '3\nS -5\nS -9\nQ\n'] })

export const CATALOG = TASKS
