// 生成タスク 第37波：lv551〜599。lv550(貪欲・バックトラッキング)とlv600(グラフ探索)の橋渡し。
// 貪欲法/区間スケジューリング/ハフマン/グラフ探索(BFS/DFS/最短路/トポロジカル)の本物の別問題。
// 重複なし・決定的・採点一意(整数/文字列/列出力のみ)。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 551, concept: '貪欲: 区間スケジューリング最大化', title: '重ならない区間の最大数', tags: ['貪欲'], io: '1行目に区間数 n、続く n 行に区間 l r が与えられます。', ask: '互いに重ならないように選べる区間の最大個数を出力してください。', h1: '終点でソートする。', h2: '直前の終点以降に始まる区間を貪欲に取る。', ref: 'n=int(input())\nivs=[tuple(map(int,input().split())) for _ in range(n)]\nivs.sort(key=lambda x:x[1])\ncnt=0\nlast=float("-inf")\nfor l,r in ivs:\n    if l>=last:\n        cnt+=1\n        last=r\nprint(cnt)', tip: '区間スケジューリングは「終わりが早い順」に取るのが最適(交換論法で証明できる)。', ins: ['3\n1 2\n2 3\n1 3\n', '4\n1 3\n2 4\n3 5\n0 6\n', '1\n0 10\n', '3\n1 2\n3 4\n5 6\n', '3\n1 5\n1 5\n1 5\n', '5\n1 2\n2 3\n3 4\n1 4\n2 5\n'] })

t({ lv: 552, concept: '貪欲: 最小の会議室数', title: '会議室の最小数', tags: ['貪欲'], io: '1行目に n、続く n 行に会議の開始 s と終了 e が与えられます。', ask: 'すべての会議を行うのに必要な会議室の最小数を出力してください。', h1: '開始と終了を別々にソートする。', h2: '開始イベントで+1、終了で-1し最大同時数を取る。', ref: 'n=int(input())\nevents=[]\nfor _ in range(n):\n    s,e=map(int,input().split())\n    events.append((s,1))\n    events.append((e,-1))\nevents.sort(key=lambda x:(x[0],x[1]))\ncur=0\nbest=0\nfor _,d in events:\n    cur+=d\n    if cur>best:\n        best=cur\nprint(best)', tip: '終了(-1)を開始(+1)より先に処理すると、端点が接する会議を同室扱いにできる。', ins: ['3\n0 30\n5 10\n15 20\n', '2\n7 10\n2 4\n', '1\n0 5\n', '3\n1 5\n2 6\n3 7\n', '4\n1 2\n2 3\n3 4\n4 5\n', '3\n0 10\n0 10\n0 10\n'] })

t({ lv: 553, concept: '貪欲: 完了時刻の総和最小化', title: '完了時刻の総和を最小化', tags: ['貪欲'], io: '各ジョブの処理時間の列が1行で与えられます(1台の機械で順に処理)。', ask: '処理順を最適化したときの、全ジョブの完了時刻の総和の最小値を出力してください。', h1: '短い処理時間の順に並べる(SPT)。', h2: '累積時間を足し込んでいく。', ref: 'a=sorted(map(int,input().split()))\nt=0\ntotal=0\nfor x in a:\n    t+=x\n    total+=t\nprint(total)', tip: '完了時刻の総和は「処理時間が短い順(SPT)」に並べると最小になる(短いほど多くのジョブに加算される)。', ins: ['3 1 2\n', '5\n', '1 1 1\n', '4 3 2 1\n', '10 20\n', '2 2 2 2\n'] })

t({ lv: 554, concept: '貪欲: 最小コインで支払う枚数', title: '正準硬貨系での最小枚数', tags: ['貪欲'], io: '1行目に金額 amount、2行目に硬貨の額面(降順でなくてよい)が与えられます(正準系=大きい順貪欲が最適)。', ask: '大きい額面から貪欲に使ったときの最小硬貨枚数を出力してください。作れないなら -1。', h1: '額面を降順に並べる。', h2: '各額面で可能な限り使う。', ref: 'amount=int(input())\ncoins=sorted(map(int,input().split()),reverse=True)\ncnt=0\nfor c in coins:\n    if amount<=0:\n        break\n    cnt+=amount//c\n    amount%=c\nprint(cnt if amount==0 else -1)', tip: '正準硬貨系(例: 1,5,10,50,100)では大きい順の貪欲が最適。一般系ではDPが必要。', ins: ['93\n1 5 10 50\n', '0\n1 5\n', '7\n2 4\n', '100\n1 5 10 25\n', '3\n1\n', '67\n1 5 10 25\n'] })

t({ lv: 555, concept: '貪欲: 活動の最大利益(締切付き)', title: '締切付きジョブの最大利益', tags: ['貪欲', 'ヒープ'], io: '1行目に n、続く n 行に締切 d と利益 p が与えられます(1ジョブ1単位時間)。', ask: '各時刻に1ジョブ、締切までに終えられるジョブだけ選んで得られる最大利益を出力してください。', h1: '利益降順に並べる。', h2: '小さいヒープで現在選んだ集合を保ち、容量超過なら最小利益を捨てる。', ref: 'import heapq\nn=int(input())\njobs=[tuple(map(int,input().split())) for _ in range(n)]\njobs.sort(key=lambda x:x[0])\nheap=[]\nfor d,p in jobs:\n    heapq.heappush(heap,p)\n    if len(heap)>d:\n        heapq.heappop(heap)\nprint(sum(heap))', tip: '締切付きジョブは「締切順に詰め、容量を超えたら最小利益を捨てる」最小ヒープ貪欲。', ins: ['4\n1 10\n2 20\n2 30\n1 40\n', '1\n1 5\n', '3\n3 10\n3 20\n3 30\n', '2\n1 100\n1 50\n', '3\n1 5\n2 5\n3 5\n', '4\n2 100\n1 19\n2 27\n1 25\n'] })

t({ lv: 556, concept: '貪欲: ガソリンスタンド一周', title: '一周できる開始地点', tags: ['貪欲'], io: '1行目に n、2行目に各地点のガソリン量、3行目に次の地点までの消費量が与えられます。', ask: '時計回りに一周して戻れる開始地点の添字(0始まり)を出力してください。複数あれば最小、不可能なら -1。', h1: '総ガソリン < 総消費 なら不可能。', h2: '走行残量が負になったら次の地点から再スタート。', ref: 'n=int(input())\ngas=list(map(int,input().split()))\ncost=list(map(int,input().split()))\nif sum(gas)<sum(cost):\n    print(-1)\nelse:\n    start=0\n    tank=0\n    for i in range(n):\n        tank+=gas[i]-cost[i]\n        if tank<0:\n            start=i+1\n            tank=0\n    print(start)', tip: '総和が足りれば必ず解があり、残量が負になった直後を始点にすれば一周できる。', ins: ['5\n1 2 3 4 5\n3 4 5 1 2\n', '3\n2 3 4\n3 4 3\n', '1\n5\n4\n', '2\n1 1\n2 2\n', '4\n5 1 2 3\n4 4 1 5\n', '3\n3 3 3\n3 3 3\n'] })

t({ lv: 557, concept: '貪欲: 風船を割る最小の矢', title: '区間を貫く最小の点数', tags: ['貪欲'], io: '1行目に n、続く n 行に区間 l r が与えられます。', ask: 'すべての区間を少なくとも1つ含むように打つ点(矢)の最小個数を出力してください。', h1: '終点でソートする。', h2: '現在の矢が届かない区間で新しい矢を打つ。', ref: 'n=int(input())\nif n==0:\n    print(0)\nelse:\n    ivs=[tuple(map(int,input().split())) for _ in range(n)]\n    ivs.sort(key=lambda x:x[1])\n    arrows=0\n    last=float("-inf")\n    for l,r in ivs:\n        if l>last:\n            arrows+=1\n            last=r\n    print(arrows)', tip: '区間を貫く最小点は「終点でソートし、外れたら終点に矢を置く」貪欲で最適。', ins: ['4\n10 16\n2 8\n1 6\n7 12\n', '4\n1 2\n3 4\n5 6\n7 8\n', '4\n1 2\n2 3\n3 4\n4 5\n', '1\n1 10\n', '3\n1 5\n2 3\n4 6\n', '3\n1 100\n1 100\n1 100\n'] })

t({ lv: 558, concept: '貪欲: 文字を消して最大単調列', title: '辞書順最小の単調増加スタック列', tags: ['貪欲', 'スタック'], io: '1行目に文字列 s、2行目に消す文字数 k が与えられます。', ask: 's から k 文字を消して残せる、辞書順で最小の文字列を出力してください。', h1: '単調増加スタックを保つ。', h2: '直前より小さい文字が来たら、消す枠がある限り pop。', ref: 's=input()\nk=int(input())\nstack=[]\nfor ch in s:\n    while stack and k>0 and stack[-1]>ch:\n        stack.pop()\n        k-=1\n    stack.append(ch)\nwhile k>0:\n    stack.pop()\n    k-=1\nprint("".join(stack))', tip: '「k文字消して辞書順最小」は単調スタック貪欲。大きい文字を後ろから削るほど小さくなる。', ins: ['cba\n1\n', 'abcde\n2\n', 'bcabc\n2\n', 'aaa\n1\n', 'edcba\n2\n', 'dacb\n2\n'] })

t({ lv: 559, concept: '貪欲: ジャンプで端に届くか', title: '配列の端に到達できるか', tags: ['貪欲'], io: '非負整数の列が1行で与えられます(各値はそこから進める最大歩数)。', ask: '先頭から最後尾に到達できるなら yes、できないなら no を出力してください。', h1: '到達可能な最遠位置を更新する。', h2: '現在地が最遠を超えたら失敗。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nreach=0\nok=True\nfor i in range(n):\n    if i>reach:\n        ok=False\n        break\n    if i+a[i]>reach:\n        reach=i+a[i]\nprint("yes" if ok and reach>=n-1 else "no")', tip: '到達判定は「今までに届く最遠位置」を1パスで更新する貪欲。', ins: ['2 3 1 1 4\n', '3 2 1 0 4\n', '0\n', '1 0 0\n', '2 0 0\n', '5 0 0 0 0 0\n'] })

t({ lv: 560, concept: '貪欲: 端に届く最小ジャンプ数', title: '最後尾までの最小ジャンプ数', tags: ['貪欲'], io: '非負整数の列が1行で与えられます(各値は最大歩数。最後尾に到達可能とする)。', ask: '先頭から最後尾に着く最小のジャンプ回数を出力してください。', h1: '現在の到達範囲の終端を意識する。', h2: '範囲を使い切ったら1ジャンプ増やし、次の最遠へ。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nif n<=1:\n    print(0)\nelse:\n    jumps=0\n    cur_end=0\n    farthest=0\n    for i in range(n-1):\n        if i+a[i]>farthest:\n            farthest=i+a[i]\n        if i==cur_end:\n            jumps+=1\n            cur_end=farthest\n    print(jumps)', tip: '最小ジャンプは「今のジャンプで届く範囲を使い切ったら次の最遠へ」というBFS的貪欲。', ins: ['2 3 1 1 4\n', '2 3 0 1 4\n', '1\n', '1 1 1 1\n', '5 1 1 1 1\n', '3 2 1 0 4\n'] })

t({ lv: 561, concept: 'グラフ: 連結成分の数(BFS)', title: 'BFSで連結成分を数える', tags: ['グラフ', 'BFS'], io: '1行目に n m、続く m 行に無向辺 u v が与えられます。', ask: '連結成分の個数を出力してください。', h1: '未訪問の頂点ごとにBFSを開始する。', h2: 'BFSを始めた回数が成分数。', ref: 'from collections import deque\nfirst=input().split()\nn=int(first[0])\nm=int(first[1])\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\nseen=[False]*(n+1)\ncnt=0\nfor s in range(1,n+1):\n    if not seen[s]:\n        cnt+=1\n        seen[s]=True\n        dq=deque([s])\n        while dq:\n            x=dq.popleft()\n            for y in g[x]:\n                if not seen[y]:\n                    seen[y]=True\n                    dq.append(y)\nprint(cnt)', tip: '未訪問頂点からBFS/DFSを始めた回数が連結成分の数になる。', ins: ['5 3\n1 2\n2 3\n4 5\n', '3 0\n', '4 4\n1 2\n2 3\n3 4\n4 1\n', '1 0\n', '6 2\n1 2\n3 4\n', '2 1\n1 2\n'] })

t({ lv: 562, concept: 'グラフ: 最短経路の長さ(BFS)', title: '重みなしグラフの最短距離', tags: ['グラフ', 'BFS'], io: '1行目に n m s t、続く m 行に無向辺 u v が与えられます。', ask: '頂点 s から t への最短経路の辺数を出力してください。到達不能なら -1。', h1: 'BFSで距離を配る。', h2: '初めて t に着いた距離が最短。', ref: 'from collections import deque\nfirst=input().split()\nn=int(first[0])\nm=int(first[1])\ns=int(first[2])\nt=int(first[3])\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\ndist=[-1]*(n+1)\ndist[s]=0\ndq=deque([s])\nwhile dq:\n    x=dq.popleft()\n    for y in g[x]:\n        if dist[y]==-1:\n            dist[y]=dist[x]+1\n            dq.append(y)\nprint(dist[t])', tip: '重みなしの最短路はBFS。キューから取り出した順に距離が確定する。', ins: ['4 3 1 4\n1 2\n2 3\n3 4\n', '4 2 1 4\n1 2\n3 4\n', '1 0 1 1\n', '5 4 1 5\n1 2\n2 3\n3 4\n4 5\n', '3 3 1 3\n1 2\n2 3\n1 3\n', '6 5 1 6\n1 2\n2 3\n3 6\n1 4\n4 5\n'] })

t({ lv: 563, concept: 'グラフ: グリッド最短路(BFS)', title: '記号で書かれた迷路の最短歩数', tags: ['グラフ', 'BFS'], io: '1行目に R C、続く R 行に迷路(. は通路、# は壁)。スタートは S、ゴールは G。', ask: 'S から G への最短歩数を出力してください。到達不能なら -1。', h1: '4方向にBFSを広げる。', h2: '壁(#)は通れない。', ref: 'from collections import deque\nfirst=input().split()\nR=int(first[0])\nC=int(first[1])\ngrid=[input() for _ in range(R)]\nsr=sc=gr=gc=0\nfor i in range(R):\n    for j in range(C):\n        if grid[i][j]=="S":\n            sr,sc=i,j\n        elif grid[i][j]=="G":\n            gr,gc=i,j\ndist=[[-1]*C for _ in range(R)]\ndist[sr][sc]=0\ndq=deque([(sr,sc)])\nwhile dq:\n    x,y=dq.popleft()\n    for dx,dy in ((1,0),(-1,0),(0,1),(0,-1)):\n        nx,ny=x+dx,y+dy\n        if 0<=nx<R and 0<=ny<C and grid[nx][ny]!="#" and dist[nx][ny]==-1:\n            dist[nx][ny]=dist[x][y]+1\n            dq.append((nx,ny))\nprint(dist[gr][gc])', tip: 'グリッド最短路もBFS。マスを頂点、隣接4方向を辺とみなす。', ins: ['3 3\nS..\n.#.\n..G\n', '1 2\nSG\n', '3 3\nS#G\n.#.\n...\n', '2 2\nS#\n#G\n', '3 5\nS....\n.###.\n....G\n', '1 5\nS...G\n'] })

t({ lv: 564, concept: 'グラフ: ダイクストラ最短路', title: '重み付き最短距離(ダイクストラ)', tags: ['グラフ', 'ヒープ'], io: '1行目に n m s t、続く m 行に有向辺 u v w(w>=0)が与えられます。', ask: 's から t への最短距離を出力してください。到達不能なら -1。', h1: '最小ヒープで未確定の最小距離頂点を取り出す。', h2: '取り出した距離が確定値。隣接を緩和する。', ref: 'import heapq\nfirst=input().split()\nn=int(first[0])\nm=int(first[1])\ns=int(first[2])\nt=int(first[3])\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v,w=map(int,input().split())\n    g[u].append((v,w))\nINF=float("inf")\ndist=[INF]*(n+1)\ndist[s]=0\npq=[(0,s)]\nwhile pq:\n    d,x=heapq.heappop(pq)\n    if d>dist[x]:\n        continue\n    for y,w in g[x]:\n        if d+w<dist[y]:\n            dist[y]=d+w\n            heapq.heappush(pq,(dist[y],y))\nprint(dist[t] if dist[t]<INF else -1)', tip: 'ダイクストラは非負重みの最短路。ヒープから出した瞬間にその頂点の距離が確定する。', ins: ['4 4 1 4\n1 2 1\n2 4 5\n1 3 2\n3 4 2\n', '2 1 1 2\n1 2 7\n', '3 1 1 3\n1 2 1\n', '1 0 1 1\n', '5 6 1 5\n1 2 2\n2 3 2\n3 5 2\n1 4 1\n4 5 10\n2 5 5\n', '3 3 1 3\n1 2 4\n1 3 10\n2 3 1\n'] })

t({ lv: 565, concept: 'グラフ: 二重終端BFS距離合計', title: '全頂点からの最短距離の和', tags: ['グラフ', 'BFS'], io: '1行目に n m s、続く m 行に無向辺 u v が与えられます。', ask: '頂点 s から各頂点への最短距離(辺数)の総和を出力してください。到達不能な頂点は無視します。', h1: 'sからBFSする。', h2: '到達できた頂点の距離を合計する。', ref: 'from collections import deque\nfirst=input().split()\nn=int(first[0])\nm=int(first[1])\ns=int(first[2])\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\ndist=[-1]*(n+1)\ndist[s]=0\ndq=deque([s])\nwhile dq:\n    x=dq.popleft()\n    for y in g[x]:\n        if dist[y]==-1:\n            dist[y]=dist[x]+1\n            dq.append(y)\ntotal=sum(d for d in dist[1:] if d>0)\nprint(total)', tip: '単一始点BFSの距離配列を合計するだけ。閉路があっても最短距離は一意。', ins: ['4 3 1\n1 2\n2 3\n3 4\n', '3 0 1\n', '4 4 1\n1 2\n2 3\n3 4\n4 1\n', '1 0 1\n', '5 4 3\n1 2\n2 3\n3 4\n4 5\n', '3 2 2\n1 2\n2 3\n'] })

t({ lv: 566, concept: 'グラフ: 極大マッチングかどうか', title: '今のペアに1組も足せないか', tags: ['グラフ'], io: '1行目に n m k、続く m 行に無向辺 u v、続く k 行に選んだペア u v が与えられます。選んだペアはすべて実在する辺で、どの頂点も高々1回しか現れません。', ask: '選んだペアにこれ以上どの辺も足せない(どの辺も少なくとも片方の端点が既に使われている)なら yes、まだ足せる辺が残っているなら no を出力してください。', h1: '既にペアで使われている頂点を集合にまとめる。', h2: '両端がどちらも未使用の辺が1本でもあれば、まだ足せる。', ref: 'first=input().split()\nn,m,k=int(first[0]),int(first[1]),int(first[2])\nes=[]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    es.append((u,v))\nused=set()\nfor _ in range(k):\n    u,v=map(int,input().split())\n    used.add(u)\n    used.add(v)\nprint("yes" if all(u in used or v in used for u,v in es) else "no")', tip: '「これ以上足せない(極大)」と「本数が最大」は別物。辺 1-2, 2-3, 3-4 で真ん中の 2-3 だけを選ぶと極大だが、1-2 と 3-4 を選べば2本取れる。貪欲に取っていけば必ず極大にはなり、そこが最大マッチング(既出)との差の出発点になる。', ins: ['4 3 2\n1 2\n3 4\n1 3\n1 2\n3 4\n', '4 2 1\n1 2\n3 4\n1 2\n', '2 1 0\n1 2\n', '5 4 2\n1 2\n2 3\n3 4\n4 5\n1 2\n3 4\n', '6 3 1\n1 2\n3 4\n5 6\n1 2\n', '3 3 1\n1 2\n2 3\n1 3\n1 2\n'] })

t({ lv: 567, concept: 'グラフ: サイクル検出(無向)', title: 'Union-Findで閉路を見つける', tags: ['グラフ', 'DFS'], io: '1行目に n m、続く m 行に無向辺 u v が与えられます。', ask: '閉路が存在するなら yes、なければ no を出力してください。', h1: 'Union-Findで辺を併合する。', h2: '既に同じ集合の2頂点を結ぶ辺で閉路。', ref: 'first=input().split()\nn=int(first[0])\nm=int(first[1])\npar=list(range(n+1))\ndef find(x):\n    while par[x]!=x:\n        par[x]=par[par[x]]\n        x=par[x]\n    return x\nhas=False\nfor _ in range(m):\n    u,v=map(int,input().split())\n    ru=find(u)\n    rv=find(v)\n    if ru==rv:\n        has=True\n    else:\n        par[ru]=rv\nprint("yes" if has else "no")', tip: '無向グラフの閉路はUnion-Findで「両端が既に連結な辺」を見つければ検出できる。', ins: ['3 3\n1 2\n2 3\n1 3\n', '3 2\n1 2\n2 3\n', '4 4\n1 2\n2 3\n3 4\n4 1\n', '1 0\n', '5 3\n1 2\n3 4\n4 5\n', '2 2\n1 2\n1 2\n'] })

t({ lv: 568, concept: 'グラフ: 単純パスの数え上げ(DFS)', title: 's から t への単純パスの本数', tags: ['グラフ', 'DFS'], io: '1行目に n m s t、続く m 行に有向辺 u v が与えられます(頂点数は小さめです)。', ask: 's から t へ、同じ頂点を2度通らずに行く道(単純パス)の本数を出力してください。', h1: 'DFSで今の経路上にいる頂点に印をつける。', h2: 't に着いたら1本と数え、戻るときに印を消す。', ref: 'import sys\nsys.setrecursionlimit(10000)\nfirst=input().split()\nn=int(first[0])\nm=int(first[1])\ns=int(first[2])\nt=int(first[3])\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\nused=[False]*(n+1)\ncnt=[0]\ndef dfs(x):\n    if x==t:\n        cnt[0]+=1\n        return\n    for y in g[x]:\n        if not used[y]:\n            used[y]=True\n            dfs(y)\n            used[y]=False\nused[s]=True\ndfs(s)\nprint(cnt[0])', tip: '単純パスの数え上げは訪問印を「潜るときに付け、戻るときに外す」バックトラックで行う。最短路の本数と違ってDPには畳めず、道の本数は指数的に増えうるので小さいグラフ専用の手法になる。', ins: ['4 4 1 4\n1 2\n2 4\n1 3\n3 4\n', '3 3 1 3\n1 2\n2 3\n1 3\n', '2 1 1 2\n1 2\n', '4 3 1 4\n1 2\n2 3\n3 4\n', '3 2 1 3\n1 2\n2 1\n', '5 6 1 5\n1 2\n1 3\n2 4\n3 4\n4 5\n2 5\n'] })

t({ lv: 569, concept: 'グラフ: s-t 間で必ず通る頂点', title: '通らずには行けない頂点の数', tags: ['グラフ', 'BFS'], io: '1行目に n m s t、続く m 行に無向辺 u v が与えられます(s から t へ到達できることが保証されます)。', ask: 's と t 以外の頂点のうち、その頂点を取り除くと s から t へ行けなくなるものの数を出力してください。', h1: '頂点を1つずつ通行禁止にしてBFSする。', h2: '禁止したときに t へ届かなければ、その頂点は必ず通る頂点。', ref: 'from collections import deque\nfirst=input().split()\nn=int(first[0])\nm=int(first[1])\ns=int(first[2])\nt=int(first[3])\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\ndef reach(ban):\n    seen=[False]*(n+1)\n    seen[s]=True\n    dq=deque([s])\n    while dq:\n        x=dq.popleft()\n        for y in g[x]:\n            if y!=ban and not seen[y]:\n                seen[y]=True\n                dq.append(y)\n    return seen[t]\ncnt=0\nfor v in range(1,n+1):\n    if v!=s and v!=t and not reach(v):\n        cnt+=1\nprint(cnt)', tip: '「必ず通る頂点」は1つずつ塞いで到達判定を繰り返せば素朴に求まる。関節点はグラフ全体の連結性を壊す頂点だが、こちらは s と t の間だけを見るので、関節点であっても必須とは限らない。', ins: ['4 4 1 4\n1 2\n2 4\n1 3\n3 4\n', '4 3 1 4\n1 2\n2 3\n3 4\n', '2 1 1 2\n1 2\n', '5 5 1 5\n1 2\n2 3\n3 4\n4 5\n1 3\n', '6 6 1 6\n1 2\n1 3\n2 4\n3 4\n4 5\n5 6\n', '3 3 1 3\n1 2\n2 3\n1 3\n'] })

t({ lv: 570, concept: 'グラフ: 多始点BFS最遠距離', title: '複数始点からの最遠距離', tags: ['グラフ', 'BFS'], io: '1行目に R C、続く R 行にグリッド(1=発生源、0=空)が与えられます(4近傍で毎ステップ広がる)。', ask: 'すべてのマスが埋まるまでのステップ数(最遠の0までの距離)を出力してください。0が無ければ0、埋まらない0があれば -1。', h1: '全ての1を同時にキューに入れる多始点BFS。', h2: '最後に確定した距離が答え。', ref: 'from collections import deque\nfirst=input().split()\nR=int(first[0])\nC=int(first[1])\ngrid=[list(map(int,input().split())) for _ in range(R)]\ndq=deque()\ndist=[[-1]*C for _ in range(R)]\nfresh=0\nfor i in range(R):\n    for j in range(C):\n        if grid[i][j]==1:\n            dist[i][j]=0\n            dq.append((i,j))\n        else:\n            fresh+=1\nbest=0\nwhile dq:\n    x,y=dq.popleft()\n    for dx,dy in ((1,0),(-1,0),(0,1),(0,-1)):\n        nx,ny=x+dx,y+dy\n        if 0<=nx<R and 0<=ny<C and dist[nx][ny]==-1:\n            dist[nx][ny]=dist[x][y]+1\n            best=max(best,dist[nx][ny])\n            fresh-=1\n            dq.append((nx,ny))\nprint(best if fresh==0 else -1)', tip: '多始点BFSは全始点を距離0でキューに入れるだけ。腐ったオレンジ等の同時拡散に使う。', ins: ['2 3\n1 0 0\n0 0 1\n', '1 1\n0\n', '1 1\n1\n', '2 2\n1 0\n0 0\n', '2 2\n0 0\n0 0\n', '3 3\n1 1 1\n1 1 1\n1 1 1\n'] })

t({ lv: 571, concept: 'グラフ: 単一始点の到達可能数', title: '到達可能な頂点の数(DFS)', tags: ['グラフ', 'DFS'], io: '1行目に n m s、続く m 行に有向辺 u v が与えられます。', ask: '頂点 s から有向辺をたどって到達できる頂点の数(s 自身を含む)を出力してください。', h1: 'sからDFS/BFSする。', h2: '訪問済み頂点を数える。', ref: 'first=input().split()\nn=int(first[0])\nm=int(first[1])\ns=int(first[2])\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\nseen=[False]*(n+1)\nseen[s]=True\nstack=[s]\ncnt=0\nwhile stack:\n    x=stack.pop()\n    cnt+=1\n    for y in g[x]:\n        if not seen[y]:\n            seen[y]=True\n            stack.append(y)\nprint(cnt)', tip: '到達可能集合のサイズはDFS/BFSの訪問数。スタックで非再帰DFSにできる。', ins: ['4 3 1\n1 2\n2 3\n3 4\n', '4 2 1\n1 2\n3 4\n', '1 0 1\n', '3 3 1\n1 2\n2 3\n3 1\n', '5 4 2\n1 2\n2 3\n3 4\n4 5\n', '3 1 3\n1 2\n'] })

t({ lv: 572, concept: 'グラフ: トポロジカル順序の復元', title: 'トポロジカルソート(任意の1つ)', tags: ['グラフ'], io: '1行目に n m、続く m 行に有向辺 u v(u が v より前)が与えられます(DAG)。', ask: 'トポロジカル順序を1つ、頂点番号の空白区切りで出力してください(入次数0は小さい番号から)。', h1: '入次数0をキューに入れる。', h2: '取り出して隣接の入次数を減らす。', ref: 'from collections import deque\nfirst=input().split()\nn=int(first[0])\nm=int(first[1])\ng=[[] for _ in range(n+1)]\nindeg=[0]*(n+1)\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    indeg[v]+=1\ndq=deque()\nfor i in range(1,n+1):\n    if indeg[i]==0:\n        dq.append(i)\norder=[]\nwhile dq:\n    x=dq.popleft()\n    order.append(x)\n    for y in g[x]:\n        indeg[y]-=1\n        if indeg[y]==0:\n            dq.append(y)\nprint(*order)', tip: 'カーンのアルゴリズムは入次数0を順に取り出す。普通のキューだと挿入順、ヒープだと辞書順。', ins: ['3 2\n1 2\n1 3\n', '4 3\n1 2\n2 3\n3 4\n', '3 0\n', '5 4\n1 2\n1 3\n3 4\n3 5\n', '2 1\n2 1\n', '4 2\n1 2\n3 4\n'] })

t({ lv: 573, concept: 'グラフ: 木の高さ(根付き)', title: '根付き木の高さ', tags: ['グラフ', 'BFS'], io: '1行目に n と根 r、続く n-1 行に無向辺 u v が与えられます。', ask: '根 r から最も遠い頂点までの距離(木の高さ)を出力してください。', h1: '根からBFSする。', h2: '最大距離が高さ。', ref: 'from collections import deque\nfirst=input().split()\nn=int(first[0])\nr=int(first[1])\ng=[[] for _ in range(n+1)]\nfor _ in range(n-1):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\ndist=[-1]*(n+1)\ndist[r]=0\ndq=deque([r])\nbest=0\nwhile dq:\n    x=dq.popleft()\n    for y in g[x]:\n        if dist[y]==-1:\n            dist[y]=dist[x]+1\n            best=max(best,dist[y])\n            dq.append(y)\nprint(best)', tip: '根付き木の高さは根からの最大距離。BFSでもDFSでも求まる。', ins: ['3 1\n1 2\n2 3\n', '1 1\n', '4 1\n1 2\n1 3\n1 4\n', '5 3\n1 2\n2 3\n3 4\n4 5\n', '2 2\n1 2\n', '7 1\n1 2\n1 3\n2 4\n2 5\n3 6\n3 7\n'] })

t({ lv: 574, concept: 'グラフ: 各頂点の部分木サイズ和', title: '部分木サイズの総和', tags: ['グラフ', '木'], io: '1行目に n と根 r、続く n-1 行に無向辺 u v が与えられます。', ask: '各頂点を根とする部分木のサイズを全頂点について合計した値を出力してください。', h1: '帰りがけ順で子のサイズを足す。', h2: '全頂点の size の合計を出す。', ref: 'first=input().split()\nn=int(first[0])\nr=int(first[1])\ng=[[] for _ in range(n+1)]\nfor _ in range(n-1):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\nsize=[1]*(n+1)\nparent=[0]*(n+1)\norder=[]\nseen=[False]*(n+1)\nseen[r]=True\nstack=[r]\nwhile stack:\n    x=stack.pop()\n    order.append(x)\n    for y in g[x]:\n        if not seen[y]:\n            seen[y]=True\n            parent[y]=x\n            stack.append(y)\nfor x in reversed(order):\n    if parent[x]!=0:\n        size[parent[x]]+=size[x]\nprint(sum(size[1:]))', tip: '部分木サイズは帰りがけ順(子→親)で積み上げる。総和は各頂点の深さの総和+nに等しい。', ins: ['3 1\n1 2\n2 3\n', '1 1\n', '4 1\n1 2\n1 3\n1 4\n', '5 1\n1 2\n2 3\n3 4\n4 5\n', '2 1\n1 2\n', '7 1\n1 2\n1 3\n2 4\n2 5\n3 6\n3 7\n'] })

t({ lv: 575, concept: 'グラフ: 橋を渡らない連結成分(2辺連結)', title: '2辺連結成分の数', tags: ['グラフ', 'DFS'], io: '1行目に n m、続く m 行に無向辺 u v が与えられます。', ask: '橋を取り除いたときにできる連結成分(2辺連結成分)の数を出力してください。', h1: 'まず橋を low リンクで検出する。', h2: '橋以外の辺で連結成分を数える。', ref: 'import sys\nsys.setrecursionlimit(500000)\nfirst=input().split()\nn=int(first[0])\nm=int(first[1])\ng=[[] for _ in range(n+1)]\nedges=[]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append((v,len(edges)))\n    g[v].append((u,len(edges)))\n    edges.append((u,v))\nvisited=[False]*(n+1)\ntin=[0]*(n+1)\nlow=[0]*(n+1)\ntimer=[1]\nis_bridge=[False]*len(edges)\ndef dfs(u,pe):\n    visited[u]=True\n    tin[u]=low[u]=timer[0]\n    timer[0]+=1\n    for v,ei in g[u]:\n        if ei==pe:\n            continue\n        if visited[v]:\n            low[u]=min(low[u],tin[v])\n        else:\n            dfs(v,ei)\n            low[u]=min(low[u],low[v])\n            if low[v]>tin[u]:\n                is_bridge[ei]=True\nfor i in range(1,n+1):\n    if not visited[i]:\n        dfs(i,-1)\npar=list(range(n+1))\ndef find(x):\n    while par[x]!=x:\n        par[x]=par[par[x]]\n        x=par[x]\n    return x\nfor ei,(u,v) in enumerate(edges):\n    if not is_bridge[ei]:\n        ru,rv=find(u),find(v)\n        if ru!=rv:\n            par[ru]=rv\nprint(len(set(find(i) for i in range(1,n+1))))', tip: '2辺連結成分は「橋を除いた連結成分」。橋検出(low)とUnion-Findを組み合わせる。', ins: ['3 2\n1 2\n2 3\n', '3 3\n1 2\n2 3\n1 3\n', '1 0\n', '5 5\n1 2\n2 3\n3 1\n3 4\n4 5\n', '4 4\n1 2\n2 3\n3 1\n3 4\n', '2 1\n1 2\n'] })

t({ lv: 576, concept: 'グラフ: 最短路の本数', title: '最短経路の通り数', tags: ['グラフ', 'BFS'], io: '1行目に n m s t、続く m 行に無向辺 u v が与えられます。', ask: 's から t への最短経路の本数を出力してください。到達不能なら0。', h1: 'BFSで距離と本数を同時に配る。', h2: '同じ距離で到達したら本数を足す。', ref: 'from collections import deque\nfirst=input().split()\nn=int(first[0])\nm=int(first[1])\ns=int(first[2])\nt=int(first[3])\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\ndist=[-1]*(n+1)\nways=[0]*(n+1)\ndist[s]=0\nways[s]=1\ndq=deque([s])\nwhile dq:\n    x=dq.popleft()\n    for y in g[x]:\n        if dist[y]==-1:\n            dist[y]=dist[x]+1\n            ways[y]=ways[x]\n            dq.append(y)\n        elif dist[y]==dist[x]+1:\n            ways[y]+=ways[x]\nprint(ways[t])', tip: '最短路の本数はBFSの距離確定と同時に「同じ距離で来た本数」を足し込めば数えられる。', ins: ['4 4 1 4\n1 2\n1 3\n2 4\n3 4\n', '2 1 1 2\n1 2\n', '3 2 1 3\n1 2\n2 3\n', '1 0 1 1\n', '5 5 1 5\n1 2\n1 3\n2 4\n3 4\n4 5\n', '4 2 1 4\n1 2\n3 4\n'] })

t({ lv: 577, concept: 'グラフ: 重み付き木の2点間距離', title: '木の2頂点間の重み距離', tags: ['グラフ', '木'], io: '1行目に n、続く n-1 行に重み付き無向辺 u v w、最後の行に a b が与えられます。', ask: '頂点 a から b への(木なので一意な)経路の重みの合計を出力してください。', h1: 'aからBFS/DFSで全頂点への距離を出す。', h2: 'bの距離が答え。', ref: 'from collections import deque\nn=int(input())\ng=[[] for _ in range(n+1)]\nfor _ in range(n-1):\n    u,v,w=map(int,input().split())\n    g[u].append((v,w))\n    g[v].append((u,w))\na,b=map(int,input().split())\ndist=[-1]*(n+1)\ndist[a]=0\ndq=deque([a])\nwhile dq:\n    x=dq.popleft()\n    for y,w in g[x]:\n        if dist[y]==-1:\n            dist[y]=dist[x]+w\n            dq.append(y)\nprint(dist[b])', tip: '木では2点間の経路が一意なので、片方からの単一始点探索で距離が出る。', ins: ['3\n1 2 5\n2 3 7\n1 3\n', '2\n1 2 10\n1 2\n', '4\n1 2 1\n2 3 2\n3 4 3\n1 4\n', '1\n1 1\n', '5\n1 2 2\n1 3 3\n3 4 4\n3 5 5\n4 5\n', '3\n1 2 100\n1 3 1\n2 3\n'] })

t({ lv: 578, concept: 'グラフ: フラッドフィルの領域数', title: '同色領域の数', tags: ['グラフ', 'BFS'], io: '1行目に R C、続く R 行に C 個の整数(色)が与えられます。', ask: '上下左右に同じ色がつながった領域の個数を出力してください。', h1: '未訪問マスごとにBFSで同色を塗る。', h2: '開始した回数が領域数。', ref: 'from collections import deque\nfirst=input().split()\nR=int(first[0])\nC=int(first[1])\ngrid=[list(map(int,input().split())) for _ in range(R)]\nseen=[[False]*C for _ in range(R)]\ncnt=0\nfor i in range(R):\n    for j in range(C):\n        if not seen[i][j]:\n            cnt+=1\n            col=grid[i][j]\n            seen[i][j]=True\n            dq=deque([(i,j)])\n            while dq:\n                x,y=dq.popleft()\n                for dx,dy in ((1,0),(-1,0),(0,1),(0,-1)):\n                    nx,ny=x+dx,y+dy\n                    if 0<=nx<R and 0<=ny<C and not seen[nx][ny] and grid[nx][ny]==col:\n                        seen[nx][ny]=True\n                        dq.append((nx,ny))\nprint(cnt)', tip: 'フラッドフィルは未訪問マスから同色をBFS/DFSで塗りつぶす。塗り始めた回数が領域数。', ins: ['2 2\n1 1\n2 2\n', '1 1\n5\n', '2 2\n1 2\n3 4\n', '3 3\n1 1 1\n1 1 1\n1 1 1\n', '2 3\n1 1 2\n2 1 1\n', '3 3\n1 2 1\n2 1 2\n1 2 1\n'] })

t({ lv: 579, concept: 'グラフ: 偶数長で到達できるか', title: '偶数歩で到達できるか', tags: ['グラフ', 'BFS'], io: '1行目に n m s t、続く m 行に無向辺 u v が与えられます。', ask: 's から t へ偶数本の辺を使って到達できるなら yes、できないなら no を出力してください(同じ辺の往復も可)。', h1: '(頂点, 偶奇)を状態にBFS。', h2: '(t, 偶) に到達できれば yes。', ref: 'from collections import deque\nfirst=input().split()\nn=int(first[0])\nm=int(first[1])\ns=int(first[2])\nt=int(first[3])\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\nseen=[[False,False] for _ in range(n+1)]\nseen[s][0]=True\ndq=deque([(s,0)])\nwhile dq:\n    x,p=dq.popleft()\n    for y in g[x]:\n        np=p^1\n        if not seen[y][np]:\n            seen[y][np]=True\n            dq.append((y,np))\nprint("yes" if seen[t][0] else "no")', tip: '歩数の偶奇を頂点に付け足した「拡張グラフ」上でBFSすれば、パリティ付き到達判定ができる。', ins: ['4 4 1 4\n1 2\n2 3\n3 4\n4 1\n', '3 2 1 3\n1 2\n2 3\n', '2 1 1 2\n1 2\n', '1 0 1 1\n', '5 4 1 5\n1 2\n2 3\n3 4\n4 5\n', '3 3 1 1\n1 2\n2 3\n1 3\n'] })

t({ lv: 580, concept: 'グラフ: 重み最小の経路上の最大辺', title: '経路の最大辺を最小化(ミニマックス)', tags: ['グラフ', 'ヒープ'], io: '1行目に n m s t、続く m 行に無向辺 u v w が与えられます。', ask: 's から t への経路で「使う辺の最大重み」を最小化した値を出力してください。到達不能なら -1。', h1: 'ダイクストラ風に「経路上の最大辺」を距離とする。', h2: '緩和は max(現在の最大辺, 辺重み)。', ref: 'import heapq\nfirst=input().split()\nn=int(first[0])\nm=int(first[1])\ns=int(first[2])\nt=int(first[3])\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v,w=map(int,input().split())\n    g[u].append((v,w))\n    g[v].append((u,w))\nINF=float("inf")\nbest=[INF]*(n+1)\nbest[s]=0\npq=[(0,s)]\nwhile pq:\n    d,x=heapq.heappop(pq)\n    if d>best[x]:\n        continue\n    for y,w in g[x]:\n        nd=max(d,w)\n        if nd<best[y]:\n            best[y]=nd\n            heapq.heappush(pq,(nd,y))\nprint(best[t] if best[t]<INF else -1)', tip: 'ミニマックス経路は緩和を「和」でなく「max」にしたダイクストラで解ける(最小全域木上の経路にも一致)。', ins: ['4 4 1 4\n1 2 3\n2 4 1\n1 3 1\n3 4 4\n', '2 1 1 2\n1 2 7\n', '3 2 1 3\n1 2 5\n2 3 2\n', '1 0 1 1\n', '5 6 1 5\n1 2 10\n2 5 10\n1 3 2\n3 4 2\n4 5 2\n1 5 100\n', '3 1 1 3\n1 2 4\n'] })

t({ lv: 581, concept: 'グラフ: 経路上の最小容量を最大化', title: '最大ボトルネック経路', tags: ['グラフ', 'ヒープ'], io: '1行目に n m s t、続く m 行に無向辺 u v c(容量)が与えられます。', ask: 's から t への経路で「使う辺の最小容量」を最大化した値を出力してください。到達不能なら -1。', h1: '最大ヒープで「経路上の最小容量」を距離にする。', h2: '緩和は min(現在の最小容量, 辺容量)。', ref: 'import heapq\nfirst=input().split()\nn=int(first[0])\nm=int(first[1])\ns=int(first[2])\nt=int(first[3])\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v,c=map(int,input().split())\n    g[u].append((v,c))\n    g[v].append((u,c))\nbest=[-1]*(n+1)\nbest[s]=float("inf")\npq=[(-best[s],s)]\nwhile pq:\n    nd,x=heapq.heappop(pq)\n    d=-nd\n    if d<best[x]:\n        continue\n    for y,c in g[x]:\n        nc=min(d,c)\n        if nc>best[y]:\n            best[y]=nc\n            heapq.heappush(pq,(-nc,y))\nans=best[t]\nprint(ans if ans!=-1 and ans!=float("inf") else -1)', tip: '最大ボトルネック経路は「min容量を最大化」。最大ヒープ＋min緩和のダイクストラ変形で解ける。', ins: ['4 4 1 4\n1 2 3\n2 4 5\n1 3 4\n3 4 4\n', '2 1 1 2\n1 2 7\n', '3 2 1 3\n1 2 2\n2 3 5\n', '2 0 1 2\n', '5 5 1 5\n1 2 10\n2 5 1\n1 3 5\n3 4 5\n4 5 5\n', '3 1 1 3\n1 2 4\n'] })

t({ lv: 582, concept: 'グラフ: K個先までの到達頂点数', title: 'Kステップ以内に到達できる頂点数', tags: ['グラフ', 'BFS'], io: '1行目に n m s K、続く m 行に無向辺 u v が与えられます。', ask: 's から K 本以内の辺で到達できる頂点の数(s 自身を含む)を出力してください。', h1: 'BFSで距離を求める。', h2: '距離が K 以下の頂点を数える。', ref: 'from collections import deque\nfirst=input().split()\nn=int(first[0])\nm=int(first[1])\ns=int(first[2])\nK=int(first[3])\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\ndist=[-1]*(n+1)\ndist[s]=0\ndq=deque([s])\nwhile dq:\n    x=dq.popleft()\n    if dist[x]==K:\n        continue\n    for y in g[x]:\n        if dist[y]==-1:\n            dist[y]=dist[x]+1\n            dq.append(y)\ncnt=sum(1 for i in range(1,n+1) if dist[i]!=-1 and dist[i]<=K)\nprint(cnt)', tip: '距離制限付き到達数はBFSで距離を測り、Kを超えたら展開を打ち切る。', ins: ['5 4 1 2\n1 2\n2 3\n3 4\n4 5\n', '5 4 1 1\n1 2\n2 3\n3 4\n4 5\n', '4 4 1 1\n1 2\n1 3\n1 4\n2 3\n', '1 0 1 5\n', '3 2 2 1\n1 2\n2 3\n', '6 5 1 2\n1 2\n2 3\n3 4\n4 5\n5 6\n'] })

t({ lv: 583, concept: 'グラフ: 重み付きグリッド最短コスト', title: 'コスト付きグリッドの最短コスト', tags: ['グラフ', 'ヒープ'], io: '1行目に R C、続く R 行に C 個の通行コスト(正整数)が与えられます。', ask: '左上から右下へ4方向に進み、入った各マスのコストを足した最小合計(始点も含む)を出力してください。', h1: 'ダイクストラでマスを頂点にする。', h2: '隣接マスへの距離 = 現在 + そのマスのコスト。', ref: 'import heapq\nfirst=input().split()\nR=int(first[0])\nC=int(first[1])\ngrid=[list(map(int,input().split())) for _ in range(R)]\nINF=float("inf")\ndist=[[INF]*C for _ in range(R)]\ndist[0][0]=grid[0][0]\npq=[(grid[0][0],0,0)]\nwhile pq:\n    d,x,y=heapq.heappop(pq)\n    if d>dist[x][y]:\n        continue\n    for dx,dy in ((1,0),(-1,0),(0,1),(0,-1)):\n        nx,ny=x+dx,y+dy\n        if 0<=nx<R and 0<=ny<C:\n            nd=d+grid[nx][ny]\n            if nd<dist[nx][ny]:\n                dist[nx][ny]=nd\n                heapq.heappush(pq,(nd,nx,ny))\nprint(dist[R-1][C-1])', tip: 'コスト付きグリッドはマスを頂点としたダイクストラ。4方向移動なので戻る経路も考慮できる。', ins: ['2 2\n1 2\n3 4\n', '1 1\n5\n', '3 3\n1 3 1\n1 5 1\n4 2 1\n', '1 4\n1 2 3 4\n', '2 3\n1 2 3\n4 5 6\n', '3 3\n1 1 1\n9 9 1\n1 1 1\n'] })

t({ lv: 584, concept: 'グラフ: 距離が等しい頂点の数', title: '2点から等距離の頂点数', tags: ['グラフ', 'BFS'], io: '1行目に n m a b、続く m 行に無向辺 u v が与えられます。', ask: 'a からの距離と b からの距離が等しい頂点の数を出力してください(両方から到達可能な頂点のみ)。', h1: 'a と b からそれぞれBFSする。', h2: '両方到達可能かつ距離が等しい頂点を数える。', ref: 'from collections import deque\nfirst=input().split()\nn=int(first[0])\nm=int(first[1])\na=int(first[2])\nb=int(first[3])\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\ndef bfs(s):\n    dist=[-1]*(n+1)\n    dist[s]=0\n    dq=deque([s])\n    while dq:\n        x=dq.popleft()\n        for y in g[x]:\n            if dist[y]==-1:\n                dist[y]=dist[x]+1\n                dq.append(y)\n    return dist\nda=bfs(a)\ndb=bfs(b)\ncnt=0\nfor i in range(1,n+1):\n    if da[i]!=-1 and db[i]!=-1 and da[i]==db[i]:\n        cnt+=1\nprint(cnt)', tip: '2始点BFSの距離配列を比べるだけ。垂直二等分線にあたる頂点集合が求まる。', ins: ['4 4 1 3\n1 2\n2 3\n3 4\n4 1\n', '3 2 1 3\n1 2\n2 3\n', '5 4 1 5\n1 2\n2 3\n3 4\n4 5\n', '1 0 1 1\n', '4 3 1 4\n1 2\n2 3\n3 4\n', '5 6 1 5\n1 2\n2 5\n1 3\n3 5\n1 4\n4 5\n'] })

t({ lv: 585, concept: 'グラフ: 重み付き有向の最遠点', title: '始点から最も遠い頂点の距離', tags: ['グラフ', 'ヒープ'], io: '1行目に n m s、続く m 行に有向辺 u v w(w>=0)が与えられます。', ask: 's から到達できる頂点のうち、最短距離が最大の値を出力してください(s のみなら0)。', h1: 'ダイクストラで全頂点の最短距離を出す。', h2: '到達可能な距離の最大を取る。', ref: 'import heapq\nfirst=input().split()\nn=int(first[0])\nm=int(first[1])\ns=int(first[2])\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v,w=map(int,input().split())\n    g[u].append((v,w))\nINF=float("inf")\ndist=[INF]*(n+1)\ndist[s]=0\npq=[(0,s)]\nwhile pq:\n    d,x=heapq.heappop(pq)\n    if d>dist[x]:\n        continue\n    for y,w in g[x]:\n        if d+w<dist[y]:\n            dist[y]=d+w\n            heapq.heappush(pq,(dist[y],y))\nbest=0\nfor i in range(1,n+1):\n    if dist[i]<INF and dist[i]>best:\n        best=dist[i]\nprint(best)', tip: '「信号が全頂点に届く時間」型の問題。ダイクストラ後の最大最短距離が答え。', ins: ['4 4 1\n1 2 1\n2 3 1\n3 4 1\n1 4 10\n', '2 1 1\n1 2 5\n', '1 0 1\n', '3 2 1\n1 2 3\n2 3 4\n', '4 3 2\n1 2 1\n2 3 2\n3 4 3\n', '5 5 1\n1 2 2\n1 3 4\n3 5 1\n2 4 7\n4 5 1\n'] })

t({ lv: 586, concept: 'グラフ: 強制経由の最短路', title: '指定点を経由する最短距離', tags: ['グラフ', 'ヒープ'], io: '1行目に n m s t k、続く m 行に無向辺 u v w が与えられます。', ask: 's から必ず k を通って t へ行く最短距離を出力してください。到達不能なら -1。', h1: 's→k と k→t を別々にダイクストラ。', h2: '両方到達可能なら和が答え。', ref: 'import heapq\nfirst=input().split()\nn=int(first[0])\nm=int(first[1])\ns=int(first[2])\nt=int(first[3])\nk=int(first[4])\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v,w=map(int,input().split())\n    g[u].append((v,w))\n    g[v].append((u,w))\nINF=float("inf")\ndef dijkstra(src):\n    dist=[INF]*(n+1)\n    dist[src]=0\n    pq=[(0,src)]\n    while pq:\n        d,x=heapq.heappop(pq)\n        if d>dist[x]:\n            continue\n        for y,w in g[x]:\n            if d+w<dist[y]:\n                dist[y]=d+w\n                heapq.heappush(pq,(dist[y],y))\n    return dist\nds=dijkstra(s)\ndk=dijkstra(k)\nif ds[k]<INF and dk[t]<INF:\n    print(ds[k]+dk[t])\nelse:\n    print(-1)', tip: '経由点つき最短路は s→経由点 と 経由点→t に分けて足す。経由点からの探索は無向なら1回で済む。', ins: ['4 4 1 4 2\n1 2 1\n2 4 1\n1 3 1\n3 4 1\n', '3 2 1 3 2\n1 2 2\n2 3 3\n', '2 1 1 2 1\n1 2 5\n', '4 3 1 4 3\n1 2 1\n2 3 1\n3 4 1\n', '3 1 1 3 2\n1 2 4\n', '5 5 1 5 3\n1 2 1\n2 3 1\n3 4 1\n4 5 1\n1 3 5\n'] })

t({ lv: 587, concept: '木: 根からの経路に現れる色の種類数', title: '根から辿って出会う色の最大種類数', tags: ['グラフ', '木', 'DFS'], io: '1行目に n、2行目に n 個の色番号(頂点1から n の順)、続く n-1 行に無向辺 u v が与えられます。', ask: '頂点1を根としたとき、根からその頂点までの経路に現れる相異なる色の数を各頂点について求め、その最大値を出力してください。', h1: '色ごとの出現回数を辞書で持ちながら根からDFSする。', h2: '潜るときに+1して0から1になったら種類数を増やし、戻るときに-1して0になったら減らす。', ref: 'import sys\nsys.setrecursionlimit(500000)\nn=int(input())\ncol=list(map(int,input().split()))\ng=[[] for _ in range(n+1)]\nfor _ in range(n-1):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\ncnt={}\nstate=[0,0]\ndef dfs(x,p):\n    c=col[x-1]\n    cnt[c]=cnt.get(c,0)+1\n    if cnt[c]==1:\n        state[0]+=1\n    if state[0]>state[1]:\n        state[1]=state[0]\n    for y in g[x]:\n        if y!=p:\n            dfs(y,x)\n    cnt[c]-=1\n    if cnt[c]==0:\n        state[0]-=1\ndfs(1,0)\nprint(state[1])', tip: '根からその頂点までの経路はDFSのスタックそのものなので、出現回数を潜るときに増やし戻るときに減らすだけで経路上の色集合を保てる。部分木の情報を集める木DPとは向きが逆で、こちらは根から葉へ流す情報になる。', ins: ['5\n1 2 2 3 1\n1 2\n2 3\n3 4\n1 5\n', '1\n7\n', '4\n1 1 1 1\n1 2\n2 3\n3 4\n', '4\n1 2 3 4\n1 2\n2 3\n3 4\n', '6\n1 2 1 3 2 3\n1 2\n1 3\n2 4\n2 5\n3 6\n', '3\n5 5 6\n1 2\n1 3\n'] })

t({ lv: 588, concept: 'グラフ: 二部グラフの片側サイズ', title: '2彩色した片側の頂点数', tags: ['グラフ', 'BFS'], io: '1行目に n m、続く m 行に無向辺 u v が与えられます(連結とは限らない2部グラフ)。', ask: '各連結成分を2色に塗り、成分ごとに「多い側の色の頂点数」を足した合計を出力してください(2部でない成分があれば -1)。', h1: '成分ごとにBFSで2色塗り。', h2: '色0と色1の数の多い方を足す。', ref: 'from collections import deque\nfirst=input().split()\nn=int(first[0])\nm=int(first[1])\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\ncolor=[-1]*(n+1)\nok=True\ntotal=0\nfor s in range(1,n+1):\n    if color[s]==-1:\n        color[s]=0\n        cnt=[1,0]\n        dq=deque([s])\n        while dq:\n            x=dq.popleft()\n            for y in g[x]:\n                if color[y]==-1:\n                    color[y]=color[x]^1\n                    cnt[color[y]]+=1\n                    dq.append(y)\n                elif color[y]==color[x]:\n                    ok=False\n        total+=max(cnt)\nprint(total if ok else -1)', tip: '連結成分ごとに2色塗り、多い側を足すと「最大の独立集合(2部グラフ)」の下界が得られる。', ins: ['4 4\n1 2\n2 3\n3 4\n4 1\n', '3 3\n1 2\n2 3\n1 3\n', '2 1\n1 2\n', '1 0\n', '6 3\n1 2\n3 4\n5 6\n', '5 4\n1 2\n2 3\n3 4\n4 5\n'] })

t({ lv: 589, concept: 'グラフ: 入次数0と出次数0の数', title: '源点と井戸の数', tags: ['グラフ'], io: '1行目に n m、続く m 行に有向辺 u v が与えられます。', ask: '入次数0の頂点(源点)の数と出次数0の頂点(井戸)の数を、空白区切りで出力してください。', h1: '入次数・出次数を数える。', h2: 'それぞれ0の頂点を数える。', ref: 'first=input().split()\nn=int(first[0])\nm=int(first[1])\nindeg=[0]*(n+1)\noutdeg=[0]*(n+1)\nfor _ in range(m):\n    u,v=map(int,input().split())\n    outdeg[u]+=1\n    indeg[v]+=1\nsrc=sum(1 for i in range(1,n+1) if indeg[i]==0)\nsink=sum(1 for i in range(1,n+1) if outdeg[i]==0)\nprint(src,sink)', tip: '源点(入次数0)と井戸(出次数0)はDAGのトポロジカル構造の端点。次数を数えるだけで分かる。', ins: ['3 2\n1 2\n2 3\n', '3 0\n', '4 4\n1 2\n2 3\n3 4\n4 1\n', '1 0\n', '5 4\n1 2\n1 3\n4 5\n4 2\n', '2 1\n1 2\n'] })

t({ lv: 590, concept: 'グラフ: 最短路で使われない辺数', title: '最短路木に含まれない辺の数', tags: ['グラフ', 'ヒープ'], io: '1行目に n m s、続く m 行に無向辺 u v w(w>=0、連結)が与えられます。', ask: 's を根とする最短路を成すのに「絶対に不要」な辺(両端の最短距離の差が辺重みに一致しない辺)の数を出力してください。', h1: 'sからダイクストラで全最短距離を出す。', h2: '|dist[u]-dist[v]| != w の辺を数える。', ref: 'import heapq\nfirst=input().split()\nn=int(first[0])\nm=int(first[1])\ns=int(first[2])\nedges=[]\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v,w=map(int,input().split())\n    g[u].append((v,w))\n    g[v].append((u,w))\n    edges.append((u,v,w))\nINF=float("inf")\ndist=[INF]*(n+1)\ndist[s]=0\npq=[(0,s)]\nwhile pq:\n    d,x=heapq.heappop(pq)\n    if d>dist[x]:\n        continue\n    for y,w in g[x]:\n        if d+w<dist[y]:\n            dist[y]=d+w\n            heapq.heappush(pq,(dist[y],y))\ncnt=0\nfor u,v,w in edges:\n    if abs(dist[u]-dist[v])!=w:\n        cnt+=1\nprint(cnt)', tip: '辺(u,v,w)が何らかの最短路に乗るのは |dist[u]-dist[v]|=w のとき。そうでなければ最短路に不要。', ins: ['4 4 1\n1 2 1\n2 4 1\n1 3 1\n3 4 1\n', '2 1 1\n1 2 5\n', '3 3 1\n1 2 1\n2 3 1\n1 3 1\n', '3 3 1\n1 2 1\n2 3 1\n1 3 5\n', '1 0 1\n', '4 4 1\n1 2 1\n2 3 1\n3 4 1\n1 4 1\n'] })

t({ lv: 591, concept: '貪欲: 最大の数を作る並べ替え', title: '連結して最大の数', tags: ['貪欲', 'ソート'], io: '非負整数の列が1行で与えられます。', ask: 'それらを並べ替えて連結したときにできる最大の数(文字列)を出力してください。', h1: '2数 a,b は a+b と b+a を比べる。', h2: '連結文字列が大きい順に並べる。', ref: 'import functools\na=input().split()\ndef cmp(x,y):\n    if x+y>y+x:\n        return -1\n    elif x+y<y+x:\n        return 1\n    return 0\na.sort(key=functools.cmp_to_key(cmp))\nres="".join(a)\nres=res.lstrip("0")\nprint(res if res else "0")', tip: '最大連結数は「a+b と b+a」を比較する比較ソートが鍵。辞書順ソートでは不正解。', ins: ['3 30 34 5 9\n', '10 2\n', '0 0\n', '1\n', '432 43 43\n', '12 121\n'] })

t({ lv: 592, concept: '貪欲: 連続部分の最大平均(固定長)', title: '長さkの最大和の窓', tags: ['貪欲'], io: '1行目に k、2行目に整数列が与えられます。', ask: '長さ k の連続部分配列の和の最大値を出力してください。', h1: '最初の k 個の和を作る。', h2: '窓をずらしながら端を足し引きする。', ref: 'k=int(input())\na=list(map(int,input().split()))\nn=len(a)\ncur=sum(a[:k])\nbest=cur\nfor i in range(k,n):\n    cur+=a[i]-a[i-k]\n    if cur>best:\n        best=cur\nprint(best)', tip: '固定長の最大和はスライディングウィンドウ。端を足して反対端を引くだけで O(n)。', ins: ['2\n1 2 3 4\n', '1\n5 1 9 3\n', '3\n-1 -2 -3\n', '3\n1 1 1 1 1\n', '2\n5 -1 5 -1\n', '4\n1 2 3 4\n'] })

t({ lv: 593, concept: 'グラフ: 重みつき木の直径の端点距離', title: '木の最遠点までの距離', tags: ['グラフ', '木'], io: '1行目に n s、続く n-1 行に重み付き無向辺 u v w が与えられます。', ask: '頂点 s から最も遠い頂点までの距離を出力してください。', h1: 'sからBFS/DFSで距離を配る。', h2: '最大距離を取る。', ref: 'from collections import deque\nfirst=input().split()\nn=int(first[0])\ns=int(first[1])\ng=[[] for _ in range(n+1)]\nfor _ in range(n-1):\n    u,v,w=map(int,input().split())\n    g[u].append((v,w))\n    g[v].append((u,w))\ndist=[-1]*(n+1)\ndist[s]=0\ndq=deque([s])\nbest=0\nwhile dq:\n    x=dq.popleft()\n    for y,w in g[x]:\n        if dist[y]==-1:\n            dist[y]=dist[x]+w\n            best=max(best,dist[y])\n            dq.append(y)\nprint(best)', tip: '木の直径を2回BFSで求める際の「1回目」。任意点からの最遠点は直径の端点になる。', ins: ['3 1\n1 2 5\n2 3 7\n', '1 1\n', '4 1\n1 2 1\n1 3 2\n1 4 3\n', '5 3\n1 2 1\n2 3 1\n3 4 1\n4 5 1\n', '2 2\n1 2 10\n', '4 2\n1 2 2\n2 3 3\n3 4 4\n'] })

t({ lv: 594, concept: 'グラフ: 経路上の頂点重みの最大和(DAG)', title: 'DAG上の最大重み経路', tags: ['グラフ', 'dp'], io: '1行目に n m、2行目に n 個の頂点重み、続く m 行に有向辺 u v が与えられます(DAG)。', ask: '任意の頂点から始め有向辺をたどる経路で、訪れた頂点重みの合計の最大値を出力してください。', h1: 'トポロジカル順序で後ろからDP。', h2: 'dp[v]=重み[v]+max(子のdp)。', ref: 'from collections import deque\nfirst=input().split()\nn=int(first[0])\nm=int(first[1])\nw=list(map(int,input().split()))\ng=[[] for _ in range(n+1)]\nindeg=[0]*(n+1)\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    indeg[v]+=1\ndq=deque(i for i in range(1,n+1) if indeg[i]==0)\norder=[]\nwhile dq:\n    x=dq.popleft()\n    order.append(x)\n    for y in g[x]:\n        indeg[y]-=1\n        if indeg[y]==0:\n            dq.append(y)\ndp=[0]*(n+1)\nfor x in reversed(order):\n    base=w[x-1]\n    add=0\n    for y in g[x]:\n        if dp[y]>add:\n            add=dp[y]\n    dp[x]=base+add\nprint(max(dp[1:]))', tip: 'DAGの最長(最大重み)経路はトポロジカル順序で1回スキャンするDPで解ける。', ins: ['4 3\n1 2 3 4\n1 2\n2 3\n3 4\n', '3 0\n5 1 9\n', '4 4\n1 1 1 1\n1 2\n1 3\n2 4\n3 4\n', '1 0\n7\n', '5 4\n2 3 1 4 1\n1 2\n2 3\n1 4\n4 5\n', '3 2\n10 20 5\n1 2\n1 3\n'] })

t({ lv: 595, concept: '貪欲: 重複なく覆う最小区間数', title: '点を覆う最小の固定長区間数', tags: ['貪欲'], io: '1行目に区間の長さ L、2行目に座標上の点の列が与えられます。', ask: 'すべての点を覆うのに必要な、長さ L の閉区間(始点は自由)の最小個数を出力してください。', h1: '点をソートする。', h2: '未覆の最小点に左端を合わせ、L先まで覆う。', ref: 'L=int(input())\npts=sorted(map(int,input().split()))\ncnt=0\ni=0\nn=len(pts)\nwhile i<n:\n    cnt+=1\n    start=pts[i]\n    while i<n and pts[i]<=start+L:\n        i+=1\nprint(cnt)', tip: '固定長区間での被覆は「最小の未覆点に左端を合わせる」貪欲が最適。', ins: ['2\n1 2 3 5 6\n', '0\n1 1 1\n', '5\n1 2 3 4 5\n', '1\n1 3 5 7\n', '3\n10\n', '4\n1 2 7 8 9\n'] })

t({ lv: 596, concept: 'グラフ: 重み無し全点対の最大距離', title: 'グラフの直径(重みなし)', tags: ['グラフ', 'BFS'], io: '1行目に n m、続く m 行に無向辺 u v が与えられます(連結)。', ask: '全頂点ペアの最短距離(辺数)の最大値(直径)を出力してください。', h1: '各頂点からBFSする。', h2: '得られた最短距離の最大を取る。', ref: 'from collections import deque\nfirst=input().split()\nn=int(first[0])\nm=int(first[1])\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\ndef bfs(s):\n    dist=[-1]*(n+1)\n    dist[s]=0\n    dq=deque([s])\n    mx=0\n    while dq:\n        x=dq.popleft()\n        for y in g[x]:\n            if dist[y]==-1:\n                dist[y]=dist[x]+1\n                mx=max(mx,dist[y])\n                dq.append(y)\n    return mx\nbest=0\nfor s in range(1,n+1):\n    best=max(best,bfs(s))\nprint(best)', tip: '一般グラフの直径は全頂点からBFSして最大の最短距離を取る(木なら2回BFSで十分)。', ins: ['4 3\n1 2\n2 3\n3 4\n', '3 3\n1 2\n2 3\n1 3\n', '1 0\n', '5 4\n1 2\n2 3\n3 4\n4 5\n', '4 4\n1 2\n2 3\n3 4\n4 1\n', '2 1\n1 2\n'] })

t({ lv: 597, concept: 'グラフ: 重み付き経路数(最短)の最小頂点', title: '最短経路の中で頂点数が最小の値', tags: ['グラフ', 'ヒープ'], io: '1行目に n m s t、続く m 行に有向辺 u v w が与えられます。', ask: 's から t への最短距離を達成する経路のうち、通る頂点数(辺数+1)の最小値を出力してください。到達不能なら -1。', h1: '(距離, 辺数) を辞書順最小にする。', h2: 'ダイクストラで距離が同じなら辺数を最小化。', ref: 'import heapq\nfirst=input().split()\nn=int(first[0])\nm=int(first[1])\ns=int(first[2])\nt=int(first[3])\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v,w=map(int,input().split())\n    g[u].append((v,w))\nINF=float("inf")\ndist=[INF]*(n+1)\nhops=[INF]*(n+1)\ndist[s]=0\nhops[s]=0\npq=[(0,0,s)]\nwhile pq:\n    d,h,x=heapq.heappop(pq)\n    if d>dist[x] or (d==dist[x] and h>hops[x]):\n        continue\n    for y,w in g[x]:\n        nd=d+w\n        nh=h+1\n        if nd<dist[y] or (nd==dist[y] and nh<hops[y]):\n            dist[y]=nd\n            hops[y]=nh\n            heapq.heappush(pq,(nd,nh,y))\nprint(hops[t]+1 if dist[t]<INF else -1)', tip: '同距離での副目的(辺数最小)は (距離, 辺数) のタプルを比較するダイクストラで同時最適化できる。', ins: ['4 4 1 4\n1 2 1\n2 4 2\n1 3 3\n3 4 0\n', '2 1 1 2\n1 2 5\n', '3 3 1 3\n1 2 1\n2 3 1\n1 3 2\n', '1 0 1 1\n', '4 4 1 4\n1 2 1\n2 3 1\n3 4 1\n1 4 3\n', '3 1 1 3\n1 2 4\n'] })

t({ lv: 598, concept: '貪欲: 最小の辞書順になる隣接交換', title: 'k回の隣接交換で辞書順最小', tags: ['貪欲'], io: '1行目に数列(空白区切り)、2行目に許される隣接交換回数 k が与えられます。', ask: '高々 k 回の隣接交換で得られる辞書順最小の数列を空白区切りで出力してください。', h1: '各位置で、k 以内に届く範囲の最小要素を前に持ってくる。', h2: '移動コスト(距離)を k から引く。', ref: 'a=list(map(int,input().split()))\nk=int(input())\nn=len(a)\ni=0\nwhile i<n and k>0:\n    best=i\n    for j in range(i+1,min(n,i+k+1)):\n        if a[j]<a[best]:\n            best=j\n    for j in range(best,i,-1):\n        a[j],a[j-1]=a[j-1],a[j]\n    k-=(best-i)\n    i+=1\nprint(*a)', tip: '隣接交換での辞書順最小は「k歩以内の最小値を前に運ぶ」貪欲。バブルソートの部分適用。', ins: ['4 2 3 1\n2\n', '1 2 3\n5\n', '3 2 1\n1\n', '5 4 3 2 1\n10\n', '2 1\n0\n', '7 6 5 4\n3\n'] })

t({ lv: 599, concept: 'グラフ: 最短路の辺集合サイズ', title: '最短路DAGの辺数', tags: ['グラフ', 'ヒープ'], io: '1行目に n m s、続く m 行に有向辺 u v w(w>=0)が与えられます。', ask: 'いずれかの最短路に使われ得る辺(dist[u]+w==dist[v] を満たす辺)の数を出力してください。', h1: 'sからダイクストラ。', h2: 'dist[u]+w==dist[v] の有向辺を数える。', ref: 'import heapq\nfirst=input().split()\nn=int(first[0])\nm=int(first[1])\ns=int(first[2])\nedges=[]\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v,w=map(int,input().split())\n    g[u].append((v,w))\n    edges.append((u,v,w))\nINF=float("inf")\ndist=[INF]*(n+1)\ndist[s]=0\npq=[(0,s)]\nwhile pq:\n    d,x=heapq.heappop(pq)\n    if d>dist[x]:\n        continue\n    for y,w in g[x]:\n        if d+w<dist[y]:\n            dist[y]=d+w\n            heapq.heappush(pq,(dist[y],y))\ncnt=0\nfor u,v,w in edges:\n    if dist[u]<INF and dist[u]+w==dist[v]:\n        cnt+=1\nprint(cnt)', tip: '最短路DAGの辺は dist[u]+w==dist[v] を満たす有向辺。最短路の数え上げや復元の土台。', ins: ['4 4 1\n1 2 1\n2 4 1\n1 3 1\n3 4 1\n', '2 1 1\n1 2 5\n', '3 3 1\n1 2 1\n2 3 1\n1 3 2\n', '1 0 1\n', '4 4 1\n1 2 1\n1 2 2\n2 3 1\n3 4 1\n', '3 2 1\n1 2 1\n2 3 1\n'] })

export const CATALOG = TASKS
