// 生成タスク 第34波：lv421〜450。最上級帯の踏み段。
// ゲーム理論/高度数論/文字列構造/2-SAT/木DP/行列木定理/シュタイナー木 など。
// 再帰は prereq 土台外なので使用可。重複なし・決定的・採点一意。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 421, concept: 'ゲーム: Nimの勝敗', title: 'Nimの必勝判定', tags: ['ゲーム'], io: '各山の石の数の列が1行で与えられます。2人が交互に1つの山から1個以上取り、取れなくなった方が負けです。', ask: '先手必勝なら First、後手必勝なら Second を出力してください。', h1: '各山のXOR (ニム和) を取る。', h2: 'XORが0でなければ先手必勝。', ref: 'a=list(map(int,input().split()))\nx=0\nfor v in a:\n    x^=v\nprint("First" if x!=0 else "Second")', tip: 'Nimの必勝条件は山のサイズのXORが非ゼロ (Sprague-Grundyの原点)。', ins: ['1 2 3\n', '1 2 4\n', '5\n', '0 0\n', '3 3\n', '1 1 1\n'] })

t({ lv: 422, concept: 'ゲーム: 石取りゲームのGrundy数', title: '1からk個取る石取りの勝敗', tags: ['ゲーム'], io: 'n k が空白区切りで与えられます。1つの山 n から交互に 1〜k 個取り、取れなくなった方が負けです。', ask: '先手必勝なら First、後手必勝なら Second を出力してください。', h1: 'Grundy数は n mod (k+1)。', h2: '0でなければ先手必勝。', ref: 'n,k=map(int,input().split())\nprint("First" if n%(k+1)!=0 else "Second")', tip: '「1〜k個取る」ゲームの必勝条件は周期 k+1 の余りで決まる。', ins: ['10 3\n', '4 3\n', '0 5\n', '7 7\n', '12 3\n', '1 1\n'] })

t({ lv: 423, concept: 'ゲーム: 部分集合取りのMex必勝', title: '取れる個数が指定された石取り', tags: ['ゲーム'], io: '1行目に石の数 n と取れる個数の種類 m、2行目に取れる個数の集合 (m 個) が与えられます。1つの山から交互に取り、取れなくなった方が負けです。', ask: '先手必勝なら First、後手必勝なら Second を出力してください。', h1: '各 i の Grundy数を mex で計算。', h2: '到達可能な Grundy数に無い最小の非負整数が mex。', ref: 'line=input().split()\nn=int(line[0])\nm=int(line[1])\nS=list(map(int,input().split()))\ngrundy=[0]*(n+1)\nfor i in range(1,n+1):\n    reach=set()\n    for s in S:\n        if s<=i:\n            reach.add(grundy[i-s])\n    g=0\n    while g in reach:\n        g+=1\n    grundy[i]=g\nprint("First" if grundy[n]!=0 else "Second")', tip: 'Grundy数は「遷移先のGrundy値の mex」。0が後手必勝局面。', ins: ['10 2\n1 2\n', '4 1\n2\n', '6 2\n2 3\n', '0 1\n1\n', '7 3\n1 3 4\n', '5 1\n1\n'] })

t({ lv: 424, concept: '数論: ミラーラビン素数判定', title: '大きな数の素数判定', tags: ['数論'], io: '整数 n (>=2) が1行で与えられます。', ask: 'n が素数なら yes、合成数なら no を出力してください。', h1: 'n-1 を 2^r·d に分解する。', h2: '固定した底で強擬素数テストを行う (決定的判定)。', ref: 'n=int(input())\ndef is_prime(n):\n    if n<2:\n        return False\n    for p in [2,3,5,7,11,13,17,19,23,29,31,37]:\n        if n%p==0:\n            return n==p\n    d=n-1\n    r=0\n    while d%2==0:\n        d//=2\n        r+=1\n    for a in [2,3,5,7,11,13,17,19,23,29,31,37]:\n        x=pow(a,d,n)\n        if x==1 or x==n-1:\n            continue\n        ok=False\n        for _ in range(r-1):\n            x=x*x%n\n            if x==n-1:\n                ok=True\n                break\n        if not ok:\n            return False\n    return True\nprint("yes" if is_prime(n) else "no")', tip: '少数の固定底でミラーラビンは巨大な範囲まで決定的に判定できる。', ins: ['7\n', '561\n', '1000000007\n', '4\n', '2\n', '1000003\n'] })

t({ lv: 425, concept: '数論: ポラードのρ素因数分解', title: '大きな数の最大の素因数', tags: ['数論'], io: '整数 n (>=2) が1行で与えられます。', ask: 'n の最大の素因数を出力してください。', h1: 'ミラーラビンで素数判定。', h2: '合成数はポラードρで分割して再帰的に分解。', ref: 'import math\ndef is_prime(n):\n    if n<2:\n        return False\n    for p in [2,3,5,7,11,13,17,19,23,29,31,37]:\n        if n%p==0:\n            return n==p\n    d=n-1\n    r=0\n    while d%2==0:\n        d//=2\n        r+=1\n    for a in [2,3,5,7,11,13,17,19,23,29,31,37]:\n        x=pow(a,d,n)\n        if x==1 or x==n-1:\n            continue\n        ok=False\n        for _ in range(r-1):\n            x=x*x%n\n            if x==n-1:\n                ok=True\n                break\n        if not ok:\n            return False\n    return True\ndef pollard(n):\n    if n%2==0:\n        return 2\n    x=2\n    y=2\n    c=1\n    while True:\n        x=(x*x+c)%n\n        y=(y*y+c)%n\n        y=(y*y+c)%n\n        d=math.gcd(abs(x-y),n)\n        if d!=1:\n            if d==n:\n                c+=1\n                x=2\n                y=2\n                continue\n            return d\nstack=[int(input())]\nbest=1\nwhile stack:\n    v=stack.pop()\n    if v==1:\n        continue\n    if is_prime(v):\n        if v>best:\n            best=v\n        continue\n    d=pollard(v)\n    stack.append(d)\n    stack.append(v//d)\nprint(best)', tip: 'ポラードρはO(n^(1/4))程度で巨大な合成数を分割できる確率的手法。', ins: ['12\n', '13\n', '100\n', '1000000007\n', '999999999999\n', '2\n'] })

t({ lv: 426, concept: '数論: リュカの定理', title: '大きなnの二項係数 mod 素数', tags: ['数論'], io: 'n k p が空白区切りで与えられます (p は素数、n は大きくてよい)。', ask: 'C(n,k) を p で割った余りを出力してください。', h1: 'n,k を p 進法で各桁に分解。', h2: '各桁の小さな二項係数の積 (リュカの定理)。', ref: 'n,k,p=map(int,input().split())\ndef comb_mod(n,k,p):\n    if k<0 or k>n:\n        return 0\n    num=1\n    den=1\n    for i in range(k):\n        num=num*((n-i)%p)%p\n        den=den*((i+1)%p)%p\n    return num*pow(den,p-2,p)%p\nres=1\nwhile n>0 or k>0:\n    ni=n%p\n    ki=k%p\n    if ki>ni:\n        res=0\n        break\n    res=res*comb_mod(ni,ki,p)%p\n    n//=p\n    k//=p\nprint(res)', tip: 'リュカの定理は二項係数 mod 素数を p 進の各桁の積に分解する。', ins: ['1000000 500000 13\n', '5 2 7\n', '10 3 5\n', '7 3 11\n', '4 4 5\n', '6 0 7\n'] })

t({ lv: 427, concept: '数論: 最小の原始根', title: '素数の最小原始根', tags: ['数論'], io: '素数 p が1行で与えられます。', ask: 'p の最小の原始根 (位数が p-1 となる最小の数) を出力してください。', h1: 'p-1 を素因数分解する。', h2: '各素因数 f について g^((p-1)/f)≠1 なら原始根。', ref: 'p=int(input())\nif p==2:\n    print(1)\nelse:\n    n=p-1\n    factors=[]\n    m=n\n    d=2\n    while d*d<=m:\n        if m%d==0:\n            factors.append(d)\n            while m%d==0:\n                m//=d\n        d+=1\n    if m>1:\n        factors.append(m)\n    g=2\n    while True:\n        ok=True\n        for f in factors:\n            if pow(g,n//f,p)==1:\n                ok=False\n                break\n        if ok:\n            print(g)\n            break\n        g+=1', tip: '原始根は乗法群の生成元。位数が p-1 になるかを素因数で確認する。', ins: ['7\n', '2\n', '5\n', '11\n', '13\n', '23\n'] })

t({ lv: 428, concept: '数論: 離散対数(BSGS)', title: '離散対数を求める', tags: ['数論'], io: 'a b p が空白区切りで与えられます (p は素数)。', ask: 'a^x ≡ b (mod p) を満たす最小の非負整数 x を出力してください。無ければ -1 を出力してください。', h1: 'x=im-j と分け、ベビーステップを辞書に貯める。', h2: 'ジャイアントステップで一致を探す (BSGS)。', ref: 'import math\na,b,p=map(int,input().split())\na%=p\nb%=p\nif p==1:\n    print(0)\nelse:\n    m=int(math.isqrt(p))+1\n    table={}\n    cur=b%p\n    for j in range(m+1):\n        table[cur]=j\n        cur=cur*a%p\n    am=pow(a,m,p)\n    found=-1\n    cur=1\n    for i in range(1,m+1):\n        cur=cur*am%p\n        if cur in table:\n            x=i*m-table[cur]\n            if x>=0:\n                found=x\n                break\n    print(found)', tip: 'BSGS は離散対数を O(√p) に落とす「分割して表引き」の典型。', ins: ['2 1 5\n', '3 4 7\n', '2 3 5\n', '5 2 7\n', '2 0 5\n', '3 1 7\n'] })

t({ lv: 429, concept: '文字列: 接尾辞配列', title: '接尾辞配列の構築', tags: ['文字列'], io: '文字列 s が1行で与えられます。', ask: 's の全接尾辞を辞書順に並べたときの、各接尾辞の開始位置 (0始まり) を空白区切りで出力してください。', h1: '各開始位置の接尾辞をキーにソート。', h2: 'sorted の key に s[i:] を使う。', ref: 's=input()\nn=len(s)\nsa=sorted(range(n),key=lambda i:s[i:])\nprint(*sa)', tip: '接尾辞配列は文字列検索・反復・LCPなど多くの高速アルゴリズムの土台。', ins: ['banana\n', 'abc\n', 'aaa\n', 'a\n', 'abab\n', 'cba\n'] })

t({ lv: 430, concept: '文字列: LCP配列の和', title: '隣接接尾辞の共通接頭辞の総和', tags: ['文字列'], io: '文字列 s が1行で与えられます。', ask: '接尾辞配列順で隣り合う接尾辞どうしの最長共通接頭辞の長さを求め、その総和を出力してください。', h1: '接尾辞配列を作る。', h2: '隣接ペアの共通接頭辞長を足す。', ref: 's=input()\nn=len(s)\nif n<=1:\n    print(0)\nelse:\n    sa=sorted(range(n),key=lambda i:s[i:])\n    total=0\n    for k in range(1,n):\n        i=sa[k-1]\n        j=sa[k]\n        l=0\n        while i+l<n and j+l<n and s[i+l]==s[j+l]:\n            l+=1\n        total+=l\n    print(total)', tip: 'LCP配列の総和は「異なる部分文字列の数」などの計算に直結する。', ins: ['banana\n', 'abc\n', 'aaaa\n', 'abab\n', 'a\n', 'abcabc\n'] })

t({ lv: 431, concept: '文字列: 複数パターンの出現総数', title: '複数パターンの総出現回数', tags: ['文字列'], io: '1行目に本文、2行目にパターン数 k、3行目に k 個のパターン (空白区切り) が与えられます (k=0 のときは3行目はありません)。', ask: 'すべてのパターンの本文中での出現回数 (重なり可) の総和を出力してください。', h1: 'パターンからトライを作り、失敗リンクを張る (Aho-Corasick)。', h2: '本文を1回走査し、各位置で出力リンクを辿った数を加える。', ref: 'from collections import deque\ntext=input()\nk=int(input())\npatterns=input().split() if k>0 else []\ngoto=[{}]\nout=[0]\nfail=[0]\nfor p in patterns:\n    node=0\n    for ch in p:\n        if ch not in goto[node]:\n            goto.append({})\n            out.append(0)\n            fail.append(0)\n            goto[node][ch]=len(goto)-1\n        node=goto[node][ch]\n    out[node]+=1\ndq=deque()\nfor ch in goto[0]:\n    v=goto[0][ch]\n    fail[v]=0\n    dq.append(v)\nwhile dq:\n    u=dq.popleft()\n    for ch in goto[u]:\n        v=goto[u][ch]\n        f=fail[u]\n        while f!=0 and ch not in goto[f]:\n            f=fail[f]\n        if ch in goto[f] and goto[f][ch]!=v:\n            fail[v]=goto[f][ch]\n        else:\n            fail[v]=0\n        out[v]+=out[fail[v]]\n        dq.append(v)\nnode=0\ntotal=0\nfor ch in text:\n    while node!=0 and ch not in goto[node]:\n        node=fail[node]\n    if ch in goto[node]:\n        node=goto[node][ch]\n    else:\n        node=0\n    total+=out[node]\nprint(total)', tip: 'Aho-Corasick は多数パターンの同時検索を本文1回の走査で行う。', ins: ['ahishers\n3\nhe she hers\n', 'aaaa\n1\naa\n', 'abc\n2\nd e\n', 'xyz\n1\nxyz\n', 'aaa\n2\na aa\n', 'test\n0\n'] })

t({ lv: 432, concept: 'グラフ: オイラー閉路の存在', title: 'オイラー閉路が存在するか', tags: ['グラフ', 'BFS'], io: '1行目に n m、続く m 行に無向辺 u v が与えられます。', ask: 'すべての辺をちょうど1回ずつ通って出発点に戻る閉路 (オイラー閉路) が存在するなら yes、なければ no を出力してください。', h1: '辺を持つ頂点が連結であること。', h2: 'すべての頂点の次数が偶数であること。', ref: 'from collections import deque\nn,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\ndeg=[0]*(n+1)\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\n    deg[u]+=1\n    deg[v]+=1\nstart=-1\nfor i in range(1,n+1):\n    if deg[i]>0:\n        start=i\n        break\nconnected=True\nif start!=-1:\n    seen=[False]*(n+1)\n    seen[start]=True\n    dq=deque([start])\n    while dq:\n        x=dq.popleft()\n        for y in g[x]:\n            if not seen[y]:\n                seen[y]=True\n                dq.append(y)\n    for i in range(1,n+1):\n        if deg[i]>0 and not seen[i]:\n            connected=False\nalleven=all(deg[i]%2==0 for i in range(1,n+1))\nprint("yes" if connected and alleven else "no")', tip: 'オイラー閉路の条件は「連結 ＋ 全頂点が偶数次数」。経路 (0か2が奇数) との違いに注意。', ins: ['3 3\n1 2\n2 3\n1 3\n', '4 3\n1 2\n2 3\n3 4\n', '4 4\n1 2\n2 3\n3 4\n4 1\n', '5 3\n1 2\n3 4\n4 5\n', '1 0\n', '5 6\n1 2\n2 3\n3 1\n3 4\n4 5\n5 3\n'] })

t({ lv: 433, concept: 'グラフ: 2-SATの充足可能性', title: '2-SATが充足可能か', tags: ['グラフ'], io: '1行目に変数数 n と節数 m、続く m 行にリテラル a b (±i、節は (a∨b)) が与えられます。', ask: 'すべての節を満たす真偽割り当てが存在するなら yes、なければ no を出力してください。', h1: '含意グラフを作り強連結成分に分解する。', h2: '同じ変数の真と偽が同一成分なら不可能。', ref: 'import sys\nsys.setrecursionlimit(500000)\nn,m=map(int,input().split())\nN=2*n\ng=[[] for _ in range(N)]\ndef node(lit):\n    i=abs(lit)-1\n    return 2*i if lit>0 else 2*i+1\nfor _ in range(m):\n    a,b=map(int,input().split())\n    g[node(-a)].append(node(b))\n    g[node(-b)].append(node(a))\nrg=[[] for _ in range(N)]\nfor u in range(N):\n    for v in g[u]:\n        rg[v].append(u)\nvisited=[False]*N\norder=[]\nfor s in range(N):\n    if not visited[s]:\n        stack=[(s,0)]\n        visited[s]=True\n        while stack:\n            nd,idx=stack.pop()\n            if idx<len(g[nd]):\n                stack.append((nd,idx+1))\n                nx=g[nd][idx]\n                if not visited[nx]:\n                    visited[nx]=True\n                    stack.append((nx,0))\n            else:\n                order.append(nd)\ncomp=[-1]*N\nc=0\nfor s in reversed(order):\n    if comp[s]==-1:\n        stack=[s]\n        comp[s]=c\n        while stack:\n            x=stack.pop()\n            for y in rg[x]:\n                if comp[y]==-1:\n                    comp[y]=c\n                    stack.append(y)\n        c+=1\nok=True\nfor i in range(n):\n    if comp[2*i]==comp[2*i+1]:\n        ok=False\n        break\nprint("yes" if ok else "no")', tip: '2-SATは含意グラフのSCCに帰着する (xと¬xが同じ成分なら矛盾)。', ins: ['2 2\n1 2\n-1 -2\n', '1 2\n1 1\n-1 -1\n', '3 3\n1 2\n2 3\n-1 -3\n', '1 1\n1 1\n', '2 4\n1 2\n1 -2\n-1 2\n-1 -2\n', '2 1\n-1 -2\n'] })

t({ lv: 434, concept: 'bitDP: 部分集合和(SOS)', title: '部分集合についての総和の最大', tags: ['bitDP'], io: '1行目に n、2行目に 2^n 個の値 f[0..2^n-1] が与えられます。', ask: '各 mask について「mask の部分集合 sub すべての f[sub] の総和」を G[mask] とし、G の最大値を出力してください。', h1: 'ビットごとに「そのビットを含む mask へ含まない側を足す」。', h2: 'これを n ビット繰り返す (Sum over Subsets DP)。', ref: 'n=int(input())\nf=list(map(int,input().split()))\nF=f[:]\nfor i in range(n):\n    for mask in range(1<<n):\n        if (mask>>i)&1:\n            F[mask]+=F[mask^(1<<i)]\nprint(max(F))', tip: 'SOS DP は全部分集合の集計を O(n·2^n) で行う (各ビットを独立に処理)。', ins: ['2\n1 2 3 4\n', '1\n5 7\n', '2\n0 0 0 0\n', '2\n-1 -1 -1 -1\n', '3\n1 1 1 1 1 1 1 1\n', '1\n10 0\n'] })

t({ lv: 435, concept: 'DP: 非減少にする最小コスト', title: '非減少列にする最小変更コスト', tags: ['dp'], io: '整数列が1行で与えられます。', ask: '各要素を任意の整数に増減して非減少列にするとき、変更量の絶対値の総和の最小値を出力してください。', h1: '最適値は元の値のどれかになる。', h2: 'dp[j]=末尾を vals[j] にする最小コスト、前方最小で繋ぐ。', ref: 'a=list(map(int,input().split()))\nvals=sorted(set(a))\nL=len(vals)\ndp=[abs(a[0]-v) for v in vals]\nfor i in range(1,len(a)):\n    for j in range(1,L):\n        if dp[j-1]<dp[j]:\n            dp[j]=dp[j-1]\n    ndp=[dp[j]+abs(a[i]-vals[j]) for j in range(L)]\n    dp=ndp\nprint(min(dp))', tip: 'L1の単調回帰。候補値を元の値に絞ると O(n²) のDPで解ける。', ins: ['3 2 1\n', '1 2 3\n', '5 4 3 2 1\n', '1\n', '2 1 2\n', '3 1 4 1 5\n'] })

t({ lv: 436, concept: '区間DP: 印刷の最小回数', title: '重ね塗りの最小回数', tags: ['区間DP', 'dp'], io: '文字列 s が1行で与えられます。一度に連続した同じ文字の範囲を印刷でき、上から重ね塗りできます。', ask: 's を作るのに必要な最小の印刷回数を出力してください。', h1: '連続する重複文字をまず1つに潰す。', h2: '区間DPで「右端と同じ文字を一緒に塗る」分を節約。', ref: 's=input()\nn=len(s)\nif n==0:\n    print(0)\nelse:\n    tlist=[]\n    for ch in s:\n        if not tlist or tlist[-1]!=ch:\n            tlist.append(ch)\n    s=tlist\n    n=len(s)\n    dp=[[0]*n for _ in range(n)]\n    for i in range(n):\n        dp[i][i]=1\n    for length in range(2,n+1):\n        for i in range(n-length+1):\n            j=i+length-1\n            best=dp[i][j-1]+1\n            for k in range(i,j):\n                if s[k]==s[j]:\n                    cand=dp[i][k]+(dp[k+1][j-1] if k+1<=j-1 else 0)\n                    if cand<best:\n                        best=cand\n            dp[i][j]=best\n    print(dp[0][n-1])', tip: '同じ文字をまとめて塗れる区間DP。右端と一致する位置で結合する。', ins: ['aaabbb\n', 'aba\n', 'abc\n', 'a\n', 'aabacba\n', 'abcba\n'] })

t({ lv: 437, concept: 'DP: 価値V以上の最小重さ', title: '価値V以上を満たす最小重さ', tags: ['dp'], io: '1行目に n V、続く n 行に重さ w と価値 v が与えられます。', ask: '価値の合計が V 以上になる選び方の中で、重さの合計の最小値を出力してください。不可能なら -1 を出力してください。', h1: '価値を添字、重さを最小化するナップサック。', h2: 'dp[value]=その価値を作る最小重さ。', ref: 'n,V=map(int,input().split())\nitems=[tuple(map(int,input().split())) for _ in range(n)]\nINF=float("inf")\nmaxv=sum(v for w,v in items)\ndp=[INF]*(maxv+1)\ndp[0]=0\nfor w,v in items:\n    for val in range(maxv,v-1,-1):\n        if dp[val-v]+w<dp[val]:\n            dp[val]=dp[val-v]+w\nbest=INF\nfor val in range(maxv+1):\n    if val>=V and dp[val]<best:\n        best=dp[val]\nprint(best if best<INF else -1)', tip: '価値が大きく重さが小さいときは「価値を添字にする」双対ナップサックが有効。', ins: ['3 5\n2 3\n3 4\n4 5\n', '1 10\n1 5\n', '2 0\n5 1\n3 1\n', '3 6\n1 2\n1 2\n1 2\n', '2 3\n10 3\n1 1\n', '1 5\n2 5\n'] })

t({ lv: 438, concept: '木DP: 最小頂点被覆', title: '木の最小頂点被覆', tags: ['木', 'dp'], io: '1行目に頂点数 n、続く n-1 行に木の無向辺 u v が与えられます。', ask: 'すべての辺の少なくとも一端を選ぶように頂点を選ぶとき、選ぶ頂点数の最小値を出力してください。', h1: '各頂点で「選ぶ/選ばない」の2状態。', h2: '選ばないなら子は全て選ぶ必要がある。', ref: 'n=int(input())\ng=[[] for _ in range(n+1)]\nfor _ in range(n-1):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\nparent=[0]*(n+1)\norder=[]\nseen=[False]*(n+1)\nseen[1]=True\nstack=[1]\nwhile stack:\n    x=stack.pop()\n    order.append(x)\n    for y in g[x]:\n        if not seen[y]:\n            seen[y]=True\n            parent[y]=x\n            stack.append(y)\ninc=[1]*(n+1)\nexc=[0]*(n+1)\nfor x in reversed(order):\n    for y in g[x]:\n        if y!=parent[x]:\n            inc[x]+=min(inc[y],exc[y])\n            exc[x]+=inc[y]\nprint(min(inc[1],exc[1]))', tip: '木の最小頂点被覆は2状態の木DP。選ばない頂点の子は必ず選ぶ。', ins: ['3\n1 2\n2 3\n', '1\n', '4\n1 2\n1 3\n1 4\n', '5\n1 2\n2 3\n3 4\n4 5\n', '2\n1 2\n', '7\n1 2\n1 3\n2 4\n2 5\n3 6\n3 7\n'] })

t({ lv: 439, concept: '木DP: 最小支配集合', title: '木の最小支配集合', tags: ['木', 'dp'], io: '1行目に頂点数 n、続く n-1 行に木の無向辺 u v が与えられます。', ask: '選んだ頂点とその隣接で全頂点を覆う (支配する) とき、選ぶ頂点数の最小値を出力してください。', h1: '「集合に入る/子に支配される/まだ支配されない」の3状態。', h2: 'まだ支配されない状態は親が集合に入る前提。', ref: 'n=int(input())\ng=[[] for _ in range(n+1)]\nfor _ in range(n-1):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\nparent=[0]*(n+1)\norder=[]\nseen=[False]*(n+1)\nseen[1]=True\nstack=[1]\nwhile stack:\n    x=stack.pop()\n    order.append(x)\n    for y in g[x]:\n        if not seen[y]:\n            seen[y]=True\n            parent[y]=x\n            stack.append(y)\nINF=float("inf")\ndp=[[0,0,0] for _ in range(n+1)]\nfor x in reversed(order):\n    children=[y for y in g[x] if y!=parent[x]]\n    s0=1\n    for y in children:\n        s0+=min(dp[y][0],dp[y][1],dp[y][2])\n    s2=0\n    for y in children:\n        s2+=min(dp[y][0],dp[y][1])\n    if not children:\n        s1=INF\n    else:\n        base=0\n        for y in children:\n            base+=min(dp[y][0],dp[y][1])\n        s1=INF\n        for y in children:\n            cand=base-min(dp[y][0],dp[y][1])+dp[y][0]\n            if cand<s1:\n                s1=cand\n    dp[x][0]=s0\n    dp[x][1]=s1\n    dp[x][2]=s2\nprint(min(dp[1][0],dp[1][1]))', tip: '支配集合の木DPは3状態 (入る/子に支配/未支配) を区別するのが要点。', ins: ['3\n1 2\n2 3\n', '1\n', '4\n1 2\n1 3\n1 4\n', '5\n1 2\n2 3\n3 4\n4 5\n', '2\n1 2\n', '7\n1 2\n1 3\n2 4\n2 5\n3 6\n3 7\n'] })

t({ lv: 440, concept: '幾何: 最近点対の距離の2乗', title: '最も近い2点の距離の2乗', tags: ['幾何'], io: '1行目に点数 n (>=2)、続く n 行に点 x y が与えられます。', ask: '最も近い2点のユークリッド距離の2乗を出力してください。', h1: '全ペアの距離の2乗を比べる。', h2: '2乗のまま比較すれば平方根の誤差を避けられる。', ref: 'n=int(input())\npts=[tuple(map(int,input().split())) for _ in range(n)]\nbest=float("inf")\nfor i in range(n):\n    for j in range(i+1,n):\n        d=(pts[i][0]-pts[j][0])**2+(pts[i][1]-pts[j][1])**2\n        if d<best:\n            best=d\nprint(best)', tip: '距離は2乗のまま比較すると整数演算で済み、誤差も出ない。', ins: ['3\n0 0\n3 4\n1 1\n', '2\n0 0\n5 0\n', '4\n0 0\n0 1\n1 0\n1 1\n', '2\n1 1\n1 1\n', '5\n0 0\n10 10\n1 0\n0 1\n5 5\n', '3\n0 0\n100 0\n50 1\n'] })

t({ lv: 441, concept: '幾何: 最遠点対の距離の2乗', title: '最も遠い2点の距離の2乗', tags: ['幾何'], io: '1行目に点数 n、続く n 行に点 x y が与えられます。', ask: '最も遠い2点のユークリッド距離の2乗を出力してください (点が1個なら0)。', h1: '全ペアの距離の2乗を比べる。', h2: '最大を取る (本質的には凸包上の点対)。', ref: 'n=int(input())\npts=[tuple(map(int,input().split())) for _ in range(n)]\nbest=0\nfor i in range(n):\n    for j in range(i+1,n):\n        d=(pts[i][0]-pts[j][0])**2+(pts[i][1]-pts[j][1])**2\n        if d>best:\n            best=d\nprint(best)', tip: '最遠点対 (直径) は必ず凸包の頂点間に現れる。回転キャリパスでO(n)化できる。', ins: ['3\n0 0\n3 4\n1 1\n', '2\n0 0\n5 0\n', '4\n0 0\n0 1\n1 0\n1 1\n', '1\n5 5\n', '5\n0 0\n10 0\n0 10\n10 10\n5 5\n', '3\n0 0\n1 0\n2 0\n'] })

t({ lv: 442, concept: '幾何: 非退化三角形の数', title: '同一直線上にない3点の組の数', tags: ['幾何'], io: '1行目に点数 n、続く n 行に点 x y が与えられます。', ask: '3点が同一直線上にない (面積が正の三角形をなす) 組の個数を出力してください。', h1: '3点の外積が0でなければ非退化。', h2: '全3つ組を調べる。', ref: 'n=int(input())\npts=[tuple(map(int,input().split())) for _ in range(n)]\ncnt=0\nfor i in range(n):\n    for j in range(i+1,n):\n        for k in range(j+1,n):\n            ax,ay=pts[i]\n            bx,by=pts[j]\n            cx,cy=pts[k]\n            cross=(bx-ax)*(cy-ay)-(by-ay)*(cx-ax)\n            if cross!=0:\n                cnt+=1\nprint(cnt)', tip: '面積0 (外積0) は退化三角形。3点の向き付けで判定する。', ins: ['4\n0 0\n1 0\n0 1\n1 1\n', '3\n0 0\n1 1\n2 2\n', '3\n0 0\n1 0\n0 1\n', '5\n0 0\n1 0\n2 0\n0 1\n0 2\n', '4\n0 0\n1 0\n2 0\n3 0\n', '2\n0 0\n1 1\n'] })

t({ lv: 443, concept: '数論: √nの連分数の周期', title: '平方根の連分数の周期', tags: ['数論'], io: '整数 n (>=1) が1行で与えられます。', ask: '√n の連分数展開の周期の長さを出力してください (n が平方数なら0)。', h1: '(m,d,a) の三つ組を更新していく標準アルゴリズム。', h2: 'a が 2·a0 に戻るまでが1周期。', ref: 'import math\nn=int(input())\na0=math.isqrt(n)\nif a0*a0==n:\n    print(0)\nelse:\n    m=0\n    d=1\n    a=a0\n    period=0\n    while a!=2*a0:\n        m=d*a-m\n        d=(n-m*m)//d\n        a=(a0+m)//d\n        period+=1\n    print(period)', tip: '√n の連分数は必ず周期的で、末項が 2a0 になる (ペル方程式に直結)。', ins: ['2\n', '3\n', '4\n', '7\n', '23\n', '13\n'] })

t({ lv: 444, concept: '数論: ペル方程式の最小解', title: 'ペル方程式の基本解', tags: ['数論'], io: '平方数でない整数 n (>=2) が1行で与えられます。', ask: 'x²−n·y²=1 を満たす最小の正の x を出力してください。', h1: '√n の連分数の収束分数を順に作る。', h2: 'x²−n·y²=1 を満たした分子が答え。', ref: 'import math\nn=int(input())\na0=math.isqrt(n)\nif a0*a0==n:\n    print(0)\nelse:\n    m=0\n    d=1\n    a=a0\n    num1=1\n    num=a0\n    den1=0\n    den=1\n    while num*num-n*den*den!=1:\n        m=d*a-m\n        d=(n-m*m)//d\n        a=(a0+m)//d\n        num2=a*num+num1\n        num1=num\n        num=num2\n        den2=a*den+den1\n        den1=den\n        den=den2\n    print(num)', tip: 'ペル方程式の基本解は √n の連分数の収束分数の中に現れる。', ins: ['2\n', '3\n', '5\n', '7\n', '13\n', '6\n'] })

t({ lv: 445, concept: '数論: 平方剰余の根(Tonelli)', title: '法素数での平方根', tags: ['数論'], io: 'a p が空白区切りで与えられます (p は素数)。', ask: 'x²≡a (mod p) を満たす x (0<=x<p) が存在すれば最小のものを、無ければ -1 を出力してください。', h1: 'ルジャンドル記号で平方剰余か判定。', h2: 'トネリ・シャンクス法で平方根を構成。', ref: 'a,p=map(int,input().split())\na%=p\ndef legendre(a,p):\n    return pow(a,(p-1)//2,p)\nif a==0:\n    print(0)\nelif p==2:\n    print(a%2)\nelif legendre(a,p)!=1:\n    print(-1)\nelse:\n    q=p-1\n    s=0\n    while q%2==0:\n        q//=2\n        s+=1\n    if s==1:\n        r=pow(a,(p+1)//4,p)\n    else:\n        z=2\n        while legendre(z,p)!=p-1:\n            z+=1\n        m=s\n        c=pow(z,q,p)\n        tt=pow(a,q,p)\n        r=pow(a,(q+1)//2,p)\n        while tt!=1:\n            i=0\n            temp=tt\n            while temp!=1:\n                temp=temp*temp%p\n                i+=1\n            b=pow(c,1<<(m-i-1),p)\n            r=r*b%p\n            c=b*b%p\n            tt=tt*c%p\n            m=i\n    r=min(r,p-r)\n    print(r)', tip: 'トネリ・シャンクス法は法素数での平方根を効率よく構成する。', ins: ['2 7\n', '3 11\n', '5 7\n', '0 5\n', '4 7\n', '10 13\n'] })

t({ lv: 446, concept: '文字列: 長さLの辞書順最小部分文字列', title: '長さLの辞書順最小の連続部分文字列', tags: ['文字列'], io: '1行目に文字列 s と整数 L (L<=|s|) が空白区切りで与えられます。', ask: '長さ L の連続部分文字列のうち辞書順で最小のものを出力してください。', h1: '各開始位置の長さ L の部分文字列を比べる。', h2: '最小を更新する。', ref: 'line=input().split()\ns=line[0]\nL=int(line[1])\nbest=s[:L]\nfor i in range(1,len(s)-L+1):\n    cand=s[i:i+L]\n    if cand<best:\n        best=cand\nprint(best)', tip: '長さ固定の最小部分文字列。大規模では接尾辞配列で高速化できる。', ins: ['banana 3\n', 'abcabc 2\n', 'zzza 1\n', 'a 1\n', 'cba 2\n', 'dcba 3\n'] })

t({ lv: 447, concept: 'データ構造: 区間GCD', title: '更新つき区間GCD (セグメント木)', tags: ['データ構造'], io: '1行目に n q、2行目に n 個の値、続く q 行に "upd i x" または "gcd l r" が与えられます。', ask: 'すべての "gcd" の結果の合計を出力してください。', h1: 'セグメント木の集約を gcd にする。', h2: 'gcd(0,x)=x なので単位元は0。', ref: 'import math\nn,q=map(int,input().split())\na=list(map(int,input().split()))\nsize=1\nwhile size<n:\n    size*=2\ntree=[0]*(2*size)\nfor i in range(n):\n    tree[size+i]=a[i]\nfor i in range(size-1,0,-1):\n    tree[i]=math.gcd(tree[2*i],tree[2*i+1])\ndef update(pos,val):\n    pos+=size\n    tree[pos]=val\n    pos//=2\n    while pos>=1:\n        tree[pos]=math.gcd(tree[2*pos],tree[2*pos+1])\n        pos//=2\ndef query(l,r):\n    l+=size\n    r+=size+1\n    res=0\n    while l<r:\n        if l&1:\n            res=math.gcd(res,tree[l])\n            l+=1\n        if r&1:\n            r-=1\n            res=math.gcd(res,tree[r])\n        l//=2\n        r//=2\n    return res\ntotal=0\nfor _ in range(q):\n    op=input().split()\n    if op[0]=="upd":\n        update(int(op[1]),int(op[2]))\n    else:\n        total+=query(int(op[1]),int(op[2]))\nprint(total)', tip: 'gcd は結合的で単位元0を持つので、そのままセグ木に載る。', ins: ['5 2\n2 4 6 8 10\ngcd 0 4\ngcd 1 2\n', '3 1\n6 9 15\ngcd 0 2\n', '1 1\n7\ngcd 0 0\n', '4 2\n12 8 6 4\nupd 0 5\ngcd 0 3\n', '5 1\n10 20 30 40 50\ngcd 0 4\n', '4 2\n6 12 18 24\ngcd 0 1\ngcd 2 3\n'] })

t({ lv: 448, concept: 'データ構造: BIT上の二分探索', title: 'k番目に小さい値 (BIT二分探索)', tags: ['データ構造'], io: '1行目に値域 maxv とクエリ数 q、続く q 行に "add x" (値 x を1個追加) または "kth k" (現在 k 番目に小さい値を求める) が与えられます。', ask: 'すべての "kth" の結果の合計を出力してください。', h1: '値の出現数を BIT で管理する。', h2: 'BIT 上を上位ビットから降りて k 番目を探す。', ref: 'mx,q=map(int,input().split())\nLOG=mx.bit_length()\nbit=[0]*(mx+1)\ndef add(i,v):\n    while i<=mx:\n        bit[i]+=v\n        i+=i&(-i)\ndef kth(k):\n    pos=0\n    rem=k\n    pw=1<<LOG\n    while pw>0:\n        nxt=pos+pw\n        if nxt<=mx and bit[nxt]<rem:\n            pos=nxt\n            rem-=bit[nxt]\n        pw>>=1\n    return pos+1\ntotal=0\nfor _ in range(q):\n    op=input().split()\n    if op[0]=="add":\n        add(int(op[1]),1)\n    else:\n        total+=kth(int(op[1]))\nprint(total)', tip: 'BIT上を上位ビットから降りると順位検索が O(log) でできる。', ins: ['10 4\nadd 5\nadd 3\nkth 1\nkth 2\n', '5 3\nadd 1\nadd 2\nkth 2\n', '10 2\nadd 7\nkth 1\n', '100 3\nadd 50\nadd 50\nkth 2\n', '5 4\nadd 1\nadd 3\nadd 5\nkth 3\n', '10 2\nadd 10\nkth 1\n'] })

t({ lv: 449, concept: 'グラフ: 全域木の数(行列木定理)', title: '全域木の数', tags: ['グラフ'], io: '1行目に n m、続く m 行に無向辺 u v が与えられます。', ask: 'グラフの全域木の総数を出力してください。', h1: 'ラプラシアン行列の1行1列を除いた小行列式 (キルヒホッフの定理)。', h2: '整数のままバライス法で行列式を計算する。', ref: 'n,m=map(int,input().split())\nL=[[0]*n for _ in range(n)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    u-=1\n    v-=1\n    L[u][u]+=1\n    L[v][v]+=1\n    L[u][v]-=1\n    L[v][u]-=1\nif n==1:\n    print(1)\nelse:\n    sz=n-1\n    M=[row[:sz] for row in L[:sz]]\n    sign=1\n    prev=1\n    singular=False\n    for i in range(sz):\n        if M[i][i]==0:\n            sw=-1\n            for r in range(i+1,sz):\n                if M[r][i]!=0:\n                    sw=r\n                    break\n            if sw==-1:\n                singular=True\n                break\n            M[i],M[sw]=M[sw],M[i]\n            sign=-sign\n        for r in range(i+1,sz):\n            for c in range(i+1,sz):\n                M[r][c]=(M[r][c]*M[i][i]-M[r][i]*M[i][c])//prev\n        prev=M[i][i]\n    if singular:\n        print(0)\n    else:\n        print(sign*M[sz-1][sz-1])', tip: 'キルヒホッフの定理: 全域木の数＝ラプラシアン余因子の行列式。', ins: ['3 3\n1 2\n2 3\n1 3\n', '4 4\n1 2\n2 3\n3 4\n4 1\n', '2 1\n1 2\n', '1 0\n', '4 6\n1 2\n1 3\n1 4\n2 3\n2 4\n3 4\n', '3 2\n1 2\n2 3\n'] })

t({ lv: 450, concept: 'bitDP: シュタイナー木の最小重み', title: '指定端点を結ぶ最小重みの木', tags: ['bitDP', 'グラフ'], io: '1行目に n m k、続く m 行に無向辺 u v w、最後の行に k 個の端点 (ターミナル) が与えられます。', ask: 'すべての端点を連結にする部分木 (シュタイナー木) の重みの最小値を出力してください。', h1: 'dp[端点集合][頂点] を持つ。', h2: '部分集合の合体と、辺による緩和 (ダイクストラ) を交互に行う。', ref: 'import heapq\nfirst=input().split()\nn=int(first[0])\nm=int(first[1])\nk=int(first[2])\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v,w=map(int,input().split())\n    g[u].append((v,w))\n    g[v].append((u,w))\nterminals=list(map(int,input().split()))\nINF=float("inf")\ndp=[[INF]*(n+1) for _ in range(1<<k)]\nfor i in range(k):\n    dp[1<<i][terminals[i]]=0\nfor mask in range(1,1<<k):\n    sub=(mask-1)&mask\n    while sub>0:\n        other=mask^sub\n        for v in range(1,n+1):\n            if dp[sub][v]<INF and dp[other][v]<INF and dp[sub][v]+dp[other][v]<dp[mask][v]:\n                dp[mask][v]=dp[sub][v]+dp[other][v]\n        sub=(sub-1)&mask\n    pq=[]\n    for v in range(1,n+1):\n        if dp[mask][v]<INF:\n            heapq.heappush(pq,(dp[mask][v],v))\n    while pq:\n        d,v=heapq.heappop(pq)\n        if d>dp[mask][v]:\n            continue\n        for to,w in g[v]:\n            if d+w<dp[mask][to]:\n                dp[mask][to]=d+w\n                heapq.heappush(pq,(dp[mask][to],to))\nfull=(1<<k)-1\nprint(min(dp[full][v] for v in range(1,n+1)))', tip: 'シュタイナー木は「端点集合×頂点」のbitDP＋ダイクストラで最小重みを求める。', ins: ['4 4 2\n1 2 1\n2 3 1\n3 4 1\n1 4 1\n1 3\n', '2 1 2\n1 2 5\n1 2\n', '3 3 3\n1 2 1\n2 3 1\n1 3 1\n1 2 3\n', '1 0 1\n1\n', '5 5 2\n1 2 1\n2 3 1\n3 4 1\n4 5 1\n1 5 10\n1 5\n', '4 6 3\n1 2 1\n1 3 1\n1 4 1\n2 3 5\n3 4 5\n2 4 4\n2 3 4\n'] })

export const CATALOG = TASKS
