// 生成タスク 第71波：各レベル2問化フェーズ(26)。lv941〜970 に2問目を追加。
// 最高峰帯前半: ゲーム/幾何/数列/数論。重複なし・決定的・採点一意。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 941, concept: '数え上げ: 同点を許すリードの並べ方', title: '一度も逆転されない開票順', tags: ['数学', 'DP'], io: 'p q が空白区切りで1行で与えられます (p≥q)。', ask: '候補Aがp票、Bがq票のとき、開票の全過程でAの票数がBの票数を下回らない(同点は許す)開票順の数を出力してください。', h1: '格子経路で「対角線より下に落ちない」道の数。', h2: 'dp[a][b] を「A a票・B b票まで開票して常に a≥b」と定めて足し上げる。', ref: 'p,q=map(int,input().split())\ndp=[[0]*(q+1) for _ in range(p+1)]\ndp[0][0]=1\nfor a in range(p+1):\n    for b in range(q+1):\n        if b>a:\n            continue\n        if a>0:\n            dp[a][b]+=dp[a-1][b]\n        if b>0 and a>=b:\n            dp[a][b]+=dp[a][b-1]\nprint(dp[p][q])', tip: '「厳密にリード」版と「同点許容」版は反射原理の使い方が1ずれるだけの兄弟。DPで数えれば公式 (p−q+1)/(p+1)·C(p+q,q) の検算にもなる。', ins: ['2 1\n', '2 2\n', '3 1\n', '1 1\n', '3 3\n', '4 2\n'] })

t({ lv: 942, concept: 'グラフ: ドミノ牌を一列に並べられるか', title: 'ドミノの鎖は完成するか', tags: ['グラフ'], io: '1行目に牌の数 m、続く m 行に各牌の両端の数字 a b (0〜6) が与えられます。', ask: '全ての牌を(向きは自由に)一列に、接する端の数字が一致するように並べられるなら yes、無理なら no を出力してください。', h1: '数字を頂点、牌を辺とみなす。', h2: '多重グラフのオイラー路の存在条件: 辺のある頂点が連結で、奇数次数の頂点が0個か2個。', ref: 'm=int(input())\ndeg=[0]*7\nadj=[[] for _ in range(7)]\nfor _ in range(m):\n    a,b=map(int,input().split())\n    deg[a]+=1\n    deg[b]+=1\n    adj[a].append(b)\n    adj[b].append(a)\nstart=next((v for v in range(7) if deg[v]>0),-1)\nok=True\nif start>=0:\n    seen=[False]*7\n    st=[start]\n    seen[start]=True\n    while st:\n        x=st.pop()\n        for y in adj[x]:\n            if not seen[y]:\n                seen[y]=True\n                st.append(y)\n    if any(deg[v]>0 and not seen[v] for v in range(7)):\n        ok=False\n    if sum(1 for v in range(7) if deg[v]%2==1) not in (0,2):\n        ok=False\nprint("yes" if ok else "no")', tip: 'ドミノ牌の鎖=数字グラフのオイラー路、という古典的モデル化(オイラー自身の一筆書きと同型)。ゾロ目牌は自己ループで次数+2になる点も要注意。', ins: ['3\n1 2\n2 3\n3 1\n', '2\n1 2\n3 4\n', '2\n1 2\n2 3\n', '1\n5 5\n', '4\n0 1\n1 2\n2 0\n0 0\n', '3\n1 2\n2 3\n4 4\n'] })

t({ lv: 943, concept: 'ゲーム: 取れない人が勝ちの石取り', title: '取り尽くしたら負けの石取り', tags: ['ゲーム', 'DP'], io: '1行目に石の数 n、2行目に1手で取れる個数の集合 S が与えられます。', ask: '最後の石を取った人が「負け」(ミゼール規則)のとき、両者最善で先手が勝つなら first、負けるなら second を出力してください(取れる手が無い人はパスできず、その時点で石が残っていても指せなければ負け…ではなく、ここでは常に1個は取れるよう1∈S とします)。', h1: '状態は石の数だけ。', h2: 'win[0] は「直前の相手が最後を取った」ので勝ち。win[i] は「ある手で相手を負け状態にできるか」。', ref: 'n=int(input())\nS=list(map(int,input().split()))\nwin=[False]*(n+1)\nwin[0]=True\nfor i in range(1,n+1):\n    win[i]=any(i>=s and not win[i-s] for s in S)\nprint("first" if win[n] else "second")', tip: '通常規則とミゼール規則の差は境界条件 win[0] の一行だけ。同じDPで規則の反転が表せる一方、Nimのような多山ではミゼールの解析が急に難しくなる。', ins: ['3 \n1 2\n', '1\n1\n', '4\n1 2\n', '5\n1 3\n', '2\n1 2 3\n', '10\n1 4\n'] })

t({ lv: 944, concept: 'ゲーム: DAG上のコマ動かしゲーム', title: '行き止まりに追い込むコマ遊び', tags: ['ゲーム', '再帰'], io: '1行目に n m k、続く m 行に閉路のない有向辺、最後の行に k 個のコマの位置が与えられます。', ask: '2人交互に「どれか1つのコマを辺に沿って1歩動かす」。動かせなくなった方が負け。両者最善で先手が勝つなら first、負けるなら second を出力してください(複数コマが同じ頂点に居てもよい)。', h1: '各頂点のGrundy数を求める。', h2: '独立なコマの合成はGrundy数のXOR。0なら後手必勝。', ref: 'import sys\nsys.setrecursionlimit(100000)\nn,m,k=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\ntokens=list(map(int,input().split()))\nmemo={}\ndef gr(v):\n    if v in memo:\n        return memo[v]\n    s=set(gr(w) for w in g[v])\n    r=0\n    while r in s:\n        r+=1\n    memo[v]=r\n    return r\nx=0\nfor t_ in tokens:\n    x^=gr(t_)\nprint("first" if x!=0 else "second")', tip: 'スプレイグ・グランディ理論の一般形そのもの。「山」が「グラフ上のコマ」に置き換わっても、独立和はXORで束ねられる。', ins: ['3 2 1\n1 2\n2 3\n1\n', '3 2 2\n1 2\n2 3\n1 1\n', '2 1 1\n1 2\n2\n', '4 4 2\n1 2\n2 4\n1 3\n3 4\n1 3\n', '5 4 1\n1 2\n2 3\n3 4\n4 5\n1\n', '3 2 3\n1 2\n2 3\n1 2 3\n'] })

t({ lv: 945, concept: '数え上げ: k個の非攻撃ルークの置き方', title: 'k個のルークを平和に置く', tags: ['数学'], io: 'n k が空白区切りで1行で与えられます (0≤k≤n)。', ask: 'n×n の盤に k 個のルークを互いに取り合わないように置く方法の数を出力してください。', h1: '使う行と列を選んでから対応させる。', h2: 'C(n,k)² · k!。', ref: 'from math import comb,factorial\nn,k=map(int,input().split())\nprint(comb(n,k)**2*factorial(k))', tip: '「行を選ぶ×列を選ぶ×対応づけ」の三段分解。k=n で n! (順列)に退化し、ルーク多項式という一般理論の最初の一歩になる。', ins: ['2 1\n', '2 2\n', '3 2\n', '4 0\n', '3 3\n', '4 2\n'] })

t({ lv: 946, concept: 'スタック: 論理式の評価', title: '真か偽か、式を読み解く', tags: ['スタック', '文字列'], io: 'T(真)、F(偽)、&(かつ)、|(または)、!(否定)、丸括弧からなる論理式が1行で与えられます(2項演算は必ず括弧つき、例 (T&(!F)))。', ask: '式を評価した結果を T か F で出力してください。', h1: '完全括弧化なら再帰下降が素直。', h2: '閉じ括弧が来たら直前の部分式をまとめる、スタック評価でも書ける。', ref: 's=input()\npos=0\ndef parse():\n    global pos\n    c=s[pos]\n    if c=="T":\n        pos+=1\n        return True\n    if c=="F":\n        pos+=1\n        return False\n    if c=="!":\n        pos+=1\n        return not parse()\n    pos+=1\n    a=parse()\n    if s[pos]==")":\n        pos+=1\n        return a\n    op=s[pos]\n    pos+=1\n    b=parse()\n    pos+=1\n    return (a and b) if op=="&" else (a or b)\nprint("T" if parse() else "F")', tip: '完全括弧化文法は先読み1文字の再帰下降パーサの練習に最適。文法をゆるめる(優先順位・省略括弧)と操車場アルゴリズムの出番になる。', ins: ['(T&F)\n', '(T|F)\n', '!T\n', '(!F&T)\n', '((T|F)&(!F))\n', 'F\n'] })

t({ lv: 947, concept: 'DP: t回k個で調べ切れる最大の階', title: '試行回数から逆算するビル調査', tags: ['DP'], io: 't k が空白区切りで1行で与えられます(試行回数 t、卵 k 個)。', ask: 't 回の試行と k 個の卵で「確実に割れる境界階を特定できる」建物の最大の階数を出力してください。', h1: '「n階をt回で」でなく「t回で何階まで?」と裏返す。', h2: 'f(t,k) = f(t−1,k−1) + f(t−1,k) + 1(割れた場合と割れない場合+その階自身)。', ref: 't,k=map(int,input().split())\nf=[[0]*(k+1) for _ in range(t+1)]\nfor i in range(1,t+1):\n    for j in range(1,k+1):\n        f[i][j]=f[i-1][j-1]+f[i-1][j]+1\nprint(f[t][k])', tip: '卵落とし問題の双対で、こちらの表は二項係数の和 Σ C(t,i) (i=1..k) に一致する。逆関数を表で持つ発想が計算量を劇的に変える。', ins: ['1 1\n', '2 1\n', '3 2\n', '4 2\n', '5 3\n', '10 1\n'] })

t({ lv: 948, concept: 'オートマトン: DFAの受理判定', title: 'この文字列は受理されるか', tags: ['オートマトン'], io: '1行目に 状態数 n、初期状態 s、受理状態の個数 f と受理状態の列。続く n 行に各状態の遷移(0を読んだ先と1を読んだ先)。最後の行に0/1の文字列が与えられます。', ask: '決定性有限オートマトンが入力文字列を読み終えたとき受理状態にあるなら yes、なければ no を出力してください。', h1: '状態を1つ持って1文字ずつ遷移する。', h2: '遷移表 delta[状態][文字] を引くだけ。', ref: 'first=input().split()\nn=int(first[0])\ns=int(first[1])\nf=int(first[2])\nacc=set(int(x) for x in first[3:3+f])\ndelta=[]\nfor _ in range(n):\n    a,b=map(int,input().split())\n    delta.append((a,b))\nw=input()\ncur=s\nfor c in w:\n    cur=delta[cur][int(c)]\nprint("yes" if cur in acc else "no")', tip: '正規表現エンジンや字句解析器の心臓部は結局この5行のループ。状態×入力→状態の表こそが「計算」の最小モデルであることを体感できる。', ins: ['2 0 1 1\n0 1\n1 0\n101\n', '2 0 1 0\n0 1\n1 0\n11\n', '1 0 1 0\n0 0\n0101\n', '3 0 1 2\n1 0\n2 1\n2 2\n01\n', '2 0 1 1\n1 1\n1 1\n\n', '2 1 1 1\n0 1\n1 0\n0\n'] })

t({ lv: 949, concept: '累積和: 十字形の最大和', title: '十字の形に切り取る最大の和', tags: ['累積和'], io: '1行目に H W k(腕の長さ)、続く H 行に整数の行列が与えられます(十字が収まる位置が1つ以上あります)。', ask: '中心+上下左右に長さ k の腕を伸ばした十字(マス数 4k+1)を盤内に置くときの、合計の最大を出力してください。', h1: '行方向と列方向の累積和を用意する。', h2: '中心ごとに縦の腕は列累積、横の腕は行累積でO(1)。中心の二重加算を引く。', ref: 'h,w,k=map(int,input().split())\ng=[list(map(int,input().split())) for _ in range(h)]\nrow=[[0]*(w+1) for _ in range(h)]\nfor i in range(h):\n    for j in range(w):\n        row[i][j+1]=row[i][j]+g[i][j]\ncol=[[0]*(h+1) for _ in range(w)]\nfor j in range(w):\n    for i in range(h):\n        col[j][i+1]=col[j][i]+g[i][j]\nbest=None\nfor i in range(k,h-k):\n    for j in range(k,w-k):\n        v=row[i][j+k+1]-row[i][j-k]+col[j][i+k+1]-col[j][i-k]-g[i][j]\n        if best is None or v>best:\n            best=v\nprint(best)', tip: '軸に沿った図形は行・列の1次元累積和2本で分解できる。2次元累積和(矩形)との使い分け、中心の重複を1回引く包除が実装の勘所。', ins: ['3 3 1\n1 1 1\n1 5 1\n1 1 1\n', '3 3 0\n1 2 3\n4 5 6\n7 8 9\n', '5 5 2\n1 1 1 1 1\n1 1 1 1 1\n1 1 9 1 1\n1 1 1 1 1\n1 1 1 1 1\n', '3 5 1\n0 1 0 2 0\n1 1 1 9 1\n0 1 0 2 0\n', '1 3 0\n-1 -2 -3\n', '3 3 1\n-1 -1 -1\n-1 -1 -1\n-1 -1 -1\n'] })

t({ lv: 950, concept: '数え上げ: 表し方がちょうどk通りの金額', title: '作り方がぴったりk通りの金額', tags: ['数え上げ', 'DP'], io: 'N a b k が1行で与えられます。', ask: '1 以上 N 以下の金額のうち、a·x + b·y (x,y は非負整数)としての表し方(x,yの組)がちょうど k 通りのものの個数を出力してください。', h1: '各金額の表し方の数を数える配列を作る。', h2: 'x を回して a·x + b·y ≤ N の全てに1を加算する。', ref: 'N,a,b,k=map(int,input().split())\nreps=[0]*(N+1)\nx=0\nwhile a*x<=N:\n    v=a*x\n    while v<=N:\n        reps[v]+=1\n        v+=b\n    x+=1\nprint(sum(1 for v in range(1,N+1) if reps[v]==k))', tip: '「可否」→「通り数」→「通り数の分布」への3段目。フロベニウスの世界を頻度の目で見ると、大きな金額ほど表し方が線形に増える構造が見える。', ins: ['10 2 3 1\n', '10 2 3 0\n', '20 3 5 2\n', '12 4 6 1\n', '15 2 2 0\n', '30 5 7 1\n'] })

t({ lv: 951, concept: '文字列: 辞書順k番目の相異なる部分列', title: 'k番目の隠れた部分列', tags: ['文字列', '再帰'], io: '1行目に k、2行目に英小文字の文字列が与えられます(kは相異なる空でない部分列の総数以下)。', ask: '相異なる空でない部分列を辞書順に並べたときの k 番目を出力してください。', h1: '「この文字から始まる相異なる部分列の数」を数える。', h2: '各位置から各文字の初出だけを辿る木を考え、部分木サイズで k を消費しながら降りる。', ref: 'import sys\nsys.setrecursionlimit(100000)\nk=int(input())\ns=input()\nn=len(s)\nnxt=[dict() for _ in range(n+1)]\nlast={}\nfor i in range(n-1,-1,-1):\n    last[s[i]]=i\n    nxt[i]=dict(last)\ncntmemo={}\ndef cnt(i):\n    if i>n-1 and i not in nxt[min(i,n)]:\n        pass\n    if i in cntmemo:\n        return cntmemo[i]\n    total=1\n    if i<=n-1:\n        for c in sorted(nxt[i]):\n            total+=cnt(nxt[i][c]+1)\n    cntmemo[i]=total\n    return total\nres=[]\ni=0\nwhile k>0:\n    if i>n-1:\n        break\n    for c in sorted(nxt[i]):\n        sub=cnt(nxt[i][c]+1)\n        if k<=sub:\n            res.append(c)\n            k-=1\n            if k==0:\n                break\n            i=nxt[i][c]+1\n            break\n        k-=sub\nprint("".join(res))', tip: '相異なる部分列の木は「各文字の最初の出現だけ子にする」ことで重複が消える。数えながら降りるアンランクの型は順列・組合せ・部分列で共通。', ins: ['1\nab\n', '2\nab\n', '3\nab\n', '2\naba\n', '5\naba\n', '4\nabc\n'] })

t({ lv: 952, concept: '文字列: 2文字が交互に並ぶ最長', title: 'アルテミスの縞模様', tags: ['文字列'], io: '英小文字の文字列が1行で与えられます。', ask: '2種類の文字が交互に並ぶ(ababab… の形、1種類だけの区間は長さ1まで)連続部分文字列の最大の長さを出力してください。', h1: '「1つ前と違い、2つ前と同じ」が続く限り伸びる。', h2: 'その条件が崩れたら長さ2(または1)から仕切り直す。', ref: 's=input()\nn=len(s)\nbest=1\nrun=1\nfor i in range(1,n):\n    if s[i]==s[i-1]:\n        run=1\n    elif i>=2 and s[i]==s[i-2]:\n        run+=1\n    else:\n        run=2\n    if run>best:\n        best=run\nprint(best)', tip: '交互列の判定は「2つ前と同じ・1つ前と違う」の局所条件に潰せる。ランの仕切り直しの初期値(1か2か)の場合分けが唯一の罠。', ins: ['ababab\n', 'aaaa\n', 'abcbcbc\n', 'a\n', 'abba\n', 'xyxyz\n'] })

t({ lv: 953, concept: '幾何: 平行な線分の組数', title: '平行になっている線分ペア', tags: ['幾何'], io: '1行目に線分数 n、続く n 行に線分 x1 y1 x2 y2 が与えられます(長さ0の線分はありません)。', ask: '互いに平行(方向が同じか正反対)な線分の組の個数を出力してください。', h1: '方向ベクトルを正規化する。', h2: 'gcdで割り、符号を(先頭が正になるよう)揃えると平行が同一キーになる。', ref: 'import math\nfrom collections import Counter\nn=int(input())\nc=Counter()\nfor _ in range(n):\n    x1,y1,x2,y2=map(int,input().split())\n    dx,dy=x2-x1,y2-y1\n    g=math.gcd(abs(dx),abs(dy))\n    dx//=g\n    dy//=g\n    if dx<0 or (dx==0 and dy<0):\n        dx,dy=-dx,-dy\n    c[(dx,dy)]+=1\nprint(sum(v*(v-1)//2 for v in c.values()))', tip: '傾きをfloatで持つと誤差と垂直線で事故る。既約整数ベクトル+符号正規化は方向の正準形として盤石で、一直線上の点数問題でも同じ技を使う。', ins: ['3\n0 0 1 1\n2 2 4 4\n0 0 1 0\n', '2\n0 0 1 0\n5 5 6 5\n', '2\n0 0 1 2\n0 0 2 1\n', '4\n0 0 0 1\n1 0 1 5\n2 2 2 3\n0 0 1 0\n', '2\n0 0 2 4\n3 3 2 1\n', '1\n0 0 3 3\n'] })

t({ lv: 954, concept: '幾何: 長方形たちの合計被覆面積', title: '重なりを数えない紙の面積', tags: ['幾何'], io: '1行目に枚数 n、続く n 行に軸に平行な長方形 x1 y1 x2 y2 (左下と右上、整数)が与えられます。', ask: '少なくとも1枚に覆われる領域の総面積を出力してください。', h1: '重なりがあるので単純な和では駄目。', h2: '出現する x座標・y座標で平面を小さなセルに切り(座標圧縮)、各セルが覆われるか判定して足す。', ref: 'n=int(input())\nrects=[tuple(map(int,input().split())) for _ in range(n)]\nxs=sorted(set([r[0] for r in rects]+[r[2] for r in rects]))\nys=sorted(set([r[1] for r in rects]+[r[3] for r in rects]))\ntotal=0\nfor i in range(len(xs)-1):\n    for j in range(len(ys)-1):\n        cx=xs[i]\n        cy=ys[j]\n        if any(r[0]<=cx and xs[i+1]<=r[2] and r[1]<=cy and ys[j+1]<=r[3] for r in rects):\n            total+=(xs[i+1]-xs[i])*(ys[j+1]-ys[j])\nprint(total)', tip: '座標圧縮は「答えが変化しうる境界」だけを残す離散化。セル数はO(n²)に潰れ、走査線+セグ木のO(n log n)への入り口になる。', ins: ['2\n0 0 2 2\n1 1 3 3\n', '1\n0 0 5 5\n', '2\n0 0 1 1\n2 2 3 3\n', '3\n0 0 4 1\n0 0 1 4\n3 3 4 4\n', '2\n0 0 3 3\n1 1 2 2\n', '3\n0 0 2 2\n2 0 4 2\n0 2 4 4\n'] })

t({ lv: 955, concept: '幾何: 自己交差のない多角形か', title: 'この多角形はねじれていないか', tags: ['幾何'], io: '1行目に頂点数 n、続く n 行に多角形の頂点(順に結ぶ)が与えられます。', ask: '隣り合わない辺どうしが交わらない(単純多角形である)なら yes、そうでなければ no を出力してください。', h1: '全ての辺のペアを調べる。', h2: '隣接する辺(端点を共有)は除外し、それ以外に線分交差判定を適用する。', ref: 'n=int(input())\np=[tuple(map(int,input().split())) for _ in range(n)]\ndef sgn(x):\n    return (x>0)-(x<0)\ndef cross(o,a,b):\n    return (a[0]-o[0])*(b[1]-o[1])-(a[1]-o[1])*(b[0]-o[0])\ndef on(a,b,c):\n    return cross(a,b,c)==0 and min(a[0],b[0])<=c[0]<=max(a[0],b[0]) and min(a[1],b[1])<=c[1]<=max(a[1],b[1])\ndef inter(a,b,c,d):\n    d1=sgn(cross(c,d,a))\n    d2=sgn(cross(c,d,b))\n    d3=sgn(cross(a,b,c))\n    d4=sgn(cross(a,b,d))\n    if d1*d2<0 and d3*d4<0:\n        return True\n    return on(c,d,a) or on(c,d,b) or on(a,b,c) or on(a,b,d)\nok=True\nfor i in range(n):\n    for j in range(i+1,n):\n        if j==i+1 or (i==0 and j==n-1):\n            continue\n        if inter(p[i],p[(i+1)%n],p[j],p[(j+1)%n]):\n            ok=False\nprint("yes" if ok else "no")', tip: '多角形アルゴリズム(面積・内外判定)の前提「単純である」を自前で検査する門番。隣接辺の共有端点を交差扱いしない除外条件が肝心。', ins: ['4\n0 0\n2 0\n2 2\n0 2\n', '4\n0 0\n2 2\n2 0\n0 2\n', '3\n0 0\n3 0\n0 3\n', '5\n0 0\n4 0\n4 4\n2 6\n0 4\n', '4\n0 0\n3 0\n1 -1\n1 1\n', '6\n0 0\n2 0\n2 1\n1 1\n1 2\n0 2\n'] })

t({ lv: 956, concept: '数列: k-ボナッチ数', title: '直前k項を足す数列', tags: ['数列'], io: 'k n が空白区切りで1行で与えられます (k≥2)。', ask: '初期値が 0,…,0,1 (k項、最後だけ1)で、以降は直前 k 項の和で定まる k-ボナッチ数列の第 n 項(先頭を第1項)を出力してください。', h1: 'k=2 がフィボナッチ、k=3 がトリボナッチ。', h2: '直近k項のリストを窓のように更新する。', ref: 'k,n=map(int,input().split())\nseq=[0]*(k-1)+[1]\nwhile len(seq)<n:\n    seq.append(sum(seq[-k:]))\nprint(seq[n-1])', tip: 'kを大きくすると隣接比は2に近づく(特性方程式の最大根)。フィボナッチ→トリボ→テトラの系列を1つのパラメータで統一する視点。', ins: ['2 7\n', '3 7\n', '4 8\n', '2 1\n', '5 6\n', '3 10\n'] })

t({ lv: 957, concept: '数列: ヤコブスタール・リュカ数', title: 'ヤコブスタールの相棒数列', tags: ['数列'], io: '非負整数 n が1行で与えられます。', ask: 'b(0)=2, b(1)=1, b(n)=b(n−1)+2·b(n−2) で定まるヤコブスタール・リュカ数列の第 n 項を出力してください。', h1: '漸化式はヤコブスタール数と同じで初期値だけ違う。', h2: '2項を持ち回るループ。', ref: 'n=int(input())\na,b=2,1\nfor _ in range(n):\n    a,b=b,b+2*a\nprint(a)', tip: 'リュカ型(同じ漸化式・別初期値)の相棒は 2ⁿ+(−1)ⁿ という閉形式を持つ。フィボナッチとリュカ、ペルとペル・リュカと同じ対の構図。', ins: ['0\n', '1\n', '2\n', '3\n', '5\n', '10\n'] })

t({ lv: 958, concept: '数列: ナラヤナの牛の数列', title: '毎年子を産む牛の頭数', tags: ['数列'], io: '非負整数 n が1行で与えられます。', ask: 'a(0)=1, a(1)=1, a(2)=1, a(n)=a(n−1)+a(n−3) で定まるナラヤナの牛の数列の第 n 項を出力してください。', h1: '「生まれて3年たつと毎年1頭産む」個体数モデル。', h2: '3項の持ち回り。', ref: 'n=int(input())\na,b,c=1,1,1\nfor _ in range(n):\n    a,b,c=b,c,c+a\nprint(a)', tip: 'フィボナッチの兎(成熟1期)を成熟3期にした一般化。遅延つき増殖はパドヴァン(a(n−2)+a(n−3))と兄弟で、成長率は塑性数の親戚になる。', ins: ['0\n', '3\n', '5\n', '7\n', '10\n', '1\n'] })

t({ lv: 959, concept: '数列: レオナルド数', title: 'スムーズソートの隠れた数列', tags: ['数列'], io: '非負整数 n が1行で与えられます。', ask: 'L(0)=1, L(1)=1, L(n)=L(n−1)+L(n−2)+1 で定まるレオナルド数の第 n 項を出力してください。', h1: '+1つきのフィボナッチ型。', h2: '2項持ち回りに+1を添えるだけ。', ref: 'n=int(input())\na,b=1,1\nfor _ in range(n):\n    a,b=b,a+b+1\nprint(a)', tip: 'L(n)=2F(n+1)−1 でフィボナッチと結ばれる。ダイクストラがヒープソート改良(スムーズソート)の木のサイズに採用したことで知られる実用出身の数列。', ins: ['0\n', '2\n', '3\n', '5\n', '8\n', '10\n'] })

t({ lv: 960, concept: '数列: マルコフ数の列挙', title: 'マルコフのトリプルを探す', tags: ['数列', 'BFS'], io: '正整数 N が1行で与えられます。', ask: 'x²+y²+z²=3xyz の正整数解(マルコフのトリプル)に現れる数のうち N 以下のものを、小さい順に空白区切りで出力してください。', h1: '(1,1,1)から始めて「1成分の置き換え」で解が増える。', h2: '(x,y,z) → (x,y,3xy−z) の変異をBFSし、N以下の成分を集める。', ref: 'N=int(input())\nseen=set()\nnums=set()\nstack=[(1,1,1)]\nwhile stack:\n    t_=stack.pop()\n    x,y,z=sorted(t_)\n    if (x,y,z) in seen or z>N:\n        continue\n    seen.add((x,y,z))\n    nums.update((x,y,z))\n    stack.append(tuple(sorted((x,y,3*x*y-z))))\n    stack.append(tuple(sorted((x,3*x*z-y,z))))\n    stack.append(tuple(sorted((3*y*z-x,y,z))))\nprint(*sorted(nums))', tip: '1,2,5,13,29,34,…。全ての解が(1,1,1)からの木で尽くされる(マルコフの定理)。「各数が最大成分として一意か」は未解決のマルコフ予想。', ins: ['1\n', '5\n', '13\n', '2\n', '34\n', '200\n'] })

t({ lv: 961, concept: '数え上げ: アペリー数', title: 'ζ(3)を無理数にした数列', tags: ['数学'], io: '非負整数 n が1行で与えられます。', ask: 'アペリー数 A(n) = Σ C(n,k)²·C(n+k,k)² (k=0..n) を出力してください。', h1: '二項係数の積の和をそのまま計算する。', h2: 'math.comb で各項を作って総和。', ref: 'from math import comb\nn=int(input())\nprint(sum(comb(n,k)**2*comb(n+k,k)**2 for k in range(n+1)))', tip: '1,5,73,1445,…。アペリーがζ(3)の無理性証明(1978)に用いた数列で、(n+1)³A(n+1)=(34n³+…)A(n)−n³A(n−1) という異様な漸化式も成り立つ。', ins: ['0\n', '1\n', '2\n', '3\n', '4\n', '5\n'] })

t({ lv: 962, concept: '数え上げ: 面積と周長が等しい三角形', title: '面積=周長の整数三角形', tags: ['数学', '幾何'], io: '正整数 N が1行で与えられます。', ask: '辺が全て N 以下の整数の三角形(a≤b≤c)で、面積と周長が(数値として)等しいものの個数を出力してください。', h1: 'ヘロンの公式を16倍して整数のまま扱う。', h2: '16·面積² = (a+b+c)(−a+b+c)(a−b+c)(a+b−c)。面積=周長 P なら 16P² と比較。', ref: 'N=int(input())\ncnt=0\nfor a in range(1,N+1):\n    for b in range(a,N+1):\n        for c in range(b,min(N,a+b-1)+1):\n            P=a+b+c\n            if (P)*(-a+b+c)*(a-b+c)*(a+b-c)==16*P*P:\n                cnt+=1\nprint(cnt)', tip: '該当する三角形は(5,12,13),(6,8,10),(6,25,29),(7,15,20),(9,10,17)の5つだけ、と証明されている。有限個で尽きる整数問題の好例。', ins: ['13\n', '10\n', '20\n', '29\n', '5\n', '30\n'] })

t({ lv: 963, concept: '数論: 疑似完全数の判定', title: '約数の一部でぴったり作れるか', tags: ['数論', 'DP'], io: '正整数 n が1行で与えられます。', ask: 'n の真の約数(n自身を除く)の部分集合の和として n を表せる(疑似完全数)なら yes、表せなければ no を出力してください。', h1: 'まず真の約数を列挙する。', h2: '部分和のDP(可否)を n を目標に回す。', ref: 'n=int(input())\ndivs=[d for d in range(1,n) if n%d==0]\nok=[False]*(n+1)\nok[0]=True\nfor d in divs:\n    for v in range(n,d-1,-1):\n        if ok[v-d]:\n            ok[v]=True\nprint("yes" if ok[n] else "no")', tip: '完全数は自動的に疑似完全。過剰数なのに疑似完全でない「weird number」(最小70)が存在するのが面白いところで、その希少さは今も研究対象。', ins: ['6\n', '12\n', '8\n', '10\n', '70\n', '20\n'] })

t({ lv: 964, concept: '数論: 倍積完全数の判定', title: '約数和が自分の何倍か', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: '全約数の和 σ(n) が n の整数倍なら、その倍率 k を出力してください(完全数は2)。倍数でなければ -1。', h1: 'σ(n) を計算して割り切れるか見る。', h2: 'σ(n) % n が0なら σ(n)//n。', ref: 'n=int(input())\ns=0\ni=1\nwhile i*i<=n:\n    if n%i==0:\n        s+=i\n        if i!=n//i:\n            s+=n//i\n    i+=1\nprint(s//n if s%n==0 else -1)', tip: 'k=3の最小は120、k=4の最小は30240。k倍完全数(multiperfect)は現在k=11まで発見済みで、完全数の一般化として探索が続いている。', ins: ['6\n', '120\n', '28\n', '10\n', '1\n', '30240\n'] })

t({ lv: 965, concept: '数論: 婚約数の判定', title: 'ひとつずれた友愛、婚約数', tags: ['数論'], io: '正整数 a b が空白区切りで1行で与えられます (a≠b)。', ask: '「1を除いた真の約数の和」がお互いを指し合う(s(a)=b かつ s(b)=a、ここで s は1と自分自身を除く約数の和)なら yes、そうでなければ no を出力してください。', h1: '1を除くので普通の友愛数と定義が1ずれる。', h2: '各数の「1と自分以外の約数の和」を計算して相互チェック。', ref: 'a,b=map(int,input().split())\ndef s(n):\n    total=0\n    i=2\n    while i*i<=n:\n        if n%i==0:\n            total+=i\n            if i!=n//i:\n                total+=n//i\n        i+=1\n    return total\nprint("yes" if s(a)==b and s(b)==a else "no")', tip: '(48,75),(140,195),…。既知の婚約数ペアは必ず偶奇が異なる、という観察があり「偶偶・奇奇のペアが存在するか」は未解決。', ins: ['48 75\n', '140 195\n', '220 284\n', '5 9\n', '1050 1925\n', '10 12\n'] })

t({ lv: 966, concept: '数論: 桁の積で割り切れる数の判定', title: '自分の桁の積で割り切れるか', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: 'n の各桁の積が0でなく、かつ n がその積で割り切れる(ズッカーマン数)なら yes、そうでなければ no を出力してください。', h1: '桁に0があれば即 no。', h2: '桁の積を作って n % 積 を見る。', ref: 'n=int(input())\np=1\nfor c in str(n):\n    p*=int(c)\nprint("yes" if p!=0 and n%p==0 else "no")', tip: '桁の「和」で割れるのがハーシャッド数、「積」で割れるのがズッカーマン数。表記(基数)に依存する性質は数学的には浅いが、プログラム練習には最適の題材。', ins: ['36\n', '24\n', '111\n', '20\n', '15\n', '384\n'] })

t({ lv: 967, concept: '数論: 約数がちょうどk個の最小数', title: '約数k個クラブの最年少', tags: ['数論'], io: '正整数 k が1行で与えられます。', ask: '約数の個数がちょうど k である最小の正整数を出力してください。', h1: '小さい順に約数の個数を数えて探す。', h2: '約数個数は素因数の指数+1の積。素数kなら 2^(k−1) が答えになる、と構造からも分かる。', ref: 'k=int(input())\ndef d(x):\n    c=0\n    i=1\n    while i*i<=x:\n        if x%i==0:\n            c+=2 if i*i!=x else 1\n        i+=1\n    return c\nn=1\nwhile d(n)!=k:\n    n+=1\nprint(n)', tip: '指数の並べ方の最適化(大きい指数を小さい素数へ)で構成的にも解ける。素朴探索と構成解の照合は高度合成数の理解にも繋がる。', ins: ['1\n', '2\n', '3\n', '4\n', '6\n', '8\n'] })

t({ lv: 968, concept: '数論: 約数の逆数の和', title: '約数の逆数を全部足すと', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: 'n の全約数 d について 1/d を足した値を既約分数で「分子 分母」の形で出力してください。', h1: 'Σ1/d = σ(n)/n が成り立つ。', h2: 'σ(n) を計算し、gcd で約分する。', ref: 'import math\nn=int(input())\ns=0\ni=1\nwhile i*i<=n:\n    if n%i==0:\n        s+=i\n        if i!=n//i:\n            s+=n//i\n    i+=1\ng=math.gcd(s,n)\nprint(s//g,n//g)', tip: 'd と n/d の対応から Σ1/d=σ(n)/n が一行で出る。完全数なら答えがちょうど2になる、という定義の言い換えにもなっている。', ins: ['6\n', '4\n', '1\n', '12\n', '28\n', '10\n'] })

t({ lv: 969, concept: '数論: √nに最も近い約数', title: '一番正方形に近い長方形', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: '面積 n の整数辺の長方形のうち、縦横の差が最小のものの辺の長さを「短い方 長い方」の順で出力してください。', h1: '√n 以下で最大の約数を探す。', h2: 'isqrt(n) から下へ降りて最初に割り切れた d と n//d が答え。', ref: 'import math\nn=int(input())\nd=math.isqrt(n)\nwhile n%d!=0:\n    d-=1\nprint(d,n//d)', tip: '画像のタイル分割やUIのグリッド設計で頻出する「なるべく正方形」の計算。√nからの下降は必ず1で止まるので停止性も明快。', ins: ['12\n', '16\n', '13\n', '36\n', '48\n', '1\n'] })

t({ lv: 970, concept: '数論: ファレイ数列で隣どうしか', title: 'その2つの分数は隣り合うか', tags: ['数論'], io: 'n a b c d が1行で与えられます(既約分数 a/b < c/d、分母は n 以下)。', ask: 'ファレイ数列 F_n で a/b と c/d が隣接しているなら yes、間に別の分数が挟まるなら no を出力してください。', h1: '隣接なら bc − ad の値に特徴がある。', h2: '隣接 ⇔ bc−ad=1 かつ 中間分数(メディアント)の分母 b+d が n を超える。', ref: 'n,a,b,c,d=map(int,input().split())\nprint("yes" if b*c-a*d==1 and b+d>n else "no")', tip: 'bc−ad=1(ユニモジュラ性)はファレイ隣接の刻印で、シュターン・ブロコ木や連分数と同じ行列 SL(2,Z) の世界に属する。メディアントの分母判定が「次の世代でも割り込まれないか」を言う。', ins: ['5 1 3 2 5\n', '5 1 3 1 2\n', '3 1 3 1 2\n', '4 1 4 1 3\n', '5 2 5 1 2\n', '2 0 1 1 2\n'] })

export const CATALOG = TASKS
