// 生成タスク 第62波：各レベル2問化フェーズ(17)。lv716〜740 に2問目を追加。
// DP応用/数え上げ/スタック/ゲーム帯。重複なし・決定的・採点一意。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 716, concept: 'ハッシュ: 積がちょうどkのペア数', title: '掛けてkになる2つの数', tags: ['ハッシュ'], io: '1行目に k、2行目に正整数の列が与えられます。', ask: 'i<j で a[i]×a[j] が k に等しいペアの個数を出力してください。', h1: '相方は k÷a[i] と決まっている。', h2: '左から走査し「これまでの値の個数」を辞書に持てば、割り切れるときだけ相方の数を足せる。', ref: 'from collections import Counter\nk=int(input())\na=list(map(int,input().split()))\nseen=Counter()\ncnt=0\nfor x in a:\n    if k%x==0:\n        cnt+=seen[k//x]\n    seen[x]+=1\nprint(cnt)', tip: '2-SUMの積バージョン。和と違い「割り切れるか」の枝刈りが入るのが積らしさ。過去だけ数えるとペアの二重数えが自然に防げる。', ins: ['6\n1 2 3 6\n', '4\n2 2 2\n', '12\n3 4 2 6 1 12\n', '5\n2 3\n', '1\n1 1 1\n', '9\n3 3 3 9\n'] })

t({ lv: 717, concept: '配列: 隣接和がすべて素数か', title: '隣どうしの和が全部素数か', tags: ['配列', '数論'], io: '整数列(2個以上)が1行で空白区切りで与えられます。', ask: '隣接する全てのペアの和が素数なら yes、そうでなければ no を出力してください。', h1: '素数判定の関数を用意する。', h2: 'zipで隣接ペアを作り、全てに判定を適用する。', ref: 'a=list(map(int,input().split()))\ndef isp(x):\n    if x<2:\n        return False\n    i=2\n    while i*i<=x:\n        if x%i==0:\n            return False\n        i+=1\n    return True\nprint("yes" if all(isp(x+y) for x,y in zip(a,a[1:])) else "no")', tip: 'zip(a, a[1:]) は隣接ペアを作る最短のイディオム。判定を「積が平方数」「差が2べき」に差し替えても骨格はそのまま使える。', ins: ['1 2 3\n', '2 2\n', '1 4 3 4\n', '5 6\n', '1 1 1\n', '2 3 4 7\n'] })

t({ lv: 718, concept: 'DP: 3次元の箱の入れ子最大', title: '箱の中に箱、最大何重か', tags: ['DP', 'ソート'], io: '1行目に箱の数 n、続く n 行に各箱の3辺 x y z が与えられます(回転不可、各辺が厳密に小さいときだけ中に入る)。', ask: '入れ子にできる箱の最大の重なり数を出力してください。', h1: '2次元の封筒問題の3次元版。', h2: 'xでソートし、(y,z)について「両方厳密に大きい」への最長鎖をO(n²)DPで求める。xの同値に注意。', ref: 'n=int(input())\nboxes=sorted([tuple(map(int,input().split())) for _ in range(n)])\ndp=[1]*n\nfor i in range(n):\n    for j in range(i):\n        if boxes[j][0]<boxes[i][0] and boxes[j][1]<boxes[i][1] and boxes[j][2]<boxes[i][2]:\n            if dp[j]+1>dp[i]:\n                dp[i]=dp[j]+1\nprint(max(dp) if n else 0)', tip: '次元が増えるとソートで消せる軸は1本だけになり、残りは全比較DPに戻る。封筒(2次元)はLISでO(n log n)にできたが3次元は難しくなる、次元の壁。', ins: ['3\n1 1 1\n2 2 2\n3 3 3\n', '2\n1 2 3\n3 2 1\n', '1\n5 5 5\n', '4\n1 1 1\n2 2 1\n2 2 2\n3 3 3\n', '3\n2 2 2\n2 2 2\n2 2 2\n', '5\n1 1 1\n2 2 2\n1 3 3\n3 4 4\n5 5 5\n'] })

t({ lv: 719, concept: 'bitDP: k班分けの最大負荷最小化', title: 'k班に分けて一番重い班を軽く', tags: ['bitDP'], io: '1行目に 人数 n と班数 k (n≤12)、2行目に各人の作業量が与えられます。', ask: '全員をちょうど k 班(空の班は不可)に分けるとき、班ごとの作業量合計の最大値を最小化した値を出力してください。', h1: '部分集合の作業量を前計算する。', h2: 'dp[集合] を「その集合をいくつかの班に分けたときの最小の最大負荷」…ではなく、k回に分けて部分集合を剥がす再帰で全分割を試す。', ref: 'import sys\nsys.setrecursionlimit(100000)\nn,k=map(int,input().split())\na=list(map(int,input().split()))\nssum=[0]*(1<<n)\nfor m in range(1,1<<n):\n    i=(m&-m).bit_length()-1\n    ssum[m]=ssum[m^(1<<i)]+a[i]\nINF=float("inf")\nmemo={}\ndef f(mask,g):\n    if g==1:\n        return ssum[mask]\n    key=(mask,g)\n    if key in memo:\n        return memo[key]\n    low=(mask&-mask)\n    best=INF\n    sub=mask\n    while sub:\n        if sub&low:\n            rest=mask^sub\n            if bin(rest).count("1")>=g-1:\n                c=max(ssum[sub],f(rest,g-1))\n                if c<best:\n                    best=c\n        sub=(sub-1)&mask\n    memo[key]=best\n    return best\nprint(f((1<<n)-1,k))', tip: '「最小番号の人を含む部分集合」だけ試すと班の順序の重複が消える。部分集合の列挙 (sub-1)&mask は集合DPの必修イディオム。', ins: ['4 2\n1 2 3 4\n', '3 3\n5 5 5\n', '2 1\n3 7\n', '5 2\n1 1 1 1 10\n', '4 4\n1 2 3 4\n', '6 3\n2 3 5 7 11 13\n'] })

t({ lv: 720, concept: '貪欲: マッチ棒で作る最大の数', title: 'マッチn本で作れる最大の数', tags: ['貪欲'], io: 'マッチ棒の本数 n (n≥2) が1行で与えられます。', ask: '7セグメント表示(1は2本、7は3本、他も通常の本数)で、ちょうど n 本使って作れる最大の整数を出力してください。', h1: '桁数を最大にするのが最優先。', h2: '1(2本)を並べるのが基本。本数が奇数なら先頭を7(3本)にする。', ref: 'n=int(input())\nif n%2==0:\n    print("1"*(n//2))\nelse:\n    print("7"+"1"*((n-3)//2))', tip: '「桁数最大→辞書順最大」の2段階最適化。奇数の端数を先頭の7で吸収する場合分けだけで、貪欲が厳密最適になる。', ins: ['2\n', '3\n', '4\n', '5\n', '7\n', '10\n'] })

t({ lv: 721, concept: '数え上げ: 出目の積が偶数になる振り方', title: '積が偶数になるサイコロの列', tags: ['数学'], io: 'n k が空白区切りで1行で与えられます(k面サイコロをn回)。', ask: 'n 回の出目の積が偶数になる出目の列の数を出力してください。', h1: '「積が奇数」の方が数えやすい。', h2: '全体 k^n から「全部奇数」((k+1)//2)^n を引く(補集合)。', ref: 'n,k=map(int,input().split())\nodd=(k+1)//2\nprint(k**n-odd**n)', tip: '「少なくとも1つ偶数」は補集合で一撃。確率の余事象と同じ考え方が数え上げでも第一選択になる。', ins: ['1 6\n', '2 6\n', '3 2\n', '1 1\n', '2 3\n', '5 4\n'] })

t({ lv: 722, concept: 'BFS: 障害物ありビショップの最短手数', title: 'ビショップは何手で着けるか', tags: ['BFS'], io: '1行目に H W、続く H 行に盤面(S:開始, G:目標, #:障害物, .:空き)が与えられます。ビショップは斜めに何マスでも滑れます(障害物は飛び越せない)。', ask: 'S から G への最小手数を出力してください。到達できなければ -1。', h1: '1手で行ける先は「4斜め方向の途中の全マス」。', h2: '各方向へ障害物か端まで1マスずつ進み、通過点すべてを隣接としてBFS。', ref: 'from collections import deque\nh,w=map(int,input().split())\ng=[input() for _ in range(h)]\nfor i in range(h):\n    for j in range(w):\n        if g[i][j]=="S":\n            sr,sc=i,j\n        if g[i][j]=="G":\n            gr,gc=i,j\ndist=[[-1]*w for _ in range(h)]\ndist[sr][sc]=0\nq=deque([(sr,sc)])\nwhile q:\n    r,c=q.popleft()\n    for dr,dc in ((1,1),(1,-1),(-1,1),(-1,-1)):\n        nr,nc=r+dr,c+dc\n        while 0<=nr<h and 0<=nc<w and g[nr][nc]!="#":\n            if dist[nr][nc]<0:\n                dist[nr][nc]=dist[r][c]+1\n                q.append((nr,nc))\n            nr+=dr\n            nc+=dc\nprint(dist[gr][gc])', tip: '滑る駒の1手は「線分上の全マス」への辺。マスの色(市松のパリティ)が違うGへは永遠に届かない、という不変量too判定に使える。', ins: ['3 3\nS..\n...\n..G\n', '3 3\nS..\n.#.\n..G\n', '2 2\nS.\n.G\n', '3 3\nS.#\n.#.\n#.G\n', '2 3\nS.G\n...\n', '4 4\nS...\n....\n....\n...G\n'] })

t({ lv: 723, concept: '数え上げ: 3の倍数と3のつく数', title: '3の倍数か3のつく数を数える', tags: ['数学'], io: '正整数 N が1行で与えられます。', ask: '1 以上 N 以下で「3の倍数である」か「十進表記に数字の3を含む」数の個数を出力してください。', h1: '2条件の和集合を数える。', h2: 'or で判定して数えるだけ。大きなNなら包除+桁DPに発展する。', ref: 'n=int(input())\nprint(sum(1 for x in range(1,n+1) if x%3==0 or "3" in str(x)))', tip: '「倍数条件」と「桁の条件」は性質が違うので、大きな範囲では 倍数=床関数、桁=桁DP、重なり=桁DPに剰余状態を足す、と別々の道具で数えて包除する。', ins: ['10\n', '30\n', '1\n', '33\n', '100\n', '2\n'] })

t({ lv: 724, concept: 'bit演算: 1ビット違いの判定', title: '1か所だけビットが違うか', tags: ['bit演算'], io: '非負整数 a b が空白区切りで1行で与えられます。', ask: '2進表記でちょうど1箇所だけビットが異なるなら yes、そうでなければ no を出力してください。', h1: '違いはXORに現れる。', h2: 'a^b が「1ビットだけ立っている」= 0でなく (x&(x−1))==0。', ref: 'a,b=map(int,input().split())\nx=a^b\nprint("yes" if x!=0 and x&(x-1)==0 else "no")', tip: 'x&(x−1) は最下位の1ビットを消す演算。「2のべき判定」「ビット数を数えるKernighan法」など、この1行から派生する技は多い。', ins: ['2 3\n', '5 5\n', '7 5\n', '0 1\n', '8 0\n', '10 2\n'] })

t({ lv: 725, concept: '貪欲: 同色連続から残す1つ', title: '同じ色の連続を1つに間引く最小コスト', tags: ['貪欲'], io: '1行目に色の文字列、2行目に各位置の撤去コストが与えられます。', ask: '同じ色が連続しないよう風船を撤去します。連続する同色の塊ごとに1つだけ残すとき、撤去コストの合計の最小を出力してください。', h1: '塊ごとに考えればよい。', h2: '塊の中で最大コストの1つを残す(=塊の合計−最大)。', ref: 's=input()\ncost=list(map(int,input().split()))\ntotal=0\ni=0\nn=len(s)\nwhile i<n:\n    j=i\n    seg=0\n    mx=0\n    while j<n and s[j]==s[i]:\n        seg+=cost[j]\n        if cost[j]>mx:\n            mx=cost[j]\n        j+=1\n    total+=seg-mx\n    i=j\nprint(total)', tip: '「塊の中で最良を残す」局所最適が全体最適に一致するのは塊どうしが独立だから。問題を独立な部分に割ってから貪欲する2段構えの型。', ins: ['abaac\n1 2 3 4 5\n', 'aabaa\n1 2 3 4 1\n', 'abc\n1 2 3\n', 'aaaa\n3 4 5 1\n', 'a\n9\n', 'aabb\n2 1 1 2\n'] })

t({ lv: 726, concept: 'DP: 行列内の最長増加経路', title: '行列の中の最長増加ルート', tags: ['DP', '再帰'], io: '1行目に H W、続く H 行に行列が与えられます。上下左右に移動でき、値が厳密に増える方向にだけ進めます。', ask: 'たどれる経路の最大の長さ(マス数)を出力してください。', h1: '各マスを始点にした最長をメモ化する。', h2: 'f(r,c) は「より大きい隣」への f の最大+1。増加方向しか進めないので循環せずメモ化が効く。', ref: 'import sys\nsys.setrecursionlimit(100000)\nh,w=map(int,input().split())\ng=[list(map(int,input().split())) for _ in range(h)]\nmemo={}\ndef f(r,c):\n    if (r,c) in memo:\n        return memo[(r,c)]\n    best=1\n    for dr,dc in ((1,0),(-1,0),(0,1),(0,-1)):\n        nr,nc=r+dr,c+dc\n        if 0<=nr<h and 0<=nc<w and g[nr][nc]>g[r][c]:\n            best=max(best,1+f(nr,nc))\n    memo[(r,c)]=best\n    return best\nprint(max(f(r,c) for r in range(h) for c in range(w)))', tip: '「増加」という向きがサイクルを消すので、明示的なトポロジカルソートなしにメモ化だけでDAGのDPになる。暗黙のDAGを見抜くのが鍵。', ins: ['3 3\n9 9 4\n6 6 8\n2 1 1\n', '3 3\n3 4 5\n3 2 6\n2 2 1\n', '1 1\n7\n', '1 4\n1 2 3 4\n', '2 2\n1 1\n1 1\n', '2 3\n1 2 3\n6 5 4\n'] })

t({ lv: 727, concept: '単調スタック: 132パターンの検出', title: '132の形をした3つ組はあるか', tags: ['スタック'], io: '整数列が1行で空白区切りで与えられます。', ask: 'i<j<k で a[i]<a[k]<a[j] となる(132パターンの)3つ組が存在するなら yes、無ければ no を出力してください。', h1: '右から走査して「2になれる値」の最大を追う。', h2: '単調減少スタックからはみ出た(pop された)値が「2の候補」。a[i] がその候補より小さければ完成。', ref: 'a=list(map(int,input().split()))\nst=[]\nsecond=float("-inf")\nans="no"\nfor x in reversed(a):\n    if x<second:\n        ans="yes"\n        break\n    while st and st[-1]<x:\n        second=st.pop()\n    st.append(x)\nprint(ans)', tip: 'popされた値=「自分より左に大きい値がある値」だけが中央の“3”の相方“2”になれる。スタックの捨て値に意味を持たせる逆転の発想が光る一問。', ins: ['1 2 3 4\n', '3 1 4 2\n', '1 3 2\n', '3 5 0 3 4\n', '1 1 1\n', '2 1\n'] })

t({ lv: 728, concept: 'スタック: 余分な括弧の検出', title: '意味のない括弧を見つける', tags: ['スタック'], io: '1行に数式(1桁の数字、+ - * /、丸括弧のみ。空白なし)が与えられます。括弧の対応は取れています。', ask: '「中身を包む必要がない括弧」(空の括弧、または直下に演算子を含まない括弧、例 ((a+b)) の外側や (a))があるなら yes、無ければ no を出力してください。', h1: '閉じ括弧が来たとき、対応する開き括弧までに何があったか。', h2: 'スタックに積み、 ) が来たら開き括弧までpop。間に演算子が1つも無ければ余分。', ref: 's=input()\nst=[]\nans="no"\nfor c in s:\n    if c==")":\n        hasop=False\n        while st and st[-1]!="(":\n            if st.pop() in "+-*/":\n                hasop=True\n        st.pop()\n        if not hasop:\n            ans="yes"\n        st.append("x")\n    else:\n        st.append(c)\nprint(ans)', tip: '構文の冗長性チェックはコンパイラの警告機能そのもの。「対応する開きまでに演算子があったか」という局所情報だけで判定できる。', ins: ['((1+2))\n', '(1+2)\n', '(1)+2\n', '1+(2*3)\n', '((1)+2)\n', '(1+(2))\n'] })

t({ lv: 729, concept: 'ゲーム: 約数を引き合うゲーム', title: '約数を引くゲームの勝者', tags: ['ゲーム'], io: '正整数 n が1行で与えられます。', ask: '2人交互に「今の数の1以上で自分自身より小さい約数」を引きます(1は必ず引ける)。0にできず動けなくなった方…ではなく、n が 1 になって引けなくなった方が負けです。先手必勝なら first、後手必勝なら second を出力してください。', h1: '小さい n で勝敗を実験してみる。', h2: 'n が偶数なら先手必勝、奇数なら後手必勝(奇数の約数は奇数なので、奇数からは奇数しか引けず必ず偶数を渡される)。', ref: 'n=int(input())\nprint("first" if n%2==0 else "second")', tip: '奇数−奇数の約数=偶数、という偶奇の閉じ方だけで勝敗が完全に決まる。ゲームDPを書いて表を眺め、規則を見抜いて式に潰す2段階の楽しみがある。', ins: ['2\n', '3\n', '1\n', '10\n', '7\n', '100\n'] })

t({ lv: 730, concept: 'DP: k個の郵便局の最適配置', title: '郵便局をどこに建てるか', tags: ['DP'], io: '1行目に 家の数 n と郵便局の数 k、2行目に家の座標(昇順)が与えられます。', ask: 'k 個の郵便局を(任意の座標に)建て、各家から最寄り局までの距離の合計を最小化した値を出力してください。', h1: '1つの局が受け持つのは連続した家の区間で、局は中央値に建てるのが最適。', h2: 'cost(i,j)=家i..jを1局で受け持つ費用を前計算し、dp[局数][先頭からの家数]で区切る。', ref: 'n,k=map(int,input().split())\nx=list(map(int,input().split()))\ncost=[[0]*n for _ in range(n)]\nfor i in range(n):\n    for j in range(i+1,n):\n        m=x[(i+j)//2]\n        cost[i][j]=sum(abs(v-m) for v in x[i:j+1])\nINF=float("inf")\ndp=[[INF]*(n+1) for _ in range(k+1)]\ndp[0][0]=0\nfor g in range(1,k+1):\n    for j in range(1,n+1):\n        for i in range(j):\n            if dp[g-1][i]<INF:\n                c=dp[g-1][i]+cost[i][j-1]\n                if c<dp[g][j]:\n                    dp[g][j]=c\nprint(dp[k][n])', tip: '「担当範囲は連続区間」+「1区間の最適は中央値」という2つの構造定理がDPを可能にする。施設配置問題(k-median)の1次元は厳密に解ける。', ins: ['3 1\n1 2 10\n', '4 2\n1 2 9 10\n', '2 2\n3 8\n', '5 1\n1 2 3 4 5\n', '4 1\n0 0 10 10\n', '6 3\n1 2 10 11 20 21\n'] })

t({ lv: 731, concept: '文字列: 各単語が他の何語の部分列か', title: '飛ばし読みで含まれる語を数える', tags: ['文字列'], io: '1行に相異なる英小文字の単語が空白区切りで与えられます。', ask: '各単語について、その単語を部分列として含む他の単語がいくつあるかを、入力順に空白区切りで出力してください。', h1: '部分列の判定は、含む側を左から1回だけ走査して文字を順に拾えるかで決まる。', h2: 'イテレータを1つ作って all(ch in it for ch in a) と書くと、拾った続きから探してくれる。', ref: 'ws=input().split()\ndef issub(a,b):\n    it=iter(b)\n    return all(ch in it for ch in a)\nout=[]\nfor i,w in enumerate(ws):\n    out.append(str(sum(1 for j,x in enumerate(ws) if i!=j and issub(w,x))))\nprint(\' \'.join(out))', tip: '1文字削って作れる単語ペア(同レベル既出)は削除が1回だけだったが、部分列なら何文字でも飛ばせる。イテレータに対する in は「続きから探す」ので、この性質だけで部分列判定が1行になるのがPythonらしい所。', ins: ['ab abc abcd', 'cat dog bird', 'a ab abc', 'xy x y xyz', 'hello he lo helo', 'abc acb bac'] })

t({ lv: 732, concept: 'DP: 重ならない2つの長方形の最大和', title: '2枚の畑の区画で最大の収穫', tags: ['DP', '累積和'], io: '1行目に H W、続く H 行に整数の行列が与えられます。', ask: '重ならない2つの長方形領域の和の合計の最大を出力してください(各長方形は1マス以上)。', h1: '2つの長方形は必ず水平か垂直な直線で分離できる。', h2: '各分割線の上下(左右)それぞれで最大部分長方形和を前計算して足す。小さな盤面なら全列挙でもよい。', ref: 'h,w=map(int,input().split())\ng=[list(map(int,input().split())) for _ in range(h)]\nS=[[0]*(w+1) for _ in range(h+1)]\nfor i in range(h):\n    for j in range(w):\n        S[i+1][j+1]=S[i][j+1]+S[i+1][j]-S[i][j]+g[i][j]\ndef rect(r1,c1,r2,c2):\n    return S[r2+1][c2+1]-S[r1][c2+1]-S[r2+1][c1]+S[r1][c1]\nrects=[]\nfor r1 in range(h):\n    for r2 in range(r1,h):\n        for c1 in range(w):\n            for c2 in range(c1,w):\n                rects.append((r1,c1,r2,c2,rect(r1,c1,r2,c2)))\nbest=None\nfor a in rects:\n    for b in rects:\n        if a[2]<b[0] or b[2]<a[0] or a[3]<b[1] or b[3]<a[1]:\n            v=a[4]+b[4]\n            if best is None or v>best:\n                best=v\nprint(best)', tip: '「重ならない2つ」は分離直線の存在で場合分けすると前計算が効く。全列挙O(R²)→分割線DP O(HW(H+W))への高速化の階段が見える問題。', ins: ['2 2\n1 2\n3 4\n', '1 4\n1 -2 3 4\n', '3 3\n1 1 1\n1 1 1\n1 1 1\n', '2 2\n-1 -2\n-3 -4\n', '2 3\n5 -9 5\n5 -9 5\n', '3 1\n4\n-1\n4\n'] })

t({ lv: 733, concept: '貪欲: ソートできる最大の分割数', title: 'ばらしてソートできる最多チャンク', tags: ['貪欲'], io: '0..n-1 の順列が1行で空白区切りで与えられます。', ask: '列をいくつかの連続チャンクに切り、各チャンクを個別にソートしてから連結すると全体がソート済みになる、そのチャンク数の最大を出力してください。', h1: 'チャンクの切れ目になれる位置の条件を考える。', h2: '位置 i までの最大値がちょうど i なら、そこで切れる。', ref: 'a=list(map(int,input().split()))\nmx=0\ncnt=0\nfor i,x in enumerate(a):\n    if x>mx:\n        mx=x\n    if mx==i:\n        cnt+=1\nprint(cnt)', tip: '順列だからこそ「接頭辞の最大=位置」で完結する判定になる。一般の配列では「接頭辞max ≤ 接尾辞min」の比較に一般化される(LC 768)。', ins: ['1 0 2 3 4\n', '4 3 2 1 0\n', '0 1 2\n', '1 2 0\n', '0\n', '2 0 1 4 3\n'] })

t({ lv: 734, concept: 'DP: 文章の折り返し最小ペナルティ', title: '単語の折り返しで余白を最小に', tags: ['DP'], io: '1行目に 行の幅 W、2行目に各単語の長さの列が与えられます(単語間には空白1つ、どの単語も幅W以下)。', ask: '単語を順に行へ詰めます。各行の余白(W−使用幅)の2乗の合計(最終行は除く)を最小化した値を出力してください。', h1: '行の先頭になる単語で区切るDP。', h2: 'dp[i]=単語iから最後までの最小ペナルティ。iから始まる行に入れる単語数を全て試す。', ref: 'W=int(input())\nw=list(map(int,input().split()))\nn=len(w)\nINF=float("inf")\ndp=[INF]*(n+1)\ndp[n]=0\nfor i in range(n-1,-1,-1):\n    width=-1\n    for j in range(i,n):\n        width+=w[j]+1\n        if width>W:\n            break\n        pen=0 if j==n-1 else (W-width)**2\n        if dp[j+1]<INF and pen+dp[j+1]<dp[i]:\n            dp[i]=pen+dp[j+1]\nprint(dp[0])', tip: 'TeXの美しい段組みはこのDP(最小残余2乗)が原型。貪欲(詰め込めるだけ詰める)が最適でない例を作れるのが2乗ペナルティの妙。', ins: ['6\n3 2 2 5\n', '10\n10\n', '7\n3 3 3\n', '5\n1 1 1 1\n', '8\n4 4 4\n', '6\n2 2 2 2 2\n'] })

t({ lv: 735, concept: 'DP: コスト消費で作る最大の整数', title: '塗料をちょうど使い切る最大の数', tags: ['DP', '貪欲'], io: '1行目に使い切るコスト T、2行目に数字1〜9それぞれを1桁書くのに要るコストが9個与えられます。', ask: 'コストの合計がちょうど T になるように数字を並べて作れる最大の整数を出力してください。作れなければ 0。', h1: 'まず「最大の桁数」をDPで求める。', h2: '桁数が同じなら大きい数字から貪欲に置けるか(残りコストで残り桁数が達成可能か)を確かめながら構築する。', ref: 't=int(input())\ncost=list(map(int,input().split()))\nNEG=-10**9\ndp=[NEG]*(t+1)\ndp[0]=0\nfor v in range(1,t+1):\n    for d in range(9):\n        c=cost[d]\n        if c<=v and dp[v-c]+1>dp[v]:\n            dp[v]=dp[v-c]+1\nif dp[t]<=0:\n    print(0)\nelse:\n    res=[]\n    rem=t\n    for _ in range(dp[t]):\n        for d in range(8,-1,-1):\n            c=cost[d]\n            if c<=rem and dp[rem-c]==dp[rem]-1:\n                res.append(str(d+1))\n                rem-=c\n                break\n    print("".join(res))', tip: '「長さ最大→辞書順最大」は、長さのDP表を証明書にして貪欲構築する2段式。復元時に dp[rem−c]==dp[rem]−1 で正当性を確かめるのが要。', ins: ['5\n2 4 6 2 4 6 4 4 4\n', '2\n9 9 9 9 9 9 9 9 1\n', '1\n2 2 2 2 2 2 2 2 2\n', '4\n2 2 2 2 2 2 2 2 2\n', '3\n1 1 1 1 1 1 1 1 1\n', '10\n3 3 3 3 3 3 3 3 2\n'] })

t({ lv: 736, concept: '配列: 魔方陣の判定', title: '3×3は魔方陣になっているか', tags: ['配列'], io: '3行に3個ずつ整数が与えられます。', ask: '1〜9 が1度ずつ現れ、全ての行・列・対角線の和が等しいなら yes、そうでなければ no を出力してください。', h1: 'まず1〜9の集合と一致するか。', h2: '行3本・列3本・対角2本の和8個が全て同じか。', ref: 'g=[list(map(int,input().split())) for _ in range(3)]\nvals=sorted(v for row in g for v in row)\nok=vals==list(range(1,10))\nif ok:\n    sums=[sum(g[i]) for i in range(3)]+[sum(g[i][j] for i in range(3)) for j in range(3)]\n    sums.append(g[0][0]+g[1][1]+g[2][2])\n    sums.append(g[0][2]+g[1][1]+g[2][0])\n    ok=len(set(sums))==1\nprint("yes" if ok else "no")', tip: '3×3の魔方陣は回転・鏡映を除けば1種類しかなく、中央は必ず5。判定を「集合の一致」と「和の一様性」に分けると読みやすい。', ins: ['2 7 6\n9 5 1\n4 3 8\n', '1 2 3\n4 5 6\n7 8 9\n', '2 7 6\n9 5 1\n4 3 7\n', '4 9 2\n3 5 7\n8 1 6\n', '2 2 2\n2 2 2\n2 2 2\n', '6 1 8\n7 5 3\n2 9 4\n'] })

t({ lv: 737, concept: '数え上げ: 出目が単調増加の列', title: '厳密に増え続けるサイコロの列', tags: ['数学'], io: 'n k が空白区切りで1行で与えられます(k面サイコロをn回)。', ask: '出目が厳密に増加し続ける列の数を出力してください(n>kなら0)。', h1: '厳密増加なら同じ目は使えない。', h2: '出目の集合を選べば並びは1通り。答えは C(k,n)。', ref: 'from math import comb\nn,k=map(int,input().split())\nprint(comb(k,n) if n<=k else 0)', tip: '「厳密増加の列=部分集合」「非減少の列=重複組合せ」という対応は数え上げの基本辞書。列の条件が集合の言葉に翻訳できると一気に楽になる。', ins: ['2 6\n', '3 3\n', '4 3\n', '1 5\n', '2 2\n', '3 10\n'] })

t({ lv: 738, concept: 'DP: 最長の等比連続区間', title: '比が一定で続く最長の区間', tags: ['DP'], io: '正整数列が1行で空白区切りで与えられます。', ask: '隣接する比が一定(等比数列)である連続区間の最大の長さを出力してください(長さ1や2は常に等比とみなす)。', h1: '比の比較は割り算しない。', h2: 'a[i−1]² と a[i]×a[i−2] の比較で「比が続いているか」が整数のまま分かる。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nbest=min(n,2)\nrun=2 if n>=2 else 1\nfor i in range(2,n):\n    if a[i-1]*a[i-1]==a[i]*a[i-2]:\n        run+=1\n    else:\n        run=2\n    if run>best:\n        best=run\nprint(best)', tip: '等差は「差の一致」、等比は「交差積の一致」で浮動小数なしに判定できる。b²=ac は等比中項の関係そのもの。', ins: ['1 2 4 8 3\n', '5 5 5\n', '1 2 3 4\n', '3 6 12 24 48\n', '7\n', '2 4 8 12 18 27\n'] })

t({ lv: 739, concept: '配列: 並べ替えて等差数列にできるか', title: '並べ替えたら等差数列になるか', tags: ['配列', 'ソート'], io: '整数列(2個以上)が1行で空白区切りで与えられます。', ask: '並べ替えて等差数列にできるなら yes、できなければ no を出力してください。', h1: 'ソートすれば並びは決まる。', h2: 'ソート後の隣接差が全て同じか確かめる。', ref: 'a=sorted(map(int,input().split()))\nd=a[1]-a[0]\nprint("yes" if all(a[i+1]-a[i]==d for i in range(len(a)-1)) else "no")', tip: 'ソートで候補を一意化してから性質を検査する2段構え。ソートせずに解くなら min と max から公差を推定して集合で照合するO(n)版もある。', ins: ['3 5 1\n', '1 2 4\n', '7 7 7\n', '10 4 6 8\n', '1 2\n', '0 -3 3 6\n'] })

t({ lv: 740, concept: 'DP: 全1の長方形の総数', title: '1だけでできた長方形を数える', tags: ['DP', 'スタック'], io: '1行目に H W、続く H 行に0/1の行列が与えられます。', ask: '全てのマスが1の長方形(位置・サイズが違えば別)の総数を出力してください。', h1: '各マスで「上に連続する1の高さ」を持つ。', h2: 'そのマスを右下の角とする長方形の数は、左へ見た高さの最小値を足し込むと数えられる。', ref: 'h,w=map(int,input().split())\ng=[list(map(int,input().split())) for _ in range(h)]\nup=[[0]*w for _ in range(h)]\nfor i in range(h):\n    for j in range(w):\n        if g[i][j]:\n            up[i][j]=(up[i-1][j] if i else 0)+1\ntotal=0\nfor i in range(h):\n    for j in range(w):\n        m=up[i][j]\n        k=j\n        while k>=0 and m>0:\n            if up[i][k]<m:\n                m=up[i][k]\n            total+=m\n            k-=1\nprint(total)', tip: '「右下の角を固定して数える」と重複なく全列挙できる。O(HW²)の素朴版から単調スタックでO(HW)へ、ヒストグラム最大長方形と同じ進化を辿る。', ins: ['2 2\n1 1\n1 1\n', '1 3\n1 0 1\n', '2 3\n1 1 0\n1 1 1\n', '2 2\n0 0\n0 0\n', '3 3\n1 1 1\n1 1 1\n1 1 1\n', '1 1\n1\n'] })

export const CATALOG = TASKS
