// 生成タスク 第14波：文字列アルゴリズム2。整数/文字列=採点一意。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 45, concept: '文字列: 最小周期', title: '文字列の最小周期', tags: ['文字列'], io: '文字列 s が与えられます。', ask: 's 全体を「ある部分文字列の繰り返し」で表すときの、最短の繰り返し単位の長さを出力してください。', h1: '長さ p が n を割り切るか。', h2: 's[:p]*(n//p)==s か。', ref: 's=input()\nn=len(s)\nfor p in range(1,n+1):\n    if n%p==0 and s[:p]*(n//p)==s:\n        print(p)\n        break', ins: ['ababab\n', 'abcabc\n', 'aaaa\n', 'abcd\n', 'xyzxyzxyz\n', 'a\n'] })
t({ lv: 150, concept: '文字列: 最長回文部分文字列', title: '最長回文部分文字列の長さ', tags: ['文字列', 'アルゴリズム'], io: '文字列 s が与えられます。', ask: '回文になっている連続部分文字列の最大の長さを出力してください。', h1: '各中心から左右に広げる。', h2: '奇数長・偶数長の2通り。', ref: 's=input()\nbest=0\nfor c in range(len(s)):\n    for a,b in ((c,c),(c,c+1)):\n        while a>=0 and b<len(s) and s[a]==s[b]:\n            a-=1\n            b+=1\n        best=max(best,b-a-1)\nprint(best)', ins: ['babad\n', 'cbbd\n', 'a\n', 'racecar\n', 'abacdfgdcaba\n', 'aaaa\n'], tip: '💡 「中心から広げる」で全回文を O(n²) で調べられる。' })
t({ lv: 45, concept: '文字列: アナグラムの組数', title: 'アナグラムのグループ数', tags: ['文字列', 'set'], io: '空白区切りの単語が1行で与えられます。', ask: '互いにアナグラムな単語を1グループとしたとき、グループの数を出力してください。', h1: '各単語をソートして正規化。', h2: '異なる正規形の数。', ref: "words=input().split()\nprint(len(set(''.join(sorted(w)) for w in words)))", ins: ['eat tea tan ate nat bat\n', 'abc cba bca\n', 'a b c\n', 'listen silent\n', 'x\n', 'aa bb ab ba\n'] })
t({ lv: 45, concept: '文字列: キャメル→スネーク', title: 'キャメルケースをスネークケースに', tags: ['文字列'], io: 'camelCase の識別子 s が与えられます。', ask: '大文字の前に _ を入れて小文字化したスネークケースを出力してください。', h1: '大文字を見つけたら _ +小文字。', h2: '1文字ずつ処理。', ref: "s=input()\nr=''\nfor c in s:\n    if c.isupper():\n        r+='_'+c.lower()\n    else:\n        r+=c\nprint(r)", ins: ['camelCase\n', 'helloWorld\n', 'abc\n', 'myVarName\n', 'aBcD\n', 'noUpper\n'] })
t({ lv: 45, concept: '文字列: スネーク→キャメル', title: 'スネークケースをキャメルケースに', tags: ['文字列', 'split'], io: 'snake_case の識別子 s が与えられます。', ask: '各 _ 区切りの2語目以降の先頭を大文字にしたキャメルケースを出力してください。', h1: "_ で分割。", h2: '2番目以降を capitalize。', ref: "parts=input().split('_')\nprint(parts[0]+''.join(p.capitalize() for p in parts[1:]))", ins: ['snake_case\n', 'hello_world\n', 'abc\n', 'my_var_name\n', 'a_b_c\n', 'no\n'] })
t({ lv: 45, concept: '文字列: 回転の判定', title: 'もう一方の回転か', tags: ['文字列'], io: '2つの文字列が各行で与えられます。', ask: '一方をずらして (回転して) もう一方に一致するなら yes、しないなら no を出力してください。', h1: '長さが同じか確認。', h2: 'b が a+a の部分文字列か。', ref: 'a=input()\nb=input()\nprint("yes" if len(a)==len(b) and b in a+a else "no")', ins: ['abcde\ncdeab\n', 'abc\nbca\n', 'abc\nacb\n', 'aaa\naaa\n', 'abcd\nabdc\n', 'x\nx\n'], tip: '💡 「b は a の回転か」は b in a+a で判定できる。' })
t({ lv: 150, concept: '文字列: 異なる部分文字列の数', title: '異なる部分文字列の個数', tags: ['文字列', 'set'], io: '文字列 s が与えられます。', ask: '連続する部分文字列のうち相異なるものの個数を出力してください。', h1: 'すべての i<=j で s[i:j] を集合に。', h2: '集合の大きさ。', ref: 's=input()\nsub=set()\nfor i in range(len(s)):\n    for j in range(i+1,len(s)+1):\n        sub.add(s[i:j])\nprint(len(sub))', ins: ['abc\n', 'aaa\n', 'abab\n', 'a\n', 'abcd\n', 'aa\n'] })
t({ lv: 45, concept: '文字列: 連続母音の最長', title: '連続する母音の最長の長さ', tags: ['文字列'], io: '英小文字の文字列 s が与えられます。', ask: '母音 (a,i,u,e,o) が連続する最長の長さを出力してください。', h1: '母音で伸ばし子音でリセット。', h2: '最大を更新。', ref: "s=input()\nbest=cur=0\nfor c in s:\n    if c in 'aeiou':\n        cur+=1\n        best=max(best,cur)\n    else:\n        cur=0\nprint(best)", ins: ['beautiful\n', 'xyz\n', 'aeiou\n', 'queue\n', 'rhythm\n', 'aaa\n'] })

export const CATALOG = TASKS
