// 生成タスク 第59波：各レベル2問化フェーズ(14)。lv641〜649, lv651〜665 に2問目を追加。
// グラフ応用/フロー/ナップサック帯。重複なし・決定的・採点一意。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 641, concept: 'ダイクストラ: 重みの積が最小の経路', title: '重みを掛け合わせて最小の経路', tags: ['ダイクストラ'], io: '1行目に n m s t、続く m 行に無向辺 u v w (w≥1) が与えられます。', ask: '経路上の辺の重みの「積」が最小になるときの積を出力してください。到達できなければ -1。', h1: '和の最短路と同じ枠組みが使えるか考える。', h2: '重みが1以上なら積も単調に増えるので、ダイクストラの + を × に替えるだけでよい(初期値は1)。', ref: 'import heapq\nn,m,s,t=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v,w=map(int,input().split())\n    g[u].append((v,w))\n    g[v].append((u,w))\nINF=float("inf")\ndist=[INF]*(n+1)\ndist[s]=1\nh=[(1,s)]\nwhile h:\n    d,x=heapq.heappop(h)\n    if d>dist[x]:\n        continue\n    for y,w in g[x]:\n        nd=d*w\n        if nd<dist[y]:\n            dist[y]=nd\n            heapq.heappush(h,(nd,y))\nprint(dist[t] if dist[t]<INF else -1)', tip: 'ダイクストラは (+,min) に限らず「単調な結合」なら動く(半環の一般化)。対数を取れば積の最短路は和の最短路と同じ、という見方もできる。', ins: ['3 3 1 3\n1 2 2\n2 3 3\n1 3 10\n', '2 1 1 2\n1 2 7\n', '2 0 1 2\n', '4 4 1 4\n1 2 2\n2 4 2\n1 3 5\n3 4 1\n', '3 2 1 3\n1 2 1\n2 3 1\n', '1 0 1 1\n'] })

t({ lv: 642, concept: '木: 3頂点の合流点', title: '3人が木の上で集まる場所', tags: ['木', 'BFS'], io: '1行目に頂点数 n、続く n−1 行に木の辺、最後の行に3頂点 a b c が与えられます。', ask: '3頂点からの距離の合計が最小になる頂点(合流点)の番号を出力してください(木では一意に定まる)。', h1: '3頂点それぞれからBFSで距離を求める。', h2: '距離の和が最小の頂点を選ぶ。木ではこの点は3本のパスの交点になる。', ref: 'from collections import deque\nn=int(input())\ng=[[] for _ in range(n+1)]\nfor _ in range(n-1):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\na,b,c=map(int,input().split())\ndef bfs(s):\n    dist=[-1]*(n+1)\n    dist[s]=0\n    q=deque([s])\n    while q:\n        x=q.popleft()\n        for y in g[x]:\n            if dist[y]<0:\n                dist[y]=dist[x]+1\n                q.append(y)\n    return dist\nda,db,dc=bfs(a),bfs(b),bfs(c)\nbest=min(range(1,n+1),key=lambda v:da[v]+db[v]+dc[v])\nprint(best)', tip: '木では a-b, b-c, a-c の3本のパスがただ1点で交わり、そこが合流点。LCAを使うと (d(a,b)+d(b,c)+d(c,a))/2 の式でも求められる。', ins: ['5\n1 2\n2 3\n3 4\n3 5\n1 4 5\n', '3\n1 2\n2 3\n1 3 2\n', '4\n1 2\n1 3\n1 4\n2 3 4\n', '7\n1 2\n2 3\n3 4\n2 5\n5 6\n6 7\n4 7 1\n', '2\n1 2\n1 2 1\n', '6\n1 2\n2 3\n2 4\n4 5\n4 6\n3 5 6\n'] })

t({ lv: 643, concept: 'グラフ: 塗り分けの検証', title: 'この塗り分けは正しいか', tags: ['グラフ'], io: '1行目に n m、2行目に各頂点の色番号、続く m 行に無向辺が与えられます。', ask: '隣接する2頂点が必ず異なる色になっている(正しい彩色である)なら yes、そうでなければ no を出力してください。', h1: '全ての辺を1本ずつ確かめる。', h2: '両端の色が同じ辺が1本でもあれば no。', ref: 'n,m=map(int,input().split())\ncolor=list(map(int,input().split()))\nok=True\nfor _ in range(m):\n    u,v=map(int,input().split())\n    if color[u-1]==color[v-1]:\n        ok=False\nprint("yes" if ok else "no")', tip: '彩色を「作る」のはNP困難でも「検証」は辺を舐めるだけの線形時間。この非対称こそNP(検証は速い問題のクラス)の定義そのもの。', ins: ['3 3\n1 2 3\n1 2\n2 3\n1 3\n', '3 3\n1 2 1\n1 2\n2 3\n1 3\n', '2 1\n1 1\n1 2\n', '4 4\n1 2 1 2\n1 2\n2 3\n3 4\n4 1\n', '4 0\n1 1 1 1\n', '5 4\n1 2 1 2 1\n1 2\n2 3\n3 4\n4 5\n'] })

t({ lv: 644, concept: 'フロー: 頂点容量つき最大流', title: '中継地に容量がある最大流', tags: ['フロー'], io: '1行目に n m s t、2行目に各頂点の容量(sとtの容量は無視してよい)、続く m 行に有向辺 u v c が与えられます。', ask: '辺の容量に加えて「各頂点を通過できる量」にも上限があるときの、s から t への最大流を出力してください。', h1: '頂点を「入口」と「出口」の2つに分裂させる。', h2: '入口→出口に頂点容量の辺を張り、元の辺は出口→入口へ繋ぐと、ただの最大流になる。', ref: 'from collections import deque,defaultdict\nn,m,s,t=map(int,input().split())\nvc=list(map(int,input().split()))\ncap=defaultdict(int)\nadj=defaultdict(list)\ndef add(u,v,c):\n    if v not in adj[u]:\n        adj[u].append(v)\n    if u not in adj[v]:\n        adj[v].append(u)\n    cap[(u,v)]+=c\nBIG=10**9\nfor v in range(1,n+1):\n    c=BIG if v==s or v==t else vc[v-1]\n    add(v,v+n,c)\nfor _ in range(m):\n    u,v,c=map(int,input().split())\n    add(u+n,v,c)\nS=s\nT=t+n\nflow=0\nwhile True:\n    par={S:None}\n    q=deque([S])\n    while q:\n        x=q.popleft()\n        if x==T:\n            break\n        for y in adj[x]:\n            if y not in par and cap[(x,y)]>0:\n                par[y]=x\n                q.append(y)\n    if T not in par:\n        break\n    b=float("inf")\n    x=T\n    while par[x] is not None:\n        p=par[x]\n        if cap[(p,x)]<b:\n            b=cap[(p,x)]\n        x=p\n    x=T\n    while par[x] is not None:\n        p=par[x]\n        cap[(p,x)]-=b\n        cap[(x,p)]+=b\n        x=p\n    flow+=b\nprint(flow)', tip: '頂点分裂(vertex splitting)は頂点の制約を辺の制約に変える万能変換。点素パス・避難計画・通信の中継容量など応用は幅広い。', ins: ['3 2 1 3\n9 1 9\n1 2 5\n2 3 5\n', '2 1 1 2\n9 9\n1 2 3\n', '4 4 1 4\n9 2 2 9\n1 2 9\n1 3 9\n2 4 9\n3 4 9\n', '3 2 1 3\n9 5 9\n1 2 3\n2 3 9\n', '4 3 1 4\n9 1 1 9\n1 2 9\n2 3 9\n3 4 9\n', '3 3 1 3\n9 2 9\n1 2 9\n2 3 9\n1 3 1\n'] })

t({ lv: 645, concept: 'グラフ: 距離行列から最小の辺数を復元', title: '距離表を作る最少の道路数', tags: ['グラフ'], io: '1行目に n、続く n 行に整合の取れた距離行列(対称・対角0・三角不等式を満たす)が与えられます。', ask: 'この行列を全点対最短距離として実現するグラフに最低限必要な辺の本数を出力してください。', h1: '辺 (i,j) が要らないのはどんなときか。', h2: '中継点 k で d[i][j] が d[i][k]+d[k][j] と等しく書けるなら、その辺は他の道で代用できる。', ref: 'n=int(input())\nd=[list(map(int,input().split())) for _ in range(n)]\ncnt=0\nfor i in range(n):\n    for j in range(i+1,n):\n        needed=True\n        for k in range(n):\n            if k!=i and k!=j and d[i][k]+d[k][j]==d[i][j]:\n                needed=False\n                break\n        if needed:\n            cnt+=1\nprint(cnt)', tip: '距離だけ渡されて構造を復元する逆問題。等号で中継できるペアを削ぎ落とすと、木なら n−1 本がきっちり残る。ネットワークトモグラフィの入り口。', ins: ['3\n0 1 2\n1 0 1\n2 1 0\n', '3\n0 1 1\n1 0 1\n1 1 0\n', '4\n0 1 2 3\n1 0 1 2\n2 1 0 1\n3 2 1 0\n', '2\n0 5\n5 0\n', '4\n0 1 1 2\n1 0 2 1\n1 2 0 1\n2 1 1 0\n', '3\n0 2 3\n2 0 4\n3 4 0\n'] })

t({ lv: 646, concept: 'グラフ: 強連結にする最小追加辺数', title: '全て行き来できるようにする追加辺', tags: ['グラフ', '再帰'], io: '1行目に n m、続く m 行に有向辺が与えられます。', ask: '辺を何本か追加して全体を強連結(どの頂点からどの頂点へも到達可能)にするときの最小追加本数を出力してください。既に強連結なら 0。', h1: '強連結成分に縮約すると閉路のないグラフになる。', h2: '縮約後の「入次数0の成分数」と「出次数0の成分数」の大きい方が答え(成分が1つなら0)。', ref: 'import sys\nsys.setrecursionlimit(100000)\nn,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nrg=[[] for _ in range(n+1)]\nedges=[]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    rg[v].append(u)\n    edges.append((u,v))\nseen=[False]*(n+1)\norder=[]\ndef dfs1(x):\n    seen[x]=True\n    for y in g[x]:\n        if not seen[y]:\n            dfs1(y)\n    order.append(x)\nfor v in range(1,n+1):\n    if not seen[v]:\n        dfs1(v)\ncomp=[0]*(n+1)\nc=0\ndef dfs2(x,c):\n    comp[x]=c\n    for y in rg[x]:\n        if comp[y]==0:\n            dfs2(y,c)\nfor v in reversed(order):\n    if comp[v]==0:\n        c+=1\n        dfs2(v,c)\nif c==1:\n    print(0)\nelse:\n    indeg=[0]*(c+1)\n    outdeg=[0]*(c+1)\n    for u,v in edges:\n        if comp[u]!=comp[v]:\n            outdeg[comp[u]]+=1\n            indeg[comp[v]]+=1\n    src=sum(1 for i in range(1,c+1) if indeg[i]==0)\n    snk=sum(1 for i in range(1,c+1) if outdeg[i]==0)\n    print(max(src,snk))', tip: '答えが max(源の数, 汇の数) になるのは、汇から源へ辺を渡していけば両方を同時に1ずつ消せるから。縮約→DAGの形を見る、が有向グラフ設計の定石。', ins: ['3 2\n1 2\n2 3\n', '3 3\n1 2\n2 3\n3 1\n', '4 2\n1 2\n3 4\n', '2 0\n', '5 4\n1 2\n2 1\n3 4\n4 5\n', '6 6\n1 2\n2 3\n3 1\n4 5\n5 6\n6 4\n'] })

t({ lv: 647, concept: 'グラフ: ある頂点が並べる最も早い順位', title: 'トポロジカル順での最良の順位', tags: ['グラフ'], io: '1行目に n m k、続く m 行に閉路のない有向辺(u が v より先)が与えられます。', ask: 'あり得る全てのトポロジカル順序の中で、頂点 k が取れる最も早い順位(1始まり)を出力してください。', h1: 'k より前に必ず来る頂点はどれか。', h2: 'k の先祖(k に到達できる頂点)は必ず前に来るし、それ以外は後に回せる。答えは先祖の数+1。', ref: 'from collections import deque\nn,m,k=map(int,input().split())\nrg=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    rg[v].append(u)\nseen=[False]*(n+1)\nseen[k]=True\nq=deque([k])\ncnt=0\nwhile q:\n    x=q.popleft()\n    for y in rg[x]:\n        if not seen[y]:\n            seen[y]=True\n            cnt+=1\n            q.append(y)\nprint(cnt+1)', tip: '「必ず前に来るのは先祖だけ」で下限が決まり、先祖以外を全部後回しにする順序で達成できる。可能性の範囲を上下から挟む論法の好例。', ins: ['4 3 4\n1 2\n2 4\n3 4\n', '4 3 1\n1 2\n2 4\n3 4\n', '3 0 2\n', '5 4 3\n1 3\n2 3\n3 4\n3 5\n', '2 1 2\n1 2\n', '6 5 6\n1 2\n2 3\n3 6\n4 6\n5 6\n'] })

t({ lv: 648, concept: 'bitDP: 依存つきプロジェクト選択', title: '前提つき案件の利益最大化', tags: ['bitDP'], io: '1行目に案件数 n と依存数 m (n≤15)、2行目に各案件の利益(負もある)、続く m 行に「a をやるには b が必要」が与えられます。', ask: '依存を全て満たすように案件の集合を選ぶ(何も選ばなくてもよい)ときの利益合計の最大を出力してください。', h1: '選んだ集合が「閉じている」かを確かめる。', h2: '全部分集合を試し、含まれる各案件の前提も全て含まれていれば合計を候補にする。', ref: 'n,m=map(int,input().split())\np=list(map(int,input().split()))\nneed=[0]*n\nfor _ in range(m):\n    a,b=map(int,input().split())\n    need[a-1]|=1<<(b-1)\nbest=0\nfor mask in range(1<<n):\n    ok=True\n    x=mask\n    while x:\n        i=(x&-x).bit_length()-1\n        if need[i]&~mask:\n            ok=False\n            break\n        x&=x-1\n    if ok:\n        s=sum(p[i] for i in range(n) if mask>>i&1)\n        if s>best:\n            best=s\nprint(best)', tip: '大規模なら最大流の最小カットで解ける閉包問題(project selection)。「前提のビットが mask からはみ出ていないか」は need & ~mask 一発で見える。', ins: ['3 1\n5 -2 3\n1 2\n', '2 1\n10 -3\n1 2\n', '3 2\n-1 -1 8\n3 2\n2 1\n', '2 0\n-5 -7\n', '4 2\n4 4 -3 -3\n1 3\n2 4\n', '3 3\n6 -2 -2\n1 2\n2 3\n1 3\n'] })

t({ lv: 649, concept: '木: ジグザグ順の出力', title: '深さごとに往復しながら読む', tags: ['木', 'BFS'], io: '1行目に頂点数 n (根は1、n≥2)、2行目に頂点2..nの親が与えられます。', ask: '各深さの頂点を、深さ1は左から(番号の小さい順)、深さ2は右から、と交互に向きを変えて並べた列(ジグザグ順)を空白区切りで出力してください。', h1: '深さごとに頂点を集める。', h2: '偶数番目の深さだけ逆順にして連結する。', ref: 'from collections import deque\nn=int(input())\npar=[0,0]+list(map(int,input().split()))\nch=[[] for _ in range(n+1)]\nfor v in range(2,n+1):\n    ch[par[v]].append(v)\nlevels=[]\nq=deque([(1,0)])\nwhile q:\n    x,d=q.popleft()\n    if d==len(levels):\n        levels.append([])\n    levels[d].append(x)\n    for c in sorted(ch[x]):\n        q.append((c,d+1))\nout=[]\nfor i,lv in enumerate(levels):\n    out.extend(lv if i%2==0 else lv[::-1])\nprint(*out)', tip: 'レベルごとの反転は「後で向きを変える」方が、探索中に交互ロジックを混ぜるより単純で間違えにくい。収集と整形を分けるのは実装の一般則。', ins: ['5\n1 1 2 2\n', '3\n1 1\n', '7\n1 1 2 2 3 3\n', '4\n1 2 3\n', '6\n1 1 2 2 3\n', '2\n1\n'] })

t({ lv: 651, concept: '行列: 全ての1を覆う最小の線の数', title: '1を消すための最少の線', tags: ['全探索'], io: '1行目に H W、続く H 行に0/1の行列が与えられます。', ask: '行全体か列全体を選んで線を引き、全ての1を少なくとも1本の線で覆うときの最小の線の本数を出力してください。', h1: '行と列の選び方を全部試す。', h2: '行の集合を決めると、覆われない1が残る列は全て選ぶしかない。', ref: 'h,w=map(int,input().split())\ng=[list(map(int,input().split())) for _ in range(h)]\nbest=h+w\nfor mask in range(1<<h):\n    cols=set()\n    for i in range(h):\n        if not mask>>i&1:\n            for j in range(w):\n                if g[i][j]:\n                    cols.add(j)\n    total=bin(mask).count("1")+len(cols)\n    if total<best:\n        best=total\nprint(best)', tip: 'ケーニグの定理により、最小の線の数は「1を頂点マッチングと見たときの最大マッチング」に等しい。ハンガリー法(割当問題)の中でこの被覆が使われる。', ins: ['3 3\n1 0 0\n0 1 0\n0 0 1\n', '2 2\n1 1\n1 1\n', '3 3\n1 1 1\n1 0 0\n1 0 0\n', '2 3\n0 0 0\n0 0 0\n', '2 2\n1 0\n0 0\n', '3 4\n1 1 1 1\n0 1 0 0\n0 1 0 0\n'] })

t({ lv: 652, concept: 'フロー: 供給と需要を満たせるか', title: '工場から店へ全て届けられるか', tags: ['フロー'], io: '1行目に 工場数 a 店舗数 b 道路数 e、2行目に各工場の供給量、3行目に各店舗の需要量、続く e 行に「工場 u から店 v へ容量 c」が与えられます。', ask: '道路の容量の範囲で全店舗の需要を満たせるなら yes、満たせなければ no を出力してください。', h1: '仮想の始点と終点を作る。', h2: '始点→工場に供給量、店→終点に需要量の辺を張り、最大流が需要の合計に届くか見る。', ref: 'from collections import deque,defaultdict\na,b,e=map(int,input().split())\nsup=list(map(int,input().split()))\ndem=list(map(int,input().split()))\ncap=defaultdict(int)\nadj=defaultdict(list)\ndef add(u,v,c):\n    if v not in adj[u]:\n        adj[u].append(v)\n    if u not in adj[v]:\n        adj[v].append(u)\n    cap[(u,v)]+=c\nS=0\nT=a+b+1\nfor i in range(1,a+1):\n    add(S,i,sup[i-1])\nfor j in range(1,b+1):\n    add(a+j,T,dem[j-1])\nfor _ in range(e):\n    u,v,c=map(int,input().split())\n    add(u,a+v,c)\nflow=0\nwhile True:\n    par={S:None}\n    q=deque([S])\n    while q:\n        x=q.popleft()\n        if x==T:\n            break\n        for y in adj[x]:\n            if y not in par and cap[(x,y)]>0:\n                par[y]=x\n                q.append(y)\n    if T not in par:\n        break\n    bl=float("inf")\n    x=T\n    while par[x] is not None:\n        p=par[x]\n        if cap[(p,x)]<bl:\n            bl=cap[(p,x)]\n        x=p\n    x=T\n    while par[x] is not None:\n        p=par[x]\n        cap[(p,x)]-=bl\n        cap[(x,p)]+=bl\n        x=p\n    flow+=bl\nprint("yes" if flow==sum(dem) else "no")', tip: '複数の源と汇は「スーパー源・スーパー汇」で1対1に束ねるのが定番。供給・需要・輸送路の三層構造は物流ネットワークの基本形。', ins: ['1 1 1\n5\n3\n1 1 4\n', '1 1 1\n2\n3\n1 1 9\n', '2 2 3\n3 3\n2 4\n1 1 2\n2 2 4\n1 2 1\n', '2 1 2\n1 1\n2\n1 1 1\n2 1 1\n', '1 2 2\n5\n2 2\n1 1 2\n1 2 1\n', '2 2 2\n4 4\n4 4\n1 1 4\n2 2 4\n'] })

t({ lv: 653, concept: 'マッチング: 欠けた盤面のドミノ最大数', title: '穴あき盤に置けるドミノの数', tags: ['マッチング'], io: '1行目に H W、続く H 行に盤面(.は空き、#は穴)が与えられます。', ask: '1×2のドミノ(縦横自由)を空きマスに重ならないように置くときの最大枚数を出力してください。', h1: '市松模様に塗ると、ドミノは必ず白黒1マスずつ覆う。', h2: '白マスと黒マスの2部マッチング。増加道を探す標準の方法で最大マッチングを求める。', ref: 'h,w=map(int,input().split())\ng=[input() for _ in range(h)]\nmatchv={}\ndef ok(r,c):\n    return 0<=r<h and 0<=c<w and g[r][c]=="."\ndef aug(u,seen):\n    for dr,dc in ((1,0),(-1,0),(0,1),(0,-1)):\n        v=(u[0]+dr,u[1]+dc)\n        if ok(v[0],v[1]) and v not in seen:\n            seen.add(v)\n            if v not in matchv or aug(matchv[v],seen):\n                matchv[v]=u\n                return True\n    return False\ncnt=0\nfor r in range(h):\n    for c in range(w):\n        if g[r][c]=="." and (r+c)%2==0:\n            if aug((r,c),set()):\n                cnt+=1\nprint(cnt)', tip: '盤面のマッチングは「白側からだけ増加道を探す」のがコツ。穴が偶奇のバランスを崩すと置けない枚数が発生する、市松塗りの威力が見える問題。', ins: ['2 2\n..\n..\n', '1 3\n...\n', '2 2\n#.\n.#\n', '3 3\n...\n.#.\n...\n', '1 1\n.\n', '2 3\n..#\n...\n'] })

t({ lv: 654, concept: 'DP: 重さと体積の二重制約ナップサック', title: '重さも体積も限られたリュック', tags: ['DP'], io: '1行目に 品数 n 重さ上限 W 体積上限 V、続く n 行に各品の「重さ 体積 価値」が与えられます。', ask: '重さの合計が W 以下かつ体積の合計が V 以下になるように品を選ぶ(各1回)ときの価値合計の最大を出力してください。', h1: 'dp[重さ][体積] の2次元で持つ。', h2: '0/1なので両方の添字を降順に更新する。', ref: 'n,W,V=map(int,input().split())\ndp=[[0]*(V+1) for _ in range(W+1)]\nfor _ in range(n):\n    w,v,val=map(int,input().split())\n    for i in range(W,w-1,-1):\n        for j in range(V,v-1,-1):\n            c=dp[i-w][j-v]+val\n            if c>dp[i][j]:\n                dp[i][j]=c\nprint(dp[W][V])', tip: '制約が1つ増えるごとにDP表の次元が1つ増える。0/1の「降順走査」は次元がいくつでも全ての添字に適用する、が鉄則。', ins: ['3 5 5\n2 3 4\n3 2 5\n4 4 9\n', '1 1 1\n2 2 10\n', '2 4 4\n2 2 3\n2 2 3\n', '3 10 2\n5 1 10\n5 1 10\n5 1 10\n', '2 3 3\n3 3 7\n1 1 2\n', '1 0 0\n1 1 5\n'] })

t({ lv: 655, concept: 'DP: グループから1つずつのナップサック', title: 'カテゴリごとに1つまで選ぶ買い物', tags: ['DP'], io: '1行目に グループ数 g と予算 W。続いて各グループについて「品数 k」の行と、k 行の「重さ 価値」が与えられます。', ask: '各グループから高々1品だけ選び、重さ合計 W 以下で価値合計を最大化した値を出力してください。', h1: 'グループ単位でDPを1段ずつ進める。', h2: '同じグループ内の品どうしが両立しないよう、前の段の表からだけ遷移する。', ref: 'g,W=map(int,input().split())\ndp=[0]*(W+1)\nfor _ in range(g):\n    k=int(input())\n    items=[tuple(map(int,input().split())) for _ in range(k)]\n    nd=dp[:]\n    for w,v in items:\n        for i in range(W,w-1,-1):\n            c=dp[i-w]+v\n            if c>nd[i]:\n                nd[i]=c\n    dp=nd\nprint(dp[W])', tip: 'グループ内の排他は「古い表からのみ遷移して段ごとに差し替える」ことで自然に表せる。装備選択・献立作成など現実の選択はたいていこの形。', ins: ['2 5\n2\n2 3\n3 4\n1\n2 5\n', '1 3\n2\n2 10\n3 12\n', '2 4\n1\n5 100\n1\n2 7\n', '3 6\n1\n2 4\n1\n2 4\n1\n2 4\n', '1 0\n1\n1 9\n', '2 6\n2\n3 5\n4 9\n2\n2 3\n3 6\n'] })

t({ lv: 656, concept: '貪欲: 部分集合で作れない最小の和', title: '作れない最小の金額', tags: ['貪欲'], io: '正整数の列(硬貨、各1枚)が1行で空白区切りで与えられます。', ask: 'いくつかを選んだ合計として作れない最小の正整数を出力してください。', h1: 'ソートして小さい方から考える。', h2: '「1..reach が全部作れる」とき、次の硬貨 x が reach+1 以下なら reach+x まで伸びる。超えたら reach+1 が作れない。', ref: 'a=sorted(map(int,input().split()))\nreach=0\nfor x in a:\n    if x>reach+1:\n        break\n    reach+=x\nprint(reach+1)', tip: '区間 [1,reach] を保ちながら伸ばす美しい貪欲(O(n log n))。DPで2^n通り調べる問題が、不変条件ひとつで一次走査に潰れる。', ins: ['1 2 4\n', '1 1 1\n', '2 3\n', '1 2 2 5\n', '1\n', '1 1 3 9\n'] })

t({ lv: 657, concept: 'DP: 和Tを作る最小の要素数', title: '最少の枚数でちょうどTを作る(各1枚)', tags: ['DP'], io: '1行目に目標 T、2行目に正整数の列(各1回まで使用可)が与えられます。', ask: 'いくつか選んで合計をちょうど T にするときの最小の個数を出力してください。作れなければ -1。', h1: '硬貨の最小枚数と似ているが「各1回」が違う。', h2: 'dp[和] を最小個数として、要素ごとに和を降順に更新する(0/1の型)。', ref: 't=int(input())\na=list(map(int,input().split()))\nINF=10**9\ndp=[0]+[INF]*t\nfor x in a:\n    for v in range(t,x-1,-1):\n        if dp[v-x]+1<dp[v]:\n            dp[v]=dp[v-x]+1\nprint(dp[t] if dp[t]<INF else -1)', tip: '「無制限なら昇順、各1回なら降順」の走査方向が唯一の違い。目的関数(可否・通り数・最小個数)を替えても骨格は同じ、がナップサック族の見取り図。', ins: ['6\n1 2 3 4\n', '11\n5 5 1\n', '4\n1 1 1 1\n', '7\n2 4\n', '0\n3 5\n', '10\n5 5\n'] })

t({ lv: 658, concept: '数学: 連続する平方数の和で表せるか', title: '連続平方和で書けるか', tags: ['数学'], io: '正整数 n が1行で与えられます。', ask: 'n を「連続する2個以上の正の平方数の和」(例 14 は 1+4+9)で表せるなら yes、表せなければ no を出力してください。', h1: '開始点 a を全て試す。', h2: 'a² から順に足していき、n に一致すれば yes、超えたら次の a へ。', ref: 'n=int(input())\nans="no"\na=1\nwhile a*a<n:\n    s=0\n    b=a\n    while s<n:\n        s+=b*b\n        b+=1\n        if s==n and b-a>=2:\n            ans="yes"\n    a+=1\nprint(ans)', tip: '二重ループの全探索だが、内側は超えたら即打ち切るので実質は軽い。「連続和」系は先頭と長さの2変数を回すのが型で、平方でも立方でも同じ。', ins: ['5\n', '14\n', '29\n', '3\n', '50\n', '30\n'] })

t({ lv: 659, concept: 'DP: コスト付き操作でnを作る', title: '足すか2倍するかの最小コスト', tags: ['DP'], io: 'n a b が空白区切りで1行で与えられます(+1のコストが a、2倍のコストが b)。', ask: '0 から始めて「+1」(コストa)と「2倍」(コストb)だけで n を作る最小コストを出力してください。', h1: '前からは分岐が多い。n から逆にたどる。', h2: '偶数なら「半分にする(元の2倍)」か「1引く」、奇数なら「1引く」。dp を n から 0 へ。', ref: 'n,a,b=map(int,input().split())\nINF=float("inf")\ndp=[INF]*(n+1)\ndp[0]=0\nfor v in range(1,n+1):\n    dp[v]=dp[v-1]+a\n    if v%2==0 and dp[v//2]+b<dp[v]:\n        dp[v]=dp[v//2]+b\nprint(dp[n])', tip: '操作の逆再生(nから0へ)で状態空間が一本道になる。コストの比 a:b によって最適な戦略が切り替わる様子をDPが自動で吸収してくれる。', ins: ['10 1 1\n', '1 5 1\n', '8 3 1\n', '7 2 10\n', '0 4 4\n', '15 1 2\n'] })

t({ lv: 660, concept: 'DP: 最大価値の達成通り数', title: 'ナップサック最適解は何通りか', tags: ['DP'], io: '1行目に 品数 n と重さ上限 W、続く n 行に「重さ 価値」が与えられます。', ask: '重さ W 以下で価値合計を最大にする選び方(部分集合)が何通りあるかを出力してください(最大価値が0なら空集合なども数える)。', h1: '価値の最大と通り数を2本のDPで並走させる。', h2: '更新時「より良ければ通り数を引き継ぎ、同点なら加算」。', ref: 'n,W=map(int,input().split())\nval=[0]*(W+1)\ncnt=[1]*(W+1)\nfor _ in range(n):\n    w,v=map(int,input().split())\n    for i in range(W,w-1,-1):\n        nv=val[i-w]+v\n        if nv>val[i]:\n            val[i]=nv\n            cnt[i]=cnt[i-w]\n        elif nv==val[i]:\n            cnt[i]+=cnt[i-w]\nprint(cnt[W])', tip: 'cnt[i] の初期値1は「何も入れない選び方」。最適値+個数のペアDPは、最短路の本数や最長路の本数と全く同じ骨組みで書ける。', ins: ['3 5\n2 3\n3 4\n2 3\n', '2 3\n2 5\n2 5\n', '1 1\n2 9\n', '2 4\n2 3\n2 3\n', '3 6\n2 4\n2 4\n2 4\n', '2 2\n1 1\n1 1\n'] })

t({ lv: 661, concept: 'デック: 窓内最大を使う跳びDP', title: 'k歩以内ジャンプの最大スコア', tags: ['DP', 'デック'], io: '1行目に最大歩幅 k、2行目に各マスの得点(負もある)が与えられます。先頭のマスから開始し、毎回1〜k歩先へ進みます。', ask: '最後のマスに到達するまでに通ったマスの得点合計(最初と最後を含む)の最大を出力してください。', h1: 'dp[i] は「直前 k 個の dp の最大 + 得点」。', h2: '直前k個の最大は単調減少デックで O(1) ずつ取れる。', ref: 'from collections import deque\nk=int(input())\na=list(map(int,input().split()))\nn=len(a)\ndp=[0]*n\ndp[0]=a[0]\ndq=deque([0])\nfor i in range(1,n):\n    while dq and dq[0]<i-k:\n        dq.popleft()\n    dp[i]=dp[dq[0]]+a[i]\n    while dq and dp[dq[-1]]<=dp[i]:\n        dq.pop()\n    dq.append(i)\nprint(dp[n-1])', tip: 'DPの遷移が「区間の最大」のとき、単調デックを併走させると全体O(n)になる。素朴なO(nk)から一段上がるスライド窓最適化の入門。', ins: ['2\n1 -1 -2 4 -7 3\n', '1\n1 2 3\n', '3\n1 -5 -20 4 -1 3 -6 -3\n', '2\n5\n', '2\n10 -5 -2 4 0 3\n', '1\n1 -2 -3 -4\n'] })

t({ lv: 662, concept: 'DP: 市松模様の最大正方形', title: '白黒交互の最大正方形', tags: ['DP'], io: '1行目に H W、続く H 行に0/1の行列が与えられます。', ask: '縦横に隣接するマスの値が必ず異なる(市松模様になっている)正方形の最大の辺の長さを出力してください。', h1: '右下の角ごとに「そこで終わる最大の市松正方形」を考える。', h2: '左・上と違い、左上と同じ値なら dp を伸ばせる。だめなら1。', ref: 'h,w=map(int,input().split())\ng=[list(map(int,input().split())) for _ in range(h)]\ndp=[[1]*w for _ in range(h)]\nbest=1\nfor i in range(1,h):\n    for j in range(1,w):\n        if g[i][j]!=g[i][j-1] and g[i][j]!=g[i-1][j] and g[i][j]==g[i-1][j-1]:\n            dp[i][j]=min(dp[i-1][j],dp[i][j-1],dp[i-1][j-1])+1\n            if dp[i][j]>best:\n                best=dp[i][j]\nprint(best)', tip: '最大正方形DPの「全部1」条件を「局所パターンの整合」に差し替えた形。min+1 の合成則は条件が局所的でさえあれば使い回せる。', ins: ['3 3\n0 1 0\n1 0 1\n0 1 0\n', '2 2\n1 1\n1 1\n', '1 4\n0 1 0 1\n', '3 4\n0 1 0 1\n1 0 1 0\n0 1 1 0\n', '2 2\n0 1\n1 0\n', '1 1\n1\n'] })

t({ lv: 663, concept: 'DP: 経路の文字列を辞書順最小に', title: '数字を拾いながら最小の文字列で到達', tags: ['DP'], io: '1行目に H W、続く H 行に数字(0〜9)だけの行が与えられます(空白なし)。左上から右下へ、右か下にのみ進みます。', ask: '通ったマスの数字を並べた文字列が辞書順最小になるときの、その文字列を出力してください。', h1: '同じ歩数で到達できるマスは斜めの線上に並ぶ。', h2: '斜めの線ごとに「最小の数字を持つマスたち」だけ残して進めると、全体が辞書順最小になる。', ref: 'h,w=map(int,input().split())\ng=[input() for _ in range(h)]\ncur={(0,0)}\nres=[g[0][0]]\nfor _ in range(h+w-2):\n    nxt=set()\n    for r,c in cur:\n        if r+1<h:\n            nxt.add((r+1,c))\n        if c+1<w:\n            nxt.add((r,c+1))\n    mn=min(g[r][c] for r,c in nxt)\n    res.append(mn)\n    cur={(r,c) for r,c in nxt if g[r][c]==mn}\nprint("".join(res))', tip: '「候補の波面を持ち、各段で最良のものだけ生かす」多点同時の貪欲。1本の経路を追うのでなく最良フロンティアを転がすのが肝。', ins: ['2 2\n12\n34\n', '2 3\n199\n111\n', '1 4\n2024\n', '3 3\n111\n999\n111\n', '2 2\n55\n55\n', '3 2\n12\n30\n45\n'] })

t({ lv: 664, concept: 'DP: 2×nマスの隣接禁止最大和', title: '2段の畑から隣り合わずに収穫', tags: ['DP'], io: '1行目に列数 n、続く2行に 2×n の畑の価値が与えられます。', ask: '上下・左右に隣接するマスを同時に選ばないように選ぶときの、価値合計の最大を出力してください。', h1: '列ごとに「選ばない/上を選ぶ/下を選ぶ」の3状態。', h2: '上を選んだ列の次は「下か無し」、と状態遷移で隣接禁止を守る。', ref: 'n=int(input())\ntop=list(map(int,input().split()))\nbot=list(map(int,input().split()))\nnone_=0\nup=top[0]\ndown=bot[0]\nfor i in range(1,n):\n    n2=max(none_,up,down)\n    u2=max(none_,down)+top[i]\n    d2=max(none_,up)+bot[i]\n    none_,up,down=n2,u2,d2\nprint(max(none_,up,down))', tip: '2×nの盤は「列の状態」を持つDPの最小モデル。行が増えたら状態が2^行のビットマスクになる、輪郭線DPへの入り口。', ins: ['3\n1 2 3\n4 5 6\n', '1\n7\n3\n', '2\n5 1\n1 5\n', '4\n9 1 1 9\n1 9 9 1\n', '2\n0 0\n0 0\n', '3\n10 1 10\n1 10 1\n'] })

t({ lv: 665, concept: 'DP: 自由長2区間の最大和', title: '重ならない2つの区間の最大和(長さ自由)', tags: ['DP'], io: '整数列(負もある)が1行で空白区切りで与えられます(要素は2個以上)。', ask: '重ならない空でない2つの連続部分配列の和の合計の最大を出力してください。', h1: '分割点を全て試す。', h2: '「i以前で終わる最大部分和」と「iより後で始まる最大部分和」を前後からKadaneで前計算して足す。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nleft=[0]*n\ncur=-10**18\nbest=-10**18\nfor i in range(n):\n    cur=max(a[i],cur+a[i])\n    best=max(best,cur)\n    left[i]=best\nright=[0]*n\ncur=-10**18\nbest=-10**18\nfor i in range(n-1,-1,-1):\n    cur=max(a[i],cur+a[i])\n    best=max(best,cur)\n    right[i]=best\nprint(max(left[i]+right[i+1] for i in range(n-1)))', tip: '「前からの最良」と「後ろからの最良」を配列で持ち、境界で突き合わせる前後前計算はKadaneに限らず区間2分割問題の万能骨格。', ins: ['1 2 -5 3 4\n', '1 1\n', '-1 -2 -3\n', '5 -100 5\n', '2 -1 2 -1 2\n', '3 -2 5 -1 4 -3 2\n'] })

export const CATALOG = TASKS
