// 生成タスク 第41波：lv751〜799。lv750(DP応用)とlv800(高度なデータ構造)の橋渡し。
// 数列クエリ/累積和・いもす法/しゃくとり/集合・辞書の応用/数え上げDPの本物の別問題。
// 重複なし・決定的・採点一意(整数/文字列/列出力のみ)。無限ループ無し。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 751, concept: '累積和: 区間和クエリの総和', title: '区間和クエリの結果の総和', tags: ['累積和'], io: '1行目に n q、2行目に n 個の値、続く q 行に l r(0始まり・両端含む)が与えられます。', ask: 'すべてのクエリの区間和の合計を出力してください。', h1: '累積和 pre を前計算する。', h2: '区間和 = pre[r+1]-pre[l]。', ref: 'first=input().split()\nn=int(first[0])\nq=int(first[1])\na=list(map(int,input().split()))\npre=[0]*(n+1)\nfor i in range(n):\n    pre[i+1]=pre[i]+a[i]\ntotal=0\nfor _ in range(q):\n    l,r=map(int,input().split())\n    total+=pre[r+1]-pre[l]\nprint(total)', tip: '累積和は区間和を O(1) で。pre[i] に先頭 i 個の和を入れておくのが定石。', ins: ['5 2\n1 2 3 4 5\n0 4\n1 3\n', '3 1\n10 20 30\n0 2\n', '1 1\n7\n0 0\n', '4 2\n1 1 1 1\n0 1\n2 3\n', '5 1\n-1 -2 -3 -4 -5\n0 4\n', '3 3\n5 5 5\n0 0\n1 1\n2 2\n'] })

t({ lv: 752, concept: 'いもす法: 区間加算後の最大値', title: '区間加算を重ねた最大値', tags: ['累積和'], io: '1行目に n q、続く q 行に l r v(区間[l,r]に v を加算、0始まり)が与えられます。', ask: 'すべての加算後の配列の最大値を出力してください。', h1: '差分配列に +v と -v を置く。', h2: '累積和を取って最大を求める(いもす法)。', ref: 'first=input().split()\nn=int(first[0])\nq=int(first[1])\ndiff=[0]*(n+1)\nfor _ in range(q):\n    l,r,v=map(int,input().split())\n    diff[l]+=v\n    diff[r+1]-=v\ncur=0\nbest=0\nfor i in range(n):\n    cur+=diff[i]\n    if cur>best:\n        best=cur\nprint(best)', tip: 'いもす法は区間加算を差分の2点だけで表し、最後に1回の累積和で復元する O(n+q)。', ins: ['5 2\n0 2 1\n1 3 2\n', '3 1\n0 2 5\n', '1 1\n0 0 7\n', '4 3\n0 0 1\n1 1 1\n2 2 1\n', '5 2\n0 4 1\n2 2 10\n', '3 2\n0 1 1\n1 2 1\n'] })

t({ lv: 753, concept: '累積和: 2次元領域和', title: '2次元区間和クエリの総和', tags: ['累積和'], io: '1行目に R C q、続く R 行に C 個の値、続く q 行に r1 c1 r2 c2(0始まり・両端含む)が与えられます。', ask: 'すべての矩形領域和の合計を出力してください。', h1: '2次元累積和を前計算する。', h2: '包除で矩形和を O(1) で求める。', ref: 'first=input().split()\nR=int(first[0])\nC=int(first[1])\nq=int(first[2])\ng=[list(map(int,input().split())) for _ in range(R)]\npre=[[0]*(C+1) for _ in range(R+1)]\nfor i in range(R):\n    for j in range(C):\n        pre[i+1][j+1]=pre[i][j+1]+pre[i+1][j]-pre[i][j]+g[i][j]\ntotal=0\nfor _ in range(q):\n    r1,c1,r2,c2=map(int,input().split())\n    s=pre[r2+1][c2+1]-pre[r1][c2+1]-pre[r2+1][c1]+pre[r1][c1]\n    total+=s\nprint(total)', tip: '2次元累積和は包除原理で矩形和を O(1)。pre[i][j] は左上 i×j の和。', ins: ['2 2 1\n1 2\n3 4\n0 0 1 1\n', '3 3 1\n1 1 1\n1 1 1\n1 1 1\n1 1 2 2\n', '1 1 1\n5\n0 0 0 0\n', '2 3 2\n1 2 3\n4 5 6\n0 0 0 2\n1 0 1 2\n', '2 2 1\n1 0\n0 1\n0 0 1 1\n', '3 3 1\n1 2 3\n4 5 6\n7 8 9\n0 0 2 2\n'] })

t({ lv: 754, concept: 'しゃくとり: 積がk未満の部分配列数', title: '積がk未満の連続部分配列の数', tags: ['二ポインタ'], io: '1行目に k、2行目に正整数列が与えられます。', ask: '要素の積が k 未満になる連続部分配列の個数を出力してください。', h1: '右端を伸ばしながら積を掛ける。', h2: '積が k 以上になったら左端を縮める。', ref: 'k=int(input())\na=list(map(int,input().split()))\nn=len(a)\nif k<=1:\n    print(0)\nelse:\n    prod=1\n    left=0\n    cnt=0\n    for right in range(n):\n        prod*=a[right]\n        while prod>=k and left<=right:\n            prod//=a[left]\n            left+=1\n        cnt+=right-left+1\n    print(cnt)', tip: '積<kの部分配列数はしゃくとり法。各右端で「左端から右端まで」の (right-left+1) 個を足す。', ins: ['100\n10 5 2 6\n', '1\n1 2 3\n', '2\n1 1 1\n', '50\n1 2 3 4\n', '10\n5 5\n', '1000\n2 3 4 5\n'] })

t({ lv: 755, concept: 'しゃくとり: 相異なるk種以下の最長', title: '異なる要素がk種以下の最長部分配列', tags: ['二ポインタ', 'ハッシュ'], io: '1行目に k、2行目に整数列が与えられます。', ask: '異なる種類の値が k 個以下になる最長の連続部分配列の長さを出力してください。', h1: '窓内の種類数を辞書で数える。', h2: 'k 種を超えたら左端を縮める。', ref: 'from collections import defaultdict\nk=int(input())\na=list(map(int,input().split()))\nn=len(a)\ncnt=defaultdict(int)\nleft=0\nbest=0\ndistinct=0\nfor right in range(n):\n    if cnt[a[right]]==0:\n        distinct+=1\n    cnt[a[right]]+=1\n    while distinct>k:\n        cnt[a[left]]-=1\n        if cnt[a[left]]==0:\n            distinct-=1\n        left+=1\n    if right-left+1>best:\n        best=right-left+1\nprint(best)', tip: '「異なる要素k種まで」の最長窓はしゃくとり。窓内の種類数を辞書のカウントで管理する。', ins: ['2\n1 2 1 2 3\n', '1\n1 1 1\n', '3\n1 2 3 4\n', '0\n1 2\n', '2\n1 2 3 2 2\n', '1\n1 2 1\n'] })

t({ lv: 756, concept: 'ハッシュ: 最長の重複なし部分配列', title: '重複要素のない最長部分配列', tags: ['二ポインタ', 'ハッシュ'], io: '整数列が1行で与えられます。', ask: '同じ値が2回現れない最長の連続部分配列の長さを出力してください。', h1: '各値の最後の位置を記録する。', h2: '重複が出たら左端をその次へ飛ばす。', ref: 'a=list(map(int,input().split()))\nlast={}\nleft=0\nbest=0\nfor right,x in enumerate(a):\n    if x in last and last[x]>=left:\n        left=last[x]+1\n    last[x]=right\n    if right-left+1>best:\n        best=right-left+1\nprint(best)', tip: '重複なし最長窓は「各値の最終出現位置」を辞書に持ち、重複時に左端を飛ばす O(n)。', ins: ['1 2 3 1 2\n', '1 1 1\n', '1 2 3 4\n', '5\n', '1 2 2 3 4 4 5\n', '7 7 7 7\n'] })

t({ lv: 757, concept: 'ハッシュ: アナグラムのグループ数', title: 'アナグラムでまとめたグループ数', tags: ['ハッシュ', '文字列'], io: '1行目に n、続く n 行に文字列が与えられます。', ask: '文字を並べ替えると一致する語を同じグループとみなしたときのグループ数を出力してください。', h1: '各語をソートした文字列をキーにする。', h2: '異なるキーの数を数える。', ref: 'n=int(input())\nkeys=set()\nfor _ in range(n):\n    w=input()\n    keys.add("".join(sorted(w)))\nprint(len(keys))', tip: 'アナグラム判定は「文字をソートした文字列」を正規キーにする。辞書/集合でまとめる定番。', ins: ['3\neat\ntea\ntan\n', '1\nabc\n', '2\nabc\ncba\n', '4\na\nb\nc\nd\n', '3\nlisten\nsilent\nenlist\n', '2\nab\nabc\n'] })

t({ lv: 758, concept: 'ハッシュ: 最頻値の出現回数', title: '最も多い要素の出現回数', tags: ['ハッシュ'], io: '整数列が1行で与えられます。', ask: '最も多く現れる値の出現回数を出力してください。', h1: 'Counter で集計する。', h2: '最大の出現回数を取る。', ref: 'from collections import Counter\na=list(map(int,input().split()))\nif not a:\n    print(0)\nelse:\n    print(max(Counter(a).values()))', tip: 'Counter は出現回数の集計に最適。most_common(1) でも最頻値が取れる。', ins: ['1 2 2 3 3 3\n', '5\n', '1 1 1\n', '1 2 3 4\n', '7 7 8 8\n', '4 4 4 4 1\n'] })

t({ lv: 759, concept: 'ソート: k番目に大きい値', title: 'k番目に大きい要素', tags: ['ソート', 'ヒープ'], io: '1行目に k、2行目に整数列が与えられます。', ask: 'k 番目に大きい値を出力してください。', h1: '降順にソートする。', h2: 'k-1 番目を取る(またはサイズkの最小ヒープ)。', ref: 'import heapq\nk=int(input())\na=list(map(int,input().split()))\nprint(heapq.nlargest(k,a)[-1])', tip: 'k番目に大きい値は nlargest や部分ソートで。サイズkの最小ヒープなら O(n log k)。', ins: ['2\n3 2 1 5 6 4\n', '1\n1\n', '4\n3 2 3 1 2 4 5 5 6\n', '3\n5 5 5\n', '1\n9 8 7\n', '5\n1 2 3 4 5\n'] })

t({ lv: 760, concept: 'ヒープ: k番目に小さい和(数列対)', title: '2配列の和のk番目に小さい値', tags: ['ヒープ'], io: '1行目に k、2行目に配列 A、3行目に配列 B が与えられます。', ask: 'A の要素と B の要素を1つずつ足した和のうち、k 番目に小さい値を出力してください。', h1: '小さい和から最小ヒープで取り出す。', h2: '取り出すたびに次の候補を入れる。', ref: 'import heapq\nk=int(input())\nA=sorted(map(int,input().split()))\nB=sorted(map(int,input().split()))\nna=len(A)\nnb=len(B)\nheap=[(A[0]+B[0],0,0)]\nseen={(0,0)}\nres=0\nfor _ in range(k):\n    s,i,j=heapq.heappop(heap)\n    res=s\n    if i+1<na and (i+1,j) not in seen:\n        seen.add((i+1,j))\n        heapq.heappush(heap,(A[i+1]+B[j],i+1,j))\n    if j+1<nb and (i,j+1) not in seen:\n        seen.add((i,j+1))\n        heapq.heappush(heap,(A[i]+B[j+1],i,j+1))\nprint(res)', tip: '和のk番目最小はヒープで「最小の和から隣接候補を展開」する。全 n² を作らず O(k log k)。', ins: ['3\n1 7 11\n2 4 6\n', '1\n1 2\n3 4\n', '2\n1 1\n1 1\n', '4\n1 2 3\n1 2 3\n', '1\n5\n10\n', '6\n1 2\n3 4 5\n'] })

t({ lv: 761, concept: 'ヒープ: 中央値の維持', title: 'プレフィックス中央値の総和の2倍', tags: ['ヒープ'], io: '整数列が1行で与えられます。', ask: '先頭から i 個までの中央値(偶数個なら中央2つの平均)を 2 倍した整数を、各 i について合計した値を出力してください。', h1: '小さい半分の最大ヒープと大きい半分の最小ヒープ。', h2: 'サイズを均衡させ中央値を O(1) で得る。', ref: 'import heapq\na=list(map(int,input().split()))\nlow=[]\nhigh=[]\ntotal=0\nfor x in a:\n    if not low or x<=-low[0]:\n        heapq.heappush(low,-x)\n    else:\n        heapq.heappush(high,x)\n    if len(low)>len(high)+1:\n        heapq.heappush(high,-heapq.heappop(low))\n    elif len(high)>len(low):\n        heapq.heappush(low,-heapq.heappop(high))\n    if len(low)>len(high):\n        total+=2*(-low[0])\n    else:\n        total+=(-low[0])+high[0]\nprint(total)', tip: '逐次中央値は「下半分の最大ヒープ＋上半分の最小ヒープ」をサイズ均衡させて O(log n)/要素。', ins: ['1 2 3\n', '5\n', '2 1 5 7 2 0 5\n', '1 1 1 1\n', '4 3 2 1\n', '10 20 30 40\n'] })

t({ lv: 762, concept: '集合: 連続する数列の最長長さ', title: '最長の連続整数列の長さ', tags: ['ハッシュ'], io: '整数列が1行で与えられます。', ask: '値として連続する整数(順不同)が作る最長の長さを出力してください(例:100,4,200,1,3,2→1,2,3,4で4)。', h1: '集合に入れる。', h2: '連続の先頭(x-1が無い)から伸ばす。', ref: 'a=set(map(int,input().split()))\nbest=0\nfor x in a:\n    if x-1 not in a:\n        length=1\n        cur=x\n        while cur+1 in a:\n            cur+=1\n            length+=1\n        if length>best:\n            best=length\nprint(best)', tip: '最長連続列は集合化し「連続の先頭からだけ伸ばす」ことで全体 O(n) になる(ソート不要)。', ins: ['100 4 200 1 3 2\n', '0 0 1 1\n', '5\n', '1 2 3 4 5\n', '10 30 20\n', '1 3 5 7\n'] })

t({ lv: 763, concept: 'ソート: 最小の絶対差ペア数', title: '最小絶対差になるペアの数', tags: ['ソート'], io: '整数列が1行で与えられます。', ask: 'すべての2要素ペアの絶対差の最小値を達成するペアの個数を出力してください。', h1: 'ソートすると最小差は隣接で生じる。', h2: '隣接差の最小値とその出現数を数える。', ref: 'a=sorted(map(int,input().split()))\nn=len(a)\nif n<2:\n    print(0)\nelse:\n    mn=min(a[i+1]-a[i] for i in range(n-1))\n    cnt=sum(1 for i in range(n-1) if a[i+1]-a[i]==mn)\n    print(cnt)', tip: '最小絶対差は必ず隣接要素間に現れる。ソート後に隣接差を見るだけで O(n log n)。', ins: ['4 2 1 3\n', '1 3 6 10 15\n', '1 1 1\n', '5\n', '1 2 2 3\n', '10 20 30\n'] })

t({ lv: 764, concept: '数え上げ: 転倒数(マージ)', title: '配列の転倒数', tags: ['ソート'], io: '整数列が1行で与えられます。', ask: 'i<j かつ a[i]>a[j] となるペアの個数(転倒数)を出力してください。', h1: 'マージソートの過程で数える。', h2: '右側が先に取られた回数を加算。', ref: 'a=list(map(int,input().split()))\ndef sort_count(arr):\n    n=len(arr)\n    if n<=1:\n        return arr,0\n    mid=n//2\n    left,cl=sort_count(arr[:mid])\n    right,cr=sort_count(arr[mid:])\n    merged=[]\n    i=j=0\n    inv=cl+cr\n    while i<len(left) and j<len(right):\n        if left[i]<=right[j]:\n            merged.append(left[i])\n            i+=1\n        else:\n            merged.append(right[j])\n            j+=1\n            inv+=len(left)-i\n    merged+=left[i:]\n    merged+=right[j:]\n    return merged,inv\n_,inv=sort_count(a)\nprint(inv)', tip: '転倒数はマージソートで「右が先に並ぶ回数」を数えると O(n log n)。BITでも求まる。', ins: ['2 4 1 3 5\n', '1 2 3\n', '3 2 1\n', '5\n', '1 1 1\n', '5 4 3 2 1\n'] })

t({ lv: 765, concept: '数え上げ: ペアの和がkになる数', title: '和がkになるペアの個数', tags: ['ハッシュ'], io: '1行目に k、2行目に整数列が与えられます。', ask: '異なる2要素(添字で区別)の和が k になるペアの個数を出力してください。', h1: '各値の出現回数を辞書で持つ。', h2: '走査しながら k-x の既出数を足す。', ref: 'from collections import defaultdict\nk=int(input())\na=list(map(int,input().split()))\ncnt=defaultdict(int)\nres=0\nfor x in a:\n    res+=cnt[k-x]\n    cnt[x]+=1\nprint(res)', tip: '和がkのペア数は「これまでに見た k-x の個数」を足す1パス。辞書で出現数を管理する。', ins: ['6\n1 5 2 4 3\n', '4\n2 2 2\n', '10\n1 2 3\n', '0\n0 0 0\n', '5\n5\n', '7\n3 4 3 4\n'] })

t({ lv: 766, concept: '文字列: 最頻の単語', title: '最も頻出する単語', tags: ['ハッシュ', '文字列'], io: '1行目に n、続く n 行に単語が与えられます。', ask: '最も多く現れる単語を出力してください。複数あれば辞書順で最小のもの。', h1: '出現回数を辞書で数える。', h2: '(回数の多い順, 辞書順)で選ぶ。', ref: 'from collections import Counter\nn=int(input())\nwords=[input() for _ in range(n)]\ncnt=Counter(words)\nbest=None\nbestc=-1\nfor w in sorted(cnt):\n    if cnt[w]>bestc:\n        bestc=cnt[w]\n        best=w\nprint(best)', tip: '最頻単語の同点は辞書順で割る。先に sorted してから最大回数を探すと安定して最小語が選べる。', ins: ['3\napple\nbanana\napple\n', '1\nx\n', '4\nb\na\nb\na\n', '3\ncat\ndog\nbird\n', '5\nz\nz\na\na\na\n', '2\nhello\nhello\n'] })

t({ lv: 767, concept: '数え上げ: 部分配列のGCDが1の数', title: 'GCDが1になる連続部分配列の数', tags: ['数論'], io: '正整数列が1行で与えられます。', ask: '連続部分配列の要素のGCDがちょうど1になるものの個数を出力してください。', h1: '各右端で「その右端を含む区間のGCD集合」を持つ。', h2: 'GCDの種類は対数個なので効率的。', ref: 'import math\na=list(map(int,input().split()))\nprev=[]\ntotal=0\nfor x in a:\n    cur={}\n    cur[x]=1\n    for g,c in prev:\n        ng=math.gcd(g,x)\n        cur[ng]=cur.get(ng,0)+c\n    total+=cur.get(1,0)\n    prev=list(cur.items())\nprint(total)', tip: '区間GCDは右端ごとに種類が対数個しか増えないので、(GCD値→個数)を持ち回すと効率的。', ins: ['1 2 3\n', '2 4 6\n', '3 3 3\n', '1\n', '6 10 15\n', '2 3 4\n'] })

t({ lv: 768, concept: '数え上げ: 和が0になる部分配列の有無', title: '和が0の連続部分配列があるか', tags: ['ハッシュ'], io: '整数列が1行で与えられます。', ask: '和が0になる空でない連続部分配列が存在するなら yes、しなければ no を出力してください。', h1: '累積和の重複を探す。', h2: '同じ累積和が2回出れば間の和が0。', ref: 'a=list(map(int,input().split()))\nseen={0}\ns=0\nfound=False\nfor x in a:\n    s+=x\n    if s in seen:\n        found=True\n        break\n    seen.add(s)\nprint("yes" if found else "no")', tip: '和0の部分配列は「累積和が重複する2点」があるかで判定。0を初期値に入れておく。', ins: ['1 2 -3 4\n', '1 2 3\n', '0\n', '4 -4\n', '1 -1 1 -1\n', '5 5 5\n'] })

t({ lv: 769, concept: '文字列: 最初に1度だけ出る文字', title: '最初の一意な文字の位置', tags: ['ハッシュ', '文字列'], io: '英小文字の文字列が1行で与えられます。', ask: '1度しか現れない最初の文字の位置(0始まり)を出力してください。無ければ -1。', h1: '各文字の出現回数を数える。', h2: '前から見て回数1の最初を返す。', ref: 's=input()\nfrom collections import Counter\ncnt=Counter(s)\nans=-1\nfor i,ch in enumerate(s):\n    if cnt[ch]==1:\n        ans=i\n        break\nprint(ans)', tip: '最初の一意文字は2パス: まず全文字を数え、次に前から回数1を探す。', ins: ['beetroot\n', 'rootbeetroot\n', 'aabb\n', 'z\n', 'abcabc\n', 'abacabad\n'] })

t({ lv: 770, concept: '数え上げ: 各要素の右の小さい要素数', title: '右側の小さい要素数の総和', tags: ['ソート', 'BIT'], io: '整数列が1行で与えられます。', ask: '各要素について「自分より右にある自分未満の要素数」を求め、その総和を出力してください(=転倒数)。', h1: '座標圧縮してBITで数える。', h2: '右から見て、自分未満の既出数を足す。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nsorted_vals=sorted(set(a))\nrank={v:i+1 for i,v in enumerate(sorted_vals)}\nm=len(sorted_vals)\nbit=[0]*(m+1)\ndef update(i):\n    while i<=m:\n        bit[i]+=1\n        i+=i&(-i)\ndef query(i):\n    s=0\n    while i>0:\n        s+=bit[i]\n        i-=i&(-i)\n    return s\ntotal=0\nfor x in reversed(a):\n    r=rank[x]\n    total+=query(r-1)\n    update(r)\nprint(total)', tip: '「右の小さい要素数」はBITで右から走査し、自分未満の既出数を query する。総和は転倒数に等しい。', ins: ['5 2 6 1\n', '1 2 3\n', '3 2 1\n', '5\n', '1 1 1\n', '2 0 1\n'] })

t({ lv: 771, concept: '数え上げ: majority(1/3超)の要素', title: '1/3を超える要素の個数', tags: ['ハッシュ'], io: '整数列が1行で与えられます。', ask: '出現回数が要素数の 1/3 を超える値の種類数を出力してください。', h1: 'Counter で集計する。', h2: '回数 > n/3 の種類を数える。', ref: 'from collections import Counter\na=list(map(int,input().split()))\nn=len(a)\ncnt=Counter(a)\nres=sum(1 for v in cnt.values() if v*3>n)\nprint(res)', tip: '1/3超の要素は高々2個(Boyer-Mooreの拡張)。ここでは単純にCounterで数える。', ins: ['3 2 3\n', '1 1 1 3 3 2 2 2\n', '1\n', '1 2 3\n', '2 2 2 2\n', '1 1 2 2 3 3\n'] })

t({ lv: 772, concept: '文字列: 文字の最小削除で頻度を一意に', title: '頻度を相異なるにする最小削除数', tags: ['ハッシュ', 'ソート'], io: '英小文字の文字列が1行で与えられます。', ask: '各文字の出現回数がすべて異なるようにするための最小削除文字数を出力してください。', h1: '頻度を降順に並べる。', h2: '使用済み頻度を避け、必要なら減らす。', ref: 'from collections import Counter\ns=input()\nfreqs=sorted(Counter(s).values(),reverse=True)\nused=set()\ndeletes=0\nfor f in freqs:\n    while f>0 and f in used:\n        f-=1\n        deletes+=1\n    if f>0:\n        used.add(f)\nprint(deletes)', tip: '頻度を一意にする最小削除は「降順に見て、既使用なら1ずつ減らす」貪欲。', ins: ['aab\n', 'aaabbbcc\n', 'abc\n', 'a\n', ' accc\n', 'bbbaaab\n'] })

t({ lv: 773, concept: 'ソート: 区間の重なり除去後の数', title: '重なる区間を統合した後の区間数', tags: ['ソート', '区間'], io: '1行目に n、続く n 行に区間 l r が与えられます。', ask: '重なる(端点で接する場合も統合)区間をまとめた後の区間の個数を出力してください。', h1: '左端でソートする。', h2: '直前の右端以下で始まれば統合。', ref: 'n=int(input())\nif n==0:\n    print(0)\nelse:\n    ivs=sorted(tuple(map(int,input().split())) for _ in range(n))\n    cnt=1\n    cur_r=ivs[0][1]\n    for l,r in ivs[1:]:\n        if l<=cur_r:\n            cur_r=max(cur_r,r)\n        else:\n            cnt+=1\n            cur_r=r\n    print(cnt)', tip: '区間統合は左端ソート後に「直前の右端以上で始まるか」で判定する貪欲。', ins: ['4\n1 3\n2 6\n8 10\n15 18\n', '1\n0 5\n', '3\n1 2\n2 3\n3 4\n', '3\n1 5\n2 3\n4 6\n', '2\n1 2\n3 4\n', '3\n1 10\n2 3\n4 5\n'] })

t({ lv: 774, concept: '数え上げ: 部分配列の最大-最小がk', title: '最大-最小=kの部分配列の数(全探索)', tags: ['配列'], io: '1行目に k、2行目に整数列が与えられます。', ask: '連続部分配列で「最大値-最小値」がちょうど k になるものの個数を出力してください。', h1: '各左端から右へ最大・最小を更新する。', h2: '差が k のとき数える(O(n²))。', ref: 'k=int(input())\na=list(map(int,input().split()))\nn=len(a)\ncnt=0\nfor i in range(n):\n    mx=a[i]\n    mn=a[i]\n    for j in range(i,n):\n        if a[j]>mx:\n            mx=a[j]\n        if a[j]<mn:\n            mn=a[j]\n        if mx-mn==k:\n            cnt+=1\nprint(cnt)', tip: '部分配列の最大・最小は左端を固定して右へ更新すれば O(n²) で全探索できる。', ins: ['2\n1 3 2 5\n', '0\n1 1 1\n', '1\n1 2 3\n', '3\n5\n', '2\n2 4 2 4\n', '0\n5 5 5\n'] })

t({ lv: 775, concept: '文字列: ランレングス符号化の長さ', title: 'ランレングス圧縮後の文字数', tags: ['文字列'], io: '文字列が1行で与えられます。', ask: '連続する同じ文字を「文字+個数」に圧縮したときの全体の文字数を出力してください(個数1は数字を付けない)。', h1: '連続する同一文字をまとめる。', h2: '個数>1なら数字の桁数を足す。', ref: 's=input()\nif not s:\n    print(0)\nelse:\n    total=0\n    i=0\n    n=len(s)\n    while i<n:\n        j=i\n        while j<n and s[j]==s[i]:\n            j+=1\n        run=j-i\n        total+=1\n        if run>1:\n            total+=len(str(run))\n        i=j\n    print(total)', tip: 'ランレングス圧縮の長さは「1文字＋(個数>1なら桁数)」を各ランで足す。個数1は数字を省く。', ins: ['aaabbc\n', 'abc\n', 'aaaaaaaaaa\n', 'a\n', '\n', 'aabbbbbbbbbbb\n'] })

t({ lv: 776, concept: 'ハッシュ: ちょうど2回出る値の数', title: 'ちょうど2回現れる値の種類数', tags: ['ハッシュ'], io: '整数列が1行で与えられます。', ask: '出現回数がちょうど2回の値の種類数を出力してください。', h1: '各値の出現回数を数える。', h2: '回数が2のものを数える。', ref: 'from collections import Counter\na=list(map(int,input().split()))\ncnt=Counter(a)\nprint(sum(1 for v in cnt.values() if v==2))', tip: 'Counter で回数を集計し、ちょうど2のものだけ数える単純な頻度問題。', ins: ['1 1 2 3 3\n', '1 2 3\n', '1 1 1\n', '5 5\n', '7\n', '2 2 3 3 4 4 4\n'] })

t({ lv: 777, concept: '文字列: 左右の文字の種類数が等しくなる分け方の数', title: '語彙が釣り合う切れ目を数える', tags: ['文字列', '累積'], io: '英小文字だけからなる文字列が1行で与えられます。', ask: '文字列を空でない2つの連続部分に切り分けたとき、左側に現れる文字の種類数と右側に現れる文字の種類数が等しくなる切れ目の数を出力してください。', h1: '左から順に「そこまでに何種類出たか」を記録した表を作る。', h2: '右からも同じ表を作り、切れ目ごとに左の表と右の表を突き合わせる。', ref: 's=input()\nn=len(s)\nleft=[0]*n\nseen=set()\nfor i in range(n):\n    seen.add(s[i])\n    left[i]=len(seen)\nright=[0]*n\nseen=set()\nfor i in range(n-1,-1,-1):\n    seen.add(s[i])\n    right[i]=len(seen)\ncnt=0\nfor i in range(n-1):\n    if left[i]==right[i+1]:\n        cnt+=1\nprint(cnt)', tip: '切れ目ごとに左右を数え直すと二重ループになるが、前からの累積と後ろからの累積を先に用意すれば走査は2往復で済む。重複なしの最長区間(同レベル既出)は窓を動かしながら種類を見たが、こちらは2本の表を突き合わせる——同じ「種類数」でも、聞かれ方で道具が変わる。', ins: ['aacaba\n', 'abcd\n', 'aaaaa\n', 'a\n', 'ab\n', 'aab\n'] })

t({ lv: 778, concept: '数え上げ: 和が等しく分けられる最大グループ', title: '等和に分割できる最大グループ数', tags: ['数論'], io: '正整数列が1行で与えられます。', ask: '配列を和が等しい連続でないグループに分割できる最大数(=総和の約数のうち各グループ和が作れる最大数)を…部分和で判定して出力してください。', h1: '総和の約数を大きい候補から試す。', h2: 'その和を作るグループにちょうど分割できるか部分和で確認。', ref: 'a=list(map(int,input().split()))\ntotal=sum(a)\nn=len(a)\nif total==0:\n    print(n)\nelse:\n    best=1\n    for k in range(n,0,-1):\n        if total%k!=0:\n            continue\n        target=total//k\n        if max(a)>target:\n            continue\n        groups=0\n        cur=0\n        ok=True\n        for x in sorted(a,reverse=True):\n            pass\n        dp=[False]*(total+1)\n        dp[0]=True\n        for x in a:\n            for s in range(total,x-1,-1):\n                if dp[s-x]:\n                    dp[s]=True\n        if dp[target]:\n            best=k\n            break\n    print(best)', tip: '等和グループ数は「総和の約数 k」を大きい方から試し、各グループ和を部分和で作れるか確認する。', ins: ['1 2 3 4\n', '5 5 5\n', '1 1 1 1\n', '7\n', '2 2 2 2 2\n', '1 2 3\n'] })

t({ lv: 779, concept: 'ソート: 隣接差の最大(円環)', title: '円環に並べた隣接差の最小化…の最大ギャップ', tags: ['ソート'], io: '整数列が1行で与えられます。', ask: '昇順に並べたとき、円環(末尾と先頭も隣接)とみなした隣接差の最大値を出力してください。', h1: 'ソートして隣接差を見る。', h2: '末尾-先頭は円環では0扱い(直線の最大ギャップ)。', ref: 'a=sorted(map(int,input().split()))\nn=len(a)\nif n<2:\n    print(0)\nelse:\n    best=0\n    for i in range(1,n):\n        if a[i]-a[i-1]>best:\n            best=a[i]-a[i-1]\n    print(best)', tip: '円環でも昇順に並べた隣接差の最大が答え(端の折り返しは差を生まない)。', ins: ['1 5 3 9\n', '10\n', '1 2 3\n', '1 100\n', '5 4 3 2 1\n', '0 3 9 10\n'] })

t({ lv: 780, concept: '数え上げ: 累積XORがkの部分配列数', title: 'XORがkになる部分配列の数', tags: ['ハッシュ', 'bit演算'], io: '1行目に k、2行目に非負整数列が与えられます。', ask: '連続部分配列のXORがちょうど k になるものの個数を出力してください。', h1: '累積XOR pre を持つ。', h2: 'pre^k の出現数を辞書で数える。', ref: 'from collections import defaultdict\nk=int(input())\na=list(map(int,input().split()))\ncnt=defaultdict(int)\ncnt[0]=1\npre=0\nres=0\nfor x in a:\n    pre^=x\n    res+=cnt[pre^k]\n    cnt[pre]+=1\nprint(res)', tip: '部分配列のXORは累積XORの差(XOR)。pre^k の出現数を足す、和版(lv519)のXOR版。', ins: ['6\n4 2 2 6 4\n', '0\n1 1\n', '1\n1 2 3\n', '5\n5\n', '0\n0 0 0\n', '3\n3 3 3\n'] })

t({ lv: 781, concept: '文字列: 回文かの判定(英数字のみ)', title: '英数字だけで回文か', tags: ['文字列', '二ポインタ'], io: '文字列が1行で与えられます。', ask: '英数字以外を無視し大文字小文字を区別しないとき、回文なら yes、そうでなければ no を出力してください。', h1: '英数字だけ取り出して小文字化。', h2: '前後から二ポインタで比較。', ref: 's=input()\nfiltered=[c.lower() for c in s if c.isalnum()]\ni=0\nj=len(filtered)-1\nok=True\nwhile i<j:\n    if filtered[i]!=filtered[j]:\n        ok=False\n        break\n    i+=1\n    j-=1\nprint("yes" if ok else "no")', tip: '正規化(英数字のみ・小文字)してから二ポインタで両端比較するのが回文判定の定石。', ins: ['A man a plan a canal Panama\n', 'race a car\n', ' \n', 'ab_a\n', '0P\n', 'Was it a car or a cat I saw\n'] })

t({ lv: 782, concept: '数え上げ: 文字の組合せで作れる最長回文', title: '文字を並べ替えて作れる最長回文の長さ', tags: ['ハッシュ', '文字列'], io: '文字列が1行で与えられます。', ask: 'その文字を並べ替えて作れる最長の回文の長さを出力してください。', h1: '各文字の出現回数を数える。', h2: '偶数分を全部使い、奇数があれば中央に1つ足す。', ref: 'from collections import Counter\ns=input()\ncnt=Counter(s)\nlength=0\nodd=False\nfor v in cnt.values():\n    length+=v//2*2\n    if v%2==1:\n        odd=True\nif odd:\n    length+=1\nprint(length)', tip: '最長回文の長さは「各文字の偶数分＋奇数が1つでもあれば中央に1文字」で決まる。', ins: ['abccccdd\n', 'a\n', 'bb\n', 'abc\n', 'aaa\n', 'Aa\n'] })

t({ lv: 783, concept: '数え上げ: 差がkになるペアの種類数', title: '差がkになる値ペアの種類数', tags: ['ハッシュ'], io: '1行目に k、2行目に整数列が与えられます。', ask: '|x-y|=k となる相異なる値ペア {x,y} の種類数を出力してください(k>=0)。', h1: '値の集合を作る。', h2: 'k=0なら2回以上出る値、k>0なら x と x+k の両方がある数。', ref: 'k=int(input())\na=list(map(int,input().split()))\nfrom collections import Counter\ncnt=Counter(a)\nvals=set(a)\nif k==0:\n    print(sum(1 for v in cnt if cnt[v]>=2))\nelse:\n    print(sum(1 for v in vals if v+k in vals))', tip: '差kのペア種類数は集合で判定。k=0は重複値、k>0は x と x+k の共存を数える。', ins: ['2\n3 1 4 1 5\n', '1\n1 2 3 4 5\n', '0\n1 3 1 5 4\n', '3\n1 5 2 7\n', '2\n1 1 1\n', '5\n1 2 3\n'] })

t({ lv: 784, concept: '文字列: 単語の最小ウィンドウ長', title: '全文字を含む最小窓の長さ', tags: ['二ポインタ', '文字列'], io: '1行目に文字列 s、2行目に必要文字の集合 t が与えられます。', ask: 's の連続部分文字列で t の全文字を(重複度も含め)含む最小の長さを出力してください。無ければ0。', h1: 't の必要数を辞書で持つ。', h2: 'しゃくとりで条件を満たす最小窓を探す。', ref: 'from collections import Counter\ns=input()\nt=input()\nneed=Counter(t)\nrequired=len(need)\nformed=0\nwindow=Counter()\nleft=0\nbest=float("inf")\nfor right in range(len(s)):\n    c=s[right]\n    window[c]+=1\n    if c in need and window[c]==need[c]:\n        formed+=1\n    while formed==required:\n        if right-left+1<best:\n            best=right-left+1\n        lc=s[left]\n        window[lc]-=1\n        if lc in need and window[lc]<need[lc]:\n            formed-=1\n        left+=1\nprint(best if best<float("inf") else 0)', tip: '最小ウィンドウはしゃくとり。必要文字を満たしたら左端を縮めて最小化する典型。', ins: ['ADOBECODEBANC\nABC\n', 'a\na\n', 'a\naa\n', 'abc\nd\n', 'aa\naa\n', 'cabwefgewcwaefgcf\ncae\n'] })

t({ lv: 785, concept: '数え上げ: 単調増加部分配列の最大長', title: '最長の連続非減少部分配列', tags: ['配列'], io: '整数列が1行で与えられます。', ask: '非減少(<=)が続く最長の連続部分配列の長さを出力してください。', h1: '直前以上なら伸ばす。', h2: '崩れたら1にリセット。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nif n==0:\n    print(0)\nelse:\n    best=1\n    cur=1\n    for i in range(1,n):\n        if a[i]>=a[i-1]:\n            cur+=1\n            if cur>best:\n                best=cur\n        else:\n            cur=1\n    print(best)', tip: '非減少(<=)の最長連続はリセット型走査。狭義増加(<)版(lv675)との違いは等号の扱い。', ins: ['1 2 2 3 1\n', '5 4 3\n', '1 1 1\n', '7\n', '1 2 3 4\n', '3 1 2 2 4 1\n'] })

t({ lv: 786, concept: '数え上げ: 和が最大のk個', title: '上位k個の和', tags: ['ソート', 'ヒープ'], io: '1行目に k、2行目に整数列が与えられます。', ask: '最も大きい k 個の要素の和を出力してください(k>=要素数なら全部)。', h1: '大きい順に k 個取る。', h2: 'nlargest の和。', ref: 'import heapq\nk=int(input())\na=list(map(int,input().split()))\nprint(sum(heapq.nlargest(k,a)))', tip: '上位kの和は nlargest で。サイズkの最小ヒープを維持すれば O(n log k)。', ins: ['2\n4 1 3 2\n', '1\n5\n', '3\n1 2 3\n', '5\n1 2\n', '2\n-1 -2 -3\n', '3\n10 10 10 1\n'] })

t({ lv: 787, concept: '文字列: 2文字列が回転で一致するか', title: '回転して一致するか', tags: ['文字列'], io: '1行目に文字列 a、2行目に文字列 b が与えられます。', ask: 'b が a の巡回シフトのいずれかと一致するなら yes、しなければ no を出力してください。', h1: '長さが等しいか確認。', h2: 'a+a の中に b が部分文字列として現れるか。', ref: 'a=input()\nb=input()\nif len(a)!=len(b):\n    print("no")\nelif len(a)==0:\n    print("yes")\nelse:\n    print("yes" if b in a+a else "no")', tip: '回転一致は「a+a の中に b が含まれるか」で O(n) 判定できる古典テク。', ins: ['abcde\ncdeab\n', 'abc\nacb\n', 'a\na\n', 'abab\nbaba\n', 'abc\nabcd\n', 'aaaa\naaaa\n'] })

t({ lv: 788, concept: '数え上げ: 累積和がmの倍数の部分配列数', title: '和がmの倍数の部分配列数(再)', tags: ['ハッシュ'], io: '1行目に m、2行目に整数列が与えられます。', ask: '和が m で割り切れる連続部分配列の個数を出力してください。', h1: '累積和の mod m を持つ。', h2: '同じ余りの組数を数える。', ref: 'from collections import defaultdict\nm=int(input())\na=list(map(int,input().split()))\ncnt=defaultdict(int)\ncnt[0]=1\ns=0\nres=0\nfor x in a:\n    s=(s+x)%m\n    res+=cnt[s]\n    cnt[s]+=1\nprint(res)', tip: '和がmの倍数の部分配列数は累積和の余りで同種を数える。lv520と同主題だが mod を毎回取る実装。', ins: ['5\n4 5 0 -2 -3 1\n', '3\n1 2 3\n', '2\n2 4 6\n', '1\n1 2 3\n', '4\n4 4 4\n', '7\n3 1 4 1 5\n'] })

t({ lv: 789, concept: '文字列: 母音と子音の最大差', title: '母音数-子音数が最大の窓', tags: ['文字列', '配列'], io: '英小文字の文字列が1行で与えられます。', ask: '連続部分文字列での(母音の数 - 子音の数)の最大値を出力してください(空窓は0)。', h1: '母音+1、子音-1とみなす。', h2: 'Kadaneで最大部分和(空も許して0以上)。', ref: 's=input()\nvowels=set("aeiou")\ncur=0\nbest=0\nfor ch in s:\n    v=1 if ch in vowels else -1\n    cur=max(0,cur+v)\n    if cur>best:\n        best=cur\nprint(best)', tip: '母音+1・子音-1に置き換えれば「最大部分和(空許容)」のKadaneに帰着する。', ins: ['abeci\n', 'bcd\n', 'aeiou\n', 'a\n', 'xyz\n', 'aebcdiou\n'] })

t({ lv: 790, concept: '数え上げ: しゃくとりで和がちょうどkの数', title: '和がちょうどkの部分配列数(非負)', tags: ['二ポインタ'], io: '1行目に k、2行目に非負整数列が与えられます。', ask: '和がちょうど k になる連続部分配列の個数をしゃくとり法で求めて出力してください。', h1: '和が k 以下になる窓数 - k-1 以下になる窓数。', h2: 'atMost(k)-atMost(k-1)。', ref: 'k=int(input())\na=list(map(int,input().split()))\nn=len(a)\ndef at_most(K):\n    if K<0:\n        return 0\n    left=0\n    cur=0\n    cnt=0\n    for right in range(n):\n        cur+=a[right]\n        while cur>K and left<=right:\n            cur-=a[left]\n            left+=1\n        cnt+=right-left+1\n    return cnt\nprint(at_most(k)-at_most(k-1))', tip: '「ちょうどk」は atMost(k) - atMost(k-1) に分解するのがしゃくとりの定番(非負前提)。', ins: ['3\n1 2 1 2 3\n', '0\n0 0 0\n', '5\n5\n', '2\n1 1 1\n', '10\n1 2 3\n', '4\n4 1 1 2 4\n'] })

t({ lv: 791, concept: '文字列: 最も長い共通接頭辞', title: '複数文字列の最長共通接頭辞', tags: ['文字列'], io: '1行目に n、続く n 行に文字列が与えられます。', ask: 'すべての文字列に共通する最長の接頭辞を出力してください(無ければ空行)。', h1: '最初の語を基準に1文字ずつ確認。', h2: 'どれかで不一致になったら打ち切る。', ref: 'n=int(input())\nwords=[input() for _ in range(n)]\nif n==0:\n    print("")\nelse:\n    base=words[0]\n    prefix=base\n    for w in words[1:]:\n        while not w.startswith(prefix):\n            prefix=prefix[:-1]\n            if prefix=="":\n                break\n    print(prefix)', tip: '最長共通接頭辞は先頭語を候補にし、一致しない語が来たら末尾を削るのが簡単。', ins: ['3\nflower\nflow\nflight\n', '3\ndog\ncat\nfish\n', '1\nhello\n', '2\nabc\nabc\n', '2\na\nab\n', '3\nprefix\npre\npremium\n'] })

t({ lv: 792, concept: '数え上げ: ヒストグラムの面積(台形なし)', title: '各バーの可視幅の総和', tags: ['スタック'], io: 'バーの高さの列が1行で与えられます。', ask: '各バー i について「左側で i より低くなる直前までの連続幅」を求め、その総和を出力してください(自分を含む、単調スタックで)。', h1: '単調増加スタックで左に小さい要素を探す。', h2: 'span = i - 前の小さい位置。', ref: 'h=list(map(int,input().split()))\nn=len(h)\nstack=[]\ntotal=0\nfor i in range(n):\n    while stack and h[stack[-1]]>=h[i]:\n        stack.pop()\n    prev=stack[-1] if stack else -1\n    total+=i-prev\n    stack.append(i)\nprint(total)', tip: '株価スパン問題。単調スタックで「左に自分以上が続く幅」を O(n) で求める。', ins: ['100 80 60 70 60 75 85\n', '5\n', '1 2 3 4\n', '4 3 2 1\n', '3 3 3\n', '10 1 10 1 10\n'] })

t({ lv: 793, concept: '文字列: 圧縮文字列の復元長', title: '括弧つき繰り返し文字列の展開長', tags: ['文字列', 'スタック'], io: 'k[文字列] 形式を含む文字列が1行で与えられます(例: 3[a]2[bc])。', ask: '展開後の文字列の長さを出力してください。', h1: 'スタックで現在の長さと繰り返し数を保持。', h2: ']で内側を倍にして外側へ足す。', ref: 's=input()\nstack=[]\ncur=0\nnum=0\nfor ch in s:\n    if ch.isdigit():\n        num=num*10+int(ch)\n    elif ch=="[":\n        stack.append((cur,num))\n        cur=0\n        num=0\n    elif ch=="]":\n        prev,k=stack.pop()\n        cur=prev+cur*k\n    else:\n        cur+=1\nprint(cur)', tip: 'ネストした繰り返し展開はスタックで「外側の長さと倍率」を退避し、]で内側を倍にして合流する。', ins: ['3[a]2[bc]\n', '3[a2[c]]\n', 'abc\n', '2[abc]3[cd]ef\n', '10[a]\n', '2[2[2[a]]]\n'] })

t({ lv: 794, concept: '数え上げ: 二分探索で挿入位置', title: '昇順列への挿入位置の総和', tags: ['二分探索'], io: '1行目にソート済み列、2行目にクエリ列が与えられます。', ask: '各クエリ値を昇順を保って挿入する最小位置(0始まり、bisect_left相当)を求め、その総和を出力してください。', h1: '二分探索で左端位置を求める。', h2: '各クエリの位置を足す。', ref: 'import bisect\na=list(map(int,input().split()))\nqs=list(map(int,input().split()))\ntotal=0\nfor q in qs:\n    total+=bisect.bisect_left(a,q)\nprint(total)', tip: '挿入位置は bisect_left。重複時は最も左の位置を返す点が bisect_right との違い。', ins: ['1 3 5 6\n5 2 7 0\n', '1 2 3\n2\n', '1 1 1\n1\n', '10 20 30\n5 15 35\n', '5\n5\n', '2 4 6 8\n1 3 5 7 9\n'] })

t({ lv: 795, concept: '文字列: 単語の逆順', title: '単語単位で逆順に並べる', tags: ['文字列'], io: '空白区切りの文章が1行で与えられます。', ask: '単語の順序を逆にして、単語間は空白1つで出力してください(余分な空白は除去)。', h1: '空白で分割する。', h2: '逆順にして空白1つで結合。', ref: 's=input()\nwords=s.split()\nprint(" ".join(reversed(words)))', tip: 'split() は連続空白をまとめ前後の空白も除く。reversed と join で語順反転。', ins: ['the sky is blue\n', '  hello world  \n', 'a\n', 'one two three\n', '   \n', 'Bob Loves Alice\n'] })

t({ lv: 796, concept: '数え上げ: 各値の最初と最後の距離の最大', title: '同じ値の最遠出現間隔', tags: ['ハッシュ'], io: '整数列が1行で与えられます。', ask: '同じ値が現れる最初と最後の位置の差の最大値を出力してください(全要素が相異なるなら0)。', h1: '各値の最初と最後の位置を記録する。', h2: '差の最大を取る。', ref: 'a=list(map(int,input().split()))\nfirst={}\nlast={}\nfor i,x in enumerate(a):\n    if x not in first:\n        first[x]=i\n    last[x]=i\nbest=0\nfor x in first:\n    d=last[x]-first[x]\n    if d>best:\n        best=d\nprint(best)', tip: '同値の最遠間隔は「各値の初出と最終位置」を記録して差の最大を取る1パス。', ins: ['1 2 1 3 1\n', '1 2 3\n', '5\n', '1 1\n', '2 3 2 3 2\n', '4 5 6 4\n'] })

t({ lv: 797, concept: '単調デック: 窓の最大値の総和', title: '長さkの各窓の最大値の総和', tags: ['二ポインタ'], io: '1行目に k、2行目に整数列が与えられます。', ask: '長さ k の連続窓それぞれの最大値を求め、その総和を出力してください。', h1: '単調減少デックに添字を積む。', h2: '窓外の先頭を捨て、先頭が窓の最大。', ref: 'from collections import deque\nk=int(input())\na=list(map(int,input().split()))\nn=len(a)\ndq=deque()\ntotal=0\nfor i in range(n):\n    while dq and a[dq[-1]]<=a[i]:\n        dq.pop()\n    dq.append(i)\n    if dq[0]<=i-k:\n        dq.popleft()\n    if i>=k-1:\n        total+=a[dq[0]]\nprint(total)', tip: 'スライディングウィンドウ最大は単調減少デックで各窓 O(1)。全体 O(n) で最大値を取り出せる。', ins: ['3\n1 3 -1 -3 5 3 6 7\n', '1\n5 1 9\n', '2\n1 2 3\n', '3\n1 1 1\n', '2\n5 4 3\n', '4\n1 2 3 4\n'] })

t({ lv: 798, concept: '文字列: 最長の繰り返し回数', title: '文字列が最大何回繰り返しか', tags: ['文字列'], io: '文字列が1行で与えられます。', ask: '文字列がある部分文字列の繰り返しで表せる最大回数を出力してください(例: abab→2、abcabc→2、abc→1)。', h1: '長さの約数 d を小さい順に試す。', h2: '先頭 d 文字の繰り返しで全体になるか。', ref: 's=input()\nn=len(s)\nif n==0:\n    print(0)\nelse:\n    ans=1\n    for d in range(1,n+1):\n        if n%d==0:\n            if s[:d]*(n//d)==s:\n                ans=n//d\n                break\n    print(ans)', tip: '最大繰り返し回数は最小周期 d を探し n/d を返す。約数を小さい順に試すと最小dが先に見つかる。', ins: ['abab\n', 'abcabc\n', 'abc\n', 'aaaa\n', 'a\n', 'ababab\n'] })

t({ lv: 799, concept: '数え上げ: 和が負になる部分配列数', title: '和が負の連続部分配列の数', tags: ['ソート', 'BIT'], io: '整数列が1行で与えられます。', ask: '和が負(<0)になる連続部分配列の個数を出力してください。', h1: '累積和 pre を作り、pre[r]<pre[l] となる l<r を数える。', h2: '転倒数と同様にマージ/BITで数える。', ref: 'a=list(map(int,input().split()))\nn=len(a)\npre=[0]*(n+1)\nfor i in range(n):\n    pre[i+1]=pre[i]+a[i]\ndef count_inv(arr):\n    def rec(lo,hi):\n        if hi-lo<=1:\n            return 0\n        mid=(lo+hi)//2\n        cnt=rec(lo,mid)+rec(mid,hi)\n        merged=[]\n        i=lo\n        j=mid\n        while i<mid and j<hi:\n            if arr[i]<arr[j]:\n                cnt+=hi-j\n                merged.append(arr[i])\n                i+=1\n            else:\n                merged.append(arr[j])\n                j+=1\n        merged+=arr[i:mid]\n        merged+=arr[j:hi]\n        arr[lo:hi]=merged\n        return cnt\n    return rec(0,len(arr))\nprint(count_inv(pre[:]))', tip: '「和が負の部分配列数」は累積和の中で pre[l]>pre[r] (l<r) を数える＝転倒数。マージソートで O(n log n)。', ins: ['1 -2 3 -4\n', '1 2 3\n', '-1 -1 -1\n', '5\n', '-5\n', '3 -2 1 -4 2\n'] })

export const CATALOG = TASKS
