// 生成タスク 第50波：各レベル2問化フェーズ(5)。lv245〜294 に2問目を追加。
// 数論/配列/桁処理の「要素」。重複なし・決定的・採点一意。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 245, concept: '数: 中心つき六角数', title: 'n番目の中心つき六角数', tags: ['数学'], io: '非負整数 n が1行で与えられます。', ask: '中心つき六角数 3n²+3n+1 を出力してください。', h1: '公式 3n²+3n+1。', h2: 'そのまま計算。', ref: 'n=int(input())\nprint(3*n*n+3*n+1)', tip: '中心つき六角数は中心の1点を六角形状に囲む点の総数。連続する立方数の差にも現れる。', ins: ['0\n', '1\n', '2\n', '10\n', '5\n', '100\n'] })

t({ lv: 246, concept: '数: 最初のn個の偶数の和', title: '1から数えてn個の偶数の和', tags: ['数学'], io: '非負整数 n が1行で与えられます。', ask: '最初の n 個の正の偶数(2,4,6,...)の和を出力してください。', h1: '公式 n(n+1)。', h2: 'そのまま。', ref: 'n=int(input())\nprint(n*(n+1))', tip: '最初のn個の偶数の和は n(n+1)=2(1+2+...+n)。奇数和 n² と対になる公式。', ins: ['3\n', '0\n', '1\n', '10\n', '5\n', '100\n'] })

t({ lv: 247, concept: '配列: 平方数の個数', title: 'リスト中の平方数の個数', tags: ['配列', '数論'], io: '非負整数の列が1行で与えられます。', ask: '完全平方数である要素の個数を出力してください。', h1: '各要素の平方根を整数で確認。', h2: 'isqrt の2乗と一致するか。', ref: 'import math\na=list(map(int,input().split()))\nprint(sum(1 for x in a if math.isqrt(x)**2==x))', tip: '平方数判定は isqrt(x)**2==x。浮動小数の sqrt は誤差が出るので整数で確認する。', ins: ['1 2 4 5 9\n', '3\n', '0 1 4\n', '7 8\n', '16 25 26\n', '100\n'] })

t({ lv: 248, concept: '配列: 素数の個数', title: 'リスト中の素数の個数', tags: ['配列', '数論'], io: '整数の列が1行で与えられます。', ask: '素数である要素の個数を出力してください。', h1: '各要素を素数判定。', h2: '素数を数える。', ref: 'a=list(map(int,input().split()))\ndef is_prime(x):\n    if x<2:\n        return False\n    d=2\n    while d*d<=x:\n        if x%d==0:\n            return False\n        d+=1\n    return True\nprint(sum(1 for x in a if is_prime(x)))', tip: '素数フィルタは試し割り判定を各要素に適用。大量・大値なら篩で前計算する。', ins: ['1 2 3 4 5\n', '4 6 8\n', '7\n', '2 3 5 7 11\n', '0 1\n', '13 14 15'] })

t({ lv: 249, concept: '配列: 素数の和', title: 'リスト中の素数の和', tags: ['配列', '数論'], io: '整数の列が1行で与えられます。', ask: '素数である要素の合計を出力してください。', h1: '各要素を素数判定。', h2: '素数だけ足す。', ref: 'a=list(map(int,input().split()))\ndef is_prime(x):\n    if x<2:\n        return False\n    d=2\n    while d*d<=x:\n        if x%d==0:\n            return False\n        d+=1\n    return True\nprint(sum(x for x in a if is_prime(x)))', tip: '条件付き合計(素数だけ)はフィルタ＋sum。素数判定を関数化すると読みやすい。', ins: ['1 2 3 4 5\n', '4 6 8\n', '7\n', '2 3 5\n', '0 1\n', '11 13 14'] })

t({ lv: 250, concept: '配列: 回文数の個数', title: 'リスト中の回文数の個数', tags: ['配列'], io: '非負整数の列が1行で与えられます。', ask: '10進表記が回文になる要素の個数を出力してください。', h1: '各要素を文字列にして反転比較。', h2: '回文を数える。', ref: 'a=input().split()\nprint(sum(1 for s in a if s==s[::-1]))', tip: '回文数判定は文字列のまま s==s[::-1]。入力をそのまま文字列で扱うと簡潔。', ins: ['1 22 121 123\n', '7\n', '10 11 12\n', '0 5 55\n', '99 100 101\n', '1221'] })

t({ lv: 251, concept: '配列: 桁数が偶数の要素数', title: '桁数が偶数の要素の個数', tags: ['配列'], io: '非負整数の列が1行で与えられます。', ask: '10進の桁数が偶数である要素の個数を出力してください。', h1: '各要素の桁数を見る。', h2: '偶数桁を数える。', ref: 'a=input().split()\nprint(sum(1 for s in a if len(s)%2==0))', tip: '桁数は文字列の長さ。偶数桁の数え上げは len(s)%2==0 でフィルタ。', ins: ['1 22 333 4444\n', '5\n', '10 100\n', '0\n', '12 345 6789\n', '99 999'] })

t({ lv: 252, concept: '配列: 桁和の総和', title: '全要素の桁和の合計', tags: ['配列'], io: '非負整数の列が1行で与えられます。', ask: '各要素の桁の和を求め、それらの合計を出力してください。', h1: '各要素の桁和を計算。', h2: 'それらを合計。', ref: 'a=input().split()\nprint(sum(sum(int(c) for c in s) for s in a))', tip: '各要素の桁和の総和は二重の sum。文字列のまま各桁を int 化して足す。', ins: ['12 34\n', '5\n', '100 200\n', '0\n', '9 99 999\n', '11 22 33'] })

t({ lv: 253, concept: '配列: 最大の桁和', title: '桁和が最大の要素の桁和', tags: ['配列'], io: '非負整数の列が1行で与えられます。', ask: '各要素の桁和のうち最大の値を出力してください。', h1: '各要素の桁和を求める。', h2: 'その最大。', ref: 'a=input().split()\nprint(max(sum(int(c) for c in s) for s in a))', tip: '桁和の最大は各要素で桁和を計算して max。桁和でソートする問題の前段にもなる。', ins: ['12 99 5\n', '5\n', '100 19\n', '0\n', '111 9\n', '88 77'] })

t({ lv: 254, concept: '数論: 2数の最小公倍数', title: '2数の最小公倍数', tags: ['数論'], io: 'a b が空白区切りで与えられます。', ask: 'a と b の最小公倍数を出力してください。', h1: 'gcd を求める。', h2: 'a·b/gcd。', ref: 'import math\na,b=map(int,input().split())\nprint(a*b//math.gcd(a,b))', tip: 'lcm(a,b)=a·b/gcd(a,b)。先に gcd で割るとオーバーフローを避けられる。', ins: ['4 6\n', '3 5\n', '12 18\n', '7 7\n', '1 10\n', '8 12'] })

t({ lv: 255, concept: '数論: リストの最小公倍数', title: 'リスト全体の最小公倍数', tags: ['数論'], io: '正整数の列が1行で与えられます。', ask: '全要素の最小公倍数を出力してください。', h1: '順に lcm を畳み込む。', h2: 'lcm(a,b)=a·b/gcd。', ref: 'import math\nfrom functools import reduce\na=list(map(int,input().split()))\nprint(reduce(lambda x,y:x*y//math.gcd(x,y),a))', tip: '配列のLCMは reduce で lcm を畳み込む。lcm は結合的なので順序に依らない。', ins: ['2 3 4\n', '5\n', '6 10 15\n', '1 1 1\n', '2 4 8\n', '3 5 7'] })

t({ lv: 256, concept: '数論: 互いに素なペア数', title: 'リスト中の互いに素なペア数', tags: ['数論'], io: '正整数の列が1行で与えられます。', ask: 'gcd が1になる2要素のペア (i<j) の個数を出力してください。', h1: '全ペアの gcd を見る。', h2: 'gcd==1 を数える。', ref: 'import math\na=list(map(int,input().split()))\nn=len(a)\ncnt=0\nfor i in range(n):\n    for j in range(i+1,n):\n        if math.gcd(a[i],a[j])==1:\n            cnt+=1\nprint(cnt)', tip: '互いに素なペア数は全ペアの gcd を見る素朴 O(n²)。大規模はメビウス関数で高速化。', ins: ['2 3 4\n', '4 6 8\n', '1 1\n', '5 7 11\n', '6\n', '2 3 5 7'] })

t({ lv: 257, concept: '数論: 隣接gcdの和', title: '隣り合う要素のgcdの和', tags: ['数論'], io: '正整数の列が1行で与えられます(2個以上)。', ask: '隣接する2要素の gcd を全て足した値を出力してください。', h1: '隣接ペアの gcd を取る。', h2: 'その合計。', ref: 'import math\na=list(map(int,input().split()))\nprint(sum(math.gcd(a[i],a[i+1]) for i in range(len(a)-1)))', tip: '隣接gcdの和は zip(a, a[1:]) でペアを作って gcd を合計。系列の関連度の指標。', ins: ['4 6 8\n', '3 5\n', '12 18 6\n', '7 7 7\n', '2 4\n', '10 15 20'] })

t({ lv: 258, concept: '数: 2乗和と和の2乗の差', title: '和の2乗と2乗和の差', tags: ['数学'], io: '整数列が1行で与えられます。', ask: '(要素の和)² から (要素の2乗の和) を引いた値を出力してください。', h1: '和と2乗和を別々に求める。', h2: '差を取る。', ref: 'a=list(map(int,input().split()))\ns=sum(a)\nsq=sum(x*x for x in a)\nprint(s*s-sq)', tip: '(Σx)²-Σx² = 2·Σ_{i<j}x_i·x_j(ペア積の2倍)という恒等式。ペア積の総和を割り算なしで一発で求める古典。', ins: ['1 2 3\n', '5\n', '1 1 1\n', '10 20\n', '0 0\n', '1 2 3 4'] })

t({ lv: 259, concept: '配列: ハーシャッド数の個数', title: '桁和で割り切れる数の個数', tags: ['配列'], io: '正整数の列が1行で与えられます。', ask: '各要素が自身の桁和で割り切れる(ハーシャッド数)ものの個数を出力してください。', h1: '各要素の桁和を求める。', h2: '割り切れるか判定。', ref: 'a=input().split()\ncnt=0\nfor s in a:\n    ds=sum(int(c) for c in s)\n    if ds!=0 and int(s)%ds==0:\n        cnt+=1\nprint(cnt)', tip: 'ハーシャッド数判定を各要素に適用。桁和を計算してから整除を確認する。', ins: ['18 19 21\n', '1\n', '10 12\n', '100\n', '11 22 33\n', '13 17'] })

t({ lv: 260, concept: '配列: 反転が存在する数の個数', title: '逆順の数も列にある要素の数', tags: ['配列', 'ハッシュ'], io: '非負整数の列が1行で与えられます。', ask: 'その数の桁を逆順にした数も列に含まれる要素の個数を出力してください(自分自身が回文なら自分を反転とみなしてよい)。', h1: '集合に入れる。', h2: '各要素の反転が集合にあるか。', ref: 'a=input().split()\ns=set(int(x) for x in a)\ncnt=0\nfor x in a:\n    if int(x[::-1]) in s:\n        cnt+=1\nprint(cnt)', tip: '反転数の存在判定は集合で。文字列反転 x[::-1] を int 化して in で確認する。', ins: ['12 21 13\n', '5\n', '10 1\n', '11 22\n', '123 321 9\n', '100 1'] })

t({ lv: 261, concept: '配列: アームストロング数の個数', title: 'ナルシシスト数の個数', tags: ['配列'], io: '正整数の列が1行で与えられます。', ask: '各桁を桁数乗した和が自分に等しい(アームストロング数)要素の個数を出力してください。', h1: '各要素で桁数乗和を計算。', h2: '自分と一致するか。', ref: 'a=input().split()\ncnt=0\nfor s in a:\n    k=len(s)\n    if sum(int(c)**k for c in s)==int(s):\n        cnt+=1\nprint(cnt)', tip: 'アームストロング数判定(各桁の桁数乗の和)を各要素に適用。153,370などが該当。', ins: ['153 154 9\n', '1\n', '370 371\n', '10\n', '407 100\n', '5 6 7'] })

t({ lv: 262, concept: '配列: 相異なる桁和の数', title: '相異なる桁和の種類数', tags: ['配列', '集合'], io: '非負整数の列が1行で与えられます。', ask: '各要素の桁和を求め、その相異なる種類数を出力してください。', h1: '各桁和を集合に入れる。', h2: '要素数を取る。', ref: 'a=input().split()\nds=set(sum(int(c) for c in s) for s in a)\nprint(len(ds))', tip: '桁和の種類数は各桁和を集合に。digital root などで同値類にまとめる前段になる。', ins: ['12 21 30\n', '5\n', '10 100\n', '11 22\n', '9 18 27\n', '1 2 3'] })

t({ lv: 263, concept: '数論: 隣接lcmの最小', title: '隣り合う要素のlcmの最小', tags: ['数論'], io: '正整数の列が1行で与えられます(2個以上)。', ask: '隣接する2要素の最小公倍数のうち最小の値を出力してください。', h1: '隣接ペアの lcm を取る。', h2: 'その最小。', ref: 'import math\na=list(map(int,input().split()))\nprint(min(a[i]*a[i+1]//math.gcd(a[i],a[i+1]) for i in range(len(a)-1)))', tip: '隣接lcmの最小は各ペアで lcm を求めて min。lcm=積/gcd の組合せ。', ins: ['4 6 3\n', '2 4\n', '5 10 2\n', '7 7\n', '3 9 6\n', '8 12 4'] })

t({ lv: 264, concept: '配列: 2のべきの個数', title: '2のべき乗である要素の個数', tags: ['配列', 'bit演算'], io: '正整数の列が1行で与えられます。', ask: '2のべき乗(1,2,4,8,...)である要素の個数を出力してください。', h1: 'x>0 かつ x&(x-1)==0。', h2: '条件カウント。', ref: 'a=list(map(int,input().split()))\nprint(sum(1 for x in a if x>0 and (x&(x-1))==0))', tip: '2のべき判定は x&(x-1)==0(立つビットが1個)。各要素に適用して数える。', ins: ['1 2 3 4\n', '5 6 7\n', '8\n', '16 32 64\n', '3\n', '1 1 2'] })

t({ lv: 265, concept: '配列: 降順の隣接ペア数', title: '隣り合って減少するペアの数', tags: ['配列'], io: '整数列が1行で与えられます。', ask: 'a[i]>a[i+1] となる隣接ペアの個数を出力してください。', h1: '隣接要素を比べる。', h2: '減少を数える。', ref: 'a=list(map(int,input().split()))\nprint(sum(1 for i in range(len(a)-1) if a[i]>a[i+1]))', tip: '降順隣接ペア(descents)は増加版と対称。並びの乱れの指標になる。', ins: ['3 1 2 1\n', '1 2 3\n', '3 2 1\n', '5\n', '1 1 1\n', '5 3 4 2 1'] })

t({ lv: 266, concept: '配列: ゼロで区切られた区間数', title: '0で区切られた非ゼロ区間の数', tags: ['配列'], io: '整数列が1行で与えられます。', ask: '0を区切りとみなしたときの、非ゼロ要素が連続する区間(ブロック)の数を出力してください。', h1: '非ゼロが始まる位置を数える。', h2: '直前が0または先頭なら新ブロック。', ref: 'a=list(map(int,input().split()))\ncnt=0\nprev0=True\nfor x in a:\n    if x!=0:\n        if prev0:\n            cnt+=1\n        prev0=False\n    else:\n        prev0=True\nprint(cnt)', tip: '0区切りの非ゼロブロック数は「0の直後に非ゼロが来る回数」。区切り文字でのトークン分割と同型。', ins: ['1 2 0 3 0 0 4\n', '0 0 0\n', '1 2 3\n', '0\n', '1 0 1 0 1\n', '5 5 0 5'] })

t({ lv: 267, concept: '配列: ラン(連続同値ブロック)の数', title: '連続する同値ブロックの数', tags: ['配列'], io: '整数列が1行で与えられます。', ask: '同じ値が連続するブロック(ラン)の個数を出力してください。', h1: '直前と異なる位置を数える。', h2: '変化点+1がラン数。', ref: 'a=list(map(int,input().split()))\nif not a:\n    print(0)\nelse:\n    cnt=1\n    for i in range(1,len(a)):\n        if a[i]!=a[i-1]:\n            cnt+=1\n    print(cnt)', tip: 'ラン数は「隣接で値が変わる回数+1」。ランレングス圧縮後の長さに等しい。', ins: ['1 1 2 2 2 3\n', '1 2 3\n', '5 5 5\n', '1\n', '1 2 2 1\n', '7 7 8 8 8 7'] })

t({ lv: 268, concept: '配列: 隣接和の最小', title: '隣り合う2要素の和の最小', tags: ['配列'], io: '整数列が1行で与えられます(2個以上)。', ask: '隣接する2要素の和の最小値を出力してください。', h1: '隣接ペアの和を取る。', h2: 'その最小。', ref: 'a=list(map(int,input().split()))\nprint(min(a[i]+a[i+1] for i in range(len(a)-1)))', tip: '隣接和の最小は連続2要素の和の最小。長さ2の窓の最小和。最大版と対称。', ins: ['1 2 3 4\n', '5 2\n', '-3 -4 1\n', '0 5 0\n', '2 2 2\n', '1 10 1 10'] })

t({ lv: 269, concept: '配列: 符号反転の回数', title: '符号が変わる回数', tags: ['配列'], io: '0を含まない整数列が1行で与えられます。', ask: '隣り合う要素で符号(正負)が変わる回数を出力してください。', h1: '隣接の符号を比べる。', h2: '異なれば数える。', ref: 'a=list(map(int,input().split()))\nprint(sum(1 for i in range(len(a)-1) if (a[i]>0)!=(a[i+1]>0)))', tip: '符号反転の回数は (x>0) の真偽が隣で変わる数。振動やゼロ交差の検出に使う。', ins: ['1 -1 1 -1\n', '1 2 3\n', '-1 -2 -3\n', '5\n', '1 -2 3\n', '-1 1 1 -1'] })

t({ lv: 270, concept: '配列: 最小絶対値', title: 'リストの最小絶対値', tags: ['配列'], io: '整数列が1行で与えられます。', ask: '絶対値が最小の要素の絶対値を出力してください(0に最も近い要素の絶対値)。', h1: '各要素の絶対値。', h2: 'その最小。', ref: 'a=list(map(int,input().split()))\nprint(min(abs(x) for x in a))', tip: '最小絶対値は min(abs(x))。0に最も近い値を探すのに使う。最大絶対値と対称。', ins: ['1 -5 3\n', '5\n', '-10 2\n', '0 9\n', '-3 -7 4\n', '8 -8'] })

t({ lv: 271, concept: '配列: 偶数の積', title: '偶数要素の積', tags: ['配列'], io: '整数列が1行で与えられます。', ask: '偶数の要素だけの積を出力してください(偶数が無ければ1)。', h1: '偶数を選ぶ。', h2: '掛け合わせる。', ref: 'a=list(map(int,input().split()))\np=1\nfor x in a:\n    if x%2==0:\n        p*=x\nprint(p)', tip: '条件付きの積。偶数だけ掛ける。空の積は1(乗法の単位元)とする慣習。', ins: ['1 2 3 4\n', '1 3 5\n', '2 4\n', '0 1\n', '6\n', '2 2 2'] })

t({ lv: 272, concept: '配列: ゼロ交差の数', title: '正と負の境界の数', tags: ['配列'], io: '0を含まない整数列が1行で与えられます。', ask: '正の値と負の値の境界(隣接で符号が異なる箇所)の数を出力してください。', h1: '隣接の符号を比べる。', h2: '異符号を数える。', ref: 'a=list(map(int,input().split()))\nprint(sum(1 for i in range(len(a)-1) if a[i]*a[i+1]<0))', tip: 'ゼロ交差は隣接積が負(a[i]·a[i+1]<0)の箇所。信号処理の基本特徴量。', ins: ['1 -1 2 -2\n', '1 2 3\n', '-1 -1\n', '5\n', '3 -1 -2 4\n', '-1 1'] })

t({ lv: 273, concept: 'ハッシュ: kで割った余りの種類数', title: 'mod kの相異なる余りの数', tags: ['ハッシュ'], io: '1行目に k、2行目に整数列が与えられます。', ask: '各要素を k で割った余りの相異なる種類数を出力してください。', h1: '余りを集合に入れる。', h2: '要素数を取る。', ref: 'k=int(input())\na=list(map(int,input().split()))\nprint(len(set(x%k for x in a)))', tip: '剰余類の種類数は set(x%k)。ハッシュやグループ分けの基礎となる剰余演算。', ins: ['3\n1 2 3 4 5\n', '2\n2 4 6\n', '5\n1 6 11\n', '10\n5\n', '3\n3 6 9\n', '4\n1 2 3'] })

t({ lv: 274, concept: 'ハッシュ: 最頻の余り', title: 'mod kで最も多い余り', tags: ['ハッシュ'], io: '1行目に k、2行目に整数列が与えられます。', ask: '各要素を k で割った余りのうち、最も多く現れる余りを出力してください。同数なら最小。', h1: '余りの出現回数を数える。', h2: '(回数降順, 余り昇順)で選ぶ。', ref: 'from collections import Counter\nk=int(input())\na=list(map(int,input().split()))\ncnt=Counter(x%k for x in a)\nbest=None\nbestc=-1\nfor r in sorted(cnt):\n    if cnt[r]>bestc:\n        bestc=cnt[r]\n        best=r\nprint(best)', tip: '最頻の剰余類は余りを Counter で数えて最頻を選ぶ。負荷分散やハッシュ衝突の解析に使う。', ins: ['3\n1 2 3 4 6\n', '2\n1 3 5\n', '5\n5 10 1\n', '4\n0 4 8\n', '3\n1 1 2\n', '2\n2 4 1'] })

t({ lv: 275, concept: '配列: パリティ別の和', title: '偶数の和と奇数の和', tags: ['配列'], io: '整数列が1行で与えられます。', ask: '偶数の合計と奇数の合計を空白区切りで出力してください。', h1: '偶奇で分けて足す。', h2: '2つの和を出す。', ref: 'a=list(map(int,input().split()))\neven=sum(x for x in a if x%2==0)\nodd=sum(x for x in a if x%2==1)\nprint(even,odd)', tip: 'パリティ別集計は条件付き sum を2回。グループ集計(groupby)の最小形。', ins: ['1 2 3 4\n', '2 4 6\n', '1 3 5\n', '0\n', '10 5\n', '7 8 9 10'] })

t({ lv: 276, concept: '配列: 正の数の個数', title: '正の数の個数', tags: ['配列'], io: '整数列が1行で与えられます。', ask: '0より大きい要素の個数を出力してください。', h1: '0より大きいか見る。', h2: '条件カウント。', ref: 'a=list(map(int,input().split()))\nprint(sum(1 for x in a if x>0))', tip: '正の数の数え上げは x>0。負・ゼロ・正で3分類する集計の一部。', ins: ['1 -1 2 0\n', '1 2 3\n', '-1 -2\n', '0 0\n', '5\n', '-3 4 -5 6'] })

t({ lv: 277, concept: '配列: 中間値の個数', title: '最小と最大の間にある要素数', tags: ['配列'], io: '整数列が1行で与えられます。', ask: '最小値より大きく最大値より小さい要素(両端を除く)の個数を出力してください。', h1: '最小と最大を求める。', h2: 'その間にある数を数える。', ref: 'a=list(map(int,input().split()))\nlo=min(a)\nhi=max(a)\nprint(sum(1 for x in a if lo<x<hi))', tip: '中間値の個数は両端を除いた範囲のカウント。外れ値除去後の規模などに使う。', ins: ['1 2 3 4 5\n', '1 5\n', '3 3 3\n', '1 2 3\n', '5\n', '0 10 5 5'] })

t({ lv: 278, concept: '配列: 谷型の列の判定', title: '配列が谷型(V字)か', tags: ['配列'], io: '整数列が1行で与えられます。', ask: '厳密に減少してから厳密に増加する(谷型)なら yes、違うなら no を出力してください(単調のみは no)。', h1: '減少部分と増加部分を順に見る。', h2: '減少→増加の1回だけなら yes。', ref: 'a=list(map(int,input().split()))\nn=len(a)\ni=0\nwhile i+1<n and a[i]>a[i+1]:\n    i+=1\nif i==0 or i==n-1:\n    print("no")\nelse:\n    while i+1<n and a[i]<a[i+1]:\n        i+=1\n    print("yes" if i==n-1 else "no")', tip: '谷型(V字)判定は「減少してから増加」を順に消費。ビトニック(山型)の上下反転版。', ins: ['5 3 1 2 4\n', '1 2 3\n', '3 2 1\n', '3 1 2\n', '2 1 1\n', '6 4 2 3 5 7'] })

t({ lv: 279, concept: '配列: 隣接差の種類数', title: '相異なる隣接差の種類数', tags: ['配列', '集合'], io: '整数列が1行で与えられます(2個以上)。', ask: '隣り合う要素の差(後-前)の相異なる種類数を出力してください。', h1: '隣接差を集合に入れる。', h2: '要素数を取る。', ref: 'a=list(map(int,input().split()))\nprint(len(set(a[i+1]-a[i] for i in range(len(a)-1))))', tip: '隣接差の種類数。差が1種類なら等差数列。階差の分布を見る指標。', ins: ['1 2 3 4\n', '1 3 6 10\n', '5 5 5\n', '1 2\n', '2 4 6 8\n', '1 2 4 7'] })

t({ lv: 280, concept: '配列: 極値の個数', title: '局所的な山と谷の合計数', tags: ['配列'], io: '整数列が1行で与えられます。', ask: '両隣より大きい(山)または両隣より小さい(谷)内部要素の個数を合計して出力してください。', h1: '内側の各位置を見る。', h2: '山か谷を数える。', ref: 'a=list(map(int,input().split()))\ncnt=0\nfor i in range(1,len(a)-1):\n    if (a[i]>a[i-1] and a[i]>a[i+1]) or (a[i]<a[i-1] and a[i]<a[i+1]):\n        cnt+=1\nprint(cnt)', tip: '極値(山＋谷)の数は局所最大と局所最小の合計。波形の起伏の多さを表す。', ins: ['1 3 2 4 1\n', '1 2 3\n', '3 1 2 1 3\n', '5\n', '1 1 1\n', '2 5 1 6 3'] })

t({ lv: 281, concept: '配列: 素数添字の和', title: '素数の添字にある要素の和', tags: ['配列', '数論'], io: '整数列が1行で与えられます。', ask: '添字(0始まり)が素数である要素の合計を出力してください。', h1: '添字が素数か判定。', h2: '該当要素を足す。', ref: 'a=list(map(int,input().split()))\ndef is_prime(x):\n    if x<2:\n        return False\n    d=2\n    while d*d<=x:\n        if x%d==0:\n            return False\n        d+=1\n    return True\nprint(sum(a[i] for i in range(len(a)) if is_prime(i)))', tip: '添字に条件をかける集計。素数の添字 2,3,5,7,... の要素だけ足す。', ins: ['10 20 30 40 50\n', '1 2 3\n', '5\n', '0 1 2 3 4 5\n', '1 1 1 1\n', '9 8 7 6 5 4 3'] })

t({ lv: 282, concept: '配列: 累積和が最大の位置', title: '累積和が最大になる位置', tags: ['配列'], io: '整数列が1行で与えられます。', ask: '先頭からの累積和が最大になる位置(0始まり、最初のもの)を出力してください。', h1: '累積和を走査。', h2: '最大時の位置を記録。', ref: 'a=list(map(int,input().split()))\ns=0\nbest=None\nbesti=0\nfor i,x in enumerate(a):\n    s+=x\n    if best is None or s>best:\n        best=s\n        besti=i\nprint(besti)', tip: '累積和の最大位置は走査しながら最大を更新。利益が最大になる時点などに対応する。', ins: ['1 2 -1 3\n', '-1 -2 -3\n', '1 1 1\n', '5\n', '3 -5 4\n', '2 2 -10 2'] })

t({ lv: 283, concept: '配列: 増加した回数', title: '前より大きくなった回数', tags: ['配列'], io: '整数列が1行で与えられます。', ask: '直前の要素より大きくなった回数を出力してください。', h1: '隣接を比べる。', h2: '増加を数える。', ref: 'a=list(map(int,input().split()))\nprint(sum(1 for i in range(1,len(a)) if a[i]>a[i-1])) ', tip: '増加回数(上昇の数)は時系列の上昇日数などに対応。隣接比較の基本集計。', ins: ['1 2 1 3 3\n', '1 2 3\n', '3 2 1\n', '5\n', '1 1 1\n', '2 1 2 1 5'] })

t({ lv: 284, concept: '配列: 自分より後に小さい数がある要素数', title: '右に小さい数を持つ要素の数', tags: ['配列'], io: '整数列が1行で与えられます。', ask: '自分より右に、自分より小さい要素が1つでもある要素の個数を出力してください。', h1: '右からの最小を追う。', h2: '右の最小より大きいか。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nmn=float("inf")\ncnt=0\nfor i in range(n-1,-1,-1):\n    if a[i]>mn:\n        cnt+=1\n    if a[i]<mn:\n        mn=a[i]\nprint(cnt)', tip: '「右に小さい数を持つ」は右からの累積最小と比較する O(n)。降順でない要素の数に対応。', ins: ['3 1 2 4\n', '1 2 3\n', '3 2 1\n', '5\n', '1 1 1\n', '5 4 3 2 1'] })

t({ lv: 285, concept: '配列: 最大値の出現回数', title: '最大値が現れる回数', tags: ['配列'], io: '整数列が1行で与えられます。', ask: '最大値が現れる回数を出力してください。', h1: '最大値を求める。', h2: 'count で数える。', ref: 'a=list(map(int,input().split()))\nm=max(a)\nprint(a.count(m))', tip: '最大値の出現回数は max を求めてから count。最頻最大値の多重度を測る。', ins: ['1 3 3 2\n', '5\n', '1 1 1\n', '1 2 3\n', '4 4 4 4\n', '7 8 8'] })

t({ lv: 286, concept: 'ハッシュ: 値と頻度が一致する数', title: '出現回数が値に等しい要素数', tags: ['ハッシュ'], io: '正整数の列が1行で与えられます。', ask: '値 v がちょうど v 回現れるような相異なる値 v の種類数を出力してください。', h1: '出現回数を数える。', h2: '回数==値 を数える。', ref: 'from collections import Counter\na=list(map(int,input().split()))\ncnt=Counter(a)\nprint(sum(1 for v in cnt if cnt[v]==v))', tip: '「値=頻度」の数え上げ。Counter のキーと値が一致するものを探す自己参照的な集計。', ins: ['1 2 2 3 3 3\n', '1\n', '2 2\n', '1 2 3\n', '3 3 3\n', '2 2 2'] })

t({ lv: 287, concept: 'ハッシュ: ちょうどk回の値の数', title: 'ちょうどk回現れる値の種類数', tags: ['ハッシュ'], io: '1行目に k、2行目に整数列が与えられます。', ask: '出現回数がちょうど k 回の値の種類数を出力してください。', h1: '出現回数を数える。', h2: '回数==k を数える。', ref: 'from collections import Counter\nk=int(input())\na=list(map(int,input().split()))\ncnt=Counter(a)\nprint(sum(1 for v in cnt.values() if v==k))', tip: '回数指定の集計の一般形(k回)。1回・2回の特殊版をパラメータ化したもの。', ins: ['2\n1 1 2 3 3\n', '1\n1 2 3\n', '3\n1 1 1\n', '2\n5\n', '1\n4 4 5\n', '2\n7 7 8 8'] })

t({ lv: 288, concept: 'ハッシュ: 頻度の最大-最小', title: '出現回数の最大と最小の差', tags: ['ハッシュ'], io: '整数列が1行で与えられます。', ask: '相異なる値の出現回数のうち最大と最小の差を出力してください。', h1: '出現回数を数える。', h2: '回数の max-min。', ref: 'from collections import Counter\na=list(map(int,input().split()))\nv=list(Counter(a).values())\nprint(max(v)-min(v))', tip: '頻度のばらつきは max-min。データの偏り具合を測る単純な指標。', ins: ['1 1 2 3 3 3\n', '1 2 3\n', '5 5 5\n', '1\n', '4 4 5 5 6\n', '7 7 7 8'] })

t({ lv: 289, concept: '配列: 全桁が相異なる数の個数', title: '各桁が異なる数の個数', tags: ['配列'], io: '非負整数の列が1行で与えられます。', ask: 'どの桁も重複しない(全桁が相異なる)要素の個数を出力してください。', h1: '各要素の桁を集合と比べる。', h2: '桁数と種類数が一致するか。', ref: 'a=input().split()\nprint(sum(1 for s in a if len(set(s))==len(s)))', tip: '全桁相異なる判定は len(set(s))==len(s)。文字の重複検出と同じイディオム。', ins: ['12 11 123\n', '5\n', '122 34\n', '0\n', '102 99\n', '123 321 11'] })

t({ lv: 290, concept: '配列: 重複桁を持つ数の個数', title: '同じ桁を含む数の個数', tags: ['配列'], io: '非負整数の列が1行で与えられます。', ask: '少なくとも1つ重複する桁を持つ要素の個数を出力してください。', h1: '桁数と種類数を比べる。', h2: '異なれば重複あり。', ref: 'a=input().split()\nprint(sum(1 for s in a if len(set(s))<len(s)))', tip: '重複桁を持つ判定は len(set(s))<len(s)。全桁相異なる(別問題)の余事象。', ins: ['12 11 123\n', '5\n', '122 34\n', '0\n', '102 99\n', '112 121 1'] })

t({ lv: 291, concept: '配列: 偶数桁の合計', title: '全要素の偶数桁の合計', tags: ['配列'], io: '非負整数の列が1行で与えられます。', ask: '全要素の桁のうち偶数(0,2,4,6,8)である桁の値の合計を出力してください。', h1: '各桁の偶奇を見る。', h2: '偶数桁を足す。', ref: 'a=input().split()\ntotal=0\nfor s in a:\n    for c in s:\n        d=int(c)\n        if d%2==0:\n            total+=d\nprint(total)', tip: '桁レベルのフィルタ集計。全要素の全桁を走査して偶数桁だけ足す二重ループ。', ins: ['12 34\n', '5\n', '246 13\n', '0\n', '111 2\n', '8 8 8'] })

t({ lv: 292, concept: '配列: 奇数桁の合計', title: '全要素の奇数桁の合計', tags: ['配列'], io: '非負整数の列が1行で与えられます。', ask: '全要素の桁のうち奇数(1,3,5,7,9)である桁の値の合計を出力してください。', h1: '各桁の偶奇を見る。', h2: '奇数桁を足す。', ref: 'a=input().split()\ntotal=0\nfor s in a:\n    for c in s:\n        d=int(c)\n        if d%2==1:\n            total+=d\nprint(total)', tip: '偶数桁の合計と対になる奇数桁版。桁単位の条件集計のパターン。', ins: ['12 34\n', '5\n', '135 24\n', '0\n', '222 1\n', '9 9 9'] })

t({ lv: 293, concept: '数: 桁を並べ替えた最大数', title: '桁を並べ替えて作る最大の数', tags: ['数学'], io: '非負整数 n が1行で与えられます。', ask: 'n の桁を並べ替えて作れる最大の整数を出力してください。', h1: '桁を降順に並べる。', h2: '連結して整数化。', ref: 'n=input().strip()\nprint(int("".join(sorted(n,reverse=True))))', tip: '桁を並べ替えた最大数は桁を降順ソートして連結。貪欲に大きい桁を前へ置く。', ins: ['123\n', '0\n', '9\n', '4071\n', '111\n', '321'] })

t({ lv: 294, concept: '数: 桁を並べ替えた最小数', title: '桁を並べ替えて作る最小の数', tags: ['数学'], io: '非負整数 n が1行で与えられます。', ask: 'n の桁を並べ替えて作れる最小の整数を出力してください(先頭0は数値として消える)。', h1: '桁を昇順に並べる。', h2: '連結して整数化。', ref: 'n=input().strip()\nprint(int("".join(sorted(n))))', tip: '桁を昇順ソートして連結すると最小数。int 化で先頭の0が自動的に消える。', ins: ['321\n', '0\n', '9\n', '4071\n', '111\n', '120'] })

export const CATALOG = TASKS
