// 生成タスク 第60波：各レベル2問化フェーズ(15)。lv666〜690 に2問目を追加。
// 古典DP/文字列DP/しゃくとり帯。重複なし・決定的・採点一意。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 666, concept: '累積和: 円環で和がSの区間数', title: '円卓で合計がSになる連続区間', tags: ['累積和'], io: '1行目に目標 S、2行目に円環状に並んだ整数列が与えられます。', ask: '円環上の連続した区間(長さ1以上n以下)で、和がちょうど S のものの個数を出力してください(開始位置と長さが違えば別と数える)。', h1: '配列を2周分つなげると円環の区間が普通の区間になる。', h2: '開始位置ごとに長さ1..nを試す。大きな入力では接頭和+辞書に発展する。', ref: 's=int(input())\na=list(map(int,input().split()))\nn=len(a)\ncnt=0\nfor st in range(n):\n    run=0\n    for L in range(1,n+1):\n        run+=a[(st+L-1)%n]\n        if run==s:\n            cnt+=1\nprint(cnt)', tip: '円環は「2倍に延長」か「添字を%nで回す」かの二択で直線に戻せる。全周(長さn)の区間を数えるかどうかの境界条件が唯一の罠。', ins: ['5\n2 3 1 4\n', '3\n1 1 1\n', '10\n2 3 1 4\n', '0\n1 -1 2\n', '7\n7\n', '4\n2 2 2 2\n'] })

t({ lv: 667, concept: '累積和: 積が正の部分配列の個数', title: '積が正になる区間を数える', tags: ['累積和'], io: '0を含まない整数列が1行で空白区切りで与えられます。', ask: '要素の積が正になる連続部分配列の個数を出力してください。', h1: '積の符号は「負の個数の偶奇」で決まる。', h2: '接頭辞ごとの負の個数の偶奇を数え、同じ偶奇のペア数を組合せで数える。', ref: 'a=list(map(int,input().split()))\neven=1\nodd=0\np=0\ncnt=0\nfor x in a:\n    if x<0:\n        p^=1\n    if p==0:\n        cnt+=even\n        even+=1\n    else:\n        cnt+=odd\n        odd+=1\nprint(cnt)', tip: '「区間の性質」を「接頭辞2点の関係」に置き換える定石の符号版。和がkの区間数と同じ勘定が、パリティという2値の世界でも成立する。', ins: ['1 2 3\n', '-1 -2 3\n', '-1 2 -3 4\n', '-5\n', '2 -2 2\n', '-1 -1 -1 -1\n'] })

t({ lv: 668, concept: 'DP: k連続を避ける最大和', title: 'k個連続では選べない最大和', tags: ['DP'], io: '1行目に k、2行目に正整数列が与えられます。', ask: 'どの k 個連続の並びも「全部選ぶ」ことにならないように要素を選ぶ(k連続選択の禁止)ときの、選んだ合計の最大を出力してください。', h1: '状態は「今何個連続で選んでいるか」。', h2: 'dp[i][r] を先頭i個でr連続中の最大とし、選ぶ(r+1、kは不可)か選ばない(r=0)かで遷移。', ref: 'k=int(input())\na=list(map(int,input().split()))\nn=len(a)\nNEG=-10**18\ndp=[NEG]*k\ndp[0]=0\nfor x in a:\n    nd=[NEG]*k\n    nd[0]=max(dp)\n    for r in range(1,k):\n        if dp[r-1]>NEG:\n            nd[r]=dp[r-1]+x\n    dp=nd\nprint(max(dp))', tip: '隣接禁止(2連続禁止)の一般化は「連続選択数」を状態に持つだけ。禁止の形が変わってもDPは状態の定義で吸収する、を体感できる。', ins: ['2\n1 2 3\n', '3\n5 5 5 5\n', '2\n10 1 10\n', '4\n1 1 1 1\n', '2\n7\n', '3\n4 9 4 9 4\n'] })

t({ lv: 669, concept: '貪欲: 花壇に植えられる最大数', title: '間を空けて植えられる最大の花', tags: ['貪欲'], io: '0(空き)と1(植栽済み)の列が1行で空白区切りで与えられます。', ask: '隣どうしに花が並ばないという規則を守って、さらに植えられる花の最大本数を出力してください。', h1: '左から見て植えられる場所にはすぐ植えてよい。', h2: '両隣(端は片側)が0なら植えて、その場を1に更新して進む。', ref: 'a=list(map(int,input().split()))\nn=len(a)\ncnt=0\nfor i in range(n):\n    if a[i]==0 and (i==0 or a[i-1]==0) and (i==n-1 or a[i+1]==0):\n        a[i]=1\n        cnt+=1\nprint(cnt)', tip: '「植えても損しない」ことが交換論法で言えるので貪欲が最適。インデックスの端の場合分けを or の短絡評価で書くと簡潔になる。', ins: ['1 0 0 0 1\n', '0 0 0\n', '1 0 1 0 1\n', '0\n', '0 0 0 0 0\n', '1 1 0 0 0 1\n'] })

t({ lv: 670, concept: 'DP: 相異なる共通部分列の数', title: '共通の部分列は何種類か', tags: ['DP'], io: '1行目と2行目に英小文字の文字列が与えられます。', ask: '両方の文字列の部分列(連続でなくてよい)として現れる、空でない相異なる文字列の種類数を出力してください。', h1: '2次元DPで「共通部分列の種類数」を数える。', h2: 'f(i,j) は f(i−1,j)+f(i,j−1)−f(i−1,j−1)、末尾が一致するときはさらに f(i−1,j−1) を足す(包除)。', ref: 's=input()\nt=input()\nn,m=len(s),len(t)\nf=[[0]*(m+1) for _ in range(n+1)]\nfor i in range(n+1):\n    f[i][0]=1\nfor j in range(m+1):\n    f[0][j]=1\nfor i in range(1,n+1):\n    for j in range(1,m+1):\n        f[i][j]=f[i-1][j]+f[i][j-1]-f[i-1][j-1]\n        if s[i-1]==t[j-1]:\n            f[i][j]+=f[i-1][j-1]\nprint(f[n][m]-1)', tip: '重複を数えないDPは包除(足しすぎを引く)が芯。空列を1として持ち最後に引く設計は、数え上げDPの初期条件の典型テクニック。', ins: ['ab\nab\n', 'ab\nba\n', 'aa\naa\n', 'abc\nxyz\n', 'aab\nab\n', 'abab\nbaba\n'] })

t({ lv: 671, concept: 'DP: 隣接入れ替えも許す編集距離', title: '入れ替えもできる編集距離', tags: ['DP'], io: '1行目と2行目に英小文字の文字列が与えられます。', ask: '挿入・削除・置換に加えて「隣接2文字の入れ替え」も1操作として使えるときの、最小操作回数(ダメラウ・レーベンシュタイン距離)を出力してください。', h1: '普通の編集距離の表に遷移を1つ足す。', h2: 's[i−1]とt[j−2]、s[i−2]とt[j−1]が一致するとき dp[i−2][j−2]+1 で転置遷移できる。', ref: 's=input()\nt=input()\nn,m=len(s),len(t)\ndp=[[0]*(m+1) for _ in range(n+1)]\nfor i in range(n+1):\n    dp[i][0]=i\nfor j in range(m+1):\n    dp[0][j]=j\nfor i in range(1,n+1):\n    for j in range(1,m+1):\n        c=0 if s[i-1]==t[j-1] else 1\n        dp[i][j]=min(dp[i-1][j]+1,dp[i][j-1]+1,dp[i-1][j-1]+c)\n        if i>1 and j>1 and s[i-1]==t[j-2] and s[i-2]==t[j-1]:\n            dp[i][j]=min(dp[i][j],dp[i-2][j-2]+1)\nprint(dp[n][m])', tip: 'タイプミスの大半は隣接キーの入れ替えなので、スペルチェッカはこの距離を使う。遷移を1本足すだけで現実の誤りモデルに近づく好例。', ins: ['ab\nba\n', 'abc\nacb\n', 'ca\nabc\n', 'abc\nabc\n', 'a\nb\n', 'abcd\nbadc\n'] })

t({ lv: 672, concept: 'DP: 共通の回文部分列の最長', title: '2人に共通する最長の回文', tags: ['DP', '再帰'], io: '1行目と2行目に英小文字の文字列(各8文字以下)が与えられます。', ask: '両方の文字列の部分列であり、かつ回文でもある文字列の最大の長さを出力してください。', h1: '両文字列に区間を1つずつ持つ4添字のDP。', h2: '両区間の端の4文字が全て同じ文字なら内側+2。そうでなければ端をどれか縮める。', ref: 'import sys\nsys.setrecursionlimit(100000)\ns=input()\nt=input()\nmemo={}\ndef f(i,j,k,l):\n    if i>j or k>l:\n        return 0\n    key=(i,j,k,l)\n    if key in memo:\n        return memo[key]\n    if s[i]==s[j]==t[k]==t[l]:\n        if i==j and k==l:\n            r=1\n        elif i==j or k==l:\n            r=max(1,f(i+1,j-1,k+1,l-1))\n        else:\n            r=f(i+1,j-1,k+1,l-1)+2\n    else:\n        r=max(f(i+1,j,k,l),f(i,j-1,k,l),f(i,j,k+1,l),f(i,j,k,l-1))\n    memo[key]=r\n    return r\nprint(f(0,len(s)-1,0,len(t)-1))', tip: '最長回文部分列(2添字)とLCS(2添字)の合体で4添字になる。状態の直積で問題を掛け合わせる、DP設計の可換な組み立て方。', ins: ['ab\nba\n', 'aba\nab\n', 'abcba\nacbca\n', 'ab\ncd\n', 'aaa\naa\n', 'abab\nbaba\n'] })

t({ lv: 673, concept: '貪欲: 単調な区間への最小分割数', title: '上りか下りの区間に切り分ける', tags: ['貪欲'], io: '相異なる整数の列が1行で空白区切りで与えられます。', ask: '列を連続した区間に分け、各区間が単調増加または単調減少になるようにするときの、区間数の最小を出力してください。', h1: '方向が確定してから逆向きが来たら切るしかない。', h2: '「未確定→上り/下り」の状態を持ち、向きが崩れた位置で区間を増やして状態を戻す。', ref: 'a=list(map(int,input().split()))\nn=len(a)\ncnt=1\ndirection=0\nfor i in range(1,n):\n    d=1 if a[i]>a[i-1] else -1\n    if direction==0:\n        direction=d\n    elif d!=direction:\n        cnt+=1\n        direction=0\nprint(cnt)', tip: '「切るのを先延ばしにして損はない」ので貪欲が最適。向きが壊れた直後の要素は次の区間の先頭として方向未確定に戻す、が実装の勘所。', ins: ['1 2 3 2 1\n', '5 4 3 2 1\n', '1 3 2 4 3 5\n', '7\n', '1 2\n', '2 1 3 4 5\n'] })

t({ lv: 674, concept: 'DP: 高々k件の重み付き区間選択', title: 'k件までの仕事で報酬最大', tags: ['DP'], io: '1行目に 仕事数 n と上限 k、続く n 行に「開始 終了 報酬」が与えられます(終了と同時刻の開始は可)。', ask: '時間が重ならないように高々 k 件選ぶときの報酬合計の最大を出力してください。', h1: '終了時刻でソートし、各仕事と両立する直前の仕事を二分探索で見つける。', h2: 'dp[i][j] を「先頭i件でj件選んだ最大」とし、i番目を選ぶ/選ばないで遷移。', ref: 'import bisect\nn,k=map(int,input().split())\njobs=sorted([tuple(map(int,input().split())) for _ in range(n)],key=lambda x:x[1])\nends=[j[1] for j in jobs]\ndp=[[0]*(k+1) for _ in range(n+1)]\nfor i in range(1,n+1):\n    s,e,p=jobs[i-1]\n    prev=bisect.bisect_right(ends,s,0,i-1)\n    for j in range(k+1):\n        dp[i][j]=dp[i-1][j]\n        if j>0:\n            c=dp[prev][j-1]+p\n            if c>dp[i][j]:\n                dp[i][j]=c\nprint(dp[n][k])', tip: '重み付き区間スケジューリングに「件数」の次元を1本足した形。二分探索で直前互換ジョブを引くところは件数制限があっても変わらない。', ins: ['3 1\n1 3 5\n2 5 6\n4 6 5\n', '3 2\n1 3 5\n2 5 6\n4 6 5\n', '2 2\n1 2 3\n1 2 4\n', '1 1\n5 9 7\n', '4 2\n1 2 2\n2 3 2\n3 4 2\n4 5 2\n', '3 3\n1 2 1\n2 3 1\n3 4 1\n'] })

t({ lv: 675, concept: 'DP: 1つ消してよい最長連続増加', title: '1要素消して作る最長増加区間', tags: ['DP'], io: '整数列が1行で空白区切りで与えられます。', ask: '高々1つの要素を削除してよいとき、狭義単調増加の連続区間の最大の長さを出力してください。', h1: '各位置で「ここで終わる増加長」と「ここから始まる増加長」を前計算する。', h2: '要素iを消すとき a[i−1]<a[i+1] なら左右の増加長が連結できる。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nleft=[1]*n\nfor i in range(1,n):\n    if a[i]>a[i-1]:\n        left[i]=left[i-1]+1\nright=[1]*n\nfor i in range(n-2,-1,-1):\n    if a[i]<a[i+1]:\n        right[i]=right[i+1]+1\nbest=max(left)\nfor i in range(1,n-1):\n    if a[i-1]<a[i+1]:\n        c=left[i-1]+right[i+1]\n        if c>best:\n            best=c\nprint(best)', tip: '「消す1点」を全部試し、左右の前計算で各判定をO(1)にする。削除・置換・反転など1回だけの改変系はこの前後分解が定石。', ins: ['1 2 5 3 4\n', '1 2 3\n', '5 4 3\n', '1 9 2 3 4\n', '7\n', '1 3 2 4 5 6\n'] })

t({ lv: 676, concept: 'ゲーム: 3つまで取る得点ゲーム', title: '先頭から1〜3枚取り合うゲームの差', tags: ['ゲーム', 'DP'], io: '得点が書かれたカードの列が1行で空白区切りで与えられます(先頭からしか取れない)。', ask: '2人が交互に先頭から1〜3枚を取り、取ったカードの合計が自分の得点になります。両者最善のとき「先手の得点−後手の得点」を出力してください。', h1: '後ろから「自分の番がここから始まるときの得点差の最大」を考える。', h2: 'dp[i] は max(先頭x枚の和 − dp[i+x]) (x=1..3)。相手も最善なので引き算になる。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nsuf=[0]*(n+1)\nfor i in range(n-1,-1,-1):\n    suf[i]=suf[i+1]+a[i]\nNEG=-10**18\ndp=[NEG]*(n+1)\ndp[n]=0\nfor i in range(n-1,-1,-1):\n    take=0\n    for x in range(1,4):\n        if i+x<=n:\n            take+=a[i+x-1]\n            c=take-dp[i+x]\n            if c>dp[i]:\n                dp[i]=c\nprint(dp[0])', tip: 'ゲームDPは「得点差」を1本で持つと、自分の番も相手の番も同じ式 max(取り分−dp) で書ける。符号の反転が手番の交代を表す。', ins: ['1 2 3 7\n', '1 2 3 -9\n', '1 2 3 6\n', '5\n', '1 1 1 1 1\n', '-1 -2 -3\n'] })

t({ lv: 677, concept: 'DP: ちょうどk歩でn段を上る', title: 'ぴったりk歩で上り切る方法', tags: ['数学'], io: 'n k が空白区切りで1行で与えられます。', ask: '1段か2段ずつ、ちょうど k 歩で n 段を上り切る方法の数を出力してください(不可能なら0)。', h1: '2段を何回使うかは k と n から決まる。', h2: '2段の回数は n−k 回。歩の並べ方は C(k, n−k) 通り。', ref: 'from math import comb\nn,k=map(int,input().split())\ntwo=n-k\nif 0<=two<=k:\n    print(comb(k,two))\nelse:\n    print(0)', tip: '歩数を固定すると数え上げが二項係数1個に潰れる。DPで解ける問題も、制約を1つ足すと閉形式が現れることがある。', ins: ['5 3\n', '4 2\n', '3 3\n', '5 2\n', '2 1\n', '10 7\n'] })

t({ lv: 678, concept: 'DP: 壊れた段を踏まない上り方', title: '壊れた段を避けて上る方法の数', tags: ['DP'], io: '1行目に 段数 n と壊れた段の数 b、2行目に壊れた段の番号(b=0なら空行)が与えられます。', ask: '0段目から1歩で1段か2段上れ、壊れた段は踏めないとき、ちょうど n 段目(壊れていない)に立つ方法の数を出力してください。', h1: '普通の階段DPに「踏めない段は0」を足す。', h2: '壊れた段の dp を常に0にすれば遷移はそのまま。', ref: 'n,b=map(int,input().split())\nbroken=set(map(int,input().split())) if b>0 else set()\nif b==0:\n    input()\ndp=[0]*(n+1)\ndp[0]=1\nfor i in range(1,n+1):\n    if i in broken:\n        continue\n    dp[i]=dp[i-1]+(dp[i-2] if i>=2 else 0)\nprint(dp[n])', tip: '障害物ありのグリッド経路数と同じ「到達不能マスを0で埋める」型の1次元版。フィボナッチに障害物が混ざる様子が観察できる。', ins: ['4 1\n2\n', '4 0\n\n', '5 2\n2 4\n', '3 1\n1\n', '6 1\n3\n', '2 2\n1 2\n'] })

t({ lv: 679, concept: 'DP: 深さ制限つき括弧列の数', title: '深さd以下の正しい括弧列', tags: ['DP'], io: 'n d が空白区切りで1行で与えられます。', ask: '長さ 2n の正しい括弧列のうち、ネストの深さが d 以下のものの数を出力してください。', h1: '位置と現在の深さを状態にする。', h2: 'dp[位置][深さ] で、開くと深さ+1(d超は不可)、閉じると−1。', ref: 'n,d=map(int,input().split())\ndp=[[0]*(d+2) for _ in range(2*n+1)]\ndp[0][0]=1\nfor i in range(2*n):\n    for h in range(d+1):\n        if dp[i][h]==0:\n            continue\n        if h+1<=d:\n            dp[i+1][h+1]+=dp[i][h]\n        if h>0:\n            dp[i+1][h-1]+=dp[i][h]\nprint(dp[2*n][0])', tip: '深さ制限なしならカタラン数。制限つきは「幅d の帯の中を歩く格子路」の数えになり、dを大きくするとカタラン数へ収束する様子が見える。', ins: ['3 1\n', '3 2\n', '3 3\n', '4 2\n', '1 1\n', '5 1\n'] })

t({ lv: 680, concept: '累積和: 固定サイズ窓の最大和(2次元)', title: 'h×wの窓で最大の合計', tags: ['累積和'], io: '1行目に H W h w、続く H 行に整数の行列が与えられます (h≤H, w≤W)。', ask: 'サイズ h×w の長方形窓を置ける全ての位置の中で、窓内の合計の最大を出力してください。', h1: '2次元累積和を前計算する。', h2: '各位置の窓の和は累積和4点の加減でO(1)。', ref: 'H,W,h,w=map(int,input().split())\ng=[list(map(int,input().split())) for _ in range(H)]\nS=[[0]*(W+1) for _ in range(H+1)]\nfor i in range(H):\n    for j in range(W):\n        S[i+1][j+1]=S[i][j+1]+S[i+1][j]-S[i][j]+g[i][j]\nbest=None\nfor i in range(h,H+1):\n    for j in range(w,W+1):\n        v=S[i][j]-S[i-h][j]-S[i][j-w]+S[i-h][j-w]\n        if best is None or v>best:\n            best=v\nprint(best)', tip: '包除の4点差分は2次元累積和の核心。窓を全走査してもO(HW)で済むのは、1窓あたりの集計が定数時間に落ちているから。', ins: ['3 3 2 2\n1 2 3\n4 5 6\n7 8 9\n', '2 2 1 1\n-1 -2\n-3 -4\n', '2 3 2 3\n1 1 1\n1 1 1\n', '3 3 1 3\n1 2 3\n9 9 9\n4 5 6\n', '1 4 1 2\n3 -1 4 -1\n', '2 2 2 1\n5 1\n2 6\n'] })

t({ lv: 681, concept: '文字列: 部分列として含む単語の数', title: '文の中に隠れている単語', tags: ['文字列'], io: '1行目に文字列 S、2行目に単語が空白区切りで与えられます。', ask: '単語のうち、S の部分列(順序を保って拾える)になっているものの個数を出力してください。', h1: '各単語について2本指で判定する。', h2: 'Sを1回走査し、単語側のポインタが最後まで進めば部分列。', ref: 's=input()\nwords=input().split()\ndef sub(w):\n    i=0\n    for c in s:\n        if i<len(w) and w[i]==c:\n            i+=1\n    return i==len(w)\nprint(sum(1 for w in words if sub(w)))', tip: '単語が大量なら「文字ごとの待ち行列」に単語を吊るし、Sを1回だけ走査する一括判定に進化させられる。まずは2本指の確実な理解から。', ins: ['abcde\na bb acd ace\n', 'xyz\nx y z xyz zyx\n', 'aaa\naaaa aa\n', 'hello\nho el llo ol\n', 'a\na b\n', 'abc\nabc\n'] })

t({ lv: 682, concept: 'しゃくとり: k回書き換えで同じ文字の最長', title: 'k回変えて作る同じ文字の最長区間', tags: ['しゃくとり'], io: '1行目に書き換え回数 k、2行目に英大文字の文字列が与えられます。', ask: '高々 k 文字を任意の文字に書き換えるとき、同じ文字だけからなる連続区間の最大の長さを出力してください。', h1: '窓の中で「最頻文字以外」を書き換えると考える。', h2: '窓長 − 窓内の最頻文字数 が k 以下なら実現可能。窓を伸ばし、破れたら左を縮める。', ref: 'from collections import Counter\nk=int(input())\ns=input()\ncnt=Counter()\nl=0\nbest=0\nfor r,c in enumerate(s):\n    cnt[c]+=1\n    while r-l+1-max(cnt.values())>k:\n        cnt[s[l]]-=1\n        l+=1\n    if r-l+1>best:\n        best=r-l+1\nprint(best)', tip: '判定条件「窓長−最頻数≤k」が単調なのでしゃくとりが成立する。最頻数は厳密に減らさなくても答えが壊れない、という緩い更新も有名な小技。', ins: ['1\nABAB\n', '2\nAABABBA\n', '0\nAABB\n', '1\nA\n', '2\nABCDE\n', '3\nBBBBB\n'] })

t({ lv: 683, concept: '累積和: 等和3分割の切り方の数', title: '3等分する切り方は何通りか', tags: ['累積和'], io: '整数列が1行で空白区切りで与えられます(要素3個以上)。', ask: '列を3つの空でない連続ブロックに切って和を全て等しくする切り方(切る2箇所の位置の組)の数を出力してください。', h1: '合計が3の倍数でなければ0。', h2: '左から見て「接頭和が T/3 になった回数」を持ち、接頭和が 2T/3 の位置(最後の要素より前)でその回数を加算する。', ref: 'a=list(map(int,input().split()))\nn=len(a)\ntotal=sum(a)\nways=0\nif total%3==0:\n    t=total//3\n    firsts=0\n    pre=0\n    for j in range(n-1):\n        pre+=a[j]\n        if pre==2*t and j>=1:\n            ways+=firsts\n        if pre==t and j<=n-3:\n            firsts+=1\nprint(ways)', tip: '「左の候補数を持ち歩いて右の確定点で掛ける」1パス集計。判定(可否)から数え上げへは、フラグをカウンタに置き換えるだけで進化する。', ins: ['1 2 3 0 3\n', '0 0 0 0\n', '1 1 1\n', '3 3 6\n', '1 -1 1 -1 1 -1\n', '2 2 2 2 2 2\n'] })

t({ lv: 684, concept: 'ハッシュ: 3種が同数の最長区間', title: '0と1と2が同数の最長区間', tags: ['ハッシュ'], io: '0,1,2 だけからなる列が1行で空白区切りで与えられます。', ask: '0と1と2の個数が全て等しい連続区間の最大の長さを出力してください(存在しなければ0)。', h1: '個数の差だけが問題。', h2: '(0の数−1の数, 1の数−2の数) のペアが同じ2地点の間は3種が同数。初出位置を辞書に覚える。', ref: 'a=list(map(int,input().split()))\nfirst={(0,0):-1}\nc0=c1=c2=0\nbest=0\nfor i,x in enumerate(a):\n    if x==0:\n        c0+=1\n    elif x==1:\n        c1+=1\n    else:\n        c2+=1\n    key=(c0-c1,c1-c2)\n    if key in first:\n        if i-first[key]>best:\n            best=i-first[key]\n    else:\n        first[key]=i\nprint(best)', tip: '「同数」は差ベクトルの一致に翻訳できる。0/1の2種なら差1個、3種なら差2個…と、種類が増えても次元を増やすだけで同じ辞書勘定が通る。', ins: ['0 1 2 2\n', '0 1 2\n', '0 0 1 1 2 2\n', '0 0 0\n', '2 1 0 2 1 0\n', '1\n'] })

t({ lv: 685, concept: '文字列: 2つの回文に切れるか', title: '回文2つに分割できるか', tags: ['文字列'], io: '英小文字の文字列(2文字以上)が1行で与えられます。', ask: '文字列を空でない2つに切り、両方とも回文にできるなら yes、できなければ no を出力してください。', h1: '切る位置は n−1 通りしかない。', h2: '各位置で前半と後半をスライス反転比較する。', ref: 's=input()\nn=len(s)\nans="no"\nfor i in range(1,n):\n    if s[:i]==s[:i][::-1] and s[i:]==s[i:][::-1]:\n        ans="yes"\n        break\nprint(ans)', tip: '切断位置の全探索+O(n)判定で十分だが、大規模では前後からの回文接頭辞判定(Z配列やManacher)でO(n)に落とせる。', ins: ['abaab\n', 'ab\n', 'aa\n', 'abc\n', 'racecarnoon\n', 'aab\n'] })

t({ lv: 686, concept: 'DP: ちょうどk個の隣接禁止最大和', title: 'k個選ぶ隣接禁止の最大和', tags: ['DP'], io: '1行目に選ぶ個数 k、2行目に整数列(負もある)が与えられます(隣接せずにk個選べる長さ)。', ask: '隣り合う要素を同時に選ばずにちょうど k 個選ぶときの、合計の最大を出力してください。', h1: '「何個選んだか」の次元を足す。', h2: 'dp[i][j] を先頭i個からj個選ぶ最大とし、i番目を選ぶ(dp[i−2][j−1])か選ばない(dp[i−1][j])か。', ref: 'k=int(input())\na=list(map(int,input().split()))\nn=len(a)\nNEG=-10**18\ndp=[[NEG]*(k+1) for _ in range(n+1)]\nfor i in range(n+1):\n    dp[i][0]=0\nfor i in range(1,n+1):\n    for j in range(1,k+1):\n        dp[i][j]=dp[i-1][j]\n        base=dp[i-2][j-1] if i>=2 else (0 if j==1 else NEG)\n        if base>NEG:\n            c=base+a[i-1]\n            if c>dp[i][j]:\n                dp[i][j]=c\nprint(dp[n][k])', tip: '「最大和」だけなら貪欲もどきが通じるが「ちょうどk個」が付くとDPの独壇場。個数次元の初期化(0個は和0、他は不可能)が正しさの要。', ins: ['2\n1 2 3 4\n', '1\n-5 -1 -9\n', '2\n5 1 1 5\n', '3\n1 9 1 9 1 9\n', '1\n7\n', '2\n-1 -2 -3 -4\n'] })

t({ lv: 687, concept: '文字列: 並べ替えの最小隣接交換', title: 'アナグラムへの最小隣接スワップ', tags: ['文字列'], io: '1行目に文字列 s、2行目にその並べ替え(アナグラム) t が与えられます。', ask: '隣接する2文字の交換だけで s を t に変えるときの最小交換回数を出力してください。', h1: 't の各文字が s のどの位置から来るかを対応付ける。', h2: '同じ文字は左から順に対応させるのが最適。対応位置の列の転倒数が答え。', ref: 's=input()\nt=input()\nused=[False]*len(s)\npos=[]\nfor c in t:\n    for i,ch in enumerate(s):\n        if not used[i] and ch==c:\n            used[i]=True\n            pos.append(i)\n            break\ncnt=0\nfor i in range(len(pos)):\n    for j in range(i+1,len(pos)):\n        if pos[i]>pos[j]:\n            cnt+=1\nprint(cnt)', tip: '「隣接交換の最小回数=転倒数」に、同種文字の対応は交差させない(左から順)が最適という貪欲を重ねる。ソート距離の文字列版。', ins: ['ab\nba\n', 'abc\nabc\n', 'aabb\nbbaa\n', 'abab\nbaba\n', 'ba\nab\n', 'cba\nabc\n'] })

t({ lv: 688, concept: '文字列: 重ならず2回現れる最長', title: '重ならない繰り返しの最長', tags: ['文字列'], io: '英小文字の文字列が1行で与えられます。', ask: '同じ文字列が「重ならずに」2箇所以上に現れるものの最大の長さを出力してください(無ければ0)。', h1: '長さを固定して判定する。', h2: '長さ L の各部分文字列の開始位置を記録し、開始位置の差が L 以上のペアがあれば実現可能。', ref: 's=input()\nn=len(s)\nbest=0\nfor L in range(n//2,0,-1):\n    found=False\n    first={}\n    for i in range(n-L+1):\n        sub=s[i:i+L]\n        if sub in first:\n            if i-first[sub]>=L:\n                found=True\n                break\n        else:\n            first[sub]=i\n    if found:\n        best=L\n        break\nprint(best)', tip: '「最初の出現だけ覚える」と、後続との距離が最大になり重なり判定に最も有利。二分探索+ローリングハッシュでO(n log n)にも改良できる。', ins: ['aabaab\n', 'abcabc\n', 'aaaa\n', 'abcd\n', 'ababab\n', 'aa\n'] })

t({ lv: 689, concept: 'DP: 全部分配列の積の総和', title: '全ての連続区間の積の合計', tags: ['DP'], io: '整数列が1行で空白区切りで与えられます。', ask: '全ての連続部分配列について要素の積を求め、その総和を出力してください。', h1: '「iで終わる全区間の積の和」を s とすると、次は a[i+1]×(1+s)。', h2: '各位置でこの s を答えに足し込みながら更新する。', ref: 'a=list(map(int,input().split()))\ns=0\ntotal=0\nfor x in a:\n    s=x*(1+s)\n    total+=s\nprint(total)', tip: '「iで終わる区間」への分解は和の総和・積の総和・最小の総和すべてに通じる末尾固定の型。積は分配法則 x(1+s) が遷移を1行にする。', ins: ['1 2 3\n', '2 2\n', '-1 2\n', '5\n', '1 0 2\n', '2 -1 3\n'] })

t({ lv: 690, concept: 'しゃくとり: 奇数をk個含む区間の数', title: '奇数がちょうどk個の区間', tags: ['しゃくとり'], io: '1行目に k、2行目に正整数列が与えられます。', ask: '奇数がちょうど k 個含まれる連続部分配列の個数を出力してください。', h1: '奇数の位置だけが本質。', h2: '奇数の位置リストを作ると、k個の奇数の塊の左右に「偶数を何個付けるか」の掛け算で数えられる。', ref: 'k=int(input())\na=list(map(int,input().split()))\nodds=[-1]+[i for i,x in enumerate(a) if x%2==1]+[len(a)]\ncnt=0\nfor i in range(1,len(odds)-k):\n    j=i+k-1\n    if j>=len(odds)-1:\n        break\n    left=odds[i]-odds[i-1]\n    right=odds[j+1]-odds[j]\n    cnt+=left*right\nprint(cnt)', tip: '「ちょうどk個」は境界の自由度の積で数えるのがエレガント。番兵(−1とn)を置くと端の場合分けが消える、リスト処理の定番の仕込み。', ins: ['1\n1 1 2 1 1\n', '2\n2 2 2 1 2 2 1 2\n', '1\n2 4 6\n', '2\n1 1\n', '1\n1\n', '3\n1 2 1 2 1\n'] })

export const CATALOG = TASKS
