// 生成タスク 第58波：各レベル2問化フェーズ(13)。lv616〜640 に2問目を追加。
// グラフ応用帯(内周/マッチング/MST/フロー/DAG)。重複なし・決定的・採点一意。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 616, concept: 'グラフ: 最短閉路の長さ', title: '最も短い閉路(内周)', tags: ['グラフ', 'BFS'], io: '1行目に n m、続く m 行に無向辺が与えられます(自己ループ・多重辺なし)。', ask: 'グラフに含まれる最短の閉路の長さ(内周)を出力してください。閉路が無ければ -1。', h1: '各頂点からBFSする。', h2: '訪問済みの頂点へ「親以外から」たどり着いたら、dist[x]+dist[y]+1 が閉路長の候補。', ref: 'from collections import deque\nn,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\nINF=float("inf")\nbest=INF\nfor s in range(1,n+1):\n    dist=[-1]*(n+1)\n    par=[0]*(n+1)\n    dist[s]=0\n    q=deque([s])\n    while q:\n        x=q.popleft()\n        for y in g[x]:\n            if dist[y]<0:\n                dist[y]=dist[x]+1\n                par[y]=x\n                q.append(y)\n            elif par[x]!=y:\n                c=dist[x]+dist[y]+1\n                if c<best:\n                    best=c\nprint(best if best<INF else -1)', tip: '最短閉路上の頂点からBFSすれば正確な閉路長が拾える、が正しさの根拠。同レベルの交差辺なら奇閉路、隣レベルなら偶閉路になる。', ins: ['3 3\n1 2\n2 3\n1 3\n', '4 4\n1 2\n2 3\n3 4\n4 1\n', '4 3\n1 2\n2 3\n3 4\n', '5 6\n1 2\n2 3\n3 4\n4 5\n5 1\n2 5\n', '6 6\n1 2\n2 3\n3 4\n4 5\n5 6\n6 1\n', '5 5\n1 2\n2 3\n3 1\n3 4\n4 5\n'] })

t({ lv: 617, concept: '木: 完全二分木か判定', title: 'パーフェクトな二分木か', tags: ['木', 'BFS'], io: '1行目に頂点数 n (根は1、n≥2)、2行目に頂点2..nの親が与えられます。', ask: 'どの内部頂点も子をちょうど2つ持ち、全ての葉の深さが等しい(完全二分木である)なら yes、そうでなければ no を出力してください。', h1: '子の数が0か2以外の頂点があれば即アウト。', h2: '葉の深さを集合に集め、1種類だけかを確かめる。', ref: 'from collections import deque\nn=int(input())\npar=[0,0]+list(map(int,input().split()))\nch=[[] for _ in range(n+1)]\nfor v in range(2,n+1):\n    ch[par[v]].append(v)\ndepths=set()\nok=True\nq=deque([(1,1)])\nwhile q:\n    x,d=q.popleft()\n    if len(ch[x])==0:\n        depths.add(d)\n    elif len(ch[x])==2:\n        for c in ch[x]:\n            q.append((c,d+1))\n    else:\n        ok=False\n        break\nprint("yes" if ok and len(depths)==1 else "no")', tip: '完全二分木は頂点数が必ず 2^k−1。先に頂点数のビットパターン(n+1が2のべき)で足切りする高速な必要条件チェックもある。', ins: ['7\n1 1 2 2 3 3\n', '3\n1 1\n', '2\n1\n', '5\n1 1 2 2\n', '4\n1 1 1\n', '15\n1 1 2 2 3 3 4 4 5 5 6 6 7 7\n'] })

t({ lv: 618, concept: 'グラフ: 共通の友人がいるペア数', title: '共通の知り合いを持つ2人組', tags: ['グラフ'], io: '1行目に n m、続く m 行に無向辺(友人関係)が与えられます。', ask: '共通の友人が1人以上いる2人の組(順序なし、本人どうしが友人かは問わない)の個数を出力してください。', h1: '隣接集合をsetで持つ。', h2: '2つの集合の共通部分が空でないかは & 演算で分かる。', ref: 'n,m=map(int,input().split())\nadj=[set() for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    adj[u].add(v)\n    adj[v].add(u)\ncnt=0\nfor u in range(1,n+1):\n    for v in range(u+1,n+1):\n        if adj[u]&adj[v]:\n            cnt+=1\nprint(cnt)', tip: '共通隣接の個数まで数えて C(c,2) を足すと4頂点閉路の数になる。「共通の隣」はコミュニティ検出や推薦の基本特徴量。', ins: ['3 2\n1 2\n2 3\n', '3 3\n1 2\n2 3\n1 3\n', '4 3\n1 2\n1 3\n1 4\n', '2 1\n1 2\n', '4 0\n', '5 4\n1 2\n2 3\n3 4\n4 5\n'] })

t({ lv: 619, concept: 'マッチング: 貪欲マッチングの大きさ', title: '早い者勝ちのペア成立数', tags: ['マッチング', '貪欲'], io: '1行目に n m、続く m 行に希望ペア(無向辺)が申し込み順に与えられます。', ask: '申し込み順に「両者ともまだ誰とも組んでいなければ成立」させるとき、成立するペア数を出力してください。', h1: '各頂点の使用済みフラグを持つ。', h2: '辺を順に見て両端が未使用なら採用。', ref: 'n,m=map(int,input().split())\nused=[False]*(n+1)\ncnt=0\nfor _ in range(m):\n    u,v=map(int,input().split())\n    if not used[u] and not used[v]:\n        used[u]=True\n        used[v]=True\n        cnt+=1\nprint(cnt)', tip: '貪欲マッチングは最適の半分以上を必ず確保する(2近似)。順序で結果が変わる点が最大マッチングとの本質的な差で、比較すると増加道の意味が見える。', ins: ['4 3\n1 2\n1 3\n3 4\n', '4 3\n2 3\n1 2\n3 4\n', '2 1\n1 2\n', '6 4\n1 2\n3 4\n5 6\n1 3\n', '3 2\n1 2\n1 3\n', '5 4\n1 2\n2 3\n3 4\n4 5\n'] })

t({ lv: 620, concept: 'MST: 最小全域木の個数', title: '最小全域木は何通りあるか', tags: ['MST', '全探索'], io: '1行目に n m (m≤12)、続く m 行に連結な無向グラフの辺 u v w が与えられます。', ask: '総重みが最小の全域木が何通りあるかを出力してください。', h1: 'n−1本の辺の組合せを全て試す。', h2: '各組合せが全域木か(連結か)をUnion-Findで確かめ、最小重みのものを数える。', ref: 'from itertools import combinations\nn,m=map(int,input().split())\nedges=[tuple(map(int,input().split())) for _ in range(m)]\nbest=None\ncnt=0\nfor comb in combinations(range(m),n-1):\n    par=list(range(n+1))\n    def find(x):\n        while par[x]!=x:\n            par[x]=par[par[x]]\n            x=par[x]\n        return x\n    comps=n\n    w=0\n    for i in comb:\n        u,v,ww=edges[i]\n        ru,rv=find(u),find(v)\n        if ru!=rv:\n            par[ru]=rv\n            comps-=1\n        w+=ww\n    if comps==1:\n        if best is None or w<best:\n            best=w\n            cnt=1\n        elif w==best:\n            cnt+=1\nprint(cnt)', tip: '辺の重みが全て異なればMSTは一意。同じ重みの辺のグループごとの選び方の積として、行列木定理で大規模にも数えられる。', ins: ['3 3\n1 2 1\n2 3 1\n1 3 1\n', '3 3\n1 2 1\n2 3 1\n1 3 2\n', '4 4\n1 2 1\n2 3 1\n3 4 1\n4 1 1\n', '2 1\n1 2 5\n', '4 5\n1 2 1\n2 3 1\n3 4 1\n1 3 1\n2 4 2\n', '3 2\n1 2 1\n2 3 4\n'] })

t({ lv: 621, concept: 'ダイクストラ: 周期便を待つ最短時間', title: '定期便を乗り継ぐ最短時刻', tags: ['ダイクストラ'], io: '1行目に n m s t、続く m 行に路線「u v p c」(両方向。時刻がpの倍数のときだけ出発でき、c だけかかる)が与えられます。時刻0に s を出発します。', ask: 't に到着できる最も早い時刻を出力してください。到達できなければ -1。', h1: '辺のコストが「今の時刻」に依存する。', h2: '出発可能時刻は「現在時刻以上で最小のpの倍数」。切り上げは (d+p−1)//p*p。単調なのでダイクストラがそのまま使える。', ref: 'import heapq\nn,m,s,t=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v,p,c=map(int,input().split())\n    g[u].append((v,p,c))\n    g[v].append((u,p,c))\nINF=float("inf")\ndist=[INF]*(n+1)\ndist[s]=0\nh=[(0,s)]\nwhile h:\n    d,x=heapq.heappop(h)\n    if d>dist[x]:\n        continue\n    for y,p,c in g[x]:\n        nd=(d+p-1)//p*p+c\n        if nd<dist[y]:\n            dist[y]=nd\n            heapq.heappush(h,(nd,y))\nprint(dist[t] if dist[t]<INF else -1)', tip: '「早く着いて損はない」(出発時刻の単調性)が成り立つ限り、時刻依存コストでもダイクストラは正しい。時刻表検索エンジンの心臓部。', ins: ['3 2 1 3\n1 2 3 2\n2 3 5 1\n', '2 1 1 2\n1 2 1 7\n', '2 0 1 2\n', '3 3 1 3\n1 2 2 2\n2 3 2 2\n1 3 10 1\n', '4 3 1 4\n1 2 4 1\n2 3 4 1\n3 4 4 1\n', '2 2 1 2\n1 2 5 4\n1 2 3 5\n'] })

t({ lv: 622, concept: 'グラフ: 推移簡約の辺数', title: '省略できない矢印の数', tags: ['グラフ'], io: '1行目に n m、続く m 行に閉路のない有向辺が与えられます。', ask: '「他の経路で言い換えられる辺」を全て取り除いたとき(推移簡約)に残る辺の本数を出力してください。', h1: 'まず到達可能性(推移閉包)を作る。', h2: '辺 (u,v) は、中継点 w で u→w かつ w→v が成り立つものがあれば省略できる。', ref: 'n,m=map(int,input().split())\ng=[[False]*(n+1) for _ in range(n+1)]\nedges=[]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    edges.append((u,v))\n    g[u][v]=True\nadjr=[row[:] for row in g]\nfor k in range(1,n+1):\n    for i in range(1,n+1):\n        if adjr[i][k]:\n            for j in range(1,n+1):\n                if adjr[k][j]:\n                    adjr[i][j]=True\ncnt=0\nfor u,v in edges:\n    if not any(adjr[u][w] and adjr[w][v] for w in range(1,n+1) if w!=u and w!=v):\n        cnt+=1\nprint(cnt)', tip: '推移簡約はハッセ図(半順序の最小表現)そのもの。依存関係図やクラス階層図を「見やすく間引く」処理は正にこれ。DAGなら一意に定まる。', ins: ['3 3\n1 2\n2 3\n1 3\n', '3 2\n1 2\n2 3\n', '4 5\n1 2\n2 3\n3 4\n1 3\n1 4\n', '2 1\n1 2\n', '4 4\n1 2\n1 3\n2 4\n3 4\n', '5 6\n1 2\n2 3\n1 3\n3 4\n4 5\n3 5\n'] })

t({ lv: 623, concept: '木: 1辺を0にして直径最小', title: '1本を高速化して直径を縮める', tags: ['木'], io: '1行目に頂点数 n (n≥2)、続く n−1 行に木の辺 u v w が与えられます。', ask: 'どれか1本の辺の重みを0にできるとき、木の直径(最遠頂点対の距離)の最小値を出力してください。', h1: '0にする辺を全部試す。', h2: '各ケースで全頂点から探索して直径を計算し、最小を取る。', ref: 'n=int(input())\nE=[tuple(map(int,input().split())) for _ in range(n-1)]\ndef diam(zero):\n    g=[[] for _ in range(n+1)]\n    for i,(u,v,w) in enumerate(E):\n        ww=0 if i==zero else w\n        g[u].append((v,ww))\n        g[v].append((u,ww))\n    best=0\n    for s in range(1,n+1):\n        dist=[-1]*(n+1)\n        dist[s]=0\n        st=[s]\n        while st:\n            x=st.pop()\n            for y,w in g[x]:\n                if dist[y]<0:\n                    dist[y]=dist[x]+w\n                    st.append(y)\n        mx=max(dist[1:n+1])\n        if mx>best:\n            best=mx\n    return best\nprint(min(diam(i) for i in range(n-1)))', tip: '直径を縮めたいなら直径パス上の辺を狙うのが直感だが、複数の直径があると単純には決まらない。全試しで確かめてから枝刈りを考えるのが安全。', ins: ['3\n1 2 5\n2 3 5\n', '2\n1 2 9\n', '4\n1 2 1\n2 3 10\n3 4 1\n', '4\n1 2 3\n1 3 3\n1 4 3\n', '5\n1 2 2\n2 3 2\n3 4 2\n4 5 2\n', '3\n1 2 1\n2 3 9\n'] })

t({ lv: 624, concept: 'グラフ: 1辺追加後の最大成分', title: '橋を1本架けたときの最大の島', tags: ['グラフ'], io: '1行目に n m、続く m 行に無向辺が与えられます。', ask: 'どこにでも辺を1本追加できるとき、最大の連結成分の頂点数を出力してください。', h1: '別々の成分を繋ぐのが常に得。', h2: '成分サイズの上位2つの和(成分が1つならその大きさ)。', ref: 'n,m=map(int,input().split())\npar=list(range(n+1))\ndef find(x):\n    while par[x]!=x:\n        par[x]=par[par[x]]\n        x=par[x]\n    return x\nsize=[1]*(n+1)\nfor _ in range(m):\n    u,v=map(int,input().split())\n    ru,rv=find(u),find(v)\n    if ru!=rv:\n        par[ru]=rv\n        size[rv]+=size[ru]\nsizes=sorted((size[v] for v in range(1,n+1) if find(v)==v),reverse=True)\nprint(sizes[0]+sizes[1] if len(sizes)>=2 else sizes[0])', tip: 'Union-Findの根にサイズを載せる「サイズ付き素集合」。上位2成分の合体が最適という貪欲は、成分の集計値さえあれば一行で済む。', ins: ['5 3\n1 2\n2 3\n4 5\n', '4 0\n', '3 3\n1 2\n2 3\n1 3\n', '6 4\n1 2\n3 4\n5 6\n1 3\n', '2 1\n1 2\n', '7 3\n1 2\n3 4\n5 6\n'] })

t({ lv: 625, concept: 'フロー: 最小カットを構成する辺数', title: '最小カットで切れる辺の本数', tags: ['フロー'], io: '1行目に n m s t、続く m 行に有向辺 u v c(容量)が与えられます。', ask: '最大流を流し切った後、残余グラフで s から到達できる集合を S とします。S から外へ出る元の辺(最小カットを構成する辺)の本数を出力してください。', h1: 'まずEdmonds-Karpで最大流を求める。', h2: '残余容量が正の辺だけで s からBFSし、S→V∖S の元辺を数える。', ref: 'from collections import deque,defaultdict\nn,m,s,t=map(int,input().split())\ncap=defaultdict(int)\nadj=defaultdict(list)\norig=[]\ndef add(u,v,c):\n    if v not in adj[u]:\n        adj[u].append(v)\n    if u not in adj[v]:\n        adj[v].append(u)\n    cap[(u,v)]+=c\nfor _ in range(m):\n    u,v,c=map(int,input().split())\n    orig.append((u,v))\n    add(u,v,c)\nwhile True:\n    par={s:None}\n    q=deque([s])\n    while q:\n        x=q.popleft()\n        if x==t:\n            break\n        for y in adj[x]:\n            if y not in par and cap[(x,y)]>0:\n                par[y]=x\n                q.append(y)\n    if t not in par:\n        break\n    b=float("inf")\n    x=t\n    while par[x] is not None:\n        p=par[x]\n        if cap[(p,x)]<b:\n            b=cap[(p,x)]\n        x=p\n    x=t\n    while par[x] is not None:\n        p=par[x]\n        cap[(p,x)]-=b\n        cap[(x,p)]+=b\n        x=p\nseen={s}\nq=deque([s])\nwhile q:\n    x=q.popleft()\n    for y in adj[x]:\n        if y not in seen and cap[(x,y)]>0:\n            seen.add(y)\n            q.append(y)\nprint(sum(1 for u,v in orig if u in seen and v not in seen))', tip: '最大流の値だけでなく「どこが切れるか」まで読むのが実戦。残余グラフの到達集合が最小カットの証明書(双対解)になっている。', ins: ['4 5 1 4\n1 2 2\n1 3 2\n2 4 2\n3 4 2\n2 3 1\n', '2 1 1 2\n1 2 5\n', '3 2 1 3\n1 2 3\n2 3 1\n', '4 4 1 4\n1 2 1\n2 4 3\n1 3 3\n3 4 1\n', '3 3 1 3\n1 2 1\n1 3 1\n2 3 1\n', '5 5 1 5\n1 2 9\n2 3 1\n3 4 9\n4 5 9\n2 5 1\n'] })

t({ lv: 626, concept: 'グラフ: 最大反鎖', title: '互いに比べられない最大の集合', tags: ['グラフ', 'bitDP'], io: '1行目に n m (n≤15)、続く m 行に閉路のない有向辺(u が v より先)が与えられます。', ask: 'どの2要素の間にも到達関係(順序)が無い頂点集合(反鎖)の最大サイズを出力してください。', h1: 'まず推移閉包で「比べられるか」を全ペアについて求める。', h2: '部分集合を全列挙し、比較可能なペアを含まない最大の集合を探す。', ref: 'n,m=map(int,input().split())\nreach=[[False]*n for _ in range(n)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    reach[u-1][v-1]=True\nfor k in range(n):\n    for i in range(n):\n        if reach[i][k]:\n            for j in range(n):\n                if reach[k][j]:\n                    reach[i][j]=True\nbest=0\nfor mask in range(1<<n):\n    vs=[i for i in range(n) if mask>>i&1]\n    ok=True\n    for a in range(len(vs)):\n        for b in range(a+1,len(vs)):\n            if reach[vs[a]][vs[b]] or reach[vs[b]][vs[a]]:\n                ok=False\n                break\n        if not ok:\n            break\n    if ok and len(vs)>best:\n        best=len(vs)\nprint(best)', tip: 'ディルワースの定理により最大反鎖のサイズは最小チェイン分割数と等しい。大規模には2部マッチングで解けるが、まず定義通りの全探索で感覚を掴む。', ins: ['4 4\n1 2\n1 3\n2 4\n3 4\n', '3 2\n1 2\n2 3\n', '4 0\n', '5 4\n1 2\n1 3\n1 4\n1 5\n', '6 6\n1 2\n2 3\n4 5\n5 6\n1 6\n4 3\n', '2 1\n1 2\n'] })

t({ lv: 627, concept: 'グラフ: 最大のk-core', title: '崩れない集団の強さ(縮退度)', tags: ['グラフ'], io: '1行目に n m、続く m 行に無向辺が与えられます。', ask: '「次数が最小の頂点を取り除く」操作を全頂点が無くなるまで繰り返します。取り除く瞬間の次数の最大値(グラフの縮退度、最大のkコアのk)を出力してください。同じ次数の頂点が複数あれば番号の小さい方を取り除きます。', h1: '隣接を集合で持ち、削除のたびに更新する。', h2: '毎回 (次数, 番号) が最小の頂点を選ぶ。', ref: 'n,m=map(int,input().split())\nadj=[set() for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    adj[u].add(v)\n    adj[v].add(u)\nalive=set(range(1,n+1))\nbest=0\nwhile alive:\n    v=min(alive,key=lambda x:(len(adj[x]),x))\n    d=len(adj[v])\n    if d>best:\n        best=d\n    for y in adj[v]:\n        adj[y].discard(v)\n    adj[v]=set()\n    alive.discard(v)\nprint(best)', tip: 'SNSの「密なコミュニティ」抽出で使うkコア分解。最小次数から剥がす操作は貪欲だが縮退度を正確に与えることが証明できる。', ins: ['4 6\n1 2\n1 3\n1 4\n2 3\n2 4\n3 4\n', '4 3\n1 2\n2 3\n3 4\n', '3 0\n', '5 6\n1 2\n2 3\n3 1\n3 4\n4 5\n5 3\n', '6 7\n1 2\n2 3\n3 1\n1 4\n4 5\n5 6\n6 4\n', '2 1\n1 2\n'] })

t({ lv: 628, concept: 'ダイクストラ: 路線乗り換えコスト', title: '乗り換え料金込みの最安経路', tags: ['ダイクストラ'], io: '1行目に n m f s t (fは乗り換え料金)、続く m 行に路線区間「u v c l」(コストc、路線番号l、両方向)が与えられます。', ask: '別の路線番号の区間に乗り換えるたびに f かかる(最初の乗車は無料)ときの、s から t への最小費用を出力してください。到達できなければ -1。', h1: '「今どの路線に乗っているか」を状態に足す。', h2: '(頂点, 路線) を状態にダイクストラ。同じ路線なら c、違う路線なら c+f。', ref: 'import heapq\nn,m,f,s,t=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v,c,l=map(int,input().split())\n    g[u].append((v,c,l))\n    g[v].append((u,c,l))\ndist={}\nh=[(0,s,0)]\nbest=float("inf")\nwhile h:\n    d,x,l=heapq.heappop(h)\n    if (x,l) in dist and dist[(x,l)]<d:\n        continue\n    dist[(x,l)]=d\n    if x==t and d<best:\n        best=d\n    for y,c,l2 in g[x]:\n        nd=d+c+(f if l!=0 and l2!=l else 0)\n        if (y,l2) not in dist or nd<dist[(y,l2)]:\n            dist[(y,l2)]=nd\n            heapq.heappush(h,(nd,y,l2))\nprint(best if best<float("inf") else -1)', tip: '路線図の最安検索は「駅×路線」の積グラフの最短路。バスと電車、色つき辺、燃料タンクなど“今の状態”を持つ移動は全部この型に落ちる。', ins: ['3 2 5 1 3\n1 2 1 1\n2 3 1 1\n', '3 2 5 1 3\n1 2 1 1\n2 3 1 2\n', '4 4 3 1 4\n1 2 1 1\n2 4 1 2\n1 3 1 2\n3 4 1 2\n', '2 1 10 1 2\n1 2 4 7\n', '2 0 1 1 2\n', '4 3 2 1 4\n1 2 1 1\n2 3 1 2\n3 4 1 1\n'] })

t({ lv: 629, concept: 'シミュレーション: 総当たり戦の日程', title: '総当たり戦の第rラウンドの組合せ', tags: ['シミュレーション'], io: 'チーム数 n(偶数)とラウンド番号 r が空白区切りで1行で与えられます (1≤r≤n−1)。', ask: 'サークル法で日程を組みます: 1..n−1 を左に r−1 回巡回シフトした列 a を作り、a の先頭とチーム n、a の i 番目と後ろから i 番目(i≥2)を対戦させます。第 r ラウンドの全対戦を、各行「小さい番号 大きい番号」で番号順に出力してください。', h1: '列の回転はスライスで作れる。', h2: '先頭は固定チーム n と、残りは前後から挟むように組む。', ref: 'n,r=map(int,input().split())\narr=list(range(1,n))\nk=(r-1)%(n-1)\narr=arr[k:]+arr[:k]\npairs=[(min(arr[0],n),max(arr[0],n))]\nfor i in range(1,(n-1)//2+1):\n    x,y=arr[i],arr[n-1-i]\n    pairs.append((min(x,y),max(x,y)))\npairs.sort()\nfor a,b in pairs:\n    print(a,b)', tip: '1チームを固定して残りを回すサークル法は、n−1ラウンドで全ペアがちょうど1回対戦することが保証される。リーグ戦日程の実務でも現役の構成法。', ins: ['4 1\n', '4 2\n', '4 3\n', '6 1\n', '6 4\n', '2 1\n'] })

t({ lv: 630, concept: 'グラフ: 距離ごとの頂点数', title: '距離別に頂点を数える', tags: ['グラフ', 'BFS'], io: '1行目に n m s、続く m 行に無向辺が与えられます。', ask: 's からの最短距離が 0,1,2,… の頂点数を、到達できる最大距離まで空白区切りで出力してください。', h1: 'BFSで距離を求める。', h2: 'Counterで距離ごとに集計する。', ref: 'from collections import deque,Counter\nn,m,s=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\ndist=[-1]*(n+1)\ndist[s]=0\nq=deque([s])\nwhile q:\n    x=q.popleft()\n    for y in g[x]:\n        if dist[y]<0:\n            dist[y]=dist[x]+1\n            q.append(y)\nc=Counter(d for d in dist[1:n+1] if d>=0)\nprint(*[c[i] for i in range(max(c)+1)])', tip: 'BFSの「層」の大きさの列は、感染シミュレーションの日毎の新規数やSNSの何次のつながりの人数そのもの。層の膨らみ方でグラフの形が見える。', ins: ['5 4 1\n1 2\n1 3\n2 4\n3 5\n', '3 2 2\n1 2\n2 3\n', '4 2 1\n1 2\n3 4\n', '1 0 1\n', '6 5 1\n1 2\n2 3\n3 4\n4 5\n5 6\n', '4 4 1\n1 2\n1 3\n2 4\n3 4\n'] })

t({ lv: 631, concept: 'グラフ: 経路の重みの幅を最小化', title: '使う辺の最大と最小の差を最小に', tags: ['グラフ', 'ダイクストラ'], io: '1行目に n m s t、続く m 行に無向辺 u v w が与えられます。', ask: 's から t への経路のうち「使う辺の最大重み − 最小重み」が最小になるときの値を出力してください。到達できなければ -1。', h1: '最小辺の重みを固定してみる。', h2: '重み L 以上の辺だけで「最大辺を最小化する経路」を求めると、幅は 最大−L 以下。全ての L を試して最小を取る。', ref: 'import heapq\nn,m,s,t=map(int,input().split())\nedges=[tuple(map(int,input().split())) for _ in range(m)]\nINF=float("inf")\nbest=INF\nfor L in sorted(set(w for u,v,w in edges)):\n    g=[[] for _ in range(n+1)]\n    for u,v,w in edges:\n        if w>=L:\n            g[u].append((v,w))\n            g[v].append((u,w))\n    mx=[INF]*(n+1)\n    mx[s]=0\n    h=[(0,s)]\n    while h:\n        d,x=heapq.heappop(h)\n        if d>mx[x]:\n            continue\n        for y,w in g[x]:\n            nd=max(d,w)\n            if nd<mx[y]:\n                mx[y]=nd\n                heapq.heappush(h,(nd,y))\n    if mx[t]<INF and mx[t]-L<best:\n        best=mx[t]-L\nprint(best if best<INF else -1)', tip: '2変数の最適化は「片方を全通り固定して、もう片方を単独最適化」する二重ループに割るのが定石。下限を全列挙しミニマックス経路を重ねる合わせ技。', ins: ['3 3 1 3\n1 2 5\n2 3 7\n1 3 100\n', '2 1 1 2\n1 2 9\n', '4 4 1 4\n1 2 1\n2 4 10\n1 3 4\n3 4 6\n', '2 0 1 2\n', '4 3 1 4\n1 2 3\n2 3 5\n3 4 4\n', '5 5 1 5\n1 2 2\n2 5 2\n1 3 1\n3 4 9\n4 5 1\n'] })

t({ lv: 632, concept: 'シミュレーション: トーナメントの優勝者', title: '勝ち上がり戦の優勝者', tags: ['シミュレーション'], io: '2のべき乗人の選手の強さ(相異なる)が並び順に1行で与えられます。', ask: '隣どうしで対戦し、強さが大きい方が勝ち上がるトーナメントの優勝者が、最初の並びで何番目(1始まり)かを出力してください。', h1: '各ラウンドで隣接ペアの勝者を残す。', h2: '選手はインデックスで持ち回ると、最後に元の位置が分かる。', ref: 'a=list(map(int,input().split()))\nplayers=list(range(len(a)))\nwhile len(players)>1:\n    nxt=[]\n    for i in range(0,len(players),2):\n        p,q=players[i],players[i+1]\n        nxt.append(p if a[p]>a[q] else q)\n    players=nxt\nprint(players[0]+1)', tip: 'この設定では優勝者は常に最強だが、「値」でなく「位置」を持ち回る書き方は準優勝(最強と同じ山の2番手)などの分析に直結する。', ins: ['3 1 4 2\n', '5 9\n', '1 2 4 3 8 7 6 5\n', '2 1\n', '1 8 2 7\n', '9 3 5 7\n'] })

t({ lv: 633, concept: 'MST: 全ての最小全域木に共通の辺数', title: '必ず使われる辺は何本か', tags: ['MST'], io: '1行目に n m、続く m 行に連結な無向グラフの辺 u v w が与えられます。', ask: 'どの最小全域木にも必ず含まれる辺の本数を出力してください。', h1: 'その辺を禁止してMSTを作り直してみる。', h2: '禁止すると総重みが増える(または木が作れない)辺こそ「必須」。', ref: 'n,m=map(int,input().split())\nedges=[tuple(map(int,input().split())) for _ in range(m)]\ndef mst(skip):\n    par=list(range(n+1))\n    def find(x):\n        while par[x]!=x:\n            par[x]=par[par[x]]\n            x=par[x]\n        return x\n    total=0\n    comps=n\n    for u,v,w in sorted((e for i,e in enumerate(edges) if i!=skip),key=lambda e:e[2]):\n        ru,rv=find(u),find(v)\n        if ru!=rv:\n            par[ru]=rv\n            comps-=1\n            total+=w\n    return total if comps==1 else None\nbase=mst(-1)\ncnt=0\nfor i in range(m):\n    r=mst(i)\n    if r is None or r>base:\n        cnt+=1\nprint(cnt)', tip: '「解に必ず入る/絶対入らない/どちらもあり得る」の3分類は感度分析の基本。辺を1本禁止して再計算する素朴法が最初の一歩になる。', ins: ['3 3\n1 2 1\n2 3 1\n1 3 1\n', '3 3\n1 2 1\n2 3 2\n1 3 3\n', '2 1\n1 2 5\n', '4 5\n1 2 1\n2 3 1\n3 4 1\n1 3 1\n2 4 2\n', '4 4\n1 2 1\n2 3 2\n3 4 3\n4 1 4\n', '3 2\n1 2 1\n2 3 1\n'] })

t({ lv: 634, concept: 'ダイクストラ: 同距離なら頂点数最小', title: '最短距離、その中で最少の頂点数', tags: ['ダイクストラ'], io: '1行目に n m s t、続く m 行に無向辺 u v w が与えられます。', ask: 's から t への最短距離と、その距離を達成する経路の中で最小の頂点数を空白区切りで出力してください。到達できなければ -1。', h1: '距離のタプル (距離, 頂点数) を辞書式に比較する。', h2: 'ダイクストラの距離をタプルに置き換えるだけで、第2基準の最適化が同時にできる。', ref: 'import heapq\nn,m,s,t=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v,w=map(int,input().split())\n    g[u].append((v,w))\n    g[v].append((u,w))\nINF=(float("inf"),float("inf"))\ndist=[INF]*(n+1)\ndist[s]=(0,1)\nh=[(0,1,s)]\nwhile h:\n    d,c,x=heapq.heappop(h)\n    if (d,c)>dist[x]:\n        continue\n    for y,w in g[x]:\n        nd=(d+w,c+1)\n        if nd<dist[y]:\n            dist[y]=nd\n            heapq.heappush(h,(nd[0],nd[1],y))\nif dist[t][0]==float("inf"):\n    print(-1)\nelse:\n    print(dist[t][0],dist[t][1])', tip: 'タプルの辞書式比較は「第1目標を最優先、同点なら第2目標」を1つの比較で表す。コスト+乗換回数、距離+料金など多基準最短路の最短の書き方。', ins: ['4 4 1 4\n1 2 1\n2 4 1\n1 4 2\n1 3 5\n', '2 1 1 2\n1 2 3\n', '3 3 1 3\n1 2 1\n2 3 1\n1 3 2\n', '2 0 1 2\n', '5 5 1 5\n1 2 1\n2 3 1\n3 5 1\n1 4 1\n4 5 2\n', '3 2 1 3\n1 2 2\n2 3 2\n'] })

t({ lv: 635, concept: 'グラフ: 一方通行化で強連結にできるか', title: '全ての道を一方通行にできるか', tags: ['グラフ'], io: '1行目に n m、続く m 行に無向辺が与えられます。', ask: '全ての辺に向きを付けて、どの頂点からどの頂点へも行けるように(強連結に)できるなら yes、できなければ no を出力してください。', h1: 'ロビンズの定理: 可能 ⇔ 連結かつ橋が無い。', h2: '各辺を1本ずつ抜いて連結性を確かめれば橋が見つかる。', ref: 'from collections import deque\nn,m=map(int,input().split())\nedges=[tuple(map(int,input().split())) for _ in range(m)]\ndef conn(skip):\n    g=[[] for _ in range(n+1)]\n    for i,(u,v) in enumerate(edges):\n        if i!=skip:\n            g[u].append(v)\n            g[v].append(u)\n    seen=[False]*(n+1)\n    seen[1]=True\n    q=deque([1])\n    c=1\n    while q:\n        x=q.popleft()\n        for y in g[x]:\n            if not seen[y]:\n                seen[y]=True\n                c+=1\n                q.append(y)\n    return c==n\nok=conn(-1) and all(conn(i) for i in range(m))\nprint("yes" if ok else "no")', tip: '一方通行の道路網が破綻しない条件が「橋なし」一点に集約されるロビンズの定理(1939)。DFS木の後退辺で実際の向き付けも構成できる。', ins: ['3 3\n1 2\n2 3\n1 3\n', '3 2\n1 2\n2 3\n', '4 4\n1 2\n2 3\n3 4\n4 1\n', '4 3\n1 2\n3 4\n2 3\n', '5 6\n1 2\n2 3\n3 1\n3 4\n4 5\n5 3\n', '2 1\n1 2\n'] })

t({ lv: 636, concept: '木: 鏡映対称の判定', title: '左右をひっくり返しても同じ木か', tags: ['木', '再帰'], io: '1行目に頂点数 n (根は1、n≥2)、2行目に頂点2..nの親が与えられます。各頂点の子は番号の小さい順に並んでいるとみなします。', ask: 'この順序付き木が左右鏡映しても同じ形なら yes、そうでなければ no を出力してください。', h1: '形をかっこ列に符号化すると比較できる。', h2: '普通の符号化と、子を逆順にたどる符号化が一致すれば鏡映対称。', ref: 'import sys\nsys.setrecursionlimit(100000)\nn=int(input())\npar=[0,0]+list(map(int,input().split()))\nch=[[] for _ in range(n+1)]\nfor v in range(2,n+1):\n    ch[par[v]].append(v)\ndef enc(v):\n    return "("+"".join(enc(c) for c in ch[v])+")"\ndef menc(v):\n    return "("+"".join(menc(c) for c in reversed(ch[v]))+")"\nprint("yes" if enc(1)==menc(1) else "no")', tip: '木をかっこ列に潰す符号化は同型判定の基本技(AHU法の原型)。「逆順にたどる関数」を別に書くだけで鏡映が扱えるのが再帰の柔らかさ。', ins: ['3\n1 1\n', '7\n1 1 2 2 3 3\n', '4\n1 1 2\n', '2\n1\n', '5\n1 1 2 3\n', '6\n1 1 2 2 3\n'] })

t({ lv: 637, concept: 'グラフ: 各頂点の離心数', title: '全頂点の離心数を並べる', tags: ['グラフ', 'BFS'], io: '1行目に n m、続く m 行に連結な無向グラフの辺が与えられます(辺の長さは全て1)。', ask: '各頂点の離心数(最も遠い頂点までの距離)を頂点1から順に空白区切りで出力してください。', h1: '各頂点からBFSする。', h2: '距離の最大がその頂点の離心数。', ref: 'from collections import deque\nn,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\nout=[]\nfor s in range(1,n+1):\n    dist=[-1]*(n+1)\n    dist[s]=0\n    q=deque([s])\n    while q:\n        x=q.popleft()\n        for y in g[x]:\n            if dist[y]<0:\n                dist[y]=dist[x]+1\n                q.append(y)\n    out.append(max(dist[1:n+1]))\nprint(*out)', tip: '離心数の最小が半径、最大が直径、最小を実現する頂点が中心。1つの表に半径・直径・中心・周辺が全部入っている。', ins: ['4 3\n1 2\n2 3\n3 4\n', '3 3\n1 2\n2 3\n1 3\n', '5 4\n1 2\n1 3\n1 4\n1 5\n', '2 1\n1 2\n', '6 5\n1 2\n2 3\n3 4\n4 5\n5 6\n', '4 4\n1 2\n2 3\n3 4\n4 1\n'] })

t({ lv: 638, concept: 'BFS: 色が交互の最短路', title: '赤と青を交互に通る最短路', tags: ['BFS'], io: '1行目に n m s t、続く m 行に色付きの無向辺「u v c」(cはrかb)が与えられます。', ask: '連続して同じ色の辺を通れない(交互に使う。最初の辺は自由)ときの、s から t への最小辺数を出力してください。到達できなければ -1。', h1: '「今いる頂点」だけでは足りない。', h2: '(頂点, 直前の色) を状態にBFS。', ref: 'from collections import deque\nn,m,s,t=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    parts=input().split()\n    u,v,c=int(parts[0]),int(parts[1]),parts[2]\n    g[u].append((v,c))\n    g[v].append((u,c))\ndist={(s,""):0}\nq=deque([(s,"")])\nans=-1\nwhile q:\n    x,lc=q.popleft()\n    if x==t:\n        ans=dist[(x,lc)]\n        break\n    for y,c in g[x]:\n        if c!=lc and (y,c) not in dist:\n            dist[(y,c)]=dist[(x,lc)]+1\n            q.append((y,c))\nprint(ans)', tip: '「同じ頂点でも直前の色が違えば別の状態」。到達判定は状態のどれか1つで着けばよいので、pop時にゴール判定するのが安全な書き方。', ins: ['3 2 1 3\n1 2 r\n2 3 b\n', '3 2 1 3\n1 2 r\n2 3 r\n', '2 1 1 2\n1 2 b\n', '4 4 1 4\n1 2 r\n2 4 r\n1 3 b\n3 4 r\n', '5 5 1 5\n1 2 r\n2 3 b\n3 4 r\n4 5 b\n1 5 r\n', '3 3 1 3\n1 2 r\n2 3 r\n1 3 b\n'] })

t({ lv: 639, concept: 'グラフ: 正則グラフの判定', title: 'みんな同じ次数か', tags: ['グラフ'], io: '1行目に n m、続く m 行に無向辺が与えられます。', ask: '全頂点の次数が等しい(正則グラフ)ならその次数を、そうでなければ -1 を出力してください。', h1: '次数配列を作る。', h2: 'setにして要素が1種類か見る。', ref: 'n,m=map(int,input().split())\ndeg=[0]*(n+1)\nfor _ in range(m):\n    u,v=map(int,input().split())\n    deg[u]+=1\n    deg[v]+=1\nd=set(deg[1:n+1])\nprint(deg[1] if len(d)==1 else -1)', tip: 'k正則グラフは辺数が nk/2 で決まるので、nとkが両方奇数だと存在しない。「一様さ」の判定はsetの大きさ1つで書くのが簡潔。', ins: ['3 3\n1 2\n2 3\n1 3\n', '4 4\n1 2\n2 3\n3 4\n4 1\n', '3 2\n1 2\n2 3\n', '4 0\n', '4 6\n1 2\n1 3\n1 4\n2 3\n2 4\n3 4\n', '2 1\n1 2\n'] })

t({ lv: 640, concept: 'グラフ: 距離行列の整合性検証', title: 'この表は距離になっているか', tags: ['グラフ', '数学'], io: '1行目に n、続く n 行に n×n の整数の表が与えられます。', ask: 'この表が距離の公理を満たす(対角が0、対称、他は正、どの3点でも三角不等式が成り立つ)なら yes、そうでなければ no を出力してください。', h1: '対角・対称・正値を先に確かめる。', h2: '三角不等式は3重ループで d[i][j] が d[i][k]+d[k][j] を超えないか全て見る。', ref: 'n=int(input())\nd=[list(map(int,input().split())) for _ in range(n)]\nok=True\nfor i in range(n):\n    if d[i][i]!=0:\n        ok=False\n    for j in range(n):\n        if d[i][j]!=d[j][i] or (i!=j and d[i][j]<=0):\n            ok=False\nfor i in range(n):\n    for j in range(n):\n        for k in range(n):\n            if d[i][j]>d[i][k]+d[k][j]:\n                ok=False\nprint("yes" if ok else "no")', tip: '三角不等式の全数検査はワーシャルフロイドを1周して行列が変化しないことの確認と同じ。「不動点なら整合」という見方はあらゆる緩和法に通じる。', ins: ['3\n0 1 2\n1 0 1\n2 1 0\n', '3\n0 5 1\n5 0 1\n1 1 0\n', '2\n0 3\n3 0\n', '2\n0 3\n4 0\n', '3\n0 1 1\n1 0 1\n1 1 1\n', '3\n0 0 1\n0 0 1\n1 1 0\n'] })

export const CATALOG = TASKS
