// 生成タスク 第55波：各レベル2問化フェーズ(10)。lv491〜499, lv501〜540 に2問目を追加。
// 線形代数/bit/組合せ/二分探索/ヒープ/ハッシュ/バックトラック/DP帯。重複なし・決定的・採点一意。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 491, concept: 'シミュレーション: 1次元ライツアウト', title: '一列のライツアウトの最小手数', tags: ['シミュレーション'], io: '0/1の文字列が1行で与えられます(1が点灯)。ボタン i を押すと i とその両隣の明かりが反転します。', ask: '全部消灯にするための最小のボタン押下回数を出力してください。不可能なら -1。', h1: '先頭のボタンを押すか押さないかを決めると、残りは連鎖的に決まる。', h2: '左隣がまだ点いていたら押すしかない(掃き出し)。最後に全消灯かを確認。', ref: 's=input().strip()\nn=len(s)\nbest=-1\nfor first in range(2):\n    b=[int(c) for c in s]\n    total=0\n    for i in range(n):\n        press=first if i==0 else b[i-1]\n        if press:\n            total+=1\n            for j in (i-1,i,i+1):\n                if 0<=j<n:\n                    b[j]^=1\n    if all(v==0 for v in b):\n        if best<0 or total<best:\n            best=total\nprint(best)', tip: '「最初の1手を全通り試すと残りが強制される」chasing法。2次元のライツアウトも1行目を全探索すれば同じ构造で解ける。', ins: ['111\n', '0000\n', '1\n', '10\n', '101\n', '11011\n'] })

t({ lv: 492, concept: '線形代数: 2×2逆行列 mod p', title: '2×2行列の逆行列を法pで', tags: ['数学'], io: '1行目に素数 p、2行目に行列の成分 a b c d が与えられます。', ask: '行列 [[a,b],[c,d]] の mod p での逆行列の成分を「x11 x12 x21 x22」の順で出力してください(各成分は 0 以上 p 未満)。逆行列が無ければ -1。', h1: '行列式 ad−bc を mod p で計算する。', h2: '逆行列は 1/det × [[d,−b],[−c,a]]。1/det はフェルマーの小定理 det^(p−2) で。', ref: 'p=int(input())\na,b,c,d=map(int,input().split())\ndet=(a*d-b*c)%p\nif det==0:\n    print(-1)\nelse:\n    inv=pow(det,p-2,p)\n    print(d*inv%p,(-b)*inv%p,(-c)*inv%p,a*inv%p)', tip: '2×2の逆行列は「対角を入れ替え、反対角の符号を反転、行列式で割る」。modの世界では割り算がべき乗(逆元)に化ける。', ins: ['5\n1 2 3 4\n', '7\n2 0 0 2\n', '5\n1 2 2 4\n', '11\n1 1 0 1\n', '13\n3 5 1 2\n', '3\n1 0 0 1\n'] })

t({ lv: 493, concept: 'bit演算: 偶奇ビットの交換', title: '隣り合うビットのペアを入れ替える', tags: ['bit演算'], io: '非負整数 n が1行で与えられます。', ask: '2進表現の偶数番目のビット(0,2,4,…)と奇数番目のビット(1,3,5,…)をペアごとに入れ替えた値を出力してください。', h1: '偶数位置だけのマスク 0101…、奇数位置だけのマスク 1010… を作る。', h2: '偶数側を左へ1シフト、奇数側を右へ1シフトして OR。', ref: 'n=int(input())\nb=max(n.bit_length()+1,2)\nif b%2:\n    b+=1\neven=0\nfor i in range(0,b,2):\n    even|=1<<i\nodd=even<<1\nprint(((n&even)<<1)|((n&odd)>>1))', tip: 'マスク0x55555555と0xAAAAAAAAの入れ替えは、ビット並列アルゴリズム(SWAR)の入り口。popcountの分割統治もこの発想で書かれている。', ins: ['1\n', '2\n', '10\n', '23\n', '0\n', '6\n'] })

t({ lv: 494, concept: '組合せ: 辞書順k番目の順列', title: '辞書順でk番目の順列を作る', tags: ['数学'], io: 'n k が空白区切りで1行で与えられます (kはn!以下)。', ask: '1..n の順列を辞書順に並べたときの k 番目(1始まり)を空白区切りで出力してください。', h1: '先頭の数字1つにつき (n−1)! 個の順列がある。', h2: 'k−1 を階乗で割った商が「残り候補の何番目を取るか」。階乗進法で上の桁から決める。', ref: 'import math\nn,k=map(int,input().split())\nk-=1\nitems=list(range(1,n+1))\nout=[]\nfor i in range(n,0,-1):\n    f=math.factorial(i-1)\n    out.append(items.pop(k//f))\n    k%=f\nprint(*out)', tip: '「順列→順位」(ランク)の逆演算(アンランク)。階乗進法はk番目の組合せ・k番目のカタラン構造など、数え上げから実体を復元する技の共通土台。', ins: ['3 3\n', '3 1\n', '4 24\n', '1 1\n', '4 10\n', '5 60\n'] })

t({ lv: 495, concept: 'シミュレーション: 完全シャッフルの復元回数', title: '元に戻るまでの完全シャッフル回数', tags: ['シミュレーション'], io: '偶数のカード枚数 n が1行で与えられます。', ask: 'カードの山を半分に分け、上半分と下半分を1枚ずつ交互に(元の一番上が一番上のままになるように)混ぜる完全シャッフルを繰り返します。並びが元に戻るまでの回数を出力してください。', h1: '並びを配列で持ち、シャッフルを素直に実装する。', h2: '元の並びと一致したら停止。', ref: 'n=int(input())\norig=list(range(n))\ncur=orig[:]\ncnt=0\nwhile True:\n    half=n//2\n    nxt=[]\n    for i in range(half):\n        nxt.append(cur[i])\n        nxt.append(cur[half+i])\n    cur=nxt\n    cnt+=1\n    if cur==orig:\n        break\nprint(cnt)', tip: '52枚ではわずか8回で元に戻る。回数は「2 の位数 mod n−1」に一致し、シャッフルという操作が数論の位数と繋がる。', ins: ['2\n', '4\n', '8\n', '6\n', '52\n', '10\n'] })

t({ lv: 496, concept: 'マッチング: 安定性の検証', title: 'このマッチングは安定か', tags: ['マッチング'], io: '1行目に人数 n。続く n 行に男性1..nの希望順(女性番号の列)、続く n 行に女性1..nの希望順(男性番号の列)、最後の行に男性 i の相手の女性番号が n 個与えられます。', ask: '「今の相手より互いを好むペア(ブロッキングペア)」が存在しなければ yes、存在すれば no を出力してください。', h1: '全ての男女ペア (m,w) を調べる。', h2: 'm が今の相手より w を好み、かつ w も今の相手より m を好むなら不安定。順位表を辞書にしておくと速い。', ref: 'n=int(input())\nmp=[list(map(int,input().split())) for _ in range(n)]\nwp=[list(map(int,input().split())) for _ in range(n)]\nmatch=list(map(int,input().split()))\nhusband=[0]*(n+1)\nfor m in range(n):\n    husband[match[m]]=m+1\nmrank=[{w:r for r,w in enumerate(mp[m])} for m in range(n)]\nwrank=[{mm:r for r,mm in enumerate(wp[w])} for w in range(n)]\nok=True\nfor m in range(1,n+1):\n    for w in range(1,n+1):\n        if match[m-1]==w:\n            continue\n        if mrank[m-1][w]<mrank[m-1][match[m-1]] and wrank[w-1][m]<wrank[w-1][husband[w]]:\n            ok=False\nprint("yes" if ok else "no")', tip: '解を作るより検証する方が易しい、の典型。安定マッチングの検証はO(n²)、構成はGale-Shapley。「検証容易・構成困難」の非対称はNP理論の核心でもある。', ins: ['2\n1 2\n1 2\n1 2\n1 2\n1 2\n', '2\n1 2\n1 2\n1 2\n1 2\n2 1\n', '1\n1\n1\n1\n', '3\n1 2 3\n2 1 3\n3 1 2\n1 2 3\n2 1 3\n3 1 2\n1 2 3\n', '2\n2 1\n1 2\n1 2\n1 2\n2 1\n', '3\n1 2 3\n1 2 3\n1 2 3\n3 2 1\n3 2 1\n3 2 1\n1 2 3\n'] })

t({ lv: 497, concept: '文字列: ちょうど1回の編集で一致', title: '1回の編集で変換できるか', tags: ['文字列'], io: '1行目と2行目に文字列 s, t が与えられます(空行もありうる)。', ask: 's にちょうど1回の編集(1文字の挿入・削除・置換)を行って t にできるなら yes、できなければ no を出力してください(等しい場合は no)。', h1: '長さの差が2以上なら不可能。', h2: '同じ長さなら「違う文字がちょうど1箇所」。長さ差1なら最初の不一致を飛ばして残りが一致するか。', ref: 's=input()\nt=input()\nif len(s)>len(t):\n    s,t=t,s\nans="no"\nif len(t)-len(s)==1:\n    i=0\n    while i<len(s) and s[i]==t[i]:\n        i+=1\n    if s[i:]==t[i+1:]:\n        ans="yes"\nelif len(s)==len(t):\n    diff=sum(1 for a,b in zip(s,t) if a!=b)\n    if diff==1:\n        ans="yes"\nprint(ans)', tip: '編集距離のDP表を作らなくても「距離が1以下か」だけなら線形時間・定数領域で判定できる。必要な答えの粗さに合わせてアルゴリズムを軽くする発想。', ins: ['abc\nabd\n', 'abc\nabc\n', 'abc\nabcd\n', 'abc\naXbc\n', 'abc\nxyz\n', 'a\n\n'] })

t({ lv: 498, concept: '単調スタック: 車列グループの数', title: 'ゴールまでに合流する車列の数', tags: ['スタック', 'ソート'], io: '1行目にゴール位置 D、2行目に各車の現在位置、3行目に各車の速度が与えられます(位置は相異なり、全てDより手前)。', ask: '車は追い越せず、追いついたら前の車と同じ速度の車列になります。ゴールに到着する時点の車列の数を出力してください。', h1: 'ゴールに近い車から順に、単独で走った場合の到着時刻を計算する。', h2: '前の車列の到着時刻以下なら合流する(吸収)。時刻が真に大きいときだけ新しい車列。分数のまま比較すると誤差がない。', ref: 'from fractions import Fraction\nd=int(input())\npos=list(map(int,input().split()))\nspd=list(map(int,input().split()))\ncars=sorted(zip(pos,spd),reverse=True)\nfleets=0\nlead=None\nfor p,s in cars:\n    t=Fraction(d-p,s)\n    if lead is None or t>lead:\n        fleets+=1\n        lead=t\nprint(fleets)', tip: '位置降順に「到着時刻の単調減少列」だけが生き残る、と読み替えると単調スタックそのもの。Fractionを使えば浮動小数の比較誤差と無縁になる。', ins: ['12\n10 8 0 5 3\n2 4 1 1 3\n', '10\n3\n3\n', '100\n0 2 4\n4 2 1\n', '10\n6 8\n3 2\n', '10\n0 4 2\n2 1 3\n', '5\n1 2 3 4\n1 1 1 1\n'] })

t({ lv: 499, concept: 'DP: 枠だけ全1の最大正方形', title: '境界が全て1の最大正方形', tags: ['DP'], io: '1行目に H W、続く H 行に0/1が空白区切りで与えられます。', ask: '4辺(枠)が全て1でできた正方形(内部は問わない)の最大の辺の長さを出力してください。1が無ければ 0。', h1: '各マスで「左に連続する1の数」「上に連続する1の数」を前計算する。', h2: '右下の角を固定し、大きい辺から「上の辺の左伸び」と「左の辺の上伸び」が足りるか確かめる。', ref: 'h,w=map(int,input().split())\ng=[list(map(int,input().split())) for _ in range(h)]\nleft=[[0]*w for _ in range(h)]\nup=[[0]*w for _ in range(h)]\nfor i in range(h):\n    for j in range(w):\n        if g[i][j]:\n            left[i][j]=(left[i][j-1] if j else 0)+1\n            up[i][j]=(up[i-1][j] if i else 0)+1\nbest=0\nfor i in range(h):\n    for j in range(w):\n        k=min(left[i][j],up[i][j])\n        while k>best:\n            if left[i-k+1][j]>=k and up[i][j-k+1]>=k:\n                best=k\n                break\n            k-=1\nprint(best)', tip: '「全部1の正方形」はdpの最小値で解けるが、「枠だけ」は連続1の長さの前計算で角どうしを突き合わせる。何を前計算すれば角の条件が O(1) で見えるかが設計の焦点。', ins: ['3 3\n1 1 1\n1 0 1\n1 1 1\n', '2 2\n1 1\n1 1\n', '1 1\n0\n', '1 3\n1 1 1\n', '3 4\n1 1 1 0\n1 0 1 0\n1 1 1 0\n', '2 2\n1 0\n0 1\n'] })

t({ lv: 501, concept: '二分探索: 回転配列で目的値', title: '回転したソート配列から探す', tags: ['二分探索'], io: '1行目に目的値、2行目に「昇順の列を途中で回転した」相異なる整数の列が与えられます。', ask: '目的値の位置(0始まり)を出力してください。無ければ -1。', h1: '中央で割ると、必ず片側はソートされたままになっている。', h2: 'ソートされている側に目的値が入るかで探索範囲を絞る。', ref: 't=int(input())\na=list(map(int,input().split()))\nlo,hi=0,len(a)-1\nans=-1\nwhile lo<=hi:\n    mid=(lo+hi)//2\n    if a[mid]==t:\n        ans=mid\n        break\n    if a[lo]<=a[mid]:\n        if a[lo]<=t<a[mid]:\n            hi=mid-1\n        else:\n            lo=mid+1\n    else:\n        if a[mid]<t<=a[hi]:\n            lo=mid+1\n        else:\n            hi=mid-1\nprint(ans)', tip: '「壊れた単調性でも、半分は必ず無事」という観察で二分探索が生き残る。どちらが無事かの判定は端と中央の比較だけでできる。', ins: ['0\n4 5 6 7 0 1 2\n', '3\n4 5 6 7 0 1 2\n', '5\n5 1 3\n', '1\n3 1\n', '7\n1 2 3 4 5 6 7\n', '2\n2\n'] })

t({ lv: 502, concept: '二分探索: 伐採高さの最大化', title: '必要量を確保できる最高の刃の高さ', tags: ['二分探索'], io: '1行目に必要な木材量 M、2行目に木の高さの列が与えられます(合計で確保可能)。', ask: '高さ h より上を全ての木から切り取るとき、合計 M 以上を確保できる最大の整数 h を出力してください。', h1: 'h を上げるほど取れる量は減る(単調)。', h2: '答えの h を二分探索し、判定は Σmax(0, 高さ−h)。', ref: 'm=int(input())\na=list(map(int,input().split()))\nlo,hi=0,max(a)\nbest=0\nwhile lo<=hi:\n    mid=(lo+hi)//2\n    got=sum(v-mid for v in a if v>mid)\n    if got>=m:\n        best=mid\n        lo=mid+1\n    else:\n        hi=mid-1\nprint(best)', tip: '「できるだけ高く、でも足りるように」は答えの二分探索の合図。判定関数が単調ならどんな複雑な量でも同じ骨格で解ける。', ins: ['7\n20 15 10 17\n', '10\n4 42 40 26 46\n', '1\n1\n', '3\n5 5\n', '20\n10 10\n', '5\n6\n'] })

t({ lv: 503, concept: '二分探索: 袋の最大個数の最小化', title: 'k回の分割で袋の最大を最小に', tags: ['二分探索'], io: '1行目に操作回数 k、2行目に各袋の玉の個数が与えられます。', ask: '1回の操作で1つの袋を2つに分けられます。k 回以内の操作後の「最大の袋の個数」の最小値を出力してください。', h1: '「最大を x 以下にできるか」で二分探索。', h2: '袋 v を x 以下に割るには ceil(v/x)−1 回、つまり (v−1)//x 回必要。', ref: 'k=int(input())\na=list(map(int,input().split()))\nlo,hi=1,max(a)\nwhile lo<hi:\n    mid=(lo+hi)//2\n    ops=sum((v-1)//mid for v in a)\n    if ops<=k:\n        hi=mid\n    else:\n        lo=mid+1\nprint(lo)', tip: '最小化したい量そのものを二分探索の変数にし、コスト計算を判定関数に落とす。(v−1)//x が「x以下に割るための最小分割数」を一発で与える。', ins: ['1\n9\n', '2\n2 4 8 2\n', '0\n7 17\n', '4\n2 4 8 2\n', '3\n7\n', '1\n1 1\n'] })

t({ lv: 504, concept: '二分探索: 生産ノルマの最小時間', title: 'T個作り終える最短時刻', tags: ['二分探索'], io: '1行目に必要個数 T、2行目に各機械の「1個作るのにかかる秒数」が与えられます。', ask: '全機械が同時に動き続けるとき、合計 T 個以上が完成する最短の時刻(秒、整数)を出力してください。', h1: '時刻 t までに機械 s は t//s 個作る。', h2: '完成数は時刻について単調なので二分探索。', ref: 't=int(input())\nsp=list(map(int,input().split()))\nlo,hi=1,min(sp)*t\nwhile lo<hi:\n    mid=(lo+hi)//2\n    if sum(mid//s for s in sp)>=t:\n        hi=mid\n    else:\n        lo=mid+1\nprint(lo)', tip: '「時間を固定すれば生産数が計算できる」なら時間を二分探索。上限は「最速の機械が1台で全部作る時間」で十分、と粗く張るのがコツ。', ins: ['5\n2 3\n', '1\n10\n', '4\n1\n', '10\n1 2 3\n', '3\n5 5 5\n', '7\n2 2\n'] })

t({ lv: 505, concept: '二分探索: k番目に近いペアの距離', title: 'k番目に小さいペア間距離', tags: ['二分探索', '二点法'], io: '1行目に k、2行目に整数列が与えられます(kはペア総数以下)。', ask: '全てのペア (i<j) の距離 |a[i]−a[j]| のうち、小さい方から k 番目を出力してください。', h1: 'ソートすると「距離 d 以下のペア数」がしゃくとりで数えられる。', h2: '距離を二分探索し、ペア数が k 以上になる最小の距離が答え。', ref: 'k=int(input())\na=sorted(map(int,input().split()))\nn=len(a)\nlo,hi=0,a[-1]-a[0]\ndef cnt(d):\n    c=0\n    j=0\n    for i in range(n):\n        while a[i]-a[j]>d:\n            j+=1\n        c+=i-j\n    return c\nwhile lo<hi:\n    mid=(lo+hi)//2\n    if cnt(mid)>=k:\n        hi=mid\n    else:\n        lo=mid+1\nprint(lo)', tip: 'ペアを全列挙せず「値で二分探索+個数勘定」でk番目を当てる。答えの候補が値域にあるとき、この型はk番目系のほとんどに通用する。', ins: ['1\n1 3 1\n', '3\n1 3 1\n', '2\n1 6 1\n', '1\n5 5\n', '6\n1 2 3 4\n', '4\n2 4 6 8\n'] })

t({ lv: 506, concept: '二分探索: 山型配列から目的値', title: '山型配列で目的値を探す', tags: ['二分探索'], io: '1行目に目的値、2行目に山型(増加してから減少する)の相異なる整数の列が与えられます。', ask: '目的値の最小の位置(0始まり)を出力してください。無ければ -1。', h1: 'まず山頂の位置を二分探索で見つける。', h2: '上り側は昇順、下り側は降順として、それぞれ二分探索する。上り側を先に調べれば最小位置になる。', ref: 'import bisect\nt=int(input())\na=list(map(int,input().split()))\nlo,hi=0,len(a)-1\nwhile lo<hi:\n    mid=(lo+hi)//2\n    if a[mid]<a[mid+1]:\n        lo=mid+1\n    else:\n        hi=mid\npeak=lo\ni=bisect.bisect_left(a,t,0,peak+1)\nif i<=peak and a[i]==t:\n    print(i)\nelse:\n    lo2,hi2=peak,len(a)-1\n    ans=-1\n    while lo2<=hi2:\n        mid=(lo2+hi2)//2\n        if a[mid]==t:\n            ans=mid\n            break\n        if a[mid]>t:\n            lo2=mid+1\n        else:\n            hi2=mid-1\n    print(ans)', tip: '単調でない配列も「単調な区間に分解」すれば二分探索が使える。山頂探し(隣との比較で登る方向へ)は答えの二分探索の変種。', ins: ['3\n1 2 3 4 5 3 1\n', '3\n0 1 2 4 2 1\n', '5\n1 5 2\n', '1\n0 5 1\n', '2\n1 2 3 2\n', '7\n3 7 4\n'] })

t({ lv: 507, concept: '数学: 完全べき乗の判定', title: 'aのb乗の形で書けるか', tags: ['数学'], io: '2以上の整数 n が1行で与えられます。', ask: 'n が a^b (a≥2, b≥2) の形で書けるなら yes、書けなければ no を出力してください。', h1: '指数 b は 2 から log2(n) までしかない。', h2: '各 b について b 乗根の近くの整数を試す(浮動小数の丸めに注意して±1も確認)。', ref: 'n=int(input())\nans="no"\nb=2\nwhile 2**b<=n:\n    a=round(n**(1/b))\n    for c in (a-1,a,a+1):\n        if c>=2 and c**b==n:\n            ans="yes"\n    b+=1\nprint(ans)', tip: '浮動小数の冪根は僅かにずれるので「候補の周辺を整数演算で検算」する。この“floatで当たりを付けてintで確定”は数値×厳密のハイブリッドの定石。', ins: ['8\n', '16\n', '12\n', '9\n', '2\n', '100\n'] })

t({ lv: 508, concept: '二分探索: ソート行列の負数の個数', title: '両方向ソート行列の負の数を数える', tags: ['二分探索'], io: '1行目に H W、続く H 行に「各行が左から右へ非増加、各列も上から下へ非増加」の整数が与えられます。', ask: '行列に含まれる負の数の個数を出力してください。', h1: '下の行ほど負の数は多い(単調性)。', h2: '各行の「最初の負の位置」は行が進むと左にしか動かない。階段状に1回なぞればO(H+W)。', ref: 'h,w=map(int,input().split())\ng=[list(map(int,input().split())) for _ in range(h)]\ncnt=0\nc=w\nfor r in range(h):\n    while c>0 and g[r][c-1]<0:\n        c-=1\n    cnt+=w-c\nprint(cnt)', tip: '2方向にソートされた行列では、境界線が階段状になり左下から右上へ一度なぞるだけで数えられる。行ごとの二分探索 O(H log W) より速い。', ins: ['4 4\n4 3 2 -1\n3 2 1 -1\n1 1 -1 -2\n-1 -1 -2 -3\n', '2 2\n3 2\n1 0\n', '1 3\n5 -1 -2\n', '3 1\n1\n0\n-5\n', '2 3\n1 0 -1\n0 -2 -3\n', '1 1\n-7\n'] })

t({ lv: 509, concept: 'ヒープ: 石をぶつけ合う最後の重さ', title: '最後に残る石の重さ', tags: ['ヒープ'], io: '石の重さの列が1行で空白区切りで与えられます。', ask: '毎回最も重い2つをぶつけ、同じなら両方消え、違えば差の石が残ります。最後に残る石の重さ(残らなければ0)を出力してください。', h1: '「最大を2つ取り出す」を繰り返す。', h2: 'heapqは最小ヒープなので符号を反転して入れる。', ref: 'import heapq\na=[-x for x in map(int,input().split())]\nheapq.heapify(a)\nwhile len(a)>1:\n    x=-heapq.heappop(a)\n    y=-heapq.heappop(a)\n    if x!=y:\n        heapq.heappush(a,-(x-y))\nprint(-a[0] if a else 0)', tip: '最大ヒープが欲しいときは値を負にして入れるのがPython流。シミュレーション系は「毎回の最大(最小)取り出し」が見えたらヒープ一択。', ins: ['2 7 4 1 8 1\n', '1\n', '3 3\n', '5 5 5\n', '10 4 2 10\n', '9 3 2 10\n'] })

t({ lv: 510, concept: '二点法: 平方のソート済み配列', title: '各要素を2乗して昇順に並べる', tags: ['二点法'], io: '昇順にソートされた整数列(負を含みうる)が1行で与えられます。', ask: '各要素を2乗した値を昇順に並べて空白区切りで出力してください。', h1: '2乗すると大きいのは「両端のどちらか」。', h2: '左右のポインタから絶対値の大きい方を、答えの後ろから詰める。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nres=[0]*n\ni,j=0,n-1\nfor k in range(n-1,-1,-1):\n    if abs(a[i])>abs(a[j]):\n        res[k]=a[i]*a[i]\n        i+=1\n    else:\n        res[k]=a[j]*a[j]\n        j-=1\nprint(*res)', tip: 'ソート済み入力なら再ソートO(n log n)は負け。単調性が壊れる変換でも「壊れ方が両端から」なら二点法で線形に組み直せる。', ins: ['-4 -1 0 3 10\n', '-7 -3 2 3 11\n', '1 2 3\n', '-5 -3 -1\n', '0\n', '-2 2\n'] })

t({ lv: 511, concept: '数え上げ: 九九表の値の種類数', title: 'n×n乗算表に現れる値の種類', tags: ['数学'], io: '正整数 n が1行で与えられます。', ask: 'i×j (1≤i,j≤n) として現れる値の種類数を出力してください。', h1: '積を集合に入れて数える。', h2: '内包表記とsetで一行で書ける。', ref: 'n=int(input())\nprint(len({i*j for i in range(1,n+1) for j in range(1,n+1)}))', tip: 'n²個中の相異なる値はぐっと少ない(乗算表問題)。この密度がどう漸近するかはエルデシュが研究した現役の数論問題。', ins: ['3\n', '1\n', '9\n', '2\n', '5\n', '10\n'] })

t({ lv: 512, concept: '二分探索: 等長ロープの最大長', title: 'k本切り出せる最大のロープ長', tags: ['二分探索'], io: '1行目に必要本数 k、2行目に手持ちのロープの長さの列が与えられます。', ask: '同じ整数長 L (L≥1) のロープを合計 k 本以上切り出せる最大の L を出力してください。1でも無理なら 0。', h1: '長さ L を固定すればロープ v から v//L 本取れる。', h2: '取れる本数は L について単調減少なので二分探索。', ref: 'k=int(input())\na=list(map(int,input().split()))\nlo,hi=1,max(a)\nbest=0\nwhile lo<=hi:\n    mid=(lo+hi)//2\n    if sum(v//mid for v in a)>=k:\n        best=mid\n        lo=mid+1\n    else:\n        hi=mid-1\nprint(best)', tip: '切り出し・分配・積載…「量を固定→可否を判定」に直せる最適化は全部この型。判定が整数割り算1発なのがロープ切りの気持ちよさ。', ins: ['11\n802 743 457 539\n', '4\n5 5\n', '3\n1 1\n', '1\n7\n', '5\n10\n', '2\n3 5\n'] })

t({ lv: 513, concept: '配列: 重複と欠落の特定', title: 'ダブった数と消えた数', tags: ['配列'], io: '1..n のはずが1つの数が重複し1つの数が欠けている長さ n の列が与えられます。', ask: '重複している数と欠けている数を空白区切りで出力してください。', h1: '出現回数を数える配列を作る。', h2: '回数2の値と回数0の値を探す。', ref: 'a=list(map(int,input().split()))\nn=len(a)\ncnt=[0]*(n+1)\nfor v in a:\n    cnt[v]+=1\nprint(cnt.index(2),cnt.index(0,1))', tip: '和と2乗和の差から連立方程式で求める算術解、XORで求めるビット解もある。カウント配列が最も素直で、list.indexの第2引数(開始位置)も地味に便利。', ins: ['1 2 2 4\n', '1 1\n', '3 2 3 4 6 5\n', '2 2\n', '1 5 3 2 2\n', '1 2 3 4 5 3\n'] })

t({ lv: 514, concept: 'ソート: パンケーキソートの反転回数', title: 'パンケーキソートの操作回数', tags: ['ソート', 'シミュレーション'], io: '相異なる整数の列が1行で与えられます。', ask: '「先頭からk枚をまとめて反転」だけで並べ替えるパンケーキソートを、次の規則で実行したときの反転回数を出力してください: 大きい方から順に、その値が正位置になければ(先頭にないときはまず先頭へ反転してから)正位置へ反転する。', h1: '最大値の位置を探し、先頭へ→定位置へ、の2回の反転。', h2: '既に定位置なら0回、既に先頭なら1回で済む。', ref: 'a=list(map(int,input().split()))\nn=len(a)\ncnt=0\nfor size in range(n,1,-1):\n    m=a.index(max(a[:size]))\n    if m==size-1:\n        continue\n    if m>0:\n        a[:m+1]=a[:m+1][::-1]\n        cnt+=1\n    a[:size]=a[:size][::-1]\n    cnt+=1\nprint(cnt)', tip: 'スライスへの代入 a[:k]=a[:k][::-1] で先頭反転が一行。最小反転回数の決定は実はNP困難で、ビル・ゲイツが上界の論文を書いたことでも有名。', ins: ['3 2 4 1\n', '1 2 3\n', '3 1 2\n', '2 1\n', '1\n', '4 3 2 1\n'] })

t({ lv: 515, concept: '分割統治: パスカル三角形の奇数の個数', title: '三角形の上n行にある奇数の個数', tags: ['数学', 'bit演算'], io: '正整数 n が1行で与えられます。', ask: 'パスカルの三角形の第0行から第n−1行までに現れる奇数の個数を出力してください。', h1: '第 i 行の奇数の個数には綺麗な法則がある。', h2: 'C(i,k) が奇数になる k は「kのビットがiのビットに含まれる」場合(リュカの定理)。つまり第 i 行に 2^(iの立っているビット数) 個。', ref: 'n=int(input())\nprint(sum(2**bin(i).count("1") for i in range(n)))', tip: 'パスカル三角形を偶奇で塗るとシェルピンスキーのギャスケット(フラクタル)が現れる。行数を2倍にすると個数が3倍になる自己相似が式にも見える。', ins: ['1\n', '2\n', '4\n', '8\n', '5\n', '16\n'] })

t({ lv: 516, concept: 'ヒープ: 資本を増やすk案件の選択', title: 'k件選んで資本を最大化', tags: ['ヒープ', '貪欲'], io: '1行目に選べる件数 k と初期資本 W、2行目に各案件の必要資本、3行目に各案件の利益が与えられます。', ask: '資本が必要額以上の案件だけ着手でき、完了すると利益が資本に加わります。最大 k 件選んで得られる最終資本の最大値を出力してください。', h1: '今の資本で着手できる案件のうち利益最大を選ぶのが最善。', h2: '必要資本でソートしておき、資本が増えるたびに解禁された案件を最大ヒープへ入れる。', ref: 'import heapq\nk,w=map(int,input().split())\ncap=list(map(int,input().split()))\npro=list(map(int,input().split()))\nprojects=sorted(zip(cap,pro))\nh=[]\ni=0\nn=len(projects)\nfor _ in range(k):\n    while i<n and projects[i][0]<=w:\n        heapq.heappush(h,-projects[i][1])\n        i+=1\n    if not h:\n        break\n    w+=-heapq.heappop(h)\nprint(w)', tip: '「解禁待ちリスト(ソート)+選択候補(ヒープ)」の2段構えは、資本・時刻・レベルなど“閾値で選択肢が開く”貪欲の共通骨格。', ins: ['2 0\n0 1 1\n1 2 3\n', '3 0\n0 1 2\n1 2 3\n', '1 2\n3 4\n5 6\n', '2 1\n1 1 2\n2 2 3\n', '1 0\n0\n10\n', '2 5\n1 2 3\n1 1 1\n'] })

t({ lv: 517, concept: 'DP: 全部分配列の和の総和', title: '全ての連続部分配列の和の合計', tags: ['数学'], io: '整数列が1行で空白区切りで与えられます。', ask: '全ての連続部分配列について要素の和を求め、その総和を出力してください。', h1: '部分配列を列挙すると O(n²) 個ある。まず各要素が何回数えられるかを考える。', h2: 'a[i] は「左端の選び方 (i+1) × 右端の選び方 (n−i)」回現れる。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nprint(sum(a[i]*(i+1)*(n-i) for i in range(n)))', tip: '「全区間について集計」は区間を回すのでなく各要素の寄与回数を掛ける(寄与テクニック)。min/max の寄与版が単調スタック問題に発展する。', ins: ['1 2 3\n', '5\n', '1 1 1 1\n', '2 3\n', '-1 2\n', '4 0 4\n'] })

t({ lv: 518, concept: '配列: 波形への並べ替え', title: '低い・高いが交互になる並べ替え', tags: ['配列'], io: '整数列が1行で空白区切りで与えられます。', ask: '先頭から「1番目≤2番目≥3番目≤4番目…」となるよう、左から順に走査して条件に反する隣接ペアをその場で交換した結果を空白区切りで出力してください。', h1: '偶数番目の位置では次以下、奇数番目の位置では次以上になっていればよい。', h2: '条件を破る隣接ペアをswapするだけで、前方の条件は壊れない(局所修正の貪欲)。', ref: 'a=list(map(int,input().split()))\nfor i in range(len(a)-1):\n    if (i%2==0 and a[i]>a[i+1]) or (i%2==1 and a[i]<a[i+1]):\n        a[i],a[i+1]=a[i+1],a[i]\nprint(*a)', tip: 'ソートして互い違いに取る方法もあるが、1回の走査+局所swapで済むのは「swapしても直前の不等式は保たれる」ことの帰納法による。証明できる貪欲は強い。', ins: ['3 5 2 1 6 4\n', '1 2 3 4\n', '5\n', '2 1\n', '1 1 1\n', '9 8 7 6\n'] })

t({ lv: 519, concept: 'ハッシュ: 出現回数の一意性判定', title: '出現回数がすべて異なるか', tags: ['ハッシュ'], io: '値の列が1行で空白区切りで与えられます。', ask: 'それぞれの値の出現回数がすべて相異なるなら yes、同じ回数の値が2つ以上あれば no を出力してください。', h1: 'まず値ごとの回数を数える。', h2: '回数のリストが重複を持つかは set と長さ比較で分かる。', ref: 'from collections import Counter\nc=Counter(input().split())\nv=list(c.values())\nprint("yes" if len(v)==len(set(v)) else "no")', tip: 'Counterの結果をさらに集計する「2段集計」。len(v)とlen(set(v))の比較は重複検出の最短イディオムで、あらゆる一意性チェックに流用できる。', ins: ['1 2 2 1 1 3\n', '1 2\n', '5\n', '1 1 2 2\n', '-3 0 1 -3 1 1 1 -3 10 0\n', '7 7 7\n'] })

t({ lv: 520, concept: 'ハッシュ: 和がkで割り切れるペア数', title: '和がkの倍数になるペアの数', tags: ['ハッシュ', '数学'], io: '1行目に k、2行目に整数列が与えられます。', ask: 'i<j で a[i]+a[j] が k で割り切れるペアの個数を出力してください。', h1: '各値は k で割った余りだけが重要。', h2: '余り r と k−r の個数の積を足す。r が 0 や k/2 のときは同じグループ内の組合せ C(c,2)。', ref: 'from collections import Counter\nk=int(input())\na=list(map(int,input().split()))\nc=Counter(v%k for v in a)\nans=c[0]*(c[0]-1)//2\nfor r in range(1,k//2+1):\n    if r!=k-r:\n        ans+=c[r]*c[k-r]\n    else:\n        ans+=c[r]*(c[r]-1)//2\nprint(ans)', tip: '「和の条件」は余りの世界ではペアの相性表になる。自分自身と対になる余り(0とk/2)だけ組合せ計算になる場合分けが定番の罠。', ins: ['3\n1 2 3 4 5 6\n', '2\n1 3 5\n', '5\n5 10\n', '4\n2 2 2 2\n', '7\n1 2 3\n', '3\n3 6 9 1\n'] })

t({ lv: 521, concept: 'ヒープ: 2次元の雨水', title: '地形に溜まる水の総量(2次元)', tags: ['ヒープ', 'BFS'], io: '1行目に H W、続く H 行に各マスの高さが与えられます。', ask: '外周から水は流れ出るとして、この地形に溜まる水の総量を出力してください。', h1: '1次元と違い左右の最大だけでは決まらない。水は最も低い外壁から漏れる。', h2: '外周をヒープに入れ、常に最も低い境界から内側へ広げる。境界の高さより低いマスには差の分だけ水が溜まる。', ref: 'import heapq\nh,w=map(int,input().split())\ng=[list(map(int,input().split())) for _ in range(h)]\nseen=[[False]*w for _ in range(h)]\npq=[]\nfor i in range(h):\n    for j in range(w):\n        if i in (0,h-1) or j in (0,w-1):\n            seen[i][j]=True\n            heapq.heappush(pq,(g[i][j],i,j))\nwater=0\nwhile pq:\n    lvl,i,j=heapq.heappop(pq)\n    for di,dj in ((1,0),(-1,0),(0,1),(0,-1)):\n        ni,nj=i+di,j+dj\n        if 0<=ni<h and 0<=nj<w and not seen[ni][nj]:\n            seen[ni][nj]=True\n            if g[ni][nj]<lvl:\n                water+=lvl-g[ni][nj]\n                heapq.heappush(pq,(lvl,ni,nj))\n            else:\n                heapq.heappush(pq,(g[ni][nj],ni,nj))\nprint(water)', tip: '「一番低い境界から攻める」のはダイクストラの親戚(最小をヒープで広げる)。水位は max(境界, 自分の高さ) で単調に上がっていく。', ins: ['3 6\n1 4 3 1 3 2\n3 2 1 3 2 4\n2 3 3 2 3 1\n', '3 3\n3 3 3\n3 0 3\n3 3 3\n', '1 1\n5\n', '2 2\n1 2\n3 4\n', '3 3\n2 2 2\n2 1 2\n2 2 1\n', '3 4\n5 5 5 5\n5 1 1 5\n5 5 5 5\n'] })

t({ lv: 522, concept: '二点法: 目標に最も近いペア和', title: '目標に最も近い2数の和', tags: ['二点法'], io: '1行目に目標値、2行目に整数列(2個以上)が与えられます。', ask: '2つの要素の和のうち目標に最も近いものを出力してください。同じ近さなら小さい方の和。', h1: 'ソートして両端にポインタを置く。', h2: '和が目標より小さければ左を右へ、大きければ右を左へ。差の絶対値と同点処理を更新しながら。', ref: 't=int(input())\na=sorted(map(int,input().split()))\ni,j=0,len(a)-1\nbest=a[i]+a[j]\nwhile i<j:\n    s=a[i]+a[j]\n    if abs(s-t)<abs(best-t) or (abs(s-t)==abs(best-t) and s<best):\n        best=s\n    if s<t:\n        i+=1\n    elif s>t:\n        j-=1\n    else:\n        break\nprint(best)', tip: '「ちょうど」ではなく「最も近い」でも二点法はそのまま動く。動かす判断(和と目標の大小)が探索空間を漏れなく刈る、という不変条件は同じ。', ins: ['10\n1 3 5 7\n', '5\n1 2 9\n', '0\n-3 4 1\n', '8\n2 2 2\n', '100\n1 2\n', '7\n3 4 2 5\n'] })

t({ lv: 523, concept: 'bit演算: 奇数回現れる2つの値', title: '奇数回だけ現れる2つの数', tags: ['bit演算'], io: '整数列が1行で空白区切りで与えられます。ちょうど2種類の値だけが奇数回現れ、他は全て偶数回現れます。', ask: '奇数回現れる2つの値を昇順に空白区切りで出力してください。', h1: '全部XORすると偶数回の値は消える。', h2: '残った x⊕y の立っているビットで全体を2グループに分ければ、各グループのXORが答えのそれぞれになる。', ref: 'a=list(map(int,input().split()))\nx=0\nfor v in a:\n    x^=v\nb=x&-x\np=q=0\nfor v in a:\n    if v&b:\n        p^=v\n    else:\n        q^=v\nprint(min(p,q),max(p,q))', tip: '「1つだけ奇数回」はXOR一発、「2つ」は違いのビットで分割してから各々XOR。x&-x で最下位の差ビットを取るのが定石(single number III)。', ins: ['1 2 1 3\n', '1 1 2 2 3 4\n', '5 7\n', '0 1 0 2\n', '10 10 10 10 3 9\n', '4 4 1 2 1 8\n'] })

t({ lv: 524, concept: 'ソート: 整列への最小交換回数', title: 'ソートに必要な最小スワップ数', tags: ['ソート'], io: '相異なる整数の列が1行で空白区切りで与えられます。', ask: '任意の2要素の交換だけで昇順に並べ替えるときの最小交換回数を出力してください。', h1: '「今の位置→あるべき位置」を矢印で結ぶと巡回(サイクル)に分かれる。', h2: '長さ L のサイクルは L−1 回の交換で直る。答えは n − サイクル数。', ref: 'a=list(map(int,input().split()))\nn=len(a)\npos={v:i for i,v in enumerate(sorted(a))}\nseen=[False]*n\nsw=0\nfor i in range(n):\n    if seen[i]:\n        continue\n    j=i\n    size=0\n    while not seen[j]:\n        seen[j]=True\n        j=pos[a[j]]\n        size+=1\n    sw+=size-1\nprint(sw)', tip: '置換のサイクル分解は「最小交換」「順列の位数」「偶奇(符号)」を一気に教えてくれる。隣接交換しか許さないと最小回数は転倒数に変わる。', ins: ['4 3 2 1\n', '1 2 3\n', '2 3 1\n', '1\n', '10 20 5\n', '3 1 2 4\n'] })

t({ lv: 525, concept: '配列: 直す必要のある最短区間', title: 'そこだけ直せば整列する最短区間', tags: ['配列', 'ソート'], io: '整数列が1行で空白区切りで与えられます。', ask: 'その連続区間だけを並べ替えれば全体が昇順になる、最短の区間の長さを出力してください。既に昇順なら 0。', h1: 'ソートした列と比べる。', h2: '先頭から一致が崩れる位置と、末尾から一致が崩れる位置に挟まれた区間が答え。', ref: 'a=list(map(int,input().split()))\nb=sorted(a)\nn=len(a)\ni=0\nwhile i<n and a[i]==b[i]:\n    i+=1\nif i==n:\n    print(0)\nelse:\n    j=n-1\n    while a[j]==b[j]:\n        j-=1\n    print(j-i+1)', tip: 'ソート済みコピーとの先頭・末尾一致で挟み撃ちにする方法はO(n log n)。スタックや接頭辞max/接尾辞minを使えばO(n)にもできる。', ins: ['2 6 4 8 10 9 15\n', '1 2 3 4\n', '1\n', '2 1\n', '1 3 2 2 2\n', '1 2 5 3 4\n'] })

t({ lv: 526, concept: 'ソート: g指数', title: '論文のg指数', tags: ['ソート'], io: '各論文の被引用数が1行で空白区切りで与えられます。', ask: '被引用数を大きい順に並べたとき、上位 g 件の合計が g² 以上になる最大の g(g指数)を出力してください。', h1: '降順ソートして累積和を取る。', h2: '累積和が i² 以上である最大の i。', ref: 'a=sorted(map(int,input().split()),reverse=True)\ns=0\ng=0\nfor i,v in enumerate(a,1):\n    s+=v\n    if s>=i*i:\n        g=i\nprint(g)', tip: 'h指数は「上位h件が各h回以上」、g指数は「上位g件の合計がg²以上」。少数の大ヒットを評価に反映させたいという動機の違いが式の違いに出ている。', ins: ['10 8 5 4 3\n', '0 0\n', '5\n', '1 1 1 1\n', '9 9 9\n', '4 4 4 4 1\n'] })

t({ lv: 527, concept: '区間: カバーされない長さ', title: '区間で覆われない部分の長さ', tags: ['区間', 'ソート'], io: '1行目に全体の長さ T (区間 [0,T])、2行目に区間の本数 n、続く n 行に区間 l r (0≤l≤r≤T) が与えられます。', ask: '[0,T] のうち、どの区間にも覆われない部分の長さの合計を出力してください。', h1: '区間を開始位置でソートして重なりを併合する。', h2: '覆われた総長を T から引く。', ref: 't=int(input())\nn=int(input())\niv=[tuple(map(int,input().split())) for _ in range(n)]\niv.sort()\ncov=0\ncl,cr=None,None\nfor l,r in iv:\n    if cl is None:\n        cl,cr=l,r\n    elif l<=cr:\n        if r>cr:\n            cr=r\n    else:\n        cov+=cr-cl\n        cl,cr=l,r\nif cl is not None:\n    cov+=cr-cl\nprint(t-cov)', tip: '「覆われない量」は直接追うより「覆われた量の補集合」が楽。併合済み区間のリストは他にも衝突判定・空き時間検索などに使い回せる。', ins: ['10\n2\n1 3\n5 8\n', '10\n0\n', '5\n1\n0 5\n', '10\n3\n0 4\n2 6\n8 9\n', '7\n2\n1 2\n2 3\n', '100\n2\n0 50\n50 100\n'] })

t({ lv: 528, concept: '配列: つり合いの位置', title: '左右の和が等しくなる位置', tags: ['配列', '累積和'], io: '整数列が1行で空白区切りで与えられます。', ask: 'その位置より左の総和と右の総和が等しくなる最小の位置(0始まり)を出力してください。無ければ -1。', h1: '全体の和を先に求めておく。', h2: '左の和を持ち回れば、右の和は「全体−左−自分」で O(1)。', ref: 'a=list(map(int,input().split()))\ntotal=sum(a)\nleft=0\nans=-1\nfor i,v in enumerate(a):\n    if left==total-left-v:\n        ans=i\n        break\n    left+=v\nprint(ans)', tip: '両側の累積和を2本持つ代わりに「全体から引く」ことで1本で済ませる。左右対称な量は片側+全体で表せないか、と一度は疑うと良い。', ins: ['1 7 3 6 5 6\n', '1 2 3\n', '2 1 -1\n', '5\n', '0 0 0\n', '1 -1 4\n'] })

t({ lv: 529, concept: '単調スタック: k桁削って最小の数', title: 'k桁消して作る最小の数', tags: ['スタック', '貪欲'], io: '1行目に消す桁数 k、2行目に数字だけの文字列が与えられます (kは桁数未満)。', ask: 'k 桁をどこからでも消して作れる最小の数を出力してください(先頭の0は取り除き、空になれば0)。', h1: '前の桁が次の桁より大きければ、前の桁を消すと必ず小さくなる。', h2: '増加を保つスタックに積み、大きい末尾を k 回まで捨てる。余った削除権は末尾から使う。', ref: 'k=int(input())\ns=input()\nst=[]\nfor c in s:\n    while st and k>0 and st[-1]>c:\n        st.pop()\n        k-=1\n    st.append(c)\nwhile k>0:\n    st.pop()\n    k-=1\nres="".join(st).lstrip("0")\nprint(res if res else "0")', tip: '「辞書順最小の部分列」系は単調スタックの十八番。削除権が余ったら末尾を削る、先頭0の後始末、の2つが実装の落とし穴。', ins: ['3\n1432219\n', '1\n10200\n', '2\n10\n', '1\n112\n', '2\n54321\n', '0\n10\n'] })

t({ lv: 530, concept: 'バックトラック: 4×4数独の解の数', title: 'ミニ数独の解を数える', tags: ['バックトラック'], io: '4行に4個ずつ、0(空)または1〜4の数字が与えられます。', ask: '各行・各列・各2×2ブロックに1〜4が1度ずつ現れるように空マスを埋める方法の数を出力してください。', h1: '左上から順に空マスを埋めて再帰する。', h2: '行・列・2×2ブロックの3つの制約を満たす数字だけ試す。', ref: 'g=[list(map(int,input().split())) for _ in range(4)]\ndef ok(r,c,v):\n    for i in range(4):\n        if g[r][i]==v or g[i][c]==v:\n            return False\n    br,bc=r//2*2,c//2*2\n    for i in range(br,br+2):\n        for j in range(bc,bc+2):\n            if g[i][j]==v:\n                return False\n    return True\ncnt=0\ndef solve(p):\n    global cnt\n    if p==16:\n        cnt+=1\n        return\n    r,c=divmod(p,4)\n    if g[r][c]:\n        solve(p+1)\n        return\n    for v in range(1,5):\n        if ok(r,c,v):\n            g[r][c]=v\n            solve(p+1)\n            g[r][c]=0\nsolve(0)\nprint(cnt)', tip: '4×4の数独(空盤)の解は288個。本物の9×9では約6.67×10²¹個ある。「解の一意性」がパズルの良問条件で、それも同じ数え上げで検査できる。', ins: ['0 0 0 0\n0 0 0 0\n0 0 0 0\n0 0 0 0\n', '1 2 3 4\n3 4 1 2\n2 1 4 3\n4 3 2 1\n', '1 0 0 0\n0 0 0 0\n0 0 0 0\n0 0 0 0\n', '1 2 0 0\n0 0 0 0\n0 0 0 0\n0 0 0 0\n', '1 1 0 0\n0 0 0 0\n0 0 0 0\n0 0 0 0\n', '1 2 3 4\n3 4 1 2\n0 0 0 0\n0 0 0 0\n'] })

t({ lv: 531, concept: 'バックトラック: ラテン方陣の数', title: 'n次ラテン方陣を数える', tags: ['バックトラック'], io: '正整数 n (n≤4) が1行で与えられます。', ask: '各行・各列に 1〜n が1度ずつ現れる n×n の表(ラテン方陣)の総数を出力してください。', h1: 'マスを左上から順に埋める再帰で数える。', h2: '同じ行・同じ列の既出だけ確認すればよい。', ref: 'n=int(input())\ng=[[0]*n for _ in range(n)]\ncnt=0\ndef solve(p):\n    global cnt\n    if p==n*n:\n        cnt+=1\n        return\n    r,c=divmod(p,n)\n    for v in range(1,n+1):\n        okv=True\n        for i in range(c):\n            if g[r][i]==v:\n                okv=False\n        for i in range(r):\n            if g[i][c]==v:\n                okv=False\n        if okv:\n            g[r][c]=v\n            solve(p+1)\n            g[r][c]=0\nsolve(0)\nprint(cnt)', tip: '1,2,12,576,161280,…と爆発的に増え、n=12以上の正確な総数は未解明。数独はラテン方陣にブロック制約を足した特殊形にあたる。', ins: ['1\n', '2\n', '3\n', '4\n'] })

t({ lv: 532, concept: 'バックトラック: グリッドで単語探し', title: '盤面から単語をなぞれるか', tags: ['バックトラック'], io: '1行目に H W、続く H 行に英大文字の盤面(空白なし)、最後の行に単語が与えられます。', ask: '上下左右に隣接するマスをたどり(同じマスは1回まで)、単語をなぞれるなら yes、なぞれなければ no を出力してください。', h1: '各マスを開始点に深さ優先で試す。', h2: '訪問中のマスを集合に入れ、行き止まりなら取り除いて戻る(バックトラック)。', ref: 'h,w=map(int,input().split())\ng=[input() for _ in range(h)]\nword=input()\ndef dfs(r,c,k,used):\n    if g[r][c]!=word[k]:\n        return False\n    if k==len(word)-1:\n        return True\n    used.add((r,c))\n    for dr,dc in ((1,0),(-1,0),(0,1),(0,-1)):\n        nr,nc=r+dr,c+dc\n        if 0<=nr<h and 0<=nc<w and (nr,nc) not in used and dfs(nr,nc,k+1,used):\n            used.discard((r,c))\n            return True\n    used.discard((r,c))\n    return False\nans=any(dfs(r,c,0,set()) for r in range(h) for c in range(w))\nprint("yes" if ans else "no")', tip: '「試して、ダメなら печать戻す」の型。usedへの追加と削除を対で書くと状態復元を忘れない。単語が多いときはトライ木を持って一括探索に発展する。', ins: ['3 4\nABCE\nSFCS\nADEE\nABCCED\n', '3 4\nABCE\nSFCS\nADEE\nSEE\n', '3 4\nABCE\nSFCS\nADEE\nABCB\n', '1 1\nA\nA\n', '2 2\nAB\nCD\nABDC\n', '2 2\nAA\nAA\nAAAAA\n'] })

t({ lv: 533, concept: 'DP: 連続3分割で等和', title: '3つの連続ブロックに等分できるか', tags: ['累積和'], io: '整数列が1行で空白区切りで与えられます。', ask: '列を3つの空でない連続した部分に切り、3つの和がすべて等しくできるなら yes、できなければ no を出力してください。', h1: '合計が3で割り切れなければ不可能。', h2: '接頭和が T/3 になる位置を見つけた後、2T/3 になる位置がさらに後ろ(最後の要素より前)にあるか。', ref: 'a=list(map(int,input().split()))\nn=len(a)\ntotal=sum(a)\nans="no"\nif n>=3 and total%3==0:\n    t=total//3\n    pre=0\n    seen=False\n    for j in range(n-1):\n        pre+=a[j]\n        if seen and pre==2*t:\n            ans="yes"\n            break\n        if pre==t and j<=n-3:\n            seen=True\nprint(ans)', tip: '部分集合の3等分はNP困難だが、「連続」制約が付くと接頭和の走査1回で解ける。制約が問題を易しくする好例。負の数や0でも接頭和の論法は壊れない。', ins: ['1 2 3 0 3\n', '1 2 3\n', '3 3 3\n', '0 0 0 0\n', '1 -1 1 -1 1 -1\n', '1 1\n'] })

t({ lv: 534, concept: 'バックトラック: 演算子を挟んで目標値', title: '演算子の挟み方で目標を作る', tags: ['バックトラック'], io: '1行目に目標値、2行目に数字だけの文字列が与えられます。', ask: '各数字の間に +, -, × のどれかを1つずつ挟んでできる式(通常の優先順位で計算)のうち、値が目標に等しいものの個数を出力してください。', h1: '挟み方は 3^(桁数−1) 通りしかない。', h2: '式を文字列で組み立てて評価するか、乗算の連なりを保留しながら再帰する。', ref: 't=int(input())\ns=input()\nn=len(s)\ncnt=0\ndef go(i,expr):\n    global cnt\n    if i==n:\n        if eval(expr)==t:\n            cnt+=1\n        return\n    for op in ("+","-","*"):\n        go(i+1,expr+op+s[i])\ngo(1,s[0])\nprint(cnt)', tip: 'evalは優先順位を正しく処理してくれるので全列挙の検証にぴったり(外部入力に使うのは危険)。高速化するなら「直前の乗算項」を状態に持つDPへ。', ins: ['6\n123\n', '0\n12\n', '2\n12\n', '1\n1\n', '7\n124\n', '24\n234\n'] })

t({ lv: 535, concept: '文字列: 交互01にする最小変更数', title: '0と1を交互にする最小の書き換え', tags: ['文字列'], io: '0/1の文字列が1行で与えられます。', ask: '文字をいくつか書き換えて「隣どうしが必ず異なる」文字列にするときの最小の書き換え数を出力してください。', h1: '完成形は 0101… か 1010… の2通りしかない。', h2: '0101… とのずれの個数を a とすると、1010… とのずれは 長さ−a。小さい方が答え。', ref: 's=input()\na=sum(1 for i,c in enumerate(s) if int(c)!=i%2)\nprint(min(a,len(s)-a))', tip: '「完成形が数種類しかない」問題は、各完成形との距離を測って最小を取るだけ。2つの距離が補い合う(和が長さ)ことに気づくと片方だけ数えれば済む。', ins: ['0100\n', '10\n', '1111\n', '0\n', '010101\n', '1001\n'] })

t({ lv: 536, concept: 'バックトラック: 禁止マスありルーク配置数', title: '避けて置くn個のルーク', tags: ['バックトラック'], io: '1行目に n、続く n 行に盤面(.は置ける、#は禁止)が与えられます。', ask: 'n×n の盤に互いに取り合わない(同じ行・列に2個置かない)ように n 個のルークを置く方法の数を出力してください。', h1: '各行にちょうど1個置くことになる。', h2: '行ごとに「まだ使っていない列」かつ「禁止でない」マスを選ぶ再帰。使用列はビットマスクが速い。', ref: 'n=int(input())\ng=[input() for _ in range(n)]\ncnt=0\ndef go(r,used):\n    global cnt\n    if r==n:\n        cnt+=1\n        return\n    for c in range(n):\n        if not used>>c&1 and g[r][c]==".":\n            go(r+1,used|1<<c)\ngo(0,0)\nprint(cnt)', tip: 'この数は0/1行列のパーマネント(行列式の符号なし版)。行列式は多項式時間だがパーマネントは#P完全、という計算量の名コントラストがある。', ins: ['2\n..\n..\n', '2\n#.\n.#\n', '3\n...\n...\n...\n', '3\n#..\n.#.\n..#\n', '2\n##\n##\n', '1\n.\n'] })

t({ lv: 537, concept: 'DP: 2台同時収集の最大', title: '2台のロボットで拾う最大量', tags: ['DP'], io: '1行目に H W、続く H 行に各マスの値が与えられます。ロボットAは左上、ロボットBは右上から出発します。', ask: '各ロボットは毎行「真下・左下・右下」のどれかに進みます。通ったマスの値を得ますが、同じマスに2台が来たら1回分だけです。最下段に着くまでに得られる合計の最大を出力してください。', h1: '2台の列位置の組 (c1,c2) を状態に持つ。', h2: '行ごとに 3×3 通りの移動で遷移し、同じマスなら加算は1回分。', ref: 'h,w=map(int,input().split())\ng=[list(map(int,input().split())) for _ in range(h)]\nNEG=-10**9\ndp=[[NEG]*w for _ in range(w)]\ndp[0][w-1]=g[0][0]+(g[0][w-1] if w>1 else 0)\nfor r in range(1,h):\n    nd=[[NEG]*w for _ in range(w)]\n    for c1 in range(w):\n        for c2 in range(w):\n            if dp[c1][c2]==NEG:\n                continue\n            for d1 in (-1,0,1):\n                for d2 in (-1,0,1):\n                    n1,n2=c1+d1,c2+d2\n                    if 0<=n1<w and 0<=n2<w:\n                        v=dp[c1][c2]+g[r][n1]+(g[r][n2] if n1!=n2 else 0)\n                        if v>nd[n1][n2]:\n                            nd[n1][n2]=v\n    dp=nd\nprint(max(max(row) for row in dp))', tip: '「2回別々に最適化」すると同じマスの2重取りが直せない。2つの主体を1つの状態にまとめて同時に動かすのが多主体DPの要点。', ins: ['3 3\n3 1 1\n2 5 1\n1 5 5\n', '1 1\n7\n', '1 2\n1 2\n', '2 2\n1 1\n1 1\n', '4 3\n1 0 0\n0 0 0\n0 0 0\n0 0 1\n', '2 3\n1 2 3\n4 5 6\n'] })

t({ lv: 538, concept: '数え上げ: 同じ文字が隣り合わない並べ方', title: '同じ文字を離して並べる方法の数', tags: ['数学', '再帰'], io: '英小文字の文字列(文字の多重集合)が1行で与えられます。', ask: '文字を並べ替えてできる文字列のうち、同じ文字が隣り合わないものの個数を出力してください。', h1: '「直前に置いた文字」と「残りの文字数」で状態が決まる。', h2: '文字種ごとの残数を辞書に持ち、直前と違う文字を選んで再帰する。', ref: 'from collections import Counter\ns=input()\nc=Counter(s)\nkeys=sorted(c)\nn=len(s)\ndef go(last,rem):\n    if rem==0:\n        return 1\n    tot=0\n    for k in keys:\n        if k!=last and c[k]>0:\n            c[k]-=1\n            tot+=go(k,rem-1)\n            c[k]+=1\n    return tot\nprint(go("",n))', tip: '多重集合の並べ替え数え上げは「残数ベクトル+直前」のメモ化で多項式的に潰せる。包除原理(隣接ペアを塊とみなす)でも同じ答えに到達できる。', ins: ['aab\n', 'ab\n', 'aa\n', 'aabb\n', 'abc\n', 'aaab\n'] })

t({ lv: 539, concept: '数え上げ: 積への分解の数', title: '掛け算で作る分解の数', tags: ['数学', '再帰'], io: '2以上の整数 n が1行で与えられます。', ask: 'n を2以上の整数の積として表す方法の数(順序は区別しない。n 単独も1通りと数える)を出力してください。', h1: '最小の因数を決めて再帰する。', h2: 'f(n, m) を「因数を全て m 以上にする分解の数」とし、m 以上の約数 d ごとに f(n/d, d) を足す。', ref: 'import sys\nsys.setrecursionlimit(10000)\nn=int(input())\ndef f(n,m):\n    total=1 if n>=m else 0\n    d=m\n    while d*d<=n:\n        if n%d==0:\n            total+=f(n//d,d)\n        d+=1\n    return total\nprint(f(n,2))', tip: '因数を昇順に選ぶことで順序の重複を潰す、整数分割と同じ「最小要素を固定する」型。乗法的分割数はfactorisatio numerorumと呼ばれる古典。', ins: ['12\n', '2\n', '8\n', '30\n', '16\n', '7\n'] })

t({ lv: 540, concept: 'DP: 同じ歩幅を続けない階段', title: '同じ歩幅を連続で使えない階段', tags: ['DP'], io: '段数 n が1行で与えられます。', ask: '1段か2段ずつ上るが「直前と同じ歩幅は連続で使えない」とき、ちょうど n 段を上り切る方法の数を出力してください。', h1: '「最後の歩幅」を状態に持つ。', h2: '1で終わる方法は直前が2、2で終わる方法は直前が1、と互い違いに遷移する。', ref: 'n=int(input())\ndp1=[0]*(n+1)\ndp2=[0]*(n+1)\nfor i in range(1,n+1):\n    dp1[i]=(1 if i==1 else 0)+dp2[i-1]\n    if i>=2:\n        dp2[i]=(1 if i==2 else 0)+dp1[i-2]\nprint(dp1[n]+dp2[n])', tip: '制約「直前と違う」は状態に直前の選択を持たせるだけで表せる。歩幅が交互に固定されるため、方法数はほぼ1通りに絞られていくのが面白い。', ins: ['1\n', '2\n', '3\n', '4\n', '5\n', '7\n'] })

export const CATALOG = TASKS
