// 生成タスク 第42波：lv801〜849。lv800(高度なデータ構造)帯。
// セグメント木/遅延伝播/BIT(各種)/Sparse Table/単調スタック・デック/Union-Find応用の別問題。
// 重複なし・決定的・採点一意(整数/文字列出力のみ)。無限ループ無し。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 801, concept: 'セグ木: 一点更新区間和', title: '一点更新と区間和(セグメント木)', tags: ['データ構造'], io: '1行目に n q、2行目に n 個の値、続く q 行に "upd i x" または "sum l r"(0始まり両端含む)が与えられます。', ask: 'すべての "sum" の結果の合計を出力してください。', h1: '葉に値、内部に部分和を持つ。', h2: '一点更新は親を辿り、区間和は左右に分けて足す。', ref: 'first=input().split()\nn=int(first[0])\nq=int(first[1])\na=list(map(int,input().split()))\nsize=1\nwhile size<n:\n    size*=2\ntree=[0]*(2*size)\nfor i in range(n):\n    tree[size+i]=a[i]\nfor i in range(size-1,0,-1):\n    tree[i]=tree[2*i]+tree[2*i+1]\ndef update(pos,val):\n    pos+=size\n    tree[pos]=val\n    pos//=2\n    while pos>=1:\n        tree[pos]=tree[2*pos]+tree[2*pos+1]\n        pos//=2\ndef query(l,r):\n    l+=size\n    r+=size+1\n    res=0\n    while l<r:\n        if l&1:\n            res+=tree[l]\n            l+=1\n        if r&1:\n            r-=1\n            res+=tree[r]\n        l//=2\n        r//=2\n    return res\ntotal=0\nfor _ in range(q):\n    op=input().split()\n    if op[0]=="upd":\n        update(int(op[1]),int(op[2]))\n    else:\n        total+=query(int(op[1]),int(op[2]))\nprint(total)', tip: 'セグメント木は一点更新O(log n)・区間和O(log n)。和は結合的で単位元0。', ins: ['5 3\n1 2 3 4 5\nsum 0 4\nupd 2 10\nsum 0 4\n', '3 1\n1 1 1\nsum 0 2\n', '1 1\n5\nsum 0 0\n', '4 2\n1 2 3 4\nupd 0 5\nsum 0 1\n', '5 1\n2 4 6 8 10\nsum 1 3\n', '4 2\n1 1 1 1\nsum 0 3\nsum 1 2\n'] })

t({ lv: 802, concept: 'セグ木: 一点更新区間最大', title: '一点更新と区間最大(セグメント木)', tags: ['データ構造'], io: '1行目に n q、2行目に n 個の値、続く q 行に "upd i x" または "max l r"(0始まり両端含む)が与えられます。', ask: 'すべての "max" の結果の合計を出力してください。', h1: '集約を max にする。', h2: '単位元は -inf(またはとても小さい値)。', ref: 'first=input().split()\nn=int(first[0])\nq=int(first[1])\na=list(map(int,input().split()))\nNEG=float("-inf")\nsize=1\nwhile size<n:\n    size*=2\ntree=[NEG]*(2*size)\nfor i in range(n):\n    tree[size+i]=a[i]\nfor i in range(size-1,0,-1):\n    tree[i]=max(tree[2*i],tree[2*i+1])\ndef update(pos,val):\n    pos+=size\n    tree[pos]=val\n    pos//=2\n    while pos>=1:\n        tree[pos]=max(tree[2*pos],tree[2*pos+1])\n        pos//=2\ndef query(l,r):\n    l+=size\n    r+=size+1\n    res=NEG\n    while l<r:\n        if l&1:\n            res=max(res,tree[l])\n            l+=1\n        if r&1:\n            r-=1\n            res=max(res,tree[r])\n        l//=2\n        r//=2\n    return res\ntotal=0\nfor _ in range(q):\n    op=input().split()\n    if op[0]=="upd":\n        update(int(op[1]),int(op[2]))\n    else:\n        total+=query(int(op[1]),int(op[2]))\nprint(total)', tip: '区間最大のセグ木は集約を max、単位元を -inf にするだけ。更新・クエリともO(log n)。', ins: ['5 3\n1 5 3 4 2\nmax 0 4\nupd 0 10\nmax 0 2\n', '3 1\n1 2 3\nmax 0 2\n', '1 1\n7\nmax 0 0\n', '4 2\n4 3 2 1\nmax 2 3\nupd 3 100\nmax 0 3\n', '5 1\n5 4 3 2 1\nmax 1 3\n', '4 2\n1 2 3 4\nmax 0 1\nmax 2 3\n'] })

t({ lv: 803, concept: '遅延セグ木: 区間加算区間和', title: '区間加算と区間和(遅延伝播)', tags: ['データ構造'], io: '1行目に n q、2行目に n 個の値、続く q 行に "add l r v" または "sum l r"(0始まり両端含む)が与えられます。', ask: 'すべての "sum" の結果の合計を出力してください。', h1: '各ノードに区間和と遅延値を持つ。', h2: '降りる前に push し、戻りで pull する。', ref: 'import sys\nfirst=input().split()\nn=int(first[0])\nq=int(first[1])\na=list(map(int,input().split()))\nsize=1\nwhile size<n:\n    size*=2\nsm=[0]*(2*size)\nlz=[0]*(2*size)\nln=[0]*(2*size)\nfor i in range(size):\n    ln[size+i]=1\nfor i in range(n):\n    sm[size+i]=a[i]\nfor i in range(size-1,0,-1):\n    sm[i]=sm[2*i]+sm[2*i+1]\n    ln[i]=ln[2*i]+ln[2*i+1]\ndef apply(node,v):\n    sm[node]+=v*ln[node]\n    lz[node]+=v\ndef push(node):\n    if lz[node]!=0:\n        apply(2*node,lz[node])\n        apply(2*node+1,lz[node])\n        lz[node]=0\ndef add(node,nl,nr,l,r,v):\n    if r<nl or nr<l:\n        return\n    if l<=nl and nr<=r:\n        apply(node,v)\n        return\n    push(node)\n    mid=(nl+nr)//2\n    add(2*node,nl,mid,l,r,v)\n    add(2*node+1,mid+1,nr,l,r,v)\n    sm[node]=sm[2*node]+sm[2*node+1]\ndef qsum(node,nl,nr,l,r):\n    if r<nl or nr<l:\n        return 0\n    if l<=nl and nr<=r:\n        return sm[node]\n    push(node)\n    mid=(nl+nr)//2\n    return qsum(2*node,nl,mid,l,r)+qsum(2*node+1,mid+1,nr,l,r)\ntotal=0\nfor _ in range(q):\n    op=input().split()\n    if op[0]=="add":\n        add(1,0,size-1,int(op[1]),int(op[2]),int(op[3]))\n    else:\n        total+=qsum(1,0,size-1,int(op[1]),int(op[2]))\nprint(total)', tip: '遅延伝播は「区間まとめて更新」を遅延値に貯め、必要時にだけ子へ push する。区間加算＋区間和の定番。', ins: ['5 3\n1 2 3 4 5\nadd 0 2 10\nsum 0 4\nsum 0 2\n', '3 1\n1 1 1\nsum 0 2\n', '1 2\n5\nadd 0 0 3\nsum 0 0\n', '4 2\n0 0 0 0\nadd 1 2 5\nsum 0 3\n', '5 1\n1 2 3 4 5\nsum 0 4\n', '4 3\n1 1 1 1\nadd 0 3 1\nadd 0 1 1\nsum 0 3\n'] })

t({ lv: 804, concept: '遅延セグ木: 区間代入区間最小', title: '区間代入と区間最小(遅延伝播)', tags: ['データ構造'], io: '1行目に n q、2行目に n 個の値、続く q 行に "set l r v" または "min l r"(0始まり両端含む)が与えられます。', ask: 'すべての "min" の結果の合計を出力してください。', h1: '代入の遅延値を持つ(未設定フラグを使う)。', h2: 'push で子へ代入を伝える。', ref: 'import sys\nfirst=input().split()\nn=int(first[0])\nq=int(first[1])\na=list(map(int,input().split()))\nINF=float("inf")\nNONE=None\nsize=1\nwhile size<n:\n    size*=2\nmn=[INF]*(2*size)\nlz=[NONE]*(2*size)\nfor i in range(n):\n    mn[size+i]=a[i]\nfor i in range(size-1,0,-1):\n    mn[i]=min(mn[2*i],mn[2*i+1])\ndef apply(node,v):\n    mn[node]=v\n    lz[node]=v\ndef push(node):\n    if lz[node] is not None:\n        apply(2*node,lz[node])\n        apply(2*node+1,lz[node])\n        lz[node]=None\ndef setr(node,nl,nr,l,r,v):\n    if r<nl or nr<l:\n        return\n    if l<=nl and nr<=r:\n        apply(node,v)\n        return\n    push(node)\n    mid=(nl+nr)//2\n    setr(2*node,nl,mid,l,r,v)\n    setr(2*node+1,mid+1,nr,l,r,v)\n    mn[node]=min(mn[2*node],mn[2*node+1])\ndef qmin(node,nl,nr,l,r):\n    if r<nl or nr<l:\n        return INF\n    if l<=nl and nr<=r:\n        return mn[node]\n    push(node)\n    mid=(nl+nr)//2\n    return min(qmin(2*node,nl,mid,l,r),qmin(2*node+1,mid+1,nr,l,r))\ntotal=0\nfor _ in range(q):\n    op=input().split()\n    if op[0]=="set":\n        setr(1,0,size-1,int(op[1]),int(op[2]),int(op[3]))\n    else:\n        total+=qmin(1,0,size-1,int(op[1]),int(op[2]))\nprint(total)', tip: '区間代入は「未設定(None)」を遅延値の初期状態にし、代入で上書きする。最小クエリと組み合わせる。', ins: ['5 3\n5 4 3 2 1\nmin 0 4\nset 0 2 9\nmin 0 2\n', '3 1\n1 2 3\nmin 0 2\n', '1 2\n5\nset 0 0 2\nmin 0 0\n', '4 2\n4 3 2 1\nset 0 3 7\nmin 0 3\n', '5 1\n1 2 3 4 5\nmin 1 3\n', '4 3\n9 9 9 9\nset 1 2 1\nmin 0 3\nmin 0 0\n'] })

t({ lv: 805, concept: 'BIT: 一点加算と接頭辞和', title: 'Fenwick木の一点加算と接頭辞和', tags: ['データ構造'], io: '1行目に n q、2行目に n 個の値、続く q 行に "add i x"(位置iにx加算) または "pre i"(先頭からiまでの和、0始まり両端含む)が与えられます。', ask: 'すべての "pre" の結果の合計を出力してください。', h1: '最下位ビットで木を登り降りする。', h2: '接頭辞和は i+1 から下位ビットを引きながら足す。', ref: 'first=input().split()\nn=int(first[0])\nq=int(first[1])\na=list(map(int,input().split()))\nbit=[0]*(n+1)\ndef add(i,x):\n    i+=1\n    while i<=n:\n        bit[i]+=x\n        i+=i&(-i)\ndef pre(i):\n    i+=1\n    s=0\n    while i>0:\n        s+=bit[i]\n        i-=i&(-i)\n    return s\nfor i in range(n):\n    add(i,a[i])\ntotal=0\nfor _ in range(q):\n    op=input().split()\n    if op[0]=="add":\n        add(int(op[1]),int(op[2]))\n    else:\n        total+=pre(int(op[1]))\nprint(total)', tip: 'BIT(Fenwick)は最下位ビット i&(-i) で部分和を管理。一点加算・接頭辞和ともO(log n)。', ins: ['5 3\n1 2 3 4 5\npre 4\nadd 2 10\npre 2\n', '3 1\n1 1 1\npre 2\n', '1 1\n5\npre 0\n', '4 2\n1 2 3 4\nadd 0 5\npre 0\n', '5 1\n2 4 6 8 10\npre 2\n', '4 2\n1 1 1 1\npre 3\npre 1\n'] })

t({ lv: 806, concept: 'BIT: 区間加算一点取得', title: '差分BITの区間加算と一点取得', tags: ['データ構造'], io: '1行目に n q、続く q 行に "add l r v"(区間[l,r]にv加算) または "get i"(位置iの値、初期0)が与えられます。', ask: 'すべての "get" の結果の合計を出力してください。', h1: '差分配列をBITで管理する。', h2: 'add は l に +v, r+1 に -v。get は接頭辞和。', ref: 'first=input().split()\nn=int(first[0])\nq=int(first[1])\nbit=[0]*(n+2)\ndef upd(i,x):\n    i+=1\n    while i<=n:\n        bit[i]+=x\n        i+=i&(-i)\ndef pre(i):\n    i+=1\n    s=0\n    while i>0:\n        s+=bit[i]\n        i-=i&(-i)\n    return s\ntotal=0\nfor _ in range(q):\n    op=input().split()\n    if op[0]=="add":\n        l=int(op[1])\n        r=int(op[2])\n        v=int(op[3])\n        upd(l,v)\n        if r+1<n:\n            upd(r+1,-v)\n    else:\n        total+=pre(int(op[1]))\nprint(total)', tip: '区間加算・一点取得は差分配列をBITに載せる。位置iの値はBITの接頭辞和になる。', ins: ['5 3\nadd 0 2 5\nget 1\nget 3\n', '3 1\nget 0\n', '1 2\nadd 0 0 7\nget 0\n', '4 2\nadd 0 3 1\nget 2\n', '5 1\nadd 1 4 10\nget 0\n', '4 3\nadd 0 1 1\nadd 1 2 1\nget 1\n'] })

t({ lv: 807, concept: 'BIT: 区間加算区間和(2本BIT)', title: '2本のBITで区間加算区間和', tags: ['データ構造'], io: '1行目に n q、続く q 行に "add l r v" または "sum l r"(0始まり両端含む)が与えられます(初期0)。', ask: 'すべての "sum" の結果の合計を出力してください。', h1: '2本のBITで一次の係数と定数項を管理する。', h2: '接頭辞和 = B1·i - B2 の形にする。', ref: 'first=input().split()\nn=int(first[0])\nq=int(first[1])\nb1=[0]*(n+2)\nb2=[0]*(n+2)\ndef _upd(bit,i,x):\n    i+=1\n    while i<=n+1:\n        bit[i]+=x\n        i+=i&(-i)\ndef _pre(bit,i):\n    i+=1\n    s=0\n    while i>0:\n        s+=bit[i]\n        i-=i&(-i)\n    return s\ndef range_add(l,r,v):\n    _upd(b1,l,v)\n    _upd(b1,r+1,-v)\n    _upd(b2,l,v*(l-1))\n    _upd(b2,r+1,-v*r)\ndef prefix(i):\n    return _pre(b1,i)*i-_pre(b2,i)\ntotal=0\nfor _ in range(q):\n    op=input().split()\n    if op[0]=="add":\n        range_add(int(op[1]),int(op[2]),int(op[3]))\n    else:\n        l=int(op[1])\n        r=int(op[2])\n        total+=prefix(r)-prefix(l-1)\nprint(total)', tip: '区間加算・区間和は2本のBITで「一次項と定数項」を分けて持つと両方O(log n)で実現できる。', ins: ['5 3\nadd 0 2 5\nsum 0 4\nsum 0 2\n', '3 1\nsum 0 2\n', '1 2\nadd 0 0 3\nsum 0 0\n', '4 2\nadd 1 2 5\nsum 0 3\n', '5 1\nsum 0 4\n', '4 3\nadd 0 3 1\nadd 0 1 1\nsum 0 3\n'] })

t({ lv: 808, concept: 'BIT: 2次元一点更新矩形和', title: '2次元BITの矩形和', tags: ['データ構造'], io: '1行目に R C q、続く q 行に "upd r c v"(マスに加算) または "sum r1 c1 r2 c2"(矩形和、0始まり両端含む)が与えられます(初期0)。', ask: 'すべての "sum" の結果の合計を出力してください。', h1: '2次元BITで点更新する。', h2: '矩形和は包除で4つの接頭辞和を組み合わせる。', ref: 'first=input().split()\nR=int(first[0])\nC=int(first[1])\nq=int(first[2])\nbit=[[0]*(C+1) for _ in range(R+1)]\ndef upd(r,c,v):\n    r+=1\n    i=r\n    while i<=R:\n        j=c+1\n        while j<=C:\n            bit[i][j]+=v\n            j+=j&(-j)\n        i+=i&(-i)\ndef pre(r,c):\n    r+=1\n    s=0\n    i=r\n    while i>0:\n        j=c+1\n        while j>0:\n            s+=bit[i][j]\n            j-=j&(-j)\n        i-=i&(-i)\n    return s\ntotal=0\nfor _ in range(q):\n    op=input().split()\n    if op[0]=="upd":\n        upd(int(op[1]),int(op[2]),int(op[3]))\n    else:\n        r1=int(op[1]);c1=int(op[2]);r2=int(op[3]);c2=int(op[4])\n        s=pre(r2,c2)-pre(r1-1,c2)-pre(r2,c1-1)+pre(r1-1,c1-1)\n        total+=s\nprint(total)', tip: '2次元BITは行・列の両方向に最下位ビットで木を組む。矩形和は2次元の包除で4点。', ins: ['2 2 3\nupd 0 0 5\nsum 0 0 1 1\nsum 0 0 0 0\n', '1 1 2\nupd 0 0 7\nsum 0 0 0 0\n', '3 3 1\nsum 0 0 2 2\n', '2 3 2\nupd 1 2 4\nsum 0 0 1 2\n', '2 2 1\nupd 1 1 9\nsum 0 0 1 1\n', '3 3 3\nupd 0 0 1\nupd 2 2 1\nsum 0 0 2 2\n'] })

t({ lv: 809, concept: 'Sparse Table: 区間最大', title: 'Sparse Tableの区間最大', tags: ['データ構造'], io: '1行目に n q、2行目に n 個の値、続く q 行に l r(0始まり両端含む)が与えられます。', ask: 'すべてのクエリの区間最大値の合計を出力してください。', h1: '2^k 長の最大値テーブルを前計算。', h2: '区間を2ブロックで覆い max を取る。', ref: 'first=input().split()\nn=int(first[0])\nq=int(first[1])\na=list(map(int,input().split()))\nsp=[a[:]]\nk=1\nwhile (1<<k)<=n:\n    prev=sp[k-1]\n    cur=[]\n    for i in range(n-(1<<k)+1):\n        cur.append(max(prev[i],prev[i+(1<<(k-1))]))\n    sp.append(cur)\n    k+=1\ndef query(l,r):\n    j=(r-l+1).bit_length()-1\n    return max(sp[j][l],sp[j][r-(1<<j)+1])\ntotal=0\nfor _ in range(q):\n    l,r=map(int,input().split())\n    total+=query(l,r)\nprint(total)', tip: 'Sparse Tableは更新なし区間最大を前計算O(n log n)・クエリO(1)。冪等な max が前提。', ins: ['5 2\n3 1 4 1 5\n0 4\n1 3\n', '3 1\n5 2 8\n0 2\n', '1 1\n7\n0 0\n', '4 2\n4 3 2 1\n0 1\n2 3\n', '5 1\n1 2 3 4 5\n1 4\n', '6 2\n6 5 4 3 2 1\n0 2\n3 5\n'] })

t({ lv: 810, concept: 'Sparse Table: 区間GCD', title: 'Sparse Tableの区間GCD', tags: ['データ構造', '数論'], io: '1行目に n q、2行目に n 個の値、続く q 行に l r(0始まり両端含む)が与えられます。', ask: 'すべてのクエリの区間GCDの合計を出力してください。', h1: 'GCDは冪等なので Sparse Table が使える。', h2: '2ブロックの gcd を取る(重なり可)。', ref: 'import math\nfirst=input().split()\nn=int(first[0])\nq=int(first[1])\na=list(map(int,input().split()))\nsp=[a[:]]\nk=1\nwhile (1<<k)<=n:\n    prev=sp[k-1]\n    cur=[]\n    for i in range(n-(1<<k)+1):\n        cur.append(math.gcd(prev[i],prev[i+(1<<(k-1))]))\n    sp.append(cur)\n    k+=1\ndef query(l,r):\n    j=(r-l+1).bit_length()-1\n    return math.gcd(sp[j][l],sp[j][r-(1<<j)+1])\ntotal=0\nfor _ in range(q):\n    l,r=map(int,input().split())\n    total+=query(l,r)\nprint(total)', tip: 'GCDは冪等(gcd(x,x)=x)なので重なるブロックでも正しく、Sparse Tableで更新なし区間GCDが O(1)。', ins: ['5 2\n2 4 6 8 10\n0 4\n1 2\n', '3 1\n6 9 15\n0 2\n', '1 1\n7\n0 0\n', '4 2\n12 8 6 4\n0 1\n2 3\n', '5 1\n10 20 30 40 50\n0 4\n', '4 2\n6 12 18 24\n0 1\n2 3\n'] })

t({ lv: 811, concept: 'Sparse Table: 区間AND', title: 'Sparse Tableの区間AND', tags: ['データ構造', 'bit演算'], io: '1行目に n q、2行目に n 個の非負整数、続く q 行に l r(0始まり両端含む)が与えられます。', ask: 'すべてのクエリの区間ビットANDの合計を出力してください。', h1: 'ANDは冪等なので Sparse Table が使える。', h2: '2ブロックの AND を取る。', ref: 'first=input().split()\nn=int(first[0])\nq=int(first[1])\na=list(map(int,input().split()))\nsp=[a[:]]\nk=1\nwhile (1<<k)<=n:\n    prev=sp[k-1]\n    cur=[]\n    for i in range(n-(1<<k)+1):\n        cur.append(prev[i]&prev[i+(1<<(k-1))])\n    sp.append(cur)\n    k+=1\ndef query(l,r):\n    j=(r-l+1).bit_length()-1\n    return sp[j][l]&sp[j][r-(1<<j)+1]\ntotal=0\nfor _ in range(q):\n    l,r=map(int,input().split())\n    total+=query(l,r)\nprint(total)', tip: 'ビットANDも冪等な演算なので Sparse Table に載る。区間ANDが O(1) で求まる。', ins: ['5 2\n7 6 4 12 8\n0 4\n0 1\n', '3 1\n6 4 2\n0 2\n', '1 1\n5\n0 0\n', '4 2\n15 7 3 1\n0 3\n1 2\n', '5 1\n255 127 63 31 15\n0 4\n', '4 2\n8 12 14 15\n0 1\n2 3\n'] })

t({ lv: 812, concept: 'Sparse Table: 区間OR', title: 'Sparse Tableの区間OR', tags: ['データ構造', 'bit演算'], io: '1行目に n q、2行目に n 個の非負整数、続く q 行に l r(0始まり両端含む)が与えられます。', ask: 'すべてのクエリの区間ビットORの合計を出力してください。', h1: 'ORは冪等なので Sparse Table が使える。', h2: '2ブロックの OR を取る。', ref: 'first=input().split()\nn=int(first[0])\nq=int(first[1])\na=list(map(int,input().split()))\nsp=[a[:]]\nk=1\nwhile (1<<k)<=n:\n    prev=sp[k-1]\n    cur=[]\n    for i in range(n-(1<<k)+1):\n        cur.append(prev[i]|prev[i+(1<<(k-1))])\n    sp.append(cur)\n    k+=1\ndef query(l,r):\n    j=(r-l+1).bit_length()-1\n    return sp[j][l]|sp[j][r-(1<<j)+1]\ntotal=0\nfor _ in range(q):\n    l,r=map(int,input().split())\n    total+=query(l,r)\nprint(total)', tip: 'ビットORも冪等なので Sparse Table に載る。区間ORが O(1) で求まる。', ins: ['5 2\n1 2 4 8 16\n0 4\n0 1\n', '3 1\n1 2 4\n0 2\n', '1 1\n5\n0 0\n', '4 2\n1 1 1 1\n0 3\n1 2\n', '5 1\n8 4 2 1 0\n0 3\n', '4 2\n3 5 9 1\n0 1\n2 3\n'] })

t({ lv: 813, concept: '単調デック: 窓の最小値の総和', title: '長さkの各窓の最小値の総和', tags: ['二ポインタ'], io: '1行目に k、2行目に整数列が与えられます。', ask: '長さ k の連続窓それぞれの最小値を求め、その総和を出力してください。', h1: '単調増加デックに添字を積む。', h2: '窓外の先頭を捨て、先頭が窓の最小。', ref: 'from collections import deque\nk=int(input())\na=list(map(int,input().split()))\nn=len(a)\ndq=deque()\ntotal=0\nfor i in range(n):\n    while dq and a[dq[-1]]>=a[i]:\n        dq.pop()\n    dq.append(i)\n    if dq[0]<=i-k:\n        dq.popleft()\n    if i>=k-1:\n        total+=a[dq[0]]\nprint(total)', tip: 'スライディングウィンドウ最小は単調増加デックで。最大版(lv797)の不等号を反転しただけ。', ins: ['3\n1 3 -1 -3 5 3 6 7\n', '1\n5 1 9\n', '2\n3 2 1\n', '3\n1 1 1\n', '2\n5 4 3\n', '4\n4 3 2 1\n'] })

t({ lv: 814, concept: '単調スタック: 部分配列の最小値の総和', title: '全部分配列の最小値の総和', tags: ['スタック'], io: '正整数列が1行で与えられます。', ask: 'すべての連続部分配列の最小値の総和を出力してください。', h1: '各要素が最小となる区間数を数える。', h2: '左に厳密に小さい・右に小さい以下の境界をスタックで。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nleft=[0]*n\nright=[0]*n\nstack=[]\nfor i in range(n):\n    while stack and a[stack[-1]]>a[i]:\n        stack.pop()\n    left[i]=i-(stack[-1] if stack else -1)\n    stack.append(i)\nstack=[]\nfor i in range(n-1,-1,-1):\n    while stack and a[stack[-1]]>=a[i]:\n        stack.pop()\n    right[i]=(stack[-1] if stack else n)-i\n    stack.append(i)\ntotal=0\nfor i in range(n):\n    total+=a[i]*left[i]*right[i]\nprint(total)', tip: '各要素 a[i] が最小となる部分配列数は「左右の境界の積」。同値の扱いを左右で非対称にして二重計上を防ぐ。', ins: ['3 1 2 4\n', '11 81 94 43 3\n', '5\n', '1 1 1\n', '2 3 4\n', '4 3 2 1\n'] })

t({ lv: 815, concept: '単調スタック: 部分配列の最大値の総和', title: '全部分配列の最大値の総和', tags: ['スタック'], io: '正整数列が1行で与えられます。', ask: 'すべての連続部分配列の最大値の総和を出力してください。', h1: '各要素が最大となる区間数を数える。', h2: '左右の境界をスタックで求め積を取る。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nleft=[0]*n\nright=[0]*n\nstack=[]\nfor i in range(n):\n    while stack and a[stack[-1]]<a[i]:\n        stack.pop()\n    left[i]=i-(stack[-1] if stack else -1)\n    stack.append(i)\nstack=[]\nfor i in range(n-1,-1,-1):\n    while stack and a[stack[-1]]<=a[i]:\n        stack.pop()\n    right[i]=(stack[-1] if stack else n)-i\n    stack.append(i)\ntotal=0\nfor i in range(n):\n    total+=a[i]*left[i]*right[i]\nprint(total)', tip: '最大値版は不等号を反転。各要素が最大となる部分配列数を左右境界の積で数える。', ins: ['3 1 2 4\n', '1 2 3\n', '5\n', '1 1 1\n', '4 3 2 1\n', '2 4 1 3\n'] })

t({ lv: 816, concept: '単調スタック: 部分配列の範囲の総和', title: '全部分配列の(最大-最小)の総和', tags: ['スタック'], io: '整数列が1行で与えられます。', ask: 'すべての連続部分配列について(最大値-最小値)を求め、その総和を出力してください。', h1: '最大値の総和-最小値の総和。', h2: '各要素が最大/最小となる区間数を別々に数える。', ref: 'a=list(map(int,input().split()))\nn=len(a)\ndef sum_with(cmp_pop_left,cmp_pop_right):\n    left=[0]*n\n    right=[0]*n\n    st=[]\n    for i in range(n):\n        while st and cmp_pop_left(a[st[-1]],a[i]):\n            st.pop()\n        left[i]=i-(st[-1] if st else -1)\n        st.append(i)\n    st=[]\n    for i in range(n-1,-1,-1):\n        while st and cmp_pop_right(a[st[-1]],a[i]):\n            st.pop()\n        right[i]=(st[-1] if st else n)-i\n        st.append(i)\n    return sum(a[i]*left[i]*right[i] for i in range(n))\nmax_sum=sum_with(lambda x,y:x<y,lambda x,y:x<=y)\nmin_sum=sum_with(lambda x,y:x>y,lambda x,y:x>=y)\nprint(max_sum-min_sum)', tip: '部分配列の範囲(max-min)の総和は「最大値の総和」と「最小値の総和」の差。各要素の寄与を境界の積で数える。', ins: ['1 2 3\n', '4 1 2 4\n', '5\n', '1 1 1\n', '3 1 2\n', '1 3 2 4\n'] })

t({ lv: 817, concept: 'Union-Find: 重み付き(パリティ)整合', title: '重み付きUnion-Findで矛盾検出', tags: ['データ構造'], io: '1行目に n m、続く m 行に "a b d"(a と b の差が d という制約)が与えられます。', ask: 'すべての制約が矛盾なく満たせるなら yes、矛盾するなら no を出力してください。', h1: '各頂点に親からの相対差(ポテンシャル)を持つ。', h2: '同じ根の2点は既知の差と一致するか確認。', ref: 'first=input().split()\nn=int(first[0])\nm=int(first[1])\npar=list(range(n+1))\nrank_w=[0]*(n+1)\ndef find(x):\n    if par[x]==x:\n        return x,0\n    root,w=find(par[x])\n    par[x]=root\n    rank_w[x]+=w\n    return root,rank_w[x]\nok=True\nfor _ in range(m):\n    a,b,d=map(int,input().split())\n    ra,wa=find(a)\n    rb,wb=find(b)\n    if ra==rb:\n        if wb-wa!=d:\n            ok=False\n    else:\n        par[ra]=rb\n        rank_w[ra]=wb-wa-d\nprint("yes" if ok else "no")', tip: '重み付きUnion-Findは「根からの相対値(ポテンシャル)」を持ち、同根の2点で既知の差と矛盾しないか検査する。', ins: ['3 3\n1 2 1\n2 3 1\n1 3 2\n', '3 3\n1 2 1\n2 3 1\n1 3 5\n', '2 1\n1 2 3\n', '1 0\n', '4 3\n1 2 1\n3 4 1\n1 3 0\n', '3 2\n1 2 5\n2 1 -5\n'] })

t({ lv: 818, concept: 'Union-Find: 余分な辺の数', title: '閉路を作る余分な辺の本数', tags: ['データ構造', 'グラフ'], io: '1行目に n m、続く m 行に無向辺 u v が与えられます。', ask: '辺を順に追加するとき、既に連結な2頂点を結ぶ(閉路を作る)辺の本数を出力してください。', h1: 'Union-Findで併合を試みる。', h2: '既に同じ根なら余分な辺。', ref: 'first=input().split()\nn=int(first[0])\nm=int(first[1])\npar=list(range(n+1))\ndef find(x):\n    while par[x]!=x:\n        par[x]=par[par[x]]\n        x=par[x]\n    return x\nextra=0\nfor _ in range(m):\n    u,v=map(int,input().split())\n    ru,rv=find(u),find(v)\n    if ru==rv:\n        extra+=1\n    else:\n        par[ru]=rv\nprint(extra)', tip: '余分な辺(閉路を作る辺)はUnion-Findで「両端が既に同じ根」の回数。全域森の補集合に相当する。', ins: ['3 3\n1 2\n2 3\n1 3\n', '4 3\n1 2\n2 3\n3 4\n', '3 2\n1 2\n1 2\n', '1 0\n', '5 5\n1 2\n2 3\n3 1\n4 5\n4 5\n', '4 4\n1 2\n2 3\n3 4\n1 4\n'] })

t({ lv: 819, concept: '区間: 被覆された総長', title: '区間を重ねて覆われた総長', tags: ['区間', 'ソート'], io: '1行目に n、続く n 行に区間 l r が与えられます。', ask: '区間の和集合が覆う長さの合計を出力してください。', h1: '左端でソートする。', h2: '重なりを統合して各塊の長さを足す。', ref: 'n=int(input())\nif n==0:\n    print(0)\nelse:\n    ivs=sorted(tuple(map(int,input().split())) for _ in range(n))\n    total=0\n    cl,cr=ivs[0]\n    for l,r in ivs[1:]:\n        if l<=cr:\n            cr=max(cr,r)\n        else:\n            total+=cr-cl\n            cl,cr=l,r\n    total+=cr-cl\n    print(total)', tip: '和集合の長さは左端ソートで重なりを統合し、各塊の (右-左) を足す。', ins: ['3\n1 3\n2 5\n7 9\n', '1\n0 10\n', '2\n1 2\n3 4\n', '3\n1 4\n2 3\n5 6\n', '2\n0 5\n0 5\n', '4\n1 2\n2 3\n3 4\n10 12\n'] })

t({ lv: 820, concept: 'オフライン: 区間内の相異なる数の総和', title: '各クエリ区間の相異なる要素数の総和', tags: ['データ構造'], io: '1行目に n q、2行目に n 個の値、続く q 行に l r(0始まり両端含む)が与えられます。', ask: '各クエリ区間内の相異なる値の種類数を求め、その総和を出力してください。', h1: '右端でクエリをソートする。', h2: '各値の最後の出現位置だけBITに残し、区間内の点数を数える。', ref: 'first=input().split()\nn=int(first[0])\nq=int(first[1])\na=list(map(int,input().split()))\nqueries=[]\nfor idx in range(q):\n    l,r=map(int,input().split())\n    queries.append((r,l,idx))\nqueries.sort()\nbit=[0]*(n+1)\ndef upd(i,x):\n    i+=1\n    while i<=n:\n        bit[i]+=x\n        i+=i&(-i)\ndef pre(i):\n    i+=1\n    s=0\n    while i>0:\n        s+=bit[i]\n        i-=i&(-i)\n    return s\nlast={}\nans=[0]*q\nptr=0\nfor r,l,idx in queries:\n    while ptr<=r:\n        v=a[ptr]\n        if v in last:\n            upd(last[v],-1)\n        upd(ptr,1)\n        last[v]=ptr\n        ptr+=1\n    ans[idx]=pre(r)-(pre(l-1) if l>0 else 0)\nprint(sum(ans))', tip: '区間の相異なる数はオフライン(右端ソート)＋BIT。各値の最終出現位置だけ1を立てる定石。', ins: ['5 2\n1 2 1 3 2\n0 4\n1 3\n', '3 1\n1 1 1\n0 2\n', '1 1\n5\n0 0\n', '4 2\n1 2 3 4\n0 3\n1 2\n', '5 1\n1 1 2 2 3\n0 4\n', '4 2\n2 2 2 2\n0 1\n2 3\n'] })

t({ lv: 821, concept: '座標圧縮: 順位の総和', title: '座標圧縮した順位の総和', tags: ['ソート'], io: '整数列が1行で与えられます。', ask: '各要素を「相異なる値の中で小さい方から何番目か(0始まり)」に置き換えた順位の総和を出力してください。', h1: '相異なる値をソートして順位を割る。', h2: '各要素の順位を足す。', ref: 'a=list(map(int,input().split()))\nvals=sorted(set(a))\nrank={v:i for i,v in enumerate(vals)}\nprint(sum(rank[x] for x in a))', tip: '座標圧縮は「相異なる値→順位」の辞書を作るだけ。大きな値域をBIT/セグ木に載せる前処理に必須。', ins: ['40 10 20 10\n', '5\n', '1 2 3\n', '3 3 3\n', '100 1 100 50\n', '7 7 8 9 8\n'] })

t({ lv: 822, concept: 'オイラーツアー: 部分木の和', title: '部分木への一点更新と部分木和', tags: ['データ構造', '木'], io: '1行目に n、2行目に各頂点の初期値(頂点1..n)、続く n-1 行に木の辺 u v(根は1)、次の行に q、続く q 行に "add x v"(頂点xにv加算) または "sub x"(xの部分木の和)が与えられます。', ask: 'すべての "sub" の結果の合計を出力してください。', h1: 'オイラーツアーで部分木を連続区間に対応づける。', h2: 'BITで一点加算・区間和。', ref: 'import sys\nsys.setrecursionlimit(500000)\nn=int(input())\nval=list(map(int,input().split()))\ng=[[] for _ in range(n+1)]\nfor _ in range(n-1):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\ntin=[0]*(n+1)\ntout=[0]*(n+1)\ntimer=[0]\nseen=[False]*(n+1)\nstack=[(1,False)]\nseen[1]=True\nwhile stack:\n    node,processed=stack.pop()\n    if processed:\n        tout[node]=timer[0]\n        continue\n    timer[0]+=1\n    tin[node]=timer[0]\n    stack.append((node,True))\n    for ch in g[node]:\n        if not seen[ch]:\n            seen[ch]=True\n            stack.append((ch,False))\ntout_fix=[0]*(n+1)\n# recompute tout as max tin in subtree via second pass not needed; use timer end\nbit=[0]*(n+2)\ndef upd(i,x):\n    while i<=n:\n        bit[i]+=x\n        i+=i&(-i)\ndef pre(i):\n    s=0\n    while i>0:\n        s+=bit[i]\n        i-=i&(-i)\n    return s\n# tout: largest tin among descendants. Recompute via order of tin\norder=sorted(range(1,n+1),key=lambda x:tin[x])\n# compute subtree max tin\nimport functools\nchildren=[[] for _ in range(n+1)]\nparent=[0]*(n+1)\nseen2=[False]*(n+1)\nst=[1]\nseen2[1]=True\nwhile st:\n    x=st.pop()\n    for y in g[x]:\n        if not seen2[y]:\n            seen2[y]=True\n            parent[y]=x\n            children[x].append(y)\n            st.append(y)\nsub_max=[0]*(n+1)\nfor x in sorted(range(1,n+1),key=lambda v:-tin[v]):\n    m=tin[x]\n    for c in children[x]:\n        if sub_max[c]>m:\n            m=sub_max[c]\n    sub_max[x]=m\nfor i in range(1,n+1):\n    upd(tin[i],val[i-1])\nq=int(input())\ntotal=0\nfor _ in range(q):\n    op=input().split()\n    if op[0]=="add":\n        x=int(op[1]);v=int(op[2])\n        upd(tin[x],v)\n    else:\n        x=int(op[1])\n        total+=pre(sub_max[x])-pre(tin[x]-1)\nprint(total)', tip: 'オイラーツアーで部分木を [tin, 部分木内の最大tin] の連続区間に写し、BITで部分木和を扱う。', ins: ['3\n1 2 3\n1 2\n1 3\n2\nsub 1\nsub 2\n', '1\n5\n1\nsub 1\n', '4\n1 1 1 1\n1 2\n2 3\n3 4\n1\nsub 2\n', '3\n1 2 3\n1 2\n2 3\n2\nadd 3 10\nsub 1\n', '5\n1 2 3 4 5\n1 2\n1 3\n2 4\n2 5\n1\nsub 2\n', '2\n7 8\n1 2\n1\nsub 1\n'] })

t({ lv: 823, concept: 'オフライン: 区間内の特定値の出現数の総和', title: '各クエリの値vの出現数の総和', tags: ['ハッシュ'], io: '1行目に n q、2行目に n 個の値、続く q 行に l r v(区間[l,r]内の値vの個数、0始まり両端含む)が与えられます。', ask: 'すべてのクエリの「区間内のvの出現数」の総和を出力してください。', h1: '各値の出現位置を昇順リストに保存。', h2: '二分探索で [l,r] に入る個数を数える。', ref: 'import bisect\nfirst=input().split()\nn=int(first[0])\nq=int(first[1])\na=list(map(int,input().split()))\nfrom collections import defaultdict\npos=defaultdict(list)\nfor i,x in enumerate(a):\n    pos[x].append(i)\ntotal=0\nfor _ in range(q):\n    l,r,v=map(int,input().split())\n    lst=pos.get(v,[])\n    cnt=bisect.bisect_right(lst,r)-bisect.bisect_left(lst,l)\n    total+=cnt\nprint(total)', tip: '区間内の特定値の数は「値ごとの出現位置リスト」に二分探索するのが定石(オフラインで前計算)。', ins: ['5 2\n1 2 1 3 1\n0 4 1\n1 3 1\n', '3 1\n5 5 5\n0 2 5\n', '1 1\n7\n0 0 7\n', '4 2\n1 2 3 4\n0 3 5\n0 3 2\n', '5 1\n2 2 3 2 3\n0 4 2\n', '4 2\n1 1 2 2\n0 1 1\n2 3 2\n'] })

t({ lv: 824, concept: 'オフライン: 区間内のk番目に小さい値(ソート)', title: '各クエリ区間のk番目に小さい値の総和', tags: ['データ構造'], io: '1行目に n q、2行目に n 個の値、続く q 行に l r k(区間[l,r]内でk番目に小さい値、0始まり両端含む)が与えられます。', ask: 'すべてのクエリの結果の合計を出力してください。', h1: '各区間をソートする(素朴解)。', h2: 'k 番目(1始まり)を取る。', ref: 'first=input().split()\nn=int(first[0])\nq=int(first[1])\na=list(map(int,input().split()))\ntotal=0\nfor _ in range(q):\n    l,r,k=map(int,input().split())\n    seg=sorted(a[l:r+1])\n    total+=seg[k-1]\nprint(total)', tip: '区間k番目は素朴にはソートだが、永続セグ木やマージソート木で O(log²) に高速化できる。', ins: ['5 2\n3 1 4 1 5\n0 4 2\n1 3 1\n', '3 1\n5 2 8\n0 2 3\n', '1 1\n7\n0 0 1\n', '4 2\n4 3 2 1\n0 3 1\n0 3 4\n', '5 1\n9 8 7 6 5\n1 4 2\n', '4 2\n1 2 3 4\n0 1 2\n2 3 1\n'] })

t({ lv: 825, concept: 'ヒープ: 遅延削除つき最小値', title: '遅延削除ヒープの最小値の総和', tags: ['ヒープ'], io: '1行目に q、続く q 行に "push x"・"pop x"(値xを1つ削除)・"min"(現在の最小値)が与えられます。', ask: 'すべての "min" の結果の合計を出力してください(空のときは無視)。', h1: '削除予定をカウンタで保持する。', h2: '最小取得時に削除済みの先頭を捨てる。', ref: 'import heapq\nfrom collections import defaultdict\nq=int(input())\nheap=[]\nremoved=defaultdict(int)\ntotal=0\nfor _ in range(q):\n    op=input().split()\n    if op[0]=="push":\n        heapq.heappush(heap,int(op[1]))\n    elif op[0]=="pop":\n        removed[int(op[1])]+=1\n    else:\n        while heap and removed[heap[0]]>0:\n            removed[heap[0]]-=1\n            heapq.heappop(heap)\n        if heap:\n            total+=heap[0]\nprint(total)', tip: '遅延削除ヒープは「削除予定カウンタ」を持ち、最小参照時に無効な先頭を捨てる。任意要素の削除を擬似的に実現。', ins: ['5\npush 3\npush 1\nmin\npop 1\nmin\n', '3\npush 5\nmin\nmin\n', '2\nmin\npush 1\n', '4\npush 2\npush 2\npop 2\nmin\n', '3\npush 10\npop 10\nmin\n', '6\npush 4\npush 2\npush 6\nmin\npop 2\nmin\n'] })

t({ lv: 826, concept: 'ヒープ: タスクスケジューラ', title: '同種タスクのクールダウン込み最短時間', tags: ['ヒープ', '貪欲'], io: '1行目にクールダウン n、2行目にタスク種別(英大文字)の文字列が与えられます。', ask: '同じ種別の間に n 単位以上空けてすべて実行する最短の総単位時間(アイドル含む)を出力してください。', h1: '最多種別の数 maxc とその個数を求める。', h2: '(maxc-1)·(n+1)+同数の種別数 と 全体長 の大きい方。', ref: 'from collections import Counter\nn=int(input())\ntasks=input()\ncnt=Counter(tasks)\nif not cnt:\n    print(0)\nelse:\n    maxc=max(cnt.values())\n    num_max=sum(1 for v in cnt.values() if v==maxc)\n    formula=(maxc-1)*(n+1)+num_max\n    print(max(formula,len(tasks)))', tip: 'タスクスケジューラは「最多タスクで骨組みを作る」貪欲。公式 (maxc-1)(n+1)+同数種別数 と総数の大きい方。', ins: ['2\nAAABBB\n', '0\nAAABBB\n', '2\nA\n', '2\nABCDEF\n', '2\nAAABBBCCC\n', '1\nAABB\n'] })

t({ lv: 827, concept: 'ヒープ: ストリームのk番目に大きい値', title: '逐次追加でのk番目に大きい値の総和', tags: ['ヒープ'], io: '1行目に k、2行目に整数列(順に追加)が与えられます。', ask: '各要素を追加するたびに、それまでの中で k 番目に大きい値を求め(要素がk未満のときは無視)、その総和を出力してください。', h1: 'サイズkの最小ヒープを保つ。', h2: 'ヒープの先頭が k 番目に大きい値。', ref: 'import heapq\nk=int(input())\na=list(map(int,input().split()))\nheap=[]\ntotal=0\nfor x in a:\n    heapq.heappush(heap,x)\n    if len(heap)>k:\n        heapq.heappop(heap)\n    if len(heap)==k:\n        total+=heap[0]\nprint(total)', tip: 'k番目に大きい値はサイズkの最小ヒープで管理。先頭が常にk番目になる(超過したらpop)。', ins: ['3\n4 5 8 2 3 5 10 9 4\n', '1\n1 2 3\n', '2\n5 5 5\n', '3\n1 2\n', '1\n9 8 7\n', '2\n1 2 3 4\n'] })

t({ lv: 828, concept: 'ヒープ: 上位k頻度要素の和', title: '出現頻度上位kの要素の合計', tags: ['ヒープ', 'ハッシュ'], io: '1行目に k、2行目に整数列が与えられます。', ask: '出現頻度の高い順に上位 k 種類の値の合計(値そのものの和)を出力してください(頻度同点は値の小さい方を優先)。', h1: '頻度を集計する。', h2: '(頻度降順, 値昇順)で上位kを取る。', ref: 'from collections import Counter\nk=int(input())\na=list(map(int,input().split()))\ncnt=Counter(a)\nitems=sorted(cnt.items(),key=lambda x:(-x[1],x[0]))\nprint(sum(v for v,c in items[:k]))', tip: '上位k頻度は (頻度降順, 値昇順) でソートして先頭kを取る。大規模ではサイズkのヒープで O(n log k)。', ins: ['2\n1 1 1 2 2 3\n', '1\n5\n', '3\n1 2 3\n', '2\n4 4 5 5 6\n', '1\n7 7 8\n', '2\n1 1 2 2 3 3\n'] })

t({ lv: 829, concept: '単調スタック: 次に小さい要素', title: '各要素の次に小さい要素', tags: ['スタック'], io: '整数列が1行で与えられます。', ask: '各要素について、その右側で最初に出る小さい要素を並べて出力してください(無ければ -1)。', h1: '増加スタックに添字を積む。', h2: '今の値より大きい先頭を解決して答えを埋める。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nres=[-1]*n\nstack=[]\nfor i in range(n):\n    while stack and a[stack[-1]]>a[i]:\n        res[stack.pop()]=a[i]\n    stack.append(i)\nprint(*res)', tip: '「次に小さい要素」は単調増加スタックで。次に大きい要素(lv529)の不等号を反転しただけ。', ins: ['4 2 1 5 3\n', '1 2 3\n', '3 2 1\n', '5\n', '2 1 2 4 3\n', '5 5 5\n'] })

t({ lv: 830, concept: '単調スタック: 前に大きい要素の数', title: '各要素より前にある大きい要素までの距離の総和', tags: ['スタック'], io: '整数列が1行で与えられます。', ask: '各要素について「左側で最初に自分より大きい要素までの距離」を求め、その総和を出力してください(無ければ自分の位置+1)。', h1: '減少スタックに添字を積む。', h2: '自分以下の先頭を捨て、残った先頭との距離。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nstack=[]\ntotal=0\nfor i in range(n):\n    while stack and a[stack[-1]]<=a[i]:\n        stack.pop()\n    prev=stack[-1] if stack else -1\n    total+=i-prev\n    stack.append(i)\nprint(total)', tip: '「左で最初に大きい要素までの距離」は株価スパンの双対。単調減少スタックで O(n)。', ins: ['3 1 4 1 5\n', '5 4 3 2 1\n', '1 2 3 4\n', '5\n', '3 3 3\n', '10 1 10 1\n'] })

t({ lv: 831, concept: 'セグ木: 最大部分配列和(単一クエリ)', title: 'セグ木で最大連続部分和', tags: ['データ構造', 'dp'], io: '整数列が1行で与えられます。', ask: '空でない連続部分配列の和の最大値を、区間マージ可能な構造(全体和・接頭最大・接尾最大・最大部分和)で求めて出力してください。', h1: '各ノードに total/pre/suf/best を持つ。', h2: 'マージは pre=max(左pre,左total+右pre) など。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nNEG=float("-inf")\ndef make(x):\n    return (x,x,x,x)\ndef merge(L,R):\n    lt,lp,ls,lb=L\n    rt,rp,rs,rb=R\n    total=lt+rt\n    pre=max(lp,lt+rp)\n    suf=max(rs,rt+ls)\n    best=max(lb,rb,ls+rp)\n    return (total,pre,suf,best)\nnode=make(a[0])\nfor i in range(1,n):\n    node=merge(node,make(a[i]))\nprint(node[3])', tip: '最大部分和は(全体和・接頭最大・接尾最大・最大部分和)の4値をマージできる。セグ木のGSS問題の核。', ins: ['-2 1 -3 4 -1 2 1 -5 4\n', '1 2 3\n', '-1 -2 -3\n', '5\n', '-5\n', '3 -2 5 -1\n'] })

t({ lv: 832, concept: 'セグ木上の二分探索: 接頭和が初めてx以上', title: '接頭和が初めてx以上になる位置', tags: ['データ構造', '二分探索'], io: '1行目に x、2行目に非負整数列が与えられます。', ask: '先頭からの累積和が初めて x 以上になる位置(0始まり)を出力してください。最後まで届かなければ -1。', h1: '累積和を作る。', h2: '二分探索で最小の位置を探す(セグ木上の二分降下の代用)。', ref: 'import bisect\nx=int(input())\na=list(map(int,input().split()))\npre=[0]\nfor v in a:\n    pre.append(pre[-1]+v)\nidx=bisect.bisect_left(pre,x,1)\nif idx<=len(a):\n    print(idx-1)\nelse:\n    print(-1)', tip: 'セグ木上の二分探索は「接頭和が閾値を超える最左」を O(log n) で。非負なら累積和＋二分探索で代用できる。', ins: ['7\n1 2 3 4 5\n', '100\n1 2 3\n', '1\n0 0 1\n', '5\n5\n', '0\n3 1\n', '6\n2 2 2 2\n'] })

t({ lv: 833, concept: 'オフライン: 区間和が範囲内のクエリ数', title: '区間和が[lo,hi]に入る部分配列の数', tags: ['ソート'], io: '1行目に lo hi、2行目に整数列が与えられます。', ask: '連続部分配列の和が lo 以上 hi 以下になるものの個数を出力してください。', h1: '累積和 pre を作る。', h2: 'pre[j]-pre[i] が [lo,hi] となる i<j を分割統治/全探索で数える。', ref: 'first=input().split()\nlo=int(first[0])\nhi=int(first[1])\na=list(map(int,input().split()))\nn=len(a)\npre=[0]*(n+1)\nfor i in range(n):\n    pre[i+1]=pre[i]+a[i]\ncnt=0\nfor j in range(1,n+1):\n    for i in range(j):\n        s=pre[j]-pre[i]\n        if lo<=s<=hi:\n            cnt+=1\nprint(cnt)', tip: '区間和が範囲内の数は累積和の差。大規模ではマージソートやBITで O(n log n) に落とせる。', ins: ['2 5\n1 2 3\n', '0 0\n1 -1 1 -1\n', '5 5\n5\n', '1 3\n1 1 1\n', '10 100\n1 2 3\n', '-1 1\n2 -2 2\n'] })

t({ lv: 834, concept: '2次元いもす法: 矩形加算後の最大', title: '矩形加算を重ねた最大値', tags: ['累積和'], io: '1行目に R C q、続く q 行に r1 c1 r2 c2 v(矩形[r1,r2]×[c1,c2]にv加算、0始まり両端含む)が与えられます。', ask: 'すべての加算後の格子の最大値を出力してください。', h1: '差分の4隅に +v,-v を置く。', h2: '2次元累積和で復元し最大を取る。', ref: 'first=input().split()\nR=int(first[0])\nC=int(first[1])\nq=int(first[2])\ndiff=[[0]*(C+1) for _ in range(R+1)]\nfor _ in range(q):\n    r1,c1,r2,c2,v=map(int,input().split())\n    diff[r1][c1]+=v\n    diff[r2+1][c1]-=v\n    diff[r1][c2+1]-=v\n    diff[r2+1][c2+1]+=v\nbest=0\nfor i in range(R):\n    for j in range(C):\n        if i>0:\n            diff[i][j]+=diff[i-1][j]\n        if j>0:\n            diff[i][j]+=diff[i][j-1]\n        if i>0 and j>0:\n            diff[i][j]-=diff[i-1][j-1]\n        if diff[i][j]>best:\n            best=diff[i][j]\nprint(best)', tip: '2次元いもす法は矩形加算を4隅の差分で表し、2次元累積和で一括復元する O(RC+q)。', ins: ['3 3 2\n0 0 1 1 1\n1 1 2 2 2\n', '2 2 1\n0 0 1 1 5\n', '1 1 1\n0 0 0 0 7\n', '3 3 1\n0 0 2 2 1\n', '2 3 2\n0 0 0 2 1\n1 0 1 0 10\n', '2 2 0\n'] })

t({ lv: 835, concept: 'BIT: 自分より前の大きい要素数の総和', title: '左側にある大きい要素数の総和', tags: ['データ構造'], io: '整数列が1行で与えられます。', ask: '各要素について「自分より左にある自分より大きい要素の数」を求め、その総和を出力してください。', h1: '座標圧縮してBITで数える。', h2: '左から見て、自分より大きい既出数 = 既出総数 - 自分以下の数。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nvals=sorted(set(a))\nrank={v:i+1 for i,v in enumerate(vals)}\nm=len(vals)\nbit=[0]*(m+1)\ndef upd(i):\n    while i<=m:\n        bit[i]+=1\n        i+=i&(-i)\ndef pre(i):\n    s=0\n    while i>0:\n        s+=bit[i]\n        i-=i&(-i)\n    return s\ntotal=0\nseen=0\nfor x in a:\n    r=rank[x]\n    le=pre(r)\n    total+=seen-le\n    upd(r)\n    seen+=1\nprint(total)', tip: '「左の大きい要素数」はBITで左から走査し「既出総数 - 自分以下の既出数」を足す。右の小さい数(lv770)の対称。', ins: ['1 2 3\n', '3 2 1\n', '5\n', '1 1 1\n', '2 4 1 3\n', '5 4 3 2 1\n'] })

t({ lv: 836, concept: 'ヒープ: 連続最小コスト併合', title: '配列を1つに併合する最小コスト(隣接以外)', tags: ['ヒープ', '貪欲'], io: '正整数列が1行で与えられます(任意の2要素を選んで併合、コストは和、結果を戻す)。', ask: 'すべてを1つに併合する最小総コストを出力してください。', h1: '常に最小の2つを選んで併合する。', h2: '最小ヒープで取り出し、和を戻す。', ref: 'import heapq\na=list(map(int,input().split()))\nif len(a)<=1:\n    print(0)\nelse:\n    heapq.heapify(a)\n    total=0\n    while len(a)>1:\n        x=heapq.heappop(a)\n        y=heapq.heappop(a)\n        total+=x+y\n        heapq.heappush(a,x+y)\n    print(total)', tip: '任意2要素の最小併合コストは「最小2つを選び続ける」ヒープ貪欲。ハフマンと同じ構造だが入力は頻度でなく値。', ins: ['1 2 3 4\n', '5\n', '1 1 1 1\n', '2 3\n', '4 3 2 6\n', '10 20 30\n'] })

t({ lv: 837, concept: 'マルチセット: 中央値の差の総和', title: '配列をk分割した各中央値の…(固定窓の中央値の総和)', tags: ['ソート'], io: '1行目に窓幅 k(奇数)、2行目に整数列が与えられます。', ask: '長さ k の各連続窓の中央値を求め、その総和を出力してください(k は奇数)。', h1: '各窓をソートして中央を取る(素朴解)。', h2: '中央 = ソート後の k//2 番目。', ref: 'k=int(input())\na=list(map(int,input().split()))\nn=len(a)\ntotal=0\nfor i in range(n-k+1):\n    w=sorted(a[i:i+k])\n    total+=w[k//2]\nprint(total)', tip: '窓中央値は素朴にはソート。高速化には2つのヒープやマルチセット(平衡木)で O(n log k)。', ins: ['3\n1 3 -1 -3 5 3 6 7\n', '1\n5 2 8\n', '3\n1 2 3\n', '3\n5 5 5\n', '5\n1 2 3 4 5\n', '3\n9 1 5 3 7\n'] })

t({ lv: 838, concept: 'セグ木: 区間代入区間和', title: '区間代入と区間和(遅延伝播)', tags: ['データ構造'], io: '1行目に n q、2行目に n 個の値、続く q 行に "set l r v" または "sum l r"(0始まり両端含む)が与えられます。', ask: 'すべての "sum" の結果の合計を出力してください。', h1: '代入の遅延値を持つ(未設定はNone)。', h2: 'push で子へ代入を伝え、区間和を更新する。', ref: 'first=input().split()\nn=int(first[0])\nq=int(first[1])\na=list(map(int,input().split()))\nsize=1\nwhile size<n:\n    size*=2\nsm=[0]*(2*size)\nln=[0]*(2*size)\nlz=[None]*(2*size)\nfor i in range(size):\n    ln[size+i]=1\nfor i in range(n):\n    sm[size+i]=a[i]\nfor i in range(size-1,0,-1):\n    sm[i]=sm[2*i]+sm[2*i+1]\n    ln[i]=ln[2*i]+ln[2*i+1]\ndef apply(node,v):\n    sm[node]=v*ln[node]\n    lz[node]=v\ndef push(node):\n    if lz[node] is not None:\n        apply(2*node,lz[node])\n        apply(2*node+1,lz[node])\n        lz[node]=None\ndef setr(node,nl,nr,l,r,v):\n    if r<nl or nr<l:\n        return\n    if l<=nl and nr<=r:\n        apply(node,v)\n        return\n    push(node)\n    mid=(nl+nr)//2\n    setr(2*node,nl,mid,l,r,v)\n    setr(2*node+1,mid+1,nr,l,r,v)\n    sm[node]=sm[2*node]+sm[2*node+1]\ndef qsum(node,nl,nr,l,r):\n    if r<nl or nr<l:\n        return 0\n    if l<=nl and nr<=r:\n        return sm[node]\n    push(node)\n    mid=(nl+nr)//2\n    return qsum(2*node,nl,mid,l,r)+qsum(2*node+1,mid+1,nr,l,r)\ntotal=0\nfor _ in range(q):\n    op=input().split()\n    if op[0]=="set":\n        setr(1,0,size-1,int(op[1]),int(op[2]),int(op[3]))\n    else:\n        total+=qsum(1,0,size-1,int(op[1]),int(op[2]))\nprint(total)', tip: '区間代入＋区間和は遅延伝播の典型。代入は加算と違い「上書き」なので遅延値はそのまま置き換える。', ins: ['5 3\n1 2 3 4 5\nset 0 2 0\nsum 0 4\nsum 0 2\n', '3 1\n1 1 1\nsum 0 2\n', '1 2\n5\nset 0 0 3\nsum 0 0\n', '4 2\n1 2 3 4\nset 1 2 5\nsum 0 3\n', '5 1\n2 2 2 2 2\nsum 0 4\n', '4 3\n1 1 1 1\nset 0 3 2\nset 0 1 5\nsum 0 3\n'] })

t({ lv: 839, concept: 'DSU: 隣接行列の連結成分数', title: '友達関係(隣接行列)の連結成分数', tags: ['データ構造', 'グラフ'], io: '1行目に n、続く n 行に n×n の 0/1 隣接行列(対称)が与えられます。', ask: '連結成分(友達グループ)の数を出力してください。', h1: '行列の1の位置で併合する。', h2: 'Union-Find後の根の種類数。', ref: 'n=int(input())\nmat=[list(map(int,input().split())) for _ in range(n)]\npar=list(range(n))\ndef find(x):\n    while par[x]!=x:\n        par[x]=par[par[x]]\n        x=par[x]\n    return x\nfor i in range(n):\n    for j in range(i+1,n):\n        if mat[i][j]==1:\n            par[find(i)]=find(j)\nprint(len(set(find(i) for i in range(n))))', tip: '隣接行列入力の連結成分はUnion-Find。行列の上三角の1だけ見れば対称性で十分。', ins: ['3\n1 1 0\n1 1 0\n0 0 1\n', '1\n1\n', '3\n1 0 0\n0 1 0\n0 0 1\n', '4\n1 1 0 0\n1 1 1 0\n0 1 1 0\n0 0 0 1\n', '2\n1 1\n1 1\n', '3\n1 1 1\n1 1 1\n1 1 1\n'] })

t({ lv: 840, concept: 'セグ木: 区間内の最大値の位置', title: '区間最大とその最左位置', tags: ['データ構造'], io: '1行目に n q、2行目に n 個の値、続く q 行に l r(0始まり両端含む)が与えられます。', ask: '各クエリ区間の最大値が最初に現れる位置(0始まり)を求め、その位置の総和を出力してください。', h1: '区間最大は素朴/Sparse Tableで。', h2: '最大値の最左位置を線形に特定する。', ref: 'first=input().split()\nn=int(first[0])\nq=int(first[1])\na=list(map(int,input().split()))\ntotal=0\nfor _ in range(q):\n    l,r=map(int,input().split())\n    mx=max(a[l:r+1])\n    for i in range(l,r+1):\n        if a[i]==mx:\n            total+=i\n            break\nprint(total)', tip: '最大値の位置クエリはセグ木に「(最大値,位置)」を載せると O(log n)。ここでは素朴に最左を線形探索。', ins: ['5 2\n1 3 2 3 1\n0 4\n2 4\n', '3 1\n5 5 5\n0 2\n', '1 1\n7\n0 0\n', '4 2\n4 1 2 3\n0 3\n1 3\n', '5 1\n1 2 3 4 5\n0 4\n', '4 2\n3 1 3 1\n0 1\n2 3\n'] })

t({ lv: 841, concept: 'オフライン: しきい値以上の要素数(BIT)', title: '各クエリで値v以上の要素数の総和', tags: ['データ構造'], io: '1行目に n q、2行目に n 個の値、続く q 行に v(配列全体で v 以上の要素数)が与えられます。', ask: 'すべてのクエリの結果の合計を出力してください。', h1: 'ソートして二分探索する。', h2: 'v 以上の個数 = n - (v 未満の個数)。', ref: 'import bisect\nfirst=input().split()\nn=int(first[0])\nq=int(first[1])\na=sorted(map(int,input().split()))\ntotal=0\nfor _ in range(q):\n    v=int(input())\n    cnt=n-bisect.bisect_left(a,v)\n    total+=cnt\nprint(total)', tip: '「v以上の個数」はソート＋二分探索で O(log n)。動的更新があるならBITに載せる。', ins: ['5 2\n1 2 3 4 5\n3\n6\n', '3 1\n1 1 1\n1\n', '1 1\n5\n5\n', '4 2\n10 20 30 40\n25\n5\n', '5 1\n5 4 3 2 1\n3\n', '3 3\n1 2 3\n1\n2\n4\n'] })

t({ lv: 842, concept: 'セグ木: 区間XOR一点更新', title: '一点更新と区間XOR(セグメント木)', tags: ['データ構造', 'bit演算'], io: '1行目に n q、2行目に n 個の非負整数、続く q 行に "upd i x" または "xor l r"(0始まり両端含む)が与えられます。', ask: 'すべての "xor" の結果の合計を出力してください。', h1: '集約を XOR にする。', h2: '単位元は0、結合的なのでセグ木に載る。', ref: 'first=input().split()\nn=int(first[0])\nq=int(first[1])\na=list(map(int,input().split()))\nsize=1\nwhile size<n:\n    size*=2\ntree=[0]*(2*size)\nfor i in range(n):\n    tree[size+i]=a[i]\nfor i in range(size-1,0,-1):\n    tree[i]=tree[2*i]^tree[2*i+1]\ndef update(pos,val):\n    pos+=size\n    tree[pos]=val\n    pos//=2\n    while pos>=1:\n        tree[pos]=tree[2*pos]^tree[2*pos+1]\n        pos//=2\ndef query(l,r):\n    l+=size\n    r+=size+1\n    res=0\n    while l<r:\n        if l&1:\n            res^=tree[l]\n            l+=1\n        if r&1:\n            r-=1\n            res^=tree[r]\n        l//=2\n        r//=2\n    return res\ntotal=0\nfor _ in range(q):\n    op=input().split()\n    if op[0]=="upd":\n        update(int(op[1]),int(op[2]))\n    else:\n        total+=query(int(op[1]),int(op[2]))\nprint(total)', tip: 'XORは結合的で単位元0なのでセグ木に載る。区間XOR・一点更新ともO(log n)。', ins: ['5 3\n1 2 3 4 5\nxor 0 4\nupd 0 0\nxor 0 2\n', '3 1\n1 2 3\nxor 0 2\n', '1 1\n7\nxor 0 0\n', '4 2\n1 1 1 1\nxor 0 3\nxor 0 1\n', '5 1\n5 4 3 2 1\nxor 1 3\n', '4 2\n8 4 2 1\nupd 1 0\nxor 0 3\n'] })

t({ lv: 843, concept: '単調デック: 窓内の最大最小差の最大', title: '長さkの各窓の(最大-最小)の最大', tags: ['二ポインタ'], io: '1行目に k、2行目に整数列が与えられます。', ask: '長さ k の各連続窓について(最大-最小)を求め、その最大値を出力してください。', h1: '最大用と最小用の単調デックを使う。', h2: '各窓の最大-最小を比べる。', ref: 'from collections import deque\nk=int(input())\na=list(map(int,input().split()))\nn=len(a)\nmaxd=deque()\nmind=deque()\nbest=0\nfor i in range(n):\n    while maxd and a[maxd[-1]]<=a[i]:\n        maxd.pop()\n    maxd.append(i)\n    while mind and a[mind[-1]]>=a[i]:\n        mind.pop()\n    mind.append(i)\n    if maxd[0]<=i-k:\n        maxd.popleft()\n    if mind[0]<=i-k:\n        mind.popleft()\n    if i>=k-1:\n        diff=a[maxd[0]]-a[mind[0]]\n        if diff>best:\n            best=diff\nprint(best)', tip: '窓の最大と最小を別々の単調デックで同時に追えば、各窓の極差が O(1) で求まる。', ins: ['3\n1 3 6 2 5 4\n', '1\n5 2 8\n', '2\n1 1 1\n', '4\n4 3 2 1\n', '3\n5 5 5\n', '2\n1 10 1 10\n'] })

t({ lv: 844, concept: 'BIT: 接尾辞の小さい要素数の総和', title: '各要素の左にある小さい要素数の総和', tags: ['データ構造'], io: '整数列が1行で与えられます。', ask: '各要素について「自分より左にある自分未満の要素の数」を求め、その総和を出力してください。', h1: '座標圧縮してBITで数える。', h2: '左から見て自分未満の既出数を足す。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nvals=sorted(set(a))\nrank={v:i+1 for i,v in enumerate(vals)}\nm=len(vals)\nbit=[0]*(m+1)\ndef upd(i):\n    while i<=m:\n        bit[i]+=1\n        i+=i&(-i)\ndef pre(i):\n    s=0\n    while i>0:\n        s+=bit[i]\n        i-=i&(-i)\n    return s\ntotal=0\nfor x in a:\n    r=rank[x]\n    total+=pre(r-1)\n    upd(r)\nprint(total)', tip: '「左の小さい要素数」の総和はBITで左から走査し、自分未満の既出数を足す(右の小さい数lv770の左版)。', ins: ['1 2 3\n', '3 2 1\n', '5\n', '1 1 1\n', '2 4 1 3\n', '1 2 1 2\n'] })

t({ lv: 845, concept: 'セグ木: 区間内の0の数', title: '区間内の0の個数(セグ木一点更新)', tags: ['データ構造'], io: '1行目に n q、2行目に n 個の 0/1、続く q 行に "flip i"(0と1を反転) または "cnt l r"(区間内の0の数、0始まり両端含む)が与えられます。', ask: 'すべての "cnt" の結果の合計を出力してください。', h1: '各葉に「0なら1」を入れて和を取る。', h2: 'flip は値を1-値にして更新。', ref: 'first=input().split()\nn=int(first[0])\nq=int(first[1])\na=list(map(int,input().split()))\nzero=[1-x for x in a]\nsize=1\nwhile size<n:\n    size*=2\ntree=[0]*(2*size)\nfor i in range(n):\n    tree[size+i]=zero[i]\nfor i in range(size-1,0,-1):\n    tree[i]=tree[2*i]+tree[2*i+1]\ndef update(pos,val):\n    pos+=size\n    tree[pos]=val\n    pos//=2\n    while pos>=1:\n        tree[pos]=tree[2*pos]+tree[2*pos+1]\n        pos//=2\ndef query(l,r):\n    l+=size\n    r+=size+1\n    res=0\n    while l<r:\n        if l&1:\n            res+=tree[l]\n            l+=1\n        if r&1:\n            r-=1\n            res+=tree[r]\n        l//=2\n        r//=2\n    return res\ntotal=0\nfor _ in range(q):\n    op=input().split()\n    if op[0]=="flip":\n        i=int(op[1])\n        a[i]^=1\n        update(i,1-a[i])\n    else:\n        total+=query(int(op[1]),int(op[2]))\nprint(total)', tip: '「0の数」は「0なら1」を載せた和のセグ木で扱える。反転は値を1-値に更新するだけ。', ins: ['5 3\n1 0 1 0 1\ncnt 0 4\nflip 0\ncnt 0 2\n', '3 1\n0 0 0\ncnt 0 2\n', '1 1\n1\ncnt 0 0\n', '4 2\n1 1 1 1\ncnt 0 3\nflip 0\n', '5 1\n0 1 0 1 0\ncnt 1 3\n', '4 2\n0 0 1 1\ncnt 0 3\ncnt 2 3\n'] })

t({ lv: 846, concept: 'オフライン: 累積和の最大接尾', title: '各接尾辞の最大和の総和', tags: ['dp'], io: '整数列が1行で与えられます。', ask: '各開始位置 i について「i から始まる連続部分配列の最大和」を求め、その総和を出力してください。', h1: '右から累積最大を持つ。', h2: 'suf[i]=a[i]+max(0,suf[i+1])。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nif n==0:\n    print(0)\nelse:\n    suf=[0]*n\n    suf[n-1]=a[n-1]\n    for i in range(n-2,-1,-1):\n        suf[i]=a[i]+max(0,suf[i+1])\n    print(sum(suf))', tip: '各開始位置の最大和は右から「a[i]+max(0,次)」で O(n)。Kadaneの開始位置別バージョン。', ins: ['1 -2 3\n', '1 2 3\n', '-1 -2 -3\n', '5\n', '3 -1 2\n', '-5 4 -1\n'] })

t({ lv: 847, concept: 'セグ木: 区間最小の更新回数', title: '区間最小を素朴に求めた総和', tags: ['データ構造'], io: '1行目に n q、2行目に n 個の値、続く q 行に "upd i x" または "min l r"(0始まり両端含む)が与えられます。', ask: 'すべての "min" の結果の合計を出力してください。', h1: '集約を min、単位元を +inf にする。', h2: '一点更新・区間最小ともO(log n)。', ref: 'first=input().split()\nn=int(first[0])\nq=int(first[1])\na=list(map(int,input().split()))\nINF=float("inf")\nsize=1\nwhile size<n:\n    size*=2\ntree=[INF]*(2*size)\nfor i in range(n):\n    tree[size+i]=a[i]\nfor i in range(size-1,0,-1):\n    tree[i]=min(tree[2*i],tree[2*i+1])\ndef update(pos,val):\n    pos+=size\n    tree[pos]=val\n    pos//=2\n    while pos>=1:\n        tree[pos]=min(tree[2*pos],tree[2*pos+1])\n        pos//=2\ndef query(l,r):\n    l+=size\n    r+=size+1\n    res=INF\n    while l<r:\n        if l&1:\n            res=min(res,tree[l])\n            l+=1\n        if r&1:\n            r-=1\n            res=min(res,tree[r])\n        l//=2\n        r//=2\n    return res\ntotal=0\nfor _ in range(q):\n    op=input().split()\n    if op[0]=="upd":\n        update(int(op[1]),int(op[2]))\n    else:\n        total+=query(int(op[1]),int(op[2]))\nprint(total)', tip: '区間最小のセグ木は集約を min、単位元を +inf に。最大版(lv802)の対称形。', ins: ['5 3\n5 1 4 2 3\nmin 0 4\nupd 1 10\nmin 0 2\n', '3 1\n3 2 1\nmin 0 2\n', '1 1\n7\nmin 0 0\n', '4 2\n4 3 2 1\nmin 0 1\nupd 3 0\nmin 0 3\n', '5 1\n1 2 3 4 5\nmin 1 3\n', '4 2\n2 2 2 2\nmin 0 3\nmin 1 2\n'] })

t({ lv: 848, concept: 'セグ木: 区間が非減少に並んでいるか', title: '更新のたびに区間がソート済みか調べる', tags: ['データ構造'], io: '1行目に n q、2行目に n 個の値、続く q 行に "set i x"(i 番目を x にする) または "ask l r"(区間が非減少に並んでいるか、0始まり両端含む)が与えられます。', ask: 'すべての "ask" のうち、区間が非減少に並んでいるものの個数を出力してください。', h1: '各ノードに(左端の値, 右端の値, 非減少か)の3つ組を持つ。', h2: '左右をつなぐときは、左の右端が右の左端以下かどうかも確かめる。', ref: 'first=input().split()\nn=int(first[0])\nq=int(first[1])\na=list(map(int,input().split()))\nsize=1\nwhile size<n:\n    size*=2\ntree=[None]*(2*size)\ndef merge(x,y):\n    if x is None:\n        return y\n    if y is None:\n        return x\n    return (x[0],y[1],x[2] and y[2] and x[1]<=y[0])\nfor i in range(n):\n    tree[size+i]=(a[i],a[i],True)\nfor i in range(size-1,0,-1):\n    tree[i]=merge(tree[2*i],tree[2*i+1])\ndef update(i,val):\n    p=size+i\n    tree[p]=(val,val,True)\n    p//=2\n    while p>=1:\n        tree[p]=merge(tree[2*p],tree[2*p+1])\n        p//=2\ndef query(l,r):\n    resl=None\n    resr=None\n    l+=size\n    r+=size+1\n    while l<r:\n        if l&1:\n            resl=merge(resl,tree[l])\n            l+=1\n        if r&1:\n            r-=1\n            resr=merge(tree[r],resr)\n        l//=2\n        r//=2\n    return merge(resl,resr)\ncnt=0\nfor _ in range(q):\n    op=input().split()\n    if op[0]=="set":\n        update(int(op[1]),int(op[2]))\n    else:\n        res=query(int(op[1]),int(op[2]))\n        if res is not None and res[2]:\n            cnt+=1\nprint(cnt)', tip: '「ソート済みか」は(左端, 右端, 判定)の3つ組にすると結合できる情報になる。左右の子が両方ソート済みでも境目で逆転していれば全体は崩れるので、境界の比較が結合の要になる。', ins: ['5 4\n1 2 3 2 5\nask 0 2\nask 0 4\nset 3 4\nask 0 4\n', '1 1\n7\nask 0 0\n', '4 3\n4 3 2 1\nask 0 3\nask 2 2\nask 1 2\n', '6 3\n1 1 1 1 1 1\nask 0 5\nask 2 4\nask 0 0\n', '5 5\n5 4 3 2 1\nset 0 1\nask 0 1\nset 1 2\nask 0 4\nask 3 4\n', '3 4\n2 2 1\nask 0 1\nask 1 2\nset 2 5\nask 0 2\n'] })

t({ lv: 849, concept: 'オフライン: ソートクエリの区間和(累積)', title: '値の昇順クエリでの上位和', tags: ['ソート', '累積和'], io: '1行目に n q、2行目に n 個の値、続く q 行に t(値が t 以上の要素の合計)が与えられます。', ask: 'すべてのクエリの結果の合計を出力してください。', h1: '値を降順ソートし接尾辞和を作る。', h2: '各クエリは二分探索で境界を求め合計を引く。', ref: 'import bisect\nfirst=input().split()\nn=int(first[0])\nq=int(first[1])\na=sorted(map(int,input().split()))\npre=[0]*(n+1)\nfor i in range(n):\n    pre[i+1]=pre[i]+a[i]\ntotal=0\nfor _ in range(q):\n    t=int(input())\n    idx=bisect.bisect_left(a,t)\n    s=pre[n]-pre[idx]\n    total+=s\nprint(total)', tip: '「t以上の要素の和」はソート＋接尾辞和＋二分探索で O(log n)。境界位置から先の累積和を取る。', ins: ['5 2\n1 2 3 4 5\n3\n1\n', '3 1\n1 1 1\n1\n', '1 1\n5\n10\n', '4 2\n10 20 30 40\n25\n5\n', '5 1\n5 4 3 2 1\n3\n', '3 3\n1 2 3\n1\n2\n4\n'] })

export const CATALOG = TASKS
