// 生成タスク 第19波：上級の競技プログラミング技法。整数=採点一意。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 500, concept: 'CP: 最長非減少部分列', title: '最長非減少部分列の長さ (bisect)', tags: ['二分探索', 'dp', 'アルゴリズム'], io: '整数列が1行で与えられます。', ask: '広義単調増加 (前以上ならOK) になる部分列の最大の長さを出力してください。', h1: '各長さでの末尾最小値 tails を保つ。', h2: 'bisect_right で更新位置を探す。', ref: 'import bisect\na=list(map(int,input().split()))\ntails=[]\nfor x in a:\n    i=bisect.bisect_right(tails,x)\n    if i==len(tails):\n        tails.append(x)\n    else:\n        tails[i]=x\nprint(len(tails))', ins: ['1 3 2 3 1\n', '1 2 3\n', '3 2 1\n', '5 5 5\n', '1 3 5 4 7\n', '2 2 3 1 4\n'], tip: '💡 LIS は tails 配列＋二分探索で O(n log n)。狭義は bisect_left, 広義は bisect_right。' })
t({ lv: 650, concept: 'CP: ダブリング', title: 'k回後の到達先 (ダブリング)', tags: ['ダブリング', 'アルゴリズム'], io: '1行目に n、2行目に各頂点の遷移先 next[0..n-1] (0始まり)、3行目に開始 s と回数 k が与えられます。', ask: 's から next を k 回たどった先の頂点を出力してください (k は非常に大きいことがあります)。', h1: '2^b 回後の表を前計算。', h2: 'k の各ビットで合成。', ref: 'n=int(input())\nnxt=list(map(int,input().split()))\ns,k=map(int,input().split())\nLOG=60\nup=[nxt]\nfor _ in range(LOG):\n    prev=up[-1]\n    up.append([prev[prev[i]] for i in range(n)])\npos=s\nfor b in range(LOG+1):\n    if (k>>b)&1:\n        pos=up[b][pos]\nprint(pos)', ins: ['3\n1 2 0\n0 5\n', '4\n1 2 3 0\n0 10\n', '3\n1 2 0\n2 1\n', '5\n1 2 3 4 0\n0 100\n', '2\n1 0\n0 3\n', '3\n0 0 0\n1 1000000000\n'], tip: '💡 ダブリングは「2のべき回後」を合成して k 回を O(log k) で。LCA等にも。' })
t({ lv: 550, concept: 'CP: 三分探索', title: '凸な2次関数の整数最小値 (三分探索)', tags: ['三分探索', 'アルゴリズム'], io: '2次関数 a·x² + b·x + c の係数 a b c が空白区切りで与えられます (a>0)。', ask: '-1000≤x≤1000 の整数 x における最小値を出力してください。', h1: '下に凸なので三分探索。', h2: '範囲を 1/3 ずつ詰める。', ref: 'a,b,c=map(int,input().split())\nlo,hi=-1000,1000\nf=lambda x:a*x*x+b*x+c\nwhile hi-lo>2:\n    m1=lo+(hi-lo)//3\n    m2=hi-(hi-lo)//3\n    if f(m1)>f(m2):\n        lo=m1\n    else:\n        hi=m2\nprint(min(f(x) for x in range(lo,hi+1)))', ins: ['1 -4 5\n', '1 0 0\n', '2 -8 3\n', '1 2 1\n', '3 6 0\n', '1 -10 25\n'], tip: '💡 三分探索は単峰(凸)関数の極値探し。二分探索の凸版。' })
t({ lv: 550, concept: 'CP: 半分全列挙', title: '部分集合の和=K の存在 (半分全列挙)', tags: ['bit全探索', 'アルゴリズム'], io: '1行目に n k、2行目に n 個の整数が与えられます。', ask: '一部を選んで和をちょうど k にできるなら yes、できなければ no を出力してください。', h1: '前半・後半に分けて全列挙。', h2: '前半の和を集合に、後半で k−s を探す。', ref: 'n,k=map(int,input().split())\na=list(map(int,input().split()))\nh=n//2\ndef subs(arr):\n    res=[0]\n    for x in arr:\n        res+=[s+x for s in res]\n    return res\nls=set(subs(a[:h]))\nprint("yes" if any(k-s in ls for s in subs(a[h:])) else "no")', ins: ['4 7\n3 1 4 2\n', '3 10\n1 2 3\n', '5 0\n1 2 3 4 5\n', '4 100\n10 20 30 40\n', '2 5\n2 3\n', '3 6\n1 2 4\n'], tip: '💡 半分全列挙は 2ⁿ を 2·2^(n/2) に。n≦40 の部分和に有効。' })
t({ lv: 650, concept: 'CP: 木の直径', title: '木の直径 (2回BFS)', tags: ['グラフ', 'BFS', 'アルゴリズム'], io: '1行目に n、続く n-1 行に木の無向辺 u v (1始まり) が与えられます。', ask: '最も離れた2頂点間の辺数 (直径) を出力してください。', h1: '任意点から最遠点 u を見つける。', h2: 'u から最遠点までの距離が直径。', ref: 'from collections import deque\nn=int(input())\ng=[[] for _ in range(n+1)]\nfor _ in range(n-1):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\ndef bfs(s):\n    dist=[-1]*(n+1)\n    dist[s]=0\n    far=s\n    dq=deque([s])\n    while dq:\n        x=dq.popleft()\n        for y in g[x]:\n            if dist[y]<0:\n                dist[y]=dist[x]+1\n                if dist[y]>dist[far]:\n                    far=y\n                dq.append(y)\n    return far,dist\nu,_=bfs(1)\nv,dist=bfs(u)\nprint(dist[v])', ins: ['4\n1 2\n2 3\n3 4\n', '1\n', '5\n1 2\n1 3\n1 4\n1 5\n', '3\n1 2\n1 3\n', '6\n1 2\n2 3\n2 4\n4 5\n4 6\n', '2\n1 2\n'], tip: '💡 木の直径は「端から最遠 → そこから最遠」の2回BFSで求まる。' })
t({ lv: 750, concept: 'CP: 行列連鎖乗算', title: '行列連鎖乗算の最小コスト', tags: ['区間DP', 'dp', 'アルゴリズム'], io: '行列の次元列 p0 p1 … pn が空白区切りで与えられます (i番目の行列は p[i-1]×p[i])。', ask: 'すべて掛け合わせる際のスカラー乗算回数の最小値を出力してください。', h1: '区間DP: dp[i][j]=区間の最小コスト。', h2: '分割点 k を全部試す。コストは p[i]·p[k+1]·p[j+1]。', ref: 'p=list(map(int,input().split()))\nn=len(p)-1\nINF=float("inf")\ndp=[[0]*n for _ in range(n)]\nfor length in range(2,n+1):\n    for i in range(n-length+1):\n        j=i+length-1\n        dp[i][j]=INF\n        for k in range(i,j):\n            c=dp[i][k]+dp[k+1][j]+p[i]*p[k+1]*p[j+1]\n            if c<dp[i][j]:\n                dp[i][j]=c\nprint(dp[0][n-1])', ins: ['1 2 3 4\n', '10 20 30\n', '5 5\n', '40 20 30 10 30\n', '1 2 3\n', '2 3 6 4 5\n'], tip: '💡 行列連鎖乗算は区間DPの代表例。掛ける順序で計算量が大きく変わる。' })

export const CATALOG = TASKS
