// 生成タスク 第77波：各レベル3問化フェーズ(4)。lv183〜231 の薄い47段に3問目を追加。
// 文字列/グラフ/グリッド/行列/DP/数え上げ帯。クラスタ3問まで可・言い換え水増し禁止。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 183, concept: '文字列: 2番目に多い単語', title: '準優勝の単語', tags: ['文字列', 'ハッシュ'], io: '単語が空白区切りで1行に与えられます(相異なる単語が2種類以上)。', ask: '出現回数が2番目に多い単語を出力してください(同数の場合は辞書順で小さい方を先とみなします)。', h1: '(−回数, 単語) で並べ替える。', h2: 'ソート済みリストの2番目を取る。', ref: 'from collections import Counter\nc=Counter(input().split())\ns=sorted(c.items(),key=lambda kv:(-kv[1],kv[0]))\nprint(s[1][0])', tip: '最頻(1位)の次を問うと、タイブレークの規約を決めないと答えが定まらないことに気づく。順位づけは常に「同点処理」とセットで仕様化する。', ins: ['cat dog cat bird dog cat\n', 'a b a b c\n', 'x y\n', 'one two two three three three\n', 'p q r p\n', 'z z y y x\n'] })

t({ lv: 184, concept: '文字列: 異なり語率', title: '語彙の豊かさを測る', tags: ['文字列'], io: '単語が空白区切りで1行に与えられます。', ask: '相異なる単語の数を単語の総数で割った割合を、パーセントの整数(切り捨て)で出力してください。', h1: 'setとlenの組合せ。', h2: '100倍してから整数除算すると誤差が出ない。', ref: 'ws=input().split()\nprint(len(set(ws))*100//len(ws))', tip: '異なり語率(type-token ratio)は文体分析の古典的指標。割ってから丸めるのではなく「100倍して整数除算」の順にすると浮動小数を経由せずに済む。', ins: ['a b a c\n', 'x x x\n', 'a b c\n', 'w\n', 'a a b b\n', 'p q p q p\n'] })

t({ lv: 185, concept: '文字列: 単語の文字数の中央値', title: '長さの真ん中', tags: ['文字列'], io: '奇数個の単語が空白区切りで1行に与えられます。', ask: '各単語の文字数を並べたときの中央値を出力してください。', h1: '長さのリストに変換してソート。', h2: '真ん中は添字 n//2。', ref: 'ls=sorted(len(w) for w in input().split())\nprint(ls[len(ls)//2])', tip: '平均文字数(同レベル既出)は外れ値の長い単語に引きずられるが、中央値は動じない。指標の頑健さの違いを同じデータで見比べられる。', ins: ['a bb ccc\n', 'hello\n', 'a bb ccc dddd eeeee\n', 'aa aa aa\n', 'x yy zzz zz z\n', 'abc de fghij\n'] })

t({ lv: 186, concept: '文字列: 辞書順で真ん中の単語', title: '並べたら真ん中に来る単語', tags: ['文字列', 'ソート'], io: '相異なる単語が奇数個、空白区切りで1行に与えられます。', ask: '辞書順に並べたときに真ん中に来る単語を出力してください。', h1: 'sortedして中央を取る。', h2: '添字は n//2。', ref: 'ws=sorted(input().split())\nprint(ws[len(ws)//2])', tip: '数の中央値と同じ操作が文字列にもそのまま通用するのは、比較さえ定義されていればソートも中央値も動くから。「比較可能なら何でも」を体感する1問。', ins: ['b a c\n', 'apple\n', 'e d c b a\n', 'dog cat pig\n', 'z x y\n', 'm a z b n\n'] })

t({ lv: 187, concept: '文字列: 2番目に短い単語', title: '下から2番目の長さの単語', tags: ['文字列', 'ソート'], io: '単語(2個以上)が空白区切りで1行に与えられます。', ask: '文字数の昇順(同じ長さは元の順を保つ)に並べたときの2番目の単語を出力してください。', h1: 'key=len のソートは安定。', h2: 'sorted(ws,key=len)[1]。', ref: 'ws=sorted(input().split(),key=len)\nprint(ws[1])', tip: 'Pythonのsortedは安定ソートなので「同じ長さなら元の順」が無料でついてくる。安定性を仕様として頼るのは実務でも頻出の書き方。', ins: ['a bbb cc\n', 'dd e fff gg\n', 'x y\n', 'aaa bb c\n', 'ab cd ef\n', 'hello hi hey\n'] })

t({ lv: 188, concept: '文字列: すべて大文字の単語の数', title: '全部大文字で書かれた単語', tags: ['文字列'], io: '英字の単語が空白区切りで1行に与えられます。', ask: '全ての文字が大文字である単語の個数を出力してください。', h1: 'isupperは文字列全体にも使える。', h2: 'sumとgenexpで1行。', ref: 'print(sum(1 for w in input().split() if w.isupper()))', tip: '略語(NASA, HTML)の検出はまさにこの判定。isupper()は「大文字が1つ以上あり、大文字化可能な文字が全て大文字」という仕様で、記号だけの文字列はFalseになる。', ins: ['ABC def GHI\n', 'abc\n', 'A B c\n', 'HELLO WORLD\n', 'Mixed CASE mix\n', 'X\n'] })

t({ lv: 189, concept: '文字列: 英数字だけ残す', title: '記号と空白をふるい落とす', tags: ['文字列'], io: '文字列が1行で与えられます(英数字を1文字以上含む)。', ask: '英数字(アルファベットと数字)だけを元の順に残した文字列を出力してください。', h1: 'isalnumで1文字ずつ選別。', h2: 'joinとgenexpで1行。', ref: 'print("".join(c for c in input() if c.isalnum()))', tip: '「英数字だけ見て回文か」(上位レベル既出)の前処理そのもの。フィルタを独立した部品として書いておくと、後段の判定と自由に組み合わせられる。', ins: ['a1-b2!\n', 'hello, world!\n', 'abc\n', '3.14\n', 'a b c\n', 'x+y=z\n'] })

t({ lv: 190, concept: '文字列: 逆さの相方がいる単語の数', title: '鏡写しの相棒を探す', tags: ['文字列', 'ハッシュ'], io: '単語が空白区切りで1行に与えられます。', ask: '「逆順にした文字列が自分以外の単語としてリストに存在する」単語の個数を出力してください(回文単語は自分自身なので数えません)。', h1: '単語の集合を先に作る。', h2: 'w[::-1] in 集合 かつ w[::-1] が w と異なる。', ref: 'ws=input().split()\nst=set(ws)\nprint(sum(1 for w in ws if w[::-1] in st and w[::-1]!=w))', tip: '集合を「存在確認の索引」として使う定石に、自分自身を除外する条件を重ねた形。除外条件を忘れると回文が誤って数えられる、境界仕様の練習台。', ins: ['abc cba dog\n', 'level cat\n', 'ab ba cd dc x\n', 'abc def\n', 'raw war draw\n', 'ab ba ab\n'] })

t({ lv: 191, concept: 'グラフ: 孤立した頂点の数', title: 'ひとりぼっちの頂点', tags: ['グラフ'], io: '1行目に頂点数 n と辺数 m、続く m 行に辺 u v が与えられます。', ask: 'どの辺にも現れない頂点(孤立点)の個数を出力してください。', h1: '辺に現れた頂点を集合に入れる。', h2: 'n から集合の大きさを引く。', ref: 'n,m=map(int,input().split())\nseen=set()\nfor _ in range(m):\n    u,v=map(int,input().split())\n    seen.add(u)\n    seen.add(v)\nprint(n-len(seen))', tip: '孤立点は「連結成分の数」を数えるとき見落としやすい存在で、辺リスト形式の入力では辺を読むだけだと現れない。頂点数nを別に持つ意味がここにある。', ins: ['4 2\n1 2\n2 3\n', '3 0\n', '5 2\n1 2\n3 4\n', '2 1\n1 2\n', '6 3\n1 2\n1 3\n1 4\n', '3 1\n2 3\n'] })

t({ lv: 192, concept: 'グラフ: 頂点の最小次数', title: '一番つながりの少ない頂点', tags: ['グラフ'], io: '1行目に頂点数 n と辺数 m、続く m 行に辺 u v が与えられます。', ask: '全頂点の中での次数の最小値を出力してください。', h1: '次数の配列を作る。', h2: '辺のない頂点の次数は0。', ref: 'n,m=map(int,input().split())\ndeg=[0]*(n+1)\nfor _ in range(m):\n    u,v=map(int,input().split())\n    deg[u]+=1\n    deg[v]+=1\nprint(min(deg[1:n+1]))', tip: '最小次数はグラフの頑健性の下限を示す量で、彩色の貪欲アルゴリズムの保証(δ+1色)にも登場する。最大次数(同レベル既出)と対で押さえたい。', ins: ['3 2\n1 2\n1 3\n', '4 3\n1 2\n2 3\n3 1\n', '2 1\n1 2\n', '5 4\n1 2\n1 3\n1 4\n1 5\n', '3 3\n1 2\n2 3\n3 1\n', '4 0\n'] })

t({ lv: 193, concept: 'グラフ: 森かどうか', title: '閉路のない世界か', tags: ['グラフ', 'Union-Find'], io: '1行目に頂点数 n と辺数 m、続く m 行に辺 u v が与えられます(多重辺なし)。', ask: 'グラフに閉路が1つもない(森である)なら yes、あれば no を出力してください(連結でなくてもよい)。', h1: '木の判定から連結条件を外す。', h2: 'Union-Findで、すでに同じ組の2頂点を結ぶ辺が来たら閉路。', ref: 'n,m=map(int,input().split())\np=list(range(n+1))\ndef find(x):\n    while p[x]!=x:\n        p[x]=p[p[x]]\n        x=p[x]\n    return x\nok=True\nfor _ in range(m):\n    u,v=map(int,input().split())\n    ru,rv=find(u),find(v)\n    if ru==rv:\n        ok=False\n    else:\n        p[ru]=rv\nprint("yes" if ok else "no")', tip: '木は「連結な森」。森の判定は m が n−(成分数) に等しいかでも書けるが、Union-Findなら辺を読みながら即座に閉路を検出できる。クラスカル法の中身もこれ。', ins: ['4 2\n1 2\n3 4\n', '3 3\n1 2\n2 3\n3 1\n', '5 4\n1 2\n2 3\n3 4\n4 5\n', '4 3\n1 2\n2 3\n1 3\n', '1 0\n', '6 3\n1 2\n3 4\n5 6\n'] })

t({ lv: 194, concept: '数え上げ: 奇数だけの区間の数', title: '奇数が続く場所から生まれる区間', tags: ['数え上げ'], io: '整数列が1行で空白区切りで与えられます。', ask: '全要素が奇数である連続部分配列(長さ1以上)の個数を出力してください。', h1: '奇数の連続の長さに注目。', h2: '長さLの奇数の連なりからは L(L+1)/2 個の区間が取れる。', ref: 'a=list(map(int,input().split()))\nans=0\nrun=0\nfor x in a:\n    if x%2==1:\n        run+=1\n        ans+=run\n    else:\n        run=0\nprint(ans)', tip: '「条件を満たす要素の連なり」ごとに三角数を足す数え方。run を足し込む書き方は L(L+1)/2 の逐次版で、breakのない1パスに収まる。', ins: ['1 3 2 5\n', '2 4\n', '1 1 1\n', '1 2 1 2 1\n', '7\n', '2 1 3 5 4 9\n'] })

t({ lv: 195, concept: 'グラフ: 最も遠い頂点の番号', title: '一番遠くにいるのは誰', tags: ['グラフ', 'BFS'], io: '1行目に頂点数 n と辺数 m、続く m 行に辺 u v が与えられます(連結)。', ask: '頂点1からの最短距離が最大である頂点の番号を出力してください(複数あれば最小の番号)。', h1: 'BFSで全頂点の距離を求める。', h2: '最大距離を先に求め、その距離を持つ最小番号を探す。', ref: 'from collections import deque\nn,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\ndist=[-1]*(n+1)\ndist[1]=0\nq=deque([1])\nwhile q:\n    x=q.popleft()\n    for y in g[x]:\n        if dist[y]<0:\n            dist[y]=dist[x]+1\n            q.append(y)\nbest=max(dist[1:n+1])\nfor v in range(1,n+1):\n    if dist[v]==best:\n        print(v)\n        break', tip: '最遠距離(同レベル既出)のargmax版。これを2回繰り返す「2回BFS」が木の直径を求める有名アルゴリズムになる、その部品にあたる。', ins: ['4 3\n1 2\n2 3\n2 4\n', '2 1\n1 2\n', '5 4\n1 2\n2 3\n3 4\n4 5\n', '3 3\n1 2\n2 3\n1 3\n', '1 0\n', '6 5\n1 2\n1 3\n3 4\n4 5\n3 6\n'] })

t({ lv: 196, concept: '数え上げ: 同じ値の3つ組の数', title: 'そっくりさんトリオ', tags: ['数え上げ', 'ハッシュ'], io: '整数列が1行で空白区切りで与えられます。', ask: 'i<j<k で a[i], a[j], a[k] が全て等しい3つ組の個数を出力してください。', h1: '値ごとの個数から組合せを数える。', h2: '個数cからは C(c,3) すなわち c(c−1)(c−2)/6 組。', ref: 'from collections import Counter\nc=Counter(input().split())\nprint(sum(v*(v-1)*(v-2)//6 for v in c.values()))', tip: '等しいペア数 C(c,2)(同レベル既出)の3人版。組合せの式を差し替えるだけで骨格が再利用でき、k人組への一般化も見えてくる。', ins: ['2 2 2 3\n', '1 1 2 2\n', '5 5 5 5\n', '1 2 3\n', '4 4 4\n', '1 1 1 2 2 2 2\n'] })

t({ lv: 197, concept: '数え上げ: 和が0のペアの数', title: '打ち消し合う2人', tags: ['数え上げ', 'ハッシュ'], io: '整数列が1行で空白区切りで与えられます。', ask: 'i<j で a[i]+a[j] が 0 になるペアの個数を出力してください。', h1: 'xと−xの個数の積。', h2: '0どうしは C(c,2)、正のxごとに c[x]×c[−x] を足す。', ref: 'from collections import Counter\nc=Counter(map(int,input().split()))\nans=c[0]*(c[0]-1)//2\nfor x in c:\n    if x>0:\n        ans+=c[x]*c[-x]\nprint(ans)', tip: '0だけ「相方が自分と同じ値」なので組合せ、他は積、という場合分けが肝。和がKのペア数でK=0のときだけ二重計上の罠が出る、その正体がここにある。', ins: ['1 -1 2 -2 -1\n', '0 0 0\n', '1 2 3\n', '5 -5\n', '0 1 -1\n', '2 2 -2\n'] })

t({ lv: 198, concept: 'グリッド: 行き止まりの数', title: '袋小路を数える', tags: ['グリッド'], io: '1行目に H W、続く H 行に迷路(. が通れる、# が壁)が与えられます。', ask: '通れるマスのうち、上下左右で隣接する通れるマスがちょうど1つである「行き止まり」の個数を出力してください。', h1: '各マスの4近傍を調べる。', h2: '範囲内かつ . の近傍を数えて1と比較。', ref: 'h,w=map(int,input().split())\ng=[input() for _ in range(h)]\ncnt=0\nfor i in range(h):\n    for j in range(w):\n        if g[i][j]==".":\n            k=0\n            for di,dj in ((1,0),(-1,0),(0,1),(0,-1)):\n                ni,nj=i+di,j+dj\n                if 0<=ni<h and 0<=nj<w and g[ni][nj]==".":\n                    k+=1\n            if k==1:\n                cnt+=1\nprint(cnt)', tip: '迷路生成の品質評価や「行き止まりを埋める」枝刈り(dead-end filling)の前段になる集計。孤立マス(近傍0)は行き止まりに含めない仕様の線引きに注意。', ins: ['2 3\n..#\n#..\n', '1 3\n...\n', '1 1\n.\n', '2 2\n..\n..\n', '3 3\n###\n#.#\n###\n', '3 1\n.\n.\n.\n'] })

t({ lv: 199, concept: 'グリッド: 最小の島のサイズ', title: '一番小さな島', tags: ['グリッド', 'DFS'], io: '1行目に H W、続く H 行に 0/1 の文字列(1が陸)が与えられます(陸が1マス以上)。', ask: '上下左右でつながる陸のまとまり(島)のうち、最小の島のマス数を出力してください。', h1: '最大の島(同レベル既出)の集計をminに変える。', h2: '塗りつぶしで各島のサイズを求める。', ref: 'h,w=map(int,input().split())\ng=[list(input()) for _ in range(h)]\nbest=h*w+1\nfor si in range(h):\n    for sj in range(w):\n        if g[si][sj]=="1":\n            size=0\n            st=[(si,sj)]\n            g[si][sj]="0"\n            while st:\n                i,j=st.pop()\n                size+=1\n                for di,dj in ((1,0),(-1,0),(0,1),(0,-1)):\n                    ni,nj=i+di,j+dj\n                    if 0<=ni<h and 0<=nj<w and g[ni][nj]=="1":\n                        g[ni][nj]="0"\n                        st.append((ni,nj))\n            if size<best:\n                best=size\nprint(best)', tip: '最大→最小の鏡像だが、初期値を「あり得ない大きさ」にする必要が生まれる点だけ非対称。訪問済みを盤面の書き換えで表すとvisited配列が省ける。', ins: ['2 3\n110\n001\n', '1 4\n1111\n', '3 3\n101\n010\n101\n', '2 2\n11\n11\n', '1 5\n10011\n', '3 3\n111\n101\n111\n'] })

t({ lv: 201, concept: '行列: 主対角成分の積', title: '対角線を掛け合わせる', tags: ['行列'], io: '1行目に n、続く n 行に n×n の行列が与えられます。', ask: '主対角成分(左上から右下)の積を出力してください。', h1: 'A[i][i] を集める。', h2: 'ループで掛け込むかmath.prod。', ref: 'n=int(input())\np=1\nfor i in range(n):\n    row=list(map(int,input().split()))\n    p*=row[i]\nprint(p)', tip: '上三角行列では対角積がそのまま行列式になる。行を読みながら i 番目だけ使えば行列全体を保存する必要がない、省メモリの読み方も添えて。', ins: ['2\n1 2\n3 4\n', '1\n7\n', '3\n2 1 1\n1 3 1\n1 1 4\n', '2\n5 9\n9 0\n', '3\n1 2 3\n4 5 6\n7 8 9\n', '2\n-2 1\n1 3\n'] })

t({ lv: 202, concept: '行列: 和が最小の行の番号', title: '合計が一番軽い行', tags: ['行列'], io: '1行目に n、続く n 行に整数の行が与えられます。', ask: '要素の合計が最小である行の番号(1始まり、同点なら最小の番号)を出力してください。', h1: '行ごとにsumを取る。', h2: '「より小さいときだけ」更新すれば先勝ち。', ref: 'n=int(input())\nbest=None\nans=1\nfor i in range(n):\n    s=sum(map(int,input().split()))\n    if best is None or s<best:\n        best=s\n        ans=i+1\nprint(ans)', tip: '和が最大の行(同レベル既出)のmin版。Noneを「まだ無い」の印に使う初期化は、最小値の初期値に巨大な定数を置くより意図が明確になる。', ins: ['2\n3 4\n1 2\n', '3\n1 1\n5 5\n0 0\n', '1\n9 9 9\n', '3\n2 2\n2 2\n2 2\n', '2\n-5 0\n1 1\n', '4\n3\n1\n4\n1\n'] })

t({ lv: 203, concept: '単調デック: 各窓の最小値の列', title: 'すべての窓の底値', tags: ['単調デック'], io: '1行目に n k、2行目に n 個の整数列が与えられます。', ask: '長さ k の各窓(左から順)の最小値を空白区切りで1行に出力してください。', h1: '窓の最大値の列(同レベル既出)の不等号を逆に。', h2: '単調増加のデックを保てば先頭が常に最小。', ref: 'from collections import deque\nn,k=map(int,input().split())\na=list(map(int,input().split()))\nq=deque()\nout=[]\nfor i,x in enumerate(a):\n    while q and a[q[-1]]>=x:\n        q.pop()\n    q.append(i)\n    if q[0]<=i-k:\n        q.popleft()\n    if i>=k-1:\n        out.append(a[q[0]])\nprint(" ".join(map(str,out)))', tip: '最大版との差分は比較演算子1つ。この対称性に気づけば、min用とmax用を別々に暗記する必要がなくなる。O(n)なのは各要素が高々1回入り1回出るから。', ins: ['5 3\n1 3 2 5 4\n', '4 2\n4 3 2 1\n', '3 3\n5 1 5\n', '5 1\n2 4 1 3 5\n', '6 3\n2 1 3 1 5 6\n', '4 4\n7 2 8 3\n'] })

t({ lv: 204, concept: 'リスト: 前半と後半が分離しているか', title: '前半チームと後半チームの力関係', tags: ['リスト'], io: '偶数個の整数列が1行で空白区切りで与えられます。', ask: '前半のどの要素も後半のどの要素より小さい(前半の最大が後半の最小より小さい)なら yes、そうでなければ no を出力してください。', h1: '全ペアを比べる必要はない。', h2: 'max(前半) と min(後半) だけで決まる。', ref: 'a=list(map(int,input().split()))\nh=len(a)//2\nprint("yes" if max(a[:h])<min(a[h:]) else "no")', tip: '「全ての組合せの条件」が代表値2つの比較に潰れる好例。クイックソートの分割(パーティション)が成功したかの検算もこの形をしている。', ins: ['1 2 3 4\n', '3 1 2 4\n', '1 1 2 2\n', '5 6\n', '2 2\n', '1 4 2 3\n'] })

t({ lv: 205, concept: '数え上げ: 左に小さい要素がある数', title: '前に格下がいる要素', tags: ['数え上げ'], io: '整数列が1行で空白区切りで与えられます。', ask: '自分より左に、自分より小さい要素が1つでも存在するような要素の個数を出力してください。', h1: '右に大きい要素(同レベル既出)の鏡像。', h2: 'ここまでの最小値を持ち回り、自分と比べる。', ref: 'a=list(map(int,input().split()))\nlo=a[0]\ncnt=0\nfor x in a[1:]:\n    if lo<x:\n        cnt+=1\n    if x<lo:\n        lo=x\nprint(cnt)', tip: '右からmaxを走らせる問題と左からminを走らせる問題は完全な鏡像で、走査方向と極値の向きが同時に反転する。両方書いて対称性を確かめたい。', ins: ['3 1 4 2\n', '5 4 3\n', '1 2 3\n', '2 2\n', '4 1 5 1 6\n', '7\n'] })

t({ lv: 206, concept: '行列: 全ての行が昇順か', title: 'どの行も左から右へ上り調子か', tags: ['行列'], io: '1行目に H W、続く H 行に整数の行が与えられます。', ask: '全ての行が広義単調増加(各要素が1つ左の要素以上)なら yes、そうでなければ no を出力してください。', h1: '1行の昇順判定を全行に適用。', h2: 'all を2重に使う。', ref: 'h,w=map(int,input().split())\ng=[list(map(int,input().split())) for _ in range(h)]\nok=all(all(r[j]<=r[j+1] for j in range(w-1)) for r in g)\nprint("yes" if ok else "no")', tip: '行ソート済みは「行き先ごとにソート済みのデータベース」の抽象で、各行への二分探索や階段状探索の前提条件になる。前提の検証を独立した1問として書く価値がある。', ins: ['2 3\n1 2 3\n1 1 5\n', '2 2\n2 1\n3 4\n', '1 4\n1 1 2 2\n', '3 2\n1 2\n5 5\n0 9\n', '2 2\n9 8\n7 6\n', '1 1\n4\n'] })

t({ lv: 207, concept: '行列: 内側の要素の合計', title: '外周を除いた中身の合計', tags: ['行列'], io: '1行目に H W、続く H 行に整数の行が与えられます。', ask: '外周(1行目・最終行・各行の両端)を除いた内側の要素の合計を出力してください(内側が無ければ 0)。', h1: '外周の和(同レベル既出)の補集合。', h2: '行を1..H−2、列を1..W−2の範囲で回す。', ref: 'h,w=map(int,input().split())\ng=[list(map(int,input().split())) for _ in range(h)]\nprint(sum(g[i][j] for i in range(1,h-1) for j in range(1,w-1)))', tip: '全体の和から外周の和を引く方法と直接足す方法の2通りがあり、答え合わせに使える。H<3やW<3で内側が空になる境界はrangeが自然に守ってくれる。', ins: ['3 3\n1 2 3\n4 5 6\n7 8 9\n', '4 4\n1 1 1 1\n1 2 3 1\n1 4 5 1\n1 1 1 1\n', '2 3\n1 2 3\n4 5 6\n', '3 4\n0 0 0 0\n0 7 9 0\n0 0 0 0\n', '1 1\n5\n', '3 3\n0 0 0\n0 -4 0\n0 0 0\n'] })

t({ lv: 208, concept: '行列: 相異なる列の数', title: '列のバリエーション', tags: ['行列', 'ハッシュ'], io: '1行目に H W、続く H 行に整数の行が与えられます。', ask: '列として相異なるものが何種類あるかを出力してください。', h1: '相異なる行(同レベル既出)の列版。', h2: 'zip(*g) で列をタプルとして取り出し集合へ。', ref: 'h,w=map(int,input().split())\ng=[list(map(int,input().split())) for _ in range(h)]\nprint(len(set(zip(*g))))', tip: 'zip(*g) は転置のイディオムで、列の問題を一撃で行の問題に変換する。タプルはハッシュ可能なのでそのままsetに入る、という2つの道具の噛み合わせ。', ins: ['2 3\n1 2 1\n3 4 3\n', '2 2\n1 1\n2 2\n', '3 3\n1 2 3\n1 2 3\n1 2 3\n', '2 4\n1 1 2 2\n1 1 2 2\n', '1 3\n7 7 7\n', '2 2\n1 2\n3 4\n'] })

t({ lv: 209, concept: '数え上げ: 一周できる出発点の数', title: '一周できるスタート地点は何箇所', tags: ['数え上げ', 'シミュレーション'], io: '1行目に地点数 n、2行目に各地点の補給量、3行目に次の地点までの消費量が与えられます。', ask: '燃料0でスタートし、途中で燃料が負にならずに一周できる出発点の個数を出力してください。', h1: '一周できる出発点を1つ探す問題(同レベル既出)の全数版。', h2: '各出発点から一周をシミュレーションする。', ref: 'n=int(input())\ng=list(map(int,input().split()))\nc=list(map(int,input().split()))\nans=0\nfor s in range(n):\n    tank=0\n    ok=True\n    for i in range(n):\n        j=(s+i)%n\n        tank+=g[j]-c[j]\n        if tank<0:\n            ok=False\n            break\n    if ok:\n        ans+=1\nprint(ans)', tip: '総和が正なら成功する出発点が必ず1つ存在するが、「何箇所あるか」は分布による。貪欲で1点を即答できる問題でも、全数はシミュレーションが素直。', ins: ['3\n2 3 1\n1 2 2\n', '2\n1 1\n2 2\n', '3\n1 1 1\n1 1 1\n', '4\n4 0 0 0\n1 1 1 1\n', '2\n3 1\n1 1\n', '5\n1 2 3 4 5\n5 4 3 2 1\n'] })

t({ lv: 211, concept: 'リスト: 範囲へのクリップ', title: 'はみ出しを枠に押し戻す', tags: ['リスト'], io: '1行目に lo hi、2行目に整数列が与えられます。', ask: '各要素を lo 未満なら lo に、hi 超なら hi に置き換えた列を空白区切りで出力してください。', h1: 'minとmaxの入れ子で書ける。', h2: 'max(lo, min(hi, x))。', ref: 'lo,hi=map(int,input().split())\na=list(map(int,input().split()))\nprint(" ".join(str(max(lo,min(hi,x))) for x in a))', tip: 'クリップ(クランプ)は画像の画素値、音声の振幅、学習率など至る所に現れる基本演算。numpyのclip、C++のstd::clampと、どの環境にも同名の道具がある。', ins: ['1 5\n0 3 7 5 -2\n', '0 10\n1 2 3\n', '2 4\n1 5\n', '-1 1\n-5 0 5\n', '3 3\n1 2 3 4\n', '0 100\n50\n'] })

t({ lv: 212, concept: '数え上げ: 和がt未満の窓の数', title: '合計が控えめな窓', tags: ['数え上げ', '累積和'], io: '1行目に k t、2行目に整数列(長さk以上)が与えられます。', ask: '長さ k の連続する窓のうち、和が t 未満であるものの個数を出力してください。', h1: '和がt超の窓(同レベル既出)の裏返し。', h2: '窓をずらしながら「出る要素を引き、入る要素を足す」。', ref: 'k,t=map(int,input().split())\na=list(map(int,input().split()))\ns=sum(a[:k])\ncnt=1 if s<t else 0\nfor i in range(k,len(a)):\n    s+=a[i]-a[i-k]\n    if s<t:\n        cnt+=1\nprint(cnt)', tip: '超・以上・未満・以下の4兄弟は不等号の向きと等号の有無だけが違う。「全窓数から超と同点を引く」補集合の検算で、境界のズレを1発で発見できる。', ins: ['2 5\n1 2 3 4\n', '3 100\n1 2 3\n', '1 3\n1 5 2 4\n', '2 4\n2 2 2\n', '2 10\n1 1 1 1 1\n', '4 15\n1 2 3 4 5\n'] })

t({ lv: 213, concept: 'DP: 壁があっても右下へ行けるか', title: 'その迷路、右下へ抜けられるか', tags: ['DP', 'グリッド'], io: '1行目に H W、続く H 行に盤面(. が通れる、# が壁)が与えられます。移動は右か下のみです。', ask: '左上から右下へ到達できるなら yes、できなければ no を出力してください。', h1: '経路数を数える問題(同レベル既出)の存在判定版。', h2: '到達可能フラグを左上から伝播させる。', ref: 'h,w=map(int,input().split())\ng=[input() for _ in range(h)]\ndp=[[False]*w for _ in range(h)]\nfor i in range(h):\n    for j in range(w):\n        if g[i][j]=="#":\n            continue\n        if i==0 and j==0:\n            dp[i][j]=True\n        else:\n            dp[i][j]=(i>0 and dp[i-1][j]) or (j>0 and dp[i][j-1])\nprint("yes" if dp[h-1][w-1] else "no")', tip: '「経路数が0より大きいか」でも解けるが、真偽値のDPは数が爆発しないぶん本質だけが残る。数える・最適化する・判定するはDPの3つの顔で、遷移は同じ形。', ins: ['2 2\n..\n#.\n', '2 2\n.#\n#.\n', '1 3\n..#\n', '3 3\n...\n###\n...\n', '1 1\n.\n', '3 3\n..#\n#.#\n#..\n'] })

t({ lv: 214, concept: 'DP: 最小コスト経路の道順', title: '最安ルートの道案内', tags: ['DP', 'グリッド'], io: '1行目に H W、続く H 行にコストの格子が与えられます。左上から右下へ、右(R)か下(D)にだけ進みます。', ask: '通ったマスのコスト合計が最小になる経路の移動列を、複数あれば辞書順最小(DはRより先)のものを出力してください。', h1: 'コスト最小の値(同レベル既出)を求めてから道を復元する。', h2: 'ゴール側からDPを作れば、先頭から貪欲に「下が同点以下なら下」を選ぶだけで辞書順最小になる。', ref: 'h,w=map(int,input().split())\ng=[list(map(int,input().split())) for _ in range(h)]\ndp=[[0]*w for _ in range(h)]\nfor i in range(h-1,-1,-1):\n    for j in range(w-1,-1,-1):\n        if i==h-1 and j==w-1:\n            dp[i][j]=g[i][j]\n        elif i==h-1:\n            dp[i][j]=g[i][j]+dp[i][j+1]\n        elif j==w-1:\n            dp[i][j]=g[i][j]+dp[i+1][j]\n        else:\n            dp[i][j]=g[i][j]+min(dp[i+1][j],dp[i][j+1])\ni=j=0\nmv=[]\nwhile i<h-1 or j<w-1:\n    if i==h-1:\n        mv.append("R")\n        j+=1\n    elif j==w-1:\n        mv.append("D")\n        i+=1\n    elif dp[i+1][j]<=dp[i][j+1]:\n        mv.append("D")\n        i+=1\n    else:\n        mv.append("R")\n        j+=1\nprint("".join(mv))', tip: '復元は「後ろ向きDP+前向き貪欲」が定石。前向きDPで作ると復元が逆順になり、辞書順最小の保証も崩れる。値を求める問題との違いはこの設計判断にある。', ins: ['2 2\n1 2\n3 1\n', '2 2\n1 1\n1 1\n', '1 3\n1 2 3\n', '3 1\n1\n2\n3\n', '3 3\n1 9 9\n1 1 9\n9 1 1\n', '2 3\n1 5 1\n2 1 1\n'] })

t({ lv: 215, concept: '数え上げ: 重なる区間のペア数', title: 'かち合う予定は何組', tags: ['数え上げ', '区間'], io: '1行目に n、続く n 行に区間 l r (l≤r) が与えられます。', ask: '共有する点が1つでもある区間のペア(i<j)の個数を出力してください(端点だけ触れる場合も重なりとみなします)。', h1: '2区間が重なる条件は1つの不等式で書ける。', h2: 'max(l1,l2) が min(r1,r2) 以下なら重なる。', ref: 'n=int(input())\niv=[tuple(map(int,input().split())) for _ in range(n)]\ncnt=0\nfor i in range(n):\n    for j in range(i+1,n):\n        if max(iv[i][0],iv[j][0])<=min(iv[i][1],iv[j][1]):\n            cnt+=1\nprint(cnt)', tip: '重なり判定 max(l)≤min(r) は「重ならない条件の否定」から導くと間違えない。会議室数(同レベル既出)が時間軸で数えたものを、こちらはペア単位で数えている。', ins: ['3\n1 3\n2 4\n5 6\n', '2\n1 2\n3 4\n', '3\n1 10\n2 3\n4 5\n', '2\n1 2\n2 3\n', '4\n1 2\n1 2\n1 2\n1 2\n', '1\n5 9\n'] })

t({ lv: 216, concept: 'リスト: 届かない最初の位置', title: 'ジャンプの限界地点', tags: ['リスト', '貪欲'], io: '各位置からの最大ジャンプ距離の列が1行で空白区切りで与えられます(位置は左端から始まります)。', ask: '左端から始めて到達できない最初の位置(1始まり)を出力してください。全ての位置に到達できるなら all を出力してください。', h1: '届く範囲の最大を持ち回る。', h2: '位置iが今の届く範囲を超えていたらそこが答え。', ref: 'a=list(map(int,input().split()))\nreach=0\nans="all"\nfor i in range(len(a)):\n    if i>reach:\n        ans=str(i+1)\n        break\n    if i+a[i]>reach:\n        reach=i+a[i]\nprint(ans)', tip: '末尾へ届くかの判定(同レベル既出)に「どこで詰むか」の答えを足した構成版。reachの更新を答えの確定より後に置くと自分自身のジャンプ力を数え損ねない。', ins: ['1 0 5 2\n', '2 0 1 4\n', '0 7\n', '3 1 1 1 1\n', '1 1 0 0 5\n', '5\n'] })

t({ lv: 217, concept: 'DP: ちょうどkジャンプで到達できるか', title: 'きっかりk回で着地せよ', tags: ['DP'], io: '1行目に k、2行目に各位置からの最大ジャンプ距離の列が与えられます。位置iからは1以上その値以下だけ右へ進めます。', ask: '左端からちょうど k 回のジャンプで右端に到達できるなら yes、できなければ no を出力してください(右端を通り過ぎることはできません)。', h1: '最小ジャンプ数(同レベル既出)は貪欲だが「ちょうど」は集合の伝播で。', h2: 'jジャンプ後にいられる位置の集合を k 回更新する。', ref: 'k=int(input())\na=list(map(int,input().split()))\nn=len(a)\ncur={0}\nfor _ in range(k):\n    nxt=set()\n    for p in cur:\n        for q in range(p+1,min(p+a[p],n-1)+1):\n            nxt.add(q)\n    cur=nxt\nprint("yes" if n-1 in cur else "no")', tip: '「最小」が貪欲で解けても「ちょうど」は状態を全部持つ必要が出る。到達可能集合を回すこの形は、BFSの世代管理やオートマトンの状態遷移と同じ骨格。', ins: ['2\n2 1 1\n', '1\n2 1 1\n', '3\n2 1 1\n', '2\n1 1 1 1\n', '4\n1 1 1 1 1\n', '2\n3 1 2 1\n'] })

t({ lv: 218, concept: '二分探索: 挿入したときの両隣', title: '割り込んだら誰と誰の間か', tags: ['二分探索'], io: '1行目に x、2行目に昇順の整数列が与えられます。', ask: 'x を順序を保って(等しい値があればその直前に)挿入したときの、左隣と右隣の値を空白区切りで出力してください(存在しない側は - とします)。', h1: 'bisect_leftで挿入位置を求める。', h2: '位置pの左隣は a[p−1]、右隣は a[p]。端の存在チェックを忘れずに。', ref: 'import bisect\nx=int(input())\na=list(map(int,input().split()))\np=bisect.bisect_left(a,x)\nleft=str(a[p-1]) if p>0 else "-"\nright=str(a[p]) if p<len(a) else "-"\nprint(left,right)', tip: 'x以下の最大・x以上の最小(同レベル既出)を1回のbisectで同時に取り出す統合版。bisect_leftとbisect_rightの違いは「等しい値のどちら側に割り込むか」に尽きる。', ins: ['5\n1 3 7 9\n', '3\n1 3 7\n', '0\n1 2\n', '10\n1 2\n', '5\n5 5 5\n', '4\n2 4 6\n'] })

t({ lv: 219, concept: '数え上げ: 差がd以下のペア数', title: '近い者どうしの組', tags: ['数え上げ', '二点法'], io: '1行目に d、2行目に整数列が与えられます。', ask: 'i<j で |a[i]−a[j]| が d 以下のペアの個数を出力してください。', h1: 'ソートすれば絶対値が外れる。', h2: '右端ごとに「差がdを超えない左端」までを二点法で保ち、r−l を足す。', ref: 'd=int(input())\na=sorted(map(int,input().split()))\nl=0\ncnt=0\nfor r in range(len(a)):\n    while a[r]-a[l]>d:\n        l+=1\n    cnt+=r-l\nprint(cnt)', tip: '差がちょうどd(同レベル既出)はハッシュ、以下なら二点法と、同じ「差」でも道具が変わる。ソート済み列の二点法は窓が単調に動くことが計算量O(n)の根拠。', ins: ['2\n1 3 6 8\n', '0\n1 1 2\n', '10\n1 2 3\n', '1\n5 7 9\n', '3\n4 1 2 8\n', '5\n10 10\n'] })

t({ lv: 220, concept: 'DP: 減少部分列の最大和', title: '下り坂で稼げるだけ稼ぐ', tags: ['DP'], io: '整数列が1行で空白区切りで与えられます。', ask: '厳密に減少する部分列(連続でなくてよい)の和の最大値を出力してください。', h1: '増加部分列の和の最大(同レベル既出)の鏡像。', h2: 'dp[i] は a[i] で終わる減少列の最大和。左のより大きい要素から繋ぐ。', ref: 'a=list(map(int,input().split()))\nn=len(a)\ndp=[0]*n\nfor i in range(n):\n    best=0\n    for j in range(i):\n        if a[j]>a[i] and dp[j]>best:\n            best=dp[j]\n    dp[i]=a[i]+best\nprint(max(dp))', tip: '増加版の不等号を1つ反転しただけの鏡像だが、「列を逆順にして増加版を呼ぶ」変換でも解ける。同じ問題への2経路を持つとバグの切り分けが速い。', ins: ['5 3 8 4 1\n', '1 2 3\n', '9\n', '4 3 5 2\n', '2 2 2\n', '10 1 9 8\n'] })

t({ lv: 221, concept: '数え上げ: 0と1が同数の区間の数', title: 'ゼロとイチが釣り合う区間', tags: ['数え上げ', '累積和'], io: '0と1の列が1行で空白区切りで与えられます。', ask: '0の個数と1の個数が等しい連続部分配列の個数を出力してください。', h1: '最長版(同レベル既出)と同じ変換が効く。', h2: '0を−1とみなした累積和が同じ値になる2地点の組を数える。', ref: 'from collections import Counter\na=list(map(int,input().split()))\nc=Counter([0])\ns=0\nans=0\nfor x in a:\n    s+=1 if x==1 else -1\n    ans+=c[s]\n    c[s]+=1\nprint(ans)', tip: '「同じ累積値のペア数」に落とすと、最長(最遠のペア)も個数(全ペア)も同じ前処理から出る。1つの変換が複数の問いに答える、累積和の底力。', ins: ['0 1 0\n', '1 1\n', '0 1 1 0\n', '0 0 1 1\n', '1\n', '0 1 0 1 0 1\n'] })

t({ lv: 222, concept: 'リスト: 中央値に揃える移動量の合計', title: 'みんなで真ん中に集合', tags: ['リスト', 'ソート'], io: '整数列が1行で空白区切りで与えられます。', ask: '全要素をある1つの値に揃えるとき、各要素の変更量(絶対値)の合計が最小になるようにします。その最小の合計を出力してください。', h1: '揃える先は平均ではない。', h2: '絶対値の和を最小にする点は中央値。ソートして中央の値との差を足す。', ref: 'a=sorted(map(int,input().split()))\nm=a[len(a)//2]\nprint(sum(abs(x-m) for x in a))', tip: '二乗誤差の最小は平均、絶対誤差の最小は中央値。この対比は統計学の平均vs中央値の頑健性の話と同じ構造で、偶数長ではどちらの中央でも合計が変わらない。', ins: ['1 2 9\n', '1 2 3 4\n', '5\n', '1 1 1\n', '-3 0 3\n', '10 2 8\n'] })

t({ lv: 223, concept: 'DP: ちょうどの重さで最大価値', title: 'ぴったり詰めて価値最大', tags: ['DP'], io: '1行目に n W、続く n 行に品物の 重さ 価値 が与えられます。', ask: '重さの合計をちょうど W にする選び方の中で価値の合計の最大を出力してください。ちょうど W にできなければ -1 を出力してください。', h1: '容量以下で最大化する問題(同レベル既出)の「ちょうど」版。', h2: '不可能な重さを−∞(番兵)で表し、dp[0]だけ0から始める。', ref: 'n,W=map(int,input().split())\nNEG=-(10**9)\ndp=[NEG]*(W+1)\ndp[0]=0\nfor _ in range(n):\n    w,v=map(int,input().split())\n    for c in range(W,w-1,-1):\n        if dp[c-w]>NEG and dp[c-w]+v>dp[c]:\n            dp[c]=dp[c-w]+v\nprint(dp[W] if dp[W]>NEG else -1)', tip: '「以下」と「ちょうど」の違いは初期化に集約される。全部0で始めると「余りは空きでよい」、−∞で始めると「その重さを本当に作れた場合のみ有効」になる。', ins: ['3 5\n2 3\n3 4\n5 6\n', '2 4\n2 3\n3 4\n', '1 3\n3 10\n', '3 6\n2 2\n2 3\n2 4\n', '2 5\n5 1\n2 9\n', '3 4\n1 5\n3 5\n4 9\n'] })

t({ lv: 224, concept: 'リスト: k番目に大きい相異なる値', title: '上から数えてk番目(重複抜き)', tags: ['リスト', 'ソート'], io: '1行目に k、2行目に整数列(相異なる値がk個以上)が与えられます。', ask: '重複を除いた値を大きい順に並べたときの k 番目を出力してください。', h1: 'k番目に小さい版(同レベル既出)の鏡像。', h2: 'sorted(set(a), reverse=True)[k−1]。', ref: 'k=int(input())\na=list(map(int,input().split()))\nprint(sorted(set(a),reverse=True)[k-1])', tip: 'reverse=Trueと[k−1]の組は「降順の順位」の直訳。重複を除くか除かないかで順位の意味が変わるので、仕様を読むとき最初に確かめる点になる。', ins: ['2\n5 1 5 3\n', '1\n2 9 9\n', '3\n4 4 3 2 1\n', '2\n7 7 8\n', '4\n5 6 1 2 3\n', '1\n1\n'] })

t({ lv: 225, concept: '組合せ: 隣り合う二項係数の比', title: 'パスカルの三角形の横の傾き', tags: ['組合せ'], io: 'n k (0≤k<n) が空白区切りで1行で与えられます。', ask: 'C(n,k+1) を C(n,k) で割った比を既約分数にして「分子 分母」の形で出力してください。', h1: '2つの二項係数を実際に計算しなくても比は簡単になる。', h2: '比は (n−k)/(k+1)。gcdで約分する。', ref: 'from math import gcd\nn,k=map(int,input().split())\np=n-k\nq=k+1\ng=gcd(p,q)\nprint(p//g,q//g)', tip: '比が1をまたぐ場所が二項係数の山の頂上(k≒n/2)。C(n,k)を順に計算するときの逐次更新式そのものでもあり、公式の丸暗記より使い出がある。', ins: ['4 1\n', '5 0\n', '6 2\n', '10 4\n', '8 3\n', '9 2\n'] })

t({ lv: 226, concept: 'リスト: 最頻の奇数', title: '奇数の中の人気者', tags: ['リスト', 'ハッシュ'], io: '整数列(奇数を1つ以上含む)が1行で空白区切りで与えられます。', ask: '奇数の中で最も多く現れる値を出力してください(同数なら最小の値)。', h1: '最も多い偶数(同レベル既出)の奇数版。', h2: '奇数だけをCounterに入れ、(−回数, 値)の最小を取る。', ref: 'from collections import Counter\nc=Counter(x for x in map(int,input().split()) if x%2==1)\nprint(min(c.items(),key=lambda kv:(-kv[1],kv[0]))[0])', tip: 'フィルタ付き集計はgenexpをCounterに直接渡すと1行で書ける。x%2==1は負の奇数で偽になる罠(Pythonでは−3%2は1なので実は安全)も確認しておきたい。', ins: ['1 2 3 3 5 5\n', '2 4 7\n', '9 9 1\n', '5 3 5 3 3\n', '2 2 1\n', '11 13 11 13\n'] })

t({ lv: 227, concept: 'リスト: 一度だけの値の積', title: '一匹狼たちの掛け算', tags: ['リスト', 'ハッシュ'], io: '整数列(ちょうど1回現れる値を1つ以上含む)が1行で空白区切りで与えられます。', ask: 'ちょうど1回だけ現れる値すべての積を出力してください。', h1: '1回だけの値の合計(同レベル既出)の積版。', h2: 'Counterで回数1の値を選んで掛け込む。', ref: 'from collections import Counter\nc=Counter(map(int,input().split()))\np=1\nfor x,k in c.items():\n    if k==1:\n        p*=x\nprint(p)', tip: '和の単位元が0、積の単位元が1。集計の初期値を単位元にする原則を押さえると、和→積の書き換えで初期値だけ直し忘れるバグが消える。', ins: ['2 3 2 5\n', '4\n', '1 1 2\n', '3 5 7 3\n', '6 2 6 2 9\n', '10 10 3\n'] })

t({ lv: 228, concept: 'リスト: 3回現れる値の合計', title: 'ちょうど三度現れる数', tags: ['リスト', 'ハッシュ'], io: '整数列が1行で空白区切りで与えられます。', ask: 'ちょうど3回現れる値の合計(各値は1回だけ数える)を出力してください。1つも無ければ 0 を出力してください。', h1: '2回現れる値の合計(同レベル既出)の回数違い。', h2: 'Counterのitemsで回数3を選ぶ。', ref: 'from collections import Counter\nc=Counter(map(int,input().split()))\nprint(sum(x for x,k in c.items() if k==3))', tip: '「ちょうどk回」は等号、「k回以上」は不等号と、条件の1文字が集合を変える。4回現れる値はちょうど3回には該当しない、という読み落としを試す1問。', ins: ['1 1 1 2\n', '5 5 5 2 2 2\n', '1 2 3\n', '4 4 4 4\n', '7 7 7 1 1\n', '2 2 2 3 3 3 3\n'] })

t({ lv: 229, concept: '数論: n番目の双子素数', title: '双子の素数を順に訪ねる', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: '差が2の素数の組(双子素数)を小さい方の値の順に並べ、n 番目の組の小さい方を出力してください。', h1: 'pとp+2の両方を素数判定する。', h2: '3から順に奇数を試して数える。', ref: 'n=int(input())\ndef isp(x):\n    if x<2:\n        return False\n    i=2\n    while i*i<=x:\n        if x%i==0:\n            return False\n        i+=1\n    return True\nc=0\np=1\nwhile c<n:\n    p+=2\n    if isp(p) and isp(p+2):\n        c+=1\nprint(p)', tip: '双子素数が無限にあるかは未解決だが、張益唐の2013年の突破口から「差が246以下の素数対は無限」まで詰められている。現在進行形の数学に触れる入り口。', ins: ['1\n', '2\n', '3\n', '4\n', '6\n', '5\n'] })

t({ lv: 230, concept: 'ハッシュ: 文字の種類が同じグループ数', title: '使っている文字が同じ仲間', tags: ['ハッシュ', '文字列'], io: '単語が空白区切りで1行に与えられます。', ask: '「使われている文字の種類の集合」が同じ単語を同じグループとみなしたとき、グループが何個できるかを出力してください。', h1: 'アナグラムのグループ数(同レベル既出)は文字の多重集合、こちらは集合。', h2: 'frozenset(w) をキーに集める。', ref: 'ws=input().split()\nprint(len(set(frozenset(w) for w in ws)))', tip: 'aab と ab は文字種が同じでもアナグラムではない。分類のキーを sorted(w)、frozenset(w)、len(w) と替えると分類の粗さが変わる、同値関係の設計練習。', ins: ['abc cab bca dog\n', 'aa a\n', 'ab ba abb\n', 'x y z\n', 'listen silent enlist\n', 'cat act tac dog god\n'] })

t({ lv: 231, concept: 'リスト: 隣接ANDの最大', title: '隣どうしのANDで一番強い組', tags: ['bit演算', 'リスト'], io: '整数列(2個以上)が1行で空白区切りで与えられます。', ask: '隣り合う2要素のビットANDの最大値を出力してください。', h1: 'zipで隣接ペアを作る。', h2: 'max(x&y for ...)。', ref: 'a=list(map(int,input().split()))\nprint(max(x&y for x,y in zip(a,a[1:])))', tip: 'ANDは「共通して立つビット」だけ残すので、似たビットパターンの隣人ほど大きくなる。全要素のAND(同レベル既出)が全員の共通部分なのに対し、こちらは局所の共通部分。', ins: ['5 3 6\n', '7 7\n', '1 2 4\n', '12 10 6\n', '9 9 9\n', '15 8\n'] })

export const CATALOG = TASKS
