// 生成タスク 第88波：各レベル3問化フェーズ(15)。lv725〜749, 751〜774 の薄い49段に3問目を追加。
// リスト/ハッシュ/窓/ヒープ帯。クラスタ3問まで可・言い換え水増し禁止。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 725, concept: 'リスト: 3連続以上のかたまりの数', title: '間引き候補のかたまり', tags: ['リスト'], io: '整数列が1行で空白区切りで与えられます。', ask: '同じ値が3回以上連続するかたまり(極大なもの)の個数を出力してください。', h1: 'ランレングスで数える。', h2: 'ランの長さが3以上のものをカウント。', ref: 'a=list(map(int,input().split()))\ncnt=0\ni=0\nn=len(a)\nwhile i<n:\n    j=i\n    while j<n and a[j]==a[i]:\n        j+=1\n    if j-i>=3:\n        cnt+=1\n    i=j\nprint(cnt)', tip: 'パズルゲームの「3つ揃い」検出の1次元版。極大なランで数える(4連続は1個と数える)という仕様の一言が、窓で数える解法を誤りにする。', ins: ['1 1 1 2\n', '1 2 3\n', '2 2 2 2\n', '1 1 2 2 2 3 3 3\n', '5\n', '4 4 4 1 4 4 4\n'] })

t({ lv: 726, concept: 'DP: 各列を遷移する最小落下和', title: '一番安く滑り落ちる', tags: ['DP', '行列'], io: '1行目に n、続く n 行に n×n の格子が与えられます。1行目のどこかから出発し、真下か斜め下(左右1列まで)へ降ります。', ask: '最終行までの通過マスの合計の最小を出力してください。', h1: '最大落下和(同レベル既出)の鏡像。', h2: '行ごとに上3方向のminを足す。', ref: 'n=int(input())\ng=[list(map(int,input().split())) for _ in range(n)]\ndp=g[0][:]\nfor i in range(1,n):\n    nd=[0]*n\n    for j in range(n):\n        best=dp[j]\n        if j>0 and dp[j-1]<best:\n            best=dp[j-1]\n        if j<n-1 and dp[j+1]<best:\n            best=dp[j+1]\n        nd[j]=g[i][j]+best\n    dp=nd\nprint(min(dp))', tip: '落下和(falling path sum)はLeetCode定番の名で知られる形。maxとminで境界処理が1文字も変わらないことをdiffで確かめると、DPの骨格の理解が完成する。', ins: ['2\n1 2\n3 4\n', '1\n5\n', '3\n2 1 3\n6 5 4\n7 8 9\n', '2\n-1 -2\n-3 -4\n', '3\n1 1 1\n9 1 9\n9 1 9\n', '2\n5 1\n1 5\n'] })

t({ lv: 727, concept: 'スタック: 各棒が主役でいられる幅', title: '自分が一番低い区間の広さ', tags: ['スタック'], io: 'ヒストグラムの高さの列が1行で空白区切りで与えられます(高さは相異なる)。', ask: '各棒について「その棒が最小値である極大の連続区間」の幅を、空白区切りで出力してください。', h1: '最大長方形(同レベル既出)の中身の部品。', h2: '左右それぞれ「自分より低い棒」まで伸ばす。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nout=[]\nfor i in range(n):\n    l=i\n    while l>0 and a[l-1]>a[i]:\n        l-=1\n    r=i\n    while r<n-1 and a[r+1]>a[i]:\n        r+=1\n    out.append(r-l+1)\nprint(" ".join(map(str,out)))', tip: '高さ×この幅の最大がヒストグラム最大長方形の答え。単調スタックで左右の境界を線形時間に前計算するのが本番だが、素朴版で「幅」の意味を体に入れるのが先。', ins: ['2 1 3\n', '1 2 3\n', '3 2 1\n', '5\n', '2 4 3\n', '6 2 5 4 7\n'] })

t({ lv: 728, concept: 'スタック: 深さの推移の出力', title: 'ネストの起伏を描く', tags: ['スタック'], io: '正しい括弧列が1行で与えられます。', ask: '各文字を処理した直後のネストの深さを、順に空白区切りで出力してください。', h1: '開きで+1、閉じで−1。', h2: '累積の列を出力するだけ。', ref: 's=input()\nd=0\nout=[]\nfor c in s:\n    d+=1 if c=="(" else -1\n    out.append(d)\nprint(" ".join(map(str,out)))', tip: '括弧列を山の稜線(Dyckパス)として見る変換そのもの。最大の深さ・最上位ブロック数・対応表(いずれも既出)は全部この推移の読み取りで、可視化が理解の近道と分かる。', ins: ['(())\n', '()\n', '()()\n', '(()())\n', '((()))\n', '(())()\n'] })

t({ lv: 729, concept: 'ゲーム: 半分以下しか取れない石取り', title: '欲張れない石取り合戦', tags: ['ゲーム'], io: '石の数 n (2以上) が1行で与えられます。', ask: '交互に「1個以上、今の山の半分以下」の石を取り、動けなくなった(石が1個で手番が来た)方が負けです。双方最善で先手が勝つなら first、後手なら second を出力してください。', h1: '小さいnから勝敗を埋める。', h2: '負け位置には美しい法則(2^k−1)が現れる。', ref: 'n=int(input())\nwin=[False]*(n+1)\nfor k in range(2,n+1):\n    for take in range(1,k//2+1):\n        if not win[k-take]:\n            win[k]=True\n            break\nprint("first" if win[n] else "second")', tip: '負け位置は 1, 3, 7, 15, … の 2^k−1。半分以下の制約が2進の構造を呼び込む、ゲームDPから法則を発見する楽しみの詰まった1問。', ins: ['2\n', '3\n', '4\n', '7\n', '8\n', '15\n'] })

t({ lv: 730, concept: '貪欲: 半径rでカバーする最小個数', title: '街灯を最少本数で', tags: ['貪欲'], io: '1行目に半径 r、2行目に家の位置(昇順)が与えられます。', ask: '位置 x に置いた設備は [x−r, x+r] を照らします。全ての家を照らす設備の最小個数を出力してください(設備は任意の位置に置けます)。', h1: '一番左の照らされていない家に合わせて置く。', h2: 'その家+rの位置に置くのが最も右まで届く。', ref: 'r=int(input())\nhs=list(map(int,input().split()))\ncnt=0\ncover=None\nfor h in hs:\n    if cover is None or h>cover:\n        cnt+=1\n        cover=h+2*r\nprint(cnt)', tip: '「まだの中で最左に合わせ、できるだけ右に置く」貪欲の交換論法は区間スケジューリングと同じ型。基地局配置・散水機・防犯カメラ、名前を変えて何度も出会う問題。', ins: ['1\n1 3 6\n', '2\n1 2 3\n', '0\n1 2 3\n', '5\n1 20\n', '1\n1 2 3 4 5 6 7\n', '3\n0 10 20\n'] })

t({ lv: 731, concept: '数え上げ: 1文字削って作れる単語ペア', title: '一字抜きの親子関係', tags: ['数え上げ', '文字列'], io: '相異なる単語が空白区切りで1行に与えられます。', ask: '順序対 (a, b) で「a から1文字消すと b になる」ものの個数を出力してください。', h1: '単語チェーン(同レベル既出)の1歩分の関係。', h2: '長い方から各位置を消して一致を確かめる。', ref: 'ws=input().split()\nst=set(ws)\ncnt=0\nfor w in ws:\n    seen=set()\n    for i in range(len(w)):\n        t2=w[:i]+w[i+1:]\n        if t2 in st and t2 not in seen:\n            seen.add(t2)\n            cnt+=1\nprint(cnt)', tip: '同じ単語が2通りの消し方で作れる(aab→abはどちらのaを消しても)場合の重複除去が採点の芯。チェーン(既出)のグラフの辺数を数えている。', ins: ['a ab abc\n', 'cat at\n', 'x y\n', 'aab ab\n', 'ab a b\n', 'abc ac bc\n'] })

t({ lv: 732, concept: '数え上げ: 和が3の倍数になる3つ組', title: '3人の合計を3で割ると', tags: ['数え上げ'], io: '整数列(3個以上)が1行で空白区切りで与えられます。', ask: 'i<j<k で和が3の倍数になる3つ組の個数を出力してください。', h1: '3で割った余りで分類する。', h2: '(0,0,0), (1,1,1), (2,2,2), (0,1,2) の4パターン。', ref: 'a=list(map(int,input().split()))\nc=[0,0,0]\nfor x in a:\n    c[x%3]+=1\ndef c3(m):\n    return m*(m-1)*(m-2)//6\nprint(c3(c[0])+c3(c[1])+c3(c[2])+c[0]*c[1]*c[2])', tip: '余りの組合せを尽くす場合分けは、mod計算の数え上げの王道。O(n³)の総当たりがO(n)の分類計数に潰れる圧縮率も、剰余類の威力を物語る。', ins: ['1 2 3\n', '3 6 9\n', '1 1 1\n', '1 2 4\n', '0 1 2 3\n', '1 1 2 2 3 3\n'] })

t({ lv: 733, concept: 'リスト: kごとに逆順にする', title: 'k人ずつ回れ右', tags: ['リスト'], io: '1行目に k、2行目に整数列が与えられます。', ask: '先頭から k 個ずつのグループに分け、各グループ内を逆順にした列を出力してください(末尾の端数グループも逆順にします)。', h1: 'スライスをkずつ進める。', h2: 'a[i:i+k][::-1] を連結。', ref: 'k=int(input())\na=input().split()\nout=[]\nfor i in range(0,len(a),k):\n    out+=a[i:i+k][::-1]\nprint(" ".join(out))', tip: 'ブロック転置はメモリのキャッシュライン単位の並べ替えや連結リストの古典問題(k個ずつ反転)の配列版。range(0, n, k) の3引数rangeがブロック処理の定石。', ins: ['2\n1 2 3 4 5\n', '3\n1 2 3 4 5 6\n', '1\n7 8\n', '4\n1 2\n', '2\n9 8 7 6\n', '3\n1 2 3 4\n'] })

t({ lv: 734, concept: '貪欲: 幅に詰めて何行になるか', title: '折り返しの行数勘定', tags: ['貪欲'], io: '1行目に行の幅 W、2行目に単語の長さの列が与えられます(各単語はW以下)。単語間には空白1つが必要です。', ask: '単語を順に、入るだけ詰めて折り返すとき、全体が何行になるかを出力してください。', h1: '現在行の使用幅を持ち回る。', h2: '次の単語が「+1(空白)+長さ」で入るか判定。', ref: 'W=int(input())\nws=list(map(int,input().split()))\nlines=1\ncur=ws[0]\nfor w in ws[1:]:\n    if cur+1+w<=W:\n        cur+=1+w\n    else:\n        lines+=1\n        cur=w\nprint(lines)', tip: 'テキストエディタの折り返しの最小モデル。DPで余白を均す整形(同レベル既出)の対照として、貪欲は行数最小(だが見た目は貪欲)という性質の違いが際立つ。', ins: ['10\n3 5 4\n', '5\n5 5\n', '11\n5 5 5\n', '7\n3 3 3\n', '4\n1 1 1 1\n', '20\n2 2 2\n'] })

t({ lv: 735, concept: 'シミュレーション: 空き瓶交換で飲める本数', title: '瓶を返してもう一本', tags: ['シミュレーション'], io: '1行目に最初に買う本数 n と、交換に必要な空き瓶の本数 k (k≥2) が与えられます。', ask: '空き瓶 k 本を新しい1本と交換できるとき、合計で飲める本数を出力してください。', h1: '空き瓶の数を持ち回る。', h2: '交換できる間ループ。', ref: 'n,k=map(int,input().split())\ntotal=n\nempty=n\nwhile empty>=k:\n    new=empty//k\n    total+=new\n    empty=empty%k+new\nprint(total)', tip: 'ボトルキャップ問題の名で親しまれる古典で、答えはほぼ n+⌊(n−1)/(k−1)⌋ に一致する(1本が実質k−1本分の空き瓶を消費する見方)。ループと公式の突き合わせが楽しい。', ins: ['10 3\n', '3 3\n', '2 3\n', '15 4\n', '9 3\n', '100 10\n'] })

t({ lv: 736, concept: '行列: 魔方陣の穴埋め', title: '欠けた1マスを推理する', tags: ['行列'], io: '3行に3×3の方陣が与えられます(ちょうど1箇所が 0 で、そこを埋めると魔方陣になります)。', ask: '0 のマスに入るべき値を出力してください。', h1: '完全な行(0を含まない行)の和が基準になる。', h2: '基準の和から欠けた行の和を引く。', ref: 'g=[list(map(int,input().split())) for _ in range(3)]\nlines=[]\nfor i in range(3):\n    lines.append(g[i])\n    lines.append([g[0][i],g[1][i],g[2][i]])\nlines.append([g[0][0],g[1][1],g[2][2]])\nlines.append([g[0][2],g[1][1],g[2][0]])\ntarget=next(sum(L) for L in lines if 0 not in L)\nbroken=next(L for L in lines if 0 in L)\nprint(target-sum(broken))', tip: '魔方陣の制約(全ラインの和が同じ)が強力すぎて、1マスの穴は連立を解くまでもなく引き算1回で決まる。判定問題(既出)を逆向きに使う推理の form。', ins: ['2 7 6\n9 5 1\n4 3 0\n', '0 1 6\n3 5 7\n4 9 2\n', '8 1 6\n3 0 7\n4 9 2\n', '2 9 4\n7 5 3\n6 1 0\n', '6 1 8\n7 5 3\n2 0 4\n', '4 9 2\n3 5 7\n8 0 6\n'] })

t({ lv: 737, concept: '数え上げ: 目が全て異なるサイコロの列', title: 'かぶらない出目の並び', tags: ['数え上げ'], io: '振る回数 n が1行で与えられます。', ask: 'n 回の出目の列(順序を区別)のうち、全ての目が相異なるものの数を出力してください(n>6 なら 0)。', h1: '順列の数え上げ。', h2: '6×5×4×… のn項の積。', ref: 'n=int(input())\nif n>6:\n    print(0)\nelse:\n    p=1\n    for i in range(n):\n        p*=6-i\n    print(p)', tip: '6P n(下降階乗)そのもので、n=7で必ず0になるのは鳩の巣原理。誕生日のパラドックスのサイコロ版として、重複が起きやすさの直感を修正してくれる。', ins: ['1\n', '2\n', '3\n', '6\n', '7\n', '4\n'] })

t({ lv: 738, concept: 'リスト: 等差で続く最長の区間', title: '一定ペースの最長記録', tags: ['リスト'], io: '整数列(2個以上)が1行で空白区切りで与えられます。', ask: '隣接差が一定である最長の連続区間の長さを出力してください(長さ2はどんな2要素でも等差)。', h1: '差の列を作ってランを測る。', h2: '同じ差が続く最長+1。', ref: 'a=list(map(int,input().split()))\nd=[a[i+1]-a[i] for i in range(len(a)-1)]\nbest=1\nrun=1\nfor i in range(1,len(d)):\n    if d[i]==d[i-1]:\n        run+=1\n        if run>best:\n            best=run\n    else:\n        run=1\nprint(best+1)', tip: '「元の列の性質」を「差の列のラン」に写す変換で、等差の問題群(個数・判定、既出)が全部同じ前処理を共有する。+1のオフセット(区間長=差の個数+1)が事故りどころ。', ins: ['1 3 5 7 2\n', '1 2\n', '5 5 5\n', '1 2 4 8\n', '3 6 9 12 15\n', '1 2 3 5 7 9\n'] })

t({ lv: 739, concept: '数え上げ: 等比な連続区間の個数', title: '掛け算のリズムの区間', tags: ['数え上げ'], io: '正整数の列が1行で空白区切りで与えられます。', ask: '長さ3以上の連続部分配列で、隣接する比が一定(等比)のものの個数を出力してください。', h1: '等差の個数(同レベル既出)の掛け算版。', h2: '比の一致は交差積 a[i+1]²==a[i]×a[i+2] の連続で判定。', ref: 'a=list(map(int,input().split()))\nn=len(a)\ncnt=0\nrun=0\nfor i in range(n-2):\n    if a[i+1]*a[i+1]==a[i]*a[i+2]:\n        run+=1\n        cnt+=run\n    else:\n        run=0\nprint(cnt)', tip: '「条件を満たす位置のラン」から三角数的に足し込む型の等比版。割り算を使わない交差積判定が、整数のまま等比を語る語法として3度目の登場になる。', ins: ['1 2 4 8\n', '1 2 3\n', '3 9 27\n', '1 1 1 1\n', '2 4 8 15\n', '5 5\n'] })

t({ lv: 740, concept: 'グリッド: L字の欠けブロックの数', title: '一枚欠けた田の字', tags: ['グリッド'], io: '1行目に H W、続く H 行に 0/1 の文字列が与えられます。', ask: '2×2 のブロックのうち、ちょうど3マスが1(1マスだけ0)のものの個数を出力してください。', h1: '2×2の窓を全部見る。', h2: '4マスの和が3か。', ref: 'h,w=map(int,input().split())\ng=[input() for _ in range(h)]\ncnt=0\nfor i in range(h-1):\n    for j in range(w-1):\n        s=int(g[i][j])+int(g[i][j+1])+int(g[i+1][j])+int(g[i+1][j+1])\n        if s==3:\n            cnt+=1\nprint(cnt)', tip: '2×2窓の和による分類は、画像処理の角検出(コーナーカウント)の基礎。実は「図形の角の数」はこの種の窓の集計だけで求まる、という位相幾何の入り口でもある。', ins: ['2 2\n11\n10\n', '2 2\n11\n11\n', '2 3\n110\n111\n', '3 3\n111\n101\n111\n', '1 2\n11\n', '2 4\n1011\n1110\n'] })

t({ lv: 741, concept: 'bit演算: 累積XORが0に戻る最初の位置', title: '打ち消しが完成する瞬間', tags: ['bit演算', '累積和'], io: '正整数の列が1行で空白区切りで与えられます。', ask: '先頭からの累積XORが最初に 0 になる位置(1始まり)を出力してください(最後まで0にならなければ none)。', h1: '累積XORの列(既出)を走査。', h2: '0になった瞬間にbreak。', ref: 'a=list(map(int,input().split()))\nx=0\nans="none"\nfor i,v in enumerate(a,1):\n    x^=v\n    if x==0:\n        ans=str(i)\n        break\nprint(ans)', tip: '先頭からの区間XORが0 ⇔ その区間のどのビットも偶数回現れる、という完全打ち消しの検出。パリティ検査のストリーム版で、エラーが自己相殺した最初の時点を探している。', ins: ['1 2 3\n', '5 5\n', '1 2\n', '7 7 1\n', '3 5 6\n', '4\n'] })

t({ lv: 742, concept: 'bit演算: XORが最小のペア', title: '一番そっくりな2進ペア', tags: ['bit演算', 'ソート'], io: '相異なる正整数の列(2個以上)が1行で空白区切りで与えられます。', ask: '2要素のXORの最小値を出力してください。', h1: 'XOR最大(同レベル既出)はトライが要るが、最小は簡単になる。', h2: 'ソートすると最小XORペアは必ず隣接に現れる。', ref: 'a=sorted(map(int,input().split()))\nprint(min(a[i]^a[i+1] for i in range(len(a)-1)))', tip: '「ソート後の隣接だけ見ればよい」の証明は上位ビットの一致長の議論で、最大XOR(離れたペアが最適)と綺麗に対をなす。maxとminで探索空間の構造が逆転する好例。', ins: ['1 2 3\n', '5 9\n', '4 6 7\n', '10 2 8\n', '1 4\n', '12 13 7\n'] })

t({ lv: 743, concept: '貪欲: 懐中電灯の橋渡りの最短時間', title: '夜の吊り橋を全員で', tags: ['貪欲', 'ソート'], io: '1行目に人数 n、2行目に各人の渡る時間が与えられます。橋は2人まで、渡る速さは遅い方、懐中電灯は1つで誰かが持ち帰ります。', ask: '全員が渡り終える最短時間を出力してください。', h1: '最遅の2人をどう送るかで2戦略を比べる。', h2: '「最速が往復して1人ずつ運ぶ」vs「最速2人が先導して最遅2人を一緒に送る」。', ref: 't2=sorted(map(int,input().split()))\nn=len(t2)\ntotal=0\ni=n-1\nwhile i>=3:\n    total+=min(t2[0]+2*t2[1]+t2[i],2*t2[0]+t2[i]+t2[i-1])\n    i-=2\nif i==2:\n    total+=t2[0]+t2[1]+t2[2]\nelif i==1:\n    total+=t2[1]\nelse:\n    total+=t2[0]\nprint(total)', tip: '有名な「橋とたいまつ」パズルの一般解。1,2,5,10の答えが17(15+2ではない)になる非自明さは、遅い2人をまとめて送る第2戦略の存在が生む。', ins: ['4\n1 2 5 10\n', '1\n7\n', '2\n3 8\n', '3\n1 4 6\n', '4\n1 1 1 1\n', '5\n1 2 3 4 5\n'] })

t({ lv: 744, concept: 'リスト: 折り返しペアの和の一覧', title: '両端から一組ずつ', tags: ['リスト'], io: '偶数個の整数列が1行で空白区切りで与えられます。', ask: '先頭からi番目と末尾からi番目のペアの和を、i=1から順に空白区切りで出力してください。', h1: 'a[i] と a[n−1−i]。', h2: '前半だけループ。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nprint(" ".join(str(a[i]+a[n-1-i]) for i in range(n//2)))', tip: 'ガウスの逸話(1+100, 2+99, …)の計算をそのまま出力する問題。等差数列なら全部同じ値になる、という性質が総和公式 n(a+l)/2 の視覚的証明になる。', ins: ['1 2 3 4\n', '5 5\n', '1 2 3 4 5 6\n', '10 20 30 40\n', '-1 1\n', '2 4 6 8\n'] })

t({ lv: 745, concept: '数え上げ: 文字がかぶらない単語ペア数', title: '共通文字ゼロの2語', tags: ['数え上げ', 'ハッシュ'], io: '単語が空白区切りで1行に与えられます。', ask: '使っている文字が1つも共通しない単語のペア (i<j) の個数を出力してください。', h1: '文字集合の交わりが空か。', h2: 'setのisdisjoint。', ref: 'ws=[set(w) for w in input().split()]\nn=len(ws)\nprint(sum(1 for i in range(n) for j in range(i+1,n) if ws[i].isdisjoint(ws[j])))', tip: '「かぶらないペアの長さの積の最大」という有名問題の数え上げ版。文字集合をビットマスク化すると判定が (m1&m2)==0 の1命令になる高速化も定番。', ins: ['ab cd ac\n', 'abc def\n', 'aa ab\n', 'x y z\n', 'cat dog tac\n', 'q q\n'] })

t({ lv: 746, concept: '文字列: 区間を1つ消して回文にできるか', title: 'ひと区間の切除手術', tags: ['文字列'], io: '英小文字の文字列が1行で与えられます。', ask: '連続する区間(空でもよい、全体は不可)を高々1つ取り除いて回文にできるなら yes、できなければ no を出力してください。', h1: '1文字削除(既出)の区間版。', h2: '全ての区間の除去を試す総当たりが基準解。', ref: 's=input()\nn=len(s)\ndef pal(x):\n    return x==x[::-1]\nans="yes" if pal(s) else "no"\nif ans=="no":\n    for i in range(n):\n        for j in range(i,n):\n            if (i,j)!=(0,n-1):\n                t2=s[:i]+s[j+1:]\n                if pal(t2):\n                    ans="yes"\n                    break\n        if ans=="yes":\n            break\nprint(ans)', tip: 'O(n³)の総当たりでも、両端一致を先に剥がしてから考えると実は「残りの左寄せ削除か右寄せ削除」に絞れる、という観察でO(n)にできる。素朴版はその検証台。', ins: ['abca\n', 'abcddcefba\n', 'abc\n', 'aba\n', 'ab\n', 'abcdba\n'] })

t({ lv: 747, concept: '数え上げ: 谷型の3つ組の数', title: '真ん中がへこんだ三人組', tags: ['数え上げ'], io: '整数列が1行で空白区切りで与えられます。', ask: 'i<j<k で a[j]<a[i] かつ a[j]<a[k] となる(真ん中が一番小さい)3つ組の個数を出力してください。', h1: '山型(同レベル既出)の鏡像。', h2: '各jについて左の大きい数×右の大きい数。', ref: 'a=list(map(int,input().split()))\nn=len(a)\ntotal=0\nfor j in range(n):\n    L=sum(1 for i in range(j) if a[i]>a[j])\n    R=sum(1 for k in range(j+1,n) if a[k]>a[j])\n    total+=L*R\nprint(total)', tip: '真ん中を固定して左右の候補数の積、という数え方は3つ組系の万能定石。BITで左右の計数を前計算すればO(n log n)へ、と高速化も定型に乗る。', ins: ['3 1 2\n', '1 2 3\n', '5 1 5 1 5\n', '2 2 2\n', '9 4 8\n', '4 1 3 2 5\n'] })

t({ lv: 748, concept: 'リスト: 要素ごとの大小の記号', title: '2列の勝ち負け表', tags: ['リスト'], io: '1行目と2行目に同じ長さの整数列が与えられます。', ask: '各位置について、1行目の方が大きければ >、小さければ <、等しければ = を並べた文字列を出力してください。', h1: 'zipで対応させて3分岐。', h2: '条件式の連結で1行にできる。', ref: 'a=list(map(int,input().split()))\nb=list(map(int,input().split()))\nprint("".join(">" if x>y else "<" if x<y else "=" for x,y in zip(a,b)))', tip: '対戦成績の可視化やテスト結果の差分表示の骨格。3値比較の結果を記号列に落とすと、後段の集計(勝ち数、連勝)が文字列処理に統一できる。', ins: ['3 1 2\n1 2 2\n', '5\n5\n', '1 2\n3 4\n', '9 8 7\n1 2 7\n', '0 0\n0 1\n', '4 5 6\n6 5 4\n'] })

t({ lv: 749, concept: 'DP: 飛び石の踏み順の復元', title: 'カエルの足あとの記録', tags: ['DP'], io: '1行目に石の数 n、2行目に各石の高さが与えられます。石1から石nへ、1つ先か2つ先へ跳び、コストは高さの差の絶対値です。', ask: '合計コスト最小の跳び方のうち、同コストなら「より近い石を選ぶ」規則で決まる踏み順(石の番号列)を出力してください。', h1: '後ろ向きDPで各石からのコストを確定。', h2: '前から「+1歩が同コスト以下なら+1歩」を選ぶ。', ref: 'n=int(input())\nh=list(map(int,input().split()))\nINF=10**18\ndp=[INF]*n\ndp[n-1]=0\nfor i in range(n-2,-1,-1):\n    dp[i]=abs(h[i+1]-h[i])+dp[i+1]\n    if i+2<n:\n        dp[i]=min(dp[i],abs(h[i+2]-h[i])+dp[i+2])\npath=[1]\ni=0\nwhile i<n-1:\n    if i+2>=n:\n        i+=1\n    elif abs(h[i+1]-h[i])+dp[i+1]<=abs(h[i+2]-h[i])+dp[i+2]:\n        i+=1\n    else:\n        i+=2\n    path.append(i+1)\nprint(" ".join(map(str,path)))', tip: 'Frog Jumpの復元版。「値のDP+前から貪欲」の型に、タイブレーク規則(近い石優先)を不等号の等号側に埋め込む——仕様と実装の対応が1文字単位で問われる。', ins: ['4\n10 30 40 20\n', '2\n10 10\n', '3\n10 20 10\n', '5\n30 10 60 10 60\n', '3\n1 1 1\n', '6\n1 3 2 4 6 5\n'] })

t({ lv: 751, concept: '累積和: ちょうど目標に達した日数', title: '目標ぴったりの節目', tags: ['累積和'], io: '1行目に目標 T、2行目に日ごとの数値の列が与えられます。', ask: '先頭からの累計がちょうど T になる日が何回あるかを出力してください。', h1: '累積和を走らせて一致を数える。', h2: '負の値があると複数回ありうる。', ref: 'T=int(input())\na=list(map(int,input().split()))\ns=0\ncnt=0\nfor x in a:\n    s+=x\n    if s==T:\n        cnt+=1\nprint(cnt)', tip: '売上目標の達成日、貯金の節目——「累計がちょうど」の検出は日常の集計そのもの。増減が混ざると同じ目標を何度も跨ぐ、という観察が負数の意味を教えてくれる。', ins: ['3\n1 2 3\n', '5\n5 -5 5\n', '10\n1 2 3\n', '0\n1 -1 2 -2\n', '4\n4\n', '6\n2 2 2 -2 2\n'] })

t({ lv: 752, concept: 'いもす: 二重以上に重なる長さ', title: '密になっている時間', tags: ['いもす', '区間'], io: '1行目に n、続く n 行に区間 l r ([l, r)) が与えられます。', ask: '2つ以上の区間に同時に覆われている部分の長さの合計を出力してください。', h1: 'ちょうど1回の長さ(既出)の相方。', h2: 'いもすの累積が2以上の座標を数える。', ref: 'n=int(input())\nevents=[]\nmx=0\nfor _ in range(n):\n    l,r=map(int,input().split())\n    events.append((l,1))\n    events.append((r,-1))\n    if r>mx:\n        mx=r\nimos=[0]*(mx+2)\nfor t2,d in events:\n    imos[t2]+=d\ncur=0\ntotal=0\nfor t2 in range(mx+1):\n    cur+=imos[t2]\n    if cur>=2:\n        total+=1\nprint(total)', tip: '「覆われた長さ」「ちょうど1回」「2回以上」は同じいもす配列の閾値読みだけの違い。予約のダブルブッキング時間の集計そのもので、実務の頻出クエリ。', ins: ['2\n1 4\n2 6\n', '2\n0 2\n3 5\n', '3\n0 5\n1 4\n2 3\n', '1\n0 10\n', '3\n0 3\n0 3\n0 3\n', '2\n1 5\n4 8\n'] })

t({ lv: 753, concept: '行列: 行と列の合計が最小のマス', title: '一番目立たない交差点', tags: ['行列'], io: '1行目に H W、続く H 行に整数の行列が与えられます。', ask: '各マスについて「その行の合計+その列の合計」を考え、その最小値を出力してください。', h1: '最大版(同レベル既出)の鏡像。', h2: '行和と列和を前計算して全マスO(1)。', ref: 'h,w=map(int,input().split())\ng=[list(map(int,input().split())) for _ in range(h)]\nrs=[sum(r) for r in g]\ncs=[sum(c) for c in zip(*g)]\nprint(min(rs[i]+cs[j] for i in range(h) for j in range(w)))', tip: '行和・列和の前計算でO(HW(H+W))がO(HW)に落ちる、次元分解の定番。ヒートマップの「最も冷えた十字」を探す操作で、自分自身が二重に数えられている点も仕様の要。', ins: ['2 2\n1 2\n3 4\n', '1 3\n5 1 3\n', '2 3\n1 1 1\n2 2 2\n', '2 2\n-1 5\n5 -1\n', '1 1\n7\n', '3 2\n1 0\n0 1\n2 2\n'] })

t({ lv: 754, concept: '数え上げ: 積がちょうどkの区間の数', title: '掛けてぴったりkの区間', tags: ['数え上げ'], io: '1行目に k、2行目に正整数の列が与えられます。', ask: '要素の積がちょうど k になる連続部分配列の個数を出力してください。', h1: '未満の個数(同レベル既出)の「ちょうど」版。', h2: '積がkを超えたら内側ループを打ち切れる。', ref: 'k=int(input())\na=list(map(int,input().split()))\nn=len(a)\ncnt=0\nfor i in range(n):\n    p=1\n    for j in range(i,n):\n        p*=a[j]\n        if p==k:\n            cnt+=1\n        if p>k:\n            break\nprint(cnt)', tip: '1が混ざると同じ積が長さ違いで何度も現れるのが「ちょうど」の面白さ。未満なら二点法が効くのに、ちょうどは打ち切りつき総当たりが素直、と目標の形で道具が変わる。', ins: ['6\n1 2 3\n', '4\n2 2 2\n', '1\n1 1\n', '12\n3 4 2\n', '5\n2 3\n', '8\n2 2 2 1\n'] })

t({ lv: 755, concept: '二点法: 全種類を含む最短の区間', title: '全色コンプの最短区間', tags: ['二点法'], io: '整数列が1行で空白区切りで与えられます。', ask: '列に現れる全ての種類の値を少なくとも1つずつ含む、最短の連続部分配列の長さを出力してください。', h1: '種類数を先に数える。', h2: '窓を右に伸ばし全種類入ったら左を縮める。', ref: 'a=list(map(int,input().split()))\nneed=len(set(a))\nfrom collections import defaultdict\ncnt=defaultdict(int)\nl=0\nkinds=0\nbest=len(a)\nfor r,x in enumerate(a):\n    if cnt[x]==0:\n        kinds+=1\n    cnt[x]+=1\n    while kinds==need:\n        if r-l+1<best:\n            best=r-l+1\n        cnt[a[l]]-=1\n        if cnt[a[l]]==0:\n            kinds-=1\n        l+=1\nprint(best)', tip: 'ポケモン全種を最短の期間で集める問題。最小窓部分文字列(既出)の「目標=自分自身の全種類」版で、needの数え方だけが違う兄弟になっている。', ins: ['1 2 1 3 2\n', '1 1 1\n', '1 2 3\n', '2 1 1 2\n', '5\n', '1 2 2 3 1 3\n'] })

t({ lv: 756, concept: 'ハッシュ: 同じ値の最短距離', title: '一番近い同じ顔', tags: ['ハッシュ'], io: '整数列が1行で空白区切りで与えられます。', ask: '同じ値が現れる2つの位置の距離(添字の差)の最小を出力してください(同じ値が2度現れなければ -1)。', h1: '各値の直前の出現位置を辞書で覚える。', h2: '出るたびに距離を更新。', ref: 'a=list(map(int,input().split()))\nlast={}\nbest=-1\nfor i,x in enumerate(a):\n    if x in last:\n        d=i-last[x]\n        if best<0 or d<best:\n            best=d\n    last[x]=i\nprint(best)', tip: '最短距離は必ず「同じ値の隣り合う出現」の間に現れるので、直前の位置だけ覚えれば全出現ペアを見なくてよい。ログの重複イベントの最短間隔の検出そのもの。', ins: ['1 2 1 3 2\n', '1 2 3\n', '5 5\n', '1 2 2 1\n', '7\n', '3 1 4 1 3\n'] })

t({ lv: 757, concept: 'ハッシュ: 逆さ仲間でまとめたグループ数', title: '鏡写しの単語も同じ班', tags: ['ハッシュ'], io: '単語が空白区切りで1行に与えられます。', ask: '「同じ単語、または逆さにすると同じ単語」を同じグループとみなしたとき、グループの総数を出力してください。', h1: 'アナグラムのグループ化(同レベル既出)のキー違い。', h2: '単語と逆さのうち辞書順で小さい方を代表キーにする。', ref: 'ws=input().split()\nprint(len(set(min(w,w[::-1]) for w in ws)))', tip: '同値関係のグループ化は「正規形(代表)への写像」で書くのが定石で、min(w, w[::-1])が2要素軌道の正規形。回文はどちらでも同じになり自然に1人グループになる。', ins: ['abc cba xyz\n', 'ab ba ab\n', 'aa aa\n', 'x y\n', 'stop pots tops\n', 'ab cd dc ba\n'] })

t({ lv: 758, concept: 'ハッシュ: 最頻値の一覧', title: '同率首位を全員表彰', tags: ['ハッシュ'], io: '整数列が1行で空白区切りで与えられます。', ask: '最も多く現れる値を全て、昇順に空白区切りで出力してください。', h1: '最頻回数(同レベル既出)を求めてから集める。', h2: 'その回数を持つキーを昇順ソート。', ref: 'from collections import Counter\nc=Counter(map(int,input().split()))\nm=max(c.values())\nprint(" ".join(map(str,sorted(k for k,v in c.items() if v==m))))', tip: 'モードが複数あるか(既出)のyes/noから全列挙への拡張。統計ソフトのmode関数が多値を返す仕様なのはこの問題意識で、単一値APIは情報を落としている。', ins: ['1 1 2 2 3\n', '5\n', '3 3 3 1\n', '1 2 3\n', '2 2 1 1 2 1\n', '4 4 5 5 6 6\n'] })

t({ lv: 759, concept: 'ソート: 抜かさない順位表(dense rank)', title: '銀メダルの次は2位', tags: ['ソート'], io: '得点の列が1行で空白区切りで与えられます(大きいほど上位)。', ask: '各人の順位を「同点は同順位、次の異なる得点は順位を1つだけ進める」方式(dense rank)で、入力順に空白区切りで出力してください。', h1: '同点飛ばし方式(同レベル既出)との違いは進み方。', h2: '相異なる得点を降順に並べた中での位置+1。', ref: 'a=list(map(int,input().split()))\nuniq=sorted(set(a),reverse=True)\nrank={v:i+1 for i,v in enumerate(uniq)}\nprint(" ".join(str(rank[x]) for x in a))', tip: 'SQLのDENSE_RANKとRANKの違いそのもの。1224方式(既出)と1223方式で「3位が消える」かどうかが変わる、順位の仕様バリエーションの代表2種。', ins: ['3 1 2\n', '5 5 4\n', '1 1 1\n', '10 20 30\n', '7 3 7 5\n', '2\n'] })

t({ lv: 760, concept: 'ヒープ: 2配列のペア積のk番目', title: '掛け算ペアの番付', tags: ['ヒープ', 'ソート'], io: '1行目に k、2行目と3行目に正整数の列が与えられます。', ask: '2つの列からそれぞれ1つずつ選んだ積を全て並べたとき、小さい方から k 番目の値を出力してください。', h1: 'ペア和のk番目(同レベル既出)の積版。', h2: '全部作ってソートするのが基準解。', ref: 'k=int(input())\na=list(map(int,input().split()))\nb=list(map(int,input().split()))\nps=sorted(x*y for x in a for y in b)\nprint(ps[k-1])', tip: '和なら行ごとに単調でヒープが効くが、積も正の数なら同じ単調性が立つ。負を混ぜると行の単調性が崩れる——演算と符号の組で成立条件が変わる好例。', ins: ['3\n1 2\n3 4\n', '1\n2 3\n5\n', '4\n1 2 3\n1 2\n', '2\n5\n2 3\n', '6\n2 3\n2 3 4\n', '1\n7\n7\n'] })

t({ lv: 761, concept: 'ヒープ: 逐次中央値の列', title: '増えるたびの真ん中の記録', tags: ['ヒープ'], io: '整数列が1行で空白区切りで与えられます。', ask: '先頭から1個、2個、…と読み進めるたびの中央値(偶数個のときは小さい方)を空白区切りで出力してください。', h1: '合計(同レベル既出)ではなく列そのものを出す。', h2: 'この規模なら都度ソートで十分。2つのヒープならO(n log n)。', ref: 'a=list(map(int,input().split()))\nout=[]\nfor i in range(1,len(a)+1):\n    b=sorted(a[:i])\n    out.append(b[(i-1)//2])\nprint(" ".join(map(str,out)))', tip: 'ストリーミング統計の代表例で、2つのヒープ(max-heapとmin-heap)で挟む実装が本番。「小さい方の中央値」という仕様が (i−1)//2 という添字に正確に写る。', ins: ['3 1 2\n', '5\n', '1 2 3 4\n', '2 2 2\n', '5 1 4 2\n', '9 8 7\n'] })

t({ lv: 762, concept: 'ハッシュ: 欠けている範囲の表記', title: '空席のまとめ書き', tags: ['ハッシュ'], io: '1行目に上限 N、2行目に持っている番号(1〜Nの一部、重複なし。無い場合は空行)が与えられます。', ask: '1〜N のうち欠けている番号を、連続する部分は「a-b」、単独は「a」として、空白区切りで出力してください(欠けが無ければ none)。', h1: '範囲圧縮(同レベル既出)を補集合に適用。', h2: '欠け番号の列を作って連続ランをまとめる。', ref: 'N=int(input())\nhave=set(map(int,input().split()))\nmiss=[x for x in range(1,N+1) if x not in have]\nif not miss:\n    print("none")\nelse:\n    out=[]\n    i=0\n    while i<len(miss):\n        j=i\n        while j+1<len(miss) and miss[j+1]==miss[j]+1:\n            j+=1\n        out.append(str(miss[i]) if i==j else f"{miss[i]}-{miss[j]}")\n        i=j+1\n    print(" ".join(out))', tip: 'IPアドレスの空き番管理やチケットの欠番レポートの実務フォーマット。補集合を取ってから既出の範囲圧縮を通す、2部品の直列合成で書ける。', ins: ['5\n1 2 5\n', '3\n1 2 3\n', '4\n\n', '6\n2 4 6\n', '5\n5\n', '7\n1 7\n'] })

t({ lv: 763, concept: 'ソート: 隣接差の中央値', title: '間隔の標準感覚', tags: ['ソート', '統計'], io: '偶数個(2個以上)の整数列が1行で空白区切りで与えられます。', ask: '昇順に並べたときの隣接差(n−1個、nは偶数なので奇数個)の中央値を出力してください。', h1: 'ソート→差の列→また中央値。', h2: '差の列は奇数個なので中央は一意。', ref: 'a=sorted(map(int,input().split()))\nd=sorted(a[i+1]-a[i] for i in range(len(a)-1))\nprint(d[len(d)//2])', tip: '最大隙間(既出)が外れ値なら、隙間の中央値は「典型的な間隔」を表す頑健な統計。イベントの発生間隔の分析で、平均間隔より実感に合う値を返すことが多い。', ins: ['1 3 6 10\n', '1 2\n', '5 5 5 5\n', '1 4 5 8\n', '10 20 21 40\n', '2 3 9 10\n'] })

t({ lv: 764, concept: '数え上げ: 3重転倒の数', title: '三段逆スライド', tags: ['数え上げ'], io: '整数列が1行で空白区切りで与えられます。', ask: 'i<j<k で a[i]>a[j]>a[k] となる(厳密に3段下がる)3つ組の個数を出力してください。', h1: '転倒数(同レベル既出)の3要素版。', h2: '真ん中を固定して左の大きい数×右の小さい数。', ref: 'a=list(map(int,input().split()))\nn=len(a)\ntotal=0\nfor j in range(n):\n    L=sum(1 for i in range(j) if a[i]>a[j])\n    R=sum(1 for k in range(j+1,n) if a[k]<a[j])\n    total+=L*R\nprint(total)', tip: '転倒(2要素)の一般化で、k要素版は「長さkの減少部分列の数」。真ん中固定の積の数え方が、山型・谷型の3つ組(既出)と完全に同じ骨格で通用する。', ins: ['3 2 1\n', '1 2 3\n', '4 3 2 1\n', '2 1 2 1\n', '5\n', '5 4 1 3 2\n'] })

t({ lv: 765, concept: '数え上げ: 和が素数になるペア', title: '足すと素数の縁結び', tags: ['数え上げ', '数論'], io: '正整数の列が1行で空白区切りで与えられます。', ask: 'i<j で a[i]+a[j] が素数になるペアの個数を出力してください。', h1: '平方数ペア(同レベル既出)の述語違い。', h2: '素数判定関数+総当たり。', ref: 'a=list(map(int,input().split()))\ndef isp(x):\n    if x<2:\n        return False\n    i=2\n    while i*i<=x:\n        if x%i==0:\n            return False\n        i+=1\n    return True\nn=len(a)\nprint(sum(1 for i in range(n) for j in range(i+1,n) if isp(a[i]+a[j])))', tip: '和が奇素数になるには偶数+奇数が必要(2を除く)、という偶奇の観察で高速化の枝が見える。ゴールドバッハ予想(偶数=素数+素数)の裏返しの集計でもある。', ins: ['1 2 3\n', '2 2\n', '1 1 1\n', '4 6 8\n', '1 4 6\n', '3 8 10\n'] })

t({ lv: 766, concept: 'ハッシュ: 大小文字を区別しない最頻単語', title: '大文字も小文字も同じ声', tags: ['ハッシュ', '文字列'], io: '単語が空白区切りで1行に与えられます。', ask: '大文字小文字を区別せずに数えたとき最も多く現れる単語を、小文字にして出力してください(同数なら辞書順最小)。', h1: '正規化(lower)してから数える。', h2: '(−回数, 単語)の最小。', ref: 'from collections import Counter\nc=Counter(w.lower() for w in input().split())\nprint(min(c.items(),key=lambda kv:(-kv[1],kv[0]))[0])', tip: '集計前の正規化(大文字小文字・全角半角・ゆらぎ)はテキスト処理の品質を決める前段。正規化を数え上げの内側でやるか前段でやるかの設計も、パイプラインの美学。', ins: ['Apple apple APPLE banana\n', 'a A b\n', 'Dog dog Cat cat\n', 'x\n', 'Hi hi HI ho\n', 'B b a A\n'] })

t({ lv: 767, concept: '数論: 隣どうし互いに素が続く最長', title: '仲良し隣人の最長行列', tags: ['数論'], io: '正整数の列が1行で空白区切りで与えられます。', ask: '「隣り合うどの2つも互いに素」である最長の連続部分配列の長さを出力してください。', h1: '隣接ペアの性質のランを測る。', h2: 'gcd==1が続く長さ+1。', ref: 'from math import gcd\na=list(map(int,input().split()))\nbest=1\nrun=1\nfor i in range(1,len(a)):\n    if gcd(a[i-1],a[i])==1:\n        run+=1\n        if run>best:\n            best=run\n    else:\n        run=1\nprint(best)', tip: '「隣接ペアの述語のラン+1」の型が、交互・等差・等比に続き互いに素でも再登場。gcd計算の回数はn−1回で済む、ペア述語走査の省エネ設計も共通。', ins: ['2 3 4 9\n', '2 4\n', '5\n', '6 35 6 35\n', '2 2 3 5\n', '4 9 25 49\n'] })

t({ lv: 768, concept: '累積和: 最初に和が0になる区間', title: '最初の帳消し区間', tags: ['累積和', 'ハッシュ'], io: '整数列が1行で空白区切りで与えられます。', ask: '和が0になる連続部分配列のうち、終わりの位置が最も早いもの(同じなら始まりが最も早いもの)を「l r」(1始まり)で出力してください(無ければ none)。', h1: '存在判定(同レベル既出)の位置報告版。', h2: '累積和の値が再登場した瞬間が区間の終わり。最初の出現位置を辞書に。', ref: 'a=list(map(int,input().split()))\nfirst={0:0}\ns=0\nans="none"\nfor i,x in enumerate(a,1):\n    s+=x\n    if s in first:\n        ans=f"{first[s]+1} {i}"\n        break\n    first[s]=i\nprint(ans)', tip: '「最初に見つかった瞬間にbreak」が終端最早を、辞書に最初の出現だけ残すことが始端最早を、それぞれ自動で保証する。仕様のタイブレークがデータ構造の方針に翻訳される良問。', ins: ['1 -1 2\n', '2 3 -5 1\n', '1 2 3\n', '0 5\n', '3 -1 -2 4\n', '1 -2 1 2\n'] })

t({ lv: 769, concept: '文字列: 一度だけ現れる最後の文字', title: 'しんがりの一匹狼', tags: ['文字列', 'ハッシュ'], io: '英小文字の文字列が1行で与えられます。', ask: 'ちょうど1回だけ現れる文字のうち、最も後ろに位置するものを出力してください(無ければ -)。', h1: '最初の一意文字(同レベル既出)の鏡像。', h2: '後ろから走査するか、位置の最大を取る。', ref: 'from collections import Counter\ns=input()\nc=Counter(s)\nans="-"\nfor ch in s:\n    if c[ch]==1:\n        ans=ch\nprint(ans)', tip: '前から走査して上書きし続けると「最後」が残る——逆順走査+breakと等価だが、上書き方式は「最初/最後」の切り替えがbreakの有無だけで書ける。', ins: ['abcabd\n', 'aabb\n', 'x\n', 'abab\n', 'aabbc\n', 'stress\n'] })

t({ lv: 770, concept: '数え上げ: 積が和を超えるペア', title: '掛けた方が強い2人', tags: ['数え上げ'], io: '正整数の列が1行で空白区切りで与えられます。', ask: 'i<j で a[i]×a[j] > a[i]+a[j] となるペアの個数を出力してください。', h1: '小さい値(1や2)だけが例外を作る。', h2: '総当たりで確かめるのが基準解。', ref: 'a=list(map(int,input().split()))\nn=len(a)\nprint(sum(1 for i in range(n) for j in range(i+1,n) if a[i]*a[j]>a[i]+a[j]))', tip: '(a−1)(b−1)>1 と変形すると「両方2以上、かつ(2,2)以外」が条件だと分かる。総当たりの答えを変形式のO(n)集計で検算する、式変形の練習台。', ins: ['1 2 3\n', '2 2\n', '3 4 5\n', '1 1 1\n', '2 3\n', '1 5 2 4\n'] })

t({ lv: 771, concept: 'ハッシュ: 3分の1を超える値の一覧', title: '3分の1の壁を越えた者', tags: ['ハッシュ'], io: '整数列が1行で空白区切りで与えられます。', ask: '出現回数が全体の 1/3 を厳密に超える値を、昇順に空白区切りで出力してください(無ければ none)。', h1: '個数(同レベル既出)の実体列挙版。', h2: '該当は高々2種類しかない。', ref: 'from collections import Counter\na=list(map(int,input().split()))\nc=Counter(a)\nres=sorted(k for k,v in c.items() if v*3>len(a))\nprint(" ".join(map(str,res)) if res else "none")', tip: 'n/3超は高々2つ、という鳩の巣の帰結がボイヤー・ムーア法の2候補版(有名なmajority II)を成立させる。列挙の上限が理論で先に分かっている集計は設計が締まる。', ins: ['1 1 1 2 3\n', '1 2 3\n', '2 2 3 3\n', '5 5 5\n', '1 2\n', '4 4 4 4 5 6\n'] })

t({ lv: 772, concept: '貪欲: 出現回数を揃える最小削除', title: '声の大きさを揃える', tags: ['貪欲', 'ハッシュ'], io: '英小文字の文字列が1行で与えられます。', ask: 'いくつかの文字を削除して「残った全ての文字の出現回数が同じ」になるようにするとき、削除の最小数を出力してください(全部消すのも可)。', h1: '目標の回数tを決めれば削除数が決まる。', h2: 'tの候補は現れる回数の値だけ。各文字はtまで減らすか全消し。', ref: 'from collections import Counter\ns=input()\nc=list(Counter(s).values())\nbest=len(s)\nfor t2 in set(c):\n    cost=sum(v-t2 if v>=t2 else v for v in c)\n    if cost<best:\n        best=cost\nprint(best)', tip: '「揃える先の候補は既存の値だけでよい」という離散化の論法が探索を有限にする。頻度を相異なるに(同レベル既出)と真逆の目標で、同じCounterから出発する対問題。', ins: ['aaabb\n', 'aabb\n', 'abc\n', 'aaaa\n', 'aabbbcccc\n', 'z\n'] })

t({ lv: 773, concept: '区間: 誰とも重ならない区間の数', title: '孤高のスケジュール', tags: ['区間'], io: '1行目に n、続く n 行に区間 l r が与えられます。', ask: '他のどの区間とも共有点を持たない区間の個数を出力してください。', h1: '全員と重なる区間(同レベル既出)の対極。', h2: '総当たりで重なり判定。', ref: 'n=int(input())\niv=[tuple(map(int,input().split())) for _ in range(n)]\ncnt=0\nfor i in range(n):\n    if all(i==j or max(iv[i][0],iv[j][0])>min(iv[i][1],iv[j][1]) for j in range(n)):\n        cnt+=1\nprint(cnt)', tip: 'ソートして左右の隣とだけ比べればO(n log n)にできる(重なりは隣接候補にしか起きない)。孤立区間は統合(既出)後も単独で残る成分、という見方も繋がる。', ins: ['3\n1 2\n5 6\n1 3\n', '2\n1 2\n3 4\n', '3\n1 10\n2 3\n4 5\n', '1\n0 5\n', '4\n1 2\n2 3\n5 6\n8 9\n', '2\n1 5\n2 3\n'] })

t({ lv: 774, concept: '数え上げ: 最小値がちょうどkの区間', title: '底値を指名して数える', tags: ['数え上げ'], io: '1行目に k、2行目に整数列が与えられます。', ask: '連続部分配列のうち最小値がちょうど k のものの個数を出力してください。', h1: '最大がちょうどk(同レベル既出)の鏡像。', h2: '「全要素≥k」の区間数 − 「全要素≥k+1」の区間数。', ref: 'k=int(input())\na=list(map(int,input().split()))\ndef atleast(t2):\n    total=0\n    run=0\n    for x in a:\n        if x>=t2:\n            run+=1\n            total+=run\n        else:\n            run=0\n    return total\nprint(atleast(k)-atleast(k+1))', tip: '「ちょうど=閾値集計の差」の変換がここでも決め手。閾値を満たすランの三角数和、という部品も既出のもので、差分の発想だけが新しい積み木になる。', ins: ['1\n1 2 1\n', '2\n2 2\n', '3\n1 2\n', '2\n3 2 4\n', '1\n1 1 1\n', '5\n5\n'] })

export const CATALOG = TASKS
