// 生成タスク 第30波：lv301〜330。
// 上級データ構造/アルゴリズムの踏み段。フェニック木・スパーステーブル・単調キュー(min)・
// 流れる中央値(2ヒープ)・区間DP(風船割り)・多始点BFS・DAG重み付き最長路・グリッドDijkstra など。
// lv500未満なので再帰なし(反復)。重複なし・決定的・採点一意。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 301, concept: '数論: 半完全数の判定', title: '約数をいくつか足して自分になる', tags: ['数論', 'DP'], io: '整数 n (>=1) が1行で与えられます。', ask: 'n 自身を除く約数(真の約数)の中からいくつかを選び、和をちょうど n にできるなら yes、どう選んでもできないなら no を出力してください。', h1: 'まず真の約数をすべて集める。', h2: '作れる和の集合を用意し、約数を1つずつ「足す/足さない」で広げていく。', ref: 'n=int(input())\ndivs=[d for d in range(1,n) if n%d==0]\nposs={0}\nfor d in divs:\n    poss|={p+d for p in poss if p+d<=n}\nprint("yes" if n in poss else "no")', tip: '過剰度(同レベル既出)は真の約数の和が n を超えるかを測るだけだったが、超えていても n ちょうどを組めるとは限らない。約数の列挙と部分和の考え方が合流する判定で、完全数は真の約数を全部使う特別な場合として自然にこの仲間に入る。', ins: ['6\n', '12\n', '8\n', '70\n', '20\n', '1\n'] })

t({ lv: 302, concept: '数論: 区間の素数の個数', title: '区間内の素数の個数', tags: ['数論'], io: 'L R が空白区切りで与えられます (2<=L<=R)。', ask: 'L 以上 R 以下の素数の個数を出力してください。', h1: 'エラトステネスの篩で R まで判定。', h2: '区間内の True を数える。', ref: 'l,r=map(int,input().split())\nsieve=[True]*(r+1)\nsieve[0]=False\nsieve[1]=False\ni=2\nwhile i*i<=r:\n    if sieve[i]:\n        for j in range(i*i,r+1,i):\n            sieve[j]=False\n    i+=1\nprint(sum(1 for x in range(l,r+1) if sieve[x]))', tip: '篩は合成数を倍数として消す。i*i から消し始めれば十分。', ins: ['2 10\n', '10 20\n', '2 2\n', '14 16\n', '2 100\n', '90 100\n'] })

t({ lv: 303, concept: '数論: カタラン数', title: 'n番目のカタラン数', tags: ['数論'], io: '整数 n (>=0) が1行で与えられます。', ask: 'n 番目のカタラン数 C(2n,n)/(n+1) を出力してください。', h1: 'まず C(2n,n) を整数で計算。', h2: '最後に n+1 で割る (割り切れる)。', ref: 'n=int(input())\nres=1\nfor i in range(n):\n    res=res*(2*n-i)//(i+1)\nres//=(n+1)\nprint(res)', tip: 'カタラン数は括弧列・二分木・経路など多くの数え上げに現れる。', ins: ['3\n', '0\n', '1\n', '4\n', '5\n', '10\n'] })

t({ lv: 304, concept: '累積和: 長さKの最大和', title: '長さKの連続部分配列の最大和', tags: ['累積和'], io: '1行目に n k、2行目に n 個の整数が与えられます。', ask: '長さ k の連続部分配列の和の最大値を出力してください。', h1: '最初の窓の和を作る。', h2: '窓を1つずらすたびに入る値を足し出る値を引く。', ref: 'n,k=map(int,input().split())\na=list(map(int,input().split()))\ns=sum(a[:k])\nbest=s\nfor i in range(k,n):\n    s+=a[i]-a[i-k]\n    if s>best:\n        best=s\nprint(best)', tip: '固定長の窓は差分更新で O(n) (毎回足し直さない)。', ins: ['5 2\n1 2 3 4 5\n', '3 3\n1 2 3\n', '5 1\n3 1 4 1 5\n', '4 2\n-1 -2 -3 -4\n', '6 3\n1 2 3 1 2 3\n', '1 1\n7\n'] })

t({ lv: 305, concept: '二点法: 和がT以下の最長区間', title: '和がT以下になる最長の連続部分配列', tags: ['スライディングウィンドウ'], io: '1行目に n T、2行目に n 個の正整数が与えられます。', ask: '和が T 以下になる連続部分配列の最大の長さを出力してください。', h1: '右端を伸ばし、超えたら左を縮める尺取り。', h2: '条件を満たす窓の長さの最大を取る。', ref: 'n,T=map(int,input().split())\na=list(map(int,input().split()))\nl=0\ns=0\nbest=0\nfor r in range(n):\n    s+=a[r]\n    while s>T:\n        s-=a[l]\n        l+=1\n    if r-l+1>best:\n        best=r-l+1\nprint(best)', tip: '正の値なら尺取りで O(n)。和が単調に増減する性質を使う。', ins: ['5 7\n2 1 3 2 4\n', '3 1\n2 3 4\n', '4 100\n1 2 3 4\n', '1 5\n5\n', '5 5\n1 1 1 1 1\n', '5 6\n3 1 2 1 5\n'] })

t({ lv: 306, concept: '貪欲: 作れない最小の金額', title: '部分集合の和で作れない最小の正整数', tags: ['貪欲', 'ソート'], io: '正整数列が1行で与えられます (各値はコインの額面、各1枚)。', ask: 'いくつか選んだ和では作れない最小の正整数を出力してください。', h1: '昇順にソートする。', h2: '今 1..reach-1 が作れるとき、次の値が reach 以下なら範囲が伸びる。', ref: 'a=sorted(map(int,input().split()))\nreach=1\nfor x in a:\n    if x<=reach:\n        reach+=x\n    else:\n        break\nprint(reach)', tip: '「今作れる最大+1」を超える額面が来た瞬間に穴ができる。', ins: ['1 2 3 10\n', '1 1 1\n', '2 3 4\n', '1 2 4 8\n', '5\n', '1 1 1 1 1 5 10 20\n'] })

t({ lv: 307, concept: 'DP: 整数分割の最大積', title: '整数を分割した積の最大', tags: ['dp'], io: '整数 n (>=2) が1行で与えられます。', ask: 'n を2個以上の正整数の和に分けたとき、それらの積の最大値を出力してください。', h1: 'dp[i]=i を分割した積の最大。', h2: 'j と i-j に分け、i-j はさらに分けてもよい。', ref: 'n=int(input())\ndp=[0]*(n+1)\ndp[1]=1\nfor i in range(2,n+1):\n    for j in range(1,i):\n        cand=max(j*(i-j),j*dp[i-j])\n        if cand>dp[i]:\n            dp[i]=cand\nprint(dp[n])', tip: '最適分割は3をできるだけ多く使う形になる (数学的にも示せる)。', ins: ['2\n', '10\n', '4\n', '5\n', '8\n', '11\n'] })

t({ lv: 308, concept: 'DP: 落下経路の最小和', title: 'グリッドを斜めに下る最小和', tags: ['dp', 'グリッド'], io: '1行目に n、続く n 行に n 個ずつの整数 (n×n) が与えられます。最上段の任意の列から始め、各ステップで真下・左下・右下のいずれかへ進みます。', ask: '最下段へ到達する経路上の値の合計の最小値を出力してください。', h1: '行ごとに各列の最小累計を持つ。', h2: '上の行の左・真上・右の最小 + 自分の値。', ref: 'n=int(input())\ng=[list(map(int,input().split())) for _ in range(n)]\ndp=g[0][:]\nfor i in range(1,n):\n    cur=[0]*n\n    for j in range(n):\n        best=dp[j]\n        if j>0 and dp[j-1]<best:\n            best=dp[j-1]\n        if j<n-1 and dp[j+1]<best:\n            best=dp[j+1]\n        cur[j]=g[i][j]+best\n    dp=cur\nprint(min(dp))', tip: '三角形DPの斜め移動を3方向に拡張した形。', ins: ['3\n2 1 3\n6 5 4\n7 8 9\n', '1\n5\n', '2\n1 2\n3 4\n', '3\n1 2 3\n4 5 6\n7 8 9\n', '2\n5 5\n5 5\n', '3\n100 1 100\n100 1 100\n100 1 100\n'] })

t({ lv: 309, concept: 'DP: 重み付き仕事選択の最大報酬', title: '重ならない仕事で報酬最大', tags: ['dp', 'ソート'], io: '1行目に仕事数 n、続く n 行に開始 s・終了 e・報酬 p が与えられます。', ask: '時間が重ならないように仕事を選び、報酬の合計を最大化した値を出力してください (終了と同時の開始は両立可)。', h1: '終了時刻でソートする。', h2: 'dp[i]=i番目まででの最大。直前に両立する仕事を探す。', ref: 'n=int(input())\njobs=[tuple(map(int,input().split())) for _ in range(n)]\njobs.sort(key=lambda x:x[1])\ndp=[0]*(n+1)\nfor i in range(1,n+1):\n    s,e,p=jobs[i-1]\n    best_prev=0\n    for k in range(i-1,0,-1):\n        if jobs[k-1][1]<=s:\n            best_prev=dp[k]\n            break\n    take=p+best_prev\n    dp[i]=max(dp[i-1],take)\nprint(dp[n])', tip: '報酬なしの区間スケジューリング (個数最大) の重み付き版。', ins: ['3\n1 3 50\n2 5 20\n4 6 70\n', '1\n0 10 5\n', '0\n', '3\n1 2 10\n2 3 10\n3 4 10\n', '2\n1 10 100\n2 3 50\n', '4\n1 2 5\n1 3 6\n2 4 5\n3 5 4\n'] })

t({ lv: 310, concept: 'DP: 3列の最長共通部分列', title: '3つの列の最長共通部分列', tags: ['dp'], io: '3つの整数列が各行で与えられます。', ask: '3つすべてに同じ順序で現れる共通部分列の最大の長さを出力してください。', h1: '3次元のDP表を作る。', h2: '3要素が一致で +1、違えば3方向の最大。', ref: 'a=list(map(int,input().split()))\nb=list(map(int,input().split()))\nc=list(map(int,input().split()))\nla,lb,lc=len(a),len(b),len(c)\ndp=[[[0]*(lc+1) for _ in range(lb+1)] for _ in range(la+1)]\nfor i in range(1,la+1):\n    for j in range(1,lb+1):\n        for k in range(1,lc+1):\n            if a[i-1]==b[j-1]==c[k-1]:\n                dp[i][j][k]=dp[i-1][j-1][k-1]+1\n            else:\n                dp[i][j][k]=max(dp[i-1][j][k],dp[i][j-1][k],dp[i][j][k-1])\nprint(dp[la][lb][lc])', tip: '2列LCSの自然な拡張。次元が増えても遷移の形は同じ。', ins: ['1 2 3\n2 3 4\n3 4 5\n', '1 2 3\n1 2 3\n1 2 3\n', '1 2 3\n4 5 6\n7 8 9\n', '1 2 3 4\n2 4 6\n1 2 4 8\n', '5\n5\n5\n', '1 2\n2 1\n1 2\n'] })

t({ lv: 311, concept: 'DP: ワイルドカード一致', title: 'ワイルドカードのパターン一致', tags: ['dp', '文字列'], io: '1行目に文字列 s、2行目にパターン p が与えられます。p の ? は任意の1文字、* は任意の文字列 (空も可) に一致します。', ask: 's 全体が p に一致するなら yes、しなければ no を出力してください。', h1: 'dp[i][j]=s の前 i 文字と p の前 j 文字が一致するか。', h2: '* は「使わない」か「1文字消費」の論理和。', ref: 's=input()\np=input()\nm,n=len(s),len(p)\ndp=[[False]*(n+1) for _ in range(m+1)]\ndp[0][0]=True\nfor j in range(1,n+1):\n    if p[j-1]=="*":\n        dp[0][j]=dp[0][j-1]\nfor i in range(1,m+1):\n    for j in range(1,n+1):\n        if p[j-1]=="*":\n            dp[i][j]=dp[i-1][j] or dp[i][j-1]\n        elif p[j-1]=="?" or p[j-1]==s[i-1]:\n            dp[i][j]=dp[i-1][j-1]\nprint("yes" if dp[m][n] else "no")', tip: '* の2分岐 (消費する/しない) がワイルドカードDPの核。', ins: ['abc\na?c\n', 'abcde\na*e\n', 'abc\nabd\n', 'aa\n*\n', 'ab\n?\n', '\n*\n'] })

t({ lv: 312, concept: '文字列: 回文部分文字列の個数', title: '回文になる連続部分文字列の数', tags: ['文字列'], io: '文字列 s が1行で与えられます。', ask: 's の連続部分文字列のうち回文になっているものの個数を出力してください (1文字も回文に数えます)。', h1: '各中心から左右に広げる。', h2: '奇数長と偶数長の中心を両方試す。', ref: 's=input()\nn=len(s)\ncnt=0\nfor center in range(2*n-1):\n    l=center//2\n    r=l+center%2\n    while l>=0 and r<n and s[l]==s[r]:\n        cnt+=1\n        l-=1\n        r+=1\nprint(cnt)', tip: '中心は文字 (奇数) と文字間 (偶数) の 2n-1 通り。', ins: ['abc\n', 'aaa\n', 'aba\n', 'a\n', 'abba\n', 'xyzzyx\n'] })

t({ lv: 313, concept: '文字列: アナグラムにする最小削除数', title: '2文字列をアナグラムにする最小削除数', tags: ['文字列', 'ハッシュ'], io: '2つの文字列が各行で与えられます。', ask: '両方から文字を削除して、互いにアナグラム (文字の多重集合が一致) にするのに必要な最小の削除回数を出力してください。', h1: '各文字の出現回数を数える。', h2: '文字ごとの個数の差の絶対値を合計。', ref: 'from collections import Counter\na=input()\nb=input()\nca=Counter(a)\ncb=Counter(b)\ntotal=0\nfor k in set(ca)|set(cb):\n    total+=abs(ca[k]-cb[k])\nprint(total)', tip: '多重集合の対称差の大きさ＝消すべき文字の総数。', ins: ['cde\nabc\n', 'abc\nabc\n', 'aab\nbcc\n', 'a\n\n', 'xxyy\nxy\n', 'abc\ndef\n'] })

t({ lv: 314, concept: 'グラフ: 全頂点の深さの合計', title: '根からの深さの総和', tags: ['グラフ', 'BFS'], io: '1行目に頂点数 n、続く n-1 行に木の無向辺 u v が与えられます。頂点1を根とします。', ask: '全頂点の (根からの) 深さの合計を出力してください。', h1: '根から幅優先で各頂点の深さを求める。', h2: '深さを足し合わせる。', ref: 'from collections import deque\nn=int(input())\ng=[[] for _ in range(n+1)]\nfor _ in range(n-1):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\ndist=[-1]*(n+1)\ndist[1]=0\ndq=deque([1])\ntotal=0\nwhile dq:\n    x=dq.popleft()\n    for y in g[x]:\n        if dist[y]<0:\n            dist[y]=dist[x]+1\n            total+=dist[y]\n            dq.append(y)\nprint(total)', tip: '深さの総和は木の「経路長の総量」を測る基本量。', ins: ['4\n1 2\n2 3\n3 4\n', '4\n1 2\n1 3\n1 4\n', '1\n', '2\n1 2\n', '5\n1 2\n2 3\n2 4\n4 5\n', '3\n1 2\n1 3\n'] })

t({ lv: 315, concept: 'グラフ: 二部彩色の色別頂点数の差', title: '各成分の二色サイズ差の合計', tags: ['グラフ', 'BFS'], io: '1行目に n m、続く m 行に無向辺 u v が与えられます (二部グラフを保証)。', ask: '各連結成分を2色で塗ったときの「色0の頂点数 − 色1の頂点数」の絶対値を、全成分で合計した値を出力してください。', h1: '幅優先で交互に塗りながら各色を数える。', h2: '成分ごとに差の絶対値を足す。', ref: 'from collections import deque\nn,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\ncolor=[-1]*(n+1)\nans=0\nfor s in range(1,n+1):\n    if color[s]==-1:\n        color[s]=0\n        dq=deque([s])\n        c0=1\n        c1=0\n        while dq:\n            x=dq.popleft()\n            for y in g[x]:\n                if color[y]==-1:\n                    color[y]=1-color[x]\n                    if color[y]==0:\n                        c0+=1\n                    else:\n                        c1+=1\n                    dq.append(y)\n        ans+=abs(c0-c1)\nprint(ans)', tip: '二部グラフの片側集合のサイズは独立集合などの解析に効く。', ins: ['4 3\n1 2\n2 3\n3 4\n', '3 2\n1 2\n2 3\n', '2 1\n1 2\n', '1 0\n', '5 4\n1 2\n2 3\n3 4\n4 5\n', '6 3\n1 2\n3 4\n5 6\n'] })

t({ lv: 316, concept: 'グラフ: 多始点BFSの最大距離', title: '最も近い発生源までの距離の最大', tags: ['BFS', 'グリッド'], io: '1行目に H W、続く H 行に 0/1 のグリッドが与えられます (1=発生源)。全マス通行可、4方向移動です。', ask: '各マスについて最も近い発生源までの距離を求め、その最大値を出力してください (発生源が無ければ -1)。', h1: '全発生源を同時にキューに入れて幅優先。', h2: '最後に確定する距離が最大。', ref: 'from collections import deque\nh,w=map(int,input().split())\ng=[input().split() for _ in range(h)]\ndist=[[-1]*w for _ in range(h)]\ndq=deque()\nfor i in range(h):\n    for j in range(w):\n        if g[i][j]=="1":\n            dist[i][j]=0\n            dq.append((i,j))\nwhile dq:\n    y,x=dq.popleft()\n    for dy,dx in ((1,0),(-1,0),(0,1),(0,-1)):\n        ny,nx=y+dy,x+dx\n        if 0<=ny<h and 0<=nx<w and dist[ny][nx]<0:\n            dist[ny][nx]=dist[y][x]+1\n            dq.append((ny,nx))\nbest=-1\nfor i in range(h):\n    for j in range(w):\n        if dist[i][j]>best:\n            best=dist[i][j]\nprint(best)', tip: '複数始点を同時に入れると「最も近い源までの距離」が一括で出る。', ins: ['3 3\n1 0 0\n0 0 0\n0 0 1\n', '2 2\n1 0\n0 0\n', '1 1\n0\n', '1 1\n1\n', '3 3\n0 0 0\n0 1 0\n0 0 0\n', '2 3\n1 0 0\n0 0 1\n'] })

t({ lv: 317, concept: 'グラフ: DAGの重み付き最長経路', title: 'DAGの重み付き最長経路', tags: ['トポロジカル', 'dp'], io: '1行目に n m、続く m 行に有向辺 u v w (重み w、閉路なし) が与えられます。', ask: '任意の頂点から始め任意の頂点で終わる経路の重みの合計の最大値を出力してください (辺を1本も使わない＝0も許容)。', h1: 'トポロジカル順 (Kahn) にDP。', h2: 'dp[v]=max(dp[u]+w)。', ref: 'from collections import deque\nn,m=map(int,input().split())\ng=[[] for _ in range(n+1)]\nindeg=[0]*(n+1)\nfor _ in range(m):\n    u,v,w=map(int,input().split())\n    g[u].append((v,w))\n    indeg[v]+=1\ndq=deque(i for i in range(1,n+1) if indeg[i]==0)\ndp=[0]*(n+1)\nbest=0\nwhile dq:\n    x=dq.popleft()\n    for y,w in g[x]:\n        if dp[x]+w>dp[y]:\n            dp[y]=dp[x]+w\n        if dp[y]>best:\n            best=dp[y]\n        indeg[y]-=1\n        if indeg[y]==0:\n            dq.append(y)\nprint(best)', tip: '辺数だけの最長経路を重み付きに一般化したDP。', ins: ['4 4\n1 2 3\n2 3 4\n3 4 5\n1 4 2\n', '3 0\n', '2 1\n1 2 7\n', '4 3\n1 2 1\n1 3 10\n3 4 1\n', '5 4\n1 2 2\n2 3 2\n3 4 2\n4 5 2\n', '3 2\n1 2 5\n1 3 3\n'] })

t({ lv: 318, concept: 'グラフ: 木の半径', title: '木の半径 (最小の離心数)', tags: ['グラフ', 'BFS'], io: '1行目に頂点数 n、続く n-1 行に木の無向辺 u v が与えられます。', ask: '各頂点の離心数 (その頂点から最も遠い頂点までの距離) のうち、最小値 (木の半径) を出力してください。', h1: '各頂点を始点にBFSして離心数を求める。', h2: 'その最小が半径。', ref: 'from collections import deque\nn=int(input())\ng=[[] for _ in range(n+1)]\nfor _ in range(n-1):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\nbest=n\nfor s in range(1,n+1):\n    dist=[-1]*(n+1)\n    dist[s]=0\n    dq=deque([s])\n    ecc=0\n    while dq:\n        x=dq.popleft()\n        for y in g[x]:\n            if dist[y]<0:\n                dist[y]=dist[x]+1\n                if dist[y]>ecc:\n                    ecc=dist[y]\n                dq.append(y)\n    if ecc<best:\n        best=ecc\nprint(best)', tip: '半径は中心の離心数。直径とともに木の「広がり」を表す。', ins: ['4\n1 2\n2 3\n3 4\n', '1\n', '3\n1 2\n2 3\n', '5\n1 2\n1 3\n1 4\n1 5\n', '2\n1 2\n', '7\n1 2\n2 3\n3 4\n4 5\n5 6\n6 7\n'] })

t({ lv: 319, concept: 'データ構造: フェニック木の区間和', title: '更新つき区間和 (フェニック木)', tags: ['データ構造'], io: '1行目に n q、2行目に n 個の初期値、続く q 行に "add i x" (位置 i に x を加算、0始まり) または "sum l r" (区間 [l,r] の和を求める) が与えられます。', ask: 'すべての "sum" 操作の結果の合計を出力してください。', h1: '部分和を木構造 (BIT) で持つ。', h2: 'i += i&(-i) で更新、i -= i&(-i) で前方和。', ref: 'n,q=map(int,input().split())\na=list(map(int,input().split()))\nbit=[0]*(n+1)\ndef update(i,x):\n    i+=1\n    while i<=n:\n        bit[i]+=x\n        i+=i&(-i)\ndef pref(i):\n    s=0\n    i+=1\n    while i>0:\n        s+=bit[i]\n        i-=i&(-i)\n    return s\nfor idx in range(n):\n    update(idx,a[idx])\ntotal=0\nfor _ in range(q):\n    op=input().split()\n    if op[0]=="add":\n        update(int(op[1]),int(op[2]))\n    else:\n        l=int(op[1])\n        r=int(op[2])\n        total+=pref(r)-(pref(l-1) if l>0 else 0)\nprint(total)', tip: 'BIT は更新も区間和も O(log n)。i&(-i) が最下位ビットを取り出す。', ins: ['5 3\n1 2 3 4 5\nsum 0 4\nadd 2 10\nsum 0 4\n', '3 2\n1 1 1\nsum 0 0\nsum 0 2\n', '1 1\n5\nsum 0 0\n', '4 3\n0 0 0 0\nadd 1 5\nadd 3 7\nsum 0 3\n', '3 1\n1 2 3\nsum 1 2\n', '5 2\n1 2 3 4 5\nadd 0 100\nsum 0 0\n'] })

t({ lv: 320, concept: 'データ構造: 区間最小(前計算)', title: '区間最小クエリ (スパーステーブル)', tags: ['データ構造'], io: '1行目に n q、2行目に n 個の整数、続く q 行に l r (0始まりの閉区間) が与えられます。', ask: '各クエリの区間最小値を求め、その合計を出力してください。', h1: '長さ 2^k の区間の最小を前計算する。', h2: '区間 [l,r] は2つの 2^j 区間の重ね合わせで覆える。', ref: 'n,q=map(int,input().split())\na=list(map(int,input().split()))\nsp=[a[:]]\nk=1\nwhile (1<<k)<=n:\n    prev=sp[k-1]\n    half=1<<(k-1)\n    cur=[0]*(n-(1<<k)+1)\n    for i in range(len(cur)):\n        cur[i]=min(prev[i],prev[i+half])\n    sp.append(cur)\n    k+=1\ntotal=0\nfor _ in range(q):\n    l,r=map(int,input().split())\n    length=r-l+1\n    j=length.bit_length()-1\n    total+=min(sp[j][l],sp[j][r-(1<<j)+1])\nprint(total)', tip: '冪等な演算 (min/max/gcd) は区間が重なってもよいので O(1) で答えられる。', ins: ['5 2\n3 1 4 1 5\n0 4\n1 3\n', '3 1\n5 2 8\n0 2\n', '1 1\n7\n0 0\n', '4 2\n4 3 2 1\n0 1\n2 3\n', '5 1\n1 2 3 4 5\n2 2\n', '6 2\n9 8 7 6 5 4\n0 5\n0 2\n'] })

t({ lv: 321, concept: '単調キュー: 各窓の最小値', title: 'スライディング窓の最小値の合計', tags: ['単調スタック', 'スライディングウィンドウ'], io: '1行目に n k、2行目に n 個の整数が与えられます。', ask: '長さ k の窓を左から右へずらしたときの各窓の最小値の合計を出力してください。', h1: '単調増加デックに添字を保つ。', h2: '末尾の大きい値を捨て、窓外の先頭を捨てる。', ref: 'from collections import deque\nn,k=map(int,input().split())\na=list(map(int,input().split()))\ndq=deque()\ntotal=0\nfor i in range(n):\n    while dq and a[dq[-1]]>=a[i]:\n        dq.pop()\n    dq.append(i)\n    if dq[0]<=i-k:\n        dq.popleft()\n    if i>=k-1:\n        total+=a[dq[0]]\nprint(total)', tip: '単調キューは各窓の最小/最大を全体 O(n) で求める道具。', ins: ['6 3\n1 3 -1 -3 5 3\n', '4 2\n4 3 2 1\n', '3 3\n1 2 3\n', '5 1\n5 4 3 2 1\n', '5 2\n1 2 3 4 5\n', '4 4\n2 2 2 2\n'] })

t({ lv: 322, concept: 'ヒープ: 流れる中央値', title: '逐次追加での中央値の合計', tags: ['heapq'], io: '整数列が1行で与えられます。', ask: '左から1個ずつ追加していき、その都度の下側中央値 (個数が偶数なら小さい方) を求め、全ステップ分の合計を出力してください。', h1: '小さい半分を最大ヒープ、大きい半分を最小ヒープで持つ。', h2: '2つのサイズ差を1以内に保つと中央値が頂点で取れる。', ref: 'import heapq\na=list(map(int,input().split()))\nlow=[]\nhigh=[]\ntotal=0\nfor x in a:\n    if not low or x<=-low[0]:\n        heapq.heappush(low,-x)\n    else:\n        heapq.heappush(high,x)\n    if len(low)>len(high)+1:\n        heapq.heappush(high,-heapq.heappop(low))\n    elif len(high)>len(low):\n        heapq.heappush(low,-heapq.heappop(high))\n    total+=-low[0]\nprint(total)', tip: '2つのヒープで中央値を O(log n)/追加 で維持できる古典テク。', ins: ['1 2 3 4 5\n', '5 4 3 2 1\n', '1\n', '2 2 2\n', '3 1 4 1 5\n', '10 20 30\n'] })

t({ lv: 323, concept: 'スライディングウィンドウ: k個の0を反転した最長の1', title: 'k回反転で作れる最長の連続1', tags: ['スライディングウィンドウ'], io: '1行目に n k、2行目に n 個の 0/1 が与えられます。', ask: '高々 k 個の 0 を 1 に変えてよいとき、連続する 1 の最大の長さを出力してください。', h1: '窓内の0の個数を数える。', h2: '0が k を超えたら左を縮める。', ref: 'n,k=map(int,input().split())\na=list(map(int,input().split()))\nl=0\nzeros=0\nbest=0\nfor r in range(n):\n    if a[r]==0:\n        zeros+=1\n    while zeros>k:\n        if a[l]==0:\n            zeros-=1\n        l+=1\n    if r-l+1>best:\n        best=r-l+1\nprint(best)', tip: '「条件を満たす最長窓」の典型。0の個数を制約に尺取り。', ins: ['6 1\n1 0 1 1 0 1\n', '5 0\n1 1 0 1 1\n', '4 2\n0 0 0 0\n', '3 3\n0 0 0\n', '5 1\n1 1 1 1 1\n', '7 2\n1 0 0 1 1 0 1\n'] })

t({ lv: 324, concept: 'DP: 金額を作る最大硬貨数', title: '金額をちょうど作る最大硬貨枚数', tags: ['dp'], io: '1行目に金額 X と硬貨の種類数 n、2行目に n 種類の額面が与えられます。各額面は何枚でも使えます。', ask: 'X をちょうど作るときに使う硬貨の最大枚数を出力してください。作れないなら -1 を出力してください。', h1: 'dp[v]=金額vを作る最大枚数 (作れなければ負)。', h2: 'min ではなく max を取る。', ref: 'x,n=map(int,input().split())\ncoins=list(map(int,input().split()))\ndp=[-1]*(x+1)\ndp[0]=0\nfor v in range(1,x+1):\n    for c in coins:\n        if c<=v and dp[v-c]>=0 and dp[v-c]+1>dp[v]:\n            dp[v]=dp[v-c]+1\nprint(dp[x])', tip: '最小枚数DPの max 版。到達不能を負で表すのがコツ。', ins: ['11 3\n1 2 5\n', '3 1\n2\n', '0 1\n5\n', '6 2\n2 3\n', '10 2\n2 5\n', '5 1\n5\n'] })

t({ lv: 325, concept: 'DP: 数字列のデコード方法数', title: '数字列を文字に復号する方法の数', tags: ['dp', '文字列'], io: '数字のみの文字列が1行で与えられます。', ask: '各数字を 1→A, …, 26→Z に対応づけて復号する方法の数を出力してください (1桁または2桁ずつ。先頭0や0単独、27以上の2桁は復号できません)。', h1: 'dp[i]=先頭 i 文字の復号方法数。', h2: '1桁(0以外)と2桁(10〜26)の可否で加算。', ref: 's=input()\nn=len(s)\nif n==0 or s[0]=="0":\n    print(0)\nelse:\n    dp=[0]*(n+1)\n    dp[0]=1\n    dp[1]=1\n    for i in range(2,n+1):\n        if s[i-1]!="0":\n            dp[i]+=dp[i-1]\n        two=int(s[i-2:i])\n        if 10<=two<=26:\n            dp[i]+=dp[i-2]\n    print(dp[n])', tip: '「1文字使う/2文字使う」の分岐は段の上り方DPと同じ骨格。', ins: ['12\n', '226\n', '0\n', '10\n', '27\n', '111\n'] })

t({ lv: 326, concept: 'グラフ: 隣接行列の連結成分数', title: '隣接行列から連結成分を数える', tags: ['グラフ', 'BFS'], io: '1行目に n、続く n 行に n×n の 0/1 隣接行列 (対称、対角は0) が与えられます。', ask: '連結成分の個数を出力してください。', h1: '未訪問の頂点から幅優先。', h2: '行 g[x] の 1 を隣接とみなす。', ref: 'from collections import deque\nn=int(input())\ng=[input().split() for _ in range(n)]\nseen=[False]*n\ncnt=0\nfor s in range(n):\n    if not seen[s]:\n        cnt+=1\n        seen[s]=True\n        dq=deque([s])\n        while dq:\n            x=dq.popleft()\n            for y in range(n):\n                if g[x][y]=="1" and not seen[y]:\n                    seen[y]=True\n                    dq.append(y)\nprint(cnt)', tip: '隣接行列でも隣接リストでも連結成分の数え方は同じ。', ins: ['3\n0 1 0\n1 0 0\n0 0 0\n', '1\n0\n', '4\n0 1 1 1\n1 0 1 1\n1 1 0 1\n1 1 1 0\n', '2\n0 0\n0 0\n', '4\n0 1 0 0\n1 0 0 0\n0 0 0 1\n0 0 1 0\n', '3\n0 0 0\n0 0 0\n0 0 0\n'] })

t({ lv: 327, concept: '数論: 階乗の末尾ゼロの数', title: '階乗の末尾に並ぶ0の個数', tags: ['数論'], io: '整数 n (>=0) が1行で与えられます。', ask: 'n! の末尾に連続して並ぶ0の個数を出力してください。', h1: '末尾0の数は因数5の個数で決まる。', h2: 'n//5 + n//25 + n//125 + …。', ref: 'n=int(input())\nc=0\np=5\nwhile p<=n:\n    c+=n//p\n    p*=5\nprint(c)', tip: '10=2×5 で2は5より多いので、5の個数だけ数えれば足りる。', ins: ['5\n', '10\n', '25\n', '0\n', '100\n', '4\n'] })

t({ lv: 328, concept: '区間DP: 風船割りの最大スコア', title: '風船を割る順序で得点最大', tags: ['区間DP', 'dp'], io: '整数列が1行で与えられます (各風船に書かれた数)。両端の外側には1があるとみなします。', ask: '風船を1つずつ割り、割るとき (左隣)×(自分)×(右隣) を得点に加える (隣は既に割れていれば外側へ繋がる) とき、得られる総得点の最大値を出力してください。', h1: '区間 (l,r) で「最後に割る風船 k」を全探索。', h2: 'dp[l][r]=max(dp[l][k]+dp[k][r]+v[l]*v[k]*v[r])。', ref: 'a=list(map(int,input().split()))\nv=[1]+a+[1]\nm=len(v)\ndp=[[0]*m for _ in range(m)]\nfor length in range(2,m):\n    for l in range(0,m-length):\n        r=l+length\n        best=0\n        for k in range(l+1,r):\n            cand=dp[l][k]+dp[k][r]+v[l]*v[k]*v[r]\n            if cand>best:\n                best=cand\n        dp[l][r]=best\nprint(dp[0][m-1])', tip: '「最後に割る要素」で分けるのが区間DPの発想転換。', ins: ['3 1 5 8\n', '1\n', '1 5\n', '2 3\n', '5\n', '3 1 5\n'] })

t({ lv: 329, concept: '文字列: 複数文字列の最長共通接頭辞', title: '全単語に共通する最長接頭辞の長さ', tags: ['文字列'], io: '1行目に単語数 n、続く n 行に文字列が与えられます。', ask: 'すべての文字列に共通する最長の接頭辞の長さを出力してください。', h1: '先頭の単語を基準にする。', h2: '各単語と先頭から一致する長さを縮めていく。', ref: 'n=int(input())\nws=[input() for _ in range(n)]\nif n==0:\n    print(0)\nelse:\n    base=ws[0]\n    p=len(base)\n    for w in ws[1:]:\n        i=0\n        while i<p and i<len(w) and w[i]==base[i]:\n            i+=1\n        p=i\n    print(p)', tip: '共通接頭辞は1つずつ突き合わせれば十分。短くなる一方なので速い。', ins: ['3\nflower\nflow\nflight\n', '2\nabc\nabc\n', '3\na\nb\nc\n', '1\nhello\n', '2\nprefix\npre\n', '3\nxyz\nxya\nxyb\n'] })

t({ lv: 330, concept: 'グラフ: グリッドのコスト最小経路', title: 'コスト付きグリッドの最小コスト経路', tags: ['グラフ', 'heapq'], io: '1行目に H W、続く H 行に W 個の非負整数 (マスのコスト) が与えられます。左上から右下へ4方向に移動し、経路コストは通過した全マスのコストの和 (始点含む) です。', ask: '右下までの最小コストを出力してください。', h1: '優先度付きキューで距離が小さい順に確定 (ダイクストラ)。', h2: 'マスへ入るたびそのマスのコストを加える。', ref: 'import heapq\nh,w=map(int,input().split())\ng=[list(map(int,input().split())) for _ in range(h)]\nINF=float("inf")\ndist=[[INF]*w for _ in range(h)]\ndist[0][0]=g[0][0]\npq=[(g[0][0],0,0)]\nwhile pq:\n    d,y,x=heapq.heappop(pq)\n    if d>dist[y][x]:\n        continue\n    for dy,dx in ((1,0),(-1,0),(0,1),(0,-1)):\n        ny,nx=y+dy,x+dx\n        if 0<=ny<h and 0<=nx<w:\n            nd=d+g[ny][nx]\n            if nd<dist[ny][nx]:\n                dist[ny][nx]=nd\n                heapq.heappush(pq,(nd,ny,nx))\nprint(dist[h-1][w-1])', tip: '4方向移動はDPで解けないのでダイクストラ。0-1BFSの一般化。', ins: ['3 3\n1 1 1\n1 9 1\n1 1 1\n', '1 1\n5\n', '2 2\n1 2\n3 4\n', '2 3\n1 1 1\n1 1 1\n', '3 1\n1\n2\n3\n', '3 3\n1 2 3\n4 5 6\n7 8 9\n'] })

export const CATALOG = TASKS
