// 生成タスク 第22波：lv86〜104 の空き段を別計算で埋める。既存と重複しない概念のみ。
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 86, concept: 'リスト: 総変動', title: '隣接差の絶対値の和', tags: ['list'], io: '整数列が1行で与えられます。', ask: '隣り合う要素の差の絶対値をすべて足したものを出力してください。', h1: '|aᵢ₊₁−aᵢ| を足す。', h2: '総変動(total variation)。', ref: 'a=list(map(int,input().split()))\nprint(sum(abs(a[i+1]-a[i]) for i in range(len(a)-1)))', ins: ['1 3 2 5\n', '5 5 5\n', '1 2 3 4\n', '10 1 10\n', '7\n', '4 4 1\n'] })
t({ lv: 87, concept: 'リスト: 最頻値と回数', title: '最頻値とその回数', tags: ['collections'], io: '整数列が1行で与えられます。', ask: '最も多い値とその回数を空白区切りで出力してください。', h1: 'Counter。', h2: 'most_common(1)。', ref: 'from collections import Counter\nc=Counter(map(int,input().split()))\nv,n=c.most_common(1)[0]\nprint(v,n)', ins: ['1 1 2 3 3 3\n', '5 5 5\n', '1 2 3\n', '7 7 8\n', '4\n', '9 9 9 1\n'] })
t({ lv: 88, concept: 'リスト: 最大と最小の積', title: '最大値と最小値の積', tags: ['list'], io: '整数列が1行で与えられます。', ask: '最大値と最小値の積を出力してください。', h1: 'max と min。', h2: '掛ける。', ref: 'a=list(map(int,input().split()))\nprint(max(a)*min(a))', ins: ['1 2 3 4\n', '5 5\n', '-2 3\n', '10\n', '0 9\n', '3 1 4 1 5\n'] })
t({ lv: 89, concept: 'リスト: 偶数番目の和', title: '偶数番目の要素の和', tags: ['list', 'スライス'], io: '整数列が1行で与えられます。', ask: '0番目, 2番目, 4番目, … の要素の和を出力してください。', h1: 'スライス [::2]。', h2: 'その和。', ref: 'a=list(map(int,input().split()))\nprint(sum(a[::2]))', ins: ['1 2 3 4 5\n', '10 20 30\n', '7\n', '1 1 1 1\n', '5 4 3 2\n', '9 8 7 6 5\n'] })
t({ lv: 91, concept: 'リスト: 連続偶数の最長', title: '連続する偶数の最長の長さ', tags: ['list'], io: '整数列が1行で与えられます。', ask: '偶数が連続する最長の長さを出力してください。', h1: '偶数で伸ばしリセット。', h2: '最大を更新。', ref: 'a=list(map(int,input().split()))\nbest=cur=0\nfor x in a:\n    cur=cur+1 if x%2==0 else 0\n    best=max(best,cur)\nprint(best)', ins: ['2 4 1 6 8\n', '1 3 5\n', '2 4 6 8\n', '7\n', '1 2 4 6\n', '3 3 2 2 2\n'] })
t({ lv: 92, concept: 'リスト: 中央値以上の個数', title: '中央値以上の要素の個数', tags: ['list', 'ソート'], io: '整数列が1行で与えられます。', ask: '中央値 (ソートして真ん中) 以上の要素の個数を出力してください。', h1: '中央値を求める。', h2: '>= で数える。', ref: 'a=list(map(int,input().split()))\ns=sorted(a)\nmed=s[len(s)//2]\nprint(sum(1 for x in a if x>=med))', ins: ['1 2 3 4 5\n', '5 5 5\n', '3 1 2\n', '10 1 100\n', '7\n', '4 4 4 4\n'] })
t({ lv: 93, concept: 'リスト: 隣接和の最大', title: '隣り合う2数の和の最大', tags: ['list'], io: '2個以上の整数列が1行で与えられます。', ask: '隣り合う2要素の和の最大を出力してください。', h1: 'a[i]+a[i+1]。', h2: 'その最大。', ref: 'a=list(map(int,input().split()))\nprint(max(a[i]+a[i+1] for i in range(len(a)-1)))', ins: ['1 5 4 2\n', '3 6 1\n', '5 5\n', '10 1 100\n', '2 3 4\n', '9 1 8\n'] })
t({ lv: 94, concept: 'リスト: 前半と後半の差', title: '前半と後半の和の差', tags: ['list', 'スライス'], io: '整数列が1行で与えられます。', ask: '前半 (前から floor(n/2) 個) の和と残りの和の差の絶対値を出力してください。', h1: '半分で分ける。', h2: '2つの和の差の絶対値。', ref: 'a=list(map(int,input().split()))\nh=len(a)//2\nprint(abs(sum(a[:h])-sum(a[h:])))', ins: ['1 2 3 4\n', '1 1 1 1\n', '10\n', '5 5 5 5\n', '1 2 3\n', '100 1\n'] })
t({ lv: 96, concept: '文字列: 部分列判定', title: '部分列かどうか', tags: ['文字列', '二点ポインタ'], io: '2つの文字列 a, b が各行で与えられます。', ask: 'a が b の部分列 (順序を保って一部を取り出すと一致) なら yes、違えば no を出力してください。', h1: 'b を順に走査。', h2: 'a の各文字を順に消費。', ref: 'a=input()\nb=input()\nit=iter(b)\nprint("yes" if all(c in it for c in a) else "no")', ins: ['ace\nabcde\n', 'aec\nabcde\n', 'abc\nabc\n', 'xyz\nxxyyzz\n', 'a\nb\n', '\nabc\n'], tip: '💡 iter と「c in it」で部分列判定が簡潔に書ける。' })
t({ lv: 97, concept: '文字列: 共通文字の種類', title: '2語の共通文字の種類数', tags: ['set'], io: '2つの文字列が各行で与えられます。', ask: '両方に現れる文字の種類数を出力してください。', h1: '集合の積。', h2: 'len(a&b)。', ref: 'a=set(input())\nb=set(input())\nprint(len(a&b))', ins: ['abc\nbcd\n', 'aaa\nbbb\n', 'xyz\nxyz\n', 'abc\ndef\n', 'a\na\n', 'hello\nworld\n'] })
t({ lv: 98, concept: '文字列: ランレングス復号', title: 'ランレングス復号', tags: ['文字列'], io: '「文字+繰り返し数」が並んだ文字列 (例: a3b2) が与えられます。', ask: '元の文字列に復元して出力してください (例: a3b2 → aaabb)。', h1: '文字の後の数字を読む。', h2: '文字×回数を連結。', ref: 's=input()\nr=""\ni=0\nwhile i<len(s):\n    ch=s[i]\n    j=i+1\n    while j<len(s) and s[j].isdigit():\n        j+=1\n    r+=ch*int(s[i+1:j])\n    i=j\nprint(r)', ins: ['a3b2\n', 'x1\n', 'a1b1c1\n', 'z5\n', 'a2b3a1\n', 'q4\n'] })
t({ lv: 99, concept: '文字列: 初出位置の和', title: '各文字の初出位置の和', tags: ['文字列'], io: '文字列 s が与えられます。', ask: '各文字が初めて現れた位置 (0始まり) を、文字の種類ごとに合計して出力してください。', h1: '初出だけ記録。', h2: '位置を足す。', ref: 's=input()\nseen=set()\ntotal=0\nfor i,c in enumerate(s):\n    if c not in seen:\n        seen.add(c)\n        total+=i\nprint(total)', ins: ['abcabc\n', 'aaa\n', 'abc\n', 'xyzzyx\n', 'a\n', 'banana\n'] })
t({ lv: 101, concept: 'リスト: 等しい隣接ペア', title: '等しい隣接ペアの数', tags: ['list'], io: '整数列が1行で与えられます。', ask: '隣り合う要素が等しいペアの個数を出力してください。', h1: 'a[i]==a[i+1] を数える。', h2: '隣接比較。', ref: 'a=list(map(int,input().split()))\nprint(sum(1 for i in range(len(a)-1) if a[i]==a[i+1]))', ins: ['1 1 2 2 2 3\n', '1 2 3\n', '5 5\n', '7\n', '1 1 1 1\n', '3 3 1 1\n'] })
t({ lv: 102, concept: 'リスト: 最長プラトー', title: '同じ値が続く最長の長さ', tags: ['list'], io: '整数列が1行で与えられます。', ask: '同じ値が連続する最長の長さを出力してください。', h1: '前と同じなら伸ばす。', h2: '最大を更新。', ref: 'a=list(map(int,input().split()))\nbest=cur=1\nfor i in range(1,len(a)):\n    cur=cur+1 if a[i]==a[i-1] else 1\n    best=max(best,cur)\nprint(best)', ins: ['1 1 2 2 2 3\n', '1 2 3\n', '5 5 5 5\n', '7\n', '1 2 2 1\n', '9 9 9 1 1\n'] })
t({ lv: 103, concept: 'リスト: 山(ピーク)の数', title: '山(両隣より大きい)の数', tags: ['list'], io: '整数列が1行で与えられます。', ask: '両隣より大きい要素 (端は除く) の個数を出力してください。', h1: '内側だけ見る。', h2: '左右より大きいか。', ref: 'a=list(map(int,input().split()))\nprint(sum(1 for i in range(1,len(a)-1) if a[i]>a[i-1] and a[i]>a[i+1]))', ins: ['1 3 2 5 4\n', '1 2 3\n', '3 1 3 1 3\n', '5\n', '1 5 1\n', '2 2 2\n'] })
t({ lv: 104, concept: 'リスト: 谷の数', title: '谷(両隣より小さい)の数', tags: ['list'], io: '整数列が1行で与えられます。', ask: '両隣より小さい要素 (端は除く) の個数を出力してください。', h1: '内側だけ見る。', h2: '左右より小さいか。', ref: 'a=list(map(int,input().split()))\nprint(sum(1 for i in range(1,len(a)-1) if a[i]<a[i-1] and a[i]<a[i+1]))', ins: ['3 1 4 1 5\n', '3 2 1\n', '5 1 5 1 5\n', '7\n', '5 1 5\n', '2 2 2\n'] })

export const CATALOG = TASKS
