// 生成タスク 第5波。すべて別の計算(オリジナル)。1タスク=1問。
const TASKS = []
const t = (obj) => TASKS.push(obj)

const L = ['3 1 4 1 5\n', '2 7 1 8 2\n', '5 4 3 2 1\n', '1 2 3 4 5\n', '9 1 2 8 3\n', '10 20 30\n']

// ---- 配列アルゴリズム (lv50) ----
const NK = ['5 2\n3 1 4 1 5\n', '4 1\n9 2 6 5\n', '3 3\n1 2 3\n', '5 5\n5 4 3 2 1\n', '6 2\n10 20 30 40 50 60\n', '3 2\n7 7 8\n']
t({ lv: 50, concept: '配列: k番目に小さい値', title: 'k番目に小さい値', tags: ['ソート', 'list'], io: '1行目に n k、2行目に n 個の整数が与えられます。', ask: '小さい方から k 番目の値を出力してください。', h1: 'ソートして k-1 番目。', h2: '0始まりに注意。', ref: 'n,k=map(int,input().split())\na=sorted(map(int,input().split()))\nprint(a[k-1])', ins: NK })
t({ lv: 50, concept: '配列: 最長の連続増加長', title: '最長の連続増加部分列の長さ', tags: ['list', 'ループ'], io: '空白区切りの整数列が1行で与えられます。', ask: '隣り合う要素が増加し続ける最長の長さを出力してください。', h1: '増えていれば伸ばす、崩れたら1に。', h2: '最大を更新。', ref: 'a=list(map(int,input().split()))\nbest=cur=1\nfor i in range(1,len(a)):\n    cur=cur+1 if a[i]>a[i-1] else 1\n    best=max(best,cur)\nprint(best)', ins: L })
t({ lv: 50, concept: '配列: 1回売買の最大利益', title: '1回の売買で得られる最大利益', tags: ['list', 'ループ'], io: '日ごとの価格を表す整数列が1行で与えられます。', ask: '1回だけ買って後で売るときの最大利益 (利益が出なければ0) を出力してください。', h1: 'これまでの最安値を覚える。', h2: '今の価格−最安値の最大。', ref: 'a=list(map(int,input().split()))\nmn=a[0]\nbest=0\nfor x in a:\n    best=max(best,x-mn)\n    mn=min(mn,x)\nprint(best)', ins: ['7 1 5 3 6 4\n', '7 6 5 4 3\n', '1 2 3 4 5\n', '3 3 3\n', '2 4 1 7\n', '5 1\n'], tip: '💡 「最安値を覚えながら差の最大」を1走査で。' })
const ROT = ['1 2 3 4 5\n2\n', '1 2 3\n0\n', '1 2 3 4\n4\n', '5 6 7\n1\n', '10 20\n3\n', '1 2 3 4 5\n5\n']
t({ lv: 50, concept: '配列: 左回転', title: '配列を左に k 回転', tags: ['list', 'スライス'], io: '1行目に整数列、2行目に回転量 k が与えられます。', ask: '左に k 個ぶん回転させた列を空白区切りで出力してください。', h1: 'k を長さで割った余りに。', h2: 'a[k:]+a[:k]。', ref: 'a=list(map(int,input().split()))\nk=int(input())%len(a)\nprint(*(a[k:]+a[:k]))', ins: ROT })
t({ lv: 50, concept: '配列: 単調増加か', title: '狭義単調増加か', tags: ['list', 'any/all'], io: '空白区切りの整数列が1行で与えられます。', ask: '常に前より大きくなっていれば yes、そうでなければ no を出力してください。', h1: '隣接で a[i]<a[i+1]。', h2: 'all で全チェック。', ref: 'a=list(map(int,input().split()))\nprint("yes" if all(a[i]<a[i+1] for i in range(len(a)-1)) else "no")', ins: L })
t({ lv: 50, concept: '配列: 山型か', title: '山型の列か', tags: ['list', 'ループ'], io: '空白区切りの整数列が1行で与えられます。', ask: '増加してから減少する「山型」なら yes、そうでなければ no を出力してください (単調増加・単調減少は no)。', h1: '増加区間を登り切る。', h2: '頂点が両端でなく、その後ずっと減少。', ref: 'a=list(map(int,input().split()))\nn=len(a)\ni=0\nwhile i+1<n and a[i]<a[i+1]:\n    i+=1\nif i==0 or i==n-1:\n    print("no")\nelse:\n    while i+1<n and a[i]>a[i+1]:\n        i+=1\n    print("yes" if i==n-1 else "no")', ins: ['1 3 2\n', '1 2 3\n', '3 2 1\n', '1 5 5 2\n', '2 4 6 4 1\n', '1 3 2 4\n'] })
t({ lv: 50, concept: '配列: すべて同じか', title: '全要素が同じか', tags: ['set'], io: '空白区切りの整数列が1行で与えられます。', ask: 'すべて同じ値なら yes、違えば no を出力してください。', h1: 'set にすると1種類。', h2: 'len(set)==1。', ref: 'a=input().split()\nprint("yes" if len(set(a))==1 else "no")', ins: ['5 5 5\n', '1 2 1\n', '7\n', '3 3 3 3\n', '9 9 8\n', '0 0\n'] })
t({ lv: 50, concept: '配列: 最頻値の回数', title: '最頻値の出現回数', tags: ['collections', 'Counter'], io: '空白区切りの整数列が1行で与えられます。', ask: '最も多く現れる値の「出現回数」を出力してください。', h1: 'Counter で数える。', h2: 'most_common(1) の回数。', ref: 'from collections import Counter\na=input().split()\nprint(Counter(a).most_common(1)[0][1])', ins: ['1 1 2 3 3 3\n', '5 5 5\n', '1 2 3\n', '7 7 8 8\n', '4\n', '9 9 9 1 1\n'] })
const PK = ['5 8\n3 5 1 7 2\n', '4 6\n1 2 3 4\n', '3 10\n5 5 5\n', '4 7\n7 0 7 0\n', '5 5\n1 2 3 4 5\n', '2 3\n1 2\n']
t({ lv: 50, concept: '配列: 和がkのペア数', title: '和が k になるペアの個数', tags: ['全探索', 'list'], io: '1行目に n k、2行目に n 個の整数が与えられます。', ask: '異なる2要素 (位置 i<j) の和が k になる組の個数を出力してください。', h1: '2重ループで全ペア。', h2: 'i<j で重複を防ぐ。', ref: 'n,k=map(int,input().split())\na=list(map(int,input().split()))\nc=0\nfor i in range(n):\n    for j in range(i+1,n):\n        if a[i]+a[j]==k:\n            c+=1\nprint(c)', ins: PK })
t({ lv: 50, concept: '配列: 2番目に小さい値', title: '2番目に小さい値', tags: ['ソート', 'set'], io: '空白区切りの整数列 (異なる値を2つ以上含む) が1行で与えられます。', ask: '2番目に小さい値を出力してください。', h1: '重複除去してソート。', h2: '前から2番目。', ref: 'a=sorted(set(map(int,input().split())))\nprint(a[1])', ins: ['3 1 4 1 5\n', '9 2 6 5\n', '1 2\n', '7 8 9\n', '10 1 100 50 2\n', '8 6 4 2\n'] })

// ---- 文字列処理2 (lv45) ----
t({ lv: 45, concept: '文字列: 大文字の数', title: '大文字の個数', tags: ['文字列'], io: '1行の文字列 s が与えられます。', ask: '大文字アルファベットの個数を出力してください。', h1: '.isupper() を数える。', h2: '内包で件数。', ref: 's=input()\nprint(sum(1 for c in s if c.isupper()))', ins: ['Hello World\n', 'ABC\n', 'abc\n', 'PyThOn\n', '123\n', 'A1b2\n'] })
t({ lv: 45, concept: '文字列: 数字の数', title: '数字の個数', tags: ['文字列'], io: '1行の文字列 s が与えられます。', ask: '数字 (0-9) の個数を出力してください。', h1: '.isdigit()。', h2: '件数。', ref: 's=input()\nprint(sum(1 for c in s if c.isdigit()))', ins: ['a1b2c3\n', 'abc\n', '12345\n', 'Year2024\n', '...\n', 'x9\n'] })
t({ lv: 45, concept: '文字列: 母音を除去', title: '母音を取り除く', tags: ['文字列'], io: '英小文字の文字列 s が与えられます。', ask: '母音 (a,i,u,e,o) を取り除いた文字列を出力してください。', h1: '母音でない文字だけ連結。', h2: 'c not in "aiueo"。', ref: 's=input()\nprint("".join(c for c in s if c not in "aiueo"))', ins: ['hello\n', 'programming\n', 'aiueo\n', 'sky\n', 'banana\n', 'rhythm\n'] })
t({ lv: 45, concept: '文字列: ランレングス符号化', title: 'ランレングス符号化', tags: ['文字列', 'ループ'], io: '英小文字の文字列 s が与えられます。', ask: '連続する同じ文字を「文字+連続数」にまとめて出力してください (例: aaabb → a3b2)。', h1: '同じ文字が続く区間を測る。', h2: '区間ごとに文字+長さ。', ref: 's=input()\nr=[]\ni=0\nwhile i<len(s):\n    j=i\n    while j<len(s) and s[j]==s[i]:\n        j+=1\n    r.append(s[i]+str(j-i))\n    i=j\nprint("".join(r))', ins: ['aaabb\n', 'abc\n', 'aaaa\n', 'aabbaa\n', 'x\n', 'mississippi\n'], tip: '💡 ランレングス圧縮は画像や連長データの基本。' })
t({ lv: 45, concept: '文字列: ROT13', title: 'ROT13 暗号', tags: ['文字列'], io: '英字を含む文字列 s が与えられます。', ask: '各英字を13文字ずらした ROT13 を出力してください (英字以外はそのまま)。', h1: '13ずらして 26 で剰余。', h2: '大文字小文字それぞれ。', ref: 's=input()\nr=""\nfor c in s:\n    if c.islower():\n        r+=chr((ord(c)-97+13)%26+97)\n    elif c.isupper():\n        r+=chr((ord(c)-65+13)%26+65)\n    else:\n        r+=c\nprint(r)', ins: ['hello\n', 'Hello World\n', 'abc\n', 'xyz\n', 'ROT13\n', 'a-b\n'], tip: '💡 ROT13 はもう一度かけると元に戻る対称暗号。' })
t({ lv: 45, concept: '文字列: 各単語を反転', title: '各単語を反転 (並びは保持)', tags: ['文字列', 'split'], io: '空白区切りの単語からなる1行が与えられます。', ask: '各単語の文字を反転し、単語の並びはそのままにして出力してください。', h1: '単語ごとに [::-1]。', h2: "' '.join。", ref: "s=input()\nprint(' '.join(w[::-1] for w in s.split()))", ins: ['hello world\n', 'abc def\n', 'a b c\n', 'racecar level\n', 'one\n', 'Python is fun\n'] })
t({ lv: 45, concept: '文字列: 文字頻度を昇順で', title: '各文字の出現回数 (文字昇順)', tags: ['文字列', 'collections'], io: '英小文字の文字列 s が与えられます。', ask: '出現する文字を昇順に、「文字+回数」を続けて出力してください (例: aab → a2b1)。', h1: 'Counter で数える。', h2: 'sorted で文字順に。', ref: 'from collections import Counter\ns=input()\nc=Counter(s)\nprint("".join(f"{ch}{c[ch]}" for ch in sorted(c)))', ins: ['aab\n', 'banana\n', 'abc\n', 'zzz\n', 'cba\n', 'mississippi\n'] })
const CP = ['flower\nflight\n', 'abc\nabd\n', 'same\nsame\n', 'x\ny\n', 'prefix\npre\n', 'ab\nabc\n']
t({ lv: 45, concept: '文字列: 最長共通接頭辞', title: '2語の最長共通接頭辞', tags: ['文字列'], io: '2つの文字列が各行で与えられます。', ask: '先頭から一致する最長の共通部分 (なければ空行) を出力してください。', h1: '先頭から1文字ずつ比較。', h2: '違ったら止める。', ref: 'a=input()\nb=input()\ni=0\nwhile i<len(a) and i<len(b) and a[i]==b[i]:\n    i+=1\nprint(a[:i])', ins: CP })

// ---- 数論・組合せ2 (lv130) ----
const AB = ['12 8\n', '7 3\n', '10 10\n', '100 7\n', '5 20\n', '9 6\n']
t({ lv: 130, concept: '数論: 互いに素か', title: '2数が互いに素か', tags: ['数論', '素数'], io: '2つの正の整数 a b が空白区切りで与えられます。', ask: '最大公約数が1 (互いに素) なら yes、違えば no を出力してください。', h1: 'gcd を計算。', h2: '==1 か。', ref: 'import math\na,b=map(int,input().split())\nprint("yes" if math.gcd(a,b)==1 else "no")', ins: AB })
t({ lv: 130, concept: '数論: ハミング距離', title: '2数のハミング距離', tags: ['ビット演算', '数論'], io: '2つの非負整数 a b が空白区切りで与えられます。', ask: '2進表現で異なるビットの個数を出力してください。', h1: 'a^b で差分ビット。', h2: 'popcount。', ref: 'a,b=map(int,input().split())\nprint(bin(a^b).count("1"))', ins: AB, tip: '💡 XOR して立っているビット数 = ハミング距離。' })
t({ lv: 130, concept: '数論: グレイコード', title: 'グレイコードに変換', tags: ['ビット演算'], io: '非負整数 n が与えられます。', ask: 'n に対応するグレイコードの値を出力してください (n ^ (n>>1))。', h1: 'n ^ (n>>1)。', h2: '隣接で1ビットだけ変わる符号。', ref: 'n=int(input())\nprint(n^(n>>1))', ins: ['0\n', '1\n', '2\n', '3\n', '10\n', '255\n'] })
const DIG = ['1234\n', '9\n', '5050\n', '321\n', '405\n', '40\n']
t({ lv: 130, concept: '数論: 各桁の階乗の和', title: '各桁の階乗の和', tags: ['整数', '数論'], io: '非負整数 n が与えられます。', ask: '各桁の階乗を合計して出力してください (例: 145 → 1!+4!+5!)。', h1: 'math.factorial を桁ごと。', h2: '合計。', ref: 'import math\nn=input()\nprint(sum(math.factorial(int(c)) for c in n))', ins: ['145\n', '40585\n', '123\n', '0\n', '9\n', '100\n'] })
t({ lv: 130, concept: '数論: 桁を降順に並べた数', title: '桁を降順に並べた数', tags: ['整数', 'ソート'], io: '非負整数 n が与えられます。', ask: '桁を大きい順に並べ替えてできる数を出力してください。', h1: 'str をソート(降順)。', h2: 'int に戻す。', ref: 'n=input()\nprint(int("".join(sorted(n,reverse=True))))', ins: DIG })
t({ lv: 130, concept: '数論: カプレカ操作', title: 'カプレカ操作 (4桁)', tags: ['整数', 'ソート'], io: '4桁以内の非負整数 n が与えられます。', ask: '4桁ゼロ埋めし「桁を降順に並べた数 − 昇順に並べた数」を出力してください。', h1: 'zfill(4) で4桁化。', h2: '降順−昇順。', ref: 'n=input().zfill(4)\nhi=int("".join(sorted(n,reverse=True)))\nlo=int("".join(sorted(n)))\nprint(hi-lo)', ins: ['3524\n', '1000\n', '2111\n', '9831\n', '1234\n', '6174\n'], tip: '💡 4桁でこれを繰り返すと多くが 6174 (カプレカ数) に収束する。' })
t({ lv: 130, concept: '数論: パスカルの三角形の行', title: 'パスカルの三角形の第n行', tags: ['組合せ'], io: '非負整数 n が与えられます。', ask: 'パスカルの三角形の第 n 行 (nC0, nC1, ..., nCn) を空白区切りで出力してください。', h1: 'math.comb(n,k)。', h2: 'k=0..n。', ref: 'import math\nn=int(input())\nprint(*[math.comb(n,k) for k in range(n+1)])', ins: ['4\n', '0\n', '1\n', '5\n', '6\n', '2\n'] })
const NN = ['12\n', '7\n', '100\n', '1\n', '50\n', '36\n']
t({ lv: 130, concept: '数論: n以下の素数の和', title: 'n以下の素数の和', tags: ['素数', '篩'], io: '整数 n が与えられます。', ask: 'n 以下の素数をすべて足した和を出力してください。', h1: 'エラトステネスの篩。', h2: 'True の添字を合計。', ref: 'n=int(input())\nif n<2:\n    print(0)\nelse:\n    s=[True]*(n+1)\n    s[0]=s[1]=False\n    i=2\n    while i*i<=n:\n        if s[i]:\n            for j in range(i*i,n+1,i):\n                s[j]=False\n        i+=1\n    print(sum(i for i in range(n+1) if s[i]))', ins: NN })
t({ lv: 130, concept: '数論: 2進の最長連続1', title: '2進表現の最長連続1', tags: ['ビット演算'], io: '正の整数 n が与えられます。', ask: 'n を2進数で見たときの「1が連続する最長の長さ」を出力してください。', h1: 'bin(n) を 0 で分割。', h2: '1の塊の最大長。', ref: 'n=int(input())\nprint(max(len(r) for r in bin(n)[2:].split("0")))', ins: ['5\n', '7\n', '10\n', '255\n', '1\n', '21\n'] })

// ---- 分類2 (lv6) ----
const ABC = ['3 1 2\n', '5 5 5\n', '9 1 4\n', '2 8 6\n', '1 1 2\n', '7 3 5\n']
t({ lv: 6, concept: '分類: 3数の中央値', title: '3数の中央値', tags: ['ソート', '条件分岐'], io: '3つの整数 a b c が空白区切りで与えられます。', ask: '中央の値 (2番目に大きい値) を出力してください。', h1: 'ソートして真ん中。', h2: 'sorted(...)[1]。', ref: 'print(sorted(map(int,input().split()))[1])', ins: ABC })
t({ lv: 6, concept: '分類: 3数を昇順に', title: '3数を昇順に並べる', tags: ['ソート'], io: '3つの整数 a b c が空白区切りで与えられます。', ask: '小さい順に空白区切りで出力してください。', h1: 'sorted。', h2: 'print(*...)。', ref: 'print(*sorted(map(int,input().split())))', ins: ABC })
const MD = ['2024 2\n', '2023 2\n', '2024 1\n', '2024 4\n', '2000 2\n', '1900 2\n']
t({ lv: 6, concept: '分類: 月の日数', title: 'その月の日数', tags: ['datetime'], io: '年 月 が空白区切りで与えられます。', ask: 'その月が何日あるかを出力してください (うるう年を考慮)。', h1: 'calendar.monthrange。', h2: '戻り値の2番目が日数。', ref: 'import calendar\ny,m=map(int,input().split())\nprint(calendar.monthrange(y,m)[1])', ins: MD })
t({ lv: 6, concept: '分類: 3つの多数決', title: '3つの0/1の多数決', tags: ['条件分岐'], io: '3つの値 (0 または 1) が空白区切りで与えられます。', ask: '多い方の値 (0 か 1) を出力してください。', h1: '合計が2以上なら1。', h2: 'sum>=2。', ref: 'a=list(map(int,input().split()))\nprint(1 if sum(a)>=2 else 0)', ins: ['1 0 1\n', '0 0 0\n', '1 1 1\n', '0 1 0\n', '1 1 0\n', '0 0 1\n'] })

export const CATALOG = TASKS
