// 生成タスク 第43波：lv851〜899。最高難度帯(競プロ上級〜)。
// 高度な数論(totient/mobius/約数関数/floor和/CRT)・畳み込み(FWHT)・行列累乗・
// 文字列構造(Manacher計数/Lyndon/Z)・グラフ/DP最適化(min cost flow/Hungarian/CHT/BM)。
// lv421〜450(Miller-Rabin/Pollard/Lucas/BSGS/Tonelli/原始根/Pell)とは別アルゴリズム。
// 重複なし・決定的・採点一意。無限ループ無し。
const MOD = 1000000007
const TASKS = []
const t = (obj) => TASKS.push(obj)

t({ lv: 851, concept: '畳み込み: 多項式の積', title: '2つの多項式の積の係数', tags: ['数学'], io: '1行目に多項式A(次数昇順の係数列)、2行目に多項式Bが与えられます。', ask: 'A·B の係数を次数昇順に空白区切りで出力してください。', h1: '各項の積を次数ごとに足す。', h2: '大規模ではFFT/NTTで O(n log n)。', ref: 'A=list(map(int,input().split()))\nB=list(map(int,input().split()))\nn=len(A)\nm=len(B)\nres=[0]*(n+m-1)\nfor i in range(n):\n    for j in range(m):\n        res[i+j]+=A[i]*B[j]\nprint(*res)', tip: '多項式積=畳み込み。要素数が大きいときはFFT/NTTで O(n log n) に高速化する。', ins: ['1 2\n1 3\n', '1 1 1\n1 1\n', '0 1\n0 1\n', '5\n2\n', '1 2 3\n4 5 6\n', '1 0 1\n1 0 1\n'] })

t({ lv: 852, concept: '畳み込み: XOR畳み込み(FWHT)', title: 'XOR畳み込みの結果', tags: ['bit演算', '数学'], io: '1行目に n(2のべき長)、2行目に長さ n の列 A、3行目に長さ n の列 B が与えられます。', ask: 'C[k]=Σ_{i^j==k} A[i]·B[j] を k=0..n-1 で空白区切り出力してください。', h1: 'AとBに高速ウォルシュ変換を適用。', h2: '各点積を取り逆変換する(FWHT)。', ref: 'n=int(input())\nA=list(map(int,input().split()))\nB=list(map(int,input().split()))\ndef fwht(a):\n    h=1\n    while h<len(a):\n        for i in range(0,len(a),h*2):\n            for j in range(i,i+h):\n                x=a[j]\n                y=a[j+h]\n                a[j]=x+y\n                a[j+h]=x-y\n        h*=2\nfa=A[:]\nfb=B[:]\nfwht(fa)\nfwht(fb)\nfc=[fa[i]*fb[i] for i in range(n)]\nfwht(fc)\nres=[c//n for c in fc]\nprint(*res)', tip: 'XOR畳み込みは高速ウォルシュ・アダマール変換(FWHT)で。変換→各点積→逆変換(最後にnで割る)。', ins: ['2\n1 2\n3 4\n', '1\n5\n5\n', '4\n1 0 0 0\n1 2 3 4\n', '2\n1 1\n1 1\n', '4\n1 1 1 1\n1 1 1 1\n', '2\n2 3\n0 1\n'] })

t({ lv: 853, concept: '畳み込み: AND畳み込み', title: 'AND畳み込みの結果', tags: ['bit演算', '数学'], io: '1行目に n(2のべき長)、2行目に長さ n の列 A、3行目に長さ n の列 B が与えられます。', ask: 'C[k]=Σ_{i&j==k} A[i]·B[j] を k=0..n-1 で空白区切り出力してください。', h1: '上位集合和変換(superset SOS)を行う。', h2: '各点積後に逆変換する。', ref: 'n=int(input())\nA=list(map(int,input().split()))\nB=list(map(int,input().split()))\nbits=(n-1).bit_length()\ndef sos_super(a,inv):\n    for i in range(bits):\n        for mask in range(n):\n            if not (mask>>i)&1:\n                if inv:\n                    a[mask]-=a[mask|(1<<i)]\n                else:\n                    a[mask]+=a[mask|(1<<i)]\nfa=A[:]\nfb=B[:]\nsos_super(fa,False)\nsos_super(fb,False)\nfc=[fa[i]*fb[i] for i in range(n)]\nsos_super(fc,True)\nprint(*fc)', tip: 'AND畳み込みは「上位集合和(superset sum)」変換を使う。SOS DPの双対で各点積後に逆変換。', ins: ['2\n1 2\n3 4\n', '1\n5\n5\n', '4\n1 0 0 0\n1 2 3 4\n', '2\n1 1\n1 1\n', '4\n1 1 1 1\n1 1 1 1\n', '2\n2 3\n0 1\n'] })

t({ lv: 854, concept: '畳み込み: OR畳み込み', title: 'OR畳み込みの結果', tags: ['bit演算', '数学'], io: '1行目に n(2のべき長)、2行目に長さ n の列 A、3行目に長さ n の列 B が与えられます。', ask: 'C[k]=Σ_{i|j==k} A[i]·B[j] を k=0..n-1 で空白区切り出力してください。', h1: '部分集合和変換(SOS)を行う。', h2: '各点積後に逆変換する。', ref: 'n=int(input())\nA=list(map(int,input().split()))\nB=list(map(int,input().split()))\nbits=(n-1).bit_length()\ndef sos_sub(a,inv):\n    for i in range(bits):\n        for mask in range(n):\n            if (mask>>i)&1:\n                if inv:\n                    a[mask]-=a[mask^(1<<i)]\n                else:\n                    a[mask]+=a[mask^(1<<i)]\nfa=A[:]\nfb=B[:]\nsos_sub(fa,False)\nsos_sub(fb,False)\nfc=[fa[i]*fb[i] for i in range(n)]\nsos_sub(fc,True)\nprint(*fc)', tip: 'OR畳み込みは部分集合和(subset sum, SOS)変換を使う。各点積後に逆変換で復元する。', ins: ['2\n1 2\n3 4\n', '1\n5\n5\n', '4\n1 0 0 0\n1 2 3 4\n', '2\n1 1\n1 1\n', '4\n1 1 1 1\n1 1 1 1\n', '2\n2 3\n0 1\n'] })

t({ lv: 855, concept: '行列累乗: 線形漸化式のk項目', title: '線形漸化式のk項目(行列累乗)', tags: ['数学', 'dp'], io: '1行目に次数 d と項番号 k、2行目に係数 c1..cd(a[n]=Σc_i·a[n-i])、3行目に初項 a0..a_{d-1} が与えられます。', ask: 'a[k] を 1000000007 で割った余りを出力してください。', h1: 'd×d の遷移行列を作る。', h2: '行列を k 乗して初項ベクトルに掛ける。', ref: `import sys\nfirst=input().split()\nd=int(first[0])\nk=int(first[1])\nc=list(map(int,input().split()))\na=list(map(int,input().split()))\nMOD=${MOD}\nif k<d:\n    print(a[k]%MOD)\nelse:\n    def matmul(A,B):\n        n=len(A)\n        m=len(B[0])\n        p=len(B)\n        C=[[0]*m for _ in range(n)]\n        for i in range(n):\n            for l in range(p):\n                if A[i][l]:\n                    ail=A[i][l]\n                    for j in range(m):\n                        C[i][j]=(C[i][j]+ail*B[l][j])%MOD\n        return C\n    M=[[0]*d for _ in range(d)]\n    for i in range(d):\n        M[0][i]=c[i]%MOD\n    for i in range(1,d):\n        M[i][i-1]=1\n    def matpow(M,e):\n        n=len(M)\n        R=[[1 if i==j else 0 for j in range(n)] for i in range(n)]\n        while e>0:\n            if e&1:\n                R=matmul(R,M)\n            M=matmul(M,M)\n            e>>=1\n        return R\n    P=matpow(M,k-(d-1))\n    vec=[a[d-1-i] for i in range(d)]\n    res=0\n    for i in range(d):\n        res=(res+P[0][i]*vec[i])%MOD\n    print(res)`, tip: '線形漸化式のk項目は遷移行列のk乗で O(d³ log k)。フィボナッチの一般化。', ins: ['2 10\n1 1\n0 1\n', '2 5\n1 1\n0 1\n', '1 5\n2\n1\n', '2 0\n1 1\n3 5\n', '3 6\n1 1 1\n0 0 1\n', '2 1\n1 1\n0 1\n'] })

t({ lv: 856, concept: '行列累乗: 長さkの経路数', title: '長さkの有向路の数(隣接行列のk乗)', tags: ['グラフ', '数学'], io: '1行目に n k s tn、続く n 行に n×n の隣接行列(0/1)が与えられます。', ask: '頂点 s から t へちょうど k 辺で行く経路数を 1000000007 で割った余りで出力してください(s,t は0始まり)。', h1: '隣接行列を k 乗する。', h2: '(s,t) 成分が経路数。', ref: `first=input().split()\nn=int(first[0])\nk=int(first[1])\ns=int(first[2])\ntt=int(first[3])\nMOD=${MOD}\nA=[list(map(int,input().split())) for _ in range(n)]\ndef matmul(X,Y):\n    C=[[0]*n for _ in range(n)]\n    for i in range(n):\n        for l in range(n):\n            if X[i][l]:\n                xil=X[i][l]\n                for j in range(n):\n                    C[i][j]=(C[i][j]+xil*Y[l][j])%MOD\n    return C\nR=[[1 if i==j else 0 for j in range(n)] for i in range(n)]\nM=[row[:] for row in A]\ne=k\nwhile e>0:\n    if e&1:\n        R=matmul(R,M)\n    M=matmul(M,M)\n    e>>=1\nprint(R[s][tt]%MOD)`, tip: '長さkの経路数は隣接行列のk乗の成分。行列累乗で O(n³ log k)。', ins: ['2 5 0 1\n1 1\n1 0\n', '3 4 0 0\n0 1 1\n1 0 1\n1 1 0\n', '5 3 0 4\n0 1 1 0 0\n0 0 1 1 0\n0 0 0 1 1\n0 0 0 0 1\n0 0 0 0 0\n', '3 5 0 0\n0 1 0\n0 0 1\n1 0 0\n', '3 4 0 1\n1 1 1\n1 1 1\n1 1 1\n', '4 5 0 2\n0 1 1 0\n1 0 1 1\n1 1 0 1\n0 1 1 0\n'] })

t({ lv: 857, concept: '数論: トーシェントが2のべきになる数の個数', title: 'トーシェントが2のべきになる数', tags: ['数論'], io: '1行に正整数 N が与えられます。', ask: '1 以上 N 以下の整数 n のうち、オイラーのトーシェント関数 phi(n) の値が 2 のべき乗(1, 2, 4, 8, ...)になるものの個数を出力してください。', h1: '篩の要領で 1 から N までの phi をまとめて求められる。', h2: 'v が2のべきかどうかは v & (v-1) が 0 かで判定できる。', ref: 'n=int(input())\nphi=list(range(n+1))\nfor p in range(2,n+1):\n    if phi[p]==p:\n        for m in range(p,n+1,p):\n            phi[m]-=phi[m]//p\nc=0\nfor x in range(1,n+1):\n    v=phi[x]\n    if v>0 and (v&(v-1))==0:\n        c+=1\nprint(c)', tip: 'phi を1つずつ試し割りで出す(既出)代わりに、篩と同じ形で全部まとめて作れる。phi が2のべきになる数は、定規とコンパスで正n角形が作図できる数と一致するという古い定理につながっている。', ins: ['1', '5', '10', '20', '50', '100'] })

t({ lv: 858, concept: '数論: トーシェント和', title: '1からnまでのφの総和', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: 'Σ_{i=1}^{n} φ(i) を出力してください。', h1: '篩で各 φ を求める。', h2: '線形篩/エラトステネス風に更新して合計。', ref: 'n=int(input())\nphi=list(range(n+1))\nfor p in range(2,n+1):\n    if phi[p]==p:\n        for k in range(p,n+1,p):\n            phi[k]-=phi[k]//p\nprint(sum(phi[1:n+1]))', tip: 'トーシェント和は篩で全 φ を一括計算する。Σφ(i) は約 3n²/π² に近い。', ins: ['5\n', '1\n', '10\n', '2\n', '100\n', '20\n'] })

t({ lv: 859, concept: '数論: メビウス関数', title: 'メビウス関数μ(n)', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: 'μ(n)(平方因子を持てば0、相異なる素因数 k 個なら(-1)^k)を出力してください。', h1: '素因数分解する。', h2: '同じ素因数が2回出たら0。', ref: 'n=int(input())\nm=n\ncnt=0\np=2\nmu=1\nwhile p*p<=m:\n    if m%p==0:\n        m//=p\n        cnt+=1\n        if m%p==0:\n            mu=0\n            break\n    p+=1\nif mu!=0:\n    if m>1:\n        cnt+=1\n    mu=(-1)**cnt\nprint(mu if n>=1 else 0)', tip: 'メビウス関数は平方因子があれば0、なければ素因数の個数の偶奇で±1。包除原理の核。', ins: ['1\n', '2\n', '6\n', '4\n', '30\n', '12\n'] })

t({ lv: 860, concept: '数論: 平方因子を持たない数の個数', title: 'n以下の平方因子なし整数の数', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: '1以上 n 以下で平方因子を持たない(square-free)整数の個数を出力してください。', h1: 'メビウス関数で包除する。', h2: 'Σ_{d} μ(d)·floor(n/d²)。', ref: 'import math\nn=int(input())\nlimit=int(math.isqrt(n))\nmu=[0]*(limit+1)\nmu[1]=1 if limit>=1 else 0\nfor i in range(1,limit+1):\n    if mu[i]!=0:\n        for j in range(2*i,limit+1,i):\n            mu[j]-=mu[i]\ncount=0\nfor d in range(1,limit+1):\n    count+=mu[d]*(n//(d*d))\nprint(count)', tip: '平方因子なしの個数は Σμ(d)·⌊n/d²⌋。メビウス関数で「平方因子を持つ数」を包除で除く。', ins: ['10\n', '1\n', '4\n', '100\n', '50\n', '2\n'] })

t({ lv: 861, concept: '数論: 相異なる素因数の個数', title: '相異なる素因数の個数ω(n)', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: 'n の相異なる素因数の個数 ω(n) を出力してください(n=1 は0)。', h1: '試し割りで素因数を見つける。', h2: '見つけるたびにその素因数で割り切る。', ref: 'n=int(input())\nm=n\ncnt=0\np=2\nwhile p*p<=m:\n    if m%p==0:\n        cnt+=1\n        while m%p==0:\n            m//=p\n    p+=1\nif m>1:\n    cnt+=1\nprint(cnt)', tip: 'ω(n)は相異なる素因数の数(乗法的でない加法的関数)。素因数分解しながら種類だけ数える。', ins: ['12\n', '1\n', '7\n', '30\n', '100\n', '60\n'] })

t({ lv: 862, concept: '数論: 重複込みの素因数の個数', title: '重複を込めた素因数の個数Ω(n)', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: 'n の素因数を重複込みで数えた個数 Ω(n) を出力してください(n=1 は0)。', h1: '試し割りで割れるたびに数える。', h2: '指数の総和になる。', ref: 'n=int(input())\nm=n\ncnt=0\np=2\nwhile p*p<=m:\n    while m%p==0:\n        m//=p\n        cnt+=1\n    p+=1\nif m>1:\n    cnt+=1\nprint(cnt)', tip: 'Ω(n)は重複込みの素因数の数(=素因数分解の指数の総和)。完全加法的関数。', ins: ['12\n', '1\n', '7\n', '8\n', '100\n', '60\n'] })

t({ lv: 863, concept: '数論: 約数関数の和', title: 'Σfloor(n/i)の値', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: 'Σ_{i=1}^{n} ⌊n/i⌋ (=1からnまでの約数の個数の総和)を出力してください。', h1: 'floor(n/i)が同じ値になる区間でまとめる。', h2: '区間ごとに値×個数を足す(調和分割)。', ref: 'n=int(input())\ntotal=0\ni=1\nwhile i<=n:\n    v=n//i\n    j=n//v\n    total+=v*(j-i+1)\n    i=j+1\nprint(total)', tip: '⌊n/i⌋ は O(√n) 種類しか値を取らない。同値区間でまとめると O(√n) で総和が求まる。', ins: ['5\n', '1\n', '10\n', '100\n', '2\n', '1000\n'] })

t({ lv: 864, concept: '数論: floor和', title: '一次式の床関数の和(floor sum)', tags: ['数論'], io: 'n a b m が空白区切りで与えられます(m>0)。', ask: 'Σ_{i=0}^{n-1} ⌊(a·i+b)/m⌋ を出力してください。', h1: 'ユークリッドの互除法のように a,b を m で割る。', h2: '格子点の数え替えで O(log) に落とす(floor_sum)。', ref: 'def floor_sum(n,m,a,b):\n    ans=0\n    if a<0:\n        a2=a%m\n        ans-=n*(n-1)//2*((a2-a)//m)\n        a=a2\n    if b<0:\n        b2=b%m\n        ans-=n*((b2-b)//m)\n        b=b2\n    while True:\n        if a>=m:\n            ans+=n*(n-1)//2*(a//m)\n            a%=m\n        if b>=m:\n            ans+=n*(b//m)\n            b%=m\n        ymax=a*n+b\n        if ymax<m:\n            break\n        n=ymax//m\n        b=ymax%m\n        m,a=a,m\n    return ans\nn,a,b,m=map(int,input().split())\nprint(floor_sum(n,m,a,b))', tip: 'floor sum は互除法的に (a,b,m) を縮約し O(log) で計算する。格子点の数え上げに帰着する強力なテク。', ins: ['4 1 0 2\n', '1 0 0 5\n', '5 2 3 4\n', '10 3 1 7\n', '3 0 0 1\n', '100 1 1 2\n'] })

t({ lv: 865, concept: '数論: 中国剰余定理(2式)', title: '2つの合同式の最小解', tags: ['数論'], io: 'r1 m1 r2 m2 が空白区切りで与えられます。', ask: 'x≡r1 (mod m1), x≡r2 (mod m2) を満たす最小の非負整数 x を出力してください。解が無ければ -1。', h1: '拡張ユークリッドで結合する。', h2: '解の周期は lcm(m1,m2)。', ref: 'import math\nr1,m1,r2,m2=map(int,input().split())\ndef extgcd(a,b):\n    if b==0:\n        return a,1,0\n    g,x,y=extgcd(b,a%b)\n    return g,y,x-(a//b)*y\ng,p,q=extgcd(m1,m2)\nif (r2-r1)%g!=0:\n    print(-1)\nelse:\n    lcm=m1//g*m2\n    tmp=(r2-r1)//g*p%(m2//g)\n    x=(r1+m1*tmp)%lcm\n    print(x%lcm)', tip: '中国剰余定理は拡張ユークリッドで2式を1式に結合する。解の存在条件は (r2-r1) が gcd で割れること。', ins: ['2 3 3 5\n', '0 2 0 3\n', '1 2 0 2\n', '1 4 3 6\n', '0 1 0 1\n', '2 3 2 7\n'] })

t({ lv: 866, concept: '数論: 拡張ユークリッド', title: '一次不定方程式の最小正の解', tags: ['数論'], io: 'a b が空白区切りで与えられます(正整数)。', ask: 'a·x + b·y = gcd(a,b) を満たす整数解のうち、x が最小の正(>0)になる解の x を出力してください。', h1: '拡張ユークリッドで1つの解を得る。', h2: 'x を mod (b/g) に正規化する。', ref: 'a,b=map(int,input().split())\ndef extgcd(a,b):\n    if b==0:\n        return a,1,0\n    g,x,y=extgcd(b,a%b)\n    return g,y,x-(a//b)*y\ng,x,y=extgcd(a,b)\nmod=b//g\nx%=mod\nif x<=0:\n    x+=mod\nprint(x)', tip: '拡張ユークリッドは ax+by=gcd の整数解を与える。解は x0 + k·(b/g) の形で周期 b/g。', ins: ['3 5\n', '4 6\n', '1 1\n', '7 11\n', '12 18\n', '5 3\n'] })

t({ lv: 867, concept: '数論: 一次合同式の解の数', title: 'ax≡b mod m の解の個数', tags: ['数論'], io: 'a b m が空白区切りで与えられます(m>0)。', ask: '0以上 m 未満で a·x≡b (mod m) を満たす x の個数を出力してください。', h1: 'g=gcd(a,m) を求める。', h2: 'b が g で割れれば解は g 個、割れなければ0個。', ref: 'import math\na,b,m=map(int,input().split())\ng=math.gcd(a%m if m else a,m)\nif b%g==0:\n    print(g)\nelse:\n    print(0)', tip: 'ax≡b (mod m) は g=gcd(a,m) が b を割れば解が g 個、割れなければ0個。', ins: ['2 4 6\n', '2 3 6\n', '3 0 9\n', '1 5 7\n', '4 2 8\n', '6 3 9\n'] })

t({ lv: 868, concept: '数論: モジュラ逆元(拡張ユークリッド)', title: '法mでの逆元', tags: ['数論'], io: 'a m が空白区切りで与えられます(gcd(a,m)=1 とは限らない)。', ask: 'a の法 m での逆元(0以上m未満)を出力してください。存在しなければ -1。', h1: '拡張ユークリッドで ax+my=1 を解く。', h2: 'gcd≠1なら逆元は存在しない。', ref: 'a,m=map(int,input().split())\ndef extgcd(a,b):\n    if b==0:\n        return a,1,0\n    g,x,y=extgcd(b,a%b)\n    return g,y,x-(a//b)*y\ng,x,y=extgcd(a%m,m)\nif g!=1:\n    print(-1)\nelse:\n    print(x%m)', tip: '逆元は ax≡1 (mod m) の解。拡張ユークリッドで gcd=1 のときだけ存在する。', ins: ['3 11\n', '2 4\n', '10 17\n', '1 5\n', '6 9\n', '7 13\n'] })

t({ lv: 869, concept: '数論: カタラン数 mod p', title: 'カタラン数を素数で割った余り', tags: ['数論'], io: '非負整数 n が1行で与えられます。', ask: 'n 番目のカタラン数を 1000000007 で割った余りを出力してください。', h1: 'C(2n,n)/(n+1) を mod で。', h2: '階乗と逆元(フェルマー)を使う。', ref: `n=int(input())\nMOD=${MOD}\nN=2*n+1\nfact=[1]*(N+1)\nfor i in range(1,N+1):\n    fact[i]=fact[i-1]*i%MOD\ninv_fact=[1]*(N+1)\ninv_fact[N]=pow(fact[N],MOD-2,MOD)\nfor i in range(N-1,-1,-1):\n    inv_fact[i]=inv_fact[i+1]*(i+1)%MOD\ndef comb(a,b):\n    if b<0 or b>a:\n        return 0\n    return fact[a]*inv_fact[b]%MOD*inv_fact[a-b]%MOD\nres=comb(2*n,n)*pow(n+1,MOD-2,MOD)%MOD\nprint(res)`, tip: 'カタラン数 mod p は C(2n,n)·(n+1)^{-1} を階乗とフェルマー逆元で。巨大nでも O(n)。', ins: ['5\n', '0\n', '1\n', '10\n', '100\n', '3\n'] })

t({ lv: 870, concept: '数論: 二項係数 mod p', title: '二項係数C(n,k) mod p', tags: ['数論'], io: 'n k が空白区切りで与えられます。', ask: 'C(n,k) を 1000000007 で割った余りを出力してください。', h1: '階乗とその逆元を前計算する。', h2: 'C(n,k)=n!·(k!)^{-1}·((n-k)!)^{-1}。', ref: `n,k=map(int,input().split())\nMOD=${MOD}\nif k<0 or k>n:\n    print(0)\nelse:\n    fact=[1]*(n+1)\n    for i in range(1,n+1):\n        fact[i]=fact[i-1]*i%MOD\n    inv_fact=[1]*(n+1)\n    inv_fact[n]=pow(fact[n],MOD-2,MOD)\n    for i in range(n-1,-1,-1):\n        inv_fact[i]=inv_fact[i+1]*(i+1)%MOD\n    print(fact[n]*inv_fact[k]%MOD*inv_fact[n-k]%MOD)`, tip: '二項係数 mod p は階乗とフェルマー逆元で O(n) 前計算→O(1) 取得。組合せ論の基本道具。', ins: ['5 2\n', '10 0\n', '10 10\n', '6 3\n', '100 50\n', '4 5\n'] })

t({ lv: 871, concept: '数論: 完全順列 mod p', title: '完全順列の数 mod p', tags: ['数論'], io: '非負整数 n が1行で与えられます。', ask: '完全順列(撹乱)の数 D(n) を 1000000007 で割った余りを出力してください。', h1: 'D(n)=(n-1)(D(n-1)+D(n-2))。', h2: 'mod を取りながら漸化。', ref: `n=int(input())\nMOD=${MOD}\nif n==0:\n    print(1)\nelif n==1:\n    print(0)\nelse:\n    a=1\n    b=0\n    for i in range(2,n+1):\n        c=(i-1)*((a+b)%MOD)%MOD\n        a=b\n        b=c\n    print(b)`, tip: '完全順列 mod p は漸化式 D(n)=(n-1)(D(n-1)+D(n-2)) を mod で回すだけ。大きい n でも O(n)。', ins: ['4\n', '0\n', '1\n', '5\n', '100\n', '10\n'] })

t({ lv: 872, concept: '数論: 第二種スターリング数 mod p', title: '第二種スターリング数 S(n,k) mod p', tags: ['数論', 'dp'], io: 'n k が空白区切りで与えられます。', ask: 'S(n,k) を 1000000007 で割った余りを出力してください。', h1: '包除原理の閉じた式を使う。', h2: 'S(n,k)=(1/k!)Σ(-1)^i C(k,i)(k-i)^n。', ref: `n,k=map(int,input().split())\nMOD=${MOD}\nif k==0:\n    print(1 if n==0 else 0)\nelse:\n    fact=[1]*(k+1)\n    for i in range(1,k+1):\n        fact[i]=fact[i-1]*i%MOD\n    inv_fact=[1]*(k+1)\n    inv_fact[k]=pow(fact[k],MOD-2,MOD)\n    for i in range(k-1,-1,-1):\n        inv_fact[i]=inv_fact[i+1]*(i+1)%MOD\n    def comb(a,b):\n        if b<0 or b>a:\n            return 0\n        return fact[a]*inv_fact[b]%MOD*inv_fact[a-b]%MOD\n    res=0\n    for i in range(k+1):\n        term=comb(k,i)*pow((k-i)%MOD,n,MOD)%MOD\n        if i%2==0:\n            res=(res+term)%MOD\n        else:\n            res=(res-term)%MOD\n    res=res*inv_fact[k]%MOD\n    print(res%MOD)`, tip: '第二種スターリング数の閉じた式 S(n,k)=(1/k!)Σ(-1)^i C(k,i)(k-i)^n を mod で計算する。', ins: ['5 2\n', '4 2\n', '3 3\n', '0 0\n', '6 3\n', '10 4\n'] })

t({ lv: 873, concept: '数論: 分割数 mod p', title: '整数の分割数 mod p', tags: ['数論', 'dp'], io: '非負整数 n が1行で与えられます。', ask: '分割数 p(n) を 1000000007 で割った余りを出力してください。', h1: '五角数定理を使う。', h2: 'p(n)=Σ(-1)^{k-1}(p(n-g_k)) で一般化五角数 g_k。', ref: `n=int(input())\nMOD=${MOD}\np=[0]*(n+1)\np[0]=1\nfor i in range(1,n+1):\n    total=0\n    k=1\n    while True:\n        g1=k*(3*k-1)//2\n        g2=k*(3*k+1)//2\n        if g1>i and g2>i:\n            break\n        sign=1 if k%2==1 else -1\n        if g1<=i:\n            total+=sign*p[i-g1]\n        if g2<=i:\n            total+=sign*p[i-g2]\n        k+=1\n    p[i]=total%MOD\nprint(p[n]%MOD)`, tip: '分割数は五角数定理で O(n√n)。一般化五角数 g_k=k(3k∓1)/2 の項を符号付きで足す。', ins: ['5\n', '0\n', '1\n', '10\n', '100\n', '50\n'] })

t({ lv: 874, concept: '数論: ベル数 mod p', title: 'ベル数 mod p', tags: ['数論', 'dp'], io: '非負整数 n が1行で与えられます。', ask: 'ベル数 B(n) を 1000000007 で割った余りを出力してください。', h1: 'ベル三角形を mod で作る。', h2: '各行を前行から構築する。', ref: `n=int(input())\nMOD=${MOD}\nrow=[1]\nfor i in range(1,n+1):\n    nxt=[row[-1]]\n    for j in range(i):\n        nxt.append((nxt[-1]+row[j])%MOD)\n    row=nxt\nprint(row[0]%MOD)`, tip: 'ベル数 mod p はベル三角形を mod で回す O(n²)。集合の分割数を表す。', ins: ['5\n', '0\n', '1\n', '10\n', '3\n', '20\n'] })

t({ lv: 875, concept: '数論: フィボナッチ(高速ダブリング)', title: 'フィボナッチ数 mod p(高速ダブリング)', tags: ['数論'], io: '非負整数 n が1行で与えられます。', ask: 'F(n) を 1000000007 で割った余りを出力してください(F0=0,F1=1)。', h1: 'F(2k)=F(k)(2F(k+1)-F(k))。', h2: 'F(2k+1)=F(k+1)²+F(k)²。', ref: `n=int(input())\nMOD=${MOD}\ndef fib(n):\n    if n==0:\n        return (0,1)\n    a,b=fib(n>>1)\n    c=a*((2*b-a)%MOD)%MOD\n    d=(a*a+b*b)%MOD\n    if n&1:\n        return (d,(c+d)%MOD)\n    else:\n        return (c,d)\nprint(fib(n)[0]%MOD)`, tip: '高速ダブリングはフィボナッチを O(log n) で。行列累乗より定数倍が軽い再帰公式。', ins: ['10\n', '0\n', '1\n', '50\n', '100\n', '1000\n'] })

t({ lv: 876, concept: '数論: gcdの総和', title: 'Σgcd(i,n)の値', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: 'Σ_{i=1}^{n} gcd(i,n) を出力してください。', h1: '各約数 d について gcd=d となる i の数は φ(n/d)。', h2: 'Σ_{d|n} d·φ(n/d)。', ref: 'n=int(input())\ndef phi(x):\n    res=x\n    m=x\n    p=2\n    while p*p<=m:\n        if m%p==0:\n            while m%p==0:\n                m//=p\n            res-=res//p\n        p+=1\n    if m>1:\n        res-=res//m\n    return res\ntotal=0\nd=1\nwhile d*d<=n:\n    if n%d==0:\n        total+=d*phi(n//d)\n        if d!=n//d:\n            total+=(n//d)*phi(d)\n    d+=1\nprint(total)', tip: 'Σgcd(i,n)=Σ_{d|n} d·φ(n/d)。約数ごとに「gcdがdになるiの数=φ(n/d)」を使う。', ins: ['6\n', '1\n', '12\n', '10\n', '100\n', '7\n'] })

t({ lv: 877, concept: '数論: 互いに素なペアの数', title: 'n以下の互いに素なペアの数', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: '1<=i<j<=n で gcd(i,j)=1 となるペアの個数を出力してください。', h1: 'メビウス関数で包除する。', h2: 'Σμ(d)·C(⌊n/d⌋,2)。', ref: 'n=int(input())\nmu=[0]*(n+1)\nif n>=1:\n    mu[1]=1\nfor i in range(1,n+1):\n    if mu[i]!=0:\n        for j in range(2*i,n+1,i):\n            mu[j]-=mu[i]\ntotal=0\nfor d in range(1,n+1):\n    c=n//d\n    total+=mu[d]*(c*(c-1)//2)\nprint(total)', tip: '互いに素なペア数はメビウス包除。Σμ(d)·C(⌊n/d⌋,2) で「公約数dを持つペア」を引いていく。', ins: ['3\n', '1\n', '5\n', '10\n', '2\n', '20\n'] })

t({ lv: 878, concept: '数論: メルテンス関数', title: 'メルテンス関数M(n)', tags: ['数論'], io: '正整数 n が1行で与えられます。', ask: 'M(n)=Σ_{i=1}^{n} μ(i) を出力してください。', h1: '篩でメビウス関数を求める。', h2: '累積和を取る。', ref: 'n=int(input())\nmu=[0]*(n+1)\nif n>=1:\n    mu[1]=1\nfor i in range(1,n+1):\n    if mu[i]!=0:\n        for j in range(2*i,n+1,i):\n            mu[j]-=mu[i]\nprint(sum(mu[1:n+1]))', tip: 'メルテンス関数 M(n)=Σμ(i) はメビウス関数の累積和。素数定理と深く関わる。', ins: ['5\n', '1\n', '10\n', '2\n', '100\n', '20\n'] })

t({ lv: 879, concept: '文字列: 回文部分文字列の総数', title: '回文である連続部分文字列の総数', tags: ['文字列'], io: '文字列 s が1行で与えられます。', ask: '回文になっている連続部分文字列の個数(位置で区別)を出力してください。', h1: 'Manacherで各中心の回文半径を求める。', h2: '各中心の半径から回文の個数を足す。', ref: 's=input()\nt="#"+"#".join(s)+"#"\nn=len(t)\np=[0]*n\nc=0\nr=0\nfor i in range(n):\n    if i<r:\n        p[i]=min(r-i,p[2*c-i])\n    while i-p[i]-1>=0 and i+p[i]+1<n and t[i-p[i]-1]==t[i+p[i]+1]:\n        p[i]+=1\n    if i+p[i]>r:\n        c=i\n        r=i+p[i]\ntotal=0\nfor v in p:\n    total+=(v+1)//2\nprint(total)', tip: 'Manacherで各中心の回文半径から回文部分文字列の総数を O(n) で数える(最長を求めるlv453と別計算)。', ins: ['aaa\n', 'abc\n', 'abba\n', 'a\n', 'aba\n', 'aabaa\n'] })

t({ lv: 880, concept: '文字列: 相異なる回文部分文字列の数', title: '相異なる回文部分文字列の数', tags: ['文字列'], io: '文字列 s が1行で与えられます。', ask: '相異なる回文部分文字列(連続)の種類数を出力してください。', h1: 'すべての回文部分文字列を集合に入れる。', h2: '集合のサイズを数える(高度には回文木)。', ref: 's=input()\nn=len(s)\npals=set()\nfor i in range(n):\n    l=i\n    r=i\n    while l>=0 and r<n and s[l]==s[r]:\n        pals.add(s[l:r+1])\n        l-=1\n        r+=1\n    l=i\n    r=i+1\n    while l>=0 and r<n and s[l]==s[r]:\n        pals.add(s[l:r+1])\n        l-=1\n        r+=1\nprint(len(pals))', tip: '相異なる回文の数は中心拡張＋集合で全列挙できる。大規模には回文木(eertree)で O(n)。', ins: ['aaa\n', 'abc\n', 'abba\n', 'a\n', 'aabaa\n', 'banana\n'] })

t({ lv: 881, concept: '文字列: Lyndon分解の個数', title: 'Lyndon分解の要素数', tags: ['文字列'], io: '文字列 s が1行で与えられます。', ask: 's を辞書順非増加なLyndon語の列に一意分解(Duval法)したときの要素数を出力してください。', h1: 'Duvalのアルゴリズムで貪欲に分解する。', h2: 'i,j,k のポインタで次のLyndon語を確定。', ref: 's=input()\nn=len(s)\ncount=0\ni=0\nwhile i<n:\n    j=i+1\n    k=i\n    while j<n and s[k]<=s[j]:\n        if s[k]<s[j]:\n            k=i\n        else:\n            k+=1\n        j+=1\n    while i<=k:\n        count+=1\n        i+=j-k\nprint(count)', tip: 'Lyndon分解(Chen-Fox-Lyndon)はDuval法で O(n)。最小回転や最小表現の計算にも使える。', ins: ['banana\n', 'abc\n', 'aaa\n', 'cba\n', 'ababab\n', 'a\n'] })

t({ lv: 882, concept: '文字列: Z配列の総和', title: 'Z配列の値の総和', tags: ['文字列'], io: '文字列 s が1行で与えられます。', ask: 's の Z 配列(各位置から始まる接頭辞との最長一致長)の総和を出力してください(z[0]は0扱い)。', h1: 'Zボックスを保持して線形に計算。', h2: '区間内なら既知の値を再利用する。', ref: 's=input()\nn=len(s)\nz=[0]*n\nl=0\nr=0\nfor i in range(1,n):\n    if i<r:\n        z[i]=min(r-i,z[i-l])\n    while i+z[i]<n and s[z[i]]==s[i+z[i]]:\n        z[i]+=1\n    if i+z[i]>r:\n        l=i\n        r=i+z[i]\nprint(sum(z))', tip: 'Z配列は各位置から始まる接頭辞一致長を O(n) で。総和は反復構造の指標になる。', ins: ['aaaa\n', 'abc\n', 'ababab\n', 'a\n', 'aabaa\n', 'abcabc\n'] })

t({ lv: 883, concept: '文字列: 接頭辞関数の総和', title: '接頭辞関数(KMP)の総和', tags: ['文字列'], io: '文字列 s が1行で与えられます。', ask: 's の接頭辞関数(各位置の最長の真の境界長)の総和を出力してください。', h1: '前の値から境界を辿る。', h2: '一致したら+1、しなければ縮める。', ref: 's=input()\nn=len(s)\npi=[0]*n\nfor i in range(1,n):\n    j=pi[i-1]\n    while j>0 and s[i]!=s[j]:\n        j=pi[j-1]\n    if s[i]==s[j]:\n        j+=1\n    pi[i]=j\nprint(sum(pi))', tip: '接頭辞関数(KMP失敗関数)は各接尾辞が接頭辞と一致する最長長。総和は周期性の度合いを表す。', ins: ['aaaa\n', 'abc\n', 'abcabc\n', 'a\n', 'aabaaab\n', 'ababab\n'] })

t({ lv: 884, concept: '文字列: 長さkの相異なる部分文字列数', title: '長さkの相異なる連続部分文字列の数', tags: ['文字列'], io: '1行目に文字列 s、2行目に長さ k が与えられます。', ask: '長さ k の相異なる連続部分文字列の種類数を出力してください。', h1: '長さkの窓を集合に入れる。', h2: '集合のサイズ(ローリングハッシュで高速化可)。', ref: 's=input()\nk=int(input())\nn=len(s)\nif k>n or k<=0:\n    print(0)\nelse:\n    subs=set()\n    for i in range(n-k+1):\n        subs.add(s[i:i+k])\n    print(len(subs))', tip: '長さ固定の相異なる部分文字列はローリングハッシュや接尾辞配列で高速化できる(ここは集合で全列挙)。', ins: ['banana\n2\n', 'aaaa\n2\n', 'abc\n1\n', 'abcabc\n3\n', 'a\n1\n', 'abab\n2\n'] })

t({ lv: 885, concept: '文字列: 最小回転の開始位置', title: '辞書順最小の回転の開始位置(Booth)', tags: ['文字列'], io: '文字列 s が1行で与えられます。', ask: '辞書順で最小になる巡回シフトの開始位置(0始まり、複数あれば最小の位置)を出力してください。', h1: 'Boothのアルゴリズムで最小開始を求める。', h2: '失敗関数を回しながら候補を更新。', ref: 's=input()\nn=len(s)\nif n==0:\n    print(0)\nelse:\n    ss=s+s\n    f=[-1]*(2*n)\n    k=0\n    for j in range(1,2*n):\n        sj=ss[j]\n        i=f[j-k-1]\n        while i!=-1 and sj!=ss[k+i+1]:\n            if sj<ss[k+i+1]:\n                k=j-i-1\n            i=f[i]\n        if sj!=ss[k+i+1]:\n            if sj<ss[k]:\n                k=j\n            f[j-k]=-1\n        else:\n            f[j-k]=i+1\n    print(k)', tip: 'Boothのアルゴリズムは最小回転の開始位置を O(n) で求める。最小表現(canonical form)の計算に使う。', ins: ['bca\n', 'cba\n', 'aaa\n', 'dcba\n', 'abab\n', 'b\n'] })

t({ lv: 886, concept: '文字列: 連続ブロックの数', title: '同一文字の連続ブロック数', tags: ['文字列'], io: '文字列 s が1行で与えられます。', ask: '同じ文字が連続するブロック(極大ラン)の個数を出力してください。', h1: '直前の文字と比較する。', h2: '異なるたびにブロックを増やす。', ref: 's=input()\nif not s:\n    print(0)\nelse:\n    cnt=1\n    for i in range(1,len(s)):\n        if s[i]!=s[i-1]:\n            cnt+=1\n    print(cnt)', tip: '連続ブロック数(ラン数)は隣接が変わる回数+1。ランレングス符号化の基礎。', ins: ['aaabbbcc\n', 'abc\n', 'aaaa\n', 'a\n', 'ababab\n', 'aabbaa\n'] })

t({ lv: 887, concept: 'グラフ: ハンガリアン法の割当最小コスト', title: 'ハンガリアン法による割当問題', tags: ['グラフ'], io: '1行目に n、続く n 行に n×n のコスト行列が与えられます。', ask: '各行を異なる列にちょうど1つ割り当てる最小総コストを出力してください。', h1: '行・列のポテンシャルを更新する。', h2: 'O(n³) のハンガリアン法(Kuhn-Munkres)。', ref: 'import sys\nn=int(input())\na=[list(map(int,input().split())) for _ in range(n)]\nINF=float("inf")\nu=[0]*(n+1)\nv=[0]*(n+1)\npp=[0]*(n+1)\nway=[0]*(n+1)\nfor i in range(1,n+1):\n    pp[0]=i\n    j0=0\n    minv=[INF]*(n+1)\n    used=[False]*(n+1)\n    while True:\n        used[j0]=True\n        i0=pp[j0]\n        delta=INF\n        j1=-1\n        for j in range(1,n+1):\n            if not used[j]:\n                cur=a[i0-1][j-1]-u[i0]-v[j]\n                if cur<minv[j]:\n                    minv[j]=cur\n                    way[j]=j0\n                if minv[j]<delta:\n                    delta=minv[j]\n                    j1=j\n        for j in range(n+1):\n            if used[j]:\n                u[pp[j]]+=delta\n                v[j]-=delta\n            else:\n                minv[j]-=delta\n        j0=j1\n        if pp[j0]==0:\n            break\n    while j0:\n        j1=way[j0]\n        pp[j0]=pp[j1]\n        j0=j1\nres=0\nfor j in range(1,n+1):\n    res+=a[pp[j]-1][j-1]\nprint(res)', tip: 'ハンガリアン法(Kuhn-Munkres)は割当問題を O(n³) で。ポテンシャルを更新して増加道を見つける。', ins: ['2\n1 2\n3 4\n', '1\n5\n', '3\n9 2 7\n6 4 3\n5 8 1\n', '2\n5 5\n5 5\n', '3\n1 1 1\n1 1 1\n1 1 1\n', '3\n7 5 11\n5 4 1\n9 3 2\n'] })

t({ lv: 888, concept: 'フロー: 最小費用流', title: '最小費用最大流の費用', tags: ['グラフ', 'フロー'], io: '1行目に n m s t f(流したい流量)、続く m 行に有向辺 u v cap cost が与えられます。', ask: 's から t へ f だけ流すときの最小総費用を出力してください。流せなければ -1。', h1: 'ベルマンフォードで最小費用の増加道を探す。', h2: '残余グラフに逆辺(費用-cost)を張る。', ref: 'first=input().split()\nn=int(first[0])\nm=int(first[1])\ns=int(first[2])\nt=int(first[3])\nf=int(first[4])\ngraph=[[] for _ in range(n+1)]\ndef add_edge(u,v,cap,cost):\n    graph[u].append([v,cap,cost,len(graph[v])])\n    graph[v].append([u,0,-cost,len(graph[u])-1])\nfor _ in range(m):\n    u,v,cap,cost=map(int,input().split())\n    add_edge(u,v,cap,cost)\nINF=float("inf")\nres=0\nflow=0\nwhile flow<f:\n    dist=[INF]*(n+1)\n    dist[s]=0\n    inqueue=[False]*(n+1)\n    prevv=[-1]*(n+1)\n    preve=[-1]*(n+1)\n    from collections import deque\n    dq=deque([s])\n    inqueue[s]=True\n    while dq:\n        x=dq.popleft()\n        inqueue[x]=False\n        for ei,e in enumerate(graph[x]):\n            to,cap,cost,rev=e\n            if cap>0 and dist[x]+cost<dist[to]:\n                dist[to]=dist[x]+cost\n                prevv[to]=x\n                preve[to]=ei\n                if not inqueue[to]:\n                    dq.append(to)\n                    inqueue[to]=True\n    if dist[t]==INF:\n        break\n    d=f-flow\n    v=t\n    while v!=s:\n        d=min(d,graph[prevv[v]][preve[v]][1])\n        v=prevv[v]\n    v=t\n    while v!=s:\n        graph[prevv[v]][preve[v]][1]-=d\n        rev=graph[prevv[v]][preve[v]][3]\n        graph[v][rev][1]+=d\n        v=prevv[v]\n    flow+=d\n    res+=d*dist[t]\nprint(res if flow==f else -1)', tip: '最小費用流は「最小費用の増加道」を繰り返し流す。逆辺の費用を負にして残余グラフで最短路を求める。', ins: ['4 5 1 4 2\n1 2 2 1\n1 3 1 2\n2 4 1 1\n2 3 1 1\n3 4 2 1\n', '2 1 1 2 1\n1 2 5 3\n', '2 1 1 2 2\n1 2 1 3\n', '1 0 1 1 0\n', '3 2 1 3 1\n1 2 1 5\n2 3 1 5\n', '4 4 1 4 1\n1 2 1 1\n2 4 1 1\n1 3 1 10\n3 4 1 10\n'] })

t({ lv: 889, concept: 'グラフ: DAGの最小パス被覆', title: 'DAGの最小パス被覆数', tags: ['グラフ'], io: '1行目に n m、続く m 行に有向辺 u v が与えられます(DAG)。', ask: 'すべての頂点をちょうど1回ずつ通るように、頂点素なパスでDAGを覆う最小のパス数を出力してください。', h1: '二部マッチングに帰着する。', h2: '答え = n - 最大マッチング。', ref: 'first=input().split()\nn=int(first[0])\nm=int(first[1])\ng=[[] for _ in range(n+1)]\nfor _ in range(m):\n    u,v=map(int,input().split())\n    g[u].append(v)\nmatchR=[0]*(n+1)\ndef try_kuhn(u,used):\n    for v in g[u]:\n        if not used[v]:\n            used[v]=True\n            if matchR[v]==0 or try_kuhn(matchR[v],used):\n                matchR[v]=u\n                return True\n    return False\nmatching=0\nfor u in range(1,n+1):\n    used=[False]*(n+1)\n    if try_kuhn(u,used):\n        matching+=1\nprint(n-matching)', tip: 'DAGの最小パス被覆は二部マッチングに帰着。答え = 頂点数 - 最大マッチング(König型の定理)。', ins: ['3 2\n1 2\n2 3\n', '3 0\n', '4 2\n1 2\n3 4\n', '1 0\n', '4 3\n1 2\n1 3\n1 4\n', '5 4\n1 2\n2 3\n3 4\n4 5\n'] })

t({ lv: 890, concept: '木: パスの最大値クエリ(LCA分解)', title: '木のパス上の最大辺重み', tags: ['グラフ', '木'], io: '1行目に n、続く n-1 行に重み付き辺 u v w、次の行に q、続く q 行に a b が与えられます。', ask: '各クエリ a-b 間のパス上の最大辺重みを求め、その総和を出力してください。', h1: 'ダブリングで親と区間最大を前計算。', h2: 'LCAまで登りながら最大を取る。', ref: 'from collections import deque\nn=int(input())\ng=[[] for _ in range(n+1)]\nfor _ in range(n-1):\n    u,v,w=map(int,input().split())\n    g[u].append((v,w))\n    g[v].append((u,w))\nLOG=1\nwhile (1<<LOG)<n:\n    LOG+=1\nLOG+=1\nup=[[0]*(n+1) for _ in range(LOG)]\nmx=[[0]*(n+1) for _ in range(LOG)]\ndepth=[0]*(n+1)\nseen=[False]*(n+1)\nseen[1]=True\nup[0][1]=1\ndq=deque([1])\nwhile dq:\n    x=dq.popleft()\n    for y,w in g[x]:\n        if not seen[y]:\n            seen[y]=True\n            up[0][y]=x\n            mx[0][y]=w\n            depth[y]=depth[x]+1\n            dq.append(y)\nfor k in range(1,LOG):\n    for v in range(1,n+1):\n        up[k][v]=up[k-1][up[k-1][v]]\n        mx[k][v]=max(mx[k-1][v],mx[k-1][up[k-1][v]])\ndef query(a,b):\n    res=0\n    if depth[a]<depth[b]:\n        a,b=b,a\n    d=depth[a]-depth[b]\n    for k in range(LOG):\n        if (d>>k)&1:\n            res=max(res,mx[k][a])\n            a=up[k][a]\n    if a==b:\n        return res\n    for k in range(LOG-1,-1,-1):\n        if up[k][a]!=up[k][b]:\n            res=max(res,mx[k][a],mx[k][b])\n            a=up[k][a]\n            b=up[k][b]\n    res=max(res,mx[0][a],mx[0][b])\n    return res\nq=int(input())\ntotal=0\nfor _ in range(q):\n    a,b=map(int,input().split())\n    total+=query(a,b)\nprint(total)', tip: 'パスの最大辺はダブリングで「2^k 先の親」と「その区間の最大辺」を同時に持つと O(log n)/クエリ。', ins: ['3\n1 2 5\n2 3 7\n2\n1 3\n1 2\n', '2\n1 2 10\n1\n1 2\n', '4\n1 2 1\n2 3 2\n3 4 3\n1\n1 4\n', '5\n1 2 4\n1 3 2\n3 4 6\n3 5 1\n2\n2 4\n4 5\n', '1\n0\n', '3\n1 2 100\n1 3 1\n1\n2 3\n'] })

t({ lv: 891, concept: '木: 距離kの頂点対の数(重心分解)', title: '距離がちょうどkの頂点対の数', tags: ['グラフ', '木'], io: '1行目に n k、続く n-1 行に無向辺 u v が与えられます。', ask: '木の中で距離(辺数)がちょうど k の頂点対の個数を出力してください。', h1: '各頂点からの距離分布を数える(小規模はBFS)。', h2: '大規模は重心分解で O(n log²n)。', ref: 'from collections import deque\nfirst=input().split()\nn=int(first[0])\nk=int(first[1])\ng=[[] for _ in range(n+1)]\nfor _ in range(n-1):\n    u,v=map(int,input().split())\n    g[u].append(v)\n    g[v].append(u)\ntotal=0\nfor s in range(1,n+1):\n    dist=[-1]*(n+1)\n    dist[s]=0\n    dq=deque([s])\n    while dq:\n        x=dq.popleft()\n        for y in g[x]:\n            if dist[y]==-1:\n                dist[y]=dist[x]+1\n                dq.append(y)\n    for v in range(s+1,n+1):\n        if dist[v]==k:\n            total+=1\nprint(total)', tip: '距離kの頂点対は素朴には全点BFSで O(n²)。大規模では重心分解(centroid decomposition)で高速化する。', ins: ['5 2\n1 2\n1 3\n2 4\n2 5\n', '3 1\n1 2\n2 3\n', '1 0\n', '4 3\n1 2\n2 3\n3 4\n', '5 1\n1 2\n1 3\n1 4\n1 5\n', '7 2\n1 2\n1 3\n2 4\n2 5\n3 6\n3 7\n'] })

t({ lv: 892, concept: 'DP: Convex Hull Trickの最小値', title: '直線群の最小値の総和(CHT)', tags: ['dp', '数学'], io: '1行目に直線の数 m とクエリ数 q、続く m 行に直線 a b(y=a·x+b)、続く q 行に x が与えられます。', ask: '各クエリ x で全直線の最小値を求め、その総和を出力してください。', h1: '下側凸包を構成する(傾き降順)。', h2: 'クエリxで二分探索/単調に評価する。', ref: 'first=input().split()\nm=int(first[0])\nq=int(first[1])\nlines=[tuple(map(int,input().split())) for _ in range(m)]\nqueries=[int(input()) for _ in range(q)]\ntotal=0\nfor x in queries:\n    best=None\n    for a,b in lines:\n        val=a*x+b\n        if best is None or val<best:\n            best=val\n    total+=best\nprint(total)', tip: 'Convex Hull Trickは直線群の最小/最大を凸包で管理し O(log) 評価する。ここは素朴に全直線を評価。', ins: ['2 2\n1 0\n-1 4\n1\n3\n', '1 1\n2 3\n5\n', '3 1\n1 0\n2 -1\n-1 5\n2\n', '2 1\n0 5\n0 3\n10\n', '2 2\n1 1\n-1 1\n0\n2\n', '1 1\n-3 10\n4\n'] })

t({ lv: 893, concept: '数論: 区間篩の素数個数', title: '区間[L,R]の素数の個数', tags: ['数論'], io: 'L R が空白区切りで与えられます(L<=R)。', ask: 'L 以上 R 以下の素数の個数を出力してください。', h1: '√R までの素数を通常の篩で求める。', h2: 'それらで区間[L,R]だけを篩い落とす(区間篩)。', ref: 'import math\nL,R=map(int,input().split())\nif R<2:\n    print(0)\nelse:\n    L=max(L,2)\n    limit=int(math.isqrt(R))+1\n    sieve=[True]*(limit+1)\n    primes=[]\n    for i in range(2,limit+1):\n        if sieve[i]:\n            primes.append(i)\n            for j in range(i*i,limit+1,i):\n                sieve[j]=False\n    seg=[True]*(R-L+1)\n    for p in primes:\n        start=max(p*p,((L+p-1)//p)*p)\n        for j in range(start,R+1,p):\n            seg[j-L]=False\n    print(sum(1 for i in range(R-L+1) if seg[i]))', tip: '区間篩は√Rまでの素数だけで [L,R] を篩う。Rが巨大でも区間が狭ければ素数を列挙できる。', ins: ['10 30\n', '1 10\n', '2 2\n', '1 1\n', '90 100\n', '1 100\n'] })

t({ lv: 894, concept: '線形代数: 行列のランク mod p', title: 'mod素数での行列の階数', tags: ['数論'], io: '1行目に r c p、続く r 行に c 個の整数が与えられます(p は素数)。', ask: 'GF(p) 上での行列の階数を出力してください。', h1: 'mod p のガウス消去を行う。', h2: 'ピボットの逆元で前進消去する。', ref: 'first=input().split()\nr=int(first[0])\nc=int(first[1])\np=int(first[2])\nmat=[[int(x)%p for x in input().split()] for _ in range(r)]\nrank=0\nfor col in range(c):\n    pivot=-1\n    for i in range(rank,r):\n        if mat[i][col]%p!=0:\n            pivot=i\n            break\n    if pivot==-1:\n        continue\n    mat[rank],mat[pivot]=mat[pivot],mat[rank]\n    inv=pow(mat[rank][col],p-2,p)\n    for j in range(c):\n        mat[rank][j]=mat[rank][j]*inv%p\n    for i in range(r):\n        if i!=rank and mat[i][col]%p!=0:\n            factor=mat[i][col]\n            for j in range(c):\n                mat[i][j]=(mat[i][j]-factor*mat[rank][j])%p\n    rank+=1\nprint(rank)', tip: 'mod素数のランクはフェルマー逆元を使ったガウス消去で。GF(2)版(lv491)の一般素数版。', ins: ['2 2 1000000007\n1 2\n2 4\n', '2 2 7\n1 0\n0 1\n', '3 3 5\n1 2 3\n4 5 6\n7 8 9\n', '1 1 3\n0\n', '2 3 11\n1 1 1\n2 2 2\n', '3 3 1000000007\n1 0 0\n0 1 0\n0 0 1\n'] })

t({ lv: 895, concept: '線形代数: 連立一次方程式 mod p', title: 'mod素数での連立方程式の解の数', tags: ['数論'], io: '1行目に n p(n元、p素数)、続く n 行に拡大係数行列(各行 n+1 個)が与えられます。', ask: '解の個数を出力してください(一意なら1、無数なら p^自由度を p で…ここでは自由度をdとして "INF" でなく自由変数の数、解なしなら -1)。', h1: 'mod p のガウス消去で階段化する。', h2: '矛盾行があれば-1、無ければ自由変数の数を出力。', ref: 'first=input().split()\nn=int(first[0])\np=int(first[1])\nmat=[[int(x)%p for x in input().split()] for _ in range(n)]\nrank=0\nfor col in range(n):\n    pivot=-1\n    for i in range(rank,n):\n        if mat[i][col]%p!=0:\n            pivot=i\n            break\n    if pivot==-1:\n        continue\n    mat[rank],mat[pivot]=mat[pivot],mat[rank]\n    inv=pow(mat[rank][col],p-2,p)\n    for j in range(n+1):\n        mat[rank][j]=mat[rank][j]*inv%p\n    for i in range(n):\n        if i!=rank and mat[i][col]%p!=0:\n            f=mat[i][col]\n            for j in range(n+1):\n                mat[i][j]=(mat[i][j]-f*mat[rank][j])%p\n    rank+=1\nno_sol=False\nfor i in range(rank,n):\n    if mat[i][n]%p!=0:\n        no_sol=True\nif no_sol:\n    print(-1)\nelse:\n    print(n-rank)', tip: 'mod素数の連立方程式はガウス消去で階段化。矛盾行で解なし、自由変数の数 n-rank が解空間の次元。', ins: ['2 7\n1 0 3\n0 1 5\n', '2 5\n1 1 2\n2 2 4\n', '2 3\n1 1 0\n1 1 1\n', '1 5\n0 3\n', '3 1000000007\n1 0 0 1\n0 1 0 2\n0 0 1 3\n', '2 7\n1 1 1\n1 1 1\n'] })

t({ lv: 896, concept: '数論: 累乗の塔 mod m', title: 'べき乗の塔 a^a^...^a mod m', tags: ['数論'], io: 'a k m が空白区切りで与えられます(a を k 回重ねた累乗塔)。', ask: 'a↑↑k(高さ k の累乗塔) を m で割った余りを出力してください。', h1: '拡張オイラー定理で指数を φ で畳む。', h2: '再帰的に mod φ(m) を取る。', ref: 'import sys\nsys.setrecursionlimit(10000)\nimport math\ndef phi(x):\n    res=x\n    m=x\n    pp=2\n    while pp*pp<=m:\n        if m%pp==0:\n            while m%pp==0:\n                m//=pp\n            res-=res//pp\n        pp+=1\n    if m>1:\n        res-=res//m\n    return res\ndef tower(a,k,m):\n    if m==1:\n        return 0\n    if k==0:\n        return 1%m\n    if k==1:\n        return a%m\n    ph=phi(m)\n    e=tower(a,k-1,ph)\n    return pow(a,e+ph,m)\na,k,m=map(int,input().split())\nprint(tower(a,k,m))', tip: '累乗の塔は拡張オイラー定理で指数を mod φ(m)+φ(m) に畳む再帰で計算する。', ins: ['2 3 1000\n', '3 2 7\n', '2 1 5\n', '2 4 100\n', '5 0 3\n', '7 3 13\n'] })

t({ lv: 897, concept: '数え上げ: 相異なる部分への分割数', title: '相異なる正整数への分割数', tags: ['dp'], io: '非負整数 n が1行で与えられます。', ask: 'n を相異なる正整数の和で表す方法(順不同)の数を出力してください。', h1: '各部品を高々1回使う0/1ナップサック。', h2: 'dp[x]+=dp[x-k] を後ろから。', ref: 'n=int(input())\ndp=[0]*(n+1)\ndp[0]=1\nfor k in range(1,n+1):\n    for x in range(n,k-1,-1):\n        dp[x]+=dp[x-k]\nprint(dp[n])', tip: '相異なる部分への分割数は「各部品を1回まで」の0/1ナップサック。オイラーの定理で奇数部分への分割数に等しい。', ins: ['5\n', '0\n', '1\n', '10\n', '6\n', '20\n'] })

t({ lv: 898, concept: '数え上げ: 最大部分がk以下の分割数', title: '最大の部分がk以下の分割数', tags: ['dp'], io: 'n k が空白区切りで与えられます。', ask: 'n を「各部分が k 以下の正整数」の和で表す方法(順不同)の数を出力してください。', h1: '部品を 1..k に限定した無制限ナップサック。', h2: 'dp[x]+=dp[x-i] を前から(i=1..k)。', ref: 'n,k=map(int,input().split())\ndp=[0]*(n+1)\ndp[0]=1\nfor i in range(1,k+1):\n    for x in range(i,n+1):\n        dp[x]+=dp[x-i]\nprint(dp[n])', tip: '最大部分がk以下の分割数は部品を1..kに限った無制限ナップサック。共役を取ると「部分がk個以下」の分割数に等しい。', ins: ['5 3\n', '5 5\n', '0 3\n', '10 2\n', '7 1\n', '6 4\n'] })

t({ lv: 899, concept: '数論: べき乗和(ファウルハーバー)', title: '1^k+2^k+...+n^k mod p', tags: ['数論'], io: 'n k が空白区切りで与えられます。', ask: 'Σ_{i=1}^{n} i^k を 1000000007 で割った余りを出力してください。', h1: 'k+2 個の点を取りラグランジュ補間する。', h2: '前計算した階乗逆元で O(k) 補間。', ref: `n,k=map(int,input().split())\nMOD=${MOD}\nif n==0:\n    print(0)\nelse:\n    deg=k+1\n    xs=list(range(deg+1))\n    ys=[0]*(deg+1)\n    s=0\n    for i in range(deg+1):\n        s=(s+pow(i,k,MOD))%MOD\n        ys[i]=s\n    if n<=deg:\n        print(ys[n]%MOD)\n    else:\n        pre=[1]*(deg+2)\n        for i in range(deg+1):\n            pre[i+1]=pre[i]*((n-i)%MOD)%MOD\n        suf=[1]*(deg+2)\n        for i in range(deg,-1,-1):\n            suf[i]=suf[i+1]*((n-i)%MOD)%MOD\n        fact=[1]*(deg+1)\n        for i in range(1,deg+1):\n            fact[i]=fact[i-1]*i%MOD\n        inv_fact=[1]*(deg+1)\n        inv_fact[deg]=pow(fact[deg],MOD-2,MOD)\n        for i in range(deg-1,-1,-1):\n            inv_fact[i]=inv_fact[i+1]*(i+1)%MOD\n        res=0\n        for i in range(deg+1):\n            num=pre[i]*suf[i+1]%MOD\n            den=inv_fact[i]*inv_fact[deg-i]%MOD\n            term=ys[i]*num%MOD*den%MOD\n            if (deg-i)%2==1:\n                term=MOD-term\n            res=(res+term)%MOD\n        print(res%MOD)`, tip: 'べき乗和 Σi^k は次数 k+1 の多項式。k+2 点からラグランジュ補間で任意の n の値を O(k) で求める。', ins: ['10 1\n', '5 2\n', '1 5\n', '3 0\n', '100 3\n', '0 2\n'] })

export const CATALOG = TASKS
